### ISSUE TITLE
Error upgrading to 0.62.1

### ISSUE THREAD

**Issue by joshuaspence** [RocketChat/Rocket.Chat#10038]
I am trying to upgrade from 0.61.2 to 0.62.1, but am seeing the following error when the service starts:

```
Mar 07 05:36:23 ip-10-52-1-183 node[32379]: Exception in callback of async function: Error: EISDIR: illegal operation on a directory, read
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at Object.fs.readSync (fs.js:675:18)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at tryReadSync (fs.js:540:20)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at Object.fs.readFileSync (fs.js:583:19)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at fetch (/opt/rocketchat/programs/server/npm/node_modules/@google-cloud/vision/node_modules/protobufjs/src/root.js:160:34)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at GoogleProtoFilesRoot.load (/opt/rocketchat/programs/server/npm/node_modules/@google-cloud/vision/node_modules/protobufjs/src/root.js:194:13)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at GoogleProtoFilesRoot.loadSync (/opt/rocketchat/programs/server/npm/node_modules/@google-cloud/vision/node_modules/protobufjs/src/root.js:235:17)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at Object.loadSync (/opt/rocketchat/programs/server/npm/node_modules/@google-cloud/vision/node_modules/protobufjs/src/index-light.js:69:17)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at GrpcClient.loadProto (/opt/rocketchat/programs/server/npm/node_modules/@google-cloud/vision/node_modules/google-gax/lib/grpc.js:156:14)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at module.exports.apiVersion (/opt/rocketchat/programs/server/npm/node_modules/@google-cloud/vision/src/helpers.js:252:6)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at Object.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/@google-cloud/vision/src/index.js:53:30)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at Module._compile (module.js:643:30)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at Object.Module._extensions..js (module.js:654:10)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at Module.load (module.js:556:32)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at tryModuleLoad (module.js:499:12)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at Function.Module._load (module.js:491:3)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at Module.require (module.js:587:17)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at require (internal/module.js:11:18)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at npmRequire (/opt/rocketchat/programs/server/npm-require.js:133:10)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at Module.useNode (packages/modules-runtime.js:697:18)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at fileEvaluate (packages/modules-runtime.js:342:20)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at require (packages/modules-runtime.js:238:16)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at new GoogleVision (packages/rocketchat:google-vision/server/googlevision.js:4:17)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at googlevision.js (packages/rocketchat:google-vision/server/googlevision.js:153:27)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at fileEvaluate (packages/modules-runtime.js:343:9)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at require (packages/modules-runtime.js:238:16)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at /opt/rocketchat/programs/server/packages/rocketchat_google-vision.js:390:1
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at /opt/rocketchat/programs/server/packages/rocketchat_google-vision.js:396:3
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at /opt/rocketchat/programs/server/boot.js:411:36
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at Array.forEach (<anonymous>)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at /opt/rocketchat/programs/server/boot.js:220:19
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at /opt/rocketchat/programs/server/boot.js:471:5
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at Function.run (/opt/rocketchat/programs/server/profile.js:510:12)
Mar 07 05:36:23 ip-10-52-1-183 node[32379]:     at /opt/rocketchat/programs/server/boot.js:470:11
```

* Version of Rocket.Chat Server: 0.61.2
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): TAR
* Number of Running Instances: 3
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.4
* mongoDB Version: 3.4.13

**Comment by geekgonecrazy** [comment]
Are you attempting to start all nodes at once? Or how are these being started?

**Comment by joshuaspence** [comment]
Originally I did, yes. But then I stopped two nodes and attempted to start only one of them, but I got the same error.

**Comment by joshuaspence** [comment]
I wiped the database (this is in our staging environment) and attempted to upgrade from 0.61.2 to 0.62.1 again, this time ensuring that I was only running on a single host. However, I got the exact same error.

**Comment by geekgonecrazy** [comment]
Check your home directory and delete the file: `.npmrc` and then delete the node_modules folder on rocket.chat.

And then run `npm install` again like before

**Comment by geekgonecrazy** [comment]
Something to do with the npmrc file having another path in it that's incorrect.

I read about a case of that happening a while back, very safe to try so figured we might as well try.

Glad you got it! I'll go ahead and close since resolved
