### ISSUE TITLE
Can't connect to Mongo after Upgrade

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#10112]
### Description:

A production instance running 0.61 was upgraded to 0.62.2. After the Upgrade the Server was/is unable to connect to Mongodb. A downgrade to 0.61 is possible and RC connects to MongoDB again.

Error as follows:

`BIND_IP=127.0.0.1 ROOT_URL=http://ares.xxx.net PORT=3000 MONGO_URL=mongodb://localhost:27017/rocketchat MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=001-rs /usr/local/nodejs/bin/node main.js

/opt/rocket.chat/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoError: failed to connect to server [ares.xxx:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.1.1:27017]
    at Pool.<anonymous> (/opt/rocket.chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/opt/rocket.chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/opt/rocket.chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

MongoDB shows:

`2018-03-13T00:25:16.152+0100 I NETWORK  [thread1] connection accepted from 127.0.0.1:44354 #16017 (1 connection now open)
2018-03-13T00:25:16.166+0100 I NETWORK  [conn16017] received client metadata from 127.0.0.1:44354 conn16017: { driver: { name: "nodejs", version: "2.2.34" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "3.10.0" }, platform: "Node.js v8.9.4, LE, mongodb-core: 2.1.18" }
2018-03-13T00:25:16.195+0100 I NETWORK  [thread1] connection accepted from 127.0.0.1:44362 #16018 (2 connections now open)
2018-03-13T00:25:16.196+0100 I NETWORK  [conn16018] received client metadata from 127.0.0.1:44362 conn16018: { driver: { name: "nodejs", version: "2.2.34" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "3.10.0" }, platform: "Node.js v8.9.4, LE, mongodb-core: 2.1.18" }
2018-03-13T00:25:16.202+0100 I -        [conn16018] end connection 127.0.0.1:44362 (2 connections now open)
2018-03-13T00:25:16.233+0100 I -        [conn16017] end connection 127.0.0.1:44354 (1 connection now open)
2018-03-13T00:25:31.421+0100 I NETWORK  [thread1] connection accepted from 127.0.0.1:44664 #16019 (1 connection now open)
2018-03-13T00:25:31.453+0100 I -        [conn16019] end connection 127.0.0.1:44664 (1 connection now open)
2018-03-13T00:26:31.410+0100 I NETWORK  [thread1] connection accepted from 127.0.0.1:45610 #16020 (1 connection now open)
2018-03-13T00:26:31.422+0100 I -        [conn16020] end connection 127.0.0.1:45610 (1 connection now open)
2018-03-13T00:27:31.850+0100 I NETWORK  [thread1] connection accepted from 127.0.0.1:46538 #16021 (1 connection now open)
2018-03-13T00:27:31.869+0100 I -        [conn16021] end connection 127.0.0.1:46538 (1 connection now open)
2018-03-13T00:28:31.550+0100 I NETWORK  [thread1] connection accepted from 127.0.0.1:47668 #16022 (1 connection now open)
2018-03-13T00:28:31.559+0100 I -        [conn16022] end connection 127.0.0.1:47668 (1 connection now open)
2018-03-13T00:29:31.353+0100 I NETWORK  [thread1] connection accepted from 127.0.0.1:48526 #16023 (1 connection now open)
2018-03-13T00:29:31.376+0100 I -        [conn16023] end connection 127.0.0.1:48526 (1 connection now open)
2018-03-13T00:30:31.802+0100 I NETWORK  [thread1] connection accepted from 127.0.0.1:49544 #16024 (1 connection now open)
2018-03-13T00:30:31.814+0100 I -        [conn16024] end connection 127.0.0.1:49544 (1 connection now open)`

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): Binary Tarball
* Number of Running Instances:  1
* DB Replicaset Oplog: Yes
* Node Version: Node.js v8.9.4
* mongoDB Version: 

### Steps to Reproduce:

1. 
2. 
3. 

### Expected behavior:

I would connect to the MongoDB as like every update.

### Actual behavior:

It does not connect to MongoDB, no changes to MongoDB nor NodeJS. After RC Downgrade everything works again.

**Comment by christianreiss** [comment]
I fixed _this_ error by removed the MONGO_OPLOG_URL environment.
