### ISSUE TITLE
Rocket chat doesn't send notification after the recent upgrade to 0.62.2

### ISSUE THREAD

**Issue by jankogaga** [RocketChat/Rocket.Chat#10173]
Rocket chat doesn't send notification after the recent upgrade to 0.62.2
The noticed error is:

[34mI20180319-16:34:07.756(1) Exception in defer callback: Error: Greeting never received at SMTPConnection._formatError (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19) at SMTPConnection._onError (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:531:20) at Timeout._greetingTimeout.setTimeout (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:472:22) at ontimeout (timers.js:482:11) at tryOnTimeout (timers.js:317:5) at Timer.listOnTimeout (timers.js:277:5)

I found within Rocket chat issues https://github.com/RocketChat/Rocket.Chat/pull/6680 that the meteor email version should be downgraded to 1.1.18, but not sure how to check and proceed further.

Thanks,
Dragan

**Comment by jankogaga** [comment]
SMTP port was changed, so I assume somehow an update set it to some default value.
