### ISSUE TITLE
Image Upload with Resizing causes Filesystem overflow

### ISSUE THREAD

**Issue by comander192** [RocketChat/Rocket.Chat#10195]
### Description:

When we upload an image that needs to be resized the upload hangs at 0% in the UI and our filesystem fills itself to 100% because of a broken file descriptor it seems. The issue was persistent when GraphicsMagick was used and we hoped it would be fixed when switching to the sharp module but it is still happening. We are using StorageType FileSystem for the uploads and Avatar resizing is activated.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: RHEL 7.4 3.10.0-693.21.1.el7.x86_64
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 8.9.3
* mongoDB Version: 2.6.12-1
* StorageType: FileSystem

### Steps to Reproduce:

1. Start image upload that needs to be resized by the server, extension/file type doesn't matter - same problem with avatar upload

### Expected behavior:

Image is uploaded, resized and shown in UI

### Actual behavior:

Filesystem overflow

### Relevant logs:
Before:
`[root@]# df -h
Filesystem             Size  Used Avail Use% Mounted on
...
/dev/mapper/varvg-var   25G   13G   13G  51% /var
`
After:
`[root@]# df -h
/dev/mapper/varvg-var   25G   25G   20K 100% /var
`
`-rw-r--r--. 1 rocket rocket   14G Mar 22 11:24 SvMjaZ22auSP3LR69`
`[root@]# lsof | grep deleted | grep node
node      24371         rocket   22r      REG              253,0          0  153379983 /var/rc_fileupload/h5zNhs2sbaRxYYN6H (deleted)
node      24371         rocket   25r      REG              253,0          0  153379983 /var/rc_fileupload/h5zNhs2sbaRxYYN6H (deleted)
`
rocketchat.log
`Mar 22 11:53:16  Rocket.Chat: rocketchat_logger rocketchat_logger.js:278 #033[34mMeteor ➔ method#033[39m setAvatarFromService -> userId: JRKfyCx3EE6YJrgXL , arguments:  { '0': 'data:image/jpeg;base64,/<data>==',
Mar 22 11:53:16  Rocket.Chat: '1': 'image/jpeg',
Mar 22 11:53:16  Rocket.Chat: '2': 'upload' }
Mar 22 11:53:16  Rocket.Chat: rocketchat_logger rocketchat_logger.js:278 #033[34mMeteor ➔ method#033[39m ufsComplete -> userId: JRKfyCx3EE6YJrgXL , arguments:  { '0': 'wPaiBDCdxcMj7HQAY',
Mar 22 11:53:16  Rocket.Chat: '1': 'FileSystem:Avatars',
Mar 22 11:53:16  Rocket.Chat: '2': '8Bbb79AA6b' }
...
Mar 22 11:54:41  Rocket.Chat: Error: FileNotFound: no file with id wPaiBDCdxcMj7HQAY found
Mar 22 11:54:41  Rocket.Chat: at /opt/rocket.chat-0.62.2/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:190:25
Mar 22 11:54:41  Rocket.Chat: at /opt/rocket.chat-0.62.2/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1215:18
Mar 22 11:54:41  Rocket.Chat: at handleCallback (/opt/rocket.chat-0.62.2/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:120:56)
Mar 22 11:54:41  Rocket.Chat: at /opt/rocket.chat-0.62.2/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1252:5
Mar 22 11:54:41  Rocket.Chat: at /opt/rocket.chat-0.62.2/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
Mar 22 11:54:41  Rocket.Chat: at _combinedTickCallback (internal/process/next_tick.js:131:7)
Mar 22 11:54:41  Rocket.Chat: at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Mar 22 11:54:41  Rocket.Chat: ufs: cannot delete temp file at /tmp/ufs/wPaiBDCdxcMj7HQAY (ENOENT: no such file or directory, unlink '/tmp/ufs/wPaiBDCdxcMj7HQAY')
Mar 22 11:54:41  rsyslogd: fopen() failed: 'No space left on device', path: '/var/lib/rsyslog/imjournal.state.tmp'  [v8.24.0 try http://www.rsyslog.com/e/2013 ]
Mar 22 11:54:41  Rocket.Chat: ufs: cannot write file "wPaiBDCdxcMj7HQAY" (ENOSPC: no space left on device, write) { Error: ENOSPC: no space left on device, write
Mar 22 11:54:41  Rocket.Chat: errno: -28, code: 'ENOSPC', syscall: 'write' }
Mar 22 11:54:41  Rocket.Chat: ufs: cannot delete temp file "/tmp/ufs/wPaiBDCdxcMj7HQAY" (ENOENT: no such file or directory, unlink '/tmp/ufs/wPaiBDCdxcMj7HQAY')
`

Browser Logs:
Browser just gets a timeout here.

**Comment by comander192** [comment]
EDIT: There was a Rocketchat Version which always set the Fileupload Path to default /tmp/ufs and it didnt matter what we set this path to. Our workaround was then to create a system in the filesystem /tmp/ufs -> /var/rc_fileupload which worked fine. This seems to brake the newer Rocketchat Uploads.

Scenario that breaks the upload and fills the filesystem:
Fileupload Storage Type: Filesystem
Filesystem Path: /tmp/ufs (this is linked in the filesystem to /var/rc_fileupload)
Avatar Resize: False
Set Default Avatar: False

I will add this to the initial comment.

**Comment by GoetheG** [comment]
This gets me thinking that there should be a cooperation betweek Rocket.Chat and Nextcloud regarding all the data. This would create anreal collabkrative solution with open sourse software.
