### ISSUE TITLE
CustomFields: Internal Server Error when changing user profile settings

### ISSUE THREAD

**Issue by cadetmsv** [RocketChat/Rocket.Chat#10232]
### Description:

When saving any changes to my profile (e.g. CustomFields.Phones) Rocket Chat displays an "Internal server error". But can save any changes. Some of the users on my server are affected but not all of them only old. New users do not have this error.
We installed Rocket.Chat ubuntu-snap 0.61. Then upgraded to 0.62.1 and 0.62.2. Were set up CustomFields. Old users created before the upgraded 0.62.1, new after. Old users in mongodb have added fields CustomFields (Phones, Mobiles).

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Ubuntu Server
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: unkown
* Node Version: v8.8.1
* mongoDB Version: 3.2.7

### Steps to Reproduce:

1. Open the old user profile settings
2. Change the custom fields "Phones" or "Mobiles"

### Expected behavior:

I expect that I can save the changes without any problems and error messages

### Actual behavior:

Output of the error message in the logs and in the profile settings

### Relevant logs:

```
[34mI20180329-17:30:13.197(3) Exception while invoking method 'saveUserProfile' MongoError: cannot use the part 
(customFields of customFields.Phones) to traverse the element ({customFields: null})     
at Function.MongoError.create (/snap/rocketchat-server/1232/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)     
at toError (/snap/rocketchat-server/1232/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)     
at /snap/rocketchat-server/1232/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67     
at /snap/rocketchat-server/1232/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18     
at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9) 
```

User record in the database Mongo:

```
{
    "_id": "k76sCSPbhr63ePmH7",
    "createdAt": ISODate("2018-02-26T08:00:43.384Z"),
    "services": {
        "password": {
            "bcrypt": "$2a$10$ta.6vjzz1dCT8.1qR6OGwODRhm8aOeM41ojBZN0mjhzH1UJMk2aHG"
        },
        "email": {
            "verificationTokens": []
        },
        "resume": {
            "loginTokens": [
                {
                    "when": ISODate("2018-03-28T12:21:05.462Z"),
                    "hashedToken": "tL8hkWhKZX0DbSNke2wXfnSkneFUxuTBOTu2mN/M+Tk="
                },
                {
                    "when": ISODate("2018-03-29T14:29:57.925Z"),
                    "hashedToken": "ItPgpxWOCr1sIRCJCts0qN6ctfqHpuWJ1MQKaQ0B2Bo="
                }
            ]
        }
    },
    "emails": [
        {
            "address": "test@mail.com",
            "verified": true
        }
    ],
    "type": "user",
    "status": "online",
    "active": true,
    "name": "TEST",
    "_updatedAt": ISODate("2018-03-29T14:30:13.163Z"),
    "roles": [
        "user"
    ],
    "customFields": {
        "Phones": "123456789",
        "Mobiles": "12345678"
    },
    "username": "test",
    "requirePasswordChange": false,
    "lastLogin": ISODate("2018-03-29T14:29:57.918Z"),
    "statusConnection": "online",
    "utcOffset": 3,
    "settings": {
        "profile": {}
    },
    "avatarOrigin": "upload"
}
```

**Comment by cadetmsv** [comment]
Fix. After you delete all records from the "Null" in the "CustomFields" field of the "parties.rocketchat_subscribtion" table. There was no error.

**Comment by DRON4eg** [comment]
how did you do this? I have installed snap 66.3
