### ISSUE TITLE
Have installed in ubuntu 16.04 LTS, but when open localhost:3000 is not loading

### ISSUE THREAD

**Issue by javeedrahman** [RocketChat/Rocket.Chat#10251]
Hi,
When I start node main.js as per the documents, I got the following output in the terminal, When I open the browser and type http://localhost:3000 it is not loading.

I am using Ubuntu 16.04 LTS,
Node: v8.10.0
Mongodb: 3.4

I don't know what i am doing wrong, please help

Will load cache for users
1 records load from users
Will load cache for rocketchat_room
1 records load from rocketchat_room
Will load cache for rocketchat_subscription
0 records load from rocketchat_subscription
Will load cache for rocketchat_settings
628 records load from rocketchat_settings
Updating process.env.MAIL_URL
Will load cache for rocketchat_permissions
75 records load from rocketchat_permissions
Will load cache for rocketchat_roles
11 records load from rocketchat_roles
Starting Email Intercepter...
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead npm/node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read npm/node_modules/connect/lib/middleware/multipart.js:86:15
{"line":"152","file":"rocketchat_migrations.js","message":"Migrations: Not migrating, already at version 107","time":{"$date":1522248611079},"level":"info"}
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
Updating process.env.MAIL_URL
Exception in callback of async function: Error: Invalid PORT specified
    at Object.exports.main.argv (/home/javi/Rocket.Chat/programs/server/packages/webapp.js:963:15)
    at /home/javi/Rocket.Chat/programs/server/boot.js:459:27
    at /home/javi/Rocket.Chat/programs/server/boot.js:473:5
    at Function.run (/home/javi/Rocket.Chat/programs/server/profile.js:510:12)
    at /home/javi/Rocket.Chat/programs/server/boot.js:470:11

➔ System ➔ startup
➔ +----------------------------------------------+
➔ |                SERVER RUNNING                |
➔ +----------------------------------------------+
➔ |                                              |
➔ |  Rocket.Chat Version: 0.62.2                 |
➔ |       NodeJS Version: 8.10.0 - x64           |
➔ |             Platform: linux                  |
➔ |         Process Port: undefined              |
➔ |             Site URL: http://localhost:3000  |
➔ |     ReplicaSet OpLog: Enabled                |
➔ |          Commit Hash: 07f0e3f77c             |
➔ |        Commit Branch: HEAD                   |
➔ |                                              |
➔ +----------------------------------------------+

**Comment by kaiiiiiiiii** [comment]
Hi @javeedrahman,

please have a look at the following page to get support:
https://rocket.chat/docs/getting-support/

The GitHub issue board is mainly used for bugs and feature requests. Your issue looks more like a support case to me :)

Cheers,
Kai
