### ISSUE TITLE
Cannot add a user to a private channel; user cannot join channel even when made public

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat#10312]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Linux 4.13.0-37-generic
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.8.1
* mongoDB Version: 

### Steps to Reproduce:

1. Attempt to add user to private channel
or
1. User attempts to join channel once made public; same result

### Expected behavior:

User to be added.

### Actual behavior:

Red notification in top right of screen, no message.

When user tries to join, they get an internal server error and something about preview mode.

### Relevant logs:

`[34mI20180403-17:25:57.552(0) Exception while invoking method 'addUsersToRoom' TypeError: Cannot read property 'joinRoom' of undefined     at IrcRoomJoiner (/snap/rocketchat-server/1238/programs/server/packages/rocketchat_irc.js:609:13)     at /snap/rocketchat-server/1238/programs/server/packages/rocketchat_lib.js:1162:30     at Array.reduce (<anonymous>:null:null)     at Object.RocketChat.callbacks.run (/snap/rocketchat-server/1238/programs/server/packages/rocketchat_lib.js:1155:8)     at EventEmitter.RocketChat.addUserToRoom (/snap/rocketchat-server/1238/programs/server/packages/rocketchat_lib.js:4143:26)     at data.users.forEach.username (/snap/rocketchat-server/1238/programs/server/packages/rocketchat_lib.js:14200:18)     at Array.forEach (<anonymous>:null:null)     at MethodInvocation.addUsersToRoom (/snap/rocketchat-server/1238/programs/server/packages/rocketchat_lib.js:14191:16)     at MethodInvocation.methodsMap.(anonymous function) (/snap/rocketchat-server/1238/programs/server/packages/rocketchat_lib.js:2158:28)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/snap/rocketchat-server/1238/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/snap/rocketchat-server/1238/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)     at DDPServer._CurrentWriteFence.withValue (/snap/rocketchat-server/1238/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)     at Promise (/snap/rocketchat-server/1238/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/snap/rocketchat-server/1238/programs/server/packages/ddp-server.js:875:23)     at /snap/rocketchat-server/1238/programs/server/packages/ddp-server.js:754:85  `

**Comment by HammyHavoc** [comment]
Turns out it just needed a restart after tinkering with IRC a few days ago.
