### ISSUE TITLE
Error when I go to change username or other settings.

### ISSUE THREAD

**Issue by thunderchild91** [RocketChat/Rocket.Chat#10377]
### Server Setup Information:

* Version of Rocket.Chat Server:  0.63.0
* Operating System:  Cenntos 7
* Deployment Method(snap/docker/tar/etc): tar download / install
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 8,9.3
* mongoDB Version: 3,4,14

### Steps to Reproduce:
Go into admin panel and change username, of said user and it won't change all the time and says internal server error but sometimes the persons name still changes or setting but reverts back slowly. Also sometimes.

### Expected behavior:
I would expect the username / name or profile picture of said user to change without error.

### Actual behavior:
Sometimes changes for a short while and gives internal server error then sometime later reverts back.

### Relevant logs:
20180407-08:34:54.499(0) Exception while invoking method 'insertOrUpdateUser' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: mentions.$.username     at Function.MongoError.create (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)     at toError (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)  
[34mI20180407-08:38:07.868(0) Exception while invoking method 'insertOrUpdateUser' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: mentions.$.username     at Function.MongoError.create (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)     at toError (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)  

Btw I am also able to use a older version of rocket chat without any errors I can go back to version 59.3 and everything works fine but when I update to anything newer users cannot get their info changed by themselves or admins. I would like to be able to use the newer version and not be stuck with 59.3.

**Comment by martinvonwittich** [comment]
Can confirm:

Version of Rocket.Chat Server: 0.63.2
Operating System: Debian stretch
Deployment Method(snap/docker/tar/etc): tar
Number of Running Instances: 1
DB Replicaset Oplog: Disabled
Node Version: v8.9.3
mongoDB Version: mongodb-org 3.2.17

The user then attempted to change his own name (from "first.lastname" to "firstname.lastname"), and now his account seems to be damaged:

- On top of the chat window it still says "@first.lastname".
- Below the chat window it still says "first.lastname is writing..."
- The profile is completely empty. It just says "User info" and nothing else, while for other users it shows avatar, display name, user name, online/offline, block user button, email address, created at, last login and timezone.
- The @ tab completion shows him twice, as first.lastname (online) and firstname.lastname (offline).
- In the chat, his name is displayed as "Firstname Lastname @firstname.lastname", so for some reason at this point it uses the new username, while at almost all other points it seems to use the old username.

I guess this is the reason why it's not a good idea to use document stores like MongoDB for relational data :(

**Comment by simopaasisalo** [comment]
I am also seeing this bug with the username change resetting over time, but there are no server errors accompanying it and the user profile seems intact. 
On version 0.63.0

We've tried changing the username both from the admin view and the user's own profile settings. It changes for a while, but then resets after some time to the original. Seems to be related to the user logging in or already being logged in, since when the user is logged out the username does not seem to reset by itself.

**Comment by luckenbach** [comment]
After upgrading to Version 0.66 this is no longer an issue on my side.

**Comment by Patrick-Remy** [comment]
Unfortunately, I have still the same exception in 0.66.

**Comment by Patrick-Remy** [comment]
Version 0.66.3 fixed it for me! But all profile pictures are lost.
