### ISSUE TITLE
LDAP Authenication: LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed on the connection.

### ISSUE THREAD

**Issue by iconist** [RocketChat/Rocket.Chat#10493]
I have configured LDAP Authentication to Rocket Chat.But when I try to login , message popup as "user not found or incorrect password" even with correct password.
AM I missing anything??

### Description:
Sync User Avatar is set to false
on/admin/LDAP, TEST CONNECTION giving success
Base DN is give in the format : dc=abcd,dc=com

### Server Setup Information:

* Version of Rocket.Chat Server:  0.62.2  
* Operating System: linux
* Node Version: 8.9.4 - x64 

### Steps to Reproduce:

1. Connection.info LDAP connected
2. giving search error : LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed on the connection.

### Expected behavior:

Login with LDAP Credentials

### Actual behavior:

user not found or incorrect password popup with correct credentials

### Relevant logs:
 `rocketchat_logger rocketchat_logger.js:278 [34mLDAPHandler ➔ info Init LDAP login myid@abc.com 

rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Connection.info Init setup 

rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Connection.info Connecting ldap://myldaserver:389

rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Connection.debug connectionOptions { url: 'ldap://myldaserver:389',   timeout: 60000,   connectTimeout: 1000,   idleTimeout: 1000,   reconnect: false,   log:     Logger {      domain: null,      _events: {},      _eventsCount: 0,      _maxListeners: undefined,      _level: 30,      streams: [ [Object] ],      serializers: null,      src: false,      fields:        { name: 'ldapjs',         component: 'client',         hostname: 'myhostname',         pid: 102863 } } }  

rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Connection.info LDAP connected 

rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.info Searching user myid@abc.com

rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.debug searchOptions { filter: '(&(objectclass=*)(sAMAccountName=myid@abc.com))',   scope: 'sub',   sizeLimit: 1000,   paged: { pageSize: 250, pagePause: false } } 

 rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.debug BaseDN dc=abcd,dc=com  

 rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Search.error { OperationsError: 000004DC: LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580     at messageCallback (/home/rootuser/Rocket/Rocket.Chat/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/home/rootuser/Rocket/Rocket.Chat/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/home/rootuser/Rocket/Rocket.Chat/node_modules/ldapjs/lib/messages/parser.js:111:8)     at Socket.onData (/home/rootuser/Rocket/Rocket.Chat/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:594:20)    lde_message: '000004DC: LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580\u0000',   lde_dn: null }

**Comment by adipose** [comment]
Is that the correct sAMAccountName?  I think in openLDAP you can use uid as the default id checker.

If you browse the ldap and find the user, what does it show for sAMAccountName / uid?

**Comment by iconist** [comment]
I am using an organization LDAP and I am not authorized to install any of LDAP software to browse through LDAP records, Is there any way to find sAMAccountName via command line linux?

**Comment by bbrauns** [comment]
have a look at: https://wiki.debian.org/LDAP/LDAPUtils or http://directory.apache.org/studio/downloads.html

**Comment by iconist** [comment]
hi @adipose we have correct sAMAccountName only.but still the issue.

**Comment by bbrauns** [comment]
@iconist please install the correct ldap cmdline tools for your distribution and check locally on your rocket.chat server that you can successfully query/bind a user. Examples: https://www.digitalocean.com/community/tutorials/how-to-manage-and-use-ldap-servers-with-openldap-utilities#using-ldapsearch-to-query-the-dit-and-lookup-entries

**Comment by zimmertr** [comment]
Hello, I'm experiencing this LDAP issue for an unrelated matter. What solution did you end up finding?  How do you "Bind" to a domain before joining? 

>Couldn't lookup domain short name: 000004DC: LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580

**Comment by mydoghasworms** [comment]
@iconist Did you manage to resolve the issue? It seems I may have logged a duplicate with issue #11100. I get the same message in the log. From my understanding, pointing to the LDAP server should be all to configure LDAP authentication. Someone else on my issue confirmed they did not have to configure a service user. I get the same message in the log as you.
