### ISSUE TITLE
[0.64.0-rc1] email verification link leads to mongodb error

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#10548]
### Description:

When a  new user hits the email verification link he gets after registering a server error 500 is shown. Additionally in the rocketchat error log i see:

`
Exception while invoking method 'verifyEmail' MongoError: The positional operator did not find the match needed from the query. Unexpa
nded update: emails.$.verified
    at Function.MongoError.create (/opt/rocketchat-0.64.0-rc1/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-c
ore/lib/error.js:31:11)
    at toError (/opt/rocketchat-0.64.0-rc1/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)
    at /opt/rocketchat-0.64.0-rc1/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67
    at /opt/rocketchat-0.64.0-rc1/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:4
69:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
`

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.0-rc1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: no
* Node Version: 8.9.4
* mongoDB Version: 3.6.3

### Steps to Reproduce:

1. Settings: Email Verification: true
2. Settings: Manually Approve New Users: true
3. New User registers
4. New User gets email with verification link
5. User klicks on that link

### Expected behavior:

Email gets verified.

### Actual behavior:

Server Error

### Relevant logs:

`
Meteor ➔ publish null -> userId: null , arguments:  {}
Exception while invoking method 'verifyEmail' MongoError: The positional operator did not find the match needed from the query. Unexpa
nded update: emails.$.verified
    at Function.MongoError.create (/opt/rocketchat-0.64.0-rc1/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-c
ore/lib/error.js:31:11)
    at toError (/opt/rocketchat-0.64.0-rc1/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)
    at /opt/rocketchat-0.64.0-rc1/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67
    at /opt/rocketchat-0.64.0-rc1/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:4
69:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

Meteor ➔ publish stream-notify-user -> userId: null , arguments:  { '0': 'null/subscriptions-changed',
`

thanks and cheers

**Comment by axis78** [comment]
+1
Right the same problem.

Version of Rocket.Chat Server: 0.62.1
Operating System: Centos 7 Linux
Deployment Method(snap/docker/tar/etc): tar
Number of Running Instances: 1
Node Version: 8.9.3
mongoDB Version: 3.6.4

**Comment by Hudell** [comment]
Duplicate of #10149

**Comment by tarator** [comment]
Still getting the same error on version 0.65.1 (fresh docker installation. Installed today.)

    rocket_1        | Exception while invoking method 'verifyEmail' MongoError: The positional operator did not find the match needed from the query.
    rocket_1        |     at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    rocket_1        |     at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)
    rocket_1        |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67
    rocket_1        |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    rocket_1        |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
    rocket_1        |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

Issue should be reopened in my opinion. Please let me know if you need any further information.
