### ISSUE TITLE
[0.64.0-rc.2] Expected Array in field attachments

### ISSUE THREAD

**Issue by ph1p** [RocketChat/Rocket.Chat#10568]
### Description:

No integration seems to work.
For example, I got an error by using the giphy integration. (https://github.com/FinndropStudios/GifRocket)
Additional: No one can create a message, when alias is empty in user settings.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.0-rc.2
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc):  docker
* Number of Running Instances: 1
* DB Replicaset Oplog: deactivated
* Node Version: v8.9.3
* mongoDB Version: latest

### Steps to Reproduce:

1. Add giphy integration
2. Type in /gif WORD
3. Open logs

### Expected behavior:

Rocket.Chat creates a message with a giphy url.

### Actual behavior:

Nothing happened.

### Relevant logs:

`Exception in callback of async function: Error: Match error: Match error: Expected Array in field attachments 
at check (/app/bundle/programs/server/packages/check.js:68:17)
at EventEmitter.RocketChat.sendMessage (/app/bundle/programs/server/packages/rocketchat_lib.js:5320:3) at processWebhookMessage (/app/bundle/programs/server/packages/rocketchat_integrations.js:2715:38) 
at RocketChatIntegrationHandler.sendMessage (/app/bundle/programs/server/packages/rocketchat_integrations.js:603:15) 
at HTTP.call (/app/bundle/programs/server/packages/rocketchat_integrations.js:1193:38) 
at runWithEnvironment (packages/meteor.js:1238:24)`

**Comment by graywolf336** [comment]
@ph1p can you go to the integration's history and show a screenshot of the result that errors out?
