### ISSUE TITLE
Rocket Chat Rest Api Login error (Server error.) 

### ISSUE THREAD

**Issue by hannes-angst** [RocketChat/Rocket.Chat#10581]
Issue https://github.com/RocketChat/Rocket.Chat/issues/10199 got closed too soon.

The sytem is the same. Only the Rocket.Chat version is now 0.63.3

**Comment by hannes-angst** [comment]
I do not get a direct match to the code. 
Best match is `./packages/rocketchat-api/server/api.js`...?

```
$ git checkout tags/0.63.3
$ find . | grep api.js
./packages/rocketchat-graphql/server/mocks/accounts/graphql-api.js
./packages/rocketchat-graphql/server/api.js
./packages/rocketchat-livechat/server/api.js
./packages/rocketchat-videobridge/client/public/external_api.js
./packages/rocketchat-api/server/api.js
./packages/rocketchat-integrations/server/api/api.js
```

My guess is that `this.logger` is not defined when called as `this.logger.debug(...)`.

**Comment by pettitto** [comment]
Haven't had a chance to look at this, but one of my users is having this very same issue.

**Comment by guardian-liferay** [comment]
I have installed my new rocket chat and i still got the same problem
May I know how to fix this?
Here is my logs snapshot.
`assist4-rocketchat | ➔ +-----------------------------------------------------------------+
assist4-rocketchat | ➔ | SERVER RUNNING |
assist4-rocketchat | ➔ +-----------------------------------------------------------------+
assist4-rocketchat | ➔ | |
assist4-rocketchat | ➔ | Rocket.Chat Version: 0.64.1 |
assist4-rocketchat | ➔ | NodeJS Version: 8.9.3 - x64 |
assist4-rocketchat | ➔ | Platform: linux |
assist4-rocketchat | ➔ | Process Port: 3000 |
assist4-rocketchat | ➔ | Site URL: https://dev04.ccoc.applabs.nec.com.au/im |
assist4-rocketchat | ➔ | ReplicaSet OpLog: Disabled |
assist4-rocketchat | ➔ | Commit Hash: 54738c011b |
assist4-rocketchat | ➔ | Commit Branch: HEAD |
assist4-rocketchat | ➔ | |
assist4-rocketchat | ➔ +-----------------------------------------------------------------+
assist4-rocketchat | TypeError: Cannot read property 'debug' of undefined
assist4-rocketchat | at Object._internalRouteActionHandler [as action] (/app/bundle/programs/server/packages/rocketchat_api.js:181:25)
assist4-rocketchat | at Route.share.Route.Route._callEndpoint (/app/bundle/programs/server/packages/nimble_restivus.js:347:32)
assist4-rocketchat | at /app/bundle/programs/server/packages/nimble_restivus.js:236:33
assist4-rocketchat | at packages/simple_json-routes.js:98:9
assist4-rocketchat |
assist4-rocketchat | TypeError: Cannot read property 'debug' of undefined
assist4-rocketchat | at Object._internalRouteActionHandler [as action] (/app/bundle/programs/server/packages/rocketchat_api.js:181:25)
assist4-rocketchat | at Route.share.Route.Route._callEndpoint (/app/bundle/programs/server/packages/nimble_restivus.js:347:32)
assist4-rocketchat | at /app/bundle/programs/server/packages/nimble_restivus.js:236:33
assist4-rocketchat | at packages/simple_json-routes.js:98:9`

**Comment by haffla** [comment]
I can only cofirm this! When trying to login via REST API => `Server error.` Same log entries like @hannes-angst
