### ISSUE TITLE
LDAP (re)synchronisation adding new users to channels and avatars missing

### ISSUE THREAD

**Issue by CoMPaTech** [RocketChat/Rocket.Chat#10602]
### Description:

When pressing the LDAP (manual) sync button existing (as in, already joined) users don't have their avatar updated while users that never logged in to our rocket.chat server are joining the default channels.

Reason/cause:
Some users are missing their (jpegPhoto) LDAP avatar synced, even when asking them to logout/login again. 
Effect:
Trying to synchronize manually (with 'add new users' set to off) doesn't update the avatars of existing users but does have every user that didn't join in, join the default channels.

No harm done, since this happened before on a different occasion we did backup before hitting the sync button and restored the parties DB ... But would definitely like the manual button to NOT add new users to the channels + do the intended work (sync avatars).

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.4 - x64
* mongoDB Version: 3.2.7

### Steps to Reproduce:

1. Admin->LDAP->Sync / Import
2. Press Background Sync Now
3. All users determined by "User Search (Group Validation)" set group to be allowed joining are joined to the default channel

Settings in LDAP:
- Username field: uid
- Merge existing: True
- Sync User data: True
- Sync User Avatar: True
- Background sync: True (interval 2 hours)
- Background Sync import new users: False
- Background Sync Update existing: True

Partially referring to #8728 but on our system they don't sync - even overnight. Also recurring in our logs is #6535 for which i spotted is a workaround.

### Expected behavior:

Sync existing users - especially avatars

### Actual behavior:

Avatars not synced (minor)
All users not yet ever logged in or joined default channels were joined into default channels

### Relevant logs:

Logs show the below for about 23 users (not pasted all of those)
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]: rocketchat_logger rocketchat_logger.js:278 LDAPSync _ error Error creating user { Error: Username already exists. [403]
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:     at AccountsServer.Ap.insertUserDoc (/snap/rocketchat-server/1254/programs/server/packages/accounts-base.js:1766:52)
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:     at AccountsServer.<anonymous> (/snap/rocketchat-server/1254/programs/server/app/app.js:570:29)
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:     at executeBound (/snap/rocketchat-server/1254/programs/server/npm/node_modules/underscore/underscore.js:701:67)
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:     at AccountsServer.bound [as insertUserDoc] (/snap/rocketchat-server/1254/programs/server/npm/node_modules/underscore/underscore.js:733:14)
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:     at createUser (/snap/rocketchat-server/1254/programs/server/packages/accounts-password.js:1242:25)
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:     at AccountsServer.Accounts.createUser (/snap/rocketchat-server/1254/programs/server/packages/accounts-password.js:1302:10)
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:     at addLdapUser (/snap/rocketchat-server/1254/programs/server/packages/rocketchat_ldap.js:1273:31)
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:     at ldapUsers.forEach.ldapUser (/snap/rocketchat-server/1254/programs/server/packages/rocketchat_ldap.js:1335:9)
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:     at Array.forEach (<anonymous>:null:null)
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:     at ldap.searchUsersSync.Meteor.bindEnvironment (/snap/rocketchat-server/1254/programs/server/packages/rocketchat_ldap.js:1305:15)
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:     at runWithEnvironment (packages/meteor.js:1238:24)
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:   isClientSafe: true,
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:   error: 403,
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:   reason: 'Username already exists.',
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:   details: undefined,
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:   message: 'Username already exists. [403]',
Apr 27 09:03:36 chat rocketchat-server.rocketchat-server[4950]:   errorType: 'Meteor.Error' }

**Comment by CoMPaTech** [comment]
Any ideas?

**Comment by CoMPaTech** [comment]
I'll close this one in favour of #9470
