### ISSUE TITLE
RC instances get stuck after a while after update to 0.64.0

### ISSUE THREAD

**Issue by himpich** [RocketChat/Rocket.Chat#10616]
### Description:
After upgrading from 0.63.3 to 0.64.0 the RC instances get stuck after a while (30-90 minutes).
They still accept the http connection and the request but never deliver any answers. The http connection stays open forever.

This happens with a single instance as well as a 4 instance cluster. 

The info-level logoutput shows nothing special, the 'getting stuck' happens at different times / logoutputs.
No errors in the mongo log either.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.0
* Operating System: linux
* Deployment Method(snap/docker/tar/etc):  docker(-compose)
* Number of Running Instances: 1-4
* DB Replicaset Oplog: yes
* mongoDB Version: 3.2.9

### Steps to Reproduce:
1. start your RC and use it
2. chat or wait

### Expected behavior:
chat on forever :)

### Actual behavior:
after a while the http connections (proxy or not) don't answer

**Comment by yfoelling** [comment]
I´m affected by the same issue :-(

**Comment by derjohn** [comment]
+1

**Comment by himpich** [comment]
Update: After disabling all integrations, it seems to be stable. Will do further debugging.

**Comment by himbeere** [comment]
My three installations running fine. But they are not running with docker.

**Comment by andypost** [comment]
Same here, nothing useful in logs between container restart
```
Can't mix remove and get fields
Can't mix remove and get fields
Can't mix remove and get fields
Can't mix remove and get fields
Can't mix remove and get fields
Can't mix remove and get fields
Can't mix remove and get fields
Fontconfig warning: "/etc/fonts/fonts.conf", line 146: Fontconfig warning: "/etc/fonts/fonts.conf", line 146: blank doesn't take any effect anymore. please remove it from your fonts.confblank doesn't take any effect anymore. please remove it from your fonts.conf

Fontconfig warning: "/etc/fonts/fonts.conf", line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
Fontconfig warning: "/etc/fonts/fonts.conf", line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
Can't mix remove and get fields
{ room: 
   { _id: 'GCb538qdFCScorLMukiEd3vGQ7QN9qkMYJ',
     _updatedAt: 2018-04-27T10:31:28.385Z,
     t: 'd',
     msgs: 3104,
     ts: 2017-03-23T10:10:53.817Z,
     lm: 2018-04-27T10:31:28.371Z,
     meta: { revision: 0, created: 1525013815765, version: 0 },
     '$loki': 766,
     usernames: [ 'msauty', 'ktran' ] },
  subscription: 
   { _id: 'd648fMxQhAbaPsJj4',
     rid: 'GCb538qdFCScorLMukiEd3vGQ7QN9qkMYJ',
     name: 'msauty',
     t: 'd',
     open: true,
     alert: false,
     unread: 0,
     u: { _id: 'GCb538qdFCScorLMu', username: 'ktran' },
     _updatedAt: 2018-04-27T17:26:45.508Z,
     ls: 2018-04-27T10:33:32.317Z,
     userMentions: 0,
     groupMentions: 0,
     ts: 2018-02-16T09:37:29.183Z,
     meta: { revision: 0, created: 1525013816179, version: 0 },
     '$loki': 3238,
     _room: 
      { _id: 'GCb538qdFCScorLMukiEd3vGQ7QN9qkMYJ',
        _updatedAt: 2018-04-27T10:31:28.385Z,
        t: 'd',
        msgs: 3104,
        ts: 2017-03-23T10:10:53.817Z,
        lm: 2018-04-27T10:31:28.371Z,
        meta: [Object],
        '$loki': 766,
        usernames: [Array] },
     _user: 
      { _id: 'GCb538qdFCScorLMu',
        createdAt: 2017-03-22T09:17:18.861Z,
        services: [Object],
        emails: [Array],
        type: 'user',
        status: 'away',
        active: true,
        name: 'Kiêt Trân',
        _updatedAt: 2018-04-30T09:01:27.355Z,
        roles: [Array],
        lastLogin: 2018-04-30T09:01:27.339Z,
        statusConnection: 'away',
        utcOffset: 2,
        username: 'ktran',
        settings: [Object],
        statusDefault: 'online',
        language: 'en',
        requirePasswordChange: false,
        importIds: [Array],
        meta: [Object],
        '$loki': 42 },
     fname: 'Marine Sauty' } }
Can't mix remove and get fields
Can't mix remove and get fields
removing push token cCMd6AxK7Gw:APA91bGpqBvnSalSMHirCstWCuisUM7gJOeC-jRUgsIk2cEE-Zd4RVMv-kYqDTGw2oG46zpYGMqnHtjakPGqXwvgRImHd_6cUDyoZwxUapxQ0oH7Nd7l9JMIGZIoHS_C5LbhjmtseeqV
Will load cache for users
182 records load from users
Will load cache for rocketchat_room
1785 records load from rocketchat_room
Will load cache for rocketchat_subscription
5322 records load from rocketchat_subscription
Will load cache for rocketchat_settings
665 records load from rocketchat_settings
Updating process.env.MAIL_URL
Starting Email Intercepter...
Will load cache for rocketchat_permissions
78 records load from rocketchat_permissions
Will load cache for rocketchat_roles
11 records load from rocketchat_roles
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
Setting default file store to GridFS
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Mon, 30 Apr 2018 10:14:09 GMT connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead at npm/node_modules/connect/lib/middleware/bodyParser.js:56:20
Mon, 30 Apr 2018 10:14:09 GMT connect deprecated limit: Restrict request size at location of read at npm/node_modules/connect/lib/middleware/multipart.js:86:15
{"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Not migrating, already at version 115","time":{"$date":1525083250366},"level":"info"}
Using GridFS for custom sounds storage
```

**Comment by jbguerraz** [comment]
@himpich  disabling integrations didn't help here => we did it that way : ```
rs0:PRIMARY> db.rocketchat_integrations.updateMany({}, {$set: {enabled: false}})
{ "acknowledged" : true, "matchedCount" : 35, "modifiedCount" : 34 }
rs0:PRIMARY> 

```

**Comment by himbeere** [comment]
It seems we are hit by this bug too now. It only took longer I think. Deactivating integrations seems to fixit for now.

**Comment by pingutux** [comment]
Same here after update from 0.63.3 to 0.64.0.

**Comment by himbeere** [comment]
Had to go back to 063.x. Problem was getting worse.

**Comment by himpich** [comment]
Is a downgrade possible, no migrations?

**Comment by himbeere** [comment]
No it's not. Had to restore the mongodb backup from last night. The messages from today are gone.

**Comment by andypost** [comment]
I did the same - restored backup

**Comment by rodrigok** [comment]
Thanks for the reports, we are investigating this problem.

**Comment by himbeere** [comment]
@rodrigok we have just a bunch of incoming webhooks. developers, teams get a Webhook URL and a token and use that to post messages to specific channels.

**Comment by rodrigok** [comment]
Other question that could help us on this is:
Did you noticed this behavior happening on version 0.63.3 even in more rare cases?

**Comment by himbeere** [comment]
I came from 0.63.1 and had *never* such an error.  Now I'm back to 0.63.1. No complaints. Stable.

**Comment by himpich** [comment]
We did not have this problem with 0.63.3 or before.

**Comment by andypost** [comment]
I got 1 out webhook and a bunch of incoming
Also found that slack integration broken - it require disable to start container at least

**Comment by andypost** [comment]
About slack integration I got the same error as https://github.com/RocketChat/Rocket.Chat/issues/10624

**Comment by traxanos** [comment]
we have the same problem!

**Comment by joshuaspence** [comment]
I'm also seeing this problem.

**Comment by neurolabs** [comment]
symptoms are the same as #10643 (reproducible)
