### ISSUE TITLE
File upload integration doesn't work (The dollar ($) prefixed field is not valid for storage)

### ISSUE THREAD

**Issue by iprok** [RocketChat/Rocket.Chat#10617]
Freshly updated to rocket.chat 0.64. Not sure whether is was in earlier versions. I've setup outgoing integration for uploading a file in channel. But when I upload file in the channgel nothing is received in software serving the integration (matterbridge) and I see in rocket chat logs:

> [34mI20180428-23:11:05.256(0) Exception in defer callback: MongoError: The dollar ($) prefixed field '$loki' in 'httpCallData.room.$loki' is not valid for storage.     at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)     at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by rohitmyaim** [comment]
Even I am facing the same issue on Rocket chat 0.66 version.
