### ISSUE TITLE
npm/node_modules/sharp/build/Release/sharp.node: Undefined symbol "_ZTVN4vips7VOptionE"

### ISSUE THREAD

**Issue by bryn1u** [RocketChat/Rocket.Chat#10884]
Hello guys,

After node install main.js rocketchat crashes. Logs below. Im was trying to find something solution on google but google is completely keeping silent.

### Server Setup Information:

* Version of Rocket.Chat Server:  rocket.chat-latest.tgz
* Operating System: FreeBSD 11 - Stable
* Deployment Method(snap/docker/tar/etc): tar and then node install main.js
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: v10.1.0
* mongoDB Version: mongodb36-3.6.4_1 

### Expected behavior:

Possibility to install properlly.

### Actual behavior:
```
[bryn1u@HBSD /usr/home/bryn1u/bundle]$ node main.js 
Will load cache for users
0 records load from users
Will load cache for rocketchat_room
0 records load from rocketchat_room
Will load cache for rocketchat_subscription
0 records load from rocketchat_subscription
Will load cache for rocketchat_settings
364 records load from rocketchat_settings
Updating process.env.MAIL_URL
Starting Email Intercepter...
Will load cache for rocketchat_permissions
0 records load from rocketchat_permissions
Will load cache for rocketchat_roles
0 records load from rocketchat_roles
Exception in callback of async function: Error: /usr/home/bryn1u/bundle/programs/server/npm/node_modules/sharp/build/Release/sharp.node: Undefined symbol "_ZTVN4vips7VOptionE"
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:707:18)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/home/bryn1u/bundle/programs/server/npm/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/home/bryn1u/bundle/programs/server/npm/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at npmRequire (/usr/home/bryn1u/bundle/programs/server/npm-require.js:133:10)
    at Module.useNode (packages/modules-runtime.js:697:18)
    at fileEvaluate (packages/modules-runtime.js:342:20)
    at require (packages/modules-runtime.js:238:16)
    at FileUpload.js (packages/rocketchat:file-uploe.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /usr/home/bryn1u/bundle/programs/server/packages/rocketchat_file-upload.js:2254:1
    at /usr/home/bryn1u/bundle/programs/server/packages/rocketchat_file-upload.js:2268:3
    at /usr/home/bryn1u/bundle/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /usr/home/bryn1u/bundle/programs/server/boot.js:220:19
    at /usr/home/bryn1u/bundle/programs/server/boot.js:471:5
    at Function.run (/usr/home/bryn1u/bundle/programs/server/profile.js:510:12)
    at /usr/home/bryn1u/bundle/programs/server/boot.js:470:11
   ad/server/lib/FileUpload.js:1:351)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /usr/home/bryn1u/bundle/programs/server/packages/rocketchat_file-upload.js:2254:1
    at /usr/home/bryn1u/bundle/programs/server/packages/rocketchat_file-upload.js:2268:3
    at /usr/home/bryn1u/bundle/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /usr/home/bryn1u/bundle/programs/server/boot.js:220:19
    at /usr/home/bryn1u/bundle/programs/server/boot.js:471:5
    at Function.run (/usr/home/bryn1u/bundle/programs/server/profile.js:510:12)
    at /usr/home/bryn1u/bundle/programs/server/boot.js:470:11

```

**Comment by tinlans** [comment]
Pre-compiled release version is unsuitable to FreeBSD. You should set up the developement environment called Meteor first. However, the default installation of Meteor doesn't work and no people are willing to share how they fine-tune Meteor so it's still a secret now.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
