### ISSUE TITLE
Internal server error after adding custom fields

### ISSUE THREAD

**Issue by siberijah** [RocketChat/Rocket.Chat#10979]
### Description:

I've added some custom fields and while trying to save some info in it, cathing an error "Internal server error". Dowsn't matter if you are user or admin or trying to register, if you are trying to write something in the costom fields, you will see error.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.1 (latest by this date)
* Operating System: debian 9
* Deployment Method(snap/docker/tar/etc): tar/pm2
* Number of Running Instances: 1
* DB Replicaset Oplog: unkown
* Node Version: v8.9.3
* mongoDB Version: v3.6.4

### Steps to Reproduce:

1. I've added custom field like this:
{
 "Phone": {"type": "text",
  "required": false,
  "minLength": 2,
  "maxLength": 100}
}
2. I can see my custom field in my profile settings (admin account)
3. Putting digits in the field
4. Catching "Internal Server Error"
Also I'm cathing the same error when I'm trying to register a new account and put some info in the custom field.

### Relevant logs:

`0|rocketch | Exception while invoking method 'saveUserProfile' MongoError: Cannot create field 'Phone' in element {customFields: null}
0|rocketch |     at Function.MongoError.create (/var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
0|rocketch |     at toError (/var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)
0|rocketch |     at /var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67
0|rocketch |     at /var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
0|rocketch |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
0|rocketch |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
`

**Comment by sovaby** [comment]
Clear all fields containing NUL

**Comment by siberijah** [comment]
Thank you, that worked for me:

Steps:

I've found in the internet how to find and delete NULL recursively in collection. Saves it as .js file
My db name is "rocketchat"
```
use rocketchat;
var coll = db.getCollection("string_to_sed");
var cursor = coll.find();
while (cursor.hasNext()) {
    var doc = cursor.next();
    var keys = {};
    var hasNull = false;
    for ( var x in doc) {
        if (x != "_id" && doc[x] == null) {
            keys[x] = 1;
            hasNull = true;
        }
    }
    if (hasNull) {
        coll.update({_id: doc._id}, {$unset:keys});
    }
}
```
2. the fastest way for me was to loop this script for all collections in my database;
```
root@server# for i in $(mongo chat --eval "db.getCollectionNames().join('\n')"); do sed -i 's/string_to_sed/'$i'/g' removenulls.js; mongo < removenulls.js; sed -i 's/'$i'/string_to_sed/g' removenulls.js; done
```

Noob but fast =)

**Comment by siberijah** [comment]
As I've posted above, clearing NULLs worked for me, but there is another issue. One user still cathes an error, the same mongo error with NULLs but his profile changes and everybody can see it. No Nulls in mongo btw. Is it a bug or what?
