### ISSUE TITLE
Does not permit "MongoDB Atlas" DBaaS - Auth

### ISSUE THREAD

**Issue by jaydestro** [RocketChat/Rocket.Chat#10997]
### Description:

When using MongoDB Atlas as the DB provider in the docker-compose.yml you are told there is no valid database user - it will not permit access tot he database.  looks like scramsha-1 isn't supported?

```
bash-3.2$ vi docker-compose.yml
bash-3.2$ docker-compose up
Recreating jaygordon_rocketchat_1 ... done
Attaching to jaygordon_rocketchat_1
rocketchat_1  |
rocketchat_1  | /app/bundle/programs/server/node_modules/fibers/future.js:313
rocketchat_1  | 						throw(ex);
rocketchat_1  | 						^
rocketchat_1  | MongoError: not authorized on admin to execute command { listIndexes: "users", cursor: {}, $db: "admin" }
rocketchat_1  |     at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
rocketchat_1  |     at queryCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:212:36)
rocketchat_1  |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
rocketchat_1  |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
rocketchat_1  |     at process._tickCallback (internal/process/next_tick.js:180:9)
jaygordon_rocketchat_1 exited with code 1
```

### Server Setup Information:

* Version of Rocket.Chat Server: latest
* Operating System: Docker - Debian
* Deployment Method(snap/docker/tar/etc): Docker 
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 3.4

### Steps to Reproduce:

Use MongoDB Atlas with Auth enabled

**Comment by engelgabriel** [comment]
@MartinSchoeler can you please add this to the docs?
