### ISSUE TITLE
"Internal server error" when downloading "my data" from the user Profile 

### ISSUE THREAD

**Issue by brtptrs** [RocketChat/Rocket.Chat#10994]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: CentOS
* Deployment Method(snap/docker/tar/etc): Repo
* Number of Running Instances: 1
* Node Version: v8.11.1
* mongoDB Version: 

### Steps to Reproduce:

1. Go to "My acount->settings
2. Scroll down to "My Data"
3. Select download

### Expected behavior:

Pesonal data should be downloaded

### Actual behavior:

System returns an internal server error.

### Relevant logs:
[34mI20180604-12:44:25.455(2) Exception while invoking method 'requestDataDownload' Error: ENOENT: no such file or directory, mkdir '/tmp/userData/xxx'     at Object.fs.mkdirSync (fs.js:885:18)     at MethodInvocation.requestDataDownload (pathto/Rocket.Chat/programs/server/app/app.js:10356:10)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at MethodInvocation.methodsMap.(anonymous function) (pathto/Rocket.Chat/programs/server/packages/rocketchat_lib.js:2186:28)     at maybeAuditArgumentChecks (pathto/Rocket.Chat/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (pathto/Rocket.Chat/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (pathto/Rocket.Chat/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (pathto/Rocket.Chat/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (pathto/Rocket.Chat/programs/server/packages/ddp-server.js:875:23)     at pathto/Rocket.Chat/programs/server/packages/ddp-server.js:754:8

**Comment by kaiiiiiiiii** [comment]
Please upgrade to the latest version. This has already been adressed in #10777 and was fixed in PR #10837 (part of Release 0.65.0)

**Comment by brtptrs** [comment]
Thanks, and sorry for the noise, I missed that fix.
