### ISSUE TITLE
Exception while invoking method 'rocketchatSearch.search' MongoError

### ISSUE THREAD

**Issue by mmiskiew** [RocketChat/Rocket.Chat#11000]
### Description:

It's impossible to search messages with "search option". It is returning alert "Search failed" and no results.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.2
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: -
* Node Version: v 8.9.3
* mongoDB Version: 3.6

### Steps to Reproduce:

1. get into any conversation / room
2. Click search
3. Search anything

### Expected behavior:

Search results should appear

### Actual behavior:

Error message (alert)

### Relevant logs:
`Exception while invoking method 'rocketchatSearch.search' MongoError: Unable to execute query: error processing query: ns=rocketchat.rocketchat_message limit=10 skip=0 Tree: $and     rid == "***"     $not         _hidden == true     $not         t == "rm"     TEXT : query=pi, language=, tag=NULL Sort: { ts: -1 } Proj: { score: { $meta: "textScore" } }  planner returned error: need exactly one text index for $text query     at Function.MongoError.create (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)     at queryCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:197:34)     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
`

**Comment by mmiskiew** [comment]
Ok, the problem is that i migrated old rocket.chat with mogodump and mongorestore and used "noIndex" parameter. Just recreated indexes on rocketchat_message manually and everything is now ok (used metadata from old dump, modified by removing textindexversion: 3 and 2dsphere from 3 to 2).
