### ISSUE TITLE
Failure to authenticate with LDAP

### ISSUE THREAD

**Issue by mydoghasworms** [RocketChat/Rocket.Chat#11100]
### Description:

Server has been configured to perform authentication against an LDAP server. However, it does not seem that authentication is working. The server seems to expect that there must be an admin service user available. When trying to log on, a response as follows is given:

`User not found or incorrect password`

On the server log, the following entry appears:

`LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection`

### Steps to reproduce:

Log on to server that has been configured with LDAP authentication.

### Expected behavior:

The RC server should be able to use the supplied credentials to bind to the given LDAP server to confirm login details are correct and copy user from server, without the need for an admin service user.

### Actual behavior:

As described above.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Operating System: 4.15.0-23-generic
- Deployment Method: snap
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.2
- MongoDB Version: 

### Relevant logs:

```
[34mI20180612-13:12:41.356(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TCP.onread (net.js:618:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
[34mI20180612-13:14:04.226(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TCP.onread (net.js:618:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
[34mI20180612-13:14:07.085(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Search.error { OperationsError: 000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580     at messageCallback (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)     at Socket.onData (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:597:20)    lde_message: '000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580\u0000',   lde_dn: null } 
[34mI20180612-13:14:07.087(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAPHandler ➔ error { OperationsError: 000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580     at messageCallback (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)     at Socket.onData (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:597:20)    lde_message: '000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580\u0000',   lde_dn: null } 
[34mI20180612-13:14:19.353(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Search.error { OperationsError: 000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580     at messageCallback (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)     at Socket.onData (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:597:20)    lde_message: '000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580\u0000',   lde_dn: null } 
[34mI20180612-13:14:19.355(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAPHandler ➔ error { OperationsError: 000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580     at messageCallback (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)     at Socket.onData (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:597:20)    lde_message: '000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580\u0000',   lde_dn: null } 
[34mI20180612-13:14:34.239(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TCP.onread (net.js:618:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
[34mI20180612-13:15:04.255(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TCP.onread (net.js:618:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
[34mI20180612-13:15:04.256(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TCP.onread (net.js:618:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
[34mI20180612-13:15:41.440(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TCP.onread (net.js:618:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
[34mI20180612-13:16:45.654(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Search.error { OperationsError: 000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580     at messageCallback (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)     at Socket.onData (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:597:20)    lde_message: '000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580\u0000',   lde_dn: null } 
[34mI20180612-13:16:45.655(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAPHandler ➔ error { OperationsError: 000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580     at messageCallback (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)     at Socket.onData (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:597:20)    lde_message: '000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580\u0000',   lde_dn: null } 
[34mI20180612-13:17:04.325(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TCP.onread (net.js:618:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
[34mI20180612-13:17:34.334(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TCP.onread (net.js:618:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
```

**Comment by TheReal1604** [comment]
@mydoghasworms Logs to me like there is something wrong with your service account how performs the initial LDAP lookup. LDAP Authentication is working for me in 0.65.1 with 3k~ users.

**Comment by mydoghasworms** [comment]
@TheReal1604 I am not using a service account. Why do I need to? 
What is the purpose of the service account? Surely you just want to check that you can bind to the LDAP with the given credentials. That should suffice to authenticate an LDAP user. And then copy their details (as I assume a user has at least read access to their own data like email, name etc.)
Besides, the service user details under the "Authentication" section are optional. There is a switch to enable Authentication (true/false). So what is the actual purpose of this service account?

**Comment by moonwolf-github** [comment]
It works for me without service account.

**Comment by mydoghasworms** [comment]
@moonwolf-github Thanks for the suggestion. I tried setting that switch in the Authentication tab on, but the logon still fails. I get the following in the log:

```
[34mI20180613-14:51:39.622(2) rocketchat_logger rocketchat_logger.js:278 [31mLDAPHandler ➔ error { OperationsError: 000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580     at messageCallback (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)     at Socket.onData (/snap/rocketchat-server/1273/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:597:20)    lde_message: '000004DC: LdapErr: DSID-0C090752, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580\u0000',   lde_dn: null } 
```

**Comment by mydoghasworms** [comment]
What I don't understand is that the description for the first option on the first section, where you enable LDAP integration, is "Attempt to utilize LDAP for authentication".
So, as I understand, providing the details in the first section should be sufficient to allow users logging in to be authenticated against the LDAP. All the other options are, and should be, optional.

**Comment by mydoghasworms** [comment]
Welll, I finally got it working, but I had to use a service user :disappointed: 

@moonwolf-github Does your LDAP allow anonymous bind for read, or how is your setup different?

Again, I cannot understand the purpose of the service user, or why it is needed, especially when it is an optional configuration setting. To my mind:

1. Rocket.Chat should use the credentials of the person logging on to bind to the LDAP and count that as authentication, without the need of a service user
2. The details for the user can be read, surely, without a service user, but with the credentials of the person logging on (all that is needed is email and name, I suppose)

**Comment by moonwolf-github** [comment]
Well yes, i can read from LDAP server anonymously (not everything of course - passwords for example are only for authenticated users).

**Comment by mydoghasworms** [comment]
@TheReal1604 It doesn't  justify the need for a service account though. As I said above, the user that is providing their credentials presumably should have (and that should probably be 99.9% of cases) access to read their own data from the LDAP.
Therefore, when they log on for the first time to RC and RC needs to get their details from the LDAP (cn, email, etc.), the connection that is established to the LDAP when the user authenticates themselves (i.e. binding with the user's own credentials) can (and I think should) be used to read this data.
That would, in my mind, make a service account optional, and only needed in the (highly unlikely) case that an LDAP user does not have access to read their own entry from the LDAP server.
Perhaps I have not expressed myself clearly enough; I hope I have.

**Comment by balcsida** [comment]
We don't use service account and LDAP auth and sync works as it should.
