### ISSUE TITLE
Error: MONGO_URL must be set in environment

### ISSUE THREAD

**Issue by duckle** [RocketChat/Rocket.Chat#11218]
### Description:
When try to start RocketChat server(ver 0.66.rc-0), I got an error to say MONGO_URL must be set even if this environment var is there.

### Steps to reproduce:

1. Download the tar file from Rocketchat
2. Use tar command to unzip it to local /var/www/rocket.chat
3. change current path to /var/www/rocket.chat/bundle/programs/server
4. run npm install command to install dependencies successfully
5. change current folder to /var/www/rocket.chat/bundle
6. set following variable
`NODE_ENV=production 
PORT=3000 
ROOT_URL=http://localhost:3000 
MONGO_URL=mongodb://localhost:27017/rocketchat 
MONGO_OPLOG_URL=mongodb://localhost:27017/local ` 
7. run node main.js to start rocketchat server

### Expected behavior:
expect RocketChat server is started successfully

### Actual behavior:
I got following error message to say **Error: MONGO_URL must be set in environment**

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.0-rc.0
- Operating System: CentOS 7
- Deployment Method:  Tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.1
- MongoDB Version: v3.6.5

### Additional context
![image](https://user-images.githubusercontent.com/6891277/41727278-da2bbc2c-756b-11e8-9990-70fece7d8bbc.png)

### Relevant logs:
`
[yuhua@UNKNOWN bundle]$ node main.js
/home/yuhua/bundle/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Collection (packages/mongo/collection.js:97:40)
    at new AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at server_main.js (packages/accounts-base/server_main.js:9:12)

    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /home/yuhua/bundle/programs/server/packages/accounts-base.js:2012:15
    at /home/yuhua/bundle/programs/server/packages/accounts-base.js:2019:3
    at /home/yuhua/bundle/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /home/yuhua/bundle/programs/server/boot.js:220:19
    at /home/yuhua/bundle/programs/server/boot.js:471:5
    at Function.run (/home/yuhua/bundle/programs/server/profile.js:510:12)
    at /home/yuhua/bundle/programs/server/boot.js:470:11
`

**Comment by victoorlucas** [comment]
I have the same error on Google Cloud VM
