### ISSUE TITLE
Exception in callback of async function: Error: [Can't find migration version 128]

### ISSUE THREAD

**Issue by ChessSpider** [RocketChat/Rocket.Chat#11226]
I just pulled the latest version from https://hub.docker.com/r/rocketchat/rocket.chat/tags/ and got this.
its probably due to this push: latest
242 MB
9 hours ago

downgrading doesnt work
```
rocketchat_1          | Exception in callback of async function: Error: [Can't find migration version 128]
rocketchat_1          |     at Object.Migrations._findIndexByVersion (/app/bundle/programs/server/packages/rocketchat_migrations.js:435:9)
rocketchat_1          |     at Object.Migrations._migrateTo (/app/bundle/programs/server/packages/rocketchat_migrations.js:300:25)
rocketchat_1          |     at Object.Migrations.migrateTo (/app/bundle/programs/server/packages/rocketchat_migrations.js:227:23)
rocketchat_1          |     at xrun.js (/app/bundle/programs/server/app/app.js:7213:25)
rocketchat_1          |     at fileEvaluate (packages/modules-runtime.js:343:9)
rocketchat_1          |     at require (packages/modules-runtime.js:238:16)
rocketchat_1          |     at /app/bundle/programs/server/app/app.js:12922:1
rocketchat_1          |     at /app/bundle/programs/server/boot.js:411:36
rocketchat_1          |     at Array.forEach (<anonymous>:null:null)
rocketchat_1          |     at /app/bundle/programs/server/boot.js:220:19
rocketchat_1          |     at /app/bundle/programs/server/boot.js:471:5
rocketchat_1          |     at Function.run (/app/bundle/programs/server/profile.js:510:12)
rocketchat_1          |     at /app/bundle/programs/server/boot.js:470:11
```

**Comment by azgul** [comment]
I reported the same over at https://github.com/RocketChat/Docker.Official.Image/issues/52

Is there any way to run the migration manually?

**Comment by azgul** [comment]
Found a workaround if you're still struggling with this issue: https://github.com/RocketChat/Docker.Official.Image/issues/52#issuecomment-399703289

**Comment by ChessSpider** [comment]
Hi @azgul I posted my worry about your fix in the thread. But Im glad you have your installation working again!

**Comment by ChessSpider** [comment]
So my rocket.chat instance is working agian.

I created a new rocketchat instance, and logged into the mongo-database to find its current migration level.  

```
docker-compose exec mongo /bin/bash
root@373da192e035:/# mongo
MongoDB shell version: 3.2.20
connecting to: test
rs0:PRIMARY> use rocketchat
switched to db rocketchat
rs0:PRIMARY> db.migrations.find()
{ "_id" : "control", "version" : 121, "locked" : false, "lockedAt" : ISODate("2018-06-25T09:34:59.270Z"), "buildAt" : "2018-06-16T21:33:15.003Z" }
```

I then changed the migration-level of the broken rocketchat instance to 121:
```
 docker-compose exec mongo /bin/bash
mongo
rs0:PRIMARY> use rocketchat
switched to db rocketchat
drs0:PRIMARY>db.migrations.find()
{ "_id" : "control", "version" : 128, "locked" : true, "lockedAt" : ISODate("2018-06-21T21:24:50.824Z"), "buildAt" : "2018-06-16T21:33:15.003Z" }
rs0:PRIMARY> db.migrations.update({"_id": "control"}, {"version": 121, "locked": false})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
rs0:PRIMARY> db.migrations.find()
{ "_id" : "control", "version" : 121, "locked" : false }
exit
exit
docker-compose restart
```
Watch the logs, and it said ``{"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Not migrating, already at version 121","time":{"$date":1529919716358},"level":"info"}``.

Now running: Rocket.Chat Version: 0.65.2   ~~ SAML login is still broken lol but at least existing sessions work again.
