### ISSUE TITLE
[BUG]can't de develop in Ubuntu 18.04 LTS amd64

### ISSUE THREAD

**Issue by YangYaRu123** [RocketChat/Rocket.Chat#11258]
### Description:

use 'meteor npm start' many times, but't always success

### Steps to reproduce:

1. cd my-project
2. run 'meteor npm start'
3. throw error

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.0-develop
- Operating System: Ubuntu 18.04 LTS amd64
- NodeJS Version: 8.11.3

### Additional context
use taobao's npm registy

### Relevant logs:
[[[[[ ~/skill-box ]]]]]    
=> Started proxy.                             
sh: 0: Can't open /home/yang/skill-box/packages/rocketchat-livechat/plugin/build.sh
/home/yang/.meteor/packages/swydo_graphql/.0.0.3.1ij3jfu.o9swh++os+web.browser+web.cordova/plugin.compile-graphql.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: Builder can not write without either data or a file path or a symlink path: os/packages/rocketchat_livechat/public/head.html
    at Builder.write (/tools/isobuild/builder.js:258:13)
    at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:389:10)
    at /tools/isobuild/unibuild.js:327:17
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/home/yang/.meteor/packages/meteor-tool/.1.6.1_1.12mpanq.ybql++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Unibuild.toJSON (/tools/isobuild/unibuild.js:320:7)
    at /tools/isobuild/isopack.js:1099:39
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/home/yang/.meteor/packages/meteor-tool/.1.6.1_1.12mpanq.ybql++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Isopack.saveToPath (/tools/isobuild/isopack.js:1076:9)
    at /tools/isobuild/isopack-cache.js:377:23
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:315:18)
    at Profile.time (/tools/isobuild/isopack-cache.js:249:16)
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:248:17
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
    at /tools/isobuild/isopack-cache.js:75:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/home/yang/.meteor/packages/meteor-tool/.1.6.1_1.12mpanq.ybql++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at exports.PackageMap.eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:74:24)
    at /tools/project-context.js:847:25
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:846:18)
    at /tools/project-context.js:285:9
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:275:18)
    at Profile.run (/tools/project-context.js:267:12)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:266:13)
    at /tools/runners/run-app.js:554:29
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:553:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:622:35)
    at AppRunner._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:408:12

**Comment by YangYaRu123** [comment]
already see all issues about 'promise_server' and 'Builder can not write without either data or a file path or a symlink path' 
but not issues can't solve my problem QAQ

**Comment by tassoevan** [comment]
Did you see any error just running `meteor npm install`?

**Comment by TwizzyDizzy** [comment]
Hi @YangYaRu123 

Please use the [forums](https://forums.rocket.chat/) for such questions, as this is not a Rocket.Chat bug.

Cheers (+close)
Thomas
