### ISSUE TITLE
Exception during startup

### ISSUE THREAD

**Issue by avignat** [RocketChat/Rocket.Chat#11286]
```
Jun 28 13:18:55  rocketchat[2003]: Updating process.env.MAIL_URL
Jun 28 13:18:55  rocketchat[2003]: Using GridFS for custom sounds storage
Jun 28 13:18:55  rocketchat[2003]: Using GridFS for custom emoji storage
Jun 28 13:18:58  rocketchat[2003]: Loaded the Apps Framework and loaded a total of 0 Apps!
Jun 28 13:18:59  rocketchat[2003]: Exception in defer callback: TypeError: Cannot read property 'name' of undefined
Jun 28 13:18:59  rocketchat[2003]:     at cursor.forEach.subscription (/home/rocketchat/programs/server/packages/rocketchat_user-data-download.js:120:29)
Jun 28 13:18:59  rocketchat[2003]:     at Array.forEach (<anonymous>:null:null)
Jun 28 13:18:59  rocketchat[2003]:     at Object.forEach (/home/rocketchat/programs/server/packages/rocketchat_lib.js:11947:26)
Jun 28 13:18:59  rocketchat[2003]:     at loadUserSubscriptions (/home/rocketchat/programs/server/packages/rocketchat_user-data-download.js:117:10)
Jun 28 13:18:59  rocketchat[2003]:     at continueExportOperation (/home/rocketchat/programs/server/packages/rocketchat_user-data-download.js:493:5)
Jun 28 13:18:59  rocketchat[2003]:     at cursor.forEach.exportOperation (/home/rocketchat/programs/server/packages/rocketchat_user-data-download.js:556:5)
Jun 28 13:18:59  rocketchat[2003]:     at SynchronousCursor.forEach (/home/rocketchat/programs/server/packages/mongo.js:1060:16)
Jun 28 13:18:59  rocketchat[2003]:     at Cursor.(anonymous function) [as forEach] (/home/rocketchat/programs/server/packages/mongo.js:902:44)
Jun 28 13:18:59  rocketchat[2003]:     at processDataDownloads (/home/rocketchat/programs/server/packages/rocketchat_user-data-download.js:551:10)
Jun 28 13:18:59  rocketchat[2003]:     at /home/rocketchat/programs/server/packages/rocketchat_user-data-download.js:567:5
Jun 28 13:18:59  rocketchat[2003]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
Jun 28 13:18:59  rocketchat[2003]:     at packages/meteor.js:502:25
Jun 28 13:18:59  rocketchat[2003]:     at runWithEnvironment (packages/meteor.js:1238:24)
Jun 28 13:19:00  rocketchat[2003]: ➔ System ➔ startup
```

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.0
- Operating System: Debian 9
- Deployment Method: Manual
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.3
- MongoDB Version: 3.2

This doesn't interrupt the server startup but it is wierd.

**Comment by geekgonecrazy** [comment]
Shouldn’t be happening any more.  If so let us jnow

**Comment by dsobrinho40** [comment]
Description: 
I20220325-22:38:20.686(0) LocalStore: store created at {"level":40,"time":"2022-03-25T22:38:26.857Z","pid":709,"hostname":"98150b92ca2a","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"} 
{"level":51,"time":"2022-03-25T22:38:27.107Z","pid":709,"hostname":"98150b92ca2a","name":"Migrations","msg":"Not migrating, already at version 256"}

I20220325-22:36:32.651(0) Loaded the Apps Framework and loaded a total of 2 Apps!

Server Setup Information
Server hardware: 			                Hypervisor
Version of Rocket.Chat Server:		4.5.3 	
Operating System: 			                Ubuntu 18.04LTS
Deployment Method:			        docker
Number of Running Instances:		1
DB Replicaset Oplog:			        Enabled
NodeJS Version:				       14.18.3 - x64
MongoDB Version:			5.0.6
