### ISSUE TITLE
Duplicate key error when trying to log in with GitHub connected account after recent database migration

### ISSUE THREAD

**Issue by alexweissman** [RocketChat/Rocket.Chat#11326]
### Description:

 It looks like snap triggered a database migration (but not an application update) on our chat server this morning:

![screen shot 2018-07-03 at 1 29 49 pm](https://user-images.githubusercontent.com/5004534/42235247-36cac7ae-7ec5-11e8-8dbe-e92ae92659a2.png)

I found that I had been automatically logged out this morning, most likely because of this migration. I had been logged in via OAuth with my connected Github account. When I try to log back in with the same account using the Github integration, I get a generic "Internal server error" message.

When I check the logs using a separate, non-OAuth account, I can see this error being generated when I try to log in:

```
Exception while invoking method 'login' MongoError: E11000 duplicate key error collection: parties.users index: services.github.id_1 dup key: { : 5004534 }     at Function.MongoError.create (/snap/rocketchat-server/1273/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)     at toError (/snap/rocketchat-server/1273/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)     at /snap/rocketchat-server/1273/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67     at /snap/rocketchat-server/1273/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

It appears that it is trying to create a duplicate record on a unique key - is it trying to recreate the record for my OAuth account, instead of finding the one that already exists?

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.2

**Comment by reetp** [comment]
Can you advise is this still occurs on the latest snap 0.70.4
