### ISSUE TITLE
Error sending push to gateway (3 try) -> TypeError: First argument should be a valid curve name

### ISSUE THREAD

**Issue by soyisraelortiz** [RocketChat/Rocket.Chat#11337]
### Description:

I got an error on rocket chat log when i press the button "send test notification" from admin panel 

```
rocketchat_logger rocketchat_logger.js:278 System ➔ error Error sending push to gateway (3 try) -> 
```
push is never received on iphone app nor android app 

### Steps to reproduce:

1. Install new instance of rocket chat 
2. Use default gateway configuration
3. Press send test push notification from admin panel 

### Expected behavior:

Receive a push on my iphone or android apps of rocket chat (installed Rocketchat+) 

### Actual behavior:

Push is never received, and rocket chat logger shows error: 
Error sending push to gateway (3 try) -> TypeError: First argument should be a valid curve name

### Server Setup Information:

- Version of Rocket.Chat Server:  0.66.0
- Operating System: Linux / ubuntu 16.04
- Deployment Method: mup (docker)
- Number of Running Instances: 1 
- DB Replicaset Oplog: disabled
- NodeJS Version: v8.4.0
- MongoDB Version: mongo:3.4.1   MONGO_URL: 'mongodb://localhost/meteor'

### Relevant logs:
```
rocketchat_logger rocketchat_logger.js:278 System ➔ error Error sending push to gateway (3 try) -> TypeError: First argument should be a valid curve name
at Object.createSecureContext (_tls_common.js:115:15)
at Object.exports.connect (_tls_wrap.js:1048:48)
at Agent.createConnection (https.js:111:22)
at Agent.createSocket (_http_agent.js:217:26)
at Agent.addRequest (_http_agent.js:187:10)
at new ClientRequest (_http_client.js:272:16)
at Object.request (http.js:39:10)
at Object.request (https.js:239:15)
at Request.start (/built_app/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:748:32)
at Request.write (/built_app/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1498:10)
at end (/built_app/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:546:18)
at Immediate.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:575:7)
at runCallback (timers.js:781:20)
at tryOnImmediate (timers.js:743:5)
at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by sampaiodiego** [comment]
thx for the detailed report.

does you server have access to send POST requests to https://gateway.rocket.chat ? that is the only thing rocket.chat does when you push that button.

**Comment by DJayKay** [comment]
Have also Problems with it in a 0.66.2 Server (Manual installation, on a Debian9 AWS Instance)

My Heroku Test System (0.65.1) Is working well.

But I can't give you an Error Message because I don't get one

**Comment by geekgonecrazy** [comment]
Please let us know if happens again.  But definitely should not be happening any more with newer versions of Rocket.chat
