### ISSUE TITLE
RocketChat does not start due to IRC plugin ?

### ISSUE THREAD

**Issue by NicolasBertrand** [RocketChat/Rocket.Chat#11479]
Running on debian stretch 64 bits with snap

### Description:
On Debian 9 with rocketchat running on snap.
Rocketchat no more start after upgrade (via snap).  

### Steps to reproduce:

`
 systemctl restart snap.rocketchat-server.rocketchat-server.service 

Jul 17 09:56:21 smaug rocketchat-server.rocketchat-server[434]: Checking if oplog has been enabled, and enabling if not
Jul 17 09:56:21 smaug rocketchat-server.rocketchat-server[434]: MongoDB shell version: 3.2.7
Jul 17 09:56:21 smaug rocketchat-server.rocketchat-server[434]: connecting to: test
Jul 17 09:56:23 smaug rocketchat-server.rocketchat-server[434]: Will load cache for users
Jul 17 09:56:23 smaug rocketchat-server.rocketchat-server[434]: 6 records load from users
Jul 17 09:56:23 smaug rocketchat-server.rocketchat-server[434]: Will load cache for rocketchat_room
Jul 17 09:56:23 smaug rocketchat-server.rocketchat-server[434]: 5 records load from rocketchat_room
Jul 17 09:56:23 smaug rocketchat-server.rocketchat-server[434]: Will load cache for rocketchat_subscription
Jul 17 09:56:23 smaug rocketchat-server.rocketchat-server[434]: 13 records load from rocketchat_subscription
Jul 17 09:56:23 smaug rocketchat-server.rocketchat-server[434]: Will load cache for rocketchat_settings
Jul 17 09:56:23 smaug rocketchat-server.rocketchat-server[434]: 705 records load from rocketchat_settings
Jul 17 09:56:24 smaug rocketchat-server.rocketchat-server[434]: Updating process.env.MAIL_URL
Jul 17 09:56:25 smaug rocketchat-server.rocketchat-server[434]: Will load cache for rocketchat_permissions
Jul 17 09:56:25 smaug rocketchat-server.rocketchat-server[434]: 80 records load from rocketchat_permissions
Jul 17 09:56:25 smaug rocketchat-server.rocketchat-server[434]: Will load cache for rocketchat_roles
Jul 17 09:56:25 smaug rocketchat-server.rocketchat-server[434]: 11 records load from rocketchat_roles
Jul 17 09:56:26 smaug rocketchat-server.rocketchat-server[434]: Starting Email Intercepter...
Jul 17 09:56:26 smaug rocketchat-server.rocketchat-server[434]: Warning: connect.session() MemoryStore is not
Jul 17 09:56:26 smaug rocketchat-server.rocketchat-server[434]: designed for a production environment, as it will leak
Jul 17 09:56:26 smaug rocketchat-server.rocketchat-server[434]: memory, and will not scale past a single process.
Jul 17 09:56:26 smaug rocketchat-server.rocketchat-server[434]: LocalStore: store created at
Jul 17 09:56:26 smaug rocketchat-server.rocketchat-server[434]: LocalStore: store created at
Jul 17 09:56:26 smaug rocketchat-server.rocketchat-server[434]: LocalStore: store created at
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]: Setting default file store to GridFS
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]: Exception in callback of async function: TypeError: Server is not a constructor
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]:     at new Bridge (/snap/rocketchat-server/1307/programs/server/packages/rocketchat_irc.js:230:19)
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]:     at irc.js (/snap/rocketchat-server/1307/programs/server/packages/rocketchat_irc.js:47:22)
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]:     at fileEvaluate (packages/modules-runtime.js:343:9)
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]:     at require (packages/modules-runtime.js:238:16)
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]:     at /snap/rocketchat-server/1307/programs/server/packages/rocketchat_irc.js:2268:1
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]:     at /snap/rocketchat-server/1307/programs/server/packages/rocketchat_irc.js:2275:3
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]:     at /snap/rocketchat-server/1307/programs/server/boot.js:411:36
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]:     at Array.forEach (<anonymous>:null:null)
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]:     at /snap/rocketchat-server/1307/programs/server/boot.js:220:19
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]:     at /snap/rocketchat-server/1307/programs/server/boot.js:471:5
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]:     at Function.run (/snap/rocketchat-server/1307/programs/server/profile.js:510:12)
Jul 17 09:56:27 smaug rocketchat-server.rocketchat-server[434]:     at /snap/rocketchat-server/1307/programs/server/boot.js:470:11
`

Maybe remove rocketchat IRC before start ? Byt how I can  do this ?

**Comment by erenfro** [comment]
I'm having the same issue. I just updated rocket.chat with docker-compose pull, and now it won't start because of this similar issue.

**Comment by wrein** [comment]
Same here. But in docker deploy.
