### ISSUE TITLE
Error invoking Method 'livechat:pageVisited' / 500 Internal Server Error

### ISSUE THREAD

**Issue by Hativ** [RocketChat/Rocket.Chat#11530]
### Description:

LiveChat does not appear on website. Javascript console shows error.

### Steps to reproduce:

1. Integrate LiveChat in Website using the code from "Installation"
2. Go to Website
3. No LiveChat appears

### Expected behavior:

LiveChat should appear.

### Actual behavior:

LiveChat does not appear.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.3
- Operating System: Ubuntu 18.04 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.3
- MongoDB Version: 

### Relevant logs:

Browser log:
```
Error invoking Method 'livechat:pageVisited': 
    r
      details: undefined
      error: 500
      errorType: "Meteor.Error"isClientSafe: true
      message: "Internal server error [500]"
      reason: "Internal server error"stack: "Error: Internal server error [500]↵    at t.e [as _livedata_result] (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:65:20481)↵    at t.e [as onMessage] (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:65:23113)↵    at https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:3467↵    at Array.forEach (<anonymous>)↵    at e.t [as forEachCallback] (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:4747)↵    at T.socket.onmessage (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:3429)↵    at T.o.dispatchEvent (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:7660)↵    at T._dispatchMessage (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:21411)↵    at T._didMessage (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:22311)↵    at WebSocket.o.ws.onmessage (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:24460)"
      __proto__: Error Error: Internal server error [500]
    at t.e [as _livedata_result] (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:65:20481)
    at t.e [as onMessage] (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:65:23113)
    at https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:3467
    at Array.forEach (<anonymous>)
    at e.t [as forEachCallback] (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:4747)
    at T.socket.onmessage (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:3429)
    at T.o.dispatchEvent (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:7660)
    at T._dispatchMessage (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:21411)
    at T._didMessage (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:22311)
    at WebSocket.o.ws.onmessage (https://chat.example.com/livechat/livechat.js?_dc=34fbf320244d9d049ce5ffa8f00aabbfa2e6a30e:63:24460)
```

Server log:
```
[34mI20180720-19:21:07.726(0) [34mMeteor ➔ publish null -> userId: null , arguments:  {} 
[34mI20180720-19:21:07.727(0) [34mMeteor ➔ method livechat:loginByToken -> userId: null , arguments:  { '0': 'iNxLAskEXR8Zayb2X' } 
[34mI20180720-19:21:07.729(0) [34mMeteor ➔ method livechat:getInitialData -> userId: null , arguments:  { '0': 'iNxLAskEXR8Zayb2X' } 
[34mI20180720-19:21:07.790(0) [34mMeteor ➔ method livechat:pageVisited -> userId: null , arguments:  { '0': 'iNxLAskEXR8Zayb2X',   '1': null,   '2':     { change: 'url',      location:        { href: 'https://example.com/livesupport/',         ancestorOrigins: {},         origin: 'https://example.com',         protocol: 'https:',         host: 'example.com',         hostname: example.com',         port: '',         pathname: '/livesupport/',         search: '',         hash: '' },      title: 'ExampleLiveSupport' } } 
[34mI20180720-19:21:07.791(0) Exception while invoking method 'livechat:pageVisited' TypeError: Cannot read property '_id' of undefined
at Object.createNavigationHistoryWithRoomIdMessageAndUser (/snap/rocketchat-server/1311/programs/server/packages/rocketchat_lib.js:8218:19)
at Object.savePageHistory (/snap/rocketchat-server/1311/programs/server/packages/rocketchat_livechat.js:4259:41)
at MethodInvocation.livechat:pageVisited (/snap/rocketchat-server/1311/programs/server/packages/rocketchat_livechat.js:1176:25)
at MethodInvocation.methodsMap.(anonymous function) (/snap/rocketchat-server/1311/programs/server/packages/rocketchat_lib.js:2504:36)
at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
at maybeAuditArgumentChecks (/snap/rocketchat-server/1311/programs/server/packages/ddp-server.js:1877:12)
at DDP._CurrentMethodInvocation.withValue (/snap/rocketchat-server/1311/programs/server/packages/ddp-server.js:902:126)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
at DDPServer._CurrentWriteFence.withValue (/snap/rocketchat-server/1311/programs/server/packages/ddp-server.js:902:98)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
at Promise (/snap/rocketchat-server/1311/programs/server/packages/ddp-server.js:902:46)
at new Promise (<anonymous>:null:null)
at Session.method (/snap/rocketchat-server/1311/programs/server/packages/ddp-server.js:875:23)
at /snap/rocketchat-server/1311/programs/server/packages/ddp-server.js:754:85
[34mI20180720-19:21:07.793(0) [34mMeteor ➔ method livechat:pageVisited -> userId: null , arguments:  { '0': 'iNxLAskEXR8Zayb2X',   '1': null,   '2':     { change: 'title',      location:        { href: 'https://example.com/livesupport/',         ancestorOrigins: {},         origin: 'https://example.com',         protocol: 'https:',         host: 'example.com',         hostname: 'example.com',         port: '',         pathname: '/livesupport/',         search: '',         hash: '' },      title: 'Example LiveSupport' } } 
```

**Comment by Hativ** [comment]
The LiveChat is now working (setting thing). But the error still appears, probably it has to do with something else.

**Comment by renatobecker** [comment]
hi @Hativ!
Please make sure you have a user with `_id = 'rocket.cat'` in the` users` collection.

**Comment by Hativ** [comment]
That could be the issue, because I have deleted the default user.

How could I connect to the rocket chat database when installed via snap? Using `mongo` it doesn't show  the rocketchat database, only the test database.

**Comment by renatobecker** [comment]
@Hativ, when you restart the server, the `rocket.cat` user is recreated.
Thanks.

**Comment by Hativ** [comment]
Thank you, that's it.
