### ISSUE TITLE
Outgoing Webhook fails with SELF_SIGNED_CERT_IN_CHAIN because of corporate CA cert in snap installation

### ISSUE THREAD

**Issue by mydoghasworms** [RocketChat/Rocket.Chat#11546]
### Description:

Requests for a new outgoing Webhook we created fails with SELF_SIGNED_CERT_IN_CHAIN in the log.

Our rocket chat installation is behind a corporate firewall, where the company uses its own CA certificate.

I should be possible with node to use the NODE_EXTRA_CA_CERTS environment variable to point to an extra file containing certificates, to be able to include the corporate CA certificate.

However, because we are using a snap app Rocket.Chat server, there seems to be no opportunity to insert the environment variable anywhere, except perhaps by modifying the environment of the current snap version, but this would be modified when the snap is next updated.

The following forum ~discussion~ monologue refers: https://forums.rocket.chat/t/self-signed-cert-in-chain-from-npm-in-snap-installation/1585

### Steps to reproduce:

This problem is difficult to reproduce, unless you are behind a corporate firewall where the company inserts its own CA root certificate into all requests.

In that case, an outgoing webhook that makes a request to an HTTPS resource fails.

### Expected behavior:

It should be possible to add an additional CA certificate so that the Rocket.Chat node installation trusts this as well.

### Actual behavior:

We have already tried two possibilities for adding the NODE_EXTRA_CA_CERTS, but both involve modifying the root user's environment which is presumably disregarded in the snap's execution environment.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.3
- Operating System: Ubuntu (Linux_x64)
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: 8.11.3
- MongoDB Version:  3.2.7

### Relevant logs:
```
[34mI20180723-07:21:46.012(2) rocketchat_logger rocketchat_logger.js:278 [31mIntegrations ➔ Outgoing WebHook.error Error for the Integration "JIRA" to [CENSORED] is: 
[34mI20180723-07:21:46.013(2) rocketchat_logger rocketchat_logger.js:278 [31mIntegrations ➔ Outgoing WebHook.error { Error: self signed certificate in certificate chain     at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)     at emitNone (events.js:106:13)     at TLSSocket.emit (events.js:208:7)     at TLSSocket._finishInit (_tls_wrap.js:639:8)     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)  code: 'SELF_SIGNED_CERT_IN_CHAIN' } 
```

**Comment by mydoghasworms** [comment]
Where would the best place be to fix this? After some investigation, I thought that maybe one could set the `NODE_EXTRA_CA_CERTS` environment variable directly for the snap, but the problem is that it applies only to the current snap and the change will be lost when the snap is upgraded.

So where is the right place to fix this? In Node? In Meteor? Or in Rocket Chat? And how?

**Comment by mydoghasworms** [comment]
@geekgonecrazy I made mention of this on the forum, but on the Snapcraft forum, there was a suggestion that possibly settings like these can be made to work with snap config. (So presumably it can be set with `snap set`). Could you please take a look at https://forum.snapcraft.io/t/declaratively-defining-environment-variables/175/27 and advise?
There is also a possible workaround given which I will try and provide feedback if that works.

**Comment by mydoghasworms** [comment]
I have tried the option as suggested in the Snapcraft forum, to add the NODE_EXTRA_CA_CERTS environment variable to the process.
I can confirm that adding the environment variable works by issuing `sudo cat /proc/[process]/environ` for both processes that I see when I issue `sudo service snap.rocketchat-server.rocketchat-server status`.
However, the environment variable is ignored.
Is it possible that Meteor or Rocket.Chat is perhaps making calls in a way that is ignoring this setting to Node?

**Comment by mydoghasworms** [comment]
And in other words, it's probably not a snap-specific problem?

**Comment by mydoghasworms** [comment]
Based on the following issue from Meteor:
https://github.com/meteor/meteor/issues/7499
I also tried using the `CAFILE` environment variable, but that also did not solve it.

**Comment by azeton** [comment]
I stumbled upon this when I was facing the exact same Issue and I seem to have found a solution to this.
I know this is from 3 years ago but maybe someone finds this helpful.

What I have done to fix this is:

- Create a .env file in the Snap Environment, like /var/snap/rocketchat-server/common/proxy.env
- Insert your Proxy Environment Data
- In that env File I also declared the NODE_EXTRA_CA_CERTS Environment Variable
- You have to make sure that your corperate CA Cert is within /var/snap/rocketchat-server/current/

So my File (/var/snap/rocketchat-server/common/proxy.env) looks like this:

HTTP_PROXY=http://YOUR_PROXY_IP:PORT/
HTTPS_PROXY=http://YOUR_PROXY_IP:PORT/
NODE_EXTRA_CA_CERTS=/var/snap/rocketchat-server/current/YOUR-CA-CERTIFICATE.crt


After that restart the rocketchat service like so: systemctl restart snap.rocketchat-server.rocketchat-server.service

Now my Marketplace is working and embedded Images are loading too. No entries of self-signed CA in the logs.
