### ISSUE TITLE
Slack invalid import file format

### ISSUE THREAD

**Issue by davidberardozzi** [RocketChat/Rocket.Chat#11571]
### Description:

Rocket.chat is stating that the file format is invalid for a freshly created slack export when trying to import it.

### Steps to reproduce:

Follow the import procedure for slack import:
1. Go to https://[your_app].slack.com/services/export
2. Click on Start Export
3. Wait until your download is ready and download it (it will be a .zip file)
4. Go to https://[your_rocketchat]/admin/import/prepare/slack
5. Choose your downloaded .zip file and wait until Rocket.Chat can read it (it can take a few minutes, 
    depending on the size of your Slack export)
6. Deselect any items you don’t want to import
7. At the top of the page, click on Start Importing

It fails at step 5

### Expected behavior:

Should access to step 6

### Actual behavior:

![capture d ecran de 2018-07-26 11-02-21](https://user-images.githubusercontent.com/12343017/43252698-7255e186-90c3-11e8-954b-548f8c03a890.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.67.0 (same with last 0.66)
- Operating System: Kubernetes official docker image
- Deployment Method: Kubernetes manifest
- Number of Running Instances: 1
- DB Replicaset Oplog: True
- NodeJS Version: 8.11.3 - x64
- MongoDB Version: v3.6.4

### Additional context

Using google storage as storage backend
On previous first tests (simplifed env generated with helm chart) with 1 mongodb host, GridFs and oplog disbaled, I was able to import slack files with minimal efforts (removing special characters from channel's names). In every cases I was able to get to step 5

### Relevant logs:

```
Exception while invoking method 'prepareImport' TypeError: Cannot read property 'prepare' of undefined
    at MethodInvocation.prepareImport (/app/bundle/programs/server/packages/rocketchat_importer.js:806:39)
    at MethodInvocation.methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:2494:36)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1877:12)
    at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (/app/bundle/programs/server/packages/ddp-server.js:902:46)
    at new Promise (&lt;anonymous&gt;:null:null)
    at Session.method (/app/bundle/programs/server/packages/ddp-server.js:875:23)
    at /app/bundle/programs/server/packages/ddp-server.js:754:85
```

**Comment by davidberardozzi** [comment]
Ok solved, the problem was due to mongodb being configured with tls and closing abruptly the connexion before end of process for an uknown reason (was tring to use promising https://www.kubestack.com/catalog/mongodb). I am using know bitnami mongodb helm chart without tls and it is working again.

**Comment by davidberardozzi** [comment]
Sorry I thought it was ok and I would just have to deal with renaming channels using special characters after I am still getting erratic errors at import step still giving "invalid file format" message with this log trace and a fresh slack export:

```
Exception while invoking method 'prepareImport' TypeError: Cannot read property '_id' of undefined
    at SlackImporter.updateRecord (/app/bundle/programs/server/packages/rocketchat_importer.js:365:30)
    at SlackImporter.updateProgress (/app/bundle/programs/server/packages/rocketchat_importer.js:313:10)
    at SlackImporter.prepare (/app/bundle/programs/server/packages/rocketchat_importer.js:234:10)
    at SlackImporter.prepare (/app/bundle/programs/server/packages/rocketchat_importer-slack.js:104:11)
    at MethodInvocation.prepareImport (/app/bundle/programs/server/packages/rocketchat_importer.js:806:39)
    at MethodInvocation.methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:2506:36)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1877:12)
    at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (/app/bundle/programs/server/packages/ddp-server.js:902:46)
    at new Promise (&lt;anonymous&gt;:null:null)
    at Session.method (/app/bundle/programs/server/packages/ddp-server.js:875:23)
    at /app/bundle/programs/server/packages/ddp-server.js:754:85
```

**Comment by davidberardozzi** [comment]
Restarting again from scratch, removing all special character in channels directly from Slack finally did the trick.

Thank you for this masterpiece.
