### ISSUE TITLE
Upload problems with multiple instances

### ISSUE THREAD

**Issue by abuethe** [RocketChat/Rocket.Chat#11871]
When uploading there's a 50/50 chance that the upload hangs at 0% for a while (e.g. a minute) until starting completion. This problem seems to occur only with multiple instances and an nginx running on a different machine. This might be related to #7706, I guess.

My setup is as follows:
* Two instances on one backend system
  * Rocket.Chat Version: 0.66.0
  * NodeJS Version: 8.11.3 - x64
  * Platform: linux
  * ReplicaSet OpLog: Enabled
  * Commit Hash: 5aa08cba32
* Listening on ports 3000/3001 on external interface `ens160`
* Nginx webserver v1.12.2 on frontend system in DMZ

Debug log output:
```
Aug 16 14:21:37 ************* rocketchat01: { name: 'Clipboard - August 16, 2018 2:21 PM',
Aug 16 14:21:37 ************* rocketchat01: size: 23174,
Aug 16 14:21:37 ************* rocketchat01: type: 'image/png',
Aug 16 14:21:37 ************* rocketchat01: rid: '**********************************************',
Aug 16 14:21:37 ************* rocketchat01: description: 'Another try.',
Aug 16 14:21:37 ************* rocketchat01: store: 'Uploads' } }
Aug 16 14:21:37 ************* rocketchat02: #033[34mUploadProxy ➔ debug#033[39m Upload URL: /ufs/FileSystem:Uploads/***********************?token=*************&progress=0.7069992232674549
Aug 16 14:21:37 ************* rocketchat02: #033[34mUploadProxy ➔ debug#033[39m Wrong instance, proxing to: localhost:3000
Aug 16 14:21:37 ************* rocketchat02: Exception in callback of async function: Error: connect ECONNREFUSED 127.0.0.1:3000
Aug 16 14:21:37 ************* rocketchat02: at Object._errnoException (util.js:992:11)
Aug 16 14:21:37 ************* rocketchat02: at _exceptionWithHostPort (util.js:1014:20)
Aug 16 14:21:37 ************* rocketchat02: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
Aug 16 14:21:37 ************* rocketchat02: [Thu Aug 16 2018 14:21:37 GMT+0200 (CEST)] ERROR Error: connect ECONNREFUSED 127.0.0.1:3000
Aug 16 14:21:37 ************* rocketchat02: at Object._errnoException (util.js:992:11)
Aug 16 14:21:37 ************* rocketchat02: at _exceptionWithHostPort (util.js:1014:20)
Aug 16 14:21:37 ************* rocketchat02: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
Aug 16 14:21:37 ************* rocketchat02: Exception in callback of async function: Error: socket hang up
Aug 16 14:21:37 ************* rocketchat02: at createHangUpError (_http_client.js:331:15)
Aug 16 14:21:37 ************* rocketchat02: at Socket.socketCloseListener (_http_client.js:363:23)
Aug 16 14:21:37 ************* rocketchat02: at emitOne (events.js:121:20)
Aug 16 14:21:37 ************* rocketchat02: at Socket.emit (events.js:211:7)
Aug 16 14:21:37 ************* rocketchat02: at TCP._handle.close [as _onclose] (net.js:557:12)
Aug 16 14:21:37 ************* rocketchat02: [Thu Aug 16 2018 14:21:37 GMT+0200 (CEST)] ERROR Error: socket hang up
Aug 16 14:21:37 ************* rocketchat02: at createHangUpError (_http_client.js:331:15)
Aug 16 14:21:37 ************* rocketchat02: at Socket.socketCloseListener (_http_client.js:363:23)
Aug 16 14:21:37 ************* rocketchat02: at emitOne (events.js:121:20)
Aug 16 14:21:37 ************* rocketchat02: at Socket.emit (events.js:211:7)
Aug 16 14:21:37 ************* rocketchat02: at TCP._handle.close [as _onclose] (net.js:557:12)
```

I tried adding the `INSTANCE_IP` (same as `BIND_IP') to the systemd unit but it didn't change anything.
```
Environment="INSTANCE_IP=10.xx.xx.xx"
```

Do you have any idea how to mitigate my upload problems?

For reference the original systemd unit:
```
$ cat /etc/systemd/system/rocketchat02.service
[Unit]
Description=The Rocket.Chat server
After=network.target mongod.target

[Service]
Type=simple
WorkingDirectory=/opt/rocket
User=rocket
Group=rocket
ExecStart=/usr/local/bin/node main.js
Restart=always
SyslogIdentifier=rocketchat02
Environment="BIND_IP=10.xx.xx.xx"
Environment="ROOT_URL=https://****************"
Environment="PORT=3001"
Environment="MONGO_URL=mongodb://localhost:27017/rocketchat"
Environment="MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs0"
LimitNOFILE=10240
LimitNPROC=8192
```

**Comment by AmShaegar13** [comment]
You must not set BIND_IP like this. `BIND_IP=10.xx.xx.xx` means your instance can only be accessed using `10.xx.xx.xx`. Rocket.Chat detects if two instances run on the same host and changes the IP to localhost/127.0.0.1.
