### ISSUE TITLE
Yet another Slack import problem

### ISSUE THREAD

**Issue by Crazy-Hopper** [RocketChat/Rocket.Chat#12075]
Hello, I've installed rocket chat into a kubernetes cluster, v0.69.2 git-7df981810510 and tried to import the Slack dump archive, both official and the one made with zach-snell/slack-export tool.

During the import attempts I was running 3 replicas of mongo, with OpLog enabled and only 1 instance of RocketChat.

Both attempts fail similarly:

```
rocketchat_logger rocketchat_logger.js:278 Slack Importer ➔ error TypeError: Cannot read property '_id' of undefined
    at msgs.messages.forEach.message (/app/bundle/programs/server/packages/rocketchat_importer-slack.js:583:35)
    at Array.forEach (<anonymous>:null:null)
    at Object.keys.forEach.date (/app/bundle/programs/server/packages/rocketchat_importer-slack.js:458:29)
    at Array.forEach (<anonymous>:null:null)
    at DDPCommon.MethodInvocation.Meteor.runAsUser (/app/bundle/programs/server/packages/rocketchat_importer-slack.js:456:38)
    at packages/dispatch_run-as-user.js:211:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
    at Object.keys.forEach.channel (/app/bundle/programs/server/packages/rocketchat_importer-slack.js:442:18)
    at Array.forEach (<anonymous>:null:null)
    at Meteor.defer (/app/bundle/programs/server/packages/rocketchat_importer-slack.js:440:36)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at packages/meteor.js:502:25
    at runWithEnvironment (packages/meteor.js:1238:24)
```

Could you please let me know if any other info might be of help here ?

**Comment by Crazy-Hopper** [comment]
The bad thing is that after that trick i have the following exception upon each startup:
`WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: rocketchat.rocketchat_room index: name_1 dup key: { : \"general\" }","op":{"_id":"GENERAL","ts":"2018-09-16T21:11:04.409Z","t":"c","name":"general","usernames":[],"msgs":0,"usersCount":0,"default":true,"_updatedAt":"2018-09-16T21:11:04.409Z"}})`

I guess I will have to change something in mongo to make rocketchat recognize the 'custom' general channel I created. But I need help here please.

**Comment by Crazy-Hopper** [comment]
Meanwhile I've made the same workaround as in this comment: https://github.com/RocketChat/Rocket.Chat/issues/3870#issuecomment-244053695
