### ISSUE TITLE
iOS App cannot upload images to channels

### ISSUE THREAD

**Issue by zenjabba** [RocketChat/Rocket.Chat#12096]
### Description:

When trying to upload a jpeg image through RocketChat IOS app, a incorrect error comes up

### Steps to reproduce:

Open iOS app, and try to upload picture within a channel

### Expected behavior:

Picture to be uploaded? 

### Actual behavior:
![img_8134](https://user-images.githubusercontent.com/679864/45702887-e808ec00-bb40-11e8-9ed4-250d4502d338.PNG)

![img_8135](https://user-images.githubusercontent.com/679864/45702868-df181a80-bb40-11e8-9709-107731cfcce8.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.5
- Operating System: Ubuntu 16.04 LTS
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled 
- NodeJS Version: v8.11.3
- MongoDB Version: 

### Relevant logs:

[34mAPI ➔ debug post rooms.upload/:rid threw an error: Error: File size is too small (min = 1) [file-too-small]     at Filter.check (/app/bundle/programs/server/packages/jalik_ufs.js:577:13)     at FileUploadClass.insert (/app/bundle/programs/server/packages/rocketchat_file-upload.js:650:14)     at packages/meteor.js:258:21     at DDPCommon.MethodInvocation.Meteor.runAsUser (/app/bundle/programs/server/packages/rocketchat_api.js:2276:78)     at packages/dispatch_run-as-user.js:211:14     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)     at Object.post (/app/bundle/programs/server/packages/rocketchat_api.js:2275:12)     at Object._internalRouteActionHandler [as action] (/app/bundle/programs/server/packages/rocketchat_api.js:194:37)     at Route.share.Route.Route._callEndpoint (/app/bundle/programs/server/packages/nimble_restivus.js:347:32)     at /app/bundle/programs/server/packages/nimble_restivus.js:236:33     at packages/simple_json-routes.js:98:9

**Comment by zenjabba** [comment]
MongoDB Version mongo:3.0 installed via docker

**Comment by kaiiiiiiiii** [comment]
Wrong repository mate :)

https://github.com/RocketChat/Rocket.Chat.iOS

// CC: @TwizzyDizzy

**Comment by zenjabba** [comment]
DOH!
