### ISSUE TITLE
Save user preferences - Internal Server Error

### ISSUE THREAD

**Issue by flam22** [RocketChat/Rocket.Chat#12163]
### Description:

After updating to version 0.70.0-rc.1 if a user attempts to save their preferences an 'Internal Server Error' is produced.

### Steps to reproduce:

1. Update to version 0.70.0-rc.1
2. Click on My Account
3. Make any change (optional).
4. Click on 'Save changes'

### Expected behavior:

Any changes to be successfully saved.

### Actual behavior:

'Internal Server Error' returned.

### Server Setup Information:

- Version of Rocket.Chat Server:  0.70.0-rc.1
- Operating System: linux
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.9.4
- MongoDB Version: 3.4.16

### Relevant logs:

`Exception while invoking method 'saveUserPreferences' TypeError: Cannot read property 'clockMode' of undefined
    at ModelUsers.setPreferences (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:11608:56)
    at MethodInvocation.saveUserPreferences (/var/www/rocket.chat/bundle/programs/server/app/app.js:11864:29)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at MethodInvocation.methodsMap.(anonymous function) (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:2503:36)
    at maybeAuditArgumentChecks (/var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:1877:12)
    at DDP._CurrentMethodInvocation.withValue (/var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:902:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (/var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:902:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (/var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:902:46)
    at new Promise (<anonymous>:null:null)
    at Session.method (/var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:875:23)
    at /var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:754:85
`

**Comment by flam22** [comment]
I didn't need to make any change. Just clicking on 'Save Changes' would trigger the error.

It has now been fixed in rc.2 - refer to #12170

**Comment by geekgonecrazy** [comment]
Perfect! That's exactly why I couldn't reproduce. Thanks!
