### ISSUE TITLE
Users getting session timeout and don't recieve messages/sent messages are greyed out

### ISSUE THREAD

**Issue by maik28** [RocketChat/Rocket.Chat#12206]
### Description:

Diverse users are getting in different times a session timeout although expiration day is set to 90 days. 
After reconnecting there are several problems with sending and receiving messages in direct message and channels for these users. Occurs in browser as well as in client. 

### Steps to reproduce:

1. User A gets disconnected and logs in again.
2. User A sends a message to any User B.
3. The sent message is greyed out for user A/User B receives message ordinarily.
4. Now if user B sends a message to user A, he can see "User B is typing" and he gets a new message notification, but there are no new messages visible for User A in chat window. 
5. Refreshing browser cache or relogin solves this bug. 

### Expected behavior:

- Session timeout should apply after 90 days. 
- Messages should be sent and received ordinarily after session timeout. 

### Actual behavior:

- Users getting timeout several times in weeks. 
- Sent messages are buggy after session timeout.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: No
- NodeJS Version: 8.11.3
- MongoDB Version: 3.2.11

### Additional context

In browser console for the greyed out message: 
`id=123xyz“ class=“message background-transparent-dark-hover own temp“`

### Relevant logs:

Couldn't lookup logs yet.

**Comment by reetp** [comment]
Can you please test on latest 0.70.x please.
You probably need to post some logs as well.

**Comment by iostat** [comment]
I've actually been noticing the same issue on our install. We have session timeout set to 90 days, however sometimes our users get logged out or have sent messages grayed out until they refresh and have to log in again.

Found a bunch of this error in the instance logs, might be relevant?
```
I20190227-14:46:26.455(0) Exception in onLogin callback:
 TypeError: Cannot redefine property: loginAt
     at Function.defineProperty (<anonymous>)
     at Object.keys.forEach.p (packages/rocketchat:statistics/server/lib/SAUMonitor.js:279:12)
     at Array.forEach (<anonymous>)     at SAUMonitorClass._updateConnectionInfo (packages/rocketchat:statistics/server/lib/SAUMonitor.js:278:22)
     at Accounts.onLogin.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:120:9)
     at packages/callback-hook/hook.js:130:22
     at _onLoginHook.each.callback (packages/accounts-base/accounts_server.js:178:7)
     at Hook.each (packages/callback-hook/hook.js:108:15)
     at AccountsServer._successfulLogin (packages/accounts-base/accounts_server.js:177:23)
     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:350:12)
     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)
     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
     at Promise (packages/ddp-server/livedata_server.js:715:46)
     at new Promise (<anonymous>)
     at Session.method (packages/ddp-server/livedata_server.js:689:23)
     at packages/ddp-server/livedata_server.js:559:43 
```

**Comment by iostat** [comment]
Also saw this pop up numerous times before that `loginAt` exception. Probably also relevant given that this sounds like a DDP problem?:
```
I20190223-01:20:33.489(0) Exception in handling DDP reset:
 { MongoError: not master and slaveOk=false
     at queryCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)
     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
     at _combinedTickCallback (internal/process/next_tick.js:131:7)
     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
     at Promise.asyncApply (packages/mongo/mongo_driver.js:1042:14)
     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1091:12)
     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1105:22)
     at SynchronousCursor.map (packages/mongo/mongo_driver.js:1115:10)
     at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1139:17)
     at Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:887:44)
     at MongoConnection.findOne (packages/mongo/mongo_driver.js:794:56)
     at Object.<anonymous> (packages/matb33_collection-hooks.js:819:16)
     at Object.collection.(anonymous function) [as findOne] (packages/matb33_collection-hooks.js:146:21)
     at ns.Collection.findOne (packages/mongo/collection.js:356:29)
     at authorizeConnection (server/stream/streamBroadcast.js:41:38)
     at Connection.connections.(anonymous function).onReconnect (server/stream/streamBroadcast.js:95:12)
     at Connection._callOnReconnectAndSendAppropriateOutstandingMethods (packages/ddp-client/common/livedata_connection.js:1563:30)
     at Connection.onReset (packages/ddp-client/common/livedata_connection.js:1748:10)
     at runWithEnvironment (packages/meteor.js:1356:24)
     at packages/meteor.js:1369:14
     at forEachCallback.callback (packages/socket-stream-client/node.js:83:7)
     at Array.forEach (<anonymous>)
     at ClientStream.forEachCallback (packages/socket-stream-client/common.js:30:31)
     at ClientStream._onConnect (packages/socket-stream-client/node.js:82:10)
     at client.on.Meteor.bindEnvironment (packages/socket-stream-client/node.js:158:21)
     at runWithEnvironment (packages/meteor.js:1356:24)
   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1550884829 },
   ok: 0,
   errmsg: 'not master and slaveOk=false',
   code: 13435,
   codeName: 'NotMasterNoSlaveOk',
   '$clusterTime':     { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1550884829 },      signature: { hash: [Object], keyId: 0 } },
   name: 'MongoError',
   [Symbol(mongoErrorContextSymbol)]: {}
} 
```

**Comment by joshmartintv** [comment]
We're also having the same issue, but we don't have any exceptions in our logs.

**Comment by dkoo761** [comment]
Also having the same issue but only when using the mobile web version on my Android phone. When it happens I see this in the logs:

`Exception while invoking method loadMissedMessages Error: Invalid user [error-invalid-user]`

That exception is thrown when Meteor.userId() is undefined, so it might just be a consequence of the logout and not actually related to it or part of the cause.
