### ISSUE TITLE
rocketchat 0.70.0 livestream broken?

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#12201]
### Description:

Tried to configure livestream for a channel but got Error 400 in return.

### Steps to reproduce:

1. Enable livestream in settings
2. Configure livestream in channel
3. Error 400

### Expected behavior:

Successfully have a livestream running.

### Actual behavior:

Error 400.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.0
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: no
- NodeJS Version: 8.12.0
- MongoDB Version: 3.6

### Additional context

```
Exception while invoking method 'saveRoomSettings' Error: Match error: Unknown key in field id
    at check (/opt/rocketchat-0.70.0/programs/server/packages/check.js:68:17)
    at EventEmitter.RocketChat.saveStreamingOptions (/opt/rocketchat-0.70.0/programs/server/packages/rocketchat_livestream.js:62:3)
    at Object.keys.forEach.setting (/opt/rocketchat-0.70.0/programs/server/packages/rocketchat_channel-settings.js:467:22)
    at Array.forEach (<anonymous>:null:null)
    at MethodInvocation.saveRoomSettings (/opt/rocketchat-0.70.0/programs/server/packages/rocketchat_channel-settings.js:412:27)
    at MethodInvocation.methodsMap.(anonymous function) (/opt/rocketchat-0.70.0/programs/server/packages/rocketchat_lib.js:2518:36)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at maybeAuditArgumentChecks (/opt/rocketchat-0.70.0/programs/server/packages/ddp-server.js:1877:12)
    at DDP._CurrentMethodInvocation.withValue (/opt/rocketchat-0.70.0/programs/server/packages/ddp-server.js:902:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (/opt/rocketchat-0.70.0/programs/server/packages/ddp-server.js:902:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (/opt/rocketchat-0.70.0/programs/server/packages/ddp-server.js:902:46)
    at new Promise (<anonymous>:null:null)
    at Session.method (/opt/rocketchat-0.70.0/programs/server/packages/ddp-server.js:875:23)
    at /opt/rocketchat-0.70.0/programs/server/packages/ddp-server.js:754:85
```

thanks and cheers

**Comment by stephane-** [comment]
Same bug here, but have an other log : 
```
Exception while invoking method 'saveRoomSettings' Error: Match error: Expected string, got boolean in field isAudioOnly     at check (/home/disk1/storage/rocketchat/Rocket.Chat/programs/server/packages/check.js:68:17)     at EventEmitter.RocketChat.saveStreamingOptions (/home/disk1/storage/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_livestream.js:62:3)     at Object.keys.forEach.setting (/home/disk1/storage/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_channel-settings.js:467:22)     at Array.forEach (<anonymous>:null:null)     at MethodInvocation.saveRoomSettings (/home/disk1/storage/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_channel-settings.js:412:27)     at MethodInvocation.methodsMap.(anonymous function) (/home/disk1/storage/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_lib.js:2518:36)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/home/disk1/storage/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/home/disk1/storage/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/home/disk1/storage/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/home/disk1/storage/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/home/disk1/storage/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:875:23)     at /home/disk1/storage/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:754:85 
```

**Comment by himpierre** [comment]
Still broken in 0.70.1.

**Comment by saschafoerster** [comment]
Same bug after playing around with live-streaming and broadcasting... 
0.70.4
```
[34mI20181015-21:49:36.935(0) Exception while invoking method 'saveRoomSettings' Error: Match error: Unknown key in field id     at check (/app/bundle/programs/server/packages/check.js:68:17)     at EventEmitter.RocketChat.saveStreamingOptions (/app/bundle/programs/server/packages/rocketchat_livestream.js:62:3)     at Object.keys.forEach.setting (/app/bundle/programs/server/packages/rocketchat_channel-settings.js:467:22)     at Array.forEach (<anonymous>:null:null)     at MethodInvocation.saveRoomSettings (/app/bundle/programs/server/packages/rocketchat_channel-settings.js:412:27)     at MethodInvocation.methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:2518:36)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/app/bundle/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/app/bundle/programs/server/packages/ddp-server.js:875:23)     at /app/bundle/programs/server/packages/ddp-server.js:754:85  
[34mI20181015-21:49:36.936(0) Sanitized and reported to the client as: Match failed [400] 
[34mI20181015-21:49:36.938(0) undefined undefined 
```

**Comment by saschafoerster** [comment]
Probably same error as in #12060
