### ISSUE TITLE
can't upload files larger than 10k

### ISSUE THREAD

**Issue by MikasaAkerman** [RocketChat/Rocket.Chat#12217]
i got this error message when i try to upload a file larger than 10k.
`Error: FileNotFound: no file with id KfkcvaDfYdm3QEDGa found
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:190:25
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1215:18
    at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:120:56)
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1252:5
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
`
anyone can help me?

**Comment by MikasaAkerman** [comment]
ADD: I can upload from android client, but can't upload from web and windows client. 
why?

**Comment by MikasaAkerman** [comment]
ok, it is caused by my nginx configuration.
