### ISSUE TITLE
Error in oplog callback MinimongoError: Invalid modifier specified $v

### ISSUE THREAD

**Issue by nlapshin** [RocketChat/Rocket.Chat#12352]
Hello.

I see in the logs of the following:

```
Error in oplog callback MinimongoError: Invalid modifier specified $v
    at MinimongoError (/var/www/chat/bundle/programs/server/packages/minimongo.js:1435:17)
    at Object.keys.forEach.operator (/var/www/chat/bundle/programs/server/packages/minimongo.js:3361:15)
    at Array.forEach (<anonymous>:null:null)
    at Function.LocalCollection._modify (/var/www/chat/bundle/programs/server/packages/minimongo.js:3354:27)
    at Matcher.Minimongo.Matcher.canBecomeTrueByModifier (/var/www/chat/bundle/programs/server/packages/minimongo.js:167:21)
    at /var/www/chat/bundle/programs/server/packages/mongo.js:2858:59
    at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
    at OplogObserveDriver._handleOplogEntrySteadyOrFetching (/var/www/chat/bundle/programs/server/packages/mongo.js:2798:12)
    at /var/www/chat/bundle/programs/server/packages/mongo.js:2369:18
    at /var/www/chat/bundle/programs/server/packages/mongo.js:2267:9
    at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
    at /var/www/chat/bundle/programs/server/packages/mongo.js:2356:14
    at /var/www/chat/bundle/programs/server/packages/mongo.js:1475:7
    at runWithEnvironment (packages/meteor.js:1240:24)
    at Object.callback (packages/meteor.js:1253:14)
    at /var/www/chat/bundle/programs/server/packages/ddp-server.js:2130:36
    at Array.forEach (<anonymous>:null:null)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at DDPServer._Crossbar.fire (/var/www/chat/bundle/programs/server/packages/ddp-server.js:2128:7)
    at /var/www/chat/bundle/programs/server/packages/mongo.js:1700:26
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at packages/meteor.js:502:25
    at runWithEnvironment (packages/meteor.js:1240:24)
```
Rocket.Chat version 0.62.0
OS Ubuntu 16.04.2 LTS
Instances running with forever-server
Number of running instances - 6.
NodeJS 8.93
Mongodb version v3.6.7

Thanks in advance!

**Comment by reetp** [comment]
You are running several versions and months out of date.

Please test on latest 0.70.x

Also note you have a DPP server there too. Can you explain a bit more about your setup?

**Comment by KevLehman** [comment]
oplog is no longer in use. thx
