### ISSUE TITLE
ReferenceError: TAPi18n is not defined

### ISSUE THREAD

**Issue by phillipplum** [RocketChat/Rocket.Chat#12454]
Hello, my latest bug report #12212 is not fixed for me in the latest version 0.71.0.

**Steps to reproduce:**
docker-compose pull rocketchat
docker-compose down
docker-compose up -d

**Server Setup Information:**
Version of Rocket.Chat Server: 0.71.0
Operating System: Debian
Deployment Method: Docker
Number of Running Instances: 1

My logs say after a pull and restart:

```
Exception in callback of async function: ReferenceError: TAPi18n is not defined
    at str.replace (packages/rocketchat:mailer/server/api.js:14:110)
    at String.replace (<anonymous>)
    at translate (packages/rocketchat:mailer/server/api.js:14:39)
    at replace (packages/rocketchat:mailer/server/api.js:29:92)
    at value (packages/rocketchat:mailer/server/api.js:68:19)
    at Settings.get (packages/rocketchat:mailer/server/api.js:46:3)
    at Object.get (packages/rocketchat:lib/lib/settings.js:32:43)
    at getTemplate (packages/rocketchat:mailer/server/api.js:44:11)
    at Module.setSettings (packages/rocketchat:mailer/server/api.js:67:2)
    at index.js (packages/rocketchat:lib/startup/index.js:3:8)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /app/bundle/programs/server/packages/rocketchat_lib.js:18387:1
    at /app/bundle/programs/server/packages/rocketchat_lib.js:18396:3
    at /app/bundle/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /app/bundle/programs/server/boot.js:220:19
    at /app/bundle/programs/server/boot.js:471:5
    at Function.run (/app/bundle/programs/server/profile.js:510:12)
    at /app/bundle/programs/server/boot.js:470:11
Updating process.env.MAIL_URL
Starting Email Intercepter...
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook_id
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook_callback_url
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Google
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Google_id
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Google_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Google_callback_url
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Github
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Github_id
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Github_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Github_callback_url
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin_id
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin_callback_url
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Meteor
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Meteor_id
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Meteor_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Meteor_callback_url
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter_id
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter_callback_url
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Proxy_host
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Proxy_services
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin_URL
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin_id
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin_login_style
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin_button_label_text
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin_button_label_color
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin_button_color
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Drupal
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Drupal_id
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Drupal_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Drupal_callback_url
rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise
rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise_id
rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise_callback_url
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Gitlab
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Gitlab_id
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Gitlab_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Gitlab_callback_url
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Tokenpass
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Tokenpass_id
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Tokenpass_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Tokenpass_callback_url
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_id
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_callback_url
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_server_type
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_identity_path
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_identity_token_sent_via
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_token_path
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_authorize_path
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_scope
```

**Comment by tassoevan** [comment]
@MarcosSpessatto Any idea about this? (I link you here because #12467).

**Comment by MarcosSpessatto** [comment]
@tassoevan I think has no connection with this PR, because the PR of the removal of global variables, will only enter the next release (0.72)

**Comment by phillipplum** [comment]
Do someone have an idea for a workaround? Currently we can not do any updates.

**Comment by MarcosSpessatto** [comment]
@phillipplum Did you update the codebase with branch `development`? Because the PR metioned by @tassoevan , has already been merged, and maybe corrected the problem.

**Comment by phillipplum** [comment]
With the new version 0.72.0 now the problem is solved! Thanks.
