### ISSUE TITLE
Video message doesn't upload

### ISSUE THREAD

**Issue by markathomas** [RocketChat/Rocket.Chat#12474]
### Description:

Video messages fail to send to user

### Steps to reproduce:

1. Run rocket as a docker container. 
2. Take a video message and click send. 
3. View error in logs.

### Expected behavior:

video message successfully sent

### Actual behavior:

error in logs. webm video never completes.  error is as follows:
```
rocketchat_1 | Error: FileNotFound: no file with id k6854v2ND2mgWK4qe found
rocketchat_1 |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:190:25
rocketchat_1 |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1215:18
rocketchat_1 |     at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:120:56)
rocketchat_1 |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1252:5
rocketchat_1 |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
rocketchat_1 |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
rocketchat_1 |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.0
- Operating System: Ubuntu 14
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: no
- NodeJS Version: 8.11
- MongoDB Version: 4.0

**Comment by reetp** [comment]
First question. Is it an allowed file type in Admin?
Second. How are you uploading? Browser, app etc?

**Comment by markathomas** [comment]
On Thu, Nov 1, 2018 at 7:56 PM John Crisp <notifications@github.com> wrote:

> First question. Is it an allowed file type in Admin?
> Second. How are you uploading? Browser, app etc?
>
> yesm uploading as an admin  of an allowed file ttype.

upload was in a browser.

**Comment by reetp** [comment]
Just tested on my 0.71.1 docker test Rocket server with a demo webm file from here:

https://www.webmfiles.org/demo-files/

Using local file store. File uploaded via Chromium on *buntu

Uploaded and played without issue.

I think you may have a configuration issue rather than a specific issue with Rocket.

rocketchat_1 | Error: FileNotFound: no file with id k6854v2ND2mgWK4qe found

What type of file storage are you using?

Do you have a proxy in front of Rocket?

**Comment by markathomas** [comment]
GridFS wasnt wproking shoi i tried local flesystem with same results

>

**Comment by reetp** [comment]
Any news on this please or can we close it?

**Comment by arrow003** [comment]
Centos7.6 env, there is the same error output.
MongoDB:4.0
node:12.14.0
npm:6.13.4
RocketChat:3.0.0
```
Jun  3 09:30:34 XXXXXXXX rocketchat: Error: FileNotFound: no file with id RhEbNQTqeHvsN2QDj found
Jun  3 09:30:34 XXXXXXXX rocketchat: at /opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:188:25
Jun  3 09:30:34 XXXXXXXX rocketchat: at /opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:410:17
Jun  3 09:30:34 XXXXXXXX rocketchat: at /opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:398:11
Jun  3 09:30:34 XXXXXXXX rocketchat: at ClientSession.endSession (/opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sessions.js:134:41)
Jun  3 09:30:34 XXXXXXXX rocketchat: at executeCallback (/opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:395:17)
Jun  3 09:30:34 XXXXXXXX rocketchat: at deleteCallback (/opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:349:17)
Jun  3 09:30:34 XXXXXXXX rocketchat: at /opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:364:54
Jun  3 09:30:34 XXXXXXXX rocketchat: at handleCallback (/opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:128:55)
Jun  3 09:30:34 XXXXXXXX rocketchat: at /opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:1259:5
Jun  3 09:30:34 XXXXXXXX rocketchat: at /opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:397:18
Jun  3 09:30:34 XXXXXXXX rocketchat: at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
