### ISSUE TITLE
Cannot add users to a re-created channel

### ISSUE THREAD

**Issue by markathomas** [RocketChat/Rocket.Chat#12482]
### Description:

Attempting to add users to a private channel that was previously deleted and re-created always fails

### Steps to reproduce:

1. create a channel
2. enter channel
3. create one message
4. delete channel
5. re-create channel
6. enter channel
7. attempt to add user(s)

### Expected behavior:

users are invited

### Actual behavior:

Error:
```
Exception while invoking method 'addUsersToRoom' TypeError: Cannot read property 't' of undefined
meteor.js:1005
    at MethodInvocation.addUsersToRoom (/data/git/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:16166:14)
    at MethodInvocation.methodsMap.(anonymous function) (/data/git/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:2518:36)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at maybeAuditArgumentChecks (/data/git/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1877:12)
    at DDP._CurrentMethodInvocation.withValue (/data/git/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:902:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (/data/git/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:902:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (/data/git/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:902:46)
    at new Promise (<anonymous>:null:null)
    at Session.method (/data/git/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:875:23)
    at /data/git/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:754:85
```

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.0 - develop branch
- Operating System: openSUSE Tumbleweed
- Deployment Method: debug via VS Code
- Number of Running Instances: 1
- DB Replicaset Oplog: no
- NodeJS Version: 8
- MongoDB Version: 4

**Comment by markathomas** [comment]
Debugged this and the rid being sent to the `Rooms.findOneById` is the deleted room's rid.  This must be cached somewhere?  If anyone can point me to it I'll fix it.

**Comment by markathomas** [comment]
Even with turning off caching i still cannot add new users to the room. Additionally, the UI for the user who created the room sees deleted messages and subscriptions.

**Comment by markathomas** [comment]
The room cause of this is in `cachedCollection.js` in the code block
```
if (t === 'removed') {
    this.collection.remove(record._id);
    RoomManager.close(record.t + record.name);
}
```
as the record data structure on room remove has neither the `t` or `name` fields thus the room is never removed from `RoomManager`

**Comment by reetp** [comment]
If you have a fix can you post as a PR? More likely to get the devs attention :-)

**Comment by reetp** [comment]
Looks like this might have been fixed in 0.74.1

Can someone try it please

**Comment by MarcosSpessatto** [comment]
@markathomas any news?

**Comment by MartinSchoeler** [comment]
Closing this due to lack of response, if the issue persists, please reopen this. Thanks!
