### ISSUE TITLE
Ldap Filter Broken in 0.70.4

### ISSUE THREAD

**Issue by polevoyserg** [RocketChat/Rocket.Chat#12568]
### Description:

The authentication with rocket chat users not works.
The LDAP connection works fine, and the authentication of the user seems too.
But the result it's always: User not found or incorrect password
What is wrong in my configuration?

In user-search filter i use:
{“filter”: “(&(objectCategory=person)(objectclass=user)(memberOf=CN=team-infrastructure,DC=example,DC=com)(sAMAccountName=#{username}))”, “scope”: “sub”, “userDN”: “chat@example.com”, “password”: “*****”}

I use only user-search filter, without group filter.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4
- Operating System: Ubuntu 16.04
- Deployment Method: snap rocketchat-server
- Number of Running Instances: 1
- LDAP from AWS Directory Service

### Relevant logs:

[34mI20181108-18:36:19.957(3) [34mLDAP ➔ Connection.info LDAP connected 
[34mI20181108-18:36:19.957(3) [34mLDAP ➔ Bind.info Binding UserDN CN=chat,OU=Users,OU=DevOps,OU=Development,OU=Offices,DC=example,DC=com 
[34mI20181108-18:36:19.965(3) [34mLDAP ➔ Search.info Searching user chat 
[34mI20181108-18:36:19.966(3) [34mLDAP ➔ Search.debug searchOptions { filter: '(&({“filter”: “(&(objectCategory=person)(objectclass=user)(memberOf=CN=team-infrastructure,DC=example,DC=com)(sAMAccountName=#{username}))”, “scope”: “sub”, “userDN”: “chat@example.com”, “password”: “*****”})(sAMAccountName=chat))',   scope: 'sub',   sizeLimit: 1000,   paged: { pageSize: 250, pagePause: false } } 
[34mI20181108-18:36:19.967(3) [34mLDAP ➔ Search.debug BaseDN OU=Offices,DC=example,DC=com
[34mI20181108-18:36:19.969(3) [34mLDAP ➔ Search.info Search result count 0 
[34mI20181108-18:36:19.970(3) [34mLDAPHandler ➔ info Search returned 0 record(s) for chat 
[34mI20181108-18:36:19.972(3) rocketchat_logger rocketchat_logger.js:278 [31mLDAPHandler ➔ error Error: User not Found     at MethodInvocation.<anonymous> (/snap/rocketchat-server/1337/programs/server/packages/rocketchat_ldap.js:647:13)     at /snap/rocketchat-server/1337/programs/server/packages/accounts-base.js:876:30     at tryLoginMethod (/snap/rocketchat-server/1337/programs/server/packages/accounts-base.js:702:14)     at AccountsServer.Ap._runLoginHandlers (/snap/rocketchat-server/1337/programs/server/packages/accounts-base.js:875:18)     at AccountsServer.Accounts._runLoginHandlers (/snap/rocketchat-server/1337/programs/server/packages/rocketchat_lib.js:3367:36)     at MethodInvocation.methods.login (/snap/rocketchat-server/1337/programs/server/packages/accounts-base.js:933:27)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/snap/rocketchat-server/1337/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/snap/rocketchat-server/1337/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/snap/rocketchat-server/1337/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/snap/rocketchat-server/1337/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/snap/rocketchat-server/1337/programs/server/packages/ddp-server.js:875:23)     at /snap/rocketchat-server/1337/programs/server/packages/ddp-server.js:754:85  
[34mI20181108-18:36:19.973(3) [34mLDAPHandler ➔ info Fallback to default account system { username: 'chat' } 
[34mI20181108-18:36:20.970(3) [34mLDAP ➔ Search.info Idle 
[34mI20181108-18:36:20.971(3) [34mLDAP ➔ Connection.info Disconecting 
[34mI20181108-18:36:20.973(3) [34mLDAP ➔ Search.info Closed

**Comment by polevoyserg** [comment]
i change user-search filter on next
(&(objectclass=user)(objectcategory=person)(!(useraccountcontrol:1.2.840.113556.1.4.803:=2)))
But now i have a fault (wrong password, but password is correct), see below
[34mI20181109-12:34:39.910(3) [34mLDAP ➔ Connection.info LDAP connected 
[34mI20181109-12:34:39.911(3) [34mLDAP ➔ Bind.info Binding UserDN CN=chat,OU=Users,OU=DevOps,OU=Development,OU=Offices,DC=example,DC=org 
[34mI20181109-12:34:39.919(3) [34mLDAP ➔ Search.info Searching user chat 
[34mI20181109-12:34:39.920(3) [34mLDAP ➔ Search.debug searchOptions { filter: '(&(&(objectclass=user)(objectcategory=person)(!(useraccountcontrol:1.2.840.113556.1.4.803:=2)))(sAMAccountName=chat))',   scope: 'sub',   sizeLimit: 1000,   paged: { pageSize: 250, pagePause: false } } 
[34mI20181109-12:34:39.920(3) [34mLDAP ➔ Search.debug BaseDN DC=example,DC=org 
[34mI20181109-12:34:39.924(3) [34mLDAP ➔ Search.info Search result count 1 
[34mI20181109-12:34:39.925(3) [34mLDAP ➔ Auth.info Authenticating CN=chat,OU=Users,OU=DevOps,OU=Development,OU=Offices,DC=example=org
[34mI20181109-12:34:39.930(3) [34mLDAP ➔ Auth.info Not authenticated CN=chat,OU=Users,OU=DevOps,OU=Development,OU=Offices,DC=example,DC=org 
[34mI20181109-12:34:39.932(3) [34mLDAP ➔ Auth.debug error { InvalidCredentialsError: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1     at messageCallback (/snap/rocketchat-server/1337/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/snap/rocketchat-server/1337/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/snap/rocketchat-server/1337/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)     at Socket.onData (/snap/rocketchat-server/1337/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:597:20)    lde_message: '80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1',   lde_dn: null } 
[34mI20181109-12:34:39.933(3) [34mLDAPHandler ➔ info Wrong password for chat 
[34mI20181109-12:34:39.934(3) [34mLDAPHandler ➔ info Fallback to default account system { username: 'chat' } 
[34mI20181109-12:34:40.930(3) [34mLDAP ➔ Search.info Idle 
[34mI20181109-12:34:40.931(3) [34mLDAP ➔ Connection.info Disconecting 
[34mI20181109-12:34:40.932(3) [34mLDAP ➔ Search.info Closed

**Comment by polevoyserg** [comment]
After that, when i delete local user, and disable option (Find user after login)
My ldap is working!

![image](https://user-images.githubusercontent.com/23742659/48260361-de568300-e423-11e8-95f5-4cfdc01441bc.png)
