### ISSUE TITLE
Rocket chat won't start

### ISSUE THREAD

**Issue by Mebus** [RocketChat/Rocket.Chat#1257]
Hi!

If  I do 

pm2 start pm2-rocket-chat.json

I get this error messge:

<code>
/usr/lib/node_modules/pm2/lib/CLI.js:2508
    return vm.runInNewContext(code, sandbox, filename);
              ^
SyntaxError: Unexpected token )
    at parseConfig (/usr/lib/node_modules/pm2/lib/CLI.js:2508:15)
    at Object.CLI._startJson (/usr/lib/node_modules/pm2/lib/CLI.js:296:15)
    at Object.CLI.start (/usr/lib/node_modules/pm2/lib/CLI.js:100:9)
    at Command.recycle (/usr/lib/node_modules/pm2/bin/pm2:206:11)
    at Command.listener (/usr/lib/node_modules/pm2/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (/usr/lib/node_modules/pm2/node_modules/commander/index.js:610:12)
    at Command.parse (/usr/lib/node_modules/pm2/node_modules/commander/index.js:458:21)
    at beginCommandProcessing (/usr/lib/node_modules/pm2/bin/pm2:117:13)
    at recycle (/usr/lib/node_modules/pm2/bin/pm2:170:7)
</code>

What can I do?

Mebus

**Comment by Mebus** [comment]
Bracket was missing in pm2-rocket-chat.json.
