### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mrjavum** [RocketChat/Rocket.Chat#12587]
### Description:

There is one repeated error in logs (for many versions of RC for many months):
```
{ Error: ENOENT: no such file or directory, stat '/tmp/zipFiles/o7nEL5RgT3Ecm8er4.zip'


  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/tmp/zipFiles/o7nEL5RgT3Ecm8er4.zip' }
```

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4
- Operating System: CentOS 7.4.1708
- Deployment Method: docker (rocketchat/rocket.chat:latest)
- Number of Running Instances: 1
- DB Replicaset Oplog: off
- NodeJS Version: v8.11.3
- MongoDB Version: v3.6.4

Please, help. How to delete this file from db or upload empty file to exclude this error?
I.ve tried to find it in this collections, but with no luck:
```
> db.rocketchat_uploads.find({ _id: "o7nEL5RgT3Ecm8er4" })
> db.rocketchat_uploads.files.find({ _id: "o7nEL5RgT3Ecm8er4" })
> db.rocketchat_uploads.chunks.find({ _id: "o7nEL5RgT3Ecm8er4" })
```

Thanks!

**Comment by UAnton** [comment]
RC 3.7.1

```
Error: ENOENT: no such file or directory, open '/tmp/userData/p5WDcHfv4PmWtQWnR/user.html'
    at Object.openSync (fs.js:440:3)
    at Object.writeFileSync (fs.js:1265:35)
    at startFile (app/user-data-download/server/cronProcessDownloads.js:36:5)
   at generateUserFile (app/user-data-download/server/cronProcessDownloads.js:401:2)
   at app/user-data-download/server/cronProcessDownloads.js:468:4
   at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
 errno: -2,
 syscall: 'open',
 code: 'ENOENT',
 path: '/tmp/userData/p5WDcHfv4PmWtQWnR/user.html'
 }
```

**Comment by northway** [comment]
Rocket.Chat 3.8.0 (Docker)

```
Error: ENOENT: no such file or directory, stat '/tmp/zipFiles/S9uRGJe7apYkcaesu.zip'
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at app/user-data-download/server/cronProcessDownloads.js:292:12
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at app/user-data-download/server/cronProcessDownloads.js:527:10
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/tmp/zipFiles/S9uRGJe7apYkcaesu.zip'
}
```

**Comment by JakobFerdinand** [comment]
I got the same log some seconds after starting.

`Rockte.Chat 3.12.1 (Docker)`

```
Error: ENOENT: no such file or directory, open '/tmp/userData/Fkjq6DhSzWaeRKEFp/user.html'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1362:35)
    at startFile (app/user-data-download/server/cronProcessDownloads.js:36:5)
    at generateUserFile (app/user-data-download/server/cronProcessDownloads.js:404:2)
    at app/user-data-download/server/cronProcessDownloads.js:471:4
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/tmp/userData/Fkjq6DhSzWaeRKEFp/user.html'
}
 ```

**Comment by ankar84** [comment]
@UAnton @JakobFerdinand @northway any solutions for that issue?

**Comment by JakobFerdinand** [comment]
@ankar84 no, sadly I´m still getting the same error...

**Comment by northway** [comment]
Yeah, it's still the same. 😞

**Comment by ICarryTheDustOfAJourney** [comment]
Have that error too on V 4.5.1. on Ubuntu 20.04.4 LTS

**Comment by cebrox** [comment]
Hi. i found this i rocketchat forum.

`Hi,

I am not sure if you have figured this issue out already.

Basically a user in your organization requested to download his data and it was generated and listed in rocketchat_user_data_files table. It creates the file under /tmp/zipFiles and since it is removed from filesystem usually on every boot it is not able to find the zipfile there. To remove this issue from logs you can just remove the document causing the issue from the database.

You can also cleanup rocketchat_export_operations in case there is something queued and not processed because of the first error.

I faced the same problem today and that’s how I was able to sort it out.`

In my case there was a document in the "rocketchat_export_operations".

**Comment by Aleksei-Badyaev** [comment]
@cebrox But where to find this "document" and how to delete it???

**Comment by cebrox** [comment]
@Aleksei-Badyaev A document is called an entry in a mongodb. In my case the entry was in the table "rocketchat_export_operations". But in can also be in "rocketchat_user_data_files".
