### ISSUE TITLE
Build of Rocket.Chat failed

### ISSUE THREAD

**Issue by ChristianKniep** [RocketChat/Rocket.Chat#1263]
Hey there,

I would love to include Rocket.Chat in my QNIBTerminal environment. I put the installation in a Dockerfile, but I get the same error using Ubuntu15 then a couple of weeks back using Ubuntu14.
The docker-repository can be found here: https://github.com/qnib/docker-rocketchat
Just check it out and run `docker build -t qnib/rocketchat .` within the directory to reproduce the error.

```
docker-rocketchat (master) $ docker build --rm -t qnib/rocketchat .
Sending build context to Docker daemon 78.85 kB
Sending build context to Docker daemon
Step 0 : FROM qnib/u-terminal
 ---> 1c7cc6d0cec4
Step 1 : RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 &&     echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" >>  /etc/apt/sources.list.d/mongodb-org-3.0.list &&     apt-get update &&     apt-get install -y git nodejs npm mongodb-org curl &&     ln -s /usr/bin/nodejs /usr/bin/node
 ---> Using cache
 ---> b6628d455d02
Step 2 : ADD etc/supervisord.d/mongod.ini /etc/supervisord.d/
 ---> Using cache
 ---> f694cb2f5175
Step 3 : RUN npm install nave -g &&     nave usemain 0.10.40
 ---> Using cache
 ---> 6526a55b3276
Step 4 : RUN curl -s https://install.meteor.com/ | sh
 ---> Using cache
 ---> be5edc1b8fc3
Step 5 : RUN npm install pm2 -g &&     pm2 startup
 ---> Using cache
 ---> e0108c170d76
Step 6 : RUN mkdir -p /var/www &&     curl -fsL wget https://github.com/RocketChat/Rocket.Chat/archive/master.tar.gz|tar xfz - -C /var/www/ &&     mv /var/www/Rocket.Chat-master /var/www/rocket.chat
 ---> Using cache
 ---> 8eacb7f9af4a
Step 7 : ADD pm2-rocket-chat.json /var/www/rocket.chat/
 ---> Using cache
 ---> 361010a433c9
Step 8 : RUN export HOST=http://192.168.99.100 &&     cd /var/www/rocket.chat &&     meteor build --server "$HOST" --directory .
 ---> Running in 9528386c9dcb
rocketchat:file: updating npm dependencies -- mkdirp, gridfs-stream, gm...

/root/.meteor/packages/meteor-tool/.1.1.9.vaspeb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: EXDEV, rename '/var/www/rocket.chat/packages/rocketchat-file/.npm/package'
    at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.9.vaspeb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as rename] (/tools/fs/files.js:1334:20)
    at Object.files.renameDirAlmostAtomically (/tools/fs/files.js:812:11)
    at completeNpmDirectory (/tools/isobuild/meteor-npm.js:319:9)
    at updateExistingNpmDirectory (/tools/isobuild/meteor-npm.js:278:3)
    at Object.meteorNpm.updateDependencies (/tools/isobuild/meteor-npm.js:86:7)
    at Object.compile (/tools/isobuild/compiler.js:118:19)
    at /tools/isobuild/isopack-cache.js:271:30
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at [object Object]._.extend._loadLocalPackage (/tools/isobuild/isopack-cache.js:227:18)
    at /tools/isobuild/isopack-cache.js:166:14
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at [object Object]._.extend._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:158:20)
    at /tools/isobuild/isopack-cache.js:73:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.1.9.vaspeb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object]._.extend.eachPackage (/tools/packaging/package-map.js:49:7)
    at [object Object]._.extend.buildLocalPackages (/tools/isobuild/isopack-cache.js:72:24)
    at /tools/project-context.js:735:25
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:734:18)
    at /tools/project-context.js:257:35
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
    at /tools/cli/commands.js:838:20
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.main.captureAndExit (/tools/cli/main.js:270:29)
    at buildCommand (/tools/cli/commands.js:837:8)
    at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:791:12)
    at /tools/cli/main.js:1378:23
    - - - - -
The command '/bin/sh -c export HOST=http://192.168.99.100 &&     cd /var/www/rocket.chat &&     meteor build --server "$HOST" --directory .' returned a non-zero code: 8
>>
```
Cheers
Christian

**Comment by ChristianKniep** [comment]
I guess it's due to my node installation.. If someone could have a look, I would appreciate it.
In the meantime I created a Debian version of the Image, which mimics the installation path of the 'official' image. This is now merged into the github repo above.
The commit that broke like seen above is this: https://github.com/qnib/docker-rocketchat/tree/dc467442731b17f7043091ebaabfcb33e0c061cb
