### ISSUE TITLE
App server failing to join broadcast with migration error

### ISSUE THREAD

**Issue by luckenbach** [RocketChat/Rocket.Chat#12652]
### Description:

HA install on Kuberentes presenting odd behavior with singular pod in deployment

### Steps to reproduce:

Migrate RocketChat single app, single mongo to replicaset based deployment

- 3 x Mongo Replicas created
- mongodump of old database
- mongorestore on replica
- ensure users and opslog db's exist
- 3 replica deployment of RC

### Expected behavior:

All Pods to come up and show in "Broadcast Connected Instances"

### Actual behavior:

- 2 replicas startup as expected 1 pod crashing with error
```Exception in callback of async function: Error: [Can't find migration version 135]```
- Scaled replicas to 4 and now i have 3 working and 1 pod still error'ing 

### Server Setup Information:

- Version of Rocket.Chat Server:  0.70.4
- Operating System:  CentOS / k8s
- Deployment Method:  Docker Image on K8s
- Number of Running Instances: 
- DB Replicaset Oplog:  yes
- NodeJS Version: v8.11.3
- MongoDB Version:  3.6.9

### Additional context

I tested the setup in my dev environment before endeavoring on this journey and it works successfully there. There was a misstep during the installation and the opslog database was not created prior to the starting of multiple RC instances.  

### Relevant logs:

Only out of place error i see

```[34mI20181117-21:45:01.810(0) Error in oplog callback TypeError: Cannot read property 'u' of undefined     at ModelsBaseDb.RocketChat.models.Subscriptions.on (/app/bundle/programs/server/app/app.js:13316:58)     at emitOne (events.js:116:13)     at ModelsBaseDb.emit (events.js:211:7)     at ModelsBaseDb.processOplogRecord (/app/bundle/programs/server/packages/rocketchat_lib.js:12150:12)     at /app/bundle/programs/server/packages/mongo.js:1494:7     at runWithEnvironment (packages/meteor.js:1238:24)     at Object.callback (packages/meteor.js:1251:14)     at /app/bundle/programs/server/packages/ddp-server.js:2130:36     at Array.forEach (<anonymous>:null:null)     at Function._.each._.forEach (packages/underscore.js:139:11)     at DDPServer._Crossbar.fire (/app/bundle/programs/server/packages/ddp-server.js:2128:7)     at /app/bundle/programs/server/packages/mongo.js:1719:26     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at packages/meteor.js:502:25     at runWithEnvironment (packages/meteor.js:1238:24)  ```

**Comment by luckenbach** [comment]
Upgraded to 0.71 and this is no longer occuring
