### ISSUE TITLE
0.72.0-rc.0 fails to reach mongoDB replica

### ISSUE THREAD

**Issue by pkolmann** [RocketChat/Rocket.Chat#12711]
### Description:

I am testing 0.72.0-rc.0 on my setup with mongodb 3.2.11-2+deb9u1 and it fails to start:

```
Nov 23 11:13:45 web-d-1 systemd[1]: Started Rocket.Chat Dev Server.
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]: /home/dev/rocketChat-0.72.0.rc.0/bundle/programs/server/node_modules/fibers/future.js:313
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]:                                                 throw(ex);
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]:                                                 ^
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]: MongoError: no primary found in replicaset or invalid replica set name
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]:     at /home/dev/rocketChat-0.72.0.rc.0/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:636:11
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]:     at Server.<anonymous> (/home/dev/rocketChat-0.72.0.rc.0/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:357:9)
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]:     at Object.onceWrapper (events.js:315:30)
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]:     at emitOne (events.js:116:13)
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]:     at Server.emit (events.js:211:7)
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]:     at /home/dev/rocketChat-0.72.0.rc.0/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:508:16
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]:     at /home/dev/rocketChat-0.72.0.rc.0/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
Nov 23 11:13:46 web-d-1 RocketChat-Dev[14634]:     at process._tickCallback (internal/process/next_tick.js:181:9)
```

I don't have these connection issues with versions 0.71 and below

### Steps to reproduce:

1.) Build rc 0.72.0.rc.0
2.) start
3.) fails to connect to DB

### Expected behavior:

can connect to DB

### Actual behavior:

see log above

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.0-rc.0
- Operating System: Debian Stretch 4.9.110-3+deb9u4
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: 
- NodeJS Version: 8.12.0-1
- MongoDB Version: 3.2.11-2+deb9u1

### Relevant logs:

MongoDB Log:
```
2018-11-23T11:26:00.401+0100 I NETWORK  [initandlisten] connection accepted from 172.17.47.174:59936 #1238 (14 connections now open)
2018-11-23T11:26:00.415+0100 I NETWORK  [conn1238] end connection 172.17.47.174:59936 (13 connections now open)
2018-11-23T11:26:00.419+0100 I NETWORK  [initandlisten] connection accepted from 172.17.47.174:59942 #1239 (14 connections now open)
2018-11-23T11:26:00.432+0100 I NETWORK  [conn1239] end connection 172.17.47.174:59942 (13 connections now open)
```

**Comment by rodrigok** [comment]
@pkolmann can you post your connection string? We updated Meteor to 1.8 which updated the MongoDB driver, it may changed something in the connection pattern.

**Comment by geekgonecrazy** [comment]
@rodrigok yes please see: https://github.com/RocketChat/Rocket.Chat/issues/12781.  We need meteor to update.  

@pkolmann best bet is stay on 0.71.1 until you see #12781 close
