### ISSUE TITLE
Fails with replica set (setName from ismaster does not match provided connection setName)

### ISSUE THREAD

**Issue by pafik13** [RocketChat/Rocket.Chat#12718]
### Description:
 Newest code base fails with replica set

### Steps to reproduce:

1. Checkout 'develop' branch
2. Build
3. Start with old config (used for 0.70.4 version)

### Expected behavior:
Connect to MongoDB with enabled OpLog option

### Actual behavior:
Error on startup if using connection string with **?replicaSet=001-rs**

### Server Setup Information:

- Version of Rocket.Chat Server: 'develop' branch ( > 0.72.0-rc1 )
- Operating System: Ubuntu 16.04.5 LTS (x86_64)
- Deployment Method: metor build
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: v8.11.3
- MongoDB Version: 3.2.21

### Relevant logs:

```
/opt/Rocket.Chat-Anon/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^

MongoError: setName from ismaster does not match provided connection setName [001-rs] != [1]
    at ReplSetState.update (/opt/Rocket.Chat-Anon/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset_state.js:403:14)
    at /opt/Rocket.Chat-Anon/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:809:45
    at applyAuthenticationContexts (/opt/Rocket.Chat-Anon/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:731:12)
    at Server.<anonymous> (/opt/Rocket.Chat-Anon/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:802:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at /opt/Rocket.Chat-Anon/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:508:16
    at /opt/Rocket.Chat-Anon/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by MartinSchoeler** [comment]
Could you try asking this at our [forums](https://forums.rocket.chat/) before opening a bug report? As it could be a myriad of unrelated problems that is causing this, will be closing this issue for now. Thanks!

**Comment by arisau** [comment]
I'm also getting this error after upgrading to 0.72.0.

**Comment by ohmonster** [comment]
This may be what's affecting you
https://github.com/RocketChat/Rocket.Chat/issues/12781

**Comment by geekgonecrazy** [comment]
yes please see #12781
