### ISSUE TITLE
Problem with installation on clean ubuntu

### ISSUE THREAD

**Issue by vetash** [RocketChat/Rocket.Chat#1275]
After all steps is done i see these errors in `/var/log/rocket.chat/err-0.log`
```
root@chat:/var/www/rocket.chat/bundle# tail -f /var/log/rocket.chat/err-0.log 
    at Error (<anonymous>)
    at [object Object]._.extend._startTailing (packages/mongo/oplog_tailing.js:216:1)
    at new OplogHandle (packages/mongo/oplog_tailing.js:76:1)
    at new MongoConnection (packages/mongo/mongo_driver.js:216:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
Error: $MONGO_OPLOG_URL must be set to the 'local' database of a Mongo replica set
    at Error (<anonymous>)
    at [object Object]._.extend._startTailing (packages/mongo/oplog_tailing.js:216:1)
    at new OplogHandle (packages/mongo/oplog_tailing.js:76:1)
    at new MongoConnection (packages/mongo/mongo_driver.js:216:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
Error: $MONGO_OPLOG_URL must be set to the 'local' database of a Mongo replica set
    at Error (<anonymous>)
    at [object Object]._.extend._startTailing (packages/mongo/oplog_tailing.js:216:1)
    at new OplogHandle (packages/mongo/oplog_tailing.js:76:1)
    at new MongoConnection (packages/mongo/mongo_driver.js:216:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
^C
```

**Comment by vetash** [comment]
root@chat:/var/www/rocket.chat/bundle# echo $MONGO_OPLOG_URL
mongodb://localhost:27017/local

**Comment by richardwlu** [comment]
@vetash Which version of monogodb are you running? If you're using 3.0.7, take a look at https://github.com/RocketChat/Rocket.Chat/issues/1026.

**Comment by vetash** [comment]
Hello @richardwlu! 
Thank to reply, yes i am using 3.0.7. 
After reading issue 1026, i check my hosts file.
So, problem was in line
`127.0.1.1      chat`
After i comment this line and add 
`127.0.0.1       localhost chat`
rocket chat is start normaly and worked fine.

Thank you!
