### ISSUE TITLE
RocketChat 0.73.0 won't start

### ISSUE THREAD

**Issue by immanuelfodor** [RocketChat/Rocket.Chat#13042]
### Description:

After upgrading the server from 0.72.1 to 0.73.0, it won't start and an exception is printed to syslog. Restoring the folder to the backup is running again fine.

### Steps to reproduce:

Acting as root:

```bash
systemctl stop rocketchat
systemctl status rocketchat

cd ~
curl -L https://releases.rocket.chat/latest/download -o rocket.chat.tgz
ls -la
tar zxvf rocket.chat.tgz
rm rocket.chat.tgz

systemctl status mongod

rm -rf Rocket.Chat-bak
mv Rocket.Chat Rocket.Chat-bak
mv bundle Rocket.Chat
cd Rocket.Chat/programs/server
npm install
cd ~

systemctl start rocketchat
systemctl status rocketchat
journalctl -xef
# error is printed after a while and so server won't start
```

### Expected behavior:

0.73.0 starts up fine without errors.

### Actual behavior:

An error is printed to syslog and 0.73.0 won't start up, server inaccessible from Android app, etc. 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.0
- Operating System: Ubuntu Linux Server
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: none
- NodeJS Version: 8.11.4
- MongoDB Version: MongoDB shell/db version v4.0.5, git version: 3739429dd92b92d1b0ab120911a23d50bf03c412 

### Additional context

Service file:

```bash
cat /etc/systemd/system/rocketchat.service

[Unit]
Description=RocketChat Server
After=network.target remote-fs.target nss-lookup.target mongod.target

[Service]
ExecStart=/usr/local/n/versions/node/8.11.4/bin/node /root/Rocket.Chat/main.js
Restart=always
RestartSec=10
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=nodejs-rocketchat
Environment=NODE_ENV=production PORT=3000 ROOT_URL=https://domain.tld MONGO_URL=mongodb://XXX:YYY@localhost:27017/rocketchat

[Install]
WantedBy=multi-user.target
```

Restored previous version from bak, restarted service, and 0.72.1 works fine again:

```bash
rm -rf Rocket.Chat
mv Rocket.Chat-bak Rocket.Chat
systemctl start rocketchat
systemctl status rocketchat
journalctl -xef
# 0.72.1 starts up fine as expected, no error printed
```

### Relevant logs:

**SERVER 0.73.0**

```
...
Dec 28 06:01:29 x nodejs-rocketchat[8028]: rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_authorize_path                        
Dec 28 06:01:29 x nodejs-rocketchat[8028]: rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_scope                                 
Dec 28 06:01:29 x nodejs-rocketchat[8028]: rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_callback_url                          
Dec 28 06:01:29 x nodejs-rocketchat[8028]: Using GridFS for custom sounds storage                                                        
Dec 28 06:01:29 x nodejs-rocketchat[8028]: Using GridFS for custom emoji storage                                                        
Dec 28 06:01:29 x nodejs-rocketchat[8028]: Exception in callback of async function: Error: Unable to resolve "~" in path                 
Dec 28 06:01:29 x nodejs-rocketchat[8028]:     at new RocketChatFile.FileSystem (packages/rocketchat:file/server/file.server.js:150:11)  
Dec 28 06:01:29 x nodejs-rocketchat[8028]:     at packages/rocketchat:importer/server/startup/store.js:16:33                             
Dec 28 06:01:29 x nodejs-rocketchat[8028]:     at Function.time (/root/Rocket.Chat/programs/server/profile.js:309:28)                    
Dec 28 06:01:29 x nodejs-rocketchat[8028]:     at /root/Rocket.Chat/programs/server/boot.js:427:13                                       
Dec 28 06:01:29 x nodejs-rocketchat[8028]:     at /root/Rocket.Chat/programs/server/boot.js:472:5                                        
Dec 28 06:01:29 x nodejs-rocketchat[8028]:     at Function.run (/root/Rocket.Chat/programs/server/profile.js:510:12)                     
Dec 28 06:01:29 x nodejs-rocketchat[8028]:     at /root/Rocket.Chat/programs/server/boot.js:470:11                                       
Dec 28 06:01:29 x nodejs-rocketchat[8028]: CROWD ➔ info Disabling CROWD Background Sync                                                  
Dec 28 06:01:30 x nodejs-rocketchat[8028]: CAS ➔ info Disabling CAS login servic
```

And it stops here without any further progress.

**SERVER 0.72.1**

After restoring from backup, this version works fine just as before:

```
...
]: ➔ +-----------------------------------------------------+              
]: ➔ |                    SERVER RUNNING                   |              
]: ➔ +-----------------------------------------------------+              
]: ➔ |                                                     |              
]: ➔ |  Rocket.Chat Version: 0.72.1                        |              
]: ➔ |       NodeJS Version: 8.11.4 - x64                  |              
]: ➔ |             Platform: linux                         |              
]: ➔ |         Process Port: 3000                          |              
]: ➔ |             Site URL: https://domain.tld            |              
]: ➔ |     ReplicaSet OpLog: Disabled                      |              
]: ➔ |          Commit Hash: 490679a709                    |              
]: ➔ |        Commit Branch: HEAD                          |              
]: ➔ |                                                     |              
]: ➔ +-----------------------------------------------------+
```

**BROWSER** 

None, server won't start on 0.73.0.

**Comment by immanuelfodor** [comment]
Refs Release 0.73.0 #13040

**Comment by immanuelfodor** [comment]
I guess the problem lies somewhere here in this relatively new file (7 days ago): https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-importer/server/startup/store.js
I have no `~/uploads` folder (never had).

**Comment by Pitstopper** [comment]
@immanuelfodor same problem

**Comment by sampaiodiego** [comment]
thanks @immanuelfodor for the very detailed report.. I'll work on a fix for this ASAP

**Comment by immanuelfodor** [comment]
Thanks @sampaiodiego it's now working fine after the update to 0.73.1 :clap:
