### ISSUE TITLE
Frequent outage of Rocket chat

### ISSUE THREAD

**Issue by BSuraj93** [RocketChat/Rocket.Chat#13113]
Lately, we are facing frequent outages of rocket chat. We have our chat console configured at chat.zencode.guru. However, in both web app and desktop app, it shows connecting, trying in <n> seconds. Before three days, it was a rare occurrence, however the outage frequency has increased and it is now almost 2-3 times a day for a long time (more than 10-15 minutes). Is it occurring due to a global issue or a problem from the our side?

**Comment by grandizzy** [comment]
Same here, this started to become a real problem for our production env,  RC logs indicates problem with loading missed messages, see below

Server version installed from snap
Rocket.Chat Version: 0.72.3  
NodeJS Version: 8.11.3 - x64
ReplicaSet OpLog: Enabled
Commit Hash: 65747ce814
Commit Branch: HEAD

Thanks

Exception while invoking method 'loadMissedMessages' { MongoError: Cursor not found, cursor id: 181470740694
    at /snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:489:15)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
 => awaited here:
    at Function.Promise.await (/snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at Promise.asyncApply (/snap/rocketchat-server/1356/programs/server/packages/mongo.js:1055:32)
    at /snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at SynchronousCursor._nextObject (/snap/rocketchat-server/1356/programs/server/packages/mongo.js:1104:43)
    at SynchronousCursor.forEach (/snap/rocketchat-server/1356/programs/server/packages/mongo.js:1117:22)
    at SynchronousCursor.map (/snap/rocketchat-server/1356/programs/server/packages/mongo.js:1127:10)
    at SynchronousCursor.fetch (/snap/rocketchat-server/1356/programs/server/packages/mongo.js:1147:17)
    at Cursor.(anonymous function) [as fetch] (/snap/rocketchat-server/1356/programs/server/packages/mongo.js:918:44)
    at MethodInvocation.loadMissedMessages (/snap/rocketchat-server/1356/programs/server/app/app.js:11368:94)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at MethodInvocation.methodsMap.(anonymous function) (/snap/rocketchat-server/1356/programs/server/packages/rocketchat_lib.js:2702:36)
    at maybeAuditArgumentChecks (/snap/rocketchat-server/1356/programs/server/packages/ddp-server.js:1877:12)
    at DDP._CurrentMethodInvocation.withValue (/snap/rocketchat-server/1356/programs/server/packages/ddp-server.js:902:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at DDPServer._CurrentWriteFence.withValue (/snap/rocketchat-server/1356/programs/server/packages/ddp-server.js:902:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Promise (/snap/rocketchat-server/1356/programs/server/packages/ddp-server.js:902:46)
    at new Promise (<anonymous>:null:null)
    at Session.method (/snap/rocketchat-server/1356/programs/server/packages/ddp-server.js:875:23)
    at /snap/rocketchat-server/1356/programs/server/packages/ddp-server.js:754:85

**Comment by frdmn** [comment]
@BSuraj93 Can you check if the problem still occur with the latest version of Rocket.Chat?

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates, if you experience this on the latest release, feel free to open a new issue.

Thanks!
