### ISSUE TITLE
Rocketchat freeze couple of times per day

### ISSUE THREAD

**Issue by grandizzy** [RocketChat/Rocket.Chat#13140]
Hi All,

this started to exhibit lately (one to no more than 2 weeks) and it is a real problem for our production env, any help really appreciated

Server version installed from snap
Rocket.Chat Version: 0.72.3
NodeJS Version: 8.11.3 - x64
ReplicaSet OpLog: Enabled
Commit Hash: 65747ce
Commit Branch: HEAD
MongoDB: 3.2.7

RC logs indicates problem with loading missed messages:

Exception while invoking method 'loadMissedMessages' { MongoError: Cursor not found, cursor id: 181470740694
at /snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:581:63
at authenticateStragglers (/snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:504:16)
at Connection.messageHandler (/snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:540:5)
at emitMessageHandler (/snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:310:10)
at Socket. (/snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:489:15)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:597:20)
=> awaited here:
at Function.Promise.await (/snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at Promise.asyncApply (/snap/rocketchat-server/1356/programs/server/packages/mongo.js:1055:32)
at /snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Promise.await (/snap/rocketchat-server/1356/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
at SynchronousCursor._nextObject (/snap/rocketchat-server/1356/programs/server/packages/mongo.js:1104:43)
at SynchronousCursor.forEach (/snap/rocketchat-server/1356/programs/server/packages/mongo.js:1117:22)
at SynchronousCursor.map (/snap/rocketchat-server/1356/programs/server/packages/mongo.js:1127:10)
at SynchronousCursor.fetch (/snap/rocketchat-server/1356/programs/server/packages/mongo.js:1147:17)
at Cursor.(anonymous function) [as fetch] (/snap/rocketchat-server/1356/programs/server/packages/mongo.js:918:44)
at MethodInvocation.loadMissedMessages (/snap/rocketchat-server/1356/programs/server/app/app.js:11368:94)
at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
at MethodInvocation.methodsMap.(anonymous function) (/snap/rocketchat-server/1356/programs/server/packages/rocketchat_lib.js:2702:36)
at maybeAuditArgumentChecks (/snap/rocketchat-server/1356/programs/server/packages/ddp-server.js:1877:12)
at DDP._CurrentMethodInvocation.withValue (/snap/rocketchat-server/1356/programs/server/packages/ddp-server.js:902:126)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
at DDPServer._CurrentWriteFence.withValue (/snap/rocketchat-server/1356/programs/server/packages/ddp-server.js:902:98)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
at Promise (/snap/rocketchat-server/1356/programs/server/packages/ddp-server.js:902:46)
at new Promise (:null:null)
at Session.method (/snap/rocketchat-server/1356/programs/server/packages/ddp-server.js:875:23)
at /snap/rocketchat-server/1356/programs/server/packages/ddp-server.js:754:85

It could be related to Mongo node driver, was there any update of that?

Thanks

**Comment by frdmn** [comment]
@grandizzy Can you check if this problem still occurs with the latest version of Rocket.Chat?

**Comment by grandizzy** [comment]
@frdmn nope, didn't see it for a while, I guess this can be closed now
