### ISSUE TITLE
Cannot read property 'getReadStream' of undefined

### ISSUE THREAD

**Issue by zpavlig** [RocketChat/Rocket.Chat#13174]
Hello

I updated rocket.chat to 0.73.2, try upload file for webdav

error:

```
Exception in callback of async function: TypeError: Cannot read property 'getReadStream' of undefined
    at FileUploadClass.get (packages/rocketchat:file-upload/server/config/Webdav.js:6:13)
    at Object.get (packages/rocketchat:file-upload/server/lib/FileUpload.js:256:17)
    at server/startup/avatar.js:97:23
    at runWithEnvironment (packages/meteor.js:1356:24)
    at packages/meteor.js:1369:14
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

thx

**Comment by zpavlig** [comment]
@MarcosSpessatto thank you very much! I update rocket chat to 0.74.0-develop and upload file with webdav ok.
