### ISSUE TITLE
Problem with IRC federation

### ISSUE THREAD

**Issue by asunyer90** [RocketChat/Rocket.Chat#13202]
Hi!
I'm getting this when trying to send one message even from irc to rocket or viceversa:

[irc][server][err] { Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:364:12)
    at RFC2813.write (packages/rocketchat:irc/server/servers/RFC2813/index.js:115:22)
    at RFC2813.sentMessage (packages/rocketchat:irc/server/servers/RFC2813/localCommandHandlers.js:55:7)
    at RFC2813.onReceiveFromLocal (packages/rocketchat:irc/server/servers/RFC2813/index.js:173:34)
    at emitTwo (events.js:126:13)
    at RFC2813.emit (events.js:214:7)
    at Bridge.sendCommand (packages/rocketchat:irc/server/irc-bridge/index.js:135:15)
    at Bridge.handleOnSaveMessage (packages/rocketchat:irc/server/irc-bridge/localHandlers/onSaveMessage.js:33:7)
    at Promise.asyncApply (packages/rocketchat:irc/server/irc-bridge/index.js:83:46)
    at /root/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 code: 'EPIPE' }

Thanks

**Comment by asunyer90** [comment]
Solved, have to use last version of ngircd

**Comment by geekgonecrazy** [comment]
Thanks for following up with the solution
