### ISSUE TITLE
Trying to use the REST API to login anonymously

### ISSUE THREAD

**Issue by cactrot** [RocketChat/Rocket.Chat#13304]
### Description:

I am trying to use the REST API to login anonymously from an app I'm developing in js. I get a 400 bad request response.
I have enabled anonymous login and can login to the server anonymously using Google Chrome.

### Steps to reproduce:

Run one of these requests in Javascript:

var req = new XMLHttpRequest();
req.open("POST", "https://example.com/api/v1/users.register");
req.setRequestHeader("Content-Type", "application/json");
req.send(JSON.stringify({ "username": "", "email": "", "pass": "","name":""}));
req.responseText

//"{"success":false,"error":"Invalid email  [error-invalid-email]","errorType":"error-invalid-email"}"

var req = new XMLHttpRequest();
req.open("POST", "https://example.com/api/v1/users.register");
req.setRequestHeader("Content-Type", "application/json");
req.send(JSON.stringify({ "username": "", "email": null, "pass": "","name":""}));
req.responseText

//"{"success":false,"error":"Cannot read property 'id' of null"}"

### Expected behavior:

A JSON object that has entries similar too => "success":true and _id:"nSYqWzZ4GsKTX4dyK"

### Actual behavior:

These are the two results I get depending on the query I try.

// result "{"success":false,"error":"Invalid email  [error-invalid-email]","errorType":"error-invalid-email"}"

// result "{"success":false,"error":"Cannot read property 'id' of null"}"

### Server Setup Information:

- Version of Rocket.Chat Server: 0.64.0-develop
- Operating System: debian
- Deployment Method: run meteor from command line
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.1
- MongoDB Version: 

### Additional context

I have tried to trace through the code in the following files and haven't found the difference in logic yet.
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/users.js

https://github.com/RocketChat/Rocket.Chat/blob/c1dbe59f9410e74e58fc0a070c71be00a46e7370/packages/rocketchat-ui-message/client/messageBox.html
https://github.com/RocketChat/Rocket.Chat/blob/2882438c0406e0b91419f5df41a85dbb6fda81ce/server/methods/registerUser.js

I searched for similar issues but none seem to cover the issue I'm experiencing.

### Relevant logs:

Exception while invoking method 'browseChannels'
```
TypeError: Cannot read property '_id' of null
    at MethodInvocation.browseChannels (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/app/app.js:8284:48)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at MethodInvocation.methodsMap.(anonymous function) (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:2235:28)
    at maybeAuditArgumentChecks (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1877:12)
    at DDP._CurrentMethodInvocation.withValue (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:902:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:902:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:902:46)
    at new Promise (<anonymous>:null:null)
    at Session.method (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:875:23)
    at /home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:754:85


```
Exception while invoking method 'logoutCleanUp'
```
Error: Match error: Expected object, got null
    at check (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/check.js:68:17)
    at MethodInvocation.logoutCleanUp (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/app/app.js:9647:5)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at MethodInvocation.methodsMap.(anonymous function) (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:2235:28)
    at maybeAuditArgumentChecks (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1877:12)
    at DDP._CurrentMethodInvocation.withValue (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:902:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:902:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:902:46)
    at new Promise (<anonymous>:null:null)
    at Session.method (/home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:875:23)
    at /home/example/Documents/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:754:85


```
Sanitized and reported to the client as:
```
Match failed [400]

**Comment by reetp** [comment]
>0.64.0-develop

You appear to be using a very old version of Rocket??

Please update to the latest stable 0.73.2 or 0.74.0 and test thank you.

I'd also think about why you get this response

> // result "{"success":false,"error":"Invalid email [error-invalid-email]","errorType":"error-invalid-email"}"

**Comment by cactrot** [comment]
Thanks for taking a look at my issue. What leads to the error is exactly what I'm thinking about, but I haven't found the failure point yet. Although I haven't found the difference in the registration code between my local version and current I'll update the server. It would be a very pleasant surprise if an existing patch fixes the problem.

The html UI calls the registerUser function with empty formData. 
https://github.com/RocketChat/Rocket.Chat/blob/c1dbe59f9410e74e58fc0a070c71be00a46e7370/packages/rocketchat-ui-message/client/messageBox.js#L371

https://github.com/RocketChat/Rocket.Chat/blob/2882438c0406e0b91419f5df41a85dbb6fda81ce/server/methods/registerUser.js#L17

But when I send a null email address something errors out.
https://github.com/RocketChat/Rocket.Chat/blob/5795b3f870f58f631e6d74a6aed37f03d4a44285/packages/rocketchat-api/server/v1/users.js#L195

**Comment by graywolf336** [comment]
Closing until you test with the latest version. As a rule of thumb, we generally only support three versions including the latest. However, if after testing it still needs looked at then comment back with an update and re-open the issue.
