### ISSUE TITLE
official docker image fails to run 

### ISSUE THREAD

**Issue by wjimenez5271** [RocketChat/Rocket.Chat#1333]
```
bash-3.2$ docker run rocketchat/rocket.chat

/app/bundle/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: failed to connect to [db:27017]
    at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /app/bundle/programs/server/packages/accounts-base.js:1814:4
    - - - - -
    at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
    at process._tickCallback (node.js:448:13)
```

**Comment by jonbaer** [comment]
You need to make sure you create a mongo instance first + then link to it (via the db alias)

See: https://github.com/docker-library/docs/tree/master/rocket.chat

**Comment by Sing-Li** [comment]
Yes, or follow the *Deploy with Docker*  link close to  the top of  https://github.com/RocketChat/Rocket.Chat  README , which links to wiki page:

https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-with-Docker

**Comment by wjimenez5271** [comment]
OK thanks. Sorry if I missed that, the README just said invoke `docker run` with a container name, so I made the assumption it was that simple.

**Comment by boulakar** [comment]
Hi i have like this bug but i'm not one Docker i'm on Ubuntu AWS

**Comment by engelgabriel** [comment]
please open a new issue @boulakar 

Note that if you are using Rocket.Chat develop, you need NodeJS 4.5
