### ISSUE TITLE
err-0 log fills with error: module did not self-register, bcrypt.js related?

### ISSUE THREAD

**Issue by mgancarzdsi** [RocketChat/Rocket.Chat#1347]
Hi, trying to get rocket.chat test installed using the install without docker instructions, on CentOS 7.

I've gotten it to the point of starting rocket chat, but after running pm2 start pm2-rocket-chat.json, it seems to keep restarting.

The err-0 log is filled with (<snip> replaces the URL path which is a staging server)
```
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/var/www/html/<snip>/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/var/www/html/<snip>/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

pm2 show 0 displays:
```
┌───────────────────┬──────────────────────────────────────────────────────────────────────┐
│ status            │ online                                                               │
│ name              │ rocket.chat                                                          │
│ id                │ 0                                                                    │
│ path              │ /var/www/html/<snip>/bundle/main.js │
│ args              │                                                                      │
│ exec cwd          │ /var/www/html/<snip>/bundle         │
│ error log path    │ /var/log/rocket.chat/err-0.log                                       │
│ out log path      │ /var/log/rocket.chat/app-0.log                                       │
│ pid path          │ /root/.pm2/pids/rocket.chat-0.pid                                    │
│ mode              │ fork_mode                                                            │
│ node v8 arguments │                                                                      │
│ watch & reload    │ ✘                                                                    │
│ interpreter       │ node                                                                 │
│ restarts          │ 244                                                                  │
│ unstable restarts │ 11                                                                   │
│ uptime            │ 0s                                                                   │
│ created at        │ 2015-11-06T23:38:16.311Z                                             │
└───────────────────┴──────────────────────────────────────────────────────────────────────┘
```

**Comment by emcguinness** [comment]
A quick Google shows lots of people with that error using the wrong version of node. I am not entirely sure what the newest version Rocket.Chat will run on but hopefully if you post it here hopefully someone who does know can confirm. Can find it easy enough with a `node -v`

**Comment by mcmyt** [comment]
I've fixed this by downgrading to Node V0.10 with
`nave usemain 0.10`

**Comment by stephenreda** [comment]
I've had a similar error. I deleted the bcrypt library, and performed a general 'npm update'. After this, re-installing worked just fine.

**Comment by LiftedKilt** [comment]
I am encountering the same error. Using nave usemain 0.10 allows me to start the server (it's the only version that works), but all of the css fails to load when I do so.

**Comment by mgancarzdsi** [comment]
Thank you, confirming that `nave usemain 0.10.40`, followed by pm2 start again fixed the issue. Thank you to all who suggested that!
