### ISSUE TITLE
Error: Cannot find module '@accounts/server'

### ISSUE THREAD

**Issue by xiefangzhenz** [RocketChat/Rocket.Chat#13489]
### Description:
When running command "meteor npm start" an unclear error is thrown

### Server Setup Information:
* Version of Rocket.Chat Server: Latest
* Operating System: MAC OS 10.14.3
* Deployment Method(snap/docker/tar/etc): meteor
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: 8.9.3
* mongoDB Version: 3.6.10

### Steps to Reproduce:
1. Follow steps in the documentation
2. run "meteor npm start"

### Expected behavior:
Either provide better error message that provides better details as to what went wrong or start Rocket.Chat

### Actual behavior:
Error thrown

### Relevant logs:
Error Thrown:

/Users/xiefangzhen/.meteor/packages/meteor-tool/.1.8.0_2.cty1uc.prsil++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Cannot find module '@accounts/server'
     at makeMissingError (packages/modules-runtime.js:222:12)
     at Module.require (packages/modules-runtime.js:241:17)
     at Module.moduleLink [as link] (/Users/xiefangzhen/.meteor/packages/modules/.0.13.0.1pfv79d.ujmak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at config.js (packages/rocketchat:accounts/server/config.js:1:27)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/xiefangzhen/.meteor/packages/modules/.0.13.0.1pfv79d.ujmak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
     at index.js (packages/rocketchat:accounts/server/index.js:1:59)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
     at require (packages/modules-runtime.js:258:21)
     at /Users/xiefangzhen/Documents/develop/HTML/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_accounts.js:98:15
    at /Users/xiefangzhen/Documents/develop/HTML/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_accounts.js:103:3
    at /Users/xiefangzhen/Documents/develop/HTML/Rocket.Chat/.meteor/local/build/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /Users/xiefangzhen/Documents/develop/HTML/Rocket.Chat/.meteor/local/build/programs/server/boot.js:220:19

**Comment by reetp** [comment]
Can you make sure you run the recommended software versions as per this:

https://github.com/RocketChat/Rocket.Chat/releases

Node: 8.11.4 (yours shows 8.9.3)
NPM: 6.4.1
MongoDB: 3.2, 3.4, 3.6, 4.0

Not saying that will cure anything, but the devs will know the baseline to try and debug it.

**Comment by xiefangzhenz** [comment]
Thanks,it works!
