### ISSUE TITLE
UnhandledPromiseRejectionWarning: MongoError: FieldPath 'user_daily' doesn't start with $

### ISSUE THREAD

**Issue by tars21** [RocketChat/Rocket.Chat#13494]
### Description:
Since updating from 0.73.2 to 0.74.2 (also 0.74.3) there is periodically at 02:00 in the morning an UnhandledPromiseRejectionWarning (see relevant logs).
With moving back to 0.73.2 the error message drops out.

### Steps to reproduce:
1. Update RocketChat to version 0.74.2
2. Wait until 02:00 CET
3. Get Error Message "UnhandledPromiseRejectionWarning"

### Expected behavior:
I expect no error messages

### Actual behavior:
Getting an error message exactly at 02:00 CET: 
`UnhandledPromiseRejectionWarning: MongoError: FieldPath 'user_daily' doesn't start with $`

### Server Setup Information:
- Version of Rocket.Chat Server: 0.74.2 and 0.74.3
- Operating System: Debian 9.7 (Stretch)
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: true
- NodeJS Version: 8.15.0-1
- MongoDB Version: 3.2.11-2

### Additional context
I've renamed the replicaset a few weeks ago: https://github.com/RocketChat/Rocket.Chat/issues/12781
0.73.2 was running fine then.

### Relevant logs:
```
Feb 15 02:00:00 rocketchat-staging RocketChat[4187]: (node:4187) UnhandledPromiseRejectionWarning: MongoError: FieldPath 'user_daily' doesn't start with $
Feb 15 02:00:00 rocketchat-staging RocketChat[4187]:     at queryCallback (/srv/rocketchat-program/rocket.chat-0.74.3/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)
Feb 15 02:00:00 rocketchat-staging RocketChat[4187]:     at /srv/rocketchat-program/rocket.chat-0.74.3/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
Feb 15 02:00:00 rocketchat-staging RocketChat[4187]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
Feb 15 02:00:00 rocketchat-staging RocketChat[4187]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Feb 15 02:00:00 rocketchat-staging RocketChat[4187]: (node:4187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Feb 15 02:00:00 rocketchat-staging RocketChat[4187]: (node:4187) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tars21** [comment]
This error does not appear on our productive setup with the same environment like avove.
I've no idea which difference is responsible for this error.. but I think this issue here can be closed then.

**Comment by geekgonecrazy** [comment]
If you see this again definitely open a new issue.  In the future unhandled promise rejection will actually terminate the process.

**Comment by tars21** [comment]
Can I reopen this one here or shall I create a new issue with the same content?

Meanwhile I saw this error on our productive environment once in the last 4 days (v0.74.3) and again daily on our updated staging environment (1.0.2).
```
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]: === UnHandledPromiseRejection ===
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]: { MongoError: FieldPath 'user_daily' doesn't start with $
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]:     at queryCallback (/srv/rocketchat-program/rocket.chat-1.0.2/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]:     at /srv/rocketchat-program/rocket.chat-1.0.2/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]:   ok: 0,
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]:   errmsg: 'FieldPath \'user_daily\' doesn\'t start with $',
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]:   code: 16873,
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]:   name: 'MongoError',
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]:   [Symbol(mongoErrorContextSymbol)]: {} }
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]: ---------------------------------
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]: Errors like this can cause oplog processing errors.
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]: Future node.js versions will automatically exit the process
Mai 07 02:00:00 rocketchat-staging RocketChat[30077]: =================================
```
The "process termination" makes me listen attentively now. Is there something I can debug here? What is running exactly at 02:00 CET?

**Comment by geekgonecrazy** [comment]
related #14243 

cc: @rodrigok

**Comment by tars21** [comment]
since I've deleted all "no-name" Anonymous user (from testing "Allow Anonymous Read", meanwhile deactivated) those messages disappeared.

**Comment by geekgonecrazy** [comment]
Re-opening.  I think this is still an issue that needs solved.  Some will be using anonymous read we must account for that

**Comment by KevLehman** [comment]
Closing again, if you encounter it again, pls leave a comment.

Seems the issue was related to Sessions (or at least, that was the only place where `user_daily` appeared)
