### ISSUE TITLE
at Function.Module._resolveFilename (module.js:331:15)

### ISSUE THREAD

**Issue by mcmyt** [RocketChat/Rocket.Chat#1350]
I just tried to install Rocket.chat in a fresh Ubuntu 14.04 LTS had some troubles first but then almost worked under another fresh install. I can't start the app with pm2. I'm getting this error

Here is err-0.log
```
Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/var/www/rocket.chat/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
```

`node -v`
```
v0.12.7
```

I'm trying to install it in a DigitalOcean droplet (VPS) with Ubuntu 14.04 LTS

Here is my /etc/hosts
```
127.0.0.1 LegalPlace-Dev LegalPlace-Dev
127.0.0.1 localhost
```

<img width="794" alt="capture d ecran 2015-11-07 a 03 06 35" src="https://cloud.githubusercontent.com/assets/623186/11012934/c136ab1c-84fc-11e5-9f6c-2661e489fb24.png">

Thanks for your help.

**Comment by mcmyt** [comment]
I've fixed this by installing `npm -g n`then `n stable`. And like I'm pretty lucky I get the same error then this issue now #1347
