### ISSUE TITLE
user-presence-tests.js

### ISSUE THREAD

**Issue by harimani83** [RocketChat/Rocket.Chat#13542]
C:\Users\--SystemName--\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\HARIHA~1\AppData\Local\Temp\mt-achd9u.hjqo8\os\konecty:user-presence-tests.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.wrapper [as open] (C:\tools\fs\files.js:1609:35)
    at Object.files.readBufferWithLengthAndOffset (C:\tools\fs\files.js:1860:20)
    at C:\tools\isobuild\unibuild.js:122:26
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\--SystemName--\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Function.fromJSON (C:\tools\isobuild\unibuild.js:119:7)
    at C:\tools\isobuild\isopack.js:921:33
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\--SystemName--\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:908:7)
    at _.each (C:\tools\packaging\tropohouse.js:521:21)
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\--SystemName--\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at buildmessage.enterJob (C:\tools\packaging\tropohouse.js:520:13)
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at C:\tools\packaging\tropohouse.js:515:22
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:600:22
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at exports.Tropohouse.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:597:20)
    at C:\tools\project-context.js:836:25
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at C:\tools\project-context.js:835:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:834:13)
    at C:\tools\project-context.js:300:9
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:290:18)
    at Profile.run (C:\tools\project-context.js:282:12)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:281:13)
    at C:\tools\runners\run-app.js:544:29
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at bundleApp (C:\tools\runners\run-app.js:543:31)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:610:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:908:28)
    at C:\tools\runners\run-app.js:398:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Rocket.Chat@1.0.0-develop start: `meteor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Rocket.Chat@1.0.0-develop start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\--SystemName--\AppData\Roaming\npm-cache\_logs\2019-02-22T04_59_18_465Z-debug.log

**Comment by harimani83** [comment]
any one can this issue

**Comment by saurabhshahare** [comment]
Facing this too, with 0.74 Master branch

**Comment by saurabhshahare** [comment]
+1

**Comment by Hudell** [comment]
We are currently using a package with one file that has a name that is not valid on windows and it causes the file to not be found. We'll rename this file to fix this problem.

**Comment by harimani83** [comment]
Hi  Pierre H. Lehnen ,
  Where I need change the file name because while installing only I'm
getting this error. So please help me which I file I want to change in
Windows machine before installing package

**Comment by saurabhshahare** [comment]
@harimani83 for the workaround try changing the version of konecty:user-presence@2.1.0 from @2.30

**Comment by harimani83** [comment]
Thanks for update me

**Comment by pafik13** [comment]
Hi.
I have same problem. I found _konecty:user-presence_ in _rocketchat-livechat_ and it has 2.3.0 version.
It has 2.3.0 version in _.meteor\versions_ and __meteor run__ still doesn't work.

**Comment by harimani83** [comment]
Hi,
  I got mail from rockchat team they're made some change in that so wait
for some time once they commit the code our error ill be fix
..

**Comment by harimani83** [comment]
> Hi.
> I have same problem. I found _konecty:user-presence_ in _rocketchat-livechat_ and it has 2.3.0 version.
> It has 2.3.0 version in _.meteor\versions_ and **meteor run** still doesn't work.

@pafik13 this error was fixed or not still i am facing same issue on my windows 10

**Comment by pafik13** [comment]
> > Hi.
> > I have same problem. I found _konecty:user-presence_ in _rocketchat-livechat_ and it has 2.3.0 version.
> > It has 2.3.0 version in _.meteor\versions_ and **meteor run** still doesn't work.
> 
> @pafik13 this error was fixed or not still i am facing same issue on my windows 10

i try now and it's not working

**Comment by tassoevan** [comment]
Please, notice that development on Windows is **not** recommended: https://rocket.chat/docs/developer-guides/quick-start/#on-windows
