### ISSUE TITLE
Rocket Chat does not show members list

### ISSUE THREAD

**Issue by brase** [RocketChat/Rocket.Chat#13544]
### Description:

Cannot open the members list of any private groups and channels. Happens at least in the browser and in the windows client. 

### Steps to reproduce:

1. Click on MembersList of a private group or channel

### Expected behavior:

It should show the members.

### Actual behavior:

It does not finish loading:
![image](https://user-images.githubusercontent.com/170088/53232338-32137200-368b-11e9-89dd-6cff63394cfe.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu 16.04.5 LTS
- Deployment Method: docker
- Number of Running Instances:  1
- DB Replicaset Oplog: ?
- NodeJS Version: ?
- MongoDB Version: 3 (docker)

### Relevant logs:

Server:
```
[34mI20190222-09:12:44.715(0) Updating process.env.MAIL_URL 
[34mI20190222-09:12:44.776(0) LocalStore: store created at  
[34mI20190222-09:12:44.776(0) LocalStore: store created at  
[34mI20190222-09:12:44.776(0) LocalStore: store created at  
[34mI20190222-09:12:45.296(0) Starting Email Intercepter... 
[34mI20190222-09:12:45.297(0) Setting default file store to GridFS 
[34mI20190222-09:12:52.467(0) (migrations.js:121) Migrations: Not migrating, already at version 137
[34mI20190222-09:12:52.705(0) ufs: temp directory created at "/tmp/ufs" 
[34mI20190222-09:12:53.227(0) Updating process.env.MAIL_URL 
[34mI20190222-09:12:53.288(0) Using GridFS for custom sounds storage 
[34mI20190222-09:12:53.328(0) Using GridFS for custom emoji storage 
[34mI20190222-09:12:54.697(0) Loaded the Apps Framework and loaded a total of 0 Apps! 
[34mI20190222-09:12:56.234(0) ➔ System ➔ startup 
[34mI20190222-09:12:56.235(0) ➔ +-----------------------------------------------------+ 
[34mI20190222-09:12:56.235(0) ➔ |                    SERVER RUNNING                   | 
[34mI20190222-09:12:56.235(0) ➔ +-----------------------------------------------------+ 
[34mI20190222-09:12:56.235(0) ➔ |                                                     | 
[34mI20190222-09:12:56.235(0) ➔ |  Rocket.Chat Version: 0.74.3                        | 
[34mI20190222-09:12:56.235(0) ➔ |       NodeJS Version: 8.11.4 - x64                  | 
[34mI20190222-09:12:56.235(0) ➔ |             Platform: linux                         | 
[34mI20190222-09:12:56.235(0) ➔ |         Process Port: 3000                          | 
[34mI20190222-09:12:56.236(0) ➔ |             Site URL: https://chat.rhein-spree.com  | 
[34mI20190222-09:12:56.236(0) ➔ |     ReplicaSet OpLog: Disabled                      | 
[34mI20190222-09:12:56.236(0) ➔ |          Commit Hash: 202a465f1c                    | 
[34mI20190222-09:12:56.236(0) ➔ |        Commit Branch: HEAD                          | 
[34mI20190222-09:12:56.236(0) ➔ |                                                     | 
[34mI20190222-09:12:56.236(0) ➔ +-----------------------------------------------------+ 
[34mI20190222-09:13:17.476(0) Exception while invoking method 'getUsersOfRoom' { MongoError: exception: Unrecognized pipeline stage name: '$lookup'     at queryCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (server/methods/getUsersOfRoom.js:23:11)     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40   errmsg: 'exception: Unrecognized pipeline stage name: \'$lookup\'',   code: 16436,   ok: 0,   name: 'MongoError',   [Symbol(mongoErrorContextSymbol)]: {} } 
```

Client:
```
Exception in delivering result of invoking 'getUsersOfRoom': TypeError: Cannot read property 'records' of undefined
    at o.call (f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:487)
    at n._callback (f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:1)
    at n._maybeInvokeCallback (f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:61)
    at n.receiveResult (f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:61)
    at w._livedata_result (f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:61)
    at w.onMessage (f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:61)
    at currentStatus.connected.forEachCallback.e (f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:59)
    at Array.forEach (<anonymous>)
    at l.forEachCallback (f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:59)
    at k.socket.onmessage.t [as onmessage] (f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:59)
```

**Comment by brase** [comment]
Ahh, I forgot. We are using ldap for authentication.

**Comment by brase** [comment]
Okay, my fault.

MongoDB was too old. Upgraded to 3.2. Not it works again.
