### ISSUE TITLE
PM process errored

### ISSUE THREAD

**Issue by stephenreda** [RocketChat/Rocket.Chat#1355]
After having issues on installing rocketchat on a clean ubuntu 14.04.01 with mongo 3.0.7, I followed the instructions (Update an existing installation with the latest code)

![image](https://cloud.githubusercontent.com/assets/2557554/11014810/b99b0c50-8546-11e5-809d-5a987214258f.png)

When I check the proces, I can see the application is errored
![image](https://cloud.githubusercontent.com/assets/2557554/11014820/fc749f3c-8546-11e5-9650-5c74685a0d17.png)

    cat /var/log/rocket.chat/err-0.log

    Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/var/www/rocket.chat/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/var/www/rocket.chat/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

The only weird thing during the upgrade was an issue with 

    user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.7"

![image](https://cloud.githubusercontent.com/assets/2557554/11014832/911d2604-8547-11e5-9cc8-59b2ac7a0ce6.png)

Any ideas?

**Comment by stephenreda** [comment]
I've solved this since.
I had to delete bcrypt, run npm update (node-gyp!) and then re-install the server.

**Comment by trashcan** [comment]
Thanks I ran into the same problem. 

```
/var/www/rocket.chat/bundle/programs/server/npm/npm-bcrypt# npm update
````
^ resolved it for me
