### ISSUE TITLE
notifications and offline emails are not working

### ISSUE THREAD

**Issue by adispi** [RocketChat/Rocket.Chat#13579]
i am not sure what is happening, but desktop notification test button is grayed out, while it is saying that notifications are on, no notifications, no sounds and no offline emails are being sent from the server.
server ver: 0.74.1
node: v8.11.4
npm: 6.4.1

output of npm v:

meteor-dev-bundle@0.0.0 | Proprietary | deps: 5 | versions: 1

dist
.tarball: https://registry.npmjs.org/meteor-dev-bundle/-/meteor-dev-bundle-0.0.0.tgz
.shasum: ef20333898552a552bc1045e7e700168f1cd71d3
.integrity: sha512-xRyRSrJvmaqjXY573d7/jUdE/WKIxv8Se1+iBR2w0zYLOn/dWXvoFgCn3DnIsh4Zj7zCI8GlqBqY9xI79T5ePA==

dependencies:
fibers: 1.0.8
meteor-promise: 0.5.1
semver: 4.1.0
source-map-support: https://github.com/meteor/node-source-map-support/tarball/1912478769d76e5df4c365e147f25896aee6375e
underscore: 1.5.2

maintainers:
- ruenetwork <rue.network@gmail.com>

dist-tags:
latest: 0.0.0

published a year ago by ruenetwork <rue.network@gmail.com>

log errors:

server logs are full of mongoerror crashes:
[34mI20190227-10:19:01.344(0) Exception in defer callback: { MongoError: exception: Unrecognized pipeline stage name: '$lookup'     at queryCallback (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)     at /home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)  => awaited here:     at Function.Promise.await (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:257:21)     at /home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at RocketChat.callbacks.add (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:316:65)     at callbacks.runItem (packages/rocketchat:callbacks/lib/callbacks.js:73:9)     at Object.callbacks.runItem (packages/rocketchat:metrics/server/callbacksMetrics.js:24:20)     at packages/rocketchat:callbacks/lib/callbacks.js:94:36     at Array.reduce (<anonymous>)     at callbacks.run (packages/rocketchat:callbacks/lib/callbacks.js:91:31)     at Object.callbacks.run (packages/rocketchat:metrics/server/callbacksMetrics.js:14:17)     at Meteor.defer (packages/rocketchat:lib/server/functions/sendMessage.js:192:32)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at packages/meteor.js:620:25     at runWithEnvironment (packages/meteor.js:1356:24)   errmsg: 'exception: Unrecognized pipeline stage name: \'$lookup\'',   code: 16436,   ok: 0,   name: 'MongoError',   [Symbol(mongoErrorContextSymbol)]: {} } 
[34mI20190227-10:19:01.801(0) Exception in defer callback: { MongoError: exception: Unrecognized pipeline stage name: '$lookup'     at queryCallback (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)     at /home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)  => awaited here:     at Function.Promise.await (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:257:21)     at /home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at RocketChat.callbacks.add (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:316:65)     at callbacks.runItem (packages/rocketchat:callbacks/lib/callbacks.js:73:9)     at Object.callbacks.runItem (packages/rocketchat:metrics/server/callbacksMetrics.js:24:20)     at packages/rocketchat:callbacks/lib/callbacks.js:94:36     at Array.reduce (<anonymous>)     at callbacks.run (packages/rocketchat:callbacks/lib/callbacks.js:91:31)     at Object.callbacks.run (packages/rocketchat:metrics/server/callbacksMetrics.js:14:17)     at Meteor.defer (packages/rocketchat:lib/server/functions/sendMessage.js:192:32)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at packages/meteor.js:620:25     at runWithEnvironment (packages/meteor.js:1356:24)   errmsg: 'exception: Unrecognized pipeline stage name: \'$lookup\'',   code: 16436,   ok: 0,   name: 'MongoError',   [Symbol(mongoErrorContextSymbol)]: {} } 
[34mI20190227-10:19:45.168(0) Exception in defer callback: { MongoError: exception: Unrecognized pipeline stage name: '$lookup'     at queryCallback (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)     at /home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)  => awaited here:     at Function.Promise.await (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:257:21)     at /home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at RocketChat.callbacks.add (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:316:65)     at callbacks.runItem (packages/rocketchat:callbacks/lib/callbacks.js:73:9)     at Object.callbacks.runItem (packages/rocketchat:metrics/server/callbacksMetrics.js:24:20)     at packages/rocketchat:callbacks/lib/callbacks.js:94:36     at Array.reduce (<anonymous>)     at callbacks.run (packages/rocketchat:callbacks/lib/callbacks.js:91:31)     at Object.callbacks.run (packages/rocketchat:metrics/server/callbacksMetrics.js:14:17)     at Meteor.defer (packages/rocketchat:lib/server/functions/sendMessage.js:192:32)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at packages/meteor.js:620:25     at runWithEnvironment (packages/meteor.js:1356:24)   errmsg: 'exception: Unrecognized pipeline stage name: \'$lookup\'',   code: 16436,   ok: 0,   name: 'MongoError',   [Symbol(mongoErrorContextSymbol)]: {} } 
[34mI20190227-10:19:50.566(0) Exception in defer callback: { MongoError: exception: Unrecognized pipeline stage name: '$lookup'     at queryCallback (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)     at /home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)  => awaited here:     at Function.Promise.await (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:257:21)     at /home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at RocketChat.callbacks.add (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:316:65)     at callbacks.runItem (packages/rocketchat:callbacks/lib/callbacks.js:73:9)     at Object.callbacks.runItem (packages/rocketchat:metrics/server/callbacksMetrics.js:24:20)     at packages/rocketchat:callbacks/lib/callbacks.js:94:36     at Array.reduce (<anonymous>)     at callbacks.run (packages/rocketchat:callbacks/lib/callbacks.js:91:31)     at Object.callbacks.run (packages/rocketchat:metrics/server/callbacksMetrics.js:14:17)     at Meteor.defer (packages/rocketchat:lib/server/functions/sendMessage.js:192:32)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at packages/meteor.js:620:25     at runWithEnvironment (packages/meteor.js:1356:24)   errmsg: 'exception: Unrecognized pipeline stage name: \'$lookup\'',   code: 16436,   ok: 0,   name: 'MongoError',   [Symbol(mongoErrorContextSymbol)]: {} } 
[34mI20190227-10:20:08.823(0) Exception in defer callback: { MongoError: exception: Unrecognized pipeline stage name: '$lookup'     at queryCallback (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)     at /home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)  => awaited here:     at Function.Promise.await (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:257:21)     at /home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at RocketChat.callbacks.add (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:316:65)     at callbacks.runItem (packages/rocketchat:callbacks/lib/callbacks.js:73:9)     at Object.callbacks.runItem (packages/rocketchat:metrics/server/callbacksMetrics.js:24:20)     at packages/rocketchat:callbacks/lib/callbacks.js:94:36     at Array.reduce (<anonymous>)     at callbacks.run (packages/rocketchat:callbacks/lib/callbacks.js:91:31)     at Object.callbacks.run (packages/rocketchat:metrics/server/callbacksMetrics.js:14:17)     at Meteor.defer (packages/rocketchat:lib/server/functions/sendMessage.js:192:32)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at packages/meteor.js:620:25     at runWithEnvironment (packages/meteor.js:1356:24)   errmsg: 'exception: Unrecognized pipeline stage name: \'$lookup\'',   code: 16436,   ok: 0,   name: 'MongoError',   [Symbol(mongoErrorContextSymbol)]: {} }

**Comment by adispi** [comment]
issue was in wrong version of mongodb
