### ISSUE TITLE
Unable to upload files on snap version of RC

### ISSUE THREAD

**Issue by atsag** [RocketChat/Rocket.Chat#13580]
Installing a snap and then trying to upload a file (I have tried with jpg and pdf) do not work.
Tested in the snap versions provided for Ubuntu 16.04 server and Raspbian 9.
The related error which appears in the logs of the server service itself is the following:

`Feb 27 13:58:22 localhost rocketchat-server.rocketchat-server[1985]: Error: FileNotFound: no file with id GSkEKEQSyjREkBJBH found
Feb 27 13:58:22 localhost rocketchat-server.rocketchat-server[1985]:     at /snap/rocketchat-server/1278/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:190:25
Feb 27 13:58:22 localhost rocketchat-server.rocketchat-server[1985]:     at /snap/rocketchat-server/1278/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1215:18
Feb 27 13:58:22 localhost rocketchat-server.rocketchat-server[1985]:     at handleCallback (/snap/rocketchat-server/1278/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:120:56)
Feb 27 13:58:22 localhost rocketchat-server.rocketchat-server[1985]:     at /snap/rocketchat-server/1278/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1252:5
Feb 27 13:58:22 localhost rocketchat-server.rocketchat-server[1985]:     at /snap/rocketchat-server/1278/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
Feb 27 13:58:22 localhost rocketchat-server.rocketchat-server[1985]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
Feb 27 13:58:22 localhost rocketchat-server.rocketchat-server[1985]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)`

**Comment by atsag** [comment]
Issue continues to be present on snap version 0.74.3, tested on Raspbian 9

**Comment by atsag** [comment]
Issue continues to be present on snap version 1.2.3

**Comment by MrMatthias** [comment]
is there a manual fix?

**Comment by wsnipex** [comment]
this issue is still there on the current stable snap:
rocketchat-server  2.4.14

the issue seem to be the reverse proxy. Opening dev tools in firefox, you can observe the wrong URL being used for the http post request: `http://localhost/ufs/FileSystem:Uploads/TTdTFkCmFnobBna48?token=****&progress=0.03139455117518788`

This is rocketchats internal URL, which is not reachable from outside. Instead the public URL on caddy should be used.
