### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by bazzilio** [RocketChat/Rocket.Chat#13602]
### Description:

I see memory leak on the latest rocket chat  version 0.74.3
How can i debug the root cause of the issue ?

### Expected behavior:

No memory leak :)

### Actual behavior:
![image](https://user-images.githubusercontent.com/13622424/53686630-b4aaca00-3d3a-11e9-8eb3-55b1f08a5c49.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu 18.04.1
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled
- NodeJS Version: v8.11.4
- MongoDB Version: v4.0.5

### Relevant logs:
I see some strange errors, that can be related to the issue:
```
[34mI20190302-14:54:21.610(0) Exception in onLogin callback: TypeError: Cannot redefine property: loginAt     at Function.defineProperty (<anonymous>)     at Object.keys.forEach.p (packages/rocketchat:statistics/server/lib/SAUMonitor.js:279:12)     at Array.forEach (<anonymous>)     at SAUMonitorClass._updateConnectionInfo (packages/rocketchat:statistics/server/lib/SAUMonitor.js:278:22)     at Accounts.onLogin.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:120:9)     at packages/callback-hook/hook.js:130:22     at _onLoginHook.each.callback (packages/accounts-base/accounts_server.js:178:7)     at Hook.each (packages/callback-hook/hook.js:108:15)     at AccountsServer._successfulLogin (packages/accounts-base/accounts_server.js:177:23)     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:350:12)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
```

```
DDP RATE LIMIT: limit by connectionId per method
{
  "allowed": false,
  "timeToReset": 644,
  "numInvocationsLeft": 0,
  "userId": "oetxdmjGiBewXf34T",
  "clientAddress": "172.20.0.2",
  "type": "method",
  "name": "stream-notify-room",
  "connectionId": "rpkiRALqTkoMpSwjz",
  "broadcastAuth": false
}
```

Full logs:
Logs from the server interface: 
[server-rocket.log](https://github.com/RocketChat/Rocket.Chat/files/2922443/server-rocket.log)

Logs from docker container:
[docker-rocket.log](https://github.com/RocketChat/Rocket.Chat/files/2922442/docker-rocket.log)

**Comment by tassoevan** [comment]
The `Exception in onLogin callback: TypeError: Cannot redefine property: loginAt` was solved by #13553, but I'm not sure it is connected somehow.

**Comment by bazzilio** [comment]
Thank you, for quick answer, i'll try update to the master branch and return later.

**Comment by rasos** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/12880 ?

**Comment by bazzilio** [comment]
In #12880 says, that Leak rate seems to correlate with message volume"
In my case i don't see any correlation.

**Comment by izenk** [comment]
Faced with same situation on 0.73.2 (mongo 4.0.5)
docker-compose deployment
50 users, 30 active concurently
Every time after a week of stable work - memory usage increases up 4GB (2GB mongo and 2GB for rchat app).
At the same time [Recommendation](https://rocket.chat/docs/installation/minimum-requirements/#vps-recommended) says that 2GB should be enough for my situation

**Comment by dhoeld** [comment]
Same problem here. There is a restart for any of our 3 Rocket.Chat replicas on our Kubernetes Cluster every night due to "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory"

We also got these strange errors mentioned above in our logs.

**Comment by cortex3** [comment]
same here, using CentOS 7, rocketchat 0.73.2, mongodb 4.0.5, node 8.11.4 and 2 instances on the same host. Restarting the service resolves the problem for a while.
![rock](https://user-images.githubusercontent.com/10298122/56577947-a5265f80-65cc-11e9-8b6b-c6415a58e689.jpg)

**Comment by ninghao** [comment]
i had the same problem.

**Comment by reetp** [comment]
Please test on latest v1.1.1

**Comment by engelgabriel** [comment]
HI @bazzilio @rasos @ninghao are you still experiencing this issue with the latest verions?

**Comment by fcoppolani** [comment]
We have the same problem with 1.2.3, we are going to upgrade to 2.1 soon to check this issue.

**Comment by UAnton** [comment]
I had the same problem with Snap 2.4.2

**Comment by pawadski** [comment]
Potentially same problem with 3.0.3, NodeJS memory usage really high. Below Grafana screenshot of NodeJS memory exported by Prometheus exporter (enabled in Logs). We have 4 RocketChat instances and below picture shows one of them using up considerably more memory.

![image](https://user-images.githubusercontent.com/30628565/84032159-31454300-a997-11ea-9f8c-8bb1c323a65e.png)

**Comment by Bengrunt** [comment]
Hello there, still seeing the memory leak on our 3.12 instances.

I know this kind of issue is always hard to fix but is there any hope in this getting fixed sometime soon or do we invest time in countermeasures on the deployment side?
If anyone has feedback on this I'd be glad to read it :)

**Comment by ThrowAwayDan** [comment]
Issue persists. Just noticed that RC server takes an insane amount of memory.
Found out about this when I tried to activate jitsi on the marketplace, which pushed it over the edge. 

![image](https://github.com/RocketChat/Rocket.Chat/assets/88100113/511c7eac-d6da-48f8-a7f0-cf42ea5b7b3f)
