### ISSUE TITLE
TypeError: createJSAccountsGraphQL is not a function

### ISSUE THREAD

**Issue by SiJinmin** [RocketChat/Rocket.Chat#13759]
### Description:

when i run "meteor npm start", i got an error, here is the output:

```
jianyin@jianyinubt:~/Documents/Rocket.Chat$ meteor npm start

> Rocket.Chat@1.0.0-develop start /home/jianyin/Documents/Rocket.Chat
> meteor

[[[[[ ~/Documents/Rocket.Chat ]]]]]

=> Started proxy.
tap-i18n-compiler: updating npm dependencies -- yamljs...
=> Started MongoDB.
Livechat: updating npm dependencies -- shelljs, uglify-js...
Linking |
> bcrypt@3.0.2 install /home/jianyin/Documents/Rocket.Chat/packages/rocketchat-livechat/.app/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[bcrypt] Success: "/home/jianyin/Documents/Rocket.Chat/packages/rocketchat-livechat/.app/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
added 181 packages from 126 contributors and audited 624 packages in 5.886s
found 0 vulnerabilities

Installing new Livechat...
WARNING: npm peer requirements (for juliancwirko:postcss) not installed:
- postcss@7.0.14 installed, postcss@^6.0.22 needed
- postcss-load-config@2.0.0 installed, postcss-load-config@^1.2.0 needed

Read more about installing npm peer dependencies:
http://guide.meteor.com/using-packages.html#peer-npm-dependencies

=> It looks like a simple tweak to your system's configuration will make many tools (including this
Meteor command) more efficient. To learn more, see
https://github.com/meteor/docs/blob/master/long-form/file-change-watcher-efficiency.md
I20190318-12:17:11.703(8)? LocalStore: store created at
I20190318-12:17:11.786(8)? LocalStore: store created at
I20190318-12:17:11.787(8)? LocalStore: store created at
I20190318-12:17:12.195(8)? Setting default file store to GridFS
I20190318-12:17:25.887(8)? Exception in callback of async function: TypeError: createJSAccountsGraphQL is not a function
I20190318-12:17:25.889(8)? at createJSAccountsGraphQL (/home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/app/meteor:/💻app/app/graphql/server/resolvers/accounts/index.js:10:25)
I20190318-12:17:25.889(8)? at fileEvaluate (packages/modules-runtime.js:336:7)
I20190318-12:17:25.890(8)? at Module.require (packages/modules-runtime.js:238:14)
I20190318-12:17:25.890(8)? at Module.moduleLink [as link] (/home/jianyin/.meteor/packages/modules/.0.13.0.176lf51.fi71++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
I20190318-12:17:25.891(8)? at link (/home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/app/meteor:/💻app/app/graphql/server/schema.js:1:461)
I20190318-12:17:25.891(8)? at fileEvaluate (packages/modules-runtime.js:336:7)
I20190318-12:17:25.891(8)? at Module.require (packages/modules-runtime.js:238:14)
I20190318-12:17:25.891(8)? at Module.moduleLink [as link] (/home/jianyin/.meteor/packages/modules/.0.13.0.176lf51.fi71++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
I20190318-12:17:25.891(8)? at link (/home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/app/meteor:/💻app/app/graphql/server/api.js:1:877)
I20190318-12:17:25.892(8)? at fileEvaluate (packages/modules-runtime.js:336:7)
I20190318-12:17:25.892(8)? at Module.require (packages/modules-runtime.js:238:14)
I20190318-12:17:25.892(8)? at Module.moduleLink [as link] (/home/jianyin/.meteor/packages/modules/.0.13.0.176lf51.fi71++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
I20190318-12:17:25.892(8)? at link (/home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/app/meteor:/💻app/app/graphql/server/index.js:1:34)
I20190318-12:17:25.893(8)? at fileEvaluate (packages/modules-runtime.js:336:7)
I20190318-12:17:25.893(8)? at Module.require (packages/modules-runtime.js:238:14)
I20190318-12:17:25.893(8)? at require (packages/modules-runtime.js:258:21)
I20190318-12:17:25.893(8)? at require (/home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/app/meteor:/💻app/app/graphql/index.js:4:19)
I20190318-12:17:25.894(8)? at fileEvaluate (packages/modules-runtime.js:336:7)
I20190318-12:17:25.894(8)? at Module.require (packages/modules-runtime.js:238:14)
I20190318-12:17:25.894(8)? at Module.moduleLink [as link] (/home/jianyin/.meteor/packages/modules/.0.13.0.176lf51.fi71++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
I20190318-12:17:25.894(8)? at link (/home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/app/meteor:/💻app/server/importPackages.js:1:1147)
I20190318-12:17:25.895(8)? at fileEvaluate (packages/modules-runtime.js:336:7)
I20190318-12:17:25.895(8)? at Module.require (packages/modules-runtime.js:238:14)
I20190318-12:17:25.895(8)? at Module.moduleLink [as link] (/home/jianyin/.meteor/packages/modules/.0.13.0.176lf51.fi71++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
I20190318-12:17:25.895(8)? at link (/home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/app/meteor:/💻app/server/main.js:1:8)
I20190318-12:17:25.896(8)? at fileEvaluate (packages/modules-runtime.js:336:7)
I20190318-12:17:25.896(8)? at Module.require (packages/modules-runtime.js:238:14)
I20190318-12:17:25.896(8)? at require (packages/modules-runtime.js:258:21)
I20190318-12:17:25.896(8)? at /home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/app/app.js:132774:15
I20190318-12:17:25.896(8)? at /home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/boot.js:411:36
I20190318-12:17:25.897(8)? at Array.forEach (<anonymous>)
I20190318-12:17:25.897(8)? at /home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/boot.js:220:19
I20190318-12:17:25.897(8)? at /home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/boot.js:471:5
I20190318-12:17:25.897(8)? at Function.run (/home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/profile.js:510:12)
I20190318-12:17:25.898(8)? at /home/jianyin/Documents/Rocket.Chat/.meteor/local/build/programs/server/boot.js:470:11
```

### Steps to reproduce:

1. install tools required
$ sudo apt install g++ build-essential git mongodb curl python-minimal capnproto libcapnp-dev

2. install nvm
$ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
then close the teminal and reopen it to enable nvm command

3. install node
$ nvm install 8.11.4
$ node -v
it should output "v8.11.4"

4. install meteor
$ curl https://install.meteor.com/ | sh

5. get rocket.chat code
$ git clone https://github.com/RocketChat/Rocket.Chat.git

6. install modules
$ cd Rocket.Chat
$ meteor npm install

7. do post install work
$ meteor npm run postinstall
$ meteor npm install sharp chai webpack postcss postcss-syntax postcss-load-config fibers capnp bcrypt graphql-tag graphql-tools reflect-metadata @graphql-modules/core @accounts/server @accounts/password @accounts/types @accounts/common
$ meteor npm audit fix

8. start rocket.chat
$ meteor npm start

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Additional context

my os is ubuntu 18.04, amd64

### Relevant logs:

jianyin@jianyinubt:~/Documents/Rocket.Chat$ meteor npm audit fix
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN @accounts/mongo@0.0.12 requires a peer of @accounts/common@^0.0.10 but none is installed. You must install peer dependencies yourself.
npm WARN @accounts/mongo@0.0.12 requires a peer of @accounts/server@^0.0.10 but none is installed. You must install peer dependencies yourself.
npm WARN @accounts/password@0.13.0 requires a peer of @accounts/server@^0.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-toolkit@0.2.6 requires a peer of graphql-tools@4.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN @accounts/graphql-api@0.13.0 requires a peer of @accounts/password@^0.9.3 but none is installed. You must install peer dependencies yourself.
npm WARN @accounts/graphql-api@0.13.0 requires a peer of @accounts/server@^0.9.3 but none is installed. You must install peer dependencies yourself.
npm WARN @accounts/graphql-api@0.13.0 requires a peer of @accounts/types@^0.9.3 but none is installed. You must install peer dependencies yourself.
npm WARN @accounts/graphql-api@0.13.0 requires a peer of @graphql-modules/core@0.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN @accounts/graphql-api@0.13.0 requires a peer of graphql-tools@^4.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @accounts/server@0.13.0
+ express-session@1.15.6
+ @accounts/graphql-api@0.13.0
added 15 packages from 57 contributors, removed 19 packages and updated 5 packages in 22.041s
fixed 21 of 114 vulnerabilities in 22799 scanned packages
89 vulnerabilities required manual review and could not be updated
1 package update for 4 vulns involved breaking changes
(use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/14959
