### ISSUE TITLE
$lookup error in Rocketchat 0.74.1

### ISSUE THREAD

**Issue by zenjabba** [RocketChat/Rocket.Chat#13768]
### Description:

Every line a user types in creating this error in the logs

### Expected behavior:

Not to create the error in the logs

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.1
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled
- NodeJS Version: v8.11.4
- MongoDB Version: mongo:3.0 docker

### Relevant logs:

```
Exception in defer callback: { MongoError: exception: Unrecognized pipeline stage name: '$lookup'
    at queryCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at Promise.asyncApply (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:257:21)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at RocketChat.callbacks.add (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:316:65)
    at callbacks.runItem (packages/rocketchat:callbacks/lib/callbacks.js:73:9)
    at Object.callbacks.runItem (packages/rocketchat:metrics/server/callbacksMetrics.js:24:20)
 packages/rocketchat:callbacks/lib/callbacks.js:94:36
    at Array.reduce (<anonymous>)
    at callbacks.run (packages/rocketchat:callbacks/lib/callbacks.js:91:31)
    at Object.callbacks.run (packages/rocketchat:metrics/server/callbacksMetrics.js:14:17)
    at Meteor.defer (packages/rocketchat:lib/server/functions/sendMessage.js:192:32)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at packages/meteor.js:620:25
    at runWithEnvironment (packages/meteor.js:1356:24)
  errmsg: 'exception: Unrecognized pipeline stage name: \'$lookup\'',
  code: 16436,
  ok: 0,
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }

```

**Comment by geekgonecrazy** [comment]
I believe updating to Mongodb 3.2 will solve this

**Comment by zenjabba** [comment]
Thanks
