### ISSUE TITLE
Desktop Notifications

### ISSUE THREAD

**Issue by jerrylanejohns** [RocketChat/Rocket.Chat#13813]
We’re using latest versions of both server and desktop client. Client running Windows 10. Default and personal settings to show notifications for everything and to show for 30 seconds. However, no notification pop up appears in the lower right corner. I assume it should appear like other “notifications” in Windows 10. I should be able to click on the notifications icon in the tray and see RC notifications like show for Outlook and other programs. Any help is appreciated!!

**Comment by mmcconnell535** [comment]
We too are experiencing this issue.  Prior to release the iOS app was capable of reading messages but not sending messages -- now upon update, the messages send fine and it will show the number of new messages next to the account name that sent the message, but no audio plays and no notification triggers.   

This happens on the App, Web Client and Desktop Client.  If we manually go the user settings page and change the audio from default to "none" then back to default, the audio plays normally, but this does not fix the issue.  We have also experimented with additional desktop notification settings to no avail.

Desktop Client: 2.15.0 
Note: 2.15.1 is available but does not do anything when I select "install update."  

Server : 0.74.3

**Comment by krispayne** [comment]
not getting notifications on mac client 2.15.1 after updating. It also doesn't forward notifications to iOS client anymore. i.e. I stepped out for lunch and came back to several un-notified chats on my computer, but previously would get them on my phone after the timeout.

**Comment by reetp** [comment]
Please all of you **fill out a proper bug report template**. There are too many variables here to pin down any issues. Just saying 'me too' is not helping anyone.

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Are you all running the same server version, and same type of deployment eg snap/docker/whatever?

Has anyone actually looked in their server logs to see what Rocket is saying it is or isn't doing ?

Have a run through here for notification logic and see if you can try to narrow down your own issue.
https://whimsical.co/Bngw3kot3wWPMAAJTebDUJ

Please don't confuse the issues - it could be the Windows program has an problem (which should go in the Electron repo), or the IOS app etc. but not Rocket, in which case open them in the appropriate place.

**Comment by mmcconnell535** [comment]
### Description:

Chat messages fail to trigger notification, sound, or forward to email / mobile after server upgrade to 0.74.3.  The number of messages received indicator for a non-active message will show, but no audio or notification triggers.    `@all` and `@user` messages also fail to display notification, play sound or send email / to mobile. 

### Steps to reproduce:

1. Upgrade server to 0.74.3
2. Receive any message and/or mention (User1 to User2, User1 to User1, User1 to Room, `@all`, `@user`, etc.)

### Expected behavior:

If notifications and sounds are enabled, the expectation is that a sound plays and the desktop notification displays.   If the message is missed the message should forward to email / mobile device.

### Actual behavior:
No sound plays, No Notification Plays, No Forwarding occurs.

### Server Setup Information:

- Version of Rocket.Chat Server:  0.74.3
- Operating System:  CentOS 7.6.1810
- Deployment Method: TAR
- Number of Running Instances:  1
- DB Replicaset Oplog: OpLog disabled – (Can we enable briefly and attach log?)
- NodeJS Version:  8.11.4
- MongoDB Version: 2.6.12-1
- NPM Version: 6.4.1

### Additional context

This occurs on all devices, iOS, Android, Windows 10 Desktop Application, Web Browser (Google Chrome / Firefox).  None of our registered users are receiving notifications of any kind or audio of any kind.  It has greatly impacted the usage of our RocketChat instance.

From User Preferences are:
Test Desktop Notifications **does** trigger a notification firing.
Changing the sound from “Default” to “none” then back to “Default” **does** trigger the sound playing

### Relevant logs:

Browser console reports no errors, warnings or notices.

Server Logs are full of the below notice.  I did watch the log while sending a direct message to myself and it produced the following: 

`Exception in defer callback: { MongoError: exception: Unrecognized pipeline stage name: '$lookup'     at queryCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:257:21)     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at RocketChat.callbacks.add (packages/rocketchat:lib/server/lib/sendNotificationsOnMessage.js:316:65)     at callbacks.runItem (packages/rocketchat:callbacks/lib/callbacks.js:73:9)     at Object.callbacks.runItem (packages/rocketchat:metrics/server/callbacksMetrics.js:24:20)     at packages/rocketchat:callbacks/lib/callbacks.js:94:36     at Array.reduce (<anonymous>)     at callbacks.run (packages/rocketchat:callbacks/lib/callbacks.js:91:31)     at Object.callbacks.run (packages/rocketchat:metrics/server/callbacksMetrics.js:14:17)     at Meteor.defer (packages/rocketchat:lib/server/functions/sendMessage.js:192:32)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at packages/meteor.js:620:25     at runWithEnvironment (packages/meteor.js:1356:24)   errmsg: 'exception: Unrecognized pipeline stage name: \'$lookup\'',   code: 16436,   ok: 0,   name: 'MongoError',   [Symbol(mongoErrorContextSymbol)]: {} } `

Error log goes back to 6th of this month, if requested I can post the full contents.

**Comment by mmcconnell535** [comment]
Not sure if this will fix for all or not, but in our troubleshooting we determined that our MongoDB release on CentOS 7 was the the problem here.    The default CentOS repo was utilizing MongoDB at 2.6.12-1

Notifications began working again after **upgrading to at least MongoDB 3.2**  

After the upgrade, all clients (web, desktop app, iOS app, Android app) had to be restarted to begin showing notifications, but sound, notification pop over and email all are working as expected.

**Comment by reetp** [comment]
Check the releases page for the software versions required

https://github.com/RocketChat/Rocket.Chat/releases

Rocket 0.74.3 and Development 1.0.0-beta.2

Node: 8.11.4
NPM: 6.4.1
MongoDB: 3.2, 3.4, 3.6, 4.0

**Comment by mmcconnell535** [comment]
Understood, would it be possible for the update to do a dependency check and throw a warning or notice if the versions are below requirement? 

For us, I suspect that when this was initially installed it met the requirements, but over time as the dependencies changed it became out of sync on our end.

**Comment by geekgonecrazy** [comment]
@mmcconnell535 ❤️ thanks for posting your server info like that.  It really does make a world of difference in solving the issue as you see here we could see the problem. :grin:


@jerrylanejohns can you post the server info also?
