### ISSUE TITLE
Internal server error uploading .jpeg or .PNG

### ISSUE THREAD

**Issue by mouragio** [RocketChat/Rocket.Chat#13847]
### Description:
When I try to upload an image file (jpg or PNG) I get an internal server error.

### Steps to reproduce:
Upload an image

### Expected behavior:
I would expect the image would be uploaded

### Actual behavior:
It doesnt

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 
- DB Replicaset Oplog: Mongo
- NodeJS Version: v8.11.4
--
- MongoDB Version: v3.4.20

### Additional context
I can upload every other document (pdf, docx, even gif can be uploaded.

### Relevant logs:

The error I get when uploading a jpeg file:

```
Mar 22 08:31:38 server1 rocketchat: Error: FileNotFound: no file with id MQRpXGkThgGqjkEtS found
Mar 22 08:31:38 server1 rocketchat: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:188:25
Mar 22 08:31:38 server1 rocketchat: at result (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:414:17)
Mar 22 08:31:38 server1 rocketchat: at executeCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:406:9)
Mar 22 08:31:38 server1 rocketchat: at deleteCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:329:17)
Mar 22 08:31:38 server1 rocketchat: at removeDocuments (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:344:54)
Mar 22 08:31:38 server1 rocketchat: at handleCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:128:55)
Mar 22 08:31:38 server1 rocketchat: at coll.s.topology.remove (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:1168:5)
Mar 22 08:31:38 server1 rocketchat: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
Mar 22 08:31:38 server1 rocketchat: at _combinedTickCallback (internal/process/next_tick.js:132:7)
Mar 22 08:31:38 server1 rocketchat: at process._tickDomainCallback (internal/process/next_tick.js:219:9)
Mar 22 08:31:38 server1 rocketchat: Exception while invoking method 'ufsComplete' TypeError: sharp is not a function
Mar 22 08:31:38 server1 rocketchat: at LocalStore.uploadsOnValidate [as onValidate] (packages/rocketchat:file-upload/server/lib/FileUpload.js:160:13)
Mar 22 08:31:38 server1 rocketchat: at LocalStore.validate (packages/jalik:ufs/ufs-store.js:597:18)
Mar 22 08:31:38 server1 rocketchat: at MethodInvocation.ufsComplete (packages/jalik:ufs/ufs-methods.js:79:23)
Mar 22 08:31:38 server1 rocketchat: at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
Mar 22 08:31:38 server1 rocketchat: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
Mar 22 08:31:38 server1 rocketchat: at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
Mar 22 08:31:38 server1 rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
Mar 22 08:31:38 server1 rocketchat: at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
Mar 22 08:31:38 server1 rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
Mar 22 08:31:38 server1 rocketchat: at Promise (packages/ddp-server/livedata_server.js:715:46)
Mar 22 08:31:38 server1 rocketchat: at new Promise (<anonymous>)
Mar 22 08:31:38 server1 rocketchat: at Session.method (packages/ddp-server/livedata_server.js:689:23)
Mar 22 08:31:38 server1 rocketchat: at packages/ddp-server/livedata_server.js:559:43
```

![image](https://user-images.githubusercontent.com/48808712/54810114-88250680-4c85-11e9-8b96-7eaaccb2d7dd.png)

It looks like "sharp" could be causing this.. but thats just a guess.. Can someone give me a hint where to look or is it possible to disable resizing of the images? I had the same problem with avatars (when resizing is on the avatar isnt changed) But in the settings you can disable avatar resizing.. and that solved the avatar issue.

**Comment by engelgabriel** [comment]
@sampaiodiego @rodrigogs do you have any info on problems with "sharp"?

**Comment by mouragio** [comment]
btw..
The error "sharp is not a function" is displayed when uploading from the mobile app (ios)

and in the errorlog above there is the error:
Exception while invoking method 'ufsComplete' TypeError: sharp is not a function

**Comment by geekgonecrazy** [comment]
Typically when sharp isn't working right on centos its this issue: https://github.com/RocketChat/Rocket.Chat/issues/12788

@mouragio can you check: /opt/Rocket.Chat/programs/server/npm/node_modules and see if sharp is in there?

**Comment by mouragio** [comment]
hi, thanx for the reply.

I checked, but no, there is no sharp in the directory /opt/Rocket.Chat/programs/server/npm/node_modules....

the places where sharp is resided:
/opt/Rocket.Chat/node_modules/sharp
/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/sharp
/opt/Rocket.Chat/programs/server/node_modules/sharp
/usr/local/lib/node_modules/sharp

Also checked the ZLIB versions:
strings /lib64/libz.so.1 | grep ZLIB
ZLIB_1.2.0
ZLIB_1.2.0.2
ZLIB_1.2.0.8
ZLIB_1.2.2
ZLIB_1.2.2.3
ZLIB_1.2.2.4
ZLIB_1.2.3.3
ZLIB_1.2.3.4
ZLIB_1.2.3.5
ZLIB_1.2.5.1
ZLIB_1.2.5.2

same as issue: #12788... so hence I need ZLIB version version ZLIB_1.2.9? hmm..

**Comment by paolo050181** [comment]
Hello, 
I cannot upload image the debug error when i try is:
API ➔ debug POST: /api/v1/rooms.upload/rAkEiEbmzPWRdPC6k
Meteor ➔ method canAccessRoom -> userId: 6Q7PvzYcaktD56Jwb, arguments: ["rAkEiEbmzPWRdPC6k","6Q7PvzYcaktD56Jwb"]
Error: FileNotFound: no file with id cJtg56H5ZCDf49eyZ found
    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:188:25
    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:410:17
    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:398:11
    at ClientSession.endSession (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sessions.js:134:41)
    at executeCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:395:17)
    at deleteCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:349:17)
    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:364:54
    at handleCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:128:55)
    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:1259:5
    at handler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:1155:22)
    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:397:18
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
API ➔ debug post rooms.upload/:rid threw an error: TypeError: sharp is not a function
    at LocalStore.uploadsOnValidate [as onValidate] (app/file-upload/server/lib/FileUpload.js:232:13)
    at LocalStore.validate (packages/jalik:ufs/ufs-store.js:597:18)
    at MethodInvocation.ufsComplete (packages/jalik:ufs/ufs-methods.js:79:23)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at FileUploadClass._doInsert (app/file-upload/server/lib/FileUpload.js:513:24)
    at FileUploadClass.insert (app/file-upload/server/lib/FileUpload.js:538:15)
    at FileUploadClass.insertSync (packages/meteor.js:306:21)
    at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/rooms.js:122:35)
    at packages/dispatch_run-as-user.js:211:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
    at Object.post (app/api/server/v1/rooms.js:120:27)
    at app/api/server/api.js:343:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
 => awaited here:
    at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at FileUploadClass._doInsert (app/file-upload/server/lib/FileUpload.js:513:24)
    at FileUploadClass.insert (app/file-upload/server/lib/FileUpload.js:538:15)
    at FileUploadClass.insertSync (packages/meteor.js:306:21)
    at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/rooms.js:122:35)
    at packages/dispatch_run-as-user.js:211:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
    at Object.post (app/api/server/v1/rooms.js:120:27)
    at app/api/server/api.js:343:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
API ➔ debug Failure {
  statusCode: 400,
  body: {
    success: false,
    error: 'sharp is not a function',
    stack: undefined
  }
}
i have a problem only for pic, video and pdf work correctly.
Some information:
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.4 LTS
Release: 18.04
Codename: bionic

 Rocket.Chat Version: 3.0.12                         |
 NodeJS Version: 12.14.0 - arm64               
MongoDB Version: 4.2.5                         
MongoDB Engine: wiredTiger                    
Platform: linux                         
 Process Port: 3000                          
 Site URL: http://xxx.xxxx.it/ 
ReplicaSet OpLog: Enabled                       
 Commit Hash: 15ac7670be                    
Commit Branch: HEAD            
Could you help me?
Regards
Paolo

**Comment by sampaiodiego** [comment]
@paolo050181 are your NodeJS really arm64? looks like you're missing `sharp` too.. how is your rocket.chat deployed? via docker, snap or manual? can you pls describe the deployment steps?

**Comment by paolo050181** [comment]
hi @sampaiodiego i installed the Riot/Web and solved the problem.
Regards
Paolo

**Comment by bbraybrook-tc** [comment]
this really does happen on arm64.

the problem is that the rocketchat tarball contains bundle/programs/server/npm/node_modules/sharp/vendor/lib/ filled with a bunch of libraries for x86. when npm tries to install, it gets errors on those and sharp ends up not being configured correctly. (i suspect this happens to any non-x86 architecture)

if that vendor dir is removed prior to building, sharp will go and fetch a new libvips tarball (the lib it has trouble linking) and recompile everything it needs.

curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
tar -xzf /tmp/rocket.chat.tgz -C /tmp
cd /tmp/bundle/programs/server && rm -rf npm/node_modules/sharp/vendor/ && npm install
sudo mv /tmp/bundle /opt/Rocket.Chat
