### ISSUE TITLE
Issues for setup in windows from meteor

### ISSUE THREAD

**Issue by Srinivasan2017** [RocketChat/Rocket.Chat#14157]
We are utilizing the rocketchat source code for chat solutions. 

When we trying to build the dev environment windows, we get the below error

C:\Users\s.gurukannan\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
throw error;
^

Error: ENOENT: no such file or directory, open 'C:\Users\S80F7~1.GUR\AppData\Local\Temp\mt-t258bq.5uad\os\konecty:user-presence-tests.js'
at Object.fs.openSync (fs.js:646:18)
at Object.wrapper [as open] (C:\tools\fs\files.js:1641:35)
at Object.files.readBufferWithLengthAndOffset (C:\tools\fs\files.js:1887:20)
at C:\tools\isobuild\unibuild.js:122:26
at Array.forEach (<anonymous>)
at Function._.each._.forEach (C:\Users\s.gurukannan\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
at Function.fromJSON (C:\tools\isobuild\unibuild.js:119:7)
at C:\tools\isobuild\isopack.js:921:33
at Array.forEach (<anonymous>)
at Function._.each._.forEach (C:\Users\s.gurukannan\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:908:7)
at _.each (C:\tools\packaging\tropohouse.js:521:21)
at Array.forEach (<anonymous>)
at Function._.each._.forEach (C:\Users\s.gurukannan\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
at buildmessage.enterJob (C:\tools\packaging\tropohouse.js:520:13)
at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
at C:\tools\packaging\tropohouse.js:515:22
at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
at Object.download (C:\tools\packaging\tropohouse.js:427:20)
at C:\tools\packaging\tropohouse.js:600:22
at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
at exports.Tropohouse.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:597:20)
at C:\tools\project-context.js:836:25
at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
at C:\tools\project-context.js:835:20
at C:\tools\packaging\catalog\catalog.js💯5
at Object.capture (C:\tools\utils\buildmessage.js:283:5)
at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:834:13)
at C:\tools\project-context.js:300:9
at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
at ProjectContext._completeStagesThrough (C:\tools\project-context.js:290:18)
at Profile.run (C:\tools\project-context.js:282:12)
at Function.run (C:\tools\tool-env\profile.js:490:12)
at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:281:13)
at C:\tools\cli\commands-packages.js:1610:20
at Object.capture (C:\tools\utils\buildmessage.js:283:5)
at Object.main.captureAndExit (C:\tools\cli\main.js:275:29)
at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1609:8)
at Command.func (C:\tools\cli\commands-packages.js:1683:29)
at C:\tools\cli\main.js:1531:15

on analysis we noticed, the AppData\Local\Temp\mt-t258bq.5uad\os\ --

on analysis, we find the folder always empty, we tried meteor reinstall too . but that didnt help

**Comment by Srinivasan2017** [comment]
![image](https://user-images.githubusercontent.com/11881505/56212442-a957f780-6077-11e9-9cff-e8ba851ef71d.png)

**Comment by tassoevan** [comment]
I'm closing it due to our recommendations: https://rocket.chat/docs/developer-guides/quick-start/#on-windows.
