### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by adrianovieira** [RocketChat/Rocket.Chat#14186]
### Description:

UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded

### Steps to reproduce:

`#  service (re)start rocketchat`

### Expected behavior:

No log errors

### Actual behavior:

Error logging

- main one

```
UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
```

- consequent one

```
journal: Suppressed 54675 messages from /system.slice/rocketchat.service
```

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Red Hat 7.6
- Deployment Method: manual (via your CentOS documentation manual)
- Number of Running Instances: Just one
- DB Replicaset Oplog: Disabled
- NodeJS Version: 8.11.4
- MongoDB Version: MongoDB shell version v3.6.12

### Additional context

- Webdav Integration Enabled: **Yes**

### Relevant logs:

`[..]` => a lot of suppressed equals lines

```
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ System ➔ startup
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ +-------------------------------------------------+
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |                  SERVER RUNNING                 |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ +-------------------------------------------------+
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |                                                 |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |  Rocket.Chat Version: 0.74.3                    |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |       NodeJS Version: 8.11.4 - x64              |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |             Platform: linux                     |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |         Process Port: 3000                      |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |             Site URL: https://chat.local/       |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |     ReplicaSet OpLog: Disabled                  |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |          Commit Hash: 202a465f1c                |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |        Commit Branch: HEAD                      |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |                                                 |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ +-------------------------------------------------+
    Apr 18 13:10:41 rkt-server.local rocketchat: (node:18168) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    Apr 18 13:10:41 rkt-server.local rocketchat: at Array.forEach (<anonymous>)
    Apr 18 13:10:41 rkt-server.local rocketchat: at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
    Apr 18 13:10:41 rkt-server.local rocketchat: at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
    Apr 18 13:10:41 rkt-server.local rocketchat: at Array.forEach (<anonymous>)
    Apr 18 13:10:41 rkt-server.local rocketchat: at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
    Apr 18 13:10:41 rkt-server.local rocketchat: at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
    Apr 18 13:10:41 rkt-server.local rocketchat: at Array.forEach (<anonymous>)
    [..]
    Apr 18 13:10:42 rkt-server.local rocketchat: at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
    Apr 18 13:10:42 rkt-server.local rocketchat: at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
==> Apr 18 13:44:46 rkt-server.local journal: Suppressed 54675 messages from /system.slice/rocketchat.service
    Apr 18 13:44:46 rkt-server.local rocketchat: (node:18168) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    Apr 18 13:44:46 rkt-server.local rocketchat: at Array.forEach (<anonymous>)
    [..]
    Apr 18 13:44:47 rkt-server.local rocketchat: at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
    Apr 18 13:44:47 rkt-server.local rocketchat: at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
    Apr 18 13:44:47 rkt-server.local rocketchat: at Array.forEach (<anonymous>)
    Apr 18 13:44:47 rkt-server.local rocketchat: at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
    Apr 18 13:44:47 rkt-server.local rocketchat: at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
```

**Comment by adrianovieira** [comment]
It appears that it has another consequence...

rocket.chat craches. So, we need to restart both services rocketchat and httpd

**Comment by adrianovieira** [comment]
It crached at last 4 times so far!

**Comment by adrianovieira** [comment]
Wow!
That was our issue.

After disabling WebDAV integration our rocketchat environment becomes stable again.

Thank you all.
