### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by hypery2k** [RocketChat/Rocket.Chat#14231]
### Description:

Using latest develop branch docker image on our preview system and upgraded it with latest image results in error
### Steps to reproduce:

1. Deploy develop branch
2. Redeploy after changes on develop branch

### Expected behavior:

Works ;)

### Actual behavior:

Getting this error:
```
TypeError: Cannot read property '0' of undefined
    at retrieveRegistrationStatus (app/cloud/server/functions/retrieveRegistrationStatus.js:16:28)
    at getWorkspaceAccessToken (app/cloud/server/functions/getWorkspaceAccessToken.js:11:50)
    at index.js (app/cloud/server/index.js:12:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at rest.js (app/apps/server/communication/rest.js:1:320)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (app/apps/server/communication/index.js:1:271)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at orchestrator.js (app/apps/server/orchestrator.js:1:534)
    at fileEvaluate (packages/modules-runtime.js:336:7)
```

### Server Setup Information:

- Version of Rocket.Chat Server: develop branch of docker image
- Operating System: Debian 9
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: n.a.
- NodeJS Version: n.a. (in docker included)
- MongoDB Version: 4.0.9

**Comment by geekgonecrazy** [comment]
What commit? Also do you know if this was registered or unregistered? Was this an upgrade from a previous version when you got this?  If so what version?

**Comment by hypery2k** [comment]
not really sure which commit. Hat it twice. Each time I use the latest develop version. When I drop the data_dir of the mongo container all is working again

**Comment by geekgonecrazy** [comment]
going to attempt to reproduce this.  Definitely do not want this happening.  

But would be good to know if you did anything different in register

**Comment by hypery2k** [comment]
in the above repo you'll find a sample project which is getting the same issue. 

HTH

**Comment by geekgonecrazy** [comment]
This should be resolved now.  Please let me know if you get this again

**Comment by hypery2k** [comment]
still having the same issue with develop and rc4

**Comment by geekgonecrazy** [comment]
@hypery2k

Can you DM me on our community server?

https://open.rocket.chat/direct/aaron.ogle

I have a feeling being on dev branch some how state got messed up.  

I can help get it sorted.  Thanks!

**Comment by kvaps** [comment]
Hey, how did you solve this?

**Comment by kvaps** [comment]
I have this issue on `v1.0.0`
