### ISSUE TITLE
[sandstorm] TypeError: Cannot read property 'collectionName' of undefined

### ISSUE THREAD

**Issue by neynah** [RocketChat/Rocket.Chat#1423]
Grain crashes periodically.

/programs/server/packages/monbro_mongodb-mapreduce-aggregation.js:57
      collectionName: result.collectionName,
                            ^
TypeError: Cannot read property 'collectionName' of undefined
    at packages/monbro:mongodb-mapreduce-aggregation/server.coffee:42:36
    at /programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/collection/aggregation.js:86:20
    at [object Object].<anonymous> (/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1903:9)
    at [object Object].g (events.js:180:16)
    at [object Object].emit (events.js:98:17)
    at Server.Base.__executeAllCallbacksWithError (/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:346:25)
    at [object Object].<anonymous> (/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:617:14)
    at [object Object].emit (events.js:92:17)
    at [object Object].<anonymous> (/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:171:15)
    at [object Object].emit (events.js:98:17)
** HTTP-BRIDGE: App server exited with status code: 8
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain.

**Comment by engelgabriel** [comment]
@neynah do we know what version of RC was this? Is this the one on the App Market or downloaded from https://s3.amazonaws.com/rocketchatbuild/rocket.chat.latest.spk ?

**Comment by neynah** [comment]
0.6 from the App Market

**Comment by engelgabriel** [comment]
OK, we need to test with the new SPK and check if that still happens. We may wait until we fix some other bugs before we publish to the  App Market.

**Comment by neynah** [comment]
Great, thanks! :D

**Comment by engelgabriel** [comment]
Hi @neynah the Rocket.Chat SPK have been updated! Can you install a new grain and check if the problem has been fixed?

**Comment by neynah** [comment]
Hi @engelgabriel,

It appears to be fixed for now. I'll let you know if this issue comes up again. Thanks!
