### ISSUE TITLE
meteor npm install has error

### ISSUE THREAD

**Issue by nguyentuandat** [RocketChat/Rocket.Chat#14247]
### Description:
Do we have any document to deploy develop branch? Thank you

### Steps to reproduce:

1. I download pre-release 1.0.0-rc.3 at https://github.com/RocketChat/Rocket.Chat/archive/1.0.0-rc.3.tar.gz
2. Then i unzip
3. run `meteor npm install`

### Expected behavior:
`meteor npm install` is successful

### Actual behavior:

```
PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
npm WARN @accounts/mongo@0.0.12 requires a peer of @accounts/common@^0.0.10 but none is installed. You must install peer dependencies yourself.
npm WARN @accounts/mongo@0.0.12 requires a peer of @accounts/server@^0.0.10 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dat/.npm/_logs/2019-04-25T15_46_49_144Z-debug.log
```

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0-rc.3
- Operating System: CentOS 7
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.4 (Base on meteor)
- MongoDB Version: v3.6.12

**Comment by pkgodara** [comment]
@nguyentuandat Seems like package installation failed. Try installing the app again or install the package that failed.

**Comment by pedrolucasoliva** [comment]
Have you tried to delete "c:\User\USERNAME\node_modules\" folder?

**Comment by nguyentuandat** [comment]
Thank you for your response @pkgodara I got it.
I found out that i missing `bzip2` lib on my CentOS.
Just run the command `sudo yum install bzip2` then `meteor npm install` and then it resolve.

**Comment by nguyentuandat** [comment]
When i build, i have an issue
`Killedlding for web.browser `
My VPS just 1GB RAM, so Can i build? (It need 8GB of RAM) If not possible, How can i build on my local (macos) and deploy into my VPS @pedrolucasoliva ?

Thanks.

**Comment by reetp** [comment]
@rocket-cat close

This doesn't appear to be a bug in Rocket.Chat but a configuration/support situation and needs following up in https://forums.rocket.chat or https://open.rocket.chat #dev

There is plenty of documentation on building here https://rocket.chat/docs/developer-guides/
