### ISSUE TITLE
Dockerfile.local not working

### ISSUE THREAD

**Issue by miguelmota** [RocketChat/Rocket.Chat#14289]
### Description:

Trying to build local docker image using ./docker/Dockerfile.local 

### Steps to reproduce:

```bash
docker build -f .docker/Dockerfile.local -t rockethchat .
```

### Expected behavior:

Compiles docker image successfully. 

### Actual behavior:

Docker image build fails with error.

```bash
$ docker build -f .docker/Dockerfile.local -t rockethchat .
Sending build context to Docker daemon  1.938GB
Step 1/7 : FROM node:8
 ---> 0bf36d7ccc1e
Step 2/7 : ADD . /app
 ---> 491f143e214c
Step 3/7 : ENV RC_VERSION=0.57.0-designpreview     DEPLOY_METHOD=docker     NODE_ENV=production     PORT=3000     ROOT_URL=http://localhost:3000
 ---> Running in 261bc18ac015
Removing intermediate container 261bc18ac015
 ---> 8cb76ea915e2
Step 4/7 : RUN set -x  && cd /app/bundle/programs/server  && npm install  && npm cache clear --force
 ---> Running in 8c9d21ae5795
+ cd /app/bundle/programs/server
/bin/sh: 1: cd: can't cd to /app/bundle/programs/server
The command '/bin/sh -c set -x  && cd /app/bundle/programs/server  && npm install  && npm cache clear --force' returned a non-zero code: 2
```

### Server Setup Information:

- Version of Rocket.Chat Server: master branch
- Operating System: macOS

**Comment by geekgonecrazy** [comment]
That one should have been removed.  I have now removed it.

Please use the normal dockerfile.  Note you will need to download or compile the bundle.

You'd do something like:
```
meteor build --directory /tmp/build
cp .docker/Dockerfile /tm/build
cd /tmp/build/
docker build -t rocketchat .
```

Meteor build is needed as a compiled bundle is needed

**Comment by miguelmota** [comment]
Will give it a shot and report back

**Comment by miguelmota** [comment]
```bash
┌─[mota:/Volumes/hd2/Sandbox]
│  2019-04-28T19:32:48Z
└─❯❯❯ cd rocketh.chat/


┌─[mota:/Volumes/hd2/Sandbox/rocketh.chat]
│ (develop) 2019-04-28T19:32:50Z
└─❯❯❯ meteor build --directory /tmp/build
up to date in 1.572se plugins                \
Node#before is deprecated. Use Node#raws.before
Node#moveTo was deprecated. Use Container#append.


┌─[mota:/Volumes/hd2/Sandbox/rocketh.chat]
│ (develop) 2019-04-28T19:52:11Z
└─❯❯❯ cp .docker/Dockerfile /tmp/build


┌─[mota:/Volumes/hd2/Sandbox/rocketh.chat]
│ (develop) 2019-04-28T19:52:17Z
└─❯❯❯ cd /tmp/build/


┌─[mota:/tmp/build]
│  2019-04-28T19:52:21Z
└─❯❯❯ docker build -t rocketchat .
Sending build context to Docker daemon  725.7MB
Step 1/10 : FROM rocketchat/base:8
8: Pulling from rocketchat/base
bc9ab73e5b14: Pull complete
3f117e0d3349: Pull complete
29f0971335c1: Pull complete
a717aa7e730b: Pull complete
0a2d97db0648: Pull complete
Digest: sha256:244fcb3f5e39d8fe7242537e889768e6df9f2cf77727071c9efde48faa0546a3
Status: Downloaded newer image for rocketchat/base:8
 ---> eab76c2b1d75
Step 2/10 : ADD . /app
 ---> 03c7a01c1998
Step 3/10 : MAINTAINER buildmaster@rocket.chat
 ---> Running in 4315fe3b7cf1
Removing intermediate container 4315fe3b7cf1
 ---> d5e47c103f69
Step 4/10 : RUN set -x  && cd /app/bundle/programs/server  && npm install  && npm cache clear --force  && chown -R rocketchat:rocketchat /app
 ---> Running in 61a5a1c45b5b
+ cd /app/bundle/programs/server
+ npm install
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> fibers@2.0.0 install /app/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Binary is fine; exiting
npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd %s %s (wd=%s) meteor-dev-bundle@ node npm-rebuild.js /app/bundle/programs/server
added 138 packages in 6.974s
+ npm cache clear --force
npm WARN using --force I sure hope you know what you are doing.
+ chown -R rocketchat:rocketchat /app
Removing intermediate container 61a5a1c45b5b
 ---> ec29bb3a0cf9
Step 5/10 : USER rocketchat
 ---> Running in af4ee415ee21
Removing intermediate container af4ee415ee21
 ---> 8248205d19b5
Step 6/10 : VOLUME /app/uploads
 ---> Running in f2dae7a8fb57
Removing intermediate container f2dae7a8fb57
 ---> 3a7b6d3bd64c
Step 7/10 : WORKDIR /app/bundle
 ---> Running in 874f0dee7e9b
Removing intermediate container 874f0dee7e9b
 ---> 817cd4f44db8
Step 8/10 : ENV DEPLOY_METHOD=docker     NODE_ENV=production     MONGO_URL=mongodb://mongo:27017/rocketchat     HOME=/tmp     PORT=3000     ROOT_URL=http://localhost:3000     Accounts_AvatarStorePath=/app/uploads
 ---> Running in 70a1c5db614c
Removing intermediate container 70a1c5db614c
 ---> 8a69ec050050
Step 9/10 : EXPOSE 3000
 ---> Running in 280bf45e7335
Removing intermediate container 280bf45e7335
 ---> 06c79df0d569
Step 10/10 : CMD ["node", "main.js"]
 ---> Running in 12d7ab488aef
Removing intermediate container 12d7ab488aef
 ---> dc65f2834079
Successfully built dc65f2834079
Successfully tagged rocketchat:latest


┌─[mota:/tmp/build]
│  2019-04-28T20:26:11Z
└─❯❯❯ docker run -e MONGO_URL="$MONGO_URL" rocketchat:latest
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
^CUpdating process.env.MAIL_URL
Starting Email Intercepter...
Exception in callback of async function: Error: /app/bundle/programs/server/npm/node_modules/sharp/build/Release/sharp.node: invalid ELF header
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/bundle/programs/server/npm/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/bundle/programs/server/npm/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at npmRequire (/app/bundle/programs/server/npm-require.js:133:10)
    at Module.useNode (packages/modules-runtime.js:664:18)
    at index.js (packages/modules.js:580:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at assets.js (packages/rocketchat:assets/server/assets.js:1:748)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (packages/rocketchat:assets/server/index.js:1:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /app/bundle/programs/server/packages/rocketchat_assets.js:644:15
    at /app/bundle/programs/server/packages/rocketchat_assets.js:649:3
    at /app/bundle/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /app/bundle/programs/server/boot.js:220:19
    at /app/bundle/programs/server/boot.js:471:5
    at Function.run (/app/bundle/programs/server/profile.js:510:12)
    at /app/bundle/programs/server/boot.js:470:11
```

Failed building using instructions given
@geekgonecrazy

**Comment by geekgonecrazy** [comment]
what os are you building on?  did you tweak the docker image at all?

**Comment by miguelmota** [comment]
on macOS Mojave 10.14.4. Dockerfile is original with nothing altered

```bash
┌─[mota:/private/tmp/build]
│  2019-04-28T21:20:38Z
└─❯❯❯ node --version
v8.16.0



┌─[mota:/private/tmp/build]
│  2019-04-28T21:20:41Z
└─❯❯❯ uname -a
Darwin computer.lan 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

please let me know if there's additional things i need to provide

@geekgonecrazy

**Comment by geekgonecrazy** [comment]
hm.. interesting.  Newest version of docker for mac?

I just ran the following all from scratch:
```
git clone https://github.com/RocketChat/Rocket.Chat
cd Rocket.Chat
meteor npm i
meteor build --directory /tmp/build
cp .docker/Dockerfile /tmp/build
cd /tmp/build/
docker build -t rocketchat .
```

**Comment by miguelmota** [comment]
There were some changes to it but I think it has to do with my node or meteor installation. Since it's working for you then it's most likely something on my end so we can conclude this issue.
