### ISSUE TITLE
TypeError: Cannot read property '0' of undefined after  upgrade to 1.0.0

### ISSUE THREAD

**Issue by kvaps** [RocketChat/Rocket.Chat#14281]
### Description:

After upgrading rocketchat to v1.0.0, it's not starting with `TypeError: Cannot read property '0' of undefined` error.

### Steps to reproduce:

I've tried both: [manual installation](https://rocket.chat/docs/installation/manual-installation/ubuntu/#manual-install) and official docker image:

```
docker run -e ROOT_URL=http://rocketchat.example.org/ -e MONGO_URL=mongodb://rocketchat:thupho6lah9foamiShai@rocketchat-db:27017/rocketchat -e MONGO_OPLOG_URL='mongodb://rocketchat:thupho6lah9foamiShai@rocketchat-db:27017/local?replicaSet=rs0&authSource=admin' -e PORT=3000 -e BIND_IP=127.0.0.1 -ti --net=host -v /tmp/:/tmp rocketchat/rocket.chat:1.0.0
```

### Actual behavior:

```
/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

TypeError: Cannot read property '0' of undefined
    at retrieveRegistrationStatus (app/cloud/server/functions/retrieveRegistrationStatus.js:15:28)
    at getWorkspaceAccessToken (app/cloud/server/functions/getWorkspaceAccessToken.js:11:50)
    at index.js (app/cloud/server/index.js:13:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at rest.js (app/apps/server/communication/rest.js:1:344)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (app/apps/server/communication/index.js:1:271)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at orchestrator.js (app/apps/server/orchestrator.js:1:534)
    at fileEvaluate (packages/modules-runtime.js:336:7)
```

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.0 --> 1.0.0
- Operating System: Ubuntu 16.04
- Deployment Method: manual or docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.16.0 or 8.11.3
- MongoDB Version: 1:2.6.10-0ubuntu1

**Comment by hypery2k** [comment]
see #14231

**Comment by sinteur** [comment]
@hypery2k  14231 is a closed issue, and I just had this very same issue. It's not resolved yet
