### ISSUE TITLE
Several register issues on newest version

### ISSUE THREAD

**Issue by cchbr** [RocketChat/Rocket.Chat#14315]
### Description:

When a user tries to sign in anonymously he/she receives an Internal server error. See the log below. 

There are also problems creating regular new accounts, the account is created but the user isn't redirected and can't login either.

### Steps to reproduce:

1. Activate anonymous writing
2. Try to talk anonymously in any channel
3. Receive error

### Expected behavior:

The user should be able to register a new account or talk anonymously.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.1
- Operating System: Ubuntu 14.04
- Deployment Method: Docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Additional context

One additional problem is that I can't downgrade to a lower version either, the problem persists on v.1.0.0 and lower versions seems to have stopped working since upgrading.

### Relevant logs:

[34mI20190429-18:09:28.721(0) 
[34mMeteor ➔ method registerUser -> userId: null , arguments:  [ {} ] 
[34mI20190429-18:09:28.732(0) Exception while invoking method 'registerUser' TypeError: Cannot read property 'facebook' of undefined     	at getAvatarSuggestionForUser (app/lib/server/functions/getAvatarSuggestionForUser.js:12:20)     at AccountsServer.<anonymous> (server/lib/accounts.js:221:29)     	at executeBound (/app/bundle/programs/server/npm/node_modules/underscore/underscore.js:762:67)     
	at AccountsServer.bound [as insertUserDoc] (/app/bundle/programs/server/npm/node_modules/underscore/underscore.js:793:14)     
	at MethodInvocation.registerUser (server/methods/registerUser.js:22:28)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:73:34)     
	at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     	at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     	at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     	at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)    	at packages/ddp-server/livedata_server.js:559:43

**Comment by reetp** [comment]
Note there has never been an option to downgrade due to changes made to the db on upgrade.

The only way to 'downgrade' is to restore a backup from a previous version. E.g restore a 0.74.3 backup to 0.74.3 Rocket. Mixing versions will likely break your install.

Before upgrading you should always take a backup, and upgrades should be thorougly tested before deployment.

Note you also seem to be running on *buntu 14.04 which went EOL on 31st March so is no longer supported.
