### ISSUE TITLE
1.0.1 - Rocket.Chat Mobile app will not load

### ISSUE THREAD

**Issue by danpospisil** [RocketChat/Rocket.Chat#14321]
### Description:

The app will not load since 1.0.1 -  I see only this message on Android: 
Sorry an error has occurred, please try again 
There is nothing in the logs.

Version - 1.0.1
Apps Engine Version - 1.4.2
Database Migration - 143

**Comment by himpierre** [comment]
Works for me.

**Comment by pstambrecht** [comment]
I've the same issue on version 3.4.0 playDebug. There is a problem with loading rooms.

Log:
```
2019-04-30 09:38:49.832 12225-12294/chat.rocket.android.dev D/ChatRoomsViewModel$fetchRooms: Error refreshing chatrooms
    chat.rocket.common.RocketChatInvalidResponseException: com.squareup.moshi.JsonDataException: Expected END_OBJECT but was NAME at path $.update[10].lastMessage.reactions.:thumbsup:.usernames at $.update[10].lastMessage.reactions.:thumbsup:.usernames(url='https://example.cz/api/v1/rooms.get')
        at chat.rocket.core.internal.rest.RestClientKt.handleResponse(RestClient.kt:86)
        at chat.rocket.core.internal.rest.RestClientKt.handleRestCall(RestClient.kt:141)
        at chat.rocket.core.internal.rest.RestClientKt$handleRestCall$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
     Caused by: com.squareup.moshi.JsonDataException: com.squareup.moshi.JsonDataException: Expected END_OBJECT but was NAME at path $.update[10].lastMessage.reactions.:thumbsup:.usernames at $.update[10].lastMessage.reactions.:thumbsup:.usernames
        at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:94)
        at chat.rocket.core.model.KotshiMessageJsonAdapter.fromJson(KotshiMessageJsonAdapter.java:283)
        at chat.rocket.core.model.KotshiMessageJsonAdapter.fromJson(KotshiMessageJsonAdapter.java:25)
        at chat.rocket.core.model.KotshiRoomJsonAdapter.fromJson(KotshiRoomJsonAdapter.java:188)
        at chat.rocket.core.model.KotshiRoomJsonAdapter.fromJson(KotshiRoomJsonAdapter.java:22)
        at chat.rocket.core.internal.RoomListAdapter.fromJson(RoomListAdapter.kt:36)
        at chat.rocket.core.internal.RoomListAdapter.fromJson(RoomListAdapter.kt:22)
        at chat.rocket.core.internal.RestMultiResult$MoshiJsonAdapter.fromJson(RestMultiResult.java:67)
        at chat.rocket.core.internal.RestMultiResult$MoshiJsonAdapter.fromJson(RestMultiResult.java:47)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:36)
        at chat.rocket.core.internal.rest.RestClientKt.handleResponse(RestClient.kt:82)
        at chat.rocket.core.internal.rest.RestClientKt.handleRestCall(RestClient.kt:141) 
        at chat.rocket.core.internal.rest.RestClientKt$handleRestCall$1.invokeSuspend(Unknown Source:15) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) 
     Caused by: com.squareup.moshi.JsonDataException: Expected END_OBJECT but was NAME at path $.update[10].lastMessage.reactions.:thumbsup:.usernames
        at com.squareup.moshi.JsonUtf8Reader.endObject(JsonUtf8Reader.java:178)
        at chat.rocket.core.internal.ReactionsAdapter.fromJson(ReactionsAdapter.kt:37)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.squareup.moshi.AdapterMethodsFactory$AdapterMethod.invoke(AdapterMethodsFactory.java:335)
        at com.squareup.moshi.AdapterMethodsFactory$4.fromJson(AdapterMethodsFactory.java:233)
        at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:90)
        at chat.rocket.core.model.KotshiMessageJsonAdapter.fromJson(KotshiMessageJsonAdapter.java:283) 
        at chat.rocket.core.model.KotshiMessageJsonAdapter.fromJson(KotshiMessageJsonAdapter.java:25) 
        at chat.rocket.core.model.KotshiRoomJsonAdapter.fromJson(KotshiRoomJsonAdapter.java:188) 
        at chat.rocket.core.model.KotshiRoomJsonAdapter.fromJson(KotshiRoomJsonAdapter.java:22) 
        at chat.rocket.core.internal.RoomListAdapter.fromJson(RoomListAdapter.kt:36) 
        at chat.rocket.core.internal.RoomListAdapter.fromJson(RoomListAdapter.kt:22) 
        at chat.rocket.core.internal.RestMultiResult$MoshiJsonAdapter.fromJson(RestMultiResult.java:67) 
        at chat.rocket.core.internal.RestMultiResult$MoshiJsonAdapter.fromJson(RestMultiResult.java:47) 
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:36) 
        at chat.rocket.core.internal.rest.RestClientKt.handleResponse(RestClient.kt:82) 
        at chat.rocket.core.internal.rest.RestClientKt.handleRestCall(RestClient.kt:141) 
        at chat.rocket.core.internal.rest.RestClientKt$handleRestCall$1.invokeSuspend(Unknown Source:15) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) 
2019-04-30 09:38:50.434 12225-12801/chat.rocket.android.dev D/ConnectionManager$connect$$inlined$createBatchActor: Processing batch: 106
```

**Comment by nicexe2e4** [comment]
1.12.0 version "Rocket.Chat Experimental" works well, but 3.3.0 doesn't load rooms, it's true.

**Comment by himpierre** [comment]
Strange. RC 1.0.1, Android, 3.3.0, Android Pie works on my phone.

**Comment by pstambrecht** [comment]
Response JSON contains: 
```
"reactions": {
                    ":thumbsup:": {
                        "usernames": [
                            "pavel.stambrecht"
                        ],
                        "names": [
                            "PSt | Pavel Stambrecht"
                        ]
                    }
                }
```

But the model class is:
```
package chat.rocket.core.model

class Reactions : HashMap<String, List<String>>() {
    fun getUsernames(shortname: String) = get(shortname)

    fun getShortNames(): List<String> = keys.toList()
}
```

**Comment by reetp** [comment]
I have been using Android Beta 3.4.0 (2062) and that has thrown up issues with 1.0.x

![Screenshot_20190430-004142_RocketChat_edited](https://user-images.githubusercontent.com/3800384/56955894-e4136280-6b42-11e9-9fa8-9337be0a6067.jpg)

I uploaded that via the app but you could then only see this !!

![Screenshot_20190430-004904_RocketChat_edited](https://user-images.githubusercontent.com/3800384/56955815-aca4b600-6b42-11e9-9f86-74f8372a411e.jpg)

**Comment by reetp** [comment]
As a matter of interest the message **prior** to the above error I had just added a reaction with a thumbs up.

Have tried to clear cache and data and login again and still the same error.

**Comment by wreiske** [comment]
See initial conversation here https://open.rocket.chat/channel/support?msg=gqeiLDon9s3oBJoS2

**Comment by rafaelks** [comment]
FYI: The Android team is investigating the issue at this moment.

**Comment by rafaelks** [comment]
Reason of the crash: new property added called `names` in servers that are using "Real Name" and Android wasn't ready for it, the implementation of the mapping for this properties wasn't safe and we're fixing it right now. We do plan to send a hotfix ASAP to Google Play. We're really sorry for that guys! 😞

**Comment by rafaelks** [comment]
I'll move the issue to the Android repo.
