### ISSUE TITLE
[BUG] LDAP - Can't login anymore

### ISSUE THREAD

**Issue by michaudg** [RocketChat/Rocket.Chat#14337]
### Description:

Can't login anymore with LDAP. Was working with version < 1.0.0.

### Actual behavior:

User not found or incorrect password

### Server Setup Information:

- Version of Rocket.Chat Server: **1.0.1**
- Operating System: **Ubuntu 18.04**
- Deployment Method: **tar**
- Number of Running Instances: **1**
- DB Replicaset Oplog: **Enabled**
- NodeJS Version: **8.11.4**
- MongoDB Version: **4.0.8**

### Relevant logs:

```
Exception while invoking method 'login' TypeError: Cannot read property 'replace' of undefined
    at module.exports (/opt/Rocket.Chat/programs/server/npm/node_modules/limax/lib/limax.js:18:15)
    at slug (app/ldap/server/sync.js:22:9)
    at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:103:14)
    at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)
    at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

**Comment by himpierre** [comment]
Is this affecting all ldap installations or just this one user? I'm hesitating to update seeing this bug.

thanks and cheers

**Comment by Abraka** [comment]
> I'm hesitating to update seeing this bug.

Same here.

**Comment by wreiske** [comment]
From the code....
```export function slug(text) {
	if (settings.get('UTF8_Names_Slugify') !== true) {
		return text;
	}
	text = limax(text, { replacement: '.' });
	return text.replace(/[^0-9a-z-_.]/g, '');
}
```

This slug function is doing a replace on a text string... if the text is null, the replace is going to fail. 

This is called from:
```
if (settings.get('LDAP_Username_Field') !== '') {
				username = slug(getLdapUsername(ldapUser));
			}
```
So check that setting. Also make sure that the field you are using to pull the username is correct. Here's what we use.
![image](https://user-images.githubusercontent.com/6295044/57050711-edd4bd00-6c4b-11e9-8910-4bb8f8bf99b5.png)

**Comment by michaudg** [comment]
@wreiske Thanks to you!

We had **cn.givenName** for the username and **uid** for the identifier. It worked for years like that but maybe this code has been updated in the last version. Replacing with **cn** and **uidNumber** solve our problem. We can now log in again.
