### ISSUE TITLE
 Secure LDAP connection is not working after upgrade to 1.0.0

### ISSUE THREAD

**Issue by kvaps** [RocketChat/Rocket.Chat#14354]
### Description:

Secure LDAP connection is not working after upgrade to 1.0.0.

### Steps to reproduce:

1. Configure LDAP, and enable TLS encryption for it
2. Click "Test Connection" button

### Expected behavior:

Working LDAP over TLS

### Actual behavior:

Throws an error: `Error: socket hang up`.

```
[34mI20190502-14:22:50.585(2) server.js:199 �[31mLDAP ➔ Connection.error TLS connection { Error: socket hang up     at TLSSocket.onHangUp (_tls_wrap.js:1137:19)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at TLSSocket.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   code: 'ECONNRESET',   path: undefined,   host: 'freeipa.example.org',   port: undefined,   localAddress: undefined } 
{ Error: socket hang up     at TLSSocket.onHangUp (_tls_wrap.js:1137:19)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at TLSSocket.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   code: 'ECONNRESET',   path: undefined,   host: 'freeipa.example.org',   port: undefined,   localAddress: undefined }  
```

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2
- Operating System: Ubuntu
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version:

**Comment by Gummikavalier** [comment]
For the record LDAP encryption works on our 1.0.2 system.

We are using a genuine certificate, port 636, encryption is set to use SSL/LDAP (not StartTLS).

For all we know it might not be using TLS though, as the backend is Windows AD that may downgrade it to SSL at will, but at least it is not plaintext.
