### ISSUE TITLE
LDAP doesn't update users created by Oauth

### ISSUE THREAD

**Issue by tiagoefreitas** [RocketChat/Rocket.Chat#14409]
When I do a manual background sync of LDAP, I get this error with users created by manual oauth.
It should update the users with the LDAP password so I can login using LDAP as an alternative, because Oauth is not working in any of the Android clients, only iOS.

34mI20190507-09:18:36.291(0) server.js:199 [31mLDAPSync ➔ error Error creating user { Error: Email already exists. [403]     at handleError (packages/accounts-password/password_server.js:104:17)     at checkForCaseInsensitiveDuplicates (packages/accounts-password/password_server.js:245:7)     at createUser (packages/accounts-password/password_server.js:1076:3)     at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1147:10)     at addLdapUser (app/ldap/server/sync.js:260:29)     at ldapUsers.forEach.ldapUser (app/ldap/server/sync.js:323:5)     at Array.forEach (<anonymous>)     at ldap.searchUsersSync.Meteor.bindEnvironment (app/ldap/server/sync.js:290:13)     at runWithEnvironment (packages/meteor.js:1356:24)   isClientSafe: true,   error: 403,   reason: 'Email already exists.',   details: undefined,   message: 'Email already exists. [403]',   errorType: 'Meteor.Error' }

**Comment by tiagoefreitas** [comment]
may be related to https://github.com/RocketChat/Rocket.Chat/issues/13069

**Comment by saschafoerster** [comment]
May be also related to https://github.com/RocketChat/Rocket.Chat/issues/11502#issuecomment-406201275
