### ISSUE TITLE
Livechat Internal server error

### ISSUE THREAD

**Issue by CH1PSET1** [RocketChat/Rocket.Chat#14504]
Livechat show "Internal server error" when some guest write

Steps to reproduce:
Activate Livechat
Add some backend users, no info is requested from customer (guest chat)
Open a browser and open a new guest chat, free operator
Write any word
Expected behavior:
Start a new chat with any operator

Actual behavior:
"Internal server error" popup; no message to operator in backend

Server Setup Information:
Version of Rocket.Chat Server: 0.74.2
Operating System: Linux
Deployment Method: snap
Number of Running Instances: 1
�[34mI20190212-13:22:42.426(1) Meteor ➔ method sendMessageLivechat -> userId: rm98usyiqN7XJuYKM , arguments: [ { _id: 'QkYXqHCAQh4o6bvtR', rid: '7qRbf6i7qmDCriBBt', msg: 'Hola', token: 'purnihfAQvmhrGdtn' }, null ]
�[34mI20190212-13:22:42.443(1) Meteor ➔ method UserPresence:connect -> userId: rm98usyiqN7XJuYKM , arguments: [ 'purnihfAQvmhrGdtn', { visitor: 'purnihfAQvmhrGdtn' } ]
�[34mI20190212-13:22:42.480(1) Exception while invoking method 'sendMessageLivechat' { BulkWriteError: E11000 duplicate key error collection: parties.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "rm98usyiqN7XJuYKM", : null, : "l", : null } at OrderedBulkOperation.handleWriteError (/snap/rocketchat-server/1364/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:1048:11) at resultHandler (/snap/rocketchat-server/1364/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/ordered.js:159:23) at /snap/rocketchat-server/1364/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18 at _combinedTickCallback (internal/process/next_tick.js:131:7) at process._tickDomainCallback (internal/process/next_tick.js:218:9) index: 0, code: 11000, errmsg: 'E11000 duplicate key error collection: parties.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "rm98usyiqN7XJuYKM", : null, : "l", : null }', op: { rid: '7qRbf6i7qmDCriBBt', fname: 'Jo', alert: true, open: true, unread: 1, userMentions: 1, groupMentions: 0, u: { _id: 'rm98usyiqN7XJuYKM', username: 'admin' }, t: 'l', desktopNotifications: 'all', mobilePushNotifications: 'all', emailNotifications: 'all', _updatedAt: 2019-02-12T12:22:42.463Z, _id: 'fkFpTqMgnxYtNg9om' }, name: 'BulkWriteError', driver: true, err: { index: 0, code: 11000, errmsg: 'E11000 duplicate key error collection: parties.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "rm98usyiqN7XJuYKM", : null, : "l", : null }', op: { rid: '7qRbf6i7qmDCriBBt', fname: 'Jo', alert: true, open: true, unread: 1, userMentions: 1, groupMentions: 0, u: [Object], t: 'l', desktopNotifications: 'all', mobilePushNotifications: 'all', emailNotifications: 'all', _updatedAt: 2019-02-12T12:22:42.463Z, _id: 'fkFpTqMgnxYtNg9om' } }, result: BulkWriteResult { result: { ok: 1, writeErrors: [Array], writeConcernErrors: [], insertedIds: [Array], nInserted: 0, nUpserted: 0, nMatched: 0, nModified: 0, nRemoved: 0, upserted: [], lastOp: [Object] } }, [Symbol(mongoErrorContextSymbol)]: {} }
�[34mI20190212-13:22:43.429(1) Meteor ➔ method UserPresence:online -> userId: rm98usyiqN7XJuYKM , arguments: [ 'purnihfAQvmhrGdtn' ]

**Comment by CH1PSET1** [comment]
https://centrnp72.ru/53-registracija-yuridicheskih-lic.html

Exemple

**Comment by renatobecker** [comment]
Hi @CH1PSET1.

This is a very old issue, there is a migration that wasn't performed on your server:
https://github.com/RocketChat/Rocket.Chat/pull/10956/files#diff-7abbc3ce097883f6081e347190d6ba8b

**Comment by CH1PSET1** [comment]
thanks for the answer.  Please tell me how to perform this migration, do not quite understand.

**Comment by CH1PSET1** [comment]
I understand that you need to change the file according to the corrected one, but I cannot find it at the specified server / startup / migrations / v122.js location

**Comment by alebeta90** [comment]
Same issue, and I'm running the latest version of rocket from docker container

**Comment by adrianovieira** [comment]
We also just get this error here.

Trying to upgrade from rktc-3.3.0 to 3.10.4

logging: <Details>
```
 BulkWriteError: E11000 duplicate key error collection: rocketchat.rocketchat_room index: _id_ dup key: {
 	: "rocket.catsNYZbWWBmK3wDAAec"
 }
 at OrderedBulkOperation.handleWriteError(/opt/Rocket.Chat - 3.10 .4 / programs / server / npm / node_modules / meteor / npm - mongo / node_modules / mongodb / lib / bulk / common.js: 1257: 9)
 at resultHandler(/opt/Rocket.Chat - 3.10 .4 / programs / server / npm / node_modules / meteor / npm - mongo / node_modules / mongodb / lib / bulk / common.js: 521: 23)
 at / opt / Rocket.Chat - 3.10 .4 / programs / server / npm / node_modules / meteor / npm - mongo / node_modules / mongodb / lib / core / connection / pool.js: 405: 18
 at processTicksAndRejections(internal / process / task_queues.js: 79: 11) => awaited here:
 	at Promise.await(/opt/Rocket.Chat - 3.10 .4 / programs / server / npm / node_modules / meteor / promise / node_modules / meteor - promise / promise_server.js: 60: 12)
 at Server.apply(packages / ddp - server / livedata_server.js: 1638: 22)
 at Server.call(packages / ddp - server / livedata_server.js: 1607: 17)
 at DDPCommon.MethodInvocation. < anonymous > (server / lib / sendMessagesToAdmins.js: 16: 43)
 at packages / dispatch_run - as - user.js: 211: 14
 at Meteor.EnvironmentVariable.EVp.withValue(packages / meteor.js: 1234: 12)
 at Object.Meteor.runAsUser(packages / dispatch_run - as - user.js: 210: 33)
 at server / lib / sendMessagesToAdmins.js: 16: 12
 at SynchronousCursor.forEach(packages / mongo / mongo_driver.js: 1138: 16)
 at Cursor. < computed > [as forEach](packages / mongo / mongo_driver.js: 918: 44)
 at sendMessagesToAdmins(server / lib / sendMessagesToAdmins.js: 13: 33)
 at server / startup / migrations / v201.js: 41: 4
 at Function.time(/opt/Rocket.Chat - 3.10 .4 / programs / server / profile.js: 273: 30)
 at / opt / Rocket.Chat - 3.10 .4 / programs / server / boot.js: 415: 15
 at / opt / Rocket.Chat - 3.10 .4 / programs / server / boot.js: 465: 7
 at Function.run(/opt/Rocket.Chat - 3.10 .4 / programs / server / profile.js: 280: 14)
 at / opt / Rocket.Chat - 3.10 .4 / programs / server / boot.js: 463: 13 {
 	driver: true,
 	code: 11000,
 	writeErrors: [WriteError {
 		err: [Object]
 	}],
 	result: BulkWriteResult {
 		result: {
 			ok: 1,
 			writeErrors: [Array],
 			writeConcernErrors: [],
 			insertedIds: [Array],
 			nInserted: 0,
 			nUpserted: 0,
 			nMatched: 0,
 			nModified: 0,
 			nRemoved: 0,
 			upserted: [],
 			lastOp: [Object]
 		}
 	}
 }
```
</details>

I appears that all migrations has been applied:

<details>

```
 {"line":"120","file":"migrations.js","message":"Migrations: Migrating from version 191 -> 213","time":{"$date":1610733109193},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 192","time":{"$date":1610733109197},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 193","time":{"$date":1610733109738},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 194","time":{"$date":1610733109756},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 195","time":{"$date":1610733109772},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 196","time":{"$date":1610733109870},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 197","time":{"$date":1610733109876},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 198","time":{"$date":1610733109967},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 199","time":{"$date":1610733109994},"level":"info"}
 Changing schema of User records, this may take a long time ...
 Migrating 0/507
 Changing schema of User records finished.
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 200","time":{"$date":1610733111077},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 201","time":{"$date":1610733111147},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 202","time":{"$date":1610733111156},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 203","time":{"$date":1610733111175},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 204","time":{"$date":1610733111377},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 205","time":{"$date":1610733111392},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 206","time":{"$date":1610733111397},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 207","time":{"$date":1610733111422},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 208","time":{"$date":1610733111428},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 209","time":{"$date":1610733111435},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 210","time":{"$date":1610733111440},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 211","time":{"$date":1610733111479},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 212","time":{"$date":1610733112934},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 213","time":{"$date":1610733112947},"level":"info"}
 {"line":"120","file":"migrations.js","message":"Migrations: Finished migrating.","time":{"$date":1610733113066},"level":"info"}
 Not migrating, control is locked. Attempt 1/30. Trying again in 10 seconds.
 {"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 213","time":{"$date":1610733123079},"level":"info"}
```
</details>
</Details>

**Comment by KevLehman** [comment]
This pull request has been inactive for a while, so we’re closing it to keep the backlog manageable.
If you’d like to continue working on it, feel free to reopen or submit a new PR. Thanks for the contribution!
