### ISSUE TITLE
Custom wordpress oauth with miniorange

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#14550]
When trying to login with the custom oauth direction I get the following error

W20190518-12:53:21.096(-5) (oauth_server.js:392) Error in OAuth Server: Failed to fetch identity from torauth at http://talesofrokugan.com/wp-content/plugins/miniorange-oauth-20-server/web/index.php/moserver/resource. failed [400] {"error":"invalid_bearer_token","error_description":"OAuth2 Access token is empty"}

I20190518-12:53:23.037(-5) Exception while invoking method 'login' { Error: Failed to fetch identity from torauth at http://talesofrokugan.com/wp-content/plugins/miniorange-oauth-20-server/web/index.php/moserver/resource. failed [400] {"error":"invalid_bearer_token","error_description":"OAuth2 Access token is empty"}     at CustomOAuth.getIdentity (app/custom-oauth/server/custom_oauth_server.js:178:18)     at Object.OAuth.registerService.query [as handleOauthRequest] (app/custom-oauth/server/custom_oauth_server.js:188:26)     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)     at middleware (packages/oauth/oauth_server.js:161:5)     at /snap/rocketchat-server/1377/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40   message: 'Failed to fetch identity from torauth at http://talesofrokugan.com/wp-content/plugins/miniorange-oauth-20-server/web/index.php/moserver/resource. failed [400] {"error":"invalid_bearer_token","error_description":"OAuth2 Access token is empty"}',   response:     { statusCode: 400,      content: '{"error":"invalid_bearer_token","error_description":"OAuth2 Access token is empty"}',      headers:        { date: 'Sat, 18 May 2019 17:53:20 GMT',         server: 'Apache/2.4.34 (Ubuntu)',         'cache-control': 'no-cache',         'www-authenticate': 'Bearer realm="Service", error="invalid_bearer_token", error_description="OAuth2 Access token is empty"',         'content-length': '83',         connection: 'close',         'content-type': 'application/json' },      data:        { error: 'invalid_bearer_token',         error_description: 'OAuth2 Access token is empty' } } }

### Server Setup Information:

- Version of Rocket.Chat Server:  1.0.3
- Operating System: ubuntu server 18.04 
- Deployment Method: snap install
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by dtekumalla** [comment]
Hi wargamesqcf
I'm seeing the same issue with miniOrange on WP 5.2.1 and Rocket Chat 1.0.3. Were you able to get figure this out ?

**Comment by wargamesqcf** [comment]
I was not.

**Comment by johnlund** [comment]
Hi guys, I was able to get Rocket Chat working using the other Wordpress OAuth server plugin: https://wordpress.org/plugins/oauth2-provider/

**Comment by dtekumalla** [comment]
Hi John - would you be able to describe the configuration ?

**Comment by johnlund** [comment]
Yeah, in general, I followed this: https://wp-oauth.com/docs/how-to/rocket-chat-oauth-setup/ but I will give you the exact details of my setup.

Wordpress OAuth plugin settings:

Allowed Grant Types: only Authorization Code checked
Redirect URI: empty
Client Credential Assigned User: --- No User ---
Client Scope: basic

Rocket Chat Custom OAuth Settings:

Enable: true
URL: WP home page
Token Path: /oauth/token/
Token Sent Via: Payload
Identity Token Sent Via: Same as "Token Sent Via"
Identity Path: /oauth/me/
Authorize Path: /oauth/authorize/
Score: openid
Param Name for access token: access_token
Login Style: Redirect
Username Field: user_login
Merge Roles from SSO: false
Merge users: true

Cheers!
John

**Comment by westonberch** [comment]
Hey guys, I'm also having this same problem running on Ubuntu 18.04 with Rocket.Chat 1.1.1 and miniorange oauth server 2.8.1 on the latest wordpress build. 

Has anyone been able to make any progress other than switching plugins?

**Comment by mariusiscoding** [comment]
Problem is still there Ubuntu 18 and latest Rocketchat version...

**Comment by grandfoobah** [comment]
OK so I got it to work and here's my settings... Using docker-compose images:latest versions.

wordpress wp-oath (free version) plugin side:

authorization code [ticked]
redirect uri: https://chat.example.com/_oauth/wordpress
clientid XXXXXXXXXXXXXXxx
client secret XXXXXXXXXXXXXXXXXXXXXXXX
client scope: openid

settings: 
Enable OAuth Server

Everything else not mentioned, defaults.

----------------------

rocketchat side:

administration -> scroll to bottom -> find "oath" (the second one, confusingly, I never messed with the first one in the upper section of the panel menu...)
On the admin/OAuth page, scroll to bottom, expand "Wordpress"

enabled: yes
url: https://example.com
id: XXXXXXXXXXXXXXXXXXXXXX
secret: XXXXXXXXXXXXXXXX
server type: custom
identity path: ?oauth=me
Identity Token Sent Via: Payload
token path: ?oauth=token
authorize path: ?oauth=authorize
scope: openid
wordpress callback url: https://example.com/_oauth/wordpress
