### ISSUE TITLE
BigBlueButton integration not working

### ISSUE THREAD

**Issue by Shaltz** [RocketChat/Rocket.Chat#14586]
### Description:
The BigBlueButton integration in RC is not working. Users are authenticated on RC aswell as on bbb using openLDAP (the LDAP for the both of them)

### Steps to reproduce:
Installed my own bbb server, everything is working fine on the instance, but when I activate the bbb integration in rocketchat and try to start a video call from a channel, the sidebar pops up with the "Start Meeting" button" but when you click on it, nothing happens

### Expected behavior:
A bbb video call window should popup and start a video conference

### Actual behavior:
nothing except an error in the devtools 

### Server Setup Information:
- Version of Rocket.Chat Server: 1.0.3
- Operating System: Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: NA
- MongoDB Version: NA

### Additional context
All instances are in the AWS env, the LDAP, the RC and the bbb
the bbb insstance and the RC instance authenticate users from the same LDAP

### Relevant logs:

**Client logs :** 
`"Error: Internal server error [500]
    at w._livedata_result (https://chat.exemple.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:59:17834)
    at w.onMessage (https://chat.exemple.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:59:20175)
    at https://chat.exemple.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:2772
    at Array.forEach (<anonymous>)
    at l.forEachCallback (https://chat.exemple.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:3967)
    at k.socket.onmessage (https://chat.exemple.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:2742)
    at k.r.dispatchEvent (https://chat.exemple.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:6474)
    at k._dispatchMessage (https://chat.exemple.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:20111)
    at k._didMessage (https://chat.exemple.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:21011)
    at WebSocket.o.ws.onmessage (https://chat.exemple.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:23160)"`

**Server logs :** 
 `2019-05-22T07:21:00Z rocketchat-server.rocketchat-server[24110]:     at Array.forEac
h (<anonymous>)
2019-05-22T07:21:00Z rocketchat-server.rocketchat-server[24110]:     at ldap.searchU
sersSync.Meteor.bindEnvironment (app/ldap/server/sync.js:290:13)
2019-05-22T07:21:00Z rocketchat-server.rocketchat-server[24110]:     at runWithEnvir
onment (packages/meteor.js:1356:24)
2019-05-22T07:21:00Z rocketchat-server.rocketchat-server[24110]:   isClientSafe: tru
e,
2019-05-22T07:21:00Z rocketchat-server.rocketchat-server[24110]:   error: 'LDAP-logi
n-error',
2019-05-22T07:21:00Z rocketchat-server.rocketchat-server[24110]:   reason: 'LDAP Aut
hentication succeded, there is no email to create an account. Have you tried setting
 your Default Domain in LDAP Settings?',
2019-05-22T07:21:00Z rocketchat-server.rocketchat-server[24110]:   details: undefine
d,
2019-05-22T07:21:00Z rocketchat-server.rocketchat-server[24110]:   message: 'LDAP Au
thentication succeded, there is no email to create an account. Have you tried settin
g your Default Domain in LDAP Settings? [LDAP-login-error]',
2019-05-22T07:21:00Z rocketchat-server.rocketchat-server[24110]:   errorType: 'Meteo
r.Error' }
`

The default domain is set in the LDAP settings, I don't understand why this warning is in the logs

**Comment by Shaltz** [comment]
nobody else has issues with the bigbluebutton integration lately ?

**Comment by Shaltz** [comment]
the problem is still there

no LDAP issues now, but clicking on the "start meeting" button in rocketche does nothing...

this error pops up in the dev console :

`"Error: Internal server error [500]
    at w._livedata_result (https://chat.example.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:59:17834)
    at w.onMessage (https://chat.example.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:59:20175)
    at https://chat.example.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:2772
    at Array.forEach (<anonymous>)
    at l.forEachCallback (https://chat.example.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:3967)
    at k.socket.onmessage (https://chat.example.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:2742)
    at k.r.dispatchEvent (https://chat.example.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:6474)
    at k._dispatchMessage (https://chat.example.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:20111)
    at k._didMessage (https://chat.example.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:21011)
    at WebSocket.o.ws.onmessage (https://chat.example.io/c9b63b63818b7389d550732abac3e2edcb8831da.js?meteor_js_resource=true:57:23160)"`

**Comment by Beeez** [comment]
I get a similar issue when trying to start a call. Might be unrelated to yours specifically, but regardless the integration is not working despite my RC servers having access to the BigBlueButton servers external IP. 

`I20190709-13:53:46.110(-4) Exception while invoking method 'bbbJoin' { Error: connect ETIMEDOUT 50.234.137.104:443     at Object._errnoException (util.js:992:11)     at _exceptionWithHostPort (util.js:1014:20)     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)   code: 'ETIMEDOUT',   errno: 'ETIMEDOUT',   syscall: 'connect',   address: 'externalipofbbb',   port: 443 } `

**Comment by einhirn** [comment]
Well @Beeez since you see "ETIMEDOUT" your RC server has some kind of problems reaching the bbb bbb server's external IP... Re-Check your connectivity...

**Comment by einhirn** [comment]
Hi @Shaltz,
Actually BBB server doesn't authenticate users via LDAP. A frontend like Greenlight does. But RC is just pointed to the BBB Backend API URL, so there shouldn't be any messages about LDAP login succeeded etc. in your logs at all.

**Comment by robertfromont** [comment]
I'm having a similar-looking problem when trying to integrate with Big Blue Button (Rocket Chat version 3.6.3). The server-side log says:
```
I20200929-09:14:57.474(13) meeting-created 8Do...eiN 
I20200929-09:14:57.582(13) Exception while invoking method bbbJoin Error: failed [404] <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Cannot GET //bigbluebutton/api/hooks/create</pre> </body> </html>      at Object.exports.makeErrorByStatus (packages/http.js:177:10)     at Request._callback (packages/http.js:141:24)     at Request.self.callback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at Request.emit (events.js:210:5)     at Request.EventEmitter.emit (domain.js:475:20)     at Request.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at Request.emit (events.js:210:5)     at Request.EventEmitter.emit (domain.js:475:20)     at IncomingMessage.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:299:28)     at IncomingMessage.emit (events.js:215:7)     at IncomingMessage.EventEmitter.emit (domain.js:475:20)     at endReadableNT (_stream_readable.js:1184:12)     at processTicksAndRejections (internal/process/task_queues.js:80:21)  => awaited here:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
```

i.e. it seems to be getting a *404* error on `//bigbluebutton/api/hooks/create`

I changed the *BigBlueButton/Domain* setting so that there was no trailing slash after the URL (i.e. I changed `https://my.bbb.com/` to `https://my.bbb.com`) and the error went away.

**Comment by robertfromont** [comment]
I'm having a similar-looking problem when trying to integrate with Big Blue Button (Rocket Chat version 3.6.3). The server-side log says:
```
I20200929-09:14:57.474(13) meeting-created 8Do...eiN 
I20200929-09:14:57.582(13) Exception while invoking method bbbJoin Error: failed [404] <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Cannot GET //bigbluebutton/api/hooks/create</pre> </body> </html>      at Object.exports.makeErrorByStatus (packages/http.js:177:10)     at Request._callback (packages/http.js:141:24)     at Request.self.callback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at Request.emit (events.js:210:5)     at Request.EventEmitter.emit (domain.js:475:20)     at Request.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at Request.emit (events.js:210:5)     at Request.EventEmitter.emit (domain.js:475:20)     at IncomingMessage.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:299:28)     at IncomingMessage.emit (events.js:215:7)     at IncomingMessage.EventEmitter.emit (domain.js:475:20)     at endReadableNT (_stream_readable.js:1184:12)     at processTicksAndRejections (internal/process/task_queues.js:80:21)  => awaited here:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
```

i.e. it seems to be getting a *404* error on `//bigbluebutton/api/hooks/create`

I changed the *BigBlueButton/Domain* setting so that there was no trailing slash after the URL (i.e. I changed `https://my.bbb.com/` to `https://my.bbb.com`) and the error went away.

It would be great if the BBB integration handled a URL either with or without a trailing slash.

**Comment by alfonsolsl** [comment]
I have BBB working very fine.

For me the goal is to find the way to record this direct calls.

**Comment by amlamarra** [comment]
I'm having the same problem. Rocket.Chat is at v3.9.7 and both RC & BBB are LDAP authenticated with an Active Directory server.

**Comment by Hountez** [comment]
I have the same problem. 
i got a capture from wireshark:

the api call to http://10.0.0.127/bigbluebutton/api/create?[.....] works but the call to http://10.0.0.127/bigbluebutton/api/hooks/create?[....] results in an 404 error

Solution:
install webhooks for bigbluebutton as documented:
https://docs.bigbluebutton.org/dev/webhooks.html

**Comment by amlamarra** [comment]
I figured out the problem for me. I was getting the following error in rocketchat logs:
```
Exception while invoking method 'bbbJoin' Error: unable to verify the first certificate
```
My BBB url is HTTPS. I could use HTTP, but then the browser complains about mixed content and blocks it by default. Our BBB server is using a cert from an internally trusted CA. I ended up adding the following line to `/etc/environment` and rebooting the server:
```
NODE_TLS_REJECT_UNAUTHORIZED=0
```

I know that normally this is a security risk. However, this is a network with no access to the Internet.

P.S. Don't put a slash at the end of the BBB url. I wish they wouldn't make it so picky.
