### ISSUE TITLE
Random BulkWriteError seen by users.

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#14616]
### Description:

Users randomly getting a bulk write error.

### Expected behavior:

No errors

### Actual behavior:

users getting random errors.

### Server Setup Information:

Version of Rocket.Chat Server: 1.0.3
Operating System: Centos 7
Deployment Method: manual tar install
Number of Running Instances: 3
DB Replicaset Oplog: yes

### Relevant logs:

~~~

I20190523-20:53:30.369(0) server.js:199 System ➔ error Error sending message: { BulkWriteError: E11000 duplicate key error collection: rocketchat.rocketchat_message index: _id_ dup key: { : "DxY7JYiecghYquGp7" }     at OrderedBulkOperation.handleWriteError (/opt/Rocket.Chat-1.0.3/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:1048:11)     at resultHandler (/opt/Rocket.Chat-1.0.3/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/ordered.js:159:23)     at /opt/Rocket.Chat-1.0.3/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   index: 0,   code: 11000,   errmsg: 'E11000 duplicate key error collection: rocketchat-gay.rocketchat_message index: _id_ dup key: { : "DxY7JYiecghYquGp7" }',   op:     { _id: 'DxY7JYiecghYquGp7',      rid: 'NWB5mAXJiE5S2XCAh',      msg: 'this is true.......but arent you on our time now??<br>',      ts: 2019-05-23T20:53:30.336Z,      u:        { _id: 'qWTTgShw7gFgFAfo9',         username: 'Ddougtex12',         name: undefined },      mentions: [],      channels: [],      _updatedAt: 2019-05-23T20:53:30.363Z },   name: 'BulkWriteError',   driver: true,   err:     { index: 0,      code: 11000,      errmsg: 'E11000 duplicate key error collection: rocketchat-gay.rocketchat_message index: _id_ dup key: { : "DxY7JYiecghYquGp7" }',      op:        { _id: 'DxY7JYiecghYquGp7',         rid: 'NWB5mAXJiE5S2XCAh',         msg: 'this is true.......but arent you on our time now??<br>',         ts: 2019-05-23T20:53:30.336Z,         u: [Object],         mentions: [],         channels: [],         _updatedAt: 2019-05-23T20:53:30.363Z } },   result:     BulkWriteResult {      result:        { ok: 1,         writeErrors: [Array],         writeConcernErrors: [],         insertedIds: [Array],         nInserted: 0,         nUpserted: 0,         nMatched: 0,         nModified: 0,         nRemoved: 0,         upserted: [],         lastOp: [Object] } },   [Symbol(mongoErrorContextSymbol)]: {} } 

~~~

**Comment by Crazy-Hopper** [comment]
Those bulk write errors seem to be pretty much harmless cause I've seen them a lot before and didn't find any adverse effects. But printing those errors personally to the sender is quite bad indeed. Started with 1.0.3.

**Comment by serviceman** [comment]
I assumed they are harmless, but my users should not be seeing the errors. They are getting crazy ideas in their heads that the site is being hacked or worse. Users should not receive any of those kinds of error messages that would otherwise serve them no purpose to see.

**Comment by mdanovz** [comment]
My users have the same error - in a personal chat they have a notification from the rocket.cat bot:
"Only you can see this message
BulkWriteError "
In this case, the subscriber does not send anything.
Rocket chat version is 1.1.1

**Comment by novacrazy** [comment]
I also have users seeing this after upgrading from pre-1.0 to the latest develop this morning.

**Comment by antgel** [comment]
I also see this on 1.4.2. Can someone from the Rocket.Chat team take a look? This has been open for six weeks.
