### ISSUE TITLE
"OAuth" I'm having trouble logging in for the first time.

### ISSUE THREAD

**Issue by CMHyun** [RocketChat/Rocket.Chat#14637]
### Description:
I'm having trouble signing up for an account through "Google OAuth".

### Steps to reproduce:
1. Docker Run Rocket.Chat Server 
2. Go to "Rocket.Chat WebSite"
3. Click on "Setting" > "OAuth"
4. Setting Google
5. Run Rocket.Chat Client(Mac OS, Android)
6. Click on Google Button
7. Enter your Google Account information
8. Sign up with a Google Account
9. Bug!! Client is Stop

### Expected behavior:
Attempts to sign up through "Google OAuth" and returns to the initial screen. "Rocket.Chat Client" is not able to log in to Google. If you try "Google OAuth" after running the program after finishing the program completely, "Google" account is normally registered and login is possible.

### Actual behavior:
<img width="1112" alt="스크린샷 2019-05-27 오후 2 48 14" src="https://user-images.githubusercontent.com/34223857/58398074-967d0d80-808e-11e9-8755-6e0ca510a0a8.png">

### Server Setup Information:
- Version of Rocket.Chat Server: 1.0.3
- Operating System: Ubuntu 16.04 (AWS EC2)
- Deployment Method: docker
- Number of Running Instances: Docker Instance(3): RocketChat, Mongo, Hubot 
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4 - x64
- MongoDB Version: 3.6.12

### Additional context
If you have "Google OAuth" on both Mac, iOS, and Android, you'll have trouble signing up for the first time.
I have a problem, but when I look at the user list in "Rocket.Chat Web", I am registered normally.

### Relevant logs:
**Docker logs**
Exception in callback of async function: { MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}
rocketchat_1          |     at Function.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:43:12)
rocketchat_1          |     at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:149:22)
rocketchat_1          |     at coll.s.topology.update (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:1370:39)
rocketchat_1          |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
rocketchat_1          |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
rocketchat_1          |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
rocketchat_1          |   driver: true,
rocketchat_1          |   name: 'MongoError',
rocketchat_1          |   index: 0,
rocketchat_1          |   code: 9,
rocketchat_1          |   errmsg: '\'$set\' is empty. You must specify a field like so: {$set: {<field>: ...}}',
rocketchat_1          |   [Symbol(mongoErrorContextSymbol)]: {} }

**Comment by CMHyun** [comment]
The same goes for "Facebook".
