### ISSUE TITLE
Clicking "or talk as anonymous" doesn't work in the version develop or last version stable

### ISSUE THREAD

**Issue by fnaveira** [RocketChat/Rocket.Chat#14764]
### Description:

Allow read and allow write as anonymous turned on.
You click sign in to start talking or talk as anonymous

Version of Rocket.Chat Server: 1.2.0-develop, 1.0.3

### Steps to reproduce:

    Click Allow Anonymous Read / Allow Anonymous Write
    Open in new browser
    Click Or Talk as anonymous

### Expected behavior:

allow to enter a username to talk as

### Actual behavior:

![33401786-2235446c-d520-11e7-93d8-b131f84252d5](https://user-images.githubusercontent.com/1482889/59131588-10f13b80-8973-11e9-825f-41e4e670654e.png)

![Captura1](https://user-images.githubusercontent.com/1482889/59131751-80ffc180-8973-11e9-9f01-8b4cfef25008.PNG)

![Captura2](https://user-images.githubusercontent.com/1482889/59131761-852bdf00-8973-11e9-9179-c5b733c5b5a0.PNG)

![Captura3](https://user-images.githubusercontent.com/1482889/59131769-8826cf80-8973-11e9-8f5f-7bf7c170544d.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.0-develop , 1.0.3 ( cloud rocket)
- Operating System: Linux x64 4.15.0-50-generic
- Deployment Method: docker 
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: v8.11.4
- MongoDB Version: 3.2.21

### Relevant logs:

 I20190607-20:05:29.115(0) Exception while invoking method 'browseChannels' TypeError: Cannot read property '_id' of null     at MethodInvocation.browseChannels (server/methods/browseChannels.js:64:28)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:73:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
I20190607-20:25:40.080(0) Exception while invoking method 'browseChannels' TypeError: Cannot read property '_id' of null     at MethodInvocation.browseChannels (server/methods/browseChannels.js:64:28)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:73:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
I20190607-20:33:07.031(0) Exception while invoking method 'browseChannels' TypeError: Cannot read property '_id' of null     at MethodInvocation.browseChannels (server/methods/browseChannels.js:64:28)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:73:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

**Comment by fnaveira** [comment]
![Captura4](https://user-images.githubusercontent.com/1482889/59132589-e8b70c00-8975-11e9-85fe-83dc3df4a251.PNG)
