### ISSUE TITLE
LDAP multiple email parsing error

### ISSUE THREAD

**Issue by tsurai** [RocketChat/Rocket.Chat#14762]
### Description:

LDAP entries of user with multiple email addresses fail to parse rendering them unable to login.

### Steps to reproduce:

Try to login or sync data of a user with multiple email LDAP entries.

### Expected behavior:

The first email that has been found should be used as the users email address.

### Actual behavior:

Login and data sync fails for users with multiple email addresses.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Centos 7
- Deployment Method: docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.10

### Additional context

This is similar to a previous issue #2642 that has supposedly been fixed. I'm using FreeIPA as the LDAP provider.

### Relevant logs:

```
server.js:207 LDAPSync ➔ error Error creating user { Error: Match error: Expected string, got object in field email
    at check (packages/check/match.js:36:17)
    at createUser (packages/accounts-password/password_server.js:1052:3)
    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1147:10)
    at addLdapUser (app/ldap/server/sync.js:264:29)
    at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:150:17)
    at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)
    at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
  message: 'Match error: Expected string, got object in field email',
  path: 'email',
  sanitizedError: 
   { Error: Match failed [400]
    at errorClass.<anonymous> (packages/check/match.js:91:27)
    at new errorClass (packages/meteor.js:725:17)
    at check (packages/check/match.js:36:17)
    at createUser (packages/accounts-password/password_server.js:1052:3)
    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1147:10)
    at addLdapUser (app/ldap/server/sync.js:264:29)
    at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:150:17)
    at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)
    at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
     isClientSafe: true,
     error: 400,
     reason: 'Match failed',
     details: undefined,
     message: 'Match failed [400]',
     errorType: 'Meteor.Error' },
  errorType: 'Match.Error' }
```

**Comment by reetp** [comment]
Probably a duplicate of:
https://github.com/RocketChat/Rocket.Chat/issues/10247

This may be related as well:
https://github.com/RocketChat/Rocket.Chat/issues/12565

I think this was meant to be closed here:
https://github.com/RocketChat/Rocket.Chat/issues/2642

With this PR:
https://github.com/RocketChat/Rocket.Chat/pull/8372

There seem to be several other Issues all related  - I haven't got the time to go through and tie them all up. Perhaps the OP would like to pull them all together?

Start with something like this:

https://github.com/RocketChat/Rocket.Chat/issues?utf8=%E2%9C%93&q=is%3Aissue+got+object+in+field+email
