### ISSUE TITLE
JIRA notifications don't work

### ISSUE THREAD

**Issue by pawel-szon** [RocketChat/Rocket.Chat#14760]
### Description:

JIRA Integration doesn't send notifications to connected private group/channel. 

### Steps to reproduce:

1. Install and configure JIRA app as in documentation: https://rocket.chat/docs/administrator-guides/rocket-chat-apps/jira-server-integration/
2. Connect to one of the JIRA projects.
3. Modify/comment/transition one of the issues in the connected JIRA project.

### Expected behavior:

Notification shows up in the connected private group/channel.

### Actual behavior:

Notification doesn't show up, there is an exception in the server log.
 
### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Debian 9.9
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.4 - x64
- MongoDB Version: 4.0.4

### Additional context

JIRA version: JIRA Software 7.9.2
### Relevant logs:

```
server.js:207 System ➔ error Error sending message: { Error: [error-not-allowed]
    at canSendMessage (app/authorization/server/functions/canSendMessage.js:15:9)
    at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:80:17)
    at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:62:34)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1685:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at resolve (packages/ddp-server/livedata_server.js:1683:36)
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1682:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1621:26)
    at Server.call (packages/ddp-server/livedata_server.js:1603:17)
    at DDPCommon.MethodInvocation.Meteor.runAsUser (app/apps/server/bridges/messages.js:19:17)
    at packages/dispatch_run-as-user.js:211:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
    at Promise.asyncApply (app/apps/server/bridges/messages.js:18:10)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
  isClientSafe: true,
  error: 'error-not-allowed',
  reason: undefined,
  details: undefined,
  message: '[error-not-allowed]',
  errorType: 'Meteor.Error' }
=== UnHandledPromiseRejection ===
TypeError: Cannot read property '_id' of undefined
    at Promise.asyncApply (app/apps/server/bridges/messages.js:22:14)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
---------------------------------
Errors like this can cause oplog processing errors.
Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Future node.js versions will automatically exit the process
```

**Comment by gyverchang** [comment]
Same issue as well.

**Comment by apazureck** [comment]
In the original webhook they don't catch if issues don't have a priority. Replace the script in the webhook with this one:

```js
/*jshint  esnext:true*/
const DESC_MAX_LENGTH = 140;
const JIRA_LOGO = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACRElEQVRYhbWXsUscQRTGf4iIyHHIISIWIsHisMgfkNIiBJFwiKQIkipVqpA/wEZEggSxEkmZwiKI5A84REKKkIMQrINYBQmHBDmEHJdNMW+42dk3d3O76wcDu2/e973vZvfN7EF+PAfaMjYL6AzFJFBRYh0gkdEBpryciuQVwjPgFugCu068CvQcAz1g2pnfEc6taOTGL6dIAjxw5nad+FsnvuhxrosYuPbElrz5Rc8Ucu9yfhcxsAncYZZ4fwTeO+HcUcILWgFqOXg1si9vFBrAXB7iEMySfYQZzGCeWxdoAq+Bh8BYjoJjwn0jWrYrqsOIbdIvUQLseTmPgHXgiYx1ibnYU3RuYpyfKMQ/mNWx+KzkfHHmZ4Tj55zGGNhQiAlw5OQ8VeYbzvxRQCNqUxoHLgMCa07eRyd+4sTXAtwrYCLGAJje1URugLrkVIHvMuyLVZccjfsitrhFMyD0k36bTtA/cOZkTuOckaOTFtA7IgEuSG9ONeBHILctWrnwGNO/mvA3zAk4LddaThfTpoXwKiBuVyL0yxPhloLtAUVCY7us4hb7IxQ/KLu4xWFE8cP7Kg6mld4PKH5BvoNrZBMfBphohKnFMAusyvU48ClgoA3M34eBUynwUu6ngK8BE1Gn3ihYccR79Jd5nuyXsx0rZRo498Q7mK8dMDudZuC8rOLLgQI7Ts5xIGe5DANbinCP9AfmEul/SnZslWHgTBFuKnna8a3lpRCzadSVWMiAj6GPIMbAX+/+H9BS8loyN4ibwX9j/jIXDkk+pgAAAABJRU5ErkJggg==';
function stripDesc(str) {
	return (str && str.length > DESC_MAX_LENGTH) ? str.slice(0, DESC_MAX_LENGTH - 3) + '...' : str;
}

function prepareAttachment({issue, user}, text) {
	let issueType = issue.fields.issuetype;
	let res = {
		author_name: user.displayName
		, author_icon: user.avatarUrls['24x24']
		, thumb_url: issueType.iconUrl
	};
	if (text) {
		text = text.replace(/\{\{(user|issue)\.([^a-z_0-9]+)\}\}/g, (m, type, key) => (type==='user' ? user : issue)[key]);
		res.text = text;
	}
	return res;
}
class Script {
	process_incoming_request({request}) {
		const data = request.content;
		try {
			if (!data.issue || (data.user && data.user.name === 'gitlab')) {
				return;
			}
			let issue = data.issue;
			let baseJiraUrl = issue.self.replace(/\/rest\/.*$/, '');
			let user = data.user;
			let assignedTo = (issue.fields.assignee && issue.fields.assignee.name !== user.name) ? `, assigned to ${issue.fields.assignee.displayName}` : '';
          console.log("priority: " + JSON.stringify(issue.fields.priority));
			let issueSummary = `[${issue.key}](${baseJiraUrl}/browse/${issue.key}) ${issue.fields.summary}` + (issue.fields.priority ? ( " " + issue.fields.priority.name.replace(/^\s*\d*\.\s*/, '')) : "") + (assignedTo ? `**(${assignedTo})**` : "");
			let message = {
				icon_url: (issue.fields.project && issue.fields.project.avatarUrls && issue.fields.project.avatarUrls['48x48']) || JIRA_LOGO
				, attachments: []
			};

			if (data.webhookEvent === 'jira:issue_created') {
				message.attachments.push(prepareAttachment(data, `*Created* ${issueSummary}:\n${stripDesc(issue.fields.description)}`));
			} else if (data.webhookEvent === 'jira:issue_deleted') {
				message.attachments.push(prepareAttachment(data, `*Deleted* ${issueSummary}`));
			} else if (data.webhookEvent === 'jira:issue_updated') {
				if (data.changelog && data.changelog.items) { // field update
					let logs = [];
					data.changelog.items.forEach((change) => {
						if (!change.field.match('status|resolution|comment|priority') ) {
							return;
						}
						if (change.field==='description') {
							logs.push(`Changed *description* to:\n${stripDesc(change.toString)}`);
						} else {
							logs.push(`*${change.field}* changed from ${change.fromString} to *${change.toString}*`);
						}
					});
					logs.length && message.attachments.push(prepareAttachment(data, `*Updated* ${issueSummary}:\n  - ${logs.join('\n  - ')}`));
				}

				if (data.comment) { // comment update
					let comment = data.comment;
					let action = comment.created !== comment.updated ? 'Updated comment' : 'Commented';
					message.attachments.push(prepareAttachment(data, `*${action}* on ${issueSummary}:\n${stripDesc(comment.body)}`));
				}
			}

			if (message.text || message.attachments.length) {
				return {content:message};
			}
		} catch(e) {
			console.log('jiraevent error', e);
			return {
				error: {
					success: false,
					message: `${e.message || e} ${JSON.stringify(data)}`
				}
			};
		}
	}
}
```

**Comment by Shaverdoff** [comment]
for a while add to room where you connect jira-app Rocket.Cat bot. the app do not understud delete events. it don't understund it yet

**Comment by pawel-szon** [comment]
@apazureck Thanks for your comment. I guess you are referring to this webhook: https://rocket.chat/docs/administrator-guides/integrations/jira/

The issue is not with a webhook but with JIRA Server integration app from marketplace, mentioned in docs: https://rocket.chat/docs/administrator-guides/rocket-chat-apps/jira-server-integration/

**Comment by apazureck** [comment]
But does the extension not create a webhook? You can replace the script in the integration section then.

**Comment by pawel-szon** [comment]
Hmm probably it does but the webhook is not visible in the Integration section in Settings.

**Comment by Shaverdoff** [comment]
As I understud Webhook in rc do not appear with installation jira server app integration. You will see it in Jira on (instance+domain name)/plugins/servlet/webhooks#

 

 

--

Gerasim Shaverdov | Deputy CTO | Altarix 

Mobile:  <tel:+7%20937%20070%2066%2084> +7 937 070 66 84 | Skype/email :  <mailto:gerasim@altarix.ru> gerasim@altarix.ru
Lenina av.25, Samara, Russia, 443068
