### ISSUE TITLE
Guest access broken

### ISSUE THREAD

**Issue by arminfelder** [RocketChat/Rocket.Chat#14778]
since RC 1.0.0 anonymous write access is broken,
with 1.0.0, when the user clicks on the join button, the following line pops up in the log:
Exception while invoking method 'registerUser' TypeError: Cannot read property 'facebook' of undefined     at getAvatarSuggestionForUser (app/lib/server/functions/getAvatarSuggestionForUser.js:12:20)     at AccountsServer.<anonymous> (server/lib/accounts.js:221:29)     at executeBound (/app/bundle/programs/server/npm/node_modules/underscore/underscore.js:762:67)     at AccountsServer.bound [as insertUserDoc] (/app/bundle/programs/server/npm/node_modules/underscore/underscore.js:793:14)     at MethodInvocation.registerUser (server/methods/registerUser.js:22:28)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:73:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 

with 1.1 and 1.2, I don't even see the messages, only the 3 dots, and the logs shows:
Meteor ➔ publish null -> userId: null , arguments:  [] 
Meteor ➔ method public-settings/get -> userId: null , arguments:  [] 
Meteor ➔ publish userData -> userId: null , arguments:  [] 
Meteor ➔ method loadLocale -> userId: null , arguments:  [ 'de' ]

**Comment by arminfelder** [comment]
seems to be already reported here: #14764
