### ISSUE TITLE
Cant upload image file

### ISSUE THREAD

**Issue by gerroon** [RocketChat/Rocket.Chat#14816]
Hi

I just installed Rocket using the official docker compose method with all the default settings (except the ip adresses and host name). I installed it on Debian Buster x64. 

Since this is a test install I am just using it internally on my Lan. Everything seems to work except adding an image to the default chat room. Please see the error

Basically the image upload to the room is stuck at %0 with no progress

```


rocketchat_1          | Error: FileNotFound: no file with id CEaggXETg8nWE2mYs found
rocketchat_1          |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:188:25
rocketchat_1          |     at result (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:414:17)
rocketchat_1          |     at session.endSession (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:401:11)
rocketchat_1          |     at ClientSession.endSession (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sessions.js:129:41)
rocketchat_1          |     at executeCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:397:17)
rocketchat_1          |     at deleteCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:329:17)
rocketchat_1          |     at removeDocuments (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:344:54)
rocketchat_1          |     at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:128:55)
rocketchat_1          |     at coll.s.topology.remove (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:1168:5)
rocketchat_1          |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
rocketchat_1          |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
rocketchat_1          |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)


```

**Comment by gerroon** [comment]
I tried this with the mobile app uploading works however I get the error above when I try with Chromium or Firefox on my desktops

**Comment by reetp** [comment]
This seems most likely to ve a setup/support Issue and not a bug in Rocket.Chat

Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/

If you feel it is a bug please fill out a proper Issue template and give full details on your deployment including your compose file and the document you followed.

Use this link: https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md


Here is an example of how to do it properly:
 https://github.com/RocketChat/Rocket.Chat/issues/13069
