### ISSUE TITLE
Sudden timeouts

### ISSUE THREAD

**Issue by josephchan91** [RocketChat/Rocket.Chat#14846]
### Description:

Hi everyone, I just set up a Rocket chat server for our workplace of around 300 active users. Things work fine, but there are occasions when the service just stops working.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-51-generic x86_64)
- Deployment Method: Digital Ocean one-click
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.9

### Relevant logs:
```
Jun 21 06:00:40 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]: DDP RATE LIMIT: limit by connectionId per method
Jun 21 06:00:40 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]: {
Jun 21 06:00:40 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   "allowed": false,
Jun 21 06:00:40 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   "timeToReset": 98,
Jun 21 06:00:40 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   "numInvocationsLeft": 0,
Jun 21 06:00:40 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   "userId": "5oCGkB7sjT2yKj4P5",
Jun 21 06:00:40 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   "clientAddress": "127.0.0.1",
Jun 21 06:00:40 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   "type": "method",
Jun 21 06:00:40 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   "name": "readMessages",
Jun 21 06:00:40 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   "connectionId": "AoY7qx4ncCpXLqEiG",
Jun 21 06:00:40 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   "broadcastAuth": false
Jun 21 06:00:40 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]: }
```

```
<!-- Logs from both SERVER and BROWSER -->
TypeError: Cannot read property 'remoteAddress' of undefined
Jun 21 07:31:22 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at Object._internalRouteActionHandler [as action] (packages/rocketchat:api/server/api.js:215:176)
Jun 21 07:31:22 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Jun 21 07:31:22 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at packages/nimble_restivus/lib/route.coffee:59:33
Jun 21 07:31:22 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at packages/simple_json-routes.js:98:9
```

```
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]: { Error: ENOENT: no such file or directory, mkdir '/tmp/userData/GjRG5iPimq8dn573n/partial'
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at Object.fs.mkdirSync (fs.js:885:18)
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at createDir (packages/rocketchat:user-data-download/server/cronProcessDownloads.js:33:6)
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at continueExportingRoom (packages/rocketchat:user-data-download/server/cronProcessDownloads.js:186:2)
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at exportOperation.roomList.forEach.exportOpRoomData (packages/rocketchat:user-data-download/server/cronProc$
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at Array.forEach (<anonymous>)
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at continueExportOperation (packages/rocketchat:user-data-download/server/cronProcessDownloads.js:417:29)
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at cursor.forEach.exportOperation (packages/rocketchat:user-data-download/server/cronProcessDownloads.js:467$
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1107:16)
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:887:44)
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at Object.processDataDownloads [as job] (packages/rocketchat:user-data-download/server/cronProcessDownloads.$
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at packages/littledata_synced-cron.js:251:26
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at scheduleTimeout (packages/littledata_synced-cron.js:304:9)
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at packages/littledata_synced-cron.js:356:42
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at packages/meteor.js:620:25
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:     at runWithEnvironment (packages/meteor.js:1356:24)
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   errno: -2,
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   code: 'ENOENT',
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   syscall: 'mkdir',
Jun 21 07:45:09 rocketchat-s-1vcpu-1gb-sgp1-01 rocketchat[17305]:   path: '/tmp/userData/GjRG5iPimq8dn573n/partial' }
```

**Comment by novacrazy** [comment]
I know DigitalOcean had a server migration thing yesterday that interrupted a bunch of servers, resetting them without proper shutdown, and afterwards my server was showing this exact same issue with partial user data temp files not existing. The fact I had that feature disabled makes it even more silly.

It's not a particularly good solution, but what I had to do to get things back up and running was [comment out the code that starts the user data download service](https://github.com/RocketChat/Rocket.Chat/blob/d53e264b83ccc971236123853e4b68c9eb6beeb4/app/user-data-download/server/cronProcessDownloads.js#L477-L487).

**Comment by reetp** [comment]
Suggest you have a look at the rate limiter in admin.

admin/Rate Limiter

Looks like something is triggering it. Need to have a look at exactly what.

Note you should really be on latest v1.1.2 but understand that despite updates being submitted to DO they haven't done anything yet.

**Comment by josephchan91** [comment]
I just updated to 1.1.2. Hopefully it should resolve things.
