### ISSUE TITLE
custom oauth does not work

### ISSUE THREAD

**Issue by huytn** [RocketChat/Rocket.Chat#14866]
I had a openid server (phpoidc) and I configured custom oauth: 

> URL: https://openid.domain.com
> Token path: /index.php/token
> Token sent via: Payload
> Identity token sent via: Header
> Identity path: /index.php/userinfo
> Authorize path: /index.php/auth
> Scope: openid email
> Id: xxx
> Secret: xxxxxx
> Login Style: Redirect
> Username field: preferred_username

The issue is: after I successfully logined openid server but rocket chat still redirect to its login page.
Here is access log:
```
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:26:58 +0000] "GET /_timesync HTTP/1.1" 200 13 "https://rocketchat.domain.com/admin/OAuth" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:11 +0000] "GET /sockjs/info?cb=5lh8mkl7ls HTTP/1.1" 200 90 "https://rocketchat.domain.com/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:12 +0000] "GET /_timesync HTTP/1.1" 200 13 "https://rocketchat.domain.com/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:13 +0000] "GET /sockjs/642/zac8n6f9/websocket HTTP/1.1" 101 1043 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:13 +0000] "GET /sockjs/info?cb=mj0t86f7pn HTTP/1.1" 200 89 "https://rocketchat.domain.com/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:15 +0000] "GET /_timesync HTTP/1.1" 200 13 "https://rocketchat.domain.com/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:15 +0000] "GET /sockjs/476/zo_yedld/websocket HTTP/1.1" 101 987 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:26 +0000] "GET /_timesync HTTP/1.1" 200 13 "https://rocketchat.domain.com/admin/OAuth" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:43 +0000] "GET /_oauth/cid?state=eyJsb2dpblN0eWxlIjoicmVkaXJlY3QiLCJjcmVkZW50aWFsVG9rZW4iOiJXR1ZTa3VKUkFVdUdOb2U0dVN5TWVNYjNtS3FFZFBkc2pyZzJUZUJiUXYtIiwiaXNDb3Jkb3ZhIjpmYWxzZSwicmVkaXJlY3RVcmwiOiJodHRwczovL3JhYmJpdC5oaWdodHJ1c3RlZC5jb20vaG9tZSJ9&session_state=e06e4fcd51f9548de79c9b12dc587c907090c05fc2bf4721dea48d5fb58eb1ea.639682d2cddf14fd3c3ec0131f4040ea&code=H5SXS7k6velsXQR02r8CaI6-O-Er17tesRc17Nv1rUc HTTP/1.1" 200 284 "https://openid.domain.com/index.php/auth?client_id=rocket_chat&redirect_uri=https://rocketchat.domain.com/_oauth/cid&response_type=code&state=eyJsb2dpblN0eWxlIjoicmVkaXJlY3QiLCJjcmVkZW50aWFsVG9rZW4iOiJXR1ZTa3VKUkFVdUdOb2U0dVN5TWVNYjNtS3FFZFBkc2pyZzJUZUJiUXYtIiwiaXNDb3Jkb3ZhIjpmYWxzZSwicmVkaXJlY3RVcmwiOiJodHRwczovL3JhYmJpdC5oaWdodHJ1c3RlZC5jb20vaG9tZSJ9&scope=openid%20email" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:43 +0000] "GET /packages/oauth/end_of_redirect_response.js HTTP/1.1" 304 0 "https://rocketchat.domain.com/_oauth/cid?state=eyJsb2dpblN0eWxlIjoicmVkaXJlY3QiLCJjcmVkZW50aWFsVG9rZW4iOiJXR1ZTa3VKUkFVdUdOb2U0dVN5TWVNYjNtS3FFZFBkc2pyZzJUZUJiUXYtIiwiaXNDb3Jkb3ZhIjpmYWxzZSwicmVkaXJlY3RVcmwiOiJodHRwczovL3JhYmJpdC5oaWdodHJ1c3RlZC5jb20vaG9tZSJ9&session_state=e06e4fcd51f9548de79c9b12dc587c907090c05fc2bf4721dea48d5fb58eb1ea.639682d2cddf14fd3c3ec0131f4040ea&code=H5SXS7k6velsXQR02r8CaI6-O-Er17tesRc17Nv1rUc" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:44 +0000] "GET /theme.css?d88419a6c5cbc3fa8965896ce8c03b557e81f505 HTTP/1.1" 200 11066 "https://rocketchat.domain.com/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:45 +0000] "GET /home HTTP/1.1" 200 80161 "https://rocketchat.domain.com/_oauth/cid?state=eyJsb2dpblN0eWxlIjoicmVkaXJlY3QiLCJjcmVkZW50aWFsVG9rZW4iOiJXR1ZTa3VKUkFVdUdOb2U0dVN5TWVNYjNtS3FFZFBkc2pyZzJUZUJiUXYtIiwiaXNDb3Jkb3ZhIjpmYWxzZSwicmVkaXJlY3RVcmwiOiJodHRwczovL3JhYmJpdC5oaWdodHJ1c3RlZC5jb20vaG9tZSJ9&session_state=e06e4fcd51f9548de79c9b12dc587c907090c05fc2bf4721dea48d5fb58eb1ea.639682d2cddf14fd3c3ec0131f4040ea&code=H5SXS7k6velsXQR02r8CaI6-O-Er17tesRc17Nv1rUc" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:49 +0000] "GET /assets/favicon.svg HTTP/1.1" 304 0 "https://rocketchat.domain.com/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:49 +0000] "GET /images/logo/logo.svg HTTP/1.1" 304 0 "https://rocketchat.domain.com/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:50 +0000] "GET /sockjs/info?cb=c1r11o8sry HTTP/1.1" 200 90 "https://rocketchat.domain.com/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
xxx.xxx.xxx.xxx - - [25/Jun/2019:08:27:52 +0000] "GET /_timesync HTTP/1.1" 200 13 "https://rocketchat.domain.com/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0
```

**Comment by huytn** [comment]
here is log:
```
W20190626-03:37:55.154(0) (oauth_server.js:392) Error in OAuth Server: Failed to complete OAuth handshake with cid at https://openid.domain.com/index.php/token. Parse Error
I20190626-03:38:00.628(0) Exception while invoking method 'login' { Error: Failed to complete OAuth handshake with cid at https://openid.domain.com/index.php/token. Parse Error     at CustomOAuth.getAccessToken (app/custom-oauth/server/custom_oauth_server.js:132:18)     at Object.OAuth.registerService.query [as handleOauthRequest] (app/custom-oauth/server/custom_oauth_server.js:188:26)     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)     at middleware (packages/oauth/oauth_server.js:161:5)     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40   message: 'Failed to complete OAuth handshake with cid at https://openid.domain.com/index.php/token. Parse Error' }
```

my openid server worked with https://appauth.io

**Comment by huytn** [comment]
The error code is HPE_INVALID_HEADER_TOKEN, how do I resolve this issue?

**Comment by lbblitz54** [comment]
Same here

**Comment by lbblitz54** [comment]
I looked in Rocket.Chat/app/custom-oauth/custom_oauth_server.js , and I found rocket chat call function getAccessToken(query) to use authorisation code to get access token from OAuth provider.

In getAccessToken(query) I found only 'User-Agent' and 'Accept' is provided in request header. However according to the offical documentation (https://docs.aws.amazon.com/cognito/latest/developerguide/userinfo-endpoint.html) , 'Authroization' and 'Content-Type' is required in request header send to Cognito TOKEN Endpoint. Apart from header, the request parameters in request body are not sufficient either. Consequently, the integration will not work without modifying the source code, according to my understanding.

**Comment by Hudell** [comment]
You can send 'Authorization' through the header by selecting it on the "Identity Token sent via" setting on the custom oauth setup.

**Comment by lbblitz54** [comment]
> You can send 'Authorization' through the header by selecting it on the "Identity Token sent via" setting on the custom oauth setup.

Changing to "Header" vs "Payload" does at least give an error of "Internal Server Error"
![image](https://user-images.githubusercontent.com/17748076/61146261-3952e500-a49f-11e9-924a-c1e1cb4ba240.png)

**Comment by lbblitz54** [comment]
![Screenshot from 2019-07-12 12-02-15](https://user-images.githubusercontent.com/17748076/61147429-f0e8f680-a4a1-11e9-9cb5-5f45d5570811.png)

**Comment by huytn** [comment]
@Hudell, Don't need to do this, because openid server responsed expected json data. (I did it by using curl).

**Comment by lbblitz54** [comment]
I have resolved Custom Oauth with AWS Cognito with the help of the following AWS Doc  and the following RC settings. https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html
Token Path: /oauth2/token
Token Sent Via: Header
ID Token Sent Via: Header
Identity Path: /oauth2/userInfo
Authorize Path: /login
Scope: openid
Param Name for AT: access_token

**Comment by Hudell** [comment]
Thank you for sharing the proper settings, @lbblitz54 
I'll be closing this now since the original issue is also solved with the "Identity Token sent via" setting.

**Comment by sulabhpracbee** [comment]
> Same here, I'm trying to get it working with AWS Cognito Oauth and it seems to accept credentials, but then just redirects to the login page

hey. I am having the same issue. I have tried all possible settings and it still redirects to login page after accepting AWS Cognito credentials. Any pointers how you solved it?
