### ISSUE TITLE
Change of avatar causes restart of process

### ISSUE THREAD

**Issue by palacz123** [RocketChat/Rocket.Chat#1487]
I have a Rocket.Chat instance running on standalone server (no docker etc.). LDAP authentication is used to logon.

Every time user attempts to change avatar, rocket.chat process restarts. In log I can see following:

<pre>
==> err-0.log <==
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

/home/chat/rocket.chat/bundle/programs/server/packages/meteor.js:974
    throw new Error("Meteor code must always run within a Fiber. " +          
          ^
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at Object.Meteor.isRestricted (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:137:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:268:1)
    at Object.UserPresence.removeConnectionsByInstanceId (packages/konecty_user-presence/packages/konecty_user-presence.js:88:1)
    at process.<anonymous> (packages/konecty_user-presence/packages/konecty_user-presence.js:223:1)
    at process.emit (events.js:117:20)
    at process.exit (node.js:740:17)
    at process.catchException (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:52:15)
    at process.g (events.js:180:16)
</pre>

This feature worked fine up until around 1-2 weeks ago. Using development branch but the same issue happens with master.

I'd appreciate some advice.

**Comment by marceloschmidt** [comment]
How are your LDAP settings defined and is your avatar storage on GridFS or FileSystem (assuming you're uploading an image)? We're no experts on LDAP, but I have it running on a docker machine, so I might be able to hep you.

**Comment by palacz123** [comment]
Thanks for picking it up Marcelo,

LDAP settings are pretty basic. It requires user to be member of group within domain. There's no issues here.

Issue happens when user (LDAP user, haven't tested with local) uploads image file as avatar.

Avatar settings are as such:
<pre>
Resize Avatar: true
Avatar Size: 200
Avatar Storage Path: /var/www/rocket.chat/uploads/avatar/
Avatar Storage Type: GridFS
</pre>

**Comment by marceloschmidt** [comment]
This is probably related to resizing avatars, which requires graphicsmagick. See https://github.com/RocketChat/Rocket.Chat/issues/993#issuecomment-154115993. 

Can you disable resize avatar and see if that works? Thanks!

**Comment by palacz123** [comment]
Thanks a lot Marcelo! This is exactly what was causing the issue.

First attempt to upload new avatar after disabling Resize Avatar option caused restart again, but it was working fine in following attempts.
Installation of GraphicsMagick solved issue with Resize Avatar option enabled.

As improvement I'd suggest making this exception more explicit so that the error message is helpful.

Thanks very much for your help Marcelo!

**Comment by marceloschmidt** [comment]
Yes, we definitely need to make it clear that we have a dependency on that.
Thanks!
