### ISSUE TITLE
LDAP sync/import Execute Synchronisation Now not work but on login yes

### ISSUE THREAD

**Issue by bu3tt1** [RocketChat/Rocket.Chat#14925]
### Description:

When I click Execute Synchronisation Now the name and email are not synchronized, but on login are synchronized

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Mac OS
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: rocket.chat:1.2.1
- MongoDB Version: mongo:3.6.13

### Relevant logs:

```
rocketchat            | server.js:207 LDAPSync ➔ error Error creating user { Error: [error-invalid-domain]
rocketchat            |     at server/lib/accounts.js:307:10
rocketchat            |     at _validateNewUserHooks.forEach.hook (packages/accounts-base/accounts_server.js:1094:13)
rocketchat            |     at Array.forEach (<anonymous>)
rocketchat            |     at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1093:32)
rocketchat            |     at AccountsServer.<anonymous> (server/lib/accounts.js:179:28)
rocketchat            |     at executeBound (/app/bundle/programs/server/npm/node_modules/underscore/underscore.js:762:67)
rocketchat            |     at AccountsServer.bound [as insertUserDoc] (/app/bundle/programs/server/npm/node_modules/underscore/underscore.js:793:14)
rocketchat            |     at createUser (packages/accounts-password/password_server.js:1078:25)
rocketchat            |     at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1147:10)
rocketchat            |     at addLdapUser (app/ldap/server/sync.js:264:29)
rocketchat            |     at ldapUsers.forEach.ldapUser (app/ldap/server/sync.js:327:5)
rocketchat            |     at Array.forEach (<anonymous>)
rocketchat            |     at ldap.searchUsersSync.Meteor.bindEnvironment (app/ldap/server/sync.js:294:13)
rocketchat            |     at runWithEnvironment (packages/meteor.js:1356:24)
rocketchat            |   isClientSafe: true,
rocketchat            |   error: 'error-invalid-domain',
rocketchat            |   reason: undefined,
rocketchat            |   details: undefined,
rocketchat            |   message: '[error-invalid-domain]',
rocketchat            |   errorType: 'Meteor.Error' }
```

**Comment by Hudell** [comment]
May have been fixed on #14278
