### ISSUE TITLE
Exception in defer callback: { Error: Mail command failed: 555 5.5.2 Syntax error. l11sm4390931lfk.1 - gsmtp

### ISSUE THREAD

**Issue by anantaramdas** [RocketChat/Rocket.Chat#15016]
### Description:
Receiving exeption in syslog

### Steps to reproduce:

1. app up and running

### Expected behavior:

No exceptions

### Actual behavior:

Gives exception

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.3
- Operating System: Ubuntu 16,4
- Deployment Method: Manual: https://rocket.chat/docs/installation/manual-installation/ubuntu/
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.3
- MongoDB Version: v3.6.10

### Relevant logs:
```
Jul 19 04:10:01 vps13501ua rocketchat[16760]: Exception in defer callback: { Error: Mail command failed: 555 5.5.2 Syntax error. l11sm4390931lfk.1 - gsmtp
Jul 19 04:10:01 vps13501ua rocketchat[16760]:     at SMTPConnection._formatError (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)
Jul 19 04:10:01 vps13501ua rocketchat[16760]:     at SMTPConnection._actionMAIL (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:1280:34)
Jul 19 04:10:01 vps13501ua rocketchat[16760]:     at SMTPConnection._responseActions.push.str (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:797:18)
Jul 19 04:10:01 vps13501ua rocketchat[16760]:     at SMTPConnection._processResponse (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)
Jul 19 04:10:01 vps13501ua rocketchat[16760]:     at SMTPConnection._onData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)
Jul 19 04:10:01 vps13501ua rocketchat[16760]:     at TLSSocket._socket.on.chunk (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:462:47)
Jul 19 04:10:01 vps13501ua rocketchat[16760]:     at emitOne (events.js:116:13)
Jul 19 04:10:01 vps13501ua rocketchat[16760]:     at TLSSocket.emit (events.js:211:7)
Jul 19 04:10:01 vps13501ua rocketchat[16760]:     at addChunk (_stream_readable.js:263:12)
Jul 19 04:10:01 vps13501ua rocketchat[16760]:     at readableAddChunk (_stream_readable.js:250:11)
Jul 19 04:10:01 vps13501ua rocketchat[16760]:     at TLSSocket.Readable.push (_stream_readable.js:208:10)
Jul 19 04:10:01 vps13501ua rocketchat[16760]:     at TLSWrap.onread (net.js:597:20)
Jul 19 04:10:01 vps13501ua rocketchat[16760]:   code: 'EENVELOPE',
Jul 19 04:10:01 vps13501ua rocketchat[16760]:   response: '555 5.5.2 Syntax error. l11sm4390931lfk.1 - gsmtp',
Jul 19 04:10:01 vps13501ua rocketchat[16760]:   responseCode: 555,
Jul 19 04:10:01 vps13501ua rocketchat[16760]:   command: 'MAIL FROM' }
```

**Comment by reetp** [comment]
What type of deployment?
What are your mailer settings?
What were you doing to trigger this?

**Comment by anantaramdas** [comment]
Cannot reproduce how to trigger this - just normal use.
Will update deployment method in a second.
Regardsing mailer settings - need to clarify and will get back to you also.

**Comment by reetp** [comment]
>  response: '555 5.5.2 Syntax error. l11sm4390931lfk.1 - gsmtp

At a guess you are using gmail. Looks like a syntax error in your gmail settings somewhere. Do you have any odd characters in the email address?

If this is a manual deployment and not snap then also please test on latest 1.2.1

**Comment by anantaramdas** [comment]
Hi @reetp !
I have updated RC to latest version 1.2.1 and now I have following error:
```
I20190727-05:54:26.941(-4) Exception in defer callback: { Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8  https://support.google.com/mail/?p=BadCredentials s20sm9065013lfb.95 - gsmtp     at SMTPConnection._formatError (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)     at SMTPConnection._actionAUTHComplete (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:1254:34)     at SMTPConnection._responseActions.push.str (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:341:26)     at SMTPConnection._processResponse (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)     at SMTPConnection._onData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)     at TLSSocket._socket.on.chunk (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:462:47)     at emitOne (events.js:116:13)     at TLSSocket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at TLSSocket.Readable.push (_stream_readable.js:208:10)     at TLSWrap.onread (net.js:597:20)   code: 'EAUTH',   response: '535-5.7.8 Username and Password not accepted. Learn more at<br>535 5.7.8  https://support.google.com/mail/?p=BadCredentials s20sm9065013lfb.95 - gsmtp',   responseCode: 535,   command: 'AUTH PLAIN' } 
```

Login and password I rechecked few times - they are correct. SMTP configuration is:
Protocol: smtps
Host: smtp.gmail.com
Port: 465
IgnoreTLS: True
Pool: true
Username: <gmail email (no special chars there)>
Password: <gmail password>
From email: <same gmail email (no special chars there)>

Clicking on Send test mail to my user gives above error. Could you please advise?

**Comment by anantaramdas** [comment]
@reetp please ignore above - needed to setup applicaito password

**Comment by anantaramdas** [comment]
After upgrade I have following issues

````
Aug  5 07:03:16 vps13501ua rocketchat[2506]: DDP RATE LIMIT: limit by connectionId per method
Aug  5 07:03:16 vps13501ua rocketchat[2506]: {
Aug  5 07:03:16 vps13501ua rocketchat[2506]:   "allowed": false,
Aug  5 07:03:16 vps13501ua rocketchat[2506]:   "timeToReset": 3585,
Aug  5 07:03:16 vps13501ua rocketchat[2506]:   "numInvocationsLeft": 0,
Aug  5 07:03:16 vps13501ua rocketchat[2506]:   "userId": "9TXaiwMkKhKXCZvFz",
Aug  5 07:03:16 vps13501ua rocketchat[2506]:   "clientAddress": "127.0.0.1",
Aug  5 07:03:16 vps13501ua rocketchat[2506]:   "type": "subscription",
Aug  5 07:03:16 vps13501ua rocketchat[2506]:   "name": "stream-notify-user",
Aug  5 07:03:16 vps13501ua rocketchat[2506]:   "connectionId": "uDkZ9t8Fsxbgo2aAc",
Aug  5 07:03:16 vps13501ua rocketchat[2506]:   "broadcastAuth": false
Aug  5 07:03:16 vps13501ua rocketchat[2506]: }
````

and

````
Aug  5 08:37:30 vps13501ua rocketchat[2506]: server.js:207 #033[31mSystem вћ” error#033[39m Error sending push to gateway (0 try) -> { Error: connect ETIMEDOUT 3.92.249.169:443
Aug  5 08:37:30 vps13501ua rocketchat[2506]:     at Object._errnoException (util.js:992:11)
Aug  5 08:37:30 vps13501ua rocketchat[2506]:     at _exceptionWithHostPort (util.js:1014:20)
Aug  5 08:37:30 vps13501ua rocketchat[2506]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
Aug  5 08:37:30 vps13501ua rocketchat[2506]:   code: 'ETIMEDOUT',
Aug  5 08:37:30 vps13501ua rocketchat[2506]:   errno: 'ETIMEDOUT',
Aug  5 08:37:30 vps13501ua rocketchat[2506]:   syscall: 'connect',
Aug  5 08:37:30 vps13501ua rocketchat[2506]:   address: '3.92.249.169',
Aug  5 08:37:30 vps13501ua rocketchat[2506]:   port: 443 }
````

Any ideas where it came from? Where it connets?

**Comment by reetp** [comment]
For the DDP rate limiter check your reverse proxy

https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/#configuring-ssl-reverse-proxy

https://github.com/RocketChat/docs/pull/1372/files

I'd also suggest you keep a closer watch on releases - unless you are on snaps you should be on an absolute minimum of 1.1.4, preferably 1.2.3 and for testing any bugs always have a test VM and test on the latest which is currently 1.3.0

As per:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md
https://rocket.chat/docs/contributing/reporting-issues

"Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue."

>Error sending push to gateway (0 try) -> { Error: connect ETIMEDOUT 3.92.249.169:443

That is a different error again. Timeout to the push notification gateway gateway.rocket.chat

Can you ping it? Have you registered your instance? Any other log error anywhere?
