### ISSUE TITLE
Keycloak Self signed cert error

### ISSUE THREAD

**Issue by JoellyR** [RocketChat/Rocket.Chat#15132]
### Description:

When trying to set up a custom oAuth using KeyCloak.. I keep getting the listed in the logs section below.

### Steps to reproduce:

1. Set up a custom oAuth pointing to my instance of KeyCloak.
2. Go to the login page.
3. Click the KeyCloak log in button.
4. Get redirected back to the login page and nothing happens.
5. Check logs and see the following error.

### Expected behavior:

1. Set up a custom oAuth pointing to my instance of KeyCloak.
2. Go to the login page.
3. Click the KeyCloak log in button.
4. Get redirected back to the dashboard and the user is logged in.

### Actual behavior:

1. Set up a custom oAuth pointing to my instance of KeyCloak.
2. Go to the login page.
3. Click the KeyCloak log in button.
4. Get redirected back to the login page and user is not logged in.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: 
- Deployment Method: From dockerhub
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Relevant logs:

{"line":"392","file":"oauth_server.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with keycloak at https://vf-sso-keycloak-viewlet-framework.apps.dev.ecp.ehealthontario.ca/auth/realms/master/protocol/openid-connect/token . self signed certificate in certificate chain","time":{"$date":1565195011667},"level":"warn"}
Exception while invoking method 'login' { Error: Failed to complete OAuth handshake with keycloak at https://vf-sso-keycloak-viewlet-framework.apps.dev.ecp.ehealthontario.ca/auth/realms/master/protocol/openid-connect/token . self signed certificate in certificate chain
    at CustomOAuth.getAccessToken (app/custom-oauth/server/custom_oauth_server.js:132:18)
    at Object.OAuth.registerService.query [as handleOauthRequest] (app/custom-oauth/server/custom_oauth_server.js:188:26)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)
    at middleware (packages/oauth/oauth_server.js:161:5)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
  message: 'Failed to complete OAuth handshake with keycloak at https://vf-sso-keycloak-viewlet-framework.apps.dev.ecp.ehealthontario.ca/auth/realms/master/protocol/openid-connect/token . self signed certificate in certificate chain' }
{"line":"392","file":"oauth_server.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with keycloak at https://vf-sso-keycloak-viewlet-framework.apps.dev.ecp.ehealthontario.ca/auth/realms/master/protocol/openid-connect/token . self signed certificate in certificate chain","time":{"$date":1565195100016},"level":"warn"}
Exception while invoking method 'login' { Error: Failed to complete OAuth handshake with keycloak at https://vf-sso-keycloak-viewlet-framework.apps.dev.ecp.ehealthontario.ca/auth/realms/master/protocol/openid-connect/token . self signed certificate in certificate chain
    at CustomOAuth.getAccessToken (app/custom-oauth/server/custom_oauth_server.js:132:18)
    at Object.OAuth.registerService.query [as handleOauthRequest] (app/custom-oauth/server/custom_oauth_server.js:188:26)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)
    at middleware (packages/oauth/oauth_server.js:161:5)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
  message: 'Failed to complete OAuth handshake with keycloak at https://vf-sso-keycloak-viewlet-framework.apps.dev.ecp.ehealthontario.ca/auth/realms/master/protocol/openid-connect/token . self signed certificate in certificate chain' }

**Comment by col-panic** [comment]
Related https://github.com/RocketChat/hubot-rocketchat/issues/35

**Comment by col-panic** [comment]
For docker-compose, the environment variable NODE_TLS_REJECT_UNAUTHORIZED=0 does the trick of accepting self-signed certs. I don't think that this is a bug, but a regular feature.
