### ISSUE TITLE
Connection to mongodb timed out

### ISSUE THREAD

**Issue by javiergoni** [RocketChat/Rocket.Chat#15134]
### Description:

We have timeouts with our mongo database. Some users report problems connecting to rocketchat servers and other cannot send messages

It seems that some querys are too slow and do not end before the connection is closed
```
2019-08-07T17:23:14.249+0000 I COMMAND  [conn40] command rocketchat.rocketchat_message command: find { find: "rocketchat_message", filter: { $text: { $search: "3" }, t: { $ne: "rm" }, _hidden: { $ne: true }, rid: "3RAm7ciMCNTuNR7NSA8LThqozqNoRnAk6w" }, sort: { ts: -1 }, projection: { score: { $meta: "textScore" } }, limit: 10, returnKey: false, showRecordId: false } planSummary: IXSCAN { _fts: "text", _ftsx: 1 } keysExamined:138434 docsExamined:276868 hasSortStage:1 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:29933 nreturned:10 reslen:6658 locks:{ Global: { acquireCount: { r: 59870 } }, Database: { acquireCount: { r: 29935 } }, Collection: { acquireCount: { r: 29935 } } } protocol:op_query 1136998ms

2019-08-07T17:23:14.354+0000 I NETWORK  [conn40] SocketException handling request, closing client connection: 9001 socket exception [SEND_ERROR] server [<rocketchat-ip>:42124]
```

### Steps to reproduce:
I'm not able to reproduce this issue but happens almost every day in our system
1. Go to a chat room
2. Search for a message

### Expected behavior:
If the query takes to long to resolve, close the connection in a clean way

### Actual behavior:
Rocketchat is unusable for about 30 minutes

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.1
- Operating System: Ubuntu
- Deployment Method: tar
- Number of Running Instances: 4
- DB Replicaset Oplog: Yes
- NodeJS Version: 8.11.4
- MongoDB Version: 3.2.15

### Relevant logs:
```
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]: Exception in defer callback: { MongoNetworkError: connection 10 to <mongo primary node>:27017 timed out
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Socket.<anonymous> (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.
js:259:7)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Object.onceWrapper (events.js:313:30)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at emitNone (events.js:106:13)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Socket.emit (events.js:208:7)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Socket._onTimeout (net.js:410:8)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at ontimeout (timers.js:498:11)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at tryOnTimeout (timers.js:323:5)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Timer.listOnTimeout (timers.js:290:5)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:   name: 'MongoNetworkError',
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:   errorLabels: [ 'TransientTransactionError' ],
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:   [Symbol(mongoErrorContextSymbol)]: {} }
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]: Exception in setInterval callback: { MongoNetworkError: connection 10 to <mongo primary node>:27017 timed out
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Socket.<anonymous> (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.
js:259:7)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Object.onceWrapper (events.js:313:30)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at emitNone (events.js:106:13)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Socket.emit (events.js:208:7)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Socket._onTimeout (net.js:410:8)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at ontimeout (timers.js:498:11)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at tryOnTimeout (timers.js:323:5)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Timer.listOnTimeout (timers.js:290:5)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:   name: 'MongoNetworkError',
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:   errorLabels: [ 'TransientTransactionError' ],
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:   [Symbol(mongoErrorContextSymbol)]: {} }
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]: Exception in setInterval callback: { MongoNetworkError: connection 10 to <mongo primary node>:27017 timed out
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Socket.<anonymous> (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.
js:259:7)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Object.onceWrapper (events.js:313:30)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at emitNone (events.js:106:13)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Socket.emit (events.js:208:7)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Socket._onTimeout (net.js:410:8)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at ontimeout (timers.js:498:11)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at tryOnTimeout (timers.js:323:5)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Timer.listOnTimeout (timers.js:290:5)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:  => awaited here:
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Function.Promise.await (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:1
2)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Promise.asyncApply (packages/mongo/mongo_driver.js:1042:14)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at /home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:  => awaited here:
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Function.Promise.await (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:1
2)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at Promise.asyncApply (packages/mongo/mongo_driver.js:1042:14)
Aug  7 17:21:07 rocketchat-xxx rocketchat[20112]:     at /home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
.... and anothers 20000 silimar lines

```

**Comment by reetp** [comment]
You are probably not going to get a lot of help here because you are on such an old version (29th Dec 2018 which is a long time for a fast developing application).

See https://rocketchat.github.io/docs/contributing/reporting-issues/

> Before reporting a new issue
> .....
>     Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.

You need to test on latest which is currently 1.3.0

You also need to describe your hardware as well.
