### ISSUE TITLE
RocketChat doesn't start after update - AppArmor snap-update-ns.rocketchat-server apparmor="DENIED" operation="change_onexec"

### ISSUE THREAD

**Issue by alexp700** [RocketChat/Rocket.Chat#15169]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.3
- Operating System: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-55-generic x86_64)
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: N/A
- NodeJS Version: N/A
- MongoDB Version: N/A

### Additional context

I am running a dedicated ubuntu 18.04.1 install from the Ubuntu live server "CD", with rocketchat snap installed from setup. On update rocketchat fails to start. I can see in my syslog the following line:

Aug 13 11:40:12 rocketchat kernel: [   18.971673] audit: type=1400 audit(1565696412.081:11): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="unconfined" name="snap-update-ns.rocketchat-server" pid=1343 comm="snap-confine"

That sounds like the problem. I have applied the patch to apparmor mentioned here:

 https://github.com/RocketChat/Rocket.Chat/issues/14562

However with no success - that is a patch for the snmp blocking, and this appears to be some part of the update process.

I have been running Rocket since the beginning of the year, and it appears every time I reboot the rocketchat box it goes offline due to apparmor profiles or starting to quickly. If I should be installing a more reliable or preferred distro to run rocketchat I am happy to explore that possibility, as Ubuntu 18.04.1 seems unsupported - it couldn't be more vanilla than this!

Rocketchat is configured to run without https behind an HTTPS proxy, but otherwise is running on port 3000. 

### Relevant logs:

Aug 13 11:40:12 rocketchat kernel: [   18.971673] audit: type=1400 audit(1565696412.081:11): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="unconfined" name="snap-update-ns.rocketchat-server" pid=1343 comm="snap-confine"
Aug 13 11:40:12 rocketchat rocketchat-server.rocketchat-caddy[1260]: cannot change profile for the next exec call: No such file or directory
Aug 13 11:40:12 rocketchat rocketchat-server.rocketchat-caddy[1260]: snap-update-ns failed with code 1: File exists
Aug 13 11:40:12 rocketchat systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Main process exited, code=exited, status=1/FAILURE
Aug 13 11:40:12 rocketchat systemd[1]: Started LXD - container startup/shutdown.
Aug 13 11:40:12 rocketchat rocketchat-server.rocketchat-mongo[1258]: cannot change profile for the next exec call: No such file or directory
Aug 13 11:40:12 rocketchat rocketchat-server.rocketchat-mongo[1258]: snap-update-ns failed with code 1: File exists
Aug 13 11:40:12 rocketchat systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Main process exited, code=exited, status=1/FAILURE
Aug 13 11:40:12 rocketchat rocketchat-server.rocketchat-server[1259]: cannot change profile for the next exec call: No such file or directory
Aug 13 11:40:12 rocketchat rocketchat-server.rocketchat-server[1259]: snap-update-ns failed with code 1: File exists
Aug 13 11:40:12 rocketchat systemd[1]: snap.rocketchat-server.rocketchat-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 13 11:40:12 rocketchat systemd[1]: snap.rocketchat-server.rocketchat-server.service: Failed with result 'exit-code'.
Aug 13 11:40:12 rocketchat systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
Aug 13 11:40:12 rocketchat systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result 'exit-code'.

**Comment by alexp700** [comment]
I have disabled apparmor completely via grub - not ideal to say the least, but at least allowed me to get on - using:

`$ sudo mkdir -p /etc/default/grub.d
$ echo 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT apparmor=1 security=apparmor"' \
  | sudo tee /etc/default/grub.d/apparmor.cfg
$ sudo update-grub
$ sudo reboot`

and though the server did not start first time on reboot, it did start. The syslog for the first run looked like this:

`Aug 13 12:10:15 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T12:10:15.707+0000 I STORAGE  [initandlisten] Placing a marker at optime Aug  9 12:41:38:1
Aug 13 12:10:15 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T12:10:15.707+0000 I STORAGE  [initandlisten] Placing a marker at optime Aug 11 02:00:00:429
Aug 13 12:10:15 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T12:10:15.707+0000 I STORAGE  [initandlisten] Placing a marker at optime Aug 12 14:37:03:1
Aug 13 12:10:18 rocketchat systemd-resolved[725]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]: /snap/rocketchat-server/1392/programs/server/node_modules/fibers/future.js:313
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]: #011#011#011#011#011#011throw(ex);
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]: #011#011#011#011#011#011^
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at Pool.<anonymous> (/snap/rocketchat-server/1392/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at emitOne (events.js:116:13)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at Pool.emit (events.js:211:7)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at Connection.<anonymous> (/snap/rocketchat-server/1392/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at Object.onceWrapper (events.js:317:30)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at emitTwo (events.js:126:13)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at Connection.emit (events.js:214:7)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at Socket.<anonymous> (/snap/rocketchat-server/1392/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at Object.onceWrapper (events.js:315:30)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at emitOne (events.js:116:13)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at Socket.emit (events.js:211:7)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at emitErrorNT (internal/streams/destroy.js:64:8)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Aug 13 12:10:18 rocketchat rocketchat-server.rocketchat-server[938]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Aug 13 12:10:18 rocketchat systemd[1]: snap.rocketchat-server.rocketchat-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 13 12:10:18 rocketchat systemd[1]: snap.rocketchat-server.rocketchat-server.service: Failed with result 'exit-code'.`

and a little later:
`Aug 13 10:12:56 rocketchat systemd[1]: Started Service for snap application rocketchat-server.rocketchat-server.
Aug 13 10:12:56 rocketchat rocketchat-server.rocketchat-server[2731]: Checking if oplog has been enabled, and enabling if not
Aug 13 10:12:56 rocketchat rocketchat-server.rocketchat-server[2731]: MongoDB shell version v3.4.20
Aug 13 10:12:56 rocketchat rocketchat-server.rocketchat-server[2731]: connecting to: mongodb://127.0.0.1:27017
Aug 13 10:12:56 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:56.282+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:59242 #17 (1 connection now open)
Aug 13 10:12:56 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:56.282+0000 I NETWORK  [conn17] received client metadata from 127.0.0.1:59242 conn17: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.20" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
Aug 13 10:12:56 rocketchat rocketchat-server.rocketchat-server[2731]: MongoDB server version: 3.4.20
Aug 13 10:12:56 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:56.283+0000 I REPL     [conn17] replSetInitiate admin command received from client
Aug 13 10:12:56 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:56.284+0000 I -        [conn17] end connection 127.0.0.1:59242 (1 connection now open)
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:57.111+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:59246 #18 (1 connection now open)
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:57.118+0000 I NETWORK  [conn18] received client metadata from 127.0.0.1:59246 conn18: { driver: { name: "nodejs", version: "3.1.6" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-55-generic" }, platform: "Node.js v8.11.3, LE, mongodb-core: 3.1.5" }
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:57.128+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:59250 #19 (2 connections now open)
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:57.129+0000 I NETWORK  [conn19] received client metadata from 127.0.0.1:59250 conn19: { driver: { name: "nodejs", version: "3.1.6" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-55-generic" }, platform: "Node.js v8.11.3, LE, mongodb-core: 3.1.5" }
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:57.131+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:59254 #20 (3 connections now open)
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:57.131+0000 I NETWORK  [conn20] received client metadata from 127.0.0.1:59254 conn20: { driver: { name: "nodejs", version: "3.1.6" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-55-generic" }, platform: "Node.js v8.11.3, LE, mongodb-core: 3.1.5" }
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-server[2731]: /snap/rocketchat-server/1392/programs/server/node_modules/fibers/future.js:313
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-server[2731]: #011#011#011#011#011#011throw(ex);
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-server[2731]: #011#011#011#011#011#011^
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-server[2731]: MongoError: not master and slaveOk=false
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-server[2731]:     at queryCallback (/snap/rocketchat-server/1392/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-server[2731]:     at /snap/rocketchat-server/1392/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-server[2731]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-server[2731]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:57.154+0000 I -        [conn20] end connection 127.0.0.1:59254 (3 connections now open)
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:57.154+0000 I -        [conn19] end connection 127.0.0.1:59250 (2 connections now open)
Aug 13 10:12:57 rocketchat rocketchat-server.rocketchat-mongo[823]: 2019-08-13T10:12:57.154+0000 I -        [conn18] end connection 127.0.0.1:59246 (1 connection now open)
Aug 13 10:12:57 rocketchat systemd[1]: snap.rocketchat-server.rocketchat-server.service: Main process exited, code=exited, status=1/FAILURE`

So may be something about how Mongodb is shutdown?
