### ISSUE TITLE
Error when running recently built Docker image

### ISSUE THREAD

**Issue by marianotribuj** [RocketChat/Rocket.Chat#15338]
Hi! I'm trying to build a forked RC version on Mac (for the latest test, the fork is a fresh clone of the 1.3.0 tag).

Cloned the 1.3.0 tag, run meteor npm install & meteor npm start, and everything works well.

Then I'm starting building the docker image:

1) meteor build --server-only --directory ../output
2) moved to output, and removed (as mentioned in other issue, the node_modules folder)
3) copied the Dockerfile located in folder .docker
4) docker build .

Everything looks fine, tagged the image and specified that tag on my docker-compose.yml, but when I start a containers with that image I get:

Error: Cannot find module 'meteor-deque'
rocketchat_1          |     at Function.Module._resolveFilename (module.js:547:15)
rocketchat_1          |     at Function.resolve (internal/module.js:18:19)
rocketchat_1          |     at Object.require (/app/bundle/programs/server/boot.js:288:32)
rocketchat_1          |     at packages/meteor.js:854:32
rocketchat_1          |     at packages/meteor.js:1025:4
rocketchat_1          |     at packages/meteor.js:1578:3
rocketchat_1          |     at /app/bundle/programs/server/boot.js:411:36
rocketchat_1          |     at Array.forEach (<anonymous>)
rocketchat_1          |     at /app/bundle/programs/server/boot.js:220:19
rocketchat_1          |     at /app/bundle/programs/server/boot.js:471:5
rocketchat_1          | Tried 3 times. Waiting 5 secs...
rocketchat_1          | /app/bundle/programs/server/boot.js:475
rocketchat_1          | }).run();

Read somewhere to manually install that dependency:

5) Got into the container and run: npm install meteor-deque

Then the error changed to:

TypeError: require(...).enable is not a function
rocketchat_1          |     at reify.js (packages/modules.js:267:30)
rocketchat_1          |     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat_1          |     at Module.require (packages/modules-runtime.js:238:14)
rocketchat_1          |     at require (packages/modules-runtime.js:258:21)
rocketchat_1          |     at server.js (packages/modules.js:19:1)
rocketchat_1          |     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat_1          |     at Module.require (packages/modules-runtime.js:238:14)
rocketchat_1          |     at require (packages/modules-runtime.js:258:21)
rocketchat_1          |     at packages/modules.js:2728:15
rocketchat_1          |     at packages/modules.js:2735:3
rocketchat_1          | Tried 20 times. Waiting 5 secs...
^CERROR: Aborting.

I could continue analyzing and "fixing", but since it looks as a very simple task with a fresh install, I'm sure I'm doing something wrong.

Any help will be very appreciated!!!
Thanks!!

**Comment by reetp** [comment]
https://rocketchat.github.io/docs/contributing/reporting-issues/

`2. Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.`

So at the very least 1.3.2

`as mentioned in other issue`

Which 'other issue'?

**Comment by geekgonecrazy** [comment]
closing due to inactivity

**Comment by prevuelta** [comment]
Hi @marianotribuj did you ever solve this? It's the exact same problem I'm having trying to run a meteor app - any help appreciated!
