### ISSUE TITLE
Rocket.Chat 2.0.0 fails to start with "Can't find migration version 156"

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#15372]
Docker-compose install Rocket v2.0.0

Standalone (non docker) Mongo 4.0.5-18-g7e327a9017 - wiredTiger

I recently upgraded to Mongo 4 from Mongo 3.4

I then upgraded Rocket to v2.0.0

System has been running for several days in this configuration but I had to reboot today whereupon Rocket fails to start with this error:

```
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_server_type
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_token_path
CustomOAuth ➔ debug Init CustomOAuth wordpress { serverURL: '',
  identityPath: '/oauth/me',
  addAutopublishFields: 
   { forLoggedInUser: [ 'services.wordpress' ],
     forOtherUsers: [ 'services.wordpress.user_login' ] },
  accessTokenParam: 'access_token' }
Search Logger ➔ info create search provider defaultProvider
Search Logger ➔ info create search provider chatpalProvider
Exception in callback of async function: { Error: [Can't find migration version 156]
    at Object.Migrations._findIndexByVersion (app/migrations/server/migrations.js:402:8)
    at Object.Migrations._migrateTo (app/migrations/server/migrations.js:254:24)
    at Object.Migrations.migrateTo (app/migrations/server/migrations.js:179:20)
    at xrun.js (server/startup/migrations/xrun.js:6:13)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (server/startup/migrations/index.js:1:3286)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at main.js (server/main.js:1:200)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /app/bundle/programs/server/app/app.js:140805:15
    at /app/bundle/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /app/bundle/programs/server/boot.js:220:19
    at /app/bundle/programs/server/boot.js:471:5
    at Function.run (/app/bundle/programs/server/profile.js:510:12)
    at /app/bundle/programs/server/boot.js:470:11
  isClientSafe: true,
  error: 'Can\'t find migration version 156',
  reason: undefined,
  details: undefined,
  message: '[Can\'t find migration version 156]',
  errorType: 'Meteor.Error' }
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin_URL
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin_button_color

```
etc etc and until:

```
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_scope
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_secret
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_server_type
rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_token_path
```

And it just hangs there.

Tried this to no avail:

https://forums.rocket.chat/t/exception-in-callback-of-async-function-error-cant-find-migration-version-128-at-object-migrations-findindexbyversion/1397

```
use rocketchat
db.migrations.update({"_id": "control"}, {$set:{locked: false}})
```

`db.getCollection('migrations').find({})`

```
/* 1 */
{
    "_id" : "control",
    "version" : 156,
    "locked" : false,
    "lockedAt" : ISODate("2019-09-15T11:45:32.497Z"),
    "buildAt" : "2019-08-14T03:35:01.376Z"
}
```
So we are set false. Run Rocket and check again. Back to true:

```
/* 1 */
{
    "_id" : "control",
    "version" : 156,
    "locked" : true,
    "lockedAt" : ISODate("2019-09-15T12:09:43.861Z"),
    "buildAt" : "2019-08-14T03:35:01.376Z"
}
```

I presume it is all to do with removing/reinstalling Federation as per this:

https://github.com/RocketChat/Rocket.Chat/blob/18488e84f87485b053b51b3ca2df86c0a3337f14/server/startup/migrations/v156.js

Ironic bearing in mind I never touched Federation.

Note also I had been trying to register this system which was failing with no emails being sent to register and no token received as a result and I was about to open an issue with support.....

**Comment by reetp** [comment]
Doh...

My templating meant the compose file reverted to rocketchat:1.3.2 on reboot so it was trying to load the wrong version.

{slapshead}
