### ISSUE TITLE
Cannot start server after upgrade to 2.0.0 

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#15423]
### Description:
Server will not start with the following error in log:

```
Using GridFS for custom emoji storage
=== UnHandledPromiseRejection ===
{ MongoError: Cannot create view when the featureCompatibilityVersion is 3.2. See http://dochub.mongodb.org/core/3.4-feature-compatibility.
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  ok: 0,
  errmsg: 'Cannot create view when the featureCompatibilityVersion is 3.2. See http://dochub.mongodb.org/core/3.4-feature-compatibility.',
  code: 115,
  codeName: 'CommandNotSupported',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
---------------------------------
Errors like this can cause oplog processing errors.
Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Future node.js versions will automatically exit the process
=================================
```

### Steps to reproduce:

1. have existing server at 1.2
2. upgrade to rocketchat:latest image from docker hub

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System:  ubuntu 16.04lts
- Deployment Method:  docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version:  dockerhub RC 2.0 image
- MongoDB Version:  dockerhub image 3.4-xenial

**Comment by Sing-Li** [comment]
This is a problem related to upgrade of Mongo from 3.2 (non-supported) to 3.4 (recently deprecated).

https://docs.mongodb.com/manual/release-notes/3.4-upgrade-replica-set/

And is fixed by issuing the compatibility command in mongo shell.

```
db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )
```
