### ISSUE TITLE
“.S6UPZG7ZR3.chat.rocket.bgW2mr” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by ciarlystreet** [RocketChat/Rocket.Chat#15536]
Hi,
after updating macOs to Catalina, I can't open the Rocket.Chat app anymore:
```
“.S6UPZG7ZR3.chat.rocket.bgW2mr” cannot be opened because the developer cannot be verified.

macOS cannot verify that this app is free from malware.
```

If I click on cancel
```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: dlopen(/var/folders/jb/4lh4htxj5c9_7lpq9chy27qw0000gn/T/chat.rocket/.S6UPZG7ZR3.chat.rocket.pVSidF, 1): no suitable image found.  Did find:
	/var/folders/jb/4lh4htxj5c9_7lpq9chy27qw0000gn/T/chat.rocket/.S6UPZG7ZR3.chat.rocket.pVSidF: code signature in (/var/folders/jb/4lh4htxj5c9_7lpq9chy27qw0000gn/T/chat.rocket/.S6UPZG7ZR3.chat.rocket.pVSidF) not valid for use in process using Library Validation: library load disallowed by system policy
	/var/folders/jb/4lh4htxj5c9_7lpq9chy27qw0000gn/T/chat.rocket/.S6UPZG7ZR3.chat.rocket.pVSidF: stat() failed with errno=17
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/@paulcbetts/system-idle-time/addon.js:1:192)
```

macOs Catalina
Version 10.15 (19A583)
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Processor 2,3 GHz Dual-Core Intel Core i5
Memory 8 GB 2133 MHz LPDDR3
Graphis Intel Iris Plus Graphics 640 1536 MB

**Comment by metaer** [comment]
I have the same issue. @ciarlystreet How to fix that?

**Comment by romeucarvalho** [comment]
same here, but there is no problem with the version (2.15.5) that i downloaded from the website

**Comment by metaer** [comment]
Installed from App Store Rocket Chat have the same bug

**Comment by geekgonecrazy** [comment]
@tassoevan i know already on radar but reopening to direct people to
