### ISSUE TITLE
Amazon S3 File upload stopped working

### ISSUE THREAD

**Issue by sylvaint** [RocketChat/Rocket.Chat#15647]
### Description:
File upload to Amazon AWS S3 stopped working.
Error 500
Seems it does not resolve s3.amazonaws.com from error log below
This has been working fine until today, no change in configuration.

### Steps to reproduce:
Try uploading a File

### Expected behavior:
File uploads to target AWS S3 bucket

### Actual behavior:
Error 500

### Server Setup Information:
- Version of Rocket.Chat Server: 2.0.0 
- Operating System: CENTOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: 8.11.3 - x64
- MongoDB Version: 4.0.12

### Client Setup Information

- Desktop App or Browser Version:
Browser client Chrome
- Operating System:
OSX

### Relevant logs:

Exception while invoking method 'ufsComplete' { UnknownEndpoint: Inaccessible host: `s3.amazonaws.com'. This service may not be available in the `us-east-1' region.     at Request.ENOTFOUND_ERROR (/opt/Rocket.Chat/programs/server/npm/node_modules/aws-sdk/lib/event_listeners.js:486:46)     at Request.callListeners (/opt/Rocket.Chat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:106:20)     at Request.emit (/opt/Rocket.Chat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:78:10)     at Request.emit (/opt/Rocket.Chat/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)     at ClientRequest.error (/opt/Rocket.Chat/programs/server/npm/node_modules/aws-sdk/lib/event_listeners.js:325:22)     at ClientRequest.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/aws-sdk/lib/http/node.js:93:19)     at emitOne (events.js:116:13)     at ClientRequest.emit (events.js:211:7)     at TLSSocket.socketErrorListener (_http_client.js:387:9)     at emitOne (events.js:116:13)     at TLSSocket.emit (events.js:211:7)     at emitErrorNT (internal/streams/destroy.js:64:8)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   message: 'Inaccessible host: `s3.amazonaws.com\'. This service may not be available in the `us-east-1\' region.',   code: 'UnknownEndpoint',   region: 'us-east-1',   hostname: 's3.amazonaws.com',   retryable: true,   originalError:     { Error: getaddrinfo ENOTFOUND s3.amazonaws.com s3.amazonaws.com:443     at errnoException (dns.js:50:10)     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)      message: 'getaddrinfo ENOTFOUND s3.amazonaws.com s3.amazonaws.com:443',      code: 'NetworkingError',      errno: 'ENOTFOUND',      syscall: 'getaddrinfo',      hostname: 's3.amazonaws.com',      host: 's3.amazonaws.com',      port: 443,      region: 'us-east-1',      retryable: true,      time: 2019-10-22T22:20:44.186Z },   time: 2019-10-22T22:20:44.186Z }

**Comment by sylvaint** [comment]
host name server issue
