### ISSUE TITLE
Need help install rocket.chat manual on Windows Server 2012

### ISSUE THREAD

**Issue by vuongtran15** [RocketChat/Rocket.Chat#15756]
I install step by step follow install guide (https://rocket.chat/docs/installation/community-supported-installation/windows-server/)
- Node: v8.15.1
- Npm: 6.4.1
- Rocket releases 2.2.0 (https://github.com/RocketChat/Rocket.Chat/releases)

Everything is fine until I run command `node rocket.service.js install`, I recivce log file:
```
C:\Rocket.Chat\server\main.js:1
(function (exports, require, module, __filename, __dirname) { import './importPackages';
                                                                     ^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected string
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
C:\Rocket.Chat\server\main.js:1
(function (exports, require, module, __filename, __dirname) { import './importPackages';
                                                                     ^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
C:\Rocket.Chat\server\main.js:1
(function (exports, require, module, __filename, __dirname) { import './importPackages';
                                                                     ^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
C:\Rocket.Chat\node_modules\node-windows\lib\wrapper.js:177
    child.send('shutdown');
          ^

TypeError: Cannot read property 'send' of null
    at process.killkid (C:\Rocket.Chat\node_modules\node-windows\lib\wrapper.js:177:11)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process.exit (internal/process.js:146:15)
    at monitor (C:\Rocket.Chat\node_modules\node-windows\lib\wrapper.js:99:17)
    at ChildProcess.<anonymous> (C:\Rocket.Chat\node_modules\node-windows\lib\wrapper.js:170:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

Do you have anything way fix it.
Thanks.

**Comment by reetp** [comment]
@rocket-cat close

As per the documentation this is not an officially supported setup.

For setup/support issue please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/
