### ISSUE TITLE
Federated room cannot be deleted (throws an error on server)

### ISSUE THREAD

**Issue by xadhoom** [RocketChat/Rocket.Chat#15823]
### Description:

When a federated room is deleted from any server (original server or destination one) an internal server error is raised. 

### Steps to reproduce:

1. Invite a federated user to a private room
2. Try to delete the room from the admin area, from any server (origin or destination)

### Expected behavior:

Room is deleted

### Actual behavior:

Internal server error is shown and the room is not deleted.

### Server Setup Information:

- 2.2.0
- linux
- Docker

### Relevant logs:

```
server.js:204 Federation ➔ client.error beforeDeleteRoom => Could not remove room: ReferenceError: dispatchEvent is not defined
    at Promise.asyncApply (app/federation/server/hooks/beforeDeleteRoom.js:22:3)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Exception while invoking method 'eraseRoom' ReferenceError: dispatchEvent is not defined
    at Promise.asyncApply (app/federation/server/hooks/beforeDeleteRoom.js:22:3)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at callback (app/federation/server/hooks/beforeDeleteRoom.js:34:24)
    at callbacks.runItem (app/callbacks/lib/callbacks.js:110:70)
    at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)
    at app/callbacks/lib/callbacks.js:39:35
    at constants (app/callbacks/lib/callbacks.js:45:45)
    at callbacks.run (app/callbacks/lib/callbacks.js:126:9)
    at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)
    at deleteRoom (app/lib/server/functions/deleteRoom.js:8:12)
    at MethodInvocation.eraseRoom (server/methods/eraseRoom.js:41:18)
    at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:67:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

**Comment by 1rV1N-git** [comment]
Need add 
import { dispatchEvents } from '../handler';
in this line 
https://github.com/RocketChat/Rocket.Chat/blob/9c21ff405ce6c4c6ee7e9f2b90807f2e103f3941/app/federation/server/hooks/beforeDeleteRoom.js#L5
