### ISSUE TITLE
ldap function matchParens parse error

### ISSUE THREAD

**Issue by elurex** [RocketChat/Rocket.Chat#16131]
> server.js:207 LDAP ➔ Connection.info LDAP connected
server.js:207 LDAP ➔ Bind.info Binding UserDN cn=administrator,cn=users,dc=ad,dc=example,dc=com
{"name":"ldapjs","component":"client","hostname":"rchat1","pid":1796,"clazz":"Client","ldap_id":"2__ldaps://dc01.ad.example.com:636","level":20,"msg":"connected after 1 attempt(s)","time":"2020-01-05T05:26:29.2
40Z","v":0}
server.js:207 LDAP ➔ Search.info Searching user username@example.com.tw
server.js:207 LDAP ➔ Search.debug searchOptions { filter: '(&(mail=*)(|(uid=username@example.com.tw)(mail=username@example.com.tw)))',
  scope: 'sub',
  sizeLimit: 1000,
  paged: { pageSize: 250, pagePause: false } }
server.js:207 LDAP ➔ Search.debug BaseDN dc=ad,dc=example,dc=com
server.js:207 LDAP ➔ Search.info Search result count 1
server.js:207 LDAP ➔ Auth.info Authenticating CN=username,CN=Users,DC=ad,DC=example,DC=com
server.js:207 LDAP ➔ Search.info Search result count 1
server.js:207 LDAP ➔ Auth.info Authenticated CN=username,CN=Users,DC=ad,DC=example,DC=com
server.js:207 LDAPHandler ➔ info Querying user
server.js:207 LDAPHandler ➔ debug userQuery { 'services.ldap.id': '63687269732e687369616e672e66696c74726166696e652e636f6d2e7477' }
server.js:207 LDAPHandler ➔ info Logging user
server.js:207 LDAPSync ➔ info Syncing user data
server.js:207 LDAPSync ➔ info username@example.com.tw
server.js:207 LDAPSync ➔ debug user { email: 'username@example.com.tw',
  _id: 'G6gEF7swgZgBNpWD2' }
server.js:207 LDAPSync ➔ debug ldapUser undefined
server.js:207 LDAPSync ➔ debug User role exists for mapping Domain Admins -> admin
Exception while invoking method 'login' Error:   has unbalanced parentheses!
    at matchParens (/opt/Rocket.Chat/programs/server/npm/node_modules/ldap-filter/lib/index.js:50:11)
    at _buildFilterTree (/opt/Rocket.Chat/programs/server/npm/node_modules/ldap-filter/lib/index.js:157:18)
    at _parseString (/opt/Rocket.Chat/programs/server/npm/node_modules/ldap-filter/lib/index.js:412:17)
    at Object.parse (/opt/Rocket.Chat/programs/server/npm/node_modules/ldap-filter/lib/index.js:423:12)
    at Object.parseString (/opt/Rocket.Chat/programs/server/npm/node_modules/ldapjs/lib/filters/index.js:176:25)
    at Client.search (/opt/Rocket.Chat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:769:30)
    at LDAP.searchAllAsync (app/ldap/server/ldap.js:456:15)
    at LDAP._searchAllSync (packages/meteor.js:306:21)
    at LDAP.searchAllSync (app/ldap/server/ldap.js:64:15)
    at isUserInLDAPGroup (app/ldap/server/sync.js:34:22)
server.js:207 LDAP ➔ Search.info Idle
server.js:207 LDAP ➔ Connection.info Disconecting
server.js:207 LDAP ➔ Search.info Closed

### Steps to reproduce:

1. Initial LDAP SYNC is successful all users and groups are able to import into RocketChat
2. However when user trying to login, /programs/server/npm/node_modules/ldap-filter/lib/index.js  function matchParens(str, openParenIndex) failed to check parenthesis correctly.
3. **str** is passed as (mail=*)(|(uid=username@example.com.tw)(mail=username@example.com.tw))

### Expected behavior:

**str** should pass to function matchParens() (&(mail=*)(|(uid=username@example.com.tw)(mail=username@example.com.tw)))

### Actual behavior:
**str** is passed as (mail=\*)(|(uid=username@example.com.tw)(mail=username@example.com.tw)) first level & operator and ( ) is removed by _buildFilterTree(), the function receive the value as (&(mail=*)(|(uid=username@example.com.tw)(mail=username@example.com.tw))) originally

 

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: ubuntu 18.044
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset rs01: 
- NodeJS Version: 8.17
- NPM Version: 6.13.4
- MongoDB Version: 4.2.2

#### Administration -> LDAP -> Sync/Import
- Username Field: uid
- Unique Identifier Field: uid,entryUUID
- Default Domain: example.com.tw
- Merge Existing Users: yes
- Sync User Data: yes
- User Data Field Map: {"displayName": "name","mail": "email","department": "customFields.department","description":"customFields.cname"}
- Sync LDAP Groups: yes
 - Auto Remove User Roles: yes
- User Group Filter: (&(objectClass=user)(cn=#{username})(memberof=CN=#{groupName},CN=Users,DC=ad,DC=example,DC=com))
- LDAP Group BaseDN: dc=ad,dc=example,dc=com
- User Data Group Map: { "Domain Admins": "admin"}
- Auto Sync LDAP Groups to Channels: yes
- Channel Admin: rocket.chat
- LDAP Group Channel Map: { "Domain Admins": [ "itadmin", "general" ] }
- Auto Remove Users from Channels : no
- Sync User Avatar: yes
- Background Sync: yes
- Background Sync Interval: 24 hours
- Background Sync Import New Users
- Background Sync Update Existing Users

#### Administration -> LDAP -> User Search
- Filter: (&(objectClass=posixAccount)(mail=*))
- Search Field: uid,mail

### Client Setup Information

- Desktop App: 2.17.2 
- Browser Version: Firefox 71  & Chrome 79
- Operating System: Windows 10 (1909)

**Comment by elurex** [comment]
problem solved, the error comes from LDAP_Sync_User_Data_Groups_Filter in the setting contains TAB characters...
