### ISSUE TITLE
Rocketchat  Error: `gyp` failed with exit code: 1

### ISSUE THREAD

**Issue by LutfiArdiansyah** [RocketChat/Rocket.Chat#16155]
### Steps to reproduce:

1. curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
2. tar -xzf /tmp/rocket.chat.tgz -C /tmp
3. cd /tmp/bundle/programs/server && npm install
4. yum groupinstall 'Development Tools'

### Expected behavior:
No Error

### Actual behavior:

`linux-x64-57-glibc` exists; testing
Problem with the binary; manual build incoming
Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 47, in <module>
    import gyp
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 11, in <module>
    import argparse
ImportError: No module named argparse
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-642.6.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /tmp/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! fibers@3.1.1 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@3.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-08T10_58_34_317Z-debug.log

### Server Setup Information:

- Version of Rocket.Chat Server: latest
- Operating System: CentOS 6.8
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.4
- MongoDB Version: 4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

1729 verbose stack Error: fibers@3.1.1 install: `node build.js || nodejs build.js`
1729 verbose stack spawn ENOENT
1729 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
1729 verbose stack     at emitTwo (events.js:126:13)
1729 verbose stack     at ChildProcess.emit (events.js:214:7)
1729 verbose stack     at maybeClose (internal/child_process.js:925:16)
1729 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1730 verbose pkgid fibers@3.1.1
1731 verbose cwd /tmp/bundle/programs/server
1732 verbose Linux 2.6.32-642.6.1.el6.x86_64
1733 verbose argv "/usr/local/bin/node" "/usr/bin/npm" "install" "node-gyp"
1734 verbose node v8.11.4
1735 verbose npm  v6.13.4
1736 error code ELIFECYCLE
1737 error syscall spawn
1738 error file sh
1739 error errno ENOENT
1740 error fibers@3.1.1 install: `node build.js || nodejs build.js`
1740 error spawn ENOENT
1741 error Failed at the fibers@3.1.1 install script.
1741 error This is probably not a problem with npm. There is likely additional logging output above.
1742 verbose exit [ 1, true ]

**Comment by LutfiArdiansyah** [comment]
Closed!

yum install -y python-setuptools
easy_install argparse
