### ISSUE TITLE
Mac OSX -- EMFILE, too many open files, when trying to run

### ISSUE THREAD

**Issue by jonpincus** [RocketChat/Rocket.Chat#1616]
After cloning the repo, I ran meteor ... and got the following error:

```
/Users/jdp/.meteor/packages/meteor-tool/.1.1.10.46oedn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:168
    }).run();
       ^
Error: EMFILE, too many open files '/Users/jdp/.meteor/packages/meteor-tool/.1.1.10.46oedn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/logging/program.json'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.wrapper [as readFile] (/tools/fs/files.js:1338:35)
    at Function.readFromDisk (/Users/jdp/.meteor/packages/meteor-tool/.1.1.10.46oedn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/bundler.js:1554:33)
    at Object.readJsImage (/Users/jdp/.meteor/packages/meteor-tool/.1.1.10.46oedn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/bundler.js:2365:18)
    at loadIsopacketFromDisk (/Users/jdp/.meteor/packages/meteor-tool/.1.1.10.46oedn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tool-env/isopackets.js:247:23)
    at /Users/jdp/.meteor/packages/meteor-tool/.1.1.10.46oedn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tool-env/isopackets.js:85:23
    at Object.exports.noYieldsAllowed (/Users/jdp/.meteor/packages/meteor-tool/.1.1.10.46oedn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:73:14)
    at Object.load (/Users/jdp/.meteor/packages/meteor-tool/.1.1.10.46oedn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tool-env/isopackets.js:77:23)
    at getLoggingPackage (/Users/jdp/.meteor/packages/meteor-tool/.1.1.10.46oedn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/runners/run-log.js:20:24)
    at [object Object]._.extend.logAppOutput (/Users/jdp/.meteor/packages/meteor-tool/.1.1.10.46oedn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/runners/run-log.js:86:15)
    at Transformer.<anonymous> (/tools/runners/run-app.js:97:16)
    at /Users/jdp/.meteor/packages/meteor-tool/.1.1.10.46oedn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:167:12
```

I've got the latest version of meteor (1.2.1)

**Comment by Sing-Li** [comment]
@jonpicus:  Are you planning to modifying Rocket.Chat source code? Or just want to run a chat server?

**Comment by jonpincus** [comment]
Thanks, but I'm interested in modifying the code.

**Comment by Sing-Li** [comment]
NP. Problem cannot be reproduced, Both on a fresh meteor install, fresh clone; and upgraded meteor, and incremental pull. On MacOSX. 

Let see if any other community member encounters this.  Meanwhile, pls check your sys config and perhaps try a clean install of meteor.

**Comment by engelgabriel** [comment]
See 

https://github.com/Slava/tern-meteor-sublime/issues/17
https://github.com/gruntjs/grunt-contrib-copy/issues/21

> You can google the internet to find way to increase the open files limit on your OS

Like

https://medium.com/@dotfrank/solving-the-pesky-emfile-too-many-opened-files-in-ionic-angularjs-46b15dbc35eb

This happens when your project is way too big and Node tries to open all these files to analyze.

On your OS, you can bump the limit of max open files from 256 to something higher: http://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files

**Comment by jonpincus** [comment]
Indeed, resetting the open file limit worked (it was at 1000 before).  Thanks!
