### ISSUE TITLE
[Regression] Normal users can't use /webex, /math, and slash commands

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#16187]
### Description:

After updating to 2.4.0 normal users see "Error" when using slash commands like /webex, /math, etc.

### Steps to reproduce:

1. Upgrade to 2.4.0
2. Install Math or WebEx from the app marketplace
3. Type `/math 2+2` or `/webex` as a normal (non-admin) user

### Expected behavior:

Return results from the slash command as normal. 

### Actual behavior:
![image](https://user-images.githubusercontent.com/6295044/72103659-a254d180-32f7-11ea-9c16-9038a22df62b.png)

Server logs show:

```

I20200109-10:14:40.384(-5) server.js:204 System ➔ error Error sending message: Error: You are not authorized to change message properties
at validateUserIdentity (app/lib/server/functions/sendMessage.js:164:9)
at sendMessage (app/lib/server/functions/sendMessage.js:174:2)
at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:86:11)
at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:67:34)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1689:15)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
at resolve (packages/ddp-server/livedata_server.js:1687:36)
at new Promise (<anonymous>)
at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
at Server.call (packages/ddp-server/livedata_server.js:1607:17)
at DDPCommon.MethodInvocation.Meteor.runAsUser (app/api/server/v1/chat.js:175:59)
at packages/dispatch_run-as-user.js:211:14
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
at Object.post (app/api/server/v1/chat.js:175:23)
at DDP._CurrentInvocation.withValue (app/api/server/api.js:343:82)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)
at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
at packages/nimble_restivus/lib/route.coffee:59:33
at packages/simple_json-routes.js:98:9 
```

Apps engine logs:
```
[
  "{\"stack\":\"TypeError: Cannot read property '_id' of undefined
    at Promise.asyncApply (app/apps/server/bridges/messages.js:22:14)
    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\",\"message\":\"Cannot read property '_id' of undefined\"}"
]
```

![image](https://user-images.githubusercontent.com/6295044/72103582-76395080-32f7-11ea-9c84-b202c333c261.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0 (097c7c04f7a07f8498d5482b7730ca81a14bd7bd)

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

Probably related to https://github.com/RocketChat/Rocket.Chat/commit/f7f6bd0d4a590a33baa286aaaa5008c5c957e61a

**Comment by wreiske** [comment]
Related: https://github.com/wreiske/Rocket.Chat.App-Math/issues/2

**Comment by d-gubert** [comment]
We've identified the cause and are working on a fix 👍
