### ISSUE TITLE
Send file or image don't trigger the weebhook

### ISSUE THREAD

**Issue by Elintondm** [RocketChat/Rocket.Chat#16190]
### Description:
Send file or image don't trigger the weebhook on version 2.2.1. But with version 0.69 it works fine.

### Steps to reproduce:

1. Open a livechat with someone
2. Send an image file

### Expected behavior:

The rocketchat should trigger the webhook if enabled.

### Actual behavior:

The webhook is not called in this kind of message

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.1
- Operating System: Debian
- Deployment Method: docker
- Number of Running Instances: 1 

### Docker log:

`rocketchat-new        | Exception in defer callback: TypeError: Cannot read property '_id' of undefined
rocketchat-new        |     at normalizeMessageFileUpload (app/utils/server/functions/normalizeMessageFileUpload.js:7:86)
rocketchat-new        |     at messages.forEach.message (app/livechat/server/hooks/sendToCRM.js:64:27)
rocketchat-new        |     at Array.forEach (<anonymous>)
rocketchat-new        |     at sendToCRM (app/livechat/server/hooks/sendToCRM.js:39:12)
rocketchat-new        |     at app/livechat/server/hooks/sendToCRM.js:115:2
rocketchat-new        |     at callbacks.runItem (app/callbacks/lib/callbacks.js:110:70)
rocketchat-new        |     at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)
rocketchat-new        |     at app/callbacks/lib/callbacks.js:39:35
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:45)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at constants (app/callbacks/lib/callbacks.js:45:47)
rocketchat-new        |     at callbacks.run (app/callbacks/lib/callbacks.js:126:9)
rocketchat-new        |     at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)
rocketchat-new        |     at Meteor.defer (app/lib/server/functions/sendMessage.js:224:32)
rocketchat-new        |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
rocketchat-new        |     at packages/meteor.js:550:25
rocketchat-new        |     at runWithEnvironment (packages/meteor.js:1286:24)
`

**Comment by Elintondm** [comment]
This bug was fixed with https://github.com/RocketChat/Rocket.Chat/pull/15699
