### ISSUE TITLE
Exception in callback of async function: TypeError: Cannot read property 'prid' of undefined

### ISSUE THREAD

**Issue by Sys-Admin889** [RocketChat/Rocket.Chat#16290]
Hello everyone,

This error appears after upgrading server version from 2.3.1 to 2.4.2.
What does that mean and how can it solved?

Best Regards

**Comment by irfanjunaid** [comment]
+1 I am seeing the same here as well. Logs are flooding... Occasionally seeing SMTP timeouts.

```
I20200121-16:10:53.631(5.5) Exception in callback of async function: TypeError: Cannot read property 'prid' of undefined
     at getRoom (server/routes/avatar/room.js:17:11)
     at server/routes/avatar/room.js:25:15
     at runWithEnvironment (packages/meteor.js:1286:24)
     at packages/meteor.js:1299:14
     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
     
I20200121-16:13:25.664(5.5) Exception in callback of async function: TypeError: Cannot read property 'prid' of undefined
     at getRoom (server/routes/avatar/room.js:17:11)
     at server/routes/avatar/room.js:25:15
     at runWithEnvironment (packages/meteor.js:1286:24)
     at packages/meteor.js:1299:14
     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 
```

**My Setup**

```
I20200121-02:00:56.757(5.5) ➔ +--------------------------------------------------+ 
I20200121-02:00:56.758(5.5) ➔ |                  SERVER RUNNING                  | 
I20200121-02:00:56.758(5.5) ➔ +--------------------------------------------------+ 
I20200121-02:00:56.758(5.5) ➔ |                                                  | 
I20200121-02:00:56.759(5.5) ➔ |  Rocket.Chat Version: 2.4.2                      | 
I20200121-02:00:56.759(5.5) ➔ |       NodeJS Version: 8.11.4 - x64               | 
I20200121-02:00:56.759(5.5) ➔ |      MongoDB Version: 4.0.14                     | 
I20200121-02:00:56.759(5.5) ➔ |       MongoDB Engine: mmapv1                     | 
I20200121-02:00:56.760(5.5) ➔ |             Platform: linux                      | 
I20200121-02:00:56.760(5.5) ➔ |         Process Port: 3000                       | 
I20200121-02:00:56.760(5.5) ➔ |             Site URL: https://mywebsite.com  | 
I20200121-02:00:56.761(5.5) ➔ |     ReplicaSet OpLog: Enabled                    | 
I20200121-02:00:56.761(5.5) ➔ |          Commit Hash: d57a64dee6                 | 
I20200121-02:00:56.761(5.5) ➔ |        Commit Branch: HEAD                       | 
I20200121-02:00:56.761(5.5) ➔ |                                                  | 
I20200121-02:00:56.762(5.5) ➔ +--------------------------------------------------+ 
```

**Comment by Sys-Admin889** [comment]
Not solved untill now, any body can help?

**Comment by irfanjunaid** [comment]
Thanks!

**Comment by bealbrown** [comment]
Saw this as well: 

1:26 PM
Exception in callback of async function:

TypeError: Cannot read property 'prid' of undefined
