### ISSUE TITLE
Cannot start new installed RC on local machine (without Docker)

### ISSUE THREAD

**Issue by volodymyroliinyk** [RocketChat/Rocket.Chat#16341]
Hi
How I can debug RC code for understanding and solving problem with starting of new installed RC server on local machine?
- RC is last version(native RC without Docker)
- database installed and view-able by desktop MongoDB editor App 
Thanks

Terminal command result:
```
#:/var/www/html/rocketchat231.loc$ systemctl daemon-reload
#:/var/www/html/rocketchat231.loc$ systemctl status rocketchat.service
● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-01-27 19:07:05 EET; 14s ago
 Main PID: 13715 (code=exited, status=1/FAILURE)

Jan 27 19:07:05 rocketchat[13715]:     at Server.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:358:9)
Jan 27 19:07:05 rocketchat[13715]:     at Object.onceWrapper (events.js:315:30)
Jan 27 19:07:05 rocketchat[13715]:     at emitOne (events.js:116:13)
Jan 27 19:07:05 rocketchat[13715]:     at Server.emit (events.js:211:7)
Jan 27 19:07:05 rocketchat[13715]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:508:16
Jan 27 19:07:05 rocketchat[13715]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
Jan 27 19:07:05 rocketchat[13715]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
Jan 27 19:07:05 rocketchat[13715]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Jan 27 19:07:05 systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Jan 27 19:07:05 systemd[1]: rocketchat.service: Failed with result 'exit-code'.

```

**Comment by MartinSchoeler** [comment]
Hey, looks like you are looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
