### ISSUE TITLE
LDAP import of users fails "Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by stevenmcastano** [RocketChat/Rocket.Chat#16549]
I having a working server with about 450 users... but one or two new users will not import from LDAP and why I try to import while watching the logs I get the following error:

```
rocketchat[30634]: Exception in callback of async function: TypeError: Cannot read property 'replace' of undefined
rocketchat[30634]:     at module.exports (/opt/Rocket.Chat/programs/server/npm/node_modules/limax/lib/limax.js:18:15)
rocketchat[30634]:     at slug (app/ldap/server/sync.js:23:9)
rocketchat[30634]:     at ldapUsers.forEach.ldapUser (app/ldap/server/sync.js:307:16)
rocketchat[30634]:     at Array.forEach (<anonymous>)
rocketchat[30634]:     at ldap.searchUsersSync.Meteor.bindEnvironment (app/ldap/server/sync.js:294:13)
rocketchat[30634]:     at runWithEnvironment (packages/meteor.js:1356:24)
```

The server is running on Ubuntu and has the following versions:
```
rocketchat[30634]: +------------------------------------------------------------+
rocketchat[30634]: |                       SERVER RUNNING                       |
rocketchat[30634]: +------------------------------------------------------------+
rocketchat[30634]: |                                                            |
rocketchat[30634]: |  Rocket.Chat Version: 1.1.2                                |
rocketchat[30634]: |       NodeJS Version: 8.11.3 - x64                         |
rocketchat[30634]: |      MongoDB Version: 3.4.21                               |
rocketchat[30634]: |       MongoDB Engine: mmapv1                               |
rocketchat[30634]: |             Platform: linux                                |
rocketchat[30634]: |         Process Port: 3000                                 |
rocketchat[30634]: |             Site URL: https://rocketchat.xxxxxxxxxxxx.com  |
rocketchat[30634]: |     ReplicaSet OpLog: Enabled                              |
rocketchat[30634]: |          Commit Hash: aece97e1a0                           |
rocketchat[30634]: |        Commit Branch: HEAD                                 |
rocketchat[30634]: |                                                            |
rocketchat[30634]: +------------------------------------------------------------+
```

This is syncing against a Windows 2008 R2 Active Directory server. Any ideas on what can be done to troubleshoot more and find out why my LDAP sync is failing all the time now?

**Comment by mohamedhagag** [comment]
does these users have a dot in their emails like john.doe@domain.tld ?

**Comment by stevenmcastano** [comment]
These users all have dots in their name... both our usernames and email addresses are firstname.lastname.

Does that make a difference? Is there a workaround for this?

**Comment by mohamedhagag** [comment]
Sorry, I didn't update my reply.
My problem is that the mail field in our LDAP schema for some users is a list of strings containing aliases + main email.

I solved this by using another field which contain BaseMailAddress only as string.

BTW I'm using zimbra LDAP for authentication, if this may help anyone.
