### ISSUE TITLE
Not able to receive notifications on Andoird

### ISSUE THREAD

**Issue by Rafiqgithub** [RocketChat/Rocket.Chat#16588]
We are trying to enable custom push notification with fcm.
However we replcaed server key and project number.
Restarted server and still not able to get push notification on android devices.
We have also tested test push notification from admin. we received toast on the browser but on mobile side getting below mentioned error.

 ` java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/Notification$MessagingStyle;
        at com.xxx.chat.CustomPushNotification.notificationStyle(CustomPushNotification.java:189)
        at com.xxx.chat.CustomPushNotification.getNotificationBuilder(CustomPushNotification.java:108)
        at com.wix.reactnativenotifications.core.notification.PushNotification.buildNotification(PushNotification.java:143)
        at com.wix.reactnativenotifications.core.notification.PushNotification.postNotification(PushNotification.java:90)
        at com.xxx.chat.CustomPushNotification.onReceived(CustomPushNotification.java:78)
        at com.wix.reactnativenotifications.gcm.FcmInstanceIdListenerService.onMessageReceived(FcmInstanceIdListenerService.java:29)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source)
        at com.google.firebase.iid.zzb.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.Notification$MessagingStyle" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.xxx.chat-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.chat-1/lib/x86, /data/app/com.xxx.chat-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.xxx.chat.CustomPushNotification.notificationStyle(CustomPushNotification.java:189) 
        at com.xxx.chat.CustomPushNotification.getNotificationBuilder(CustomPushNotification.java:108) 
        at com.wix.reactnativenotifications.core.notification.PushNotification.buildNotification(PushNotification.java:143) 
        at com.wix.reactnativenotifications.core.notification.PushNotification.postNotification(PushNotification.java:90) 
        at com.xxx.chat.CustomPushNotification.onReceived(CustomPushNotification.java:78) 
        at com.wix.reactnativenotifications.gcm.FcmInstanceIdListenerService.onMessageReceived(FcmInstanceIdListenerService.java:29) 
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source) 
        at com.google.firebase.iid.zzb.run(Unknown Source) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source) 
        at java.lang.Thread.run(Thread.java:818) 
        Suppressed: java.lang.ClassNotFoundException: android.app.Notification$MessagingStyle
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                ... 13 more`

Can you please help us on this.

**Comment by Rafiqgithub** [comment]
Sorry wrong window.
