### ISSUE TITLE
Webhook issue. SSL error since 3.0.0. 

### ISSUE THREAD

**Issue by aimador** [RocketChat/Rocket.Chat#16649]
### Description:

After the update to RC 3.0.0 the Giphy integration does not work anymore.  Since the logs show an ssl error i was wondering if it might be a bigger problem underneath.
TLS 1.0 and 1.1 were disabled in v. 3.0.0. The cert on the Giphy side is supposed to use TLS 1.2 so in theory it should work.

### Steps to reproduce:

1. Create a custom webhook with the GifRocket script
2. trigger the script with a key word
3. nothing happens on the user side
4. check the logs to see the errors

### Expected behavior:

No errors, working integrations.

### Actual behavior:

Nothing happens on the user side. errors are generated in the logs

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.0
- Operating System: CentOS 7
- Deployment Method: tar / normal install
- Number of Running Instances:  1
- DB Replicaset Oplog: on, but not used
- NodeJS Version: 12.16.0
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: 2.17.2, 2.17.7, Firefox 73, Chrome 80
- Operating System: Win10 Pro x64

### Additional context

Since we upgraded to 3.0.0 we also had issues using Keycloak for OAuth, when the login url was accessed via https. I don't know if it's related though.

### Relevant logs:

Server Logs:
` I20200218-10:59:05.203(1) Integrations ➔ Outgoing WebHook.debug Script method "prepare_outgoing_request" result of the Integration "GifRocket Private" is: 
I20200218-10:59:05.204(1) Integrations ➔ Outgoing WebHook.debug {   url: 'https://api.giphy.com/v1/gifs/search?api_key=x=+cat',   headers: {     'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36'   },   method: 'GET' } 
I20200218-10:59:05.211(1) Integrations ➔ Outgoing WebHook.warn Result for the Integration GifRocket Private to https://api.giphy.com/v1/ is empty 
I20200218-10:59:05.220(1) server.js:204 Integrations ➔ Outgoing WebHook.error Error running Script in the Integration GifRocket Private: 
I20200218-10:59:05.220(1) Integrations ➔ Outgoing WebHook.debug   var config={color:"#225159"};var Script=function(){function Script(){}var _proto=Script.prototype;_proto.prepare_outgoing_request=function prepare_outgoing_request(_ref){var request=_ref.request;var trigger=request.data.trigger_word.toLowerCase();var phrase=request.data.text.toLowerCase().replace(trigger,"").replace(/ /g,"+");var u="";if(trigger.indexOf("gif")!==-1){if(phrase.indexOf("random")!==-1){u=request.url+"gifs/random?api_key=x=1"}else{u=request.url+"gifs/search?api_key=x&q="+phrase}}else{if(phrase.indexOf("random")!==-1){u=request.url+"stickers/random?api_key=xC&limit=1"}else{u=request.url+"stickers/search?api_key=x&q="+phrase}}return{url:u,headers:request.headers,method:"GET"}};_proto.process_outgoing_response=function process_outgoing_response(_ref2){var request=_ref2.request,response=_ref2.response;var gif="";if(response.content.data.length!==0){if(Array.isArray(response.content.data)){var count=response.content.data.length-1;var i=Math.floor(Math.random()*count);gif=response.content.data[i].images.original.url}else{gif=response.content.data.image_original_url}return{content:{attachments:[{title:"Gify",image_url:gif,color:config["color"]!=""?"#"+config["color"].replace("#",""):"#225159"}]}}}else{return{content:{text:"nice try, but I haven't found anything :cold_sweat:"}}}};return Script}(); 
I20200218-10:59:05.221(1) server.js:204 Integrations ➔ Outgoing WebHook.error Stack: 
I20200218-10:59:05.221(1) server.js:204 Integrations ➔ Outgoing WebHook.error   Error: TypeError: Cannot read property 'data' of undefined       at evalmachine.<anonymous>:11:33       at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 
I20200218-10:59:05.223(1) server.js:204 Integrations ➔ Outgoing WebHook.error Error for the Integration "GifRocket Private" to https://api.giphy.com/v1/ is: 
I20200218-10:59:05.224(1) server.js:204 Integrations ➔ Outgoing WebHook.error Error: error:140E6118:SSL routines:ssl_cipher_process_rulestr:invalid command     at Object.createSecureContext (_tls_common.js:217:13)     at Object.connect (_tls_wrap.js:1559:48)     at Agent.createConnection (https.js:130:22)     at Agent.createSocket (_http_agent.js:265:26)     at Agent.addRequest (_http_agent.js:224:10)     at new ClientRequest (_http_client.js:296:16)     at Object.request (https.js:314:10)     at Object.request (/opt/Rocket.Chat/programs/server/npm/node_modules/agent-base/patch-core.js:23:20)     at Request.start (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:751:32)     at Request.end (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1511:10)     at end (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:564:14)     at Immediate.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:578:7)     at processImmediate (internal/timers.js:456:21)     at process.topLevelDomainCallback (domain.js:137:15) {   opensslErrorStack: [     'error:140E6118:SSL routines:ssl_cipher_process_rulestr:invalid command'   ],   library: 'SSL routines',   function: 'ssl_cipher_process_rulestr',   reason: 'invalid command',   code: 'ERR_SSL_INVALID_COMMAND' } 
I20200218-10:59:05.226(1) Integrations ➔ Outgoing WebHook.info Trying the Integration GifRocket Private to https://api.giphy.com/v1/ again in 10000 milliseconds. 
I20200218-10:59:15.227(1) Integrations ➔ Outgoing WebHook.debug Starting to execute trigger: GifRocket Private (jFfmTrX6TE4vi6Gvs) 
I20200218-10:59:15.232(1) Integrations ➔ Outgoing WebHook.info Will be executing the Integration "GifRocket Private" to the url: https://api.giphy.com/v1/ 
I20200218-10:59:15.233(1) Integrations ➔ Outgoing WebHook.debug {   token: 'x',   bot: false,   trigger_word: '!gif',   channel_id: 'x',   channel_name: 'testtesttest',   message_id: 'x',   timestamp: 2020-02-18T09:59:03.908Z,   user_id: 'x',   user_name: 'x',   text: '!gif cat',   siteUrl: 'https://my-server' } 
I20200218-10:59:15.238(1) Integrations ➔ Outgoing WebHook.debug Script method "prepare_outgoing_request" result of the Integration "GifRocket Private" is: 
I20200218-10:59:15.239(1) Integrations ➔ Outgoing WebHook.debug {   url: 'https://api.giphy.com/v1/gifs/search?api_key=x=+cat',   headers: {     'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36'   },   method: 'GET' } 
I20200218-10:59:15.246(1) Integrations ➔ Outgoing WebHook.warn Result for the Integration GifRocket Private to https://api.giphy.com/v1/ is empty 
I20200218-10:59:15.255(1) server.js:204 Integrations ➔ Outgoing WebHook.error Error running Script in the Integration GifRocket Private: 
I20200218-10:59:15.255(1) Integrations ➔ Outgoing WebHook.debug   var config={color:"#225159"};var Script=function(){function Script(){}var _proto=Script.prototype;_proto.prepare_outgoing_request=function prepare_outgoing_request(_ref){var request=_ref.request;var trigger=request.data.trigger_word.toLowerCase();var phrase=request.data.text.toLowerCase().replace(trigger,"").replace(/ /g,"+");var u="";if(trigger.indexOf("gif")!==-1){if(phrase.indexOf("random")!==-1){u=request.url+"gifs/random?api_key=x&limit=1"}else{u=request.url+"gifs/search?api_key=x&q="+phrase}}else{if(phrase.indexOf("random")!==-1){u=request.url+"stickers/random?api_key=xC&limit=1"}else{u=request.url+"stickers/search?api_key=x&q="+phrase}}return{url:u,headers:request.headers,method:"GET"}};_proto.process_outgoing_response=function process_outgoing_response(_ref2){var request=_ref2.request,response=_ref2.response;var gif="";if(response.content.data.length!==0){if(Array.isArray(response.content.data)){var count=response.content.data.length-1;var i=Math.floor(Math.random()*count);gif=response.content.data[i].images.original.url}else{gif=response.content.data.image_original_url}return{content:{attachments:[{title:"Gify",image_url:gif,color:config["color"]!=""?"#"+config["color"].replace("#",""):"#225159"}]}}}else{return{content:{text:"nice try, but I haven't found anything :cold_sweat:"}}}};return Script}(); 
I20200218-10:59:15.256(1) server.js:204 Integrations ➔ Outgoing WebHook.error Stack: 
I20200218-10:59:15.257(1) server.js:204 Integrations ➔ Outgoing WebHook.error   Error: TypeError: Cannot read property 'data' of undefined       at evalmachine.<anonymous>:11:33       at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 
I20200218-10:59:15.257(1) server.js:204 Integrations ➔ Outgoing WebHook.error Error for the Integration "GifRocket Private" to https://api.giphy.com/v1/ is: 
I20200218-10:59:15.260(1) server.js:204 Integrations ➔ Outgoing WebHook.error Error: error:140E6118:SSL routines:ssl_cipher_process_rulestr:invalid command     at Object.createSecureContext (_tls_common.js:217:13)     at Object.connect (_tls_wrap.js:1559:48)     at Agent.createConnection (https.js:130:22)     at Agent.createSocket (_http_agent.js:265:26)     at Agent.addRequest (_http_agent.js:224:10)     at new ClientRequest (_http_client.js:296:16)     at Object.request (https.js:314:10)     at Object.request (/opt/Rocket.Chat/programs/server/npm/node_modules/agent-base/patch-core.js:23:20)     at Request.start (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:751:32)     at Request.end (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1511:10)     at end (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:564:14)     at Immediate.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:578:7)     at processImmediate (internal/timers.js:456:21)     at process.topLevelDomainCallback (domain.js:137:15) {   opensslErrorStack: [     'error:140E6118:SSL routines:ssl_cipher_process_rulestr:invalid command'   ],   library: 'SSL routines',   function: 'ssl_cipher_process_rulestr',   reason: 'invalid command',   code: 'ERR_SSL_INVALID_COMMAND' }`

**Comment by aimador** [comment]
Same solution as for [16694](https://github.com/RocketChat/Rocket.Chat/issues/16694). Don't use "node --tls-cipher-list" in the systemd service file to start RocketChat unless absolutely necessary.
