### ISSUE TITLE
v3.0.1 App crash on Error sending message (canSendMessage.js)

### ISSUE THREAD

**Issue by port22** [RocketChat/Rocket.Chat#16679]
### Description:

Since v 3.0.1, following errors occur on a regular basis (in terms of minutes):

```
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |                    SERVER RUNNING                   |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ +-----------------------------------------------------+
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |                                                     |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |  Rocket.Chat Version: 3.0.1                         |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |       NodeJS Version: 12.14.0 - x64                 |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |      MongoDB Version: 3.6.17                        |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |       MongoDB Engine: wiredTiger                    |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |             Platform: linux                         |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |         Process Port: 3000                          |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |             Site URL: https://chat.$$censored$$  |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |     ReplicaSet OpLog: Enabled                       |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |          Commit Hash: ef6932cd92                    |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |        Commit Branch: HEAD                          |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ |                                                     |
rocketchat_app.1.lty2hdvbkx49@swarm5    | ➔ +-----------------------------------------------------+
rocketchat_app.1.lty2hdvbkx49@swarm5    | server.js:204 System ➔ error Error sending message: Error: error-not-allowed
rocketchat_app.1.lty2hdvbkx49@swarm5    |     at app/authorization/server/functions/canSendMessage.js:16:9
rocketchat_app.1.lty2hdvbkx49@swarm5    |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
rocketchat_app.1.lty2hdvbkx49@swarm5    |  => awaited here:
rocketchat_app.1.lty2hdvbkx49@swarm5    |     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
rocketchat_app.1.lty2hdvbkx49@swarm5    |     at canSendMessage (app/authorization/server/functions/canSendMessage.js:38:84)
rocketchat_app.1.lty2hdvbkx49@swarm5    |     at executeSendMessage (app/lib/server/methods/sendMessage.js:71:16)
rocketchat_app.1.lty2hdvbkx49@swarm5    |     at app/apps/server/bridges/messages.js:18:23
rocketchat_app.1.lty2hdvbkx49@swarm5    |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
rocketchat_app.1.lty2hdvbkx49@swarm5    | === UnHandledPromiseRejection ===
rocketchat_app.1.lty2hdvbkx49@swarm5    | TypeError: Cannot read property '_id' of undefined
rocketchat_app.1.lty2hdvbkx49@swarm5    |     at app/apps/server/bridges/messages.js:20:22
rocketchat_app.1.lty2hdvbkx49@swarm5    |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
rocketchat_app.1.lty2hdvbkx49@swarm5    | ---------------------------------
rocketchat_app.1.lty2hdvbkx49@swarm5    | Errors like this can cause oplog processing errors.
```
RocketChat is running as a Stack in Docker Swarm (19.03.6) ([swarm yml file](https://gist.github.com/port22/5b4d194498d5aa139b0073af9969c2ad)) with 5x `mongo:3` but only 1x rocketchat_app.

Did not happen in the last 2.x version. I skipped the 3.0.0 and updated directly from latest 2.x to 3.0.1

**Comment by port22** [comment]
seems to be related to https://github.com/RocketChat/Rocket.Chat/issues/16097#issuecomment-569624761 which seemed to help
