### ISSUE TITLE
Default User Preferences for "MessageBox View Mode" could not be saved

### ISSUE THREAD

**Issue by sheuschkel** [RocketChat/Rocket.Chat#16802]
### Description:
Cant save default user preferences for messagebox view mode

### Steps to reproduce:
1. Installed with docker-compose as described in https://rocket.chat/docs/installation/docker-containers/
2. Setup finished with administration account
3. goto administration
4. goto accounts
5. goto default user preferences
6. change MessageBox View Mode from normal to cozy or compact
7. save settings
### Expected behavior:
saved default user preferences

### Actual behavior:
got a red notification box with the number 400

### Server Setup Information:

- Version of Rocket.Chat Server: 303
- Operating System: 
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.14.0
- MongoDB Version: 4.2.3

### Client Setup Information

- Browser: firefox 73 
- Operating System: ubuntu

### Relevant logs:
Serverlog from docker container:

Exception while invoking method 'saveSettings' errorClass [Error]: Match error: Expected string, got number
    at check (packages/check/match.js:36:17)
    at app/lib/server/methods/saveSettings.js:44:6
    at Array.forEach (<anonymous>)
    at MethodInvocation.saveSettings (app/lib/server/methods/saveSettings.js:21:10)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43 {
  message: 'Match error: Expected string, got number',
  path: '',
  sanitizedError: errorClass [Error]: Match failed [400]
      at errorClass.<anonymous> (packages/check/match.js:91:27)
      at new errorClass (packages/meteor.js:655:17)
      at check (packages/check/match.js:36:17)
      at app/lib/server/methods/saveSettings.js:44:6
      at Array.forEach (<anonymous>)
      at MethodInvocation.saveSettings (app/lib/server/methods/saveSettings.js:21:10)
      at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
      at packages/ddp-server/livedata_server.js:719:19
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
      at packages/ddp-server/livedata_server.js:717:46
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
      at packages/ddp-server/livedata_server.js:715:46
      at new Promise (<anonymous>)
      at Session.method (packages/ddp-server/livedata_server.js:689:23)
      at packages/ddp-server/livedata_server.js:559:43 {
    isClientSafe: true,
    error: 400,
    reason: 'Match failed',
    details: undefined,
    message: 'Match failed [400]',
    errorType: 'Meteor.Error'
  },
  errorType: 'Match.Error'
}
Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
    at errorClass.<anonymous> (packages/check/match.js:91:27)
    at new errorClass (packages/meteor.js:655:17)
    at check (packages/check/match.js:36:17)
    at app/lib/server/methods/saveSettings.js:44:6
    at Array.forEach (<anonymous>)
    at MethodInvocation.saveSettings (app/lib/server/methods/saveSettings.js:21:10)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43 {
  isClientSafe: true,
  error: 400,
  reason: 'Match failed',
  details: undefined,
  message: 'Match failed [400]',
  errorType: 'Meteor.Error'
}
undefined undefined

**Comment by sheuschkel** [comment]
This happens also to version 3.0.4.

If i change this setting as a normal user under "My Account -> Preferences -> Messages -> View Mode" it is stored as messageViewMode:2:Int32 in the database.

As indicated in the error message this should be a string or the check should check for a integer instead of a string.

**Comment by phlbrz** [comment]
Same issue in 3.0.10

**Comment by laurentabbal** [comment]
Same issue in 3.0.12

**Comment by lpilz** [comment]
Same in 3.1.2

**Comment by virsibl** [comment]
Same in 3.2.2

**Comment by lpilz** [comment]
There will probably be a way to set this option by directly writing to the DB. Any of you guys figured out a workaround yet?

**Comment by lpilz** [comment]
Okay, so you can circumvent the buggy UI by using:
```
curl -H "X-Auth-Token: <token>" -H "X-User-Id: <id>" -H "Content-type:application/json" https://<server>/api/v1/settings/Accounts_Default_User_Preferences_messageViewMode -d '{"value":2}'
```

**Comment by lpilz** [comment]
Still a problem in 3.4.2

**Comment by sheuschkel** [comment]
Same issue in 3.6.0

**Comment by Exordian** [comment]
the option seems to be missing since 3.5.x completly

**Comment by meomay503** [comment]
same issue in 3.9.3

**Comment by meomay503** [comment]
This caused by the setting's keys are set to type number but not string.
