### ISSUE TITLE
Errors after update to 3.0.4

### ISSUE THREAD

**Issue by martinszy** [RocketChat/Rocket.Chat#16913]
I imported the 0.74.3 database to a new server, run the old 0.74.3 docker instance with this data, which lead to the app refreshing the page every 5 seconds. Then updated to 3.0.4 and got a stable system, but now users are reporting that they are being forced to establish a new username, can't access chats and just can't use the app.

Here's part of the logs:
```

server.js:204 System ➔ error Error sending message: Error: error-not-allowed
    at app/authorization/server/functions/canSendMessage.js:16:9
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at canSendMessage (app/authorization/server/functions/canSendMessage.js:38:84)
    at executeSendMessage (app/lib/server/methods/sendMessage.js:71:16)
    at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:105:10)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/chat.js:175:59)
    at packages/dispatch_run-as-user.js:211:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
    at Object.post (app/api/server/v1/chat.js:175:23)
    at app/api/server/api.js:343:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
The endpoint "emoji-custom" is deprecated and will be removed after version v3.0.0
The endpoint "emoji-custom" is deprecated and will be removed after version 3.0.0
server.js:204 System ➔ error Error sending message: Error: error-not-allowed
    at app/authorization/server/functions/canSendMessage.js:16:9
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at canSendMessage (app/authorization/server/functions/canSendMessage.js:38:84)
    at executeSendMessage (app/lib/server/methods/sendMessage.js:71:16)
    at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:105:10)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/chat.js:175:59)
    at packages/dispatch_run-as-user.js:211:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
    at Object.post (app/api/server/v1/chat.js:175:23)
    at app/api/server/api.js:343:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
server.js:204 System ➔ error Error sending message: Error: error-not-allowed
    at app/authorization/server/functions/canSendMessage.js:16:9
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at canSendMessage (app/authorization/server/functions/canSendMessage.js:38:84)
    at executeSendMessage (app/lib/server/methods/sendMessage.js:71:16)
    at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:105:10)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/chat.js:175:59)
    at packages/dispatch_run-as-user.js:211:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
    at Object.post (app/api/server/v1/chat.js:175:23)
    at app/api/server/api.js:343:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
Exception while invoking method 'saveUserProfile' TypeError: Cannot read property 'toLowerCase' of undefined
    at checkPassword (server/methods/saveUserProfile.js:34:27)
    at MethodInvocation.saveUserProfile (server/methods/saveUserProfile.js:57:9)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
Exception while invoking method 'saveUserProfile' TypeError: Cannot read property 'toLowerCase' of undefined
    at checkPassword (server/methods/saveUserProfile.js:34:27)
    at MethodInvocation.saveUserProfile (server/methods/saveUserProfile.js:57:9)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
The endpoint "emoji-custom" is deprecated and will be removed after version v3.0.0
The endpoint "emoji-custom" is deprecated and will be removed after version 3.0.0
server.js:204 System ➔ error Error sending message: Error: error-not-allowed
    at app/authorization/server/functions/canSendMessage.js:16:9
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at canSendMessage (app/authorization/server/functions/canSendMessage.js:38:84)
    at executeSendMessage (app/lib/server/methods/sendMessage.js:71:16)
    at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:105:10)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/chat.js:175:59)
    at packages/dispatch_run-as-user.js:211:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
    at Object.post (app/api/server/v1/chat.js:175:23)
    at app/api/server/api.js:343:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
Exception while invoking method 'saveUserProfile' TypeError: Cannot read property 'toLowerCase' of undefined
    at checkPassword (server/methods/saveUserProfile.js:34:27)
    at MethodInvocation.saveUserProfile (server/methods/saveUserProfile.js:57:9)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
The endpoint "permissions" is deprecated and will be removed after version v0.69
Exception while invoking method 'sendConfirmationEmail' errorClass [Error]: Match error: Expected string, got null
    at check (packages/check/match.js:36:17)
    at MethodInvocation.sendConfirmationEmail (server/methods/sendConfirmationEmail.js:24:3)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43 {
  message: 'Match error: Expected string, got null',
  path: '',
  sanitizedError: errorClass [Error]: Match failed [400]
      at errorClass.<anonymous> (packages/check/match.js:91:27)
      at new errorClass (packages/meteor.js:655:17)
      at check (packages/check/match.js:36:17)
      at MethodInvocation.sendConfirmationEmail (server/methods/sendConfirmationEmail.js:24:3)
      at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
      at packages/ddp-server/livedata_server.js:719:19
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
      at packages/ddp-server/livedata_server.js:717:46
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
      at packages/ddp-server/livedata_server.js:715:46
      at new Promise (<anonymous>)
      at Session.method (packages/ddp-server/livedata_server.js:689:23)
      at packages/ddp-server/livedata_server.js:559:43 {
    isClientSafe: true,
    error: 400,
    reason: 'Match failed',
    details: undefined,
    message: 'Match failed [400]',
    errorType: 'Meteor.Error'
  },
  errorType: 'Match.Error'
}
Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
    at errorClass.<anonymous> (packages/check/match.js:91:27)
    at new errorClass (packages/meteor.js:655:17)
    at check (packages/check/match.js:36:17)
    at MethodInvocation.sendConfirmationEmail (server/methods/sendConfirmationEmail.js:24:3)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43 {
  isClientSafe: true,
  error: 400,
  reason: 'Match failed',
  details: undefined,
  message: 'Match failed [400]',
  errorType: 'Meteor.Error'
}
undefined undefined
Exception while invoking method 'saveUserProfile' TypeError: Cannot read property 'toLowerCase' of undefined
    at checkPassword (server/methods/saveUserProfile.js:34:27)
    at MethodInvocation.saveUserProfile (server/methods/saveUserProfile.js:57:9)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43

```

**Comment by martinszy** [comment]
It's also asking for new usernames, for everyone and people want to use their old one, which is already registered.

Oh this went south.

![Captura de pantalla de 2020-03-17 11-48-10](https://user-images.githubusercontent.com/997732/76885746-55d0c980-6845-11ea-9a26-ac3cb1b038f0.png)

**Comment by martinszy** [comment]
Don't worry, it was our cache messing things up.
