### ISSUE TITLE
Crashes on canSendMessage.js

### ISSUE THREAD

**Issue by port22** [RocketChat/Rocket.Chat#16933]
following errors occur on a regular basis (in terms of minutes):

```
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ System ➔ startup
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ +-----------------------------------------------------+
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |                    SERVER RUNNING                   |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ +-----------------------------------------------------+
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |                                                     |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |  Rocket.Chat Version: 3.0.4                         |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |       NodeJS Version: 12.14.0 - x64                 |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |      MongoDB Version: 3.6.17                        |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |       MongoDB Engine: wiredTiger                    |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |             Platform: linux                         |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |         Process Port: 3000                          |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |             Site URL: https://chat.acme.corp  |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |     ReplicaSet OpLog: Enabled                       |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |          Commit Hash: 4f845d16a5                    |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |        Commit Branch: HEAD                          |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ |                                                     |
rocketchat_app.1.wed33onw4gid@swarm2    | ➔ +-----------------------------------------------------+
rocketchat_app.1.wed33onw4gid@swarm2    | server.js:204 System ➔ error Error sending message: Error: error-not-allowed
rocketchat_app.1.wed33onw4gid@swarm2    |     at app/authorization/server/functions/canSendMessage.js:16:9
rocketchat_app.1.wed33onw4gid@swarm2    |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
rocketchat_app.1.wed33onw4gid@swarm2    |  => awaited here:
rocketchat_app.1.wed33onw4gid@swarm2    |     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
rocketchat_app.1.wed33onw4gid@swarm2    |     at canSendMessage (app/authorization/server/functions/canSendMessage.js:38:84)
rocketchat_app.1.wed33onw4gid@swarm2    |     at executeSendMessage (app/lib/server/methods/sendMessage.js:71:16)
rocketchat_app.1.wed33onw4gid@swarm2    |     at app/apps/server/bridges/messages.js:18:23
rocketchat_app.1.wed33onw4gid@swarm2    |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
rocketchat_app.1.wed33onw4gid@swarm2    | === UnHandledPromiseRejection ===
rocketchat_app.1.wed33onw4gid@swarm2    | TypeError: Cannot read property '_id' of undefined
rocketchat_app.1.wed33onw4gid@swarm2    |     at app/apps/server/bridges/messages.js:20:22
rocketchat_app.1.wed33onw4gid@swarm2    |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
rocketchat_app.1.wed33onw4gid@swarm2    | ---------------------------------
rocketchat_app.1.wed33onw4gid@swarm2    | Errors like this can cause oplog processing errors.
rocketchat_app.1.wed33onw4gid@swarm2    | Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
rocketchat_app.1.wed33onw4gid@swarm2    | Future node.js versions will automatically exit the process
rocketchat_app.1.wed33onw4gid@swarm2    | =================================
```
RocketChat is running as a Stack in Docker Swarm (19.03.6) (https://gist.github.com/port22/5b4d194498d5aa139b0073af9969c2ad) with 5x mongo:3 but only 1x rocketchat_app.

These errors seem to be caused by a sent message of a user or incoming webhook.

I tried https://github.com/RocketChat/Rocket.Chat/issues/16097#issuecomment-569624761 but the problem persists.

I need to know how I can debug every message being sent to rocketchat to identify the last sent message before the app crashes. anybody?

**Comment by port22** [comment]
ok I did a debug with tcpdump within the container. Turned out it was the Atlassian Jira plugin. Disabled and errors are gone
