### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by gamenshanev** [RocketChat/Rocket.Chat#17005]
I have an error

See here the error:
                                        return fn.apply(this, arguments);
                                                  ^

Error: Must pass options.rootUrl or set ROOT_URL in the server environment
    at Object.Meteor.absoluteUrl (packages/meteor.js:1378:11)
    at runWebAppServer (packages/webapp/webapp_server.js:771:18)
    at packages/webapp/webapp_server.js:1178:1
    at module (packages/webapp/webapp_server.js:1178:16)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /opt/Rocket.Chat/programs/server/packages/webapp.js:1610:15
    at /opt/Rocket.Chat/programs/server/packages/webapp.js:1619:3
    at /opt/Rocket.Chat/programs/server/boot.js:398:38
    at Array.forEach (<anonymous>)
    at /opt/Rocket.Chat/programs/server/boot.js:226:21
    at /opt/Rocket.Chat/programs/server/boot.js:461:7
    at Function.run (/opt/Rocket.Chat/programs/server/profile.js:280:14)
    at /opt/Rocket.Chat/programs/server/boot.js:460:13

**Comment by gabriellsh** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
