### ISSUE TITLE
LDAP user sync failing, ldapuser/ldap becomes undefined at some point

### ISSUE THREAD

**Issue by abruening-iwt** [RocketChat/Rocket.Chat#17016]
### Description:

Creating new user after first login from LDAP results in an error, login not possible.

Looks like it can't find the user after initial creation. I do see the user in the Rocket.Chat admin back-end, but the proper name is not set (empty or Unnamed, depending on where you look).

We had issues with other software in the past because the server sends back some fields with Base64 encoding, usually realted to umlauts.

### Steps to reproduce:

1. Connect Rocket.Chat server to ActiveDirectory via LDAP
2. Try logging in as user

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.5
- Operating System: Devuan ASCII
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.17

### Relevant logs:

```
I20200325-19:23:09.872(0) server.js:204 LDAPHandler ➔ info Init LDAP login  
I20200325-19:23:09.873(0) server.js:204 LDAP ➔ Connection.info Init setup 
I20200325-19:23:09.874(0) server.js:204 LDAP ➔ Connection.info Connecting ldaps://172.16.3.1:636 
I20200325-19:23:09.875(0) server.js:204 LDAP ➔ Connection.debug connectionOptions {   url: 'ldaps://172.16.3.1:636',   timeout: 60000,   connectTimeout: 1000,   idleTimeout: 3000,   reconnect: true,   log: Logger {     _events: [Object: null prototype] {},     _eventsCount: 0,     _maxListeners: undefined,     _level: 40,     streams: [ [Object] ],     serializers: null,     src: false,     fields: {       name: 'ldapjs',       component: 'client',       hostname: 'rocketchat-1',       pid: 20304     },     [Symbol(kCapture)]: false   },   tlsOptions: { rejectUnauthorized: false } } 
I20200325-19:23:10.024(0) server.js:204 LDAP ➔ Connection.info LDAP connected 
I20200325-19:23:10.027(0) server.js:204 LDAP ➔ Bind.info Binding UserDN CN=Lookup User,CN=Users,DC=myorg,DC=xy 
I20200325-19:23:10.045(0) server.js:204 LDAP ➔ Search.info Searching user myusername 
I20200325-19:23:10.049(0) server.js:204 LDAP ➔ Search.debug searchOptions {   filter: '(&(&(objectCategory=person)(objectClass=user)(mail=*)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))(sAMAccountName=myusername))',   scope: 'sub',   sizeLimit: 1000,   paged: { pageSize: 250, pagePause: false } } 
I20200325-19:23:10.054(0) server.js:204 LDAP ➔ Search.debug BaseDN DC=myorg,DC=xy 
I20200325-19:23:10.095(0) server.js:204 LDAP ➔ Search.info Search result count 1 
I20200325-19:23:10.101(0) server.js:204 LDAP ➔ Auth.info Authenticating CN=John Döe,OU=Techniker,OU=EDV,OU=Zentrale Dienste,OU=MySubOrg,DC=myorg,DC=xy 
I20200325-19:23:10.142(0) server.js:204 LDAP ➔ Search.info Search result count 1 
I20200325-19:23:10.145(0) server.js:204 LDAP ➔ Auth.info Authenticated CN=John Döe,OU=Techniker,OU=EDV,OU=Zentrale Dienste,OU=MySubOrg,DC=myorg,DC=xy 
I20200325-19:23:10.151(0) server.js:204 LDAPHandler ➔ info Querying user 
I20200325-19:23:10.153(0) server.js:204 LDAPHandler ➔ debug userQuery { 'services.ldap.id': '2afa4e91e3768442aeb0bd621c781e6e' } 
I20200325-19:23:10.160(0) server.js:204 LDAPHandler ➔ debug userQuery { username: 'myusername' } 
I20200325-19:23:10.163(0) server.js:204 LDAPHandler ➔ info User does not exist, creating myusername 
I20200325-19:23:10.165(0) server.js:204 LDAPSync ➔ debug user.name changed to: John Döe 
I20200325-19:23:10.168(0) server.js:204 LDAPSync ➔ debug New user data { username: 'myusername', email: 'myusername@myorg.de' } 
I20200325-19:23:10.176(0) server.js:204 Meteor ➔ method joinDefaultChannels -> userId: B5X78QSwWczQfYiXF, arguments: [null] 
I20200325-19:23:10.188(0) server.js:204 Integrations ➔ Outgoing WebHook.debug Execute Trigger: userCreated 
I20200325-19:23:10.191(0) server.js:204 Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: userCreated {   event: 'userCreated',   user: {     _id: 'B5X78QSwWczQfYiXF',     createdAt: 2020-03-25T19:23:10.171Z,     services: {},     username: 'myusername',     emails: [ [Object] ],     type: 'user',     status: 'offline',     active: true,     _updatedAt: 2020-03-25T19:23:10.172Z   } } 
I20200325-19:23:10.191(0) server.js:204 Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: __any 
I20200325-19:23:10.192(0) server.js:204 Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event. 
I20200325-19:23:10.201(0) server.js:204 LDAPSync ➔ info Syncing user data 
I20200325-19:23:10.201(0) server.js:204 LDAPSync ➔ debug user { email: 'myusername@myorg.de', _id: 'B5X78QSwWczQfYiXF' } 
I20200325-19:23:10.202(0) server.js:204 LDAPSync ➔ debug ldapUser undefined
I20200325-19:23:10.204(0) server.js:204 LDAPSync ➔ debug user.name changed to: John Döe 
I20200325-19:23:10.205(0) server.js:204 LDAPSync ➔ error Unexpected error : Unexpected token   in JSON at position 48 
I20200325-19:23:10.207(0) server.js:204 LDAPSync ➔ info Channel 'EDV' doesn't exist, creating it. 
I20200325-19:23:10.220(0) Exception while invoking method 'login' TypeError: Cannot read property 'searchAllSync' of undefined     at isUserInLDAPGroup (app/ldap/server/sync.js:35:22)     at app/ldap/server/sync.js:322:8     at Function._.map._.collect (/opt/Rocket.Chat/programs/server/npm/node_modules/underscore/underscore.js:205:24)     at mapLDAPGroupsToChannels (app/ldap/server/sync.js:312:4)     at syncUserData (app/ldap/server/sync.js:349:23)     at addLdapUser (app/ldap/server/sync.js:459:2)     at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:150:17)     at packages/accounts-base/accounts_server.js:460:31     at tryLoginMethod (packages/accounts-base/accounts_server.js:1289:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
I20200325-19:23:10.222(0) server.js:204 Integrations ➔ Outgoing WebHook.debug Execute Trigger: roomCreated 
I20200325-19:23:10.223(0) server.js:204 Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: roomCreated {   event: 'roomCreated',   owner: { _id: 'rocket.cat', username: 'rocket.cat' },   room: {     name: 'IT',     fname: 'IT',     t: 'c',     msgs: 0,     usersCount: 0,     u: { _id: 'rocket.cat', username: 'rocket.cat' },     customFields: { ldap: true },     ts: 2020-03-25T19:23:10.209Z,     ro: false,     _updatedAt: 2020-03-25T19:23:10.209Z,     _id: 'MFe7oetMrdAsJhxn5'   } } 
I20200325-19:23:10.223(0) server.js:204 Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: MFe7oetMrdAsJhxn5 
I20200325-19:23:10.224(0) server.js:204 Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event.  
```

**Comment by abruening-iwt** [comment]
Alright, I found the issue (after making the report, of course): I had the config option "LDAP Group BaseDN" set to the same value as "Base DN", but apparently that doesn't quite do what I thought. With the option unset, it works just fine. Even the umlauts.

**Comment by abruening-iwt** [comment]
Correction: While it does work better now, the error still occurs and group syncing does not happen.

```
I20200325-20:48:02.160(0) server.js:204 LDAPSync ➔ debug ldapUser undefined 
I20200325-20:48:02.161(0) server.js:204 LDAPSync ➔ debug user.name changed to: John Döe 
I20200325-20:48:02.163(0) server.js:204 LDAPSync ➔ error Unexpected error : Unexpected token   in JSON at position 48 
```
