### ISSUE TITLE
Incoming Webhooks cannot send direct messages as rocket.cat

### ISSUE THREAD

**Issue by Morgul** [RocketChat/Rocket.Chat#1703]
When the `rocket.cat` user is used as the user for an Incoming Webhook, it cannot post to direct messages:

```
2015-12-19T00:22:27.456484652Z Error: [methods] createDirectMessage -> Invalid target user [invalid-user]
2015-12-19T00:22:27.456552694Z     at [object Object].Meteor.methods.createDirectMessage (server/methods/createDirectMessage.coffee:14:14)
2015-12-19T00:22:27.456561755Z     at [object Object].methodsMap.(anonymous function) (packages/rocketchat_lib/server/lib/debug.js:22:1)
2015-12-19T00:22:27.456568815Z     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
2015-12-19T00:22:27.456575327Z     at livedata_server.js:1611:18
2015-12-19T00:22:27.456595127Z     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
2015-12-19T00:22:27.456601352Z     at [object Object]._.extend.apply (livedata_server.js:1610:45)
2015-12-19T00:22:27.456606740Z     at [object Object]._.extend.call (livedata_server.js:1553:17)
2015-12-19T00:22:27.456612256Z     at [object Object].<anonymous> (packages/rocketchat_integrations/server/api/api.coffee:63:14)
2015-12-19T00:22:27.456617709Z     at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1
2015-12-19T00:22:27.456622649Z     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```

If I use my user, however, this works as expected.

**Comment by engelgabriel** [comment]
Seems to be broken indeed.

**Comment by Morgul** [comment]
I can confirm this is now working with the latest code on develop.
