### ISSUE TITLE
LDAP login doesn't work for non-existant users when role-group mapping is enabled.

### ISSUE THREAD

**Issue by pcurie** [RocketChat/Rocket.Chat#17030]
### Description:

LDAP login doesn't work for non-existant users when role-group mapping is enabled.

### Steps to reproduce:

1. Configure role-group mapping
2. Login with a LDAP user that never logged into rocket.chat
3. Error

### Expected behavior:

Successful login

### Actual behavior:

"Wrong password" message for the user, in the logs :

```I20200326-15:51:59.511(1) Exception while invoking method 'login' TypeError: Cannot read property 'searchAllSync' of undefined     at isUserInLDAPGroup (app/ldap/server/sync.js:35:22)     at mapLdapGroupsToUserRoles (app/ldap/server/sync.js:253:7)     at syncUserData (app/ldap/server/sync.js:345:20)     at addLdapUser (app/ldap/server/sync.js:459:2)     at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:150:17)     at packages/accounts-base/accounts_server.js:460:31     at tryLoginMethod (packages/accounts-base/accounts_server.js:1289:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.5
- Operating System: CentOS 8
- Deployment Method: rocketchat-ctl
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

We activated SAML + LDAP auth on this RC instance, I tried theses test cases :

- login SAML existant user -> ok
- login SAML inexistant user -> ok
- login LDAP existant user -> ok
- login LDAP inexistant user -> nok

### Relevant logs:

``` I20200326-15:42:46.943(1) LDAPHandler ➔ info Init LDAP login worteks 
I20200326-15:42:46.944(1) LDAP ➔ Connection.info Init setup 
I20200326-15:42:46.947(1) LDAP ➔ Connection.info Connecting ldaps://ldap.acme.fr:636 
I20200326-15:42:46.948(1) LDAP ➔ Connection.debug connectionOptions {   url: 'ldaps://ldap.acme.fr:636',   timeout: 60000,   connectTimeout: 1000,   idleTimeout: 1000,   reconnect: true,   log: Logger {     _events: [Object: null prototype] {},     _eventsCount: 0,     _maxListeners: undefined,     _level: 20,     streams: [ [Object] ],     serializers: null,     src: false,     fields: {       name: 'ldapjs',       component: 'client',       hostname: 'rocketchat.acme.fr',       pid: 23034     }   },   tlsOptions: { rejectUnauthorized: true } } 
I20200326-15:42:47.055(1) LDAP ➔ Connection.info LDAP connected 
I20200326-15:42:47.057(1) LDAP ➔ Bind.info Binding UserDN cn=rocketchat,ou=dsa,dc=acme,dc=fr 
I20200326-15:42:47.061(1) LDAP ➔ Search.info Searching user worteks 
I20200326-15:42:47.062(1) LDAP ➔ Search.debug searchOptions {   filter: '(&(objectclass=inetOrgPerson)(uid=worteks))',   scope: 'sub',   sizeLimit: 1000,   paged: { pageSize: 500, pagePause: false } } 
I20200326-15:42:47.063(1) LDAP ➔ Search.debug BaseDN dc=acme,dc=fr 
I20200326-15:42:47.066(1) LDAP ➔ Search.info Search result count 1 
I20200326-15:42:47.067(1) LDAP ➔ Auth.info Authenticating uid=worteks,ou=users,dc=acme,dc=fr 
I20200326-15:42:47.071(1) LDAP ➔ Search.info Search result count 1 
I20200326-15:42:47.072(1) LDAP ➔ Auth.info Authenticated uid=worteks,ou=users,dc=acme,dc=fr 
I20200326-15:42:47.072(1) LDAPHandler ➔ info Querying user 
I20200326-15:42:47.074(1) LDAPHandler ➔ debug userQuery { 'services.ldap.id': '776f7274656b73' } 
I20200326-15:42:47.076(1) LDAPHandler ➔ debug userQuery { username: 'worteks' } 
I20200326-15:42:47.077(1) LDAPHandler ➔ info User does not exist, creating worteks 
I20200326-15:42:47.079(1) LDAPSync ➔ debug user.name changed to: Worteks 
I20200326-15:42:47.080(1) LDAPSync ➔ debug New user data { username: 'worteks', email: 'paucur@worteks.com' } 
I20200326-15:42:47.162(1) Meteor ➔ method joinDefaultChannels -> userId: 8hDhywjuKDuZXYo77, arguments: [null] 
I20200326-15:42:47.171(1) Integrations ➔ Outgoing WebHook.debug Execute Trigger: userCreated 
I20200326-15:42:47.172(1) Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: userCreated {   event: 'userCreated',   user: {     _id: '8hDhywjuKDuZXYo77',     createdAt: 2020-03-26T14:42:47.159Z,     services: { password: [Object] },     username: 'worteks',     emails: [ [Object] ],     type: 'user',     status: 'offline',     active: true,     _updatedAt: 2020-03-26T14:42:47.159Z   } } 
I20200326-15:42:47.190(1) Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: __any 
I20200326-15:42:47.190(1) Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event. 
I20200326-15:42:47.248(1) LDAPSync ➔ info Syncing user data 
I20200326-15:42:47.248(1) LDAPSync ➔ debug user { email: 'paucur@worteks.com', _id: '8hDhywjuKDuZXYo77' } 
I20200326-15:42:47.250(1) LDAPSync ➔ debug ldapUser undefined 
I20200326-15:42:47.251(1) LDAPSync ➔ debug user.name changed to: Worteks 
I20200326-15:42:47.252(1) LDAPSync ➔ debug User role exists for mapping AppRocketChatAdmin -> admin 
I20200326-15:42:47.253(1) Exception while invoking method 'login' TypeError: Cannot read property 'searchAllSync' of undefined     at isUserInLDAPGroup (app/ldap/server/sync.js:35:22)     at mapLdapGroupsToUserRoles (app/ldap/server/sync.js:253:7)     at syncUserData (app/ldap/server/sync.js:345:20)     at addLdapUser (app/ldap/server/sync.js:459:2)     at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:150:17)     at packages/accounts-base/accounts_server.js:460:31     at tryLoginMethod (packages/accounts-base/accounts_server.js:1289:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
I20200326-15:42:48.071(1) LDAP ➔ Search.info Idle 
I20200326-15:42:48.071(1) LDAP ➔ Connection.info Disconecti```

LDAP logs :

```5e7cbf6a conn=1024 fd=17 ACCEPT from IP=192.168.11.80:58258 (IP=0.0.0.0:636)
5e7cbf6a conn=1024 fd=17 TLS established tls_ssf=256 ssf=256
5e7cbf6a conn=1024 op=0 BIND dn="cn=rocketchat,ou=dsa,dc=acme,dc=fr" method=128
5e7cbf6a conn=1024 op=0 BIND dn="cn=rocketchat,ou=dsa,dc=acme,dc=fr" mech=SIMPLE ssf=0
5e7cbf6a conn=1024 op=0 RESULT tag=97 err=0 text=
5e7cbf6a conn=1024 op=1 SRCH base="dc=acme,dc=fr" scope=2 deref=0 filter="(&(objectClass=inetOrgPerson)(uid=worteks))"
5e7cbf6a conn=1024 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
5e7cbf6a conn=1024 op=2 BIND anonymous mech=implicit ssf=0
5e7cbf6a conn=1024 op=2 BIND dn="uid=worteks,ou=users,dc=acme,dc=fr" method=128
5e7cbf6a conn=1024 op=2 BIND dn="uid=worteks,ou=users,dc=acme,dc=fr" mech=SIMPLE ssf=0
5e7cbf6a conn=1024 op=2 RESULT tag=97 err=0 text=
5e7cbf6a conn=1024 op=3 SRCH base="uid=worteks,ou=users,dc=acme,dc=fr" scope=2 deref=0 filter="(objectClass=*)"
5e7cbf6a conn=1024 op=3 SEARCH RESULT tag=101 err=0 nentries=1 text=
5e7cbf6b conn=1024 op=4 UNBIND
5e7cbf6b conn=1024 fd=17 closed```

**Comment by pierre-lehnen-rc** [comment]
This error was fixed by #17417
