### ISSUE TITLE
Incoming Webhooks cannot sent to private group

### ISSUE THREAD

**Issue by Morgul** [RocketChat/Rocket.Chat#1704]
When attempting to send to a private group (as either `rocket.cat` or as my user, who is in the private group), I get the following error:

```
2015-12-19T00:14:59.276981201Z Error: [methods] joinRoom -> Not allowed [403]
2015-12-19T00:14:59.312369608Z     at [object Object].Meteor.methods.joinRoom (server/methods/joinRoom.coffee:10:14)
2015-12-19T00:14:59.312425040Z     at [object Object].methodsMap.(anonymous function) (packages/rocketchat_lib/server/lib/debug.js:22:1)
2015-12-19T00:14:59.312435323Z     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
2015-12-19T00:14:59.312443994Z     at livedata_server.js:1611:18
2015-12-19T00:14:59.312452412Z     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
2015-12-19T00:14:59.312461198Z     at [object Object]._.extend.apply (livedata_server.js:1610:45)
2015-12-19T00:14:59.312469384Z     at [object Object]._.extend.call (livedata_server.js:1553:17)
2015-12-19T00:14:59.312477698Z     at [object Object].<anonymous> (packages/rocketchat_integrations/server/api/api.coffee:42:13)
2015-12-19T00:14:59.312487105Z     at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1
2015-12-19T00:14:59.312495720Z     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```

Checking the slack documentation it's appears that Incoming Webhooks can't post to private groups, however, since Rocket.Chat uses a real user, I would expect that as long as the user is added to the private group, it could post. That does not appear to be the case.

**Comment by engelgabriel** [comment]
Incoming Webhooks should be able to send messages to private groups as long as the user they are authenticating as is a member of that group. Let's investigate this bug @rodrigok

**Comment by timothyparez** [comment]
Experiencing the same issue. User is part of the group can chat in it but the api endpoint just returns an internal server error response.

**Comment by Morgul** [comment]
I can confirm this is now working with the latest code on develop.

Thanks guys!
