### ISSUE TITLE
[BUG] Error: FileNotFound: no file with id [someID] found

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17096]
### Description:

I get in Rocket.Chat logs `Error: FileNotFound: no file with id [someID] found` error

### Expected behavior:

Not to have such errors

### Actual behavior:

Error in logs. And near that error additional logs

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 12
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App Version: 2.17.9
- Operating System: Windows 10

### Additional context

No any additional context

### Relevant logs:
Logs from Kibana
<details>

```

March 31st 2020, 10:57:03.706 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | at processTicksAndRejections (internal/process/task_queues.js:75:11)
-- | -- | -- | --

  | March 31st 2020, 10:57:03.705 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:1259:5

  | March 31st 2020, 10:57:03.705 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:128:55)

  | March 31st 2020, 10:57:03.705 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | at handler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:1155:22)

  | March 31st 2020, 10:57:03.705 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:397:18

  | March 31st 2020, 10:57:03.703 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:364:54

  | March 31st 2020, 10:57:03.702 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | at executeCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:395:17)

  | March 31st 2020, 10:57:03.702 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | at deleteCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:349:17)

  | March 31st 2020, 10:57:03.701 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:188:25

  | March 31st 2020, 10:57:03.701 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:410:17

  | March 31st 2020, 10:57:03.701 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | at ClientSession.endSession (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sessions.js:134:41)

  | March 31st 2020, 10:57:03.701 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | Error: FileNotFound: no file with id Wjkr2udj63CmuKFrX found

  | March 31st 2020, 10:57:03.701 | s-rc-srv-02 | rocketchat_rocketchat_3_1 | at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:398:11



March 31st 2020, 09:23:44.728	s-rc-srv-02	rocketchat_rocketchat_1_1	at processTicksAndRejections (internal/process/task_queues.js:75:11)
	March 31st 2020, 09:23:44.726	s-rc-srv-02	rocketchat_rocketchat_1_1	at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:128:55)
	March 31st 2020, 09:23:44.726	s-rc-srv-02	rocketchat_rocketchat_1_1	at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:1259:5
	March 31st 2020, 09:23:44.726	s-rc-srv-02	rocketchat_rocketchat_1_1	at handler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:1155:22)
	March 31st 2020, 09:23:44.726	s-rc-srv-02	rocketchat_rocketchat_1_1	at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:397:18
	March 31st 2020, 09:23:44.725	s-rc-srv-02	rocketchat_rocketchat_1_1	at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:410:17
	March 31st 2020, 09:23:44.725	s-rc-srv-02	rocketchat_rocketchat_1_1	at executeCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:395:17)
	March 31st 2020, 09:23:44.725	s-rc-srv-02	rocketchat_rocketchat_1_1	at deleteCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:349:17)
	March 31st 2020, 09:23:44.725	s-rc-srv-02	rocketchat_rocketchat_1_1	at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:398:11
	March 31st 2020, 09:23:44.725	s-rc-srv-02	rocketchat_rocketchat_1_1	at ClientSession.endSession (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sessions.js:134:41)
	March 31st 2020, 09:23:44.725	s-rc-srv-02	rocketchat_rocketchat_1_1	at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:364:54
	March 31st 2020, 09:23:44.722	s-rc-srv-02	rocketchat_rocketchat_1_1	Error: FileNotFound: no file with id S26uPw7fXTfbvvBAL found
	March 31st 2020, 09:23:44.722	s-rc-srv-02	rocketchat_rocketchat_1_1	at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:188:25
	March 31st 2020, 09:21:19.180	s-rc-srv-02	rocketchat_rocketchat_4_1	Tue, 31 Mar 2020 06:21:19 GMT express deprecated res.send(status): Use res.sendStatus(status) instead at app/app.js:50398:19
```

</details>

**Comment by 564064202** [comment]
Sir,please give us your dockerfile ,and we can try to analyze it

**Comment by arrow003** [comment]
Centos7.6 env, there is the same error output.
MongoDB:4.0
node:12.14.0
npm:6.13.4
RocketChat:3.0.0
```
Jun  3 09:30:34 XXXXXXXX rocketchat: Error: FileNotFound: no file with id RhEbNQTqeHvsN2QDj found
Jun  3 09:30:34 XXXXXXXX rocketchat: at /opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:188:25
Jun  3 09:30:34 XXXXXXXX rocketchat: at /opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:410:17
Jun  3 09:30:34 XXXXXXXX rocketchat: at /opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:398:11
Jun  3 09:30:34 XXXXXXXX rocketchat: at ClientSession.endSession (/opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sessions.js:134:41)
Jun  3 09:30:34 XXXXXXXX rocketchat: at executeCallback (/opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:395:17)
Jun  3 09:30:34 XXXXXXXX rocketchat: at deleteCallback (/opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:349:17)
Jun  3 09:30:34 XXXXXXXX rocketchat: at /opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:364:54
Jun  3 09:30:34 XXXXXXXX rocketchat: at handleCallback (/opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:128:55)
Jun  3 09:30:34 XXXXXXXX rocketchat: at /opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:1259:5
Jun  3 09:30:34 XXXXXXXX rocketchat: at /opt/Rocket.Chat-3.0.0/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:397:18
Jun  3 09:30:34 XXXXXXXX rocketchat: at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by LeiCaoX** [comment]
Login the web of rocket chat, find Administration / General / Site URL,  Site URL should be the same as the ROOT_URL in docker-compose.yml if you use docker-compose to deploy the rocket chat instance.
After you did as above, the upload will work success.

**Comment by LeiCaoX** [comment]
Login the web of rocket chat, find Administration / General / Site URL,  Site URL should be the same as the ROOT_URL in docker-compose.yml if you use docker-compose to deploy the rocket chat instance.
After you did as above, the upload will work success.
