### ISSUE TITLE
Rocket  suddenly crash - writesToCommitWhenWeReachSteadyLength: 0

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#17173]
### Description:

Today we have a crash of rocket chat. Suddenly CPU load incrased under 100% and chat became unresponsive. We have to restart all containers to bring it to work.
In logs I have noticed a lot of errors:
`2020-04-06T08:13:05.347938771Z     at OplogObserveDriver._doneQuerying (packages/mongo/oplog_observe_driver.js:802:13)
2020-04-06T08:13:05.347945991Z     at packages/mongo/oplog_observe_driver.js:700:14
2020-04-06T08:13:05.347951731Z     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-04-06T08:13:05.347957432Z     at packages/meteor.js:550:25
2020-04-06T08:13:05.347963135Z     at runWithEnvironment (packages/meteor.js:1286:24)
2020-04-06T08:13:34.719894374Z TIMEOUT QUERY OPERATION {
2020-04-06T08:13:34.719947889Z   observeKey: '{"ordered":false,"collectionName":"users","selector":{"_id":"QgYEQqLuRtNR7gXxq"},"options":{"transform":null,"fields":{"profile":1,"username":1,"emails":1}}}',
2020-04-06T08:13:34.719958256Z   writesToCommitWhenWeReachSteadyLength: 0,
2020-04-06T08:13:34.719977227Z   cursorDescription: '{"collectionName":"users","selector":{"_id":"QgYEQqLuRtNR7gXxq"},"options":{"transform":null,"fields":{"profile":1,"username":1,"emails":1}}}'
2020-04-06T08:13:34.719985292Z }
2020-04-06T08:13:34.720912968Z Exception in setInterval callback: SwitchedToQuery {}
2020-04-06T08:14:34.784314254Z Exception in defer callback: Error: Phase unexpectedly STEADY
2020-04-06T08:14:34.784362129Z     at OplogObserveDriver._doneQuerying (packages/mongo/oplog_observe_driver.js:802:13)
2020-04-06T08:14:34.784368614Z     at packages/mongo/oplog_observe_driver.js:700:14
2020-04-06T08:14:34.784373860Z     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-04-06T08:14:34.784379466Z     at packages/meteor.js:550:25
2020-04-06T08:14:34.784384472Z     at runWithEnvironment (packages/meteor.js:1286:24)
2020-04-06T08:15:21.151944852Z Exception in defer callback: Error: Phase unexpectedly STEADY
2020-04-06T08:15:21.152129192Z     at OplogObserveDriver._doneQuerying (packages/mongo/oplog_observe_driver.js:802:13)
2020-04-06T08:15:21.152137727Z     at packages/mongo/oplog_observe_driver.js:700:14
2020-04-06T08:15:21.152144403Z     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-04-06T08:15:21.152150653Z     at packages/meteor.js:550:25
2020-04-06T08:15:21.152156590Z     at runWithEnvironment (packages/meteor.js:1286:24)`

### Steps to reproduce:

1. Unknown

### Expected behavior:

Server is stable, not crash

### Actual behavior:

Rocket  suddenly crash

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.5
- Operating System: Centos 7
- Deployment Method: docker compose
- Number of Running Instances: 30
- DB Replicaset Oplog: YES
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.14

**Comment by AvivBenShoham** [comment]
I have the same error, any suggestions?
