### ISSUE TITLE
3.1.0-rc8 - filter in new user directory is not working

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat#17200]
### Description:

It is not possible to search for users in the new directory. Filter for Channels is working like expected.

### Steps to reproduce:

1. Directory
2. Select User List
3. no match for the name nor the username

### Expected behavior:

Filter for name or username would work

### Actual behavior:

Filter does not find anything.

### Server Setup Information:

- Version of Rocket.Chat Server:  3.1.0 rc8
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog:  enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App: 2.17.9
- Operating System: Fedora 31

### Additional context
Please let me know if further information are required.

**Comment by 1rV1N-git** [comment]
Same error in release 3.1.0
log
```
Apr 10 20:16:22 Chat rocketchat[21938]: server.js:204 API ➔ debug GET: /api/v1/directory?query={%22type%22:%22users%22,%22text%22:%22%D0%B2%22,%22workspace%22:%22local%22}&sort={%22name%22:1}&count=25
Apr 10 20:16:22 Chat rocketchat[21938]: server.js:204 Meteor ➔ method browseChannels -> userId: dAwqSuvPqt57W9DF7, arguments: [{"text":"в","type":"users","workspace":"local","sortBy":"name","sortDirection":"asc","offset":0,"limit":25}]
Apr 10 20:16:22 Chat rocketchat[21938]: server.js:204 API ➔ debug get directory threw an error: MongoError: error processing query: ns=rocketchat.usersTree: $and
Apr 10 20:16:22 Chat rocketchat[21938]:     $or
Apr 10 20:16:22 Chat rocketchat[21938]:         federation.origin $eq "domain.com"
Apr 10 20:16:22 Chat rocketchat[21938]:         $not
Apr 10 20:16:22 Chat rocketchat[21938]:             federation exists
Apr 10 20:16:22 Chat rocketchat[21938]:     $or
Apr 10 20:16:22 Chat rocketchat[21938]:         department regex /в/i
Apr 10 20:16:22 Chat rocketchat[21938]:         ipPhone regex /в/i
Apr 10 20:16:22 Chat rocketchat[21938]:         TEXT : query=в, language=none, caseSensitive=0, diacriticSensitive=0, tag=NULL
Apr 10 20:16:22 Chat rocketchat[21938]:     active $eq true
Apr 10 20:16:22 Chat rocketchat[21938]:     username exists
Apr 10 20:16:22 Chat rocketchat[21938]:     $not
Apr 10 20:16:22 Chat rocketchat[21938]:         username $in [ ]
Apr 10 20:16:22 Chat rocketchat[21938]: Sort: {}
Apr 10 20:16:22 Chat rocketchat[21938]: Proj: {}
Apr 10 20:16:22 Chat rocketchat[21938]:  No query solutions
Apr 10 20:16:22 Chat rocketchat[21938]:     at Connection.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:443:61)
Apr 10 20:16:22 Chat rocketchat[21938]:     at Connection.emit (events.js:311:20)
Apr 10 20:16:22 Chat rocketchat[21938]:     at Connection.EventEmitter.emit (domain.js:482:12)
Apr 10 20:16:22 Chat rocketchat[21938]:     at processMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:364:10)
Apr 10 20:16:22 Chat rocketchat[21938]:     at Socket.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:533:15)
Apr 10 20:16:22 Chat rocketchat[21938]:     at Socket.emit (events.js:311:20)
Apr 10 20:16:22 Chat rocketchat[21938]:     at Socket.EventEmitter.emit (domain.js:482:12)
Apr 10 20:16:22 Chat rocketchat[21938]:     at addChunk (_stream_readable.js:294:12)
Apr 10 20:16:22 Chat rocketchat[21938]:     at readableAddChunk (_stream_readable.js:275:11)
Apr 10 20:16:22 Chat rocketchat[21938]:     at Socket.Readable.push (_stream_readable.js:209:10)
Apr 10 20:16:22 Chat rocketchat[21938]:     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Apr 10 20:16:22 Chat rocketchat[21938]:  => awaited here:
Apr 10 20:16:22 Chat rocketchat[21938]:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
Apr 10 20:16:22 Chat rocketchat[21938]:     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
Apr 10 20:16:22 Chat rocketchat[21938]:     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Apr 10 20:16:22 Chat rocketchat[21938]:     at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/misc.js:193:61)
Apr 10 20:16:22 Chat rocketchat[21938]:     at packages/dispatch_run-as-user.js:211:14
Apr 10 20:16:22 Chat rocketchat[21938]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 10 20:16:22 Chat rocketchat[21938]:     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
Apr 10 20:16:22 Chat rocketchat[21938]:     at Object.get (app/api/server/v1/misc.js:193:25)
Apr 10 20:16:22 Chat rocketchat[21938]:     at app/api/server/api.js:368:82
Apr 10 20:16:22 Chat rocketchat[21938]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 10 20:16:22 Chat rocketchat[21938]:     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:368:39)
Apr 10 20:16:22 Chat rocketchat[21938]:     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Apr 10 20:16:22 Chat rocketchat[21938]:     at packages/nimble_restivus/lib/route.coffee:59:33
Apr 10 20:16:22 Chat rocketchat[21938]:     at packages/simple_json-routes.js:98:9
Apr 10 20:16:22 Chat rocketchat[21938]: server.js:204 API ➔ debug Failure {
Apr 10 20:16:22 Chat rocketchat[21938]:   statusCode: 400,
Apr 10 20:16:22 Chat rocketchat[21938]:   body: {
Apr 10 20:16:22 Chat rocketchat[21938]:     success: false,
Apr 10 20:16:22 Chat rocketchat[21938]:     error: 'error processing query: ns=rocketchat.usersTree: $and\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       '    $or\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       '        federation.origin $eq "domain.com"\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       '        $not\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       '            federation exists\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       '    $or\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       '        department regex /в/i\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       '        ipPhone regex /в/i\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       '        TEXT : query=в, language=none, caseSensitive=0, diacriticSensitive=0, tag=NULL\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       '    active $eq true\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       '    username exists\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       '    $not\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       '        username $in [ ]\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       'Sort: {}\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       'Proj: {}\n' +
Apr 10 20:16:22 Chat rocketchat[21938]:       ' No query solutions',
Apr 10 20:16:22 Chat rocketchat[21938]:     stack: undefined
Apr 10 20:16:22 Chat rocketchat[21938]:   }
Apr 10 20:16:22 Chat rocketchat[21938]: }

```
