### ISSUE TITLE
Jitsi call between servers in federation mode is not working

### ISSUE THREAD

**Issue by Stanymanman** [RocketChat/Rocket.Chat#17202]
### Description:

Hi,

Jitsi is enabled on our servers.
It's working well between users on the same server.
But when clicking "Video Chat" in a chat with users from servers in federation, users on remote server don't see the "click to join !"  

### Steps to reproduce:

On the first server we launch the video chat:

![image](https://user-images.githubusercontent.com/13351946/78675152-f2d2cf80-78e4-11ea-807b-2deea8abce28.png)

On the remote server there is no "click to join !":

![image](https://user-images.githubusercontent.com/13351946/78675295-2281d780-78e5-11ea-94e5-7637559e2081.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.12
- Operating System: Ubuntu Server 18.04
- Deployment Method: Manual Install
- Number of Running Instances: 2
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.17

### Relevant logs:

On log we have this:

Exception while invoking method 'jitsi:updateTimeout' TypeError: resource.mentions is not iterable     at Object.normalizeMessage (app/federation/server/normalizers/message.js:62:33)     at app/federation/server/hooks/afterSaveMessage.js:22:102     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at callback (app/federation/server/hooks/afterSaveMessage.js:33:39)     at callbacks.runItem (app/callbacks/lib/callbacks.js:110:70)     at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)     at app/callbacks/lib/callbacks.js:39:35     at app/callbacks/lib/callbacks.js:45:45     at app/callbacks/lib/callbacks.js:45:47     at callbacks.run (app/callbacks/lib/callbacks.js:126:9)     at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)     at MethodInvocation.jitsi:updateTimeout (app/videobridge/server/methods/jitsiSetTimeout.js:42:14)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

Thanks !

**Comment by ankar84** [comment]
Confirm that for 3.1.0

**Comment by Stanymanman** [comment]
Hi,
yes problem is always here.

**Comment by Polyblog** [comment]
I have the same problem on 3.2.2 version.

**Comment by ankar84** [comment]
I think, that the only way to resolve that issue is to configure guest virtual host without authorization in Jitsi and share created calls links in federation enabled chat. That way federated users will see the link and can join call like guests.

**Comment by Polyblog** [comment]
Yep, I use this method, but it isn't comfortable for common users. They confuse internal and external calls.

**Comment by ankar84** [comment]
Still an issue

**Comment by ankar84** [comment]
Problem still here

**Comment by ankar84** [comment]
Also I think, if one Jitsi domain set to secure domain - federated domain need same secrets to Jitsi calls works transparently

**Comment by EnCz** [comment]
still a problem

**Comment by ImaCrea** [comment]
still a problem on 3.8.1
two federated instances but sharing same jitsi instance
