### ISSUE TITLE
Starting a discussion stopped working on 3.1.0

### ISSUE THREAD

**Issue by pehlert** [RocketChat/Rocket.Chat#17246]
### Description:

The attempt to open a discussion (from a private conversation) on 3.1.0 shows "Internal server error"

### Relevant logs:
```
I20200410-10:08:18.705(0) Exception while invoking method 'createDiscussion' TypeError: Cannot read property 'localeCompare' of undefined
     at app/lib/server/functions/createDirectRoom.js:31:74 
     at Array.sort (<anonymous>)
     at createDirectRoom (app/lib/server/functions/createDirectRoom.js:31:32)
     at createRoom (app/lib/server/functions/createRoom.js:16:10)
     at create (app/discussion/server/methods/createDiscussion.js:89:21)
     at MethodInvocation.createDiscussion (app/discussion/server/methods/createDiscussion.js:137:10)
     at MethodInvocation.methodsMap.computed> (app/lib/server/lib/debug.js:67:34)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
     at packages/ddp-server/livedata_server.js:719:19
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at packages/ddp-server/livedata_server.js:717:46
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at packages/ddp-server/livedata_server.js:715:46
     at new Promise (<anonymous>)
     at Session.method (packages/ddp-server/livedata_server.js:689:23)
     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by pehlert** [comment]
After looking at the source code I think it may be relevant to mention that all users involved are imported from LDAP

**Comment by talheim-it** [comment]
@pehlert verified. This is happening.

**Comment by ankar84** [comment]
Confirm that bug from multi DM also.

**Comment by ggazzo** [comment]
introduced here: https://github.com/RocketChat/Rocket.Chat/pull/17070

**Comment by sampaiodiego** [comment]
fixed by https://github.com/RocketChat/Rocket.Chat/pull/17282

we'll ship a hotfix release including the fix by today

**Comment by pehlert** [comment]
Thanks so much guys, keep up the great work!
