### ISSUE TITLE
LDAPError [ProtocolError]: paged results cookie is invalid

### ISSUE THREAD

**Issue by solune** [RocketChat/Rocket.Chat#17248]
### Description:

When importing 10488 users from my ldap, I have this error and I have only 3400 users in RC.

### Steps to reproduce:

1. Go to Administration / Parametrs / LDAP / Sync / Import  
2.  Click on Sync now 

### Expected behavior:

No error and 10488 users in RC

### Actual behavior:

`Exception in callback of async function: LDAPError [ProtocolError]: paged results cookie is invalid
at messageCallback (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)
at Parser.onMessage (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)
at Parser.emit (events.js:311:20)
at Parser.EventEmitter.emit (domain.js:482:12)
at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)
at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)
at Socket.emit (events.js:311:20)
at Socket.EventEmitter.emit (domain.js:482:12)
at addChunk (_stream_readable.js:294:12)
at readableAddChunk (_stream_readable.js:275:11)
at Socket.Readable.push (_stream_readable.js:209:10)
at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
lde_message: 'paged results cookie is invalid',
lde_dn: null`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0
- Operating System: Kubernetes
- Deployment Method: docker
- Number of Running Instances: 1

regards

**Comment by solune** [comment]
I decrease search page size to 499
It works
