### ISSUE TITLE
MongoTimeoutError: Server selection timed out after 10000 ms - includes possible solution

### ISSUE THREAD

**Issue by peasead** [RocketChat/Rocket.Chat#17257]
### Description:

When running Rocket.Chat in Docker, there is a timeout error between Rocket.Chat and Mongo. 

I believe that this is related to an issue with Mongoose and can be addressed, I think, with an updated version of Mongoose or setting `useUnifiedTopology` to `false`...I'm not entirely sure where you do that? I tried adding it as an environment variable to Mongo, but it didn't recognize it as valid.

This issue is documented [here](https://github.com/Automattic/mongoose/issues/8180) as well as a litany of other places on the timeout issue

### Steps to reproduce:

1. Download the Docker Compose file located [here](https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/docker-compose.yml)
2. `docker-compose up`

### Expected behavior:

Services to come up.

### Actual behavior:

I think this is the crux of it
```
rocketchat_1          | MongoTimeoutError: Server selection timed out after 10000 ms
rocketchat_1          |     at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
rocketchat_1          |     at listOnTimeout (internal/timers.js:549:17)
rocketchat_1          |     at processTimers (internal/timers.js:492:7) {
rocketchat_1          |   name: 'MongoTimeoutError',
rocketchat_1          |   [Symbol(mongoErrorContextSymbol)]: {}
rocketchat_1          | }
```

### Server Setup Information:

- Version of Rocket.Chat Server: `:latest`
- Operating System: CentOS
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 128?
- NodeJS Version: Unknown, it's in the RC Docker image
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: NA
- Operating System: macOS

### Additional Context
```
rocketchat_1          | Tried 3 times. Waiting 5 secs...
mongo-init-replica_1  | 2020-04-11T03:05:12.159+0000 E QUERY    [js] Error: couldn't connect to server mongo:27017, connection attempt failed: HostNotFound: Could not find address for mongo:27017: SocketException: Host not found (authoritative) :
mongo-init-replica_1  | connect@src/mongo/shell/mongo.js:344:17
mongo-init-replica_1  | @(connect):2:6
mongo-init-replica_1  | exception: connect failed
mongo-init-replica_1  | Tried 4 times. Waiting 5 secs...
mongo-init-replica_1  | MongoDB shell version v4.0.17
mongo-init-replica_1  | connecting to: mongodb://mongo:27017/rocketchat?gssapiServiceName=mongodb
mongo_1               | find: '/data/db': Permission denied
mongo_1               | chown: changing ownership of '/data/db': Permission denied
mongo_1               | find: '/data/db': Permission denied
mongo_1               | chown: changing ownership of '/data/db': Permission denied
mongo_1               | find: '/data/db': Permission denied
mongo_1               | chown: changing ownership of '/data/db': Permission denied
mongo_1               | find: '/data/db': Permission denied
mongo_1               | chown: changing ownership of '/data/db': Permission denied
mongo_1               | find: '/data/db': Permission denied
mongo_1               | chown: changing ownership of '/data/db': Permission denied
mongo_1               | find: '/data/db': Permission denied
mongo_1               | chown: changing ownership of '/data/db': Permission denied
mongo_1               | find: '/data/db': Permission denied
mongo_1               | chown: changing ownership of '/data/db': Permission denied
mongo_1               | find: '/data/db': Permission denied
mongo_1               | chown: changing ownership of '/data/db': Permission denied
mongo_1               | find: '/data/db': Permission denied
mongo_1               | chown: changing ownership of '/data/db': Permission denied
mongo_1               | find: '/data/db': Permission denied
mongo_1               | chown: changing ownership of '/data/db': Permission denied
rocketchat_1          | /app/bundle/programs/server/node_modules/fibers/future.js:313
rocketchat_1          | 						throw(ex);
rocketchat_1          | 						^
rocketchat_1          |
rocketchat_1          | MongoTimeoutError: Server selection timed out after 10000 ms
rocketchat_1          |     at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
rocketchat_1          |     at listOnTimeout (internal/timers.js:549:17)
rocketchat_1          |     at processTimers (internal/timers.js:492:7) {
rocketchat_1          |   name: 'MongoTimeoutError',
rocketchat_1          |   [Symbol(mongoErrorContextSymbol)]: {}
rocketchat_1          | }
rocketchat_1          | Tried 4 times. Waiting 5 secs...
mongo-init-replica_1  | 2020-04-11T03:05:27.243+0000 E QUERY    [js] Error: couldn't connect to server mongo:27017, connection attempt failed: HostNotFound: Could not find address for mongo:27017: SocketException: Host not found (authoritative) :
mongo-init-replica_1  | connect@src/mongo/shell/mongo.js:344:17
mongo-init-replica_1  | @(connect):2:6
mongo-init-replica_1  | exception: connect failed
mongo-init-replica_1  | Tried 5 times. Waiting 5 secs...
mongo-init-replica_1  | MongoDB shell version v4.0.17
mongo-init-replica_1  | connecting to: mongodb://mongo:27017/rocketchat?gssapiServiceName=mongodb
rocketchat_1          | /app/bundle/programs/server/node_modules/fibers/future.js:313
rocketchat_1          | 						throw(ex);
rocketchat_1          | 						^
rocketchat_1          |
rocketchat_1          | MongoTimeoutError: Server selection timed out after 10000 ms
rocketchat_1          |     at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
rocketchat_1          |     at listOnTimeout (internal/timers.js:549:17)
rocketchat_1          |     at processTimers (internal/timers.js:492:7) {
rocketchat_1          |   name: 'MongoTimeoutError',
rocketchat_1          |   [Symbol(mongoErrorContextSymbol)]: {}
rocketchat_1          | }
rocketchat_1          | Tried 5 times. Waiting 5 secs...
mongo-init-replica_1  | 2020-04-11T03:05:42.348+0000 E QUERY    [js] Error: couldn't connect to server mongo:27017, connection attempt failed: HostNotFound: Could not find address for mongo:27017: SocketException: Host not found (authoritative) :
mongo-init-replica_1  | connect@src/mongo/shell/mongo.js:344:17
mongo-init-replica_1  | @(connect):2:6
mongo-init-replica_1  | exception: connect failed
mongo-init-replica_1  | Tried 6 times. Waiting 5 secs...
mongo-init-replica_1  | MongoDB shell version v4.0.17
mongo-init-replica_1  | connecting to: mongodb://mongo:27017/rocketchat?gssapiServiceName=mongodb
^CGracefully stopping... (press Ctrl+C again to force)
Stopping admin_hubot_1              ... done
Stopping admin_rocketchat_1         ... done
Stopping admin_mongo-init-replica_1 ... done
Stopping admin_mongo_1              ... done
```

**Comment by peasead** [comment]
This is something with my setup...not sure what, but I just did a complete bare deploy and it worked fine. 

How embarrassing.
