### ISSUE TITLE
Database duplicate key errors on federated room

### ISSUE THREAD

**Issue by ndroo** [RocketChat/Rocket.Chat#17332]
I've been working on a federated room setup, a fairly large one, and i hit a user_id collision (which seems nuts, but yeah...)

````
BulkWriteError: E11000 duplicate key error index: staff_rocketchat.rocketchat_subscription.$rid_1_u._id_1 dup key: { : "JkwT6hhMnTbQd3Ku9", : "yk9cq9FZJXnvyywpt" }
    at OrderedBulkOperation.handleWriteError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:1112:11)
    at resultHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:501:23)
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:397:18
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at app/federation/server/endpoints/dispatch.js:421:16
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
  index: 0,
  code: 11000,
  errmsg: 'E11000 duplicate key error index: staff_rocketchat.rocketchat_subscription.$rid_1_u._id_1 dup key: { : "JkwT6hhMnTbQd3Ku9", : "yk9cq9FZJXnvyywpt" }',
  op: {
    _id: 'mfnaFk6KvqKKgSbdZ',
    open: true,
    alert: true,
    unread: 1,
    userMentions: 1,
    groupMentions: 0,
    ts: 2020-04-16T16:22:10.386Z,
    rid: 'JkwT6hhMnTbQd3Ku9',
    name: 'national-forum',
    fname: 'national-forum',
    customFields: {},
    t: 'p',
    u: {
      _id: 'yk9cq9FZJXnvyywpt',
      username: 'amcgrath@wmich.abc.com',
      name: 'andrew mcgrath'
    },
    _updatedAt: 2020-04-16T16:22:16.724Z,
    federation: { origin: 'wmich.abc.com' }
  },
  name: 'BulkWriteError',
  driver: true,
  err: {
    index: 0,
    code: 11000,
    errmsg: 'E11000 duplicate key error index: staff_rocketchat.rocketchat_subscription.$rid_1_u._id_1 dup key: { : "JkwT6hhMnTbQd3Ku9", : "yk9cq9FZJXnvyywpt" }',
    op: {
      _id: 'mfnaFk6KvqKKgSbdZ',
      open: true,
      alert: true,
      unread: 1,
      userMentions: 1,
      groupMentions: 0,
      ts: 2020-04-16T16:22:10.386Z,
      rid: 'JkwT6hhMnTbQd3Ku9',
      name: 'national-forum',
      fname: 'national-forum',
      customFields: {},
      t: 'p',
      u: [Object],
      _updatedAt: 2020-04-16T16:22:16.724Z,
      federation: [Object]
    }
  },
  result: BulkWriteResult {
    result: {
      ok: 1,
      writeErrors: [Array],
      writeConcernErrors: [],
      insertedIds: [Array],
      nInserted: 0,
      nUpserted: 0,
      nMatched: 0,
      nModified: 0,
      nRemoved: 0,
      upserted: [],
      lastOp: [Object]
    }
  },
  [Symbol(mongoErrorContextSymbol)]: {}
}
---------------------------------
Errors like this can cause oplog processing errors.
Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Future node.js versions will automatically exit the process
````

I looked at the rocketchat_subscription table indexes and found that it doesnt consider the federated domain origin when looking at the rid and _uid. I am thinking given that uid's are only guaranteed to be unique within a single instance, that duplicates could be totally possible across the federation.

Am i nuts?

This is the index i'm talking about on the rocketchat_subscription table
`	{
		"v" : 2,
		"key" : {
			"rid" : 1,
			"u.username" : 1
		},
		"name" : "rid_1_u.username_1",
		"ns" : "staff_rocketchat.rocketchat_subscription"
	}
`

For now, i'm just going to catch these exceptions and log it so I can move along (as it should be super rare), but i think we need to ensure that IF a user_id collides across instances, that this doesnt mess up the federated room (which it currently seems to do).

**Comment by ndroo** [comment]
So i'm not really sure how i ended up in this state, but i have been working on other federation fixes and it's no longer an issue in light of those changes, which i'll submit a PR for in the near future.
