### ISSUE TITLE
3.1.1 fails to authenticate to MongoDB

### ISSUE THREAD

**Issue by barthalion** [RocketChat/Rocket.Chat#17360]
Hello,

I'm trying to update from 3.0.12 to 3.1.1 on OpenShift (we're using rocketchat/rocket.chat image from Docker Hub) but it always ends with the following error:

```
/app/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^

MongoError: Authentication failed.
    at Function._getError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/auth/scram.js:125:14)
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/auth/scram.js:175:31
    at Connection.messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connect.js:334:5)
    at Connection.emit (events.js:311:20)
    at processMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {}
}
```

I'm 100% sure credentials are correct as otherwise 3.0.12 wouldn't work in the first place. I also tested them via CLI mongo client and connct just fine.

**Comment by luixxiul** [comment]
I also am thinking to update 3.0.12 to 3.1.1 and would like to know how to avoid the issue.

**Comment by Madpong** [comment]
Try restarting mongoDB frist

**Comment by barthalion** [comment]
I don't see how restarting MongoDB would help. (And it did not.)

**Comment by barthalion** [comment]
Looking at Mongo logs, this is how authentication failure is logged:

```
2020-04-22T06:45:10.241+0000 I ACCESS   [conn46] SCRAM-SHA-1 authentication failed for mongodb on rocketchat?replicaSet from client x:57236 ; UserNotFound: Could not find user mongodb@rocketchat?replicaSet
```

The `?replicaSet` part is odd. MONGO_URL is set to `MONGO_URL=mongodb://mongodb:xyz@mongodb:27017/rocketchat?replicaSet=rs0`.

We run MongoDB 3.6.
