### ISSUE TITLE
[BUG] TypeError: Cannot read property 'success' of undefined on federation message

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17409]
### Description:

We set federation with 2 rocket chat deployments.
**company.ru** - RC version 3.0.3, federation test pass ok
**company.com** - RC version 3.1.1, federation test pass ok

We have a problem with federation right now.
User from company.ru can find users from company.com and can send messages to them, users in company.com see that messages, but when they send reply - user from company.ru  don't see them and in logs of company.ru deployment appears error: TypeError: Cannot read property 'success' of undefined
In company.com logs all sent messages attempts with errors:
`server.js:204 Federation ➔ http.error [IGNORED] Error Error: ETIMEDOUT*<br>`
More logs in a log section

### Expected behavior:

All messages are sent in both directions

### Actual behavior:

Messages are sent and receive only from company.ru to company.com

### Server Setup Information:
**company.ru**
- Version of Rocket.Chat Server: 3.0.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 12
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.17

**company.com**
- Version of Rocket.Chat Server: 3.1.1
- Operating System: CentOS8
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 81
- Operating System: Windows 10

### Relevant logs:
<details>

```
	April 24th 2020, 06:03:14.150	s-rc-srv-01	rocketchat_rocketchat_1_1	Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
	April 24th 2020, 06:03:14.150	s-rc-srv-01	rocketchat_rocketchat_1_1	=================================
	April 24th 2020, 06:03:14.150	s-rc-srv-01	rocketchat_rocketchat_1_1	Future node.js versions will automatically exit the process
	April 24th 2020, 06:03:14.149	s-rc-srv-01	rocketchat_rocketchat_1_1	Errors like this can cause oplog processing errors.
	April 24th 2020, 06:03:14.147	s-rc-srv-01	rocketchat_rocketchat_1_1	---------------------------------
	April 24th 2020, 06:03:14.145	s-rc-srv-01	rocketchat_rocketchat_1_1	at app/federation/server/endpoints/dispatch.js:425:21
	April 24th 2020, 06:03:14.145	s-rc-srv-01	rocketchat_rocketchat_1_1	at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
	April 24th 2020, 06:03:14.145	s-rc-srv-01	rocketchat_rocketchat_1_1	TypeError: Cannot read property 'success' of undefined
	April 24th 2020, 06:03:14.143	s-rc-srv-01	rocketchat_rocketchat_1_1	=== UnHandledPromiseRejection ===
	April 24th 2020, 06:03:08.948	s-rc-srv-01	rocketchat_rocketchat_4_1	=================================
	April 24th 2020, 06:03:08.947	s-rc-srv-01	rocketchat_rocketchat_4_1	Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
	April 24th 2020, 06:03:08.947	s-rc-srv-01	rocketchat_rocketchat_4_1	Errors like this can cause oplog processing errors.
	April 24th 2020, 06:03:08.947	s-rc-srv-01	rocketchat_rocketchat_4_1	Future node.js versions will automatically exit the process
	April 24th 2020, 06:03:08.946	s-rc-srv-01	rocketchat_rocketchat_4_1	at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
	April 24th 2020, 06:03:08.946	s-rc-srv-01	rocketchat_rocketchat_4_1	---------------------------------
	April 24th 2020, 06:03:08.946	s-rc-srv-01	rocketchat_rocketchat_4_1	at app/federation/server/endpoints/dispatch.js:425:21
	April 24th 2020, 06:03:08.940	s-rc-srv-01	rocketchat_rocketchat_4_1	TypeError: Cannot read property 'success' of undefined
	April 24th 2020, 06:03:08.938	s-rc-srv-01	rocketchat_rocketchat_4_1	=== UnHandledPromiseRejection ===
	
	April 24th 2020, 09:50:30.174	s-rc-srv-01	rocketchat_rocketchat_3_1	Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
	April 24th 2020, 09:50:30.174	s-rc-srv-01	rocketchat_rocketchat_3_1	=================================
	April 24th 2020, 09:50:30.174	s-rc-srv-01	rocketchat_rocketchat_3_1	Future node.js versions will automatically exit the process
	April 24th 2020, 09:50:30.173	s-rc-srv-01	rocketchat_rocketchat_3_1	at app/federation/server/endpoints/dispatch.js:425:21
	April 24th 2020, 09:50:30.173	s-rc-srv-01	rocketchat_rocketchat_3_1	---------------------------------
	April 24th 2020, 09:50:30.173	s-rc-srv-01	rocketchat_rocketchat_3_1	Errors like this can cause oplog processing errors.
	April 24th 2020, 09:50:30.173	s-rc-srv-01	rocketchat_rocketchat_3_1	at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
	April 24th 2020, 09:50:30.172	s-rc-srv-01	rocketchat_rocketchat_3_1	TypeError: Cannot read property 'success' of undefined
	April 24th 2020, 09:50:30.172	s-rc-srv-01	rocketchat_rocketchat_3_1	=== UnHandledPromiseRejection ===
```
</details>

**Comment by ankar84** [comment]
Rocket chat server on company.ru today was upgraded to same server version 3.1.1 as company.com and issue is solved now.
So, you should be aware, that for federation same versions could be necessary.
