### ISSUE TITLE
Problem when updating from 2.4.9 -> 3.1.1 (and 3.2.0)

### ISSUE THREAD

**Issue by JohnLukeP** [RocketChat/Rocket.Chat#17476]
Hi, I'm trying to update from rocketchat 2.4.9 to 3.1.1 (and also tried 3.2.0). I've updated all the requirements, included nodejs from 8.17 to 12.16.2. When running npm install in the extracted tgz I encounter some errors. When I try to start the build package, it gives errors and won't start.

### Steps to reproduce:

1. Download Rocket.Chat 3.1.1 or 3.2.0
2. extract the tgz into tmp
3. run _cd /tmp/bundle/programs/server && npm install_

### Expected behavior:

The build is succesfull and the application starts normally

### Actual behavior:

when building, I have these errors:
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

fibers@4.0.3 install /tmp/bundle/programs/server/node_modules/fibers
node build.js || nodejs build.js

linux-x64-72-glibc exists; testing
Problem with the binary; manual build incoming
make: Entering directory `/tmp/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory `/tmp/bundle/programs/server/node_modules/fibers/build'
Installed in `/tmp/bundle/programs/server/node_modules/fibers/bin/linux-x64-72-glibc/fibers.node`
npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd meteor-dev-bundle@ node npm-rebuild.js (wd=/tmp/bundle/programs/server)
added 146 packages from 122 contributors and audited 305 packages in 7.613s

1 package is looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

```
And when starting, in /var/log/messages I have:

```
Apr 29 11:04:05 liferayoo4 rocketchat: ## There is an issue with `node-fibers` ##
Apr 29 11:04:05 liferayoo4 rocketchat: `/wos1/Rocket.Chat/programs/server/node_modules/fibers/bin/linux-x64-72-glibc/fibers.node` is missing.
Apr 29 11:04:05 liferayoo4 rocketchat: Try running this to fix the issue: /usr/bin/node /wos1/Rocket.Chat/programs/server/node_modules/fibers/build
Apr 29 11:04:05 liferayoo4 rocketchat: Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /wos1/Rocket.Chat/programs/server/node_modules/fibers/bin/linux-x64-72-glibc/fibers.node)
Apr 29 11:04:05 liferayoo4 rocketchat: at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
Apr 29 11:04:05 liferayoo4 rocketchat: at Module.load (internal/modules/cjs/loader.js:1000:32)
Apr 29 11:04:05 liferayoo4 rocketchat: at Module.Mp.load (/wos1/Rocket.Chat/programs/server/runtime.js:15:31)
Apr 29 11:04:05 liferayoo4 rocketchat: at Function.Module._load (internal/modules/cjs/loader.js:899:14)
Apr 29 11:04:05 liferayoo4 rocketchat: at Module.require (internal/modules/cjs/loader.js:1042:19)
Apr 29 11:04:05 liferayoo4 rocketchat: at require (internal/modules/cjs/helpers.js:77:18)
Apr 29 11:04:05 liferayoo4 rocketchat: at Object.<anonymous> (/wos1/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:14:39)
Apr 29 11:04:05 liferayoo4 rocketchat: at Module._compile (internal/modules/cjs/loader.js:1156:30)
Apr 29 11:04:05 liferayoo4 rocketchat: at Module.Mp._compile (/wos1/Rocket.Chat/programs/server/runtime.js:50:23)
Apr 29 11:04:05 liferayoo4 rocketchat: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Apr 29 11:04:05 liferayoo4 rocketchat: /wos1/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:23
Apr 29 11:04:05 liferayoo4 rocketchat: throw new Error('Missing binary. See message above.');
Apr 29 11:04:05 liferayoo4 rocketchat: ^
Apr 29 11:04:05 liferayoo4 rocketchat: Error: Missing binary. See message above.
Apr 29 11:04:05 liferayoo4 rocketchat: at Object.<anonymous> (/wos1/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:23:9)
Apr 29 11:04:05 liferayoo4 rocketchat: at Module._compile (internal/modules/cjs/loader.js:1156:30)
Apr 29 11:04:05 liferayoo4 rocketchat: at Module.Mp._compile (/wos1/Rocket.Chat/programs/server/runtime.js:50:23)
Apr 29 11:04:05 liferayoo4 rocketchat: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Apr 29 11:04:05 liferayoo4 rocketchat: at Module.load (internal/modules/cjs/loader.js:1000:32)
Apr 29 11:04:05 liferayoo4 rocketchat: at Module.Mp.load (/wos1/Rocket.Chat/programs/server/runtime.js:15:31)
Apr 29 11:04:05 liferayoo4 rocketchat: at Function.Module._load (internal/modules/cjs/loader.js:899:14)
Apr 29 11:04:05 liferayoo4 rocketchat: at Module.require (internal/modules/cjs/loader.js:1042:19)
Apr 29 11:04:05 liferayoo4 rocketchat: at require (internal/modules/cjs/helpers.js:77:18)
Apr 29 11:04:05 liferayoo4 rocketchat: at Object.<anonymous> (/wos1/Rocket.Chat/programs/server/boot.js:2:15)
Apr 29 11:04:05 liferayoo4 systemd: rocketchat.service: main process exited, code=exited, status=1/FAILURE
Apr 29 11:04:05 liferayoo4 systemd: Unit rocketchat.service entered failed state.
Apr 29 11:04:05 liferayoo4 systemd: rocketchat.service failed.
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1 and 3.2.0
- Operating System: Centos 7.6.1810 
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version:  12.16.2
- MongoDB Version: v4.0.14

What can I do to properly install it?

**Comment by robinreinhardt** [comment]
Hey @JohnLukeP,
can you try to update from 2.4.9 to 2.4.11 first?
After that maybe you are able to update on the 3.0.12.
I have successfully updated from 2.4.11 to 3.0.12

**Comment by JohnLukeP** [comment]
Hi @robinreinhardt,

I've tried updating from 2.4.9 to 2.4.11 and all went smooth. Then I try updating to 3.0.0 following the Centos manual install procedure (which at this moment is still for 3.0.0) but I still have these errors when starting the server:

```
May  4 17:05:36 liferayoo4 rocketchat: ## There is an issue with `node-fibers` ##
May  4 17:05:36 liferayoo4 rocketchat: `/wos1/Rocket.Chat/programs/server/node_modules/fibers/bin/linux-x64-72-glibc/fibers.node` is missing.
May  4 17:05:36 liferayoo4 rocketchat: Try running this to fix the issue: /usr/local/bin/node /wos1/Rocket.Chat/programs/server/node_modules/fibers/build
May  4 17:05:36 liferayoo4 rocketchat: Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /wos1/Rocket.Chat/programs/server/node_modules/fibers/bin/linux-x64-72-glibc/fibers.node)
May  4 17:05:36 liferayoo4 rocketchat: at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
May  4 17:05:36 liferayoo4 rocketchat: at Module.load (internal/modules/cjs/loader.js:815:32)
May  4 17:05:36 liferayoo4 rocketchat: at Module.Mp.load (/wos1/Rocket.Chat/programs/server/runtime.js:15:31)
May  4 17:05:36 liferayoo4 rocketchat: at Function.Module._load (internal/modules/cjs/loader.js:727:14)
May  4 17:05:36 liferayoo4 rocketchat: at Module.require (internal/modules/cjs/loader.js:852:19)
May  4 17:05:36 liferayoo4 rocketchat: at require (internal/modules/cjs/helpers.js:74:18)
May  4 17:05:36 liferayoo4 rocketchat: at Object.<anonymous> (/wos1/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:14:39)
May  4 17:05:36 liferayoo4 rocketchat: at Module._compile (internal/modules/cjs/loader.js:959:30)
May  4 17:05:36 liferayoo4 rocketchat: at Module.Mp._compile (/wos1/Rocket.Chat/programs/server/runtime.js:50:23)
May  4 17:05:36 liferayoo4 rocketchat: at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
May  4 17:05:36 liferayoo4 rocketchat: /wos1/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:23
May  4 17:05:36 liferayoo4 rocketchat: throw new Error('Missing binary. See message above.');
May  4 17:05:36 liferayoo4 rocketchat: ^
May  4 17:05:36 liferayoo4 rocketchat: Error: Missing binary. See message above.
May  4 17:05:36 liferayoo4 rocketchat: at Object.<anonymous> (/wos1/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:23:9)
May  4 17:05:36 liferayoo4 rocketchat: at Module._compile (internal/modules/cjs/loader.js:959:30)
May  4 17:05:36 liferayoo4 rocketchat: at Module.Mp._compile (/wos1/Rocket.Chat/programs/server/runtime.js:50:23)
May  4 17:05:36 liferayoo4 rocketchat: at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
May  4 17:05:36 liferayoo4 rocketchat: at Module.load (internal/modules/cjs/loader.js:815:32)
May  4 17:05:36 liferayoo4 rocketchat: at Module.Mp.load (/wos1/Rocket.Chat/programs/server/runtime.js:15:31)
May  4 17:05:36 liferayoo4 rocketchat: at Function.Module._load (internal/modules/cjs/loader.js:727:14)
May  4 17:05:36 liferayoo4 rocketchat: at Module.require (internal/modules/cjs/loader.js:852:19)
May  4 17:05:36 liferayoo4 rocketchat: at require (internal/modules/cjs/helpers.js:74:18)
May  4 17:05:36 liferayoo4 rocketchat: at Object.<anonymous> (/wos1/Rocket.Chat/programs/server/boot.js:2:15)
May  4 17:05:36 liferayoo4 systemd: rocketchat.service: main process exited, code=exited, status=1/FAILURE
May  4 17:05:36 liferayoo4 systemd: Unit rocketchat.service entered failed state.
May  4 17:05:36 liferayoo4 systemd: rocketchat.service failed.
```

**Comment by robinreinhardt** [comment]
Hey @JohnLukeP,

we had the same issue. Your error log also says that CXXABI_1.3.9 is missing.
`Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found`

To my knowledge, unfortunately CXXABI_1.3.9 is not available on CentOS 7, only on CentOS 8. Maybe you can find other information about it.

**Comment by gstlouisgit** [comment]
so that's it?  No longer supporting centos 7 because of a missing dependency?  @gabriellsh
