### ISSUE TITLE
Directory not loading again after clicking on user or room

### ISSUE THREAD

**Issue by EnCz** [RocketChat/Rocket.Chat#17546]
### Description:

After clicking on a user or room **from the directory** the page stays white when entering the directory **again**. Only a site refresh helps to bring the page back.
I can reproduce this problem **on 3 different** rocketchat instances.

### Steps to reproduce:

~1. Go to Directory
2. Click on User or Room
3. Go to Directory~
-> see next coment: https://github.com/RocketChat/Rocket.Chat/issues/17546#issuecomment-625662384

### Expected behavior:

Directory Page opens

### Actual behavior:

Directory Page stays completely white

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.0
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Active
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.17

### Additional Information

**I also get JavaScript errors when clicking on a room or user:**
`/node_modules/react-dom/cjs/react-dom.production.min.js:206 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at wh (/node_modules/react-dom/cjs/react-dom.production.min.js:216:65)
    at Th (/node_modules/react-dom/cjs/react-dom.production.min.js:222:322)
    at Zh (/node_modules/react-dom/cjs/react-dom.production.min.js:228:14)
    at eval (/node_modules/react-dom/cjs/react-dom.production.min.js:258:268)
    at Object.exports.unstable_runWithPriority (/node_modules/scheduler/cjs/scheduler.production.min.js:26:163)
    at Fi (/node_modules/react-dom/cjs/react-dom.production.min.js:258:203)
    at Di (/node_modules/react-dom/cjs/react-dom.production.min.js:257:383)
    at Yh (/node_modules/react-dom/cjs/react-dom.production.min.js:256:144)
    at Ii (/node_modules/react-dom/cjs/react-dom.production.min.js:259:256)
    at Cd (/node_modules/react-dom/cjs/react-dom.production.min.js:93:207)
qh @ /node_modules/react-dom/cjs/react-dom.production.min.js:206
Ch.c.callback @ /node_modules/react-dom/cjs/react-dom.production.min.js:218
ih @ /node_modules/react-dom/cjs/react-dom.production.min.js:201
hh @ /node_modules/react-dom/cjs/react-dom.production.min.js:201
Vh @ /node_modules/react-dom/cjs/react-dom.production.min.js:225
Zh @ /node_modules/react-dom/cjs/react-dom.production.min.js:228
eval @ /node_modules/react-dom/cjs/react-dom.production.min.js:258
exports.unstable_runWithPriority @ /node_modules/scheduler/cjs/scheduler.production.min.js:26
Fi @ /node_modules/react-dom/cjs/react-dom.production.min.js:258
Di @ /node_modules/react-dom/cjs/react-dom.production.min.js:257
Yh @ /node_modules/react-dom/cjs/react-dom.production.min.js:256
Ii @ /node_modules/react-dom/cjs/react-dom.production.min.js:259
Cd @ /node_modules/react-dom/cjs/react-dom.production.min.js:93
/node_modules/react-dom/cjs/react-dom.production.min.js:256 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at wh (/node_modules/react-dom/cjs/react-dom.production.min.js:216:65)
    at Th (/node_modules/react-dom/cjs/react-dom.production.min.js:222:322)
    at Zh (/node_modules/react-dom/cjs/react-dom.production.min.js:228:14)
    at eval (/node_modules/react-dom/cjs/react-dom.production.min.js:258:268)
    at Object.exports.unstable_runWithPriority (/node_modules/scheduler/cjs/scheduler.production.min.js:26:163)
    at Fi (/node_modules/react-dom/cjs/react-dom.production.min.js:258:203)
    at Di (/node_modules/react-dom/cjs/react-dom.production.min.js:257:383)
    at Yh (/node_modules/react-dom/cjs/react-dom.production.min.js:256:144)
    at Ii (/node_modules/react-dom/cjs/react-dom.production.min.js:259:256)
    at Cd (/node_modules/react-dom/cjs/react-dom.production.min.js:93:207)`

**Comment by EnCz** [comment]
I found out when it happens! Reproduceable even on open.rocket.chat:

The problem appears when you click on a room or user **you already have opened** in the sidebar.

### Steps to reproduce*
1. Go to Directory **-> works**
2. Click User you don't already have IM with  **-> works**
3. Go to Directory **-> works**
4. Click on same User **-> works**
5. Go to Directory **-> white page**

* Note that this also applies to rooms

**Comment by EnCz** [comment]
@ggazzo is this gonna be worked on in 3.4 ? I hosted a rocket.chat server for a hackathon last weekend and with 100+ users who didn't know RC it was pretty irritating to explain why the directory doesn't work half of the time :/

**Comment by DeniseJansonFerreira** [comment]
I have the same problem. Is there a workaround for this? It usually happens on the Desktop App.

**Comment by EnCz** [comment]
> I have the same problem. Is there a workaround for this? It usually happens on the Desktop App.

Not really sadly. In the browser only a refresh helps to fix it. At least its tasked into 3.4.0 so let's hope it gets worked on :)

**Comment by EnCz** [comment]
@ggazzo / @tassoevan / @pierre-lehnen-rc 

Sorry that I'm asking again but is this gonna get worked on in 3.4.0 now ? It was even tasked in 3.3 after all.
I'm asking because its a really annoying bug that happens a lot of times in bigger instances and affects someting really central (directory).

**Comment by pierre-lehnen-rc** [comment]
Yes, it was fixed on 3.4.

**Comment by EnCz** [comment]
> Yes, it was fixed on 3.4.

Ah perfect, thanks :)

**Comment by geekgonecrazy** [comment]
yup this can no longer be reproduced. Closing
