### ISSUE TITLE
"Error dropping index" when upgrading to 3.2.1

### ISSUE THREAD

**Issue by kbojens** [RocketChat/Rocket.Chat#17557]
- Ubuntu 16.04.6 LTS
- mongodb-org-server 3.6.18
- nodejs 12.16.3-1nodesource1

This error happened on the update:

```
May 07 08:05:55  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Migrating from version 174 -> 188","time":{"$date":1588831555558},"level":"info"}
May 07 08:05:55  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 175","time":{"$date":1588831555562},"level":"info"}
May 07 08:05:55  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 176","time":{"$date":1588831555841},"level":"info"}
May 07 08:05:56  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 177","time":{"$date":1588831556046},"level":"info"}
May 07 08:05:56  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 178","time":{"$date":1588831556057},"level":"info"}
May 07 08:05:56  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 179","time":{"$date":1588831556074},"level":"info"}
May 07 08:05:56  nodejs-example[1646]: DM rooms schema migration 0/330
May 07 08:05:56  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 180","time":{"$date":1588831556525},"level":"info"}
May 07 08:05:56  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 182","time":{"$date":1588831556791},"level":"info"}
May 07 08:05:56  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 183","time":{"$date":1588831556805},"level":"info"}
May 07 08:05:56  nodejs-example[1646]: Error dropping index: users -> name_text_username_text_bio_text MongoError: index not found with name [name_text_username_text_bio_text]
May 07 08:05:56  nodejs-example[1646]:     at Connection.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:443:61)
May 07 08:05:56  nodejs-example[1646]:     at Connection.emit (events.js:210:5)
May 07 08:05:56  nodejs-example[1646]:     at Connection.EventEmitter.emit (domain.js:475:20)
May 07 08:05:56  nodejs-example[1646]:     at processMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:364:10)
May 07 08:05:56  nodejs-example[1646]:     at Socket.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:533:15)
May 07 08:05:56  nodejs-example[1646]:     at Socket.emit (events.js:210:5)
May 07 08:05:56  nodejs-example[1646]:     at Socket.EventEmitter.emit (domain.js:475:20)
May 07 08:05:56  nodejs-example[1646]:     at addChunk (_stream_readable.js:309:12)
May 07 08:05:56  nodejs-example[1646]:     at readableAddChunk (_stream_readable.js:290:11)
May 07 08:05:56  nodejs-example[1646]:     at Socket.Readable.push (_stream_readable.js:224:10)
May 07 08:05:56  nodejs-example[1646]:     at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
May 07 08:05:56  nodejs-example[1646]:   nIndexesWas: 38,
May 07 08:05:56  nodejs-example[1646]:   ok: 0,
May 07 08:05:56  nodejs-example[1646]:   errmsg: 'index not found with name [name_text_username_text_bio_text]',
May 07 08:05:56  nodejs-example[1646]:   code: 27,
May 07 08:05:56  nodejs-example[1646]:   codeName: 'IndexNotFound',
May 07 08:05:56  nodejs-example[1646]:   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 347, high_: 1588831556 },
May 07 08:05:56  nodejs-example[1646]:   '$clusterTime': {
May 07 08:05:56  nodejs-example[1646]:     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 347, high_: 1588831556 },
May 07 08:05:56  nodejs-example[1646]:     signature: { hash: [Binary], keyId: 0 }
May 07 08:05:56  nodejs-example[1646]:   },
May 07 08:05:56  nodejs-example[1646]:   name: 'MongoError',
May 07 08:05:56  nodejs-example[1646]:   [Symbol(mongoErrorContextSymbol)]: {}
May 07 08:05:56  nodejs-example[1646]: }
May 07 08:05:56  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 184","time":{"$date":1588831556848},"level":"info"}
May 07 08:05:56  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 185","time":{"$date":1588831556866},"level":"info"}
May 07 08:05:56  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 186","time":{"$date":1588831556891},"level":"info"}
May 07 08:05:56  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 187","time":{"$date":1588831556909},"level":"info"}
May 07 08:05:57  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 188","time":{"$date":1588831557007},"level":"info"}
May 07 08:05:57  nodejs-example[1646]: {"line":"120","file":"migrations.js","message":"Migrations: Finished migrating.","time":{"$date":1588831557029},"level":"info"}
```

**Comment by PRO100MIXA** [comment]
me too

> debian 10 
> Rocket.Chat Version: 3.3.3
> NodeJS Version: 12.18.0 - x64
> MongoDB Version: 4.2.7
> MongoDB Engine: wiredTiger
> Platform: linux

`{"line":"120","file":"migrations.js","message":"Migrations: Migrating from version 170 -> 191","time":{"$date":1592303415162},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 171","time":{"$date":1592303415163},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 172","time":{"$date":1592303415175},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 173","time":{"$date":1592303415183},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 174","time":{"$date":1592303415197},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 175","time":{"$date":1592303415215},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 176","time":{"$date":1592303415249},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 177","time":{"$date":1592303415254},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 178","time":{"$date":1592303415263},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 179","time":{"$date":1592303415269},"level":"info"}
DM rooms schema migration 0/2001
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 180","time":{"$date":1592303415705},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 182","time":{"$date":1592303415708},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 183","time":{"$date":1592303415710},"level":"info"}
Error dropping index: users -> name_text_username_text_bio_text MongoError: index not found with name [name_text_username_text_bio_text]
    at Connection.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:450:61)
    at Connection.emit (events.js:315:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at processMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:384:10)
    at Socket.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:553:15)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2145, high_: 1592303415 },
  ok: 0,
  errmsg: 'index not found with name [name_text_username_text_bio_text]',
  code: 27,
  codeName: 'IndexNotFound',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2145, high_: 1592303415 },
    signature: { hash: [Binary], keyId: 0 }
  },
  [Symbol(mongoErrorContextSymbol)]: {}
}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 184","time":{"$date":1592303415741},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 185","time":{"$date":1592303415744},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 186","time":{"$date":1592303415748},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 187","time":{"$date":1592303415750},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 188","time":{"$date":1592303415778},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 189","time":{"$date":1592303415781},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 190","time":{"$date":1592303415792},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 191","time":{"$date":1592303415799},"level":"info"}
{"line":"120","file":"migrations.js","message":"Migrations: Finished migrating.","time":{"$date":1592303415809},"level":"info"}`
