### ISSUE TITLE
Exception while invoking method 'channelsList'

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat#17721]
### Description:
Random exception logged into exceptions channel:
`Error: Match error: Expected string, got number`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.3
- Operating System: Debian 10
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.18

### Relevant logs:

```
Exception while invoking method 'channelsList'
Error: Match error: Expected string, got number
    at check (packages/check/match.js:36:17)
    at MethodInvocation.channelsList (server/methods/channelsList.js:14:3)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

**Comment by sampaiodiego** [comment]
Can you please provide  the API params you're using?

**Comment by dusatvoj** [comment]
It's just a random Exception shown in exceptions channel. We are using clients on all platforms. I'm not informed about 3rd party apps on this instance.
