### ISSUE TITLE
Exception while invoking method 'getUsersOfRoom' TypeError: Cannot read property 'trim' of null

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17735]
### Description:

Error appears in logs

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.17

### Relevant logs:

<details>

````

	May 25th 2020, 13:12:28.505	s-rc-srv-03	rocketchat_rocketchat_4_1	at server/methods/getUsersOfRoom.js:67:23
	May 25th 2020, 13:12:28.505	s-rc-srv-03	rocketchat_rocketchat_4_1	at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
	May 25th 2020, 13:12:28.504	s-rc-srv-03	rocketchat_rocketchat_4_1	Exception while invoking method 'getUsersOfRoom' TypeError: Cannot read property 'trim' of null
	May 25th 2020, 13:12:28.504	s-rc-srv-03	rocketchat_rocketchat_4_1	at findUsers (server/methods/getUsersOfRoom.js:32:13)
	May 25th 2020, 13:12:27.536	s-rc-srv-03	rocketchat_rocketchat_4_1	at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
	May 25th 2020, 13:12:27.534	s-rc-srv-03	rocketchat_rocketchat_4_1	at findUsers (server/methods/getUsersOfRoom.js:32:13)
	May 25th 2020, 13:12:27.534	s-rc-srv-03	rocketchat_rocketchat_4_1	Exception while invoking method 'getUsersOfRoom' TypeError: Cannot read property 'trim' of null
	May 25th 2020, 13:12:27.534	s-rc-srv-03	rocketchat_rocketchat_4_1	at server/methods/getUsersOfRoom.js:67:23
	May 25th 2020, 13:12:26.217	s-rc-srv-03	rocketchat_rocketchat_4_1	at server/methods/getUsersOfRoom.js:67:23
	May 25th 2020, 13:12:26.217	s-rc-srv-03	rocketchat_rocketchat_4_1	at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
	May 25th 2020, 13:12:26.216	s-rc-srv-03	rocketchat_rocketchat_4_1	at findUsers (server/methods/getUsersOfRoom.js:32:13)
	May 25th 2020, 13:12:26.216	s-rc-srv-03	rocketchat_rocketchat_4_1	Exception while invoking method 'getUsersOfRoom' TypeError: Cannot read property 'trim' of null
	May 25th 2020, 13:12:22.721	s-rc-srv-03	rocketchat_rocketchat_4_1	at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
	May 25th 2020, 13:12:22.720	s-rc-srv-03	rocketchat_rocketchat_4_1	at server/methods/getUsersOfRoom.js:67:23
	May 25th 2020, 13:12:22.719	s-rc-srv-03	rocketchat_rocketchat_4_1	at findUsers (server/methods/getUsersOfRoom.js:32:13)

````

</details>

**Comment by AmatorPhasma** [comment]
I also found this exception in the logs of my installation.

### Server Setup Information:
* Version of Rocket.Chat Server: 3.2.2
* Operating System: Debian
* Deployment Method: tar
* Number of Running Instances: 5
* DB Replicaset Oplog: Enabled
* NodeJS Version: 12.14.0
* MongoDB Version: 4.0.18
```
May 25 17:21:28 rocket RocketChat[9333]:     at /opt/rocket.chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
May 25 17:21:28 rocket RocketChat[9333]:     at server/methods/getUsersOfRoom.js:67:23
May 25 17:21:28 rocket RocketChat[9333]:     at findUsers (server/methods/getUsersOfRoom.js:32:13)
May 25 17:21:28 rocket RocketChat[9333]: Exception while invoking method 'getUsersOfRoom' TypeError: Cannot read property 'trim' of null

May 25 14:04:39 rocket RocketChat[9299]:     at /opt/rocket.chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
May 25 14:04:39 rocket RocketChat[9299]:     at server/methods/getUsersOfRoom.js:67:23
May 25 14:04:39 rocket RocketChat[9299]:     at findUsers (server/methods/getUsersOfRoom.js:32:13)
May 25 14:04:39 rocket RocketChat[9299]: Exception while invoking method 'getUsersOfRoom' TypeError: Cannot read property 'trim' of null

May 25 14:04:37 rocket RocketChat[9299]:     at /opt/rocket.chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
May 25 14:04:37 rocket RocketChat[9299]:     at server/methods/getUsersOfRoom.js:67:23
May 25 14:04:37 rocket RocketChat[9299]:     at findUsers (server/methods/getUsersOfRoom.js:32:13)
May 25 14:04:37 rocket RocketChat[9299]: Exception while invoking method 'getUsersOfRoom' TypeError: Cannot read property 'trim' of null
```
