### ISSUE TITLE
Failed_To_Load_Import_Data

### ISSUE THREAD

**Issue by majestique** [RocketChat/Rocket.Chat#17793]
### Description:

When importing latest slack export (just exported today), with latest rocket.chat (just installed today). We're getting this error: 
![image](https://user-images.githubusercontent.com/19336285/83375037-71e30200-a382-11ea-90b6-5dad7a451b2f.png)

With user import, it seems to work fine with the same file.

### Steps to reproduce:

1. Go to: /admin/import/prepare/slack
2. Import

### Actual behavior:

![image](https://user-images.githubusercontent.com/19336285/83375086-9ccd5600-a382-11ea-98dc-1a153f91e6df.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.11
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.17.0
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Latest chrome
- Operating System: Win10

**Comment by Aeroxander** [comment]
Dealing with the same error

**Comment by bbrauns** [comment]
same as here: https://github.com/RocketChat/Rocket.Chat/issues/17364

**Comment by TemaSM** [comment]
Facing slack importer issue too:
```
Rocket.Chat Version: 3.3.0
NodeJS Version: 12.16.1 - x64
MongoDB Version: 4.0.18
MongoDB Engine: wiredTiger
Platform: linux
ReplicaSet OpLog: Enabled
Commit Hash: a987295718
Commit Branch: HEAD
```
```javascript
Slack Importer ➔ info 130 messages imported
server.js:204 Slack Importer ➔ error TypeError: Cannot read property 'get' of undefined
    at SlackImporter._importMpims (app/importer-slack/server/importer.js:637:29)
    at app/importer-slack/server/importer.js:838:10
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/meteor.js:550:25
    at runWithEnvironment (packages/meteor.js:1286:24)
Setting default file store to GridFS
```
https://github.com/RocketChat/Rocket.Chat/blob/2abe15d097aa842de98fbf0f2582185d0d549f38/app/importer-slack/server/importer.js#L838
https://github.com/RocketChat/Rocket.Chat/blob/2abe15d097aa842de98fbf0f2582185d0d549f38/app/importer-slack/server/importer.js#L637

Probably produced by this: https://github.com/RocketChat/Rocket.Chat/commit/f6d11e20972a513b1795c26cedd3d7cd8b7005b6

**Comment by TemaSM** [comment]
Another Slack's importer issue: https://github.com/RocketChat/Rocket.Chat/issues/17855

**Comment by TemaSM** [comment]
Up 🔥
