### ISSUE TITLE
[Federation] Channels cannot be federated error when add federated user to public channel

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17794]
### Description:

I see error in logs `Channels cannot be federated` when add federated user to public channel despite green popup message that adding successful
@alansikora please take a look

### Steps to reproduce:

1. Search for federated user in public channel member list
2. Add federated user to public channel
3. See message that adding was successful but error in logs

### Expected behavior:

Federated users should be added to public channels

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/83375667-3e32c700-a3d8-11ea-8ac9-6020bbf6762d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.17

### Relevant logs:

````

at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
at app/federation/server/hooks/afterAddedToRoom.js:30:10
server.js:204 Federation ➔ client.error afterAddedToRoom => Could not add user: Error: Channels cannot be federated

````

**Comment by ankar84** [comment]
@alansikora in [current docs](https://github.com/RocketChat/docs/blob/c7051fc28e25864709bf8f1d4d80905526bca63d/guides/administrator-guides/federation.md#features) we can see, that:
#Features
##Current
- Invite users from remote servers
- Direct chats between servers
- **Public**, private and broadcast rooms with remote users from any number of servers
- Read receipts, notifications and alerts distributed to remote servers
- Mute/Unmute remote users
- Share files among servers
##Confirmed Next Features
- Encrypted rooms
- Whitelist servers to communicate with
- Better federation set-up process, with helpers to validate the configuration

But we now get error `Federation ➔ client.error afterAddedToRoom => Could not add user: Error: Channels cannot be federate` for some reason.

**Comment by ankar84** [comment]
Issue is still in place

**Comment by alansikora** [comment]
Can you please update to version `3.6.3` and circle back?

**Comment by ankar84** [comment]
> Can you please update to version `3.6.3` and circle back?

@alansikora still an issue at 3.6.3

```
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
server.js:204 Federation ➔ client.error afterAddedToRoom => Could not add user: Error: Channels cannot be federated
at app/federation/server/hooks/afterAddedToRoom.js:30:10
```

**Comment by EnCz** [comment]
Can reproduce this issue

**Comment by pierreozoux** [comment]
The piece of code is [here](https://github.com/RocketChat/Rocket.Chat/blob/18488e84f87485b053b51b3ca2df86c0a3337f14/app/federation/server/functions/helpers.js#L14)

We discussed about it in the chat the answer was:
```
Currently, safety reasons. Avoid unwanted people from another server to join your channel. We plan on having a configuration regarding that in the future!
```

I'll update documentation to reflect current reality.

**Comment by ankar84** [comment]
In recent 4.6.3 I can add federated user to publics channel, but that channel not appears in sidebar of federated user.
