### ISSUE TITLE
Custom OAuth not working Correctly (Logging into WP dashboard but not redirecting to RC)

### ISSUE THREAD

**Issue by ashleyruchi** [RocketChat/Rocket.Chat#17795]
**Below is the error i am getting in RC logs:**

Exception while invoking method 'login' Error: Service data for service ontheleveltrading must include id at AccountsServer.updateOrCreateUserFromExternalService (packages/accounts-base/accounts_server.js:1187:13
at AccountsServer.Accounts.updateOrCreateUserFromExternalService (app/custom-oauth/server/custom_oauth_server.js:423:47
at AccountsServer.Accounts.updateOrCreateUserFromExternalService (server/configuration/accounts_meld.js:52:52
at MethodInvocation.<anonymous> (packages/accounts-oauth/oauth_server.js:55:21
at packages/accounts-base/accounts_server.js:460:31 at tryLoginMethod (packages/accounts-base/accounts_server.js:1289:14
at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22
at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35
at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12
at packages/ddp-server/livedata_server.js:719:19 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js🔢12
at packages/ddp-server/livedata_server.js:717:46 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js🔢12
at packages/ddp-server/livedata_server.js:715:46 at new Promise (<anonymous>
at Session.method (packages/ddp-server/livedata_server.js:689:23
at packages/ddp-server/livedata_server.js:559:43

**Wordpress Console Error-**
{"isClientSafe":true,"error":500,"reason":"Internal server error","message":"Internal server error [500]","errorType":"Meteor.Error"}

Rocket.Chat 3.0.0
OS: CentOS 7.6
Mongodb 4.0.9
NodeJS 12.14.0

I followed this document for set up https://docs.rocket.chat/administrator-guides/authentication/wordpress

**Comment by ZelleAP** [comment]
I have the same issue with Rocket.Chat 2.4.11

**Comment by ashleyruchi** [comment]
If you using a plugin for this, then its a plugin issue i was using the Miniorange plugin so just contacted the support team and they were like go for the premium one for this. I did the same and issue resolved. So if you using the same plugin then go for the paid one.
