### ISSUE TITLE
Slack importer: MongoError: cursor id not found

### ISSUE THREAD

**Issue by TemaSM** [RocketChat/Rocket.Chat#17855]
### Description:

Error while importing Slack's file with massive amount of messages (about 250k) after 30-40 minutes of processing import.
This issue known since February of 2020, but reported only now.

<details>
  <summary>See exception stacktrace</summary>
  
  ```javascript
Slack Importer ➔ info 92601 messages imported
Slack Importer ➔ info 92602 messages imported
server.js:204 Slack Importer ➔ error MongoError: cursor id 432942697486 not found
    at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:450:61)
    at Connection.emit (events.js:311:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at processMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:384:10)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:553:15)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at packages/mongo/mongo_driver.js:1073:14
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1122:38)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1136:22)
    at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
    at DDPCommon.MethodInvocation.<anonymous> (app/importer-slack/server/importer.js:784:18)
    at packages/dispatch_run-as-user.js:211:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
    at SlackImporter._importMessages (app/importer-slack/server/importer.js:783:11)
    at app/importer-slack/server/importer.js:888:10
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/meteor.js:550:25
    at runWithEnvironment (packages/meteor.js:1286:24) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 10, high_: 1591416955 },
  ok: 0,
  errmsg: 'cursor id 432942697486 not found',
  code: 43,
  codeName: 'CursorNotFound',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 10, high_: 1591416955 },
    signature: { hash: [Binary], keyId: [Long] }
  },
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: { isGetMore: true }
}
```
  
</details>

### Steps to reproduce:

1. Go to Import tab
2. Choose Slack as import, upload file or type in URL to this file
3. Start import
3. Select what to import (I've selected everything)
4. Wait about 30-40 minutes (92k messages imported OK), watching progress of import
5. Boom, exception occurred

### Expected behavior:

Importing Slack's file with big amount of messages (> 50k) should complete successfully 

### Actual behavior:

Stacktrace:
```javascript
Slack Importer ➔ info 92601 messages imported
Slack Importer ➔ info 92602 messages imported
server.js:204 Slack Importer ➔ error MongoError: cursor id 432942697486 not found
    at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:450:61)
    at Connection.emit (events.js:311:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at processMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:384:10)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:553:15)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at packages/mongo/mongo_driver.js:1073:14
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1122:38)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1136:22)
    at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
    at DDPCommon.MethodInvocation.<anonymous> (app/importer-slack/server/importer.js:784:18)
    at packages/dispatch_run-as-user.js:211:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
    at SlackImporter._importMessages (app/importer-slack/server/importer.js:783:11)
    at app/importer-slack/server/importer.js:888:10
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/meteor.js:550:25
    at runWithEnvironment (packages/meteor.js:1286:24) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 10, high_: 1591416955 },
  ok: 0,
  errmsg: 'cursor id 432942697486 not found',
  code: 43,
  codeName: 'CursorNotFound',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 10, high_: 1591416955 },
    signature: { hash: [Binary], keyId: [Long] }
  },
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: { isGetMore: true }
}
```

### Server Setup Information:

Rocket.Chat Version: `3.3.0`
NodeJS Version: `12.16.1 - x64`
MongoDB Version: `4.0.18`
MongoDB Engine: wiredTiger
Platform: linux
ReplicaSet OpLog: Enabled
Commit Hash: a987295718
Commit Branch: HEAD

### Client Setup Information

- Browser: `Chrome 83.0.4103.61 (x64)`
- Operating System: `Windows 10 Build 2004 x64`

### Additional context

Probably related to:
https://docs.mongodb.com/manual/reference/method/cursor.noCursorTimeout/
https://stackoverflow.com/questions/28275628/where-to-specify-nocursortimeout-option-using-nodejs-mongodb-driver/35903698

**Comment by TemaSM** [comment]
Up 🔥

**Comment by bellegarde-c** [comment]
Similar issue with LDAP importer.

```
oct. 31 18:14:24 srv-rocket rocketchat[106]:   name: 'MongoError'
oct. 31 18:14:24 srv-rocket rocketchat[106]:   },
oct. 31 18:14:24 srv-rocket rocketchat[106]:     signature: { hash: [Binary], keyId: 0 }
oct. 31 18:14:24 srv-rocket rocketchat[106]:     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 14, high_: 1604164463 },
oct. 31 18:14:24 srv-rocket rocketchat[106]:   '$clusterTime': {
oct. 31 18:14:24 srv-rocket rocketchat[106]:   codeName: 'CursorNotFound',
oct. 31 18:14:24 srv-rocket rocketchat[106]:   code: 43,
oct. 31 18:14:24 srv-rocket rocketchat[106]:   ok: 0,
oct. 31 18:14:24 srv-rocket rocketchat[106]:   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 14, high_: 1604164463 },
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at packages/ddp-server/livedata_server.js:559:43 {
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at new Promise (<anonymous>)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at packages/ddp-server/livedata_server.js:715:46
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at packages/ddp-server/livedata_server.js:717:46
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at packages/ddp-server/livedata_server.js:719:19
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at MethodInvocation.ldap_sync_now (app/ldap/server/syncUsers.js:24:3)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at sync (app/ldap/server/sync.js:574:10)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1136:22)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1122:38)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_serve
oct. 31 18:14:24 srv-rocket rocketchat[106]:  => awaited here:
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at packages/mongo/mongo_driver.js:1073:14
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/prom
oct. 31 18:14:24 srv-rocket rocketchat[106]:  => awaited here:
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Socket.Readable.push (_stream_readable.js:224:10)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at readableAddChunk (_stream_readable.js:290:11)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at addChunk (_stream_readable.js:309:12)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Socket.EventEmitter.emit (domain.js:475:20)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Socket.emit (events.js:210:5)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Socket.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/conn
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at processMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connecti
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Connection.EventEmitter.emit (domain.js:475:20)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Connection.emit (events.js:210:5)
oct. 31 18:14:24 srv-rocket rocketchat[106]:     at Connection.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/
oct. 31 18:14:24 srv-rocket rocketchat[106]: server.js:204 LDAPSync ➔ error MongoError: cursor id 56077432702619072 not found
```

**Comment by pierre-lehnen-rc** [comment]
Sorry nobody replied to this issue earlier, but the reported bug is already fixed on the current version of Rocket.Chat.
