### ISSUE TITLE
LDAP does not sync all users

### ISSUE THREAD

**Issue by Rhywden** [RocketChat/Rocket.Chat#17896]
### Steps to reproduce:

1. Set up LDAP connection to an OpenLDAP server
2. Sync manually
3. Set maximum result size to 2000
3. Only get ~1255 users instead of 1829

### Expected behavior:

That I'll find all 1829 users

### Actual behavior:

I only get about 1255 users. The logs yield the following two error messages concerning LDAP. The first one is present after every user
```
I20200612-20:41:34.030(2) Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event. 
I20200612-20:41:34.222(2) LDAPSync ➔ info Syncing user data 
I20200612-20:41:34.223(2) LDAPSync ➔ debug user { email: 'foo.bar@baz', _id: 'M27EscHjCdaMno2pz' } 
I20200612-20:41:34.223(2) LDAPSync ➔ debug ldapUser undefined 
I20200612-20:41:34.224(2) TemplateVarHandler ➔ debug template found. replacing values 
I20200612-20:41:34.224(2) TemplateVarHandler ➔ debug replacing template var: #{givenName} with value: Foo 
I20200612-20:41:34.224(2) TemplateVarHandler ➔ debug replacing template var: #{sn} with value: Bar 
I20200612-20:41:34.225(2) LDAPSync ➔ debug user.name changed to: Foo Bar 
**I20200612-20:41:34.226(2) server.js:204 LDAPSync ➔ error Unexpected error : Unexpected token } in JSON at position 103** 
I20200612-20:41:34.226(2) LDAPSync ➔ debug not syncing groups to channels
```
And this error I get directly after a manual sync:
```
server.js:204 LDAP ➔ Search.error LDAPError [ProtocolError]: paged results cookie is invalid     
at messageCallback (/var/www/rocket.chat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)     
at Parser.onMessage (/var/www/rocket.chat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)     
at Parser.emit (events.js:210:5)     
at Parser.EventEmitter.emit (domain.js:475:20)     
at Parser.write (/var/www/rocket.chat/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)     at Socket.onData (/var/www/rocket.chat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)     
at Socket.emit (events.js:210:5)     
at Socket.EventEmitter.emit (domain.js:475:20)     
at addChunk (_stream_readable.js:309:12)     
at readableAddChunk (_stream_readable.js:290:11)     
at Socket.Readable.push (_stream_readable.js:224:10)     
at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {   lde_message: 'paged results cookie is invalid',   lde_dn: null }
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
- Operating System: Ubuntu 20.04
- Deployment Method: Manual
- Number of Running Instances: 1
- DB Replicaset Oplog: Active
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.18

If I use http://ldapjs.org/ and connect to our local LDAP using this code:

```
import { createClient } from 'ldapjs';

let client = createClient({
  url: 'ldap://192.168.2.15'
});

getUser = () => {
    let opts = {
      paged: true,
      scope: 'sub'
    }
    client.search('ou=users,dc=schule,dc=local', opts, (err, res) => {
      let i = 0;
      res.on('searchEntry', entry => {
        i++;
      })
      res.on('page', result => {
        console.log('page end');
      });
      res.on('error', resErr => {
        console.log(i);
        console.log(resErr);
      });
      res.on('end', result => {
        console.log('done ' + i);
      });
    })
  }
```
then I do indeed get the proper amount of users (1829)

**Comment by Rhywden** [comment]
Okay, I just set the size limits to ludicrous heights ("page size for search" is set to 2000 and "maximum results" is set to 4000).

Now I don't see the latter error anymore (the one about the invalid cookie) and I get more users - but only 1505 of them. That's still 324 short by my count.
