### ISSUE TITLE
Log Errors - Exception in defer callback - Error: self signed certificate

### ISSUE THREAD

**Issue by tars21** [RocketChat/Rocket.Chat#17986]
### Description:

The instance itself is up, running and working. But I have log errors minute-by-minute regarding a self signed certificate.
The webserver (haproxy) running in front of Rocket.Chat has a valid Let's Encrypt certificate.

### Steps to reproduce:

1.` journalctl -al -u rocketchat\* `

### Expected behavior:

Normal log behaviour

### Actual behavior:

The log is full of following messages (around every minute):
```
Jun 22 08:50:00 chat RocketChat[20742]: Error: ENOENT: no such file or directory, open '/tmp/userData/yxpgy4FYavxyyZJn7/user.html'
Jun 22 08:50:00 chat RocketChat[20742]:     at Object.openSync (fs.js:458:3)
Jun 22 08:50:00 chat RocketChat[20742]:     at Object.writeFileSync (fs.js:1355:35)
Jun 22 08:50:00 chat RocketChat[20742]:     at startFile (app/user-data-download/server/cronProcessDownloads.js:28:5)
Jun 22 08:50:00 chat RocketChat[20742]:     at generateUserFile (app/user-data-download/server/cronProcessDownloads.js:444:2)
Jun 22 08:50:00 chat RocketChat[20742]:     at app/user-data-download/server/cronProcessDownloads.js:503:4
Jun 22 08:50:00 chat RocketChat[20742]:     at /srv/rocketchat-program/rocket.chat-3.3.3/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
Jun 22 08:50:00 chat RocketChat[20742]:   errno: -2,
Jun 22 08:50:00 chat RocketChat[20742]:   syscall: 'open',
Jun 22 08:50:00 chat RocketChat[20742]:   code: 'ENOENT',
Jun 22 08:50:00 chat RocketChat[20742]:   path: '/tmp/userData/yxpgy4FYavxyyZJn7/user.html'
Jun 22 08:50:00 chat RocketChat[20742]: }
Jun 22 08:50:27 chat RocketChat[20742]: Exception in defer callback: Error: self signed certificate
Jun 22 08:50:27 chat RocketChat[20742]:     at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
Jun 22 08:50:27 chat RocketChat[20742]:     at TLSSocket.emit (events.js:315:20)
Jun 22 08:50:27 chat RocketChat[20742]:     at TLSSocket.EventEmitter.emit (domain.js:482:12)
Jun 22 08:50:27 chat RocketChat[20742]:     at TLSSocket._finishInit (_tls_wrap.js:936:8)
Jun 22 08:50:27 chat RocketChat[20742]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
Jun 22 08:50:27 chat RocketChat[20742]:   code: 'ESOCKET',
Jun 22 08:50:27 chat RocketChat[20742]:   command: 'CONN'
Jun 22 08:50:27 chat RocketChat[20742]: }
Jun 22 08:50:32 chat RocketChat[20516]: TypeError: Cannot read property 'authRequired' of undefined
Jun 22 08:50:32 chat RocketChat[20516]:     at Route.share.Route.Route._authAccepted (packages/nimble_restivus/lib/route.coffee:181:17)
Jun 22 08:50:32 chat RocketChat[20516]:     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:147:13)
Jun 22 08:50:32 chat RocketChat[20516]:     at packages/nimble_restivus/lib/route.coffee:59:33
Jun 22 08:50:32 chat RocketChat[20516]:     at packages/simple_json-routes.js:98:9
Jun 22 08:51:09 chat RocketChat[20516]: Exception in defer callback: Error: self signed certificate
Jun 22 08:51:09 chat RocketChat[20516]:     at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
Jun 22 08:51:09 chat RocketChat[20516]:     at TLSSocket.emit (events.js:315:20)
Jun 22 08:51:09 chat RocketChat[20516]:     at TLSSocket.EventEmitter.emit (domain.js:482:12)
Jun 22 08:51:09 chat RocketChat[20516]:     at TLSSocket._finishInit (_tls_wrap.js:936:8)
Jun 22 08:51:09 chat RocketChat[20516]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
Jun 22 08:51:09 chat RocketChat[20516]:   code: 'ESOCKET',
Jun 22 08:51:09 chat RocketChat[20516]:   command: 'CONN'
Jun 22 08:51:09 chat RocketChat[20516]: }
Jun 22 08:51:27 chat RocketChat[20740]: Exception in defer callback: Error: self signed certificate
Jun 22 08:51:27 chat RocketChat[20740]:     at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
Jun 22 08:51:27 chat RocketChat[20740]:     at TLSSocket.emit (events.js:315:20)
Jun 22 08:51:27 chat RocketChat[20740]:     at TLSSocket.EventEmitter.emit (domain.js:482:12)
Jun 22 08:51:27 chat RocketChat[20740]:     at TLSSocket._finishInit (_tls_wrap.js:936:8)
Jun 22 08:51:27 chat RocketChat[20740]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
Jun 22 08:51:27 chat RocketChat[20740]:   code: 'ESOCKET',
Jun 22 08:51:27 chat RocketChat[20740]:   command: 'CONN'
Jun 22 08:51:27 chat RocketChat[20740]: }
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3 (same at 3.2.1)
- Operating System: Debian 10
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.1
- MongoDB Version: 3.6.18

### Client Setup Information

-

### Additional context

What is causing this error? Even the path reference to `/tmp/userData/...` looks curious. 
The LDAP connection wasn't changed for years and is working, the option "Reject Unauthorized" is enabled and  "Test connection" is working, too.

### Relevant logs:

-

**Comment by pierre-lehnen-rc** [comment]
The first error is unrelated to the others, it is triggered by the cronjob that exports user's data when they request to download it from the server.

**Comment by IVIJL** [comment]
We having same issue, any tips how to fix it ?
