### ISSUE TITLE
Error in rc-apps create:  Cannot find name 'Buffer'

### ISSUE THREAD

**Issue by col-panic** [RocketChat/Rocket.Chat#18012]
### Description:

Creating a new app according to https://docs.rocket.chat/apps-development/getting-started leads to an error.

### Steps to reproduce:

1. `rc-apps create`
2. Enter configuration data and wait, to see the following output

```
›   Error: /Users/marco/git/sampleapp/node_modules/@rocket.chat/apps-engine/definition/accessors/IUploadRead.d.ts (4,40): 
 ›     Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i @types/node`.
 ›   Error: /Users/marco/git/sampleapp/node_modules/@rocket.chat/apps-engine/definition/accessors/IUploadRead.d.ts (5,41): 
 ›     Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i @types/node`.
Creating a Rocket.Chat App in /Users/marco/git/sampleapp... !
Error: invalid.
    at Create.run (/usr/local/lib/node_modules/@rocket.chat/apps-cli/lib/commands/create.js:52:19)
    at async Create._run (/usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (/usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/@oclif/command/lib/command.js:43:20)
```

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: OS X 10.14.6
- Deployment Method:none
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: @rocket.chat/apps-cli/1.6.0 darwin-x64 node-v14.4.0
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by imhazige** [comment]
same issue here

**Comment by imhazige** [comment]
the temp solution is: npm install --save-dev @types/node at first

**Comment by col-panic** [comment]
That does fullfill the development dependency. Is the app then deployable to the server? Resp. how to satisfy
such dependencies on server site?

**Comment by d-gubert** [comment]
Good news is the error is fixed in our current development version of the CLI :P It will be published in a few days
