### ISSUE TITLE
Docker: linked mongodb container must be called "db"

### ISSUE THREAD

**Issue by brightbulbnz** [RocketChat/Rocket.Chat#1805]
From the docker install instructions:

docker run --name db -d mongo --smallfiles
docker run --name rocketchat --link db -d rocket.chat

Changing the name to anything other than "db" causes the following error:
```
2016-01-05T05:08:06.189862600Z
2016-01-05T05:08:06.190282600Z /bundle/programs/server/node_modules/fibers/future.js:278
2016-01-05T05:08:06.190704300Z throw(ex);
2016-01-05T05:08:06.190735500Z ^
2016-01-05T05:08:06.438693700Z Error: failed to connect to [db:27017]
2016-01-05T05:08:06.438747900Z at Object.Future.wait (/bundle/programs/server/node_modules/fibers/future.js:398:15)
2016-01-05T05:08:06.438758900Z at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
2016-01-05T05:08:06.438768800Z at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
2016-01-05T05:08:06.438781000Z at Object. (packages/mongo/remote_collection_driver.js:38:1)
2016-01-05T05:08:06.438791400Z at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
2016-01-05T05:08:06.438800900Z at new Mongo.Collection (packages/mongo/collection.js:102:1)
2016-01-05T05:08:06.438810000Z at AccountsServer.AccountsCommon (accounts_common.js:23:18)
2016-01-05T05:08:06.438818700Z at new AccountsServer (accounts_server.js:16:5)
2016-01-05T05:08:06.438827200Z at Package (globals_server.js:5:12)
2016-01-05T05:08:06.438835700Z at /bundle/programs/server/packages/accounts-base.js:1814:4
2016-01-05T05:08:06.438844400Z - - - - -
2016-01-05T05:08:06.438853300Z at [object Object]. (/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
2016-01-05T05:08:06.438862600Z at [object Object].emit (events.js:106:17)
2016-01-05T05:08:06.438871100Z at [object Object]. (/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
2016-01-05T05:08:06.438880200Z at [object Object].emit (events.js:98:17)
2016-01-05T05:08:06.438897200Z at Socket. (/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
2016-01-05T05:08:06.438906500Z at Socket.emit (events.js:95:17)
2016-01-05T05:08:06.438914900Z at net.js:834:16
2016-01-05T05:08:06.438925500Z at process._tickCallback (node.js:448:13) 
```

**Comment by sampaiodiego** [comment]
you still can link from a different mongodb container name to db, like this:

`docker run --name rocketchat --link YOURMONGODBNAME:db -d rocket.chat`

**Comment by brightbulbnz** [comment]
Works! Thank you.
