### ISSUE TITLE
Admin pages are blank on 3.4.1 (clean manual installation on 18.04)

### ISSUE THREAD

**Issue by TomaszDom** [RocketChat/Rocket.Chat#18203]
### Description:

Admin pages are blank. At first I thought this was an issue with upgrading from 3.3.x, but clean install behaves exactly the same.

`lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ +--------------------------------------------------+
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |                  SERVER RUNNING                  |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ +--------------------------------------------------+
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |                                                  |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |  Rocket.Chat Version: 3.4.1                      |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |       NodeJS Version: 12.16.1 - x64              |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |      MongoDB Version: 4.0.16                     |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |       MongoDB Engine: wiredTiger                 |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |             Platform: linux                      |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |         Process Port: 3000                       |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |             Site URL: https://chat.akoportal.pl  |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |     ReplicaSet OpLog: Enabled                    |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |          Commit Hash: 21157c0c4f                 |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |        Commit Branch: HEAD                       |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ |                                                  |
lip 07 15:30:51 srv-gw rocketchat[38181]: ➔ +--------------------------------------------------+
lip 07 15:36:36 srv-gw rocketchat[38181]: Error: ENOENT: no such file or directory, open '/opt/Rocket.Chat/programs/web.browser/dynamic/node_modules/@babel/runtime/helpers/taggedTemplateLiteralLoose.js'
lip 07 15:36:36 srv-gw rocketchat[38181]:     at Object.openSync (fs.js:457:3)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at readFileSync (fs.js:359:35)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at read (packages/dynamic-import.js:205:29)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at walk (packages/dynamic-import.js:156:14)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at packages/dynamic-import.js:163:22
lip 07 15:36:36 srv-gw rocketchat[38181]:     at Array.forEach (<anonymous>)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at walk (packages/dynamic-import.js:161:23)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at packages/dynamic-import.js:163:22
lip 07 15:36:36 srv-gw rocketchat[38181]:     at Array.forEach (<anonymous>)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at walk (packages/dynamic-import.js:161:23)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at packages/dynamic-import.js:163:22
lip 07 15:36:36 srv-gw rocketchat[38181]:     at Array.forEach (<anonymous>)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at walk (packages/dynamic-import.js:161:23)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at packages/dynamic-import.js:163:22
lip 07 15:36:36 srv-gw rocketchat[38181]:     at Array.forEach (<anonymous>)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at walk (packages/dynamic-import.js:161:23)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at packages/dynamic-import.js:163:22
lip 07 15:36:36 srv-gw rocketchat[38181]:     at Array.forEach (<anonymous>)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at walk (packages/dynamic-import.js:161:23)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at readTree (packages/dynamic-import.js:184:10)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at IncomingMessage.<anonymous> (packages/dynamic-import.js:100:37)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at IncomingMessage.emit (events.js:323:22)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at IncomingMessage.EventEmitter.emit (domain.js:482:12)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at endReadableNT (_stream_readable.js:1204:12)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
lip 07 15:36:36 srv-gw rocketchat[38181]: Error: ENOENT: no such file or directory, open '/opt/Rocket.Chat/programs/web.browser/dynamic/node_modules/@rocket.chat/css-in-js/dist/index.js'
lip 07 15:36:36 srv-gw rocketchat[38181]:     at Object.openSync (fs.js:457:3)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at readFileSync (fs.js:359:35)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at read (packages/dynamic-import.js:205:29)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at walk (packages/dynamic-import.js:156:14)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at packages/dynamic-import.js:163:22
lip 07 15:36:36 srv-gw rocketchat[38181]:     at Array.forEach (<anonymous>)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at walk (packages/dynamic-import.js:161:23)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at packages/dynamic-import.js:163:22
lip 07 15:36:36 srv-gw rocketchat[38181]:     at Array.forEach (<anonymous>)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at walk (packages/dynamic-import.js:161:23)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at packages/dynamic-import.js:163:22
lip 07 15:36:36 srv-gw rocketchat[38181]:     at Array.forEach (<anonymous>)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at walk (packages/dynamic-import.js:161:23)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at packages/dynamic-import.js:163:22
lip 07 15:36:36 srv-gw rocketchat[38181]:     at Array.forEach (<anonymous>)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at walk (packages/dynamic-import.js:161:23)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at packages/dynamic-import.js:163:22
lip 07 15:36:36 srv-gw rocketchat[38181]:     at Array.forEach (<anonymous>)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at walk (packages/dynamic-import.js:161:23)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at readTree (packages/dynamic-import.js:184:10)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at IncomingMessage.<anonymous> (packages/dynamic-import.js:100:37)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at IncomingMessage.emit (events.js:323:22)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at IncomingMessage.EventEmitter.emit (domain.js:482:12)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at endReadableNT (_stream_readable.js:1204:12)
lip 07 15:36:36 srv-gw rocketchat[38181]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)`

### Steps to reproduce:

1. Follow official manual installation instructions with Nginx as reverse proxy
2. Fix stuck login following https://github.com/RocketChat/Rocket.Chat/issues/18189#issuecomment-654805164
3. Register workspace, try to access Admin pages.

### Expected behavior:

Admin pages accessible.

### Actual behavior:

Blank admin pages

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.1
- Operating System: Ubuntu 18.04
- Deployment Method: tar
- Number of Running Instances: `
- DB Replicaset Oplog: true
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by TomaszDom** [comment]
![obraz](https://user-images.githubusercontent.com/9348532/86791347-bc365d80-c069-11ea-845a-96bc71b20662.png)

**Comment by TomaszDom** [comment]
![obraz](https://user-images.githubusercontent.com/9348532/86791693-16cfb980-c06a-11ea-87cc-fe4e72efa841.png)

**Comment by rodrigok** [comment]
@TomaszDom did you try to remove the npm packages and reinstall?
```
cd bundle/programs/server
rm -rf node_modules && npm i
```

**Comment by TomaszDom** [comment]
It doesn't make any difference. I'm attaching the log.
[npm_install.txt](https://github.com/RocketChat/Rocket.Chat/files/4888602/npm_install.txt)

**Comment by TomaszDom** [comment]
I can easily reproduce this on a fresh Ubuntu 18.04 server installation. These files do not exist.
```
/opt/Rocket.Chat/programs/web.browser/dynamic/node_modules/@babel/runtime/helpers/taggedTemplateLiteralLoose.js
/opt/Rocket.Chat/programs/web.browser/dynamic/node_modules/@rocket.chat/css-in-js/dist/index.js
```

**Comment by TomaszDom** [comment]
I have clean installed version 3.3.3 to check my process and it works correctly, so I don't think the issue is on my end.

**Comment by TomaszDom** [comment]
Same issue when upgrading from 3.3.3 to 3.5.0, although the log is empty, admin pages are blank.
