### ISSUE TITLE
SAML [Error]: Email already exists.

### ISSUE THREAD

**Issue by BarnumD** [RocketChat/Rocket.Chat#18242]
### Description:

I configured SAML on a new installation of Rocketchat.  There are no users except for the admin.  When I log into SAML, it bounces me back to the login page and I get a message saying `Email already exists`.

### Steps to reproduce:

1. setup SAML
2. Click on the button on the home screen for SAML login

### Expected behavior:

Log in.

### Actual behavior:

Email already exists

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.1
- Operating System:  Docker image
- Deployment Method: Azure Kubernetes Pod
- Number of Running Instances: 2
- DB Replicaset Oplog: rs0
- NodeJS Version: Unknown - see rocketchat:3.4.1 image.
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome 83.0.4103
- Operating System: Windows 10

### Additional context

"Overwrite user fullname (use idp attribute)" Checked
"Overwrite user mail (use idp attribute)" Checked
"User Data Field Map": {"username":"username", "email":"email", "name": "cn"}

### Relevant logs:

```
errorClass [Error]: Email already exists. [403]
    at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1103:15)
    at AccountsServer.<anonymous> (app/authentication/server/startup/index.js:238:28)
    at executeBound (/app/bundle/programs/server/npm/node_modules/underscore/underscore.js:762:67)
    at AccountsServer.bound [as insertUserDoc] (/app/bundle/programs/server/npm/node_modules/underscore/underscore.js:793:14)
    at Function.insertOrUpdateSAMLUser (app/meteor-accounts-saml/server/lib/SAML.ts:145:28)
    at MethodInvocation.<anonymous> (app/meteor-accounts-saml/server/loginHandler.ts:32:15)
    at packages/accounts-base/accounts_server.js:462:31
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1291:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:460:22)
    at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:31)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:388:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9 {
  isClientSafe: true,
  error: 403,
  reason: 'Email already exists.',
  details: undefined,
  message: 'Email already exists. [403]',
  errorType: 'Meteor.Error'
}
```

**Comment by pierre-lehnen-rc** [comment]
Can you enable the SAML debug log to check what email is logged with the parsed userDataMap?

**Comment by BarnumD** [comment]
For whatever reason, when I change the mapping to this the issue went away.  `{"username":"cn", "email":"email", "name": "name"}`
