### ISSUE TITLE
/account/ gives stack trace or server error

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#1834]
I was editing my own account, and to get back to the home page I tried to remove all but the domain from the browser address bar. However, I accidentally left on /account/ and got a full stack trace.

On  https://demo.rocket.chat/account/ all it gives is an internal server error message. On my own server, I got this:

OAuth2Error: Malformed auth header
    at OAuth2Error (/root/.meteor/packages/rocketchat_oauth2-server/.1.1.1.l8310p++os+web.browser+web.cordova/npm/node_modules/oauth2-server/lib/error.js:30:12)
    at Authorise.getBearerToken (/root/.meteor/packages/rocketchat_oauth2-server/.1.1.1.l8310p++os+web.browser+web.cordova/npm/node_modules/oauth2-server/lib/authorise.js:78:19)
    at run (/root/.meteor/packages/rocketchat_oauth2-server/.1.1.1.l8310p++os+web.browser+web.cordova/npm/node_modules/oauth2-server/lib/runner.js:15:14)
    at runner (/root/.meteor/packages/rocketchat_oauth2-server/.1.1.1.l8310p++os+web.browser+web.cordova/npm/node_modules/oauth2-server/lib/runner.js:19:5)
    at new Authorise (/root/.meteor/packages/rocketchat_oauth2-server/.1.1.1.l8310p++os+web.browser+web.cordova/npm/node_modules/oauth2-server/lib/authorise.js:45:3)
    at /root/.meteor/packages/rocketchat_oauth2-server/.1.1.1.l8310p++os+web.browser+web.cordova/npm/node_modules/oauth2-server/lib/oauth2server.js:70:12
    at Layer.handle [as handle_request] (/root/.meteor/packages/rocketchat_oauth2-server/.1.1.1.l8310p++os+web.browser+web.cordova/npm/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/.meteor/packages/rocketchat_oauth2-server/.1.1.1.l8310p++os+web.browser+web.cordova/npm/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/root/.meteor/packages/rocketchat_oauth2-server/.1.1.1.l8310p++os+web.browser+web.cordova/npm/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/.meteor/packages/rocketchat_oauth2-server/.1.1.1.l8310p++os+web.browser+web.cordova/npm/node_modules/express/lib/router/layer.js:95:5)

**Comment by bsdcon** [comment]
To me it seems that this consistently reproduces when trying to do another Oauth after an already interrupted Oauth authentication (e.g. In my case Google Oauth refused servicing the transaction due to private URL usage).

PS: I have seen the rocket.chat Mac OSX app crash for the same reason.

**Comment by marceloschmidt** [comment]
I'm not sure if this was fixed by someone already or not, but for me it correctly shows the account profile. Can you test again going to https://demo.rocket.chat/account/ ?
Thanks.

**Comment by sinteur** [comment]
Looks fixed on my server to. I'll close it - good work team!
