### ISSUE TITLE
RC 3.5.0 Error: Exception in callback of async function: Error: certificate has expired: 2017-06-01T15:36:54.000Z

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#18397]
### Description:

Rocketchat-3.5.0 does not start after upgrade. I get:

Exception in callback of async function: Error: certificate has expired: 2017-06-01T15:36:54.000Z
    at validateCredentials (/opt/rocketchat-3.5.0/programs/server/npm/node_modules/apn/lib/credentials/certificate/validate.js:12:11)
    at loadAndValidate (/opt/rocketchat-3.5.0/programs/server/npm/node_modules/apn/lib/credentials/certificate/prepare.js:20:5)
    at config (/opt/rocketchat-3.5.0/programs/server/npm/node_modules/apn/lib/config.js:49:22)
    at new Client (/opt/rocketchat-3.5.0/programs/server/npm/node_modules/apn/lib/client.js:11:19)
    at new Provider (/opt/rocketchat-3.5.0/programs/server/npm/node_modules/apn/lib/provider.js:12:19)
    at initAPN (app/push/server/apn.js:114:18)
    at PushClass.configure (app/push/server/push.js:50:4)
    at configurePush (server/lib/pushConfig.js:109:8)
    at Function.time (/opt/rocketchat-3.5.0/programs/server/profile.js:273:30)
    at /opt/rocketchat-3.5.0/programs/server/boot.js:415:15
    at /opt/rocketchat-3.5.0/programs/server/boot.js:465:7
    at Function.run (/opt/rocketchat-3.5.0/programs/server/profile.js:280:14)
    at /opt/rocketchat-3.5.0/programs/server/boot.js:463:13

Had to restore the backup.

### Steps to reproduce:

1. Update to 3.5.0 from 3.4.2
2. Start Rocketchat
3. Exception in rocketchat.log
4. No running Rocketchat

### Expected behavior:

Having 3.5.0 running

### Actual behavior:

Rocketchat throws an exception.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.0
- Operating System: linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.17.0
- MongoDB Version: 4.0.19

**Comment by himpierre** [comment]
Maybe this is related? 

https://stackoverflow.com/questions/62128611/nodejs-certificate-has-expired

**Comment by himpierre** [comment]
Hm. Seems Apple Push Notification releated.  Maybe the cert for APN is expired?

**Comment by himpierre** [comment]
After resetting den push notification settings to default everything works as expected.
