### ISSUE TITLE
Could not upgrade Rocket.Chat server version 3.4.2 to version 3.5.0, "Error in updated RocketChat server health check"

### ISSUE THREAD

**Issue by rzaSF** [RocketChat/Rocket.Chat#18423]
### Description:

Attempted to upgrade from Rocket.Chat server 3.4.2 to 3.5.0, which resulted in "Error in updated RocketChat server health check"

### Steps to reproduce:

1. Install Rocket.Chat server 3.4.2
2. Execute Rocket.Chat update i.e. `rocketchatctl update`

### Server Setup Information:

```
Jul 29 11:50:52 inst01 rocketchat[1365]: Using FileSystem for custom sounds storage
Jul 29 11:50:52 inst01 rocketchat[1365]: Using FileSystem for custom emoji storage
Jul 29 11:50:52 inst01 rocketchat[1365]: Loaded the Apps Framework and loaded a total of 4 Apps!
Jul 29 11:50:52 inst01 rocketchat[1365]: Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ System ➔ startup
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ +----------------------------------------------------+
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |                   SERVER RUNNING                   |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ +----------------------------------------------------+
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |                                                    |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |  Rocket.Chat Version: 3.4.2                        |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |       NodeJS Version: 12.17.0 - x64                |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |      MongoDB Version: 4.0.3                        |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |       MongoDB Engine: mmapv1                       |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |             Platform: linux                        |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |         Process Port: 3000                         |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |             Site URL: https://xxxxx.xxxxxxxxx.tld  |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |     ReplicaSet OpLog: Enabled                      |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |          Commit Hash: e5f93d3f5e                   |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |        Commit Branch: HEAD                         |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ |                                                    |
Jul 29 11:50:53 inst01 rocketchat[1365]: ➔ +----------------------------------------------------+
```

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Ubuntu 18.04.4 LTS
- Deployment Method: Digital Ocean droplet
- Number of Running Instances: 1
- DB Replicaset Oplog: (see above)
- NodeJS Version: (see above)
- MongoDB Version: (see above)

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

Server has always been updated using `rocketchatctl update`. This instance was initially deployed with Rocket.Chat 2.4.9 (Digital Ocean droplet default), and has been upgraded through multiple versions over time to 3.4.2.

### Relevant logs:

Performed `tail -f /var/log/syslog &` before running rocketchatctl update process.

```
root@inst01:~# rocketchatctl update
Updates could be risky, you can use the backup option # rocketchatctl backup, to create a backup of the rocketchat database first. Please check that you have enough space in your system to store the backup.
Current update available for RocketChat server: from 3.4.2 to 3.5.0commit.
Jul 29 11:51:22 inst01 systemd[1]: Stopping The Rocket.Chat server...
Jul 29 11:51:22 inst01 systemd[1]: Stopped The Rocket.Chat server.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132  100   132    0     0    970      0 --:--:-- --:--:-- --:--:--   970
100  158M  100  158M    0     0   145M      0  0:00:01  0:00:01 --:--:--  190M
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> fibers@4.0.3 install /tmp/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-72-glibc` exists; testing
Binary is fine; exiting
npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd meteor-dev-bundle@ node npm-rebuild.js (wd=/tmp/bundle/programs/server)
added 146 packages from 122 contributors and audited 147 packages in 5.323s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities



   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New patch version of npm available! 6.14.5 → 6.14.6       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.6   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

Jul 29 11:51:41 inst01 systemd[1]: Started The Rocket.Chat server.
Waiting up to 60 seconds for RocketChat server to be active ... 2
Waiting up to 60 seconds for RocketChat server to be active ... 4
Waiting up to 60 seconds for RocketChat server to be active ... 6
Waiting up to 60 seconds for RocketChat server to be active ... 8
Waiting up to 60 seconds for RocketChat server to be active ... 10
Waiting up to 60 seconds for RocketChat server to be active ... 12
Waiting up to 60 seconds for RocketChat server to be active ... 14
Waiting up to 60 seconds for RocketChat server to be active ... 16
Jul 29 11:51:59 inst01 rocketchat[1580]: Setting default file store to FileSystem
Waiting up to 60 seconds for RocketChat server to be active ... 18
Waiting up to 60 seconds for RocketChat server to be active ... 20
Waiting up to 60 seconds for RocketChat server to be active ... 22
Waiting up to 60 seconds for RocketChat server to be active ... 24
Jul 29 11:52:07 inst01 rocketchat[1580]: {"line":"120","file":"migrations.js","message":"Migrations: Migrating from version 197 -> 201","time":{"$date":1596023527050},"level":"info"}
Jul 29 11:52:07 inst01 rocketchat[1580]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 198","time":{"$date":1596023527054},"level":"info"}
Jul 29 11:52:07 inst01 rocketchat[1580]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 199","time":{"$date":1596023527117},"level":"info"}
Jul 29 11:52:07 inst01 rocketchat[1580]: Changing schema of User records, this may take a long time ...
Jul 29 11:52:07 inst01 rocketchat[1580]: Migrating 0/15
Jul 29 11:52:07 inst01 rocketchat[1580]: Changing schema of User records finished.
Jul 29 11:52:07 inst01 rocketchat[1580]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 200","time":{"$date":1596023527436},"level":"info"}
Jul 29 11:52:07 inst01 rocketchat[1580]: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 201","time":{"$date":1596023527447},"level":"info"}
Jul 29 11:52:07 inst01 rocketchat[1580]: {"line":"120","file":"migrations.js","message":"Migrations: Finished migrating.","time":{"$date":1596023527492},"level":"info"}
Waiting up to 60 seconds for RocketChat server to be active ... 26
Waiting up to 60 seconds for RocketChat server to be active ... 28
Waiting up to 60 seconds for RocketChat server to be active ... 30
Waiting up to 60 seconds for RocketChat server to be active ... 32
Jul 29 11:52:13 inst01 systemd[1]: Starting Cleanup of Temporary Directories...
Jul 29 11:52:13 inst01 systemd[1]: Started Cleanup of Temporary Directories.
Waiting up to 60 seconds for RocketChat server to be active ... 34
Jul 29 11:52:17 inst01 rocketchat[1580]: Not migrating, control is locked. Attempt 1/30. Trying again in 10 seconds.
Jul 29 11:52:17 inst01 rocketchat[1580]: {"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 201","time":{"$date":1596023537501},"level":"info"}
Waiting up to 60 seconds for RocketChat server to be active ... 36
Waiting up to 60 seconds for RocketChat server to be active ... 38
Waiting up to 60 seconds for RocketChat server to be active ... 40
Waiting up to 60 seconds for RocketChat server to be active ... 42
Waiting up to 60 seconds for RocketChat server to be active ... 44
Waiting up to 60 seconds for RocketChat server to be active ... 46
Waiting up to 60 seconds for RocketChat server to be active ... 48
Waiting up to 60 seconds for RocketChat server to be active ... 50
Waiting up to 60 seconds for RocketChat server to be active ... 52
Waiting up to 60 seconds for RocketChat server to be active ... 54
Waiting up to 60 seconds for RocketChat server to be active ... 56
Jul 29 11:52:39 inst01 rocketchat[1580]: Updating process.env.MAIL_URL
Jul 29 11:52:39 inst01 rocketchat[1580]: Loaded the Apps Framework and loaded a total of 4 Apps!
Jul 29 11:52:40 inst01 rocketchat[1580]: Using FileSystem for custom sounds storage
Jul 29 11:52:40 inst01 rocketchat[1580]: Using FileSystem for custom emoji storage
Waiting up to 60 seconds for RocketChat server to be active ... 58
Jul 29 11:52:40 inst01 rocketchat[1580]: Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Waiting up to 60 seconds for RocketChat server to be active ... 60
Jul 29 11:52:45 inst01 rocketchat[1580]: Exception from task [Error: ENOENT: no such file or directory, open '/opt/Rocket.Chat/programs/web.browser/head.html'] {
Jul 29 11:52:45 inst01 rocketchat[1580]:   errno: -2,
Jul 29 11:52:45 inst01 rocketchat[1580]:   code: 'ENOENT',
Jul 29 11:52:45 inst01 rocketchat[1580]:   syscall: 'open',
Jul 29 11:52:45 inst01 rocketchat[1580]:   path: '/opt/Rocket.Chat/programs/web.browser/head.html'
Jul 29 11:52:45 inst01 rocketchat[1580]: }
Jul 29 11:52:45 inst01 rocketchat[1580]: Exception in callback of async function: [Error: ENOENT: no such file or directory, open '/opt/Rocket.Chat/programs/web.browser/head.html'] {
Jul 29 11:52:45 inst01 rocketchat[1580]:   errno: -2,
Jul 29 11:52:45 inst01 rocketchat[1580]:   code: 'ENOENT',
Jul 29 11:52:45 inst01 rocketchat[1580]:   syscall: 'open',
Jul 29 11:52:45 inst01 rocketchat[1580]:   path: '/opt/Rocket.Chat/programs/web.browser/head.html'
Jul 29 11:52:45 inst01 rocketchat[1580]: }
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ System ➔ startup
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ +----------------------------------------------------+
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |                   SERVER RUNNING                   |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ +----------------------------------------------------+
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |                                                    |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |  Rocket.Chat Version: 3.5.0                        |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |       NodeJS Version: 12.17.0 - x64                |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |      MongoDB Version: 4.0.3                        |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |       MongoDB Engine: mmapv1                       |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |             Platform: linux                        |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |         Process Port: 3000                         |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |             Site URL: https://xxxxx.xxxxxxxxx.tld  |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |     ReplicaSet OpLog: Enabled                      |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |          Commit Hash: 72718532bc                   |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |        Commit Branch: HEAD                         |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ |                                                    |
Jul 29 11:52:45 inst01 rocketchat[1580]: ➔ +----------------------------------------------------+
Jul 29 11:52:45 inst01 systemd[1]: Stopping The Rocket.Chat server...
Error in updated RocketChat server health check, restoring backup.
root@inst01:~# Jul 29 11:52:45 inst01 systemd[1]: Stopped The Rocket.Chat server.
Jul 29 11:52:45 inst01 systemd[1]: Started The Rocket.Chat server.
Jul 29 11:53:03 inst01 rocketchat[2000]: Setting default file store to FileSystem

root@inst01:~# 
Jul 29 11:53:11 inst01 rocketchat[2000]: Exception in callback of async function: errorClass [Error]: [Can't find migration version 201]
Jul 29 11:53:11 inst01 rocketchat[2000]:     at Object.Migrations._findIndexByVersion (app/migrations/server/migrations.js:402:8)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at Object.Migrations._migrateTo (app/migrations/server/migrations.js:254:24)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at Object.Migrations.migrateTo (app/migrations/server/migrations.js:179:20)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at module (server/startup/migrations/xrun.js:6:13)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at Module.require (packages/modules-runtime.js:238:14)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at module (server/startup/migrations/index.js:1:4320)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at Module.require (packages/modules-runtime.js:238:14)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at module (server/main.js:1:201)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at Module.require (packages/modules-runtime.js:238:14)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at require (packages/modules-runtime.js:258:21)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at /opt/Rocket.Chat/programs/server/app/app.js:183489:15
Jul 29 11:53:11 inst01 rocketchat[2000]:     at /opt/Rocket.Chat/programs/server/boot.js:401:38
Jul 29 11:53:11 inst01 rocketchat[2000]:     at Array.forEach (<anonymous>)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at /opt/Rocket.Chat/programs/server/boot.js:226:21
Jul 29 11:53:11 inst01 rocketchat[2000]:     at /opt/Rocket.Chat/programs/server/boot.js:464:7
Jul 29 11:53:11 inst01 rocketchat[2000]:     at Function.run (/opt/Rocket.Chat/programs/server/profile.js:280:14)
Jul 29 11:53:11 inst01 rocketchat[2000]:     at /opt/Rocket.Chat/programs/server/boot.js:463:13 {
Jul 29 11:53:11 inst01 rocketchat[2000]:   isClientSafe: true,
Jul 29 11:53:11 inst01 rocketchat[2000]:   error: "Can't find migration version 201",
Jul 29 11:53:11 inst01 rocketchat[2000]:   reason: undefined,
Jul 29 11:53:11 inst01 rocketchat[2000]:   details: undefined,
Jul 29 11:53:11 inst01 rocketchat[2000]:   errorType: 'Meteor.Error'
Jul 29 11:53:11 inst01 rocketchat[2000]: }
```

**Comment by sampaiodiego** [comment]
apparently the process was killed *right after* it came up =( but the rollback operation didn't work, because it seems to be using the upgraded database instead of backup prior the upgrade process.

what happens if you run `rocketchatctl update` again? if it still tries to upgrade, the startup should be faster now and it should start 🙏 

pinging @LuluGO and @geekgonecrazy

**Comment by rzaSF** [comment]
I did, which did not work because Rocket.Chat would not start (I believe update only works if Rocket.Chat is "up"?)

```
root@inst01:~# rocketchatctl update
Updates could be risky, you can use the backup option # rocketchatctl backup, to create a backup of the rocketchat database first. Please check that you have enough space in your system to store the backup.
/usr/local/bin/rocketchatctl: line 900: [: 3.5.0commit: unary operator expected
Could not determine if updates available for RocketChat server.
root@inst01:~# rocketchatctl update
Updates could be risky, you can use the backup option # rocketchatctl backup, to create a backup of the rocketchat database first. Please check that you have enough space in your system to store the backup.
/usr/local/bin/rocketchatctl: line 900: [: 3.5.0commit: unary operator expected
Could not determine if updates available for RocketChat server.
root@inst01:~# rocketchatctl update
Updates could be risky, you can use the backup option # rocketchatctl backup, to create a backup of the rocketchat database first. Please check that you have enough space in your system to store the backup.
/usr/local/bin/rocketchatctl: line 900: [: 3.5.0commit: unary operator expected
Could not determine if updates available for RocketChat server.
root@inst01:~# rocketchatctl update
Updates could be risky, you can use the backup option # rocketchatctl backup, to create a backup of the rocketchat database first. Please check that you have enough space in your system to store the backup.
/usr/local/bin/rocketchatctl: line 900: [: 3.5.0commit: unary operator expected
Could not determine if updates available for RocketChat server.
```


So, I concluded that the deployment was hosed.  At this point I rolled back to a snapshot pre-upgrade.  I've tried several times (rolled back to pre-upgrade snapshot) and unfortunately, each time it failed and got into the same spot.  I'm not sure there's a way out following the failure.  If I'm missing something please do let me know.

I had a similar problem (issue #18142), and it worked in a subsequent try (read: many tries from 'clean' snapshot).  Maybe the timing was just right and it worked.

I'm not sure why there seems to be a "fixed" 60 second timer.  Is the expectation that migration and bootstrap post migration should never take more than 60 seconds?  In my experience with Rocket.Chat so far, seems it's just getting migration wrapped up 30-40 seconds in.

**Comment by rzaSF** [comment]
Is it possible this is resolved in 3.5.1 update?  Or would it have been closed if it were?  (I don't see any linked PR so I'm assuming this is still an issue even with 3.5.1)

**Comment by geekgonecrazy** [comment]
All of the rocketchatctl code is actually over on github.com/rocketchat/install.sh

Indeed looks like timeout needs increased because of migration taking longer.  Also of course then rollback can’t happen because of migration.  Let’s increase the time out to 5 minutes instead and see if that helps

**Comment by geekgonecrazy** [comment]
rocketchatctl upgrade-rocketchatctl 

Should update to latest version which should now have the 5 minute timeout
