### ISSUE TITLE
GridFS to Scaleway S3 : NoSuchKey: The specified key does not exist. [ufs: cannot upload file] 

### ISSUE THREAD

**Issue by avignat** [RocketChat/Rocket.Chat#18424]
### Description:

I just moved all the uploaded files from GridFS to Scaleway S3 helped by the tool https://github.com/arminfelder/gridfsmigrate.
Everything works but the upload.

When I try to upload something I get :
`NoSuchKey: The specified key does not exist. [ufs: cannot upload file]`

### Steps to reproduce:

1. Migrate data to S3
2. Enable S3 storage
3. Try to upload something

### Expected behavior:

Upload should work

### Actual behavior:

I get an error.
`NoSuchKey: The specified key does not exist. [ufs: cannot upload file]`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.0
- Operating System: Debian 10
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: Rocket.Chat Docker image
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: W10 & Arch

### Additional context

![image](https://user-images.githubusercontent.com/1545450/88815157-4bdbb180-d1bb-11ea-8eec-49f1d7f0fdfa.png)

### Relevant logs:

```
rocketchat_1  | InvalidArgument: Invalid Argument.                                                                                                                          
rocketchat_1  |     at Request.extractError (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/services/s3.js:583:35)                                                
rocketchat_1  |     at Request.callListeners (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:106:20)                                       
rocketchat_1  |     at Request.emit (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:78:10)                                                
rocketchat_1  |     at Request.emit (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)                                                           
rocketchat_1  |     at Request.transition (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)                                                      
rocketchat_1  |     at AcceptorStateMachine.runTo (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)                                        
rocketchat_1  |     at /app/bundle/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10                                                                     
rocketchat_1  |     at Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)                                                      
rocketchat_1  |     at Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)                                                    
rocketchat_1  |     at Request.callListeners (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:116:18)                                      
rocketchat_1  |     at Request.emit (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
rocketchat_1  |     at Request.emit (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)
rocketchat_1  |     at Request.transition (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)
rocketchat_1  |     at AcceptorStateMachine.runTo (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)
rocketchat_1  |     at /app/bundle/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10
rocketchat_1  |     at Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)
rocketchat_1  |     at Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)
rocketchat_1  |     at Request.callListeners (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
rocketchat_1  |     at callNextListener (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
rocketchat_1  |     at IncomingMessage.onEnd (/app/bundle/programs/server/npm/node_modules/aws-sdk/lib/event_listeners.js:299:13)
rocketchat_1  |     at IncomingMessage.emit (events.js:323:22)
rocketchat_1  |     at IncomingMessage.EventEmitter.emit (domain.js:482:12)
rocketchat_1  |     at endReadableNT (_stream_readable.js:1204:12)
rocketchat_1  |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
rocketchat_1  |   message: 'Invalid Argument.',
rocketchat_1  |   code: 'InvalidArgument',
rocketchat_1  |   region: null,
rocketchat_1  |   time: 2020-07-29T14:25:34.067Z,
rocketchat_1  |   requestId: 'txde3432eebef2431abab3a-005f2186dd',
rocketchat_1  |   extendedRequestId: 'txde3432eebef2431abab3a-005f2186dd',
rocketchat_1  |   cfId: undefined,
rocketchat_1  |   statusCode: 400,
rocketchat_1  |   retryable: false,
rocketchat_1  |   retryDelay: 49.84465697940039
rocketchat_1  | }
```

**Comment by avignat** [comment]
Setting up an ACL based on this [doc](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl) seems to fix the issue.
What is the recommended ACL ?

**Comment by geekgonecrazy** [comment]
This would make for a great doc worth contributing.  I think you are the first one I’ve seen an issue for that used scaleways s3 store

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  As dealing with a community generated tool we didn’t write so can’t control.
