### ISSUE TITLE
Users page in admin panel not working for inactive user after registration 3.5.1

### ISSUE THREAD

**Issue by qwsj** [RocketChat/Rocket.Chat#18512]
### Description:

Users page in admin panel not working for inactive user after registration with

### Steps to reproduce:

1. Administration -> Settings -> Accounts -> Registration -> Pick for Manually Approve New Users

2. After new user registration, have succeeded message:
```
Registration Succeeded
Before you can login, your account must be manually activated by an administrator.
Please wait, this can take some time.
```

3. Next setep in admin panel: 
Administration -> Users -> Pick this user (Page not loading and error writing in log)

### Expected behavior:

Loading the page with user information

### Actual behavior:

Users page:
![1](https://user-images.githubusercontent.com/10673437/89711706-9ff14d80-d994-11ea-99c5-d0bfb8f05bd2.png)

After pick the user:
![2](https://user-images.githubusercontent.com/10673437/89711707-a253a780-d994-11ea-9b35-9ffd37eaf4ee.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.1
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: Safari 13.1.2 (15609.3.5.1.3) / Google Chrome 84.0.4147.105
- Operating System: MacOS 10.15.6

### Relevant logs:

Error in syslog:
```
 Exception while invoking method login Error: User is not activated [error-user-is-not-activated]
     at app/authentication/server/startup/index.js:327:9
     at packages/callback-hook/hook.js:131:22
     at packages/accounts-base/accounts_server.js:154:15
     at Hook.each (packages/callback-hook/hook.js:109:15)
     at AccountsServer._validateLogin (packages/accounts-base/accounts_server.js:151:29)
     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:340:10)
     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:522:23)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
     at packages/ddp-server/livedata_server.js:1689:15
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at packages/ddp-server/livedata_server.js:1687:36
     at new Promise (<anonymous>)
     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
     at Object.post (app/api/server/v1/misc.js:262:26)
     at app/api/server/api.js:388:82
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
     at packages/nimble_restivus/lib/route.coffee:59:33
     at packages/simple_json-routes.js:98:9
  => awaited here:
     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
     at Object.post (app/api/server/v1/misc.js:262:26)
     at app/api/server/api.js:388:82
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
     at packages/nimble_restivus/lib/route.coffee:59:33
     at packages/simple_json-routes.js:98:9
```

**Comment by xux1217** [comment]
I meet the same error.

I guess occurred this error because the field "username" is empty, so I use API to active this user, or use API to fill username, and then, I can use the admin panel to manage this user.

But finally, I choice register new user by admin manually, and send the password resetting email.

**Comment by rzaSF** [comment]
I'm also experiencing this problem.

**Comment by rmaksimov** [comment]
> I meet the same error.
> 
> I guess occurred this error because the field "username" is empty, so I use API to active this user, or use API to fill username, and then, I can use the admin panel to manage this user.

The same with 3.5.0, but the value of the username field doesnt matter. The problem is related to the value of the active field. If the value is false, then there is such behaviour

**Comment by haloflooder** [comment]
I'm having the same exact issue as well. Using 3.5.2

**Comment by brnck** [comment]
I also have the same issue. I can't approve or remove any newly registered users. It just fetches user info from backend and shows blank page instead of showing users list and a sidebar with selected user info.

However my colleague is able to remove or approve user by refreshing (refresh asks for re-login) the same page.
Logs shows no errors whatsoever.

Additional issue thing is that when users register, backend returns a message that user is blocked until approve by admin will be made, however no toaster is showed and user assumes that nothing happened and tries to register once again (and for sure gets an error message that user already exists). 

I guess all these issues somehow revolves around `Manually Approve New Users` feature

Server Setup Information:
* Version of Rocket.Chat Server: 3.5.2
* Operating System: Ubuntu 20.04
* Deployment Method: Docker
* Number of Running Instances: 
* DB Replicaset Oplog: enabled
* NodeJS Version: v12.16.1
* MongoDB Version:4.0
