### ISSUE TITLE
rocketchat 3.5.1 no email and push notifications

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#18536]
### Description:

Since a few days it seems users are not getting push nor email notifications anymore. Interesting enough: Sending a test push notification or a email test notification from admin interface works. Only errors in logfile are a lot of this:

```
rror: ENOENT: no such file or directory, open '/tmp/userData/dvzvHKQt5F72MAFKf/user.json'
    at Object.openSync (fs.js:457:3)
    at Object.writeFileSync (fs.js:1282:35)
    at startFile (app/user-data-download/server/cronProcessDownloads.js:29:5)
    at generateUserFile (app/user-data-download/server/cronProcessDownloads.js:445:2)
    at app/user-data-download/server/cronProcessDownloads.js:504:4
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/tmp/userData/dvzvHKQt5F72MAFKf/user.json'
}
```

And I mean a lot. Any hints where i could start to look? I set the notifications for a few channels to "every messsage" in every category but to no avail. I do not get Emails or Push Notifications. Clients disconnected of course.

### Steps to reproduce:

1. Upgrade to 3.5.1 (from 3.4.2)
2. No Notifications

### Expected behavior:

Notifications!

### Actual behavior:

No Notifications!

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.1
- Operating System: Linux
- Deployment Method: Docker / Helm / Kubernetes
- Number of Running Instances: 4
- DB Replicaset Oplog: Yes
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.10

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Ubuntu

**Comment by himpierre** [comment]
Re-Deploying the cluster fixed the issue. No clue what was going on.
