### ISSUE TITLE
Push notifications broken, server down and won't start!

### ISSUE THREAD

**Issue by paulkernstock** [RocketChat/Rocket.Chat#18550]
### Description:

Alright this is really bad for me now! Today I got noticed by my RC instance that I had to re-enable the push gateway:

> **Action required**
> The mobile notifications were disabled to all users, go to "Admin > Push" to enable the Push Gateway again

As for the requirement to register my instance at the RC cloud, this was trouble as well but seemed to have worked by last week.

On the Push panel in the administration, both notifications and the gateway were activated but all push notifications to mobile devices had ceased. So I tried to disable and re-enable them while restarting the server each time afterwards from the general setting pane. Without effect.

After waiting some time (maybe the interrupted push service would resume like it did many times in the past, but nothing changed) I reset my settings on the "Push" pane and restarted the server again and here I am now, the server didn't come up again and all I get is a 502 Bad Gateway.

I tried to restart the snap service as well and it says it's running but my reverse proxy can't connect to the backend port 3000 which indeed is not bound to any service. It seems that the caddy services has problems:

```
$ sudo snap services rocketchat-server
Service                              Startup  Current   Notes
rocketchat-server.rocketchat-caddy   enabled  inactive  -
rocketchat-server.rocketchat-mongo   enabled  active    -
rocketchat-server.rocketchat-server  enabled  active    -
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.1
- Operating System: Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1

### Relevant logs:

Here's the logs from the caddy service:
```
2020-08-13T16:34:36Z systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Main process exited, code=exited, status=1/FAILURE
2020-08-13T16:34:36Z systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result 'exit-code'.
2020-08-13T16:34:36Z systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Service hold-off time over, scheduling restart.
2020-08-13T16:34:36Z systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Scheduled restart job, restart counter is at 5.
2020-08-13T16:34:36Z systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-caddy.
2020-08-13T16:34:36Z systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Start request repeated too quickly.
2020-08-13T16:34:36Z systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result 'exit-code'.
2020-08-13T16:34:36Z systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-caddy.
```

Here's the logs from the server:
```
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ System ➔ startup
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ +--------------------------------------------------+
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |                  SERVER RUNNING                  |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ +--------------------------------------------------+
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |                                                  |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |  Rocket.Chat Version: 3.5.1                      |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |       NodeJS Version: 12.16.1 - x64              |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |      MongoDB Version: 3.6.14                     |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |       MongoDB Engine: wiredTiger                 |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |             Platform: linux                      |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |         Process Port: 3000                       |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |             Site URL: https://chat.kernstock.eu  |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |     ReplicaSet OpLog: Enabled                    |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |          Commit Hash: 2fb78cf857                 |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |        Commit Branch: HEAD                       |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ |                                                  |
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: ➔ +--------------------------------------------------+
2020-08-13T16:16:01Z rocketchat-server.rocketchat-server[14892]: Search Logger ➔ debug Start provider 'defaultProvider'
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]: Error: failed [503] Service Unavailable
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at Object.exports.makeErrorByStatus (packages/http.js:177:10)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at Request._callback (packages/http.js:141:24)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at Request.self.callback (/snap/rocketchat-server/1439/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at Request.emit (events.js:311:20)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at Request.EventEmitter.emit (domain.js:482:12)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at Request.<anonymous> (/snap/rocketchat-server/1439/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at Request.emit (events.js:311:20)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at Request.EventEmitter.emit (domain.js:482:12)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at IncomingMessage.<anonymous> (/snap/rocketchat-server/1439/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at Object.onceWrapper (events.js:417:28)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at IncomingMessage.emit (events.js:323:22)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at IncomingMessage.EventEmitter.emit (domain.js:482:12)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at endReadableNT (_stream_readable.js:1204:12)
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:   response: {
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     statusCode: 503,
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     content: 'Service Unavailable',
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     headers: {
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:       date: 'Thu, 13 Aug 2020 16:16:02 GMT',
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:       'content-length': '19',
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:       'content-type': 'text/plain; charset=utf-8',
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:       connection: 'close'
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     },
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:     data: null
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]:   }
2020-08-13T16:16:02Z rocketchat-server.rocketchat-server[14892]: }
2020-08-13T16:16:03Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ warn Failed to send usage report
2020-08-13T16:16:03Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Scheduled "Apps-Engine:check" next run @Fri Aug 14 2020 04:00:00 GMT+0200 (Central European Summer Time)
2020-08-13T16:16:03Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Scheduled "version_check" next run @Fri Aug 14 2020 02:00:00 GMT+0200 (Central European Summer Time)
2020-08-13T16:16:03Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Scheduled "aggregate-sessions" next run @Fri Aug 14 2020 02:00:00 GMT+0200 (Central European Summer Time)
2020-08-13T16:16:03Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Scheduled "Cloud Workspace Sync" next run @Fri Aug 14 2020 00:00:00 GMT+0200 (Central European Summer Time)
2020-08-13T16:16:03Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Scheduled "Remove users from Token Channels" next run @Thu Aug 13 2020 19:00:00 GMT+0200 (Central European Summer Time)
2020-08-13T16:16:03Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Scheduled "Generate download files for user data" next run @Thu Aug 13 2020 18:18:00 GMT+0200 (Central European Summer Time)
2020-08-13T16:16:03Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Scheduled "Livechat Agent Activity Monitor" next run @Fri Aug 14 2020 00:00:00 GMT+0200 (Central European Summer Time)
2020-08-13T16:16:03Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Scheduled "Generate and save statistics" next run @Thu Aug 13 2020 19:12:00 GMT+0200 (Central European Summer Time)
2020-08-13T16:16:03Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Scheduled "Cleanup OEmbed cache" next run @Fri Aug 14 2020 02:24:00 GMT+0200 (Central European Summer Time)
2020-08-13T16:16:20Z rocketchat-server.rocketchat-server[14892]: Meteor ➔ publish null -> userId: null, arguments: []
2020-08-13T16:16:20Z rocketchat-server.rocketchat-server[14892]: Meteor ➔ publish null -> userId: null, arguments: []
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: API ➔ debug GET: /api/v1/rooms.get?updatedSince=2020-08-13T15%3A48%3A07.471Z
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: API ➔ debug GET: /api/v1/subscriptions.get?updatedSince=2020-08-13T15%3A48%3A07.471Z
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: API ➔ debug GET: /api/v1/chat.syncMessages?roomId=nBT2WpKN5ZwcAYRaRrocket.cat&lastUpdate=null
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: Meteor ➔ method rooms/get -> userId: nBT2WpKN5ZwcAYRaR, arguments: [{}]
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: Meteor ➔ method subscriptions/get -> userId: nBT2WpKN5ZwcAYRaR, arguments: [{}]
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: API ➔ debug get chat.syncMessages threw an error: Error: The "lastUpdate" query parameter must be a valid date. [error-roomId-param-invalid]
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:     at Object.get (app/api/server/v1/chat.js:62:10)
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:     at app/api/server/api.js:388:82
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:     at packages/nimble_restivus/lib/route.coffee:59:33
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:     at packages/simple_json-routes.js:98:9
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: API ➔ debug Failure {
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:   statusCode: 400,
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:   body: {
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:     success: false,
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:     error: 'The "lastUpdate" query parameter must be a valid date. [error-roomId-param-invalid]',
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:     stack: undefined,
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:     errorType: 'error-roomId-param-invalid'
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:   }
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: }
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: Meteor ➔ publish null -> userId: nBT2WpKN5ZwcAYRaR, arguments: []
2020-08-13T16:16:21Z rocketchat-server.rocketchat-mongo[14884]: 2020-08-13T18:16:21.111+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:42832 #10 (7 connections now open)
2020-08-13T16:16:21Z rocketchat-server.rocketchat-mongo[14884]: 2020-08-13T18:16:21.117+0200 I NETWORK  [conn10] received client metadata from 127.0.0.1:42832 conn10: { driver: { name: "nodejs", version: "3.5.4" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-112-generic" }, platform: "'Node.js v12.16.1, LE (legacy)" }
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: Meteor ➔ method UserPresence:online -> userId: nBT2WpKN5ZwcAYRaR, arguments: [""]
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: Meteor ➔ method canAccessRoom -> userId: nBT2WpKN5ZwcAYRaR, arguments: ["nBT2WpKN5ZwcAYRaRrocket.cat","nBT2WpKN5ZwcAYRaR",null]
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: API ➔ debug Success {
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:   statusCode: 200,
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:   body: { update: [ [Object] ], remove: [], success: true }
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: }
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: API ➔ debug Success {
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:   statusCode: 200,
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]:   body: { update: [ [Object] ], remove: [], success: true }
2020-08-13T16:16:21Z rocketchat-server.rocketchat-server[14892]: }
2020-08-13T16:16:22Z rocketchat-server.rocketchat-server[14892]: Meteor ➔ method UserPresence:away -> userId: nBT2WpKN5ZwcAYRaR, arguments: [""]
2020-08-13T16:16:47Z rocketchat-server.rocketchat-server[14892]: API ➔ debug GET: /api/v1/users.presence?ids=23k7FCWim6R8uCBHj%2Crocket.cat%2CFQnxrjQHtsHWJ6KJQ%2CnBT2WpKN5ZwcAYRaR%2CEc95YeA4qB9355g7Z%2CSb5SneixuyA6koajn%2CSEoBenrKfP7wiDQSs%2CoijbqPHpnb5ZxWWHA%2C3RymTQHhxfD44dEWg%2CJRGKHSjrNxP9fMf7b%2ChmnxzMBxhDJRQNuL7%2CXTBG2yCJ2Wonf9bdR
2020-08-13T16:16:47Z rocketchat-server.rocketchat-server[14892]: API ➔ debug Success {
2020-08-13T16:16:47Z rocketchat-server.rocketchat-server[14892]:   statusCode: 200,
2020-08-13T16:16:47Z rocketchat-server.rocketchat-server[14892]:   body: { users: [ [Object], [Object] ], full: false, success: true }
2020-08-13T16:16:47Z rocketchat-server.rocketchat-server[14892]: }
2020-08-13T16:16:47Z rocketchat-server.rocketchat-server[14892]: Meteor ➔ method UserPresence:online -> userId: nBT2WpKN5ZwcAYRaR, arguments: [""]
2020-08-13T16:16:47Z rocketchat-server.rocketchat-server[14892]: API ➔ debug GET: /api/v1/rooms.get?updatedSince=2020-08-13T16%3A16%3A20.995Z
2020-08-13T16:16:47Z rocketchat-server.rocketchat-server[14892]: Meteor ➔ method rooms/get -> userId: nBT2WpKN5ZwcAYRaR, arguments: [{}]
2020-08-13T16:16:47Z rocketchat-server.rocketchat-server[14892]: API ➔ debug GET: /api/v1/subscriptions.get?updatedSince=2020-08-13T16%3A16%3A20.995Z
2020-08-13T16:16:47Z rocketchat-server.rocketchat-server[14892]: Meteor ➔ method subscriptions/get -> userId: nBT2WpKN5ZwcAYRaR, arguments: [{}]
2020-08-13T16:16:47Z rocketchat-server.rocketchat-server[14892]: API ➔ debug Success { statusCode: 200, body: { update: [], remove: [], success: true } }
2020-08-13T16:16:47Z rocketchat-server.rocketchat-server[14892]: API ➔ debug Success { statusCode: 200, body: { update: [], remove: [], success: true } }
2020-08-13T16:16:56Z rocketchat-server.rocketchat-server[14892]: Meteor ➔ method UserPresence:away -> userId: nBT2WpKN5ZwcAYRaR, arguments: [""]
2020-08-13T16:18:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Starting "Generate download files for user data".
2020-08-13T16:18:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Finished "Generate download files for user data".
2020-08-13T16:20:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Starting "Generate download files for user data".
2020-08-13T16:20:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Finished "Generate download files for user data".
2020-08-13T16:22:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Starting "Generate download files for user data".
2020-08-13T16:22:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Finished "Generate download files for user data".
2020-08-13T16:24:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Starting "Generate download files for user data".
2020-08-13T16:24:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Finished "Generate download files for user data".
2020-08-13T16:26:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Starting "Generate download files for user data".
2020-08-13T16:26:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Finished "Generate download files for user data".
2020-08-13T16:28:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Starting "Generate download files for user data".
2020-08-13T16:28:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Finished "Generate download files for user data".
2020-08-13T16:30:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Starting "Generate download files for user data".
2020-08-13T16:30:00Z rocketchat-server.rocketchat-server[14892]: SyncedCron ➔ info Finished "Generate download files for user data".

```

**Comment by graywolf336** [comment]
This was fixed with 3.5.2 (https://github.com/RocketChat/Rocket.Chat/releases/tag/3.5.2). But also should be working fine now.
