### ISSUE TITLE
Livechat method `livechat:saveBusinessHour` crashes server.

### ISSUE THREAD

**Issue by gabriellsh** [RocketChat/Rocket.Chat#18566]
### Description:
If the method is called with any parameter that does not meet the Typescript specifications, the server crashes.

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:
An error to be returned, instead of downing the whole server.

### Actual behavior:
Described above.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0-develop
- Operating System: macOS catalina
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:
Log 1:
```
W20200814-14:43:09.261(-3)? (STDERR) === UnHandledPromiseRejection ===
W20200814-14:43:09.264(-3)? (STDERR) TypeError: (name || "").toLowerCase is not a function
W20200814-14:43:09.264(-3)? (STDERR)     at normalizeName (/Users/gabriellsh/dev/Rocket.Chat/node_modules/moment-timezone/moment-timezone.js:382:23)
W20200814-14:43:09.266(-3)? (STDERR)     at getZone (/Users/gabriellsh/dev/Rocket.Chat/node_modules/moment-timezone/moment-timezone.js:404:10)
W20200814-14:43:09.267(-3)? (STDERR)     at Function.tz (/Users/gabriellsh/dev/Rocket.Chat/node_modules/moment-timezone/moment-timezone.js:495:11)
W20200814-14:43:09.268(-3)? (STDERR)     at DefaultBusinessHour.getUTCFromTimezone (app/livechat/server/business-hour/AbstractBusinessHour.ts:99:17)
W20200814-14:43:09.268(-3)? (STDERR)     at app/livechat/server/business-hour/Default.ts:23:14
W20200814-14:43:09.269(-3)? (STDERR)     at /Users/gabriellsh/.meteor/packages/promise/.0.11.2.7j140w.ob2tj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20200814-14:43:09.269(-3)? (STDERR)  => awaited here:
W20200814-14:43:09.269(-3)? (STDERR)     at Function.Promise.await (/Users/gabriellsh/.meteor/packages/promise/.0.11.2.7j140w.ob2tj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20200814-14:43:09.269(-3)? (STDERR)     at app/livechat/server/business-hour/BusinessHourManager.ts:72:14
W20200814-14:43:09.269(-3)? (STDERR)     at /Users/gabriellsh/.meteor/packages/promise/.0.11.2.7j140w.ob2tj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20200814-14:43:09.271(-3)? (STDERR) ---------------------------------
W20200814-14:43:09.272(-3)? (STDERR) Errors like this can cause oplog processing errors.
W20200814-14:43:09.272(-3)? (STDERR) Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
W20200814-14:43:09.272(-3)? (STDERR) Future node.js versions will automatically exit the process
W20200814-14:43:09.273(-3)? (STDERR) =================================
```
Log 2:
```
W20200813-18:05:06.954(-3)? (STDERR) === UnHandledPromiseRejection ===
W20200813-18:05:06.955(-3)? (STDERR) TypeError: Cannot read property 'forEach' of undefined
W20200813-18:05:06.955(-3)? (STDERR)     at DefaultBusinessHour.convertWorkHours (app/livechat/server/business-hour/AbstractBusinessHour.ts:66:30)
W20200813-18:05:06.955(-3)? (STDERR)     at app/livechat/server/business-hour/AbstractBusinessHour.ts:56:27
W20200813-18:05:06.955(-3)? (STDERR)     at /Users/gabriellsh/.meteor/packages/promise/.0.11.2.7j140w.ob2tj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20200813-18:05:06.955(-3)? (STDERR)  => awaited here:
W20200813-18:05:06.956(-3)? (STDERR)     at Function.Promise.await (/Users/gabriellsh/.meteor/packages/promise/.0.11.2.7j140w.ob2tj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20200813-18:05:06.956(-3)? (STDERR)     at app/livechat/server/business-hour/Default.ts:26:3
W20200813-18:05:06.956(-3)? (STDERR)     at /Users/gabriellsh/.meteor/packages/promise/.0.11.2.7j140w.ob2tj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20200813-18:05:06.956(-3)? (STDERR)  => awaited here:
W20200813-18:05:06.956(-3)? (STDERR)     at Function.Promise.await (/Users/gabriellsh/.meteor/packages/promise/.0.11.2.7j140w.ob2tj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20200813-18:05:06.956(-3)? (STDERR)     at app/livechat/server/business-hour/BusinessHourManager.ts:72:14
W20200813-18:05:06.956(-3)? (STDERR)     at /Users/gabriellsh/.meteor/packages/promise/.0.11.2.7j140w.ob2tj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20200813-18:05:06.957(-3)? (STDERR) ---------------------------------
W20200813-18:05:06.957(-3)? (STDERR) Errors like this can cause oplog processing errors.
W20200813-18:05:06.957(-3)? (STDERR) Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
W20200813-18:05:06.957(-3)? (STDERR) Future node.js versions will automatically exit the process
W20200813-18:05:06.957(-3)? (STDERR) =================================
```

**Comment by clemmayer** [comment]
We're also having this issue.
3.16.2 (after upgrade from 3.14.0)
RocketChat Container

Version
3.16.2
Apps Engine Version
1.27.1
Node Version
v12.22.1
MongoDB
4.0.25 / wiredTiger (oplog Enabled)

Commit Details
HEAD: (e178a9a25)
Branch: HEAD

**Comment by KevLehman** [comment]
This pull request has been inactive for a while, so we’re closing it to keep the backlog manageable.
If you’d like to continue working on it, feel free to reopen or submit a new PR. Thanks for the contribution!
