### ISSUE TITLE
Unexpected exception for autotranslate on server startup

### ISSUE THREAD

**Issue by jathan** [RocketChat/Rocket.Chat#18662]
### Description:

With autotranslate disabled I get the following exception stack trace on startup.  It seems like this shouldn't be happening when autotranslate is disabled:

### Steps to reproduce:

Startup the server with auto-translate disabled.

### Expected behavior:

Nothing should be in the logs (except maybe a Auto Translate is currently disabled)

### Actual behavior:
```
method not allowed
rocketchat: at (app/autotranslate/server/methods/getSupportedLanguages.js:11:10)
rocketchat: at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
rocketchat: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
rocketchat: at packages/ddp-server/livedata_server.js:1689:15
rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
rocketchat: at packages/ddp-server/livedata_server.js:1687:36
rocketchat: at new Promise (<anonymous>)
rocketchat: at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
rocketchat: at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
rocketchat: at Server.call (packages/ddp-server/livedata_server.js:1607:17)
rocketchat: at Object.post (app/api/server/v1/misc.js:262:26)
rocketchat: at app/api/server/api.js:388:82
rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
rocketchat: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
rocketchat: at (packages/nimble_restivus/lib/route.coffee:150:32)
rocketchat: at packages/nimble_restivus/lib/route.coffee:59:33
rocketchat: at packages/simple_json-routes.js:98:9
rocketchat: => awaited here:
rocketchat: at Promise.await
(/srv/rocketchat/Rocket.Chat.3.5.3/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
rocketchat: at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
rocketchat: at Server.call (packages/ddp-server/livedata_server.js:1607:17)
rocketchat: at Object.post (app/api/server/v1/misc.js:262:26)
rocketchat: at app/api/server/api.js:388:82
rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
rocketchat: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
rocketchat: at (packages/nimble_restivus/lib/route.coffee:150:32)
rocketchat: at packages/nimble_restivus/lib/route.coffee:59:33
rocketchat: at packages/simple_json-routes.js:98:9
rocketchat: Exception while invoking method not allowed
 rocketchat: at(app/autotranslate/server/methods/getSupportedLanguages.js:11:10)
rocketchat: at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
rocketchat: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
rocketchat: at packages/ddp-server/livedata_server.js:1689:15
rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
rocketchat: at packages/ddp-server/livedata_server.js:1687:36
rocketchat: at new Promise (<anonymous>)
rocketchat: at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
rocketchat: at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
rocketchat: at Server.call (packages/ddp-server/livedata_server.js:1607:17)
rocketchat: at Object.post (app/api/server/v1/misc.js:262:26)
rocketchat: at app/api/server/api.js:388:82
rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
rocketchat: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
rocketchat: at (packages/nimble_restivus/lib/route.coffee:150:32)
rocketchat: at packages/nimble_restivus/lib/route.coffee:59:33
rocketchat: at packages/simple_json-routes.js:98:9
rocketchat: => awaited here:
```
### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.3
- Operating System: CentOS 7.8.2003
- Deployment Method: tar
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
> rs.printReplicationInfo()
configured oplog size:   51200MB
log length start to end: 40150524secs (11152.92hrs)
oplog first event time:  Fri May 17 2019 17:22:31 GMT-0400 (EDT)
oplog last event time:   Mon Aug 24 2020 10:17:55 GMT-0400 (EDT)
now:                     Mon Aug 24 2020 10:17:57 GMT-0400 (EDT)

- NodeJS Version: 
>node --version
v12.14.0
- MongoDB Version:

>mongod --version
db version v4.0.19
git version: 7e28f4296a04d858a2e3dd84a1e79c9ba59a9568
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64

### Client Setup Information

Not applicable -- happens on server startup

### Relevant logs:

See above.

**Comment by ubergeekzone** [comment]
+1 on this issue.

**Comment by beranPro** [comment]
Same here

```
Error: Auto-Translate is not allowed [error-action-not-allowed]
    at MethodInvocation.autoTranslate.getSupportedLanguages (app/autotranslate/server/methods/getSupportedLanguages.js:11:10)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:388:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:388:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
```

**Comment by awunder** [comment]
same here though not only at startup but every couple minutes

**Comment by mhenninghaus77** [comment]
+1 on this issue.

Rocket.Chat Server 3.5.4

**Comment by piotrkochan** [comment]
Same here, auto translate feature is disabled and it spams from time to time about it

**Comment by hiukim** [comment]
+1

**Comment by UAnton** [comment]
+1

**Comment by Nono-m0le** [comment]
Same here, every minutes (SNAP install, on a Ubuntu 18.04)
```
➔ |             Platform: linux             |
➔ |       MongoDB Engine: wiredTiger        |
➔ |      MongoDB Version: 3.6.14            |
➔ |       NodeJS Version: 12.16.1 - x64     |
➔ |  Rocket.Chat Version: 3.6.2             |
```

**Comment by aiukao** [comment]
Same issue.

Red Hat Enterprise Linux Server release 7.6
MongoDB 3.6.3 wiredTiger
Nodejs v12.14.0
Rocketchat 3.5.0

**Comment by aradhya-gupta** [comment]
May I work on this issue?

**Comment by medelmourabite** [comment]
+1

**Comment by MrPoint1400** [comment]
+1

**Comment by xFuture603** [comment]
+1 for me. This error occurs every couple of minutes.

**Comment by UAnton** [comment]
Same problem
