### ISSUE TITLE
rocket chat server enters failed state every once in a while

### ISSUE THREAD

**Issue by gstlouisgit** [RocketChat/Rocket.Chat#18681]
### Description:

every once in a while rocket chat just crashes.  enters failed state with rocketchat.service: main process exited, code=killed, status=9/KILL
I see nothing in the logs that indicate anything I can work with
This started since I had an older version of RC.  Now I have upgraded and upgraded node to v 12 and still this problem persists.

Centos7
4gig of 8 gig memory used
79 of 160 gig space used
mongo never crashes.

### Steps to reproduce:

There isn't really a step to reproduce I just gotta wait and it will crash again.

### Expected behavior:

not to crash

### Actual behavior:

just stops, mostly overnight from what i can see.

### Server Setup Information:

- Version of Rocket.Chat Server: 

Version | 3.5.2
-- | --
1.16.0
202
August 26, 2020 10:23 AM
December 26, 2019 3:32 PM
18 seconds
zY4v5BXtivttdoybP
21415
1
Enabled

- Operating System: centos7
- Deployment Method: manual install
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: 12
- MongoDB Version: MongoDB server version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: mac and windows

### Relevant logs:

Aug 25 02:00:00 virtual.smbservices.ca rocketchat[8211]: Warning: language  is not supported in this project, fallback language (en)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: Exception while invoking method autoTranslate.getSupportedLanguages Error: Auto-Translate is not allowed [error-action-not-allowed]
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at MethodInvocation.autoTranslate.getSupportedLanguages (app/autotranslate/server/methods/getSupportedLanguages.js:11:10)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at packages/ddp-server/livedata_server.js:1689:15
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at packages/ddp-server/livedata_server.js:1687:36
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at new Promise (<anonymous>)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Object.post (app/api/server/v1/misc.js:262:26)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at app/api/server/api.js:388:82
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at packages/nimble_restivus/lib/route.coffee:59:33
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at packages/simple_json-routes.js:98:9
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: => awaited here:
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Object.post (app/api/server/v1/misc.js:262:26)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at app/api/server/api.js:388:82
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at packages/nimble_restivus/lib/route.coffee:59:33
Aug 25 14:27:36 virtual.smbservices.ca rocketchat[8211]: at packages/simple_json-routes.js:98:9
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: Exception while invoking method autoTranslate.getSupportedLanguages Error: Auto-Translate is not allowed [error-action-not-allowed]
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at MethodInvocation.autoTranslate.getSupportedLanguages (app/autotranslate/server/methods/getSupportedLanguages.js:11:10)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/ddp-server/livedata_server.js:1689:15
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/ddp-server/livedata_server.js:1687:36
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at new Promise (<anonymous>)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object.post (app/api/server/v1/misc.js:262:26)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at app/api/server/api.js:388:82
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/nimble_restivus/lib/route.coffee:59:33
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/simple_json-routes.js:98:9
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: => awaited here:
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object.post (app/api/server/v1/misc.js:262:26)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at app/api/server/api.js:388:82
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/nimble_restivus/lib/route.coffee:59:33
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/simple_json-routes.js:98:9
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:104:10)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/ddp-server/livedata_server.js:1689:15
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/ddp-server/livedata_server.js:1687:36
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at new Promise (<anonymous>)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object.post (app/api/server/v1/misc.js:262:26)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at app/api/server/api.js:388:82
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/nimble_restivus/lib/route.coffee:59:33
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/simple_json-routes.js:98:9
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: => awaited here:
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object.post (app/api/server/v1/misc.js:262:26)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at app/api/server/api.js:388:82
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/nimble_restivus/lib/route.coffee:59:33
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/simple_json-routes.js:98:9
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:104:10)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/ddp-server/livedata_server.js:1689:15
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/ddp-server/livedata_server.js:1687:36
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at new Promise (<anonymous>)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object.post (app/api/server/v1/misc.js:262:26)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at app/api/server/api.js:388:82
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/nimble_restivus/lib/route.coffee:59:33
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/simple_json-routes.js:98:9
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: => awaited here:
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object.post (app/api/server/v1/misc.js:262:26)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at app/api/server/api.js:388:82
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/nimble_restivus/lib/route.coffee:59:33
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/simple_json-routes.js:98:9
Aug 25 18:07:23 virtual.smbservices.ca systemd[1]: rocketchat.service: main process exited, code=killed, status=9/KILL
Aug 25 18:07:23 virtual.smbservices.ca systemd[1]: Unit rocketchat.service entered failed state.
Aug 25 18:07:23 virtual.smbservices.ca systemd[1]: rocketchat.service failed.

//	this is where I did systemctl restart rocketchat

Aug 26 10:23:01 virtual.smbservices.ca systemd[1]: Started The Rocket.Chat server.
Aug 26 10:23:12 virtual.smbservices.ca rocketchat[21415]: LocalStore: store created at
Aug 26 10:23:12 virtual.smbservices.ca rocketchat[21415]: LocalStore: store created at
Aug 26 10:23:12 virtual.smbservices.ca rocketchat[21415]: LocalStore: store created at
Aug 26 10:23:13 virtual.smbservices.ca rocketchat[21415]: Setting default file store to GridFS

● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/usr/lib/systemd/system/rocketchat.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Tue 2020-08-25 18:07:23 EDT; 16h ago
  Process: 8211 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=killed, signal=KILL)
 Main PID: 8211 (code=killed, signal=KILL)

Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object.post (app/api/server/v1/misc.js:262:26)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at app/api/server/api.js:388:82
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/nimble_restivus/lib/route.coffee:59:33
Aug 25 14:34:29 virtual.smbservices.ca rocketchat[8211]: at packages/simple_json-routes.js:98:9
Aug 25 18:07:23 virtual.smbservices.ca systemd[1]: rocketchat.service: main process exited, code=killed, status=9/KILL
Aug 25 18:07:23 virtual.smbservices.ca systemd[1]: Unit rocketchat.service entered failed state.
Aug 25 18:07:23 virtual.smbservices.ca systemd[1]: rocketchat.service failed.

**Comment by gstlouisgit** [comment]
after upgrading rocket chat I still get failed state once in a while.  However yesterday it happened, I restarted the service and this morning it crashed again.

same log errors
Oct 20 07:35:20 virtual.smbservices.ca systemd[1]: rocketchat.service: main process exited, code=killed, status=9/KILL
Oct 20 07:35:20 virtual.smbservices.ca systemd[1]: Unit rocketchat.service entered failed state.
Oct 20 07:35:20 virtual.smbservices.ca systemd[1]: rocketchat.service failed.

Are there no other logs or stack trace to follow when this happens?

**Comment by gstlouisgit** [comment]
this is still a problem.  And this CentOS instance work well with everything with lots of unused RAM and space.  I have to log in and restart the service every time.

Nov 03 08:15:06 virtual.machine rocketchat[17506]: at Object.post (app/api/server/v1/misc.js:262:26)
Nov 03 08:15:06 virtual.machine rocketchat[17506]: at app/api/server/api.js:388:82
Nov 03 08:15:06 virtual.machine rocketchat[17506]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Nov 03 08:15:06 virtual.machine rocketchat[17506]: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)
Nov 03 08:15:06 virtual.machine rocketchat[17506]: at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Nov 03 08:15:06 virtual.machine rocketchat[17506]: at packages/nimble_restivus/lib/route.coffee:59:33
Nov 03 08:15:06 virtual.machine rocketchat[17506]: at packages/simple_json-routes.js:98:9
Nov 03 08:30:56 virtual.machine systemd[1]: rocketchat.service: main process exited, code=killed, status=9/KILL
Nov 03 08:30:56 virtual.machine systemd[1]: Unit rocketchat.service entered fail

**Comment by kbondarev** [comment]
I am experiencing a similar issue with `Rocket.Chat Version: 3.10.3`.

It terminates occasionally and I have to restart it manually:

```
Sep 07 06:35:46 RocketChat systemd[1]: rocketchat.service: Main process exited, code=killed, status=9/KILL
Sep 07 06:35:46 RocketChat systemd[1]: rocketchat.service: Failed with result 'signal'.
```


Did you happen to figure this out?

**Comment by Caperious** [comment]
For me, this is happening after uploading files. Any clues on how to proceed?

**Comment by KevLehman** [comment]
This pull request has been inactive for a while, so we’re closing it to keep the backlog manageable.
If you’d like to continue working on it, feel free to reopen or submit a new PR. Thanks for the contribution!
