### ISSUE TITLE
Mail Messages - Locale Error

### ISSUE THREAD

**Issue by miscs** [RocketChat/Rocket.Chat#1879]
Hi all,

Mail messages throws an error - I can select messages, enter an email and press send, but then:
```
[methods] loadLocale -> userId: MZGGm9xhCqDAr5cSf , arguments:  { '0': 'en-US' }
{ [Error: Unknown asset: moment-locales/en-us.js] stack: [Getter] }
Exception while invoking method 'mailMessages' ReferenceError: module is not defined
    at loadLocale (packages/momentjs_moment/moment.js:273:1)
    at locale_locales__getLocale (packages/momentjs_moment/moment.js:339:1)
    at Moment.locale (packages/momentjs_moment/moment.js:2085:1)
    at packages/rocketchat_channel-settings-mail-messages/server/methods/mailMessages.coffee:42:34
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1022:1)
    at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:869:1)
    at [object Object].Meteor.methods.mailMessages (packages/rocketchat_channel-settings-mail-messages/server/methods/mailMessages.coffee:41:102)
    at [object Object].methodsMap.(anonymous function) (packages/rocketchat_lib/server/lib/debug.js:23:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
[publish] null -> userId: null , arguments:  {}
```
api/info
```
{
  "version": "0.13.0",
  "compile": {
    "date": "2016-01-11T14:27:49.945Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.13.0-63-generic",
    "totalMemmory": 7844462592,
    "freeMemmory": 4943417344,
    "cpus": 2
  },
  "travis": {
    "buildNumber": "2936",
    "branch": "0.13.0",
    "tag": "0.13.0"
  },
  "commit": {
    "hash": "15d3e44efb14f51419291738944707b459d9a0c5",
    "date": "Mon Jan 11 12:09:58 2016 -0200",
    "author": "Gabriel Engel",
    "subject": "Merge pull request #1854 from RocketChat/lingohub"
  },
  "tag": "0.13.0",
  "branch": "HEAD",
  "GraphicsMagick": {
    "enabled": false
  },
  "ImageMagick": {
    "enabled": true,
    "version": "Version: ImageMagick 6.8.9-9 Q16 x86_64 2015-01-05 http://www.imagemagick.org\nCopyright: Copyright (C) 1999-2014 ImageMagick Studio LLC\nFeatures: DPC Modules OpenMP\nDelegates: bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib\n\n"
  }
}
```
Any hints would be great. Sending emails works generally.

Thanks!

**Comment by rodrigok** [comment]
Sorry, was fixed via this commit https://github.com/RocketChat/Rocket.Chat/commit/6d0194f420ebb887c8e1b20802f29e1fc4150c51 and will be available with this PR https://github.com/RocketChat/Rocket.Chat/pull/1881

Try to set your language under `/account/profile`, this probably will solve the problem too.

**Comment by miscs** [comment]
thanks - that did the trick!
