### ISSUE TITLE
Error ([500]) in channels imported from Slack with Full Name option enabled

### ISSUE THREAD

**Issue by tindurim** [RocketChat/Rocket.Chat#18914]
### Description:
Error ([500]) in channels imported from Slack with Full Name option enabled

### Steps to reproduce:

1. Import Channels and users from slack
2. Enable "Use Real Name" option on Layout -> User interface
2. Click on a Channel imported from slack with lots of messages
3. Error [500] is present

### Expected behavior:

No error in opening a channel imported from Slack

### Actual behavior:

![image](https://user-images.githubusercontent.com/41684003/93252466-edb75d80-f76b-11ea-8d54-521a88b23032.png)

![image](https://user-images.githubusercontent.com/41684003/93252093-6a960780-f76b-11ea-8714-a4d53b25f62a.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.1
- Operating System: Linux
- Deployment Method:  docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 85.0.4183.102
- Operating System: Windows

### Additional context

Enable "Use Real Name" option on Layout -> User interface
### Relevant logs:

I20200915-18:48:07.978(0) Exception while invoking method 'loadHistory' TypeError: Cannot destructure property 'username' of '_ref' as it is null.     at app/utils/server/lib/normalizeMessagesForUser.js:34:39     at Array.forEach (<anonymous>)     at app/utils/server/lib/normalizeMessagesForUser.js:34:28     at Array.forEach (<anonymous>)     at normalizeMessagesForUser (app/utils/server/lib/normalizeMessagesForUser.js:26:11)     at loadMessageHistory (app/lib/server/functions/loadMessageHistory.js:31:19)     at MethodInvocation.loadHistory (server/methods/loadHistory.js:33:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

**Comment by storrisi** [comment]
I'm having the same issue with version 3.9.2 running on Docker.
