### ISSUE TITLE
[Bug][Federation]  Request that loops

### ISSUE THREAD

**Issue by binboum** [RocketChat/Rocket.Chat#19007]
### Description:

I am currently in version 3.4.2 of the official docker image ( rocketchat/rocket.chat ) , when I switch to 3.6.2 the migration is done correctly, but when I go to the federation dashboard the application crashes.

### Steps to reproduce:

Go to Admin
Click on Federation Dashboard

### Expected behavior:

See the dashboard

### Actual behavior:

I noticed that a loop is created in the developer console with many call of :

/api/v1/method.call/federation%3AgetOverviewData && /api/v1/method.call/federation%3AgetServers

The application ends up crashing due to api limits.

### Server Setup Information:

- Version of Rocket.Chat Server:  3.6.2
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances:  1
- DB Replicaset Oplog: Enabled
- NodeJS Version:  12.16.1 - x64 
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Chromium Version 85.0.4183.102 (Official Build) snap (64-bit)
- Operating System: Ubuntu 20.04

### Relevant logs:

```
Exception while invoking method public-settings/get Error: Error, too many requests. Please slow down. You must wait 10 seconds before trying again. [too-many-requests]
    at Object.post (app/api/server/v1/misc.js:255:11)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
```

Thank you

**Comment by piotrkochan** [comment]
![](https://i.imgur.com/jDA446c.png)
![](https://i.imgur.com/4hhT1cI.png)

**Comment by alansikora** [comment]
@piotrkochan can you please update to the latest version, `3.6.3`, and check again?

**Comment by piotrkochan** [comment]
@alansikora I'm already on 3.6.3

**Comment by binboum** [comment]
I confirm, same behavior in 3.6.3

**Comment by binboum** [comment]
Hi, same behavior in 3.7.0

![federation_dash](https://user-images.githubusercontent.com/11870307/94685232-68b27380-0329-11eb-90b3-ad4f4ee7db88.png)

**Comment by ankar84** [comment]
That issue cause DDP Rate limiter go crazy when I just open federation dashboard
![image](https://user-images.githubusercontent.com/4023037/95819067-f29d0c00-0d2d-11eb-99c1-c2521e177cc4.png)
![image](https://user-images.githubusercontent.com/4023037/95819077-faf54700-0d2d-11eb-8888-3b20c46dbd31.png)

**Comment by rbrucecel** [comment]
Hello, 
I'm also have this exact issue after the updating from 3.4.x to 3.6.  My log looks exactly like piotrkochan above, same line numbers etc.   I've now updated to 3.7.1 and still the issue exists.   The database migration seems to have worked fine.

**Comment by hugopeixoto** [comment]
I upgraded from 2.4.11 to 3.6.3 and have the same problem.

After taking a look at the code, and knowing that the error occurs in calls to `federation:getOverviewData` and `federation:getServers`, I think that the problem may be in `client/contexts/ServerContext.ts:usePolledMethodData`, as this function is only used for these two calls.

I don't have a local build that I can test this on, but could it be that the `useEffect` cache parameters (`[fetchData, intervalMs]`), are causing the effect to be executed in every frame update? Maybe `fetchData` is not being cached properly and is returning a new function every time?

**Comment by hugopeixoto** [comment]
After some local debugging, I think I found the issue. I opened a PR with the fix: #19386

**Comment by hugopeixoto** [comment]
For anyone not following the PR comments, it seems that this had already been fixed in https://github.com/RocketChat/Rocket.Chat/pull/18520, so I guess it will be included in the next release.
