### ISSUE TITLE
LDAP Sync Error Dup Key on Rocket.chat 3.6.3

### ISSUE THREAD

**Issue by dsisysteme** [RocketChat/Rocket.Chat#19058]
### Description:

When we try to sync rocketchat users from LDAP, only the first user is correctly imported and next we have this error:

```
 Meteor ➔ method joinDefaultChannels -> userId: i5k9xtXfYD6SJdPyf, arguments: [null]
 server.js:204 LDAPSync ➔ error Error creating user BulkWriteError: E11000 duplicate key error collection: rocketchat.rocketchat_subscription index: _id_ dup key: { _id: "49FJC9eXPATix92vx" }
```

1/ FIRST USER CORRECTLY IMPORTED :

```
 LDAP ➔ Connection.info LDAP connected
 LDAP ➔ Bind.info Binding UserDN uid=app,ou=ldapusers,dc=mondomaine,dc=fr
 {"name":"ldapjs","component":"client","hostname":"rocket-2-test","pid":38758,"clazz":"Client","ldap_id":"11__ldap://ldap-test.mondomaine.fr:389","level":20,"msg":"connected after 1 attempt(s)","time":"2020-09-29T12:44:28.810Z","v":0}
 LDAP ➔ Search.info Searching user *
 LDAP ➔ Search.debug searchOptions {
   filter: '(&(uid=*))',
   scope: 'sub',
   sizeLimit: 3,
   paged: { pageSize: 2, pagePause: true }
 }
 LDAP ➔ Search.debug BaseDN ou=accounts,dc=mondomaine,dc=fr
 API ➔ debug Success {
   statusCode: 200,
   body: {
     message: '{"msg":"result","id":"19","result":{"message":"Sync_in_progress","params":[]}}',LDAP Sync Error Dup Key on Rocket.chat 3.6.3
 LDAP ➔ Search.info Page
 LDAPSync ➔ debug userQuery { 'services.ldap.id': '37363831' }
 LDAPSync ➔ debug user.name changed to: Yves maurice dupuid
 LDAPSync ➔ debug New user data { username: 'yves.dupuid', email: 'yves.dupuid@mondomaine.fr' }
 Meteor ➔ method joinDefaultChannels -> userId: K6WEQ94QWjsK8YXFL, arguments: [null]
 Integrations ➔ Outgoing WebHook.debug Execute Trigger: userCreated
 Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: userCreated {
   event: 'userCreated',
   user: {
     _id: 'K6WEQ94QWjsK8YXFL',
     createdAt: 2020-09-29T12:44:29.238Z,
     services: {},
     username: 'yves.dupuid',
     emails: [ [Object] ],
     type: 'user',
     status: 'offline',
     active: true,
     _updatedAt: 2020-09-29T12:44:29.238Z
   }
 }
 Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: __any
 Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event.
 LDAPSync ➔ info Syncing user data
 LDAPSync ➔ debug user { email: 'yves.dupuid@mondomaine.fr', _id: 'K6WEQ94QWjsK8YXFL' }
 LDAPSync ➔ debug ldapUser undefined
 LDAPSync ➔ debug user.name changed to: Yves maurice dupuid
 LDAPSync ➔ debug not syncing user roles
 LDAPSync ➔ debug not syncing groups to channels
 LDAPSync ➔ debug setting {
   "name": "Yves maurice dupuid",
   "emails": [
     {
       "address": "yves.dupuid@mondomaine.fr",
       "verified": true
     }
   ],
   "services.ldap.id": "37363831",
   "services.ldap.idAttribute": "uid",
   "ldap": true
 }
```

With the right data inserted in the mongo database:
```
{ "_id" : "K6WEQ94QWjsK8YXFL", "createdAt" : ISODate("2020-09-29T12:44:29.238Z"), "services" : { "ldap" : { "id" : "37363831", "idAttribute" : "uid" } }, "username" : "yves.dupuid", "emails" : [ { "address" : "yves.dupuid@mondomaine.fr", "verified" : true } ], "type" : "user", "status" : "offline", "active" : true, "_updatedAt" : ISODate("2020-09-29T12:44:29.351Z"), "__rooms" : [ "GENERAL" ], "roles" : [ "user" ], "name" : "Yves maurice Dupuid", "customFields" : {  }, "ldap" : true }
```

But all next users are imported with this error:    
2/ USERS IMPORTED WITH ERROR :

```
LDAPSync ➔ debug userQuery { 'services.ldap.id': '36383530' }
 LDAPSync ➔ debug user.name changed to: Sylvain dupond
 LDAPSync ➔ debug New user data { username: 'sylvain.dupond', email: 'sylvain.dupond@mondomaine.fr' }
 Meteor ➔ method joinDefaultChannels -> userId: i5k9xtXfYD6SJdPyf, arguments: [null]
 server.js:204 LDAPSync ➔ error Error creating user BulkWriteError: E11000 duplicate key error collection: rocketchat.rocketchat_subscription index: _id_ dup key: { _id: "49FJC9eXPATix92vx" }
     at OrderedBulkOperation.handleWriteError (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:1210:11)
     at resultHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:519:23)
     at handler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/replset.js:1204:22)
     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:404:18
     at processTicksAndRejections (internal/process/task_queues.js:75:11)
  => awaited here:
     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
     at DDPCommon.MethodInvocation.<anonymous> (app/authentication/server/startup/index.js:247:19)
     at packages/dispatch_run-as-user.js:211:14
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
     at AccountsServer.<anonymous> (app/authentication/server/startup/index.js:246:11)
     at executeBound (/opt/Rocket.Chat/programs/server/npm/node_modules/underscore/underscore.js:758:67)
     at AccountsServer.bound [as insertUserDoc] (/opt/Rocket.Chat/programs/server/npm/node_modules/underscore/underscore.js:789:14)
     at createUser (packages/accounts-password/password_server.js:1128:27)
     at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1197:10)
     at addLdapUser (app/ldap/server/sync.js:472:29)
     at app/ldap/server/sync.js:538:5
     at Array.forEach (<anonymous>)
     at app/ldap/server/sync.js:505:13
     at runWithEnvironment (packages/meteor.js:1286:24) {
   index: 0,
   code: 11000,
   errmsg: 'E11000 duplicate key error collection: rocketchat.rocketchat_subscription index: _id_ dup key: { _id: "49FJC9eXPATix92vx" }',
   op: {
     open: true,
     alert: true,
     unread: 1,
     userMentions: 1,
     groupMentions: 0,
     ts: 2020-09-29T12:44:29.369Z,
     rid: 'GENERAL',
     name: 'general',
     fname: undefined,
     customFields: undefined,
     t: 'c',
     u: {
       _id: 'i5k9xtXfYD6SJdPyf',
       username: 'sylvain.dupond',
       name: undefined
     },
     _updatedAt: 2020-09-29T12:44:29.370Z,
     _id: '49FJC9eXPATix92vx'
   },
   name: 'BulkWriteError',
   driver: true,
   err: {
     index: 0,
     code: 11000,
     errmsg: 'E11000 duplicate key error collection: rocketchat.rocketchat_subscription index: _id_ dup key: { _id: "49FJC9eXPATix92vx" }',
     op: {
       open: true,
       alert: true,
       unread: 1,
       userMentions: 1,
       groupMentions: 0,
       ts: 2020-09-29T12:44:29.369Z,
       rid: 'GENERAL',
       name: 'general',
       fname: undefined,
       customFields: undefined,
       t: 'c',
       u: [Object],
       _updatedAt: 2020-09-29T12:44:29.370Z,
       _id: '49FJC9eXPATix92vx'
     }
   },
   result: BulkWriteResult {
     result: {
       ok: 1,
       writeErrors: [Array],
       writeConcernErrors: [],
       insertedIds: [Array],
       nInserted: 0,
       nUpserted: 0,
       nMatched: 0,
       nModified: 0,
       nRemoved: 0,
       upserted: [],
       lastOp: [Object]
     }
   },
   [Symbol(mongoErrorContextSymbol)]: {}
 }
```

If we check inside the mongo database, we can see users inserted with fields missing  ("__rooms", "roles",  "ldap")
```
{ "_id" : "i5k9xtXfYD6SJdPyf", "createdAt" : ISODate("2020-09-29T12:44:29.360Z"), "services" : {  }, "username" : "sylvain.dupond", "emails" : [ { "address" : "sylvain.dupond@mondomaine.fr", "verified" : false } ], "type" : "user", "status" : "offline", "active" : true, "_updatedAt" : ISODate("2020-09-29T12:44:29.361Z") }
```

Following this link to view another people have more or less the same issue:

https://forums.rocket.chat/t/imported-ldap-users-have-no-role/8021

### Steps to reproduce:

1. Execute LDAP synchronization

### Expected behavior:

All accounts correctly add to the database with no missing fields

### Actual behavior:

Accounts inserted with missing fileds ("__rooms", "roles",  "ldap")

### Server Setup Information:

- Version of Rocket.Chat Server: Rocket.Chat 3.6.3
- Operating System: Linux Debian Buster
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: RS01
- NodeJS Version: v12.14.0
- MongoDB Version: 4.2.9

### Client Setup Information

- Desktop App or Browser Version: Chrome 85.0.4183.121
- Operating System: Ubuntu 18.04

### Relevant logs:

```
 Meteor ➔ method joinDefaultChannels -> userId: i5k9xtXfYD6SJdPyf, arguments: [null]
 server.js:204 LDAPSync ➔ error Error creating user BulkWriteError: E11000 duplicate key error collection: rocketchat.rocketchat_subscription index: _id_ dup key: { _id: "49FJC9eXPATix92vx" }
```

Kind regards

**Comment by semack** [comment]
@pierre-lehnen-rc could you tell please, any progress on this issue? It's a blocker for many users who use LDAP to update RC to the latest version. :(
