### ISSUE TITLE
Upload avatar to private channel always show old avatar.

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat#19066]
### Description:

I updated rocket.chat 3.7.0. I has set upload new avatar to private channel. I has click save it.But it's always show old avatar.

### Steps to reproduce:

1. click private channel information.
2. choose avatar and upload it.
3. It's show old avatar image.

### Expected behavior:

It's should show new avatar.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enable
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: 2.17.11
- Operating System: Win10

**Comment by gabriellsh** [comment]
This may be due to cache. Did it change after some time?

**Comment by tharzeez** [comment]
Hey @gabriellsh , I would like to work on this, seems like the issue is with cache

**Comment by gabriellsh** [comment]
Sure. Just remember, this is open source, no need to ask for issues ;)

**Comment by tharzeez** [comment]
@akong77 i tried to reproduce your steps, but its showing the uploaded image for the private channel. I tried using Rocket.chat 3.7 and Rocket.chat 3.8.

**Comment by akong77** [comment]
If this cache problem.Could auto clear cache when upload new avatar.Or how to clear cache in app?

**Comment by akong77** [comment]
I upload my friend screenshot on word file.Please see this attachment.I has set avatar cache time to zero.But it's always show old.
[Doc1.docx](https://github.com/RocketChat/Rocket.Chat/files/5337884/Doc1.docx)

**Comment by tharzeez** [comment]
I have tested this chrome and firefox.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24750567/95323999-acbeee80-08bc-11eb-87ef-2ed7a41eb7aa.gif)

**Comment by gabriellsh** [comment]
@akong77 I don't think it's a cache problem, if it didn't update yet. Can you send logs from the console and/or server after trying to upload again? Also, please send screenshots directly on the comment, no need to put it in a word file. Thanks!

**Comment by akong77** [comment]
I got follow error:
`Oct 12 13:38:16 chat rocketchat[32669]: Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined
Oct 12 13:38:16 chat rocketchat[32669]:     at app/lib/server/functions/setRoomAvatar.js:34:46
Oct 12 13:38:16 chat rocketchat[32669]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Oct 12 13:38:16 chat rocketchat[32669]:     at packages/meteor.js:550:25
Oct 12 13:38:16 chat rocketchat[32669]:     at runWithEnvironment (packages/meteor.js:1286:24)`
What's this problem?

**Comment by cprice-kgi** [comment]
i've uploaded a PR today that should resolve this for you:
https://github.com/RocketChat/Rocket.Chat/pull/19340

**Comment by LeeThompson** [comment]
Seeing a variation of this with 3.12.0 (MongoDBb 4.4.4 / wiredTiger with oplog Enabled; running in docker container).

1. I created a new channel
2. I uploaded an avatar
3. Avatar does not appear

If I go to change the avatar, the one I uploaded shows in the Info/Edit for the channel but _nowhere_ else.

![temp-markup](https://user-images.githubusercontent.com/1982261/110188961-6cfc2480-7dd2-11eb-884b-56f9d59999a6.png)

**Comment by AdityaRaut13** [comment]
I am not able to reproduce this issue.

**Comment by himani-mehra** [comment]
Hi @akong77  , I would love to take on this issue and contribute to the project. Could you please assign it to me if it's available? Looking forward to your response. Thanks!
