### ISSUE TITLE
[Bug] Download user data builds corrupted zip file

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat#19139]
# Description:

`Download user data` functionality does not work, it generates and sends .zip which is corrupted.

### Steps to reproduce:

1. Generate user data in user preferences
2. Receive e-mail
3. Download
4. Zip can't be opened, extracted (also seems too small)
5. Extra: in client - click generate again, there is popup with 'click here to download file' and it does not work until right click - open in new window.

### Expected behavior:

Full, working history on email.

### Actual behavior:

Described in `Description` above.

### Server Setup Information:

- Version of Rocket.Chat Server:  3.6.3
- Operating System: Ubuntu 16
- Deployment Method: tar
- Number of Running Instances:  1
- DB Replicaset Oplog: yes
- NodeJS Version: 12
- MongoDB Version: 4

### Client Setup Information

- Desktop App or Browser Version: 4
- Operating System: Ubuntu

### Relevant logs:

A lot of logs like below shows up:

```
I20201006-11:38:02.965(2) Exception in callback of async function: TypeError: Cannot read property 'description' of undefined     at exportMessageObject (app/user-data-download/server/cronProcessDownloads.js:207:34)     at app/user-data-download/server/cronProcessDownloads.js:245:24     at runWithEnvironment (packages/meteor.js:1286:24)     at packages/meteor.js:1299:14     at Array.forEach (<anonymous>)     at app/user-data-download/server/cronProcessDownloads.js:238:10     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 
I20201006-11:38:02.966(2) Exception in callback of async function: TypeError: Cannot read property 'description' of undefined     at exportMessageObject (app/user-data-download/server/cronProcessDownloads.js:207:34)     at app/user-data-download/server/cronProcessDownloads.js:245:24     at runWithEnvironment (packages/meteor.js:1286:24)     at packages/meteor.js:1299:14     at Array.forEach (<anonymous>)     at app/user-data-download/server/cronProcessDownloads.js:238:10     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 
```

**Comment by piotrkochan** [comment]
log output similar to #17714
