### ISSUE TITLE
[BUG] Livechat: Forward to user (duplicate key error)

### ISSUE THREAD

**Issue by Floflobel** [RocketChat/Rocket.Chat#19221]
### Description:

The user is not currently served by anyone but when I try to assign a user it returns an error.

This problem is only on one user for the others I have no problem. 

### Steps to reproduce:

1. Click on `Visitor Info` of live chat room
1. Click on `Forward`
1. Select a user from `Forward to user` dropdown.
1. Click on Forward

### Actual behavior:

Internal server error

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Ubuntu 20.04 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: 3.0.1
- Operating System: Fedora

### Relevant logs:

```Oct 12 12:00:02 chat rocketchat-server.rocketchat-server[1004]: Exception while invoking method 'livechat:transfer' BulkWriteError: E11000 duplicate key error collection: parties.rocketchat_subscription index: rid
_1_u._id_1 dup key: { : "2Peb4uTn55omQ4vrQ", : "rycfuynxsv2EBbwYD" }
Oct 12 12:00:02 chat rocketchat-server.rocketchat-server[1004]:     at OrderedBulkOperation.handleWriteError (/snap/rocketchat-server/1442/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib
/bulk/common.js:1210:11)
Oct 12 12:00:02 chat rocketchat-server.rocketchat-server[1004]:     at resultHandler (/snap/rocketchat-server/1442/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:519:23)
Oct 12 12:00:02 chat rocketchat-server.rocketchat-server[1004]:     at /snap/rocketchat-server/1442/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:404:18
Oct 12 12:00:02 chat rocketchat-server.rocketchat-server[1004]:     at processTicksAndRejections (internal/process/task_queues.js:79:11)
Oct 12 12:00:02 chat rocketchat-server.rocketchat-server[1004]:  => awaited here:
Oct 12 12:00:02 chat rocketchat-server.rocketchat-server[1004]:     at Function.Promise.await (/snap/rocketchat-server/1442/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_serve
r.js:56:12)
Oct 12 12:00:02 chat rocketchat-server.rocketchat-server[1004]:     at app/livechat/server/lib/Helper.js:253:17
Oct 12 12:00:02 chat rocketchat-server.rocketchat-server[1004]:     at /snap/rocketchat-server/1442/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Oct 12 12:00:21 chat rocketchat-server.rocketchat-server[1004]: Error: ESOCKETTIMEDOUT
Oct 12 12:00:21 chat rocketchat-server.rocketchat-server[1004]:     at ClientRequest.<anonymous> (/snap/rocketchat-server/1442/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:816:19)
Oct 12 12:00:21 chat rocketchat-server.rocketchat-server[1004]:     at Object.onceWrapper (events.js:417:28)
Oct 12 12:00:21 chat rocketchat-server.rocketchat-server[1004]:     at ClientRequest.emit (events.js:311:20)
Oct 12 12:00:21 chat rocketchat-server.rocketchat-server[1004]:     at ClientRequest.EventEmitter.emit (domain.js:482:12)
Oct 12 12:00:21 chat rocketchat-server.rocketchat-server[1004]:     at TLSSocket.emitRequestTimeout (_http_client.js:714:9)
Oct 12 12:00:21 chat rocketchat-server.rocketchat-server[1004]:     at Object.onceWrapper (events.js:417:28)
Oct 12 12:00:21 chat rocketchat-server.rocketchat-server[1004]:     at TLSSocket.emit (events.js:311:20)
Oct 12 12:00:21 chat rocketchat-server.rocketchat-server[1004]:     at TLSSocket.EventEmitter.emit (domain.js:482:12)
Oct 12 12:00:21 chat rocketchat-server.rocketchat-server[1004]:     at TLSSocket.Socket._onTimeout (net.js:478:8)
Oct 12 12:00:21 chat rocketchat-server.rocketchat-server[1004]:     at listOnTimeout (internal/timers.js:549:17)
```

**Comment by KevLehman** [comment]
This pull request has been inactive for a while, so we’re closing it to keep the backlog manageable.
If you’d like to continue working on it, feel free to reopen or submit a new PR. Thanks for the contribution!
