### ISSUE TITLE
Exception while invoking method cloud:checkRegisterStatus and Exception while invoking method autoTranslate.getSupportedLanguages

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#19260]
### Description:
The following error messages appear when starting Rocket Chat server after a fresh server reboot (or on (re)starting the Rocket Chat service). We have imported Slack messages.

### Steps to reproduce:

1. Start Rocket Chat server/service
2. Look in log

### Expected behavior:

Start up with no errors.

### Actual behavior:

Errors appear in the log:

![Capture](https://user-images.githubusercontent.com/1122344/96115471-ba1a4f80-0f32-11eb-83a9-04385c0d82ca.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method: TAR, manual
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: Desktop App 2.17.11 and Browsers Firefox and Vivaldi
- Operating System: Linux Mint 19.3 and Windows 10

### Additional context

Not at the moment.

### Relevant logs:

```
I20201015-21:37:48.448(11) Exception while invoking method cloud:checkRegisterStatus Error: Not authorized [error-not-authorized]     at MethodInvocation.cloud:checkRegisterStatus (app/cloud/server/methods.js:24:10)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20201015-21:37:48.456(11) Exception while invoking method autoTranslate.getSupportedLanguages Error: Auto-Translate is not allowed [error-action-not-allowed]     at MethodInvocation.autoTranslate.getSupportedLanguages (app/autotranslate/server/methods/getSupportedLanguages.js:10:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9
```

**Comment by wolfcreative** [comment]
Analogous situation

![image](https://user-images.githubusercontent.com/29209797/96129638-5121e000-0f10-11eb-8ae9-05f0b1b72a39.png)
