### ISSUE TITLE
Cannot upload avatar on 3.7.1

### ISSUE THREAD

**Issue by DHCrafty** [RocketChat/Rocket.Chat#19295]
### Steps to reproduce:

1. Go to user 'My Account' section
2. Click on upload Avatar and choose image
3. Click Open and then Save

### Expected behavior:

Avatar to upload and show as user's avatar.

### Actual behavior:

Message that profile saved but when reload page it just goes back to default avatar.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System:  CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.14
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Desktop App
- Operating System: Windows 10

### Additional context

Error on server is "Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined  at app/lib/server/functions/setUserAvatar.js:66:50  at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)  at packages/meteor.js:550:25  at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by cprice-kgi** [comment]
integrating this should resolve your issue:
https://github.com/RocketChat/Rocket.Chat/pull/18841

**Comment by KevLehman** [comment]
Should be fixed
