### ISSUE TITLE
[BUG] Deactivate via REST API inconsistent 

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#19307]
### Description:

I'm using [REST API scripts](https://forums.rocket.chat/t/ldap-auth-disabled-ad-users/1715/11) to get userId and deactivate user in a moment when that user is disabled in Active Directory
I see that result of scripts using REST API is inconsistent - some users get deactivated without any issues, but sometimes script finishes with 400 error:
```
[2020.08.31 05:38:36][Error] Error: The remote server returned an error: (400) Bad Request.
[2020.08.31 05:38:36][Info] RC_UserID : System.Net.WebException: The remote server returned an error: (400) Bad Request.
at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
```
I try to deactivate user, that get error in script - and I successfully deactivated him in Admin UI

### Steps to reproduce:

1. Try to deactivate user via REST API
2. Get 400 error sometimes

### Expected behavior:

Consistent working of deactivate script

### Actual behavior:

Some REST API deactivations stops with 400 error

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version:4.0.17

### Client Setup Information

- Desktop App or Browser Version: Chrome 85
- Operating System: Windows 10

### Additional context

I see this now on 3.6.3 server version, but we checked logs, and see that it was on 3.1.1 before upgrade

### Relevant logs:

```
[2020.08.31 05:38:36][Error] Error: The remote server returned an error: (400) Bad Request.
[2020.08.31 05:38:36][Info] RC_UserID : System.Net.WebException: The remote server returned an error: (400) Bad Request.
at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
```

**Comment by ankar84** [comment]
> Do you have any logs from the Rocket.Chat side?

I did this -In Kibana from HAProxy logs get 400 response current time, and then checked RC logs in that time - nothing.
What can I do to debug that issue?

**Comment by ankar84** [comment]
@pierre-lehnen-rc that issue is still reproducible on users who gets error or script deactivate.
Now I try to deactivate that users by scripts by manually launcing them with my personal admin token - and still 400 error.
First I thought maybe data for that accounts is too large for some reverse proxies on network path and cleared couple of large attributes like `keycloak` and `ldap` - no luck
Now I think, that problem could be in rooms.
Here is en example of rooms of one users with problem
```
"__rooms" : [
                "3fnXHdmiFEariP23N",
                "aWhYSTcZooypbEbkJ",
                "Ht6qviY3AxvefrCNX",
                "ZmZmv9Z3XqoyMTYuZ",
                "FmooDnEQCCHBsdueZ",
                "HWxiaiiLud7bTCcCr",
                "zPtcTpJzrCJAgk5ZX",
                "4BnZDoWdPbuyGCcdA",
                "kej9Mn8rYH74mpcD7",
                "uPa9ETP7cwDGAJLdY",
                "f8ZJzpaB3GgdPRzwG",
                "DbG47BmXyckqgx8Lt",
                "J5myvqRNWiuE3mCMc",
                "wpygefTzbYnR53dnA",
                "LPNqxFX4KpaWYLJr7",
                "yHFDALEiczRc6JNAn",
                "NZ9zcFxjdoYYwPeY6",
                "Zpmc3qxCu7PDqH55j",
                "xgcY8vCAPZgDAGJFo",
                "6mkv7tvrJAmi4AJrR",
                "BqucKbbuTtLwDSqPy",
                "mxdGcssusr7Q5nsny",
                "PEwZDykzPh7ePDGYD",
                "CGf9hdPvw885vy8hs",
                "hXgb2F54JGHc84GxL",
                "7hQg6ew7yNKA4ShkF",
                "5W2uXEkb5njBwPLfN",
                "erMPed4QPB5nGXuea",
                "fh5CgKwes9REFwuo5",
                "dGRZ3fbwbH8gBPmnq",
                "84KNdmuqEYis26JTJ",
                "5uDcmxyKskENnBkGF",
                "X6tQLCskzujsmmpdc",
                "MwaauHFGTTRihasFM",
                "krMyqYPX6ox5fpi4d",
                "ruZxCk5pQRj4c7Dnn",
                "bhDwpeLq7fd5yNcor",
                "eDfXqZRceqzh6AbcN"
        ],
```
Maybe that array to large for REST API?

**Comment by ankar84** [comment]
No

**Comment by ankar84** [comment]
And here is a deactivate attempt in Admin UI
![image](https://user-images.githubusercontent.com/4023037/96680735-c2351d80-137e-11eb-9c63-21e76d88c5c2.png)

**Comment by ankar84** [comment]
I activate that user again in Admin UI and try to deactivate via REST API by powershell script again. And now all fine! I get true, and not 400 Bad Request.
I don't know how to fix that.
Maybe @sampaiodiego can clarify that?
Now I have about 100 problematic users like that, so I can try to fix in a various ways ;)

**Comment by ankar84** [comment]
Confirmed that if I deactivate user in Admin UI then deactivate script via REST API start to work normally on another user.
How do Admin UI deactivate user? Not via REST API in fact?

**Comment by ankar84** [comment]
Just deactivated in Admin UI another user and according mongodb document for that user changed only 2 fields: `"active"` and `"_updatedAt" ` which is really logical.
So, I'm almost 100% sure, that ussie itself not in user with it's attributes, but in all room, that user created and where he is only one owner.
In Admin UI I see this:
![image](https://user-images.githubusercontent.com/4023037/96685121-5904d880-1385-11eb-8d00-ea84b62d6cbf.png)
And I believe that is a root cause for that error - REST API could not reassign new owner for deactivated user rooms so it return 400 error. Admin UI can do that easily.
@pierre-lehnen-rc what do you think?

**Comment by pierre-lehnen-rc** [comment]
If that was the cause you should get a 'user-last-owner' error, but I'll try to replicate the situation here.

**Comment by ankar84** [comment]
> If that was the cause you should get a 'user-last-owner' error, but I'll try to replicate the situation here.

Yes, please test it, it's really easy to replicate.
For now it is a bit security issue for us, because we deactivate users in RC in moment of disable user in LDAP (when user 
resigns the Company). User should lost access to Rocket Chat in that moment.

**Comment by ankar84** [comment]
Just tested that bug in a pure docker image of version 3.7.1 in test environment
![image](https://user-images.githubusercontent.com/4023037/96829115-90d15600-1441-11eb-9a7d-281d1dcbf2c0.png)
`Удаленный сервер возвратил ошибку: (400) Недопустимый запрос.`

**Comment by ankar84** [comment]
I think issue could be here in these two lines 
https://github.com/RocketChat/Rocket.Chat/blob/287d1dcb376a4613c9c2d6f5b9c22f3699891d2e/app/api/server/v1/users.js#L471-L472

**Comment by ankar84** [comment]
Full solution for me https://forums.rocket.chat/t/ldap-auth-disabled-ad-users/1715/14
But I think, that if `users.update` have ability to deactivate user it should bi fixed.
Or it should be 2 separate functions (endpoints) - so, deactivate function must be removed from `users.update` in that case.
