### ISSUE TITLE
ENOENT error message, user-data-downloads/cronProcessDownloads.js

### ISSUE THREAD

**Issue by cprice-kgi** [RocketChat/Rocket.Chat#19317]
### Description:

These log messages keep appearing, and seem to be related to the user data download. We had this functionality turned on for a bit, and I think a few people may have actually attempted to use it. Eventually, we turned it off. Now, though, we still see this message repeating in the log file, which seems like the cron is trying to process a (stuck?) user data download operation over and over again.

If this is the case, I'd be interested to know how to kill this operation so the log message will not appear any longer. We have restarted the RC service several times, and this message comes back each time.

### Steps to reproduce:

1. Look in the Rocket.Chat server logs and you will observe this message repeating at regular intervals.

### Expected behavior:

I would expect not to see this message.

### Actual behavior:

you will observe this message repeating at regular intervals

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0
- Operating System: RedHat
- Deployment Method: tar
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: OSX

### Relevant logs:

```
Oct 21 13:32:00 ip-172-31-43-120 rocketchat: Error: ENOENT: no such file or directory, open '/tmp/userData/ngMZFJPZhQaJqTsMe/user.html'
Oct 21 13:32:00 ip-172-31-43-120 rocketchat: at Object.openSync (fs.js:457:3)
Oct 21 13:32:00 ip-172-31-43-120 rocketchat: at Object.writeFileSync (fs.js:1282:35)
Oct 21 13:32:00 ip-172-31-43-120 rocketchat: at startFile (app/user-data-download/server/cronProcessDownloads.js:35:5)
Oct 21 13:32:00 ip-172-31-43-120 rocketchat: at generateUserFile (app/user-data-download/server/cronProcessDownloads.js:421:2)
Oct 21 13:32:00 ip-172-31-43-120 rocketchat: at app/user-data-download/server/cronProcessDownloads.js:488:4
Oct 21 13:32:00 ip-172-31-43-120 rocketchat: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
Oct 21 13:32:00 ip-172-31-43-120 rocketchat: errno: -2,
Oct 21 13:32:00 ip-172-31-43-120 rocketchat: syscall: 'open',
Oct 21 13:32:00 ip-172-31-43-120 rocketchat: code: 'ENOENT',
Oct 21 13:32:00 ip-172-31-43-120 rocketchat: path: '/tmp/userData/ngMZFJPZhQaJqTsMe/user.html'
Oct 21 13:32:00 ip-172-31-43-120 rocketchat: }
Oct 21 13:32:27 ip-172-31-43-120 dhclient[2745]: XMT: Solicit on eth0, interval 110050ms.
Oct 21 13:34:00 ip-172-31-43-120 rocketchat: Error: ENOENT: no such file or directory, open '/tmp/userData/ngMZFJPZhQaJqTsMe/user.html'
Oct 21 13:34:00 ip-172-31-43-120 rocketchat: at Object.openSync (fs.js:457:3)
Oct 21 13:34:00 ip-172-31-43-120 rocketchat: at Object.writeFileSync (fs.js:1282:35)
Oct 21 13:34:00 ip-172-31-43-120 rocketchat: at startFile (app/user-data-download/server/cronProcessDownloads.js:35:5)
Oct 21 13:34:00 ip-172-31-43-120 rocketchat: at generateUserFile (app/user-data-download/server/cronProcessDownloads.js:421:2)
Oct 21 13:34:00 ip-172-31-43-120 rocketchat: at app/user-data-download/server/cronProcessDownloads.js:488:4
Oct 21 13:34:00 ip-172-31-43-120 rocketchat: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
Oct 21 13:34:00 ip-172-31-43-120 rocketchat: errno: -2,
Oct 21 13:34:00 ip-172-31-43-120 rocketchat: syscall: 'open',
Oct 21 13:34:00 ip-172-31-43-120 rocketchat: code: 'ENOENT',
Oct 21 13:34:00 ip-172-31-43-120 rocketchat: path: '/tmp/userData/ngMZFJPZhQaJqTsMe/user.html'
Oct 21 13:34:00 ip-172-31-43-120 rocketchat: }
Oct 21 13:34:17 ip-172-31-43-120 dhclient[2745]: XMT: Solicit on eth0, interval 114950ms.
```

**Comment by sennewood** [comment]
Still a problem with 3.11.2

**Comment by ICarryTheDustOfAJourney** [comment]
Having same problem with  V4.5.1 on an Ubuntu 20.04 installed as snap.

/tmp/userData/ doesn't exist (/tmp/snap.rocketchat-server/tmp/userData/)

**Comment by UAnton** [comment]
Same problem on RC 5.3.0, Ubuntu 22.04

**Comment by xavpie** [comment]
Same problem in version 5.3.4 with swarm cluster.

**Comment by krakazyabra** [comment]
RC v6.1.2, helm chart v6.1.2
Problem is still here.

**Comment by finkyseb** [comment]
Nobody takes a look to this issue ?
The service is up, but this logs generate useless noise. 
Thanks.

**Comment by UAnton** [comment]
> 

RC dev wants only $$$ and doesn't want to resolve problems.
