### ISSUE TITLE
CursorNotFound on LDAP import

### ISSUE THREAD

**Issue by bellegarde-c** [RocketChat/Rocket.Chat#19426]
### Description:

LDAP import fails to finish

### Steps to reproduce:

1. Run LDAP import

### Expected behavior:

No crash

### Actual behavior:

Crash

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: Debian 10
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  ??
- NodeJS Version: 12.18.1-1nodesource1
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:
```

nov. 01 00:38:58 srv-rocket-test rocketchat[15817]: server.js:204 LDAP ➔ Connection.info Disconecting
nov. 01 00:38:58 srv-rocket-test rocketchat[15817]: server.js:204 LDAP ➔ Search.info Idle
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]: }
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:   name: 'MongoError'
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:   },
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     signature: { hash: [Binary], keyId: 0 }
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 12, high_: 1604187535 },
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:   '$clusterTime': {
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:   codeName: 'CursorNotFound',
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:   code: 43,
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:   ok: 0,
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 12, high_: 1604187535 },
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at packages/ddp-server/livedata_server.js:559:43 {
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at new Promise (<anonymous>)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at packages/ddp-server/livedata_server.js:715:46
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at packages/ddp-server/livedata_server.js:717:46
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at packages/ddp-server/livedata_server.js:719:19
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at MethodInvocation.ldap_sync_now (app/ldap/server/syncUsers.js:24:3)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at sync (app/ldap/server/sync.js:574:10)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1136:22)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1122:38)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promis
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:  => awaited here:
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at packages/mongo/mongo_driver.js:1073:14
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promi
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:  => awaited here:
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Socket.Readable.push (_stream_readable.js:224:10)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at readableAddChunk (_stream_readable.js:290:11)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at addChunk (_stream_readable.js:309:12)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Socket.EventEmitter.emit (domain.js:475:20)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Socket.emit (events.js:210:5)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Socket.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/co
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at processMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/c
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Connection.EventEmitter.emit (domain.js:475:20)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Connection.emit (events.js:210:5)
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]:     at Connection.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/li
nov. 01 00:38:57 srv-rocket-test rocketchat[15817]: server.js:204 LDAPSync ➔ error MongoError: cursor id 1850802509835155859 not found

```

**Comment by bellegarde-c** [comment]
Looks like an issue with groups name length.

Failing channel map:
```
  "rocketchat-gea-dut-fi-s1-2020-td4": [
		"gea-dut-s1-td4"
	]
```
After renaming the group, it works without the CursorNotFound issue.
```
  "gea-dut-s1-td4": [
		"gea-dut-s1-td4"
	]
```

**Comment by bellegarde-c** [comment]
Related to this ? 

https://docs.mongodb.com/manual/reference/method/cursor.noCursorTimeout/#cursor.noCursorTimeout

**Comment by bellegarde-c** [comment]
This have fixed my issue:

`db.adminCommand( { setParameter: 1, cursorTimeoutMillis: 3600000 } )`

**Comment by paulopera** [comment]
> This has fixed my issue:
> 
> `db.adminCommand( { setParameter: 1, cursorTimeoutMillis: 3600000 } )`

This procedure has fixed my issue too, where LDAP import fails to finish.
Deployment Method: Docker
Version: 3.17.0
Apps Engine Version: 1.27.1
Node Version: v12.22.1
Database Migration: 228 (August 6, 2021 6:47 AM)
MongoDB: 4.0.24 / mmapv1 (oplog Enabled)
Operating System: Ubuntu 18.04.5 LTS
Number of Running Instances: 1
