### ISSUE TITLE
LDAP Group Channel Map: crash if too large

### ISSUE THREAD

**Issue by bellegarde-c** [RocketChat/Rocket.Chat#19425]
### Description:

When running a sync with a real large channel map (more than 500 lines), the LDAP sync fails.
With a smaller map, all is working as expected.

### Steps to reproduce:

- Groups filter: (&(cn=#{groupName})(member=CN=#{username},OU=*))

1. Add a real big LDAP Group Channel Map
2.  Run sync

### Expected behavior:

Do not crash

### Actual behavior:

Crash

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: Debian 10
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  ??
- NodeJS Version: 12.18.1-1nodesource1
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

```
Oct 31 17:11:15 srv-rocket rocketchat[106]: server.js:204 LDAPSync ➔ error LDAPError [StrongAuthRequiredError]: BindSimple: Transport encryption required.
Oct 31 17:11:15 srv-rocket rocketchat[106]:     at messageCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)
Oct 31 17:11:15 srv-rocket rocketchat[106]:     at Parser.onMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)
Oct 31 17:11:15 srv-rocket rocketchat[106]:     at Parser.emit (events.js:210:5)
Oct 31 17:11:15 srv-rocket rocketchat[106]:     at Parser.EventEmitter.emit (domain.js:475:20)
Oct 31 17:11:15 srv-rocket rocketchat[106]:     at Parser.write (/opt/Rocket.Chat/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)
Oct 31 17:11:15 srv-rocket rocketchat[106]:     at Socket.onData (/opt/Rocket.Chat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)
Oct 31 17:11:15 srv-rocket rocketchat[106]:     at Socket.emit (events.js:210:5)
Oct 31 17:11:15 srv-rocket rocketchat[106]:     at Socket.EventEmitter.emit (domain.js:475:20)
Oct 31 17:11:15 srv-rocket rocketchat[106]:     at addChunk (_stream_readable.js:309:12)
Oct 31 17:11:15 srv-rocket rocketchat[106]:     at readableAddChunk (_stream_readable.js:290:11)
Oct 31 17:11:15 srv-rocket rocketchat[106]:     at Socket.Readable.push (_stream_readable.js:224:10)
Oct 31 17:11:15 srv-rocket rocketchat[106]:     at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
Oct 31 17:11:15 srv-rocket rocketchat[106]:   lde_message: 'BindSimple: Transport encryption required.',
Oct 31 17:11:15 srv-rocket rocketchat[106]:   lde_dn: null
Oct 31 17:11:15 srv-rocket rocketchat[106]: }
```

**Comment by bellegarde-c** [comment]
BTW, the channel mapping code looks not optimal. It should get groups content on start and then compare this for every available user.

Actually, looks like it is doing one LDAP request per user and per group. 

But I may be wrong as I guess this based on the logs.

**Comment by bellegarde-c** [comment]
Tried to do a sync with a smaller version of the map (and it worked) and then added the rest of the map, but now I have another issue :-(

```
oct. 31 18:31:13 srv-rocket rocketchat[106]: }
oct. 31 18:31:13 srv-rocket rocketchat[106]:   name: 'MongoError'
oct. 31 18:31:13 srv-rocket rocketchat[106]:   },
oct. 31 18:31:13 srv-rocket rocketchat[106]:     signature: { hash: [Binary], keyId: 0 }
oct. 31 18:31:13 srv-rocket rocketchat[106]:     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1604165472 },
oct. 31 18:31:13 srv-rocket rocketchat[106]:   '$clusterTime': {
oct. 31 18:31:13 srv-rocket rocketchat[106]:   codeName: 'CursorNotFound',
oct. 31 18:31:13 srv-rocket rocketchat[106]:   code: 43,
oct. 31 18:31:13 srv-rocket rocketchat[106]:   ok: 0,
oct. 31 18:31:13 srv-rocket rocketchat[106]:   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1604165472 },
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at packages/ddp-server/livedata_server.js:559:43 {
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at new Promise (<anonymous>)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at packages/ddp-server/livedata_server.js:715:46
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at packages/ddp-server/livedata_server.js:717:46
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at packages/ddp-server/livedata_server.js:719:19
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at MethodInvocation.ldap_sync_now (app/ldap/server/syncUsers.js:24:3)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at sync (app/ldap/server/sync.js:574:10)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1136:22)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1122:38)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_serve
oct. 31 18:31:13 srv-rocket rocketchat[106]:  => awaited here:
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at packages/mongo/mongo_driver.js:1073:14
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/prom
oct. 31 18:31:13 srv-rocket rocketchat[106]:  => awaited here:
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at Socket.Readable.push (_stream_readable.js:224:10)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at readableAddChunk (_stream_readable.js:290:11)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at addChunk (_stream_readable.js:309:12)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at Socket.EventEmitter.emit (domain.js:475:20)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at Socket.emit (events.js:210:5)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at Socket.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/conn
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at processMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connecti
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at Connection.EventEmitter.emit (domain.js:475:20)
oct. 31 18:31:13 srv-rocket rocketchat[106]:     at Connection.emit (events.js:210:5)
```

**Comment by bellegarde-c** [comment]
Another variant

```
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]: server.js:204 LDAP ➔ Search.error LDAPError [OperationsError]: 00002020: Operation unavailable without authentication
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:     at messageCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:     at Parser.onMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:     at Parser.emit (events.js:210:5)
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:     at Parser.EventEmitter.emit (domain.js:475:20)
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:     at Parser.write (/opt/Rocket.Chat/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:     at Socket.onData (/opt/Rocket.Chat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:     at Socket.emit (events.js:210:5)
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:     at Socket.EventEmitter.emit (domain.js:475:20)
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:     at addChunk (_stream_readable.js:309:12)
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:     at readableAddChunk (_stream_readable.js:290:11)
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:     at Socket.Readable.push (_stream_readable.js:224:10)
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:     at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:   lde_message: '00002020: Operation unavailable without authentication',
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]:   lde_dn: null
oct. 31 22:46:05 srv-rocket-test rocketchat[15817]: }

```

**Comment by bellegarde-c** [comment]
Ok, moving from STARTTLS 389 to TLS/SSL 636 fixed the issue. Any reason ?
