### ISSUE TITLE
Hubot not compatible with 3.8.0-rc.2

### ISSUE THREAD

**Issue by JoJo2406** [RocketChat/Rocket.Chat#19432]
### Description:

Since upgrading Rocket Chat from 3.7.1 to 3.8.0-rc.2 the integration between rocket chat and our hubot instance no longer works. Every time the bot receives a message the following exception is thrown `ERROR TypeError: Cannot read property '_id' of undefined` (see below).

### Steps to reproduce
I have replicated this by creating a new basic project with only the dependencies below and run the command `hubot ping` and will still get the below exception.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0-rc.2
- Operating System: Ubuntu 20.04.1 LTS
- Deployment Method: Manual
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: v12.18.4
- MongoDB Version: v4.0.21

### Actual behavior
See below

### Additional context

From package.json

```json
  "dependencies": {
    "hubot-diagnostics": "^1.0.0",
    "hubot-help": "^1.0.1",
    "hubot": "^3.3.2",
    "hubot-rocketchat": "2.0.0"
  }
```

### Relevant logs:

[Mon Nov 02 2020 11:05:05 GMT+0000 (Greenwich Mean Time)] ERROR TypeError: Cannot read property '_id' of undefined
  at Object.<anonymous> (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\hubot-rocketchat\node_modules\@rocket.chat\sdk\dist\lib\driver.js:374:23)
  at Generator.next (<anonymous>:null:null)
  at D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\hubot-rocketchat\node_modules\@rocket.chat\sdk\dist\lib\driver.js:7:71
  at new Promise (<anonymous>:null:null)
  at __awaiter (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\hubot-rocketchat\node_modules\@rocket.chat\sdk\dist\lib\driver.js:3:12)
  at D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\hubot-rocketchat\node_modules\@rocket.chat\sdk\dist\lib\driver.js:368:45
  at ReactiveQuery.<anonymous> (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\hubot-rocketchat\node_modules\@rocket.chat\sdk\dist\lib\driver.js:344:17)
  at D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:170:12
  at Array.forEach (<anonymous>:null:null)
  at ReactiveQuery._emit (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:169:22)
  at Set.<anonymous> (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:749:8)
  at D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:170:12
  at Array.forEach (<anonymous>:null:null)
  at Set._emit (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:169:22)
  at Set.put (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:965:7)
  at Set.<anonymous> (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:1020:8)
  at D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:170:12
  at Array.forEach (<anonymous>:null:null)
  at Set._emit (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:169:22)
  at Set.put (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:965:7)
  at Collection._remoteToLocalUpdate (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:695:12)
  at Asteroid._onChanged (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:453:36)
  at DDP.<anonymous> (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\asteroid\dist\asteroid.node.js:392:8)
  at D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\ddp.js\src\ddp.js:125:12
  at Array.forEach (<anonymous>:null:null)
  at DDP._emit (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\ddp.js\src\ddp.js:124:22)
  at DDP._on_changed (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\ddp.js\src\ddp.js:248:8)
  at DDP._on_socket_message (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\ddp.js\src\ddp.js:326:26)
  at Client.dispatchEvent (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\faye-websocket\lib\faye\websocket\api\event_target.js:24:30)
  at Client._receiveMessage (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\faye-websocket\lib\faye\websocket\api.js:152:10)
  at Client.<anonymous> (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\faye-websocket\lib\faye\websocket\api.js:36:49)
  at Client.emit (node:events:339:22)
  at Client.<anonymous> (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\websocket-driver\lib\websocket\driver\hybi.js:460:14)
  at pipe (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\websocket-extensions\lib\pipeline\index.js:37:40)
  at Pipeline._loop (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\websocket-extensions\lib\pipeline\index.js:44:3)
  at Pipeline.processIncomingMessage (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\websocket-extensions\lib\pipeline\index.js:13:8)
  at Extensions.processIncomingMessage (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\websocket-extensions\lib\websocket_extensions.js:133:20)
  at Client._emitMessage (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\websocket-driver\lib\websocket\driver\hybi.js:451:22)
  at Client._emitFrame (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\websocket-driver\lib\websocket\driver\hybi.js:411:19)
  at Client.parse (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\websocket-driver\lib\websocket\driver\hybi.js:137:18)
  at Client.parse (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\websocket-driver\lib\websocket\driver\client.js:63:58)
  at IO.write (D:\ProgramData\SF2\vm0\Fabric\work\Applications\BotsType_App14\HubotPkg.Code.39.2.1-ci.18357\node_modules\websocket-driver\lib\websocket\streams.js:80:16)
  at Socket.ondata (node:internal/streams/readable:715:22)
  at Socket.emit (node:events:327:20)
  at addChunk (node:internal/streams/readable:304:12)
  at readableAddChunk (node:internal/streams/readable:279:9)
  at Socket.Readable.push (node:internal/streams/readable:218:10)
  at TCP.onStreamRead (node:internal/stream_base_commons:192:23)

**Comment by geekgonecrazy** [comment]
@JoJo2406 can you add the steps to reproduce?

**Comment by JoJo2406** [comment]
@geekgonecrazy I create a new issue
https://github.com/RocketChat/Rocket.Chat/issues/19433 but I can confirm was previous setup was working fine until 3.8.0

**Comment by MartinSchoeler** [comment]
Moving discussion to #19433
