### ISSUE TITLE
OAuth2 Graph API Azure AD / Microsoft 365 / Office 365

### ISSUE THREAD

**Issue by kiwinesian** [RocketChat/Rocket.Chat#19452]
### Description:

Hi Rocket.Chat,

Not sure if this is a bug or misconfiguration. I have configured Custom OAuth with Azure AD and looks like I have set everything correctly but it returned the following error:
`Exception while invoking method 'login' MongoError: E11000 duplicate key error collection: rocketchat.users index: services.microsoft.id_1 dup key`

This is with `Merge user` enabled.

Looking forward to hear some pointers from the community! 

### Steps to reproduce:

Rocket.Chat settings
1. URL: `https://login.microsoftonline.com/myTenantID`
2. Token Path: `Path: /oauth2/v2.0/token`
3. Token Sent Via: `Payload`
4. Identity Token Sent Via: `Header`
5. Identity Path: `https://graph.microsoft.com/v1.0/me`
6. Authorize Path: `/oauth2/v2.0/authorize`
7. Scope: `User.Read`
8. Param Name for access token: `access_token`
9. Id: `AzureRegisteredApplicationID`
10. Secret: `AzureSecretApplicationID`
11. Username field: `{{/^(.+)@/::mail}}`
12. Email field: `blank`
13. Name field: `blank`
14. Roles/groups field name: `roles`
15. Merge Roles from SSO: `No`
16. Merge users: `Yes`
17. Show Button on Login Page: `Yes`

### Expected behavior:

Logged in as a registered user with the respective username

### Actual behavior:

Server returned:

`Exception while invoking method 'login' MongoError: E11000 duplicate key error collection: rocketchat.users index: services.microsoft.id_1 dup key`

Browser displayed `Internal server error`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: Debian 10
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Tested with Safari, Edge, Chrome
- Operating System: Mac 10.13

### Additional context

If I leave Username field: `blank`, I got a prompt to set a new username.

### Relevant logs:

```Exception while invoking method 'login' MongoError: E11000 duplicate key error collection: rocketchat.users index: services.microsoft.id_1 dup key: { services.microsoft.id: "51ec5277-8b7c-4a8d-88c4-d1fe9dd2c9ee" }
    at Function.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:123:22)
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/common_functions.js:379:39
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:405:18
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by kiwinesian** [comment]
Somehow, OAuth created a new user for me hence the duplicate.

Deleted the user didn't remove it from the DB, so I had to manually delete it from the DB.
