### ISSUE TITLE
Endless chat loading when LDAP-Group-Sync is enabled

### ISSUE THREAD

**Issue by PlusaN** [RocketChat/Rocket.Chat#19539]
### Description:

Endless chat loading when LDAP-Group-Sync is enabled. 

### Steps to reproduce:

1. Update from 3.6.2 to 3.7.1
2. Add new user in ActiveDirectory
3. Execute Synchronization

### Expected behavior:

Granting rights based on LDAP groups

### Actual behavior:

![99147001-3e750500-268e-11eb-9820-c9b741b86a3e](https://user-images.githubusercontent.com/61884717/99150509-32953d00-26a6-11eb-898d-9703ffc4add8.gif)
![image](https://user-images.githubusercontent.com/61884717/99150513-37f28780-26a6-11eb-9e40-834484bf733e.png)
![image](https://user-images.githubusercontent.com/61884717/99150919-adf7ee00-26a8-11eb-9266-c8095c122cc4.png)
![image](https://user-images.githubusercontent.com/61884717/99150518-3b860e80-26a6-11eb-91fb-7754b40c9b50.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1 and 3.8.0
- Operating System: Debian 10
- Deployment Method: tar
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.4.1

### Client Setup Information

- Desktop App or Browser Version: App and all browser
- Operating System: Windows 10

### Additional context

I tried to synchronize LDAP users on the server versions 3.7.1 and 3.8.0. After synchronization, the user was created successfully, but when trying to log in, the chat was loaded endlessly. New user was given a group without a name. After deleting this group, I was able to log into the chat.

### Relevant logs:
```
I20201114-18:23:56.973(3) server.js:204 API ➔ debug get me threw an error: Error: invalid-param     at Function.isPermissionRestrictedForRole (app/authorization/lib/AuthorizationUtils.ts:26:10)     at Function.isPermissionRestrictedForRoleList (app/authorization/lib/AuthorizationUtils.ts:47:13)     at server/services/authorization/service.ts:81:26     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/services/authorization/service.ts:109:8     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/sdk/lib/LocalBroker.ts:15:15     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at hasPermission (app/authorization/server/functions/hasPermission.js:8:71)     at APIClass.shouldVerifyRateLimit (app/api/server/api.js:216:19)     at APIClass.enforceRateLimit (app/api/server/api.js:220:13)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20201114-18:23:56.973(3) server.js:204 API ➔ debug Failure {   statusCode: 400,   body: { success: false, error: 'invalid-param', stack: undefined } } 
I20201114-18:23:57.233(3) server.js:204 API ➔ debug POST: /api/v1/method.call/autoTranslate.getProviderUiMetadata 
I20201114-18:23:57.235(3) server.js:204 Meteor ➔ method autoTranslate.getProviderUiMetadata -> userId: SppB6PybNeZKwrZ6F, arguments: [] 
I20201114-18:23:57.236(3) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     message: '{"msg":"result","id":"14","result":{"google-translate":{"name":"google-translate","displayName":"Google"},"deepl-translate":{"name":"deepl-translate","displayName":"DeepL"},"microsoft-translate":{"name":"microsoft-translate","displayName":"Microsoft"}}}',     success: true   } } 
I20201114-18:23:57.240(3) server.js:204 API ➔ debug POST: /api/v1/method.call/userSetUtcOffset 
I20201114-18:23:57.241(3) server.js:204 Meteor ➔ method userSetUtcOffset -> userId: SppB6PybNeZKwrZ6F, arguments: [3] 
I20201114-18:23:57.243(3) server.js:204 API ➔ debug POST: /api/v1/method.call/autoTranslate.getProviderUiMetadata 
I20201114-18:23:57.244(3) server.js:204 Meteor ➔ method autoTranslate.getProviderUiMetadata -> userId: SppB6PybNeZKwrZ6F, arguments: [] 
I20201114-18:23:57.245(3) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     message: '{"msg":"result","id":"16","result":{"google-translate":{"name":"google-translate","displayName":"Google"},"deepl-translate":{"name":"deepl-translate","displayName":"DeepL"},"microsoft-translate":{"name":"microsoft-translate","displayName":"Microsoft"}}}',     success: true   } } 
I20201114-18:23:57.247(3) server.js:204 API ➔ debug Success {   statusCode: 200,   body: { message: '{"msg":"result","id":"15","result":0}', success: true } } 
I20201114-18:23:57.697(3) server.js:204 LDAP ➔ Search.info Idle 
I20201114-18:23:57.699(3) server.js:204 LDAP ➔ Connection.info Disconecting 
I20201114-18:23:57.700(3) server.js:204 LDAP ➔ Search.info Closed 
I20201114-18:24:00.140(3) server.js:204 SyncedCron ➔ info Starting "Generate download files for user data". 
<!-- Logs from both SERVER and BROWSER -->
<!-- For more information about collecting logs please see: https://rocket.chat/docs/contributing/reporting-issues#gathering-logs -->
```

**Comment by PlusaN** [comment]
This problem is observed only with new users, old users that were created in version 3.6.2 work fine.
