### ISSUE TITLE
LDAPSync Error

### ISSUE THREAD

**Issue by UAnton** [RocketChat/Rocket.Chat#19647]
### Description:

All RocketChat servers with LDAP auth have LDAPSync errors.

### Steps to reproduce:

Setup LDAP Auth and check logs

### Expected behavior:

No errors

### Actual behavior:

`I20201121-22:00:21.463(2) server.js:204 LDAPSync ➔ error Error creating user errorClass [Error]: Username already exists. [403]     at handleError (packages/accounts-password/password_server.js:110:17)     at checkForCaseInsensitiveDuplicates (packages/accounts-password/password_server.js:257:7)     at createUser (packages/accounts-password/password_server.js:1125:3)     at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1197:10)     at addLdapUser (app/ldap/server/sync.js:472:29)     at app/ldap/server/sync.js:538:5     at Array.forEach (<anonymous>)     at app/ldap/server/sync.js:505:13     at runWithEnvironment (packages/meteor.js:1286:24) {   isClientSafe: true,   error: 403,   reason: 'Username already exists.',   details: undefined,   errorType: 'Meteor.Error' } 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.21

### Client Setup Information

- Desktop App or Browser Version: Safari 14
- Operating System: macOS 11

**Comment by JonCSgr** [comment]
Hey , i can't even make ldap to work . I have openLDAP and i am filling out the basic settings 
ip, port and baseDN and it wont sync. Do i need to edit something else?
Sorry for jumping on ur threead.

**Comment by aecrespo95** [comment]
have you tried to activate the option "Merge existing users"  in LDAP Import options?
