### ISSUE TITLE
Quote message url parse inconsistent

### ISSUE THREAD

**Issue by Atomzwieback** [RocketChat/Rocket.Chat#19756]
### Description:

In our chat we have the problem that URLs for direct messages quotes can not be resolved correctly in 9 out of 10 cases. The error message that appears says that the user with the name "USERNAME-HASH" cannot be found. However, if you try to reload this link it sometimes works.

### Steps to reproduce:

Open a chat with some one and quote the message.

### Expected behavior:

The quote url should be resolved.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.0
- Operating System: Ubuntu 20.04
- Deployment Method: Docker
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v12.19.0
- MongoDB Version: 4.4.2

### Client Setup Information

- Desktop App or Browser Version: Desktop App and Firefox v12.19.0
- Operating System: MacOS BigSur 11.0.1

### Relevant logs:

`Exception while invoking method createDirectMessage Error: Invalid user [error-invalid-user]
    at server/methods/createDirectMessage.js:44:11
    at Array.map (<anonymous>)
    at MethodInvocation.createDirectMessage (server/methods/createDirectMessage.js:35:74)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9`

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
