### ISSUE TITLE
Problem upgrading from 3.9.0 to 3.9.1 (Docker?)

### ISSUE THREAD

**Issue by phriedrich** [RocketChat/Rocket.Chat#19770]
Server doesn't start after upgrading.

### Description:

When upgrading from 3.9.0 to 3.9.1 I got the following error in the log:

```
Exception in callback of async function: errorClass [Error]: [Can't find migration version 211]
    at Object.Migrations._findIndexByVersion (app/migrations/server/migrations.js:403:8)
    at Object.Migrations._migrateTo (app/migrations/server/migrations.js:254:24)
    at Object.Migrations.migrateTo (app/migrations/server/migrations.js:179:20)
    at module (server/startup/migrations/xrun.js:6:13)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
    at module (server/startup/migrations/index.js:1:4584)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
    at module (server/main.js:1:239)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /app/bundle/programs/server/app/app.js:191707:15
    at /app/bundle/programs/server/boot.js:401:38
    at Array.forEach (<anonymous>)
    at /app/bundle/programs/server/boot.js:226:21
    at /app/bundle/programs/server/boot.js:464:7
    at Function.run (/app/bundle/programs/server/profile.js:280:14)
    at /app/bundle/programs/server/boot.js:463:13 {
  isClientSafe: true,
  error: "Can't find migration version 211",
  reason: undefined,
  details: undefined,
  errorType: 'Meteor.Error'
}
```

And then it doesn't resume.

Going back to 3.9.0 works. It shows:

```
{"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 211","time":{"$date":1607203290427},"level":"info"}
```

but I haven't noticed any problems.

### Steps to reproduce:

1. `docker pull rocketchat/rocket.chat:latest`
2. `docker-compose up -d `
3. `docker logs -f rocketchat_rocketchat_1`

### Expected behavior:

Normal startup after migration.

### Actual behavior:

Not resuming after failing migration.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1
- Operating System: 5.4.80-gentoo-r1
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: active
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.0

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

See above.

**Comment by kokomo123** [comment]
Can confirm, this is the same issue that's happening with my instance. 
I'm on Debian 10, latest version available, on docker containers, and should be latest as described above. I'm not on gentoo.

**Comment by phriedrich** [comment]
@kokomo123 thanks for confirming this problem. I think it's a problem with the docker image.

Btw., if you didn't already have it working again with 3.9.0, my makeshift approach was to simply re-tag the docker images:

```
docker tag 1283303a35d9 rocketchat/rocket.chat:3.9.1
docker tag 9daff8f8c147 rocketchat/rocket.chat:latest
```

resulting in:

```
docker images -a
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
rocketchat/rocket.chat   3.9.1               1283303a35d9        2 hours ago         1.47GB
rocketchat/rocket.chat   3.9.0               9daff8f8c147        7 days ago          1.47GB
rocketchat/rocket.chat   latest              9daff8f8c147        7 days ago          1.47GB
```

So marking 3.9.0 as latest allowed me to run it without any changes on my config.

**Comment by kokomo123** [comment]
I fixed it with just adjusting my docker-compose and instead of latest, i did rocketchat/rocket.chat:3.9.0, and it worked successfully. I'm on the latest tag, but ill be sure to move once a fix is implemented.

**Comment by phriedrich** [comment]
This seems to be fixed with a container update:

```
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
rocketchat/rocket.chat   3.9.1               1bf9b234061f        15 hours ago        1.47GB
rocketchat/rocket.chat   latest              1bf9b234061f        15 hours ago        1.47GB
rocketchat/rocket.chat   3.9.1_broken        1283303a35d9        16 hours ago        1.47GB
rocketchat/rocket.chat   3.9.0               9daff8f8c147        8 days ago          1.47GB
```

And this time it started correctly:

```
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
{"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 211","time":{"$date":1607257123780},"level":"info"}
ufs: temp directory created at "/tmp/ufs"
Updating process.env.MAIL_URL
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
Loaded the Apps Framework and loaded a total of 4 Apps!
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
➔ System ➔ startup
➔ +---------------------------------------------------+
➔ |                   SERVER RUNNING                  |
➔ +---------------------------------------------------+
➔ |                                                   |
➔ |  Rocket.Chat Version: 3.9.1                       |
➔ |       NodeJS Version: 12.18.4 - x64               |
➔ |      MongoDB Version: 4.2.0                       |
➔ |       MongoDB Engine: wiredTiger                  |
➔ |             Platform: linux                       |
➔ |         Process Port: 3000                        |
➔ |             Site URL: https://chat.phriedrich.de  |
➔ |     ReplicaSet OpLog: Enabled                     |
➔ |          Commit Hash: 798241b9e5                  |
➔ |        Commit Branch: HEAD                        |
➔ |                                                   |
➔ +---------------------------------------------------+
```

Closed.
