### ISSUE TITLE
Cannot start server after update attempt to 3.9.

### ISSUE THREAD

**Issue by vplb** [RocketChat/Rocket.Chat#19828]
### Description:
1. Rocketchatctl check-updates fails, error: `/usr/local/bin/rocketchatctl:` line 900: [: 3.9.1: unary operator expected
1a. rocketchatctl update fails, error: `/usr/local/bin/rocketchatctl:` line 900: [: 3.9.1: unary operator expected
- able to curl new version: `echo $(curl https://releases.rocket.chat/latest/info)
{"tag":"3.9.1","commit":"798241b9e5a45a7b118c09cee38b6d8e9c0e53e1","key":"build/rocket.chat-3.9.1.tgz","etag":"e67f0f58e088728867d6bafbf59df16d-19","count":5494}

2. Manual update process seems to go correctly, but cannot start rocketchat. Not sure which logs can assist with this to provide. 

### Steps to reproduce:
1. following these instruction: https://docs.rocket.chat/installation/manual-installation/updating
2. at step: cd /tmp/bundle/programs/server && npm install, used npm install --unsafe-perm as working from root
NPM Install ends with:
`added 146 packages from 122 contributors and audited 147 packages in 28.756s
`
`2 packages are looking for funding
`  run `npm fund` for details
`
`found 0 vulnerabilities

3. at final step (systemctl start rocketchat) fails.

### Actual behavior:
Output of systemctl status rocketchat:

root@RocketChat-test:/opt/Rocket.Chat# systemctl status rocketchat
● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-12-10 11:16:18 PST; 4s ago
  Process: 1564 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 1564 (code=exited, status=1/FAILURE)

Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/program
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at module (server/main.js:1:8)
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at Module.require (packages/modules-runtime.js:238:14)
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at require (packages/modules-runtime.js:258:21)
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at /opt/Rocket.Chat/programs/server/app/app.js:191202:15
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at /opt/Rocket.Chat/programs/server/boot.js:401:38
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at Array.forEach (<anonymous>)
Dec 10 11:16:18 RocketChat-test systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAI
Dec 10 11:16:18 RocketChat-test systemd[1]: rocketchat.service: Failed with result 'exit-code'.
lines 1-16/16 (END)...skipping...
● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-12-10 11:16:18 PST; 4s ago
  Process: 1564 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 1564 (code=exited, status=1/FAILURE)

Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at module (server/main.js:1:8)
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at Module.require (packages/modules-runtime.js:238:14)
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at require (packages/modules-runtime.js:258:21)
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at /opt/Rocket.Chat/programs/server/app/app.js:191202:15
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at /opt/Rocket.Chat/programs/server/boot.js:401:38
Dec 10 11:16:18 RocketChat-test rocketchat[1564]:     at Array.forEach (<anonymous>)
Dec 10 11:16:18 RocketChat-test systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 11:16:18 RocketChat-test systemd[1]: rocketchat.service: Failed with result 'exit-code'.

### Server Setup Information:

- Version of Rocket.Chat Server: "3.7.0"
- Operating System: Debian GNU/Linux 10 (buster)
- Deployment Method: manual install
- Number of Running Instances: 1
- NodeJS Version: v12.14.0
- MongoDB Version: db version v4.2.9

### Additional context

Not linux superuser, not sure what logs may assist, as RocketChat won't start can't access those. I have updated in the past, manually, to 3.8.3. That worked with minor adjustment.

**Comment by vplb** [comment]
Adding something found during the npm install phase, not sure if critical: 

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues                                                         /3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

**Comment by vplb** [comment]
Found a fix on another problem: 
https://github.com/RocketChat/Rocket.Chat/issues/19537

On Debian 10 (buster), as suggested on a previous comment, i've symlink system NJS to local dir :

mv /usr/local/bin/node /usr/local/bin/node.old
ln -s /usr/bin/node /usr/local/bin/node

node --version
v12.19.1


The issues were related to NPM. It'd be really nice if this was added somewhere to the update document. Cheers.
