### ISSUE TITLE
Cannot join a channel as admin using the Web app

### ISSUE THREAD

**Issue by laem** [RocketChat/Rocket.Chat#19832]
### Description:

Using the Web version of RocketChat, as an admin, I can't join some channels : when I click the blue button bottom-right, the bell rings, the channel view crashes, and on refresh a message "[user] has joined the channel" appears but the button is still there. Same for sending a message : it gets sent, but the Web app does not understand I've joined. 

This issue affects only *old admins* on our instance. The instance has been updated several times, the last was 3.6.3 -> 3.8.3.
All browsers tested (Firefox, Chrome, Kiwi, Chromium).

No problem from the android app.

### Steps to reproduce:

1. As an old admin, hit Ctrl-K and find a public channel you're not in
2. Click the join button / send a message
3. Hear the bell, see the channel view become white
4. You're in the channel according to the chat history, but not for the Web client

### Expected behavior:

Join the channel.

### Actual behavior:

The blank page : 
![image](https://user-images.githubusercontent.com/1177762/101885885-ff59a700-3b9a-11eb-8be8-f3b17d2614bc.png)

After refresh, I've officially joined this channel several times... still not in.

![image](https://user-images.githubusercontent.com/1177762/101886010-329c3600-3b9b-11eb-9cc3-b0aede0ee4c9.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.3
- Operating System: Android / Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.12

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

No JS error or log in the browser console when the error happens.

**Comment by aditya-mitra** [comment]
Hi @laem
I reproduced your problem locally. Unfortunately, I could not find this problem
I even restarted the server to check if the problem exists. But, I was still there in the channel and could directly send messages without rejoining it.
To ensure this, I even checked the _channel members_ using the second account (which created the channel) and found that the _server admin_ was still in the channel.

If possible, would you mind if I asked you to reproduce this problem locally (for example - in a virtual machine) and check if the problem still persists?
If you have resolved the problem, please don't mind closing the issue. :smiley:

**Comment by laem** [comment]
Unfortunately, I don't have access to the server, and the problem is still there. 

@pierreozoux

**Comment by aditya-mitra** [comment]
I am sorry to hear that.
Can you reproduce this problem locally (for example - in a virtual machine) and check if the problem still persists?

**Comment by laem** [comment]
For what it's worth, this is the error that appears to show in the console when I refresh a channel page where this bug happens.

![Capture d’écran du 2021-01-22 12-43-35](https://user-images.githubusercontent.com/1177762/105486892-8b3d1380-5caf-11eb-9525-92fd022c4b01.png)

**Comment by laem** [comment]
Other info : the bug is not present on the mobile android app. Juste the desktop Web / app (which I assume is just a tab wrapped).

**Comment by pierreozoux** [comment]
The log on the server side:
```
server.js:204 Federation ➔ client.error afterAddedToRoom => Could not add user: Error: Channels cannot be federated
    at app/federation/server/hooks/afterAddedToRoom.js:30:10
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```
It was not a federated user trying to join, but a regular one.

The workaround was to deactivate federation.

**Comment by pierreozoux** [comment]
hi @aditya-mitra,

It was some users that couldn't join some channels. I know it is difficult to reproduce.
Do you have any idea what could I share with you to help us debug this?

Maybe I could also make a deep clean of everything federation related, if you have some instructions, I'm open to try them :)

Thanks for your help!

**Comment by aditya-mitra** [comment]
Hi @pierreozoux ,

I think the problem is that the room that the user is trying to get into is **public channel**.

However, I found out that the error happens when the room type is something other than a _private room or a direct message_ room. (But I am not completely sure).

https://github.com/RocketChat/Rocket.Chat/blob/20be361142be4dc4547dff0ab5a44e31bdccf3f5/app/federation/server/hooks/afterAddedToRoom.js#L29-L31

https://github.com/RocketChat/Rocket.Chat/blob/20be361142be4dc4547dff0ab5a44e31bdccf3f5/app/federation/server/functions/helpers.js#L20 

Can you tell which type of room was the user trying to get into?
(In the first picture, I saw it was a public channel)

**Comment by pierreozoux** [comment]
Yes, it was a public channel, but it was not a federated user, it was a regular user, a user from the instance, trying to join a public channel on the same instance.
