### ISSUE TITLE
Cannot login to Rocket.Chat workspace in the Administration menu

### ISSUE THREAD

**Issue by h3d-haivq** [RocketChat/Rocket.Chat#19880]
### Description:

Everytime I try to login to Rocket.Chat Cloud in Connectivity Services, a message like this always happens:
```
The Rocket.Chat Workspace you are attempting to sign into is currently associated with a different Rocket.Chat Cloud account than the one you are signed in with. (684afdc5-19fc-4620-b136-620af46ae0f5)
```
### Steps to reproduce:

0. Host a self-hosted rocket.chat
1. Create a new workspace in cloud.rocket.chat
2. Copy the token then paste it in the Connectivity Service
3. The Connectivity Services tab shows the Login to Rocket.Chat Cloud, click on it
4. It redirects to cloud.rocket.chat website (which I've already logged in), then it shows the message above

### Expected behavior:

I don't know, never successfully logged in before

### Actual behavior:

![image](https://user-images.githubusercontent.com/40750611/102482167-61cc0f00-4095-11eb-966d-1e9337b27168.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1
- Operating System: Ubuntu 20.04.1 LTS
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: I'm using Mongo Atlas
- NodeJS Version: 
- MongoDB Version: 4.2.11

### Client Setup Information

- Desktop App or Browser Version: Browser and Desktop have the same behavior
- Operating System: Mac/Windows/Linux

### Relevant logs:

```
Exception while invoking method autoTranslate.getProviderUiMetadata Error: Login neccessary [error-action-not-allowed]
2020-12-17 6:08:39 PM     at MethodInvocation.autoTranslate.getProviderUiMetadata (app/autotranslate/server/methods/getProviderUiMetadata.js:8:10)
2020-12-17 6:08:39 PM     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
2020-12-17 6:08:39 PM     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
2020-12-17 6:08:39 PM     at packages/ddp-server/livedata_server.js:1689:15
2020-12-17 6:08:39 PM     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-12-17 6:08:39 PM     at packages/ddp-server/livedata_server.js:1687:36
2020-12-17 6:08:39 PM     at new Promise (<anonymous>)
2020-12-17 6:08:39 PM     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
2020-12-17 6:08:39 PM     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
2020-12-17 6:08:39 PM     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
2020-12-17 6:08:39 PM     at Object.post (app/api/server/v1/misc.js:262:26)
2020-12-17 6:08:39 PM     at app/api/server/api.js:394:82
2020-12-17 6:08:39 PM     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-12-17 6:08:39 PM     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
2020-12-17 6:08:39 PM     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
2020-12-17 6:08:39 PM     at packages/nimble_restivus/lib/route.coffee:59:33
2020-12-17 6:08:39 PM     at packages/simple_json-routes.js:98:9
2020-12-17 6:08:39 PM  => awaited here:
2020-12-17 6:08:39 PM     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
2020-12-17 6:08:39 PM     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
2020-12-17 6:08:39 PM     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
2020-12-17 6:08:39 PM     at Object.post (app/api/server/v1/misc.js:262:26)
2020-12-17 6:08:39 PM     at app/api/server/api.js:394:82
2020-12-17 6:08:39 PM     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-12-17 6:08:39 PM     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
2020-12-17 6:08:39 PM     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
2020-12-17 6:08:39 PM     at packages/nimble_restivus/lib/route.coffee:59:33
2020-12-17 6:08:39 PM     at packages/simple_json-routes.js:98:9
2020-12-17 6:08:39 PM Exception while invoking method getUserRoles Error: Invalid user [error-invalid-user]
2020-12-17 6:08:39 PM     at MethodInvocation.getUserRoles (app/lib/server/methods/getUserRoles.js:9:10)
2020-12-17 6:08:39 PM     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
2020-12-17 6:08:39 PM     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
2020-12-17 6:08:39 PM     at packages/ddp-server/livedata_server.js:1689:15
2020-12-17 6:08:39 PM     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-12-17 6:08:39 PM     at packages/ddp-server/livedata_server.js:1687:36
2020-12-17 6:08:39 PM     at new Promise (<anonymous>)
2020-12-17 6:08:39 PM     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
2020-12-17 6:08:39 PM     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
2020-12-17 6:08:39 PM     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
2020-12-17 6:08:39 PM     at Object.post (app/api/server/v1/misc.js:262:26)
2020-12-17 6:08:39 PM     at app/api/server/api.js:394:82
2020-12-17 6:08:39 PM     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-12-17 6:08:39 PM     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
2020-12-17 6:08:39 PM     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
2020-12-17 6:08:39 PM     at packages/nimble_restivus/lib/route.coffee:59:33
2020-12-17 6:08:39 PM     at packages/simple_json-routes.js:98:9
2020-12-17 6:08:39 PM  => awaited here:
2020-12-17 6:08:39 PM     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
2020-12-17 6:08:39 PM     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
2020-12-17 6:08:39 PM     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
2020-12-17 6:08:39 PM     at Object.post (app/api/server/v1/misc.js:262:26)
2020-12-17 6:08:39 PM     at app/api/server/api.js:394:82
2020-12-17 6:08:39 PM     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-12-17 6:08:39 PM     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
2020-12-17 6:08:39 PM     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
2020-12-17 6:08:39 PM     at packages/nimble_restivus/lib/route.coffee:59:33
2020-12-17 6:08:39 PM     at packages/simple_json-routes.js:98:9
2020-12-17 6:08:39 PM Exception while invoking method listCustomUserStatus Error: Invalid user [error-invalid-user]
2020-12-17 6:08:39 PM     at MethodInvocation.listCustomUserStatus (app/user-status/server/methods/listCustomUserStatus.js:9:10)
2020-12-17 6:08:39 PM     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
2020-12-17 6:08:39 PM     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
2020-12-17 6:08:39 PM     at packages/ddp-server/livedata_server.js:1689:15
2020-12-17 6:08:39 PM     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-12-17 6:08:39 PM     at packages/ddp-server/livedata_server.js:1687:36
2020-12-17 6:08:39 PM     at new Promise (<anonymous>)
2020-12-17 6:08:39 PM     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
2020-12-17 6:08:39 PM     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
2020-12-17 6:08:39 PM     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
2020-12-17 6:08:39 PM     at Object.post (app/api/server/v1/misc.js:262:26)
2020-12-17 6:08:39 PM     at app/api/server/api.js:394:82
2020-12-17 6:08:39 PM     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-12-17 6:08:39 PM     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
2020-12-17 6:08:39 PM     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
2020-12-17 6:08:39 PM     at packages/nimble_restivus/lib/route.coffee:59:33
2020-12-17 6:08:39 PM     at packages/simple_json-routes.js:98:9
2020-12-17 6:08:39 PM  => awaited here:
2020-12-17 6:08:39 PM     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
2020-12-17 6:08:39 PM     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
2020-12-17 6:08:39 PM     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
2020-12-17 6:08:39 PM     at Object.post (app/api/server/v1/misc.js:262:26)
2020-12-17 6:08:39 PM     at app/api/server/api.js:394:82
2020-12-17 6:08:39 PM     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-12-17 6:08:39 PM     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
2020-12-17 6:08:39 PM     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
2020-12-17 6:08:39 PM     at packages/nimble_restivus/lib/route.coffee:59:33
2020-12-17 6:08:39 PM     at packages/simple_json-routes.js:98:9
2020-12-17 6:08:39 PM Exception while invoking method autoTranslate.getProviderUiMetadata Error: Login neccessary [error-action-not-allowed]
2020-12-17 6:08:39 PM     at MethodInvocation.autoTranslate.getProviderUiMetadata (app/autotranslate/server/methods/getProviderUiMetadata.js:8:10)
2020-12-17 6:08:39 PM     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
2020-12-17 6:08:39 PM     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
2020-12-17 6:08:39 PM     at packages/ddp-server/livedata_server.js:1689:15
2020-12-17 6:08:39 PM     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-12-17 6:08:39 PM     at packages/ddp-server/livedata_server.js:1687:36
2020-12-17 6:08:39 PM     at new Promise (<anonymous>)
2020-12-17 6:08:39 PM     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
2020-12-17 6:08:39 PM     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
2020-12-17 6:08:39 PM     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
2020-12-17 6:08:39 PM     at Object.post (app/api/server/v1/misc.js:262:26)
2020-12-17 6:08:39 PM     at app/api/server/api.js:394:82
2020-12-17 6:08:39 PM     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-12-17 6:08:39 PM     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
2020-12-17 6:08:39 PM     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
2020-12-17 6:08:39 PM     at packages/nimble_restivus/lib/route.coffee:59:33
2020-12-17 6:08:39 PM     at packages/simple_json-routes.js:98:9
2020-12-17 6:08:39 PM  => awaited here:
2020-12-17 6:08:39 PM     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
2020-12-17 6:08:39 PM     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
2020-12-17 6:08:39 PM     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
2020-12-17 6:08:39 PM     at Object.post (app/api/server/v1/misc.js:262:26)
2020-12-17 6:08:39 PM     at app/api/server/api.js:394:82
2020-12-17 6:08:39 PM     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2020-12-17 6:08:39 PM     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
2020-12-17 6:08:39 PM     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
2020-12-17 6:08:39 PM     at packages/nimble_restivus/lib/route.coffee:59:33
2020-12-17 6:08:39 PM     at packages/simple_json-routes.js:98:9
```

**Comment by daniellopesjp** [comment]
+1

**Comment by dossantg** [comment]
Same issue on 3.8.1

**Comment by h3d-haivq** [comment]
upgraded to 3.9.2 but the problem is still persisted

**Comment by dossantg** [comment]
Does anyone have any idea to fix this problem? We cannot buy an app on the marketplace without this connection with cloud.rocket.chat

**Comment by MatthiasWiesner** [comment]
Same issue on 3.12.1

**Comment by nooblag** [comment]
Same issue on 4.6.2. We haven't been able to use mobile push notifications for months now because of this.
