### ISSUE TITLE
Error updating RocketChat on npm install

### ISSUE THREAD

**Issue by joakinen** [RocketChat/Rocket.Chat#20039]
### Description:

Errors while updating RocketChat

### Steps to reproduce:

Standard update procedure from https://docs.rocket.chat/installation/manual-installation/updating

1. sudo systemctl stop rocketchat
2. sudo rm -rf /opt/Rocket.Chat
3. curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
4. tar -xzf /tmp/rocket.chat.tgz -C /tmp
5. cd /tmp/bundle/programs/server && npm install

### Expected behavior:

"npm install" run without errors

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu 18.04
- Deployment Method: manual
- Number of Running Instances: 1
- NodeJS Version: v14.15.3
- MongoDB Version: v4.0.22

### Additional context

First error was this although process continued:

```
/home/citrixadmin/.cache/node-gyp/14.15.3/include/node/v8.h:2858:8: note:   no known conversion for argument 1 from ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
../native/addon.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE eccPrivateSub(Nan::NAN_METHOD_ARGS_TYPE)’:
../native/addon.cpp:240:29: warning: ignoring return value of ‘int secp256k1_ec_privkey_negate(const secp256k1_context*, unsigned char*)’, declared with attribute warn_unused_result [-Wunused-result]
  secp256k1_ec_privkey_negate(context, tweak_negated); // returns 1 always
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
secp256k1.target.mk:153: recipe for target 'Release/obj.target/secp256k1/native/addon.o' failed
make: *** [Release/obj.target/secp256k1/native/addon.o] Error 1
make: Leaving directory '/tmp/bundle/programs/server/npm/node_modules/tiny-secp256k1/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.15.0-128-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/bundle/programs/server/npm/node_modules/tiny-secp256k1
gyp ERR! node -v v14.15.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.3 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiny-secp256k1@1.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/citrixadmin/.npm/_logs/2021-01-04T12_35_04_823Z-debug.log
secp256k1 bindings compilation fail. Pure JS implementation will be used.
```

This error aborted the update:

```
/home/citrixadmin/.cache/node-gyp/14.15.3/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
sharp.target.mk:138: recipe for target 'Release/obj.target/sharp/src/stats.o' failed
make: *** [Release/obj.target/sharp/src/stats.o] Error 1
make: Leaving directory '/tmp/bundle/programs/server/npm/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.15.0-128-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/bundle/programs/server/npm/node_modules/sharp
gyp ERR! node -v v14.15.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/citrixadmin/.npm/_logs/2021-01-04T12_35_27_747Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/citrixadmin/.npm/_logs/2021-01-04T12_35_27_823Z-debug.log
```

### Relevant logs:

This is the contents of /home/citrixadmin/.npm/_logs/2021-01-04T12_35_27_823Z-debug.log 

```
3916 verbose lifecycle meteor-dev-bundle@~install: CWD: /tmp/bundle/programs/server
3917 silly lifecycle meteor-dev-bundle@~install: Args: [ '-c', 'node npm-rebuild.js' ]
3918 silly lifecycle meteor-dev-bundle@~install: Returned: code: 1  signal: null
3919 info lifecycle meteor-dev-bundle@~install: Failed to exec install script
3920 verbose stack Error: meteor-dev-bundle@ install: `node npm-rebuild.js`
3920 verbose stack Exit status 1
3920 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
3920 verbose stack     at EventEmitter.emit (events.js:315:20)
3920 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3920 verbose stack     at ChildProcess.emit (events.js:315:20)
3920 verbose stack     at maybeClose (internal/child_process.js:1048:16)
3920 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
3921 verbose pkgid meteor-dev-bundle@
3922 verbose cwd /tmp/bundle/programs/server
3923 verbose Linux 4.15.0-128-generic
3924 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
3925 verbose node v14.15.3
3926 verbose npm  v6.14.9
3927 error code ELIFECYCLE
3928 error errno 1
3929 error meteor-dev-bundle@ install: `node npm-rebuild.js`
3929 error Exit status 1
3930 error Failed at the meteor-dev-bundle@ install script.
3930 error This is probably not a problem with npm. There is likely additional logging output above.
3931 verbose exit [ 1, true ]
```

**Comment by joakinen** [comment]
Version of n was incorrect.
