### ISSUE TITLE
Inconsitency in notifications

### ISSUE THREAD

**Issue by d3hof** [RocketChat/Rocket.Chat#20168]
### Description:

Me and several people observed that there are inconsistency regarding notifications. I didn't see any clear pattern yet. 
Sometimes people get push notifications on their Smartphone, but don't get any notfications in the browser or the rocketchat-client. Sometimes it's the other way around. Sometimes it just works fine. Sometimes they arrive too late. This is observed on Kubuntu 20.04 as well as Windows 10.

### Steps to reproduce:
Set up RocketChat-Server 3.9.1 and observe your notifications.

### Expected behavior:

You should receive Notifications in all Applications at the same time. 

### Actual behavior:
As above mentions Notifications (Push and Desktop) are not synced, they sometimes just don't happen.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1
- Operating System: Debian Stretch
- Deployment Method: docker on kubernetes
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.18.4 x64
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: 3.9.3, 3.9.1 - Browser Firefox 84.0
- Operating System: Windows 10, Kubuntu

### Relevant logs:

I  don't know if this log is related to the issue, but I am getting the following several times a day.
OEmbed duplicated record https://github.com/RocketChat/Rocket.Chat/releases/tag/3.10.3
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 GENERAL listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit
Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]
    at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:50:10)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 sCZQFqBxGypJ6ACSS listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 XTaZywoWNp3AcH6Aj listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 46nAMgmoikGrb9dYr listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 BKJj8TbEG4e5RmqfQ listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ZysCgg8q5zFD9byok listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit
Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]
    at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:50:10)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 KEx2g67oSfJsWMXfF listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 qGkrRwvLJMbhNQFGp listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit
Exception while invoking method login Error: User not found [403]
    at handleError (packages/accounts-password/password_server.js:110:17)
    at MethodInvocation.<anonymous> (packages/accounts-password/password_server.js:313:5)
    at packages/accounts-base/accounts_server.js:475:31
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1309:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:473:22)
    at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:533:31)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
Error while handling the setting of the avatar from a url (xxxxxxxxxx) for xxxxxxx: Error: url must be absolute and start with http:// or https://
    at Object._call (packages/http.js:59:11)
    at Object.<anonymous> (packages/meteor.js:306:21)
    at Object._call [as call] (packages/rocketchat:mongo-config/server/index.js:20:14)
    at Object.HTTP.get (packages/http.js:217:20)
    at setUserAvatar (app/lib/server/functions/setUserAvatar.js:19:18)
    at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/users.js:316:5)
    at packages/dispatch_run-as-user.js:211:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
    at Object.post (app/api/server/v1/users.js:314:10)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 o9qEY7ovByuTG9gzx listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 JvJZRZ8DwYyTqzcHN listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 gAJwRWj4gKcS5q8LB listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit

**Comment by ankar84** [comment]
> Sometimes they arrive too late.

I confirm that. For some reason from time to time push notifications appears on user smartphones with delay (5-10-20 minuses). And I don't actually know how to troubleshoot that issue, how and what to monitor (push queue in DB for example)


> You should receive Notifications in all Applications at the same time.

It's impossible by design. If you get notification and message on desktop or web client, why you need it on your mobile as push notification in that same moment? It's really unnecessarily. So RC logic stand that you get push notification only in there is no connected online sessions or that session is inactive (messages not read in 2 minutes). That is good logic in my opinion.

**Comment by d3hof** [comment]
> It's impossible by design. If you get notification and message on desktop or web client, why you need it on your mobile as push notification in that same moment? It's really unnecessarily. So RC logic stand that you get push notification only in there is no connected online sessions or that session is inactive (messages not read in 2 minutes). That is good logic in my opinion.

Thanks for the info. You're right that is actually a smart behaviour. I will check if that is actually how it works.

**Comment by d3hof** [comment]
But what if i have theoretically the desktop app and a browser chat shouldn't it send the notifications to both? Because I observed that sometimes there are unread messages in the browser but not in the desktop app.

**Comment by ankar84** [comment]
> But what if i have theoretically the desktop app and a browser chat shouldn't it send the notifications to both? Because I observed that sometimes there are unread messages in the browser but not in the desktop app.

Rocket chat team members can answer you more accurate, but I think you right. you will get notification in both desktop and web clients.

**Comment by d3hof** [comment]
So i realised it was an issue related to our hosting. I am closing this for now. 



> It's impossible by design. If you get notification and message on desktop or web client, why you need it on your mobile as push notification in that same moment? It's really unnecessarily. So RC logic stand that you get push notification only in there is no connected online sessions or that session is inactive (messages not read in 2 minutes). That is good logic in my opinion.

fyi it actually sends the notification to all devices, I tested it. You get the notifications on your desktop even if your absent as well as the push notification.

**Comment by joseluisq** [comment]
In our case, I'm receiving notifications on both Desktop and then Mobile device but **the same notification**.
For instance, I'm **connected** and **online** using the Desktop App then I receive one notification (the same) in the Desktop App (which is OK) and then immediately a **push notification** in the Mobile App (which is NOT necessary).

So please confirm me if that behaviour is fine because for me looks like sending the same push notification to Mobile App again it's unnecessary.

Possibly related to https://github.com/RocketChat/Rocket.Chat/issues/19446
