### ISSUE TITLE
[Windows] [Meteor] Error launch of version 0.13.0 +

### ISSUE THREAD

**Issue by Grinsens** [RocketChat/Rocket.Chat#2019]
I apologize in advance, I do not know English, using google translate

Version 0.12 runs stably (cmd meteor)
Version 0.13, 0.14 return an error when you run
![2016-01-24 13-44-02 c windows system32 cmd exe](https://cloud.githubusercontent.com/assets/16426696/12535324/a930ce62-c2a0-11e5-8614-8de226ed6124.png)

full

C:\src\0.13.0>meteor
[[[[[ C:\src\0.13.0 ]]]]]

=> Started proxy.
=> Started MongoDB.
"sh" �� ����� ����७��� ��� ���譥�            |
��������, �ᯮ��塞�� �ணࠬ��� ��� �������� 䠩���.

C:\Users\The-A\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: Builder can not write without either data or a file path or a symlink path: os/packages/rocketchat_livechat/public/head.html
    at Builder.write (C:\tools\isobuild\builder.js:225:13)
    at Builder.writeToGeneratedFilename (C:\tools\isobuild\builder.js:353:10)
    at C:\tools\isobuild\isopack.js:1346:27
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\The-A\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at _.each._.each.builder.generateFilename.directory (C:\tools\isobuild\isopack.js:1320:11)
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\The-A\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\isopack.js:1233:9
    at [object Object]._.extend.saveToPath (C:\tools\isobuild\isopack.js:1585:26)
    at C:\tools\isobuild\isopack-cache.js:289:23
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend._loadLocalPackage (C:\tools\isobuild\isopack-cache.js:227:18)
    at C:\tools\isobuild\isopack-cache.js:166:14
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:158:20)
    at C:\tools\isobuild\isopack-cache.js:73:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\The-A\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at [object Object]._.extend.eachPackage (C:\tools\packaging\package-map.js:49:7)
    at [object Object]._.extend.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:72:24)
    at C:\tools\project-context.js:735:25
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._buildLocalPackages (C:\tools\project-context.js:734:18)
    at C:\tools\project-context.js:257:35
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\tools\project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.js:240:10)
    at C:\tools\runners\run-app.js:517:29
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at bundleApp (C:\tools\runners\run-app.js:516:31)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:594:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:858:28)
    at C:\tools\runners\run-app.js:396:12

--------------------------------------- [ UPD ] --------------------------------------- 
v 0.15.0

=> Started proxy.
=> Started MongoDB.
rocketchat:file: updating npm dependencies -- mkdirp, gridfs-stream, gm...
rocketchat:assets: updating npm dependencies -- image-size, mime-types...
rocketchat:ldap: updating npm dependencies -- ldapjs...
builLivechat: updating npm dependencies -- shelljs...
"sh" �� ����� ����७��� ��� ���譥�            \
��������, �ᯮ��塞�� �ணࠬ��� ��� �������� 䠩���.
Resolve cb threw Error: Builder can not write without either data or a file path or a symlink path: os/packages/rocketchat_livechat/public/head.html
    at Builder.write (C:\tools\isobuild\builder.js:225:13)
    at Builder.writeToGeneratedFilename (C:\tools\isobuild\builder.js:353:10)
    at C:\tools\isobuild\isopack.js:1346:27
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\The-A\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at _.each._.each.builder.generateFilename.directory (C:\tools\isobuild\isopack.js:1320:11)
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\The-A\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\isopack.js:1233:9
    at [object Object]._.extend.saveToPath (C:\tools\isobuild\isopack.js:1585:26)
    at C:\tools\isobuild\isopack-cache.js:289:23
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend._loadLocalPackage (C:\tools\isobuild\isopack-cache.js:227:18)
    at C:\tools\isobuild\isopack-cache.js:166:14
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:158:20)
    at C:\tools\isobuild\isopack-cache.js:73:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\The-A\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at [object Object]._.extend.eachPackage (C:\tools\packaging\package-map.js:49:7)
    at [object Object]._.extend.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:72:24)
    at C:\tools\project-context.js:735:25
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._buildLocalPackages (C:\tools\project-context.js:734:18)
    at C:\tools\project-context.js:257:35
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\tools\project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.js:240:10)
    at C:\tools\runners\run-app.js:517:29
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at bundleApp (C:\tools\runners\run-app.js:516:31)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:594:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:858:28)
    at C:\tools\runners\run-app.js:396:12

C:\Users\The-A\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: Builder can not write without either data or a file path or a symlink path: os/packages/rocketchat_livechat/public/head.html
    at Builder.write (C:\tools\isobuild\builder.js:225:13)
    at Builder.writeToGeneratedFilename (C:\tools\isobuild\builder.js:353:10)
    at C:\tools\isobuild\isopack.js:1346:27
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\The-A\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at _.each._.each.builder.generateFilename.directory (C:\tools\isobuild\isopack.js:1320:11)
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\The-A\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\isopack.js:1233:9
    at [object Object]._.extend.saveToPath (C:\tools\isobuild\isopack.js:1585:26)
    at C:\tools\isobuild\isopack-cache.js:289:23
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend._loadLocalPackage (C:\tools\isobuild\isopack-cache.js:227:18)
    at C:\tools\isobuild\isopack-cache.js:166:14
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:158:20)
    at C:\tools\isobuild\isopack-cache.js:73:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\The-A\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at [object Object]._.extend.eachPackage (C:\tools\packaging\package-map.js:49:7)
    at [object Object]._.extend.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:72:24)
    at C:\tools\project-context.js:735:25
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._buildLocalPackages (C:\tools\project-context.js:734:18)
    at C:\tools\project-context.js:257:35
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\tools\project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.js:240:10)
    at C:\tools\runners\run-app.js:517:29
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at bundleApp (C:\tools\runners\run-app.js:516:31)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:594:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:858:28)
    at C:\tools\runners\run-app.js:396:12

**Comment by Grinsens** [comment]
1) open "Rocket.Chat\.meteor"
2) open file "packages"
3) find "rocketchat:livechat"
4) "rocketchat:livechat" -> "#rocketchat:livechat"
5) save
6) run chat

**Comment by engelgabriel** [comment]
We created a shell script to build the livechat module. We need to create a .bat version to make it compatible with Windows

**Comment by engelgabriel** [comment]
@rodrigok we need a `.bat`version of `/packages/rocketchat-livechat/plugin/build.sh`

**Comment by sysstas** [comment]
I tried 5) "rocketchat:livechat" -> "#rocketchat:livechat"
but it didn't help. the same error... Is there any way to start meteor with rocket.chat on windows?

**Comment by graywolf336** [comment]
Are you positive you did that? As I just tried it on Windows after
commenting out the live chat and it works fine.

**Comment by sysstas** [comment]
yes, positive. notthing change. I tried this trick on 2 laptops - one is on windows 10 and the seccond is on windows 7. The same error:

C:\Users\╨Ю╨╗╤П\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.
x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: ENOENT, open 'C:\Users\521F~1\AppData\Local\Temp\mt-16ovcef\os\konecty:mu
ltiple-instances-status.js'
........ and many text more.. 
Help please

**Comment by graywolf336** [comment]
Please post the full errors, those look like different errors then the
original.

**Comment by sysstas** [comment]
C:\Stas\Rocket.Chat>meteor
[[[[[ C:\Stas\Rocket.Chat ]]]]]

=> Started proxy.
=> Started MongoDB.

C:\Users\╨Ю╨╗╤П\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.
x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: ENOENT, open 'C:\Users\521F~1\AppData\Local\Temp\mt-7scc4j\os\konecty:mul
tiple-instances-status.js'
    at Object.Future.wait (C:\Users\╨Ю╨╗╤П\AppData\Local\.meteor\packages\meteor
-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:3
98:15)
    at C:\tools\fs\files.js:1331:28
    at Object.wrapper [as open] (C:\tools\fs\files.js:1334:20)
    at Object.files.readBufferWithLengthAndOffset (C:\tools\fs\files.js:1474:20)

    at C:\tools\isobuild\isopack.js:984:26
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\╨Ю╨╗╤П\AppData\Local\.meteor\packages
\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\
underscore.js:79:11)
    at C:\tools\isobuild\isopack.js:982:9
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\╨Ю╨╗╤П\AppData\Local\.meteor\packages
\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\
underscore.js:79:11)
    at [object Object]._.extend._loadUnibuildsFromPath (C:\tools\isobuild\isopac
k.js:942:7)
    at C:\tools\packaging\tropohouse.js:500:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\╨Ю╨╗╤П\AppData\Local\.meteor\packages
\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\
underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:499:11
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at Object.download (C:\tools\packaging\tropohouse.js:437:20)
    at C:\tools\packaging\tropohouse.js:575:22
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packagi
ng\tropohouse.js:572:20)
    at C:\tools\project-context.js:702:25
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at C:\tools\project-context.js:701:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalo
g\catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (C:\tools\project-contex
t.js:700:13)
    at C:\tools\project-context.js:257:35
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.
js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\tools\project-context.js:
235:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.
js:240:10)
    at C:\tools\runners\run-app.js:517:29
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at bundleApp (C:\tools\runners\run-app.js:516:31)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:594:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:858:28)
    at C:\tools\runners\run-app.js:396:12
    - - - - -

C:\Stas\Rocket.Chat>

**Comment by graywolf336** [comment]
Your error is the following:

`Error: ENOENT, open 'C:\Users\521F~1\AppData\Local\Temp\mt-7scc4j\os\konecty:mul
tiple-instances-status.js'`

Once you fix that, report back.

**Comment by sysstas** [comment]
I didn't modify any rocket.chat files yet. They are still original. 
How can I fix that moment? Can you, please, give some advices?

**Comment by sysstas** [comment]
it throw same error if I try to  `meteor add konecty:multiple-instances-status`

**Comment by rodrigok** [comment]
@sysstas your error was fixed via https://github.com/RocketChat/Rocket.Chat/commit/18617047861c7d571aa692bf966af1ef26a3d7d4?ts=2

**Comment by rodrigok** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/commit/62fe5c830b40fbacef100e36cdd6f00ce2ec2e49?ts=2

**Comment by sysstas** [comment]
Rodrigo Nascimento fixed it. Now it works well. Thank's)

**Comment by JulianKingman** [comment]
I'm having this problem on OSX. I just ran:

````
git clone https://github.com/RocketChat/Rocket.Chat.git
cd Rocket.Chat
meteor
````
