### ISSUE TITLE
Error after upgrade to 3.10.3

### ISSUE THREAD

**Issue by MJPGPleasant** [RocketChat/Rocket.Chat#20191]
### Description:

After upgrading from Rocket.Chat 3.10.0 to 3.10.3, OAuth users receive the error "No matching login attempt found" and is left at the RocketChat "Loading" page. Page refresh properly loads without error, and error does not seem to occur on subsequent logons.   

### Steps to reproduce:

1. Have OAuth configured in an older release of RocketChat, and valid OAuth users authenticated 
2. Upgrade the RocketChat Server
3. Log on with one of these previously configured / authenticated users

### Expected behavior:

User should be able to log in without error

### Actual behavior:

Error: No matching login attempt found (Red Error message on top right) and the Rocket.Chat loading page remains. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0 > 3.10.3
- Operating System: Ubuntu 20.04
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Chrome (Latest)
- Operating System: Windows 10

### Additional context

- Custom OAuth using Azure AD v1
- May be related to changes associated with #20003
- Username and name fields have been updated from original values supplied by Azure.
- Error only occurs on first logon after upgrade, subsequent logons work as expected.

### Relevant logs:

```
I20210113-16:05:58.390(0) Failed login detected - Username[unknown] ClientAddress[x.x.x.x] ForwardedFor[x.x.x.x] XRealIp[x.x.x.x] UserAgent[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36] 
I20210113-16:05:58.428(0) Exception while invoking method login Error: No matching login attempt found [145546287]
     at MethodInvocation.<anonymous> (packages/accounts-oauth/oauth_server.js:35:21)
     at packages/accounts-base/accounts_server.js:475:31
     at tryLoginMethod (packages/accounts-base/accounts_server.js:1309:14)
     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:473:22)
     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)
     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:533:31)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
     at packages/ddp-server/livedata_server.js:1689:15
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at packages/ddp-server/livedata_server.js:1687:36
     at new Promise (<anonymous>)
     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
     at Object.post (app/api/server/v1/misc.js:262:26)
     at app/api/server/api.js:394:82
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
     at packages/nimble_restivus/lib/route.coffee:59:33
     at packages/simple_json-routes.js:98:9
  => awaited here:
     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
     at Object.post (app/api/server/v1/misc.js:262:26)
     at app/api/server/api.js:394:82
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
     at packages/nimble_restivus/lib/route.coffee:59:33
     at packages/simple_json-routes.js:98:9 
```

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
