### ISSUE TITLE
Integration telegram and LiveChat (Omnichannel RocketChat) not working

### ISSUE THREAD

**Issue by VickoF** [RocketChat/Rocket.Chat#20241]
### Description:
I´m trying to integrate telegram messenger to rocket chat livechat.
I´ve searched the documentation and the forum and other resources, but was unable to find any information for integration telegram and livechat RocketChat.

### Steps to reproduce:

1. registration in cloud rocket chat and connect it
2. installing the telegram application from the rocket chat store
3. registering a bot in a telegram, receiving a token and writing this token to the application’s telegram settings in rocket chat
4.   Adding a telegram bot to a telegram account, and trying to write a message.

### Expected behavior:

Rocket chat omnichannel has any messages from telegram
### Actual behavior:
Rocket chat omnichannel has no messages from telegram

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.4
- Operating System: Linux 
- Deployment Method:  docker
- Number of Running Instances:  1
- DB Replicaset Oplog:  oplog is on
- NodeJS Version:  v12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version:  browser /latest app rocketchat ios/android
- Operating System: windows/osx 

### Additional context

Can someone please point me in the right direction or any documentation or information with it?

Thank you very much for the rocket chat and for making and improving this important product.

**Comment by renatobecker** [comment]
@murtaza98 can you please take a look at this case?

Thanks.

**Comment by murtaza98** [comment]
Hey @VickoF 

You have followed the correct steps. I'll need some more info to understand what's happening. 

1. Are you setting the `Default Department Id or Name` setting within the app 
2. Could you share the following setting - `Site Url` (Administration -> General -> Site url). Here I want to confirm that the url is `https`
    ![image](https://user-images.githubusercontent.com/34130764/105001921-803b7680-5a56-11eb-8de8-bd565caf6fc9.png)

**Comment by murtaza98** [comment]
Just an FYI, To view the logs, goto App Page (Setting > Apps > Telegram). There click on menu item (3 vertical dots icon) and then select `View Logs`
The recent logs appear on the top and the important ones are `apiExecutor` and `executePostMessageSentHandler`. If any errors are throws by the app they would appear here

**Comment by VickoF** [comment]
> Hey @VickoF
> 
> You have followed the correct steps. I'll need some more info to understand what's happening.
> 
> 1. Are you setting the `Default Department Id or Name` setting within the app
> 2. Could you share the following setting - `Site Url` (Administration -> General -> Site url). Here I want to confirm that the url is `https`
>    ![image](https://user-images.githubusercontent.com/34130764/105001921-803b7680-5a56-11eb-8de8-bd565caf6fc9.png)

Hello @murtaza98 . Looked it, The Site url is present with the https protocol and with a closing slash at the end

**Comment by VickoF** [comment]
> Just an FYI, To view the logs, goto App Page (Administrator > Apps > Telegram). There click on the menu item (3 vertical dots icon) and then select `View Logs`
> The recent logs appear on the top and the important ones are `apiExecutor`, `onSettingUpdated` and `executePostMessageSentHandler`. If any errors are throws by the app they would appear here

Yes, I found the logs. The fact of the matter is that there is nothing errors in the logs

**Comment by murtaza98** [comment]
Hey @VickoF I'm having trouble reproducing the issue you mentioned. I installed the Rocket.Chat server version `3.10.4` and installed the Telegram app there and it worked properly without any issue. Here is the recorded screenshot of the test. Could you verify if this is the correct process you are following

https://user-images.githubusercontent.com/34130764/105140079-37022a00-5b1d-11eb-8d87-f2b4fbea64b9.mp4

**Comment by dudanogueira** [comment]
Hi there @murtaza98!

I was able to make it work at 3.4.10. 

@VickoF be aware of the ngrok limitations. It will block your url if you pass the free tier request limit.

This App was previously working great at 3.4.10, but after 3.11.0 its on longer working.

This problem was also pointed at this issue: #19891 

It may or may not be related to this PR: #16467

error: 2021-02-08T18:01:31.369Z Caller: post -> post
[
  "Error occurred while processing the request. Details:- ",
  "{\"stack\":\"Error: No permission checker found for the bridge method \\\"AppLivechatBridge.isOnlineAsync\\\"\\nPlease create a new cheker one under the permissionChekers folder to fix the issue.\\n    at Function.checkPermission (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/managers/AppPermissionManager.js:47:19)\\n    at Proxy.<anonymous> (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/managers/AppPermissionManager.js:18:68)\\n    at LivechatRead.isOnlineAsync (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/accessors/LivechatRead.js:18:36)\\n    at IncomingMessages.processRequest (evalmachine.<anonymous>:46:62)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\\n    at IncomingMessages.post (evalmachine.<anonymous>:22:13)\",\"message\":\"No permission checker found for the bridge method \\\"AppLivechatBridge.isOnlineAsync\\\"\\nPlease create a new cheker one under the permissionChekers folder to fix the issue.\"}"
]

Any clues?

**Comment by dudanogueira** [comment]
I tried giving permission to the app role at the permissions option. Same result..

I was able to find some places that should have something to do with it. But I have no clue browsing into Rocketchat code, so...

**Comment by dudanogueira** [comment]
Like here: https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/master/src/server/permissions/checkers/AppLivechatBridge.ts

looks like the App Engine is trying to check if the TelegramApp has permissions to use this method. Maybe... if one create a method there it will pass this issue, but no clue whatsoever, ehehehe

I cant even try to edit the code insde the container, as its compile into one big file.

Anyway, hope our great developers help here :)

**Comment by renatobecker** [comment]
Hey @dudanogueira I'm passing by to say that our engineering team has already found the issue and the fix is coming very soon.

**Comment by murtaza98** [comment]
Hey @dudanogueira, Here's the fix for this issue - https://github.com/RocketChat/Rocket.Chat/pull/20653

**Comment by dudanogueira** [comment]
That's awesome. Thank you guys!!

**Comment by VickoF** [comment]
> Привет, @VickoF, у меня проблемы с воспроизведением упомянутой вами проблемы. Я установил серверную версию Rocket.Chat, `3.10.4`установил там приложение Telegram, и оно работало без проблем. Вот записанный снимок экрана теста. Не могли бы вы проверить, соблюдаете ли вы этот процесс?
> 
>  2021-01-20.12-38-40.mp4

hi. I'm using version 3.11.1 Rocketchat (latest) in docker, After added token  and after type "/start" in telegram, there aren't l no messages in omnichanne from telegram.

**Comment by d-gubert** [comment]
Hey @VickoF! It looks like we couldn't pin down what might be happening with your setup, so we'll need to try and understand better this situation, as it seems to be something related to that.

You seem to be using `ngrok`, can you share its logs? It looks like Telegram is not being able to reach your server.

Earlier you shared the logs of your app. The log you shared was a `executePostMessageSent`, and this is most likely related to your app sending messages over to Telegram. You should look out for `apiExecutor` logs, which would refer to your app receiving something from Telegram

**Comment by VickoF** [comment]
Hello  @murtaza98 .  In the latest version, the ability to integrate LiveChat into Omnichannel has disappeared. Where have you moved the settings? Don't see the Omnichannel panel? Tell me where to look for all this?

**Comment by dudanogueira** [comment]
> Hello @murtaza98 . In the latest version, the ability to integrate LiveChat into Omnichannel has disappeared. Where have you moved the settings? Don't see the Omnichannel panel? Tell me where to look for all this?

Hi @VickoF the Omnichannel menu (as well as the Admin) is now where the profile is. Just click at your avatar picture, where you set your presence status.

If you need help setting up the telegram app, let me know, I can help you. I have managed to install it and it's now working again at 3.11.1

**Comment by Uzzi** [comment]
Hi, Telegram-RocketChat-Ominichannel integration require Internet exposed RocketChat Server?

**Comment by murtaza98** [comment]
> Hi, Telegram-RocketChat-Ominichannel integration require Internet exposed RocketChat Server?

Yes

**Comment by Uzzi** [comment]
> > Hi, Telegram-RocketChat-Ominichannel integration require Internet exposed RocketChat Server?
> 
> Yes

:(

**Comment by thecion** [comment]
Hello guys,

I'm also trying to make the Telegram App work with my RocketChat server, but it's not working so far.

I'm trying to test it with this config: RocketChat Server Version 3.14.2, running on Docker under a ngrok URL.

One thing I could see on the RocketChat server logs was this kind of messages:

```
Error: Failed to call the method  as the app (fc96e832-5472-49e4-aace-1521a7ebeaa6) lacks the following permissions:
["api"]. Declare them in your app.json to fix the issue.
reason: undefined

Error: Failed to call the method  as the app (fc96e832-5472-49e4-aace-1521a7ebeaa6) lacks the following permissions:
["networking"]. Declare them in your app.json to fix the issue.
reason: undefined
```

I had this issue before with another App, but I "fixed" by doing this:

- Download the source code of the App
- Change app.json to reflect the permissions, which were specified in the log.
- Build using npm
- Deploy using "rc-apps deploy"

After this the App started working, but I don't think this is the case with Telegram App since I couldn't find the correct repository. 

Do you have any pointers on what is happening? Could be something with the docker image or am I missing something? Is there a repository for Telegram App?

**Comment by renatobecker** [comment]
> Hello guys,
> 
> I'm also trying to make the Telegram App work with my RocketChat server, but it's not working so far.
> 
> I'm trying to test it with this config: RocketChat Server Version 3.14.2, running on Docker under a ngrok URL.
> 
> One thing I could see on the RocketChat server logs was this kind of messages:
> 
> ```
> Error: Failed to call the method  as the app (fc96e832-5472-49e4-aace-1521a7ebeaa6) lacks the following permissions:
> ["api"]. Declare them in your app.json to fix the issue.
> reason: undefined
> 
> Error: Failed to call the method  as the app (fc96e832-5472-49e4-aace-1521a7ebeaa6) lacks the following permissions:
> ["networking"]. Declare them in your app.json to fix the issue.
> reason: undefined
> ```
> 
> I had this issue before with another App, but I "fixed" by doing this:
> 
> * Download the source code of the App
> * Change app.json to reflect the permissions, which were specified in the log.
> * Build using npm
> * Deploy using "rc-apps deploy"
> 
> After this the App started working, but I don't think this is the case with Telegram App since I couldn't find the correct repository.
> 
> Do you have any pointers on what is happening? Could be something with the docker image or am I missing something? Is there a repository for Telegram App?

@murtaza98 can you look into this, please?

**Comment by murtaza98** [comment]
Hey @thecion 
Ideally there shouldn't be any permission issue in this app since the Telegram app requires version >=`1.18.0` apps-engine package however the permission system was introduced in version `1.20.0` - To handle this the apps-engine team had setup [this rule](https://developer.rocket.chat/apps-development/permission-system#notice-about-rule-enforcement) which gives default permissions to all the apps <`1.20.0` which includes the Telegram app, however since this isn't happening now, I think the apps-engine behaviour of default permissions must have changed. I'll have to discuss this further with the apps-engine team to know what's the issue.

Until then, here's the package of the app with all the permissions defined. 

To install it:
1. Uninstall the existing app
2. Start App Development mode
![image](https://user-images.githubusercontent.com/34130764/120155931-03dc4f80-c20f-11eb-8f00-69f670c7aa88.png)
3. Goto Admin -> Apps. Click `Upload apps` button. and there upload the zip file I'm attaching to this message
![image](https://user-images.githubusercontent.com/34130764/120156086-38500b80-c20f-11eb-948d-87f7d3d05714.png)


### Telegram APP Package
[telegram_1.0.2.zip](https://github.com/RocketChat/Rocket.Chat/files/6568524/telegram_1.0.2.zip)

**Comment by thecion** [comment]
Hello @murtaza98 

I was able to get it working with the App Package you built, so it looks like the issue was indeed with the apps-engine permission system.

Great success! Thanks guys.

**Comment by pateljemin** [comment]
@murtaza98 can you give us the actual telegram app source code? I need to make some modifications as per our use case

**Comment by pateljemin** [comment]
@murtaza98 We want to do the following:

1. Onboard merchants by interacting with telegram bot. (Node Js application is listening for those messages and do onboarding process)
2. Once a merchant is onboarded we have chat_id and we are sending them periodic account status every day using corn job. (Separate Node js application is taking care of it)
3. If the merchant is having an issue or question then send a message to the same bot but at this time we want to involve a human agent using the rocket chat Omni telegram app. 

Problem we are facing right now is in the first step node js application is already polling messages using bot token so we can not use that token in the rocket chat Omni app. We do not receive messages in rocket chat. If we stop step one node js app then we receive messages in rocket chat. In short either use token node js app / Rocket chat Omni app. 

So to avoid that problem we are planning to modify the rocket chat Omni app and just use that and forward messages from rocket chat Omni to our node js server. 

I hope this will answer your question. If not you can ask me again which part is not clear. Thank you.

**Comment by renatobecker** [comment]
> @murtaza98 We want to do the following:
> 
> 1. Onboard merchants by interacting with telegram bot. (Node Js application is listening for those messages and do onboarding process)
> 2. Once a merchant is onboarded we have chat_id and we are sending them periodic account status every day using corn job. (Separate Node js application is taking care of it)
> 3. If the merchant is having an issue or question then send a message to the same bot but at this time we want to involve a human agent using the rocket chat Omni telegram app.
> 
> Problem we are facing right now is in the first step node js application is already polling messages using bot token so we can not use that token in the rocket chat Omni app. We do not receive messages in rocket chat. If we stop step one node js app then we receive messages in rocket chat. In short either use token node js app / Rocket chat Omni app.
> 
> So to avoid that problem we are planning to modify the rocket chat Omni app and just use that and forward messages from rocket chat Omni to our node js server.
> 
> I hope this will answer your question. If not you can ask me again which part is not clear. Thank you.

Hi @pateljemin thanks for sharing more context.
The point here is that the architecture you mentioned is not related to **Telegram channel**, it's about your use case/external rule, so it doesn't make sense to introduce such complexity in this App, the best approach, in this case, is to create another App for your use case, the app will listen to the events and will act accordingly.

**Comment by pateljemin** [comment]
@renatobecker Thank you for your feedback but can you guide me? how I can use rocket chat Omnichannel in that case?

**Comment by renatobecker** [comment]
> @renatobecker Thank you for your feedback but can you guide me? how I can use rocket chat Omnichannel in that case?

I'm not following, sorry. What I tried to say is that the same events and methods you want to introduce to Telegram App can be implemented as a new App, you know? In that case you'll listen to all events you need, such as room creation, message sent, room closed, etc. You can then check the context of the room and see if it is a Telegram conversation or not.

**Comment by pateljemin** [comment]
@renatobecker That is what we are planning to do but if that telegram app code is available on GitHub then we can move fast by just forking that and doing our update in that.
