### ISSUE TITLE
Bot created through integration is unable to post to private groups

### ISSUE THREAD

**Issue by gevial** [RocketChat/Rocket.Chat#2025]
Hi all!

I've made an integration to post some stuff to private group but when I'm trying to make request I get a 500 error:

```
$ curl -v -X POST --data-urlencode 'payload={"text":"test"}' https://rocket.example.com/hooks/foo/bar
$ * About to connect() to rocket.example.com port 443 (#0)
*   Trying ... connected
..
> POST /hooks/foo/bar HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: rocket.example.com
> Accept: */*
> Content-Length: 37
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 37out of 37 bytes
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.6.3
< Date: Mon, 25 Jan 2016 14:28:30 GMT
< Content-Type: text/html
< Content-Length: 13
< Connection: keep-alive
< Vary: Accept-Encoding
< Access-Control-Allow-Origin: *
< X-Rocket-Chat-Version: 0.0.1
< Access-Control-Expose-Headers: X-Rocket-Chat-Version
< 
* Connection #0 to host rocket.example.com left intact
* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
```

Rocket.Chat server puts this in the log:
```
Error: [methods] joinRoom -> Not allowed [403]
    at [object Object].Meteor.methods.joinRoom (server/methods/joinRoom.coffee:10:14)
    at [object Object].methodsMap.(anonymous function) (packages/rocketchat_lib/server/lib/debug.js:22:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:1611:18
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.apply (livedata_server.js:1610:45)
    at [object Object]._.extend.call (livedata_server.js:1553:17)
    at [object Object].<anonymous> (packages/rocketchat_integrations/server/api/api.coffee:42:13)
    at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```
Why is it trying to join the room? And why doesn't it have access to the group? Because I already made bot account member of this private group. Is it possible to make bots able to post to private groups?

Thanks.

**Comment by graywolf336** [comment]
Seems to be a duplicate of a closed task #1704, are you running on the latest version?

**Comment by gevial** [comment]
Yeah, this is the same issue, sorry. I watched through all the open issues but competely forgot about closed ones. Thank you!

**Comment by graywolf336** [comment]
Did updating fix the issue for you @gevial?

**Comment by gevial** [comment]
Yes, updating fixed the issue.
