### ISSUE TITLE
ldap (tls) connection fails because of "Error: Hostname/IP doesn't match certificate's altnames"

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#2035]
Hello Devs.

I'm trying to connect to our ldap server who forces the ldap connection on port 389 being tls. When i try to connect i get:

```
Enabling LDAP
Exception while invoking method 'login' Error: Hostname/IP doesn't match certificate's altnames
    at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)
    at packages/meteor/helpers.js:119:1
    at startTLS (packages/rocketchat_ldap/ldap_server.js:58:1)
    at [object Object].LDAP.ldapCheck (packages/rocketchat_ldap/ldap_server.js:96:1)
    at [object Object].__coffeescriptShare (packages/rocketchat_ldap/ldap_server.js:258:1)
    at accounts_server.js:462:32
    at tryLoginMethod (accounts_server.js:239:14)
    at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
    at [object Object].methods.login (accounts_server.js:522:27)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    - - - - -
    at SecurePair.<anonymous> (tls.js:1390:23)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at Socket.ondata (stream.js:51:26)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
```

The Ldap Server uses a wildcard certificate issued by rapidssl. Is there a way do go around this?

thanks and cheers
t.

**Comment by tuudik** [comment]
Try Reject Unauthorized: False.

I had same issue when putting other LDAP feat. TLS issues aside. I think this looks kinda defect. But based on conversation in https://github.com/RocketChat/Rocket.Chat/issues/1967 LDAP code will be re-worked anyway.

**Comment by engelgabriel** [comment]
Note that, in node 0.10.x, if you connect using an IP, the IP address has to be in the altnames - node.js will not try to verify the IP against the CN.

Setting the rejectUnauthorized flag to false will get around this check, but first of all if the server is giving you different credentials than you are expecting, something fishy is going on, and second this will also bypass other checks - it's not a good idea if you're connecting over the Internet.

**Comment by tuudik** [comment]
@engelgabriel I've tried with DNS name and inserted according CA cert from ldap machine. And still got the error :/

**Comment by tuudik** [comment]
Any progress with that issue? I accidentaly created new issue: #2188

**Comment by engelgabriel** [comment]
Yes, please try the version 0.18.0 just released.

**Comment by engelgabriel** [comment]
But the comments about node 0.10.x still applies.

**Comment by ich1** [comment]
Could just use stunnel4 instead

**Comment by tuudik** [comment]
Updated to v.0.18.0

CA certificate:
```
-----BEGIN CERTIFICATE-----
MIIDZTCCAh2gAwIBAgIEVoTrxjANBgkqhkiG9w0BAQsFADAiMSAwHgYDVQQDExdJ
bnRlZ3JhdGVkIFdvcmxkIEx0ZCBDQTAeFw0xNTEyMzEwODQ4MDZaFw0xNjEyMzAw
ODQ4MDZaMCIxIDAeBgNVBAMTF0ludGVncmF0ZWQgV29ybGQgTHRkIENBMIIBUjAN
BgkqhkiG9w0BAQEFAAOCAT8AMIIBOgKCATEAxLdjVwuD7+0on0Gie4Wa58o6wEcR
PwJ/AvZ6kY1fn0eXto9SX/GjHX5gqZVPN2tQeIb9c4ked08LMKWiCZIBibZuY1rn
sVykz/DVp1ip6zejAMD8IJ0zV+pDy3Q/gFAg1WJd0tV2HVm0pcngzyVHj/1Rc+4E
C9uGg5p3Gli+StLauqg1GWouFWlPK4+ceNsCEwmP2NSjYrRWfeH+Xgy7y1Y3v2+T
eijJBEt7l6DhfLVV45+2wgg76j8VKT6a1qj4hoOmIfMynlfbpzXPJQLkDYr9xWMz
vmwEZGy4hjzGTu2hKzjkbD7P+5kxnSN6ZYdNWthj0SId2bbFV0rwuWTHEXGNBswR
8qo/xz0AdSzbl43heNIIiSX7yLqOTUiKRdqdQSwIKmxK08OetPIat9AkmwIDAQAB
o0MwQTAPBgNVHRMBAf8EBTADAQH/MA8GA1UdDwEB/wQFAwMHBAAwHQYDVR0OBBYE
FIe0ll9a/dWusFxCVMi3c8eSg7sDMA0GCSqGSIb3DQEBCwUAA4IBMQAWjMyk6/sI
zGQSt+QMZhaH2rQuRb0HNsB/mhjvif9ODWH3O6+4Yqwk1xkF5SCEYyO1uskSk/ih
d+sGK5L5/KktCDAmJQvzzJh+kbFwT5YHEm2ZOos9aQDZparDesT8rs05kh54rmTT
D8kMwyvUo75lNjSv5imsZYlj7yc1OpQxTZ5hEjsxcSPJSoNVGQ2xm6XisrDsFmqW
x8LUm5aqn0PjL2bzn+Ip91eBPSd3dav9KdH079f+8bp4LmhS7XjzDqcROMQR+9KA
mhDn8wu0Lh9V4yL3kYm4pS7zc9Wrd+RmlUuPxakwFX0GLn193QAhEZxiDveNrLDA
AySt/GbvUYmHApdpnNrqhCz6hCR1MoJYzCH+TjPEY0+hcsdzvyb9qvbKyivFQ9fD
ZhyY+wvcGPYg
-----END CERTIFICATE-----
```

LDAP server certificate:
```
-----BEGIN CERTIFICATE-----
MIIETDCCAwSgAwIBAgIEVsHXyDANBgkqhkiG9w0BAQsFADAiMSAwHgYDVQQDExdJ
bnRlZ3JhdGVkIFdvcmxkIEx0ZCBDQTAeFw0xNjAyMTUxMzUxMDRaFw0yNjAyMTQx
MzUxMDRaMEMxHjAcBgNVBAoTFUludGVncmF0ZWQgV29ybGQgTHRkLjEhMB8GA1UE
AxMYbGRhcC5pbnRlZ3JhdGVkd29ybGQubmV0MIIBuDANBgkqhkiG9w0BAQEFAAOC
AaUAMIIBoAKCAZcAv0E782I6jMYEetN7Nzf+6O8VUkbJ/yzL6EcFbmt0fJRQ1s0n
dthI5lh2hWZfem4wtlkm5QAxHEHUPzQP6iE7oj0g/0AFEKaMd6769jHXJ/v1MHBB
PcXxlSaKG+AWjQZ8LHBJcwx2wmXHiinPBRCOaohI1OuY37g795hsNKNEepq75xJh
8V4sF2BjGFWnA80tRca+RP4NbfoEcmsi5L9ujyBTbkrFOoTlIiq8vjgI7U35ANXc
UdksOS081ZGZRJV8kecI+z4TJvKNnuf/2AykXh/2CgVkpfObvoL6qyWUlprVURK4
m+3BJMSJvV6jeXLaM3xDUuPM8QQoEMSP4P/e+dZ20dPf8Efrk3bEZ10d9WJ1U67t
t3FKQ0QLukcU5w0TdJOWLvuQ5gTOK4tQH0rwQnuOswJcfoDq6TCyV/6k7Yr/Xssn
3dCkuz5mm2QHGkqyr2VPmutKQbbb2qT15qKEqwSnNNzyEytzTaZTxuMuzvAVCGVT
LLZAeY84ja0EPBzkrMKatk1mFLwpROm4OuFh+lLzGw9heQIDAQABo4GiMIGfMAwG
A1UdEwEB/wQCMAAwKQYDVR0RBCIwIIIYbGRhcC5pbnRlZ3JhdGVkd29ybGQubmV0
hwQ2wnOXMBMGA1UdJQQMMAoGCCsGAQUFBwMBMA8GA1UdDwEB/wQFAwMHoAAwHQYD
VR0OBBYEFLDu0ocvaZIbQ+PS/DoMZBFfuh1OMB8GA1UdIwQYMBaAFIe0ll9a/dWu
sFxCVMi3c8eSg7sDMA0GCSqGSIb3DQEBCwUAA4IBMQCYupl6UEltJnZww8AIwsQc
pcvh/fEBgttTRhRoB7ZvpOeAXD2CsTQqaUhi0g0XKqgNhBdA+lp8BMG8IYL0uRzy
yNHMvVTCKmoMvMHHyiGzEc08jRlr6IVlgUw9/XywLMQbxXja11L/LGuHWfQ9XL+/
fSHoBkw61pue1/IriH54l7Gblxe38KvN2QZyHFL0k+dAIV9quOKiAPDfNZkQhxbq
VYFtX4zEt3tXxrOPJ3Q6ASFMgxmX+LSvJptuIN1cTuOYyxYcwCbD37G+xmPzqmfH
+KPgDstoP32RQpH1MAf64rIQK2snseQM659nNwK/1QonwvdcwRVR06HV5TIgx01M
DfyRJ6pPeCVjaoWQzqmbPEUHH8ZIyaT46X8B0ZuhEsbW4Eq5aZtS5ChvACiEgBI1
-----END CERTIFICATE-----
```

And I added the IP to Subject Alternative name:
```
            X509v3 Subject Alternative Name: 
                DNS:ldap.integratedworld.net, IP Address:54.194.115.151
```

Yet, still:
```
ldap.js:97 LDAP ➔ connection_error TLS connection [Error: Hostname/IP doesn't match certificate's altnames]
{ [Error: Hostname/IP doesn't match certificate's altnames] stack: [Getter] }
```

**Comment by rodrigok** [comment]
Your * LDAP server certificate* contains 
```
            X509v3 Subject Alternative Name:
                DNS:ldap.integratedworld.net, IP Address:54.194.115.151
```

but your CA no:
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1451551686 (0x5684ebc6)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Integrated World Ltd CA
        Validity
            Not Before: Dec 31 08:48:06 2015 GMT
            Not After : Dec 30 08:48:06 2016 GMT
        Subject: CN=Integrated World Ltd CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2432 bit)
                Modulus:
                    00:c4:b7:63:57:0b:83:ef:ed:28:9f:41:a2:7b:85:
                    9a:e7:ca:3a:c0:47:11:3f:02:7f:02:f6:7a:91:8d:
                    5f:9f:47:97:b6:8f:52:5f:f1:a3:1d:7e:60:a9:95:
                    4f:37:6b:50:78:86:fd:73:89:1e:77:4f:0b:30:a5:
                    a2:09:92:01:89:b6:6e:63:5a:e7:b1:5c:a4:cf:f0:
                    d5:a7:58:a9:eb:37:a3:00:c0:fc:20:9d:33:57:ea:
                    43:cb:74:3f:80:50:20:d5:62:5d:d2:d5:76:1d:59:
                    b4:a5:c9:e0:cf:25:47:8f:fd:51:73:ee:04:0b:db:
                    86:83:9a:77:1a:58:be:4a:d2:da:ba:a8:35:19:6a:
                    2e:15:69:4f:2b:8f:9c:78:db:02:13:09:8f:d8:d4:
                    a3:62:b4:56:7d:e1:fe:5e:0c:bb:cb:56:37:bf:6f:
                    93:7a:28:c9:04:4b:7b:97:a0:e1:7c:b5:55:e3:9f:
                    b6:c2:08:3b:ea:3f:15:29:3e:9a:d6:a8:f8:86:83:
                    a6:21:f3:32:9e:57:db:a7:35:cf:25:02:e4:0d:8a:
                    fd:c5:63:33:be:6c:04:64:6c:b8:86:3c:c6:4e:ed:
                    a1:2b:38:e4:6c:3e:cf:fb:99:31:9d:23:7a:65:87:
                    4d:5a:d8:63:d1:22:1d:d9:b6:c5:57:4a:f0:b9:64:
                    c7:11:71:8d:06:cc:11:f2:aa:3f:c7:3d:00:75:2c:
                    db:97:8d:e1:78:d2:08:89:25:fb:c8:ba:8e:4d:48:
                    8a:45:da:9d:41:2c:08:2a:6c:4a:d3:c3:9e:b4:f2:
                    1a:b7:d0:24:9b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Key Usage: critical
                Certificate Sign
            X509v3 Subject Key Identifier: 
                87:B4:96:5F:5A:FD:D5:AE:B0:5C:42:54:C8:B7:73:C7:92:83:BB:03
    Signature Algorithm: sha256WithRSAEncryption
         16:8c:cc:a4:eb:fb:08:cc:64:12:b7:e4:0c:66:16:87:da:b4:
         2e:45:bd:07:36:c0:7f:9a:18:ef:89:ff:4e:0d:61:f7:3b:af:
         b8:62:ac:24:d7:19:05:e5:20:84:63:23:b5:ba:c9:12:93:f8:
         a1:77:eb:06:2b:92:f9:fc:a9:2d:08:30:26:25:0b:f3:cc:98:
         7e:91:b1:70:4f:96:07:12:6d:99:3a:8b:3d:69:00:d9:a5:aa:
         c3:7a:c4:fc:ae:cd:39:92:1e:78:ae:64:d3:0f:c9:0c:c3:2b:
         d4:a3:be:65:36:34:af:e6:29:ac:65:89:63:ef:27:35:3a:94:
         31:4d:9e:61:12:3b:31:71:23:c9:4a:83:55:19:0d:b1:9b:a5:
         e2:b2:b0:ec:16:6a:96:c7:c2:d4:9b:96:aa:9f:43:e3:2f:66:
         f3:9f:e2:29:f7:57:81:3d:27:77:75:ab:fd:29:d1:f4:ef:d7:
         fe:f1:ba:78:2e:68:52:ed:78:f3:0e:a7:11:38:c4:11:fb:d2:
         80:9a:10:e7:f3:0b:b4:2e:1f:55:e3:22:f7:91:89:b8:a5:2e:
         f3:73:d5:ab:77:e4:66:95:4b:8f:c5:a9:30:15:7d:06:2e:7d:
         7d:dd:00:21:11:9c:62:0e:f7:8d:ac:b0:c0:03:24:ad:fc:66:
         ef:51:89:87:02:97:69:9c:da:ea:84:2c:fa:84:24:75:32:82:
         58:cc:21:fe:4e:33:c4:63:4f:a1:72:c7:73:bf:26:fd:aa:f6:
         ca:ca:2b:c5:43:d7:c3:66:1c:98:fb:0b:dc:18:f6:20
```

Is this right? I'm not a SSL expert :smile:

**Comment by tuudik** [comment]
Yes, it's correct. :)

For example, when ordering https certificate from Thawte or VeriSign, they won't add your domain/ip to their CA certificate.

**Comment by rodrigok** [comment]
@tuudik unfortunately no, this is a nodejs limitation in version 0.10.x.

There is some way to add this addresses to your CA too to try to solve this problem?

**Comment by tuudik** [comment]
@rodrigok https://help.ubuntu.com/community/GnuTLS#Certificate_Authority_Certificates

It's not possible to add IP/DNS to CA certificate

**Comment by ich1** [comment]
so am i correct in assuming documented support for LDAPS using TLS (instead of stunnel4 hack) exists and is currently in use?

**Comment by engelgabriel** [comment]
Yes @ich1, the problem is only with self signed.

**Comment by ich1** [comment]
Ok, I just deployed using stunnels, glad this is working :D might have to redo my setup now

**Comment by litewhatever** [comment]
Seems like this is only occurring with starttls but not with ldaps. So perhaps its an issue in upstream with ldapjs itself?

**Comment by litewhatever** [comment]
I think I have managed to confirm it as a upstream issue.
https://github.com/mcavage/node-ldapjs/issues/349

**Comment by litewhatever** [comment]
From upstream (ldapjs) developer noted that this issue will occur with older node versions (e.g 0.10.40).
> The situation is complicated, in the case of starttls, by the fact an existing socket is being "upgraded" to TLS. May I inquire about the version of node.js you used to test in this case? Automatic population of the TLS hostname does appear to be present in some (but not all) versions.

**Comment by engelgabriel** [comment]
This issues is unfixable until Meteor 1.4, when it will automatically be fixed.

> Note that, in node 0.10.x, if you connect using an IP, the IP address has to be in the altnames - node.js will not try to verify the IP against the CN.

**Comment by litewhatever** [comment]
To clarify I'm not connecting with IP nor is @tuudik for my knowledge.

This is coming from `tls.connect` method which is used by `ldap.starttls`.
https://nodejs.org/api/tls.html#tls_tls_connect_options_callback

tls.connect isn't populating automatically options with hostname in older nodejs versions. In newer versions this is happening automatically (I can confirm v5.6.0).

If clarification needed - please have a look at the example code:
https://github.com/mcavage/node-ldapjs/issues/349

**Comment by engelgabriel** [comment]
Looks like https://github.com/RocketChat/Rocket.Chat/pull/2256 fixed this.

**Comment by engelgabriel** [comment]
Can you guys please try the development branch/build and reopen this if it is not fixed?
