### ISSUE TITLE
MongoError: not master

### ISSUE THREAD

**Issue by shibumi** [RocketChat/Rocket.Chat#20387]
### Description:

I try to deploy rocketchat with the bitnami mongodb helm chart as external mongodb.

My mongodb deployment looks like this:

```
NAME                    READY   STATUS    RESTARTS   AGE
pod/mongodb-0           2/2     Running   0          8h
pod/mongodb-1           2/2     Running   0          8h
pod/mongodb-arbiter-0   1/1     Running   0          8h

NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
service/mongodb-arbiter-headless   ClusterIP   None            <none>        27017/TCP   8h
service/mongodb-headless           ClusterIP   None            <none>        27017/TCP   8h
service/mongodb-metrics            ClusterIP   10.43.194.240   <none>        9216/TCP    8h

NAME                               READY   AGE
statefulset.apps/mongodb           2/2     8h
statefulset.apps/mongodb-arbiter   1/1     8h
```

Rocketchat should now connect to the mongodb-headless service.
Rocketchat has the following mongodb URIs:

```
mongo-oplog-uri = mongodb://root:X@mongodb-headless.mongodb-10-5.svc.cluster.local/local?replicaSet=rs0&authSource=admin
mongo-uri = mongodb://rocketchat:X@mongodb-headless.mongodb-10-5.svc.cluster.local/rocketchat
```

When I connect with the mongo client everything works as expected, but when I start rocketchat I get this error here:

```
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Exception in callback of async function: MongoError: not master
    at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:450:61)
    at Connection.emit (events.js:311:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at processMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:384:10)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:553:15)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  topologyVersion: { processId: 600e876977001add0e333076, counter: 3 },
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1611593570 },
  ok: 0,
  errmsg: 'not master',
  code: 10107,
  codeName: 'NotWritablePrimary',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1611593570 },
    signature: { hash: [Binary], keyId: [Long] }
  },
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {}
}
Setting default file store to GridFS
```

Do you have any idea how to solve this?

### Steps to reproduce:

1. Deploy bitnami/mongodb helm chart with HA setup "replication" + Arbiter
2. Deploy Rocketchat helm chart and specify the bitnami mongodb cluster as external mongodb cluster

### Expected behavior:

Rocketchat should be deployable with an external mongodb

### Actual behavior:

Rocketchat complains about missing master, but it's a headless kubernetes service and mongodb should just connect to one
of the mongodb pods and that should get replicated over all nodes.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0
- Operating System: Kubernetes
- Deployment Method: Helm Chart
- Number of Running Instances: 1
- MongoDB Version: 10.5

### Client Setup Information

not needed

### Additional context

Your helm chart is outdated. Stable/Rocketchat is deprecated and your new repository is still empty.

### Relevant logs:

```
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Exception in callback of async function: MongoError: not master
    at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:450:61)
    at Connection.emit (events.js:311:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at processMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:384:10)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:553:15)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  topologyVersion: { processId: 600e876977001add0e333076, counter: 3 },
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1611593570 },
  ok: 0,
  errmsg: 'not master',
  code: 10107,
  codeName: 'NotWritablePrimary',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1611593570 },
    signature: { hash: [Binary], keyId: [Long] }
  },
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {}
}
Setting default file store to GridFS
```

**Comment by MatthiasHertel** [comment]
@shibumi 

hey did u find any solution for this ?

**Comment by shibumi** [comment]
@MatthiasHertel I am not sure. Let me have a look at work on tuesday. It's a while ago and we tried to use rocket chat as support chat, but failed.

**Comment by aelyasi** [comment]
@shibumi

hey did u find any solution for this ?

**Comment by shibumi** [comment]
@aelyasi  I think the following setup worked for me:

mongo-uri='mongodb://rocketchat:SECRETPW@mongodb-0.mongodb-headless.mongodb-10-5.svc.cluster.local/rocketchat'
mongo-oplog-uri='mongodb://root:SECRETPW@mongodb-1.mongodb-headless.mongodb-10-5.svc.cluster.local/local?replicaSet=rs0&authSource=admin'

The only difference is the FQDN for the mongodb. Here I specified the pods directly. I don't remember why I did this, but I think mongodb-1 was the mongodb that was in master state.

It's really just a very dirty fix.. it's not supposed to work in production this way. I really just wanted to get this deployed for testing.

**Comment by KevLehman** [comment]
This pull request has been inactive for a while, so we’re closing it to keep the backlog manageable.
If you’d like to continue working on it, feel free to reopen or submit a new PR. Thanks for the contribution!
