### ISSUE TITLE
This page isn’t working domain.com didn’t send any data. ERR_EMPTY_RESPONSE . LDAP timeout error log

### ISSUE THREAD

**Issue by JonCSgr** [RocketChat/Rocket.Chat#20415]
### Description:

I am getting empty response page on the homepage after some time rocketchat is running . 

### Steps to reproduce:

1.  Homepage , u will see the error in the screenshot below .
2. 
3. 

### Expected behavior: View rocketchat 

View rocketchat 

### Actual behavior: getting this error page

![download (2)](https://user-images.githubusercontent.com/61245954/105853461-65d14200-5fee-11eb-84fa-734994d95079.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  Latest
- Operating System:  Ubuntu 16.04
- Deployment Method:  snaps
- Number of Running Instances:  1
- DB Replicaset Oplog: ?
- NodeJS Version:  latest i guess i always update
- MongoDB Version: latest installed today

### Client Setup Information

- Desktop App or Browser Version: google chrome latest but tried on firefox etc
- Operating System: windows

### Additional context

Server status : 
![download (3)](https://user-images.githubusercontent.com/61245954/105853627-9022ff80-5fee-11eb-8124-73d4baa19eb6.png)

LDAP timeout settings
![download (5)](https://user-images.githubusercontent.com/61245954/105853558-84cfd400-5fee-11eb-9e1b-5de2b1b551f7.png)

### Relevant logs:
![download (4)](https://user-images.githubusercontent.com/61245954/105853571-87cac480-5fee-11eb-98b4-681f21affe41.png)

**Comment by JonCSgr** [comment]
By modifying the timeouts on LDAP SETTING to 100k each now i can see this:


 server.js:204 LDAPSync ➔ error TimeoutError: request timeout (client interrupt)
Jan 27 12:59:44 rocketchat-server.rocketchat-server[27361]:     at Timeout.onRequestTimeout (/snap/rocketchat-server/1449/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1435:10)
Jan 27 12:59:44 rocketchat-server.rocketchat-server[27361]:     at listOnTimeout (internal/timers.js:549:17)
Jan 27 12:59:44 rocketchat-server.rocketchat-server[27361]:     at processTimers (internal/timers.js:492:7) {
Jan 27 12:59:44 rocketchat-server.rocketchat-server[27361]:   lde_message: 'request timeout (client interrupt)',
Jan 27 12:59:44 rocketchat-server.rocketchat-server[27361]:   lde_dn: null
Jan 27 12:59:44 rocketchat-server.rocketchat-server[27361]: }

p.s server is restarted so its up now and seeing this error.

**Comment by JonCSgr** [comment]
anyone ?

**Comment by JonCSgr** [comment]
Jan 29 11:08:58 rocketchat-server.rocketchat-server[15511]: server.js:204 LDAP ➔ Connection.error connection time out 1000
Jan 29 11:08:58 rocketchat-server.rocketchat-server[15511]: server.js:204 LDAPSync ➔ error Error: Timeout
Jan 29 11:08:58 rocketchat-server.rocketchat-server[15511]:     at Timeout._onTimeout (app/ldap/server/ldap.js:181:14)
Jan 29 11:08:58 rocketchat-server.rocketchat-server[15511]:     at listOnTimeout (internal/timers.js:549:17)
Jan 29 11:08:58 rocketchat-server.rocketchat-server[15511]:     at processTimers (internal/timers.js:492:7)
Jan 29 11:09:00 rocketchat-server.rocketchat-server[15511]: server.js:204 LDAP ➔ Connection.error connection time out 1000
Jan 29 11:09:00 rocketchat-server.rocketchat-server[15511]: server.js:204 LDAPSync ➔ error Error: Timeout
Jan 29 11:09:00 rocketchat-server.rocketchat-server[15511]:     at Timeout._onTimeout (app/ldap/server/ldap.js:181:14)
Jan 29 11:09:00 rocketchat-server.rocketchat-server[15511]:     at listOnTimeout (internal/timers.js:549:17)
Jan 29 11:09:00 rocketchat-server.rocketchat-server[15511]:     at processTimers (internal/timers.js:492:7)

**Comment by JonCSgr** [comment]
I did a fresh LDAP installation and this happens again .
Background sync is set to 1 sec (need this because using rocketchat with API a lot ).

I searched the forum , found other people facing the same issue but 0 solutions.
Keep in mind ldap works just fine , everything works as should but i am getting this issue.

**Comment by JonCSgr** [comment]
I have isolated the issue and it's because of background sync. I have tested on 1 second,10 second ,30 second and i face this issue.

Any help ?
