### ISSUE TITLE
cannot start server with this error

### ISSUE THREAD

**Issue by wuhuinan47** [RocketChat/Rocket.Chat#20552]
rocketchat@757eeda3a811:/app/bundle$ node main.js 
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
{"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 215","time":{"$date":1612238777101},"level":"info"}
Loaded the Apps Framework and loaded a total of 0 Apps!
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Updating process.env.MAIL_URL
Exception in callback of async function: Error: rtsp://admin:zy888888@192.168.1.70:554/ch1/websocket is not a valid WebSocket URL
    at new Client (/app/bundle/programs/server/npm/node_modules/meteor/socket-stream-client/node_modules/websocket-driver/lib/websocket/driver/client.js:24:11)
    at Object.client (/app/bundle/programs/server/npm/node_modules/meteor/socket-stream-client/node_modules/websocket-driver/lib/websocket/driver.js:17:12)
    at new Client (/app/bundle/programs/server/npm/node_modules/meteor/socket-stream-client/node_modules/faye-websocket/lib/faye/websocket/client.js:16:25)
    at ClientStream._launchConnection (packages/socket-stream-client/node.js:155:33)
    at new ClientStream (packages/socket-stream-client/node.js:29:10)
    at new Connection (packages/ddp-client/common/livedata_connection.js:86:22)
    at Object.DDP.connect (packages/ddp-client/common/namespace.js:64:13)
    at startStreamCastBroadcast (server/stream/streamBroadcast.js:164:25)
    at server/stream/streamBroadcast.js:225:11
    at Settings.get (app/settings/lib/settings.ts:44:44)
    at startStreamBroadcast (server/stream/streamBroadcast.js:212:11)
    at server/startup/instance.js:32:9
    at Function.time (/app/bundle/programs/server/profile.js:273:30)
    at /app/bundle/programs/server/boot.js:415:15
    at /app/bundle/programs/server/boot.js:465:7
    at Function.run (/app/bundle/programs/server/profile.js:280:14)
    at /app/bundle/programs/server/boot.js:463:13

**Comment by wuhuinan47** [comment]
how can I delete this configuration -- 'rtsp://admin:zy888888@192.168.1.70:554/ch1/websocket'

**Comment by wuhuinan47** [comment]
I cannot start server , how to delete it and start  ? This is your bug , ok? Tell me why start server fail just webRTC config error ? You can try catch it and then echo it , Can't you?

**Comment by wuhuinan47** [comment]
I know this is a configuration error. But cannot start server , how can i do ? To modify mongo database or others? En ?
