### ISSUE TITLE
AD password sync

### ISSUE THREAD

**Issue by avignat** [RocketChat/Rocket.Chat#20557]
### Description:

I tried something weird. I linked a Rocket to an AD domain.
I left the options "Change password" and "Forgot my password" enabled.
I logged in Rocket using my AD credentials. Then I tried to changed my password, I succeeded.
Problem my AD password and Rocket account are now different. 

### Steps to reproduce:

1. Go to your profile settings using an AD account
2. Change your password

### Expected behavior:

Not being able to change password when using an AD account?
Being able to force the sync again?

### Actual behavior:

I can change my password, then I have two different passwords.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.3
- Operating System: Debian
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: Desktop App
- Operating System: Fedora

### Additional context

None

### Relevant logs:

```
I20210202-11:56:18.876(1) server.js:204 LDAPHandler ➔ error Error: User not Found     at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:60:10)     at packages/accounts-base/accounts_server.js:475:31     at tryLoginMethod (packages/accounts-base/accounts_server.js:1309:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:473:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:533:31)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by avignat** [comment]
After a force sync from the LDAP settings I can now use both password
