### ISSUE TITLE
Upgrade to 3.11.0 not starting because of MongoError: not master

### ISSUE THREAD

**Issue by sgohl** [RocketChat/Rocket.Chat#20632]
### Description:

When upgrading to 3.11.0, rocketchat does not start - fails with error (see Actual behavior)

When I rollback to `3.10.5`, rocketchat starts again as expected.

### Steps to reproduce:

```
      MONGO_URL: 'mongodb://rocketchat_mongo1:27017,rocketchat_mongo2:27017,rocketchat_mongo3:27017,rocketchat_mongo4:27017,rocketchat_mongo5:27017/rocketchat?replicaSet=rs0&readPreference=nearest&w=majority'
      MONGO_OPLOG_URL: 'mongodb://rocketchat_mongo1:27017,rocketchat_mongo2:27017,rocketchat_mongo3:27017,rocketchat_mongo4:27017,rocketchat_mongo5:27017/local?replicaSet=rs0'
      INSTANCE_IP: 'app'
```

first use `3.10.5`, then upgrade to `3.11.0`

### Expected behavior:

3.11.0 starts

### Actual behavior:

```
# docker service update --force --image docker.io/rocketchat/rocket.chat:3.11.0 rocketchat_app
# docker service logs -f rocketchat_app

rocketchat_app.1.dc5cmxza3i9y@swarm4    | === UnHandledPromiseRejection ===
rocketchat_app.1.dc5cmxza3i9y@swarm4    | MongoError: not master
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:451:61)
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     at Connection.emit (events.js:315:20)
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     at Connection.EventEmitter.emit (domain.js:483:12)
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     at processMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:452:10)
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:621:15)
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     at Socket.emit (events.js:315:20)
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     at Socket.EventEmitter.emit (domain.js:483:12)
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     at addChunk (_stream_readable.js:295:12)
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     at readableAddChunk (_stream_readable.js:271:9)
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     at Socket.Readable.push (_stream_readable.js:212:10)
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     at TCP.callbackTrampoline (internal/async_hooks.js:120:14) {
rocketchat_app.1.dc5cmxza3i9y@swarm4    |   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 4, high_: 1612612952 },
rocketchat_app.1.dc5cmxza3i9y@swarm4    |   ok: 0,
rocketchat_app.1.dc5cmxza3i9y@swarm4    |   code: 10107,
rocketchat_app.1.dc5cmxza3i9y@swarm4    |   codeName: 'NotMaster',
rocketchat_app.1.dc5cmxza3i9y@swarm4    |   '$clusterTime': {
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 4, high_: 1612612952 },
rocketchat_app.1.dc5cmxza3i9y@swarm4    |     signature: { hash: [Binary], keyId: 0 }
rocketchat_app.1.dc5cmxza3i9y@swarm4    |   }
rocketchat_app.1.dc5cmxza3i9y@swarm4    | }
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Centos 7
- Deployment Method: Docker Swarm
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 3.6.19

### Client Setup Information

client not relevant

### Additional context

This works:
```
/rocketchat?replicaSet=rs0&w=majority
```
while this doesnt:
```
/rocketchat?replicaSet=rs0&readPreference=nearest&w=majority
```

**Comment by sgohl** [comment]
still happens on update to `3.12.1`

it works when I remove `&readPreference=nearest` from the `MONGO_URL` connection string

Did something change within the connection pooling logic in Rocket.Chat ?
