### ISSUE TITLE
Cannot read property 't' of undefined

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#207]
Hi!

I'm just trying to run it though Docker, and I encouter the following issue.

During the first run, I see the following error from the logs:
```
Jun 19 09:31:26 k5 bash[21678]: web_1 | Exception while invoking method 'registerUser' Error: getaddrinfo EIO
Jun 19 09:31:26 k5 bash[21678]: web_1 |     at Object.Future.wait (/built_app/programs/server/node_modules/fibers/future.js:398:15)
Jun 19 09:31:26 k5 bash[21678]: web_1 |     at smtpSend (packages/email/email.js:76:1)
Jun 19 09:31:26 k5 bash[21678]: web_1 |     at Object.Email.send (packages/email/email.js:153:1)
Jun 19 09:31:26 k5 bash[21678]: web_1 |     at Object.Email.send (packages/meteorhacks:kadira/lib/hijack/email.js:10:1)
Jun 19 09:31:26 k5 bash[21678]: web_1 |     at Object.Accounts.sendVerificationEmail (packages/accounts-password/password_server.js:627:1)
Jun 19 09:31:26 k5 bash[21678]: web_1 |     at [object Object].Meteor.methods.registerUser (server/methods/registerUser.coffee:13:12)
Jun 19 09:31:26 k5 bash[21678]: web_1 |     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:161:1)
Jun 19 09:31:26 k5 bash[21678]: web_1 |     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
Jun 19 09:31:26 k5 bash[21678]: web_1 |     at packages/ddp/livedata_server.js:648:1
Jun 19 09:31:26 k5 bash[21678]: web_1 |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Jun 19 09:31:26 k5 bash[21678]: web_1 |     - - - - -
Jun 19 09:31:26 k5 bash[21678]: web_1 |     at errnoException (dns.js:37:11)
Jun 19 09:31:26 k5 bash[21678]: web_1 |     at Object.onanswer [as oncomplete] (dns.js:124:16)
Jun 19 09:31:26 k5 bash[21678]: web_1 | [publish] activeUsers
```

And then this one:
```
Jun 19 09:49:51 k5 bash[21678]: db_1  | 2015-06-19T09:31:26.897+0000 I INDEX    [conn2] build index on: meteor.avatars.files properties: { v: 1, key: { filename: 1 }, name: "filename_1", ns: "me
Jun 19 09:49:51 k5 bash[21678]: db_1  | 2015-06-19T09:31:26.897+0000 I INDEX    [conn2]          building index using bulk method
Jun 19 09:49:51 k5 bash[21678]: db_1  | 2015-06-19T09:31:26.897+0000 I INDEX    [conn2] build index done.  scanned 0 total records. 0 secs
Jun 19 09:49:51 k5 bash[21678]: db_1  | 2015-06-19T09:31:26.898+0000 I INDEX    [conn5] build index on: meteor.avatars.chunks properties: { v: 1, key: { files_id: 1, n: 1 }, name: "files_id_1_n_
Jun 19 09:49:51 k5 bash[21678]: db_1  | 2015-06-19T09:31:26.898+0000 I INDEX    [conn5]          building index using bulk method
Jun 19 09:49:51 k5 bash[21678]: db_1  | 2015-06-19T09:31:26.898+0000 I INDEX    [conn5] build index done.  scanned 0 total records. 0 secs
Jun 19 09:49:51 k5 bash[21678]: web_1 | [publish] room -> arguments: { '0': '57om6EQCcFami9wuT' }
Jun 19 09:49:51 k5 bash[21678]: web_1 | [methods] canAccessRoom ->  userId: QbjiEKqXEuo5mFAmf rid: 57om6EQCcFami9wuT
Jun 19 09:49:51 k5 bash[21678]: web_1 | Exception from sub room id 7cAsuAi7zHMWmyBGD TypeError: Cannot read property 't' of undefined
Jun 19 09:49:51 k5 bash[21678]: web_1 |     at [object Object].Meteor.methods.canAccessRoom (server/methods/canAccessRoom.coffee:15:10)
Jun 19 09:49:51 k5 bash[21678]: web_1 |     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:161:1)
Jun 19 09:49:51 k5 bash[21678]: web_1 |     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
Jun 19 09:49:51 k5 bash[21678]: web_1 |     at packages/ddp/livedata_server.js:1530:1
Jun 19 09:49:51 k5 bash[21678]: web_1 |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Jun 19 09:49:51 k5 bash[21678]: web_1 |     at [object Object]._.extend.apply (packages/ddp/livedata_server.js:1529:1)
Jun 19 09:49:51 k5 bash[21678]: web_1 |     at [object Object]._.extend.call (packages/ddp/livedata_server.js:1472:1)
Jun 19 09:49:51 k5 bash[21678]: web_1 |     at [object Object].<anonymous> (server/publications/room.coffee:10:16)
Jun 19 09:49:51 k5 bash[21678]: web_1 |     at packages/matb33:collection-hooks/collection-hooks.js:218:1
Jun 19 09:49:51 k5 bash[21678]: web_1 |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Jun 19 09:49:51 k5 bash[21678]: web_1 | [publish] messages -> rid: 57om6EQCcFami9wuT start: undefined
```

Then I can't print the chat. The rest is working fine, but the chat loads forever.
And then when I restart the app, everything is working fine.

This is just to let you know!

Tell me if you need further checking on my side!

Thanks a lot!

Pierre

**Comment by engelgabriel** [comment]
I think I know what can be causing it. We are working on the setup wizard, that should sort this out.

**Comment by pierreozoux** [comment]
Before the setup wizard, would be amazing to have an ENV var.

Please read http://12factor.net/ for in depth explanation.

But just to let you know that as a hoster, then I'd have to end up to ugly steps like this if there is just a wizzard:
https://github.com/IndiePaaS/IndiePaaS/blob/master/dockerfiles/services/piwik/startup-piwik.sh#L96-L100

Thanks :)

**Comment by engelgabriel** [comment]
I am creating the admin and the initial configuration tool. My current thinking is that we should accept init values to be passed via environment variables, but they would be overwritten if later the user changes it via /setting page.

The bugg should be fix now. Let me know otherwise?

**Comment by pierreozoux** [comment]
Great thanks!
