### ISSUE TITLE
Mail : RecipientError: Can't send mail - all recipients were rejected

### ISSUE THREAD

**Issue by p1rox** [RocketChat/Rocket.Chat#2077]
```
rocketchat_1 | Exception while invoking method 'sendInvitationEmail' RecipientError: Can't send mail - all recipients were rejected
rocketchat_1 |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
rocketchat_1 |     at smtpSend (packages/email/email.js:86:1)
rocketchat_1 |     at Object.Email.send (packages/email/email.js:185:1)
rocketchat_1 |     at [object Object].Meteor.methods.sendInvitationEmail (packages/rocketchat_lib/server/methods/sendInvitationEmail.coffee:15:10)
rocketchat_1 |     at [object Object].methodsMap.(anonymous function) (packages/rocketchat_lib/server/lib/debug.js:23:1)
rocketchat_1 |     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
rocketchat_1 |     at livedata_server.js:708:19
rocketchat_1 |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
rocketchat_1 |     at livedata_server.js:706:40
rocketchat_1 |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
rocketchat_1 |     - - - - -
rocketchat_1 |     at SMTPClient._actionRCPT (/app/bundle/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:909:27)
rocketchat_1 |     at SMTPClient._onData (/app/bundle/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:329:29)
rocketchat_1 |     at CleartextStream.emit (events.js:95:17)
rocketchat_1 |     at CleartextStream.<anonymous> (_stream_readable.js:765:14)
rocketchat_1 |     at CleartextStream.emit (events.js:92:17)
rocketchat_1 |     at emitReadable_ (_stream_readable.js:427:10)
rocketchat_1 |     at _stream_readable.js:420:7
rocketchat_1 |     at process._tickDomainCallback (node.js:492:13)
```

I'm using Rocket.Chat with Docker. I'm using a working SMTP server without authentification on port 25.
This happen when I click `Send a test mail to my user`.
Docker image : rocketchat/rocket.chat:latest

**Comment by marceloschmidt** [comment]
@p1rox can you confirm your logged in user has an e-mail on account?

**Comment by p1rox** [comment]
This is weird the placeholder of `Email` was my email.
I tried to put it again and save. And after that `Send a test mail to my user` it worked.

But if I decide to change my email, same error.

**Comment by marceloschmidt** [comment]
What placeholder? The `From Email`?

**Comment by p1rox** [comment]
`Email` in my account settings.

**Comment by marceloschmidt** [comment]
Can you double check your SMTP logs and see if it is receiving the send request, or if it's failing before even reaching the server?

**Comment by p1rox** [comment]
I'm sorry my SMTP was not well configured for the Rocket.Chat's domain. That's why it was rejecting some mail domains.

**Comment by recolic** [comment]
I'm run in a similar issue. After checking my smtp server, it says: 

```
NOQUEUE: reject: RCPT from unknown[123.206.117.183]: 554 5.7.1 <root@recolic.net>: Recipient address rejected: Policy rejection due to null sender; from=<> to=<root@recolic.net> proto=ESMTP
```

I'm trying to verify the email of my account. Why email sender is null?
