### ISSUE TITLE
Omnichannel

### ISSUE THREAD

**Issue by mks1991** [RocketChat/Rocket.Chat#20822]
Exception while invoking method livechat:changeLivechatStatus Error: Not allowed [error-not-allowed]
    at MethodInvocation.livechat:changeLivechatStatus (app/livechat/server/methods/changeLivechatStatus.js:23:10)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
 => awaited here:
    at Promise.await (/opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by japrogramer** [comment]
I also have this error, I20210706-23:45:57.863(-5)? 

```
Updating process.env.MAIL_URL
=> Meteor server restarted
I20210706-23:45:58.576(-5)? ➔ System ➔ startup
I20210706-23:45:58.577(-5)? ➔ +-----------------------------------------------+
I20210706-23:45:58.578(-5)? ➔ |                 SERVER RUNNING                |
I20210706-23:45:58.578(-5)? ➔ +-----------------------------------------------+
I20210706-23:45:58.578(-5)? ➔ |                                               |
I20210706-23:45:58.578(-5)? ➔ |  Rocket.Chat Version: 3.16.1                  |
I20210706-23:45:58.578(-5)? ➔ |       NodeJS Version: 12.22.1 - x64           |
I20210706-23:45:58.578(-5)? ➔ |      MongoDB Version: 4.2.8                   |
I20210706-23:45:58.579(-5)? ➔ |       MongoDB Engine: wiredTiger              |
I20210706-23:45:58.579(-5)? ➔ |             Platform: linux                   |
I20210706-23:45:58.579(-5)? ➔ |         Process Port: 29660                   |
I20210706-23:45:58.579(-5)? ➔ |             Site URL: http://localhost:3000/  |
I20210706-23:45:58.579(-5)? ➔ |     ReplicaSet OpLog: Enabled                 |
I20210706-23:45:58.579(-5)? ➔ |          Commit Hash: b5135c8a57              |
I20210706-23:45:58.579(-5)? ➔ |        Commit Branch: welnity                 |
I20210706-23:45:58.580(-5)? ➔ |                                               |
I20210706-23:45:58.580(-5)? ➔ +-----------------------------------------------+
I20210706-23:46:39.141(-5)? Exception while invoking method livechat:changeLivechatStatus Error: Not allowed [error-not-allowed]
```

**Comment by japrogramer** [comment]
I solved this by adding the 'livechat agent' role to my user
