### ISSUE TITLE
irect Reply by Email broken (3.12.0-rc.1)

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#20925]
### Description:

Hello Devs. 

Direct Reply by Email is broken in 3.12.0-rc.1. Don't know if it worked before. Just tried this feature after a long time again. Here is what the logs say:

`
I20210227-10:32:41.388(1) Exception in callback of async function: Error: Expected array for search criteria     at Connection._search (/opt/rocketchat-3.12.0-rc1/programs/server/npm/node_modules/imap/lib/Connection.js:573:11)     at Connection.search (/opt/rocketchat-3.12.0-rc1/programs/server/npm/node_modules/imap/lib/Connection.js:566:8)     at IMAPIntercepter.getEmails (server/email/IMAPInterceptor.ts:99:13)     at server/email/IMAPInterceptor.ts:46:11     at Connection.<anonymous> (/opt/rocketchat-3.12.0-rc1/programs/server/npm/node_modules/imap/lib/Connection.js:432:7)     at Connection._resTagged (/opt/rocketchat-3.12.0-rc1/programs/server/npm/node_modules/imap/lib/Connection.js:1535:22)     at Parser.<anonymous> (/opt/rocketchat-3.12.0-rc1/programs/server/npm/node_modules/imap/lib/Connection.js:194:10)     at Parser.emit (events.js:314:20)     at Parser.EventEmitter.emit (domain.js:483:12)     at Parser._resTagged (/opt/rocketchat-3.12.0-rc1/programs/server/npm/node_modules/imap/lib/Parser.js:175:10)     at Parser._parse (/opt/rocketchat-3.12.0-rc1/programs/server/npm/node_modules/imap/lib/Parser.js:139:16)     at Parser._tryread (/opt/rocketchat-3.12.0-rc1/programs/server/npm/node_modules/imap/lib/Parser.js:82:15)     at Socket.Parser._cbReadable (/opt/rocketchat-3.12.0-rc1/programs/server/npm/node_modules/imap/lib/Parser.js:53:12)     at Socket.emit (events.js:314:20)     at Socket.EventEmitter.emit (domain.js:483:12)     at emitReadable_ (_stream_readable.js:557:12)     at processTicksAndRejections (internal/process/task_queues.js:83:21)
`

### Steps to reproduce:

1. Enable direct Reply
2. Reply to an Email
3. Email gets not processed by Rocketchat

### Expected behavior:

Email gets processed by Rocketchat

### Actual behavior:

Rocketchat IMAP handling crashes.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-rc.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 12.21.0
- MongoDB Version: 4.2.11

### Client Setup Information

not importent.

### Additional context

nothing.

### Relevant logs:

already posted.

**Comment by himpierre** [comment]
The output from Dovecot:

`
Feb 27 10:32:41 imap-login: Info: Login: user=<rocketchat>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=14886, secured, session=<GC3yEE68Drt/AAAB>
Feb 27 11:02:41 imap(rocketchat)<14886><GC3yEE68Drt/AAAB>: Info: Disconnected for inactivity in=60 out=974 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
`

**Comment by caesarcxiv** [comment]
Confirmed still broken. 

Researching the error, appears to have to do with the + parsing in node.

**Comment by rasos** [comment]
Confirmed for RC 3.13.4 on two self hosted RC instances. Worked before (do not remember exactly what was our last version before upgrade, probably RC 3.3).   

Debug log shows that IMAP connection is successful, seems to be related to parsing the `+` separator. 

This is a show stopper for use cases when you want to roll out rocket.chat at groups where you plan a smooth transition from e-mail to chat usage as users can not simply reply anymore to an e-mail notification by e-mail.

Probably related with the introduction of IMAP inboxes https://github.com/RocketChat/Rocket.Chat/pull/20101 in RC 3.11 ?

@tiagopaixao

**Comment by chas-mafli** [comment]
Starting rocket failed because of this error when upgrading from 3.18.0 to 4.0.1

```
/opt/rocketchat/programs/server/npm/node_modules/imap/lib/Connection.js:573
    throw new Error('Expected array for search criteria');
    ^
Error: Expected array for search criteria
    at Connection._search (/opt/rocketchat/programs/server/npm/node_modules/imap/lib/Connection.js:573:11)
    at Connection.search (/opt/rocketchat/programs/server/npm/node_modules/imap/lib/Connection.js:566:8)
    at IMAPIntercepter.getEmails (server/email/IMAPInterceptor.ts:99:13)
    at server/email/IMAPInterceptor.ts:46:11
    at Connection.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/imap/lib/Connection.js:432:7)
    at Connection._resTagged (/opt/rocketchat/programs/server/npm/node_modules/imap/lib/Connection.js:1535:22)
    at Parser.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/imap/lib/Connection.js:194:10)
    at Parser.emit (events.js:314:20)
    at Parser.EventEmitter.emit (domain.js:483:12)
    at Parser._resTagged (/opt/rocketchat/programs/server/npm/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/opt/rocketchat/programs/server/npm/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/opt/rocketchat/programs/server/npm/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/opt/rocketchat/programs/server/npm/node_modules/imap/lib/Parser.js:53:12)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

**Comment by grzebo** [comment]
@chas-mafli Did you figure out a way to solve this problem?

**Comment by chas-mafli** [comment]
@grzebo Well I just disabled "Direct Reply" in the admin before upgrading :/ Seems like the feature is broken anyway https://github.com/RocketChat/Rocket.Chat/issues/23590

**Comment by grzebo** [comment]
> @grzebo Well I just disabled "Direct Reply" in the admin before upgrading :/ Seems like the feature is broken anyway #23590

Thanks, that worked for me too. I had to roll back the upgrade (from a snapshot), disable "Direct Reply" and upgrade. It works now.

**Comment by nonno-cicala** [comment]
Direct Reply by Email works for me using POP. I tried IMAP but that didn't work

**Comment by nonno-cicala** [comment]
Direct Reply by Email works for me on RC 4.8.4 using POP. I tried IMAP but that didn't work

**Comment by d3hof** [comment]
Still broken with imap on 4.8.6 and works with pop thanks to @nonno-cicala for the tip.
