### ISSUE TITLE
Though The Exception While after The installtion when we run "node main.js"

### ISSUE THREAD

**Issue by akhil004** [RocketChat/Rocket.Chat#2094]
I follow the installation guide as it is Everything install fine when i want to start the app and try to run the node main.js it through and an Exception 
I am using the Ubuntu 14.04.3 LTS (32 bit OS). We followed the Deploy Rocket.Chat without docker documentation . Everything Installed properly but when i start the application its shows the floowing error.
/home/user/Rocket.Chat/programs/server/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: /home/user/Rocket.Chat/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: wrong ELF class: ELFCLASS64
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/user/Rocket.Chat/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/home/user/Rocket.Chat/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by marceloschmidt** [comment]
Please provide additional details:
What OS are you on? 
Which install guide have you followed? 
What's your node version? 
Thanks.

**Comment by akhil004** [comment]
I am using the Ubuntu 14.04.3 LTS (32 bit OS). We followed the Deploy Rocket.Chat without docker documentation .

**Comment by Taiiwo** [comment]
Same issue here trying to get it to work in Debian. Looks like a 64bit data type is hardcoded in? I'm not familiar with node, so I can't debug any further than that.

**Comment by Artharius** [comment]
Same issue with Ubuntu 14.04.3 LTS (32 bit OS).

**Comment by erhan-** [comment]
Same problem with 32 bit Debian Jessie.

**Comment by geekgonecrazy** [comment]
I don't think this should still be happening in any edge cases.  Please let us know if otherwise
