### ISSUE TITLE
Can't access certain DMs `TypeError: Cannot read property 'filter' of undefined`

### ISSUE THREAD

**Issue by IJSlater** [RocketChat/Rocket.Chat#21047]
### Description:
Can't access certain DMs after snap auto update.
### Steps to reproduce:

upgrade to version 3.12.1.
click on DMs with any user that has an @ next to their name.

### Expected behavior:

Access DMs  for that user.

### Actual behavior:

Find a completely blank window.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: Debian 10
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version:3.6.14

### Client Setup Information

Ubuntu 20.04 Brave/Firefox web browser

### Relevant logs:

Mar 05 11:30:00 galaxie rocketchat-server.rocketchat-server[27899]: ---------------------------------
Mar 05 11:30:00 galaxie rocketchat-server.rocketchat-server[27899]: Errors like this can cause oplog processing errors.
Mar 05 11:30:00 galaxie rocketchat-server.rocketchat-server[27899]: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatica
Mar 05 11:30:00 galaxie rocketchat-server.rocketchat-server[27899]: Future node.js versions will automatically exit the process
Mar 05 11:30:00 galaxie rocketchat-server.rocketchat-server[27899]: =================================
Mar 05 11:32:00 galaxie rocketchat-server.rocketchat-server[27899]: === UnHandledPromiseRejection ===
Mar 05 11:32:00 galaxie rocketchat-server.rocketchat-server[27899]: TypeError: Cannot read property 'filter' of undefined
Mar 05 11:32:00 galaxie rocketchat-server.rocketchat-server[27899]:     at getRoomData (app/user-data-download/server/cronProcessDownloads.js:57:54)
Mar 05 11:32:00 galaxie rocketchat-server.rocketchat-server[27899]:     at app/user-data-download/server/cronProcessDownloads.js:75:20
Mar 05 11:32:00 galaxie rocketchat-server.rocketchat-server[27899]:     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1138:16)
Mar 05 11:32:00 galaxie rocketchat-server.rocketchat-server[27899]:     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
Mar 05 11:32:00 galaxie rocketchat-server.rocketchat-server[27899]:     at loadUserSubscriptions (app/user-data-download/server/cronProcessDownloads.js:74:9)
Mar 05 11:32:00 galaxie rocketchat-server.rocketchat-server[27899]:     at app/user-data-download/server/cronProcessDownloads.js:457:30
Mar 05 11:32:00 galaxie rocketchat-server.rocketchat-server[27899]:     at /snap/rocketchat-server/1455/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-p
Mar 05 11:32:00 galaxie rocketchat-server.rocketchat-server[27899]:  => awaited here:
Mar 05 11:32:00 galaxie rocketchat-server.rocketchat-server[27899]:     at Function.Promise.await (/snap/rocketchat-server/1455/programs/server/npm/node_modules/meteor/promi
Mar 05 11:32:00 galaxie rocketchat-server.rocketchat-server[27899]:     at app/user-data-download/server/cronProcessDownloads.js:559:2

**Comment by siacali** [comment]
I have the same issue.  Reproducible with Chrome, Edge, Firefox.  Oddly, the mobile (IOS) client appears to function properly...

**Comment by phpai** [comment]
Hi, same issue on version 3.13.3, with people with an @ next to their name (instead of the status indicator)

```
Exception in defer callback: TypeError: Cannot read property 'filter' of undefined
    at RocketChatIntegrationHandler.getTriggersToExecute (app/integrations/server/lib/triggerHandler.js:492:16)
    at RocketChatIntegrationHandler.executeTriggers (app/integrations/server/lib/triggerHandler.js:563:34)
    at _wrapperFunction (app/integrations/server/triggers.js:6:38)
    at app/callbacks/lib/callbacks.js:147:65
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/meteor.js:550:25
    at runWithEnvironment (packages/meteor.js:1286:24)
```
