### ISSUE TITLE
livechat: Removing livechat users will cause Internal Server errors for subsequent users

### ISSUE THREAD

**Issue by Xaroth** [RocketChat/Rocket.Chat#2104]
The steps I took to reproduce:

1: start a livechat session
2: close that session, start a new one with a new user
3: close that one as well
4: remove all livechat users (I wanted to argue the point that livechat users should not appear on the normal 'user' page, but should have their own page, and perhaps some form of auto-cleanup-thingie)
5: try to create a new session. When the livechat user types, he gets an Internal Server Error message... the console shows this:

```
Exception while invoking method 'sendMessageLivechat' MongoError: E11000 duplicate key error index: rocketchat.rocketchat_room.$name_1 dup key: { : "guest-1" }
    at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)
    at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
    at [object Object].MongoConnection.(anonymous function) [as insert] (packages/mongo/mongo_driver.js:736:1)
    at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)
    at _Class.RocketChat.models._Base._Class.insert (packages/rocketchat_lib/server/models/_Base.coffee:17:24)
    at [object Object].Meteor.methods.sendMessageLivechat (server/methods/sendMessageLivechat.js:30:28)
    at [object Object].methodsMap.(anonymous function) (packages/rocketchat_lib/server/lib/debug.js:23:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    - - - - -
    at Object.toError (/opt/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /opt/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:116:29
    at /opt/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7
    at /opt/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/opt/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /opt/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/opt/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
```

I -think- this is due to Rocket.Chat wanting to re-use a chat room that already exists from the old livechat session (which probably should have been cleaned up when the livechat user was removed).

**Comment by sampaiodiego** [comment]
This is already fixed.

We are now using two settings (`Livechat_guest_count` and `Livechat_Room_Count`) to control this names.
