### ISSUE TITLE
Possibly duplicate 'migrations' collection

### ISSUE THREAD

**Issue by skemb321** [RocketChat/Rocket.Chat#2109]
hi I am running RocketChat Master and found this error on console after running `meteor`:

`Error: A method named '/migrations/insert' is already defined`

Edit: Here's the full stack trace:
```
W20160203-05:50:48.845(8)? (STDERR) /home/myuser/.meteor/packages/meteor-tool/.1.1.10.rohhxh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160203-05:50:48.845(8)? (STDERR) 						throw(ex);
W20160203-05:50:48.845(8)? (STDERR) 						      ^
W20160203-05:50:49.113(8)? (STDERR) Error: A method named '/migrations/insert' is already defined
W20160203-05:50:49.113(8)? (STDERR)     at livedata_server.js:1542:15
W20160203-05:50:49.114(8)? (STDERR)     at Function._.each._.forEach (packages/underscore/packages/underscore.js:142:1)
W20160203-05:50:49.114(8)? (STDERR)     at [object Object]._.extend.methods (livedata_server.js:1538:7)
W20160203-05:50:49.114(8)? (STDERR)     at [object Object].Mongo.Collection._defineMutationMethods (packages/mongo/collection.js:927:1)
W20160203-05:50:49.115(8)? (STDERR)     at [object Object].Mongo.Collection (packages/mongo/collection.js:218:1)
W20160203-05:50:49.115(8)? (STDERR)     at new ns.Collection (packages/matb33_collection-hooks/collection-hooks.js:244:1)
W20160203-05:50:49.116(8)? (STDERR)     at Package (packages/percolate_migrations/packages/percolate_migrations.js:46:1)
W20160203-05:50:49.117(8)? (STDERR)     at Package (packages/percolate_migrations/packages/percolate_migrations.js:213:1)
W20160203-05:50:49.117(8)? (STDERR)     at /home/myuser/METEORAPPS/myRocketChat/.meteor/local/build/programs/server/packages/percolate_migrations.js:238:4
W20160203-05:50:49.118(8)? (STDERR)     at /home/myuser/METEORAPPS/myRocketChat/.meteor/local/build/programs/server/packages/percolate_migrations.js:247:3
```

I am pretty noob at this so a fix or work around is much appreciated.

Thanks!

**Comment by marceloschmidt** [comment]
Hi @skemb321 I'll take a look at this. Did you clone the repository, or downloaded it from elsewhere? Thanks.

**Comment by skemb321** [comment]
Hi @marceloschmidt I cloned it.

**Comment by marceloschmidt** [comment]
I'm having trouble replicating this error. Was that the first time you were cloning the repository or were you updating? If updating, do you know which version you had before that? Thanks.

**Comment by skemb321** [comment]
@marceloschmidt Hi! my bad, It was caused by my local package (added to rc) which is still using percolate:migrations. I just removed it and it solved the issue. Thanks!

**Comment by skemb321** [comment]
But also, let's make the older migrations use `RocketChat.Migrations` package. I encountered new errors when try to do a full migrate from version 1 - 28 because the older migrations still use `Migrations`.

Cheers!
