### ISSUE TITLE
Crashed when new user login by ldap

### ISSUE THREAD

**Issue by Laisky** [RocketChat/Rocket.Chat#2146]
when users login by ldap at first time, the whole app will crashed by ldap.

![srceen_shot 2016-02-04 at 17 35 15](https://cloud.githubusercontent.com/assets/4532436/12836012/fb74720c-cbef-11e5-91d5-e0136dbdfa48.jpg)

```
/app/bundle/programs/server/node_modules/fibers/future.js:226
                        throw new Error('Future resolved more than once');
                              ^
Error: Future resolved more than once
    at Object.Future.return (/app/bundle/programs/server/node_modules/fibers/future.js:226:10)
    at Client.<anonymous> (packages/rocketchat_ldap/ldap_server.js:100:1)
    at Client.emit (events.js:95:17)
    at Socket.onSocketError (/app/bundle/programs/server/npm/rocketchat_ldap/node_modules/ldapjs/lib/client/client.js:1169:12)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:492:13)
```

**Comment by homberger** [comment]
We are affected by this as well. This is a real pain :(

We are using the latest Release 1.60.

It does not matter if syncing is activated or deactivated.

Look at screenshot to see our settings (Domain changed to example.com)
![bildschirmfoto 2016-02-05 um 12 29 02](https://cloud.githubusercontent.com/assets/681335/12845159/556963ee-cc04-11e5-99ae-7e43c3c413cd.png)
.

**Comment by tpetrosy** [comment]
I just run Release 0.16, I have same problem.
the reason is the same as in #1491 . The daemon crashes because RC keeps connection opened with LDAP server. When server drop idle session, RC dies.
