### ISSUE TITLE
Problem sending email in new user registration/email verification forms

### ISSUE THREAD

**Issue by rebeld** [RocketChat/Rocket.Chat#2158]
Just installed Rocket.Chat using docker (using rocketchat/rocket.chat:latest).

Everything works so far, but I'm having problems with sending email, specifically from the new user registration and email verification forms.

SMTP settings are setup to send through Mailgun, test email works, and inviting new users through the Administration -> User -> Invite User works and invites are sent correctly.

But registering a new user results in an "Internal server error" notification. With the resulting log:

```
Exception while invoking method 'registerUser' SenderError: Mail from command failed - 501 Syntax error
    at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at smtpSend (packages/email/email.js:86:1)
    at Object.Email.send (packages/email/email.js:185:1)
    at AccountsServer.Accounts.sendVerificationEmail (password_server.js:781:9)
    at [object Object].Meteor.methods.registerUser (server/methods/registerUser.coffee:18:13)
    at [object Object].methodsMap.(anonymous function) (packages/rocketchat_lib/server/lib/debug.js:23:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    - - - - -
    at SMTPClient._actionMAIL (/app/bundle/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:879:23)
    at SMTPClient._onData (/app/bundle/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:329:29)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
    at process._tickDomainCallback (node.js:492:13)
```
The user is created, but it looks like it just fails to send the welcome email?

D

**Comment by rebeld** [comment]
Almost identical error when trying to send confirmation email:

```
Exception while invoking method 'sendConfirmationEmail' SenderError: Mail from command failed - 501 Syntax error
    at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at smtpSend (packages/email/email.js:86:1)
    at Object.Email.send (packages/email/email.js:185:1)
    at AccountsServer.Accounts.sendVerificationEmail (password_server.js:781:9)
    at [object Object].Meteor.methods.sendConfirmationEmail (server/methods/sendConfirmationEmail.coffee:6:13)
    at [object Object].methodsMap.(anonymous function) (packages/rocketchat_lib/server/lib/debug.js:23:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    - - - - -
    at SMTPClient._actionMAIL (/app/bundle/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:879:23)
    at SMTPClient._onData (/app/bundle/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:329:29)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
    at process._tickDomainCallback (node.js:492:13)
```

**Comment by rebeld** [comment]
I just updated to the latest version, and this issue seems to be resolved. Emails send from registration and email verification forms correctly.

**Comment by sjonstevens** [comment]
I am having the same issue. My version is 0.53.0
