### ISSUE TITLE
Error: TOTP Required [totp-required]

### ISSUE THREAD

**Issue by srkunze** [RocketChat/Rocket.Chat#21621]
### Description:

An error message in the logs channel despite successful email verification.

### Steps to reproduce:

Wait for users to verify their email.

### Expected behavior:

Empty log.

### Actual behavior:

Exception while invoking method verifyEmail
```
Error: TOTP Required [totp-required]
    at _checkCodeForUser (app/2fa/server/code/index.ts:161:9)
    at app/2fa/server/loginHandler.js:21:2
    at callbacks.runItem (app/callbacks/lib/callbacks.js:111:70)
    at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)
    at app/callbacks/lib/callbacks.js:39:35
    at app/callbacks/lib/callbacks.js:45:45
    at callbacks.run (app/callbacks/lib/callbacks.js:127:9)
    at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)
    at app/authentication/server/startup/index.js:345:20
    at packages/callback-hook/hook.js:131:22
    at packages/accounts-base/accounts_server.js:167:15
    at Hook.each (packages/callback-hook/hook.js:109:15)
    at AccountsServer._validateLogin (packages/accounts-base/accounts_server.js:164:29)
    at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:353:10)
    at AccountsServer._loginMethod (packages/accounts-base/accounts_server.js:385:17)
    at MethodInvocation.verifyEmail (packages/accounts-password/password_server.js:928:19)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
 => awaited here:
    at Promise.await (/snap/rocketchat-server/1451/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.4
- Operating System: Ubuntu Server 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.21
--

### Client Setup Information

- Operating System: iOS

**Comment by srkunze** [comment]
@johncrisp Not exactly sure what you mean by "test" here as this is a random error message in the logs I tried to bring up here for you.

Regarding the latest version: as you saw from the report above, I use snap:

```
root@rocketchat:~# snap list
Name               Version    Rev    Tracking       Publisher    Notes
core               16-2.49.2  10956  latest/stable  canonical✓   core
core18             20210309   2002   latest/stable  canonical✓   base
lxd                4.0.5      19648  4.0/stable/…   canonical✓   -
rocketchat-server  3.7.4      1451   3.x/stable     rocketchat✓  -
snapd              2.49.2     11584  latest/stable  canonical✓   snapd


root@rocketchat:~# snap info rocketchat-server | grep 3.x
tracking:     3.x/stable
  3.x/stable:       3.7.4  2020-12-23 (1451) 286MB -
  3.x/candidate:    3.8.4  2021-03-07 (1450) 275MB -
  3.x/beta:         3.9.3  2021-03-07 (1452) 275MB -
  3.x/edge:         3.12.0 2021-03-07 (1456) 278MB -

```

It seems like snap is not as fast as the usual update cadence, so I'm out of reporting to you (except when switching to 3.x/edge). :-/

**Comment by ali-alhaidary** [comment]
I have the same issue here connecting from moodle plugin.
Version 3.17.1
Apps Engine Version 1.27.1
Node Version v12.18.4
MongoDB 4.0.26 / mmapv1 (oplog Enabled)

moodle 3.9
plugin 1.3.3
