### ISSUE TITLE
3.11.1: createDirectMessage & getRoomByTypeAndName Exception: Invalid User

### ISSUE THREAD

**Issue by apaarfus** [RocketChat/Rocket.Chat#21735]
### Description:

Following a _major_ upgrade from 2.4 to 3.11.1, we started seeing several errors crop up in the log, listed as "`[error-invalid-user]`".  While there is some semblance of a stack trace, there's little to no additional information to explain _which_ user is generating this issue; or from what channel this issue is occurring in...just that there's a problem.

I've looked through our users both in RC's administration panel, as well as directly in MongoDB; and nothing is jumping out at me as out of place or misconfigured.

### Steps to reproduce:

1. Upgrade from (manual) 2.4 to (manual) 3.11.1
2. Check Rocket.Chat logs
  - The errors do not always appear immediately

### Expected behavior:

No exceptions -- or at the very least, a little more detail in the exception log.

### Actual behavior:

I've redacted the stack trace in this section for brevity.  Actual logs will be listed in full in the 'Relevant Logs' section.

```
I20210421-14:09:58.172(-4) Exception while invoking method getRoomByTypeAndName Error: Invalid user [error-invalid-user]
I20210421-14:09:58.431(-4) Exception while invoking method createDirectMessage Error: Invalid user [error-invalid-user]
```

While I do not have the exception to share, I have also seen similar messages for the method "`loadMissedMessages`" in the recent past as well.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Operating System: CentOS 7
- Deployment Method: tar/manual
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes (rs01)
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.24 / mmapv1 (oplog Enabled)

### Client Setup Information

N/A

### Additional context

We were not seeing these exceptions prior to our upgrade.  I'm _assuming_ something with these methods/functions changed during the _year_ we remained on the old build.  Additionally, here are some related issues I was able to locate in the tracker:

- #19703 
- #18917

We have not yet tried on the latest release to see if the issue still arises, though I fear it may still occur.

#### Rocket.Chat.Electron > Administration > View Logs

Exception @ Method: getRoomByTypeAndName

```
I20210421-14:09:58.172(-4) Exception while invoking method getRoomByTypeAndName Error: Invalid user [error-invalid-user]
	at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:42:10)
	at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
	at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
	at packages/ddp-server/livedata_server.js:1689:15
	at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
	at packages/ddp-server/livedata_server.js:1687:36
	at new Promise (<anonymous>)
	at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
	at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
	at Server.call (packages/ddp-server/livedata_server.js:1607:17)
	at Object.post (app/api/server/v1/misc.js:263:26)
	at app/api/server/api.js:394:82
	at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
	at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
	at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
	at packages/nimble_restivus/lib/route.coffee:59:33
	at packages/simple_json-routes.js:98:9  => awaited here:
	at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
	at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
	at Server.call (packages/ddp-server/livedata_server.js:1607:17)
	at Object.post (app/api/server/v1/misc.js:263:26)
	at app/api/server/api.js:394:82
	at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
	at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
	at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
	at packages/nimble_restivus/lib/route.coffee:59:33
	at packages/simple_json-routes.js:98:9
```

Exception @ Method: createDirectMessage

```
I20210421-14:09:58.431(-4) Exception while invoking method createDirectMessage Error: Invalid user [error-invalid-user]
	at MethodInvocation.createDirectMessage (server/methods/createDirectMessage.js:16:10)
	at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
	at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
	at packages/ddp-server/livedata_server.js:1689:15
	at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
	at packages/ddp-server/livedata_server.js:1687:36
	at new Promise (<anonymous>)
	at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
	at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
	at Server.call (packages/ddp-server/livedata_server.js:1607:17)
	at Object.post (app/api/server/v1/misc.js:263:26)
	at app/api/server/api.js:394:82
	at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
	at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
	at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
	at packages/nimble_restivus/lib/route.coffee:59:33
	at packages/simple_json-routes.js:98:9  => awaited here:
	at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
	at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
	at Server.call (packages/ddp-server/livedata_server.js:1607:17)
	at Object.post (app/api/server/v1/misc.js:263:26)
	at app/api/server/api.js:394:82
	at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
	at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
	at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
	at packages/nimble_restivus/lib/route.coffee:59:33
	at packages/simple_json-routes.js:98:9 
```

#### Journalctl -xeu rocketchat

Exception @ Method getRoomByNameAndType

```
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]: Exception while invoking method getRoomByTypeAndName Error: Invalid user [error-invalid-user]
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:42:10)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at packages/ddp-server/livedata_server.js:1689:15
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at packages/ddp-server/livedata_server.js:1687:36
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at new Promise (<anonymous>)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Object.post (app/api/server/v1/misc.js:263:26)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at app/api/server/api.js:394:82
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at packages/nimble_restivus/lib/route.coffee:59:33
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at packages/simple_json-routes.js:98:9
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]: => awaited here:
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Object.post (app/api/server/v1/misc.js:263:26)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at app/api/server/api.js:394:82
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at packages/nimble_restivus/lib/route.coffee:59:33
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at packages/simple_json-routes.js:98:9
```

Exception @ Method createDirectMessage

```
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]: Exception while invoking method createDirectMessage Error: Invalid user [error-invalid-user]
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at MethodInvocation.createDirectMessage (server/methods/createDirectMessage.js:16:10)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at packages/ddp-server/livedata_server.js:1689:15
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at packages/ddp-server/livedata_server.js:1687:36
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at new Promise (<anonymous>)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Object.post (app/api/server/v1/misc.js:263:26)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at app/api/server/api.js:394:82
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at packages/nimble_restivus/lib/route.coffee:59:33
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at packages/simple_json-routes.js:98:9
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]: => awaited here:
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Object.post (app/api/server/v1/misc.js:263:26)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at app/api/server/api.js:394:82
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at packages/nimble_restivus/lib/route.coffee:59:33
Apr 22 09:36:08 chat228.wtcox.com rocketchat[1030]:		at packages/simple_json-routes.js:98:9
```

**Comment by johncrisp** [comment]
HI,

That's a fairly large jump - there's a lot that can go wrong there as there have been a lot of changes through every single version.

It is normally better to go in incremental steps and allow changes to be applied gradually - they are usually tested for upgrades between a couple of versions, but not this many.

> We have not yet tried on the latest release to see if the issue still arises, though I fear it may still occur.

It may well do so, but you are no worse off and more likely to get some help. 3.11.x will not get patched.

Standard procedure is to test on latest please.

How long did it take? How many users? Any particular triggers you can see?

Have you committed to the upgrade or still testing?

**Comment by apaarfus** [comment]
> That's a fairly large jump - there's a lot that can go wrong there as there have been a lot of changes through every single version.

Yeah, that was my main concern over this past year, sitting on 2.4; however it was outside of my control to perform the upgrade.  Management wanted to remain on 2.4 as RC became our main form of communication, outside of email, when everyone transitioned to WFH.

> How long did it take?

Checking the logs:

- 2021-04-21 @ 13:38:31.663(-4) -- Server finished starting up
- 2021-04-21 @ 14:09:58.172(-4) -- Exception @ method `getRoomByTypeAndName`
- 2021-04-21 @ 14:09:58.431(-4) -- Exception @ method `createDirectMessage`

It looks like the exceptions appear in pairs, the next occurrences are at:

- 2021-04-21 @ 14:10:24.270(-4)
- 2021-04-21 @ 14:12:22.935(-4)
- 2021-04-21 @ 14:13:33.069(-4)

And so on...looks like about every minute or two, the pair of exceptions are logged.

> How many users?

We have a total of 83 users, 21 of which are _disabled_ (former employees).  Here's our user metrics from the info panel:

![image](https://user-images.githubusercontent.com/38731016/115752137-d1197e80-a367-11eb-8b0f-c0ef01bd7caa.png)

> Any particular triggers you can see?

Nothing that jumps out at me particularly.  Would it be possible for an old _desktop client version_ to cause that kind of error?  Since we're a windows shop, and `electron-updater` hasn't been working for Windows Clients for quite some time now, making sure everyone is up-to-date has been...a challenge.  We do not currently have a means to forcibly install updates on our users' machines; so some folks may be running older versions of the desktop client (eg, 2.17.7).

We do also have a testing/staging server hosted locally, to test server upgrades before deploying them in prod.  On that node, which _does not_ have any active users outside of myself and a coworker for testing; we aren't seeing those exceptions at all.

I _have not_ tried to manually step up the old snapshot from 2.4 to 3.11.x gradually; though I _can_ do that (once I learn how to build it, anyway) to see if a more gradual update would resolve the issue...though, we would lose about 1.5mo of chatlogs and such...unless that info could be "ported" over.

> Have you committed to the upgrade or still testing?

We've committed production to 3.11.1 for now, with plans to upgrade to the latest build in the coming weeks (assuming testing looks fine).

**Comment by emikolajczak** [comment]
Similar behavior on 3.14.0

`
Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]     at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:51:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9
`

**Comment by apaarfus** [comment]
Can also confirm that we are receiving the same errors on 3.15.0.

Unfortunately, I have not yet had a chance to incrementally update from our 2.4 backup.

I will provide another update to this ticket when I've done so, and report my findings.

**Comment by dkoo761** [comment]
I've having this issue as well and looking into it now.

The error on `createDirectMessage` happens when a user opens (or clicks a link to) the URL to a DM but is NOT already logged into RocketChat on the device/browser used to open the URL. In this case, they are taken to the login page and they see the "Invalid User" message appear for a moment on the screen. Actually this case triggers both the `createDirectMessage` and `getRoomByTypeAndName` errors in the logs. If they are already logged into RocketChat on the device/browser used to open the URL then there is no error and they are taken directly to the DM. 

Similarly, the error on `getRoomByTypeAndName` by itself happens in a similar scenario except this time it is triggered by opening a URL to a room instead of a direct message.

Working on a solution now and will update here when I have one.

**Comment by dkoo761** [comment]
Here's the solution I'm going to use in my own project:

In https://github.com/RocketChat/Rocket.Chat/blob/develop/app/ui-utils/client/lib/openRoom.js#L104, replace this:

`if (type === 'd') {`

with this:

`if (type === 'd' && error.error !== 'error-invalid-user') {`

That will prevent the Meteor method call to `createDirectMessage` from occurring if the user is not logged in, which will prevent the user from seeing the "Invalid User" message in the UI and will prevent the `createDirectMessage` exception on the server.

I'm not going to change how the `getRoomByTypeAndName` exception is handled since it's not impacting the UI at all and it seems like the kind of exception that RocketChat generally does log.

**Comment by vachigaggl** [comment]
3.14.5 is affected, I don't believe this has to do with updates. I am also rather convinced that I am logged in when I see this. 
The proposed fix by @dkoo761 above therefore does not seem to apply to how the case presents itself to me:
**Problem Description:**
The first of the two calls to getRoomByTypeAndName when directly navigating to a direct message room fails and "invalid user" is being displayed.
**Steps to reproduce:**
1. Directly navigate to a URL like /direct/W5xxxxxxxxQD?layout=embedded (W5xxxxxxxxQD is the room id of an existing room) -OR- (Variant B) Directly navigate to a URL /direct/Christof_Teng?layout=embedded where Christof_Teng is a username
2. Red error notification "Invalid User" is displayed
3. "No user with username "W5xxxxxxxxQD" was found! is briefly shown" -OR- (Variant B) "No user with username "Christof_Teng" was found!" is briefly shown
4. The chatroom finally loads all the same - because the user and chatroom exist.
5. search for getRoomByTypeAndName in javascript console. You will find that there are 2 calls, the first one fails always.
**Expected behavior**
1. No failure should be displayed.

**Video proof**
![recording (1)](https://user-images.githubusercontent.com/15807436/121510243-b66a9a00-c9e7-11eb-91b7-1c93cc86c0b6.gif)

**Comment by vachigaggl** [comment]
I have tested fix by @dkoo761 above. It works for me to remove the error "invalid user", which is now no longer displayed. 
The behaviour is as expected:

1. The room is correctly created and entered if it does not exist.
2. The room is opened if exists.
3. "Invalid user" error is shown if invalid user name given in URL, e.g. if room cannot be created.

I made another change to display "loading" animation instead of the "roomNotFound" error while the room is being created. Displaying an error to the user while loading is not intended behaviour.

```diff --git a/app/ui-utils/client/lib/openRoom.js b/app/ui-utils/client/lib/openRoom.js
index eec44400b..76ad23f8d 100644
--- a/app/ui-utils/client/lib/openRoom.js
+++ b/app/ui-utils/client/lib/openRoom.js
@@ -101,14 +101,14 @@ export const openRoom = async function(type, name) {
                        return callbacks.run('enter-room', sub);
                } catch (error) {
                        c.stop();
-                       if (type === 'd') {
+                       if (type === 'd' && error.error !== 'error-invalid-user') {
                                const result = await call('createDirectMessage', ...name.split(', ')).then((result) => waitUntilRoomBeInserted(type, result.rid)).catch(() => {});
                                if (result) {
                                        return FlowRouter.go('direct', { rid: result._id }, FlowRouter.current().queryParams);
                                }
                        }
                        Session.set('roomNotFound', { type, name, error });
-                       return appLayout.render('main', { center: 'roomNotFound' });
+                      return appLayout.render('main', { center: 'loading' });
                }
        });
 };```
