### ISSUE TITLE
general chat-room got froze after a clean install

### ISSUE THREAD

**Issue by oinirio** [RocketChat/Rocket.Chat#218]
I just clone the repo and after creating a new user and enter the default general chatroom the loading animation doesn't go away. this is the terminal output

```
I20150623-15:46:47.144(-4)? [methods] setUsername ->  userId: Sqs3Gv5gqEib3MP85 arguments: { '0': 'demo' }
I20150623-15:46:48.579(-4)? [methods] setAvatarFromService ->  userId: Sqs3Gv5gqEib3MP85 arguments: { '0': null, '1': null, '2': 'initials' }
I20150623-15:46:52.195(-4)? [publish] room -> arguments: { '0': '57om6EQCcFami9wuT' }
I20150623-15:46:52.196(-4)? [methods] canAccessRoom ->  userId: Sqs3Gv5gqEib3MP85 rid: 57om6EQCcFami9wuT
I20150623-15:46:52.279(-4)? Exception from sub room id ideEreiKJu7448Lwb TypeError: Cannot read property 't' of undefined
I20150623-15:46:52.280(-4)?     at [object Object].Meteor.methods.canAccessRoom (server/methods/canAccessRoom.coffee:15:10)
I20150623-15:46:52.280(-4)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:161:1)
I20150623-15:46:52.280(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150623-15:46:52.280(-4)?     at packages/ddp/livedata_server.js:1530:1
I20150623-15:46:52.280(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150623-15:46:52.280(-4)?     at [object Object]._.extend.apply (packages/ddp/livedata_server.js:1529:1)
I20150623-15:46:52.280(-4)?     at [object Object]._.extend.call (packages/ddp/livedata_server.js:1472:1)
I20150623-15:46:52.280(-4)?     at [object Object].<anonymous> (server/publications/room.coffee:10:16)
I20150623-15:46:52.280(-4)?     at packages/matb33:collection-hooks/collection-hooks.js:218:1
I20150623-15:46:52.281(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150623-15:46:52.281(-4)? [publish] messages -> rid: 57om6EQCcFami9wuT start: undefined
I20150623-15:46:52.282(-4)? [methods] canAccessRoom ->  userId: Sqs3Gv5gqEib3MP85 rid: 57om6EQCcFami9wuT
I20150623-15:46:52.285(-4)? Exception from sub messages id SYGdFhh2KaJim9shH TypeError: Cannot read property 't' of undefined
I20150623-15:46:52.286(-4)?     at [object Object].Meteor.methods.canAccessRoom (server/methods/canAccessRoom.coffee:15:10)
I20150623-15:46:52.286(-4)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:161:1)
I20150623-15:46:52.286(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150623-15:46:52.286(-4)?     at packages/ddp/livedata_server.js:1530:1
I20150623-15:46:52.286(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150623-15:46:52.286(-4)?     at [object Object]._.extend.apply (packages/ddp/livedata_server.js:1529:1)
I20150623-15:46:52.286(-4)?     at [object Object]._.extend.call (packages/ddp/livedata_server.js:1472:1)
I20150623-15:46:52.286(-4)?     at [object Object].<anonymous> (server/publications/messages.coffee:10:16)
I20150623-15:46:52.287(-4)?     at packages/matb33:collection-hooks/collection-hooks.js:218:1
I20150623-15:46:52.287(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150623-15:46:52.287(-4)? [methods] readMessages ->  userId: Sqs3Gv5gqEib3MP85 arguments: { '0': '57om6EQCcFami9wuT' }

```

**Comment by engelgabriel** [comment]
Let me try this here

**Comment by engelgabriel** [comment]
Should be fixed now.
