### ISSUE TITLE
initEncryptedSession references a root path instead of a relative one

### ISSUE THREAD

**Issue by dotdotdotpaul** [RocketChat/Rocket.Chat#21910]
### Description:

When the chat window loads, the call to `initEncryptedSession` is being made with the path `/api/...` instead of a relative path, `api/...` like most everything else seems to do.

This won't affect anyone using a dedicated hostname like "chat.foo.com" but if you're trying to serve it as a path under your existing server (ex. "www.foo.com/chat") it creates a problem.

Line in question:

https://github.com/RocketChat/Rocket.Chat/blob/a3656b3304e36ccdcb1e7cd6a0f703d1faf92ec8/ee/client/ecdh.ts#L34

The further problem is that the client appears to immediately retry `getSetupWizardParameters` and immediately goes into 'too many requests' lockdown.  The browser client has no back-off to avoid that, or any messaging to indicate what happened; but that may be moot if the underlying problem is corrected.

### Steps to reproduce:

1. Setup an install where your ROOT_URL has a path on the end of it.
2. Hit that URL
3. Watch failure cascade

### Expected behavior:

Browser app should request `api/ecdh_proxy/initEncryptedSession` (resolving to `/chat/api/ecdh_proxy/initEncryptedSession` in the example above where the `/chat` path is being rewritten and routed)

### Actual behavior:

Browser loads setup screen then immediately flashes the loading screen then back again, in very rapid succession.

WARNING:  epilepsy danger (seriously)

### Server Setup Information:

Using latest rocketchat Docker container, in a K8s pod where the ingress is capture requests to /chat and sending them into the pod (with /chat stripped off).

### Client Setup Information

Chrome on OSX, though I don't think that's the problem.

### Relevant logs:

Server logs:

```
Exception while invoking method getSetupWizardParameters Error: Error, too many requests. Please slow down. You must wait 25 seconds before trying again. [too-many-requests]
    at Object.post (app/api/server/v1/misc.js:256:11)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
Exception while invoking method getSetupWizardParameters Error: Error, too many requests. Please slow down. You must wait 25 seconds before trying again. [too-many-requests]
    at Object.post (app/api/server/v1/misc.js:256:11)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
```
(ad nauseum)

Screen grab of the Chrome network showing the initEncryptedSession failure and the repeated requests:

![Image 2021-05-01 at 7 27 08 PM](https://user-images.githubusercontent.com/55685/116800168-624ccb80-aab3-11eb-94e5-f924239d4bfe.jpg)

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

Can you please make sure you complete this template. It may be that your issue is resolved with an update so we really need to know about your environment.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Also please have a good search for your issue before opening a new one - looking for `sub domains` you might find this

https://github.com/RocketChat/Rocket.Chat/issues/17515

Also note if you are going to propose a patch please do a proper PR.

Thanks.

**Comment by dotdotdotpaul** [comment]
Issue #17515 was closed Aug 2, 2020.  The original ticket was opened May 3rd, 2020.  Almost EXACTLY one year ago.

The last comment from Sing-Li was that you were going to fix it until the deprecated version, 4.x.  As for the version I'm using, it was 'latest' -- which is 3.14.  So it should be fixed.  It isn't.  Hence, new bug.  I don't open closed bugs, particularly if they're a year old.

As for the "template" -- I used it.  That's why my issue here has WAY more information than what you got a year ago.  I missed the version, sorry, I thought 'latest' was implied.

So the basic answer here is, "supporting subdirectories is hard" (it isn't) and "we're deprecating it in 4.x" (which isn't out yet) and "we declared the deprecation in our forums" (that nobody trying to install your software is going to see).  Got it.  I guess we can close this now, "don't care, won't fix."
