### ISSUE TITLE
SAML login error: unable to validate response URL

### ISSUE THREAD

**Issue by PatriceG** [RocketChat/Rocket.Chat#21940]
### Description:
When doing a SAML login we have the following error in the log and the user is redirected back to the Rocketchat home page (the page with the 'login with saml' button:

`error Error: Unable to validate response url at app/meteor-accounts-saml/server/lib/SAML.ts:386:12 at ResponseParser.validate (app/meteor-accounts-saml/server/lib/parsers/Response.ts:51:11) at SAMLServiceProvider.validateResponse (app/meteor-accounts-saml/server/lib/ServiceProvider.ts:188:17) at Function.processValidateAction (app/meteor-accounts-saml/server/lib/SAML.ts:382:19) at Function.processRequest (app/meteor-accounts-saml/server/...`

### Investigations:

We noticed that the reponse URL contains the internal port of RocketChat (3000). This seems like a regression.
The authentication passes if we expose RocketChat on the port 3000 (which is not doable in prod since it's on 443).

This is a blocker issue for us.

### Server Setup Information:

- Version of Rocket.Chat Server:  3.14.0
- Operating System: Linux
- Deployment Method:  Helm
- Number of Running Instances: 1 
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.3 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Windows

**Comment by PatriceG** [comment]
Are we the only one to have this issue?
This is preventing us from upgrading to a recent release.

**Comment by pierre-lehnen-rc** [comment]
If it's showing the port 3000 on the logs, then it must be configured to use it somewhere. Check the SAML settings on the admin for any URL with that port. It can also be the global Site Url.

**Comment by PatriceG** [comment]
Of course we have double-checked the configuration. No URL is using the port 3000.

**Comment by leManu** [comment]
Same problem here, with same message in logs.

We are trying to upgrade Rocket.Chat from 3.18.2 to 4.1.2, after upgrade SAML authentification is not working anymore.

**Comment by leManu** [comment]
The first error message (before `unable to validate response url`) shown in logs is :

`{"level":50,"time":"2021-11-30T08:14:49.716Z","pid":3770,"hostname":"rct1","name":"steffo:meteor-accounts-saml","err":{"type":"Error","message":"Status is: urn:oasis:names:tc:SAML:2.0:status:Responder","stack":"Error: Status is: urn:oasis:names:tc:SAML:2.0:status:Responder\n    at ResponseParser.validate (app/meteor-accounts-saml/server/lib/parsers/Response.ts:51:20)\n    at SAMLServiceProvider.validateResponse (app/meteor-accounts-saml/server/lib/ServiceProvider.ts:188:17)\n    at Function.processValidateAction (app/meteor-accounts-saml/server/lib/SAML.ts:383:19)\n    at Function.processRequest (app/meteor-accounts-saml/server/lib/SAML.ts:52:17)\n    at middleware (app/meteor-accounts-saml/server/listener.ts:62:8)\n    at app/meteor-accounts-saml/server/listener.ts:80:3"},"msg":"Status is: urn:oasis:names:tc:SAML:2.0:status:Responder"}`

**Comment by pierre-lehnen-rc** [comment]
This error means that the IdP response indicated the login was not successful, but without any error message provided.

**Comment by leManu** [comment]
Ok, we just solved the problem by tuning our IdP configuration.

Rocket.Chat SP wanted `urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport` for authentication method, and `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress` for `NameIDFormat`.

It seems that this was not required by RC v3 but mandatory with RC v4.

**Comment by PatriceG** [comment]
Thank you very much for sharing this!
We'll try this ASAP.

**Comment by pierre-lehnen-rc** [comment]
Thanks for the update!
Those values are the default values for those settings (already were on v3). What did you have on those settings instead?

**Comment by Exordian** [comment]
Forcing `urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport` hits us really bad. This effectively breaks password-less authentication with Azure AD.
Why does Rocket.Chat favor password authentication on SAML?

**Comment by pierre-lehnen-rc** [comment]
It shouldn't be required. What value are you using?

**Comment by Exordian** [comment]
It can be reproduced by creating an Enterprise Application on any Azure AD [1], use SAML authentication with RocketChat CE (as AuthnContext is fixed to the default [2]).
Using non-password authentication on Azure AD (such as Windows Hello for Business, FIDO, ...) do not count as password and raise 
```
Authentication method 'MultiFactor, Fido' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'.
```
This can't be changed on Azure AD as it seems to be part of the SAML standard [3].
```
The PasswordProtectedTransport class is applicable when a principal authenticates to an authentication
authority through the presentation of a password over a protected session.```


[1] https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/add-application-portal 
[2] https://github.com/RocketChat/Rocket.Chat/blob/157b882d38b34b7b79dea527316554fe33f70891/app/meteor-accounts-saml/server/lib/constants.ts#L47
[3] https://docs.oasis-open.org/security/saml/v2.0/saml-authn-context-2.0-os.pdf

**Comment by leManu** [comment]
> Thanks for the update! Those values are the default values for those settings (already were on v3). What did you have on those settings instead?

`AuthenticationMethod` was only `urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified`, we added `urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport`.

And we had only those values for `NameIDFormat` before :

- `urn:oasis:names:tc:SAML:2.0:nameid-format:transient`
- `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`

**Comment by roysbike** [comment]
version 5.4.3
SAML with google suite 


``{"level":50,"time":"2023-02-15T20:13:15.059Z","pid":1,"hostname":"6553a01a8fdb","name":"steffo:meteor-accounts-saml","err":{"type":"Error","message":"Unable to validate response url","stack":"Error: Unable to validate response url\n    at app/meteor-accounts-saml/server/lib/SAML.ts:412:12\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"Unable to validate response url"}`
`

**Comment by rugalimov** [comment]
Hi everyone! I had the same problem with 2fa authentication:

{"level":50,"time":"2023-04-26T13:50:50.088Z","pid":1388,"hostname":"test","name":"steffo:meteor-accounts-saml","err":{"type":"Error","message":"Status is: urn:oasis:names:tc:SAML:2.0:status:Responder","stack":"Error: Status is: urn:oasis:names:tc:SAML:2.0:status:Responder<br>    at ResponseParser.validate (app/meteor-accounts-saml/server/lib/parsers/Response.ts:51:20)<br>    at SAMLServiceProvider.validateResponse (app/meteor-accounts-saml/server/lib/ServiceProvider.ts:200:17)<br>    at Function.processValidateAction (app/meteor-accounts-saml/server/lib/SAML.ts:408:19)<br>    at Function.processRequest (app/meteor-accounts-saml/server/lib/SAML.ts:58:17)<br>    at middleware (app/meteor-accounts-saml/server/listener.ts:62:8)<br>    at app/meteor-accounts-saml/server/listener.ts:80:3"},"msg":"Status is: urn:oasis:names:tc:SAML:2.0:status:Responder"} 
{"level":50,"time":"2023-04-26T13:50:50.089Z","pid":1388,"hostname":"test","name":"steffo:meteor-accounts-saml","err":{"type":"Error","message":"Unable to validate response url","stack
":"Error: Unable to validate response url<br>    at app/meteor-accounts-saml/server/lib/SAML.ts:412:12<br>    at /snap/rocketchat-server/1546/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"Unable to validate response url"}

may be someone have any ideas? Please, help!
