### ISSUE TITLE
Administration page does not display

### ISSUE THREAD

**Issue by cprice-kgi** [RocketChat/Rocket.Chat#22031]
### Description:

The Admin info page does not display.

### Steps to reproduce:

1. As an admin user, click on your icon in the upper left 
2. Click on Administration

### Expected behavior:

Administration info page should appear in browser

### Actual behavior:

Administration info page flashes momentarily then disappears, and browser shows a blank screen.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: OSX 11.3
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Tested on both Chrome and Safari
- Operating System: OSX 11.3

### Relevant logs:

No relevant log from server

Browser log:

```
DeploymentCard.js:69 Uncaught TypeError: Cannot read property 'slice' of undefined
    at eval (DeploymentCard.js:69)
    at s (DeploymentCard.js:18)
    at DeploymentCard (DeploymentCard.js:69)
    at renderWithHooks (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:53391)
    at updateFunctionComponent (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:55762)
    at updateSimpleMemoComponent (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:55621)
    at beginWork (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:57546)
    at HTMLUnknownElement.callCallback (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42351)
    at Object.invokeGuardedCallbackDev (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42400)
    at invokeGuardedCallback (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42462)
eval @ DeploymentCard.js:69
s @ DeploymentCard.js:18
DeploymentCard @ DeploymentCard.js:69
renderWithHooks @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:53391
updateFunctionComponent @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:55762
updateSimpleMemoComponent @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:55621
beginWork @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:57546
callCallback @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42351
invokeGuardedCallbackDev @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42400
invokeGuardedCallback @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42462
beginWork$1 @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:62370
performUnitOfWork @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61185
workLoopSync @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61113
renderRootSync @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61076
performSyncWorkOnRoot @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:60699
(anonymous) @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:49733
unstable_runWithPriority @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:65210
runWithPriority$1 @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:49682
flushSyncCallbackQueueImpl @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:49728
flushSyncCallbackQueue @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:49715
scheduleUpdateOnFiber @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:60299
dispatchAction @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:54545
fetchStatistics @ InformationRoute.js:45
async function (async)
fetchStatistics @ InformationRoute.js:32
eval @ InformationRoute.js:51
invokePassiveEffectCreate @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61893
callCallback @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42351
invokeGuardedCallbackDev @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42400
invokeGuardedCallback @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42462
flushPassiveEffectsImpl @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61980
unstable_runWithPriority @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:65210
runWithPriority$1 @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:49682
flushPassiveEffects @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61853
(anonymous) @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61730
workLoop @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:65160
flushWork @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:65134
performWorkUntilDeadline @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:64900
modules.js?hash=52e2d9969878faac246750bf049afff289af5803:58491 The above error occurred in the <DeploymentCard> component:

    at DeploymentCard (/client/views/admin/info/DeploymentCard.js:79:5)
    at Margins (http://localhost:3000/packages/modules.js?hash=52e2d9969878faac246750bf049afff289af5803:27256:24)
    at div
    at Box (http://localhost:3000/packages/modules.js?hash=52e2d9969878faac246750bf049afff289af5803:25020:24)
    at div
    at Box (http://localhost:3000/packages/modules.js?hash=52e2d9969878faac246750bf049afff289af5803:25020:24)
    at div
    at Box (http://localhost:3000/packages/modules.js?hash=52e2d9969878faac246750bf049afff289af5803:25020:24)
    at div
    at div
    at Scrollbars (/node_modules/rc-scrollbars/lib/Scrollbars/index.js:78:28)
    at WrappedComponent (/client/components/ScrollableContentWrapper.tsx:70:5)
    at div
    at Box (http://localhost:3000/packages/modules.js?hash=52e2d9969878faac246750bf049afff289af5803:25020:24)
    at PageScrollableContent (/client/components/Page/PageScrollableContent.tsx:53:5)
    at PageScrollableContentWithShadow (/client/components/Page/PageScrollableContentWithShadow.tsx:63:5)
    at section
    at Box (http://localhost:3000/packages/modules.js?hash=52e2d9969878faac246750bf049afff289af5803:25020:24)
    at Page (/client/components/Page/Page.tsx:44:31)
    at InformationPage (/client/views/admin/info/NewInformationPage.js:100:5)
    at InformationRoute (/client/views/admin/info/InformationRoute.js:105:13)
    at Suspense
    at SettingsProvider (/client/providers/SettingsProvider.tsx:92:5)
    at AdministrationLayout (/client/views/admin/AdministrationLayout.tsx:30:5)
    at AdministrationRouter (/client/views/admin/AdministrationRouter.js:59:5)
    at Suspense
    at WrappedComponent (http://localhost:3000/app/app.js?hash=523436f8c084ca5d7831daf314e861617fb82b03:72784:31)
    at AppLayout (/client/views/root/AppLayout.tsx:65:22)
    at AttachmentProvider (/client/components/Message/Attachments/providers/AttachmentProvider.tsx:58:5)
    at ModalProvider (/client/providers/ModalProvider.tsx:59:5)
    at OmnichannelProvider (/client/providers/OmnichannelProvider.tsx:118:5)
    at AuthorizationProvider (/client/providers/AuthorizationProvider.tsx:92:5)
    at UserProvider (/client/providers/UserProvider.tsx:84:5)
    at CustomSoundProvider (/client/providers/CustomSoundProvider.tsx:33:5)
    at AvatarUrlProvider (/client/providers/AvatarUrlProvider.tsx:61:5)
    at LayoutProvider (/client/providers/LayoutProvider.tsx:67:5)
    at SettingsProvider (/client/providers/SettingsProvider.tsx:92:5)
    at ToastMessagesProvider (/client/providers/ToastMessagesProvider.tsx:64:5)
    at SidebarProvider (/client/providers/SidebarProvider.tsx:50:5)
    at SessionProvider (/client/providers/SessionProvider.tsx:46:5)
    at TranslationProvider (/client/providers/TranslationProvider.js:130:5)
    at RouterProvider (/client/providers/RouterProvider.tsx:96:5)
    at ServerProvider (/client/providers/ServerProvider.js:113:5)
    at ConnectionStatusProvider (/client/providers/ConnectionStatusProvider.tsx:52:5)
    at MeteorProvider (/client/providers/MeteorProvider.tsx:131:5)
    at Suspense
    at AppRoot

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:58491
update.callback @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:58524
callCallback @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:50724
commitUpdateQueue @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:50745
commitLifeCycles @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:59142
commitLayoutEffects @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61832
callCallback @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42351
invokeGuardedCallbackDev @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42400
invokeGuardedCallback @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42462
commitRootImpl @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61557
unstable_runWithPriority @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:65210
runWithPriority$1 @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:49682
commitRoot @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61396
performSyncWorkOnRoot @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:60735
(anonymous) @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:49733
unstable_runWithPriority @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:65210
runWithPriority$1 @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:49682
flushSyncCallbackQueueImpl @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:49728
flushSyncCallbackQueue @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:49715
scheduleUpdateOnFiber @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:60299
dispatchAction @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:54545
fetchStatistics @ InformationRoute.js:45
async function (async)
fetchStatistics @ InformationRoute.js:32
eval @ InformationRoute.js:51
invokePassiveEffectCreate @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61893
callCallback @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42351
invokeGuardedCallbackDev @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42400
invokeGuardedCallback @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42462
flushPassiveEffectsImpl @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61980
unstable_runWithPriority @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:65210
runWithPriority$1 @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:49682
flushPassiveEffects @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61853
(anonymous) @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61730
workLoop @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:65160
flushWork @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:65134
performWorkUntilDeadline @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:64900
modules.js?hash=52e2d9969878faac246750bf049afff289af5803:16819 XHR finished loading: GET "http://localhost:3000/api/v1/statistics?refresh=false".
send @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:16819
ajax @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:16402
_rlRestApiGet @ RestApiClient.js:68
_jqueryCall @ RestApiClient.js:67
APIClient._jqueryCall @ ecdh.ts:72
async function (async)
APIClient._jqueryCall @ ecdh.ts:69
get @ RestApiClient.js:18
get @ RestApiClient.js:165
callEndpoint @ ServerProvider.js:34
(anonymous) @ ServerContext.ts:90
fetchStatistics @ InformationRoute.js:33
eval @ InformationRoute.js:51
invokePassiveEffectCreate @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61893
callCallback @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42351
invokeGuardedCallbackDev @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42400
invokeGuardedCallback @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42462
flushPassiveEffectsImpl @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61980
unstable_runWithPriority @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:65210
runWithPriority$1 @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:49682
flushPassiveEffects @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61853
(anonymous) @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:61730
workLoop @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:65160
flushWork @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:65134
performWorkUntilDeadline @ modules.js?hash=52e2d9969878faac246750bf049afff289af5803:64900
DeploymentCard.js:69 Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined
    at eval (DeploymentCard.js:69)
    at s (DeploymentCard.js:18)
    at DeploymentCard (DeploymentCard.js:69)
    at renderWithHooks (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:53391)
    at updateFunctionComponent (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:55762)
    at updateSimpleMemoComponent (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:55621)
    at beginWork (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:57546)
    at HTMLUnknownElement.callCallback (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42351)
    at Object.invokeGuardedCallbackDev (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42400)
    at invokeGuardedCallback (modules.js?hash=52e2d9969878faac246750bf049afff289af5803:42462)
```

**Comment by johncrisp** [comment]
Hi and thanks for reporting.

Can you give us a bit of history please? New install, upgrade etc.

**Comment by cprice-kgi** [comment]
New dev server install for local testing. Just downloaded zip archive from the 3.14 release page.

`meteor npm install
meteor npm start`

Let me know if there's any other info I can provide. I have run other dev server versions locally before, but only from their own respective directories.

**Comment by Gobliins** [comment]
Same Problem. Is there a fix to this, or a working branch without this problem?

**Comment by cprice-kgi** [comment]
@Gobliins i did end up resolving it here
https://github.com/RocketChat/Rocket.Chat/pull/22057

i'm not sure if it has been integrated into the main code or not, but you can see my comments and fix there.

**Comment by Gobliins** [comment]
I see. I guess it's not merged, at least not in the release / master branches i checked. For now i switched back to release 2.2 which is working without that error. Thx.

**Comment by sbelavsky** [comment]
same here

**Comment by dougfabris** [comment]
Thanks for the help @cprice-kgi! @Gobliins @sbelavsky we merged this fix 19 days ago, so no release was launched after that. I strongly believe we're going to have this fix in our today's release, keep watching version 3.17
