### ISSUE TITLE
LDAP unstable in the environment  v0.17.0

### ISSUE THREAD

**Issue by valessiobrito** [RocketChat/Rocket.Chat#2208]
Application is falling after a while with LDAP authentication

Version: 0.17.0
DB_migration: 28
Node.js  v0.10.40
Debian Stable

/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:226
                        throw new Error('Future resolved more than once');
                              ^
Error: Future resolved more than once
    at Object.Future.return (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:226:10)
    at Client.<anonymous> (packages/rocketchat_ldap/ldap_server.js:100:1)
    at Client.emit (events.js:95:17)
    at Socket.onSocketError (/opt/Rocket.Chat/programs/server/npm/rocketchat_ldap/node_modules/ldapjs/lib/client/client.js:1169:12)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:492:13)

**Comment by valessiobrito** [comment]
findStarredByUserAtRoom { '0': 'XXXXXXXX',
  '1': 'GENERAL',
  '2': { sort: { ts: -1 }, limit: 50 } }
findStarredByUserAtRoom { '0': 'XXXXXXXX',
  '1': 'XXXXXXXXX',
  '2': { sort: { ts: -1 }, limit: 50 } }
LDAP search dn dc=domain,dc=com,dc=br
LDAP search options { filter: '(&(objectclass=user)(|(mail=valessio.brito)(sAMAccountName=valessio.brito)))',
  scope: 'sub' }
Attempt to bind CN=Valessio Soares de Brito,OU=Usuarios,DC=domain,DC=com,DC=br

/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:226
                        throw new Error('Future resolved more than once');
                              ^
Error: Future resolved more than once
    at Object.Future.return (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:226:10)
    at Client.<anonymous> (packages/rocketchat_ldap/ldap_server.js:100:1)
    at Client.emit (events.js:95:17)
    at Socket.onSocketError (/opt/Rocket.Chat/programs/server/npm/rocketchat_ldap/node_modules/ldapjs/lib/client/client.js:1169:12)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:492:13)

**Comment by rodrigok** [comment]
@valessiobrito can you test the new version 0.18.0 released today? We did a refactor in LDAP.

**Comment by valessiobrito** [comment]
Ok!   0.18.0  working fine.
