### ISSUE TITLE
Exception while invoking method getRoomByTypeAndName Error: Invalid user [error-invalid-user]

### ISSUE THREAD

**Issue by QuentinPi** [RocketChat/Rocket.Chat#22149]
Rocket.Chat Version: 3.14.3 
 NodeJS Version: 12.22.1 - x64  
MongoDB Version: 3.6.21   
 MongoDB Engine: mmapv1    
 Platform: linux

```
rocketchat_1           | Exception while invoking method getRoomByTypeAndName Error: Invalid user [error-invalid-user]
rocketchat_1           |     at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:43:10)
rocketchat_1           |     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
rocketchat_1           |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
rocketchat_1           |     at packages/ddp-server/livedata_server.js:1689:15
rocketchat_1           |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
rocketchat_1           |     at packages/ddp-server/livedata_server.js:1687:36
rocketchat_1           |     at new Promise (<anonymous>)
rocketchat_1           |     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
rocketchat_1           |     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
rocketchat_1           |     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
rocketchat_1           |     at Object.post (app/api/server/v1/misc.js:263:26)
rocketchat_1           |     at app/api/server/api.js:394:82
rocketchat_1           |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
rocketchat_1           |     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
rocketchat_1           |     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
rocketchat_1           |     at packages/nimble_restivus/lib/route.coffee:59:33
rocketchat_1           |     at packages/simple_json-routes.js:98:9
rocketchat_1           |  => awaited here:
rocketchat_1           |     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
rocketchat_1           |     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
rocketchat_1           |     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
rocketchat_1           |     at Object.post (app/api/server/v1/misc.js:263:26)
rocketchat_1           |     at app/api/server/api.js:394:82
rocketchat_1           |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
rocketchat_1           |     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
rocketchat_1           |     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
rocketchat_1           |     at packages/nimble_restivus/lib/route.coffee:59:33
rocketchat_1           |     at packages/simple_json-routes.js:98:9
```
 
I can't access to anything on my rocketchat instance since this exception appears.
On the client sside : 
```
Error: No callback invoker for method 3
    _process_updated /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:696
    _process_updated /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:696
    _processOneDataMessage /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:696
    _livedata_data /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:696
    u /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:958
    t /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:958
    bindEnvironment /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:1
    promise callback*n/t.makeCompatible/n.prototype.then /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:652
    t /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:958
    sendMessage /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:696
    _sendOutstandingMethods /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:696
    _sendOutstandingMethods /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:696
    _callOnReconnectAndSendAppropriateOutstandingMethods /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:696
    onReset /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:696
    _connected /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    forEachCallback /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    _connected /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    onopen /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    dispatchEvent /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    _dispatchOpen /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    _didMessage /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    onmessage /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    websocket /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    _try_next_protocol /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    _didClose /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    onfinish /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    emit /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    onfinish /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    emit /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    onreadystatechange /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    EventHandlerNonNull* /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    XHRLocalObject /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    setTimeout handler*t/a</n.delay /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    XHRLocalObject /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    <anonymous> /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    J /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    setTimeout handler*t/a</n.delay /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    J /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    q /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    k /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    _launchConnection /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:666
    _launchConnection /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:668
    allowConnection /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:668
    l /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:958
    e /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:958
    g /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:3
    n /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:3
    a /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:5
    e /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:958
    g /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:3
    n /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:3
    e /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:3
    <anonymous> /6a1dbf84187d2b95ded5628c5e9012680877c087.js?meteor_js_resource=true:958
```

Do I have to fix the db by hand or is this related to the latest version ?

**Comment by joseluisq** [comment]
We have a similar issue after adding a new user.

v3.15.1

After new user sends a message using the browser an error is shown.
<img width="500" src="https://user-images.githubusercontent.com/1700322/123273957-5f92b380-d503-11eb-9bee-485eff5df2e3.png">

**Comment by solanha1999** [comment]
@QuentinPi and @joseluisq  how do you deal with this problem? Do you updated or was it something to fix in the database?

**Comment by joseluisq** [comment]
@solanha1999 unfortunately we have not solved the problem yet.
