### ISSUE TITLE
IRC Federation not working

### ISSUE THREAD

**Issue by jiantaozi** [RocketChat/Rocket.Chat#22165]
Description:
Hey,

the IRC implementation is  not working.

Expected behavior:
IRC Federation with Rocket Chat

Actual behavior:
Server Setup Information:
Version of Rocket.Chat Server: 3.0.5
Operating System: Centos7
Deployment Method: docker
Number of Running Instances: 1
MongoDB Version: 4.0
Additional context

Relevant logs:
rocketchat_1          | [irc][server] Connecting to @192.168.56.103:6667
rocketchat_1          | [irc][server] Connected! Registering as server...
rocketchat_1          | [irc][server] Sending Command: PASS 111111 0210 ngircd
rocketchat_1          | [irc][server] Sending Command: SERVER irc.rocket.chat :Rocket.Chat IRC Bridge
rocketchat_1          | [irc][server][err] Error: write EPIPE
rocketchat_1          |     at afterWriteDispatched (internal/stream_base_commons.js:154:25)
rocketchat_1          |     at writeGeneric (internal/stream_base_commons.js:145:3)
rocketchat_1          |     at Socket._writeGeneric (net.js:780:11)
rocketchat_1          |     at Socket._write (net.js:792:8)
rocketchat_1          |     at doWrite (_stream_writable.js:441:12)
rocketchat_1          |     at writeOrBuffer (_stream_writable.js:425:5)
rocketchat_1          |     at Socket.Writable.write (_stream_writable.js:316:11)
rocketchat_1          |     at RFC2813.write (app/irc/server/servers/RFC2813/index.js:114:22)
rocketchat_1          |     at RFC2813.onConnect (app/irc/server/servers/RFC2813/index.js:90:8)
rocketchat_1          |     at Socket.emit (events.js:323:22)
rocketchat_1          |     at Socket.EventEmitter.emit (domain.js:482:12)
rocketchat_1          |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1123:10) {
rocketchat_1          |   errno: 'EPIPE',
rocketchat_1          |   code: 'EPIPE',
rocketchat_1          |   syscall: 'write'
rocketchat_1          | }
rocketchat_1          | [irc][server] Connection Closed

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

Please always follow the guide here when reporting issues:

 https://rocket.chat/docs/contributing/reporting-issues

> Version of Rocket.Chat Server: 3.3.3

Your version is considerably out of date.

As per the guide you need to test this on latest - 3.15RC (with 3.15.0 about to land in a couple of days)

Let us know soonest if that fixes your issue.

Thanks.

**Comment by johncrisp** [comment]
Closing this.

Please let us know if you have issues on the latest version of Rocket.Chat

**Comment by jiantaozi** [comment]
Sorry to reply so long
test this on latest - 3.16.1RC  According to your request
The error is as follows
^[[35mrocketchat_1          |^[[0m [irc][server] Connecting to @192.168.56.102:6667
^[[35mrocketchat_1          |^[[0m [irc][server] Connected! Registering as server...
^[[35mrocketchat_1          |^[[0m [irc][server] Sending Command: PASS 111111 0210 ngircd
^[[35mrocketchat_1          |^[[0m [irc][server] Sending Command: SERVER irc.rocket.chat :Rocket.Chat IRC Bridge
^[[35mrocketchat_1          |^[[0m [irc][server][err] Error: write EPIPE
^[[35mrocketchat_1          |^[[0m     at afterWriteDispatched (internal/stream_base_commons.js:156:25)
^[[35mrocketchat_1          |^[[0m     at writeGeneric (internal/stream_base_commons.js:147:3)
^[[35mrocketchat_1          |^[[0m     at Socket._writeGeneric (net.js:787:11)
^[[35mrocketchat_1          |^[[0m     at Socket._write (net.js:799:8)
^[[35mrocketchat_1          |^[[0m     at doWrite (_stream_writable.js:403:12)
^[[35mrocketchat_1          |^[[0m     at writeOrBuffer (_stream_writable.js:387:5)
^[[35mrocketchat_1          |^[[0m     at Socket.Writable.write (_stream_writable.js:318:11)
^[[35mrocketchat_1          |^[[0m     at RFC2813.write (app/irc/server/servers/RFC2813/index.js:114:22)
^[[35mrocketchat_1          |^[[0m     at RFC2813.onConnect (app/irc/server/servers/RFC2813/index.js:90:8)
^[[35mrocketchat_1          |^[[0m     at Socket.emit (events.js:326:22)
^[[35mrocketchat_1          |^[[0m     at Socket.EventEmitter.emit (domain.js:483:12)
^[[35mrocketchat_1          |^[[0m     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1130:10)
^[[35mrocketchat_1          |^[[0m     at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:126:14) {
^[[35mrocketchat_1          |^[[0m   errno: 'EPIPE',
^[[35mrocketchat_1          |^[[0m   code: 'EPIPE',
^[[35mrocketchat_1          |^[[0m   syscall: 'write'
^[[35mrocketchat_1          |^[[0m }
^[[35mrocketchat_1          |^[[0m [irc][server] Connection Closed
^[[35mrocketchat_1          |^[[0m Updating process.env.MAIL_URL
^[[35mrocketchat_1          |^[[0m ➔ System ➔ startup
^[[35mrocketchat_1          |^[[0m ➔ +----------------------------------------------+
^[[35mrocketchat_1          |^[[0m ➔ |                SERVER RUNNING                |
^[[35mrocketchat_1          |^[[0m ➔ +----------------------------------------------+
^[[35mrocketchat_1          |^[[0m ➔ |                                              |
^[[35mrocketchat_1          |^[[0m ➔ |  Rocket.Chat Version: 3.16.1                 |
^[[35mrocketchat_1          |^[[0m ➔ |       NodeJS Version: 12.22.1 - x64          |
^[[35mrocketchat_1          |^[[0m ➔ |      MongoDB Version: 4.0.25                 |
