### ISSUE TITLE
SlackBridge "onMessage Error: Not enough permission" since v3.15.0

### ISSUE THREAD

**Issue by 3id0** [RocketChat/Rocket.Chat#22217]
### Description:

After upgrading from v3.14.4 to v3.15.0, SlackBridge stopped working (at least when sending from Slack to Rocket.Chat).

I tried to rollback to 3.14.4 by changing the tag in docker-compose.yml and rebuilding the containers but Rocket.Chat throws `Can’t find migration version 225` which I guess is not surprising since mongodb’s structure/schema must have change between 3.14 and 3.15.

If we restore a mongodump backup from before the upgrade we are going to lose a few days of data which is not a good solution.

### Steps to reproduce:

Post a message in a Slack channel that is paired with a Rocket.Chat channel (which used to work before 3.15.0)

### Expected behavior:

Message is posted in Rocket.Chat

### Actual behavior:

No message is posted from Slack to Rocket.Chat, instead the following error is logged:
```
server.js:204 SlackBridge ➔ Slack.error Unhandled error onMessage Error: Not enough permission
at validateMessage (app/lib/server/functions/sendMessage.js:151:10)
at sendMessage (app/lib/server/functions/sendMessage.js:165:2)
at RocketAdapter.createAndSaveMessage (app/slackbridge/server/RocketAdapter.js:499:5)
at SlackAdapter.processNewMessage (app/slackbridge/server/SlackAdapter.js:830:17)
at SlackAdapter.onMessage (app/slackbridge/server/SlackAdapter.js:453:9)
at app/slackbridge/server/SlackAdapter.js:108:11
at runWithEnvironment (packages/meteor.js:1286:24)
```

On the other hand sending a message from Rocket.Chat to Slack still works fine, as it did in 13.4.4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: Debian
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.24 / mmapv1 (oplog Enabled)
- Proxy: traefik
- Firewalls involved: iptables managed by Docker

**Comment by 3id0** [comment]
@morehek proposed a solution/workaround here:
https://github.com/RocketChat/Rocket.Chat/issues/22218#issuecomment-853722277

> After adding bot role to appropriate user it worked.
