### ISSUE TITLE
A lot of "Exception while invoking method userSetUtcOffset"

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22237]
### Description:

Rocket Chat logs are flooded with `Exception while invoking method userSetUtcOffset` error

### Steps to reproduce:

1. Look at RC server logs
2. See `Exception while invoking method userSetUtcOffset` error

### Expected behavior:

Clean logs without errors on normal server work

### Actual behavior:

Lot of `Exception while invoking method userSetUtcOffset` errors

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14 WiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.2.2
- Operating System: Windows 10

### Additional context

I don't know how to reproduce that bug actually.
Maybe RCRN mobile application generate it.

### Relevant logs:

```
I20210604-02:04:58.084(0) Exception while invoking method userSetUtcOffset Error: Error, too many requests. Please slow down. You must wait 60 seconds before trying again. [too-many-requests]     at Object.post (app/api/server/v1/misc.js:256:11)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20210604-02:05:07.561(0) Exception while invoking method userSetUtcOffset Error: Error, too many requests. Please slow down. You must wait 51 seconds before trying again. [too-many-requests]     at Object.post (app/api/server/v1/misc.js:256:11)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20210604-02:46:38.643(0) Exception while invoking method userSetUtcOffset Error: Error, too many requests. Please slow down. You must wait 60 seconds before trying again. [too-many-requests]     at Object.post (app/api/server/v1/misc.js:256:11)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20210604-02:47:55.935(0) Exception while invoking method userSetUtcOffset Error: Error, too many requests. Please slow down. You must wait 60 seconds before trying again. [too-many-requests]     at Object.post (app/api/server/v1/misc.js:256:11)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
```

**Comment by ankar84** [comment]
As a workaround did try to increase rate limiter in 10 times, didn't help
![image](https://user-images.githubusercontent.com/4023037/120743846-721c5d00-c502-11eb-96e3-2ade15692cc5.png)

**Comment by ankar84** [comment]
Still exist in 3.16.3

**Comment by dholbrook86** [comment]
Also seeing this. Any fixes you've found @ankar84?

**Comment by ankar84** [comment]
> Also seeing this. Any fixes you've found @ankar84?

Nope. Still waiting a fix from a team.

**Comment by ankar84** [comment]
Still see that log entries in logs at 3.18.1 version of Rocket.Chat.
But maybe there is less such entries.

**Comment by khornik** [comment]
Problem still exists

**Comment by ankar84** [comment]
Still on 4.2.2 but amount of that messages decreased a bit
![image](https://user-images.githubusercontent.com/4023037/148886611-49ce0df0-fe24-4dc7-9c1c-f0edf3390863.png)

**Comment by ankar84** [comment]
Still an issue at 4.6.2
174 hit in 1 hour early morning (not all users are working now)
![image](https://user-images.githubusercontent.com/4023037/163758716-a656e32d-ebd9-4773-9f37-4b7eb6ba5a73.png)

**Comment by ankar84** [comment]
Still see that log entry, but much less on 5.0.3
```
{"level":50,"time":"2022-08-19T11:17:51.679Z","pid":225,"hostname":"f7608ebd43de","name":"System","msg":"Exception while invoking method userSetUtcOffset 'Error, too many requests. Please slow down. You must wait 39 seconds before trying again. [too-many-requests]'"} 
{"level":50,"time":"2022-08-19T11:17:53.474Z","pid":225,"hostname":"f7608ebd43de","name":"System","msg":"Exception while invoking method userSetUtcOffset 'Error, too many requests. Please slow down. You must wait 37 seconds before trying again. [too-many-requests]'"} 
```

**Comment by ankar84** [comment]
I'm closing that issue. 
If I will see that log entries again, I will reopen
fixed in https://github.com/RocketChat/Rocket.Chat/pull/25381
