### ISSUE TITLE
[Bug][Jitsi] Issues with jitsi:updateTimeout

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22255]
### Description:

That issue related to my other [issue about logs flooded by jitsi errors](https://github.com/RocketChat/Rocket.Chat/issues/19441) but the issue is more complex and I decided to make separate issue.

I guess in some cases `jitsi:updateTimeout` method gets endless loop and lead to RC server overload and RC logs flooded.
That issue need to be solved somehow because really massive of RC deployments use Jitsi and can be affected.

### Steps to reproduce:

1. Setup Jitsi integration
2. Check RC Metrics and RC logs

### Expected behavior:

Jitsi integration works without issues

### Actual behavior:

Here is a graph for REST API at weekend when users activity really low and almost without Jitsi calls
![image](https://user-images.githubusercontent.com/4023037/120914804-1b04bc80-c6a9-11eb-9fa1-d88861caa426.png)
As you can see `method.call/jitsi:updateTimeout` have a high value and even RC instances restarts over night don't decrease it.
I guess that request generated by launched RC clients (maybe most of all is Electron application)
And here is amount of log entries and almost all of them about jitsi timeout
![image](https://user-images.githubusercontent.com/4023037/120914927-af6f1f00-c6a9-11eb-997a-695c2f7de71e.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0.
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14 WiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.2.2
- Operating System: Windows 10

### Additional context

I believe that issue could lead to creation of Click to Join! buttons appears on behalf of user with RC.Electron launched on RC instances restart - and I had users request about that issue on 3.14.0

Could be related to https://github.com/RocketChat/Rocket.Chat/issues/21182 in stability aspect

### Relevant logs:

A lot of similar log errors with different error text like this

```
I20201102-16:15:42.588(0) server.js:204 System ➔ error Error starting video call: Error: You_have_been_muted     at app/authorization/server/functions/canSendMessage.js:37:9     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/authorization/server/functions/canSendMessage.js:43:2     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at canSendMessage (app/authorization/server/functions/canSendMessage.js:47:84)     at MethodInvocation.jitsi:updateTimeout (app/videobridge/server/methods/jitsiSetTimeout.js:27:17)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 

I20210319-10:51:17.897(0) server.js:204 System ➔ error Error starting video call: Error: You can't send messages because the room is readonly.     at app/authorization/server/functions/canSendMessage.js:32:10     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/authorization/server/functions/canSendMessage.js:43:2     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at canSendMessage (app/authorization/server/functions/canSendMessage.js:47:84)     at MethodInvocation.jitsi:updateTimeout (app/videobridge/server/methods/jitsiSetTimeout.js:27:17)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20210319-10:51:17.905(0) Exception while invoking method jitsi:updateTimeout Error: You can't send messages because the room is readonly. [error-starting-video-call]     at MethodInvocation.jitsi:updateTimeout (app/videobridge/server/methods/jitsiSetTimeout.js:55:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20210319-10:51:17.907(0) API ➔ debug Success {   statusCode: 200,   body: {     message: `{"msg":"result","id":"50","error":{"isClientSafe":true,"error":"error-starting-video-call","reason":"You can't send messages because the room is readonly.","message":"You can't send messages because the room is readonly. [error-starting-video-call]","errorType":"Meteor.Error"}}`,     success: true   } } 

I20210422-10:54:05.048(0) server.js:204 System ➔ error Error starting video call: Error: You can't send messages because the room is readonly.     at app/authorization/server/functions/canSendMessage.js:32:10     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/authorization/server/functions/canSendMessage.js:43:2     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at canSendMessage (app/authorization/server/functions/canSendMessage.js:47:84)     at MethodInvocation.jitsi:updateTimeout (app/videobridge/server/methods/jitsiSetTimeout.js:27:17)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 

```

**Comment by johncrisp** [comment]
Thanks for reporting Anton.

I guess this goes with 'Jitsi' and 'Performance'?

**Comment by ankar84** [comment]
> Thanks for reporting Anton.
> 
> I guess this goes with 'Jitsi' and 'Performance'?

Yes, John! Our main goals to achieve - Jitsi and Performance (stability)

**Comment by ankar84** [comment]
Looks like logs is more cleaner in 3.16,X versions.
I guess https://github.com/RocketChat/Rocket.Chat/pull/22277 fixed that and all other Jitsi annoying issues!
