### ISSUE TITLE
Errors [error-invalid-user] and [error-invalid-room]

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22256]
### Description:

Since I enabled **Use REST instead of websocket for Meteor calls** in **Admin UI - General - REAT API** (and I don't know why it was disabled, because default seems to be enabled state) I get in logs a lot of useless entries like this:
```
Exception while invoking method getRoomByTypeAndName Error: Invalid user [error-invalid-user]
Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]
```
They a really useless because don't give information how to fix them - they don't mention which user or room is currently invalid. But instead of mention user or room it shows useless stack trace which is flooding our logs because we using docker deployment and that traces generates a lot of log entries.

### Steps to reproduce:

1. Enable **Use REST instead of websocket for Meteor calls** in **Admin UI - General - REST API**
2. Check logs

### Expected behavior:

Or clean logs or mention what user or room is invalid actually to handle that and fix it.

### Actual behavior:

Flooded logs and (maybe) bad influence to server general load which could lead to instability.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14 WiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.2.2
- Operating System: Windows 10

### Additional context

Could be related to https://github.com/RocketChat/Rocket.Chat/issues/21182 in stability aspect

### Relevant logs:

```

I20210606-01:21:49.596(0) Exception while invoking method getRoomByTypeAndName Error: Invalid user [error-invalid-user]     at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:43:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20210606-03:11:20.945(0) Exception while invoking method getRoomByTypeAndName Error: Invalid user [error-invalid-user]     at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:43:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20210606-03:11:20.983(0) Exception while invoking method createDirectMessage Error: Invalid user [error-invalid-user]     at MethodInvocation.createDirectMessage (server/methods/createDirectMessage.js:16:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20210605-23:10:16.745(0) Exception while invoking method loadMissedMessages Error: Invalid user [error-invalid-user]     at MethodInvocation.canAccessRoom (server/methods/canAccessRoom.js:51:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at MethodInvocation.loadMissedMessages (server/methods/loadMissedMessages.js:13:15)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at MethodInvocation.loadMissedMessages (server/methods/loadMissedMessages.js:13:15)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20210605-23:10:16.864(0) Exception while invoking method loadMissedMessages Error: Invalid user [error-invalid-user]     at MethodInvocation.canAccessRoom (server/methods/canAccessRoom.js:51:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at MethodInvocation.loadMissedMessages (server/methods/loadMissedMessages.js:13:15)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at MethodInvocation.loadMissedMessages (server/methods/loadMissedMessages.js:13:15)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 

Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]

```

**Comment by johncrisp** [comment]
Anton,

Can you edit that to say REST not REAT ?

**Comment by ankar84** [comment]
> Anton,
> 
> Can you edit that to say REST not REAT ?

Done!
One important note - we are using **KeyCloak** for authentication and after update to 3.15.0 I have a couple users request about **Invalid user** error on a blank gray background of RC.Electron application
![image](https://user-images.githubusercontent.com/4023037/120950111-be5bdd00-c74e-11eb-9fa2-fd9dd512b33e.png)
**Restart of client** and **CTRL+R** doesn't help, only **recreating our server connection** (delete - add)

**Comment by emikolajczak** [comment]
Hi, I have also observe this `Errors [error-invalid-user]` and `[error-invalid-room]` errors in logs,

**Comment by dkoo761** [comment]
I can reproduce this error....

`Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]`

Steps to reproduce:
1. Go to the directory
2. Click on the Users tab
3. Click on a user that I have never clicked on (or had a DM with) before
4. In this case, it tries to load the user using the /direct/{username} URL which throws the exception and then it creates a new room and opens it for the user and redirects to the /direct/{roomId} URL

**Comment by dkoo761** [comment]
Actually any time a user opens a DM window with another user for the first time, this exception seems to occur. Not just when you click on the user from the directory page as I mentioned above.

**Comment by tmartincpp** [comment]
We are having this error too but I can't reproduce everytime, it seems to happen randomly when you want to send a DM to a user for the first time.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.1
- Operating System: Debian Buster
- Deployment Method: build from sources
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.25


### Client Setup Information

- Desktop App: 3.2.3 or 3.1.1
- Operating System: Debian Buster


### Additional context

REST API is enabled but I don't know if this is relevant.
Our users are created and authenticated through LDAP.


### Relevant logs:

```
Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]
    at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:51:10)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:263:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
 => awaited here:
    at Promise.await (/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:263:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
Exception while invoking method createDirectMessage Error: Invalid user [error-invalid-user]
    at server/methods/createDirectMessage.js:44:11
    at Array.map (<anonymous>)
    at MethodInvocation.createDirectMessage (server/methods/createDirectMessage.js:35:74)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:263:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
 => awaited here:
    at Promise.await (/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:263:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
```

**Comment by ankar84** [comment]
Still exist in 3.16.3

**Comment by ankar84** [comment]
At 3.16.3 I see a lot of these:

```
server.js:204 System ➔ error Error starting video call: Error: error-invalid-room
Exception while invoking method jitsi:updateTimeout Error: error-invalid-room [error-starting-video-call]
Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]
Exception while invoking method createDirectMessage Error: Invalid user [error-invalid-user]
Exception while invoking method roomNameExists Error: Error, too many requests. Please slow down. You must wait 2 seconds before trying again. [too-many-requests]
Exception while invoking method jitsi:updateTimeout Error: error-invalid-room [error-starting-video-call]
server.js:204 System ➔ error Error starting video call: Error: error-invalid-room
```

**Comment by ankar84** [comment]
My guess, that all that **invalid-room** and **invalid-user** could be related to https://github.com/RocketChat/Rocket.Chat/issues/21237
And could be caused with users start conversations with disabled (deactivated) users.
Previously disactivated users chats become read-only and no one can write there. Now all that chats looks like regular chats.

**Comment by tmartincpp** [comment]
> My guess, that all that **invalid-room** and **invalid-user** could be related to #21237
> And could be caused with users start conversations with disabled (deactivated) users.
> Previously disactivated users chats become read-only and no one can write there. Now all that chats looks like regular chats.

In my case I'm 100% sure that it have nothing to do with disabled users; the issue appeared with active users.

**Comment by ankar84** [comment]
> In my case I'm 100% sure that it have nothing to do with disabled users; the issue appears with active users.
Yes, probably you are right. Did a few test with disabled user and didn't see something suspicious.

Can you share you experience in that problem? 
Maybe you have Steps to reproduce?

**Comment by battosai30** [comment]
Same issue here : fresh Debian machine, fresh install RC 3.16.3 and Keycloack OpenID connect
It leads to "invalid user" error when you try to direct message someone, and videocall doesn't work ("call already ended"). 
Regards

**Comment by tmartincpp** [comment]
> > In my case I'm 100% sure that it have nothing to do with disabled users; the issue appears with active users.
> > Yes, probably you are right. Did a few test with disabled user and didn't see something suspicious.
> 
> Can you share you experience in that problem?
> Maybe you have Steps to reproduce?

Please check my previous message: https://github.com/RocketChat/Rocket.Chat/issues/22256#issuecomment-874511533

Unfortunately I don't have any way to reproduce :|

**Comment by battosai30** [comment]
Same with LDAP auth backend on another fresh install (not done by me furthermore). It's working well when LDAP was not connected.
Clearly have an auth backend is the source of the issue.

**Comment by CvH** [comment]
We have the same problem but we use OAuth2 for SSO. Every user that start a pm to a use he never spoke before, the invalid user pops up and requires a refresh. That sounds like not a big deal, but if the target audience is not tech affine this is rather deal breaking because a core function is just not working. We have this problem at least since 3.14.x, it got worse with 3.15 if I remember correctly.

**Comment by AndreySemenov1** [comment]
Exactly the same error.

Chrome Dev Console:

```
TypeError: Cannot read property 'onDestroyed' of undefined at d.TemplateInstance. <anonymous>

Uncaught (in promise) {isClientSafe: true, error: "error-invalid-user", reason: "Invalid user", details: {…}, message: "Invalid user [error-invalid-user]",…}
details: {method: "createDirectMessage"}
error: "error-invalid-user"
errorType: "Meteor.Error"
isClientSafe: true
message: "Invalid user [error-invalid-user]"
reason: "Invalid user"
stack: "Error: Invalid user [error-invalid-user] \ n at M._livedata_result
__proto__: Error
clone: ƒ ()
constructor: ƒ ()
__proto__: Object
```

Also after refreshing (F5) with the {ROCKET_URL}/direct/ it works and opens the correct direct message channel.

**Comment by dougfabris** [comment]
> I can reproduce this error....
> 
> `Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]`
> 
> Steps to reproduce:
> 
> 1. Go to the directory
> 2. Click on the Users tab
> 3. Click on a user that I have never clicked on (or had a DM with) before
> 4. In this case, it tries to load the user using the /direct/{username} URL which throws the exception and then it creates a new room and opens it for the user and redirects to the /direct/{roomId} URL

Guys the PR-related and tests I ran, are considering the cases when opening a single DM or multiple DM for the first time. If there's a different behavior please let me know or raise another issue. Thanks a lot!

**Comment by ankar84** [comment]
> I can reproduce this error....
> 
> `Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]`
> 
> Steps to reproduce:
> 
> 1. Go to the directory
> 2. Click on the Users tab
> 3. Click on a user that I have never clicked on (or had a DM with) before
> 4. In this case, it tries to load the user using the /direct/{username} URL which throws the exception and then it creates a new room and opens it for the user and redirects to the /direct/{roomId} URL

That's all actually still an issue on most recent 4.4.0
But there is a room not found page in that case and normal DM after reload.

**Comment by mosynaq** [comment]
I have version 4.4.1 and the issue still persists.

**Comment by d3hof** [comment]
Still an Error in 3.18.5.
Oauth used for user login.
The first time you send a message to a user it shows Invalid-User.

**Comment by dougfabris** [comment]
Reopening to investigate!

**Comment by ankar84** [comment]
> Reopening to investigate!

Hey, @dougfabris Douglas!
Thank you for your interest to that issue. 
I think that all that logs errors can be related to tons of issues that was fixed by https://github.com/RocketChat/Rocket.Chat/pull/24955
But I'm can be wrong in that. 
I can tell it for sure when upgrade to 4.6.X and check logs if they have a lot of `Error: Invalid room [error-invalid-room]`

But to upgrade I need to wait a proxy fix https://github.com/RocketChat/Rocket.Chat/pull/25022

**Comment by seregasoft** [comment]
Getting crash when switching frequently between rooms or search for a user that you don't have an active direct conversation with.

Server: Docker 4.4.0
Client: WEB, Desktop 3.8.2

**Use REST instead of websocket for Meteor calls** disabled

DevTools errors:
```
TypeError: Cannot read properties of undefined (reading 'onDestroyed')
...

{isClientSafe: true, error: 'error-invalid-user', reason: 'Invalid user', details: {…}, message: 'Invalid user [error-invalid-user]', …}
details:
method: "createDirectMessage"
[[Prototype]]: Object
error: "error-invalid-user"
errorType: "Meteor.Error"
isClientSafe: true
message: "Invalid user [error-invalid-user]"
reason: "Invalid user"
stack: "Error: Invalid user [error-invalid-user] 
....
```

**Comment by ankar84** [comment]
> Server: Docker 4.4.0

Fixed in recent versions (4.5.2 I guess)

**Comment by seregasoft** [comment]
> > Server: Docker 4.4.0
> 
> Fixed in recent versions (4.5.2 I guess)

Thank you! After update server to latest 4.6.2 problem when "search for a user" is not reproduced anymore! But unfortunately 
 "switching frequently between rooms" still gives me this error.

**Comment by seregasoft** [comment]
> "switching frequently between rooms" still gives me this error.
Fixed in 4.7.1 for me.

**Comment by calebjacobson** [comment]
I am experiencing a similar issue on 4.8.3, though it is intermittent

### Steps to Reproduce:
1. send a direct message with a user (or users) for the first time (issue occurs intermittently whether using the web interface or using api/v1/chat.postMessage)
2. check rooms list - the direct message is added! though the error is thrown and no message appears in the room
3. check logs. What shows up when using the API is `Error: error-not-allowed at app/authorization/server/functions/canSendMessage.ts:26:9`

### Expected Behavior:
add the new room without error or give a more precise explanation as to why it could not send the message

### Actual Behavior
Room is added, no message is in the room, and an error is thrown (when using the web interface, "Error Not Allowed" shows up in red error bubble in the top right of the screen).

### Server Setup Information:
* Version of Rocket.Chat Server: 4.8.3
* Operating System: Ubuntu Server 18.04.3
* Deployment Method: bare metal (virtualized in a VMWare-like environment) with snap
* Number of Running instances: 1
* DB Replicaset Oplog: Enabled
* NodeJS version: 14.18.3
* MongoDB Version: 4.2.17 / wiredTiger

### Client Setup Information:
* Browser Version
* Operating System: Linux Mint 20.3
* LDAP is enabled

### Additional context
* Our rocket chat installation is being proxied through nginx for SSL termination, with rocketchat-caddy being disabled in snap.
* This issue started happing several months ago and is being increasingly reported by our users. We deployed a service that utilizes a bot user to send automated messages to our users (always in individual direct messages) and have been experiencing this error occasionally the bot user attempts to send messages. All errors occur when sending a message to a user the bot user has not messaged before, however, not all messages to new users from this bot user get an error response. Rooms are created when the bot user encounters this error, but the message it attempts to send does not appear in the room.
* Our users are set up and authenticated using LDAP

### Relevant Logs: `sudo journalctl -r -u snap.rocketchat-server.rocketchat-server | grep error-not-allowed`
```
Aug 15 12:16:58 <SERVER NAME REDACTED> rocketchat-server.rocketchat-server[8232]: {"level":35,"time":"2022-08-15T12:16:58.081Z","pid":8286,"hostname":"<SERVER NAME REDACTED>","name":"API","method":"POST","url":"/api/v1/chat.postMessage","userId":"<USER ID REDACTED>","userAgent":"axios/0.27.2","length":"247","host":"<HOST REDACTED>","remoteIP":"<IP REDACTED>","err":{"type":"Error","message":"error-not-allowed","stack":"Error: error-not-allowed\n    at app/authorization/server/functions/canSendMessage.ts:26:9\n    at /snap/rocketchat-server/1523/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/snap/rocketchat-server/1523/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at validateRoomMessagePermissions (app/authorization/server/functions/canSendMessage.ts:70:17)\n    at processWebhookMessage (app/lib/server/functions/processWebhookMessage.js:102:3)\n    at Object.post (app/api/server/v1/chat.js:162:26)\n    at app/api/server/api.js:431:96\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:431:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9"},"status":400,"responseTime":1100,"msg":"error-not-allowed"}
```

**Comment by ankar84** [comment]
we are on 5.3.5 now a I still get some invalid user and room errors
![image](https://user-images.githubusercontent.com/4023037/212237503-c7f767f4-65e4-4784-b194-d8f5654a15c9.png)

**Comment by RAurelian** [comment]
Same issue on v`6.4.5` (snap install):
![image](https://github.com/RocketChat/Rocket.Chat/assets/36531484/3d25c215-ab6f-402e-84fd-3088c2bff712)
