### ISSUE TITLE
Custom Oauth Error

### ISSUE THREAD

**Issue by joelchittum** [RocketChat/Rocket.Chat#22263]
Trying to implement a custom oauth 2 solution but am receiving an error and I am curious how to get more information about the error that is being thrown.  

"No matching login attempt found" is the error I am receiving and the logs from rocket chat docker container are as follows: SyncedCron ➔ info Starting "Generate download files for user data".
SyncedCron ➔ info Finished "Generate download files for user data".
SyncedCron ➔ info Starting "Generate download files for user data".
SyncedCron ➔ info Finished "Generate download files for user data".
API ➔ debug POST: /api/v1/method.callAnon/login
Exception while invoking method login Error: No matching login attempt found [145546287]
    at MethodInvocation.<anonymous> (packages/accounts-oauth/oauth_server.js:35:21)
    at packages/accounts-base/accounts_server.js:499:31
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1341:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:497:22)
    at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:557:31)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:263:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:263:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
API ➔ debug Success {
  statusCode: 200,
  body: {
    message: '{"msg":"result","id":"48","error":{"isClientSafe":true,"error":145546287,"reason":"No matching login attempt found","message":"No matching login attempt found [145546287]","errorType":"Meteor.Error"}}',
    success: true
  }
}

Is there an error log that I can look at to get a more detailed error?

**Comment by johncrisp** [comment]
Hi

THis repo is for actual bugs in Rocket.Chat

Please make sure you use a bug template when reporting issues.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

However, this seems to be a support request rather than a bug.

For general support please ask in https://forums.rocket.chat or https://open.rocket.chat # support

Thanks.
