### ISSUE TITLE
Docker Image for 3.14.5 published as :latest after 3.15.0 Causes Problems

### ISSUE THREAD

**Issue by LeeThompson** [RocketChat/Rocket.Chat#22269]
[RocketChat](https://registry.hub.docker.com/r/rocketchat/rocket.chat/) pushed 3.14.5 update as rocketchat:latest (10 days after 3.15.0)

If Docker containers are automatically updated, this cases RocketChat to break.

Fix: Don't push maintenance point releases as :latest without having having it be able to downgrade the database too.

```
Exception in callback of async function: errorClass [Error]: [Can't find migration version 225]                                                           
    at Object.Migrations._findIndexByVersion (app/migrations/server/migrations.js:403:8)                                                                  
    at Object.Migrations._migrateTo (app/migrations/server/migrations.js:254:24)                                                                          
    at Object.Migrations.migrateTo (app/migrations/server/migrations.js:179:20)                                                                           
    at module (server/startup/migrations/xrun.js:6:13)                                                                                                    
    at fileEvaluate (packages/modules-runtime.js:336:7)                                                                                                   
    at Module.require (packages/modules-runtime.js:238:14)                                                                                                
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)            
    at module (server/startup/migrations/index.js:1:4870)                                                                                                 
    at fileEvaluate (packages/modules-runtime.js:336:7)                                                                                                   
    at Module.require (packages/modules-runtime.js:238:14)                                                                                                
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)            
    at module (server/main.js:1:210)                                                                                                                      
    at fileEvaluate (packages/modules-runtime.js:336:7)                                                                                                   
    at Module.require (packages/modules-runtime.js:238:14)                                                                                                
    at require (packages/modules-runtime.js:258:21)                                                                                                       
    at /app/bundle/programs/server/app/app.js:202236:15                                                                                                   
    at /app/bundle/programs/server/boot.js:401:38                                                                                                         
    at Array.forEach (<anonymous>)                                                                                                                        
    at /app/bundle/programs/server/boot.js:226:21                                                                                                         
    at /app/bundle/programs/server/boot.js:464:7                                                                                                          
    at Function.run (/app/bundle/programs/server/profile.js:280:14)                                                                                       
    at /app/bundle/programs/server/boot.js:463:13 {                                                                                                       
  isClientSafe: true,                                                                                                                                     
  error: "Can't find migration version 225",                                                                                                              
  reason: undefined,                                                                                                                                      
  details: undefined,                                                                                                                                     
  errorType: 'Meteor.Error'                    
```

### Server Setup Information:

- Version of Rocket.Chat Server:  3.15.0
- Operating System: Debian (Linux 3.10.105) (Synology)
- Deployment Method: docker
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1
- MongoDB Version: 4.4.6 / wiredTiger (oplog Enabled)
- Database Migration: 225

**Comment by LeeThompson** [comment]
Rebuilt the container using the 3.15.0 image and back up and running.

I understand the need to do maintenance releases of older branches but please don't make the main latest branch go backwards (at least without very good reason and have it handle the database side).

**Comment by johncrisp** [comment]
Yes, sorry that this happened.

This was previously reported and fixed

https://github.com/RocketChat/Rocket.Chat/issues/22261#issuecomment-855855110

It is best to use a fixed version and only upgrade as you require.
