### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#2230]
Yahoo! I love the new import feature.
The import works fine on some channels but it'll fail on my very large ones

Here is a snipped of the logs during the import failure

```
I20160215-21:31:13.567(0) Uploading the file Screenshot_2015-04-08-18-07-52.png from https://files.slack.com/files-pri/T02LKC3LA-F04B96U8R/download/screenshot_2015-04-08-18-07-52.png?t=xoxe-2699411690-21488379302-21488379350-2f1faa2a60. 
I20160215-21:31:15.293(0) { '0':     { _id: 'ZXNTFWYnBAjvNhcjR',      name: 'Screenshot_2015-04-08-18-07-52.png',      size: 447466,      type: 'image/png',      rid: 'GENERAL',      store: 'rocketchat_uploads',      complete: true,      extension: 'png',      progress: 1,      uploading: false,      userId: 'CtBNHfCqpg5LGvSv6',      identify: { format: 'PNG', size: [Object] },      token: 'D9EA9B68C9',      uploadedAt: Mon Feb 15 2016 21:31:15 GMT+0000 (UTC),      url: 'https://mrplow.work:3002/ufs/rocketchat_uploads/ZXNTFWYnBAjvNhcjR/Screenshot_2015-04-08-18-07-52.png' } } 
I20160215-21:31:15.682(0) Uploading the file Screenshot_2015-04-08-22-28-52.png from https://files.slack.com/files-pri/T02LKC3LA-F04AP5A2S/download/screenshot_2015-04-08-22-28-52.png?t=xoxe-2699411690-21488379302-21488379350-2f1faa2a60. 
I20160215-21:31:15.953(0) Uploading the file Screenshot_2014-10-25-02-07-23.png from https://files.slack.com/files-pri/T02LKC3LA-F02RN15CW/download/screenshot_2014-10-25-02-07-23.png?t=xoxe-2699411690-21488379302-21488379350-2f1faa2a60. 
I20160215-21:31:16.073(0) { '0':     { _id: 'qMjgrfZe6ZxEARCuq',      name: 'IMG_4679.jpg',      size: 4650552,      type: 'image/jpeg',      rid: 'GENERAL',      store: 'rocketchat_uploads',      complete: true,      extension: 'jpg',      progress: 1,      uploading: false,      userId: 'CtBNHfCqpg5LGvSv6',      identify: { format: 'JPEG', size: [Object] },      token: '18a82A287A',      uploadedAt: Mon Feb 15 2016 21:31:16 GMT+0000 (UTC),      url: 'https://mrplow.work:3002/ufs/rocketchat_uploads/qMjgrfZe6ZxEARCuq/IMG_4679.jpg' } } 
I20160215-21:31:16.111(0) { '0':     { _id: '9k9PL9dgs2z6GDY6o',      name: 'IMG_20150809_085558.jpg',      size: 822349,      type: 'image/jpeg',      rid: 'GENERAL',      store: 'rocketchat_uploads',      complete: true,      extension: 'jpg',      progress: 1,      uploading: false,      userId: 'CtBNHfCqpg5LGvSv6',      identify: { format: 'JPEG', size: [Object] },      token: 'fBc80a2acB',      uploadedAt: Mon Feb 15 2016 21:31:16 GMT+0000 (UTC),      url: 'https://mrplow.work:3002/ufs/rocketchat_uploads/9k9PL9dgs2z6GDY6o/IMG_20150809_085558.jpg' } } 
I20160215-21:31:16.203(0) Uploading the file Screenshot_2014-10-24-22-54-33.png from https://files.slack.com/files-pri/T02LKC3LA-F02RLPY7Z/download/screenshot_2014-10-24-22-54-33.png?t=xoxe-2699411690-21488379302-21488379350-2f1faa2a60. 
I20160215-21:31:16.411(0) Uploading the file Screenshot_2014-10-25-07-28-42.png from https://files.slack.com/files-pri/T02LKC3LA-F02RM7143/download/screenshot_2014-10-25-07-28-42.png?t=xoxe-2699411690-21488379302-21488379350-2f1faa2a60. 
I20160215-21:31:16.704(0) Uploading the file Screenshot_2014-10-25-21-37-43.png from https://files.slack.com/files-pri/T02LKC3LA-F02RPVA5A/download/screenshot_2014-10-25-21-37-43.png?t=xoxe-2699411690-21488379302-21488379350-2f1faa2a60. 
I20160215-21:31:16.773(0) Slack is now at importer_import_failed. 
I20160215-21:31:16.791(0) Exception in defer callback: Error: import-slack-error     at packages/rocketchat_importer-slack/server/SlackImporter.coffee:276:15     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at packages/meteor/timers.js:6:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1) 
I20160215-21:31:17.115(0) { '0':     { _id: 'AADoBTqJKzu9kcczd',      name: 'Screenshot_2015-04-08-22-28-52.png',      size: 202772,      type: 'image/png',      rid: 'GENERAL',      store: 'rocketchat_uploads',      complete: true,      extension: 'png',      progress: 1,      uploading: false,      userId: 'CtBNHfCqpg5LGvSv6',      identify: { format: 'PNG', size: [Object] },      token: '28397bD919',      uploadedAt: Mon Feb 15 2016 21:31:17 GMT+0000 (UTC),      url: 'https://mrplow.work:3002/ufs/rocketchat_uploads/AADoBTqJKzu9kcczd/Screenshot_2015-04-08-22-28-52.png' } } 
I20160215-21:31:19.253(0) { '0':     { _id: 'aTRGxqsnjuCimxqXS',      name: 'Screenshot_2014-10-25-07-28-42.png',      size: 1186874,      type: 'image/png',      rid: 'GENERAL',      store: 'rocketchat_uploads',      complete: true,      extension: 'png',      progress: 1,      uploading: false,      userId: 'CtBNHfCqpg5LGvSv6',      identify: { format: 'PNG', size: [Object] },      token: 'F90ba90b4A',      uploadedAt: Mon Feb 15 2016 21:31:19 GMT+0000 (UTC),      url: 'https://mrplow.work:3002/ufs/rocketchat_uploads/aTRGxqsnjuCimxqXS/Screenshot_2014-10-25-07-28-42.png' } } 
I20160215-21:31:19.417(0) { '0':     { _id: 'SPMsQ7S2GtK6nLbej',      name: 'Screenshot_2014-10-25-02-07-23.png',      size: 1862996,      type: 'image/png',      rid: 'GENERAL',      store: 'rocketchat_uploads',      complete: true,      extension: 'png',      progress: 1,      uploading: false,      userId: 'CtBNHfCqpg5LGvSv6',      identify: { format: 'PNG', size: [Object] },      token: '4BFAf8586a',      uploadedAt: Mon Feb 15 2016 21:31:19 GMT+0000 (UTC),      url: 'https://mrplow.work:3002/ufs/rocketchat_uploads/SPMsQ7S2GtK6nLbej/Screenshot_2014-10-25-02-07-23.png' } } 
I20160215-21:31:19.487(0) { '0':     { _id: 'Lg4nsTSzJk4bZo9GC',      name: 'Screenshot_2014-10-25-21-37-43.png',      size: 724936,      type: 'image/png',      rid: 'GENERAL',      store: 'rocketchat_uploads',      complete: true,      extension: 'png',      progress: 1,      uploading: false,      userId: 'CtBNHfCqpg5LGvSv6',      identify: { format: 'PNG', size: [Object] },      token: '4B195A689A',      uploadedAt: Mon Feb 15 2016 21:31:19 GMT+0000 (UTC),      url: 'https://mrplow.work:3002/ufs/rocketchat_uploads/Lg4nsTSzJk4bZo9GC/Screenshot_2014-10-25-21-37-43.png' } } 
I20160215-21:31:20.417(0) { '0':     { _id: 'aSQmPXxnQydRTM3FK',      name: 'Screenshot_2014-10-24-22-54-33.png',      size: 3419889,      type: 'image/png',      rid: 'GENERAL',      store: 'rocketchat_uploads',      complete: true,      extension: 'png',      progress: 1,      uploading: false,      userId: 'CtBNHfCqpg5LGvSv6',      identify: { format: 'PNG', size: [Object] },      token: '5AF98a1Bd9',      uploadedAt: Mon Feb 15 2016 21:31:20 GMT+0000 (UTC),      url: 'https://mrplow.work:3002/ufs/rocketchat_uploads/aSQmPXxnQydRTM3FK/Screenshot_2014-10-24-22-54-33.png' } } 
```

**Comment by graywolf336** [comment]
@RocketChat/core There is currently a try/catch inside the import, but the exception which should be catch isn't in the detail. Can someone look at the code and see why that is the case?

**Comment by graywolf336** [comment]
@mrplow How big of a file is your import? Just curious

**Comment by sampaiodiego** [comment]
I got some import errors during my tests.. The only way I could find any information about the error was looking at the database record. 
@mrplow have you checked the database? `rocketchat_imports` collection. also are you trying to import the whole file or just some users/channels? is it a clean database?

**Comment by mrplow** [comment]
@graywolf336 its a big boy, 8.6mb

@sampaiodiego it is a clean dbase, importing the entire list, skipping closed users and archived channels. I'll try checking the dbase when I get home
I'm not exactly sure how to check the database but I'll see what I can do when I'm home from work.

I've just been waiting for this for a while so I had to give it a quick try during my lunch break.

The chat is kinda sensitive so I can't share the entire export, but I could share the last day's for the channel it gets stuck on. What I mean is the last imported messages for one channel is aug 8th, so I could share aug 8th and 9th's json for that channel if it would help.

**Comment by mrplow** [comment]
This could help
Rocket.Chat Hash 1d574de7522c5a44f0c2be6ee2b83d438944b780

`> db.rocketchat_import.find().pretty()
{
	"_id" : "Cs4ea479iHiru5Xu5",
	"type" : "Slack",
	"ts" : 1455606612784,
	"status" : "importer_import_cancelled",
	"valid" : false,
	"user" : "4KdncZ5i8tGuwLT4u",
	"file" : "Van Island Community Resistance Slack export Feb 15 2016.zip",
	"count" : {
		"users" : 201,
		"total" : 90853,
		"channels" : 24,
		"messages" : 90628,
		"completed" : 1500
	},
	"messagesstatus" : "complaint-department/2015-01-11.6",
	"failed" : true,
	"error" : {
		
	}
}
{
	"_id" : "YP3TXpcKSHzXCNRmr",
	"type" : "Slack",
	"ts" : 1455606832346,
	"status" : "importer_new",
	"valid" : true,
	"user" : "4KdncZ5i8tGuwLT4u"
}
>`

`I20160216-07:13:52.198(0) Slack is now at importer_import_failed. 
I20160216-07:13:52.232(0) Exception in defer callback: Error: import-slack-error     at packages/rocketchat_importer-slack/server/SlackImporter.coffee:276:15     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at packages/meteor/timers.js:6:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1) 
I20160216-07:13:52.340(0) Slack is now at importer_import_cancelled.`

**Comment by mrplow** [comment]
skipping the failing channel and starting with a fresh db I hit another wall

```
> db.rocketchat_import.find().pretty()
{
	"_id" : "vJiG6ta9sCWTchDTo",
	"type" : "Slack",
	"ts" : 1455607393479,
	"status" : "importer_import_cancelled",
	"valid" : false,
	"user" : "SmKkBJjZf6aGLjhvM",
	"file" : "Van Island Community Resistance Slack export Feb 15 2016.zip",
	"count" : {
		"users" : 201,
		"total" : 90853,
		"channels" : 24,
		"messages" : 90628,
		"completed" : 500
	},
	"messagesstatus" : "faction-comms-4_1/2014-10-25.57",
	"failed" : true,
	"error" : {
		
	}
}
```

```
I20160216-07:28:23.131(0) Slack is now at importer_import_failed. 
I20160216-07:28:23.171(0) Exception in defer callback: Error: import-slack-error     at packages/rocketchat_importer-slack/server/SlackImporter.coffee:276:15     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at packages/meteor/timers.js:6:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1) 
```

If I skip those two channels the import completes

**Comment by mrplow** [comment]
Here is the entire contents of complaint-department/2015-01-11.json

```
[
    {
        "user": "U03B5MF3Z",
        "type": "message",
        "subtype": "channel_join",
        "text": "<@U03B5MF3Z|viridae> has joined the channel",
        "ts": "1420964603.000010"
    },
    {
        "user": "U02QZS0P8",
        "type": "message",
        "subtype": "channel_join",
        "text": "<@U02QZS0P8|starstonight> has joined the channel",
        "ts": "1420973383.000011"
    },
    {
        "type": "message",
        "subtype": "file_share",
        "text": "A file was shared",
        "file": null,
        "upload": false,
        "ts": "1421039370.000012"
    },
    {
        "type": "message",
        "subtype": "file_comment",
        "text": "A file was commented on",
        "file": null,
        "comment": null,
        "ts": "1421039542.000013"
    },
    {
        "type": "message",
        "user": "U02MHAD5S",
        "text": "Its not loading for me. Do I get a hint?",
        "ts": "1421039618.000014"
    },
    {
        "type": "message",
        "user": "U02QXRDSP",
        "text": "<@U02MHAD5S>: yah its like to big a file its like 8 mb.. maybe I better convert it to a better file ext...",
        "ts": "1421039728.000015"
    }
]
```

**Comment by graywolf336** [comment]
Ah I see the issue, a file was shared but the file details are null. I'll
fix that, thanks!

**Comment by mrplow** [comment]
Thanks so much @graywolf336 
```
> db.rocketchat_import.find().pretty()
{
        "_id" : "tRXRuZhkCGrkh4nLu",
        "type" : "Slack",
        "ts" : 1455644029501,
        "status" : "importer_done",
        "valid" : true,
        "user" : "62d2w9R3mdBMHiyM8",
        "file" : "Van Island Community Resistance Slack export Feb 15 2016.zip",
        "count" : {
                "users" : 201,
                "total" : 90853,
                "channels" : 24,
                "messages" : 90628,
                "completed" : 90500
        },
        "messagesstatus" : "music/2015-12-27.1"
}
>
```

**Comment by graywolf336** [comment]
:+1:
