### ISSUE TITLE
Livechat message size seems limited on 0 chars

### ISSUE THREAD

**Issue by zigichrigi** [RocketChat/Rocket.Chat#22356]
### Description:

Livechat client cant write messages.

### Steps to reproduce:

1. Click on livechat button
2. Start typing (counter underneath the textbox increases, it says for example 1 / 5000) and press enter.
3. Message isn't sent and an error message appears "message-length-exceeds-character-limit". So the client isn't able to send one single letter!

### Expected behavior:

As long as the counter is below its maximum, the message should be accepted.

### Actual behavior:

The client can't send any messages.

Before clicking on send button:
![grafik](https://user-images.githubusercontent.com/85927231/122012980-0669a800-cdbe-11eb-9bf8-8f54e4c31db5.png)

After clicking on send button:
![grafik](https://user-images.githubusercontent.com/85927231/122013123-2ac58480-cdbe-11eb-96f3-e2335e1c7be7.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Debian 10
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: (what do I have to provide here?)
- NodeJS Version: v12.22.1
- MongoDB Version:4.4.6 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: 78.11.0esr (64-Bit)
- Operating System: Debian 10

### Relevant logs:

Jun 15 09:43:07 rocket1 rocketchat[32275]: API ➔ debug POST: /api/v1/livechat/message
Jun 15 09:43:07 rocket1 rocketchat[32275]: API ➔ debug Failure {
Jun 15 09:43:07 rocket1 rocketchat[32275]:   statusCode: 400,
Jun 15 09:43:07 rocket1 rocketchat[32275]:   body: errorClass [Error]: [message-length-exceeds-character-limit]
Jun 15 09:43:07 rocket1 rocketchat[32275]:       at Object.post (app/livechat/server/api/v1/message.js:45:11)
Jun 15 09:43:07 rocket1 rocketchat[32275]:       at app/api/server/api.js:394:82
Jun 15 09:43:07 rocket1 rocketchat[32275]:       at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Jun 15 09:43:07 rocket1 rocketchat[32275]:       at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
Jun 15 09:43:07 rocket1 rocketchat[32275]:       at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Jun 15 09:43:07 rocket1 rocketchat[32275]:       at packages/nimble_restivus/lib/route.coffee:59:33
Jun 15 09:43:07 rocket1 rocketchat[32275]:       at packages/simple_json-routes.js:98:9 {
Jun 15 09:43:07 rocket1 rocketchat[32275]:     isClientSafe: true,
Jun 15 09:43:07 rocket1 rocketchat[32275]:     error: 'message-length-exceeds-character-limit',
Jun 15 09:43:07 rocket1 rocketchat[32275]:     reason: undefined,
Jun 15 09:43:07 rocket1 rocketchat[32275]:     details: undefined,
Jun 15 09:43:07 rocket1 rocketchat[32275]:     errorType: 'Meteor.Error',
Jun 15 09:43:07 rocket1 rocketchat[32275]:     success: false
Jun 15 09:43:07 rocket1 rocketchat[32275]:   }
Jun 15 09:43:07 rocket1 rocketchat[32275]: }

**Comment by KevLehman** [comment]
This pull request has been inactive for a while, so we’re closing it to keep the backlog manageable.
If you’d like to continue working on it, feel free to reopen or submit a new PR. Thanks for the contribution!
