### ISSUE TITLE
Custom sounds won't play if used custom-sound folder on rocket chat.

### ISSUE THREAD

**Issue by Resident1981** [RocketChat/Rocket.Chat#22428]
Rocket chat server 3.15.0
node v12.22.1
db version v4.0.23
OS: CentOS Linux 7 (Core)
Built-in sounds work fine.
Permit: drwxr-xr-x 2 rocketchat rocketchat 4,0K jun 18 15:50 UserSounds
Error when try to listen:
---------
Exception in callback of async function: TypeError [ERR_HTTP_INVALID_HEADER_VALUE] [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Type" at ServerResponse.setHeader (_http_outgoing.js:533:3) at ServerResponse.res.setHeader (/home/rocketchat/RocketChatServer/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect/lib/patch.js:132:22) at app/custom-sounds/server/startup/custom-sounds.js:75:7 at runWithEnvironment (packages/meteor.js:1286:24) at packages/meteor.js:1299:14 at /home/rocketchat/RocketChatServer/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 { code: 'ERR_HTTP_INVALID_HEADER_VALUE' }
--------
The emoji are okay.

**Comment by johncrisp** [comment]
Hi,

you are going to have give us some more detail.

I suspect we'll need to know more about your proxy setup and websockets

**Comment by Resident1981** [comment]
Ok.
Reverse proxy nginx. But I tried to connect to port 3000 without it and the problem still remained. Nothing changed.

**Comment by Resident1981** [comment]
Well. I guess this is just my problem. Everyone else works fine.....
