### ISSUE TITLE
Outbound integration channel_id incorrect

### ISSUE THREAD

**Issue by mosskin-woast** [RocketChat/Rocket.Chat#22477]
### Description:

Outbound integration requests for messages sent in direct chats contain an unusable `channel_id`.

### Steps to reproduce:

1. Enable an outbound integration for `all_direct_messages`.
2. Send a message in a direct chat
3. Observe the payload sent by the integration - esp. the `channel_id` parameter. Example:
```json
{ "bot":false, "channel_id": "97wAfJEuMGc5iDPZ2vrByxjuPoWLJS8EaB" "user_id": "97wAfJEuMGc5iDPZ2", "user_name": "mossy", "text": "Hiya" }
```
4. Attempt to use the `channel_id` from this payload in another API call, such as `/api/v1/channels.members?roomId=97wAfJEuMGc5iDPZ2vrByxjuPoWLJS8EaB`. The room ID is reported as invalid.
Example:
```json
{
    "success": false,
    "error": "The required \"roomId\" or \"roomName\" param provided does not match any channel [error-room-not-found]",
    "errorType": "error-room-not-found"
}
```

### Expected behavior:

The `channel_id` from the webhook payload should be usable to retrieve the channel of the direct chat message.

### Actual behavior:

The `channel_id` is invalid.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: Whatever the [docker image](https://hub.docker.com/_/rocket-chat) uses, the host is Arch Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled (I don't know what this means)
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.25 / mmapv1 (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: API issue
- Operating System: Arch Linux

### Relevant logs:

```
Exception while invoking method getRoomByTypeAndName Error: Invalid room [error-invalid-room]     at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:51:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
```

**Comment by caesarcxiv** [comment]
We have the same issue with slack (same configuration) - also receive 3 push notifications for each slack connected channel that depletes our monthly allocation. Maybe issues are connected.
