### ISSUE TITLE
How to Handle Open Sessions When Agent Goes Offline - Not Working

### ISSUE THREAD

**Issue by alexmontoanelli** [RocketChat/Rocket.Chat#22505]
### Description:

If this settings is set to 'forward' the rocket wont forward the user to another agent ...

### Steps to reproduce:

1. Set "How to Handle Open Sessions When Agent Goes Offline" at Settings -> OmniChannel -> Sessions to "Forward"
2. Get 2 agents on a department
3. Get a new visitor
4. The agent that take that chat must goes offline - close RocketChat page
5. After the specified timeout nothing hapend.

### Expected behavior:

At step 5, we expected that the visitor are forward back to the original queue or to a new agent.

### Actual behavior:

At step 5, the chat/visitor are not forward

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System:  Linux/Debian 10
- Deployment Method: Docker
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: Brave V1.26.67
- Operating System: MAC Os

### Relevant logs:

![image](https://user-images.githubusercontent.com/4535817/123795944-f1f7d600-d8ba-11eb-9507-6ad74dc09fee.png)

rocketchat_1          | errorClass [Error]: The selected department and the current room department are the same [error-forwarding-chat-same-department]
rocketchat_1          |     at app/livechat/server/lib/Helper.js:359:9
rocketchat_1          |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
rocketchat_1          |   isClientSafe: true,
rocketchat_1          |   error: 'error-forwarding-chat-same-department',
rocketchat_1          |   reason: 'The selected department and the current room department are the same',
rocketchat_1          |   details: { function: 'forwardRoomToDepartment' },
rocketchat_1          |   errorType: 'Meteor.Error'
rocketchat_1          | }

**Comment by johncrisp** [comment]
Can you have a look if this has anything to do with it?

https://github.com/RocketChat/Rocket.Chat/pull/22584

Also check the 3.16.2 release notes and try testing on this verson:

https://github.com/RocketChat/Rocket.Chat/pull/22607

Please let us know if this is still an issue.
