### ISSUE TITLE
Report conflicting email address while doing LDAP sync

### ISSUE THREAD

**Issue by frlan** [RocketChat/Rocket.Chat#22601]
### Description:

When trying to import users from LDAP we from time to time see errors like that:

```
Jul 07 09:33:15 rocketchatserver rocketchat[704]: server.js:204 LDAPSync ➔ error Error creating user errorClass [Error]: Email already exists. [403]
Jul 07 09:33:15 rocketchatserver rocketchat[704]:     at handleError (packages/accounts-password/password_server.js:110:17)
Jul 07 09:33:15 rocketchatserver rocketchat[704]:     at checkForCaseInsensitiveDuplicates (packages/accounts-password/password_server.js:257:7)
Jul 07 09:33:15 rocketchatserver rocketchat[704]:     at createUser (packages/accounts-password/password_server.js:1130:3)
Jul 07 09:33:15 rocketchatserver rocketchat[704]:     at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1218:10)
Jul 07 09:33:15 rocketchatserver rocketchat[704]:     at addLdapUser (app/ldap/server/sync.js:477:29)
Jul 07 09:33:15 rocketchatserver rocketchat[704]:     at app/ldap/server/sync.js:543:5
Jul 07 09:33:15 rocketchatserver rocketchat[704]:     at Array.forEach (<anonymous>)
Jul 07 09:33:15 rocketchatserver rocketchat[704]:     at app/ldap/server/sync.js:510:13
Jul 07 09:33:15 rocketchatserver rocketchat[704]:     at runWithEnvironment (packages/meteor.js:1286:24) {
Jul 07 09:33:15 rocketchatserver rocketchat[704]:   isClientSafe: true,
Jul 07 09:33:15 rocketchatserver rocketchat[704]:   error: 403,
Jul 07 09:33:15 rocketchatserver rocketchat[704]:   reason: 'Email already exists.',
Jul 07 09:33:15 rocketchatserver rocketchat[704]:   details: undefined,
Jul 07 09:33:15 rocketchatserver rocketchat[704]:   errorType: 'Meteor.Error'
Jul 07 09:33:15 rocketchatserver rocketchat[704]: }
```

### Steps to reproduce:

1. Have an email used more than one in LDAP
2. Performa a LDAP-sync

### Expected behavior:

At least printing out in error log which user is conflicting (or which email)

### Actual behavior:

Sync silently not finishing

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by johncrisp** [comment]
Hi and thanks for reporting this - can you please follow the issue template guidelines and test this on the latest version?

It may well not be fixed but we need to check.
