### ISSUE TITLE
3.16.3 not working at all

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat#22658]
### Description:

The security hotfix version 3.16.3 does not start at all, throwing errors. Downgrade to 3.16.2 fortunately works.

### Steps to reproduce:

1. Update from 3.16.2 to 3.16.3 following the official procedure
2. RS does not start, throwing a couple of errors (see below)

### Expected behavior:

3.16.3 should start and work

### Actual behavior:

3.16.3 throws a bunch of errors in syslog and is not starting:

```
Jul 13 18:32:15 jaychat rocketchat[936706]: Not migrating, control is locked. Attempt 15/30. Trying again in 10 seconds.
Jul 13 18:32:25 jaychat rocketchat[936706]: Not migrating, control is locked. Attempt 16/30. Trying again in 10 seconds.
Jul 13 18:32:35 jaychat rocketchat[936706]: Not migrating, control is locked. Attempt 17/30. Trying again in 10 seconds.
Jul 13 18:32:45 jaychat rocketchat[936706]: Not migrating, control is locked. Attempt 18/30. Trying again in 10 seconds.
Jul 13 18:32:55 jaychat rocketchat[936706]: Not migrating, control is locked. Attempt 19/30. Trying again in 10 seconds.
Jul 13 18:32:55 jaychat rocketchat[936706]: Exception in callback of async function: errorClass [Error]: [Can't find migration version 226]
Jul 13 18:32:55 jaychat rocketchat[936706]:     at Object.Migrations._findIndexByVersion (app/migrations/server/migrations.js:403:8)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at Object.Migrations._migrateTo (app/migrations/server/migrations.js:254:24)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at Object.Migrations.migrateTo (app/migrations/server/migrations.js:179:20)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at module (server/startup/migrations/xrun.js:6:13)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at Module.require (packages/modules-runtime.js:238:14)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at module (server/startup/migrations/index.js:1:4936)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at Module.require (packages/modules-runtime.js:238:14)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at module (server/main.js:1:210)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at Module.require (packages/modules-runtime.js:238:14)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at require (packages/modules-runtime.js:258:21)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at /opt/Rocket.Chat/programs/server/app/app.js:203071:15
Jul 13 18:32:55 jaychat rocketchat[936706]:     at /opt/Rocket.Chat/programs/server/boot.js:401:38
Jul 13 18:32:55 jaychat rocketchat[936706]:     at Array.forEach (<anonymous>)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at /opt/Rocket.Chat/programs/server/boot.js:226:21
Jul 13 18:32:55 jaychat rocketchat[936706]:     at /opt/Rocket.Chat/programs/server/boot.js:464:7
Jul 13 18:32:55 jaychat rocketchat[936706]:     at Function.run (/opt/Rocket.Chat/programs/server/profile.js:280:14)
Jul 13 18:32:55 jaychat rocketchat[936706]:     at /opt/Rocket.Chat/programs/server/boot.js:463:13 {
Jul 13 18:32:55 jaychat rocketchat[936706]:   isClientSafe: true,
Jul 13 18:32:55 jaychat rocketchat[936706]:   error: "Can't find migration version 226",
Jul 13 18:32:55 jaychat rocketchat[936706]:   reason: undefined,
Jul 13 18:32:55 jaychat rocketchat[936706]:   details: undefined,
Jul 13 18:32:55 jaychat rocketchat[936706]:   errorType: 'Meteor.Error'
Jul 13 18:32:55 jaychat rocketchat[936706]: }
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.2
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.25

### Client Setup Information

Irrelevant

**Comment by sampaiodiego** [comment]
we had a small window where `latest` version were not matching the correct "latest" version, which was either 3.16.2 or 3.16.3 .. now everything it good.. you can update to latest and you'll correctly receive 3.16.3. thx for letting us know
