### ISSUE TITLE
Issues with new docker/docker-compose first install

### ISSUE THREAD

**Issue by r3k2** [RocketChat/Rocket.Chat#22702]
Hello I am following this official setup https://docs.rocket.chat/installing-and-updating/docker-containers
everything seems ok until I try to go to the url and create an admin account, it will just hang forever and on the nginx logs it says it timedout... 

```
 tail -f rocketchat_error.log 
2021/07/19 16:55:58 [error] 7329#7329: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 213.xx.xx.xx, server: chat.xxxxxx.com, request: "POST /api/v1/method.callAnon/registerUser HTTP/1.1", upstream: "http://127.0.0.1:3000/api/v1/method.callAnon/registerUser", host: "chat.xxxxxx.com", referrer: "https://chat.xxxxxxx.com/setup-wizard/1"
```
docker ps
```
docker ps
CONTAINER ID   IMAGE                                                COMMAND                  CREATED         STATUS                          PORTS                                       NAMES
8682114feb1b   rocketchat/hubot-rocketchat:latest                   "/bin/sh -c 'node -e…"   7 minutes ago   Restarting (1) 57 seconds ago                                               opt_hubot_1
368c7ea41010   registry.rocket.chat/rocketchat/rocket.chat:latest   "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes                    0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   opt_rocketchat_1
91b31e9d5b63   mongo:4.0                                            "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes                    27017/tcp                                   opt_mongo_1
```

on a netstat I do not see mongo port listening on 127.0.0.1 ..... could this be the issue?
I have not change anything only where I am supposed to add my domain on the docker compose yaml file.

[edit]
```
docker ps --format "{{.Ports}}"

0.0.0.0:3000->3000/tcp, :::3000->3000/tcp
27017/tcp
```

[edit 2]
```
rocketchat_1          | ➔ +----------------------------------------------------+
rocketchat_1          | Error: Connection timeout
rocketchat_1          |     at SMTPConnection._formatError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
rocketchat_1          |     at SMTPConnection._onError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
rocketchat_1          |     at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:235:22)
rocketchat_1          |     at listOnTimeout (internal/timers.js:554:17)
rocketchat_1          |     at processTimers (internal/timers.js:497:7) {
rocketchat_1          |   code: 'ETIMEDOUT',
rocketchat_1          |   command: 'CONN'
rocketchat_1          | }
```

**Comment by johncrisp** [comment]
Hi,

github is for errors and breakages, not general setup and support, and there is no evidence of that here.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

https://rocket.chat/docs/contributing/reporting-issues

https://rocket.chat/docs/getting-support

Quick tips.

Note you need to set up the root url correctly - not localhost, either disable 2FA or set your mail server up correctly, and your  rocket instance will listen on http:3000 

For apps make sure you have a web proxy running + https.

Please ask your question in https://forums.rocket.chat or https://open.rocket.chat
