### ISSUE TITLE
Custom OAuth keycloak redirect URI not correctly generated.

### ISSUE THREAD

**Issue by maudrid** [RocketChat/Rocket.Chat#22858]
### Description:

When configuring RocketChat to use keycloak using custom OAuth configuration and rocketChat is configured to run on a sub path (example http://testserver/chat) instead of on the root path, login fails because of an error raised by keycloak.
The error log from RocketChat is as follows:
```
Exception while invoking method login Error: Failed to complete OAuth handshake with keycloak at http://testserver/iam/auth/realms/Affectli/protocol/openid-connect/token. failed [400] {"error":"invalid_grant","error_description":"Incorrect redirect_uri"}
    at CustomOAuth.getAccessToken (app/custom-oauth/server/custom_oauth_server.js:148:18)
    at Object.handleOauthRequest (app/custom-oauth/server/custom_oauth_server.js:205:26)
    at OAuth._requestHandlers.<computed> (packages/oauth2/oauth2_server.js:10:33)
    at middleware (packages/oauth/oauth_server.js:170:5)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:263:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
```
The reason that keycloak returns `Incorrect redirect_uri` is because the redirect URI sent in the `../token` request does not match the redirect URI sent in the previous `.../auth` request.
I captured the requests in my reverse proxy log. and they look as follows:
For .../auth : `redirect_uri=http%3A%2F%2Ftestserver%2Fchat%2F_oauth%2Fkeycloak`
For .../token : `redirect_uri=http%3A%2F%2Ftestserver%2F_oauth%2Fkeycloak`
The difference is that .../auth includes the **/chat** sub-path and .../token **does not**.

The following are my configuration settings:

```
      - ROOT_URL=http://testserver/chat
      - OVERWRITE_SETTING_Site_Url=http://testserver
      - Accounts_OAuth_Custom_keycloak=true
      #clientId
      - Accounts_OAuth_Custom_keycloak_id=testserver
      #clientSecret
      - Accounts_OAuth_Custom_keycloak_secret=
      - Accounts_OAuth_Custom_keycloak_url=http://testserver/iam/auth
      - Accounts_OAuth_Custom_keycloak_token_path=/realms/Affectli/protocol/openid-connect/token
      - Accounts_OAuth_Custom_keycloak_identity_path=/realms/Affectli/protocol/openid-connect/userinfo
      - Accounts_OAuth_Custom_keycloak_authorize_path=/realms/Affectli/protocol/openid-connect/auth
      - Accounts_OAuth_Custom_keycloak_scope=openid
      - Accounts_OAuth_Custom_keycloak_access_token_param=access_token
      - Accounts_OAuth_Custom_keycloak_button_label_text=redacted
      - Accounts_OAuth_Custom_keycloak_button_label_color=#FFFFFF
      - Accounts_OAuth_Custom_keycloak_login_style=redirect
      - Accounts_OAuth_Custom_keycloak_button_color=#13679A
      - Accounts_OAuth_Custom_keycloak_token_sent_via=payload
      - Accounts_OAuth_Custom_keycloak_identity_token_sent_via=header
      - Accounts_OAuth_Custom_keycloak_key_field=username
      - Accounts_OAuth_Custom_keycloak_username_field=preferred_username
      - Accounts_OAuth_Custom_keycloak_name_field=name
      - Accounts_OAuth_Custom_keycloak_email_field=email
      - Accounts_OAuth_Custom_keycloak_roles_claim=
      - Accounts_OAuth_Custom_keycloak_groups_claim=
      - Accounts_OAuth_Custom_keycloak_groups_channel_map=
      - Accounts_OAuth_Custom_keycloak_channels_admin=rocket.cat
      - Accounts_OAuth_Custom_keycloak_merge_users=true
      - Accounts_OAuth_Custom_keycloak_map_channels=
      - Accounts_OAuth_Custom_keycloak_merge_roles=false
      - Accounts_OAuth_Custom_keycloak_show_button=true
      - Accounts_OAuth_Custom_keycloak_avatar_field=
```

### Steps to reproduce:

1. Configure the server to run on a sub-path
2. Configure a custom oAuth for keycloak
3. Try to log in using SSO

### Expected behavior:

Login is successful

### Actual behavior:

On the browser side, the page just refreshes and the user is back at the login page.
On the server, an error log is produced as described above.

### Server Setup Information:

- Version of Rocket.Chat Server: rocketchat/rocket.chat:3.16.3
- Operating System: Docker
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: Unknown
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Chromium
- Operating System: Linux Mint

### Relevant logs:

See description.

**Comment by debdutdeb** [comment]
Hi Stefan 👋🏼 

Can you please test this on the latest (3.17.0) ? There are many subdirectory related issues still lurking and I'm not sure if this has been fixed in 3.17.0 or not.

Since you already have things set up, I gather it'll be easier and faster for you to test it on the latest. I'll be grateful !

Thanks 🙂

**Comment by maudrid** [comment]
Still the same issue.

```
➔ +------------------------------------------+
➔ |              SERVER RUNNING              |
➔ +------------------------------------------+
➔ |                                          |
➔ |  Rocket.Chat Version: 3.17.0             |
➔ |       NodeJS Version: 12.22.1 - x64      |
➔ |      MongoDB Version: 4.0.25             |
➔ |       MongoDB Engine: mmapv1             |
➔ |             Platform: linux              |
➔ |         Process Port: 1990               |
➔ |             Site URL: http://testserver  |
➔ |     ReplicaSet OpLog: Enabled            |
➔ |          Commit Hash: d4ce52e098         |
➔ |        Commit Branch: HEAD               |
➔ |                                          |
➔ +------------------------------------------+
Inserting admin user:
Name: Administrator
Email: redacted
Username: redacted
server.js:204 System ➔ error Exception while invoking method login Failed to complete OAuth handshake with keycloak at http://testserver/iam/auth/realms/Affectli/protocol/openid-connect/token. failed [400] {"error":"invalid_grant","error_description":"Incorrect redirect_uri"}
```

**Comment by maudrid** [comment]
Hi I noticed  ` Site URL: http://testserver ` and looked at my configuration more closely.
My environment variables were as follows:
```
- ROOT_URL=http://testserver/chat
- OVERWRITE_SETTING_Site_Url=http://testserver
```

I have now changes it to :
```
- ROOT_URL=http://testserver/chat
- OVERWRITE_SETTING_SITE_URL=http://testserver
```
So there was an issue with the CASE.
Now it is working and I'm closing this issue.
