### ISSUE TITLE
Server is not starting

### ISSUE THREAD

**Issue by korobaka** [RocketChat/Rocket.Chat#22901]
### Description:

The server is not starting and is giving me the following error:
```
Aug 10 16:22:32 koro rocketchat[1598]: /opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:313
Aug 10 16:22:32 koro rocketchat[1598]:                                                 throw(ex);
Aug 10 16:22:32 koro rocketchat[1598]:                                                 ^
Aug 10 16:22:32 koro rocketchat[1598]: MongoServerSelectionError: Server selection timed out after 30000 ms
Aug 10 16:22:32 koro rocketchat[1598]:     at Timeout._onTimeout (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/sdam/topology.js:439:30)
Aug 10 16:22:32 koro rocketchat[1598]:     at listOnTimeout (internal/timers.js:549:17)
Aug 10 16:22:32 koro rocketchat[1598]:     at processTimers (internal/timers.js:492:7) {
Aug 10 16:22:32 koro rocketchat[1598]:   reason: TopologyDescription {
Aug 10 16:22:32 koro rocketchat[1598]:     type: 'ReplicaSetNoPrimary',
Aug 10 16:22:32 koro rocketchat[1598]:     setName: null,
Aug 10 16:22:32 koro rocketchat[1598]:     maxSetVersion: null,
Aug 10 16:22:32 koro rocketchat[1598]:     maxElectionId: null,
Aug 10 16:22:32 koro rocketchat[1598]:     servers: Map {
Aug 10 16:22:32 koro rocketchat[1598]:       '127.0.0.1:27017' => ServerDescription {
Aug 10 16:22:32 koro rocketchat[1598]:         address: '127.0.0.1:27017',
Aug 10 16:22:32 koro rocketchat[1598]:         error: undefined,
Aug 10 16:22:32 koro rocketchat[1598]:         roundTripTime: 0.19708625428793436,
Aug 10 16:22:32 koro rocketchat[1598]:         lastUpdateTime: 1170845,
Aug 10 16:22:32 koro rocketchat[1598]:         lastWriteDate: null,
Aug 10 16:22:32 koro rocketchat[1598]:         opTime: null,
Aug 10 16:22:32 koro rocketchat[1598]:         type: 'RSGhost',
Aug 10 16:22:32 koro rocketchat[1598]:         topologyVersion: undefined,
Aug 10 16:22:32 koro rocketchat[1598]:         minWireVersion: 0,
Aug 10 16:22:32 koro rocketchat[1598]:         maxWireVersion: 7,
Aug 10 16:22:32 koro rocketchat[1598]:         maxBsonObjectSize: 16777216,
Aug 10 16:22:32 koro rocketchat[1598]:         maxMessageSizeBytes: 48000000,
Aug 10 16:22:32 koro rocketchat[1598]:         maxWriteBatchSize: 100000,
Aug 10 16:22:32 koro rocketchat[1598]:         hosts: [],
Aug 10 16:22:32 koro rocketchat[1598]:         passives: [],
Aug 10 16:22:32 koro rocketchat[1598]:         arbiters: [],
Aug 10 16:22:32 koro rocketchat[1598]:         tags: [],
Aug 10 16:22:32 koro rocketchat[1598]:         logicalSessionTimeoutMinutes: 30
Aug 10 16:22:32 koro rocketchat[1598]:       }
Aug 10 16:22:32 koro rocketchat[1598]:     },
Aug 10 16:22:32 koro rocketchat[1598]:     stale: false,
Aug 10 16:22:32 koro rocketchat[1598]:     compatible: true,
Aug 10 16:22:32 koro rocketchat[1598]:     compatibilityError: null,
Aug 10 16:22:32 koro rocketchat[1598]:     logicalSessionTimeoutMinutes: null,
Aug 10 16:22:32 koro rocketchat[1598]:     heartbeatFrequencyMS: 10000,
Aug 10 16:22:32 koro rocketchat[1598]:     localThresholdMS: 15,
Aug 10 16:22:32 koro rocketchat[1598]:     commonWireVersion: 7
Aug 10 16:22:32 koro rocketchat[1598]:   }
Aug 10 16:22:32 koro rocketchat[1598]: }
```

### Steps to reproduce:

1. Follow the tutorial
2. Try to launch the server
3. The error appears

### Expected behavior:

The server starts correctly.

### Actual behavior:
Error:
![image](https://user-images.githubusercontent.com/35098503/128896521-4466ede1-7247-46d8-9806-9c899145f345.png)

### Server Setup Information:

- Version of Rocket.Chat Server: latest (3.17.0)
- Operating System: Ubuntu (64 bits)
- Deployment Method: Manual (followed [this guide](https://docs.rocket.chat/installing-and-updating/manual-installation/ubuntu))
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.26

### Client Setup Information

- Desktop App or Browser Version: Opera GX 77.0.4054.275
- Operating System: Windows 10

### Relevant logs:

```Aug 10 16:22:00 koro systemd[1]: Started The Rocket.Chat server.
Aug 10 16:22:32 koro rocketchat[1598]: /opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:313
Aug 10 16:22:32 koro rocketchat[1598]:                                                 throw(ex);
Aug 10 16:22:32 koro rocketchat[1598]:                                                 ^
Aug 10 16:22:32 koro rocketchat[1598]: MongoServerSelectionError: Server selection timed out after 30000 ms
Aug 10 16:22:32 koro rocketchat[1598]:     at Timeout._onTimeout (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/sdam/topology.js:439:30)
Aug 10 16:22:32 koro rocketchat[1598]:     at listOnTimeout (internal/timers.js:549:17)
Aug 10 16:22:32 koro rocketchat[1598]:     at processTimers (internal/timers.js:492:7) {
Aug 10 16:22:32 koro rocketchat[1598]:   reason: TopologyDescription {
Aug 10 16:22:32 koro rocketchat[1598]:     type: 'ReplicaSetNoPrimary',
Aug 10 16:22:32 koro rocketchat[1598]:     setName: null,
Aug 10 16:22:32 koro rocketchat[1598]:     maxSetVersion: null,
Aug 10 16:22:32 koro rocketchat[1598]:     maxElectionId: null,
Aug 10 16:22:32 koro rocketchat[1598]:     servers: Map {
Aug 10 16:22:32 koro rocketchat[1598]:       '127.0.0.1:27017' => ServerDescription {
Aug 10 16:22:32 koro rocketchat[1598]:         address: '127.0.0.1:27017',
Aug 10 16:22:32 koro rocketchat[1598]:         error: undefined,
Aug 10 16:22:32 koro rocketchat[1598]:         roundTripTime: 0.19708625428793436,
Aug 10 16:22:32 koro rocketchat[1598]:         lastUpdateTime: 1170845,
Aug 10 16:22:32 koro rocketchat[1598]:         lastWriteDate: null,
Aug 10 16:22:32 koro rocketchat[1598]:         opTime: null,
Aug 10 16:22:32 koro rocketchat[1598]:         type: 'RSGhost',
Aug 10 16:22:32 koro rocketchat[1598]:         topologyVersion: undefined,
Aug 10 16:22:32 koro rocketchat[1598]:         minWireVersion: 0,
Aug 10 16:22:32 koro rocketchat[1598]:         maxWireVersion: 7,
Aug 10 16:22:32 koro rocketchat[1598]:         maxBsonObjectSize: 16777216,
Aug 10 16:22:32 koro rocketchat[1598]:         maxMessageSizeBytes: 48000000,
Aug 10 16:22:32 koro rocketchat[1598]:         maxWriteBatchSize: 100000,
Aug 10 16:22:32 koro rocketchat[1598]:         hosts: [],
Aug 10 16:22:32 koro rocketchat[1598]:         passives: [],
Aug 10 16:22:32 koro rocketchat[1598]:         arbiters: [],
Aug 10 16:22:32 koro rocketchat[1598]:         tags: [],
Aug 10 16:22:32 koro rocketchat[1598]:         logicalSessionTimeoutMinutes: 30
Aug 10 16:22:32 koro rocketchat[1598]:       }
Aug 10 16:22:32 koro rocketchat[1598]:     },
Aug 10 16:22:32 koro rocketchat[1598]:     stale: false,
Aug 10 16:22:32 koro rocketchat[1598]:     compatible: true,
Aug 10 16:22:32 koro rocketchat[1598]:     compatibilityError: null,
Aug 10 16:22:32 koro rocketchat[1598]:     logicalSessionTimeoutMinutes: null,
Aug 10 16:22:32 koro rocketchat[1598]:     heartbeatFrequencyMS: 10000,
Aug 10 16:22:32 koro rocketchat[1598]:     localThresholdMS: 15,
Aug 10 16:22:32 koro rocketchat[1598]:     commonWireVersion: 7
Aug 10 16:22:32 koro rocketchat[1598]:   }
Aug 10 16:22:32 koro rocketchat[1598]: }
Aug 10 16:22:32 koro systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Aug 10 16:22:32 koro systemd[1]: rocketchat.service: Failed with result 'exit-code'.
```

**Comment by johncrisp** [comment]
Hi,

Please follow our guidelines for reporting issues:

https://rocket.chat/docs/contributing/reporting-issues

Note that running on Windows is not recommended. 

Your error suggests you have a Mongo connection issue.

You can ask for support here:

https://open.rocket.chat/channel/support
https://forums.rocket.chat

Closing as there is no evidence of a bug.

Thanks.

**Comment by korobaka** [comment]
> Hi,
> 
> Please follow our guidelines for reporting issues:
> 
> https://rocket.chat/docs/contributing/reporting-issues
> 
> Note that running on Windows is not recommended.
> 
> Your error suggests you have a Mongo connection issue.
> 
> You can ask for support here:
> 
> https://open.rocket.chat/channel/support
> https://forums.rocket.chat
> 
> Closing as there is no evidence of a bug.
> 
> Thanks.

The server is running on ubuntu, the client is running on Windows.

Anyways, thank you for your answer
