### ISSUE TITLE
Mongo index error during startup

### ISSUE THREAD

**Issue by cprice-kgi** [RocketChat/Rocket.Chat#22916]
### Description:

Recently migrated from old server version to 3.14.0. During startup, I can see in the logs several index error messages regarding index name_1. The server does start up, but this error appears multiple times.

### Steps to reproduce:

1. Start up the RC 3.14.0 server code.

### Expected behavior:

I don't expect to see errors regarding this index.

### Actual behavior:

I can observe these error messages in the startup log.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Red Hat Linux
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.25

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: OSX

### Relevant logs:

```
Aug 12 19:03:12 ip-172-31-6-199 rocketchat: =================================
Aug 12 19:03:13 ip-172-31-6-199 rocketchat: {"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 222","time":{"$date":1628794993808},"level":"info"}
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: === UnHandledPromiseRejection ===
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: MongoError: Index with name: name_1 already exists with different options
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: at Connection.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:451:61)
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: at Connection.emit (events.js:314:20)
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: at Connection.EventEmitter.emit (domain.js:483:12)
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: at processMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:452:10)
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: at Socket.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:621:15)
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: at Socket.emit (events.js:314:20)
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: at Socket.EventEmitter.emit (domain.js:483:12)
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: at addChunk (_stream_readable.js:297:12)
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: at readableAddChunk (_stream_readable.js:272:9)
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: at Socket.Readable.push (_stream_readable.js:213:10)
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: at TCP.callbackTrampoline (internal/async_hooks.js:126:14) {
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1628794993 },
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: ok: 0,
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: code: 85,
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: codeName: 'IndexOptionsConflict',
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: '$clusterTime': {
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1628794993 },
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: signature: { hash: [Binary], keyId: [Long] }
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: }
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: }
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: ---------------------------------
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: Errors like this can cause oplog processing errors.
Aug 12 19:03:14 ip-172-31-6-199 rocketchat: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
```

**Comment by johncrisp** [comment]
Hi,

Please give us a bit of history on your install.

What version were you upgrading from?

If it was 'relatively' recent it should work. If it is older then a lot of stuff has changed and it may not.

**Comment by cprice-kgi** [comment]
We were very far behind. On 3.6.0 previously. Is there anything we can/should do about these?

**Comment by KevLehman** [comment]
This pull request has been inactive for a while, so we’re closing it to keep the backlog manageable.
If you’d like to continue working on it, feel free to reopen or submit a new PR. Thanks for the contribution!
