### ISSUE TITLE
No LDAP login after 0.19.0 upgrade

### ISSUE THREAD

**Issue by matlj** [RocketChat/Rocket.Chat#2306]
Following issue #2262, we upgraded to 0.19.0, and our LDAP users can't login again. 

Here is what happens in the  logs at login :
```
LDAPHandler ➔ info Init login joe
LDAP ➔ Connection.info Init setup
LDAP ➔ Connection.info Connecting ldaps://ldap.xxx.fr:636
LDAP ➔ Connection.debug connectionOptions { url: 'ldaps://ldap.xxx.fr:636',
  timeout: 5000,
  connectTimeout: 10000,
  idleTimeout: 10000,
  reconnect: false,
  tlsOptions: { rejectUnauthorized: true } }
LDAP ➔ Connection.info LDAP connected
LDAP ➔ Bind.info Binding admin user cn=rocketservice,ou=people,dc=xxx,dc=fr
LDAP ➔ Search.info Searching user joe
LDAP ➔ Search.debug searchOptions { filter: '(&(objectclass=inetOrgPerson)(|(cn=joe)(mail=joe)))',
  scope: 'sub' }
LDAP ➔ Search.debug domain_base ou=people,dc=xxx,dc=fr
LDAP ➔ Search.info Search result count 1
LDAP ➔ Search.debug Search result [
  {
    "messageID": 2,
    "protocolOp": "SearchEntry",
    "objectName": "cn=joe,ou=people,dc=xxx,dc=fr",
    "attributes": [
      {
        "type": "cn",
        "vals": [
          "joe"
        ]
      },
      {
        "type": "employeeNumber",
        "vals": [
          "@joe"
        ]
      },
      {
        "type": "sn",
        "vals": [
          "GREEN"
        ]
      },
      {
        "type": "displayName",
        "vals": [
          "GREEN Joe"
        ]
      },
      {
        "type": "givenName",
        "vals": [
          "Joe"
        ]
      },
      {
        "type": "mail",
        "vals": [
          "joe@xxx.fr"
        ]
      },
      {
        "type": "mobile",
       "vals": [
          "+33XXXXXXXX"
        ]
      },
      {
        "type": "objectClass",
        "vals": [
          "inetOrgPerson"
        ]
      },
      {
        "type": "o",
        "vals": [
          "xxx Paris"
        ]
      }
    ],
    "controls": []
  }
]
LDAP ➔ Auth.info Authenticating cn=joe,ou=people,dc=xxx,dc=fr
LDAP ➔ Auth.info Authenticated cn=joe,ou=people,dc=xxx,dc=fr
LDAP ➔ Connection.info Disconecting
Exception while invoking method 'login' TypeError: Cannot read property 'value' of undefined
    at [object Object].Meteor.startup.RocketChat.settings.addGroup.enableQuery._id (server/loginHandler.js:86:46)
    at accounts_server.js:462:32
    at tryLoginMethod (accounts_server.js:239:14)
    at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
    at [object Object].methods.login (accounts_server.js:522:27)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)


When we try the new "SYNC USERS" button, we get a red "500 error" in the upper right corner, with the following message in the logs : 
sync.js:132 LDAPSync ➔ error [TypeError: Cannot read property 'value' of undefined]
Exception while invoking method 'ldap_sync_users' TypeError: Cannot read property 'value' of undefined
    at server/sync.js:63:43
    at getDataToSyncUserData (server/sync.js:69:4)
    at syncUserData (server/sync.js:79:19)
    at server/sync.js:126:5
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1022:1)
    at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:869:1)
    at sync (server/sync.js:116:9)
    at [object Object].Meteor.methods.ldap_sync_users (server/syncUsers.js:16:12)
    at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
```

**Comment by Laisky** [comment]
+1 same problem on 0.19😭

**Comment by rodrigok** [comment]
Probably you removed the value from the field `Unique Identifier Field` in LDAP settings.

Can you put the default value back to this field? Now you can fix the lack of the unique identifier enabling the sync and clicking at "SYNC USERS".

So:
1. Put the default value back into `Unique Identifier Field`
2. Enable `Sync Data`
3. Save
4. Click on `SYNC USERS`

**Comment by homberger** [comment]
We are using MS Active Directory as LDAP-Auth-Backend and entering objectGUID as "Unique Identifier Field" fixed the problem. Thank you!

**Comment by matlj** [comment]
Putting back the default value in "Unique Identifier Field" fixed it, thank you !
