### ISSUE TITLE
Messages displaying stops working coincidentally when a release is released.

### ISSUE THREAD

**Issue by tryvin** [RocketChat/Rocket.Chat#23064]
### Description:

Coincidentally every time a new release is released my rocket chat instance stops showing sent messages, so I send the message, it keeps in a "pending" state, then I reload the view, and the message is there, sent. But all the other users need to also reload the view to see the messages coming.

So when I check, there's a new release out there I just update my K8S deployment with the new image version, and it starts working back again with no issues until the next release.

### Steps to reproduce:

1. Send a message
2. See the message in a pending state
3. Reload view
4. See the message

### Expected behavior:

Send and see the messages right away.

### Actual behavior:

I send the message, it keeps in a "pending" state, then I reload the view, and the message is there, sent. But all the other users need to also reload the view to see the messages coming.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.1 (but it happens in all versions)
- Operating System: Linux
- Deployment Method: docker/k8s
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.12 / unknown (oplog Ativado)

### Client Setup Information

- Desktop App or Browser Version: Desktop App
- Operating System: OSX

**Comment by debdutdeb** [comment]
Hi

Hmm, this is quite odd. Do you have any logs? Anything at all?

Generally I'd say there is something wrong with the deployment (iff the logs are fine). But this "coincidence" is something I'm a bit ummm about. 

Please double check  the logs, the coincidence might just be your brain trying to connect the dots without enough information at hand ;) 

But nevertheless I'll still ask around if someone has come across such an issue in the past or not. 

Thanks.

**Comment by tryvin** [comment]
hey @debdutdeb here are the logs:

```
I20210830-11:16:00.042(0) LocalStore: store created at  
I20210830-11:16:00.205(0) LocalStore: store created at  
I20210830-11:16:00.206(0) LocalStore: store created at  
I20210830-11:16:00.209(0) Setting default file store to GridFS 
I20210830-11:16:08.720(0) (migrations.js:120) Migrations: Not migrating, already at version 228
I20210830-11:16:09.142(0) ufs: temp directory created at "/tmp/ufs" 
I20210830-11:16:12.846(0) Loaded the Apps Framework and loaded a total of 0 Apps! 
I20210830-11:16:12.999(0) Using GridFS for custom sounds storage 
I20210830-11:16:13.005(0) Using GridFS for custom emoji storage 
I20210830-11:16:13.283(0) Updating process.env.MAIL_URL 
I20210830-11:16:14.259(0) ➔ System ➔ startup 
I20210830-11:16:14.260(0) ➔ +-----------------------------------------------------+ 
I20210830-11:16:14.261(0) ➔ |                    SERVER RUNNING                   | 
I20210830-11:16:14.261(0) ➔ +-----------------------------------------------------+ 
I20210830-11:16:14.261(0) ➔ |                                                     | 
I20210830-11:16:14.262(0) ➔ |  Rocket.Chat Version: 3.17.2                        | 
I20210830-11:16:14.262(0) ➔ |       NodeJS Version: 12.22.1 - x64                 | 
I20210830-11:16:14.262(0) ➔ |      MongoDB Version: 4.0.12                        | 
I20210830-11:16:14.263(0) ➔ |       MongoDB Engine: unknown                       | 
I20210830-11:16:14.263(0) ➔ |             Platform: linux                         | 
I20210830-11:16:14.263(0) ➔ |         Process Port: 3000                          | 
I20210830-11:16:14.264(0) ➔ |             Site URL: https://rocket.8sistemas.com  | 
I20210830-11:16:14.264(0) ➔ |     ReplicaSet OpLog: Enabled                       | 
I20210830-11:16:14.264(0) ➔ |          Commit Hash: fe0e5e4356                    | 
I20210830-11:16:14.265(0) ➔ |        Commit Branch: HEAD                          | 
I20210830-11:16:14.265(0) ➔ |                                                     | 
I20210830-11:16:14.265(0) ➔ +-----------------------------------------------------+ 
I20210919-02:21:09.586(0) Exception in setInterval callback: MongoNetworkError: connection 2 to 10.96.101.66:27017 closed     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:68:15     at Map.forEach (<anonymous>)     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:67:20)     at Socket.emit (events.js:314:20)     at Socket.EventEmitter.emit (domain.js:483:12)     at TCP.<anonymous> (net.js:675:12)     at TCP.callbackTrampoline (internal/async_hooks.js:126:14) 
```

Maybe the process responsible for sending the events to the clients depends on an all-time-working connection to mongo?

**Comment by tryvin** [comment]
BTW, this is Kubernetes.
