### ISSUE TITLE
LDAP/AD user avatars are gone

### ISSUE THREAD

**Issue by beloniki** [RocketChat/Rocket.Chat#23098]
### Description:

After an upgrade to version 3.18.0, I see, that LDAP users avatars are becoming gone during the time.

### Steps to reproduce:

1. Install Rocket 3.17.x
2. Synchronize LDAP/AD users with avatars
3. Upgrade to 3.18.0
4. Watch logs

### Expected behavior:

All is fine

### Actual behavior:

Users avatars became alphabetic.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.0
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: any
- Operating System: any

### Relevant logs:
```
Exception in callback of async function: TypeError: Cannot read property 'toUTCString' of undefined
     at server/routes/avatar/user.js:48:50
     at runWithEnvironment (packages/meteor.js:1286:24)
     at packages/meteor.js:1299:14
     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by beloniki** [comment]
**Upd**

There are two actions helped me to restore user images:

1. Restart the RC app container. (it was oom killer)
2. Run manual users sync twice.

**Comment by beloniki** [comment]
There were no repetitions.
