### ISSUE TITLE
Send test mail will block the server

### ISSUE THREAD

**Issue by Laisky** [RocketChat/Rocket.Chat#2316]
Your Rocket.Chat version: 0.19

when I click `SEND TEST MAIL TO MY USER` on SMTP settings page, the rocketchat server seems to be blocked by the mail, everything besides channel and settings lost respond.

It has been blocked for about 10 minutes before printing these logs:

```
docker/rocketchat[32119]: Exception while invoking method 'sendSMTPTestEmail' Error: connect ETIMEDOUT
docker/rocketchat[32119]:    at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
docker/rocketchat[32119]:    at smtpSend (packages/email/email.js:86:1)
docker/rocketchat[32119]:    at Object.Email.send (packages/email/email.js:185:1)
docker/rocketchat[32119]:    at [object Object].Meteor.methods.sendSMTPTestEmail (packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:10:9)
docker/rocketchat[32119]:    at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)
docker/rocketchat[32119]:    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
docker/rocketchat[32119]:    at livedata_server.js:708:19
docker/rocketchat[32119]:    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
docker/rocketchat[32119]:    at livedata_server.js:706:40
docker/rocketchat[32119]:    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
docker/rocketchat[32119]:    - - - - -
docker/rocketchat[32119]:    at errnoException (net.js:905:11)
docker/rocketchat[32119]:    at Object.afterConnect [as oncomplete] (net.js:896:19)
```

**Comment by engelgabriel** [comment]
Are we missing a try/catch wrapper?

**Comment by rodrigok** [comment]
No, we are missing one `this.unblock()`

**Comment by engelgabriel** [comment]
Please add this?

On Wednesday, 24 February 2016, Rodrigo Nascimento <notifications@github.com>
wrote:

> No, we are missing one this.unblock()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/2316#issuecomment-188535222>
> .
>


-- 
Sent from Mobile
