### ISSUE TITLE
Bad port for federation, bug good configuration

### ISSUE THREAD

**Issue by poka-IT** [RocketChat/Rocket.Chat#23303]
On v3.18.1 in docker, I configured DNS SRV and TXT records for federation.
So now i'm pretty OK, but for unknown reasons, rocketchat interface explains to me that the port is misconfigured:

![image](https://user-images.githubusercontent.com/4574805/135132269-00352bf2-82f7-4900-8b4d-3f6cd4a4f740.png)

The test fails:

![image](https://user-images.githubusercontent.com/4574805/135132388-96ef4b46-3532-4266-b6d9-bf1ed02ecac2.png)

In server log I just got every minutes:

`server.js:204 Federation ➔ http.error Error Error: ETIMEDOUT`

But the thing is, from the host server (and same thing from inside the docker container), DNS configuration seems to be OK:

```
# dig srv _rocketchat._https.chat.axiom-team.fr

; <<>> DiG 9.10.3-P4-Debian <<>> srv _rocketchat._https.chat.axiom-team.fr
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25927
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;_rocketchat._https.chat.axiom-team.fr. IN SRV

;; ANSWER SECTION:
_rocketchat._https.chat.axiom-team.fr. 60 IN SRV 1 1 443 chat.axiom-team.fr.

;; Query time: 21 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Sep 28 19:02:10 CEST 2021
;; MSG SIZE  rcvd: 104
```

We can see the port here is 443 as well.
Any Ideas ? How can I dig the problem ?

**Comment by skruppy** [comment]
With Rocket.Chat version 4.8.1 I still get the same port validation message, but some aspects may have changed:
* The error message when pressing "Test setup" is `TypeError: e.params is not iterable (cannot read property undefined)`.
* The logs show
```
{"level":50,"time":"2022-06-22T10:58:00.883Z","pid":1385101,"hostname":"xxx","name":"Federation","section":"http","msg":"Error","err":{"type":"Error","message":"url must be absolute and start with http:// or https://","stack":"Error: url must be absolute and start with http:// or https://\n    at _call (server/lib/http/call.ts:66:9)\n    at Object.httpCallAsync (server/lib/http/call.ts:190:9)\n    at Object.<anonymous> (packages/meteor.js:311:21)\n    at Object._call [as call] (server/overrides/http.ts:6:18)\n    at app/federation/server/lib/http.js:22:20\n    at /opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/federation/server/lib/http.js:46:9\n    at /opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"url must be absolute and start with http:// or https://"}
=== UnHandledPromiseRejection ===
Error: url must be absolute and start with http:// or https://
    at _call (server/lib/http/call.ts:66:9)
    at Object.httpCallAsync (server/lib/http/call.ts:190:9)
    at Object.<anonymous> (packages/meteor.js:311:21)
    at Object._call [as call] (server/overrides/http.ts:6:18)
    at app/federation/server/lib/http.js:22:20
    at /opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at app/federation/server/lib/http.js:46:9
    at /opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at app/federation/server/handler/index.js:79:3
    at /opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at app/federation/server/handler/index.js:84:2
    at /opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
---------------------------------
Errors like this can cause oplog processing errors.
Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Future node.js versions will automatically exit the process
=================================
```
