### ISSUE TITLE
platform add android => Error: Command failed:

### ISSUE THREAD

**Issue by bharatbiswal** [RocketChat/Rocket.Chat#2336]
I am using MacOSX 10.11.2, Node v5.7.0, NPM v3.6.0 
To build the Android app, I have been following instructions from:
https://github.com/RocketChat/Rocket.Chat/wiki/Build-the-Android-Cordova-Web-App-and-connect-to-your-own-Rocket.Chat-Server

I am trying to add platform 'android'

```
Apples-MacBook-Pro:Rocket.Chat.Cordova Apple$  cordova platform add --verbose android
Executing "before_platform_add"  hook for all plugins.
No version supplied. Retrieving version from config.xml...
Adding android project...
PlatformApi successfully found for platform android
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.konecty.rocket.chat
	Name: Rocket.Chat
	Activity: MainActivity
	Android target: android-23
Copying template files...
Android project created with cordova-android@5.0.0
Executing "before_prepare"  hook for all plugins.
Resolving module name for q => q
New assets, compiling resources...

Error: Command failed: 
    at ChildProcess.proc.on.onExit (/Users/Apple/clients/Roswell/Rocket.Chat.Cordova/node_modules/gm/lib/command.js:279:17)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

Apples-MacBook-Pro:Rocket.Chat.Cordova Apple$ 
```

What could be wrong?

**Comment by engelgabriel** [comment]
We moved the mobile apps project to https://github.com/RocketChat/Rocket.Chat.Cordova. Please use that project instead.
