### ISSUE TITLE
Issue on while using meteor command on installing Rocket.Chat Server

### ISSUE THREAD

**Issue by LokiMasterMind** [RocketChat/Rocket.Chat#2340]
Issue on while using meteor command on installing Rocket.Chat Server
given steps which i followed : 

git clone https://github.com/RocketChat/Rocket.Chat.git
cd Rocket.Chat
meteor

got this error please help me : 
D:\PROJECT WORK\RocketChat\Rocket.Chat>meteor
[[[[[ ~\D\PROJECT WORK\RocketChat\Rocket.Chat ]]]]]

=> Started proxy.
=> Started MongoDB.
'D:\PROJECT' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\lokesh.chandawar\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-o
s.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: Builder can not write without either data or a file path or a symlink pat
h: os/packages/rocketchat_livechat/public/head.html
    at Builder.write (C:\tools\isobuild\builder.js:225:13)
    at Builder.writeToGeneratedFilename (C:\tools\isobuild\builder.js:353:10)
    at C:\tools\isobuild\isopack.js:1346:27
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\lokesh.chandawar\AppData\Local\.meteo
r\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\u
nderscore\underscore.js:79:11)
    at _.each._.each.builder.generateFilename.directory (C:\tools\isobuild\isopa
ck.js:1320:11)
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\lokesh.chandawar\AppData\Local\.meteo
r\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\u
nderscore\underscore.js:79:11)
    at C:\tools\isobuild\isopack.js:1233:9
    at [object Object]._.extend.saveToPath (C:\tools\isobuild\isopack.js:1585:26
)
    at C:\tools\isobuild\isopack-cache.js:289:23
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend._loadLocalPackage (C:\tools\isobuild\isopack-cac
he.js:227:18)
    at C:\tools\isobuild\isopack-cache.js:166:14
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend._ensurePackageLoaded (C:\tools\isobuild\isopack-
cache.js:158:20)
    at C:\tools\isobuild\isopack-cache.js:73:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\lokesh.chandawar\AppData\Local\.meteo
r\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\u
nderscore\underscore.js:87:22)
    at [object Object]._.extend.eachPackage (C:\tools\packaging\package-map.js:4
9:7)
    at [object Object]._.extend.buildLocalPackages (C:\tools\isobuild\isopack-ca
che.js:72:24)
    at C:\tools\project-context.js:735:25
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._buildLocalPackages (C:\tools\project-context.js:
734:18)
    at C:\tools\project-context.js:257:35
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.
js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\tools\project-context.js:
235:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.
js:240:10)
    at C:\tools\runners\run-app.js:517:29
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at bundleApp (C:\tools\runners\run-app.js:516:31)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:594:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:858:28)
    at C:\tools\runners\run-app.js:396:12

D:\PROJECT WORK\RocketChat\Rocket.Chat>

Thanks In Adv...

**Comment by LokiMasterMind** [comment]
Got similar issue #2019 Thanks For help who post on this issue..

**Comment by wd2010** [comment]
I have the same issue

**Comment by LokiMasterMind** [comment]
@wd2010 
find similar issue #2019
you get solution for it. you need to modify some file as mention in #2019

I hope this will help You !

**Comment by wd2010** [comment]
@LokiMasterMind I have added  `build.bat` file  in the   `/packages/rocketchat-livechat/plugin/`  ,but it doesn't work.

**Comment by LokiMasterMind** [comment]
@wd2010 
have you tried this steps :
1) open dir "Rocket.Chat "
2) open dir ".meteor"
3) open file "packages"
4) find "rocketchat:livechat"
5) "rocketchat:livechat" -> "#rocketchat:livechat"
6) save
7) run chat

**Comment by zolbayars** [comment]
This happened to me. After hours of trying, I noticed some messages in the log right before `Builder can not write without either data or a file path or a symlink path` error throws: 

`Jan 31 02:48:53 ip-172-31-31-212 kernel: Out of memory: Kill process 5524 (node) score 587 or sacrifice child
Jan 31 02:48:53 ip-172-31-31-212 kernel: Killed process 5524 (node) total-vm:1985124kB, anon-rss:535392kB, file-rss:604kB, shmem-rss:0kB
`
The instance I was running threw an out of memory error and killed the meteor processes.
