### ISSUE TITLE
BBB integration

### ISSUE THREAD

**Issue by bb2k** [RocketChat/Rocket.Chat#23502]
### Description:

Hello, i'm trying to integrate our BBB server into RocketChat but i got an error.

### Steps to reproduce:

1. Goto channel
2. Clic on BBB Video Call
3.  Clic start Call

### Expected behavior:

To open a conference in BBB

### Actual behavior:

Nothing appends an i've got an error _'Error: tunneling socket could not be established, statusCode=405'_ in logs

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.1
- Operating System: Linux Debian 9
- Deployment Method: tar 
- Number of Running Instances: 1
- NodeJS Version: v12.22.7
- MongoDB Version: 4.0.25 / mmapv1 (oplog Activated)

### Client Setup Information

- Desktop App or Browser Version: Firefox 93
- Operating System: Linux

### Additional context

BBB In configured with the following URL :  https://bbb-conf-2.xxx.fr/bigbluebutton/api/
The secret is the good one
The BBB Webhooks are installed

API is working manually : 
```
<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
</response>
```

### Relevant logs:
```
2021-10-19T14:30:27.709691+02:00 v-chat-2 rocketchat[7431]: Exception while invoking method 'bbbJoin' Error: tunneling socket could not be established, statusCode=405
2021-10-19T14:30:27.710085+02:00 v-chat-2 rocketchat[7431]:     at ClientRequest.onConnect (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/tunnel-agent/index.js:166:19)
2021-10-19T14:30:27.710333+02:00 v-chat-2 rocketchat[7431]:     at Object.onceWrapper (events.js:421:26)
2021-10-19T14:30:27.710559+02:00 v-chat-2 rocketchat[7431]:     at ClientRequest.emit (events.js:314:20)
2021-10-19T14:30:27.710774+02:00 v-chat-2 rocketchat[7431]:     at ClientRequest.EventEmitter.emit (domain.js:483:12)
2021-10-19T14:30:27.711003+02:00 v-chat-2 rocketchat[7431]:     at Socket.socketOnData (_http_client.js:508:11)
2021-10-19T14:30:27.709691+02:00 v-chat-2 rocketchat[7431]: Exception while invoking method 'bbbJoin' Error: tunneling socket could not be established, statusCode=405
2021-10-19T14:30:27.710085+02:00 v-chat-2 rocketchat[7431]:     at ClientRequest.onConnect (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/tunnel-agent/index.js:166:19)
2021-10-19T14:30:27.710333+02:00 v-chat-2 rocketchat[7431]:     at Object.onceWrapper (events.js:421:26)
2021-10-19T14:30:27.710559+02:00 v-chat-2 rocketchat[7431]:     at ClientRequest.emit (events.js:314:20)
2021-10-19T14:30:27.710774+02:00 v-chat-2 rocketchat[7431]:     at ClientRequest.EventEmitter.emit (domain.js:483:12)
2021-10-19T14:30:27.711003+02:00 v-chat-2 rocketchat[7431]:     at Socket.socketOnData (_http_client.js:508:11)
2021-10-19T14:30:27.711224+02:00 v-chat-2 rocketchat[7431]:     at Socket.emit (events.js:314:20)
2021-10-19T14:30:27.711224+02:00 v-chat-2 rocketchat[7431]:     at Socket.emit (events.js:314:20)
2021-10-19T14:30:27.711468+02:00 v-chat-2 rocketchat[7431]:     at Socket.EventEmitter.emit (domain.js:483:12)
2021-10-19T14:30:27.711685+02:00 v-chat-2 rocketchat[7431]:     at addChunk (_stream_readable.js:297:12)
2021-10-19T14:30:27.711468+02:00 v-chat-2 rocketchat[7431]:     at Socket.EventEmitter.emit (domain.js:483:12)
2021-10-19T14:30:27.711685+02:00 v-chat-2 rocketchat[7431]:     at addChunk (_stream_readable.js:297:12)
2021-10-19T14:30:27.711898+02:00 v-chat-2 rocketchat[7431]:     at readableAddChunk (_stream_readable.js:272:9)
2021-10-19T14:30:27.711898+02:00 v-chat-2 rocketchat[7431]:     at readableAddChunk (_stream_readable.js:272:9)
2021-10-19T14:30:27.712137+02:00 v-chat-2 rocketchat[7431]:     at Socket.Readable.push (_stream_readable.js:213:10)
2021-10-19T14:30:27.712137+02:00 v-chat-2 rocketchat[7431]:     at Socket.Readable.push (_stream_readable.js:213:10)
2021-10-19T14:30:27.712364+02:00 v-chat-2 rocketchat[7431]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
2021-10-19T14:30:27.712364+02:00 v-chat-2 rocketchat[7431]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
2021-10-19T14:30:27.712594+02:00 v-chat-2 rocketchat[7431]:     at TCP.callbackTrampoline (internal/async_hooks.js:126:14)
2021-10-19T14:30:27.712594+02:00 v-chat-2 rocketchat[7431]:     at TCP.callbackTrampoline (internal/async_hooks.js:126:14)
```

**Comment by bb2k** [comment]
ok removing /bigbluebutton/api/ from the URL seem to change the error code :

`Exception while invoking method 'bbbJoin' Error: failed [404] <Map><timestamp>1634649360035</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton/api/hooks/create</path></Map>`

**Comment by smallfish01** [comment]
> SOLVED ! sorry

Hello, could you please let us know how you resolve the issue?

Thank you so much!
