### ISSUE TITLE
rocketchat 4.1.0 crashes at startup if direct reply is enabled

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#23590]
### Description:

If direct reply (via email) is enabled server crashes after upgrading to 4.1.0. After restoring the 4.0.4 release, disabling direct reply and upgrading again everything works. Even enabling direct reply works then. But if the server restarts for some reason the crash reappears.

### Steps to reproduce:

1. Enable direct reply in a 4.0.x release
2. Upgrade to 4.1.0
3. Server crashes

### Expected behavior:

Server not crashing.

### Actual behavior:

Server crashes.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.0
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 12.22.6
- MongoDB Version: 4.4

### Relevant logs:

```
Error: Expected array for search criteria
    at Connection._search (/opt/rocketchat-4.1.0/programs/server/npm/node_modules/imap/lib/Connection.js:573:11)
    at Connection.search (/opt/rocketchat-4.1.0/programs/server/npm/node_modules/imap/lib/Connection.js:566:8)
    at IMAPIntercepter.getEmails (server/email/IMAPInterceptor.ts:99:13)
    at server/email/IMAPInterceptor.ts:46:11
    at Connection.<anonymous> (/opt/rocketchat-4.1.0/programs/server/npm/node_modules/imap/lib/Connection.js:432:7)
    at Connection._resTagged (/opt/rocketchat-4.1.0/programs/server/npm/node_modules/imap/lib/Connection.js:1535:22)
    at Parser.<anonymous> (/opt/rocketchat-4.1.0/programs/server/npm/node_modules/imap/lib/Connection.js:194:10)
    at Parser.emit (events.js:314:20)
    at Parser.EventEmitter.emit (domain.js:483:12)
    at Parser._resTagged (/opt/rocketchat-4.1.0/programs/server/npm/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/opt/rocketchat-4.1.0/programs/server/npm/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/opt/rocketchat-4.1.0/programs/server/npm/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/opt/rocketchat-4.1.0/programs/server/npm/node_modules/imap/lib/Parser.js:53:12)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

**Comment by User35123** [comment]
i can confirm this issue. Server is crashing at version 4.1.0 but starts at 4.0.5 with enabled direct reply

**Comment by svenseeberg** [comment]
Can someone provide a command to disable it directly via Mongo CLI?

**Comment by neurolabs** [comment]
`db.getCollection('rocketchat_settings').update({_id: "Direct_Reply_Enable"}, {$set: {value: false}})` fixed the crash at startup.

**Comment by paulausz** [comment]
I am facing the same problem when updating via snap from 3.18.3 to 4.6.2 via `snap switch rocketchat-server --channel=4.x/stable`. Also, when installing 4.6.2 directly with snap and importing a backup from 3.18.3. the suggestion of @neurolabs affected 0 rows and did not help.

**Comment by d3hof** [comment]
up

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
