### ISSUE TITLE
MongoServerSelectionError: getaddrinfo EAI_AGAIN mongo from a fresh install of both RocketChat and Ubuntu Server 20.04

### ISSUE THREAD

**Issue by HyperCrowd** [RocketChat/Rocket.Chat#23600]
### Description:

I am on a brand new clean install of Ubuntu Server 20.04.  I have followed the Docker install instructions found [here](https://docs.rocket.chat/quick-start/installing-and-updating/docker-containers).

When I run `docker-compose up -d` in the directory with `docker-compose.yml` and then run `docker ps -a`, I get the following output:

<img width="1475" alt="Screen Shot 2021-10-30 at 9 24 45 PM" src="https://user-images.githubusercontent.com/76200774/139562962-31f4941d-3cc0-498c-bef6-ff12ed3da79b.png">

When I run `docker logs 0e002cde40d1` I get the following output:

```
MongoServerSelectionError: getaddrinfo EAI_AGAIN mongo
    at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/sdam/topology.js:439:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        error: Error: getaddrinfo EAI_AGAIN mongo
            at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
          name: 'MongoNetworkError'
        },
        roundTripTime: -1,
        lastUpdateTime: 1247483,
        lastWriteDate: null,
        opTime: null,
        type: 'Unknown',
        topologyVersion: undefined,
        minWireVersion: 0,
        maxWireVersion: 0,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      }
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
Tried 9 times. Waiting 5 secs...
```

I have no idea why a totally clean install from a totally clean operating system would have problems connecting to the Mongo docker.

### Steps to reproduce:

1. Download and install a fresh version of Ubuntu Server 20.04
2. Follow these Docker install instructions: https://docs.rocket.chat/quick-start/installing-and-updating/docker-containers
3. Run `docker ps -a` and notice no port is binding to the RocketChat process.
4. Run `docker logs` on the RocketChat process ID and you will see the error.

### Expected behavior:

A fresh install of RocketChat on a fresh install of Ubuntu Server 20.04 should work as advertised.

### Actual behavior:

The RocketChat process will not bind to a port because it cannot connect to Mongo.  It cannot connect to Mongo before it cannot get the address information of mongo.  Curiously, if I run `docker rmi mongo`, Docker claims it cannot find an image named mongo, despite an image being there.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.5
- Operating System: Ubuntu Server 20.04
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: 

```
2021-10-31T01:00:42.219+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2021-10-31T01:00:42.225+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=ab1cc9b81b2c
2021-10-31T01:00:42.225+0000 I CONTROL  [initandlisten] db version v4.0.27
2021-10-31T01:00:42.225+0000 I CONTROL  [initandlisten] git version: d47b151b55f286546e7c7c98888ae0577856ca20
2021-10-31T01:00:42.225+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2021-10-31T01:00:42.225+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2021-10-31T01:00:42.225+0000 I CONTROL  [initandlisten] modules: none
2021-10-31T01:00:42.225+0000 I CONTROL  [initandlisten] build environment:
2021-10-31T01:00:42.225+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
2021-10-31T01:00:42.225+0000 I CONTROL  [initandlisten]     distarch: x86_64
2021-10-31T01:00:42.225+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2021-10-31T01:00:42.225+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true }, replication: { oplogSizeMB: 128, replSet: "rs0" }, storage: { engine: "mmapv1", mmapv1: { smallFiles: true } } }
2021-10-31T01:00:42.226+0000 I STORAGE  [initandlisten] 
2021-10-31T01:00:42.226+0000 I STORAGE  [initandlisten] ** WARNING: You have explicitly specified 'MMAPV1' storage engine in your
2021-10-31T01:00:42.226+0000 I STORAGE  [initandlisten] **          config file or as a command line option.  Support for the MMAPV1
2021-10-31T01:00:42.226+0000 I STORAGE  [initandlisten] **          storage engine has been deprecated and will be removed in
2021-10-31T01:00:42.226+0000 I STORAGE  [initandlisten] **          version 4.2. See http://dochub.mongodb.org/core/deprecated-mmapv1
2021-10-31T01:00:42.226+0000 I STORAGE  [initandlisten] 
2021-10-31T01:00:42.251+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
2021-10-31T01:00:42.252+0000 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
2021-10-31T01:00:42.462+0000 I JOURNAL  [durability] Durability thread started
2021-10-31T01:00:42.463+0000 I JOURNAL  [journal writer] Journal writer thread started
2021-10-31T01:00:42.487+0000 I CONTROL  [initandlisten] 
2021-10-31T01:00:42.487+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2021-10-31T01:00:42.487+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2021-10-31T01:00:42.487+0000 I CONTROL  [initandlisten] 
2021-10-31T01:00:42.487+0000 I STORAGE  [initandlisten] allocating new ns file /data/db/local.ns, filling with zeroes...
2021-10-31T01:00:42.576+0000 I STORAGE  [initandlisten] done allocating ns file /data/db/local.ns, size: 16MB, took 0.088 seconds
2021-10-31T01:00:42.576+0000 I STORAGE  [FileAllocator] allocating new datafile /data/db/local.0
2021-10-31T01:00:42.576+0000 I STORAGE  [FileAllocator] creating directory /data/db/_tmp
2021-10-31T01:00:42.583+0000 I STORAGE  [FileAllocator] done allocating datafile /data/db/local.0, size: 16MB,  took 0.003 secs
2021-10-31T01:00:42.593+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 6371af91-bc40-4a42-b181-09382ed5dcb9
2021-10-31T01:00:42.595+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2021-10-31T01:00:42.600+0000 I STORAGE  [initandlisten] createCollection: local.replset.oplogTruncateAfterPoint with generated UUID: 6f939386-dfb3-4465-bef0-7775a18233e2
2021-10-31T01:00:42.602+0000 I STORAGE  [initandlisten] createCollection: local.replset.minvalid with generated UUID: 72de1506-34f1-4bf7-a8ab-a97e9d6d18c3
2021-10-31T01:00:42.603+0000 I STORAGE  [initandlisten] createCollection: local.replset.election with generated UUID: 0cd5c181-95b4-4633-bebb-85f72f9b014b
2021-10-31T01:00:42.604+0000 I REPL     [initandlisten] Did not find local initialized voted for document at startup.
2021-10-31T01:00:42.605+0000 I REPL     [initandlisten] Did not find local Rollback ID document at startup. Creating one.
2021-10-31T01:00:42.605+0000 I STORAGE  [initandlisten] createCollection: local.system.rollback.id with generated UUID: 520a27f8-6a4a-47d3-a732-3d1f5afbc9b0
2021-10-31T01:00:42.606+0000 I REPL     [initandlisten] Initialized the rollback ID to 1
2021-10-31T01:00:42.606+0000 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2021-10-31T01:00:42.608+0000 I CONTROL  [LogicalSessionCacheRefresh] Sessions collection is not set up; waiting until next sessions refresh interval: Replication has not yet been configured
2021-10-31T01:00:42.609+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2021-10-31T01:00:42.610+0000 I CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
2021-10-31T01:00:43.488+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:59692 #1 (1 connection now open)
2021-10-31T01:00:43.489+0000 I NETWORK  [conn1] received client metadata from 172.18.0.3:59692 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.27" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "16.04" } }
2021-10-31T01:00:43.492+0000 I REPL     [conn1] replSetInitiate admin command received from client
2021-10-31T01:00:43.493+0000 I REPL     [conn1] replSetInitiate config object with 1 members parses ok
2021-10-31T01:00:43.493+0000 I REPL     [conn1] ******
2021-10-31T01:00:43.493+0000 I REPL     [conn1] creating replication oplog of size: 128MB...
2021-10-31T01:00:43.493+0000 I STORAGE  [conn1] createCollection: local.oplog.rs with generated UUID: 9ead6bf5-9dc8-41a3-ab50-a18811379770
2021-10-31T01:00:43.493+0000 I STORAGE  [FileAllocator] allocating new datafile /data/db/local.1
2021-10-31T01:00:43.496+0000 I STORAGE  [FileAllocator] done allocating datafile /data/db/local.1, size: 256MB,  took 0.001 secs
2021-10-31T01:00:43.497+0000 I REPL     [conn1] ******
2021-10-31T01:00:43.497+0000 I STORAGE  [conn1] createCollection: local.system.replset with generated UUID: 72a40f59-3232-4012-b8c7-c63ada583421
2021-10-31T01:00:43.497+0000 I STORAGE  [conn1] allocating new ns file /data/db/admin.ns, filling with zeroes...
2021-10-31T01:00:43.534+0000 I STORAGE  [conn1] done allocating ns file /data/db/admin.ns, size: 16MB, took 0.037 seconds
2021-10-31T01:00:43.535+0000 I STORAGE  [FileAllocator] allocating new datafile /data/db/admin.0
2021-10-31T01:00:43.537+0000 I STORAGE  [FileAllocator] done allocating datafile /data/db/admin.0, size: 16MB,  took 0.001 secs
2021-10-31T01:00:43.542+0000 I STORAGE  [conn1] createCollection: admin.system.version with provided UUID: c7c3a56e-a65d-42c6-a37b-ef637c2656a9
2021-10-31T01:00:43.543+0000 I COMMAND  [conn1] setting featureCompatibilityVersion to 4.0
2021-10-31T01:00:43.543+0000 I NETWORK  [conn1] Skip closing connection for connection # 1
2021-10-31T01:00:43.543+0000 I REPL     [conn1] New replica set config in use: { _id: "rs0", version: 1, protocolVersion: 1, writeConcernMajorityJournalDefault: true, members: [ { _id: 0, host: "localhost:27017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: -1, catchUpTakeoverDelayMillis: 30000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('617deabb71cb1cf2c6675800') } }
2021-10-31T01:00:43.543+0000 I REPL     [conn1] This node is localhost:27017 in the config
2021-10-31T01:00:43.543+0000 I REPL     [conn1] transition to STARTUP2 from STARTUP
2021-10-31T01:00:43.543+0000 I REPL     [conn1] Starting replication storage threads
2021-10-31T01:00:43.544+0000 I REPL     [conn1] transition to RECOVERING from STARTUP2
2021-10-31T01:00:43.544+0000 I REPL     [conn1] Starting replication fetcher thread
2021-10-31T01:00:43.544+0000 I REPL     [conn1] Starting replication applier thread
2021-10-31T01:00:43.544+0000 I REPL     [conn1] Starting replication reporter thread
2021-10-31T01:00:43.544+0000 I REPL     [rsSync-0] Starting oplog application
2021-10-31T01:00:43.545+0000 I REPL     [rsSync-0] transition to SECONDARY from RECOVERING
2021-10-31T01:00:43.545+0000 I REPL     [rsSync-0] conducting a dry run election to see if we could be elected. current term: 0
2021-10-31T01:00:43.546+0000 I REPL     [replexec-0] dry election run succeeded, running for election in term 1
2021-10-31T01:00:43.549+0000 I NETWORK  [conn1] end connection 172.18.0.3:59692 (0 connections now open)
2021-10-31T01:00:43.581+0000 I REPL     [replexec-0] election succeeded, assuming primary role in term 1
2021-10-31T01:00:43.582+0000 I REPL     [replexec-0] transition to PRIMARY from SECONDARY
2021-10-31T01:00:43.582+0000 I REPL     [replexec-0] Resetting sync source to empty, which was :27017
2021-10-31T01:00:43.582+0000 I REPL     [replexec-0] Entering primary catch-up mode.
2021-10-31T01:00:43.582+0000 I REPL     [replexec-0] Exited primary catch-up mode.
2021-10-31T01:00:43.582+0000 I REPL     [replexec-0] Stopping replication producer
2021-10-31T01:00:43.582+0000 I REPL     [ReplBatcher] Oplog buffer has been drained in term 1
2021-10-31T01:00:43.582+0000 I REPL     [ReplBatcher] Oplog buffer has been drained in term 1
2021-10-31T01:00:43.583+0000 I STORAGE  [rsSync-0] allocating new ns file /data/db/config.ns, filling with zeroes...
2021-10-31T01:00:43.678+0000 I STORAGE  [rsSync-0] done allocating ns file /data/db/config.ns, size: 16MB, took 0.095 seconds
2021-10-31T01:00:43.678+0000 I STORAGE  [FileAllocator] allocating new datafile /data/db/config.0
2021-10-31T01:00:43.681+0000 I STORAGE  [FileAllocator] done allocating datafile /data/db/config.0, size: 16MB,  took 0.002 secs
2021-10-31T01:00:43.698+0000 I STORAGE  [rsSync-0] createCollection: config.image_collection with generated UUID: 2031fabe-4e9d-4996-8e11-a4dc2f7935b0
2021-10-31T01:00:43.705+0000 I COMMAND  [rsSync-0] command config.image_collection command: create { create: "image_collection", $db: "config" } numYields:0 reslen:163 locks:{ Global: { acquireCount: { r: 2, w: 2 } }, MMAPV1Journal: { acquireCount: { w: 5 } }, Database: { acquireCount: { w: 1, W: 1 } }, Metadata: { acquireCount: { W: 2 } }, Mutex: { acquireCount: { W: 4 } }, oplog: { acquireCount: { W: 1 } } } protocol:op_msg 122ms
2021-10-31T01:00:43.707+0000 I STORAGE  [rsSync-0] createCollection: config.transactions with generated UUID: e992b02b-fb28-41ee-a51c-7f7195c445f3
2021-10-31T01:00:43.720+0000 I REPL     [rsSync-0] transition to primary complete; database writes are now permitted
2021-10-31T01:00:43.724+0000 I COMMAND  [monitoring keys for HMAC] command admin.system.keys command: find { find: "system.keys", filter: { purpose: "HMAC", expiresAt: { $gt: Timestamp(1635642043, 3) } }, sort: { expiresAt: 1 }, $readPreference: { mode: "nearest", tags: [] }, $db: "admin" } planSummary: EOF keysExamined:0 docsExamined:0 cursorExhausted:1 numYields:0 nreturned:0 reslen:231 locks:{ Global: { acquireCount: { r: 2 }, acquireWaitCount: { r: 1 }, timeAcquiringMicros: { r: 140521 } }, MMAPV1Journal: { acquireCount: { r: 1 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { R: 1 } } } protocol:op_msg 140ms
2021-10-31T01:00:43.731+0000 I STORAGE  [monitoring keys for HMAC] createCollection: admin.system.keys with generated UUID: c4aa3da0-df6e-4265-bee5-ef4a40e2b4af
2021-10-31T01:05:42.650+0000 I STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with generated UUID: 5cdb15b1-6b10-421d-bf29-1177a376b304
2021-10-31T01:05:42.651+0000 I INDEX    [LogicalSessionCacheRefresh] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
2021-10-31T01:05:42.651+0000 I INDEX    [LogicalSessionCacheRefresh] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2021-10-31T01:05:42.651+0000 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total records. 0 secs
```
- NodeJS Version: v17.0.1
- MongoDB Version: 4

### Client Setup Information

- Desktop App or Browser Version: none
- Operating System: none

### Additional context

None

### Relevant logs:

None

**Comment by HyperCrowd** [comment]
When I exec into the container to test if the container can read the `mongo` service, I am able to confirm it cannot.

### Steps to Reproduce:

1. `docker exec -it 0e002cde40d1 /bin/bash`
1. ```
 cat <<'EOF' | tee test.js
require('dns').resolve('mongo', function(err) {
  if (err) {
     console.log("No connection");
  } else {
     console.log("Connected");
  }
});
```
1. `node test.js`
1. The output is `No connection`

**Comment by HyperCrowd** [comment]
I have discovered the problem is that `network_mode: host` found its way into the `docker-compose.yml` file in the `rocketchat` service during my debugging attempts.

This issue is now resolve. :D
