### ISSUE TITLE
upgrade from 3.18 to 4.10 fails help please

### ISSUE THREAD

**Issue by davidpablomitchell** [RocketChat/Rocket.Chat#23601]
Hello i have this error all the time no errors in npm install, thank you very much.

root@rocket:/tmp/bundle/programs/server# systemctl status rocketchat
● rocketchat.service - The Rocket.Chat server
     Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-10-31 09:28:05 UTC; 20s ago
   Main PID: 66421 (node)
      Tasks: 11 (limit: 9448)
     Memory: 614.6M
     CGroup: /system.slice/rocketchat.service
             └─66421 /usr/local/bin/node /opt/Rocket.Chat/main.js

Oct 31 09:28:25 rocket rocketchat[66421]: {"level":51,"time":"2021-10-31T09:28:25.120Z","pid":66421,"hostname":"rocket","name":"Migrations","msg":"Running >
Oct 31 09:28:25 rocket rocketchat[66421]: {"level":51,"time":"2021-10-31T09:28:25.186Z","pid":66421,"hostname":"rocket","name":"Migrations","msg":"Running >
Oct 31 09:28:25 rocket rocketchat[66421]: {"level":51,"time":"2021-10-31T09:28:25.196Z","pid":66421,"hostname":"rocket","name":"Migrations","msg":"Running >
Oct 31 09:28:25 rocket rocketchat[66421]: {"level":51,"time":"2021-10-31T09:28:25.297Z","pid":66421,"hostname":"rocket","name":"Migrations","msg":"Running >
Oct 31 09:28:25 rocket rocketchat[66421]: This instance could not remove the Telegram app package. If you are running Rocket.Chat in a cluster with multipl>
Oct 31 09:28:25 rocket rocketchat[66421]: This instance could not remove the GIPHY app package. If you are running Rocket.Chat in a cluster with multiple i>
Oct 31 09:28:25 rocket rocketchat[66421]: This instance could not remove the Jitsi Slash Command app package. If you are running Rocket.Chat in a cluster w>
Oct 31 09:28:25 rocket rocketchat[66421]: {"level":51,"time":"2021-10-31T09:28:25.723Z","pid":66421,"hostname":"rocket","name":"Migrations","msg":"Running >
Oct 31 09:28:25 rocket rocketchat[66421]: {"level":51,"time":"2021-10-31T09:28:25.727Z","pid":66421,"hostname":"rocket","name":"Migrations","msg":"Running >
Oct 31 09:28:25 rocket rocketchat[66421]: {"level":51,"time":"2021-10-31T09:28:25.736Z","pid":66421,"hostname":"rocket","name":"Migrations","msg":"Running >

root@rocket:/tmp/bundle/programs/server# systemctl status rocketchat
● rocketchat.service - The Rocket.Chat server
     Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2021-10-31 09:28:31 UTC; 695ms ago
    Process: 66421 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
   Main PID: 66421 (code=exited, status=1/FAILURE)

Oct 31 09:28:31 rocket rocketchat[66421]:     at Parser._tryread (/opt/Rocket.Chat/programs/server/npm/node_modules/imap/lib/Parser.js:82:15)
Oct 31 09:28:31 rocket rocketchat[66421]:     at Socket.Parser._cbReadable (/opt/Rocket.Chat/programs/server/npm/node_modules/imap/lib/Parser.js:53:12)
Oct 31 09:28:31 rocket rocketchat[66421]:     at Socket.emit (events.js:315:20)
Oct 31 09:28:31 rocket rocketchat[66421]:     at Socket.EventEmitter.emit (domain.js:483:12)
Oct 31 09:28:31 rocket rocketchat[66421]:     at emitReadable_ (_stream_readable.js:555:12)
Oct 31 09:28:31 rocket rocketchat[66421]:     at processTicksAndRejections (internal/process/task_queues.js:83:21) {
Oct 31 09:28:31 rocket rocketchat[66421]:   source: 'authentication'
Oct 31 09:28:31 rocket rocketchat[66421]: }
Oct 31 09:28:31 rocket systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Oct 31 09:28:31 rocket systemd[1]: rocketchat.service: Failed with result 'exit-code'.
root@rocket:/tmp/bundle/programs/server#

**Comment by davidpablomitchell** [comment]
SOLVED, i you have email experimental account added you need to remove

**Comment by the-voidl** [comment]
I have the same error, so the application does not start up.
How can I remove the mail account from the command line?
