### ISSUE TITLE
Changing a room status from ACTIVE to ARCHIVED gives an error.

### ISSUE THREAD

**Issue by mikrobyte** [RocketChat/Rocket.Chat#2363]
Your Rocket.Chat version: 0.19.0

i was just playing around with the room's options and i found what seems to be an error?

Go to **_Administration --> Rooms_**

select any room and change its status from **ACTIVE to ARCHIVED**
and you can see an "Internal server error" frame popping up.

In the log i can see this:

**/opt/rocket.chat/logs/app-0.log**
```
Exception while invoking method 'archiveRoom' TypeError: Cannot read property 'u' of undefined
    at [object Object].Meteor.methods.archiveRoom (server/methods/archiveRoom.coffee:8:6)
    at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo (/opt/rocket.chat/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/opt/rocket.chat/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
```

**Comment by decan0505** [comment]
Same issue here. Log below:
```
Exception while invoking method 'archiveRoom' TypeError: Cannot read property 'u' of undefined 
at [object Object].Meteor.methods.archiveRoom (server/methods/archiveRoom.coffee:8:6)
at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)
at maybeAuditArgumentChecks (livedata_server.js:1698:12)
at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at livedata_server.js:706:40
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at livedata_server.js:704:46
at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
at doResolve (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13) 
```

**Comment by goobersmooch** [comment]
We're having the same issue. Rocket Chat Version: 0.19.0

**Comment by marceloschmidt** [comment]
It works for me on versoin 0.20.0. Nevertheless, I've added an additional check so that this error doesn't happen.

**Comment by shellster** [comment]
I am also getting this error.  I have one channel, it is called "#general".  It is the default channel, and I get this exact error when I try to archive it.
