### ISSUE TITLE
Empty Startpage after update to 4.1

### ISSUE THREAD

**Issue by knordsiek** [RocketChat/Rocket.Chat#23640]
I am running rocketchat on a RockyLinux 8.4 Server with mongodb 4.2.17  
2 weeks ago I have updated to rocketchat version 4.0.
After this I get a message that mongodb Version 4.0 is deprecated.
So I stoped rocketchat and mongodb, replaced the mongodb repository to Version 4.2.17 and then I have done a yum update so mongodb version 4.2.17 was installed. After this I started mongodb and then rocketchat and all works fine.
On this friday I want to do an update to Rocketchat Version 4.1. 
After the update the rocketchat is started but if I log into the server with the browser I get only a grey blank website.

`--The start-up result is done.
--Nov 05 14:34:55 rocketchat1.fritz.box systemd[1]: Stopping MongoDB Database Server...
-- Subject: Unit mongod.service has begun shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Unit mongod.service has begun shutting down.`

`Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]: === UnHandledPromiseRejection ===
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]: MongoError: interrupted at shutdown
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at MessageStream.messageHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm>
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at MessageStream.emit (events.js:314:20)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at MessageStream.EventEmitter.emit (domain.js:483:12)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at processIncomingData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/no>
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at MessageStream._write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/n>
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at doWrite (_stream_writable.js:403:12)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at writeOrBuffer (_stream_writable.js:387:5)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at MessageStream.Writable.write (_stream_writable.js:318:11)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at Socket.ondata (_stream_readable.js:718:22)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at Socket.emit (events.js:314:20)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at Socket.EventEmitter.emit (domain.js:483:12)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at addChunk (_stream_readable.js:297:12)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at readableAddChunk (_stream_readable.js:272:9)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at Socket.Readable.push (_stream_readable.js:213:10)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at TCP.callbackTrampoline (internal/async_hooks.js:126:14)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:  => awaited here:
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/n>
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at app/models/server/raw/NotificationQueue.ts:60:15
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promi>
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:  => awaited here:
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/n>
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at app/notification-queue/server/NotificationQueue.ts:56:21
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promi>
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1636119294 },
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:   ok: 0,
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:   code: 11600,
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:   codeName: 'InterruptedAtShutdown',
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:   '$clusterTime': {
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1636119294 },
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:     signature: { hash: [Binary], keyId: 0 }
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:   },
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]:   [Symbol(errorLabels)]: Set { 'RetryableWriteError' }
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]: }
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]: ---------------------------------
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]: Errors like this can cause oplog processing errors.
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to au>
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]: Future node.js versions will automatically exit the process
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5511]: =================================
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]: Exception in setInterval callback: MongoError: interrupted at shutdown
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at MessageStream.messageHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm>
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at MessageStream.emit (events.js:314:20)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at MessageStream.EventEmitter.emit (domain.js:483:12)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at processIncomingData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/no>
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at MessageStream._write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/n>
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at doWrite (_stream_writable.js:403:12)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at writeOrBuffer (_stream_writable.js:387:5)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at MessageStream.Writable.write (_stream_writable.js:318:11)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at Socket.ondata (_stream_readable.js:718:22)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at Socket.emit (events.js:314:20)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at Socket.EventEmitter.emit (domain.js:483:12)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at addChunk (_stream_readable.js:297:12)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at readableAddChunk (_stream_readable.js:272:9)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at Socket.Readable.push (_stream_readable.js:213:10)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     at TCP.callbackTrampoline (internal/async_hooks.js:126:14) {
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1636119294 },
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:   ok: 0,
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:   code: 11600,
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:   codeName: 'InterruptedAtShutdown',
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:   '$clusterTime': {
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1636119294 },
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:     signature: { hash: [Binary], keyId: 0 }
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:   },
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]:   [Symbol(errorLabels)]: Set { 'RetryableWriteError' }
Nov 05 14:34:57 rocketchat1.fritz.box rocketchat[5510]: }
Nov 05 14:34:58 rocketchat1.fritz.box systemd[1]: mongod.service: Succeeded.`

`[root@rocketchat1]# netstat -tulpen
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       Benutzer   Inode      PID/Program name  
tcp   0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      993        28307      5667/mongod
tcp   0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          20737      923/nginx: master p
tcp   0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          20031      714/sshd
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      1000       28814      5510/node
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      1000       28823      5511/node
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      0          20738      923/nginx: master p
tcp6       0      0 :::22                   :::*                    LISTEN      0          20033      714/sshd
tcp6       0      0 :::443                  :::*                    LISTEN      0          20739      923/nginx: master p
udp        0      0 127.0.0.1:323           0.0.0.0:*                           0          17913      670/chronyd
udp6       0      0 ::1:323                 :::*                                0          17914      670/chronyd`

`[root@rocketchat1]# node -v
v12.22.1
[root@rocketchat1]# npm -v
6.14.1
`

**Comment by knordsiek** [comment]
After Update to 4.1 the same error occurred.
The Nodeengine starts but blank startpage

**Comment by knordsiek** [comment]
Update to 4.1.2 the same error occured.
Nodeserver was startet but only blank page, without any content.

**Comment by knordsiek** [comment]
Server hardware: hypervisor (proxmox)
Version of Rocket.Chat Server: 4.1
Operating System: Rocky Linux 8.4
Deployment Method: stand alone
Number of Running Instances: 2
DB Replicaset Oplog: enabled
NodeJS Version: 12.22.1
MongoDB Version: 4.2.17

**Comment by knordsiek** [comment]
Is there anything else I can give of informations?

**Comment by knordsiek** [comment]
Problem solved.
it was a problem with the ssl certificate.
