### ISSUE TITLE
Upgrade from 4.0.0 to 4.1.2 failed

### ISSUE THREAD

**Issue by grzebo** [RocketChat/Rocket.Chat#23678]
### Description:

After upgrading from 4.0.0 to 4.1.2 the server does not start.

### Steps to reproduce:

1. run rocketchatctl update
2. the server doesn't start

### Expected behavior:

Rocket Chat 4.1.2 should work.

### Actual behavior:

Rocket Chat does not start.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.2
- Operating System: Ubuntu 18.04.6 LTS
- Deployment Method: DigitalOcean prepackaged
- Number of Running Instances: 1
- NodeJS Version: v12.22.7
- MongoDB Version:  v5.0.3

### Relevant logs:

```
# rocketchatctl update
Updates could be risky, you can use the backup option # rocketchatctl backup, to create a backup of the rocketchat database first. Please check that you have enough space in your system to store the backup.
Current update available for RocketChat server: from 4.0 to 4.1.2.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132  100   132    0     0    301      0 --:--:-- --:--:-- --:--:--   300
100  160M  100  160M    0     0  74.8M      0  0:00:02  0:00:02 --:--:-- 98.6M
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> fibers@4.0.3 install /tmp/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory '/tmp/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory '/tmp/bundle/programs/server/node_modules/fibers/build'
Installed in `/tmp/bundle/programs/server/node_modules/fibers/bin/linux-x64-57-glibc/fibers.node`
npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd meteor-dev-bundle@ node npm-rebuild.js (wd=/tmp/bundle/programs/server)
added 147 packages from 122 contributors and audited 148 packages in 8.253s

2 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Waiting up to 5 minutes for RocketChat server to be active ... 2
Waiting up to 5 minutes for RocketChat server to be active ... 4
Waiting up to 5 minutes for RocketChat server to be active ... 6
...
Waiting up to 5 minutes for RocketChat server to be active ... 118
Waiting up to 5 minutes for RocketChat server to be active ... 120
Waiting up to 5 minutes for RocketChat server to be active ... 122
RocketChat server not running. Cancelling
```

```
Nov 10 02:12:24 rocketchat-ubuntu-ski-1 systemd[1]: Started The Rocket.Chat server.
Nov 10 02:12:36 rocketchat-ubuntu-ski-1 rocketchat[3014]: {"level":30,"time":"2021-11-10T01:12:36.326Z","pid":3014,"hostname":"rocketchat-ubuntu-ski-1","name":"System","msg":"Updating process.env.MAIL_URL"}
Nov 10 02:12:36 rocketchat-ubuntu-ski-1 rocketchat[3014]: {"level":30,"time":"2021-11-10T01:12:36.602Z","pid":3014,"hostname":"rocketchat-ubuntu-ski-1","name":"System","msg":"Setting default file store to FileSystem"}
Nov 10 02:12:37 rocketchat-ubuntu-ski-1 rocketchat[3014]: {"level":30,"time":"2021-11-10T01:12:37.918Z","pid":3014,"hostname":"rocketchat-ubuntu-ski-1","name":"Federation","section":"Setup","msg":"Federation is disabled"}
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]: /opt/Rocket.Chat/programs/server/npm/node_modules/imap/lib/Connection.js:573
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     throw new Error('Expected array for search criteria');
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     ^
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]: Error: Expected array for search criteria
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Connection._search (/opt/Rocket.Chat/programs/server/npm/node_modules/imap/lib/Connection.js:573:11)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Connection.search (/opt/Rocket.Chat/programs/server/npm/node_modules/imap/lib/Connection.js:566:8)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at IMAPIntercepter.getEmails (server/email/IMAPInterceptor.ts:99:13)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at server/email/IMAPInterceptor.ts:46:11
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Connection.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/imap/lib/Connection.js:432:7)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Connection._resTagged (/opt/Rocket.Chat/programs/server/npm/node_modules/imap/lib/Connection.js:1535:22)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Parser.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/imap/lib/Connection.js:194:10)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Parser.emit (events.js:314:20)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Parser.EventEmitter.emit (domain.js:483:12)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Parser._resTagged (/opt/Rocket.Chat/programs/server/npm/node_modules/imap/lib/Parser.js:175:10)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Parser._parse (/opt/Rocket.Chat/programs/server/npm/node_modules/imap/lib/Parser.js:139:16)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Parser._tryread (/opt/Rocket.Chat/programs/server/npm/node_modules/imap/lib/Parser.js:82:15)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Socket.Parser._cbReadable (/opt/Rocket.Chat/programs/server/npm/node_modules/imap/lib/Parser.js:53:12)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Socket.emit (events.js:314:20)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at Socket.EventEmitter.emit (domain.js:483:12)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at emitReadable_ (_stream_readable.js:557:12)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 rocketchat[3014]:     at processTicksAndRejections (internal/process/task_queues.js:83:21)
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 systemd[1]: rocketchat.service: Failed with result 'exit-code'.
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 systemd[1]: rocketchat.service: Service hold-off time over, scheduling restart.
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 systemd[1]: rocketchat.service: Scheduled restart job, restart counter is at 24.
Nov 10 02:12:38 rocketchat-ubuntu-ski-1 systemd[1]: Stopped The Rocket.Chat server.
```

**Comment by zwnk** [comment]
maybe this issue: https://github.com/RocketChat/Rocket.Chat/issues/23590
