### ISSUE TITLE
Edit username is not allowed [error-action-not-allowed]

### ISSUE THREAD

**Issue by iBelow** [RocketChat/Rocket.Chat#23755]
i can't change roles, usernames and etc. 
my role admin with full access
`
Edit username is not allowed [error-action-not-allowed]
`

i see this error when i try to change the role

**Comment by dudanogueira** [comment]
hi! we need more info in order to help you.

Like version, deploy method, and the exact steps in order to reproduce this error, preferably on a clean install.

**Comment by iBelow** [comment]
Rocket.chat info

```
name:      rocketchat-server
summary:   Rocket.Chat server
publisher: Rocket.Chat (rocketchat✓)
store-url: https://snapcraft.io/rocketchat-server
contact:   https://open.rocket.chat/channel/ubuntu-snap
license:   unset
description: |
  Have your own Slack like online chat, built with Meteor. https://rocket.chat/
commands:
  - rocketchat-server.backupdb
  - rocketchat-server.initcaddy
  - rocketchat-server.mongo
  - rocketchat-server.restoredb
services:
  rocketchat-server.rocketchat-caddy: simple, enabled, inactive
  rocketchat-server.rocketchat-mongo: simple, enabled, active
  rocketchat-server:                  simple, enabled, active
snap-id:      wdBUbiEuMNHmAHLBCXQXOcXaOCvbWS1e
tracking:     4.x/stable
refresh-date: 3 days ago, at 18:33 +03
channels:
  4.x/stable:       4.0.5       2021-11-10 (1492) 284MB -
  4.x/candidate:    ↑                                   
  4.x/beta:         ↑                                   
  4.x/edge:         4.1.2       2021-11-19 (1494) 220MB -
  latest/stable:    2.4.14      2020-12-23 (1453) 267MB -
  latest/candidate: 2.4.14      2021-07-30 (1453) 267MB -
  latest/beta:      2.1.1       2019-10-21 (1414) 251MB -
  latest/edge:      2.4.11      2021-05-11 (1427) 267MB -
  3.x/stable:       3.18.3      2021-11-10 (1491) 289MB -
  3.x/candidate:    3.17.0-rc.5 2021-07-30 (1481) 288MB -
  3.x/beta:         3.13.2      2021-11-07 (1487) 219MB -
  3.x/edge:         3.18.3      2021-11-10 (1491) 289MB -
  2.x/stable:       2.4.14      2020-12-23 (1453) 267MB -
  2.x/candidate:    2.4.14      2020-12-23 (1453) 267MB -
  2.x/beta:         2.4.14      2020-12-23 (1453) 267MB -
  2.x/edge:         ↑                                   
installed:          4.0.5                  (1492) 284MB -
```

logs: 
```
[
  "qrcode's executor is being executed...",
  {
    "sender": {
      "id": "6vAAyaQ86G2xnMbFQ",
      "username": "XXXXXX",
      "emails": [
        {
          "address": "XXXXXX",
          "verified": true
        }
      ],
      "type": "user",
      "isEnabled": true,
      "name": "XXXXXX",
      "roles": [
        "admin",
        "livechat-manager",
        "livechat-agent"
      ],
      "status": "online",
      "statusConnection": "online",
      "utcOffset": 3,
      "createdAt": "2021-11-22T15:38:08.047Z",
      "updatedAt": "2021-11-25T08:50:40.761Z",
      "lastLoginAt": "2021-11-25T08:50:40.739Z"
    },
    "room": {
      "id": "GENERAL",
      "slugifiedName": "general",
      "type": "c",
      "isDefault": true,
      "isReadOnly": false,
      "displaySystemMessages": true,
      "messageCount": 0,
      "createdAt": "2021-11-22T15:37:19.063Z",
      "updatedAt": "2021-11-24T14:47:02.219Z",
      "lastModifiedAt": "2021-11-24T14:46:33.957Z"
    },
    "params": [
      "test"
    ],
    "triggerId": "k3B5ZJ3BrEwRdbLcK"
  }
]

```
```

[
  "{\"stack\":\"Error: Not enough permission\\n    at validateMessage (app/lib/server/functions/sendMessage.js:152:10)\\n    at sendMessage (app/lib/server/functions/sendMessage.js:166:2)\\n    at executeSendMessage (app/lib/server/methods/sendMessage.js:79:10)\\n    at app/apps/server/bridges/messages.ts:25:23\\n    at /snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\",\"message\":\"Not enough permission\"}"
]
```
```

[
  "qrcode's executor was unsuccessful."
]

```

**Comment by iBelow** [comment]
> hi! we need more info in order to help you.
> 
> Like version, deploy method, and the exact steps in order to reproduce this error, preferably on a clean install.

fresh installed on fresh linux server

Steps: 
install app(bot), then in any chat / room / channer i'm try to call bot via "/qrcode test"
