### ISSUE TITLE
Connection error in 4.2.0?

### ISSUE THREAD

**Issue by mzch** [RocketChat/Rocket.Chat#23828]
### Description:
After updaring Rocket.Chat server from 4.1.2 to 4.2.0, my client (Desktop and Browser) can't connect to Rocket.Chat server.

### Steps to reproduce:

1. Stop Rocket.Chat server `4.1.2`
2. Download the latest server tar ball from https://releases.rocket.chat/latest/download
3. Unpack and do `cd bundle/programs/server && npm install`
4. Start `4.2.0` server
5. Login the server using Desktop client or a browser.

### Expected behavior:
Show conversation screen.

### Actual behavior:
Clients can't connect to the server, blinking ` Connecting...` bar on the top of screen.

<img width="1592" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/144068683-d80ddff7-6c89-42db-a7cf-c9c3151c7a0c.png">

### Server Setup Information:

- Version of Rocket.Chat Server: `4.2.0`
- Operating System: `Debian 11.1`
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: `v12.22.7`
- MongoDB Version: `5.1.0 `

### Client Setup Information

- Desktop App 3.6.0 or Chrome 96.0.4664.55
- Operating System: macOS 12.0.1

### Relevant logs:

```
Nov 30 06:34:32 n13 rocketchat[63517]: {"level":51,"time":"2021-11-30T14:34:32.190Z","pid":63517,"hostname":"n13","name":"Migrations","msg":"Not migrating, already at version 249"}
Nov 30 06:34:32 n13 rocketchat[63517]: Loaded the Apps Framework and loaded a total of 0 Apps!
Nov 30 06:34:33 n13 rocketchat[63517]: +-------------------------------------------------+
Nov 30 06:34:33 n13 rocketchat[63517]: |                  SERVER RUNNING                 |
Nov 30 06:34:33 n13 rocketchat[63517]: +-------------------------------------------------+
Nov 30 06:34:33 n13 rocketchat[63517]: |                                                 |
Nov 30 06:34:33 n13 rocketchat[63517]: |  Rocket.Chat Version: 4.2.0                     |
Nov 30 06:34:33 n13 rocketchat[63517]: |       NodeJS Version: 12.22.7 - x64             |
Nov 30 06:34:33 n13 rocketchat[63517]: |      MongoDB Version: 5.1.0                     |
Nov 30 06:34:33 n13 rocketchat[63517]: |       MongoDB Engine: unknown                   |
Nov 30 06:34:33 n13 rocketchat[63517]: |             Platform: linux                     |
Nov 30 06:34:33 n13 rocketchat[63517]: |         Process Port: 3000                      |
Nov 30 06:34:33 n13 rocketchat[63517]: |             Site URL: https://confabulari.com/  |
Nov 30 06:34:33 n13 rocketchat[63517]: |     ReplicaSet OpLog: Enabled                   |
Nov 30 06:34:33 n13 rocketchat[63517]: |          Commit Hash: a4ad199f13                |
Nov 30 06:34:33 n13 rocketchat[63517]: |        Commit Branch: HEAD                      |
Nov 30 06:34:33 n13 rocketchat[63517]: |                                                 |
Nov 30 06:34:33 n13 rocketchat[63517]: +-------------------------------------------------+
```

**Comment by dudanogueira** [comment]
Hi! Were you able to solve this?

Looks like it's working fine from here:

```
curl https://confabulari.com/api/info
{"version":"4.2","success":true}
```

Also from browser, I see no errors.

Thanks!

**Comment by mzch** [comment]
Well, login screen is shown correctly, ths problem happned after login.

**Comment by kash1983** [comment]
same problem at my installation.
the login appears, after successfull login nothing will happen... gray screen with loading animation.

**Comment by ankar84** [comment]
Just to inform that it's not a problem of all deployment methods for 4.2.0 version - my test env works perfect on 4.2.0 in docker.
![image](https://user-images.githubusercontent.com/4023037/144167908-8461fa0f-d720-49db-a32d-bcc763a22b3a.png)

**Comment by dasfreak** [comment]
Also works in my installation (Docker).
I just had to reload my client (CTRL+R) and it worked.

**Comment by dudanogueira** [comment]
@kash1983 and @mzch 

Where you able to fully refresh (ctrl+shit+r) Rocket.Chat as mentioned by @dasfreak ? 

This will clear the cache and redownload latest.

Thanks!

**Comment by mzch** [comment]
Yes, but Rocket.Chat stay unchanged.

**Comment by dudanogueira** [comment]
you mean, you still has this Issue going on?

If that's the case, can you ping me on open?
https://open.rocket.chat/direct/duda.nogueira

Maybe, if yo create a user for me I can see this error myself and get better clue out of it. THanks!!

**Comment by mzch** [comment]
Well, I can't create an account because I can't login...Please try oauth login via Github so my instance will reproduce this issue.

**Comment by mzch** [comment]
In `4.2.1` this issue is fixed. Thanks!

**Comment by mzch** [comment]
Oh, the same issue happens in `4.2.1`, too.

<img width="1590" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/145788926-1910f926-6f69-498c-ae09-c52c98b1bc09.png">

- server log
```
Dec 12 16:12:04 n13 rocketchat[79206]: {"level":40,"time":"2021-12-13T00:12:04.887Z","pid":79206,"hostname":"n13","name":"SyncedCron","msg":"Failed to send usage report"}
Dec 12 18:12:02 n13 rocketchat[79206]: {"level":40,"time":"2021-12-13T02:12:02.022Z","pid":79206,"hostname":"n13","name":"SyncedCron","msg":"Failed to send usage report"}
Dec 12 19:12:04 n13 rocketchat[79206]: {"level":40,"time":"2021-12-13T03:12:04.326Z","pid":79206,"hostname":"n13","name":"SyncedCron","msg":"Failed to send usage report"}
Dec 12 21:12:02 n13 rocketchat[79206]: {"level":40,"time":"2021-12-13T05:12:02.939Z","pid":79206,"hostname":"n13","name":"SyncedCron","msg":"Failed to send usage report"}
Dec 12 22:12:04 n13 rocketchat[79206]: {"level":40,"time":"2021-12-13T06:12:04.385Z","pid":79206,"hostname":"n13","name":"SyncedCron","msg":"Failed to send usage report"}
Dec 13 00:00:01 n13 rocketchat[79206]: {"level":50,"time":"2021-12-13T08:00:01.133Z","pid":79206,"hostname":"n13","name":"System","err":{"type":"Error","message":"failed [401] {\"status\":401}","stack":"Error: failed [401] {\"status\":401}\n    at Object.exports.makeErrorByStatus (packages/http.js:177:10)\n    at Request._callback (packages/http.js:141:24)\n    at Request.self.callback (/srv/Rocket.Chat/bundle-4.2.1/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:314:20)\n    at Request.EventEmitter.emit (domain.js:483:12)\n    at Request.<anonymous> (/srv/Rocket.Chat/bundle-4.2.1/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:314:20)\n    at Request.EventEmitter.emit (domain.js:483:12)\n    at IncomingMessage.<anonymous> (/srv/Rocket.Chat/bundle-4.2.1/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:420:28)\n    at IncomingMessage.emit (events.js:326:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:483:12)\n    at endReadableNT (_stream_readable.js:1241:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","response":{"statusCode":401,"content":"{\"status\":401}","headers":{"access-control-allow-headers":"Content-Type, Authorization, Content-Length, Last-Event-ID, X-Requested-With","access-control-allow-methods":"GET, PUT, POST, DELETE, OPTIONS","access-control-allow-origin":"*","access-control-expose-headers":"Content-Type, Authorization, Cache-Control, Expires, Pragma, X-powered-by","cache-control":"private, no-cache, no-store, must-revalidate","content-length":"14","content-type":"application/json; charset=utf-8","date":"Mon, 13 Dec 2021 08:00:01 GMT","expires":"-1","pragma":"no-cache","x-fleet-version":"-5181db3","x-powered-by":"Rocket Fuel and Rocketeers","connection":"close"},"data":{"status":401}}},"msg":"failed [401] {\"status\":401}"}
Dec 13 00:12:02 n13 rocketchat[79206]: {"level":40,"time":"2021-12-13T08:12:02.683Z","pid":79206,"hostname":"n13","name":"SyncedCron","msg":"Failed to send usage report"}
Dec 13 01:12:08 n13 rocketchat[79206]: {"level":40,"time":"2021-12-13T09:12:08.750Z","pid":79206,"hostname":"n13","name":"SyncedCron","msg":"Failed to send usage report"}
Dec 13 01:38:11 n13 rocketchat[79206]: {"line":"69","file":"oauth_server.js","message":"Unable to base64 decode state from OAuth query: undefined","time":{"$date":1639388291788},"level":"warn"}
Dec 13 01:38:11 n13 rocketchat[79206]: {"line":"69","file":"oauth_server.js","message":"Unable to base64 decode state from OAuth query: undefined","time":{"$date":1639388291795},"level":"warn"}
Dec 13 01:39:53 n13 rocketchat[79206]: {"level":50,"time":"2021-12-13T09:39:53.469Z","pid":79206,"hostname":"n13","name":"System","msg":"Exception while invoking method saveSettings 'TOTP Required [totp-required]'"}
```

**Comment by mzch** [comment]
I confirmed fixing this error in `4.2.2`. Thanks.
