### ISSUE TITLE
Failed upgrade 4.0.6 to 4.2.0

### ISSUE THREAD

**Issue by lightweight** [RocketChat/Rocket.Chat#23836]
### Description:

I run several Docker Compose-based R.C instances, currently on version 4.0.6. I recently successfully upgrade MongoDB from 4.0 to 4.2 to 4.4. I have subsequently tried to upgrade the R.C code from version 4.0.6 to the latest, at this point 4.2.0. 

This process fails repeatedly with the following errors:

```
rocketchat-oeru_1     | {"level":20,"time":"2021-12-01T20:38:16.462Z","pid":440,"hostname":"a2144cb8ae5b","name":"Email Intercepter","msg":"Starting Email Intercepter..."}
rocketchat-oeru_1     | {"level":20,"time":"2021-12-01T20:38:16.462Z","pid":440,"hostname":"a2144cb8ae5b","name":"Email Intercepter","msg":"Starting new IMAP instance......"}
rocketchat-oeru_1     | {"level":30,"time":"2021-12-01T20:38:16.476Z","pid":440,"hostname":"a2144cb8ae5b","name":"System","msg":"Updating process.env.MAIL_URL"}
rocketchat-oeru_1     | {"level":20,"time":"2021-12-01T20:38:16.712Z","pid":440,"hostname":"a2144cb8ae5b","name":"CustomOAuth","msg":"Init CustomOAuth 'tokenpass' {\"serverURL\":\"\",\"identityPath\":\"/oauth/user\",\"authorizePath\":\"/oauth/authorize\",\"tokenPath\":\"/oauth/access-token\",\"scope\":\"user,tca,private-balances\",\"tokenSentVia\":\"payload\",\"usernameField\":\"username\",\"mergeUsers\":true,\"addAutopublishFields\":{\"forLoggedInUser\":[\"services.tokenpass\"],\"forOtherUsers\":[\"services.tokenpass.name\"]},\"accessTokenParam\":\"access_token\"}"}
rocketchat-oeru_1     | {"level":30,"time":"2021-12-01T20:38:16.715Z","pid":440,"hostname":"a2144cb8ae5b","name":"System","msg":"Setting default file store to GridFS"}
rocketchat-oeru_1     | Error occurred ...
rocketchat-oeru_1     | meteor://💻app/app/app.js:196020
rocketchat-oeru_1     |       throw err;
rocketchat-oeru_1     |       ^
rocketchat-oeru_1     | 
rocketchat-oeru_1     | Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
rocketchat-oeru_1     |     at doWrite (_stream_writable.js:399:19)
rocketchat-oeru_1     |     at clearBuffer (_stream_writable.js:542:7)
rocketchat-oeru_1     |     at Socket.Writable.uncork (_stream_writable.js:338:7)
rocketchat-oeru_1     |     at JSStreamSocket.doWrite (internal/js_stream_socket.js:176:17)
rocketchat-oeru_1     |     at JSStream.onwrite (internal/js_stream_socket.js:33:57)
rocketchat-oeru_1     |     at JSStream.callbackTrampoline (internal/async_hooks.js:126:14)
rocketchat-oeru_1     |     at Socket.ondata (internal/js_stream_socket.js:77:22)
rocketchat-oeru_1     |     at Socket.emit (events.js:314:20)
rocketchat-oeru_1     |     at Socket.EventEmitter.emit (domain.js:483:12)
rocketchat-oeru_1     |     at addChunk (_stream_readable.js:297:12)
rocketchat-oeru_1     |     at readableAddChunk (_stream_readable.js:272:9)
rocketchat-oeru_1     |     at Socket.Readable.push (_stream_readable.js:213:10)
rocketchat-oeru_1     |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
rocketchat-oeru_1     |     at TCP.callbackTrampoline (internal/async_hooks.js:126:14) {
rocketchat-oeru_1     |   code: 'ERR_STREAM_DESTROYED',
rocketchat-oeru_1     |   source: 'socket'
rocketchat-oeru_1     | }

```
This error repeats until the upgrade process gives up. 

### Steps to reproduce:

1. In the docker-compose.yml file, alter `image: rocketchat/rocket.chat:4.0.6` to `image: rocketchat/rocket.chat:latest`,
2. run `docker-compose pull && docker-compose up -d && docker-compose logs -f` 
3. monitor the resulting log 

### Expected behavior:

Under normal circumstances, the R.C code triggers an upgrade of the data in MongoDB to conform to the requirements of the latest version of the R.C code in the rocketchat Docker container, and eventually provide a log message announcing that the Rocket.Chat instance has successfully been upgraded to version 4.2.0. 

For example if I revert the docker-compose.yml changes so that I'm using the 4.0.6 R.C image again and restart, I see this:

```
rocketchat-oeru_1     | +----------------------------------------------+
rocketchat-oeru_1     | |                SERVER RUNNING                |
rocketchat-oeru_1     | +----------------------------------------------+
rocketchat-oeru_1     | |                                              |
rocketchat-oeru_1     | |  Rocket.Chat Version: 4.0.6                  |
rocketchat-oeru_1     | |       NodeJS Version: 12.22.1 - x64          |
rocketchat-oeru_1     | |      MongoDB Version: 4.4.10                 |
rocketchat-oeru_1     | |       MongoDB Engine: wiredTiger             |
rocketchat-oeru_1     | |             Platform: linux                  |
rocketchat-oeru_1     | |         Process Port: 3000                   |
rocketchat-oeru_1     | |             Site URL: https://chat.oeru.org  |
rocketchat-oeru_1     | |     ReplicaSet OpLog: Enabled                |
rocketchat-oeru_1     | |          Commit Hash: d2efff0169             |
rocketchat-oeru_1     | |        Commit Branch: HEAD                   |
rocketchat-oeru_1     | |                                              |
rocketchat-oeru_1     | +----------------------------------------------+
```

### Actual behavior:

Instead, I see the 'Error Occurred' and surrounding messages repeated every few seconds until the system gives up due to too many failed upgrade attempts. 

### Server Setup Information:

- Version of Rocket.Chat Server:  4.0.6
- Operating System: Host: Ubuntu 18.04
- Deployment Method: Docker Compose
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1 - x64 
- MongoDB Version: 4.4.10

### Client Setup Information

- Desktop App or Browser Version: n/a
- Operating System: n/a

### Additional context

Due to the mention of the FileSystem file store setting just prior to the error, I thought the issue might be related to the fact that the 

Note: I maintain other R.C instances which have the same deployment approach and versions, and similar configurations, fail to upgrade with the same error. 

I have also had several other R.C instances (which have almost no use and therefore almost no content) which *have* upgraded to 4.2.0 without incident. These still have the default 'GridFS' file store configured.

### Relevant logs:

```
rocketchat-oeru_1     | {"level":20,"time":"2021-12-01T20:38:16.462Z","pid":440,"hostname":"a2144cb8ae5b","name":"Email Intercepter","msg":"Starting Email Intercepter..."}
rocketchat-oeru_1     | {"level":20,"time":"2021-12-01T20:38:16.462Z","pid":440,"hostname":"a2144cb8ae5b","name":"Email Intercepter","msg":"Starting new IMAP instance......"}
rocketchat-oeru_1     | {"level":30,"time":"2021-12-01T20:38:16.476Z","pid":440,"hostname":"a2144cb8ae5b","name":"System","msg":"Updating process.env.MAIL_URL"}
rocketchat-oeru_1     | {"level":20,"time":"2021-12-01T20:38:16.712Z","pid":440,"hostname":"a2144cb8ae5b","name":"CustomOAuth","msg":"Init CustomOAuth 'tokenpass' {\"serverURL\":\"\",\"identityPath\":\"/oauth/user\",\"authorizePath\":\"/oauth/authorize\",\"tokenPath\":\"/oauth/access-token\",\"scope\":\"user,tca,private-balances\",\"tokenSentVia\":\"payload\",\"usernameField\":\"username\",\"mergeUsers\":true,\"addAutopublishFields\":{\"forLoggedInUser\":[\"services.tokenpass\"],\"forOtherUsers\":[\"services.tokenpass.name\"]},\"accessTokenParam\":\"access_token\"}"}
rocketchat-oeru_1     | {"level":30,"time":"2021-12-01T20:38:16.715Z","pid":440,"hostname":"a2144cb8ae5b","name":"System","msg":"Setting default file store to GridFS"}
rocketchat-oeru_1     | Error occurred ...
rocketchat-oeru_1     | meteor://💻app/app/app.js:196020
rocketchat-oeru_1     |       throw err;
rocketchat-oeru_1     |       ^
rocketchat-oeru_1     | 
rocketchat-oeru_1     | Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
rocketchat-oeru_1     |     at doWrite (_stream_writable.js:399:19)
rocketchat-oeru_1     |     at clearBuffer (_stream_writable.js:542:7)
rocketchat-oeru_1     |     at Socket.Writable.uncork (_stream_writable.js:338:7)
rocketchat-oeru_1     |     at JSStreamSocket.doWrite (internal/js_stream_socket.js:176:17)
rocketchat-oeru_1     |     at JSStream.onwrite (internal/js_stream_socket.js:33:57)
rocketchat-oeru_1     |     at JSStream.callbackTrampoline (internal/async_hooks.js:126:14)
rocketchat-oeru_1     |     at Socket.ondata (internal/js_stream_socket.js:77:22)
rocketchat-oeru_1     |     at Socket.emit (events.js:314:20)
rocketchat-oeru_1     |     at Socket.EventEmitter.emit (domain.js:483:12)
rocketchat-oeru_1     |     at addChunk (_stream_readable.js:297:12)
rocketchat-oeru_1     |     at readableAddChunk (_stream_readable.js:272:9)
rocketchat-oeru_1     |     at Socket.Readable.push (_stream_readable.js:213:10)
rocketchat-oeru_1     |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
rocketchat-oeru_1     |     at TCP.callbackTrampoline (internal/async_hooks.js:126:14) {
rocketchat-oeru_1     |   code: 'ERR_STREAM_DESTROYED',
rocketchat-oeru_1     |   source: 'socket'
rocketchat-oeru_1     | }
<!-- Logs from both SERVER and BROWSER -->
<!-- For more information about collecting logs please see: https://rocket.chat/docs/contributing/reporting-issues#gathering-logs -->
```

**Comment by ankar84** [comment]
I successfully upgraded to 4.2.0 from 4.1.2, can you try to update to 4.1.2 first?

> to `image: rocketchat/rocket.chat:latest`,

My personal advice to you to avoid using `latest` tag.
To fully control whole update process **use specific version tags** like `4.2.0`

**Comment by lightweight** [comment]
You're right re avoiding the `latest` tag... I just tried an upgrade from 4.0.6 to 4.1.2, and I got the same exact error: 

```
rocketchat-oeru_1     | {"level":20,"time":"2021-12-02T09:51:10.525Z","pid":24,"hostname":"e2a2adfe7eb6","name":"Email Intercepter","msg":"Starting Email Intercepter..."}
rocketchat-oeru_1     | {"level":20,"time":"2021-12-02T09:51:10.526Z","pid":24,"hostname":"e2a2adfe7eb6","name":"Email Intercepter","msg":"Starting new IMAP instance......"}
rocketchat-oeru_1     | {"level":30,"time":"2021-12-02T09:51:10.543Z","pid":24,"hostname":"e2a2adfe7eb6","name":"System","msg":"Updating process.env.MAIL_URL"}
rocketchat-oeru_1     | {"level":20,"time":"2021-12-02T09:51:10.778Z","pid":24,"hostname":"e2a2adfe7eb6","name":"CustomOAuth","msg":"Init CustomOAuth 'tokenpass' {\"serverURL\":\"\",\"identityPath\":\"/oauth/user\",\"authorizePath\":\"/oauth/authorize\",\"tokenPath\":\"/oauth/access-token\",\"scope\":\"user,tca,private-balances\",\"tokenSentVia\":\"payload\",\"usernameField\":\"username\",\"mergeUsers\":true,\"addAutopublishFields\":{\"forLoggedInUser\":[\"services.tokenpass\"],\"forOtherUsers\":[\"services.tokenpass.name\"]},\"accessTokenParam\":\"access_token\"}"}
rocketchat-oeru_1     | {"level":30,"time":"2021-12-02T09:51:10.784Z","pid":24,"hostname":"e2a2adfe7eb6","name":"System","msg":"Setting default file store to FileSystem"}
rocketchat-oeru_1     | Error occurred ...
rocketchat-oeru_1     | meteor://💻app/app/app.js:193960
rocketchat-oeru_1     |       throw err;
rocketchat-oeru_1     |       ^
rocketchat-oeru_1     | 
rocketchat-oeru_1     | Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
rocketchat-oeru_1     |     at doWrite (_stream_writable.js:399:19)
rocketchat-oeru_1     |     at clearBuffer (_stream_writable.js:542:7)
rocketchat-oeru_1     |     at Socket.Writable.uncork (_stream_writable.js:338:7)
rocketchat-oeru_1     |     at JSStreamSocket.doWrite (internal/js_stream_socket.js:176:17)
rocketchat-oeru_1     |     at JSStream.onwrite (internal/js_stream_socket.js:33:57)
rocketchat-oeru_1     |     at JSStream.callbackTrampoline (internal/async_hooks.js:126:14)
rocketchat-oeru_1     |     at Socket.ondata (internal/js_stream_socket.js:77:22)
rocketchat-oeru_1     |     at Socket.emit (events.js:314:20)
rocketchat-oeru_1     |     at Socket.EventEmitter.emit (domain.js:483:12)
rocketchat-oeru_1     |     at addChunk (_stream_readable.js:297:12)
rocketchat-oeru_1     |     at readableAddChunk (_stream_readable.js:272:9)
rocketchat-oeru_1     |     at Socket.Readable.push (_stream_readable.js:213:10)
rocketchat-oeru_1     |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
rocketchat-oeru_1     |     at TCP.callbackTrampoline (internal/async_hooks.js:126:14) {
rocketchat-oeru_1     |   code: 'ERR_STREAM_DESTROYED',
rocketchat-oeru_1     |   source: 'socket'
rocketchat-oeru_1     | }
```

**Comment by ankar84** [comment]
> I just tried an upgrade from 4.0.6 to 4.1.2, and unfortunately got the same exact error:

Strange. Looks like it something with mongo. We definitely need a teem support here.
@debdutdeb can you help?

**Comment by lightweight** [comment]
I'm keen to upgrade my various R.C instance from 4.0.6 to the latest version (4.3.0, it seems)... any further thoughts? Or even hints where I should be looking based on the error? Sounds like @ankar84 thinks it's MongoDB-related... do I need to downgrade from 4.4 back to 4.2?

**Comment by lightweight** [comment]
This needs the attention of someone with deep MongoDB and Rocket.Chat knowledge, e.g. on the core team. I still haven't upgraded from 4.0.6... I'm getting pretty frustrated. This seems to be affecting a lot of people. I went to quite a bit of trouble to upgrade my MongoDBs from 4.0 to 4.4 as instructed, but now can't upgrade R.C...

I'm going to try back-grading the MongoDB on one of my instances to 4.2 (or, if necessary, 4.0), try the upgrade, and then, if successful, return MongoDB to 4.4... (I'll do relevant backups first to ensure I can get back to the current state, of course)...

**Comment by lightweight** [comment]
Ok, I managed to get the upgrade to work - from 4.0.6 to 4.4.2. 

I downgraded Mongo to 4.2 from 4.4, and attempted the upgrade. I got another error in app.js, but this time it was different, and it turns out related to #24061 and I ran the changes recommended there in my rocketchat db on Mongo: 

```
db.getCollection('rocketchat_settings').find({_id: "Direct_Reply_Enable"}).pretty()
db.getCollection('rocketchat_settings').update({_id: "Direct_Reply_Enable"}, {$set: {value: false}})
```
as it turns out I did have "Direct_Reply_Enable" set to true... 

After that, I was able to run the upgrade, and it worked without issue. Subsequently I returned my MongoDB to 4.4 and all seems hunky dory. In hindsight, I'm not entirely sure that the downgrade from 4.4->4.2 was necessary (i.e. I could've tried to disable Direct_Reply_Enable in 4.4, too, so if you're experiencing the same problem, perhaps try it in 4.4 first before going to the trouble of downgrading.

Hope this helps someone!

**Comment by railsmechanic** [comment]
Had the same issue upgrading to v4.5.4. Disabling the `Direct_Reply_Enable` worked for me. Now I check whether all other features works as expected.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
