### ISSUE TITLE
Rocketchaat crashing after upgrade to 4.2

### ISSUE THREAD

**Issue by aforsythe** [RocketChat/Rocket.Chat#23863]
### Description:

Rocketchaat crashing after upgrade to 4.2

### Steps to reproduce:

Upgrade Mongodb
Upgrade RocketChat

### Expected behavior:

everyting works

### Actual behavior:
```
Last login: Fri Dec  3 21:39:40 2021 from 38.73.241.87
root@rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01:~# systemctl status rocketchat
● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2021-12-03 21:55:30 UTC; 4h 45min ago
  Process: 2340 ExecStart=/usr/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 2340 (code=exited, status=1/FAILURE)

Dec 03 21:55:30 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[2340]:     compatible: true,
Dec 03 21:55:30 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[2340]:     compatibilityError: null,
Dec 03 21:55:30 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[2340]:     logicalSessionTimeoutMinutes: null,
Dec 03 21:55:30 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[2340]:     heartbeatFrequencyMS: 10000,
Dec 03 21:55:30 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[2340]:     localThresholdMS: 15,
Dec 03 21:55:30 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[2340]:     commonWireVersion: 7
Dec 03 21:55:30 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[2340]:   }
Dec 03 21:55:30 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[2340]: }
Dec 03 21:55:30 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Dec 03 21:55:30 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 systemd[1]: rocketchat.service: Failed with result 'exit-code'.
```

### Server Setup Information:

'''
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
'''

'''
mongod --version
db version v4.0.3
git version: 7ea530946fa7880364d88c8d8b6026bbc9ffa48c
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1804
    distarch: x86_64
    target_arch: x86_64
'''

'''
node -v
v12.18.4
'''

### Client Setup Information

```
rocketchatctl 
'''

**Comment by aforsythe** [comment]
From the log

```
Dec  6 19:40:48 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 systemd[1]: Started The Rocket.Chat server.
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]: /opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:313
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]: #011#011#011#011#011#011throw(ex);
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]: #011#011#011#011#011#011^
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]: MongoServerSelectionError: Server selection timed out after 30000 ms
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     at Timeout._onTimeout (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/sdam/topology.js:439:30)
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     at listOnTimeout (internal/timers.js:554:17)
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     at processTimers (internal/timers.js:497:7) {
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:   reason: TopologyDescription {
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     type: 'ReplicaSetNoPrimary',
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     setName: null,
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     maxSetVersion: null,
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     maxElectionId: null,
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     servers: Map {},
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     stale: false,
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     compatible: true,
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     compatibilityError: null,
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     logicalSessionTimeoutMinutes: null,
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     heartbeatFrequencyMS: 10000,
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     localThresholdMS: 15,
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:     commonWireVersion: 7
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]:   }
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 rocketchat[11248]: }
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Dec  6 19:41:20 rocketchat-ubuntu-s-2vcpu-4gb-nyc1-01 systemd[1]: rocketchat.service: Failed with result 'exit-code'.
```

**Comment by debdutdeb** [comment]
Hi there,

Sorry for the late response.

Could you please check is mongod is running or not?

```
systemctl status mongod
```

**Comment by robertfromont** [comment]
I've seen this recently, and the cause turned out to be that I had inadvertently un-set replication in `/etc/mongod.conf`

The fix for me was to run:
```
sudo sed -i "s/^#replication:/replication:\n  replSetName: rs01/" /etc/mongod.conf
```
