### ISSUE TITLE
RocketChat Server crash - JavaScript heap out of memory - triggered by client 

### ISSUE THREAD

**Issue by amsnek** [RocketChat/Rocket.Chat#23909]
### Description:

Rocketchat Server crashes /  JavaScript heap out of memory

### Steps to reproduce:

unknown -> not reproduceable in test (maybe not enough users active there)
1) start electron rocketchat client 3.6.0
2) connect to server
3) right click on server -> clear cache
4) right click on server -> clear storage cache
5) client disconnects and server was in crashed state

### Expected behavior:

no server crash

### Actual behavior:

 FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory

### Server Setup Information:

Rocket.Chat Version: 4.1.2
NodeJS Version: 12.22.5 - x64
MongoDB Version: 4.4.10
Platform: linux
Process Port: 3000
Site URL: https://chat.redacted
ReplicaSet OpLog: Enabled
Commit Hash: 2aba8d2d82
Commit Branch: HEAD

- Version of Rocket.Chat Server: 4.1.2
- Operating System: Red Hat Enterprise Linux release 8.5 (Ootpa)
- Deployment Method: custom
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.5 - x64
- MongoDB Version: 4.4.10
- MongoDB Engine: wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Rocketchat 3.6.0
- Operating System: Windows10

### Relevant logs:

 === UnHandledPromiseRejection ===
 RangeError: Out of memory
    at Fiber.run (<anonymous>)
    at makeNewFiber (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:71:11)
    at FiberPool.run (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:92:37)
    at Function.Promise.asyncApply (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:135:22)
    at MessagesRaw.findOne (app/models/server/raw/BaseRaw.ts:110:15)
    at server/modules/watchers/watchers.module.ts:115:66
    at /data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 ---------------------------------
 Errors like this can cause oplog processing errors.
 Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
 Future node.js versions will automatically exit the process
 =================================
 === UnHandledPromiseRejection ===
 RangeError: Out of memory
    at Fiber.run (<anonymous>)
    at makeNewFiber (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:71:11)
    at FiberPool.run (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:92:37)
    at Function.Promise.asyncApply (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:135:22)
    at MessagesRaw.findOne (app/models/server/raw/BaseRaw.ts:110:15)
    at server/modules/watchers/watchers.module.ts:115:66
    at /data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 ---------------------------------
 Errors like this can cause oplog processing errors.
 Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
 Future node.js versions will automatically exit the process
 =================================
 === UnHandledPromiseRejection ===
 RangeError: Out of memory
    at Fiber.run (<anonymous>)
    at makeNewFiber (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:71:11)
    at FiberPool.run (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:92:37)
    at Function.Promise.asyncApply (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:135:22)
    at MessagesRaw.findOne (app/models/server/raw/BaseRaw.ts:110:15)
    at server/modules/watchers/watchers.module.ts:115:66
    at /data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 ---------------------------------
 Errors like this can cause oplog processing errors.
 Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
 Future node.js versions will automatically exit the process
 =================================
 === UnHandledPromiseRejection ===
 RangeError: Out of memory
    at Fiber.run (<anonymous>)
    at makeNewFiber (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:71:11)
    at FiberPool.run (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:92:37)
    at Function.Promise.asyncApply (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:135:22)
    at MessagesRaw.findOne (app/models/server/raw/BaseRaw.ts:110:15)
    at server/modules/watchers/watchers.module.ts:115:66
    at /data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 ---------------------------------
 Errors like this can cause oplog processing errors.
 Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
 Future node.js versions will automatically exit the process
 =================================
 === UnHandledPromiseRejection ===
 RangeError: Out of memory
    at Fiber.run (<anonymous>)
    at makeNewFiber (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:71:11)
    at FiberPool.run (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:92:37)
    at Function.Promise.asyncApply (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:135:22)
    at MessagesRaw.findOne (app/models/server/raw/BaseRaw.ts:110:15)
    at server/modules/watchers/watchers.module.ts:115:66
    at /data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 ---------------------------------
 Errors like this can cause oplog processing errors.
 Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
 Future node.js versions will automatically exit the process
 =================================
 === UnHandledPromiseRejection ===
 RangeError: Out of memory
    at Fiber.run (<anonymous>)
    at makeNewFiber (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:71:11)
    at FiberPool.run (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:92:37)
    at Function.Promise.asyncApply (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:135:22)
    at MessagesRaw.findOne (app/models/server/raw/BaseRaw.ts:110:15)
    at server/modules/watchers/watchers.module.ts:115:66
    at /data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 ---------------------------------
 Errors like this can cause oplog processing errors.
 Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
 Future node.js versions will automatically exit the process
 =================================
 === UnHandledPromiseRejection ===
 RangeError: Out of memory
    at Fiber.run (<anonymous>)
    at makeNewFiber (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:71:11)
    at FiberPool.run (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:92:37)
    at Function.Promise.asyncApply (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:135:22)
    at MessagesRaw.findOne (app/models/server/raw/BaseRaw.ts:110:15)
    at server/modules/watchers/watchers.module.ts:115:66
    at /data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 ---------------------------------
 Errors like this can cause oplog processing errors.
 Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
 Future node.js versions will automatically exit the process
 =================================
 === UnHandledPromiseRejection ===
 RangeError: Out of memory
    at Fiber.run (<anonymous>)
    at makeNewFiber (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:71:11)
    at FiberPool.run (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:92:37)
    at Function.Promise.asyncApply (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:135:22)
    at MessagesRaw.findOne (app/models/server/raw/BaseRaw.ts:110:15)
    at server/modules/watchers/watchers.module.ts:115:66
    at /data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 ---------------------------------
 Errors like this can cause oplog processing errors.
 Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
 Future node.js versions will automatically exit the process
 =================================
 === UnHandledPromiseRejection ===
 RangeError: Out of memory
    at Fiber.run (<anonymous>)
    at makeNewFiber (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:71:11)
    at FiberPool.run (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:92:37)
    at Function.Promise.asyncApply (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:135:22)
    at MessagesRaw.findOne (app/models/server/raw/BaseRaw.ts:110:15)
    at server/modules/watchers/watchers.module.ts:115:66
    at /data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 ---------------------------------
 Errors like this can cause oplog processing errors.
 Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
 Future node.js versions will automatically exit the process
 =================================
 === UnHandledPromiseRejection ===
 RangeError: Out of memory
    at Fiber.run (<anonymous>)
    at makeNewFiber (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:71:11)
    at FiberPool.run (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:92:37)
    at Function.Promise.asyncApply (/data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:135:22)
    at MessagesRaw.findOne (app/models/server/raw/BaseRaw.ts:110:15)
    at server/modules/watchers/watchers.module.ts:115:66
    at /data/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 ---------------------------------
 Errors like this can cause oplog processing errors.
 Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
 Future node.js versions will automatically exit the process
 =================================
 === UnHandledPromiseRejection ===
 <--- Last few GCs --->
 [2067276:0x55e7c4b8c6a0] 42016041 ms: Scavenge 626.3 (653.5) -> 621.5 (659.0) MB, 81.7 / 0.9 ms  (average mu = 1.000, current mu = 0.882) allocation failure
 [2067276:0x55e7c4b8c6a0] 42016184 ms: Scavenge 631.6 (659.0) -> 626.8 (664.2) MB, 86.1 / 0.9 ms  (average mu = 1.000, current mu = 0.882) allocation failure
 [2067276:0x55e7c4b8c6a0] 42016432 ms: Scavenge 636.7 (664.2) -> 632.5 (664.5) MB, 189.5 / 0.9 ms  (average mu = 1.000, current mu = 0.882) allocation failure
 <--- JS stacktrace --->
 Cannot get stack trace in GC.
 FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory
 1: 0x55e7c278e604 node::Abort() [/usr/bin/node]
 2: 0x55e7c267b6fa node::OnFatalError(char const*, char const*) [/usr/bin/node]
 3: 0x55e7c292651a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0x55e7c29267a6 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0x55e7c2abb789  [/usr/bin/node]
 6: 0x55e7c2b0a0d8 v8::internal::MarkCompactCollector::Evacuate() [/usr/bin/node]
 7: 0x55e7c2b0d6b0 v8::internal::MarkCompactCollector::CollectGarbage() [/usr/bin/node]
 8: 0x55e7c2ad049c v8::internal::Heap::MarkCompact() [/usr/bin/node]
 9: 0x55e7c2ad13cb v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node]
 10: 0x55e7c2ad1b57 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 11: 0x55e7c2ad41b5 v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
 12: 0x55e7c2ad4729 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
 13: 0x55e7c2a9d932 v8::internal::Factory::New(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationType) [/usr/bin/node]
 14: 0x55e7c2aa6648 v8::internal::Factory::NewFunction(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>, v8::internal::AllocationType) [/usr/bin/node]
 15: 0x55e7c2aa6ac5 v8::internal::Factory::NewFunctionFromSharedFunctionInfo(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>, v8::internal::Handle<v8::internal::FeedbackCell>, v8::internal::AllocationType) [/usr/bin/node]
 16: 0x55e7c2dd5946 v8::internal::Runtime_NewClosure_Tenured(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
 17: 0x55e7c31081f9  [/usr/bin/node]

**Comment by fdellwing** [comment]
RC does have a slight, but noticeable memory leak. You action might have been the nail in the coffin.

**Comment by amsnek** [comment]
ah, that is good to know. so best to restart at least once / nightly? as workaround for now?

**Comment by fdellwing** [comment]
For our instance (3x cluster with 2GB each for around 30 users) I usually restart once a month. But I know some people are restarting a lot more frequent.

**Comment by amsnek** [comment]
*edit: i already restart it seems nightly. Hmm hopefully this leak will be fixed in some upcoming release.
well never hit this issue so far, so i suppose thats a good sign. thanks for the input!

**Comment by juzser** [comment]
I get the same issue but with CPU, I have to restart server weekly.
Please check my server graph below you will see, sometimes it reaches 100%, and shutdown automatically.

<img width="971" alt="Screen Shot 2021-12-13 at 10 12 56" src="https://user-images.githubusercontent.com/5735071/145746676-2f93e9d4-8c07-4e0b-9689-6e8696214289.png">

**Comment by amsnek** [comment]
interesting, i checked the metrics on my system, but the cpu spikes i dont observe. maybe because restarting daily but not sure. will observe this as well now :)

**Comment by juzser** [comment]
Update:
My system is running good these days, and no longer shutdown, because I see there is a problem with file upload feature. 
I reduced the maximum upload file size (From 50mb to 3mb) and everything seem alright. 
As I checked the log, I see somehow when an user uploads a large file, they get stuck at 0% for a long time, and cannot cancel the progress. I guess, the upload pipeline cannot be closed and the system keep retrying the task, that why the memory comes up.

Maybe I think RC team should add a timeout for no responding upload progress.
Hope this helps.

**Comment by Mathiasdm** [comment]
Not sure if this is related, but with 4.5.3, we are also seeing out-of-memory issues:

<--- Last few GCs --->

[1:0x5811600] 28290833 ms: Scavenge 541.5 (574.2) -> 534.0 (574.5) MB, 218.2 / 2.0 ms  (average mu = 1.000, current mu = 0.965) task 
[1:0x5811600] 28291398 ms: Scavenge 543.2 (575.3) -> 536.5 (575.0) MB, 478.2 / 1.7 ms  (average mu = 1.000, current mu = 0.965) task 
[1:0x5811600] 28292082 ms: Scavenge 542.7 (575.0) -> 538.4 (575.2) MB, 622.3 / 1.6 ms  (average mu = 1.000, current mu = 0.965) task 


<--- JS stacktrace --->

FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory
 1: 0xa38a30 node::Abort() [node]
 2: 0x96e0af node::FatalError(char const*, char const*) [node]
 3: 0xbb7ebe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xbb8237 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd74445  [node]
 6: 0xdb4097  [node]
 7: 0xdc57d1 v8::internal::MarkCompactCollector::CollectGarbage() [node]
 8: 0xd81a98 v8::internal::Heap::MarkCompact() [node]
 9: 0xd83588 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
10: 0xd869cc v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
11: 0xd4c19d v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
12: 0xd483f9 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [node]
13: 0xd484b4 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [node]
14: 0xf8fb4e v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::AllocationType) [node]
15: 0xf8fce6 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [node]
16: 0xf90741 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Shrink(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>) [node]
17: 0x1081358 v8::internal::Runtime_MapShrink(int, unsigned long*, v8::internal::Isolate*) [node]
18: 0x14467f9  [node]
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at

**Comment by Dartv** [comment]
@Mathiasdm have been seeing this recently too. Did you figure it out?
