### ISSUE TITLE
[LDAP] ominous error message in logs - user not found - without stating username

### ISSUE THREAD

**Issue by sgohl** [RocketChat/Rocket.Chat#23949]
### Description:

Following error message appears constantly in the Logs:

```
{"level":50,"time":"2021-12-15T06:27:01.796Z","pid":1,"hostname":"a98600e97b9c","name":"LDAP","err":{"type":"Error","message":"User not found","stack":"Error: User not found<br>    at server/lib/ldap/Manager.ts:166:11<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"User not found"} 
```

Albeit this might be valid and true, but without stating the username I would like to consider the message as not complete – and therefore as a bug.

### Steps to reproduce:

Have LDAP and Users. And possibly one user which is some kind of faulty, not existing anymore, or anything like this.

### Expected behavior:

State the username in the error message

### Actual behavior:

username is missing in the error message

### Server Setup Information:

- Version of Rocket.Chat Server:  4.2.2
- Operating System: Fedora CoreOS
- Deployment Method:  docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 5.0.5

### Client Setup Information

- Desktop App or Browser Version: both, but not relevant
- Operating System: yes

### Additional context

nothing else

### Relevant logs:

```
{"level":50,"time":"2021-12-15T06:27:01.796Z","pid":1,"hostname":"a98600e97b9c","name":"LDAP","err":{"type":"Error","message":"User not found","stack":"Error: User not found<br>    at server/lib/ldap/Manager.ts:166:11<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"User not found"} 
```

**Comment by durbanbr** [comment]
I have the same problem!
