### ISSUE TITLE
 Cannot read property 'Symbol(kResourceStore)'

### ISSUE THREAD

**Issue by KevinLJJ** [RocketChat/Rocket.Chat#24032]
### Description:
I got an error when i started rocketchat service.

```
2 systemd: Started The Rocket.Chat server.
2 rocketchat: Localstore: store created at
2 rocketchat: Localstore: store created at
2 rocketchat: Localstore: store created at
2 rocketchat: TypeError: Cannot read property "Symbol (kResourcestore)" of undefined
2 rocketchat: at AsyncLocalstorage._propagate (async_hooks.js:281:34)
2 rocketchat: at AsyncHook. init (async_hooks.js:248:22)
2 rocketchat: at emitinitNative (internal/async_hooks.js:195:43)
2 rocketchat: at emitInitscript (internal/async hooks.js: 401:3)
2 rocketchat: at process.nextTick (internal/process/task queues. js:135:5)
2 rocketchat: at maybeReadMore (_stream readable. js:584:13)
2 rocketchat: at addchunk (_stream_readable. js:309:3)
2 rocketchat: at readableAddchunk (_ stream readable.js:272:9)
2 rocketchat: at ChangestreamCursor.Readable. push (_stream_readable.js:213:10)
2 rocketchat: at /opt/Rocket.Chat/programs/server/npm/node_modules/mongodb/lib/core/cursor.js:365:12
2 rocketchat: at handlecallback (/opt/Rocket.chat/programs/server/npm/node_modules/mongodb/lib/core/cursor. js:32:5)
2 rocketchat: at nextFunction (/opt/Rocket.chat/programs/server/npm/node_modules/mongodb/lib/core/cursor. js:867:5)
2 rocketchat: at /opt/Rocket.Chat/programs/server/npm/node_modules/mongodb/lib/core/cursor.js:811:7
2 rocketchat: at /opt/Rocket.Chat/programs/server/pm/node_modules/mongodb/lib/change_stream. js:363:7
2 rocketchat: at /opt/Rocket.chat/programs/server/mpm/node_modules/mongodb/lib/core/cursor.js:424:7
2 rocketchat: at /opt/Rocket.chat/programs/server/npm/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
2 rocketchat: at handleOperationResult (/opt/Rocket.chat/programs/server/mpm/node _modules/mongodb/lib/core/sdam/server.js:558:5)
2 rocketchat: at queryCallback (/opt/Rocket.chat/programs/server/mpm/node_modules/mongodb/lib/core/wireprotocol/get_more. js:54:5)
2 rocketchat: at Messagestream. messageHandler(/opt/Rocket.chat/programs/server/pm/node_modules/mongodb/lib/cmap/connection.js:281:5)
2 rocketchat: at Messagestream. emit (events.js: 314:20)
2 rocketchat: at Messagestream. EventEmitter.emit (domain. js:483:12)
2 rocketchat: at processIncomingData(/opt/Rocket.chat/programs/server/npm/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
2 systemd: rocketchat.service: main process exited, code=exited, status-1/FAILURE
2 systemd: Unit rocketchat.service entered failed state.
2 systemd: rocketchat.service failed.
```
**Ignore my host name '2' , please :)**

### Steps to reproduce:

1. mongodb started successed and I can connect it through robot3T.
2. I saw rocketchat created databases for itself.
3.  systemctl start rocketchat , the problem will reproduce.

### Server Setup Information:

- Version of Rocket.Chat Server:  4.2.2
- Operating System:  CentOS 7.8
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: none
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.10

### Client Setup Information

I can not connect to my server.

**Comment by sampaiodiego** [comment]
Are you sure you're using Node 12.22.1? I'm currently facing this issue while upgrading Meteor (on this PR https://github.com/RocketChat/Rocket.Chat/pull/24075) which uses Node v14
