### ISSUE TITLE
Upgrade from 4.2.2 to 4.3.0 failed "Error: Expected array for search criteria"

### ISSUE THREAD

**Issue by saschafoerster** [RocketChat/Rocket.Chat#24061]
### Description:

I'm having the same issue as here https://github.com/RocketChat/Rocket.Chat/issues/23590 and here https://github.com/RocketChat/Rocket.Chat/issues/23590 just with the newest version 4.3.0 (and haven't had that issue before)

I updated RocketChat from 4.2.2. to 4.3.0 and couldn't start it. Docker-Compose logs showed me this error message: "Expected array for search criteria". 

I tried the solutions from here and tried to manipulate MongoDB directly with no success. 
https://github.com/RocketChat/Rocket.Chat/issues/23590#issuecomment-966893336
https://github.com/RocketChat/Rocket.Chat/issues/23590#issuecomment-983489898

### Server Setup Information:

- Version of Rocket.Chat Server: 4.2.2. > 4.3.0
- Operating System:  Synology DSM 7.0
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: ?
- MongoDB Version: 4.4

### Relevant logs:

```
rocketchat_1  | /app/bundle/programs/server/npm/node_modules/imap/lib/Connection.js:573
rocketchat_1  |     throw new Error('Expected array for search criteria');
rocketchat_1  |     ^
rocketchat_1  | 
rocketchat_1  | Error: Expected array for search criteria
rocketchat_1  |     at Connection._search (/app/bundle/programs/server/npm/node_modules/imap/lib/Connection.js:573:11)
rocketchat_1  |     at Connection.search (/app/bundle/programs/server/npm/node_modules/imap/lib/Connection.js:566:8)
rocketchat_1  |     at IMAPIntercepter.getEmails (server/email/IMAPInterceptor.ts:99:13)
rocketchat_1  |     at server/email/IMAPInterceptor.ts:46:11
rocketchat_1  |     at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/imap/lib/Connection.js:432:7)
rocketchat_1  |     at Connection._resTagged (/app/bundle/programs/server/npm/node_modules/imap/lib/Connection.js:1535:22)
rocketchat_1  |     at Parser.<anonymous> (/app/bundle/programs/server/npm/node_modules/imap/lib/Connection.js:194:10)
rocketchat_1  |     at Parser.emit (events.js:314:20)
rocketchat_1  |     at Parser.EventEmitter.emit (domain.js:483:12)
rocketchat_1  |     at Parser._resTagged (/app/bundle/programs/server/npm/node_modules/imap/lib/Parser.js:175:10)
rocketchat_1  |     at Parser._parse (/app/bundle/programs/server/npm/node_modules/imap/lib/Parser.js:139:16)
rocketchat_1  |     at Parser._tryread (/app/bundle/programs/server/npm/node_modules/imap/lib/Parser.js:82:15)
rocketchat_1  |     at TLSSocket.Parser._cbReadable (/app/bundle/programs/server/npm/node_modules/imap/lib/Parser.js:53:12)
rocketchat_1  |     at TLSSocket.emit (events.js:314:20)
rocketchat_1  |     at TLSSocket.EventEmitter.emit (domain.js:483:12)
rocketchat_1  |     at emitReadable_ (_stream_readable.js:557:12)
rocketchat_1  |     at processTicksAndRejections (internal/process/task_queues.js:83:21)

```

**Comment by saschafoerster** [comment]
Problem solved, I forgot to switch into the right MongoDB. 

So, for anyone following: 

- docker-compose stop
- docker-compose start mongo 
- docker exec -it rocketchat_mongo_1 bash
  - mongo
    - show databases
    - use rocketchat
    - db.getCollection('rocketchat_settings').find({_id: "Direct_Reply_Enable"}).pretty()
    -  db.getCollection('rocketchat_settings').update({_id: "Direct_Reply_Enable"}, {$set: {value: false}})
    - exit
  - exit
- docker-compose up -d
