### ISSUE TITLE
Failed to deploy on Heroku

### ISSUE THREAD

**Issue by pixelpoesie** [RocketChat/Rocket.Chat#241]
The buildprocess failed with:

$ROOT_URL, if specified, must be an URL.
 !     Push rejected, failed to compile Node.js app

**Comment by Sing-Li** [comment]
@pixelpoesie -  Are you using the ONE-CLICK-DEPLOY button?

**Comment by engelgabriel** [comment]
I've tried for hours to get the ROOT_URL information from the environment, with no luck. :(

**Comment by pixelpoesie** [comment]
Ehm, so deploy to Heroku will not work after all? Hmm maybe then remove the Button in the readme.md...

**Comment by pixelpoesie** [comment]
Now it works. Didnt do any thing special since yesterday.  Thx!

**Comment by kohenkatz** [comment]
I got the same error today when using the one-click deploy button.  Here is the entire log:

```
-----> Fetching custom git buildpack... done
-----> Node.js app detected
-----> Installing node
-----> Installing meteor
Downloading Meteor distribution
                                                                  0.6%
        1.3%
                                                                      1.8%
                                                 2.3%
#########################################                                 57.8%
###################################################################       94.3%
#####################################################################     95.9%
####################################################################     96.4%
####################################################################     97.0%
#####################################################################    97.6%
Meteor 1.1.0.2 has been installed in your home directory (~/.meteor).
Now you need to do one of the following:
  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/tmp/buildpack_442b8f6cd26288e0efd13128791ed182/meteor-D2gR/.meteor/packages/meteor-tool/1.1.3/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
-----> Bundling bundle
$ROOT_URL, if specified, must be an URL.
 !     Push rejected, failed to compile Node.js app
```

**Comment by kohenkatz** [comment]
I figured out my issue.  I chose to create a new Heroku account for this app, and the first time that I clicked the "Deploy" button, Heroku interrupted the deployment to ask for credit card info in order to verify my account.  The deployment was left in "half-configured" state, so future clicks of the "deploy" button failed too.

After I deleted the old half-configured deployment and started totally fresh, it seems to have worked.

**Comment by engelgabriel** [comment]
Yes, Meteor needs the $ROOT_URL variable.

**Comment by tkdjex** [comment]
hello, how do you delete the "half-configured" deployment? I'm totally new to this and have same issue as you. Thanks

**Comment by Sing-Li** [comment]
Sign into the dashboard and delete the app.

**Comment by tkdjex** [comment]
Thanks for your answer. Unfortunately I can't see any apps installed. See
screenshot. What else can I do?

Sent from mobile.
16 gru 2015 16:13 "SingLi" <notifications@github.com> napisał(a):

**Comment by tkdjex** [comment]
Hi, thanks, I've managed that, cheers

**Comment by antonpopov** [comment]
Hi, there! I got a similar "error" when using the one-click deploy button. Here is the log:
-----> Node.js app detected
-----> Listing HEROKU_ environment variables
HEROKU_APP_ID:           
HEROKU_APP_NAME:         
HEROKU_DYNO_ID:          
HEROKU_RELEASE_VERSION:  
HEROKU_SLUG_COMMIT:      
HEROKU_SLUG_DESCRIPTION: 
-----> Installing node
-----> Installing meteor
Downloading Meteor distribution
Meteor 1.4.0.1 has been installed in your home directory (~/.meteor).
Now you need to do one of the following:
  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/app/tmp/buildpacks/ec95e5d1b974435c5c7157ba6fcb0d6323f4e70beb6f90c5dc8e2248948ff950dfcd73ff00896ded7938ceb333a80d48f2db8558e376c5c760eb8d9eb9b681d3/meteor-CXRy/.meteor/packages/meteor-tool/1.4.0-1/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
-----> Bundling bundle
-----> Checking if this meteor version supports --server-only

it just stucks on "-----> Checking if this meteor version supports --server-only" and after an hour -> Build failed.

**Comment by ravimallya** [comment]
Hi.

I'm also having the same issue with heroku CLI. I followed the procedure mentioned at: https://rocket.chat/docs/installation/paas-deployments/heroku/ . Here is the log:

```
remote: -----> Building Meteor app with ROOT_URL: https://ravimallya-dev.herokuapp.com/
remote: => Errors while initializing project:
remote:
remote: While loading emojione:emojione@2.2.6...:
remote: error: Command failed:
remote: /app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.5.1.puot9a++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
remote: rebuild --update-binary
remote: Phantom installation failed { [Error: EACCES: permission denied, open
remote: '/tmp/mt-cde1xa/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js']
remote: errno: -13,
remote: code: 'EACCES',
remote: syscall: 'open',
remote: path:
remote: '/tmp/mt-cde1xa/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
remote: } Error: EACCES: permission denied, open
remote: '/tmp/mt-cde1xa/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
remote: at Error (native)
remote: at Object.fs.openSync (fs.js:549:18)
remote: at Object.fs.writeFileSync (fs.js:1156:15)
remote: at writeLocationFile
remote: (/tmp/mt-cde1xa/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:108:6)
remote: at Promise._successFn
remote: (/tmp/mt-cde1xa/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:80:5)
remote: at nextTickCallback
remote: (/tmp/mt-cde1xa/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
remote: at nextTickCallbackWith0Args (node.js:489:9)
remote: at process._tickCallback (node.js:418:13)
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! phantomjs@1.9.20 install: `node install.js`
remote: npm ERR! Exit status 1
remote: npm ERR!
remote: npm ERR! Failed at the phantomjs@1.9.20 install script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional
remote: logging output above.
remote:
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!
remote: /app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.5.1.puot9a++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-07-26T15_55_06_957Z-debug.log
remote: Phantom installation failed { [Error: EACCES: permission denied, open
remote: '/tmp/mt-cde1xa/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js']
remote: errno: -13,
remote: code: 'EACCES',
remote: syscall: 'open',
remote: path:
remote: '/tmp/mt-cde1xa/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
remote: } Error: EACCES: permission denied, open
remote: '/tmp/mt-cde1xa/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
remote: at Error (native)
remote: at Object.fs.openSync (fs.js:549:18)
remote: at Object.fs.writeFileSync (fs.js:1156:15)
remote: at writeLocationFile
remote: (/tmp/mt-cde1xa/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:108:6)
remote: at Promise._successFn
remote: (/tmp/mt-cde1xa/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:80:5)
remote: at nextTickCallback
remote: (/tmp/mt-cde1xa/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
remote: at nextTickCallbackWith0Args (node.js:489:9)
remote: at process._tickCallback (node.js:418:13)
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! phantomjs@1.9.20 install: `node install.js`
remote: npm ERR! Exit status 1
remote: npm ERR!
remote: npm ERR! Failed at the phantomjs@1.9.20 install script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional
remote: logging output above.
remote:
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!
remote: /app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.5.1.puot9a++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-07-26T15_55_06_957Z-debug.log
remote:
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to ravimallya-dev.
remote:
To https://git.heroku.com/ravimallya-dev.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/ravimallya-dev.git'

```
Is this the issue related to Rocket.Chat or Heroku itself?
