### ISSUE TITLE
Unable to change/include a profile picture

### ISSUE THREAD

**Issue by parannoide** [RocketChat/Rocket.Chat#24100]
### Description:

Unable to either include a new profile picture or change the currente profile picture

### Steps to reproduce:

1. Go to "My Account"
2. Upload a profile picture
3. Click on "Save changes"
4. Get messages "Profile saved successfully" and "Avatar changed successfully"

### Expected behavior:

Show new profile picture to the user

### Actual behavior:

Shows de default profile picture or the previous profile picture.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.2.2
- Operating System: Ubuntu 18.04 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.7 x64
- MongoDB Version: 3.6.23

### Client Setup Information

- Desktop App or Browser Version: 
  - Firefox 95, 
  - Rocket Chat Desktop 3.2 e 3.1
  - App Rocket Chat Experimental
- Operating System:
  - Ubuntu
  - Android
  - Windows

### Relevant logs:

Browser log

```
g_CS[e] is null 2 background.js:1
    receiveCS moz-extension://2a50df9f-fcf6-43b1-889b-c0565fe2891b/background.js:1
    onconnect_listener moz-extension://2a50df9f-fcf6-43b1-889b-c0565fe2891b/background.js:1
    e moz-extension://2a50df9f-fcf6-43b1-889b-c0565fe2891b/lpfulllib.js:1
    apply self-hosted:2718
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:635
    asyncWithoutClone resource://gre/modules/ExtensionCommon.jsm:2421

```
```
I20220104-13:50:03.177(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setUserAvatar.js:67:58     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24) 
{"level":50,"time":"2022-01-04T13:55:53.936Z","pid":18051,"hostname":"optimus-rocket-chat","name":"System","err":{"type":"ApiError","message":"No such object: storage-chat/QK9v8EyTKFgxmR9YZ/avatars/Z3TxCYJ9LCZuo4GuJ","stack":"Error: No such object: storage-chat/QK9v8EyTKFgxmR9YZ/avatars/Z3TxCYJ9LCZuo4GuJ<br>    at Util.parseHttpRespBody (/snap/rocketchat-server/1502/programs/server/npm/node_modules/@google-cloud/common/build/src/util.js:191:38)<br>    at Util.handleResp (/snap/rocketchat-server/1502/programs/server/npm/node_modules/@google-cloud/common/build/src/util.js:135:117)<br>    at /snap/rocketchat-server/1502/programs/server/npm/node_modules/@google-cloud/common/build/src/util.js:423:22<br>    at onResponse (/snap/rocketchat-server/1502/programs/server/npm/node_modules/retry-request/index.js:214:7)<br>    at /snap/rocketchat-server/1502/programs/server/npm/node_modules/teeny-request/build/src/index.js:222:13<br>    at /snap/rocketchat-server/1502/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","code":404,"errors":[{"message":"No such object: storage-chat/QK9v8EyTKFgxmR9YZ/avatars/Z3TxCYJ9LCZuo4GuJ","domain":"global","reason":"notFound"}]},"msg":"No such object: storage-chat/QK9v8EyTKFgxmR9YZ/avatars/Z3TxCYJ9LCZuo4GuJ"} 
I20220104-13:55:54.321(0) Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/lib/server/functions/setUserAvatar.js:67:58     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24) 
```

**Comment by parannoide** [comment]
Related  to #15470

**Comment by AbhishekJamhoriya** [comment]
Hi, @parannoide  is this issue open. if yes, please assign me this issue.

**Comment by parannoide** [comment]
Rocket.Chat Version: 4.3.1
NodeJS Version: 12.22.8 - x64
MongoDB Version: 4.2.17
MongoDB Engine: wiredTiger
Platform: linux 

Snap updated and the problem persists.

**Comment by dougfabris** [comment]
@parannoide #25603
Thanks for reporting and helping us!
