### ISSUE TITLE
E2E encryption password only unlocks on the official site URL (mydomain.example.com) but NOT on a local instance IP (192.168.1.2)

### ISSUE THREAD

**Issue by recklessnl** [RocketChat/Rocket.Chat#24139]
### Description:

E2E encryption is enabled on a single RocketChat server. I have a domain name that via a reverse proxy points to this server. Unlocking E2E encryption using my password works without issues when connecting to the domain name. But when I connect using a local IP address on the LAN, the password will not unlock the E2E encryption. This is a bug that's quite annoying and makes it useless to use RocketChat on a local network.

### Steps to reproduce:

1. Log into the local RocketChat instance using local IP (in my case 192.168.1.209:3000)
2. Try to unlock the E2E encryption with the key. It will not work as it gives the following error:

> _Wasn't possible to decode your encryption key to be imported. 
Your encryption password seems wrong. Click here to try again_.

3. When I then try to connect to my domain name (which is a reverse proxy pointing to the exact same server) it works and unlocks just fine.

### Expected behavior:

I expect and want the E2E encryption password to unlock for both a local IP connection as well as a domain name external connection, of the same RocketChat server, just like my account password works for both instances.

### Actual behavior:

As explained above, the local instance does not unlock despite it being the correct password.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.2.2
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances:  1
- DB Replicaset Oplog: ?
- NodeJS Version: v12.22.7
- MongoDB Version: 3.6.23 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Both browser as well as Windows desktop client
- Operating System: Ubuntu & Windows 10

### Relevant logs:
```
{"level":51,"time":"2021-12-31T23:11:39.782Z","pid":741,"hostname":"rocketchat","name":"Migrations","msg":"Not migrating, already at version 249"} 
I20211231-17:11:39.905(-6) ufs: temp directory created at "/tmp/ufs" 
I20211231-17:11:42.236(-6) Loaded the Apps Framework and loaded a total of 0 Apps! 
I20211231-17:11:42.657(-6) +----------------------------------------------+ 
I20211231-17:11:42.657(-6) |                SERVER RUNNING                | 
I20211231-17:11:42.657(-6) +----------------------------------------------+ 
I20211231-17:11:42.657(-6) |                                              | 
I20211231-17:11:42.657(-6) |  Rocket.Chat Version: 4.2.2                  | 
I20211231-17:11:42.657(-6) |       NodeJS Version: 12.22.7 - x64          | 
I20211231-17:11:42.657(-6) |      MongoDB Version: 3.6.23                 | 
I20211231-17:11:42.657(-6) |       MongoDB Engine: wiredTiger             | 
I20211231-17:11:42.657(-6) |             Platform: linux                  | 
I20211231-17:11:42.657(-6) |         Process Port: 3000                   | 
I20211231-17:11:42.657(-6) |             Site URL: http://localhost:3000  | 
I20211231-17:11:42.657(-6) |     ReplicaSet OpLog: Enabled                | 
I20211231-17:11:42.657(-6) |          Commit Hash: ab3baf2f31             | 
I20211231-17:11:42.658(-6) |        Commit Branch: HEAD                   | 
I20211231-17:11:42.658(-6) |                                              | 
I20211231-17:11:42.658(-6) +----------------------------------------------+ 
I20211231-17:11:42.658(-6) +----------------------------------------------------------------------+ 
I20211231-17:11:42.658(-6) |                              DEPRECATION                             | 
I20211231-17:11:42.658(-6) +----------------------------------------------------------------------+ 
I20211231-17:11:42.658(-6) |                                                                      | 
I20211231-17:11:42.658(-6) |  YOUR CURRENT MONGODB VERSION (3.6.23) IS DEPRECATED.                | 
I20211231-17:11:42.658(-6) |  IT WILL NOT BE SUPPORTED ON ROCKET.CHAT VERSION 5.0.0 AND GREATER,  | 
I20211231-17:11:42.658(-6) |  PLEASE UPGRADE MONGODB TO VERSION 4.2 OR GREATER                    | 
I20211231-17:11:42.658(-6) |                                                                      | 
I20211231-17:11:42.658(-6) +----------------------------------------------------------------------+ 
I20220107-20:54:27.107(-6) Exception while invoking method 'permissions/get' Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation     at check (packages/check/match.js:36:17)     at app/authorization/server/streamer/permissions/index.ts:8:3     at /snap/rocketchat-server/1502/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 
I20220107-20:54:27.114(-6) Sanitized and reported to the client as: errorClass [Error]: Match failed [400]     at errorClass.<anonymous> (packages/check/match.js:91:27)     at new errorClass (packages/meteor.js:655:17)     at check (packages/check/match.js:36:17)     at app/authorization/server/streamer/permissions/index.ts:8:3     at /snap/rocketchat-server/1502/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {   isClientSafe: true,   error: 400,   reason: 'Match failed',   details: undefined,   errorType: 'Meteor.Error' } 
I20220107-20:54:27.114(-6) undefined undefined 
I20220107-20:54:34.863(-6) Exception while invoking method 'permissions/get' Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation     at check (packages/check/match.js:36:17)     at app/authorization/server/streamer/permissions/index.ts:8:3     at /snap/rocketchat-server/1502/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 
I20220107-20:54:34.863(-6) Sanitized and reported to the client as: errorClass [Error]: Match failed [400]     at errorClass.<anonymous> (packages/check/match.js:91:27)     at new errorClass (packages/meteor.js:655:17)     at check (packages/check/match.js:36:17)     at app/authorization/server/streamer/permissions/index.ts:8:3     at /snap/rocketchat-server/1502/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {   isClientSafe: true,   error: 400,   reason: 'Match failed',   details: undefined,   errorType: 'Meteor.Error' } 
I20220107-20:54:34.863(-6) undefined undefined 
```

**Comment by recklessnl** [comment]
Bump, this is still not fixed.

**Comment by mig5** [comment]
I too have a reverse proxy (Nginx) in front of the Docker container, but it doesn't even work for me unlocking the E2EE password when browsing via the domain name. I still get the same error 

> Wasn't possible to decode your encryption key to be imported.
> Your encryption password seems wrong. Click here to try again.

No matter how many times I reset the key/set a new key, it's always the same error.

```
Version 5.4.2
Apps Engine Version 1.36.0
Node Version v14.19.3
Database Migration 281 (February 3, 2023 2:38 PM)
MongoDB 4.4.15 / wiredTiger (oplog Enabled)
Commit Details HEAD: (87f116bab) Branch: HEAD
PID 1
```

**Comment by tobiasreinhard** [comment]
Same issue here with RC 5.4.0
