### ISSUE TITLE
Non-intuitive user context menu

### ISSUE THREAD

**Issue by disenchant** [RocketChat/Rocket.Chat#24156]
E.g. to remove a user from a room one will have to open the list of users in the room (so far no problems) but then the next step is to open the context menu for the user we want to remove. This can be done with a click on the three dots beside the users name but the context menu that pops up has a very bad indication of being scrollable.

<img width="40%" alt="1" src="https://user-images.githubusercontent.com/686611/149163391-6f487793-4737-4940-912e-4c91baaf1a73.png"> <img width="40%" alt="2" src="https://user-images.githubusercontent.com/686611/149163413-489159d7-ae52-41c1-a238-979015a26769.png">

It seem that this really isn't intuitive: In our company of \~60 people we had people asking how to remove users from a room twice in the last week alone and e.g. https://github.com/RocketChat/Rocket.Chat/issues/21811#issuecomment-827124541 and https://github.com/RocketChat/Rocket.Chat/issues/21811#issuecomment-1004030862 show that this seems to be a general issue among the Rocket.Chat user-base (they we're talking about the same context menu when looking at a single user but I guess it's the exact same UI element).

As a simple fix I would recommend to avoid scrolling in this context menu completely.

**Comment by Dnouv** [comment]
Hello, @dudanogueira. I'm planning to work on this issue, would it be ok to remove the scrolling part by increasing the height of the context menu so that it can accommodate all the options?
Looking forward to hearing back from you, or if this type of issue is handled by some other member please let me know.
Thank you!

**Comment by dudanogueira** [comment]
@Dnouv thank you!!

I believe it's ok to go forward.

While I can't tell you this is the best approach to fix this, we can consider that if necessary, we can change later at the PR or learn along the way.

**Comment by Dnouv** [comment]
Thank you for the prompt reply. That sounds good. I'll open a PR and will make changes accordingly.

**Comment by Dnouv** [comment]
I'm trying to run the End to End Tests as per the instructions on the site, when running the following command,
```
# Running with a local mongodb database
MONGO_URL=mongodb://localhost/empty MONGO_OPLOG_URL=mongodb://localhost/local TEST_MODE=true meteor
```

The application crashes with the error,

```
W20220205-13:52:47.454(0)? (STDERR) /home/gitpod/.meteor/packages/meteor-tool/.2.5.3.14evxav.mikm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
W20220205-13:52:47.468(0)? (STDERR)                                             throw(ex);
W20220205-13:52:47.468(0)? (STDERR)                                             ^
W20220205-13:52:47.469(0)? (STDERR) 
W20220205-13:52:47.469(0)? (STDERR) MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
W20220205-13:52:47.469(0)? (STDERR)     at Timeout._onTimeout (/home/gitpod/.meteor/packages/npm-mongo/.3.9.1.3esjx6.390nv++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/sdam/topology.js:437:30)
W20220205-13:52:47.469(0)? (STDERR)     at listOnTimeout (internal/timers.js:557:17)
W20220205-13:52:47.469(0)? (STDERR)     at processTimers (internal/timers.js:500:7) {
W20220205-13:52:47.470(0)? (STDERR)   reason: TopologyDescription {
W20220205-13:52:47.470(0)? (STDERR)     type: 'Single',
W20220205-13:52:47.470(0)? (STDERR)     setName: null,
W20220205-13:52:47.470(0)? (STDERR)     maxSetVersion: null,
W20220205-13:52:47.470(0)? (STDERR)     maxElectionId: null,
W20220205-13:52:47.471(0)? (STDERR)     servers: Map(1) {
W20220205-13:52:47.471(0)? (STDERR)       'localhost:27017' => ServerDescription {
W20220205-13:52:47.471(0)? (STDERR)         address: 'localhost:27017',
W20220205-13:52:47.471(0)? (STDERR)         error: Error: connect ECONNREFUSED 127.0.0.1:27017
W20220205-13:52:47.471(0)? (STDERR)             at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
W20220205-13:52:47.471(0)? (STDERR)           name: 'MongoNetworkError'
W20220205-13:52:47.471(0)? (STDERR)         },
W20220205-13:52:47.472(0)? (STDERR)         roundTripTime: -1,
W20220205-13:52:47.472(0)? (STDERR)         lastUpdateTime: 307542947,
W20220205-13:52:47.472(0)? (STDERR)         lastWriteDate: null,
W20220205-13:52:47.472(0)? (STDERR)         opTime: null,
W20220205-13:52:47.472(0)? (STDERR)         type: 'Unknown',
W20220205-13:52:47.472(0)? (STDERR)         topologyVersion: undefined,
W20220205-13:52:47.472(0)? (STDERR)         minWireVersion: 0,
W20220205-13:52:47.472(0)? (STDERR)         maxWireVersion: 0,
W20220205-13:52:47.472(0)? (STDERR)         hosts: [],
W20220205-13:52:47.472(0)? (STDERR)         passives: [],
W20220205-13:52:47.472(0)? (STDERR)         arbiters: [],
W20220205-13:52:47.473(0)? (STDERR)         tags: []
W20220205-13:52:47.473(0)? (STDERR)       }
W20220205-13:52:47.473(0)? (STDERR)     },
W20220205-13:52:47.473(0)? (STDERR)     stale: false,
W20220205-13:52:47.473(0)? (STDERR)     compatible: true,
W20220205-13:52:47.473(0)? (STDERR)     compatibilityError: null,
W20220205-13:52:47.473(0)? (STDERR)     logicalSessionTimeoutMinutes: null,
W20220205-13:52:47.473(0)? (STDERR)     heartbeatFrequencyMS: 10000,
W20220205-13:52:47.473(0)? (STDERR)     localThresholdMS: 15,
W20220205-13:52:47.473(0)? (STDERR)     commonWireVersion: null
W20220205-13:52:47.474(0)? (STDERR)   }
W20220205-13:52:47.474(0)? (STDERR) }
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

The development environment is set up on Gitpod, running on the latest develop branch.

@dudanogueira, would you please help me out with this issue. 
Thank you!

**Comment by himani-mehra** [comment]
Hi @disenchant , I would love to take on this issue and contribute to the project. Could you please assign it to me if it's available? Looking forward to your response. Thanks!
