### ISSUE TITLE
Rocket.Chat 4.3.1 : ldap error "msg":"illegal unescaped char: ("}

### ISSUE THREAD

**Issue by cello86** [RocketChat/Rocket.Chat#24227]
### Description:
The rocket.chat version 4.3.1 has some issues with LDAP authentication after the migration from 3.16.1 version. 

### Steps to reproduce:

1. Start a new instance of Rocket 4.3.1
2. Try to login (with error)

### Expected behavior:
The login works.

### Actual behavior:
The login fails.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System:  CentOS 7.9
- Deployment Method: tar 
- Number of Running Instances: 1
- DB Replicaset Oplog:  1
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Windows 10

### Relevant logs:

```
{"level":50,"time":"2022-01-20T11:23:31.796Z","pid":8,"hostname":"32360da5a030","name":"LDAP","err":{"type":"Error","message":"illegal unescaped char: (","stack":"Error: illegal unescaped char: (\n    at escapeValue (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:49:13)\n    at parseExpr (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:167:16)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:228:14)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:213:13)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:204:13)\n    at Object.parse (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:252:18)\n    at Object.parseString (/opt/rocketchat/programs/server/npm/node_modules/ldapjs/lib/filters/index.js:179:27)\n    at Client.search (/opt/rocketchat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:571:30)\n    at server/lib/ldap/Connection.ts:305:16\n    at new Promise (<anonymous>)\n    at server/lib/ldap/Connection.ts:304:10\n    at /opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/lib/ldap/Manager.ts:163:15\n    at /opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"illegal unescaped char: ("}
{"level":50,"time":"2022-01-20T11:23:33.821Z","pid":8,"hostname":"32360da5a030","name":"LDAP","err":{"type":"Error","message":"illegal unescaped char: (","stack":"Error: illegal unescaped char: (\n    at escapeValue (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:49:13)\n    at parseExpr (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:167:16)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:228:14)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:213:13)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:204:13)\n    at Object.parse (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:252:18)\n    at Object.parseString (/opt/rocketchat/programs/server/npm/node_modules/ldapjs/lib/filters/index.js:179:27)\n    at Client.search (/opt/rocketchat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:571:30)\n    at server/lib/ldap/Connection.ts:305:16\n    at new Promise (<anonymous>)\n    at server/lib/ldap/Connection.ts:304:10\n    at /opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/lib/ldap/Manager.ts:163:15\n    at /opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"illegal unescaped char: ("}
{"level":50,"time":"2022-01-20T11:23:41.715Z","pid":8,"hostname":"32360da5a030","name":"LDAP","err":{"type":"Error","message":"illegal unescaped char: (","stack":"Error: illegal unescaped char: (\n    at escapeValue (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:49:13)\n    at parseExpr (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:167:16)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:228:14)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:213:13)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:204:13)\n    at Object.parse (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:252:18)\n    at Object.parseString (/opt/rocketchat/programs/server/npm/node_modules/ldapjs/lib/filters/index.js:179:27)\n    at Client.search (/opt/rocketchat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:571:30)\n    at server/lib/ldap/Connection.ts:305:16\n    at new Promise (<anonymous>)\n    at server/lib/ldap/Connection.ts:304:10\n    at /opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/lib/ldap/Manager.ts:163:15\n    at /opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"illegal unescaped char: ("}
{"level":50,"time":"2022-01-20T11:24:30.814Z","pid":8,"hostname":"32360da5a030","name":"LDAP","err":{"type":"Error","message":"illegal unescaped char: (","stack":"Error: illegal unescaped char: (\n    at escapeValue (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:49:13)\n    at parseExpr (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:167:16)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:228:14)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:213:13)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:204:13)\n    at Object.parse (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:252:18)\n    at Object.parseString (/opt/rocketchat/programs/server/npm/node_modules/ldapjs/lib/filters/index.js:179:27)\n    at Client.search (/opt/rocketchat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:571:30)\n    at server/lib/ldap/Connection.ts:305:16\n    at new Promise (<anonymous>)\n    at server/lib/ldap/Connection.ts:304:10\n    at /opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/lib/ldap/Manager.ts:163:15\n    at /opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"illegal unescaped char: ("}
{"level":50,"time":"2022-01-20T11:25:34.711Z","pid":8,"hostname":"32360da5a030","name":"LDAP","err":{"type":"Error","message":"illegal unescaped char: (","stack":"Error: illegal unescaped char: (\n    at escapeValue (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:49:13)\n    at parseExpr (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:167:16)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:228:14)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:213:13)\n    at parseFilter (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:204:13)\n    at Object.parse (/opt/rocketchat/programs/server/npm/node_modules/ldap-filter/lib/index.js:252:18)\n    at Object.parseString (/opt/rocketchat/programs/server/npm/node_modules/ldapjs/lib/filters/index.js:179:27)\n    at Client.search (/opt/rocketchat/programs/server/npm/node_modules/ldapjs/lib/client/client.js:571:30)\n    at server/lib/ldap/Connection.ts:305:16\n    at new Promise (<anonymous>)\n    at server/lib/ldap/Connection.ts:304:10\n    at /opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/lib/ldap/Manager.ts:163:15\n    at /opt/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"illegal unescaped char: ("}
```

**Comment by dudanogueira** [comment]
Hi!

Looks like something with your LDAP User Search filter string. It would help posting it here, if possible.

THanks!
