### ISSUE TITLE
Trying to deploy Rocketchat in K8 using 2.4.0 version Getting Error

### ISSUE THREAD

**Issue by thangs6** [RocketChat/Rocket.Chat#24234]
We are currently using Rocketchat version 2.4.0 in our PROD environment. For our testing purpose we are trying to deploy same version in our test environment but it is getting below error, 

C:\Users\chins31\Desktop>kubectl logs rocketchat-865f989d98-69mq7 -n rc-test
New Relic for Node.js was unable to bootstrap itself due to an error:
Error: New Relic for Node.js requires a version of Node equal to or
greater than 10.0.0. Not starting!
at initialize (/app/bundle/programs/server/node_modules/newrelic/index.js:57:13)
at Object. (/app/bundle/programs/server/node_modules/newrelic/index.js:37:3)
at Module._compile (module.js:653:30)
at Module.Mp._compile (/app/bundle/programs/server/runtime.js:50:23)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at Module.Mp.load (/app/bundle/programs/server/runtime.js:15:31)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"rocketchat-865f989d98-69mq7","pid":6,"time":"2022-01-04T16:54:25.230Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}
New Relic failed to open log file /app/bundle/programs/server/newrelic_agent.log
{ Error: EACCES: permission denied, open '/app/bundle/programs/server/newrelic_agent.log'
errno: -13,
code: 'EACCES',
syscall: 'open',
path: '/app/bundle/programs/server/newrelic_agent.log' }
/app/bundle/programs/server/node_modules/fibers/future.js:313
throw(ex);
^

MongoNetworkError: failed to connect to server [rc-mongo-2.rocketchat-mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND rc-mongo-2.rocketchat-mongo rc-mongo-2.rocketchat-mongo:27017]
at Pool. (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:431:11)
at emitOne (events.js:116:13)
at Pool.emit (events.js:211:7)
at connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:557:14)
at makeConnection (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connect.js:39:11)
at callback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connect.js:261:5)
at Socket.err (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connect.js:286:7)
at Object.onceWrapper (events.js:315:30)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at emitErrorNT (internal/streams/destroy.js:73:8)
at _combinedTickCallback (internal/process/next_tick.js:139:11)
at process._tickCallback (internal/process/next_tick.js:181:9)

We are trying to build new image with latest newrelic version its not support and i am getting same error, 

Kindly advice for this issue.

**Comment by debdutdeb** [comment]
Which guide are you following?
