### ISSUE TITLE
Can't exchange images in Federation chat or channel

### ISSUE THREAD

**Issue by Skywrath-Mage** [RocketChat/Rocket.Chat#24329]
### Description:

Can't exchange images in Federation chat or channel, the setup should all be correct, but the port in the SRV Record is marked as not correct even if is on 443. 

### Steps to reproduce:

1. classic setup of federation with the wizard
2. DNS records are correct. 
3. Message a user on another domain (this works)
4. Send an image (this doesn't work)

### Expected behavior:

You should be able to send an image and if the image is not been sent, you should see at least an error message. 

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.2
- Operating System: Ubuntu (docker)
- Deployment Method: Cloudron
- Number of Running Instances: 2
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.12 

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: macOS and Windows 11

### Relevant logs:

```js
{
  "level":50,
  "time":"2022-01-28T08:56:39.208Z",
  "pid":1,
  "hostname":"XXXXXXXXXX",
  "name":"Federation",
  "section":"http",
  "msg":"[IGNORED] Error",
  "err":{
    "type":"Error",
    "message":"failed [400] {\"success\":false,\"error\":\"Forbidden [forbidden]\",\"errorType\":\"forbidden\"}",
    "stack":"Error: failed [400] {\"success\":false,\"error\":\"Forbidden [forbidden]\",\"errorType\":\"forbidden\"}\n at Object.exports.makeErrorByStatus (packages/http.js:177:10)\n at Request._callback (packages/http.js:141:24)\n at Request.self.callback (/app/code/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)\n at Request.emit (events.js:314:20)\n at Request.EventEmitter.emit (domain.js:483:12)\n at Request.<anonymous> (/app/code/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)\n at Request.emit (events.js:314:20)\n at Request.EventEmitter.emit (domain.js:483:12)\n at IncomingMessage.<anonymous> (/app/code/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)\n at Object.onceWrapper (events.js:420:28)\n at IncomingMessage.emit (events.js:326:22)\n at IncomingMessage.EventEmitter.emit (domain.js:483:12)\n at endReadableNT (_stream_readable.js:1241:12)\n at processTicksAndRejections (internal/process/task_queues.js:84:21)\n => awaited here:\n at Function.Promise.await (/app/code/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n at app/federation/server/lib/http.js:42:9\n at /app/code/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40",
    "response":{
      "statusCode":400,
      "content":"{\"success\":false,\"error\":\"Forbidden [forbidden]\",\"errorType\":\"forbidden\"}",
      "headers":{
        "server":"nginx",
        "date":"Fri, 28 Jan 2022 08:56:39 GMT",
        "content-type":"application/json",
        "transfer-encoding":"chunked",
        "connection":"close",
        "x-frame-options":"sameorigin",
        "content-security-policy":"default-src 'self' ; connect-src *; font-src 'self' data:; frame-src *; img-src * data:; media-src * data:; script-src 'self' 'unsafe-eval' 'sha256-XXXXXX=' ; style-src 'self' 'unsafe-inline'",
        "x-instance-id":"XXXXXX",
        "cache-control":"no-store",
        "pragma":"no-cache",
        "x-ratelimit-limit":"30",
        "x-ratelimit-remaining":"29",
        "x-ratelimit-reset":"1643360199877",
        "access-control-allow-origin":"*",
        "access-control-allow-headers":"Origin, X-Requested-With, Content-Type, Accept, X-User-Id, X-Auth-Token",
        "vary":"Accept-Encoding"
      },
      "data":{
        "success":false,
        "error":"Forbidden [forbidden]",
        "errorType":"forbidden"
      }
    }
  },
  "msg":"failed [400] {\"success\":false,\"error\":\"Forbidden [forbidden]\",\"errorType\":\"forbidden\"}"
}

```

**Comment by geekgonecrazy** [comment]
Closing in favor of https://github.com/RocketChat/Rocket.Chat/issues/22999 I do appreciate following the template and the details though 🙏
