### ISSUE TITLE
Upgraded to 4.4.0, app / previews no longer working

### ISSUE THREAD

**Issue by fc757** [RocketChat/Rocket.Chat#24345]
After upgrading to 4.4.0 apps like /tenor or /giphy no longer return results, The following errors show in the logs when attempting:

I20220129-06:45:12.731(-5) Exception while invoking method 'getSlashCommandPreviews' TypeError: Cannot read property 'id' of undefined     at Object._executeSlashCommandPreview [as getPreviews] (app/utils/lib/slashCommand.js:34:17)     at MethodInvocation.getSlashCommandPreviews (app/lib/server/methods/getSlashCommandPreviews.js:26:24)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:74:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)     at packages/ddp-server/livedata_server.js:769:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)     at packages/ddp-server/livedata_server.js:767:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)     at packages/ddp-server/livedata_server.js:765:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:739:23)     at packages/ddp-server/livedata_server.js:603:43 

Here are the versions for my install:

Version
4.4.0
Deployment ID
DEswvvzai9v6M2LwC
Apps Engine Version
1.30.0
Node Version
v14.18.2
Database Migration
253 (January 29, 2022 6:44 AM)
MongoDB
5.0.5 / wiredTiger (oplog Enabled)

**Comment by lovekyleman** [comment]
We also have the same issues.

**Comment by soundneedle** [comment]
same

**Comment by ali-alhaidary** [comment]
same

**Comment by Crashdummyy** [comment]
Here as well...

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.15
3 info using node@v14.18.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle tiny-secp256k1@1.1.3~prebuild: tiny-secp256k1@1.1.3
6 info lifecycle tiny-secp256k1@1.1.3~build: tiny-secp256k1@1.1.3
7 verbose lifecycle tiny-secp256k1@1.1.3~build: unsafe-perm in lifecycle true
8 verbose lifecycle tiny-secp256k1@1.1.3~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/tmp/bundle/programs/server/npm/node_modules/tiny-secp256k1/node_modules/.bin:/tmp/bundle/programs/server/npm/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/tmp/bundle/programs/server/npm/node_modules/tiny-secp256k1/node_modules/.bin:/tmp/bundle/programs/server/npm/node_modules/.bin:/usr/local/bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/tmp/bundle/programs/server/node_modules/.bin:/home/crashdummy/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/home/crashdummy/.dotnet/tools
9 verbose lifecycle tiny-secp256k1@1.1.3~build: CWD: /tmp/bundle/programs/server/npm/node_modules/tiny-secp256k1
10 silly lifecycle tiny-secp256k1@1.1.3~build: Args: [ '-c', 'node-gyp rebuild' ]
11 silly lifecycle tiny-secp256k1@1.1.3~build: Returned: code: 1  signal: null
12 info lifecycle tiny-secp256k1@1.1.3~build: Failed to exec build script
13 verbose stack Error: tiny-secp256k1@1.1.3 build: `node-gyp rebuild`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid tiny-secp256k1@1.1.3
15 verbose cwd /tmp/bundle/programs/server/npm/node_modules/tiny-secp256k1
16 verbose Linux 4.19.0-18-amd64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v14.18.2
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error tiny-secp256k1@1.1.3 build: `node-gyp rebuild`
22 error Exit status 1
23 error Failed at the tiny-secp256k1@1.1.3 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ankar84** [comment]
Do you use proxy in your deployments?

**Comment by fc757** [comment]
Thank you for the comment. Unfortunately, I'm not using a proxy in my setup.

**Comment by mr-karan** [comment]
Not using proxy, have the same issue.

**Comment by nathanielread** [comment]
Also have this issue. 4.4.0 with 5.0.5 mongo DB in docker.
I even spun up a brand new 4.2.3 with 5.0.5 mongo and (giphy) previews worked. Then I changed the version to 4.4.0 in my docker-compose and now getting the error message. 

I'm not using those proxy environment variables, but I am using traefik in my docker environment.

**Comment by thrakks** [comment]
We have the same issue. 4.4.0 installed on Centos7 with MongoDB 4.4.0. 

Restored to 4.3.3 and issue went away so 4.4.0 definitely causing it for us.

**Comment by wreiske** [comment]
https://github.com/wreiske/Rocket.Chat.App-Giphy/issues/25

Getting a lot of attention on this issue.
