### ISSUE TITLE
Node crashing after update to 4.4

### ISSUE THREAD

**Issue by knordsiek** [RocketChat/Rocket.Chat#24415]
### Description:

I have updated the rocketchat from 4.3 to 4.4 an get the following errormessage presented.

npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install /tmp/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

>gyp ERR! build error 
>gyp ERR! stack Error: not found: make
>gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
>gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
>gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
>gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
>gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
>gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
>gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:191:21)
>gyp ERR! System Linux 4.18.0-348.12.2.el8_5.x86_64
>gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-->release"
>gyp ERR! cwd /tmp/bundle/programs/server/node_modules/fibers
>gyp ERR! node -v v14.18.2
>gyp ERR! node-gyp -v v5.1.0
>gyp ERR! not ok 
>node-gyp exited with code: 1
>Please make sure you are using a supported platform and node version. If you
>would like to compile fibers on this machine please make sure you have setup your
>build environment--
>Windows + OS X instructions here: https://github.com/nodejs/node-gyp
>Ubuntu users please run: `sudo apt-get install g++ build-essential`
>RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
>Alpine users please run: `sudo apk add python make g++`
> sh: nodejs: Kommando nicht gefunden.
> npm ERR! code ELIFECYCLE
> npm ERR! syscall spawn
> npm ERR! file sh
> npm ERR! errno ENOENT
> npm ERR! fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install: `node build.js || nodejs build.js`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2022-02-04T13_39_25_878Z-debug.log

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4 
- Operating System: Rockylinux 8
- Deployment Method: manual installation
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.18.2
- NPM Version: 6.14.5
- MongoDB Version: 4.2.18

**Comment by knordsiek** [comment]
Solved. 

If yout get this error please do 
> yum install make 
then the update to 4.4
