### ISSUE TITLE
Hipchat import error

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#2441]
Hello Devs.

I am running rocketchat 0.20 and get the following error while trying to import from hipchat.

```
Exception in defer callback: Error: import-hipchat-error
    at packages/rocketchat_importer-hipchat/server/HipChatImporter.coffee:216:15
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

Any ideas how to solve this?

thanks and cheers
t.

**Comment by graywolf336** [comment]
@himbeere Mind messaging me on the demo server? The hipchat wasn't test except by me with an extremely small set of data, so if you're up for testing let me know and we can make the hipchat importer more stable.

**Comment by himbeere** [comment]
©graywolf336 Sure. Although i think we are in very different timezones. GMT+1 here.

**Comment by himbeere** [comment]
Just tried to register a new account on the demo server but the server does not respond. Seems broken to me right now.

**Comment by engelgabriel** [comment]
Hi @himbeere, did you managed to join the demo server?

**Comment by graywolf336** [comment]
I just tested with the HipChat export we had originally, so there must be something different since the export we have was exported or there's something else about your export which wasn't in our export. Start a direct message with me when you are able to get on the demo server @himbeere

**Comment by himbeere** [comment]
@engelgabriel Yes. 
@graywolf336 I send you i private message on the demo server.

**Comment by graywolf336** [comment]
The issue turned out to be `Error: NamewithUmlauts is not a valid username, use only letters, numbers, dots and dashes [username-invalid]`.

**Comment by MartinSchoeler** [comment]
@graywolf336 is this still a issue? Can this be closed?

**Comment by graywolf336** [comment]
@MartinSchoeler Yes it is still an issue.
