### ISSUE TITLE
Custom OAuth is not working in the latest version.

### ISSUE THREAD

**Issue by vivek-dhayalan** [RocketChat/Rocket.Chat#2451]
I have migrated to the latest version of the Rocket.Chat (0.21.0) and found that there is some issue with custom OAuth authentication flow. I did not have the same issue with 0.14.0 that I use.

**Following is the Error that is captured from the logs:**

Exception while invoking method 'login' Error: Failed to fetch identity from waygumsso at http://XXXXXXXXXXXXXXXXXXXXXXXXXXX:8080/auth/realms/Speed/protocol/openid-connect/userinfo. failed [403] {"error_description":"Token invalid: Couldn't parse token","error":"invalid_grant"}
    at CustomOAuth.getIdentity (packages/rocketchat_custom-oauth/custom_oauth_server.coffee:91:16)
    at Object.handleOauthRequest (packages/rocketchat_custom-oauth/custom_oauth_server.coffee:100:20)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)
    at middleware (packages/oauth/oauth_server.js:173:1)
    at packages/oauth/oauth_server.js:146:1

Note: If I switch back to the old version, things work fine. I have also tried with 0.20.0.

**Comment by vivek-dhayalan** [comment]
I apologies for raising the issue here. Actually I forgot the point that I have did a small change in code so that my custom OAuth works properly. 

Following, is the line that I have added to my code:
'Authorization': 'bearer '+ accessToken in rocketchat_custom-oauth.js. And I guess
