### ISSUE TITLE
Rocketchat 4.4.2 can not send e-mails

### ISSUE THREAD

**Issue by avaflx** [RocketChat/Rocket.Chat#24551]
### **Description:**
rocketchat to version 4.4.2 can not send e-mails 

### **Steps to reproduce:**
Try to send any notification or other e-mail message

**Expected behavior:**
E-mails are sent

### **Actual behavior:**
E-mails are not sent

### **Server Setup Information:**
Version of Rocket.Chat Server: 4.4.2
Operating System: Linux
Deployment Method: docker
Number of Running Instances: 1
Client Setup Information
Desktop App or Browser Version: Chrome
Operating System: Windows 10

### **Relevant logs:**
Exception in defer callback: Error: Greeting never received     
at SMTPConnection._formatError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)     at SMTPConnection._onError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)     
at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:704:22)     
at listOnTimeout (internal/timers.js:557:17)    
 at processTimers (internal/timers.js:500:7) {   code: 'ETIMEDOUT',   command: 'CONN' }

**Comment by dudanogueira** [comment]
Hi!

Please, check your SMTP settings. The message is saying that the connection to the SMTP server timed out.

Here you can see how to test your SMTP using telnet on both windows and linux:
https://www.sparkpost.com/blog/how-to-check-an-smtp-connection-with-a-manual-telnet-session/

**Comment by vnkmpf** [comment]
I second that. Emails are not correctly sent.
SMTP test email from admin came alright. Before 4.4.2 all emails worked and SMTP was not modified in any way.

**Comment by Neykuratick** [comment]
same
