### ISSUE TITLE
[4.5.0][CE] MongoError: index already exist after upgrade

### ISSUE THREAD

**Issue by CAberry** [RocketChat/Rocket.Chat#24672]
Dear rocket team,

os: Debian 11
node : 14.18.3
mongo: 5.0.6
npm: 6.14.15

I encountered the following error after upgrading from 4.3.3 to version 4.5.0.

Similar closed issue -> https://github.com/RocketChat/Rocket.Chat/issues/24347
Also seen and applied this [workaround](https://github.com/RocketChat/Rocket.Chat/issues/24347#issuecomment-1032161111) fix from same issue ( Working great by the way )

```
Mar 02 12:51:03  systemd[1]: Starting The Rocket.Chat server...
Mar 02 12:51:23  systemd[1]: Started The Rocket.Chat server.
Mar 02 12:51:26  rocketchat[332099]: /opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:313
Mar 02 12:51:26  rocketchat[332099]:                                                 throw(ex);
Mar 02 12:51:26  rocketchat[332099]:                                                 ^
Mar 02 12:51:26  rocketchat[332099]: MongoError: An equivalent index already exists with the same name but different options. Requested index: { v: 2, unique: true, key: { username: 1 }, name: "username_1", sparse: true }, existing index: { v: 2, unique: true, key: { username: 1 }, name: "username_1", ns: "rocketchat.users", sparse: 1 }
Mar 02 12:51:26  rocketchat[332099]:     at MessageStream.messageHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
Mar 02 12:51:26  rocketchat[332099]:     at MessageStream.emit (events.js:400:28)
Mar 02 12:51:26  rocketchat[332099]:     at processIncomingData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
Mar 02 12:51:26  rocketchat[332099]:     at MessageStream._write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
Mar 02 12:51:26  rocketchat[332099]:     at writeOrBuffer (internal/streams/writable.js:358:12)
Mar 02 12:51:26  rocketchat[332099]:     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
Mar 02 12:51:26  rocketchat[332099]:     at Socket.ondata (internal/streams/readable.js:731:22)
Mar 02 12:51:26  rocketchat[332099]:     at Socket.emit (events.js:400:28)
Mar 02 12:51:26  rocketchat[332099]:     at addChunk (internal/streams/readable.js:293:12)
Mar 02 12:51:26  rocketchat[332099]:     at readableAddChunk (internal/streams/readable.js:267:9)
Mar 02 12:51:26  rocketchat[332099]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
Mar 02 12:51:26  rocketchat[332099]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
Mar 02 12:51:26  rocketchat[332099]:   ok: 0,
Mar 02 12:51:26  rocketchat[332099]:   code: 85,
Mar 02 12:51:26  rocketchat[332099]:   codeName: 'IndexOptionsConflict',
Mar 02 12:51:26  rocketchat[332099]:   '$clusterTime': {
Mar 02 12:51:26  rocketchat[332099]:     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1646221885 },
Mar 02 12:51:26  rocketchat[332099]:     signature: {
Mar 02 12:51:26  rocketchat[332099]:       hash: Binary {
Mar 02 12:51:26  rocketchat[332099]:         _bsontype: 'Binary',
Mar 02 12:51:26  rocketchat[332099]:         sub_type: 0,
Mar 02 12:51:26  rocketchat[332099]:         position: 20,
Mar 02 12:51:26  rocketchat[332099]:         buffer: Buffer(20) [Uint8Array] [
Mar 02 12:51:26  rocketchat[332099]:           0, 0, 0, 0, 0, 0, 0,
Mar 02 12:51:26  rocketchat[332099]:           0, 0, 0, 0, 0, 0, 0,
Mar 02 12:51:26  rocketchat[332099]:           0, 0, 0, 0, 0, 0
Mar 02 12:51:26  rocketchat[332099]:         ]
Mar 02 12:51:26  rocketchat[332099]:       },
Mar 02 12:51:26  rocketchat[332099]:       keyId: 0
Mar 02 12:51:26  rocketchat[332099]:     }
Mar 02 12:51:26  rocketchat[332099]:   },
Mar 02 12:51:26  rocketchat[332099]:   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1646221885 }
Mar 02 12:51:26  rocketchat[332099]: }
Mar 02 12:51:26  systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Mar 02 12:51:26  systemd[1]: rocketchat.service: Failed with result 'exit-code'.

```
If you need any more informations, i'll do my best to share them with you.

Any fix would be greatly apreciated :)

Greetings,

**Comment by hugocostadev** [comment]
Do you still have this problem? Let me know please...
