### ISSUE TITLE
Node module Fibers got RangeError: out of memory

### ISSUE THREAD

**Issue by franciscopaniskaseker** [RocketChat/Rocket.Chat#24679]
### Steps to reproduce:

Randomly our RC is exiting with code 7. Usually it need 1 week to go down.

### Expected behavior:

To not exit.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.2
- Operating System: ubuntu 20.04 updated
- Deployment Method: tar
- Number of Running Instances: 1 
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.0.0
- MongoDB Version: 4.4.12

### Client Setup Information

The problem is related with the server part, not with the clients.

### Additional context

50 seconds before that, we saw a lot of smtp ETIMEDOUT events from SMTP. Due journalctl corruption, I do not have the older logs about the out of memory error, but I can see that we had a lot of ETIMEDOUT events (for 1 week) from SMTP (node_mailer module) before this out of memory error. Can be just a coincidence.  I fixed it some minutes ago.

### Relevant logs:

```bash
Mar 02 18:13:19 ourhostname rocketchat[751]: {"level":50,"time":"2022-03-02T18:13:19.780Z","pid":751,"hostname":"ourhostname","name":"","name":"System","msg":"Exception while invoking method sendMessage 'Out of memory'"}
Mar 02 18:13:25 ourhostname rocketchat[751]: {"level":50,"time":"2022-03-02T18:13:25.028Z","pid":751,"hostname":"ourhostname","name":"","name":"System","msg":"Exception while invoking method sendMessage 'Out of memory'"}
Mar 02 18:13:25 ourhostname rocketchat[751]: {"level":50,"time":"2022-03-02T18:13:25.213Z","pid":751,"hostname":"ourhostname","name":"","name":"System","msg":"Exception while invoking method readMessages 'Out of memory'"}
Mar 02 18:13:27 ourhostname rocketchat[751]: /opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92
Mar 02 18:13:27 ourhostname rocketchat[751]:                                         return fn.apply(this, arguments);
Mar 02 18:13:27 ourhostname rocketchat[751]:                                                   ^
Mar 02 18:13:27 ourhostname rocketchat[751]: RangeError: Out of memory
Mar 02 18:13:27 ourhostname rocketchat[751]:     at Fiber.run (<anonymous>)
Mar 02 18:13:27 ourhostname rocketchat[751]:     at Fiber.run (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92:16)
Mar 02 18:13:27 ourhostname rocketchat[751]:     at process.<anonymous> (packages/meteor.js:1334:31)
Mar 02 18:13:27 ourhostname rocketchat[751]:     at process.emit (events.js:327:22)
Mar 02 18:13:27 ourhostname rocketchat[751]:     at process.EventEmitter.emit (domain.js:485:12)
Mar 02 18:13:27 ourhostname rocketchat[751]:     at process._fatalException (internal/process/execution.js:165:25)
Mar 02 18:13:27 ourhostname systemd[1]: rocketchat.service: Main process exited, code=exited, status=7/NOTRUNNING
Mar 02 18:13:27 ourhostname systemd[1]: rocketchat.service: Failed with result 'exit-code'.
```

**Comment by postwarbreakout** [comment]
We have the same issue for about 3 weeks now. Error says "Out of memory" but the RAM usage is normal (swap being untouched), there is no problem on the server itself.

**Comment by franciscopaniskaseker** [comment]
I did not have problem with free memory too.

**Comment by franciscopaniskaseker** [comment]
Same problem today.

```bash
Mar 10 00:10:38 hostname rocketchat[754]: Exception in defer callback: Error: invalid/unsafe port
Mar 10 00:10:38 hostname rocketchat[754]:     at app/oembed/server/server.js:85:9
Mar 10 00:10:38 hostname rocketchat[754]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Mar 10 00:10:38 hostname rocketchat[754]:  => awaited here:
Mar 10 00:10:38 hostname rocketchat[754]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Mar 10 00:10:38 hostname rocketchat[754]:     at Object.OEmbed.getUrlMeta (app/oembed/server/server.js:152:26)
Mar 10 00:10:38 hostname rocketchat[754]:     at app/oembed/server/server.js:216:22
Mar 10 00:10:38 hostname rocketchat[754]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Mar 10 00:10:38 hostname rocketchat[754]:  => awaited here:
Mar 10 00:10:38 hostname rocketchat[754]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Mar 10 00:10:38 hostname rocketchat[754]:     at app/oembed/server/server.js:269:14
Mar 10 00:10:38 hostname rocketchat[754]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Mar 10 00:10:38 hostname rocketchat[754]:  => awaited here:
Mar 10 00:10:38 hostname rocketchat[754]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Mar 10 00:10:38 hostname rocketchat[754]:     at app/oembed/server/server.js:302:25
Mar 10 00:10:38 hostname rocketchat[754]:     at Callbacks.runOne (lib/callbacks.ts:214:11)
Mar 10 00:10:38 hostname rocketchat[754]:     at lib/callbacks.ts:257:11
Mar 10 00:10:38 hostname rocketchat[754]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
Mar 10 00:10:38 hostname rocketchat[754]:     at packages/meteor.js:555:25
Mar 10 00:10:38 hostname rocketchat[754]:     at runWithEnvironment (packages/meteor.js:1320:24)



Mar 10 02:00:01 hostname rocketchat[754]: {"level":50,"time":"2022-03-10T02:00:01.223Z","pid":754,"hostname":"hostname","name":"","name":"System","msg":"OEmbed duplicated record","url":"https://github.com/RocketChat/Rocket.Chat/releases/tag/4.5.1"}
Mar 10 02:00:01 hostname rocketchat[754]: {"level":50,"time":"2022-03-10T02:00:01.656Z","pid":754,"hostname":"hostname","name":"","name":"System","msg":"OEmbed duplicated record","url":"https://github.com/RocketChat/Rocket.Chat/releases/tag/4.5.1"}
Mar 10 02:00:01 hostname rocketchat[754]: {"level":50,"time":"2022-03-10T02:00:01.936Z","pid":754,"hostname":"hostname","name":"","name":"System","msg":"OEmbed duplicated record","url":"https://github.com/RocketChat/Rocket.Chat/releases/tag/4.5.1"}
Mar 10 02:00:05 hostname rocketchat[754]: {"level":40,"time":"2022-03-10T02:00:05.492Z","pid":754,"hostname":"hostname","name":"","name":"Push","msg":"Error sending push to gateway (not authorized) {\"statusCode\":401,\"content\":\"{\\\"code\\\":121,\\\"error\\\":\\\"rocket.chat cloud registration required\\\",\\\"requestId\\\":\\\"f5c4ea87-065d-44c2-9ed>
Mar 10 02:00:05 hostname rocketchat[754]: {"level":40,"time":"2022-03-10T02:00:05.510Z","pid":754,"hostname":"hostname","name":"","name":"Push","msg":"Error sending push to gateway (not authorized) {\"statusCode\":401,\"content\":\"{\\\"code\\\":121,\\\"error\\\":\\\"rocket.chat cloud registration required\\\",\\\"requestId\\\":\\\"f4dd5c72-b599-401b-9ee>
Mar 10 02:00:05 hostname rocketchat[754]: {"level":40,"time":"2022-03-10T02:00:05.519Z","pid":754,"hostname":"hostname","name":"","name":"Push","msg":"Error sending push to gateway (not authorized) {\"statusCode\":401,\"content\":\"{\\\"code\\\":121,\\\"error\\\":\\\"rocket.chat cloud registration required\\\",\\\"requestId\\\":\\\"2e2eeb59-cd26-4d3c-a80>
Mar 10 02:00:05 hostname rocketchat[754]: {"level":40,"time":"2022-03-10T02:00:05.521Z","pid":754,"hostname":"hostname","name":"","name":"Push","msg":"Error sending push to gateway (not authorized) {\"statusCode\":401,\"content\":\"{\\\"code\\\":121,\\\"error\\\":\\\"rocket.chat cloud registration required\\\",\\\"requestId\\\":\\\"9adfa63a-8793-4d56-928>
Mar 10 02:00:05 hostname rocketchat[754]: {"level":40,"time":"2022-03-10T02:00:05.529Z","pid":754,"hostname":"hostname","name":"","name":"Push","msg":"Error sending push to gateway (not authorized) {\"statusCode\":401,\"content\":\"{\\\"code\\\":121,\\\"error\\\":\\\"rocket.chat cloud registration required\\\",\\\"requestId\\\":\\\"0795cbee-fe7e-4d7d-8c9>
Mar 10 06:12:05 hostname rocketchat[754]: {"level":40,"time":"2022-03-10T06:12:05.171Z","pid":754,"hostname":"hostname","name":"","name":"SyncedCron","msg":"Failed to send usage report"}
Mar 10 11:12:05 hostname rocketchat[754]: {"level":40,"time":"2022-03-10T11:12:05.842Z","pid":754,"hostname":"hostname","name":"","name":"SyncedCron","msg":"Failed to send usage report"}
Mar 10 20:12:05 hostname rocketchat[754]: {"level":40,"time":"2022-03-10T20:12:05.858Z","pid":754,"hostname":"hostname","name":"","name":"SyncedCron","msg":"Failed to send usage report"}
Mar 10 20:46:00 hostname rocketchat[754]: {"level":40,"time":"2022-03-10T20:46:00.506Z","pid":754,"hostname":"hostname","name":"","name":"Push","msg":"Error sending push to gateway (not authorized) {\"statusCode\":401,\"content\":\"{\\\"code\\\":121,\\\"error\\\":\\\"rocket.chat cloud registration required\\\",\\\"requestId\\\":\\\"b8bc58d1-255a-49d8-a91>
Mar 11 12:00:20 hostname rocketchat[754]: {"level":50,"time":"2022-03-11T12:00:20.028Z","pid":754,"hostname":"hostname","name":"","name":"System","err":{"type":"FetchError","message":"network timeout at: https://cloud.rocket.chat/api/oauth/token","stack":"FetchError: network timeout at: https://cloud.rocket.chat/api/oauth/token\n    at Timeout.<anonymous>
Mar 11 14:27:30 hostname rocketchat[754]: {"level":50,"time":"2022-03-11T14:27:30.975Z","pid":754,"hostname":"hostname","name":"","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"}



Mar 11 19:47:00 hostname rocketchat[754]: /opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92
Mar 11 19:47:00 hostname rocketchat[754]:                                         return fn.apply(this, arguments);
Mar 11 19:47:00 hostname rocketchat[754]:                                                   ^
Mar 11 19:47:00 hostname rocketchat[754]: RangeError: Out of memory
Mar 11 19:47:00 hostname rocketchat[754]:     at Fiber.run (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92:16)
Mar 11 19:47:00 hostname rocketchat[754]:     at process.<anonymous> (packages/meteor.js:1334:31)
Mar 11 19:47:00 hostname rocketchat[754]:     at process.emit (events.js:327:22)
Mar 11 19:47:00 hostname rocketchat[754]:     at process.EventEmitter.emit (domain.js:485:12)
Mar 11 19:47:00 hostname rocketchat[754]:     at process._fatalException (internal/process/execution.js:165:25)
Mar 11 19:47:00 hostname systemd[1]: rocketchat.service: Main process exited, code=exited, status=7/NOTRUNNING
Mar 11 19:47:00 hostname systemd[1]: rocketchat.service: Failed with result 'exit-code'.
```

**Comment by pwojcieszonek** [comment]
I have same problem on 4.5.2
`mar 15 08:57:36 rocketchat rocketchat[19613]:                                                   ^
mar 15 08:57:36 rocketchat rocketchat[19613]: RangeError: Out of memory
mar 15 08:57:36 rocketchat rocketchat[19613]:     at Fiber.run (<anonymous>)
mar 15 08:57:36 rocketchat rocketchat[19613]:     at Fiber.run (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92:16)
mar 15 08:57:36 rocketchat rocketchat[19613]:     at process.<anonymous> (packages/meteor.js:1334:31)
mar 15 08:57:36 rocketchat rocketchat[19613]:     at process.emit (events.js:327:22)
mar 15 08:57:36 rocketchat rocketchat[19613]:     at process.EventEmitter.emit (domain.js:485:12)
mar 15 08:57:36 rocketchat rocketchat[19613]:     at process._fatalException (internal/process/execution.js:165:25)
mar 15 08:57:36 rocketchat systemd[1]: rocketchat.service: Main process exited, code=exited, status=7/NOTRUNNING
mar 15 08:57:36 rocketchat systemd[1]: rocketchat.service: Failed with result 'exit-code'.`

**Comment by MikolaTesla** [comment]
I have same problem on 4.5.2


Mar 22 09:19:19 srv-rocket rocketchat[767]:                                         return fn.apply(this, arguments);
Mar 22 09:19:19 srv-rocket rocketchat[767]:                                                   ^
Mar 22 09:19:19 srv-rocket rocketchat[767]: RangeError: Out of memory
Mar 22 09:19:19 srv-rocket rocketchat[767]:     at Fiber.run (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92:16)
Mar 22 09:19:19 srv-rocket rocketchat[767]:     at process.<anonymous> (packages/meteor.js:1334:31)
Mar 22 09:19:19 srv-rocket rocketchat[767]:     at process.emit (events.js:327:22)
Mar 22 09:19:19 srv-rocket rocketchat[767]:     at process.EventEmitter.emit (domain.js:485:12)
Mar 22 09:19:19 srv-rocket rocketchat[767]:     at process._fatalException (internal/process/execution.js:165:25)
Mar 22 09:19:19 srv-rocket systemd[1]: rocketchat.service: Main process exited, code=exited, status=7/NOTRUNNING
Mar 22 09:19:19 srv-rocket systemd[1]: rocketchat.service: Failed with result 'exit-code'

**Comment by franciscopaniskaseker** [comment]
The doc says to install 14.0.0 ( https://docs.rocket.chat/quick-start/installing-and-updating/other-deployment-methods/manual-installation/updating ), but I upgraed to 14.14.0 to test. After 6 days no crash yet.

**Comment by jaykoby** [comment]
Same problem here! :+1:

**Comment by vv9k** [comment]
Same problem here.

```
Mar 30 22:46:11 chat rocketchat[4757]: Internal exception while processing message { msg: 'pong' }
Mar 30 22:46:11 chat rocketchat[4757]: /opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92
Mar 30 22:46:11 chat rocketchat[4757]: #011#011#011#011#011return fn.apply(this, arguments);
Mar 30 22:46:11 chat rocketchat[4757]: #011#011#011#011#011          ^
Mar 30 22:46:11 chat rocketchat[4757]: RangeError: Out of memory
Mar 30 22:46:11 chat rocketchat[4757]:     at Fiber.run (<anonymous>)
Mar 30 22:46:11 chat rocketchat[4757]:     at Fiber.run (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92:16)
Mar 30 22:46:11 chat rocketchat[4757]:     at process.<anonymous> (packages/meteor.js:1334:31)
Mar 30 22:46:11 chat rocketchat[4757]:     at process.emit (events.js:412:35)
Mar 30 22:46:11 chat rocketchat[4757]:     at process.emit (domain.js:475:12)
Mar 30 22:46:11 chat rocketchat[4757]:     at process._fatalException (internal/process/execution.js:167:25)
```

**Comment by franciscopaniskaseker** [comment]
> The doc says to install 14.0.0 ( https://docs.rocket.chat/quick-start/installing-and-updating/other-deployment-methods/manual-installation/updating ), but I upgraed to 14.14.0 to test. After 6 days no crash yet.

new feedback: 15 days without this problem. I think the nodejs update will fix. I am using 14.14.0.

**Comment by yoerin** [comment]
We are also experiencing problems, our node is running v14.19.1
`● rocketchat.service - The Rocket.Chat server
     Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-04-04 10:16:26 CEST; 2min 41s ago
    Process: 850552 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=7)
   Main PID: 850552 (code=exited, status=7)

Apr 04 10:16:26 rocketchat[850552]:                                                   ^
Apr 04 10:16:26 rocketchat[850552]: RangeError: Out of memory
Apr 04 10:16:26 rocketchat[850552]:     at Fiber.run (<anonymous>)
Apr 04 10:16:26 rocketchat[850552]:     at Fiber.run (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92:16)
Apr 04 10:16:26 rocketchat[850552]:     at process.<anonymous> (packages/meteor.js:1334:31)
Apr 04 10:16:26 rocketchat[850552]:     at process.emit (events.js:412:35)
Apr 04 10:16:26 rocketchat[850552]:     at process.emit (domain.js:475:12)
Apr 04 10:16:26 rocketchat[850552]:     at process._fatalException (internal/process/execution.js:167:25)
Apr 04 10:16:26 systemd[1]: rocketchat.service: Main process exited, code=exited, status=7/NOTRUNNING
Apr 04 10:16:26 systemd[1]: rocketchat.service: Failed with result 'exit-code'.`

**Comment by patit72** [comment]
Same problem here (server RAM is not the issue).
Upgraded npm to 4.19.1 and RC to 4.6.0
Usually it crashes every 24 hours so I will let you know

**Comment by BoJackBR** [comment]
Same problem here, guys.

Apr 13 11:48:59 rocketchat rocketchat[24730]: /opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92
Apr 13 11:48:59 rocketchat rocketchat[24730]: #011#011#011#011#011return fn.apply(this, arguments);
Apr 13 11:48:59 rocketchat rocketchat[24730]: #011#011#011#011#011          ^
Apr 13 11:48:59 rocketchat rocketchat[24730]: RangeError: Out of memory
Apr 13 11:48:59 rocketchat rocketchat[24730]:     at Fiber.run (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92:16)
Apr 13 11:48:59 rocketchat rocketchat[24730]:     at process.<anonymous> (packages/meteor.js:1334:31)
Apr 13 11:48:59 rocketchat rocketchat[24730]:     at process.emit (events.js:327:22)
Apr 13 11:48:59 rocketchat rocketchat[24730]:     at process.EventEmitter.emit (domain.js:485:12)
Apr 13 11:48:59 rocketchat rocketchat[24730]:     at process._fatalException (internal/process/execution.js:165:25)
Apr 13 11:49:00 rocketchat systemd[1]: rocketchat.service: Main process exited, code=exited, status=7/NOTRUNNING
Apr 13 11:49:00 rocketchat systemd[1]: rocketchat.service: Failed with result 'exit-code'.

Apr 13 11:52:40 rocketchat rocketchat[57754]: +----------------------------------------------------------+
Apr 13 11:52:40 rocketchat rocketchat[57754]: |                      SERVER RUNNING                      |
Apr 13 11:52:40 rocketchat rocketchat[57754]: +----------------------------------------------------------+
Apr 13 11:52:40 rocketchat rocketchat[57754]: |                                                          |
Apr 13 11:52:40 rocketchat rocketchat[57754]: |  Rocket.Chat Version: 4.6.1                              |
Apr 13 11:52:40 rocketchat rocketchat[57754]: |       NodeJS Version: 14.0.0 - x64                       |
Apr 13 11:52:40 rocketchat rocketchat[57754]: |      MongoDB Version: 4.2.19                             |
Apr 13 11:52:40 rocketchat rocketchat[57754]: |       MongoDB Engine: wiredTiger                         |
Apr 13 11:52:40 rocketchat rocketchat[57754]: |             Platform: linux                              |
Apr 13 11:52:40 rocketchat rocketchat[57754]: |         Process Port: 3000                               |
Apr 13 11:52:40 rocketchat rocketchat[57754]: |             Site URL: https://localhost  |
Apr 13 11:52:40 rocketchat rocketchat[57754]: |     ReplicaSet OpLog: Enabled                            |
Apr 13 11:52:40 rocketchat rocketchat[57754]: |          Commit Hash: 174728c96e                         |
Apr 13 11:52:40 rocketchat rocketchat[57754]: |        Commit Branch: HEAD                               |
Apr 13 11:52:40 rocketchat rocketchat[57754]: |                                                          |
Apr 13 11:52:40 rocketchat rocketchat[57754]: +----------------------------------------------------------+

**Comment by BoJackBR** [comment]
> > The doc says to install 14.0.0 ( https://docs.rocket.chat/quick-start/installing-and-updating/other-deployment-methods/manual-installation/updating ), but I upgraed to 14.14.0 to test. After 6 days no crash yet.
> 
> new feedback: 15 days without this problem. I think the nodejs update will fix. I am using 14.14.0.


No problems yet?

**Comment by franciscopaniskaseker** [comment]
> No problems yet?

No! after upgrade nodejs to 14.14.0 I did not see problems for last 22 days. I was seeing at least one time per week.

**Comment by yoerin** [comment]
Can anyone confirm that it is running stable with nodejs 14.14.0 ?
We are running v14.19.1 and it still keeps crashing.

**Comment by franciscopaniskaseker** [comment]
For me it never happened again.

**Comment by daloman** [comment]
> Can anyone confirm that it is running stable with nodejs 14.14.0 ?

Same problem. Rocketchat crashes with "Out of memory" more than 30000 times for 9 hours
Import process (Slack archive) crashes also with "Out of memory"

> |                                                         |
|  Rocket.Chat Version: 4.5.2                             |
|       NodeJS Version: 14.18.3 - x64                     |
|      MongoDB Version: 4.4.13                            |
|       MongoDB Engine: wiredTiger                        |
|             Platform: linux                             |
|         Process Port: 3000                              |
|             Site URL:   |
|     ReplicaSet OpLog: Enabled                           |
|          Commit Hash: ed2cb3fe61                        |
|        Commit Branch: HEAD                              |


No problems after downgrade Node version to 14.14.0 for last 10 hours.

> Rocket.Chat Version: 4.5.2                                                 |
|       NodeJS Version: 14.14.0 - x64                                         |
|      MongoDB Version: 4.4.13                                                |
|       MongoDB Engine: wiredTiger                                            |
|             Platform: linux                                                 |
|         Process Port: 3000                                                  |
|             Site URL:   |
|     ReplicaSet OpLog: Enabled                                               |
|          Commit Hash: ed2cb3fe61                                            |
|        Commit Branch: HEAD

**Comment by BoJackBR** [comment]
> Can anyone confirm that it is running stable with nodejs 14.14.0 ? We are running v14.19.1 and it still keeps crashing.

I'm on version 14.18.3 and I had no more problems
![image](https://user-images.githubusercontent.com/35930902/164727816-7e78e12b-de9d-4ab6-84c3-e5a3b185b2f2.png)

**Comment by hw-p** [comment]
We got same Issue, crashing 1x / day
-----------------------

May 05 09:36:47 chat rocketchat[24310]: RangeError: Out of memory

**Comment by franciscopaniskaseker** [comment]
@hw-p which nodejs version?

**Comment by hw-p** [comment]
> @hw-p which nodejs version?

# npm -v
6.14.4
# nodejs -v
v12.22.1

**Comment by franciscopaniskaseker** [comment]
The bug still continue happening with 14.0.0 node version, but not with 14.14.0. I am not sure which is the most recent version that I can use.

Here https://docs.rocket.chat/deploy/prepare-for-your-deployment/other-deployment-methods/manual-installation/updating still say 14.0.0.
