### ISSUE TITLE
Cannot edit rocket.cat user

### ISSUE THREAD

**Issue by maciejpankanin** [RocketChat/Rocket.Chat#24703]
### Description:

I have **rocket.cat** bot user without email (IDK if it is normal). Recently I wanted to change its avatar but I cannot because form validation says email is required. Then filled it with some random email and encountered this error:
```json
{
   "success":false,
   "error":"Cannot read property '0' of undefined"
}
```

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: -
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.18.3
- MongoDB Version: 4.4.12

### Client Setup Information

- Desktop App or Browser Version: Any browser
- Operating System: Any OS

### Relevant logs:

```json
{
   "level":35,
   "time":"2022-03-04T13:43:42.599Z",
   "pid":8,
   "hostname":"2f0d2085cc00",
   "name":"",
   "name":"API",
   "method":"POST",
   "url":"/api/v1/users.update",
   "userId":"eKGietiJnJjdxs6iQ",
   "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.62",
   "length":"294",
   "host":"192.168.1.10:8804",
   "referer":"https://chat.jaggi.com.pl/admin/users/edit/rocket.cat",
   "remoteIP":"91.222.69.248",
   "err":{
      "type":"TypeError",
      "message":"Cannot read property '0' of undefined",
      "stack":"TypeError: Cannot read property '0' of undefined\n    at validateUserEditing (app/lib/server/functions/saveUser.js:210:3)\n    at saveUser (app/lib/server/functions/saveUser.js:344:2)\n    at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/users.js:594:40)\n    at packages/dispatch_run-as-user.js:211:14\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)\n    at Object.post (app/api/server/v1/users.js:594:11)\n    at app/api/server/api.js:425:96\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9"
   },
   "status":400,
   "responseTime":21,
   "msg":"Cannot read property '0' of undefined"
}
```

**Comment by dudanogueira** [comment]
This is probably related: https://github.com/RocketChat/Rocket.Chat/issues/23478

This error was a hard one to reproduce. I think we have a consistent way now. Thanks!
