### ISSUE TITLE
Can no longer add new users to a channel

### ISSUE THREAD

**Issue by skadefro** [RocketChat/Rocket.Chat#24736]
### Description:
In latest version of Rocket Chat you can no longer add users to a channel.

### Steps to reproduce:

1. Open https://rocket.openiap.io/
2. Click on a channel you are admin off 
3. Click Members, then click Add .. as soon as you type something the page turns white

### Expected behavior:

The page should not turn white, but start auto completing usernames you can add.

### Actual behavior:

![image](https://user-images.githubusercontent.com/4155937/157209881-8bc5b7cf-89bd-4a86-b466-0d34b92d1c9d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.0
- Operating System: linux/amd64 ( using docker, currently on tag :4.5.0 )
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v14.18.3
- MongoDB Version: 5.0.6 ( using mongodb atlas )

### Client Setup Information

- Desktop App or Browser Version: broken in both browser and electron app.
- Operating System: Windows 11

**Comment by devadattas** [comment]
Same here!

**Comment by txwheeler** [comment]
We are having the same issue and have submitted a ticket to them for enterprise. No resolution yet.

**Comment by vinzv** [comment]
Same problem here: 
![grafik](https://user-images.githubusercontent.com/74432/157273368-46b97666-0c81-471b-be1b-ffd55f2b133c.png)

**Comment by vinzv** [comment]
Nope, no SAML here.

**Comment by vinzv** [comment]
This PR fixes the problem btw: https://github.com/RocketChat/Rocket.Chat/pull/24328/files

**Comment by amottier** [comment]
This is likely to be a duplicated of #24673

**Comment by skadefro** [comment]
i just updasted to 4.5.1 but the error is still there.

**Comment by TwizzyDizzy** [comment]
I can confirm, that in `4.5.1` I still get the `toLowerCase` error.

While in `4.5.0` I couldn't add any user, in `4.5.1` I could add a user. Yet, when searching for another one I, again, reproducibly run into the attached error: [1647010333482.log](https://github.com/RocketChat/Rocket.Chat/files/8232993/1647010333482.log)

Cheers
Thomas

**Comment by dudanogueira** [comment]
**FYI**
I was have this bug on a playground rocketchat instance I have.

but not on my dev environment. 

While trying to find the difference, I noticed one of the users didn't had a name.  After filling up this user name and saving, the bug was gone.

running it on dev dev, I created a new user, and removed it's name directly in mongo (can't do it using UI), and **was not able to reproduce it**

This is probably those edge cases, hard to find, easy to fix.

It would help a lot if you are able to come up with exact steps to reproduce this on a fresh install. Otherwise is very difficult to scale this up with our dev team.

THanks!

**Comment by skadefro** [comment]
Good thinking. I had 52 users with no username and name.
So I set a username and name for all. That did not help. So restartet the pod, still no luck.

**Comment by dudanogueira** [comment]
I think I was able to narrow it down, or at least reproduce it consistently.

If a user **do not have** the name attribute in mongo, it triggers the error.

This MAY be caused to admin being created with the environment variables.

This is the full stack for the browser error on 4.5.1 dev environment:

Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at applyFilter (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:12650:34)
    at Array.filter (<anonymous>)
    at modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:12653:10
    at renderWithHooks (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:62654:18)
    at updateForwardRef (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:64713:20)
    at beginWork (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:66767:16)
    at HTMLUnknownElement.callCallback (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51614:14)
    at Object.invokeGuardedCallbackDev (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51663:16)
    at invokeGuardedCallback (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51725:31)
    at beginWork$1 (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:71633:7)
applyFilter @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:12650
(anonymous) @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:12653
renderWithHooks @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:62654
updateForwardRef @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:64713
beginWork @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:66767
callCallback @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51614
invokeGuardedCallbackDev @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51663
invokeGuardedCallback @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51725
beginWork$1 @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:71633
performUnitOfWork @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:70448
workLoopSync @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:70376
renderRootSync @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:70339
performSyncWorkOnRoot @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:69962
(anonymous) @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:58996
unstable_runWithPriority @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:74482
runWithPriority$1 @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:58945
flushSyncCallbackQueueImpl @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:58991
flushSyncCallbackQueue @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:58978
flushPendingDiscreteUpdates @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:70041
flushDiscreteUpdates @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:70022
finishEventHandler @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51383
batchedEventUpdates @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51417
dispatchEventForPluginEventSystem @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:56176
attemptToDispatchEvent @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:53674
dispatchEvent @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:53593
unstable_runWithPriority @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:74482
runWithPriority$1 @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:58945
discreteUpdates$1 @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:70082
discreteUpdates @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51425
dispatchDiscreteEvent @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:53558
modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:67754 The above error occurred in the <ForwardRef> component:

    at http://127.0.0.1:3000/packages/modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:12617:20
    at MultiSelectFiltered (http://127.0.0.1:3000/packages/modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:12807:22)
    at UserAutoCompleteMultiple (http://127.0.0.1:3000/app/app.js?hash=7bce30e5f8a71be1ac1d9e5707e592449dec555d:72127:5)
    at div
    at Box (http://127.0.0.1:3000/packages/modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:5352:22)
    at div
    at Box (http://127.0.0.1:3000/packages/modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:5352:22)
    at div
    at Box (http://127.0.0.1:3000/packages/modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:5352:22)
    at Scrollable (http://127.0.0.1:3000/packages/modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:14428:23)
    at ModalContent (http://127.0.0.1:3000/packages/modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:12267:23)
    at div
    at Box (http://127.0.0.1:3000/packages/modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:5352:22)
    at dialog
    at Box (http://127.0.0.1:3000/packages/modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:5352:22)
    at http://127.0.0.1:3000/packages/modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:12154:23
    at CreateDirectMessage (/client/sidebar/header/CreateDirectMessage.tsx:81:5)
    at div
    at Box (http://127.0.0.1:3000/packages/modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:5352:22)
    at ModalBackdrop (/client/components/modal/ModalBackdrop.tsx:96:5)
    at ModalPortal (/client/components/modal/ModalPortal.tsx:43:5)
    at ModalProvider (/client/providers/ModalProvider.tsx:70:5)
    at OmnichannelProvider (/client/providers/OmnichannelProvider.tsx:136:5)
    at CallProvider (/client/providers/CallProvider/CallProvider.tsx:158:5)
    at AuthorizationProvider (/client/providers/AuthorizationProvider.tsx:92:5)
    at UserProvider (/client/providers/UserProvider.tsx:104:5)
    at CustomSoundProvider (/client/providers/CustomSoundProvider.tsx:33:5)
    at AvatarUrlProvider (/client/providers/AvatarUrlProvider.tsx:70:5)
    at LayoutProvider (/client/providers/LayoutProvider.tsx:67:5)
    at SettingsProvider (/client/providers/SettingsProvider.tsx:92:5)
    at ToastMessagesProvider (/client/providers/ToastMessagesProvider.tsx:58:5)
    at SidebarProvider (/client/providers/SidebarProvider.tsx:50:5)
    at SessionProvider (/client/providers/SessionProvider.tsx:46:5)
    at TranslationProvider (/client/providers/TranslationProvider.js:132:5)
    at RouterProvider (/client/providers/RouterProvider.tsx:96:5)
    at ServerProvider (/client/providers/ServerProvider.tsx:110:5)
    at ConnectionStatusProvider (/client/providers/ConnectionStatusProvider.tsx:52:5)
    at MeteorProvider (/client/providers/MeteorProvider.tsx:138:5)
    at Suspense
    at AppRoot

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:67754
update.callback @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:67787
callCallback @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:59987
commitUpdateQueue @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:60008
commitLifeCycles @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:68405
commitLayoutEffects @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:71095
callCallback @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51614
invokeGuardedCallbackDev @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51663
invokeGuardedCallback @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51725
commitRootImpl @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:70820
unstable_runWithPriority @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:74482
runWithPriority$1 @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:58945
commitRoot @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:70659
performSyncWorkOnRoot @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:69998
(anonymous) @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:58996
unstable_runWithPriority @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:74482
runWithPriority$1 @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:58945
flushSyncCallbackQueueImpl @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:58991
flushSyncCallbackQueue @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:58978
flushPendingDiscreteUpdates @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:70041
flushDiscreteUpdates @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:70022
finishEventHandler @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51383
batchedEventUpdates @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51417
dispatchEventForPluginEventSystem @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:56176
attemptToDispatchEvent @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:53674
dispatchEvent @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:53593
unstable_runWithPriority @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:74482
runWithPriority$1 @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:58945
discreteUpdates$1 @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:70082
discreteUpdates @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51425
dispatchDiscreteEvent @ modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:53558
modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:12650 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at applyFilter (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:12650:34)
    at Array.filter (<anonymous>)
    at modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:12653:10
    at renderWithHooks (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:62654:18)
    at updateForwardRef (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:64713:20)
    at beginWork (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:66767:16)
    at HTMLUnknownElement.callCallback (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51614:14)
    at Object.invokeGuardedCallbackDev (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51663:16)
    at invokeGuardedCallback (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:51725:31)
    at beginWork$1 (modules.js?hash=0d2afd7e8d5114df0661fcf3e3b132486228101b:71633:7)

**Comment by dudanogueira** [comment]
@skadefro, Can you check if this is fixed in 4.5.2?

I was able to reproduce this on 4.5.1, but no longer on 4.5.2

Thanks!

**Comment by skadefro** [comment]
@dudanogueira success ... With 3.52 the problem is fixed :-)
