### ISSUE TITLE
tiny-secp256k1@1.1.3 fails to build during install

### ISSUE THREAD

**Issue by oliob** [RocketChat/Rocket.Chat#24815]
### Description:

When installing v4.5.2 i got build errors for tiny-secp256k1@1.1.3. 
Install works fine though. Server starts and I haven't recognized any issue yet while running the server.

### Steps to reproduce:

1. Download RocketChat tgz and extract
2. run npm install

### Expected behavior:

no errors during install

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.19.0
- MongoDB Version: 4.4.13

### Relevant logs:

> npm run build || echo "secp256k1 bindings compilation fail. Pure JS implementation will be used."

> tiny-secp256k1@1.1.3 build /tmp/bundle/programs/server/npm/node_modules/tiny-secp256k1
> node-gyp rebuild

make: Entering directory '/tmp/bundle/programs/server/npm/node_modules/tiny-secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/native/addon.o
In file included from ../native/addon.cpp:4:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../node_modules/nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../native/addon.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE ecdsaVerify(Nan::NAN_METHOD_ARGS_TYPE)’:
../native/addon.cpp:320:56: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
  320 |   strict = info[3]->BooleanValue(Nan::GetCurrentContext()).FromJust();
      |                                  ~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                        |
      |                                                        v8::Local<v8::Context>
In file included from /home/user/.cache/node-gyp/14.19.0/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:54,
                 from ../native/addon.cpp:4:
/home/user/.cache/node-gyp/14.19.0/include/node/v8.h:2858:30: note:   initializing argument 1 of ‘bool v8::Value::BooleanValue(v8::Isolate*) const’
 2858 |   bool BooleanValue(Isolate* isolate) const;
      |                     ~~~~~~~~~^~~~~~~
In file included from ../node_modules/nan/nan.h:54,
                 from ../native/addon.cpp:4:
../native/addon.cpp: At global scope:
/home/user/.cache/node-gyp/14.19.0/include/node/node.h:793:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  793 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/user/.cache/node-gyp/14.19.0/include/node/node.h:827:3: note: in expansion of macro ‘NODE_MODULE_X’
  827 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../native/addon.cpp:359:1: note: in expansion of macro ‘NODE_MODULE’
  359 | NODE_MODULE(secp256k1, Init)
      | ^~~~~~~~~~~
../native/addon.cpp: In instantiation of ‘unsigned int {anonymous}::assumeCompression(const I&, const A&) [with long unsigned int index = 2; I = Nan::FunctionCallbackInfo<v8::Value>; A = v8::Local<v8::Object>]’:
../native/addon.cpp:142:50:   required from here
../native/addon.cpp:80:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
   80 |   if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
../native/addon.cpp:82:58: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
   82 |   return info[index]->BooleanValue(Nan::GetCurrentContext()).FromJust() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
      |                                    ~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                          |
      |                                                          v8::Local<v8::Context>
In file included from /home/user/.cache/node-gyp/14.19.0/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:54,
                 from ../native/addon.cpp:4:
/home/user/.cache/node-gyp/14.19.0/include/node/v8.h:2858:30: note:   initializing argument 1 of ‘bool v8::Value::BooleanValue(v8::Isolate*) const’
 2858 |   bool BooleanValue(Isolate* isolate) const;
      |                     ~~~~~~~~~^~~~~~~
../native/addon.cpp: In instantiation of ‘unsigned int {anonymous}::assumeCompression(const I&, const A&) [with long unsigned int index = 1; I = Nan::FunctionCallbackInfo<v8::Value>; A = v8::Local<v8::Object>]’:
../native/addon.cpp:174:49:   required from here
../native/addon.cpp:80:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
   80 |   if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
../native/addon.cpp:82:58: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
   82 |   return info[index]->BooleanValue(Nan::GetCurrentContext()).FromJust() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
      |                                    ~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                          |
      |                                                          v8::Local<v8::Context>
In file included from /home/user/.cache/node-gyp/14.19.0/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:54,
                 from ../native/addon.cpp:4:
/home/user/.cache/node-gyp/14.19.0/include/node/v8.h:2858:30: note:   initializing argument 1 of ‘bool v8::Value::BooleanValue(v8::Isolate*) const’
 2858 |   bool BooleanValue(Isolate* isolate) const;
      |                     ~~~~~~~~~^~~~~~~
../native/addon.cpp: In instantiation of ‘unsigned int {anonymous}::assumeCompression(const I&) [with long unsigned int index = 1; I = Nan::FunctionCallbackInfo<v8::Value>]’:
../native/addon.cpp:189:46:   required from here
../native/addon.cpp:87:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
   87 |   if (info.Length() <= index) return SECP256K1_EC_COMPRESSED;
../native/addon.cpp:89:58: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
   89 |   return info[index]->BooleanValue(Nan::GetCurrentContext()).FromJust() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
      |                                    ~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                          |
      |                                                          v8::Local<v8::Context>
In file included from /home/user/.cache/node-gyp/14.19.0/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:54,
                 from ../native/addon.cpp:4:
/home/user/.cache/node-gyp/14.19.0/include/node/v8.h:2858:30: note:   initializing argument 1 of ‘bool v8::Value::BooleanValue(v8::Isolate*) const’
 2858 |   bool BooleanValue(Isolate* isolate) const;
      |                     ~~~~~~~~~^~~~~~~
../native/addon.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE eccPrivateSub(Nan::NAN_METHOD_ARGS_TYPE)’:
../native/addon.cpp:240:29: warning: ignoring return value of ‘int secp256k1_ec_privkey_negate(const secp256k1_context*, unsigned char*)’, declared with attribute warn_unused_result [-Wunused-result]
  240 |  secp256k1_ec_privkey_negate(context, tweak_negated); // returns 1 always
      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
make: *** [secp256k1.target.mk:153: Release/obj.target/secp256k1/native/addon.o] Error 1
make: Leaving directory '/tmp/bundle/programs/server/npm/node_modules/tiny-secp256k1/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.4.0-104-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/bundle/programs/server/npm/node_modules/tiny-secp256k1
gyp ERR! node -v v14.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.3 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-03-12T08_20_38_739Z-debug.log
secp256k1 bindings compilation fail. Pure JS implementation will be used.

**Comment by lovekyleman** [comment]
![image](https://user-images.githubusercontent.com/93461213/158021071-b7bcb77f-2960-4271-89c9-d7d995160224.jpeg)

**Comment by Gummikavalier** [comment]
We are getting this with the required NPM 6.14.15 version. Build succeeds with NPM 8.5.3 on another instance.

And the one running NPM 6.14.15 fails with anything never along with python3 env path errors.

**Comment by japrogramer** [comment]
Ive tried to use NPM @Latest to build and install but same error

the command `meteor ` fails with

```
/home/archangel/.meteor/packages/meteor-tool/.2.5.6.1oomsiz.f4ou++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.readMetadataFromDirectory (/tools/isobuild/isopack.js:204:28)
    at exports.Tropohouse._alreadyDownloaded (/tools/packaging/tropohouse.js:320:19)
    at exports.Tropohouse._makeDownloader (/tools/packaging/tropohouse.js:391:33)
    at /tools/packaging/tropohouse.js:568:29
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/packaging/tropohouse.js:565:20
    at /tools/packaging/package-map.js:57:7
    at Function.each (/home/archangel/.meteor/packages/meteor-tool/.2.5.6.1oomsiz.f4ou++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at exports.PackageMap.eachPackage (/tools/packaging/package-map.js:49:7)
    at exports.Tropohouse.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:561:16)
    at /tools/project-context.js:921:25
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/project-context.js:920:20
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (/tools/project-context.js:919:13)
    at /tools/project-context.js:365:9
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:355:18)
    at /tools/project-context.js:347:12
    at Function.run (/home/archangel/.meteor/packages/meteor-tool/.2.5.6.1oomsiz.f4ou++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:346:13)
    at /tools/runners/run-app.js:556:29
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundleApp (/tools/runners/run-app.js:555:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:627:35)
    at AppRunner._fiber (/tools/runners/run-app.js:949:28)
    at /tools/runners/run-app.js:410:12


```

**Comment by Cob0ld** [comment]
We have the same problem update ->>

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/bundle/programs/server/npm/node_modules/@rocket.chat/forked-matrix-sdk-crypto-nodejs/lib/index.linux-x64-gnu.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/tmp/bundle/programs/server/npm/node_modules/@rocket.chat/forked-matrix-sdk-crypto-nodejs/lib/napi-module.js:145:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rocket.chat/forked-matrix-sdk-crypto-nodejs@0.1.0-beta.12 postinstall: `node check-exists.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @rocket.chat/forked-matrix-sdk-crypto-nodejs@0.1.0-beta.12 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lcadmin/.npm/_logs/2022-06-03T20_32_34_087Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by FractalizeR** [comment]
Same problem on Ubuntu 18.04

**Comment by KevLehman** [comment]
Should be fixed in newer releases, if u encounter it again, pls open a new issue.
