### ISSUE TITLE
Search error when trying to direct message users for the first time.

### ISSUE THREAD

**Issue by herculesbl9** [RocketChat/Rocket.Chat#24886]
### Description:

When searching for a user I have not direct messaged in the past, the search function returns the user's username instead of name and the wrong URL to the user's room (in fact, it only seems to return a part of the actual URL). The issue is resolved when I select the user from the Directory. After that, the search returns the correct URL and full name instead of username

### Steps to reproduce:

1. On the home page of the server click the search icon on the top left
2. Type a user's username or full name
3. Click on the desired entry

### Expected behavior:

Open the user's room to direct message them.

### Actual behavior:

A page saying "This room does not exist or you may not have permission to access" comes up.
![image](https://user-images.githubusercontent.com/41948231/159128115-66a5029d-f114-4390-b87f-2a9b728c709f.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.1
- Operating System: Ubuntu 20.04.4 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.18.3
- MongoDB Version: 4.2.17 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Google Chrome Version 99.0.4844.74 (Official Build) (64-bit)
- Operating System: Windows 11

### Additional context

User registration is done via LDAP.
The account that encountered the problem is an admin account with sufficient privileges to view everything.

### Relevant logs:

```
{"level":50,"time":"2022-03-19T11:37:14.684Z","pid":1466,"hostname":"aspire","name":"LDAP","err":{"type":"Error","message":"User not found","stack":"Error: User not found<br>    at server/lib/ldap/Manager.ts:167:11<br>    at /snap/rocketchat-server/1513/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"User not found"} 
{"level":50,"time":"2022-03-19T11:37:14.802Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method login 'User not found [403]'"} 
{"level":50,"time":"2022-03-19T11:37:55.683Z","pid":1466,"hostname":"aspire","name":"LDAP","err":{"type":"Error","message":"User not found","stack":"Error: User not found<br>    at server/lib/ldap/Manager.ts:167:11<br>    at /snap/rocketchat-server/1513/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"User not found"} 
{"level":50,"time":"2022-03-19T11:37:55.702Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method login 'User not found [403]'"} 
{"level":50,"time":"2022-03-19T15:29:58.518Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-03-19T15:29:58.692Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"} 
{"level":50,"time":"2022-03-19T15:30:12.115Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-03-19T15:30:12.297Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"} 
{"level":50,"time":"2022-03-19T15:30:21.556Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-03-19T15:30:21.721Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"} 
{"level":50,"time":"2022-03-19T15:30:59.647Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-03-19T15:30:59.830Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"} 
{"level":50,"time":"2022-03-19T15:31:26.055Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method saveSetting 'TOTP Required [totp-required]'"} 
{"level":50,"time":"2022-03-19T15:32:01.628Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-03-19T15:32:01.813Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"} 
{"level":50,"time":"2022-03-19T15:32:07.451Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-03-19T15:32:07.463Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-03-19T15:32:07.652Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"} 
{"level":50,"time":"2022-03-19T15:32:07.668Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"} 
{"level":50,"time":"2022-03-19T15:32:07.724Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-03-19T15:32:07.921Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"} 
{"level":50,"time":"2022-03-19T15:32:24.939Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-03-19T15:32:51.628Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-03-19T15:32:51.815Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"} 
{"level":50,"time":"2022-03-19T15:33:12.409Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-03-19T15:39:48.460Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-03-19T15:39:48.645Z","pid":1466,"hostname":"aspire","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"} 
```

**Comment by dudanogueira** [comment]
Duplicated. Please refer to: https://github.com/RocketChat/Rocket.Chat/issues/24727
