### ISSUE TITLE
Fileupload to Filesystem is not working

### ISSUE THREAD

**Issue by miscs** [RocketChat/Rocket.Chat#2506]
Your Rocket.Chat version: 0.22.0
Using Docker with configured volume for uploads:
```
rocketchat:
  image: rocketchat/rocket.chat:latest
  volumes:
    - ./uploads:/app/uploads
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://chat.mydomain.com
  links:
    - db:db
  ports:
    - 3000:3000
```

I configured file-uploads in rocket-chat to use FileSystem with directory /app/uploads. I also tried with uploads and /upload. I also restarted the server after every change. 

I have different error Messages - depending on the directory used. I chmoded the docker volume with chmod 777 so there should be no problem writing to it.

using /app/uploads
```
I20160315-10:03:59.534(0) [methods] ufsWrite -> userId: MZGGm9xhCqDAr5cSf , arguments:  [ 'xv4KtXmep79BMkACS', 'fileSystem', 0.022734967779177745 ] 
I20160315-10:03:59.707(0) [methods] ufsWrite -> userId: MZGGm9xhCqDAr5cSf , arguments:  [ 'xv4KtXmep79BMkACS', 'fileSystem', 0.4412642995509622 ] 
I20160315-10:03:59.970(0) [methods] ufsWrite -> userId: MZGGm9xhCqDAr5cSf , arguments:  [ 'xv4KtXmep79BMkACS', 'fileSystem', 1 ] 
I20160315-10:04:00.049(0) [methods] ufsComplete -> userId: MZGGm9xhCqDAr5cSf , arguments:  { '0': 'xv4KtXmep79BMkACS', '1': 'fileSystem' } 
I20160315-10:04:00.612(0) Exception while invoking method 'ufsComplete' Error: EACCES, open '/app/uploads/xv4KtXmep79BMkACS.png'     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)     at [object Object].Meteor.methods.ufsComplete (packages/jalik_ufs/ufs-methods.js:50:1)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:706:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:704:46     at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)     - - - - - 
```

using uploads
```
I20160315-09:40:37.346(0) [methods] ufsWrite -> userId: MZGGm9xhCqDAr5cSf , arguments:  [ 'Ax2XvpDfeFNFJWjvP', 'fileSystem', 0.022734967779177745 ] 
I20160315-09:40:37.534(0) [methods] ufsWrite -> userId: MZGGm9xhCqDAr5cSf , arguments:  [ 'Ax2XvpDfeFNFJWjvP', 'fileSystem', 0.37687538506796625 ] 
I20160315-09:40:37.838(0) [methods] ufsWrite -> userId: MZGGm9xhCqDAr5cSf , arguments:  [ 'Ax2XvpDfeFNFJWjvP', 'fileSystem', 1 ] 
I20160315-09:40:37.909(0) [methods] ufsComplete -> userId: MZGGm9xhCqDAr5cSf , arguments:  { '0': 'Ax2XvpDfeFNFJWjvP', '1': 'fileSystem' } 
I20160315-09:40:38.368(0) Exception while invoking method 'ufsComplete' Error: ENOENT, open 'uploads/Ax2XvpDfeFNFJWjvP.png'     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)     at [object Object].Meteor.methods.ufsComplete (packages/jalik_ufs/ufs-methods.js:50:1)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:706:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:704:46     at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)     - - - - - 
```

Any hints? Thanks!

**Comment by dytec** [comment]
@miscs the error message for the first path (/app/uploads) states that you have a permissions problem.
Are you sure that you chmoded your docker volume recursively?

The message for the second path states that the path (folder) does not exist.

**Comment by miscs** [comment]
I figured out. Somehow it was a problem with my docker-configuration. I am using 

```
 volumes:
    - ./uploads:/fileuploads
```

now and directory /fileuploads inside rocket.chat configuration. Somehow I cloud not get /app/uploads working, but I think that has nothing to do with rocket.chat but with docker somehow. Closing the ticket. Sorry for the trouble,
