### ISSUE TITLE
Can't login to cloud.rocket.chat. 

### ISSUE THREAD

**Issue by JKawohl** [RocketChat/Rocket.Chat#25090]
Possible Dupe: #24919

### Description:

Can't login to cloud.rocket.chat

### Steps to reproduce:

1. Go to cloud.rocket.chat in your browser 
2. Try to login with "send login link" 
3. Try to login with "enter password instead" 

### Expected behavior:

In both cases I would expect be logged in. 

### Actual behavior:
With neither method i can log in to cloud.rocket.chat
![Bildschirmfoto 2022-03-31 um 16 45 27](https://user-images.githubusercontent.com/12275313/162189549-c3cb2917-b344-4e3c-820a-5f2504d9de7e.png)

Blank Page:
And Button "You should be logged to access this page."

### Client Setup Information

Latest Chrome, 
Latest Safari, 
Latest Brave,
Latest Firefox. 
Tried with inkognito mode also. 

### Additional context

I am unable to connect to cloud.rocket.chat. Thus i can't benefit of my sponsorship and / or add apps and features. Password reset mails are received. So that should actually validate the email address exists. 

### Relevant logs:

Browser Console: 
react-dom.production.min.js:209 TypeError: Cannot read properties of null (reading 'map')
    at z (AccountMenu.js:35:55)
    at Gi (react-dom.production.min.js:153:146)
    at vc (react-dom.production.min.js:261:496)
    at sl (react-dom.production.min.js:246:265)
    at cl (react-dom.production.min.js:246:194)
    at Jc (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Bo (react-dom.production.min.js:122:325)
    at Yo (react-dom.production.min.js:123:61)

**Comment by JKawohl** [comment]
Hi Folks,

any recommendations to reconnect? 

Do you need any other information?

Best regards,

Jonathan Kawohl
