### ISSUE TITLE
upgrade to 0.22 fails with Error: Module did not self-register

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#2510]
Your Rocket.Chat version: 0.22

Hello.

Trying to upgrade to 0.22 (from 0.20) gives me:

```
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/opt/rocketchat/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/opt/rocketchat/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
/opt/rocketchat/programs/server/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/opt/rocketchat/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/opt/rocketchat/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

Any hints how to solve this?

thanks and cheers
t.

**Comment by himbeere** [comment]
Obviously the problem can be solved by cd'ing to programs/server/npm/npm-bcrypt and do a "npm update". The should be addressed anyways i guess.

thanks and cheers
t.

**Comment by marceloschmidt** [comment]
@himbeere I've searched for modules using the bcrypt package to try and identify how this might have occurred and I couldn't find anything. Were you working on anything that might have added that package?

**Comment by himbeere** [comment]
hello @marceloschmidt Just installed 0.23.0 and have the same issue. It can be solved the same way as mentioned above.

Bit I really don't know what you mean by "Were you working on anything that might have added that package?" It's a plain rocketchat install. I did not work on anything.

thanks and cheers

**Comment by sampaiodiego** [comment]
@himbeere which steps are you doing for upgrade?
what is your nodejs version? `node --version`
`meteor build` will not work on nodejs version above `0.12`

**Comment by himbeere** [comment]
Hi @sampaiodiego 

Should be fine:

```
chat / # node --version
v0.12.6
chat / #
```

**Comment by engelgabriel** [comment]
Please use node v0.10 until Meteor 1.4, that will support later version of NodeJS.
