### ISSUE TITLE
RocketChat Out of memory - v8 node OOMKilled even when setting --max-old-space-

### ISSUE THREAD

**Issue by vv9k** [RocketChat/Rocket.Chat#25159]
### Description:

Since upgrading from 3.x to 4.5, we're constantly having the RocketChat process OOMKilled by v8. I've tried increasing the available heap size with `--max-old-space-size` to 12GB but the problem still occurs.

Happens everytime I try to launch a background LDAP sync during the day.

### Steps to reproduce:

1. Go to Administration
2. Go to LDAP settings
3. Click on `Sync Now`

### Expected behavior:

RocketChat server not crashing.

### Actual behavior:

The process aborts.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.5
- Operating System: Ubuntu 18.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.1
- MongoDB Version: 4.0.28 / mmapv1 (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Happens from all cleints - web/mobile/desktop
- Operating System: N/A

### Additional context

Here is how RocketChat is initialized in the systemd service:
```
ExecStart=/usr/bin/node --max-old-space-size=12288 --max_old_space_size=12288 /opt/Rocket.Chat/main.js
```

### Relevant logs:

First it crashed with:
```
Apr 12 09:43:10 chat rocketchat[8786]: Exception in callback of async function: RangeError: Out of memory
Apr 12 09:43:10 chat rocketchat[8786]:     at Fiber.run (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92:16)
Apr 12 09:43:10 chat rocketchat[8786]:     at Object.handler (packages/simple_json-routes.js:104:8)
Apr 12 09:43:10 chat rocketchat[8786]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect-route/lib/connect-route.js:106:12
Apr 12 09:43:10 chat rocketchat[8786]:     at runWithEnvironment (packages/meteor.js:1320:24)
Apr 12 09:43:10 chat rocketchat[8786]:     at packages/meteor.js:1333:14
Apr 12 09:43:10 chat rocketchat[8786]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Apr 12 09:43:11 chat rocketchat[8786]:     at Fiber.run (<anonymous>)
Apr 12 09:43:11 chat rocketchat[8786]:     at Fiber.run (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92:16)
Apr 12 09:43:11 chat rocketchat[8786]:     at process.<anonymous> (packages/meteor.js:1334:31)
Apr 12 09:43:11 chat rocketchat[8786]:     at process.emit (events.js:412:35)
Apr 12 09:43:11 chat rocketchat[8786]:     at process.emit (domain.js:475:12)
Apr 12 09:43:11 chat rocketchat[8786]:     at process._fatalException (internal/process/execution.js:167:25)
Apr 12 09:43:12 chat systemd[1]: rocketchat.service: Main process exited, code=exited, status=7/NOTRUNNING
```
On the second try after the server restarted:

```
Apr 12 09:45:20 chat rocketchat[43074]: <--- Last few GCs --->
Apr 12 09:45:20 chat rocketchat[43074]: [43074:0x46d3cd0]   122674 ms: Scavenge 661.3 (694.5) -> 654.7 (698.7) MB, 76.7 / 1.5 ms  (average mu = 0.988, current mu = 0.952) allocation failure
Apr 12 09:45:20 chat rocketchat[43074]: [43074:0x46d3cd0]   122839 ms: Scavenge 666.1 (699.1) -> 659.7 (703.8) MB, 79.0 / 1.6 ms  (average mu = 0.988, current mu = 0.952) allocation failure
Apr 12 09:45:20 chat rocketchat[43074]: [43074:0x46d3cd0]   123006 ms: Scavenge 670.8 (703.8) -> 664.6 (709.1) MB, 80.6 / 1.5 ms  (average mu = 0.988, current mu = 0.952) allocation failure
Apr 12 09:45:20 chat rocketchat[43074]: <--- JS stacktrace --->
Apr 12 09:45:20 chat rocketchat[43074]: FATAL ERROR: Zone Allocation failed - process out of memory
Apr 12 09:45:20 chat rocketchat[43074]:  1: 0xa3aaf0 node::Abort() [/usr/bin/node]
Apr 12 09:45:20 chat rocketchat[43074]:  2: 0x970199 node::FatalError(char const*, char const*) [/usr/bin/node]
Apr 12 09:45:20 chat rocketchat[43074]:  3: 0xbba45e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
Apr 12 09:45:20 chat rocketchat[43074]:  4: 0xbba7d7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
Apr 12 09:45:20 chat rocketchat[43074]:  5: 0x12606ae v8::internal::Zone::NewExpand(unsigned long) [/usr/bin/node]
Apr 12 09:45:20 chat rocketchat[43074]:  6: 0x1a955ed v8::internal::compiler::JSHeapBroker::JSHeapBroker(v8::internal::Isolate*, v8::internal::Zone*, bool, bool) [/usr/bin/node]
Apr 12 09:45:20 chat rocketchat[43074]:  7: 0x1ae9d71 v8::internal::compiler::PipelineData::PipelineData(v8::internal::compiler::ZoneStats*, v8::internal::Isolate*, v8::internal::OptimizedCompilationInfo*, v8::internal::compiler::PipelineStatistics*, bool) [/usr/bin/node]
Apr 12 09:45:20 chat rocketchat[43074]:  8: 0x1aedc9c v8::internal::compiler::PipelineCompilationJob::PipelineCompilationJob(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::BailoutId, v8::internal::JavaScriptFrame*) [/usr/bin/node]
Apr 12 09:45:20 chat rocketchat[43074]:  9: 0x1aedda8 v8::internal::compiler::Pipeline::NewCompilationJob(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, bool, v8::internal::BailoutId, v8::internal::JavaScriptFrame*) [/usr/bin/node]
Apr 12 09:45:20 chat rocketchat[43074]: 10: 0xc84f68  [/usr/bin/node]
Apr 12 09:45:20 chat rocketchat[43074]: 11: 0xc86bdd v8::internal::Compiler::CompileOptimized(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::ConcurrencyMode) [/usr/bin/node]
Apr 12 09:45:20 chat rocketchat[43074]: 12: 0x10866b1 v8::internal::Runtime_CompileOptimized_Concurrent(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
Apr 12 09:45:20 chat rocketchat[43074]: 13: 0x1448e19  [/usr/bin/node]
Apr 12 09:45:20 chat systemd[1]: rocketchat.service: Main process exited, code=killed, status=6/ABRT
```

**Comment by ankar84** [comment]
Guess you have a lot of users in your deployment.
My advise to you is to add more instances. 
And update mongo to at least to 4.2 with WiredTiger engine.

**Comment by hw-p** [comment]
got same problems with 300 Users

**Comment by DesSolo** [comment]
I have a similar problem with 800 users

**Comment by mr-dandy** [comment]
Same here, Rocket.Chat 4.5.7. Also tried on version 4.8.1.

**Comment by andys448** [comment]
Hi. try to change in /etc/sysctl.conf 

vm.max_map_count = 655300.

In your log node not using 12gb ram, after make changes you will get the errors on instances but not all :)

**Comment by Kot-o-pes** [comment]
same issue with 6.6.1 and 4k users
increasing --max-old-space-size didnt work, also scaling is not possible due to community restrictions. I dont use LDAP sync and this problem occurs randomly - cant seem to locate whats triggering it
here are my logs 
```

2024-02-29 07:25:16.328 | <--- JS stacktrace --->
-- | --

  | 2024-02-29 07:25:16.328 | [1:0x46376d0] 15906448 ms: Mark-sweep (reduce) 16305.7 (16403.1) -> 16304.6 (16404.1) MB, 6661.3 / 29.3 ms  (average mu = 0.104, current mu = 0.000) allocation failure scavenge might not succeed

  | 2024-02-29 07:25:16.328 | <--- Last few GCs --->


FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory  1: 0xa3ad50 node::Abort() [node]  2: 0x970199 node::FatalError(char const*, char const*) [node]  3: 0xbba90e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]  4: 0xbbac87 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]  5: 0xd76ea5  [node]  6: 0xd77a2f  [node]  7: 0xd8586b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]  8: 0xd8942c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]  9: 0xd57b0b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
--
```

vm.max_map_count = 524288 is set
