### ISSUE TITLE
Connection error?

### ISSUE THREAD

**Issue by mzch** [RocketChat/Rocket.Chat#25241]
### Description:

Blink `Connecting...` bar above the screen. Please see the screenshot.

### Steps to reproduce:

1. Start Rocket.Chat server.
2. Connect the server via browser or desktop client.

### Expected behavior:

Connect normally.

### Actual behavior:

Blink `Connecting...` bar above the screen.

### Server Setup Information:

- Version of Rocket.Chat Server: `4.6.2`
- Operating System: Debian GNU/Linux 11.3
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: `v14.19.1`
- MongoDB Version: `5.2.0`

### Client Setup Information

- Desktop App or Browser Version: Desktop `3.8.4`, Browser Chrome `100.0.4896.127`
- Operating System: macOS `11.3.1`

### ScreenShot

<img width="1591" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/164147273-53a2e6b3-11c2-4509-a882-80587168cec5.png">

### Relevant logs:
```
Apr 19 19:55:13 n13 systemd[1]: Started The Rocket.Chat server.
Apr 19 19:55:34 n13 rocketchat[30816]: {"level":40,"time":"2022-04-20T02:55:34.096Z","pid":30816,"hostname":"n13","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"}
Apr 19 19:55:34 n13 rocketchat[30816]: {"level":51,"time":"2022-04-20T02:55:34.464Z","pid":30816,"hostname":"n13","name":"Migrations","msg":"Not migrating, already at version 258"}
Apr 19 19:55:35 n13 rocketchat[30816]: Loaded the Apps Framework and loaded a total of 0 Apps!
Apr 19 19:55:36 n13 rocketchat[30816]: +-------------------------------------------------+
Apr 19 19:55:36 n13 rocketchat[30816]: |                  SERVER RUNNING                 |
Apr 19 19:55:36 n13 rocketchat[30816]: +-------------------------------------------------+
Apr 19 19:55:36 n13 rocketchat[30816]: |                                                 |
Apr 19 19:55:36 n13 rocketchat[30816]: |  Rocket.Chat Version: 4.6.2                     |
Apr 19 19:55:36 n13 rocketchat[30816]: |       NodeJS Version: 14.19.1 - x64             |
Apr 19 19:55:36 n13 rocketchat[30816]: |      MongoDB Version: 5.2.0                     |
Apr 19 19:55:36 n13 rocketchat[30816]: |       MongoDB Engine: unknown                   |
Apr 19 19:55:36 n13 rocketchat[30816]: |             Platform: linux                     |
Apr 19 19:55:36 n13 rocketchat[30816]: |         Process Port: 3000                      |
Apr 19 19:55:36 n13 rocketchat[30816]: |             Site URL: https://confabulari.com/  |
Apr 19 19:55:36 n13 rocketchat[30816]: |     ReplicaSet OpLog: Enabled                   |
Apr 19 19:55:36 n13 rocketchat[30816]: |          Commit Hash: e8cb666240                |
Apr 19 19:55:36 n13 rocketchat[30816]: |        Commit Branch: HEAD                      |
Apr 19 19:55:36 n13 rocketchat[30816]: |                                                 |
Apr 19 19:55:36 n13 rocketchat[30816]: +-------------------------------------------------+
Apr 19 19:55:36 n13 rocketchat[30816]: {"level":40,"time":"2022-04-20T02:55:36.832Z","pid":30816,"hostname":"n13","name":"SyncedCron","msg":"Failed to send usage report"}
Apr 19 19:55:37 n13 rocketchat[30816]: {"level":50,"time":"2022-04-20T02:55:37.255Z","pid":30816,"hostname":"n13","name":"System","err":{"type":"Error","message":"failed [401]{\"status\":401}","stack":"Error: failed [401]{\"status\":401}\n    at makeErrorByStatus (server/lib/http/call.ts:59:9)\n    at server/lib/http/call.ts:168:19\n    at /srv/Rocket.Chat/bundle-4.6.2/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","response":{"statusCode":401,"content":"{\"status\":401}","headers":{"access-control-allow-headers":"Content-Type, Authorization, Content-Length, Last-Event-ID, X-Requested-With","access-control-allow-methods":"GET, PUT, POST, DELETE, OPTIONS","access-control-allow-origin":"*","access-control-expose-headers":"Content-Type, Authorization, Cache-Control, Expires, Pragma, X-powered-by","cache-control":"private, no-cache, no-store, must-revalidate","connection":"close","content-length":"14","content-type":"application/json; charset=utf-8","date":"Wed, 20 Apr 2022 02:55:37 GMT","expires":"-1","pragma":"no-cache","vary":"Accept-Encoding","x-fleet-version":"-e0b0548","x-powered-by":"Rocket Fuel and Rocketeers"},"ok":false,"data":{"status":401}}},"msg":"failed [401]{\"status\":401}"}
Apr 19 19:57:37 n13 rocketchat[30816]: {"level":40,"time":"2022-04-20T02:57:37.768Z","pid":30816,"hostname":"n13","name":"Push","msg":"Error sending push to gateway (not authorized) {\"statusCode\":401,\"content\":\"{\\\"code\\\":121,\\\"error\\\":\\\"rocket.chat cloud registration required\\\",\\\"requestId\\\":\\\"3165f5f4-cc79-4b30-9083-3ec451bb2ad2\\\",\\\"status\\\":401}\",\"headers\":{\"access-control-allow-headers\":\"Content-Type, Authorization, Content-Length, X-Requested-With\",\"access-control-allow-methods\":\"GET, PUT, POST, DELETE, OPTIONS\",\"access-control-allow-origin\":\"*\",\"access-control-expose-headers\":\"Content-Type, Authorization, Cache-Control, Expires, Pragma, X-powered-by\",\"cache-control\":\"private, no-cache, no-store, must-revalidate\",\"connection\":\"close\",\"content-length\":\"126\",\"content-type\":\"application/json; charset=utf-8\",\"date\":\"Wed, 20 Apr 2022 02:57:37 GMT\",\"expires\":\"-1\",\"pragma\":\"no-cache\",\"vary\":\"Accept-Encoding\",\"x-powered-by\":\"Rocket Fuel and Rocketeers\"},\"ok\":false,\"data\":{\"code\":121,\"error\":\"rocket.chat cloud registration required\",\"requestId\":\"3165f5f4-cc79-4b30-9083-3ec451bb2ad2\",\"status\":401}}"}
Apr 19 20:12:02 n13 rocketchat[30816]: {"level":40,"time":"2022-04-20T03:12:02.694Z","pid":30816,"hostname":"n13","name":"SyncedCron","msg":"Failed to send usage report"}
```

**Comment by dudanogueira** [comment]
Hi! This seems more a firewall/infra config/setup than a bug to me.

Please, refer to our [Community Support Channel](https://open.rocket.chat/channel/support) or our [Forums](https://forums.rocket.chat/)

Closing for now. Thanks!

**Comment by dudanogueira** [comment]
Ps: I have seen some strange behavior like this one with WAF (Web Application Firewall) enabled.

**Comment by mzch** [comment]
Sorry, I posted this issue onto the forum. Thanks @dudanogueira !
