### ISSUE TITLE
Can not delete users in 4.6.1

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Rocket.Chat#25245]
### Description:

Can't delete user. Several "undefined" pop ups appearing.

### Steps to reproduce:

1. Go to admin, users, select an active user ( several conversations, owner of some channels ... )
2. Try to delete

### Expected behavior:

The user should be deleted 

### Actual behavior:

The user wont be deleted and log shows.
```
Exception in callback of async function: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.stat (fs.js:1083:10)
    at LocalStore.delete (packages/jalik:ufs-local/ufs-local.js:111:12)
    at Object.<anonymous> (packages/jalik:ufs/ufs-store.js:378:5)
    at packages/matb33:collection-hooks/remove.js:28:30
    at Array.forEach (<anonymous>)
    at packages/matb33:collection-hooks/remove.js:27:14
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (packages/matb33:collection-hooks/remove.js:26:22)
    at Object.collection.<computed> [as remove] (packages/matb33:collection-hooks/collection-hooks.js:93:21)
    at ns.Collection.remove (packages/mongo/collection.js:653:31)
    at ns.Collection.Mongo.Collection.<computed> [as remove] (packages/dispatch_run-as-user.js:325:19)
    at packages/jalik:ufs-local/ufs-local.js:114:36
    at runWithEnvironment (packages/meteor.js:1320:24) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Exception in callback of async function: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.stat (fs.js:1083:10)
    at LocalStore.delete (packages/jalik:ufs-local/ufs-local.js:111:12)
    at Object.<anonymous> (packages/jalik:ufs/ufs-store.js:378:5)
    at packages/matb33:collection-hooks/remove.js:28:30
    at Array.forEach (<anonymous>)
    at packages/matb33:collection-hooks/remove.js:27:14
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (packages/matb33:collection-hooks/remove.js:26:22)
    at Object.collection.<computed> [as remove] (packages/matb33:collection-hooks/collection-hooks.js:93:21)
    at ns.Collection.remove (packages/mongo/collection.js:653:31)
    at ns.Collection.Mongo.Collection.<computed> [as remove] (packages/dispatch_run-as-user.js:325:19)
    at packages/jalik:ufs-local/ufs-local.js:114:36
    at runWithEnvironment (packages/meteor.js:1320:24) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

### Server Setup Information:

- Version of Rocket.Chat Server:  4.6.1
- Deployment Method:docker
- Number of Running Instances:  3

### Client Setup Information

Web Firefox

**Comment by hailfinger** [comment]
This is a problem if someone exercises the EU GDPR right to be forgotten.

**Comment by dudanogueira** [comment]
Hi, can you check the browser developer tools and see if there is any outstanding log errors there? Specially on the return for the user deletion request.

We were facing a specific problem on this situation, where some of the error messages were not correctly showed to the user, like when deleting a user that is the only owner of a channel.

**Comment by jsalatiel** [comment]
The only strange thing I see in the logs is:
fuselage: 0.31.9 1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js:5:532649
TypeError: 'microphone' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
    e https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1493
    f https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    _withTemplateInstanceFunc https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    f https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    constructView https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    n https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    nonreactive https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1262
    _fireCallbacks https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    _withCurrentView https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    _fireCallbacks https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    _createView https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    _materializeView https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    t https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    _materializeDOM https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    _materializeDOM https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    _materializeView https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    nonreactive https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1262
    _materializeView https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    render https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    renderWithData https://my.domain.redacted/1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js?meteor_js_resource=true:1308
    l /client/views/room/components/BlazeTemplate.js:1
1cd5dca1e2c9f2d70e8c63a6b36daf8ea031d466.js:1493:418421

**Comment by dudanogueira** [comment]
The problem here is exactly replicating this issue.

Can you confirm this also happens on 4.6.3? We had a change on this same area in 4.6.2:

https://github.com/RocketChat/Rocket.Chat/releases/tag/4.6.2
