### ISSUE TITLE
Offline Emails

### ISSUE THREAD

**Issue by nikmaxott** [RocketChat/Rocket.Chat#25496]
---
name: Offline Email
about: Emails not received when Out of Office

---

### Description:

When an email is sent to an Email Inbox, and it is out of Business Hours / no online agents. Email does not go into Queue, or offline channel. 

### Steps to reproduce:

1. Change business hours so out of business
2. Send an email to Email Inbox.

### Expected behavior:

Either the email should go into the queue, as emails are less time sensitive, and more persistent than LiveChats. 
Or send details into Offline Channel given in Settings.

### Actual behavior:

Email not found on server at all.

{"level":50,"time":"2022-05-12T21:01:17.299Z","pid":634,"hostname":"mail.k-c13.org","name":"Livechat","msg":"Error receiving email","err":{"type":"errorClass","message":"Sorry, no online agents [no-agent-online]","stack":"Error: Sorry, no online agents [no-agent-online]<br>

Email is rejected as no online agents.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.6.3
- Operating System: Debian
- Deployment Method: tar
- NodeJS Version: v14.19.2
- MongoDB Version: 4.4.13 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: App / Website
- Operating System: Windows 10 / Linux Mint

### Relevant logs:

`{"level":50,"time":"2022-05-12T21:11:13.915Z","pid":634,"hostname":"---","name":"Livechat","msg":"Error receiving email","err":{"type":"errorClass","message":"Sorry, no online agents [no-agent-online]","stack":"Error: Sorry, no online agents [no-agent-online]<br>    at app/livechat/server/lib/QueueManager.js:51:10<br>    at /srv/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/srv/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/livechat/server/lib/Livechat.js:194:8<br>    at /srv/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/srv/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/livechat/server/lib/Livechat.js:219:9<br>    at /srv/rocketchat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","isClientSafe":true,"error":"no-agent-online","reason":"Sorry, no online agents","errorType":"Meteor.Error"},"msg":"Sorry, no online agents [no-agent-online]"} `

**Comment by nikmaxott** [comment]
This can be solved by Accept with No Online Agents, but then LiveChat is always on, which is not desired as out of office livechat will not be answered. 

Only way I have thought around this currently, is with differing Business Hours for the Email department, but this is a paid feature.

**Comment by nikmaxott** [comment]
Ideally I would like email inboxes to go into the standard queue regardless of Business Hours as they are persistent in nature. I assume something like this already happens with Facebook, WhatsApp, etc.

**Comment by cortopy** [comment]
I'm also experiencing this issue. I don't have any business hours set, but if no agent is online, then emails received are completely ignored.

The whole purpose of sending an email is that someone will reply whenever they can, so there shouldn't be a need for agents to be online to receive emails
