### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by max133** [RocketChat/Rocket.Chat#2554]
Today i installed the current version on xubuntu15.10. After starting the server i get this error message

```
/var/www/Rocket.Chat$ node main.js
Updating process.env.MAIL_URL
ufs: store created at
ufs: store created at
{"line":"114","file":"migrations.js","message":"Migrations: Not migrating, already at version 33","time":{"$date":1458332984758},"level":"info"}
Updating process.env.MAIL_URL
ufs: temp directory created at /tmp/ufs
configuring push
Using GridFS for Avatar storage
➔ System ➔ startup
➔ +---------------------------------------------------------+
➔ |                      SERVER RUNNING                     |
➔ +---------------------------------------------------------+
➔ |                                                         |
➔ |       Version: 0.22.0                                   |
➔ |  Process Port: 3000                                     |
➔ |      Site URL: http://xxxxxxxxxxx:3000/  |
➔ |                                                         |
➔ +---------------------------------------------------------+
Exception in defer callback: Error: socket hang up
    at Object.Future.wait (/var/www/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)
    at Object.call (packages/meteor/helpers.js:119:1)
    at Object.HTTP.post (packages/http/httpcall_common.js:61:1)
    at generateStatistics (server/startup/cron.coffee:9:8)
    at server/startup/cron.coffee:15:3
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    - - - - -
    at SecurePair.error (tls.js:1011:23)
    at EncryptedStream.CryptoStream._done (tls.js:703:22)
    at CleartextStream.read [as _read] (tls.js:499:24)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.onCryptoStreamFinish (tls.js:304:47)
    at EncryptedStream.g (events.js:180:16)
    at EncryptedStream.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:360:12)
    at endWritable (_stream_writable.js:367:3)
    at EncryptedStream.Writable.end (_stream_writable.js:345:5)

```
Whats wrong? How can I fix it?

**Comment by max133** [comment]
a restart solved the problem

**Comment by Sing-Li** [comment]
Highly recommend that you switch to an LTS version (as per general industry best practices) if you are going into production and not just experimenting.

**Comment by dukemnm** [comment]
I have the same issue, but mine comes back every time someone is mentioned in chat, even after restart
Rocket.Chat version 0.34.0
