### ISSUE TITLE
v4.7.2 does not start

### ISSUE THREAD

**Issue by ali-alhaidary** [RocketChat/Rocket.Chat#25588]
### Description:

v4.7.2 does not start

### Steps to reproduce:

sudo systemctl stop rocketchat
sudo rm -r /opt/Rocket.Chat.old
sudo mv /opt/Rocket.Chat /opt/Rocket.Chat.old
sudo n install 14.18.3
curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
tar -xzf /tmp/rocket.chat.tgz -C /tmp
cd /tmp/bundle/programs/server
sudo npm install @mapbox/node-pre-gyp --save
sudo npm install
sudo mv /tmp/bundle /opt/Rocket.Chat
sudo chown -R rocketchat:rocketchat /opt/Rocket.Chat
sudo systemctl start rocketchat

### Expected behavior:

service stars

### Actual behavior:

● rocketchat.service - The mersaal server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2022-05-20 20:15:45 UTC; 2s ago
  Process: 30150 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 30150 (code=exited, status=1/FAILURE)

May 20 20:15:45 mersaal rocketchat[30150]:     at Module.load (internal/modules/cjs/loader.js:950:32)
May 20 20:15:45 mersaal rocketchat[30150]:     at Module.Mp.load (/opt/Rocket.Chat/programs/server/runtime.js:46:33)
May 20 20:15:45 mersaal rocketchat[30150]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
May 20 20:15:45 mersaal rocketchat[30150]:     at Module.require (internal/modules/cjs/loader.js:974:19)
May 20 20:15:45 mersaal rocketchat[30150]:     at require (internal/modules/cjs/helpers.js:93:18)
May 20 20:15:45 mersaal rocketchat[30150]:     at Object.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/forked-matrix-sdk-crypto-no
May 20 20:15:45 mersaal rocketchat[30150]:   code: 'ERR_DLOPEN_FAILED'
May 20 20:15:45 mersaal rocketchat[30150]: }
May 20 20:15:45 mersaal systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
May 20 20:15:45 mersaal systemd[1]: rocketchat.service: Failed with result 'exit-code'.

**Comment by ali-alhaidary** [comment]
while installing:
npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> fibers@5.0.1 install /tmp/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-83-glibc` exists; testing
Binary is fine; exiting
npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd meteor-dev-bundle@ node npm-rebuild.js (wd=/tmp/bundle/programs/server)

**Comment by ali-alhaidary** [comment]
Service started after installing node v14.0.0
