### ISSUE TITLE
Can't reconnect to cloud service

### ISSUE THREAD

**Issue by apnagaev** [RocketChat/Rocket.Chat#25675]
Hi!
My rocketchat instance can't connect to cloud services. When I click to Administration-Connectivity Services-Sync I have error {"level":50,"time":"2022-05-30T08:46:27.553Z","pid":1,"hostname":"65efe3bbc39d","name":"System","err":{"type":"FetchError","message":"maximum redirect reached at: https://cloud.rocket.chat/","stack":"FetchError: maximum redirect reached at: https://cloud.rocket.chat/\n    at ClientRequest.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/fetch/node_modules/node-fetch/lib/index.js:1487:15)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)\n    at Socket.socketOnData (_http_client.js:515:22)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at Socket.Readable.read (internal/streams/readable.js:504:10)\n    at Socket.read (net.js:638:39)\n    at flow (internal/streams/readable.js:987:34)\n    at resume_ (internal/streams/readable.js:968:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","name":"FetchError"},"msg":"maximum redirect reached at: https://cloud.rocket.chat/"}
I try re-registr my self-hosted instance, but I have this error again. And I cant re-register it online, it's work only by offline registration.
How I can restore sync with cloud services? I can't use push, marketspace and statistic.
Thsnks in advance!

- Version of Rocket.Chat Server: 4.7.2
- Operating System: Ubuntu 20.04
- Deployment Method: docker
- Number of Running Instances: 1-3
- DB Replicaset Oplog: Enable
- MongoDB Version: 5.0.6

**Comment by apnagaev** [comment]
Rocket.Chat do revers http-get, for true work you must make true docker configuration. You should not use ROCKETCHAT_URL environment.
