### ISSUE TITLE
Integration with Webhook restarting instance RC

### ISSUE THREAD

**Issue by valessiobrito** [RocketChat/Rocket.Chat#2569]
Your Rocket.Chat version: 0.22.0 

I set up integration with Zapier and each POST via webhook the instance is restarted.

Here the error log:

````
ERROR: Push server could not find keyData
Error: ENOENT, open 'cert.pem'

/opt/Rocket.Chat/programs/server/packages/meteor.js:974
    throw new Error("Meteor code must always run within a Fiber. " +          
          ^
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at Object.Meteor.isRestricted (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:137:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:268:1)
    at Object.UserPresence.removeConnectionsByInstanceId (packages/konecty_user-presence/packages/konecty_user-presence.js:88:1)
    at process.<anonymous> (packages/konecty_user-presence/packages/konecty_user-presence.js:223:1)
    at process.emit (events.js:117:20)
    at process.exit (node.js:740:17)
    at process.catchException (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:52:15)
    at process.g (events.js:180:16)
ERROR: Push server could not find certData
````

**Comment by engelgabriel** [comment]
Seems to be something wrong with your push certificate. But it should not trigger a restart.

**Comment by valessiobrito** [comment]
What you see, it is that every time you restart, it did not generate information about page metadata. 
Only one time and not restarted generated the metadata.   See:

![rocketchat_-_2016-03-21_18 53 03](https://cloud.githubusercontent.com/assets/310049/13935483/506e892c-ef96-11e5-90e2-ff0684f0303b.png)

**Comment by rodrigok** [comment]
@valessiobrito your server is restarting by a problem in your Push certificates, since when the integration create a new message the server, probably, is trying to send that message via Push Notification and then crashing.

You should have the same behavior if you go the the "push" section in your admin page and hit the button to test push notifications.

Can you do that? Or we can talk better via chat https://demo.rocket.chat/direct/rodrigo.nascimento

**Comment by valessiobrito** [comment]
@rodrigok this type of Push works normal. I did as directed the application did not restart. I got the push usually on the smartphone.
Believe may be related to Push when posted by the BOT, I will do new tests and maintain documented in this Issue.
How to update the certificate? Any tips? I don't remember any generated certificate to set my instance.

**Comment by rodrigok** [comment]
@valessiobrito Are you using custom certificates in your Push settings? Or are you using our gateway?

**Comment by valessiobrito** [comment]
Don't use Push settings for Apple; This blank. Can be it?
Use own configuration for Android.

**Comment by rodrigok** [comment]
@valessiobrito please reopen this issue if the problem persists
