### ISSUE TITLE
Exeption: Cannot read property '_syncSendMail' when no mail server is defined

### ISSUE THREAD

**Issue by maudrid** [RocketChat/Rocket.Chat#25706]
### Description:

After upgrading to rocket chat 4.7.0 we are getting these errors in our application that is integrated using the rocket chat API so this is a regression.

This issue seems to be related to this:
https://github.com/meteor/meteor/issues/11709

### Steps to reproduce:

1. Make sure there is on mail server defined in the configuration.
2. Update the email address of a user.

### Expected behavior:

No attempt to send an email should be made and no error message should be displayed.

### Actual behavior:

The following error is reported:
```
Exception in defer callback: TypeError: Cannot read property '_syncSendMail' of null
    at smtpSend (packages/email/email.js:154:13)
    at Object.Email.send (packages/email/email.js:233:5)
    at app/mailer/server/api.ts:176:27
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/meteor.js:555:25
    at runWithEnvironment (packages/meteor.js:1320:24)
```

### Server Setup Information:

- Version of Rocket.Chat Server: 4.7.0
- Operating System: Docker
- Deployment Method: rocketchat/rocket.chat:4.7.0
- Number of Running Instances: 1
- DB Replicaset Oplog: NA
- NodeJS Version: NA
- MongoDB Version: 5

### Client Setup Information

- Desktop App or Browser Version: Browser Chrome 101
- Operating System: Linux

### Relevant logs:

Exception in defer callback: TypeError: Cannot read property '_syncSendMail' of null
    at smtpSend (packages/email/email.js:154:13)
    at Object.Email.send (packages/email/email.js:233:5)
    at app/mailer/server/api.ts:176:27
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/meteor.js:555:25
    at runWithEnvironment (packages/meteor.js:1320:24)

**Comment by danielfamiyeh** [comment]
@maudrid - Did you manage to find a solution?
