### ISSUE TITLE
im looking for a guide to upgrade from 0.72.3 to latest 

### ISSUE THREAD

**Issue by heroes1412** [RocketChat/Rocket.Chat#25801]
Hi all,
we have been using rocketchat since version 0.72.3, long time ago, everything worked very smoothly. But now we want to upgrade to latest version [4.6.4].
we not use container. separate rocketchat server vs mongodb v3.6 (a replica set)
and i have tried to install other rocketchat server with: Node: 14.18.3 + NPM: 6.14.15 + rocketchat src 4.6.4, everything seem fine:

` [root@localhost server]# npm install
npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd meteor-dev-bundle@ node npm-rebuild.js (wd=/opt/Rocket.Chat/programs/server)
audited 157 packages in 3.742s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[root@localhost server]# pwd
/opt/Rocket.Chat/programs/server
`
but then, i got errors:

> [root@localhost Rocket.Chat]# /usr/local/bin/node /opt/Rocket.Chat/main.js
Change Stream is available for your installation, give admin permissions to your database user to use this improved version.
Error creating index: room -> { default: 1 } { sparse: true } MongoError: Index with name: default_1 already exists with different options
    at MessageStream.messageHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
    at MessageStream.emit (events.js:400:28)
    at MessageStream.emit (domain.js:475:12)
    at processIncomingData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:731:22)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1654679084 },
  ok: 0,
  code: 85,
  codeName: 'IndexOptionsConflict',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1654679084 },
    signature: { hash: [Binary], keyId: [Long] }
  }
}
Error creating index: room -> { 'tokenpass.tokens.token': 1 } { sparse: true } MongoError: Index with name: tokenpass.tokens.token_1 already exists with different options
    at MessageStream.messageHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
    at MessageStream.emit (events.js:400:28)
    at MessageStream.emit (domain.js:475:12)
    at processIncomingData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:731:22)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1654679084 },
  ok: 0,
  code: 85,
  codeName: 'IndexOptionsConflict',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1654679084 },
    signature: { hash: [Binary], keyId: [Long] }
  }
}
Error creating indexes for avatars MongoError: Index with name: name_1 already exists with different options
    at MessageStream.messageHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
    at MessageStream.emit (events.js:400:28)
    at MessageStream.emit (domain.js:475:12)
    at processIncomingData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:731:22)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1654679084 },
  ok: 0,
  code: 85,
  codeName: 'IndexOptionsConflict',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1654679084 },
    signature: { hash: [Binary], keyId: [Long] }
  }
}
Error creating indexes for integration_history MongoError: Index with name: _updatedAt_1 already exists with different options
    at MessageStream.messageHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
    at MessageStream.emit (events.js:400:28)
    at MessageStream.emit (domain.js:475:12)
    at processIncomingData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:731:22)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1654679084 },
  ok: 0,
  code: 85,
  codeName: 'IndexOptionsConflict',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1654679084 },
    signature: { hash: [Binary], keyId: [Long] }
  }
}
Segmentation fault

**Comment by heroes1412** [comment]
update: i also try to run rocketserver in container with the cmd, and get same above error

docker run --name rocketchat -p 8080:3000 --env PORT=3000 --env ROOT_URL=http://localhost --env MONGO_URL="mongodb://<user>:<pass>@<mongo IP>:27017/rocketchat?replSetName=rs1" --env MONGO_OPLOG_URL="mongodb://<user>:<pass>@<mongo IP>:27017/local?authSource=admin&replSetName=rs1" --add-host <mongo hostname>:<mongo ip> -d rocket.chat

**Comment by dudanogueira** [comment]
Hi! Please, refer to our [Community Forums](https://forums.rocket.chat/) or [Support Channel on Open Server](https://open.rocket.chat/channel/support)

I will close this issue as this is not a bug.

Please, also refer to [Asking for Help](https://docs.rocket.chat/getting-support/asking-for-help) on how to properly ask for help.

My suggestion:
- Deploy a docker staging using the same old version you have
- Backup data on old production
- import into this new staging, with the same old version
- Start migrating and testing.

Hope I have helped :)
