### ISSUE TITLE
Setting ECDH_Enabled=true Causes Several Persistent Errors

### ISSUE THREAD

**Issue by kit-repo-depot** [RocketChat/Rocket.Chat#26142]
### Description:

In rocket.chat 4.8.1 installed by snap on Ubuntu 22.04, if you enable "Enable second layer encryption for data transport" (ECDH_Enabled) after restarting the service several issues occur and render the page unresponsive.

### Steps to reproduce:

1. install rocket.chat from snap (sudo snap install rocketchat-server)
2. echo "OVERWRITE_SETTING_ECDH_Enabled=true" > overwrite-ecdh.env 
3. sudo mv overwrite-ecdh.env /var/snap/rocketchat-server/common/
4. sudo snap restart rocketchat-server

it also works by setting the setting in the admin portal

1. sudo snap install rocketchat-server
2. set up the server as normal (I didn't register during my tests)
3. Enable ECDH (Administration -> Settings -> General -> Enable second layer encryption for data transport)
4. Save the settings 
5. Refresh the page

### Expected behavior:

I expected some kind of key exchange to be enabled for encryption in transport

### Actual behavior:

It causes the page to hang on "Connecting"

<img width="1226" alt="Desktop Safari screenshot showing a frozen web page" src="https://user-images.githubusercontent.com/51519580/177435445-47e9967c-c31b-42fa-a006-58743abdcbbf.png">

<img width="350" alt="Mobile Safari screenshot showing a frozen web page with a rectangular input UI element and license text" src="https://user-images.githubusercontent.com/51519580/177437308-086c8757-df7b-4722-ba6a-621db62a1042.jpeg">

### Server Setup Information:

- Version of Rocket.Chat Server: 4.8.1
- Operating System: Ubuntu 22.04
- Deployment Method: snap
- Number of Running Instances: 1
(I can't figure out how to get these versions from snap, if you tell me I can update the issue)
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Safari Version 15.5 and Microsoft Edge Version 103.0.1264.44, Safari for iOS 15.5
- Operating System: macOS Monterey 12.4 and iOS 15.5

### Relevant logs:

Server:

Due to the nature of the issue I can't access the Administrator portal to get to the View Logs screen. I've attached the truncated logs from systemctl status

`rocketchat-server.rocketchat-server[735218]: |                                              |
rocketchat-server.rocketchat-server[735218]: +----------------------------------------------+
rocketchat-server.rocketchat-server[735218]: Exception in defer callback: TypeError: Cannot read property '_syncSendMail' of null
rocketchat-server.rocketchat-server[735218]:     at smtpSend (packages/email/email.js:154:13)
rocketchat-server.rocketchat-server[735218]:     at Object.Email.send (packages/email/email.js:233:5)
rocketchat-server.rocketchat-server[735218]:     at AccountsServer.Accounts.sendEnrollmentEmail (packages/accounts-password/password_server.js:534:9)
rocketchat-server.rocketchat-server[735218]:     at app/lib/server/functions/setUsername.ts:47:14
rocketchat-server.rocketchat-server[735218]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
rocketchat-server.rocketchat-server[735218]:     at packages/meteor.js:555:25
rocketchat-server.rocketchat-server[735218]:     at runWithEnvironment (packages/meteor.js:1320:24)`

`mongod.27017[735057]: 2022-07-05T23:54:47.494+0000 I  CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
mongod.27017[735057]: 2022-07-05T23:54:47.494+0000 I  STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with provided UUID: 369df777-2734-47ad-95da-97a4c3b59963 and options: { uuid: UU>
mongod.27017[735057]: 2022-07-05T23:54:47.505+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index _id_ on ns config.system.sessions
mongod.27017[735057]: 2022-07-05T23:54:47.516+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: starting on config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "confi>
mongod.27017[735057]: 2022-07-05T23:54:47.516+0000 I  INDEX    [LogicalSessionCacheRefresh] build may temporarily use up to 200 megabytes of RAM
mongod.27017[735057]: 2022-07-05T23:54:47.516+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: collection scan done. scanned 0 total records in 0 seconds
mongod.27017[735057]: 2022-07-05T23:54:47.518+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: inserted 0 keys from external sorter into index in 0 seconds
mongod.27017[735057]: 2022-07-05T23:54:47.519+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index lsidTTLIndex on ns config.system.sessions
mongod.27017[735057]: 2022-07-05T23:54:47.995+0000 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Dropping all pooled connections to localhost:27017 due to ShutdownInProgress: Pool for localhost:27017 has expired.
mongod.27017[735057]: 2022-07-05T23:54:47.995+0000 I  NETWORK  [conn1] end connection 127.0.0.1:32802 (29 connections now open)`

Client:

`[Error] The Notification permission may only be requested in a secure context.
	getDesktopPermission (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1542:31810)
	action (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1544:418978)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:10059)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:6803)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1311:4193)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:6650)
	_compute (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1311:2330)
	_recompute (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1311:2493)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1311:3506)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1311:3122)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:7044)
	a (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:2825)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:1427)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:2886)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	o (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14188)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:1427)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:3005)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14775)
	i (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1441:14109)
[Error] Refused to connect to data:application/octet-stream;base64,AGFzbQEAAAABvgImYAJ/fwBgAAF/YAN/f38Bf2ACf38Bf2ADf39/AGABfwBgAX8Bf2AEf39/fwF/YAt/f39/f39/f39/fwF/YAV/f39/fwF/YAZ/f39/f38Bf2AHf39/f39/fwF/YAN/f34Bf2AEf35/fwF/YAZ/f39+f38Bf2AAAGAGf39+f39/AX9gBH9/fn8Bf2AGf39+f35/AX9gDH9/f39/f39/f39/fwF/YAh/f39/f39/fwF/YAR/f39/AGADf39+AGAFf39+f38AYAh/f35/f35/fwF/YAl/f39/fn9+f38Bf2ACfn8BfmACf34AYAZ/f35/f38AYAR/fn9/AGAHf39/fn9/fwF/YAp/f39/f39/f39/AX9gAn5+AX5gAX8BfmAEf39/fgBgBX9/fn5/AX9gBX9/fn9/AX9gBX9/f35/AX8CHwUBYQFhABUBYQFiAAIBYQFjAAYBYQFkAA...EQqWVVJAaZ1iogcVeFNQ70uNG7MnCgahDI0NK4FsGkGVOrQVEIbDcemeuO30x3SCeoSJvhtbywNGNaycWzDBw5y4pB40qq2E5z42N3T8qcW6O4stbzby5o/LLvXe6Cj3RgLxdDb2OleHKr8KEUeMiE7DlkGggCx4woHmMj+v++kOm9gt7rbFCkFXnGsvej+b4rU3Lj8nhxxpxhJurOPifKB8LAIce4htEe6+DN1n3a6njRbu5/T331um8Xcqpn8AammMiixX1jCq4N+b4EmD8RG0ccEzULcRuEfQQj9XfbKJMkx0B7q8oyvL7JFQq+njxMDRCcxGcdQ7ZCPsu+1MVMKn5l/Jwpf1ns+tY6q2/LXxdYR0qMGURsgABB4JACCyFTaWdFZDI1NTE5IG5vIEVkMjU1MTkgY29sbGlzaW9ucwEAQbCRAgs1MI5QAAEAAAACAAAAAwAAAAQAAAAFAAAABgAAAAcAAAAIAAAACQAAAAoAAAALAAAADAAAAA0= because it does not appear in the connect-src directive of the Content Security Policy.
[Error] Unhandled Promise Rejection: Error: Cannot find module 'stream'
	(anonymous function) (246a6d315318780570aef42cb9a7bc63dcb389ee.js:1544:104846)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise`

**Comment by fc757** [comment]
Thank you. I've not been able to upgrade past 4.6.4 because web clients could not connect like you are seeing. Fortunately, I was able to disable `Enable second layer encryption for data transport' in my 4.6.4 install, restart it and upgraded to 4.8.1 and have everything working.

**Comment by KeysBytes** [comment]
Dose anyone have any solution? Just break my server and didn't find any useful information. But I can surly confirm ECDH is the problem. please help :( thank you

**Comment by KevLehman** [comment]
This feature was removed.
