### ISSUE TITLE
Failed upgrade to v4.7+

### ISSUE THREAD

**Issue by atshim** [RocketChat/Rocket.Chat#26143]
### Description:

This is similar to https://github.com/RocketChat/Rocket.Chat/issues/25396
The error "/lib64/libc.so.6: version `GLIBC_2.25' not found" occurs when I execute "npm install" with v4.7+ on RHEL7.
The issue says the problem was fixed on v4.7.2 so I tried it, but still the same problem occurs.
The latest v4.8.1 doesn't work either.

### Steps to reproduce:

```
systemctl stop rocketchat
wget https://releases.rocket.chat/4.7.2/download
mv download rocket.chat-4.7.2.tgz
mv /opt/Rocket.Chat /opt/Rocket.Chat.bak
tar zxf ~/rocket.chat-4.7.2.tgz
mv bundle /opt/Rocket.Chat
chown -R rocketchat:rocketchat /opt/Rocket.Chat
su -s /bin/bash rocketchat -
cd /opt/Rocket.Chat/programs/server/
npm install
```

### Expected behavior:

npm install is completed successfully without any errors

### Actual behavior:

The error occurs and npm install fails

### Server Setup Information:

- Version of Rocket.Chat Server: 4.7+
- Operating System: RHEL7
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: 14.18.2 from RHSCL
- MongoDB Version: 4.2.21

### Relevant logs:

The error on npm install:

```
> @rocket.chat/forked-matrix-sdk-crypto-nodejs@0.1.0-beta.12 postinstall /opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/forked-matrix-sdk-crypto-nodejs
> node check-exists.js

/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/forked-matrix-sdk-crypto-nodejs/check-exists.js:15
        throw e;
        ^

Error: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/forked-matrix-sdk-crypto-nodejs/lib/index.linux-x64-gnu.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/forked-matrix-sdk-crypto-nodejs/lib/napi-module.js:145:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rocket.chat/forked-matrix-sdk-crypto-nodejs@0.1.0-beta.12 postinstall: `node check-exists.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @rocket.chat/forked-matrix-sdk-crypto-nodejs@0.1.0-beta.12 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rocketchat/.npm/_logs/2022-07-06T02_19_10_606Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rocketchat/.npm/_logs/2022-07-06T02_19_10_655Z-debug.log
```

**Comment by jamesshaw1987** [comment]
Same issue on Ubuntu 18.04, except GLIBC_2.28 is the version that is required, with 2.27 being the version installed.

**Comment by TheWrongGuy** [comment]
Bump. The issue persists for 4.8.2 on CentOS7. I thought maybe they dropped the support for CentOS7, since it asks for 2.25 and the latest in CentOS7 available is 2.17, but if it is asking for 2.28 in some cases I'm confused.

**Comment by Cob0ld** [comment]
bump same error here for ubuntu 18.04

**Comment by TheWrongGuy** [comment]
Still....trying to npm install version 5.0.1. @sampaiodiego Can you maybe help with this or give an update? We can't upgrade since version 4.6.4...

**Comment by sampaiodiego** [comment]
hey @TheWrongGuy , I brought this issue to the team, we'll see what we can do..

meanwhile is Docker an option? you can easily spin up a Docker container without having to manage any rocket.chat dependency

**Comment by TheWrongGuy** [comment]
Thansk!

**Comment by FractalizeR** [comment]
Same problem here with Ubuntu 18.04.

**Comment by TheWrongGuy** [comment]
Does the issue persists with the latest versions? Didn't try 5.0.4 as of now.

**Comment by TheWrongGuy** [comment]
The issue persists on 5.1.0.... Is there an offical information on this? Was the support for older OSes dropped? Remember CentOS7 and Ubuntu 18.04 are still in LTS Support!!!

**Comment by HighwayStar** [comment]
I ended up updating 18.04 host to 20.04 and after this was able to update to rocket chat 5.1.1 with no issue.

**Comment by TheWrongGuy** [comment]
I think this won't be fixed anymore. Since I was over 15 Version behind now, I migrated the whole system from CentOS7 to Ubuntu Server 20.04 LTS (Don't use 22.04 LTS MongoDB won't work there). Why the change to Ubuntu? "do-release-upgrade" for the future upgrades to later LTS releases. The new RedHad distros like AlmaLinux and Rocky offer upgrade tools too now, but I was annoyed by the upgrade wall between CentOS7 and 8 basically requiring a full new setup.

Now on 20.04. LTS I first migrated to 4.6.4 and then incrementally upgraded through to 5.2.0. Running fine now. I recommend this to all the others here. Don't wait any longer.

**Comment by JoshMcCullough** [comment]
This is unfortunate because we need to upgrade from 4.6 but cannot because nothing 4.7+ works on RHEL7. This is actually really bad, IMO. Anyone using CentOS 7 / RHEL 7 / Ubuntu <20, and many other distros will never be able to upgrade.

Any plans to release a patch for 4.x since this breaks 4.x entirely for a lot of people?
