### ISSUE TITLE
RocketChat 5.0 can't connect to mongo

### ISSUE THREAD

**Issue by apnagaev** [RocketChat/Rocket.Chat#26348]
Hi! I update rocketchat in docker from 4.8.2 to 5.0.0. I have external mongoDB-server.
My docker run command:
```
docker run --name rocketchat \
--restart unless-stopped \
--dns=my_dns1 --dns=my_dns2 \
-p 82:3000 \
--env MONGO_URL=mongodb://mongoDB_IP/rc \
--env MONGO_OPLOG_URL=mongodb://mongoDB_IP:27017/local \
--env ROOT_URL=https://chat.company.ru \
-d rocketchat/rocket.chat:latest
```

It is not work with error:
```
MongoServerSelectionError: getaddrinfo ENOTFOUND rcmongo
    at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(1) {
      'rcmongo:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'rcmongo', port: 27017 },
        address: 'rcmongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 171300075,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND rcmongo
            at connectionFailureError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:381:20)
            at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:301:22)
            at Object.onceWrapper (events.js:520:26)
            at Socket.emit (events.js:400:28)
            at emitErrorNT (internal/streams/destroy.js:106:8)
            at emitErrorCloseNT (internal/streams/destroy.js:74:3)
            at processTicksAndRejections (internal/process/task_queues.js:82:21)
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'rs0',
    maxSetVersion: 1,
    maxElectionId: ObjectId {
      [Symbol(id)]: Buffer(12) [Uint8Array] [
        127, 255, 255, 255, 0,
          0,   0,   0,   0, 0,
          0,  49
      ]
    },
    commonWireVersion: 13,
    logicalSessionTimeoutMinutes: undefined
  }
}
```

In my config I use 
`--env MONGO_URL=mongodb://mongoDB_IP/rc`
```
and in error it:
    servers: Map(1) {
      'rcmongo:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'rcmongo', port: 27017 },
        address: 'rcmongo:27017',
```

MONGO_URL variable was be ignored. If I use ocketchat/rocket.chat:4.8.2 version - all works true. How I can fix it?
Thanks in advance!

**Comment by apnagaev** [comment]
Sorry, I find documentations
`If you're using MongoDB in a Docker container, you might need to add directConnection=true to MONGO_URL and MONGO_OPLOG_URL environment variables. i.e.: MONGO_URL=mongodb://mongo/rocketchat?replicaSet=rs0&directConnection=true`
https://github.com/RocketChat/Rocket.Chat/releases/tag/5.0.0
It's works
