### ISSUE TITLE
LDAP email data sync: Error creating user { [Error: Match error: Expected string, got object in field email]

### ISSUE THREAD

**Issue by ekajmiller** [RocketChat/Rocket.Chat#2642]
Your Rocket.Chat version: 0.23

While using LDAP authentication, when a user logs in that has multiple email addresses in the LDAP field mapped to 'email' login will fail, more specifically syncing the email data will fail. I have sync data on, but I haven't checked to see if this fails with it off. My apologies.

Here's the stack trace I get from the server (pardon me blacking out info with **):

```
LDAP \u2794 Auth.info Authenticating uid=**,c=**,ou=**,o=**.com
LDAP \u2794 Auth.info Authenticated uid=**,c=**,ou=**,o=**.com
LDAP \u2794 Connection.info Disconecting
LDAPHandler \u2794 info Querying user
LDAPHandler \u2794 debug userQuery { 'services.ldap.id': '**' }
LDAPHandler \u2794 debug userQuery { username: '**' }
LDAPHandler \u2794 info User does not exists, creating **
LDAPHandler \u2794 debug New user data { username: '**',
  email: [ 'useremail1@**.com', 'useremail2@**.com' ] }
loginHandler.js:151 LDAPHandler \u2794 error Error creating user { [Error: Match error: Expected string, got object in field email]
  message: 'Match error: Expected string, got object in field email',
  path: 'email',
  sanitizedError: 
   { [Error: Match failed [400]]
     error: 400,
     reason: 'Match failed',
     details: undefined,
     message: 'Match failed [400]',
     errorType: 'Meteor.Error' },
  errorType: 'Match.Error' }
Exception while invoking method 'login' Error: Match error: Expected string, got object in field email
    at check (packages/check/match.js:33:1)
    at createUser (password_server.js:954:3)
    at AccountsServer.Accounts.createUser (password_server.js:1049:10)
    at [object Object].Meteor.startup.RocketChat.settings.addGroup.enableQuery._id (server/loginHandler.js:149:29)
    at accounts_server.js:462:32
    at tryLoginMethod (accounts_server.js:239:14)
    at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
    at [object Object].methods.login (accounts_server.js:522:27)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
Sanitized and reported to the client as: Match failed [400]
```

The offending [code](https://github.com/RocketChat/Rocket.Chat/blame/5eee69ad6301fe379f63493035aaff2115f6069a/packages/rocketchat-ldap/server/loginHandler.js#L133):

```
    if (userData && userData.emails) {
        userObject.email = userData.emails[0].address;
    } else if (ldapUser.object.mail && ldapUser.object.mail.indexOf('@') > -1) {
```

userObject.email is set to userData.emails[0].address which is read from LDAP and could be an ARRAY of strings rather than just a string.

A possible solution could be to just grab the first email in the list as the email. However this may not match with the email used for user login. Perhaps if email is used for user login it should just use that instead of the ldap field.

SIDENOTE: I've also noticed when the LDAP field for name has multiple entries it concats them all together. I mention this here because perhaps this is a systemic design issue when syncing data for LDAP entries containing multiple values.

**Comment by B2RN** [comment]
Any progress on this? Encountering the same issue since we have multiple "mail" attributes for some users.

Looks like that's bad practice in general, and mailLocalAddress should be used for any secondary e-mail addresses. But, since that'll happen At Some Point, figured I'd check here as well.

Cheers,
Juraj

**Comment by Flauschbaellchen** [comment]
I got the same error with version 0.42.0.
Even if it is bad practice to have more than one "mail"-attribute, there should be a more gracefully way to handle such cases as the schema permits such usage.
Currently, it is not possible to sync or create-on-login such accounts.

**Comment by ekajmiller** [comment]
FWIW, I use the following hacked patch to get around it (.bk is the original file from my version of RocketChat, 0.23). Be warned, this is definitely a hack since I did not re-package with meteor's tools nor does it address the true issue. It just works around the exceptions for my purposes. This hack just assumes you want to use the first email address in the array.

```javascript
% diff -u ./programs/server/packages/rocketchat_ldap.js.bk ./programs/server/packages/rocketchat_ldap.js
--- ./programs/server/packages/rocketchat_ldap.js.bk	2016-03-24 16:06:24.910948747 -0500
+++ ./programs/server/packages/rocketchat_ldap.js	2016-03-24 17:06:02.610900814 -0500
@@ -822,7 +822,11 @@
 	var userData = getDataToSyncUserData(ldapUser, {});                                                                   // 130
                                                                                                                        //
 	if (userData && userData.emails) {                                                                                    // 132
-		userObject.email = userData.emails[0].address;                                                                       // 133
+		if (typeof userData.emails[0].address == "string") {
+			userObject.email = userData.emails[0].address;                                                                       // 133
+		} else { // Assume it's an array of strings
+			userObject.email = userData.emails[0].address[0];                                                                       // 133
+		}
 	} else if (ldapUser.object.mail && ldapUser.object.mail.indexOf('@') > -1) {                                          //
 		userObject.email = ldapUser.object.mail;                                                                             // 135
 	} else if (RocketChat.settings.get('LDAP_Default_Domain') !== '') {                                                   //
```

**Comment by cs-1** [comment]
I'd also really appreciate a fix. @ekajmiller proposed what he calls is a "hack", however, I think it'd be a very useful workaround for the time being. Can you please include this patch until there's a more convenient way of solving this? We're currently deploying Rocket.chat in a large environment and we can't really do that without LDAP support.

**Comment by hartois** [comment]
On version 0.59.1 I got same error:
```
 rocketchat_logger rocketchat_logger.js:375 #033[31mLDAPSync ➔ error#033[39m Error creating user { [Error: Match error: Expected string, got object in field email]
 message: 'Match error: Expected string, got object in field email',
 path: 'email',
 sanitizedError:
 { [Error: Match failed [400]]
 isClientSafe: true,
 error: 400,
 reason: 'Match failed',
 details: undefined,
 message: 'Match failed [400]',
 errorType: 'Meteor.Error' },
 errorType: 'Match.Error' }
 Exception while invoking method 'login' Error: Match error: Expected string, got object in field email
 at exports.check (packages/check.js:55:15)
 at createUser (/opt/Rocket.Chat/programs/server/packages/accounts-password.js:1115:3)
 at AccountsServer.Accounts.createUser (/opt/Rocket.Chat/programs/server/packages/accounts-password.js:1202:10)
 at addLdapUser (/opt/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:1294:29)
 at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:783:9)
 at /opt/Rocket.Chat/programs/server/packages/accounts-base.js:925:30
 at tryLoginMethod (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:753:14)
 at AccountsServer.Ap._runLoginHandlers (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:924:18)
 at AccountsServer.Accounts._runLoginHandlers (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1951:33)
 at [object Object].methods.login (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:982:27)
 at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
 at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1857:12)
 at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:903:20
 at [object Object].EVp.withValue (packages/meteor.js:1134:15)
 at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:47
 at [object Object].EVp.withValue (packages/meteor.js:1134:15)
 at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:901:46
 at [object Object]._.extend.protocol_handlers.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:874:21)
 at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:753:85
 Sanitized and reported to the client as: Match failed [400]
 undefined undefined
```

**Comment by hartois** [comment]
Same on 0.59.2

**Comment by derkoe** [comment]
@hartois you have to add the mapping `"mail":"emails"` to the "User Data Field Map"

**Comment by hartois** [comment]
@derkoe Do I have to specify the "mail" attribute twice? Or just specify mail -> emails only mapping?

**Comment by derkoe** [comment]
@hartois good question - we have both and it works. When looking at the code it could also work with only `{"mail":"emails"}`

**Comment by priyadarshi035** [comment]
Hi @derkoe 
i have tried your solution but it doesn't help in my case.
Rocket Chat version being used is 0.66.3
Any suggestion would be nuch appreciated.
mail id : priyadarshi035@gmail.com

**Comment by derkoe** [comment]
@priyadarshi035 the config above worked for us - I think I cannot help you any more than that. Maybe you should provide an error for the dev team and/or open a new issue.

**Comment by priyadarshi035** [comment]
@derkoe
Please find the logs 
{"name":"ldapjs","component":"client","hostname":"rocketchat-test-rocketchat-66c679c8b9-t2rnh","pid":1,"clazz":"Client","level":10,"msg":"parse: data=<Buffer 0a 01 00 04 00 04 00>","time":"2018-07$
{"name":"ldapjs","component":"client","hostname":"rocketchat-test-rocketchat-66c679c8b9-t2rnh","pid":1,"clazz":"Client","level":10,"msg":"Parsing done: {\"messageID\":4,\"protocolOp\":\"LDAPResult$
{"name":"ldapjs","component":"client","hostname":"rocketchat-test-rocketchat-66c679c8b9-t2rnh","pid":1,"clazz":"Client","ldap_id":"290__ldap://10.85.108.200:1389","level":10,"msg":"response receiv$
rocketchat_logger rocketchat_logger.js:278 ^[[31mLDAPSync â error^[[39m Error creating user { Error: Match error: Expected string, got object in field email
    at check (/app/bundle/programs/server/packages/check.js:68:17)
    at createUser (/app/bundle/programs/server/packages/accounts-password.js:1215:3)
    at AccountsServer.Accounts.createUser (/app/bundle/programs/server/packages/accounts-password.js:1302:10)
    at addLdapUser (/app/bundle/programs/server/packages/rocketchat_ldap.js:1291:31)
    at MethodInvocation.<anonymous> (/app/bundle/programs/server/packages/rocketchat_ldap.js:742:18)
    at /app/bundle/programs/server/packages/accounts-base.js:876:30
    at tryLoginMethod (/app/bundle/programs/server/packages/accounts-base.js:702:14)
    at AccountsServer.Ap._runLoginHandlers (/app/bundle/programs/server/packages/accounts-base.js:875:18)
    at AccountsServer.Accounts._runLoginHandlers (/app/bundle/programs/server/packages/rocketchat_lib.js:3343:36)
    at MethodInvocation.methods.login (/app/bundle/programs/server/packages/accounts-base.js:933:27)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1877:12)
    at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (/app/bundle/programs/server/packages/ddp-server.js:902:46)
    at new Promise (<anonymous>:null:null)
    at Session.method (/app/bundle/programs/server/packages/ddp-server.js:875:23)
    at /app/bundle/programs/server/packages/ddp-server.js:754:85

  message: 'Match error: Expected string, got object in field email',
  path: 'email',
  sanitizedError:
   { Error: Match failed [400]
    at errorClass.<anonymous> (/app/bundle/programs/server/packages/check.js:117:27)
    at new errorClass (packages/meteor.js:607:17)
    at check (/app/bundle/programs/server/packages/check.js:68:17)
    at createUser (/app/bundle/programs/server/packages/accounts-password.js:1215:3)
    at AccountsServer.Accounts.createUser (/app/bundle/programs/server/packages/accounts-password.js:1302:10)
    at addLdapUser (/app/bundle/programs/server/packages/rocketchat_ldap.js:1291:31)
    at MethodInvocation.<anonymous> (/app/bundle/programs/server/packages/rocketchat_ldap.js:742:18)
isClientSafe: true,
     error: 400,
     reason: 'Match failed',
     details: undefined,
     message: 'Match failed [400]',
     errorType: 'Meteor.Error' },
  errorType: 'Match.Error' }
Exception while invoking method 'login' Error: Match error: Expected string, got object in field email
    at check (/app/bundle/programs/server/packages/check.js:68:17)
    at createUser (/app/bundle/programs/server/packages/accounts-password.js:1215:3)
    at AccountsServer.Accounts.createUser (/app/bundle/programs/server/packages/accounts-password.js:1302:10)
    at addLdapUser (/app/bundle/programs/server/packages/rocketchat_ldap.js:1291:31)
    at MethodInvocation.<anonymous> (/app/bundle/programs/server/packages/rocketchat_ldap.js:742:18)
    at /app/bundle/programs/server/packages/accounts-base.js:876:30
    at tryLoginMethod (/app/bundle/programs/server/packages/accounts-base.js:702:14)
    at AccountsServer.Ap._runLoginHandlers (/app/bundle/programs/server/packages/accounts-base.js:875:18)
    at AccountsServer.Accounts._runLoginHandlers (/app/bundle/programs/server/packages/rocketchat_lib.js:3343:36)
    at MethodInvocation.methods.login (/app/bundle/programs/server/packages/accounts-base.js:933:27)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1877:12)
    at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (/app/bundle/programs/server/packages/ddp-server.js:902:46)
    at new Promise (<anonymous>:null:null)
    at Session.method (/app/bundle/programs/server/packages/ddp-server.js:875:23)
    at /app/bundle/programs/server/packages/ddp-server.js:754:85

Sanitized and reported to the client as: Match failed [400]
undefined undefined
{"name":"ldapjs","component":"client","hostname":"rocketchat-test-rocketchat-66c679c8b9-t2rnh","pid":1,"clazz":"Client","ldap_id":"290__ldap://10.85.108.200:1389","level":10,"msg":"Setting timeout$
{"name":"ldapjs","component":"client","hostname":"rocketchat-test-rocketchat-66c679c8b9-t2rnh","pid":1,"clazz":"Client","ldap_id":"290__ldap://10.85.108.200:1389","level":10,"msg":"sending request$
{"name":"ldapjs","component":"client","hostname":"rocketchat-test-rocketchat-66c679c8b9-t2rnh","pid":1,"clazz":"Client","level":10,"msg":"end event","time":"2018-07-31T08:33:43.561Z","v":0}
