### ISSUE TITLE
Jenkins Notification Plugin does not work after upgrade to 5.0.0 from 4.8.2

### ISSUE THREAD

**Issue by StefanIGit** [RocketChat/Rocket.Chat#26483]
**Describe the bug**
The Plugin worked fine with 4.8.2
with 5.0.0 the call to /api/v1/channels.list get a 504

What operating system and which version?
Debian Linux
Which version of Rocket.Chat (Server)?
docker 5.0.0 image

Is there any setting relevant changed?

**To Reproduce**
1. setup personal API Token
2. run 'docker logs rocketchat -f'
3. run `url -H "X-Auth-Token: ${TOKEN}"      -H "X-User-Id: ${USERNAME}"      -H "Content-type: application/json"     http://localhost:3000/api/v1/channels.list`
`Exception on find Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor.js:1188:11)
    at Meteor.EnvironmentVariable.EVp.get (packages/meteor.js:1213:10)
    at Object.collection.<computed> [as find] (packages/matb33:collection-hooks/collection-hooks.js:79:37)
    at Collection.find (packages/mongo/collection.js:380:29)
    at BaseDb.find (app/models/server/models/_BaseDb.js:241:21)
    at Users.find (app/models/server/models/_Base.js:122:29)
    at Users.findUsersByUsernames (app/models/server/models/Users.js:926:15)
    at normalizeMessagesForUser (app/utils/server/lib/normalizeMessagesForUser.ts:46:9)
    at Object._composeRoomWithLastMessage [as composeRoomWithLastMessage] (app/api/server/helpers/composeRoomWithLastMessage.ts:8:25)
    at app/api/server/v1/channels.js:459:31
    at nextDocument (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor/abstract_cursor.js:425:20)
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor/abstract_cursor.js:480:82
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:510:9
    at completeEndSession (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sessions.js:147:17)
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sessions.js:157:13
    at maybePromise (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:496:5)
    at ClientSession.endSession (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sessions.js:133:41)
    at cleanupCursor (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor/abstract_cursor.js:533:32)
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor/abstract_cursor.js:480:24
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor/find_cursor.js:66:13
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:510:9
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/execute_operation.js:50:17 { username: { '$in': [ 'Jenkins', 'here' ] } } { fields: { username: 1, name: 1 } }
`

**Expected behavior**
no error ;) just works

**Comment by badchoyo** [comment]
+1

**Comment by StefanIGit** [comment]
5.0.3 fixed it,thx
