### ISSUE TITLE
Docker container rocket.chat 5.0.0 and 5.0.1 ignores hostname in variable MONGO_URL

### ISSUE THREAD

**Issue by vaclav-kasal** [RocketChat/Rocket.Chat#26503]
### Description:

Variable MONGO_URL is used to set mongodb hostname rocket chat connects to. However rocket chat 5.0.0 and 5.0.1 connects to localhost instead of hostname specified in MONGO_URL.
`MONGO_URL=mongodb://db:27017/rocketchat`
Error message: MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
Same config works for any version 4. Latest working version is 4.8.1. I assume it is a bug in rocket chat 5.

### Steps to reproduce:

1. create file docker-compose.yaml with following content:
```yaml
version: '2'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:5.0.1
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://db:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://db:27017/local
    depends_on:
      - db

  db:
    image: mongo:5.0
    restart: unless-stopped
    command: mongod --oplogSize 128 --replSet rs0
```
2. run `docker compose up`

### Expected behavior:

rocketchat connects to specified hostname in variable MONGO_URL

### Actual behavior:

rocketchat connects to localhost

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.1
- Operating System: Debian 10
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: 14.19.3
- MongoDB Version: 5

### Relevant logs:
```
rocketchat-latest-rocketchat5-1  | /app/bundle/programs/server/node_modules/fibers/future.js:313
rocketchat-latest-rocketchat5-1  | 						throw(ex);
rocketchat-latest-rocketchat5-1  | 						^
rocketchat-latest-rocketchat5-1  |
rocketchat-latest-rocketchat5-1  | MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
rocketchat-latest-rocketchat5-1  |     at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
rocketchat-latest-rocketchat5-1  |     at listOnTimeout (internal/timers.js:557:17)
rocketchat-latest-rocketchat5-1  |     at processTimers (internal/timers.js:500:7) {
rocketchat-latest-rocketchat5-1  |   reason: TopologyDescription {
rocketchat-latest-rocketchat5-1  |     type: 'ReplicaSetNoPrimary',
rocketchat-latest-rocketchat5-1  |     servers: Map(1) {
rocketchat-latest-rocketchat5-1  |       'localhost:27017' => ServerDescription {
rocketchat-latest-rocketchat5-1  |         _hostAddress: HostAddress { isIPv6: false, host: 'localhost', port: 27017 },
rocketchat-latest-rocketchat5-1  |         address: 'localhost:27017',
rocketchat-latest-rocketchat5-1  |         type: 'Unknown',
rocketchat-latest-rocketchat5-1  |         hosts: [],
rocketchat-latest-rocketchat5-1  |         passives: [],
rocketchat-latest-rocketchat5-1  |         arbiters: [],
rocketchat-latest-rocketchat5-1  |         tags: {},
rocketchat-latest-rocketchat5-1  |         minWireVersion: 0,
rocketchat-latest-rocketchat5-1  |         maxWireVersion: 0,
rocketchat-latest-rocketchat5-1  |         roundTripTime: -1,
rocketchat-latest-rocketchat5-1  |         lastUpdateTime: 2540315540,
rocketchat-latest-rocketchat5-1  |         lastWriteDate: 0,
rocketchat-latest-rocketchat5-1  |         error: MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
rocketchat-latest-rocketchat5-1  |             at connectionFailureError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:381:20)
rocketchat-latest-rocketchat5-1  |             at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:301:22)
rocketchat-latest-rocketchat5-1  |             at Object.onceWrapper (events.js:520:26)
rocketchat-latest-rocketchat5-1  |             at Socket.emit (events.js:400:28)
rocketchat-latest-rocketchat5-1  |             at emitErrorNT (internal/streams/destroy.js:106:8)
rocketchat-latest-rocketchat5-1  |             at emitErrorCloseNT (internal/streams/destroy.js:74:3)
rocketchat-latest-rocketchat5-1  |             at processTicksAndRejections (internal/process/task_queues.js:82:21)
rocketchat-latest-rocketchat5-1  |       }
rocketchat-latest-rocketchat5-1  |     },
rocketchat-latest-rocketchat5-1  |     stale: false,
rocketchat-latest-rocketchat5-1  |     compatible: true,
rocketchat-latest-rocketchat5-1  |     heartbeatFrequencyMS: 10000,
rocketchat-latest-rocketchat5-1  |     localThresholdMS: 15,
rocketchat-latest-rocketchat5-1  |     setName: 'rs0',
rocketchat-latest-rocketchat5-1  |     maxSetVersion: 3,
rocketchat-latest-rocketchat5-1  |     maxElectionId: ObjectId {
rocketchat-latest-rocketchat5-1  |       [Symbol(id)]: Buffer(12) [Uint8Array] [
rocketchat-latest-rocketchat5-1  |         127, 255, 255, 255, 0,
rocketchat-latest-rocketchat5-1  |           0,   0,   0,   0, 0,
rocketchat-latest-rocketchat5-1  |           0, 117
rocketchat-latest-rocketchat5-1  |       ]
rocketchat-latest-rocketchat5-1  |     },
rocketchat-latest-rocketchat5-1  |     commonWireVersion: 13,
rocketchat-latest-rocketchat5-1  |     logicalSessionTimeoutMinutes: undefined
rocketchat-latest-rocketchat5-1  |   }
rocketchat-latest-rocketchat5-1  | }
rocketchat-latest-rocketchat5-1 exited with code 1
```

**Comment by debdutdeb** [comment]
There are three solutions,
1. Use the new compose file. 
2. Make sure when you're setting up the replicaset you're using the correct hostname (as in the service name entry of the compose file)
3. Using `directConnection=true` parameter in the `MONGO.*_URL` variables. 

This is not a product bug. Closing. Please feel free to reopen if neither of the above works for you.

**Comment by dudanogueira** [comment]
Hi! Please check this in deep video about what is happening on this issue and some fixes.
https://www.youtube.com/watch?v=8DeBQsfe2rU
