### ISSUE TITLE
Can't play custom sound in 5.0.1-5.0.2 version [Error: Exception while invoking method uploadCustomSound]

### ISSUE THREAD

**Issue by yatounoneko** [RocketChat/Rocket.Chat#26524]
### Steps to reproduce:

1. Upload custom sound file
2. Play sound

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.2
- Operating System: Debain 11
- Deployment Method: Rocketchatctl
- Number of Running Instances: 1
- NodeJS Version: 14.19.3 - x64
- MongoDB Version: 5.0.10
- MongoDB Engine: wiredTiger
- Platform: linux
- Process Port: 3000
- Site URL: https://website.com (Nginx SSL reverse proxy with Port 443)
- ReplicaSet OpLog: Enabled

### Client Setup Information

- Desktop App or Browser Version: 
	- iOS: 4.29.0.34197
	- Android: 4.29.0.34199
	- PC: 3.8.7
- Operating System: 
	- iOS: 15.3.1
	- Android: 12
	- PC: Windows 11 22H2

### Relevant logs:
Error channel notifications
```
Exception while invoking method uploadCustomSound

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Timeout


Exception in callback of async function:

TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Type"
```

Admin panel logs
```
{"level":50,"time":"2022-08-09T12:40:00.504Z","pid":3073,"hostname":"RocketChat-HK","name":"System","msg":"Exception while invoking method uploadCustomSound 'The \"listener\" argument must be of type function. Received an instance of Timeout'"} 
I20220809-20:40:01.037(8) Version 9 of Highlight.js has reached EOL and is no longer supported. Please upgrade or ask whatever dependency you are using to upgrade. https://github.com/highlightjs/highlight.js/issues/2877 
I20220809-20:40:01.091(8) Exception in callback of async function: TypeError [ERR_HTTP_INVALID_HEADER_VALUE] [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Type"     at ServerResponse.setHeader (_http_outgoing.js:564:3)     at app/custom-sounds/server/startup/custom-sounds.js:78:8     at runWithEnvironment (packages/meteor.js:1320:24)     at packages/meteor.js:1333:14     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {   code: 'ERR_HTTP_INVALID_HEADER_VALUE' } 
I20220809-20:40:01.453(8) Exception in callback of async function: TypeError [ERR_HTTP_INVALID_HEADER_VALUE] [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Type"     at ServerResponse.setHeader (_http_outgoing.js:564:3)     at app/custom-sounds/server/startup/custom-sounds.js:78:8     at runWithEnvironment (packages/meteor.js:1320:24)     at packages/meteor.js:1333:14     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {   code: 'ERR_HTTP_INVALID_HEADER_VALUE' } 
I20220809-20:40:21.012(8) Exception in callback of async function: TypeError [ERR_HTTP_INVALID_HEADER_VALUE] [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Type"     at ServerResponse.setHeader (_http_outgoing.js:564:3)     at app/custom-sounds/server/startup/custom-sounds.js:78:8     at runWithEnvironment (packages/meteor.js:1320:24)     at packages/meteor.js:1333:14     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {   code: 'ERR_HTTP_INVALID_HEADER_VALUE' } 
```

**Comment by AkimoA** [comment]
Same problem on Server with 5.1.4 same error log as well .

**Comment by vinogradovia** [comment]
Same problem for new upload. Old sounds  play without error.

**Comment by AkimoA** [comment]
so i updated to the latest dev (5.4.0)  but the above mentioned Error stays the same it uploads fine but it wont play the actual sound, tested on 3 different Browsers here is all i could find from the logs -> 

```
{"level":50,"time":"2022-11-04T05:17:28.720Z","pid":1,"hostname":"d8a0ab2e41f2","name":"System","msg":"Exception while invoking method autoTranslate.getSupportedLanguages","err":{"type":"errorClass","message":"Auto-Translate is disabled [error-autotranslate-disabled]","stack":"Error: Auto-Translate is disabled [error-autotranslate-disabled]<br>    at MethodInvocation.autoTranslate.getSupportedLanguages (app/autotranslate/server/methods/getSupportedLanguages.ts:11:10)<br>    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:74:34)<br>    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)<br>    at packages/ddp-server/livedata_server.js:1803:15<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)<br>    at packages/ddp-server/livedata_server.js:1801:36<br>    at new Promise (<anonymous>)<br>    at Server.applyAsync (packages/ddp-server/livedata_server.js:1800:12)<br>    at Server.apply (packages/ddp-server/livedata_server.js:1739:26)<br>    at Server.call (packages/ddp-server/livedata_server.js:1721:17)<br>    at Object.post (app/api/server/v1/misc.ts:554:27)<br>    at app/api/server/api.js:463:96<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)<br>    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:463:39)<br>    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)<br>    at packages/rocketchat_restivus/lib/route.coffee:59:33<br>    at packages/simple_json-routes.js:100:9<br> => awaited here:<br>    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)<br>    at Server.apply (packages/ddp-server/livedata_server.js:1752:22)<br>    at Server.call (packages/ddp-server/livedata_server.js:1721:17)<br>    at Object.post (app/api/server/v1/misc.ts:554:27)<br>    at app/api/server/api.js:463:96<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)<br>    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:463:39)<br>    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)<br>    at packages/rocketchat_restivus/lib/route.coffee:59:33<br>    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":"error-autotranslate-disabled","reason":"Auto-Translate is disabled","errorType":"Meteor.Error"},"msg":"Auto-Translate is disabled [error-autotranslate-disabled]"} 
Exception in callback of async function: TypeError [ERR_HTTP_INVALID_HEADER_VALUE] [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Type"     at ServerResponse.setHeader (_http_outgoing.js:564:3)     at app/custom-sounds/server/startup/custom-sounds.js:78:8     at runWithEnvironment (packages/meteor.js:1320:24)     at packages/meteor.js:1333:14     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {   code: 'ERR_HTTP_INVALID_HEADER_VALUE' } 
```
