### ISSUE TITLE
[error-not-allowed] intermittently when direct messaging user(s) for first time (in web or on api call `chat.postMessage`)

### ISSUE THREAD

**Issue by calebjacobson** [RocketChat/Rocket.Chat#26605]
I commented on issue #22256 since i think it is similar to this one, however that issue had already seen a merge and was unsure if it was left open accidentally.

### Steps to Reproduce:
1. send a direct message with a user (or users) for the first time (issue occurs intermittently whether using the web interface or using api/v1/chat.postMessage)
2. check rooms list - the direct message is added! though the error is thrown and no message appears in the room
3. check logs. What shows up when using the API is `Error: error-not-allowed at app/authorization/server/functions/canSendMessage.ts:26:9`

### Expected Behavior:
add the new room without error or give a more precise explanation as to why it could not send the message

### Actual Behavior
Room is added, no message is in the room, and an error is thrown (when using the web interface, "Error Not Allowed" shows up in red error bubble in the top right of the screen).

### Server Setup Information:
* Version of Rocket.Chat Server: 4.8.3
* Operating System: Ubuntu Server 18.04.3
* Deployment Method: bare metal (virtualized in a VMWare-like environment) with snap
* Number of Running instances: 1
* DB Replicaset Oplog: Enabled
* NodeJS version: 14.18.3
* MongoDB Version: 4.2.17 / wiredTiger

### Client Setup Information:
* Browser Version: Chrome 103.0.5060.134
* Operating System: Linux Mint 20.3
* LDAP is enabled

### Additional context
* Our rocket chat installation is being proxied through nginx for SSL termination, with rocketchat-caddy being disabled in snap.
* This issue started happing several months ago and is being increasingly reported by our users. We deployed a service that utilizes a bot user to send automated messages to our users (always in individual direct messages) and have been experiencing this error occasionally the bot user attempts to send messages. All errors occur when sending a message to a user the bot user has not messaged before, however, not all messages to new users from this bot user get an error response. Rooms are created when the bot user encounters this error, but the message it attempts to send does not appear in the room.
* Our users are set up and authenticated using LDAP

### Relevant Logs: `sudo journalctl -r -u snap.rocketchat-server.rocketchat-server | grep error-not-allowed`
```
Aug 15 12:16:58 <SERVER NAME REDACTED> rocketchat-server.rocketchat-server[8232]: {"level":35,"time":"2022-08-15T12:16:58.081Z","pid":8286,"hostname":"<SERVER NAME REDACTED>","name":"API","method":"POST","url":"/api/v1/chat.postMessage","userId":"<USER ID REDACTED>","userAgent":"axios/0.27.2","length":"247","host":"<HOST REDACTED>","remoteIP":"<IP REDACTED>","err":{"type":"Error","message":"error-not-allowed","stack":"Error: error-not-allowed\n    at app/authorization/server/functions/canSendMessage.ts:26:9\n    at /snap/rocketchat-server/1523/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/snap/rocketchat-server/1523/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at validateRoomMessagePermissions (app/authorization/server/functions/canSendMessage.ts:70:17)\n    at processWebhookMessage (app/lib/server/functions/processWebhookMessage.js:102:3)\n    at Object.post (app/api/server/v1/chat.js:162:26)\n    at app/api/server/api.js:431:96\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:431:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9"},"status":400,"responseTime":1100,"msg":"error-not-allowed"}
```

**Comment by calebjacobson** [comment]
it has been three weeks since I have submitted this. Has anyone looked at it?

**Comment by debdutdeb** [comment]
I was stuck at what the exact issue is then remembered - it was fixed a long time ago though if I'm not mistaken. I'll try to find the PR.

**Comment by debdutdeb** [comment]
nevermind different issue - can you share a screengrab? 😬 I have not seen this happen .. even normal tests didn't yield anything

**Comment by calebjacobson** [comment]
The majority of the time I experience this error is with the API (see error log above). I am trying to acquire a screengrab from some of our users, but basically its a red error box in the top right that says "Not Allowed" after attempting to create a direct message (single or multiple users) with someone new. Happens intermittently. Interface shows blank area behind error message, like it never finished navigating to a room (sidebar and top menu bar still show up). could this issue be related to the still-open #22256?

**Comment by debdutdeb** [comment]
Maybe. Thanks for clarifying. I'll take a look next week.

**Comment by calebjacobson** [comment]
I am still occasionally experiencing this error. any news on this?

**Comment by calebjacobson** [comment]
This error is still occurring in our system. Our only recourse now is to catch this error and retry once. That way the second try will use the room already created. This is not a great solution since err-not-allowed can notify of more than this error. Have you found any solution yet?

**Comment by calebjacobson** [comment]
Any more news on this?

**Comment by mextex** [comment]
We also experience the error. Is there a solution for this?
