### ISSUE TITLE
Brand New RC Instance on CentOS 7 Fails With Segmentation Fault

### ISSUE THREAD

**Issue by whitetiger264** [RocketChat/Rocket.Chat#26664]
- Version of Rocket.Chat Server: 5.0.4
- Operating System: CentOS 7 
- Deployment Method: Manual
- Number of Running Instances: 1
- NodeJS Version: 14.0.0.0
- MongoDB Version: 5.0.11

I just completed a new RocketChat install on our CentOS 7 server and upon starting the service, I am presented with a Segmentation fault:

```
[root@core opt]# node /opt/Rocket.Chat/main.js
Segmentation fault (core dumped)
[root@core opt]# 
```

entry from /var/log/messages:

```
Aug 23 16:43:26 core rocketchat: /opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:313
Aug 23 16:43:26 core rocketchat: throw(ex);
Aug 23 16:43:26 core rocketchat: ^
Aug 23 16:43:26 core rocketchat: MongoServerSelectionError: Server selection timed out after 30000 ms
Aug 23 16:43:26 core rocketchat: at Timeout._onTimeout (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
Aug 23 16:43:26 core rocketchat: at listOnTimeout (internal/timers.js:549:17)
Aug 23 16:43:26 core rocketchat: at processTimers (internal/timers.js:492:7) {
Aug 23 16:43:26 core rocketchat: reason: TopologyDescription {
Aug 23 16:43:26 core rocketchat: type: 'ReplicaSetNoPrimary',
Aug 23 16:43:26 core rocketchat: servers: Map(0) {},
Aug 23 16:43:26 core rocketchat: stale: false,
Aug 23 16:43:26 core rocketchat: compatible: true,
Aug 23 16:43:26 core rocketchat: heartbeatFrequencyMS: 10000,
Aug 23 16:43:26 core rocketchat: localThresholdMS: 15,
Aug 23 16:43:26 core rocketchat: setName: 'rs01',
Aug 23 16:43:26 core rocketchat: commonWireVersion: 13,
Aug 23 16:43:26 core rocketchat: logicalSessionTimeoutMinutes: undefined
Aug 23 16:43:26 core rocketchat: }
Aug 23 16:43:26 core rocketchat: }
Aug 23 16:43:26 core systemd: rocketchat.service: main process exited, code=exited, status=1/FAILURE
Aug 23 16:43:26 core systemd: Unit rocketchat.service entered failed state.
Aug 23 16:43:26 core systemd: rocketchat.service failed.
[root@core opt]# 
```

Is there anyone that can assist with this, please?

**Comment by dudanogueira** [comment]
Hi!

This seem to be related to recent Mongo Node Driver changes.

Check this Issue message for a fix:
https://github.com/RocketChat/Rocket.Chat/issues/26519#issuecomment-1209343480

If you want to understand this issue better, we did a Rocket.Lab here:
https://www.youtube.com/watch?v=8DeBQsfe2rU

Please, let me know if this helps.

**Comment by whitetiger264** [comment]
Hi @dudanogueira 

Thank you for the update. Sadly, however, this has not worked for me. 

I updated my  `/lib/systemd/system/rocketchat.service` from this:

```
[Unit]
Description=Example RocketChat Sever
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target mongod.service
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01 MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01 ROOT_URL=https://rocketchat.example.com/ PORT=3000
[Install]
WantedBy=multi-user.target
```

To this:

```
[Unit]
Description=Example RocketChat Sever
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target mongod.service
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://mongo0:27017/rocketchat?replicaSet=rs01&directConnection=true MONGO_OPLOG_URL=mongodb://mongo0:27017/local?replicaSet=rs01&directConnection=true ROOT_URL=https://rocketchat.example.com/ PORT=3000
[Install]
WantedBy=multi-user.target
```

And still, end up with an error:

```
[root@core opt]# node /opt/Rocket.Chat/main.js
/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92
					return fn.apply(this, arguments);
					          ^

Error: Must pass options.rootUrl or set ROOT_URL in the server environment
    at Object.Meteor.absoluteUrl (packages/meteor.js:1412:11)
    at runWebAppServer (packages/webapp/webapp_server.js:990:48)
    at packages/webapp/webapp_server.js:1488:1
    at module (packages/webapp/webapp_server.js:1488:16)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /opt/Rocket.Chat/programs/server/packages/webapp.js:1957:15
    at /opt/Rocket.Chat/programs/server/packages/webapp.js:1966:3
    at /opt/Rocket.Chat/programs/server/boot.js:401:38
    at Array.forEach (<anonymous>)
    at /opt/Rocket.Chat/programs/server/boot.js:226:21
    at /opt/Rocket.Chat/programs/server/boot.js:464:7
    at Function.run (/opt/Rocket.Chat/programs/server/profile.js:280:14)
    at /opt/Rocket.Chat/programs/server/boot.js:463:13
[root@core opt]# clear
```
```
root@core opt]# systemctl status rocketchat -l
● rocketchat.service - Example RocketChat Sever
   Loaded: loaded (/usr/lib/systemd/system/rocketchat.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2022-08-30 14:44:03 CAT; 24ms ago
  Process: 37492 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 37492 (code=exited, status=1/FAILURE)

Aug 30 14:44:03 hostname rocketchat[37492]: /opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:313
Aug 30 14:44:03 hostname rocketchat[37492]: throw(ex);
Aug 30 14:44:03 hostname rocketchat[37492]: ^
Aug 30 14:44:03 hostname rocketchat[37492]: MongoServerSelectionError: getaddrinfo ENOTFOUND mongo0
Aug 30 14:44:03 hostname rocketchat[37492]: at Timeout._onTimeout (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
Aug 30 14:44:03 hostname rocketchat[37492]: at listOnTimeout (internal/timers.js:557:17)
Aug 30 14:44:03 hostname rocketchat[37492]: at processTimers (internal/timers.js:500:7) {
Aug 30 14:44:03 hostname systemd[1]: rocketchat.service: main process exited, code=exited, status=1/FAILURE
Aug 30 14:44:03 hostname systemd[1]: Unit rocketchat.service entered failed state.
Aug 30 14:44:03 hostname systemd[1]: rocketchat.service failed.
```

What else am I missing in this case?

**Comment by dudanogueira** [comment]
Hi!

We have some different errors here. 

Regarding the reported one, it's solved, as well as the ROOT_URL, as you stated yourself.

Regarding the segfault, debdut just answered here a few hours ago:
https://github.com/RocketChat/Rocket.Chat/issues/26716#issuecomment-1231853595

With all that said, I'll close this issue, so we can keep it concentrated on that one.

Thanks!
