### ISSUE TITLE
Cannot register user on rocketchat workspace

### ISSUE THREAD

**Issue by acrespomoa** [RocketChat/Rocket.Chat#26735]
### Steps to reproduce:

<!It looks that LDAP sync has been corrupted, anyone can sign in on the rocketchat workspace, it appears that the username does not exists or the password is wrong. 
![image](https://user-images.githubusercontent.com/112470149/187382199-b88d9185-e52c-47a1-8736-84abf95d66a0.png) -->

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu 20.04 LST
- Deployment Method: 
- Number of Running Instances: 3
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 5.0.9

### Client Setup Information

- Desktop App or Browser Version: Rocketchat desktop app 3.8, and web brower , latest verion of Chrome and Firefox. 
- Operating System: tested on Windows 11 and Wondws 10

### Relevant logs:

<Looking at the syslog, tow lines of the bug:
Aug 30 09:56:14 rocketchat rocketchat-medop[1118]: {"level":50,"time":"2022-08-30T07:56:14.759Z","pid":1118,"hostname":"rocketchat","name":"LDAP","section":"Connection","msg":"connection time out","timeout":1000}

Aug 30 09:56:14 rocketchat rocketchat-medop[1118]: {"level":50,"time":"2022-08-30T07:56:14.765Z","pid":1118,"hostname":"rocketchat","name":"LDAP","err":{"type":"Error","message":"Timeout","stack":"Error: Timeout\n    at Timeout._onTimeout (server/lib/ldap/Connection.ts:775:35)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)\n => awaited here:\n    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/lib/ldap/Manager.ts:34:5\n    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"Timeout"} -->

**Comment by dudanogueira** [comment]
Please, provide all the required information.

What is the server version you are running?

According to the logs, there was an LDAP Connection timeout.

Please, consider using out Community Support Channel or Forums in before opening a new issue.

Also, read thru this doc on how to better "navigate" in our community :)
https://docs.rocket.chat/getting-support/community-support

Closing this issue for now, as this seems to be a configuration problem rather a software bug.
