### ISSUE TITLE
problem with update to 5.1.0

### ISSUE THREAD

**Issue by hakerakn** [RocketChat/Rocket.Chat#26804]
### Description:

When trying to update to version 5.1.0 it gives me these errors. 

**Sep  5 10:13:08 chat systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Sep  5 10:13:08 chat systemd[1]: rocketchat.service: Failed with result 'exit-code'.**

### Server Setup Information:

- Operating System:  Ubuntu 20.04
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.3
- MongoDB Version: 5.0.6 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version:  Desktop App and Browser Version
- Operating System: Windows 10

### Relevant logs:

Sep  5 10:12:41 chat rocketchat[1790242]: strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes)
Sep  5 10:12:49 chat rocketchat[1790242]: LocalStore: store created at
Sep  5 10:12:49 chat rocketchat[1790242]: message repeated 2 times: [ LocalStore: store created at]
Sep  5 10:12:53 chat rocketchat[1790242]: MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
Sep  5 10:12:55 chat rocketchat[1790242]: {"level":40,"time":"2022-09-05T07:12:55.667Z","pid":1790242,"hostname":"chat.polimedad.com","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"}
Sep  5 10:12:55 chat rocketchat[1790242]: {"level":30,"time":"2022-09-05T07:12:55.962Z","pid":1790242,"hostname":"chat.polimedad.com","name":"Federation","section":"Setup","msg":"Federation is disabled"}
Sep  5 10:13:04 chat rocketchat[1790242]: {"level":30,"time":"2022-09-05T07:13:04.522Z","pid":1790242,"hostname":"chat.polimedad.com","name":"CAS","msg":"Disabling CAS login service"}
Sep  5 10:13:07 chat rocketchat[1790242]: {"level":30,"time":"2022-09-05T07:13:07.627Z","pid":1790242,"hostname":"chat.polimedad.com","name":"rocketchat:theme","stop_rendering":695}
Sep  5 10:13:08 chat rocketchat[1790242]: {"level":30,"time":"2022-09-05T07:13:08.295Z","pid":1790242,"hostname":"chat.polimedad.com","name":"Search Logger","msg":"create search provider defaultProvider"}
Sep  5 10:13:08 chat rocketchat[1790242]: {"level":30,"time":"2022-09-05T07:13:08.319Z","pid":1790242,"hostname":"chat.polimedad.com","name":"Search Logger","msg":"create search provider chatpalProvider"}
Sep  5 10:13:08 chat rocketchat[1790242]: {"level":30,"time":"2022-09-05T07:13:08.417Z","pid":1790242,"hostname":"chat.polimedad.com","name":"VoIPService","msg":"Stopping VoIP service"}
Sep  5 10:13:08 chat rocketchat[1790242]: {"level":40,"time":"2022-09-05T07:13:08.418Z","pid":1790242,"hostname":"chat.polimedad.com","name":"VoIPService","msg":"VoIP service already stopped"}
Sep  5 10:13:08 chat rocketchat[1790242]: /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
Sep  5 10:13:08 chat rocketchat[1790242]:       throw error;
Sep  5 10:13:08 chat rocketchat[1790242]:       ^
Sep  5 10:13:08 chat rocketchat[1790242]: MongoInvalidArgumentError: Update document requires atomic operators
Sep  5 10:13:08 chat rocketchat[1790242]:     at new UpdateOneOperation (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/update.js:67:19)
Sep  5 10:13:08 chat rocketchat[1790242]:     at Collection.updateOne (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:168:90)
Sep  5 10:13:08 chat rocketchat[1790242]:     at Proxy.updateOne (server/models/raw/BaseRaw.ts:199:20)
Sep  5 10:13:08 chat rocketchat[1790242]:     at app/settings/server/SettingsRegistry.ts:176:22
Sep  5 10:13:08 chat rocketchat[1790242]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Sep  5 10:13:08 chat rocketchat[1790242]:  => awaited here:
Sep  5 10:13:08 chat rocketchat[1790242]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Sep  5 10:13:08 chat rocketchat[1790242]:     at app/settings/server/index.ts:16:17
Sep  5 10:13:08 chat rocketchat[1790242]:     at SettingsRegistry.add (app/settings/server/Middleware.ts:12:10)
Sep  5 10:13:08 chat rocketchat[1790242]:     at Object.add (app/settings/server/SettingsRegistry.ts:231:10)
Sep  5 10:13:08 chat rocketchat[1790242]:     at Object.<anonymous> (app/lib/server/startup/settings.ts:846:7)
Sep  5 10:13:08 chat rocketchat[1790242]:     at app/settings/server/SettingsRegistry.ts:257:8
Sep  5 10:13:08 chat rocketchat[1790242]:     at app/settings/server/SettingsRegistry.ts:264:10
Sep  5 10:13:08 chat rocketchat[1790242]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Sep  5 10:13:08 chat rocketchat[1790242]:  => awaited here:
Sep  5 10:13:08 chat rocketchat[1790242]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Sep  5 10:13:08 chat rocketchat[1790242]:     at app/settings/server/index.ts:20:17
Sep  5 10:13:08 chat rocketchat[1790242]:     at SettingsRegistry.addGroup (app/settings/server/Middleware.ts:12:10)
Sep  5 10:13:08 chat rocketchat[1790242]:     at module (app/lib/server/startup/settings.ts:825:18)
Sep  5 10:13:08 chat rocketchat[1790242]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Sep  5 10:13:08 chat rocketchat[1790242]:     at Module.require (packages/modules-runtime.js:238:14)
Sep  5 10:13:08 chat rocketchat[1790242]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
Sep  5 10:13:08 chat rocketchat[1790242]:     at module (/opt/Rocket.Chat/programs/server/app/app.js:235355:8)
Sep  5 10:13:08 chat rocketchat[1790242]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Sep  5 10:13:08 chat rocketchat[1790242]:     at Module.require (packages/modules-runtime.js:238:14)
Sep  5 10:13:08 chat rocketchat[1790242]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
Sep  5 10:13:08 chat rocketchat[1790242]:     at module (server/importPackages.ts:16:8)
Sep  5 10:13:08 chat rocketchat[1790242]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Sep  5 10:13:08 chat rocketchat[1790242]:     at Module.require (packages/modules-runtime.js:238:14)
Sep  5 10:13:08 chat rocketchat[1790242]:     at require (packages/modules-runtime.js:258:21)
Sep  5 10:13:08 chat rocketchat[1790242]:     at /opt/Rocket.Chat/programs/server/app/app.js:1477288:15
Sep  5 10:13:08 chat rocketchat[1790242]:     at /opt/Rocket.Chat/programs/server/boot.js:401:38
Sep  5 10:13:08 chat rocketchat[1790242]:     at Array.forEach (<anonymous>)
Sep  5 10:13:08 chat rocketchat[1790242]:     at /opt/Rocket.Chat/programs/server/boot.js:226:21
Sep  5 10:13:08 chat rocketchat[1790242]:     at /opt/Rocket.Chat/programs/server/boot.js:464:7
Sep  5 10:13:08 chat rocketchat[1790242]:     at Function.run (/opt/Rocket.Chat/programs/server/profile.js:280:14)
Sep  5 10:13:08 chat rocketchat[1790242]:     at /opt/Rocket.Chat/programs/server/boot.js:463:13

**Comment by dudanogueira** [comment]
Hi! What is the deployment method?
From which version are you upgrading from?

**Comment by hakerakn** [comment]
I am upgrading from version 5.0.5.
I delete everything in a folder **/opt/Rocket.Chat.bkup/** 
then I give a command **rocketchatctl update**

**Comment by xmedeko** [comment]
@hakerakn Have you solved the issue somehow or are you still running v5.0.5?

**Comment by Azenet** [comment]
Getting a similar error, although 5.1.0 was running fine and then stopped working. I have upgraded to 5.1.2 and it did not fix the issue, following log is from 5.1.2. I am using MongoDB 4.4.11.
```
2022-09-13T13:57:28.630153251Z strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes)
2022-09-13T13:57:30.403602811Z LocalStore: store created at
2022-09-13T13:57:30.403629983Z LocalStore: store created at
2022-09-13T13:57:30.403672983Z LocalStore: store created at
2022-09-13T13:57:31.475247635Z MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
2022-09-13T13:57:31.717580945Z {"level":40,"time":"2022-09-13T13:57:31.717Z","pid":1,"hostname":"rocketchat-rocketchat-6cffbf75ff-wkh5f","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"}
2022-09-13T13:57:33.687000078Z {"level":40,"time":"2022-09-13T13:57:33.686Z","pid":1,"hostname":"rocketchat-rocketchat-6cffbf75ff-wkh5f","name":"VoIPService","msg":"VoIP service already stopped"}
2022-09-13T13:57:33.740434375Z /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
2022-09-13T13:57:33.740453160Z       throw error;
2022-09-13T13:57:33.740455264Z       ^
2022-09-13T13:57:33.740458430Z MongoInvalidArgumentError: Update document requires atomic operators
2022-09-13T13:57:33.740460143Z     at new UpdateOneOperation (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/update.js:67:19)
2022-09-13T13:57:33.740461947Z     at Collection.updateOne (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:168:90)
2022-09-13T13:57:33.740463620Z     at Proxy.updateOne (server/models/raw/BaseRaw.ts:199:20)
2022-09-13T13:57:33.740465213Z     at app/settings/server/SettingsRegistry.ts:176:22
2022-09-13T13:57:33.740466786Z     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2022-09-13T13:57:33.740468459Z  => awaited here:
2022-09-13T13:57:33.740470363Z     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
2022-09-13T13:57:33.740472066Z     at app/settings/server/index.ts:16:17
2022-09-13T13:57:33.740473649Z     at SettingsRegistry.add (app/settings/server/Middleware.ts:12:10)
2022-09-13T13:57:33.740475212Z     at Object.add (app/settings/server/SettingsRegistry.ts:231:10)
2022-09-13T13:57:33.740476805Z     at Object.<anonymous> (app/lib/server/startup/settings.ts:1740:8)
2022-09-13T13:57:33.740478518Z     at Object.section (app/settings/server/SettingsRegistry.ts:246:8)
2022-09-13T13:57:33.740480121Z     at Object.<anonymous> (app/lib/server/startup/settings.ts:1734:7)
2022-09-13T13:57:33.740481764Z     at app/settings/server/SettingsRegistry.ts:257:8
2022-09-13T13:57:33.740483357Z     at app/settings/server/SettingsRegistry.ts:264:10
2022-09-13T13:57:33.740484930Z     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2022-09-13T13:57:33.740496412Z  => awaited here:
2022-09-13T13:57:33.740498105Z     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
2022-09-13T13:57:33.740499848Z     at app/settings/server/index.ts:20:17
2022-09-13T13:57:33.740501471Z     at SettingsRegistry.addGroup (app/settings/server/Middleware.ts:12:10)
2022-09-13T13:57:33.740503094Z     at module (app/lib/server/startup/settings.ts:1682:18)
2022-09-13T13:57:33.740504657Z     at fileEvaluate (packages/modules-runtime.js:336:7)
2022-09-13T13:57:33.740506340Z     at Module.require (packages/modules-runtime.js:238:14)
2022-09-13T13:57:33.740508494Z     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
2022-09-13T13:57:33.740510258Z     at module (/app/bundle/programs/server/app/app.js:235355:8)
2022-09-13T13:57:33.740511851Z     at fileEvaluate (packages/modules-runtime.js:336:7)
2022-09-13T13:57:33.740513393Z     at Module.require (packages/modules-runtime.js:238:14)
2022-09-13T13:57:33.740514956Z     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
2022-09-13T13:57:33.740516640Z     at module (server/importPackages.ts:16:8)
2022-09-13T13:57:33.740518182Z     at fileEvaluate (packages/modules-runtime.js:336:7)
2022-09-13T13:57:33.740519725Z     at Module.require (packages/modules-runtime.js:238:14)
2022-09-13T13:57:33.740521248Z     at require (packages/modules-runtime.js:258:21)
2022-09-13T13:57:33.740522761Z     at /app/bundle/programs/server/app/app.js:1477288:15
2022-09-13T13:57:33.740524334Z     at /app/bundle/programs/server/boot.js:401:38
2022-09-13T13:57:33.740525917Z     at Array.forEach (<anonymous>)
2022-09-13T13:57:33.740527530Z     at /app/bundle/programs/server/boot.js:226:21
2022-09-13T13:57:33.740529063Z     at /app/bundle/programs/server/boot.js:464:7
2022-09-13T13:57:33.740530596Z     at Function.run (/app/bundle/programs/server/profile.js:280:14)
2022-09-13T13:57:33.740532189Z     at /app/bundle/programs/server/boot.js:463:13
```

**Comment by korneil** [comment]
A hack temporarily: disabling prometheus scraping (`prometheusScraping.enabed` to `false` in helm config) solved it for me. Scraping causes `OVERWRITE_SETTING_Prometheus_Enabled` and `OVERWRITE_SETTING_Prometheus_Port` environment variables set which then triggers the spooky mongo update when initializing settings.

**Comment by dudanogueira** [comment]
Hi @hakerakn ! Thanks for pointing it out!

@debdutdeb has just sent a PR for that. Nice catch!

**Comment by debdutdeb** [comment]
Good catch @korneil !
The best workaround for now is to unset **all** `OVERWRITE_SETTING` environment variables.
