### ISSUE TITLE
Status is not updating

### ISSUE THREAD

**Issue by makleng8895** [RocketChat/Rocket.Chat#26820]
When the status "Online" is clicked, the status does not update. The same is true with other statuses.

Video reference: https://watch.screencastify.com/v/Oz6Wzlgdf3fFs3agOYUp

**Comment by HrHeun** [comment]
I'm experiencing the same/similar problem on my server with the difference that when you refresh the page you see the changed status.
It looks like the status is changed on the server but not displayed until you refresh the page.

**Comment by debdutdeb** [comment]
Please fill the issue template - we can't help without having the full background =)

**Comment by Derpeta** [comment]
### Description:

Same issue. When updating by hand nothing happens. The mobile app does go to offline <> online.

### Steps to reproduce:

1. Set status >> nothing happens

### Expected behavior:

STatus changes to selected status

### Actual behavior:

Nothing happens

### Server Setup Information:

- 5.1.1
- Operating System: Ubuntu 
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: V14.19.3
- MongoDB Version: 4.4.10

### Client Setup Information

- Desktop App: 3.8.9
- Operating System: Windows 

### Relevant logs:

{"level":35,"time":"2022-09-08T14:45:18.159Z","pid":9,"hostname":"meep","name":"API","method":"POST","url":"/api/v1/users.setStatus","userId":"meep","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.9 Chrome/98.0.4758.141 Electron/17.4.11 Safari/537.36","length":"32","host":"meep.url","referer":"meep.url","remoteIP":"0.0.0.0","err":{"type":"errorClass","message":"Change status is not allowed [error-not-allowed]","stack":"Error: Change status is not allowed [error-not-allowed]<br>    at Object.post (app/api/server/v1/users.ts:994:11)<br>    at app/api/server/api.js:463:96<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)<br>    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:463:39)<br>    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)<br>    at packages/rocketchat_restivus/lib/route.coffee:59:33<br>    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":"error-not-allowed","reason":"Change status is not allowed","details":{"method":"users.setStatus"},"errorType":"Meteor.Error"},"status":400,"responseTime":5,"msg":"Change status is not allowed [error-not-allowed]"}

**Comment by yasemincidem** [comment]
I tried to reproduce issue on my local. It seems to be working. Can you check if it works on your side now ?

**Comment by SchaeVHS** [comment]
I can confirm this.

There is a POST request to `POST https://xxxxx/api/v1/users.setStatus`,
with a json content of
```
{"status":"busy","message":""}
```

The answer is:

```
{
"success":false,
"error":"Change status is not allowed [error-not-allowed]",
"errorType":"error-not-allowed",
"details":{"method":"users.setStatus"}
}
```

My permission settings deny custom status (aka `Accounts_AllowUserStatusMessageChange`).
This seems to trigger the bug in https://github.com/RocketChat/Rocket.Chat/blob/f0c37c5a8c904181577b80d239255284ac6a1280/apps/meteor/app/user-status/server/methods/setUserStatus.js#L22

**Comment by HrHeun** [comment]
I did some further testing about this issue.
I previously ran multiple instances which seems to get an enterprise only feature in the future (https://docs.rocket.chat/quick-start/scaling-rocket.chat/running-multiple-instances note the Enterprise Tag).
So I switched back to one instance, but the refresh problem still occurred.

Then I removed the replicaSet information in the env-variables for mongo and now everything seems to work as intended.

Are multiple instances still a working community feature? The broadcast-message in #26830 is a bot worrying.

**Comment by pauloriply** [comment]
> I did some further testing about this issue. I previously ran multiple instances which seems to get an enterprise-only feature in the future (https://docs.rocket.chat/quick-start/scaling-rocket.chat/running-multiple-instances note the Enterprise Tag). So I switched back to one instance, but the refresh problem still occurred.
> 
> Then I removed the replicaSet information in the env-variables for mongo and now everything seems to work as intended.
> 
> Are multiple instances still a working community feature? The broadcast-message in #26830 is a bit worrying.

For what you removed replicaSet from connection string?
I see strange behaviour after we delete one of two instance of rocket chat (because it’s Enterprise feature only) and have not idea why(
