### ISSUE TITLE
Livechat WIdget API error in pageVisited Method

### ISSUE THREAD

**Issue by billynoah** [RocketChat/Rocket.Chat#26902]
### Description:

`pageVisited()` API method fires on page load but throw a TypeError since `rid` is not defined if there is not yet an existing chat.

```
hooks.js:37 Uncaught TypeError: Cannot read properties of null (reading '_id')
    at pageVisited (hooks.js:37:26)
    at Hn (hooks.js:185:23)
```

Relevant code:
```
pageVisited(info) {
	if (info.change === 'url') {
		Triggers.processRequest(info);
	}

	const { token, room: { _id: rid } = {} } = store.state;
	const { change, title, location: { href } } = info;

	Livechat.sendVisitorNavigation({ token, rid, pageInfo: { change, title, location: { href } } });
}
```

### Steps to reproduce:
1. Copy / Paste livechat widget js onto a webpage.
2. Load the page.

### Expected behavior:

In the past `pageVisted()` would fire on page load and when a customer initiates a new chat, the chat agent can see the originating page. 

### Actual behavior:

Now this code is broken so livechat agent can't see the url of the page where chat is initiated unless the customer navigates *after* a chat has been created.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.2
- Operating System: Ubuntu 20.04.5
- Deployment Method: Manual
- Number of Running Instances: 1
- DB Replicaset Oplog: n/a
- NodeJS Version: 14.19.3
- MongoDB Version: 5.0.12

### Client Setup Information

- Desktop App or Browser Version: n/a - applies to all tested browsers
- Operating System: n/a - applies to all

**Comment by paulhibbitts** [comment]
+1
