### ISSUE TITLE
5.1.2 Failing with Meteor.Error & Server selection timed out 

### ISSUE THREAD

**Issue by whitetiger264** [RocketChat/Rocket.Chat#26903]
I Installed the latest 5.1.2 on a brand new Rocky Linux 8 VPS and I am running into issues with `Meteor.Error` and also `Server selection timed out after 30000 ms`. 

- Version of Rocket.Chat Server: 5.1.2
- Operating System: Rocky Linux 8
- Deployment Method: Manual
- Number of Running Instances: 1
- NodeJS Version: 14.18
- MongoDB Version: 4.4

When starting the RC service, I get the following error:

```
Process: 1830 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 1830 (code=exited, status=1/FAILURE)

Sep 20 00:59:11 hostname rocketchat[1830]:     at Function.run (/opt/Rocket.Chat/programs/server/profile.js:280:14)
Sep 20 00:59:11 hostname rocketchat[1830]:     at /opt/Rocket.Chat/programs/server/boot.js:463:13 {
Sep 20 00:59:11 hostname rocketchat[1830]:   isClientSafe: true,
Sep 20 00:59:11 hostname rocketchat[1830]:   error: 'An error occurred when creating an index for collection "users: not primary',
Sep 20 00:59:11 hostname rocketchat[1830]:   reason: undefined,
Sep 20 00:59:11 hostname rocketchat[1830]:   details: undefined,
Sep 20 00:59:11 hostname rocketchat[1830]:   errorType: 'Meteor.Error'
Sep 20 00:59:11 hostname rocketchat[1830]: }
Sep 20 00:59:11 hostname systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Sep 20 00:59:11 hostname systemd[1]: rocketchat.service: Failed with result 'exit-code'.
```

I assume it's failing to create ` creating an index for collection "users: not primary"` because of the `Server selection timed out after 30000 ms` error. According to past comments, we should add the `&directConnection=true` to the `MONGO_URL` and `MONGO_OPLOG_URL` URL strings, which I have done. Yet it seems to continue with the time out. 

See here:

```
[root@hostname home]# node /opt/Rocket.Chat/main.js
/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^

MongoServerSelectionError: Server selection timed out after 30000 ms
    at Timeout._onTimeout (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'localhost:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'localhost', port: 27017 },
        address: 'localhost:27017',
        type: 'RSGhost',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 9,
        roundTripTime: 26.12,
        lastUpdateTime: 28982561,
        lastWriteDate: 0,
        topologyVersion: {
          processId: ObjectId { [Symbol(id)]: [Buffer [Uint8Array]] },
          counter: 0
        },
        logicalSessionTimeoutMinutes: 30
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: 9,
    logicalSessionTimeoutMinutes: undefined
  }
}
```

```
[Unit]
Description=RocketChat Server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target mongod.service
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01&directConnection=true MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01&directConnection=true ROOT_URL=http://hostname/ PORT=3000
[Install]
WantedBy=multi-user.target
```

I also followed the recommend solution:

```
cfg = rs.conf()
cfg.members[0].host = "mongo:27017"
rs.reconfig(cfg)
```

But when running these commands I get the following:

```
> cfg = rs.conf()
uncaught exception: Error: Could not retrieve replica set config: {
	"ok" : 0,
	"errmsg" : "no replset config has been received",
	"code" : 94,
	"codeName" : "NotYetInitialized"
} :
rs.conf@src/mongo/shell/utils.js:1656:11
@(shell):1:7
> cfg.members[0].host = "mongodb:27017"
uncaught exception: ReferenceError: cfg is not defined :
@(shell):1:1
> rs.reconfig(cfg)
uncaught exception: ReferenceError: cfg is not defined :
@(shell):1:1
> 
```

And I do not think I understand what said errors mean. And this is my `mongod.conf`:

```
# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# Where and how to store data.
storage:
  dbPath: /var/lib/mongo
  journal:
    enabled: true
  engine: wiredTiger
#  wiredTiger:

# how the process runs
processManagement:
  fork: true  # fork and run in background
  pidFilePath: /var/run/mongodb/mongod.pid  # location of pidfile
  timeZoneInfo: /usr/share/zoneinfo

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1  # Enter 0.0.0.0,:: to bind to all IPv4 and IPv6 addresses or, alternatively, use the net.bindIpAll setting.


#security:

#operationProfiling:

replication:
 replSetName: rs01

#sharding:

## Enterprise-Only Options

#auditLog:

#snmp:
```

What could I be missing here? Any assistance will be appreciated, please.

**Comment by debdutdeb** [comment]
> I also followed the recommend solution:

That is only for our old docker compose users. Not applicable here.

You have not initialized a replicaset. Do so with this command
```js
rs.initiate({
  _id: 'rs01',
  members: [{_id: 0, host: 'localhost:27017'}]
})
```
in the mongo shell

restart rocketchat

**Comment by kjordan2001** [comment]
Also, as a note for anyone with an already initialized rs, it didn't work for me no matter what I tried with any 5 version until I removed replicaSet=rs01 from my URL.

**Comment by TF-R** [comment]
We got the same issue:
````rocketchat01          | errorClass [Error]: [An error occurred when creating an index for collection "users: not primary]
rocketchat01          |     at Collection.createIndex (packages/mongo/collection.js:770:15)
rocketchat01          |     at setupUsersCollection (packages/accounts-base/accounts_server.js:1812:9)
rocketchat01          |     at new AccountsServer (packages/accounts-base/accounts_server.js:74:5)
rocketchat01          |     at packages/accounts-base/server_main.js:7:12
rocketchat01          |     at module (packages/accounts-base/server_main.js:19:1)
rocketchat01          |     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat01          |     at Module.require (packages/modules-runtime.js:238:14)
rocketchat01          |     at require (packages/modules-runtime.js:258:21)
rocketchat01          |     at /app/bundle/programs/server/packages/accounts-base.js:2395:15
rocketchat01          |     at /app/bundle/programs/server/packages/accounts-base.js:2402:3
rocketchat01          |     at /app/bundle/programs/server/boot.js:401:38
rocketchat01          |     at Array.forEach (<anonymous>)
rocketchat01          |     at /app/bundle/programs/server/boot.js:226:21
rocketchat01          |     at /app/bundle/programs/server/boot.js:464:7
rocketchat01          |     at Function.run (/app/bundle/programs/server/profile.js:280:14)
rocketchat01          |     at /app/bundle/programs/server/boot.js:463:13 {
rocketchat01          |   isClientSafe: true,
rocketchat01          |   error: 'An error occurred when creating an index for collection "users: not primary',
rocketchat01          |   reason: undefined,
rocketchat01          |   details: undefined,
rocketchat01          |   errorType: 'Meteor.Error'
rocketchat01          | }
````

None of the mentioned solutions helped us.

**Comment by TF-R** [comment]
removing directConnection=true on MONGO_URL and MONGO_OPLOG_URL resolved the problem for us

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by UsVfxArtia** [comment]
Still same error occurs, used this guide to install in docker 
https://docs.rocket.chat/deploy/prepare-for-your-deployment/rapid-deployment-methods/docker-and-docker-compose
error: 'An error occurred when creating an index for collection "users: Replication is being shut down',

```
2023-04-09 18:37:54 
2023-04-09 18:37:54 /app/bundle/programs/server/node_modules/fibers/future.js:313
2023-04-09 18:37:54                                             throw(ex);
2023-04-09 18:37:54                                             ^
2023-04-09 18:37:54 errorClass [Error]: [An error occurred when creating an index for collection "users: Replication is being shut down]
2023-04-09 18:37:54     at Collection.createIndex (packages/mongo/collection.js:801:15)
2023-04-09 18:37:54     at setupUsersCollection (packages/accounts-base/accounts_server.js:1777:9)
2023-04-09 18:37:54     at new AccountsServer (packages/accounts-base/accounts_server.js:75:5)
2023-04-09 18:37:54     at packages/accounts-base/server_main.js:7:12
2023-04-09 18:37:54     at module (packages/accounts-base/server_main.js:19:31)
2023-04-09 18:37:54     at fileEvaluate (packages/modules-runtime.js:336:7)
2023-04-09 18:37:54     at Module.require (packages/modules-runtime.js:238:14)
2023-04-09 18:37:54     at require (packages/modules-runtime.js:258:21)
2023-04-09 18:37:54     at /app/bundle/programs/server/packages/accounts-base.js:2192:15
2023-04-09 18:37:54     at /app/bundle/programs/server/packages/accounts-base.js:2199:3
2023-04-09 18:37:54     at /app/bundle/programs/server/boot.js:369:38
2023-04-09 18:37:54     at Array.forEach (<anonymous>)
2023-04-09 18:37:54     at /app/bundle/programs/server/boot.js:210:21
2023-04-09 18:37:54     at /app/bundle/programs/server/boot.js:423:7
2023-04-09 18:37:54     at Function.run (/app/bundle/programs/server/profile.js:256:14)
2023-04-09 18:37:54     at /app/bundle/programs/server/boot.js:422:13 {
2023-04-09 18:37:54   isClientSafe: true,
2023-04-09 18:37:54   error: 'An error occurred when creating an index for collection "users: Replication is being shut down',
2023-04-09 18:37:54   reason: undefined,
2023-04-09 18:37:54   details: undefined,
2023-04-09 18:37:54   errorType: 'Meteor.Error'
2023-04-09 18:37:54 }
```

**Comment by andys448** [comment]
Hi! Any news? The problem still occurs in 6.2.4
