### ISSUE TITLE
Exception in setInterval callback: MongoServerSelectionError: connection timed out while Deploying on AWS

### ISSUE THREAD

**Issue by wahdatjan** [RocketChat/Rocket.Chat#26918]
i am deploying the rocketchat on aws ec2 instance . DOcker images are running but when i check the logs i am getting this error

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.3
- Operating System: linux
- Deployment Method: docker
- DB Replicaset Oplog: - MONGO_OPLOG_URL=mongodb://mongo:27017/local
- NodeJS Version: 14.19.3 - x64
- MongoDB Version:4.0.28

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:
` Exception in setInterval callback: MongoServerSelectionError: connection closed
rocketchat_1          |     at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
rocketchat_1          |     at listOnTimeout (internal/timers.js:557:17)
rocketchat_1          |     at processTimers (internal/timers.js:500:7) {
rocketchat_1          |   reason: TopologyDescription {
rocketchat_1          |     type: 'ReplicaSetNoPrimary',
rocketchat_1          |     servers: Map(1) { 'mongo:27017' => [ServerDescription] },
rocketchat_1          |     stale: false,
rocketchat_1          |     compatible: true,
rocketchat_1          |     heartbeatFrequencyMS: 10000,
rocketchat_1          |     localThresholdMS: 15,
rocketchat_1          |     setName: 'rs0',
rocketchat_1          |     maxSetVersion: 2,
rocketchat_1          |     maxElectionId: new ObjectId("7fffffff0000000000000005"),
rocketchat_1          |     commonWireVersion: 7,
rocketchat_1          |     logicalSessionTimeoutMinutes: undefined
rocketchat_1          |   }
rocketchat_1          | }
`

**Comment by dudanogueira** [comment]
Hi! Did you followed this doc?
https://docs.rocket.chat/quick-start/deploying-rocket.chat/cloud-deployments/aws

if positive, it's outdated :grimacing: We will fix this any time soon.
Please, follow this doc for the updated docker compose version:
https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/docker-and-docker-compose
