### ISSUE TITLE
add user by invite link to team is broken

### ISSUE THREAD

**Issue by photoninger** [RocketChat/Rocket.Chat#27057]
### Description:

If I add users by invite link to a team:
1. They don't autojoin in team channels which are marked with "autojoin"
2. They cannot see the public channels of the team in "Team Channels"
3. They are only member of the team itself
4. The team owner cannot remove them: error not a member
5. After adding the user via "add member" it can be removed again by the team owner

### Steps to reproduce:

1. Create new team
2. Add channels to team an set them to autojoin
3. Create invite link for team
4. Send invite link to some users
5. User click on invite link and join team
6. As team owner check channels if new members have autojoined
7. As team owner try to remove users which joined by invite link

### Expected behavior:

- users who join by invite link are properly added to the team and autojoin to teams channels

### Actual behavior:

- users who join by invite link are only added to team itself but not to autojoin channels
- users who join by invite link are not properly added as members to team
- team owner cannot remove these users without doing an "add member" for these users

### Server Setup Information:

- Version of Rocket.Chat Server: 4.8.6
- Operating System: Debian 10
- Deployment Method: ansible playbook
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.18.3
- MongoDB Version: 5.0.12 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome 106, Safari 16
- Operating System: MacOS 12

### Relevant logs:
```
Oct 12 10:30:13 myrocketchatserver RocketChat[792]: {"level":35,"time":"2022-10-12T08:30:13.603Z","pid":792,"hostname":"myrocketchatserver","name":"API","method":"GET","url":"/api/v1/teams.listRooms?teamId=63467a35ba21730318f10f87&offset=0&count=25&filter=&type=all","userId":"De2EYaEGdvgckJc6m","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","host":"myrocketchatserver.example.com:443","referer":"https://myrocketchatserver.example.com/group/team_mit_invite_link/team-channels","remoteIP":"2001:DB8::1","err":{"type":"Error","message":"user-not-on-private-team","stack":"Error: user-not-on-private-team\n    at server/services/team/service.ts:524:10\n    at /var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/sdk/lib/LocalBroker.ts:15:15\n    at /var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/v1/teams.ts:304:10\n    at /var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/api.js:431:75\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:431:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9"},"status":400,"responseTime":10,"msg":"user-not-on-private-team"}

Oct 12 10:30:16 myrocketchatserver RocketChat[781]: {"level":35,"time":"2022-10-12T08:30:16.224Z","pid":781,"hostname":"myrocketchatserver","name":"API","method":"GET","url":"/api/v1/teams.listRooms?teamId=63467a35ba21730318f10f87&offset=0&count=25&filter=&type=autoJoin","userId":"De2EYaEGdvgckJc6m","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","host":"myrocketchatserver.example.com:443","referer":"https://myrocketchatserver.example.com/group/team_mit_invite_link/team-channels","remoteIP":"2001:DB8::1","err":{"type":"Error","message":"user-not-on-private-team","stack":"Error: user-not-on-private-team\n    at server/services/team/service.ts:524:10\n    at /var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/sdk/lib/LocalBroker.ts:15:15\n    at /var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/v1/teams.ts:304:10\n    at /var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/api.js:431:75\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:431:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9"},"status":400,"responseTime":6,"msg":"user-not-on-private-team"}

Oct 12 10:30:47 myrocketchatserver RocketChat[781]: {"level":35,"time":"2022-10-12T08:30:47.739Z","pid":781,"hostname":"myrocketchatserver","name":"API","method":"POST","url":"/api/v1/teams.removeMember","userId":"y8huP9Y6aeb9iRbjT","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","length":"66","host":"myrocketchatserver.example.com:443","referer":"https://myrocketchatserver.example.com/group/team_mit_invite_link/members-list","remoteIP":"2001:DB8::1","err":{"type":"Error","message":"member-does-not-exist","stack":"Error: member-does-not-exist\n    at server/services/team/service.ts:743:11\n    at /var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/sdk/lib/LocalBroker.ts:15:15\n    at /var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/v1/teams.ts:509:8\n    at /var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/api.js:431:75\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:431:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9"},"status":400,"responseTime":21,"msg":"member-does-not-exist"}
```

**Comment by dudanogueira** [comment]
Hi! Thanks for pointing it out.

Are you able to reproduce this on latest 5.X version?

A lot has changed since 4.X due the refactoring, so this may be fixed already.

If you want help on testing on later environments, or want to help tests, we hang out here: https://open.rocket.chat/channel/beta-testers

**Comment by photoninger** [comment]
I tested with the new 5.2.0 release. Issue is gone. 😄
