### ISSUE TITLE
migration v254 warns: Error creating index: users -> { bio: 1 } { unique: 1 } MongoError: E11000 duplicate key error collection: rocketchat.users index: bio_1 dup key: { bio: null }

### ISSUE THREAD

**Issue by fuminori-ido-m** [RocketChat/Rocket.Chat#27064]
### Description:

migration v254 warns  'users.bio' uniqueness validation error as follows:

> {"level":51,"time":"2022-10-13T02:25:57.056Z","pid":1,"hostname":"MYHOST","name":"Migrations","msg":"Running up() on version 254"}
> Error creating index: users -> { bio: 1 } { unique: 1 } MongoError: E11000 duplicate key error collection: rocketchat.users index: bio_1 dup key: { bio: null }
>     at MessageStream.messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
> ...
>     at TCP.callbackTrampoline (internal/async_hooks.js:130:17) {
>   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 87, high_: 1665627957 },
>   ok: 0,
>   code: 11000,
>   codeName: 'DuplicateKey',
>   keyPattern: { bio: 1 },
>   keyValue: { bio: null },
>   '$clusterTime': {
>     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 87, high_: 1665627957 },
>     signature: { hash: [Binary], keyId: 0 }
>   }
> }
> 

This happens at the following fragment of apps/meteor/server/startup/migrations/v254.ts :

`Users.tryEnsureIndex({ bio: 1 }, { unique: 1 });`

What 'warn' means here is that index creation is failed while the error is ignored (by **try**EnsureIndex).

### Steps to reproduce:

1. prepare rocketchat < v4.4.1
2. create two users from browser with empty `bio` field.
3. migrate it >= v4.4.1

### Expected behavior:

migration finishes without any error.

(If bio is allowed to be duplicate, `unique: 1` option should not be used.)

### Actual behavior:

migration warns the createIndex error, but ignore it.  This means no index on 'users.bio' key.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.7
- Operating System: Debian ( docker image 3.18.7 )
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.23

### Client Setup Information

- Desktop App or Browser Version: n/a
- Operating System: n/a

### Relevant logs:

(please see Description section)

**Comment by LeeThompson** [comment]
Just had this same error, migrating from 4.2.4 to 4.4.5.

### Description:
During database migration, an exception occurred as reported by the original poster of this issue.

### Steps to reproduce:
See original post.

### Actual behavior:
See Logs.

### Server Setup Information:
- Version of Rocket.Chat Server: 4.4.5
- Operating System: Synology DSM (Debian)
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 14.18.2
- MongoDB Version: 4.4.6

### Client Setup Information

- Desktop App or Browser Version: N/A
- Operating System: N/A

### Relevant logs:
```
2023-05-30T05:42:48.414Z 51 pid=1 hostname=RocketChat name=Migrations msg=Running up() on version 254
Error creating index: users -> { bio: 1 } { unique: 1 } MongoError: Index build failed: 2b46d23e-1a3b-4506-a38f-932fa8efa439: Collection rocketchat.users ( 5a178528-5e89-4ab2-a54d-8491528d7890 ) :: caused by :: E11000 duplicate key error collection: rocketchat.users index: bio_1 dup key: { bio: null }
    at MessageStream.messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
    at MessageStream.emit (events.js:400:28)
    at MessageStream.emit (domain.js:475:12)
    at processIncomingData (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:731:22)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1685425370 },
  ok: 0,
  code: 11000,
  codeName: 'DuplicateKey',
  keyPattern: { bio: 1 },
  keyValue: { bio: null },
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1685425370 },
    signature: { hash: [Binary], keyId: 0 }
  }
}
2023-05-30T05:42:51.576Z 51 pid=1 hostname=RocketChat name=Migrations msg=Finished migrating.
```

**Comment by KevLehman** [comment]
This should be fixed, thx!
