### ISSUE TITLE
Update 4.8.6 --> 5.0.0: MongoParseError: option replset is not supported

### ISSUE THREAD

**Issue by kultpro** [RocketChat/Rocket.Chat#27253]
Update 4.8.6 --> 5.0.0
MongoDB version - 4.2 or 4.4

`Rocket.Chat Version: 4.8.6                     |
|       NodeJS Version: 14.18.3 - x64             |
|      MongoDB Version: 4.2.22                    |
|       MongoDB Engine: wiredTiger                |
|             Platform: linux                     |
|         Process Port: 3000                      |
|             Site URL: ...  |
|     ReplicaSet OpLog: Enabled                   |
|          Commit Hash: cf131d1657                |
|        Commit Branch: HEAD`

The problem is that updating rocketcat to version 4.8.6 was fine, but on version 5.0.0 I get errors

`~]# docker logs -f rocketchat
/app/bundle/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

MongoParseError: option replset is not supported
    at parseOptions (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/connection_string.js:289:15)
    at new MongoClient (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:62:63)
    at new MongoConnection (packages/mongo/mongo_driver.js:184:3)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:37:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Collection (packages/mongo/collection.js:106:40)
    at new AccountsCommon (packages/accounts-base/accounts_common.js:41:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:29:5)
    at packages/accounts-base/server_main.js:7:12
    at module (packages/accounts-base/server_main.js:19:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /app/bundle/programs/server/packages/accounts-base.js:2395:15
    at /app/bundle/programs/server/packages/accounts-base.js:2402:3
`

Rocketcat is in docker, but mongo is not. I have been fighting for many days, the reason is not clear to me. I studied the documentation, experimented.. Help please.

**Comment by 3x3cut0r** [comment]
Hi,
i had the same error. it has been renamed to 'replicaSet'. you need to change your URLs:
MONGO_URL: 'mongodb://mongo:27017/rocketchat?replicaSet=rs0'
MONGO_OPLOG_URL: 'mongodb://mongo:27017/local?replicaSet=rs0'

**Comment by kultpro** [comment]
> Hi,

Thanks, I'll check it out
