### ISSUE TITLE
Direct Reply broken (again)

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#27268]
### Description:

Hello Devs.

Direct reply via email was working at least until version 5.1.x. Now with 5.3.1 running I noticed it's broken again. Configuration is the same as with the working rocketchat version. It seems login to the IMAP Server (Dovecot) only works partially.

```
Nov 15 11:37:01 imap-login: Info: Login: user=<rocketchat>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=2536, TLS, session=<hDKw73/tHux/AAAB>
Nov 15 11:37:06 imap-login: Info: Disconnected: Connection closed (no auth attempts in 5 secs): user=<>, rip=127.0.0.1, lip=127.0.0.1, TLS: Connection closed, session=<e1D873/tHOx/AAAB>
Nov 15 11:37:06 imap(rocketchat)<2536><hDKw73/tHux/AAAB>: Info: Disconnected: Logged out in=117 out=1417 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
```

As you can see, the second login attempt is the username missing.

Rocketchat Log looks like this:

```
{"level":50,"time":"2022-11-15T17:52:50.902Z","pid":4759,"hostname":"pages","name":"EmailInbox","err":{"type":"Error","message":"Timed out while authenticating with server","stack":"Error: Timed out while authenticating with server\n    at Timeout._onTimeout (/opt/rocketchat-5.3.1/programs/server/npm/node_modules/imap/lib/Connection.js:139:17)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)","source":"timeout-auth"},"msg":"Timed out while authenticating with server"}
{"level":50,"time":"2022-11-15T17:52:50.907Z","pid":4759,"hostname":"pages","name":"EmailInbox","msg":"IMAP error: Timed out while authenticating with server"}
```

I'm here if you need any more infos.

### Steps to reproduce:

1. Enable Direct Reply
2. Answer to an notifiaction email via email
3. Email is not processed by rocketchat

### Expected behavior:

Email content goes to the rocketchat channel.

### Actual behavior:

It doesn't.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 14.21.1
- MongoDB Version: 5.05

**Comment by Abhi149209** [comment]
I can solve the issue @himpierre  please assign me

**Comment by himpierre** [comment]
When the Tooth Fairy grants me a wish, I ask her to allow me to assign tickets here. :)

Am 24. November 2022 20:45:58 MEZ schrieb Abhinav sahai ***@***.***>:
>I can solve the issue @himpierre  please assign me 
>

**Comment by Abhi149209** [comment]
@ggazzo can you assign me

**Comment by ggazzo** [comment]
no @Abhi149209 I can't :). we dont assign people outside the corp, because we dont want to prevent others to try

but dont worry you can still work on this problem and solve the issue

**Comment by himpierre** [comment]
Hello Y'all.

This seems to be still broken. Would be nice to have that running again!

cheers! t.
