### ISSUE TITLE
Issue upgrading from 23 to 24

### ISSUE THREAD

**Issue by jkdale** [RocketChat/Rocket.Chat#2729]
Your Rocket.Chat version: upgrading from v23 to v24

I was upgrading from a new install of v23 to v24 and I am seeing an issue upgrading.

After starting the new version, I see these in the log:

```
Updating process.env.MAIL_URL
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Github
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Github_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Github_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Github_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Gitlab
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Gitlab_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Gitlab_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Gitlab_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Google
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Google_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Google_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Google_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin_secret
rocketchat_lib oAurocketchat_lib oAurocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Meteor
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Meteor_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Meteor_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Meteor_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_secret
rocketchat_cas cas_rocketchat.js:48 CAS ➔ info Disabling CAS login service
sync.js:193 LDAPSync ➔ info Enabling LDAP user sync
{"line":"114","file":"migrations.js","message":"Migrations: Migrating from version 34 -> 35","time":{"$date":1459480493388},"level":"info"}
{"line":"114","file":"migrations.js","message":"Migrations: Running up() on version 35","time":{"$date":1459480493393},"level":"info"}
rocketchat_theme server.coffee:102 rocketchat:theme ➔ stop_rendering 1567
rocketchat_theme server.coffee:102 rocketchat:theme ➔ stop_rendering 1358
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook
steffo_meteor-accounts-saml saml_rocketchat.coffee:29 steffo:meteor-accounts-saml ➔ updated SAML_Custom_Default
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise_callback_url
{"line":"114","file":"migrations.js","message":"Migrations: Finished migrating.","time":{"$date":1459480496524},"level":"info"}
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Github
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Github_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Github_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Github_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Gitlab
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Gitlab_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Gitlab_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Gitlab_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Google
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Google_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Google_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Google_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Meteor
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Meteor_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Meteor_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Meteor_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter_secret
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_callback_url
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_id
rocketchat_lib oAuthServicesUpdate.coffee:13 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Wordpress_secret
Not migrating, control is locked. Attempt 1/30. Trying again in 10 seconds.
{"line":"114","file":"migrations.js","message":"Migrations: Not migrating, already at version 35","time":{"$date":1459480506567},"level":"info"}
sync.js:193 LDAPSync ➔ info Enabling LDAP user sync
Updating process.env.MAIL_URL
sync.js:193 LDAPSync ➔ info Enabling LDAP user sync
[methods] addSamlService -> userId: null , arguments:  { '0': 'Default' }
configuring push
Using GridFS for Avatar storage
Exception in defer callback: MongoError: E11000 duplicate key error collection: rocketchat.rocketchat_room index: name_1 dup key: { : "general" }
    at Object.Future.wait (/var/www/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)
    at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
    at [object Object].MongoConnection.(anonymous function) [as insert] (packages/mongo/mongo_driver.js:736:1)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:48:1)
    at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
    at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)
    at _Class.RocketChat.models._Base._Class.insert (packages/rocketchat_lib/server/models/_Base.coffee:17:24)
    at _Class.RocketChat.models.Rooms._Class.createWithIdTypeAndName (packages/rocketchat_lib/server/models/Rooms.coffee:404:4)
    at server/startup/initialData.coffee:5:28
    - - - - -
    at Object.toError (/var/www/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /var/www/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:116:29
    at /var/www/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7
    at /var/www/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/var/www/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /var/www/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/var/www/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/var/www/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/var/www/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
[publish] null -> userId: null , arguments:  {}
streamBroadcast.coffee:16 StreamBroadcast ➔ info startStreamBroadcast
{"line":"71","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"Generate and save statistics\" next run @Thu Mar 31 2016 22:15:08 GMT-0500 (CDT)","time":{"$date":1459480508095},"level":"info"}
➔ serverRunning.coffee:9 System ➔ startup
➔ +---------------------------------------+
➔ |             SERVER RUNNING            |
➔ +---------------------------------------+
➔ |                                       |
➔ |       Version: 0.24.0                 |
➔ |  Process Port: 3000                   |
➔ |      Site URL: https://rc.XXXXXX.com  |
➔ |                                       |
➔ +---------------------------------------+
rocketchat_cas cas_rocketchat.js:48 CAS ➔ info Disabling CAS login service
steffo_meteor-accounts-saml saml_rocketchat.coffee:29 steffo:meteor-accounts-saml ➔ updated SAML_Custom_Default
ldap.js:44 LDAP ➔ Connection.info Init setup
ldap.js:82 LDAP ➔ Connection.info Connecting ldap://XXXXXX.com:389
ldap.js:126 LDAP ➔ Connection.info LDAP connected
ldap.js:206 LDAP ➔ Bind.info Binding admin user ldap_search@XXXXXX.com
ldap.js:264 LDAP ➔ Search.info Searching by id 5628ddce1798404ebc0b1f2552d6e917
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id 421e4cd53d91e3449b0fa2df7ec230e1
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id e8f9f0465c1be44d9595db0c1765d863
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id 56e0012db38f634a94c0aa1adacd483d
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id 0cbdfc5191469e4fa74555f8327d37ef
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id d6a647614a54b844b6f90bfed9450f92
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id 60dc88bc226d624dbf408596b6444ba0
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id b33b6e6ede4ded42b3351dfa3266e618
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id 40690baf3da4b041b63bd722a95ab098
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id 932e860ae2b7d24a999bbfe9602e9987
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id b85769ead6e7294baf83852275357808
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id 19b01100482bcb48bf31c6c44a3326ed
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id 75283ce9dcd54648bc3fde86f122df6e
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id e29d124a3cc8aa44b4421841f0406e7e
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id 58076b5a8dd57642b1ba232f7e5b6768
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:264 LDAP ➔ Search.info Searching by id 05eb9454b8123e479dcf196644193c57
ldap.js:335 LDAP ➔ Search.info Search result count 1
sync.js:113 LDAPSync ➔ info Syncing user data
ldap.js:362 LDAP ➔ Connection.info Disconecting
```

The server is up and running though. If I look in mongo, I see:

```db.migrations.find().pretty()
{
	"_id" : "control",
	"version" : 35,
	"locked" : false,
	"lockedAt" : ISODate("2016-04-01T03:15:06.535Z"),
	"buildAt" : "2016-03-28T19:30:41.202Z"
}
```

Then I kill RocketChat and try to start it again and I am plagued with:

Not migrating, control is locked. Attempt 3/30. Trying again in 10 seconds.

Any ideas whats going on here?

**Comment by engelgabriel** [comment]
Why do you kill RocketChat if it is up and running?

**Comment by jkdale** [comment]
Normally I run RocketChat as a system service, in this case I was just running it through "node main.js".

**Comment by engelgabriel** [comment]
Looks like you are running it multiple times?

**Comment by engelgabriel** [comment]
have  you ever delete the general room and recreated after?

**Comment by jkdale** [comment]
I ran the upgrade with node main.js (as I like to see the output directly). Then I killed the app in the console. After I saw my web client fail to connect, I tried to start the service.

I have not ever deleted General either. We actually just started in the last week with RocketChat and were trying it out on v23.

**Comment by rodrigok** [comment]
@jkdale Can you see if there is a room with `name: 'general'` in your mongodb? If yes, can you paste the room record here?

**Comment by jkdale** [comment]
db.rocketchat_room.find({"name":"general"}).pretty()
{
	"_id" : "LpAJSiKTPLSNxPPDp",
	"name" : "general",
	"t" : "c",
	"usernames" : [
		"jack_d",
		"matt_l"
	],
	"msgs" : 225,
	"u" : {
		"_id" : "ee5T8nFSKHzmHRAJa",
		"username" : "matt_l"
	},
	"ts" : ISODate("2016-03-26T03:11:37.074Z"),
	"lm" : ISODate("2016-04-01T19:10:37.445Z"),
	"default" : true
}

**Comment by engelgabriel** [comment]
you will have to rename this room and restart the server for the original general room to be recreated.

**Comment by jkdale** [comment]
I still have issues after doing this. I cannot get the application to start smoothly after migrating. 

It just sits in a long repeating cycle doing these:
Not migrating, control is locked. Attempt 3/30. Trying again in 10 seconds.
Not migrating, control is locked. Attempt 4/30. Trying again in 10 seconds.
Not migrating, control is locked. Attempt 5/30. Trying again in 10 seconds.
Not migrating, control is locked. Attempt 6/30. Trying again in 10 seconds.

**Comment by engelgabriel** [comment]
Did you restart the "hardware"? are you sure you are not running multiple instances of the Rocket.Chat process?

**Comment by jkdale** [comment]
This is a hardware stop / start. After the server comes back online, the RocketChat app cannot be launched.

**Comment by engelgabriel** [comment]
Did you rename the general room and restarted the server? Can you paste the full logs here?

**Comment by jkdale** [comment]
We figured it out. It was user error. Our service that we have that runs RocketChat was pointed at another instance of the app on the machine, so I was upgrading the wrong location. Sorry for the mix up and appreciate the support.
