### ISSUE TITLE
Blank Grey Screen in Group / Channel using Chrome

### ISSUE THREAD

**Issue by christoboucher** [RocketChat/Rocket.Chat#27381]
### Description:

Get a Blank Grey Screen Intermittently when in a Channel / Group
Similar to Issue 27294.
Also started happening when upgraded to v5.3.0

### Steps to reproduce:

1. login to rocketchat
2. click the hamburger in the top left
3. click any channel
4. Channel will displays fine for a period of time, and then screen goes Blank / Grey Background only

### Expected behavior:

Channel loads and displays able to send and read messages without screen going grey

### Actual behavior:

Channel loads and displays, works fine for a period and then screen goes Blank / Grey Background only

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.3
- Operating System: Ubuntu 20.04.5 LTS - 5.4.0-126-generic
- Deployment Method: docker
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.3
- MongoDB Version:4.4.15 / wiredTiger (oplog Enabled)
- Apps Engine Version: 1.35.0
- Database Migration: 281 (November 28, 2022 12:33)

### Client Setup Information

- Browser Version: Chrome 107.0.5304.121 (Official Build) (64-bit)
- Operating System: Linux Mint 20.3 { Complaints froms user all over our company with different O/S's }

### Relevant logs:

Browser Logs:
`Uncaught (in promise) undefined
83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130 Error: Syntax error, unrecognized expression: .message#TICKET|90a5a210-73c8-469f-b715-3ca4e4068fca|caedfd84-f24e-4974-a652-0143fd15beea
    at ie.error (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:10123)
    at ie.tokenize (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:18741)
    at ie.select (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:19010)
    at Function.ie [as find] (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:3493)
    at y.fn.init.find (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:21596)
    at new y.fn.init (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:22087)
    at y (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1262:1041)
    at u.refreshUnreadMark (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1566:907239)
    at eval (RoomBody.tsx:1:5858)
    at lu (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130:104532)
Fi @ 83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130
83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1148 Uncaught Error: Syntax error, unrecognized expression: .message#TICKET|90a5a210-73c8-469f-b715-3ca4e4068fca|caedfd84-f24e-4974-a652-0143fd15beea
    at ie.error (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:10123)
    at ie.tokenize (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:18741)
    at ie.select (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:19010)
    at Function.ie [as find] (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:3493)
    at y.fn.init.find (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:21596)
    at new y.fn.init (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:22087)
    at y (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1262:1041)
    at u.refreshUnreadMark (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1566:907239)
    at eval (RoomBody.tsx:1:5858)
    at lu (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130:104532)
83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1441 Uncaught (in promise) undefined`
![Rocket Chat Chrome Logs](https://user-images.githubusercontent.com/54264092/204301486-73333d6b-08a3-417a-ab66-98094c49f5b4.png)

**Comment by dudanogueira** [comment]
Hi! Can you reproduce this somehow on a fresh, clean install?

The hard part of catching those issues is reproducing them consistently :(

Do you see any network requests going wrong? Does the error message appear on a specific action/event?

Thanks!

**Comment by christoboucher** [comment]
@dudanogueira I will setup a fresh VM and do Fresh Install of the same version to replicate my Production Server.

Not sure if it will be possible to reproduce this issue consistently as it is not occurring consistently on the production server.

My experience is that this occurs intermittently and has occurred when:

- Logged In, the channel / group is open in the browser and a new message comes into the channel / group. (again, not always)
- Click on the channel / group in the list on the left, channel / group messages appear on the right and then "BLANK GREY SCREEN" (again not always)

In each case, a CTRL+SHFT+R refresh's the page and the channel / group show fine and displays not "BLANK GREY SCREEN"

Will attempt to replicate it and update you on findings.
Thanx!

**Comment by christoboucher** [comment]
Upon further experimentation and test, I was able to reproduce this consistently:

- Search for channel `devtest`
- Click on it and it displays
- Click the BLUE JOIN button bottom right
- BLANK GREY SCREEN.

Does it each time with that channel

Done the same with `development-alerts` channel and there is no BLANK GREY SCREEN.

**Comment by christoboucher** [comment]
Some more information in the discovery.

In the browser console errors, below, there is this `.message#TICKET|be786827-26a2-4568-b7db-7f04bb9a02e1` reference.

```
Error: Syntax error, unrecognized expression: .message#TICKET|be786827-26a2-4568-b7db-7f04bb9a02e1
    at ie.error (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:10123)
    at ie.tokenize (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:18741)
    at ie.select (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:19010)
    at Function.ie [as find] (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:3493)
    at y.fn.init.find (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:21596)
    at new y.fn.init (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:22087)
    at y (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1262:1041)
    at u.refreshUnreadMark (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1566:907239)
    at eval (RoomBody.tsx:1:5858)
    at lu (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130:104532)
Fi @ 83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130
83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130 Uncaught Error: Syntax error, unrecognized expression: .message#TICKET|be786827-26a2-4568-b7db-7f04bb9a02e1
    at ie.error (83abe46b061083047cf3c
[TICKET|be786827-26a2-4568-b7db-7f04bb9a02e1_json.txt](https://github.com/RocketChat/Rocket.Chat/files/10134874/TICKET.be786827-26a2-4568-b7db-7f04bb9a02e1_json.txt)
29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:10123)
    at ie.tokenize (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:18741)
    at ie.select (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:19010)
    at Function.ie [as find] (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:3493)
    at y.fn.init.find (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:21596)
    at new y.fn.init (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1273:22087)
    at y (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1262:1041)
    at u.refreshUnreadMark (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1566:907239)
    at eval (RoomBody.tsx:1:5858)
    at lu (83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130:104532)
83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1441 Uncaught (in promise) undefined
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
```

Thinking there is maybe something in the actual message that is causing this exception, I took a look into the MongoDB to look for a message with that reference and I found it.

I am adding it as an attachment to this post as the JSON is quite long.
[TICKET|be786827-26a2-4568-b7db-7f04bb9a02e1_json.txt](https://github.com/RocketChat/Rocket.Chat/files/10134876/TICKET.be786827-26a2-4568-b7db-7f04bb9a02e1_json.txt)

[TICKET|7101dc1e-e831-4504-9a3c-bad88c5b939a_json.txt](https://github.com/RocketChat/Rocket.Chat/files/10134888/TICKET.7101dc1e-e831-4504-9a3c-bad88c5b939a_json.txt)

Maybe there is something in our messages that is not liked by something that was introduced in v5.3.0.

Your assistance will be greatly appreciated.
Christo

**Comment by charlinm** [comment]
Could this line not be causing the issue (ln 162)?

`$(`.message#${firstUnreadRecord._id}`).addClass('first-unread');`

[readMessages.ts](https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/app/ui-utils/client/lib/readMessages.ts
)
It seems that special characters such as `|` or `/` might no longer be supported in the message_id

I was able to reproduce the blank screen consistently by sending a message to a room using the `/chat.sendMessage` API and specifying the `_id` to include `|` , once the room chat was opened, the screen would go blank.

Once the `|` was removed from the `_id`, the messages would appear as unread and would be marked as read once the room chat was opened.

**Comment by christoboucher** [comment]
We managed to resolve this issue by changing our naming for messages.

When posting messages to rocket chat from our own system, we used "|" to delimate / separate a things in the message ID.

We change from using the "|" to an "_" and this Blank Grey Screen is not re-occuring.

Thanx and Regards
