### ISSUE TITLE
What is the maximum size of the export file?

### ISSUE THREAD

**Issue by Glaih** [RocketChat/Rocket.Chat#27515]
Hello! We are considering moving from slack to rocketchat, but we are faced with the problem of migration. The problem is that the full export from our slack is 54GB (includes emails and attachments). When trying to import, rocketchat throws an error.

```
{“level”:35,“time”:“2022-12-09T14:21:02.492Z”,“pid”:1,“hostname”:“rocketchat”,“name”:“API”,“method”:“GET”,“url”:“/api/v1/getImportFileData”,“userId”:“redacted”,“userAgent”:“Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36”,“host”:“”,“referer”:“redacted”,“remoteIP”:“redacted”,“err”:{“type”:“NodeError”,“message”:“File size (57973054684) is greater than 2 GB”,“stack”:“RangeError [ERR_FS_FILE_TOO_LARGE] [ERR_FS_FILE_TOO_LARGE]: File size (57973054684) is greater than 2 GB
at new NodeError (internal/errors.js:322:7)
at tryCreateBuffer (fs.js:369:13)
at Object.readFileSync (fs.js:405:14)
at new module.exports (/app/bundle/programs/server/npm/node_modules/adm-zip/adm-zip.js:55:37)
at SlackImporter.prepareUsingLocalFile (app/importer-slack/server/importer.js:167:15)
at app/importer/server/methods/getImportFileData.ts:51:36
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at app/api/server/v1/import.ts:85:16
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at app/api/server/api.js:463:75
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
at Object._internalRouteActionHandler [as action] (app/api/server/api.js:463:39)
at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)
at packages/rocketchat_restivus/lib/route.coffee:59:33
at packages/simple_json-routes.js:100:9”,“code”:“ERR_FS_FILE_TOO_LARGE”},“status”:400,“responseTime”:6,“msg”:“File size (57973054684) is greater than 2 GB”}
```

The documentation states that the recommended export file size is 15Mb. What is the maximum size of the export file?

Server Setup Information
Version of Rocket.Chat Server: 5.2.0
Deployment Method: docker
NodeJS Version: 14.19.3
MongoDB Version: 4.4

**Comment by vwbusguy** [comment]
I'm seeing this now.  A 5GB Slack dump still throws this error on import.

**Comment by vwbusguy** [comment]
It looks like it's related to https://github.com/cthackers/adm-zip/issues/537 

Basically, Rocket is using a nodejs library include that can't seem to handle zip files >2GiB and the error is coming from that 3rd party library.
