### ISSUE TITLE
Incomming webhook not working when the word "module" is somewhere in the comments

### ISSUE THREAD

**Issue by stephan-hartmann** [RocketChat/Rocket.Chat#27777]
### Description:

I have created a simple incoming webhook. The script contains a comment with the word "module". When I post messages to the webhook I get the response "success: false". Rocket.Chat logs an error message (see below).
 
### Steps to reproduce:

1. create a simple webhook script
```
     class Script {
       process_incoming_request({request}) {
         return { content: { text: "this is a test" } }
       }
     }
     // this is a module
```
2. Post a messaage to the webhook
`curl -X POST -H 'Content-Type: application/json' "http://localhost:3000/hooks/aaa/bbb" -d '{}'`
3. evaluate the response and the logs

### Expected behavior:

Message "this is a test" is posted to the channel of the webhook.

### Actual behavior:

The respose of the webhook request is `{"success":false}` and no message is posted to the channel.

### Server Setup Information:
Rocket.Chat Version: 6.0.0-develop
NodeJS Version: 14.21.2 - x64
MongoDB Version: 5.0.5
MongoDB Engine: wiredTiger
Platform: darwin
ReplicaSet OpLog: Enabled
Commit Hash: 1fecf0f147
Commit Branch: develop

### Relevant logs:

```
@rocket.chat/meteor:dsv: I20230117-11:05:18.039(1)? [2023-01-17T10:05:17.511Z] ERROR (Integrations/17617 on XXXXXXXX): module is not defined
@rocket.chat/meteor:dsv: I20230117-11:05:18.039(1)?     section: "Incoming WebHook"
@rocket.chat/meteor:dsv: I20230117-11:05:18.039(1)?     integration: ""
@rocket.chat/meteor:dsv: I20230117-11:05:18.040(1)?     script: "!function(module1){var Script=function(){function Script(){}var _proto=Script.prototype;_proto.process_incoming_request=function process_incoming_request(_ref){var request=_ref.request;return{content:{text:\"this is a test\"}}};return Script}()}.call(this,module);"
@rocket.chat/meteor:dsv: I20230117-11:05:18.040(1)?     err: {
@rocket.chat/meteor:dsv: I20230117-11:05:18.040(1)?       "type": "ReferenceError",
@rocket.chat/meteor:dsv: I20230117-11:05:18.043(1)?       "message": "module is not defined",
@rocket.chat/meteor:dsv: I20230117-11:05:18.043(1)?       "stack":
@rocket.chat/meteor:dsv: I20230117-11:05:18.043(1)?           ReferenceError: module is not defined
@rocket.chat/meteor:dsv: I20230117-11:05:18.043(1)?               at script.js:1:193
@rocket.chat/meteor:dsv: I20230117-11:05:18.043(1)?               at Script.runInContext (vm.js:144:12)
@rocket.chat/meteor:dsv: I20230117-11:05:18.043(1)?               at VM.runScript (/Users/xxxxx/src/Rocket.Chat/apps/meteor/node_modules/vm2/lib/vm.js:285:18)
@rocket.chat/meteor:dsv: I20230117-11:05:18.044(1)?               at VM.run (/Users/xxxxx/src/Rocket.Chat/apps/meteor/node_modules/vm2/lib/vm.js:503:16)
@rocket.chat/meteor:dsv: I20230117-11:05:18.047(1)?               at getIntegrationScript (app/integrations/server/api/api.js:78:26)
@rocket.chat/meteor:dsv: I20230117-11:05:18.047(1)?               at Object.executeIntegrationRest (app/integrations/server/api/api.js:175:13)
@rocket.chat/meteor:dsv: I20230117-11:05:18.047(1)?               at app/api/server/api.js:463:96
@rocket.chat/meteor:dsv: I20230117-11:05:18.047(1)?               at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
@rocket.chat/meteor:dsv: I20230117-11:05:18.047(1)?               at Object._internalRouteActionHandler [as action] (app/api/server/api.js:463:39)
@rocket.chat/meteor:dsv: I20230117-11:05:18.047(1)?               at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)
@rocket.chat/meteor:dsv: I20230117-11:05:18.047(1)?     }
@rocket.chat/meteor:dsv: I20230117-11:05:18.050(1)? [2023-01-17T10:05:17.512Z] ERROR (Integrations/17617 on XXXXXXXX):
@rocket.chat/meteor:dsv: I20230117-11:05:18.050(1)?     section: "Incoming WebHook"
@rocket.chat/meteor:dsv: I20230117-11:05:18.050(1)?     statusCode: 400
@rocket.chat/meteor:dsv: I20230117-11:05:18.050(1)?     body: {
@rocket.chat/meteor:dsv: I20230117-11:05:18.050(1)?       "success": false,
@rocket.chat/meteor:dsv: I20230117-11:05:18.050(1)?       "error": "error-evaluating-script"
@rocket.chat/meteor:dsv: I20230117-11:05:18.050(1)?     }
```

**Comment by aryangupta701** [comment]
Hello, I want to work on this issue

**Comment by Prateek462003** [comment]
command (packages/api-client) yarn run build exited (129) --- on yarn build can anybody tell me how to setup. I am using WSL on windows 11
