### ISSUE TITLE
App Crashing when switching to different languages

### ISSUE THREAD

**Issue by AdityaSingh-02** [RocketChat/Rocket.Chat#28307]
### Description:
As we know Rocket.chat offers us with several language features where we can select language on which we are comfortable with,
but there are few languages which are causing app to crash such as ->  bn-Bd, bn-In, hi-IN, ka-GE and others too.

### Steps to reproduce:

1. ...../admin/settings/General 
2. change language to any of  bn-Bd, bn-In, hi-IN, ka-GE 
3. save changes 

### Expected behavior:
The app should change its language 

### Actual behavior:
app crashes

![crash](https://user-images.githubusercontent.com/94185167/223416349-ac28e679-2b96-4f2c-b823-b1c095e16196.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0-develop
- Operating System: Ubuntu
- Deployment Method: snap 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0.5

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dudanogueira** [comment]
Running with docker it have not crashed, but also did not translated while changed to bn-IN

Some more relevant logs:

```
rocketconnect-rocketchat-1  | === UnHandledPromiseRejection ===
rocketconnect-rocketchat-1  | Error: Unknown asset: i18n/bn.i18n.json
rocketconnect-rocketchat-1  |     at getAsset (/app/bundle/programs/server/boot.js:299:21)
rocketconnect-rocketchat-1  |     at Object.getText (/app/bundle/programs/server/boot.js:308:18)
rocketconnect-rocketchat-1  |     at server/routes/i18n.ts:21:30
rocketconnect-rocketchat-1  |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
rocketconnect-rocketchat-1  | ---------------------------------
rocketconnect-rocketchat-1  | Errors like this can cause oplog processing errors.
rocketconnect-rocketchat-1  | Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
rocketconnect-rocketchat-1  | Future node.js versions will automatically exit the process
rocketconnect-rocketchat-1  | =================================
```

**Comment by AdityaSingh-02** [comment]
@dudanogueira languages like hindi(hi-IN) and ka-GE are causing crash and few languages like bn-IN, bn-BD are causing no changes but some logs

**Comment by mirosodja** [comment]
Hi, I have same problem. Server on ubuntu, Rocket.Chat v=5.4.3. I think that if you have language set to once which translation is in file with "-" you have a problem. Btw., I have sl-SI.

**Comment by mirosodja** [comment]
I think, that problem is in line 19 of 'server/routes/i18n.ts' file where is: 

`const { lng } = match.params;`

Some values is assigned to the new variable "lng" and variable name couldn't be with a hyphen ("-"). Well, that's my opinion.

**Comment by juzser** [comment]
I have same problem. Even if the language does not contain `-` 
Rocket.Chat version: 6.1.1.

<img width="915" alt="Screenshot 2023-04-19 at 09 24 57" src="https://user-images.githubusercontent.com/5735071/232950456-e270bda9-63e7-4093-8da5-77879f9c1cbb.png">
