### ISSUE TITLE
Cannot enable app

### ISSUE THREAD

**Issue by dolohow** [RocketChat/Rocket.Chat#28355]
### Description:

I cannot enable applications that were previously installed after upgrade to `6.0.0` from `5.4.4`.
I also had one app developed by my and deployed through `apps-cli`. Furthermore, I uninstalled it and tried to deploy again. When I have marketplace page opened, I see it pops up after successful deployment, however after page refresh, it is gone.

### Steps to reproduce:

1. Upgrade to `6.0.0`
2. Go to marketplace
3. Notice some apps are disabled
4. Try enabling them
5. Nothing happens

### Expected behavior:

Application is enabled or error presented

### Actual behavior:

App is enabled or error is presented.  Could be alert or logs.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v14.21.2
- MongoDB Version: 6.0.4

**Comment by dudanogueira** [comment]
Hi!

For the apps you install via apps-cli, they are now called `private apps`, and can be found at the private apps page: http://localhost:3000/marketplace/private/list

All the previous installed apps should work as expected, even if it exceeds the installed app quota, as they get a grandfathered status (with a * on it)

were you able to catch some logs?

**Comment by grape9292** [comment]
I have the same issue.
After upgrading to `6.0.0` from `5.4.3` all my installed apps don't work. 
I have such an error while enabling them: 

![image](https://user-images.githubusercontent.com/120737593/224648261-45f67b97-5b11-4e1f-bd71-5c372553a9e3.png)

**Comment by dolohow** [comment]
> For the apps you install via apps-cli, they are now called `private apps`, and can be found at the private apps page: http://localhost:3000/marketplace/private/list

The URL is working, however my app is listed as _disabled_, and for sure is enabled, because I can invoke it with slash command.  However, clicking now enable change its status.

> were you able to catch some logs?

I went to Network tab in web console and I have this:
```
POST: https://chat.oskar.team/api/apps/7a8cd36b-5f7b-4177-bd7f-bfc9be908bf8/status
400 bad request
{"success":false,"error":"Cannot read property 'charAt' of undefined"}
```

**Comment by jacotec** [comment]
Same here ... strange that there is no reaction at all from the Rocketchat team after all apps seems to be down for us since 6.0.0.

**Comment by bulkinav** [comment]
I  figured out the reason of problem - the thing is that now only 5 installed applications are available for the free tariff plan. At the same time, I have not seen an announcement about this 'feature'. By the way, a some of other functions have also become available only in a paid subscription.

So, if the application was installed BEFORE the updated to Rocket.Chat 6.0, then this issue occurs. Apparently, the developers incorrectly implemented the migration of previously installed applications to the "Installed" section.

To solve the problem, you just need to delete the current application and install it again.

![Screenshot 2023-03-28 at 11 05 18](https://user-images.githubusercontent.com/1636367/228170419-1d8dad39-c7e2-42e1-a35a-8cea8a1fac0f.jpg)

**Comment by jacotec** [comment]
Thanks @bulkinav ! That did it!

It's really insane ... they take away features with every new build. At some point it's usesless to still call it "Open Source" :-|

Will be time to move back to Element at some point ...

**Comment by eeuak** [comment]
I have the same issue PLUS the issue that I cannot install new apps at all!!

After disabling and finally deleting all apps, when I now click on "Install" on an app in the marketplace, a message "0 of 5 apps currently enabled. - Workspaces on Community Edition can have up to 5 apps enabled.... blabla" appears and the corresponding button "Next" (to install the app) doesn't work. I can click it as many times as I want the app won't install. Of course the other button called "Enable unlimited apps" works as expected and redirects to the Rocket.Chat full version shop page...

**Comment by CorvusGei** [comment]
I have the same problem  with "0 of 5 apps currently enabled...", I can't use the Marketplace in 6.0.0 Community Edition and can't update to the actual 6.1.4 as the docker image is deprecated and I don't want to build the docker image on my own.

**Comment by calebjacobson** [comment]
just upgraded to 6.1.5 using SNAP and also cannot install new apps. getting the "0 of 5 apps currently enabled..." message and "next" does nothing.

**Comment by eeuak** [comment]
Anyone having this issue:

You have to register your RocketChat server online by going to Administration -> Registration. After that you can install 5 apps in the free version. 

It's really unpleasant that no propper error message is shown in many cases when features get removed or need other kind of action to work. The slow forcing of registering and removal of different features makes me question how open source this project is now...

**Comment by RedOne-Guerad** [comment]
> Hi!
> 
> For the apps you install via apps-cli, they are now called `private apps`, and can be found at the private apps page: http://localhost:3000/marketplace/private/list
> 
> All the previous installed apps should work as expected, even if it exceeds the installed app quota, as they get a grandfathered status (with a * on it)
> 
> were you able to catch some logs?
@dudanogueira here is the logs i get when try to install applications from marketplace

`{"level":35,"time":"2023-07-12T16:26:20.099Z","pid":9,"hostname":"rocketchat-1","name":"API","method":"POST","url":"/api/apps/","userId":"LQeCPWitWRqw3aMNj","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","length":"561","host":"MY-COMPANY","referer":"https://MY-COMPANY/","remoteIP":"MY IP","err":{"type":"TypeError","message":"\"pkcs8\" must be PKCS#8 formatted string","stack":"TypeError: \"pkcs8\" must be PKCS#8 formatted string\n    at Object.importPKCS8 (/app/bundle/programs/server/npm/node_modules/jose/dist/node/cjs/key/import.js:102:15)\n    at AppSignatureManager.<anonymous> (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/managers/AppSignatureManager.js:35:43)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/managers/AppSignatureManager.js:5:58)\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at ee/server/apps/communication/rest.ts:405:15\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/api.ts:633:9\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"status":400,"responseTime":3353,"msg":"\"pkcs8\" must be PKCS#8 formatted string"}
`
From browser:
`POST /api/apps/` :
`{success: false, error: ""pkcs8" must be PKCS#8 formatted string"}`

**Comment by RedOne-Guerad** [comment]
RC Version: 6.2.9
cant install applications  from marketplace nor private applications
![image](https://github.com/RocketChat/Rocket.Chat/assets/29951360/545ede91-39cc-4eaf-87c8-eed1f7f1b86d)

![image](https://github.com/RocketChat/Rocket.Chat/assets/29951360/02ea2030-abb5-4fdb-8799-c06be096bf04)
![image](https://github.com/RocketChat/Rocket.Chat/assets/29951360/8d0f85d3-6249-4c23-8db6-6df3c629b957)
![image](https://github.com/RocketChat/Rocket.Chat/assets/29951360/2a7b8279-0dd9-479b-8ac7-19eaf4e34194)

**Comment by Conrado916645** [comment]
Did any one resolve this issue

**Comment by scsaht** [comment]
I solved it.
In my case, "Administration - General - Apps - Apps_Framework_Source_Package_Storage_FileSystem_Path" settings was incorrect.
It seems that a permission error occurred because this setting was set to a unrelated Nextcloud_data directory.
I don't remember setting it that way, so I suspect that other settings, for example, webdav settings were moved during the rocketchat update process.

**Comment by drummer73** [comment]
This is still unresolved, happens after every update...
