### ISSUE TITLE
Error deploying to centos6.5 

### ISSUE THREAD

**Issue by liqiaoneng** [RocketChat/Rocket.Chat#2860]
Your Rocket.Chat version: (make sure you are running the latest)
`[root@bogon Rocket.Chat]# node main.js 
{ [MongoError: text search not enabled] stack: [Getter] }
Updating process.env.MAIL_URL
ufs: store created at 

/root/Rocket.Chat/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
MongoError: Mod on _id not allowed
    at Object.Future.wait (/root/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)
    at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
    at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:1)
    at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:104:1)
    at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)
    at [object Object].Mongo.Collection.upsert (packages/mongo/collection.js:624:1)
    at packages/matb33_collection-hooks/upsert.js:96:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.directOp (packages/matb33_collection-hooks/collection-hooks.js:18:1)
    - - - - -
    at Object.toError (/root/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /root/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:636:22
    at Server.Base._callHandler (/root/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /root/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/root/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/root/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/root/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/root/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
[root@bogon Rocket.Chat]#`

**Comment by engelgabriel** [comment]
What version of NodeJS are you using? Meteor only runs on 0.10 still.

**Comment by schnutz** [comment]
The MongoDB Version is too old and causing the error. You have to Update MongoDB then it should work.

**Comment by engelgabriel** [comment]
OK, please reopen if the problem persists.
