### ISSUE TITLE
error sent email by smtps

### ISSUE THREAD

**Issue by tsf0x13** [RocketChat/Rocket.Chat#28628]
### Description:

Configure and try to send email to ssmtp 587

### Steps to reproduce:

Go to setup-Email and configure email server send email by smiths

### Expected behavior:

email is sended

### Server Setup Information:

Rocket.Chat Version: 6.0.1
     NodeJS Version: 14.21.2 - x64
    MongoDB Version: 4.4.15
     MongoDB Engine: wiredTiger
           Platform: linux
       Process Port: 3000
           Site URL: http://192.168.24.98:3000
   ReplicaSet OpLog: Enabled
        Commit Hash: 118a8c9b68
      Commit Branch: HEAD

### Client Setup Information

- Desktop App or Browser Version: -
- Operating System: -

### Relevant logs:

rocketchat-rocketchat-1  | Exception in defer callback: Error: 140371267913600:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
rocketchat-rocketchat-1  |
rocketchat-rocketchat-1  |  => awaited here:
rocketchat-rocketchat-1  |     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
rocketchat-rocketchat-1  |     at Object.Email.send (packages/email/email.js:250:18)
rocketchat-rocketchat-1  |     at Object._send [as send] (packages/rocketchat:mongo-config/server/index.js:44:15)
rocketchat-rocketchat-1  |     at app/mailer/server/api.ts:174:27
rocketchat-rocketchat-1  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
rocketchat-rocketchat-1  |     at packages/meteor.js:587:25
rocketchat-rocketchat-1  |     at runWithEnvironment (packages/meteor.js:1417:24) {
rocketchat-rocketchat-1  |   library: 'SSL routines',
rocketchat-rocketchat-1  |   function: 'ssl3_get_record',
rocketchat-rocketchat-1  |   reason: 'wrong version number',
rocketchat-rocketchat-1  |   code: 'ESOCKET',
rocketchat-rocketchat-1  |   command: 'CONN'
rocketchat-rocketchat-1  | }

**Comment by tsf0x13** [comment]
my wrong - port is 465 not 587
