### ISSUE TITLE
build server,yarn install  throw some question

### ISSUE THREAD

**Issue by windsOne** [RocketChat/Rocket.Chat#28897]
### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.1
- Operating System: windows 10
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version:  v14.21.2
- MongoDB Version:

“yarn install ” run logs
### Relevant logs:
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @devtools-ds/themes@npm:1.2.0 [083a5] doesn't provide react-dom (p19ce3), requested by @design-systems/utils
➤ YN0002: │ @devtools-ds/themes@npm:1.2.0 [7652e] doesn't provide react-dom (p6bc1a), requested by @design-systems/utils
➤ YN0002: │ @devtools-ds/themes@npm:1.2.0 [c7082] doesn't provide react-dom (pb7e33), requested by @design-systems/utils
➤ YN0002: │ @nivo/annotations@npm:0.79.1 [60a9b] doesn't provide prop-types (p26311), requested by @nivo/colors
➤ YN0002: │ @nivo/annotations@npm:0.79.1 [60a9b] doesn't provide react-dom (p76851), requested by @react-spring/web
➤ YN0002: │ @nivo/arcs@npm:0.79.1 [aaf44] doesn't provide prop-types (p3b7ae), requested by @nivo/colors
➤ YN0002: │ @nivo/arcs@npm:0.79.1 [aaf44] doesn't provide react-dom (p2be04), requested by @react-spring/web
➤ YN0002: │ @nivo/axes@npm:0.79.0 [60a9b] doesn't provide react-dom (p90b5f), requested by @react-spring/web
➤ YN0002: │ @nivo/bar@npm:0.79.1 [965c2] doesn't provide prop-types (pc8da4), requested by @nivo/colors
➤ YN0002: │ @nivo/bar@npm:0.79.1 [965c2] doesn't provide prop-types (p1fac4), requested by @nivo/axes
➤ YN0002: │ @nivo/bar@npm:0.79.1 [965c2] doesn't provide prop-types (p6ccf9), requested by @nivo/legends
➤ YN0002: │ @nivo/bar@npm:0.79.1 [965c2] doesn't provide react-dom (p1511d), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.79.0 [965c2] doesn't provide react-dom (p14d8d), requested by @react-spring/web
➤ YN0002: │ @nivo/heatmap@npm:0.79.1 [965c2] doesn't provide prop-types (p23546), requested by @nivo/colors
➤ YN0002: │ @nivo/heatmap@npm:0.79.1 [965c2] doesn't provide prop-types (p10528), requested by @nivo/axes
➤ YN0002: │ @nivo/heatmap@npm:0.79.1 [965c2] doesn't provide react-dom (p20934), requested by @react-spring/web
➤ YN0002: │ @nivo/line@npm:0.79.1 [965c2] doesn't provide react-dom (pbaa59), requested by @react-spring/web
➤ YN0002: │ @nivo/pie@npm:0.79.1 [965c2] doesn't provide prop-types (p215ec), requested by @nivo/colors
➤ YN0002: │ @nivo/pie@npm:0.79.1 [965c2] doesn't provide prop-types (p6da04), requested by @nivo/legends
➤ YN0002: │ @nivo/tooltip@npm:0.79.0 [60a9b] doesn't provide react (pea33c), requested by @react-spring/web
➤ YN0002: │ @nivo/tooltip@npm:0.79.0 [60a9b] doesn't provide react-dom (p3fbe8), requested by @react-spring/web
➤ YN0002: │ @react-aria/gridlist@npm:3.0.0 [12957] doesn't provide react-dom (pc591b), requested by @react-aria/grid
➤ YN0002: │ @react-aria/gridlist@npm:3.0.0 [7c3cc] doesn't provide react-dom (p60fe8), requested by @react-aria/grid
➤ YN0002: │ @react-aria/gridlist@npm:3.0.0 [ed7f8] doesn't provide react-dom (pd3698), requested by @react-aria/grid
➤ YN0002: │ @react-spectrum/dnd@npm:3.0.0-alpha.6 [18c89] doesn't provide react-dom (p9ad16), requested by @react-aria/dnd
➤ YN0002: │ @react-spectrum/dnd@npm:3.0.0-alpha.6 [ac09a] doesn't provide react-dom (p0bf47), requested by @react-aria/dnd
➤ YN0002: │ @react-spectrum/dnd@npm:3.0.0-alpha.6 [ddfac] doesn't provide react-dom (p502ce), requested by @react-aria/dnd
➤ YN0002: │ @react-types/list@npm:3.0.0 [4472c] doesn't provide @react-spectrum/provider (padc89), requested by @react-spectrum/dnd
➤ YN0002: │ @react-types/list@npm:3.0.0 [9c83e] doesn't provide @react-spectrum/provider (p63edd), requested by @react-spectrum/dnd
➤ YN0002: │ @react-types/list@npm:3.0.0 [b8db6] doesn't provide @react-spectrum/provider (pa87a2), requested by @react-spectrum/dnd
➤ YN0060: │ @rocket.chat/account-service@workspace:ee/apps/account-service provides pino (pf6a77) with version 8.4.2, which doesn't satisfy what moleculer requests
➤ YN0060: │ @rocket.chat/authorization-service@workspace:ee/apps/authorization-service provides pino (p44db0) with version 8.4.2, which doesn't satisfy what moleculer requests
➤ YN0060: │ @rocket.chat/css-in-js@npm:0.31.23-dev.60 provides stylis (p0db82) with version 4.1.3, which doesn't satisfy what @rocket.chat/stylis-logical-props-middleware requests
➤ YN0060: │ @rocket.chat/css-in-js@npm:0.31.23-dev.64 provides stylis (p8e448) with version 4.1.3, which doesn't satisfy what @rocket.chat/stylis-logical-props-middleware requests
➤ YN0060: │ @rocket.chat/css-supports@npm:0.31.23-dev.58 provides stylis (p2e4dd) with version 4.1.3, which doesn't satisfy what @rocket.chat/stylis-logical-props-middleware requests
➤ YN0002: │ @rocket.chat/eslint-config@workspace:packages/eslint-config doesn't provide @babel/core (p19dcc), requested by @babel/eslint-parser
➤ YN0002: │ @rocket.chat/forked-matrix-appservice-bridge@npm:4.0.1 doesn't provide express (pc5c43), requested by express-rate-limit
➤ YN0002: │ @rocket.chat/fuselage-ui-kit@workspace:packages/fuselage-ui-kit doesn't provide @babel/core (pa5224), requested by babel-loader
➤ YN0002: │ @rocket.chat/fuselage-ui-kit@workspace:packages/fuselage-ui-kit doesn't provide @babel/core (p2bc8e), requested by @storybook/addon-essentials
➤ YN0002: │ @rocket.chat/fuselage-ui-kit@workspace:packages/fuselage-ui-kit doesn't provide @rocket.chat/fuselage-tokens (p4afe7), requested by @rocket.chat/fuselage-hooks
➤ YN0002: │ @rocket.chat/fuselage-ui-kit@workspace:packages/fuselage-ui-kit doesn't provide react-virtuoso (p0e0cd), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/fuselage-ui-kit@workspace:packages/fuselage-ui-kit doesn't provide require-from-string (p979b7), requested by @storybook/react
➤ YN0002: │ @rocket.chat/fuselage-ui-kit@workspace:packages/fuselage-ui-kit [965c2] doesn't provide @babel/core (p962fb), requested by @storybook/addon-essentials
➤ YN0002: │ @rocket.chat/fuselage-ui-kit@workspace:packages/fuselage-ui-kit [965c2] doesn't provide @babel/core (p97489), requested by babel-loader
➤ YN0002: │ @rocket.chat/fuselage-ui-kit@workspace:packages/fuselage-ui-kit [965c2] doesn't provide require-from-string (p02a24), requested by @storybook/react
➤ YN0002: │ @rocket.chat/gazzodown@workspace:packages/gazzodown doesn't provide @rocket.chat/fuselage-hooks (pff022), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/gazzodown@workspace:packages/gazzodown doesn't provide @rocket.chat/fuselage-polyfills (p54ccb), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/gazzodown@workspace:packages/gazzodown doesn't provide @rocket.chat/icons (p20680), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/gazzodown@workspace:packages/gazzodown doesn't provide react-virtuoso (pcafa5), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/gazzodown@workspace:packages/gazzodown doesn't provide require-from-string (p9824d), requested by @storybook/react
➤ YN0002: │ @rocket.chat/gazzodown@workspace:packages/gazzodown doesn't provide webpack (p3ae77), requested by babel-loader
➤ YN0002: │ @rocket.chat/gazzodown@workspace:packages/gazzodown [965c2] doesn't provide require-from-string (p60612), requested by @storybook/react
➤ YN0002: │ @rocket.chat/gazzodown@workspace:packages/gazzodown [965c2] doesn't provide webpack (p46c69), requested by babel-loader
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide @babel/core (p03905), requested by @babel/eslint-parser
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide @babel/core (pc6e73), requested by @babel/preset-env
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide @babel/core (p8cda9), requested by @storybook/addon-essentials
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide @babel/core (p64967), requested by babel-loader
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide @storybook/addons (p372c9), requested by @storybook/addon-knobs
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide @storybook/api (p8cb2d), requested by @storybook/addon-knobs
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide @storybook/components (p17c9a), requested by @storybook/addon-knobs
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide @storybook/core-events (pfe3fe), requested by @storybook/addon-knobs
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide postcss (p18b42), requested by postcss-scss
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide react (p42557), requested by @storybook/theming
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide react (p62402), requested by @storybook/react
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide react (pa34f7), requested by emoji-mart
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide react (p11c3c), requested by react-dom
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide react (p04094), requested by react-i18next
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide react (p927eb), requested by @rocket.chat/logo
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat doesn't provide require-from-string (p9b283), requested by @storybook/react
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide @babel/core (p5df02), requested by @babel/eslint-parser
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide @babel/core (pd6bc2), requested by @babel/preset-env
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide @babel/core (p08937), requested by @storybook/addon-essentials
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide @babel/core (p3ea90), requested by babel-loader
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide @storybook/addons (p333d8), requested by @storybook/addon-knobs
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide @storybook/api (pc08df), requested by @storybook/addon-knobs
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide @storybook/components (p33379), requested by @storybook/addon-knobs
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide @storybook/core-events (p0e127), requested by @storybook/addon-knobs
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide postcss (p1da71), requested by postcss-scss
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide react (pfef91), requested by @storybook/theming
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide react (p3dcc8), requested by @storybook/react
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide react (p577f2), requested by emoji-mart
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide react (pcc4c2), requested by react-dom
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide react (p58966), requested by react-i18next
➤ YN0002: │ @rocket.chat/livechat@workspace:packages/livechat [965c2] doesn't provide require-from-string (p48123), requested by @storybook/react
➤ YN0002: │ @rocket.chat/logo@npm:0.32.0-dev.234 [965c2] doesn't provide @rocket.chat/fuselage-tokens (p86c02), requested by @rocket.chat/fuselage-hooks
➤ YN0002: │ @rocket.chat/logo@npm:0.32.0-dev.234 [ae4e8] doesn't provide @rocket.chat/fuselage-tokens (pd57a7), requested by @rocket.chat/fuselage-hooks
➤ YN0002: │ @rocket.chat/meteor@workspace:apps/meteor doesn't provide @nivo/tooltip (pb0dfb), requested by @nivo/core
➤ YN0002: │ @rocket.chat/meteor@workspace:apps/meteor doesn't provide @rocket.chat/styled (p84c2c), requested by @rocket.chat/fuselage-toastbar
➤ YN0002: │ @rocket.chat/meteor@workspace:apps/meteor doesn't provide @rocket.chat/styled (p875a5), requested by @rocket.chat/onboarding-ui
➤ YN0060: │ @rocket.chat/meteor@workspace:apps/meteor provides @tanstack/react-query (p0bb10) with version 4.16.1, which doesn't satisfy what @tanstack/react-query-devtools requests
➤ YN0002: │ @rocket.chat/meteor@workspace:apps/meteor doesn't provide @testing-library/dom (p899bf), requested by @testing-library/user-event
➤ YN0060: │ @rocket.chat/meteor@workspace:apps/meteor provides prom-client (p459fa) with version 14.0.1, which doesn't satisfy what prometheus-gc-stats requests
➤ YN0002: │ @rocket.chat/meteor@workspace:apps/meteor doesn't provide prop-types (p737aa), requested by @nivo/core
➤ YN0002: │ @rocket.chat/meteor@workspace:apps/meteor doesn't provide prop-types (p18f27), requested by @nivo/line
➤ YN0060: │ @rocket.chat/meteor@workspace:apps/meteor provides react (p0a24b) with version 17.0.2, which doesn't satisfy what @rocket.chat/web-ui-registration and some of its descendants request
➤ YN0060: │ @rocket.chat/meteor@workspace:apps/meteor provides react (p66909) with version 17.0.2, which doesn't satisfy what use-subscription requests
➤ YN0060: │ @rocket.chat/meteor@workspace:apps/meteor provides react-i18next (p5e2d7) with version 11.18.5, which doesn't satisfy what @rocket.chat/layout requests
➤ YN0060: │ @rocket.chat/meteor@workspace:apps/meteor provides react-i18next (p8cea8) with version 11.18.5, which doesn't satisfy what @rocket.chat/onboarding-ui requests
➤ YN0060: │ @rocket.chat/meteor@workspace:apps/meteor provides react-virtuoso (p84133) with version 1.11.1, which doesn't satisfy what @rocket.chat/fuselage requests
➤ YN0002: │ @rocket.chat/meteor@workspace:apps/meteor doesn't provide require-from-string (p3e780), requested by @storybook/react
➤ YN0060: │ @rocket.chat/omnichannel-transcript@workspace:ee/apps/omnichannel-transcript provides pino (p834c5) with version 8.4.2, which doesn't satisfy what moleculer requests
➤ YN0002: │ @rocket.chat/omnichannel-transcript@workspace:ee/apps/omnichannel-transcript doesn't provide react (p7fce2), requested by @react-pdf/renderer
➤ YN0002: │ @rocket.chat/pdf-worker@workspace:ee/packages/pdf-worker doesn't provide @babel/core (p8f8a4), requested by @storybook/addon-essentials
➤ YN0060: │ @rocket.chat/pdf-worker@workspace:ee/packages/pdf-worker provides react (p57970) with version 18.2.0, which doesn't satisfy what @storybook/addon-actions and some of its descendants request
➤ YN0060: │ @rocket.chat/pdf-worker@workspace:ee/packages/pdf-worker provides react (p9a2e5) with version 18.2.0, which doesn't satisfy what @storybook/addon-docs and some of its descendants request
➤ YN0060: │ @rocket.chat/pdf-worker@workspace:ee/packages/pdf-worker provides react (p0e342) with version 18.2.0, which doesn't satisfy what @storybook/react and some of its descendants request
➤ YN0060: │ @rocket.chat/pdf-worker@workspace:ee/packages/pdf-worker provides react-dom (p9ec76) with version 18.2.0, which doesn't satisfy what @storybook/react and some of its descendants request
➤ YN0002: │ @rocket.chat/pdf-worker@workspace:ee/packages/pdf-worker doesn't provide require-from-string (p0da10), requested by @storybook/react
➤ YN0060: │ @rocket.chat/presence-service@workspace:ee/apps/presence-service provides pino (pb9f35) with version 8.4.2, which doesn't satisfy what moleculer requests
➤ YN0060: │ @rocket.chat/queue-worker@workspace:ee/apps/queue-worker provides pino (p963ee) with version 8.4.2, which doesn't satisfy what moleculer requests
➤ YN0002: │ @rocket.chat/queue-worker@workspace:ee/apps/queue-worker doesn't provide react (p8de68), requested by @react-pdf/renderer
➤ YN0060: │ @rocket.chat/stream-hub-service@workspace:ee/apps/stream-hub-service provides pino (pbebb5) with version 8.4.2, which doesn't satisfy what moleculer requests
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client doesn't provide @rocket.chat/fuselage-polyfills (pf1bed), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client doesn't provide @rocket.chat/fuselage-tokens (p82c06), requested by @rocket.chat/fuselage-hooks
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client doesn't provide react-dom (pdc575), requested by @storybook/builder-webpack4
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client doesn't provide react-dom (p8f6cd), requested by @storybook/manager-webpack4
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client doesn't provide react-dom (p26458), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client doesn't provide react-dom (p2abfb), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client doesn't provide react-virtuoso (p21c23), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client doesn't provide require-from-string (pa7e9d), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client [8332e] doesn't provide @rocket.chat/fuselage-tokens (p4915f), requested by @rocket.chat/fuselage-hooks
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client [8332e] doesn't provide react-dom (p73c4b), requested by @storybook/builder-webpack4
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client [8332e] doesn't provide react-dom (p0d6ea), requested by @storybook/manager-webpack4
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client [8332e] doesn't provide react-dom (pae98a), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client [8332e] doesn't provide require-from-string (pdbea6), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client [965c2] doesn't provide react-dom (pc42b8), requested by @storybook/builder-webpack4
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client [965c2] doesn't provide react-dom (p41fce), requested by @storybook/manager-webpack4
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client [965c2] doesn't provide react-dom (p7a7d4), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-client@workspace:packages/ui-client [965c2] doesn't provide require-from-string (p27769), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-composer@workspace:packages/ui-composer doesn't provide @rocket.chat/fuselage-hooks (pee96b), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/ui-composer@workspace:packages/ui-composer doesn't provide @rocket.chat/fuselage-polyfills (pf0982), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/ui-composer@workspace:packages/ui-composer doesn't provide react-virtuoso (p6a741), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/ui-composer@workspace:packages/ui-composer doesn't provide require-from-string (p2b3f6), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-composer@workspace:packages/ui-composer [965c2] doesn't provide require-from-string (p543cf), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-contexts@workspace:packages/ui-contexts doesn't provide @rocket.chat/fuselage-tokens (pc6034), requested by @rocket.chat/fuselage-hooks
➤ YN0002: │ @rocket.chat/ui-contexts@workspace:packages/ui-contexts [48b0b] doesn't provide @rocket.chat/fuselage-tokens (p23e85), requested by @rocket.chat/fuselage-hooks
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming doesn't provide @babel/core (pd2fd9), requested by @storybook/addon-essentials
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming doesn't provide @rocket.chat/fuselage-polyfills (p3ba56), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming doesn't provide @rocket.chat/fuselage-tokens (pa9b65), requested by @rocket.chat/fuselage-hooks
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming doesn't provide react-dom (p740e6), requested by @storybook/builder-webpack4
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming doesn't provide react-dom (pa4462), requested by @storybook/manager-webpack4
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming doesn't provide react-dom (p5e167), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming doesn't provide react-dom (pf1cfd), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming doesn't provide react-virtuoso (pedef8), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming doesn't provide require-from-string (pb6234), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming [965c2] doesn't provide @babel/core (p80afa), requested by @storybook/addon-essentials
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming [965c2] doesn't provide react-dom (pfa3fd), requested by @storybook/builder-webpack4
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming [965c2] doesn't provide react-dom (pa3fa2), requested by @storybook/manager-webpack4
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming [965c2] doesn't provide react-dom (p61e81), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-theming@workspace:ee/packages/ui-theming [965c2] doesn't provide require-from-string (p8c463), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-video-conf@workspace:packages/ui-video-conf doesn't provide @rocket.chat/fuselage-polyfills (p24a4d), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/ui-video-conf@workspace:packages/ui-video-conf doesn't provide @rocket.chat/fuselage-tokens (p1ffbd), requested by @rocket.chat/fuselage-hooks
➤ YN0002: │ @rocket.chat/ui-video-conf@workspace:packages/ui-video-conf doesn't provide react-virtuoso (p103c6), requested by @rocket.chat/fuselage
➤ YN0002: │ @rocket.chat/ui-video-conf@workspace:packages/ui-video-conf doesn't provide require-from-string (p057f0), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-video-conf@workspace:packages/ui-video-conf [75d2e] doesn't provide require-from-string (p6aa7d), requested by @storybook/react
➤ YN0002: │ @rocket.chat/ui-video-conf@workspace:packages/ui-video-conf [965c2] doesn't provide require-from-string (p462e3), requested by @storybook/react
➤ YN0002: │ @rocket.chat/web-ui-registration@workspace:packages/web-ui-registration doesn't provide @rocket.chat/fuselage (p66714), requested by @rocket.chat/layout
➤ YN0002: │ @rocket.chat/web-ui-registration@workspace:packages/web-ui-registration doesn't provide react-dom (p61be6), requested by @rocket.chat/layout
➤ YN0002: │ @rocket.chat/web-ui-registration@workspace:packages/web-ui-registration doesn't provide react-dom (pddf0c), requested by @testing-library/react
➤ YN0002: │ @rocket.chat/web-ui-registration@workspace:packages/web-ui-registration [965c2] doesn't provide react-dom (p3e6bf), requested by @testing-library/react
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [61daa] doesn't provide @babel/core (p33030), requested by @babel/preset-env
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [61daa] doesn't provide @babel/core (p653ce), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [61daa] doesn't provide @babel/core (pa0f19), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [61daa] doesn't provide webpack (pcfe91), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [64e5b] doesn't provide @babel/core (p8507e), requested by @babel/preset-env
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [64e5b] doesn't provide @babel/core (pd63e0), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [64e5b] doesn't provide @babel/core (p9919a), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [64e5b] doesn't provide webpack (pa5592), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [6a890] doesn't provide @babel/core (p5c035), requested by @babel/preset-env
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [6a890] doesn't provide @babel/core (p53bf6), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [6a890] doesn't provide @babel/core (p61caf), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [6a890] doesn't provide webpack (p4d60e), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [a80b4] doesn't provide @babel/core (pf7731), requested by @babel/preset-env
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [a80b4] doesn't provide @babel/core (p301b8), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [a80b4] doesn't provide @babel/core (pd9630), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [a80b4] doesn't provide webpack (p7147d), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [c70f1] doesn't provide @babel/core (pe9c7d), requested by @babel/preset-env
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [c70f1] doesn't provide @babel/core (p071a3), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [c70f1] doesn't provide @babel/core (pedcad), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [c70f1] doesn't provide webpack (p90792), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [f9cc2] doesn't provide @babel/core (pf8394), requested by @babel/preset-env
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [f9cc2] doesn't provide @babel/core (p6ba98), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [f9cc2] doesn't provide @babel/core (pe44e5), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.15 [f9cc2] doesn't provide webpack (p63801), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [010c4] doesn't provide @babel/core (p6d445), requested by @babel/preset-env
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [010c4] doesn't provide @babel/core (p3b5bb), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [010c4] doesn't provide @babel/core (pc4259), requested by babel-loader
➤ YN0002: │ @storybook/addon-docs@npm:6.5.16 [010c4] doesn't provide webpack (pa72b5), requested by babel-loader
➤ YN0002: │ @storybook/addon-postcss@npm:2.0.0 doesn't provide webpack (pb2910), requested by css-loader
➤ YN0002: │ @storybook/addon-postcss@npm:2.0.0 doesn't provide webpack (pec374), requested by postcss-loader
➤ YN0002: │ @storybook/addon-postcss@npm:2.0.0 doesn't provide webpack (pe4518), requested by style-loader
➤ YN0002: │ @storybook/docs-tools@npm:6.5.15 doesn't provide react (p5aca9), requested by @storybook/store
➤ YN0002: │ @storybook/docs-tools@npm:6.5.15 doesn't provide react-dom (pda8c4), requested by @storybook/store
➤ YN0002: │ @storybook/docs-tools@npm:6.5.16 doesn't provide react (p9b542), requested by @storybook/store
➤ YN0002: │ @storybook/docs-tools@npm:6.5.16 doesn't provide react-dom (pc910b), requested by @storybook/store
➤ YN0002: │ @storybook/instrumenter@npm:6.5.14 doesn't provide react (pfdea2), requested by @storybook/addons
➤ YN0002: │ @storybook/instrumenter@npm:6.5.14 doesn't provide react-dom (p9ca24), requested by @storybook/addons
➤ YN0002: │ @storybook/mdx1-csf@npm:0.0.1 doesn't provide @babel/core (p44796), requested by @babel/preset-env
➤ YN0002: │ @storybook/telemetry@npm:6.5.15 doesn't provide react (p1e5d6), requested by @storybook/core-common
➤ YN0002: │ @storybook/telemetry@npm:6.5.15 doesn't provide react-dom (p60a6f), requested by @storybook/core-common
➤ YN0002: │ @storybook/telemetry@npm:6.5.16 doesn't provide react (p48f29), requested by @storybook/core-common
➤ YN0002: │ @storybook/telemetry@npm:6.5.16 doesn't provide react-dom (p479a1), requested by @storybook/core-common
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 1s 811ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ http2@https://github.com/node-apn/node-http2/archive/apn-2.1.4.tar.gz can't be found in the cache and will be fetched from the remote server
➤ YN0001: │ RequestError: unable to verify the first certificate
    at ClientRequest.<anonymous> (C:\Users\Z_PC\AppData\Local\node\corepack\yarn\3.2.2\yarn.js:195:14361)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.o.emit (C:\Users\Z_PC\AppData\Local\node\corepack\yarn\3.2.2\yarn.js:190:90453)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
➤ YN0013: │ lamejs@https://github.com/zhuker/lamejs.git#commit=582bbba6a12f981b984d8fb9e1874499fed85675 can't be found in the cache and will be fetched from GitHub
➤ YN0000: └ Completed in 3s 358ms
➤ YN0000: Failed with errors in 5s 178ms

**Comment by windsOne** [comment]
closed，repeat issue
