### ISSUE TITLE
Slack import fails when importing pinned images

### ISSUE THREAD

**Issue by askielboe** [RocketChat/Rocket.Chat#2904]
Your Rocket.Chat version: 0.26.0

I get the following trace when trying to import my Slack history:

```
Exception in defer callback: TypeError: Cannot read property '0' of undefined
at Slack.<anonymous> (packages/rocketchat_importer-slack/server.coffee:240:77)
at [object Object].<anonymous> (packages/rocketchat_importer-slack/server.coffee:201:9)
at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) 
at Object.Meteor.runAsUser (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:185:1)
at fn (packages/rocketchat_importer-slack/server.coffee:195:13)
at packages/rocketchat_importer-slack/server.coffee:194:5
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at packages/meteor/timers.js:6:1
at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

This is the relevant code (https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-importer-slack/server.coffee):

``` javascript
else if message.subtype is 'pinned_item'
    RocketChat.models.Messages.createWithTypeRoomIdMessageAndUser 'message_pinned', room._id, '', @getRocketUser(message.user),
        ts: new Date(parseInt(message.ts.split('.')[0]) * 1000)
        attachments: [
            "text" : @convertSlackMessageToRocketChat message.attachments[0].text
            "author_name" : message.attachments[0].author_subname
            "author_icon" : getAvatarUrlFromUsername(message.attachments[0].author_subname)
        ]
```

Seems that it expects an `attachment` field which doesn't exist for `pinned_item` containing images.

This is the JSON it fails on:

``` json
{
    "type": "message",
    "subtype": "pinned_item",
    "user": "U08R07FBQ",
    "item_type": "F",
    "text": "<@U08R07FBQ|krisse> pinned <@U09NEDH0X|sisden>'s Image <https:\/\/peppeshus.slack.com\/files\/sisden\/F0Y2ECA8Z\/screen_shot_2016-04-05_at_12.14.40.png|Screen Shot 2016-04-05 at 12.14.40.png> to this channel.",
    "item": {
        "id": "F0Y2ECA8Z",
        "created": 1459851290,
        "timestamp": 1459851290,
        "name": "Screen Shot 2016-04-05 at 12.14.40.png",
        "title": "Screen Shot 2016-04-05 at 12.14.40.png",
        "mimetype": "image\/png",
        "filetype": "png",
        "pretty_type": "PNG",
        "user": "U09NEDH0X",
        "editable": false,
        "size": 33533,
        "mode": "hosted",
        "is_external": false,
        "external_type": "",
        "is_public": true,
        "public_url_shared": false,
        "display_as_bot": false,
        "username": "",
        "url_private": "https:\/\/files.slack.com\/files-pri\/T08R07FB8-F0Y2ECA8Z\/screen_shot_2016-04-05_at_12.14.40.png",
        "url_private_download": "https:\/\/files.slack.com\/files-pri\/T08R07FB8-F0Y2ECA8Z\/download\/screen_shot_2016-04-05_at_12.14.40.png",
        "thumb_64": "https:\/\/files.slack.com\/files-tmb\/T08R07FB8-F0Y2ECA8Z-53020d9d0f\/screen_shot_2016-04-05_at_12.14.40_64.png",
        "thumb_80": "https:\/\/files.slack.com\/files-tmb\/T08R07FB8-F0Y2ECA8Z-53020d9d0f\/screen_shot_2016-04-05_at_12.14.40_80.png",
        "thumb_360": "https:\/\/files.slack.com\/files-tmb\/T08R07FB8-F0Y2ECA8Z-53020d9d0f\/screen_shot_2016-04-05_at_12.14.40_360.png",
        "thumb_360_w": 124,
        "thumb_360_h": 157,
        "thumb_160": "https:\/\/files.slack.com\/files-tmb\/T08R07FB8-F0Y2ECA8Z-53020d9d0f\/screen_shot_2016-04-05_at_12.14.40_160.png",
        "image_exif_rotation": 1,
        "original_w": 124,
        "original_h": 157,
        "permalink": "https:\/\/peppeshus.slack.com\/files\/sisden\/F0Y2ECA8Z\/screen_shot_2016-04-05_at_12.14.40.png",
        "permalink_public": "https:\/\/slack-files.com\/T08R07FB8-F0Y2ECA8Z-9321652356",
        "channels": [
            "C0F62AFU0"
        ],
        "groups": [

        ],
        "ims": [

        ],
        "comments_count": 0,
        "pinned_to": [
            "C0F62AFU0"
        ],
        "reactions": [
            {
                "name": "superlike",
                "users": [
                    "U08RB723Z"
                ],
                "count": 1
            }
        ]
    },
    "ts": "1459851308.000311"
}
```

**Comment by graywolf336** [comment]
Looks like they may have changed their format, I'll take a look today.

**Comment by graywolf336** [comment]
After testing this, pinned messages don't cause errors anymore and import successfully.
