### ISSUE TITLE
Crash Rocket.Chat containers when federation is time-out

### ISSUE THREAD

**Issue by andys448** [RocketChat/Rocket.Chat#29222]
### Description:

If between federation servers sometimes take time-out - containers stop responding and hang instead of exiting with an error. 

### Steps to reproduce:

Let rocketchat run for a while
Rocketchat gets unresponsive
Kill the container to be able to use Rocketchat again

### Expected behavior:

There can sometimes be a timeout between federated server instances. Expected behavior - ignore small delays or inform in the log

### Actual behavior:

Containers just hangs. Need to manual restart.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.8
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.19.3
- MongoDB Version: 4.4.15

### Client Setup Information

- Desktop App or Browser Version: Any
- Operating System: Any

### Relevant logs:

```
{"level":50,"time":"2023-05-12T09:45:02.267Z","pid":1,"hostname":"ef00e52b5704","name":"Federation","section":"http","msg":"Error","err":{"type":"FetchError","message":"network timeout at: https://rc.chat.ru:443/api/v1/federation.events.dispatch","stack":"FetchError: network timeout at: https://rc.chat.ru:443/api/v1/federation.events.dispatch\n    at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/fetch/node_modules/node-fetch/lib/index.js:1437:13)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/federation/server/lib/http.js:46:9\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","name":"FetchError"},"msg":"network timeout at: https://rc.chat.ru:443/api/v1/federation.events.dispatch"}
=== UnHandledPromiseRejection ===
FetchError: network timeout at: https://rc.domain.ru:443/api/v1/federation.events.dispatch
    at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/fetch/node_modules/node-fetch/lib/index.js:1437:13)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at app/federation/server/lib/http.js:46:9
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at app/federation/server/handler/index.js:79:3
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at app/federation/server/handler/index.js:84:2
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
  type: 'request-timeout'
}
---------------------------------
Errors like this can cause oplog processing errors.
Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Future node.js versions will automatically exit the process
=================================
BadRequestError: request aborted
    at IncomingMessage.onAborted (/app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:400:28)
    at IncomingMessage.emit (domain.js:475:12)
    at abortIncoming (_http_server.js:569:9)
    at socketOnClose (_http_server.js:562:3)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at TCP.<anonymous> (net.js:686:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)
{"level":50,"time":"2023-05-12T09:52:41.791Z","pid":1,"hostname":"ef00e52b5704","name":"System","msg":"No real time data received recently"}
BadRequestError: request aborted
    at IncomingMessage.onAborted (/app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:400:28)
    at IncomingMessage.emit (domain.js:475:12)
    at abortIncoming (_http_server.js:569:9)
    at socketOnClose (_http_server.js:562:3)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at TCP.<anonymous> (net.js:686:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)

```

**Comment by andys448** [comment]
Hi All! New logs when crashing RC:

```
