### ISSUE TITLE
6.2.1: Atlassian Crowd Login broken

### ISSUE THREAD

**Issue by Nezisi** [RocketChat/Rocket.Chat#29285]
After upgrading to RocketChat 6.2.1, login via Crowd is broken.

The web form doesn't even show that there is an error happening, it's only visible in the network console.

The request sent is:
method: "POST"
/api/v1/method.callAnon/login
{"msg":"method","id":"56","method":"login","params":[{"crowd":true,"username":"<...>","crowdPassword":"<...>"}]}

The response by RocketChat is:
HTTP status code: 200
{"message":"{\"msg\":\"result\",\"id\":\"56\",\"error\":\"not-authorized\"}","success":true}

If I try to login via a CURL request, e.g.

curl -XPOST -d 'user=<...>&password=<...>' https://<...>/api/v1/login
I get an valid reply.

If I use the authentication token of the reply in the browser and use the resumeToken as a query parameter:
https://<...>/home?resumeToken=<...>
Login works without any problem.

**Comment by unix196** [comment]
```
+------------------------------------------------+
|                 SERVER RUNNING                 |
+------------------------------------------------+
|                                                |
|  Rocket.Chat Version: 6.4.5                    |
|       NodeJS Version: 14.21.3 - x64            |
|      MongoDB Version: 4.4.22                   |
|       MongoDB Engine: wiredTiger               |
|             Platform: linux                    |
|         Process Port: 3000                     |
|             Site URL: https://chat.XXX.XXX  |
|     ReplicaSet OpLog: Enabled                  |
```
also broken crowd integration (updated from version 5.4.9 where integration worked).
When login with crowd login:
```
{"level":50,"time":"2023-11-15T09:34:44.687Z","pid":10,"hostname":"XXXX","name":"System","msg":"Exception while invoking method login","err":"not-authorized"}
```
When press button _Sync users_ in Crowd integration:
```
"level":50,"time":"2023-11-15T11:01:40.719Z","pid":10,"hostname":"2f8a56b367d4","name":"CROWD","msg":"Could not sync user with username","crowd_username":"SOME_USER"}
{"level":50,"time":"2023-11-15T11:01:40.720Z","pid":10,"hostname":"2f8a56b367d4","name":"CROWD","msg":"Error syncing user data. ","err":{"type":"TypeError","message":"this.crowdClient.searchSync is not a function","stack":"TypeError: this.crowdClient.searchSync is not a function\n    at app/crowd/server/crowd.ts:222:39\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/crowd/server/methods.ts:67:4\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"}}
```
