### ISSUE TITLE
Can't set the channel for an outgoing webhook to `all_public_channels,all_private_groups,all_direct_messages`

### ISSUE THREAD

**Issue by L7R7** [RocketChat/Rocket.Chat#29404]
### Description:

When creating an outgoing webhook, it's not possible to set the channel to `all_public_channels,all_private_groups,all_direct_messages`. 

### Steps to reproduce:

1. Create an outgoing webhook
2. set the channel to `all_public_channels,all_private_groups,all_direct_messages`
3. save

### Expected behavior:

Integration is saved

### Actual behavior:

There's an error message in the UI saying "Invalid channel", and the integration is not saved

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.1

### Client Setup Information

Consistent across different browsers and OS

### Additional context

Following https://forums.rocket.chat/t/outgoing-webhook-that-triggers-on-a-user-mention-or-direct-message/3488/2 and https://github.com/RocketChat/Rocket.Chat/issues/4662#issuecomment-331150973, I was assuming that this is the correct setting for listening on all messages in all channels.

**Comment by steffen-kdab** [comment]
Our Jira integration started to fail a while ago. We have Channel in the output webhook set to `all_public_channels, all_private_groups, all_direct_messages` and get the same error:
`"name":"Integrations","section":"Outgoing WebHook","err":{"type":"errorClass","message":"[invalid-channel]","stack":"Error: [invalid-channel]\n    at app/lib/server/functions/getRoomByNameOrIdWithOptionToJoin.ts:70:9\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/lib/server/functions/processWebhookMessage.ts:55:9\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/integrations/server/lib/triggerHandler.js:120:10\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/integrations/server/lib/triggerHandler.js:648:22\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","isClientSafe":true,"error":"invalid-channel","errorType":"Meteor.Error"},"msg":"[invalid-channel]"}`

We're on the latest RC, version 6.12.1
