### ISSUE TITLE
Manually Approve New Users  - does not work

### ISSUE THREAD

**Issue by AlexanderKgr** [RocketChat/Rocket.Chat#29411]
### Description:

When the option "Manually Approve New Users" is enabled, the new user registration doesn't work with error
### Steps to reproduce:

1.  Enable option "Manually Approve New Users"
2. Try to create new user
3. At console logs there is an error

### Expected behavior:
 Create the user and wait for approval

### Actual behavior:

Nothing

### Server Setup Information:

- Version of Rocket.Chat Server:  6.2.2
- Operating System:  Ubuntu 22.04
- Deployment Method: snap
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- Browser Version: Latest Chrome
- Operating System: Windows 11

### Relevant logs:

Object { success: false, error: "[usersInRole.toArray(...).forEach is not a function]", errorType: "usersInRole.toArray(...).forEach is not a function" }

![image](https://github.com/RocketChat/Rocket.Chat/assets/25532758/92c01470-8304-4bd3-97fb-9735aa08e888)

**Comment by speycode** [comment]
Can confirm my organisation are having the same issue. It has been around since at least 6.2.1 as it did not work on that version either.

**Comment by hugocostadev** [comment]
FYI here is the print of the payload, the user is being created but he gets stuck in the registration form.
If I try to login the warning (second image) appears

![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/c7e24840-092d-41a1-896d-43f5a06e14c3)
![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/93ecac71-0809-4268-a6c9-c1f78b7bcbc1)

**Comment by hugocostadev** [comment]
I'm working on it!

**Comment by alexhaiduk** [comment]
New user registration doesn't work with error, we have same problem.

Server Setup Information:
    Version of Rocket.Chat Server: 6.2.2
    Operating System: Debian v11.3
    Deployment Method: Manual
    Engine: 1.39.1
    DB migration: 294
    Number of Running Instances: 1
    NodeJS Version: v14.21.3
    MongoDB Version: 5.0.15 / wiredTiger (oplog Enabled)

Client Setup Information

    Browser Version: Latest Chrome or latest Firefox or other...
`
{"level":35,"time":"2023-06-01T07:18:43.053Z","pid":833,"hostname":"xxxxxxx","name":"API","method":"POST","url":"/api/v1/users.create","userId":"xxxxxxxxxxx","userAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148","length":"270","host":"xxxxxxx","referer":"https://xxxxxxxxx/admin/users/new","remoteIP":"xxx.xxx.xxx.xxx","err":{"type":"TypeError","message":"usersInRole.toArray(...).forEach is not a function","stack":"TypeError: usersInRole.toArray(...).forEach is not a function<br>    at app/authentication/server/startup/index.js:198:31<br>    at /opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at AccountsServer._onCreateUserHook (app/authentication/server/startup/index.js:230:17)<br>    at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1179:23)<br>    at app/authentication/server/startup/index.js:265:28<br>    at /opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at AccountsServer.Accounts.insertUserDoc (app/authentication/server/startup/index.js:321:17)<br>    at AccountsServer._createUserCheckingDuplicates (packages/accounts-base/accounts_server.js:1473:25)<br>    at packages/accounts-password/password_server.js:949:19<br>    at /opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/lib/server/functions/saveUser.js:285:11<br>    at /opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/api/server/v1/users.ts:271:19<br>    at /opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/api/server/api.ts:633:9<br>    at /opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"status":400,"responseTime":132,"msg":"usersInRole.toArray(...).forEach is not a function"}
`

**Comment by hans4rc** [comment]
Same here!
