### ISSUE TITLE
Public Channels Not Found/Invisible to Any Users Except Members

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#29456]
### Description:

We have a couple of public channels, one called "phonegroup" and another called "support-and-training", that despite being a public channel, are not visible to anybody who is not a member of it.  I [previously opened this ticket in March](https://github.com/RocketChat/Rocket.Chat/issues/28465) but @hugocostadev closed it without it being fixed.

### Steps to reproduce:

Honestly, I don't know how to reproduce this. I wish I knew how.

### Expected behavior:

When a channel is marked in administrator settings as public, I would expect it to found when searching for it.

### Actual behavior:

Here is a screenshot showing the the channel in the admin settings, showing it is public:

![image](https://github.com/RocketChat/Rocket.Chat/assets/6833993/1b4b9b6f-9823-4901-a721-ce01843eb3fd)

When I try to access the channel by url, I get an error that reads: "Room not found. The room does not exist or you may not have access permission"

![image](https://github.com/RocketChat/Rocket.Chat/assets/6833993/4e106a27-f933-4ebd-b59f-9f07ca80117b)

I don't know that this icon means, but for those that can access the phonegroup channel, they see a padlock next to the channel name:

![image](https://github.com/RocketChat/Rocket.Chat/assets/6833993/08f374df-5e80-4137-a617-4d282cdac7af)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.2
- Operating System: Redhat 8
- Deployment Method: RC provided build images
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0.17

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: all

### Relevant logs:

Here are logs from when I just tried to access the phonegroup channel, showing an exception while invoking method getRoomByTypeAndName:

Jun  5 10:47:09 chat rocketchat1[1053323]: {"level":35,"time":"2023-06-05T15:47:09.424Z","pid":1053323,"hostname":"chat.leepfrog.com","name":"Meteor","method":"getRoomByTypeAndName","userId":"536RNDyN6ABJz6DpC","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","referer":"https://chat.leepfrog.com/channel/phonegroup","remoteIP":"10.1.88.51","instanceId":"ae6b5827-d0c6-4d03-a73f-62e8a7a36c8c"}
Jun  5 10:47:09 chat rocketchat1[1053323]: {"level":50,"time":"2023-06-05T15:47:09.433Z","pid":1053323,"hostname":"chat.leepfrog.com","name":"System","msg":"Exception while invoking method getRoomByTypeAndName","err":{"type":"errorClass","message":"No permission [error-no-permission]","stack":"Error: No permission [error-no-permission]\n    at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:59:10)\n    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:74:34)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1902:12)\n    at packages/ddp-server/livedata_server.js:1820:15\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)\n    at packages/ddp-server/livedata_server.js:1818:36\n    at new Promise (<anonymous>)\n    at Server.applyAsync (packages/ddp-server/livedata_server.js:1817:12)\n    at Server.apply (packages/ddp-server/livedata_server.js:1756:26)\n    at Server.call (packages/ddp-server/livedata_server.js:1738:17)\n    at Object.post (app/api/server/v1/misc.ts:554:27)\n    at app/api/server/api.js:463:96\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:463:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9\n => awaited here:\n    at Promise.await (/opt/chat.leepfrog.com/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)\n    at Server.apply (packages/ddp-server/livedata_server.js:1769:22)\n    at Server.call (packages/ddp-server/livedata_server.js:1738:17)\n    at Object.post (app/api/server/v1/misc.ts:554:27)\n    at app/api/server/api.js:463:96\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:463:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":"error-no-permission","reason":"No permission","details":{"method":"getRoomByTypeAndName"},"errorType":"Meteor.Error"},"msg":"No permission [error-no-permission]"}
Jun  5 10:47:09 chat rocketchat1[1053323]: {"level":35,"time":"2023-06-05T15:47:09.434Z","pid":1053323,"hostname":"chat.leepfrog.com","name":"API","method":"POST","url":"/api/v1/method.call/getRoomByTypeAndName","userId":"536RNDyN6ABJz6DpC","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","length":"119","host":"chat.leepfrog.com","referer":"https://chat.leepfrog.com/channel/phonegroup","remoteIP":"10.1.88.51","status":200,"responseTime":10}

**Comment by mddvul22** [comment]
We have discovered that happens when somebody converts a public channel to a public team channel.  Something seems to be functioning incorrectly, here.   Why are team channels searchable by the people who aren't part of the team?

**Comment by hugocostadev** [comment]
Hi @mddvul22 I tested in the latest branch at the time and cannot reproduce.

The `public team channel` it's from a private team?

**Comment by mddvul22** [comment]
Yes, I'm trying to get confirmation from the person who converted them, but I believe these were originally public channels not associated with a team.  Then, a _private_ team owner converted to a team channel.

**Comment by mddvul22** [comment]
Yes, members of the private team can see it.  Also, non-team members of the channel who were already members of the channel before it became a team channel can see it.

**Comment by mddvul22** [comment]
Yes.
