### ISSUE TITLE
LDAP channel sync  "admin is not a valid room name. [error-invalid-room-name]"

### ISSUE THREAD

**Issue by xoxys** [RocketChat/Rocket.Chat#29513]
Even if the channel `admin` exists, the LDAP channel sync is failing:

```json
{"level":50,"time":"2023-06-10T12:44:53.307Z","pid":1,"hostname":"rocketchat","name":"LDAP","err":{"type":"errorClass","message":"admin is not a valid room name. [error-invalid-room-name]","stack":"Error: admin is not a valid room name. [error-invalid-room-name]\n    at app/utils/server/lib/getValidRoomName.ts:50:9\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at ee/server/lib/ldap/Manager.ts:305:16\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","isClientSafe":true,"error":"error-invalid-room-name","reason":"admin is not a valid room name.","details":{"function":"RocketChat.getValidRoomName","channel_name":"admin"},"errorType":"Meteor.Error"},"msg":"admin is not a valid room name. [error-invalid-room-name]"}
```

Used configuration for `LDAP Group Channel Map`:

```
{
  "admin": ["admin"]
}
```

**Comment by xoxys** [comment]
Looks like channel names are checked in the same way as users, https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/app/utils/server/lib/getValidRoomName.ts#L7. As a result, channel names like `admin` are invalid for channels as well....

https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/app/lib/server/functions/validateName.ts#L4
https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/server/settings/accounts.ts#L306

Is this behavior expected?
