### ISSUE TITLE
Docker image rocketchat/rocket.chat:6.2.6 contains Rocket.Chat 6.2.5

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#29555]
### Description:

When firing up the Docker image `rocketchat/rocket.chat:6.2.6` from Docker Hub, it will identify itself as Rocket.Chat 6.2.5.

### Steps to reproduce:

1. Fire up an instance of MongoDB: `docker run --name mongo_test mongo:6.0.6 mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger`
2. Initialize the MongoDB replica set: `docker exec -it mongo_test mongosh localhost/rocketchat --eval "rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: 'localhost:27017' } ]})"`
3. Run Rocket.Chat: `docker run --name rocketchat_test -e MONGO_OPLOG_URL=mongodb://mongo:27017/local?directConnection=true -e MONGO_URL=mongodb://mongo:27017/rocketchat?directConnection=true --link mongo_test:mongo -p 127.0.0.1:3000:3000 rocketchat/rocket.chat:6.2.6`

### Expected behavior:

Rocket.Chat 6.2.6 will start. There will be no banner about a newer version being available. rocket.cat will not send me a message that nudges me to update to the most recent version.

### Actual behavior:

Rocket.Chat 6.2.5 will start. It shows a banner about a Rocket.Chat 6.2.6 being available. I receive a message from rocket.cat telling me to update to 6.2.6.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.6
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.6

### Client Setup Information

Issue is client-agnostic.

### Relevant logs:

```
Unable to find image 'rocketchat/rocket.chat:6.2.6' locally
6.2.6: Pulling from rocketchat/rocket.chat
26c5c85e47da: Already exists
96da4c1974ec: Already exists
286584c9c618: Already exists
ec51043fad6b: Already exists
10845595c672: Already exists
b484386b0838: Pull complete
3b9c8a194753: Pull complete
6d1bc50dcbc0: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:14726e4f376a32d8fbe7477a8c76062974575cbd9dccb643c9af14a9a5531469
Status: Downloaded newer image for rocketchat/rocket.chat:6.2.6
(node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
LocalStore: store created at
LocalStore: store created at
LocalStore: store created at
strict mode: missing type "object" for keyword "additionalProperties" at "#" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "#" (strictTypes)
strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes)
MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
{"level":40,"time":"2023-06-15T18:45:56.087Z","pid":1,"hostname":"0034f290dc30","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"}
Exception in callback of async function: errorClass [Error]: [You must set "intervalTimeInMS" property in rateLimiter for REST API endpoint]
    at APIClass.addRateLimiterRuleForRoutes (app/api/server/api.ts:377:10)
    at app/api/server/api.ts:349:10
    at Array.forEach (<anonymous>)
    at APIClass.reloadRoutesToRefreshRateLimiter (app/api/server/api.ts:347:16)
    at app/api/server/api.ts:1046:9
    at runWithEnvironment (packages/meteor.js:1417:24)
    at packages/meteor.js:1430:14
    at runWithEnvironment (packages/meteor.js:1417:24) {
  isClientSafe: true,
  error: 'You must set "intervalTimeInMS" property in rateLimiter for REST API endpoint',
  reason: undefined,
  details: undefined,
  errorType: 'Meteor.Error'
}
[2023-06-15T18:46:02.148Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/BROKER: Moleculer v0.14.21 is starting...
[2023-06-15T18:46:02.148Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/BROKER: Namespace: <not defined>
[2023-06-15T18:46:02.148Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/BROKER: Node ID: 2c0f2170-521e-450a-a789-fbaedbab247b
[2023-06-15T18:46:02.149Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/REGISTRY: Strategy: RoundRobinStrategy
[2023-06-15T18:46:02.149Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/REGISTRY: Discoverer: LocalDiscoverer
[2023-06-15T18:46:02.150Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/BROKER: Serializer: JSONSerializer
[2023-06-15T18:46:02.154Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/BROKER: Validator: FastestValidator
[2023-06-15T18:46:02.156Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/BROKER: Registered 13 middleware(s).
[2023-06-15T18:46:02.156Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/BROKER: Transporter: TcpTransporter
{"level":51,"time":"2023-06-15T18:46:02.172Z","pid":1,"hostname":"0034f290dc30","name":"DatabaseWatcher","msg":"Using change streams"}
[2023-06-15T18:46:02.233Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/TRANSIT: Connecting to the transporter...
[2023-06-15T18:46:02.235Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/TRANSPORTER: TCP server is listening on port 40613
[2023-06-15T18:46:02.236Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/TRANSPORTER: UDP Discovery is disabled.
[2023-06-15T18:46:02.236Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/TRANSPORTER: TCP Transporter started.
(node:1) [MONGODB DRIVER] Warning: cursor.count is deprecated and will be removed in the next major version, please use `collection.estimatedDocumentCount` or `collection.countDocuments` instead
[2023-06-15T18:46:02.745Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/REGISTRY: '$node' service is registered.
[2023-06-15T18:46:02.746Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/REGISTRY: 'matrix' service is registered.
[2023-06-15T18:46:02.746Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/$NODE: Service '$node' started.
[2023-06-15T18:46:02.746Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/MATRIX: Service 'matrix' started.
[2023-06-15T18:46:02.747Z] INFO  2c0f2170-521e-450a-a789-fbaedbab247b/BROKER: ✔ ServiceBroker with 2 service(s) started successfully in 580ms.
ufs: temp directory created at "/tmp/ufs"
+----------------------------------------------+
|                SERVER RUNNING                |
+----------------------------------------------+
|                                              |
|  Rocket.Chat Version: 6.2.5                  |
|       NodeJS Version: 14.21.3 - x64          |
|      MongoDB Version: 6.0.6                  |
|       MongoDB Engine: wiredTiger             |
|             Platform: linux                  |
|         Process Port: 3000                   |
|             Site URL: http://localhost:3000  |
|     ReplicaSet OpLog: Enabled                |
|          Commit Hash: 0d0fa6fe08             |
|        Commit Branch: HEAD                   |
|                                              |
+----------------------------------------------+
```

**Comment by TimmiORG** [comment]
Same for the tar version. Looks like the version number was not bumped up.

**Comment by flexoflow** [comment]
Same problem here...

**Comment by sampaiodiego** [comment]
thx everyone for letting us know.. we're using a new automation script to publish the release, but looks like the version bump on some key files is missing.. but I can guarantee it has the fix from the change log..

I'll be working on improving the automation to fix this asap

**Comment by metode-cz** [comment]
Same problem...
