### ISSUE TITLE
An error occurred when creating an index for collection "users: Server selection timed out after 30000 ms'

### ISSUE THREAD

**Issue by FuckingToasters** [RocketChat/Rocket.Chat#29586]
### Description:
Javascript Errorlog (seem to be in future.js but im not a js dev so i ain't sure)

### Steps to reproduce:
1. Visit https://hub.docker.com/_/rocket-chat
2. run commands:
    docker run --name db -d mongo:4.0 --smallfiles --replSet rs0 --oplogSize 128
    docker exec -ti db mongo --eval "printjson(rs.initiate())"
    docker run --name rocketchat --link db --env MONGO_OPLOG_URL=mongodb://db:27017/local -d rocket.chat
3. See Error Logs in portainer dashboard

### Expected behavior:
After setting up all containers, I expect that the site on port 3000 load as expected, which hover is not the case.

### Actual behavior:
After setting up mongodb & rocket.chat docker image, visiting the site on port 3000 don't seem to work and then, these error logs appear.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Debian 10
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog:  /
- NodeJS Version: /
- MongoDB Version: latest / 4.4

### Client Setup Information

- Desktop App or Browser Version: Firefox 114.0.1 64-bit
- Operating System: Windows 10

### Relevant logs:
rocketchat logs:
```
/app/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
errorClass [Error]: [An error occurred when creating an index for collection "users: Server selection timed out after 30000 ms]
    at Collection.createIndex (packages/mongo/collection.js:801:15)
    at setupUsersCollection (packages/accounts-base/accounts_server.js:1777:9)
    at new AccountsServer (packages/accounts-base/accounts_server.js:75:5)
    at packages/accounts-base/server_main.js:7:12
    at module (packages/accounts-base/server_main.js:19:31)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /app/bundle/programs/server/packages/accounts-base.js:2193:15
    at /app/bundle/programs/server/packages/accounts-base.js:2200:3
    at /app/bundle/programs/server/boot.js:369:38
    at Array.forEach (<anonymous>)
    at /app/bundle/programs/server/boot.js:210:21
    at /app/bundle/programs/server/boot.js:423:7
    at Function.run (/app/bundle/programs/server/profile.js:256:14)
    at /app/bundle/programs/server/boot.js:422:13 {
  isClientSafe: true,
  error: 'An error occurred when creating an index for collection "users: Server selection timed out after 30000 ms',
  reason: undefined,
  details: undefined,
  errorType: 'Meteor.Error'
}
```

mongodb logs:
```
t={"$date":"2023-06-20T09:45:17.634+00:00"} s=I c=- id=4939300 ctx=monitoring-keys-for-HMAC msg=Failed to refresh key cache attr={"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":10000}
```

**Comment by hugocostadev** [comment]
Hi @FuckingToasters could you share more details about the version that you are trying to install? 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by raffitz** [comment]
Greetings all,
I'm suffering from a similar issue.
The rocket.chat is version 6.2.0 (docker image rocket.chat:6.2.0), the database is mongodb 3.6.5-0 (docker image mvertes/alpine-mongo:3.6.5-0).

Rocket.chat container log:
```
/app/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
errorClass [Error]: [An error occurred when creating an index for collection "users: Server selection timed out after 30000 ms]
    at Collection.createIndex (packages/mongo/collection.js:801:15)
    at setupUsersCollection (packages/accounts-base/accounts_server.js:1777:9)
    at new AccountsServer (packages/accounts-base/accounts_server.js:75:5)
    at packages/accounts-base/server_main.js:7:12
    at module (packages/accounts-base/server_main.js:19:31)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /app/bundle/programs/server/packages/accounts-base.js:2193:15
    at /app/bundle/programs/server/packages/accounts-base.js:2200:3
    at /app/bundle/programs/server/boot.js:369:38
    at Array.forEach (<anonymous>)
    at /app/bundle/programs/server/boot.js:210:21
    at /app/bundle/programs/server/boot.js:423:7
    at Function.run (/app/bundle/programs/server/profile.js:256:14)
    at /app/bundle/programs/server/boot.js:422:13 {
  isClientSafe: true,
  error: 'An error occurred when creating an index for collection "users: Server selection timed out after 30000 ms',
  reason: undefined,
  details: undefined,
  errorType: 'Meteor.Error'
}
```

My mongo logs only show this:

```
2023-07-07T17:10:45.015+0000 I NETWORK  [listener] connection accepted from 172.17.0.8:34574 #8 (1 connection now open)
2023-07-07T17:10:45.082+0000 I NETWORK  [conn8] received client metadata from 172.17.0.8:34574 conn8: { driver: { name: "nodejs", version: "4.14.0" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "6.0.2-arch1-1" }, platform: "Node.js v14.21.2, LE (unified)|Node.js v14.21.2, LE (unified)" }
2023-07-07T17:11:14.713+0000 I NETWORK  [conn8] end connection 172.17.0.8:34574 (0 connections now open)
2023-07-07T17:11:21.970+0000 I NETWORK  [listener] connection accepted from 172.17.0.8:59538 #9 (1 connection now open)
2023-07-07T17:11:21.985+0000 I NETWORK  [conn9] received client metadata from 172.17.0.8:59538 conn9: { driver: { name: "nodejs", version: "4.14.0" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "6.0.2-arch1-1" }, platform: "Node.js v14.21.2, LE (unified)|Node.js v14.21.2, LE (unified)" }
2023-07-07T17:11:51.968+0000 I NETWORK  [conn9] end connection 172.17.0.8:59538 (0 connections now open)
2023-07-07T17:12:01.668+0000 I NETWORK  [listener] connection accepted from 172.17.0.8:53836 #10 (1 connection now open)
2023-07-07T17:12:01.683+0000 I NETWORK  [conn10] received client metadata from 172.17.0.8:53836 conn10: { driver: { name: "nodejs", version: "4.14.0" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "6.0.2-arch1-1" }, platform: "Node.js v14.21.2, LE (unified)|Node.js v14.21.2, LE (unified)" }
2023-07-07T17:12:31.628+0000 I NETWORK  [conn10] end connection 172.17.0.8:53836 (0 connections now open)
```
Repeatedly as the rocket.chat container repeatedly restarts and tries to connect.

**Comment by SeryiBaran** [comment]
same problem =(

**Comment by podelom** [comment]
same to me

**Comment by JeroenAdam** [comment]
Same issue here when restoring from backup.
I was doing a restore from backup and it worked exactly 1 time, I had my environment up.
After a docker compose down/up I'm experiencing this error.
I had set up mongo v5.0 like this:
1. docker compose up with  --replSet rs0
2. mongorestore
3. mongo shell: rs.initiate()
4. restart rocketchatcontainer and all working fine
5. docker compose down and stuck

**Comment by Aditya-PS-05** [comment]
@hugocostadev , I am interested to solve the issue. Can you assign me this issue?
