### ISSUE TITLE
Rocket Chat does not start after 6.2.8 update

### ISSUE THREAD

**Issue by jcklerk** [RocketChat/Rocket.Chat#29618]
### Description:

After updating to 2.6.8(latest) i cant acces rocket chat annymore.
due to missing object, deprecated error and migration number not found.

### Steps to reproduce:

Docker previous latest to new latest see Relevant logs of watchtower.

### Expected behavior:

That Rocket Chat just starts and runs the migrations successfully

### Actual behavior:

```
(node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
strict mode: missing type "object" for keyword "additionalProperties" at "#" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "#" (strictTypes)
strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes)
MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
2023-06-22T07:16:13.788Z 40 pid=1 hostname=cb1b5648114b name=VoIPService msg=Voip is not enabled. Cant start the service
/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^
Error: Can't find migration version 299
    at server/lib/migrations.ts:249:9
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at module (server/startup/migrations/xrun.js:8:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (/app/bundle/programs/server/app/app.js:1432004:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (/app/bundle/programs/server/app/app.js:1438609:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (/app/bundle/programs/server/app/app.js:1510342:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /app/bundle/programs/server/app/app.js:1525553:15
    at /app/bundle/programs/server/boot.js:369:38
    at Array.forEach (<anonymous>)
    at /app/bundle/programs/server/boot.js:210:21
    at /app/bundle/programs/server/boot.js:423:7
(node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
strict mode: missing type "object" for keyword "additionalProperties" at "#" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "#" (strictTypes)
strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes)
MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
2023-06-22T07:16:51.952Z 40 pid=1 hostname=cb1b5648114b name=VoIPService msg=Voip is not enabled. Cant start the service
2023-06-22T07:16:55.434Z 40 pid=1 hostname=cb1b5648114b name=Migrations msg=Not migrating, control is locked. Attempt 0/30. Trying again in 10 seconds.
2023-06-22T07:17:05.449Z 40 pid=1 hostname=cb1b5648114b name=Migrations msg=Not migrating, control is locked. Attempt 1/30. Trying again in 10 seconds.
```

### Server Setup Information:

- Version of Rocket.Chat Server: 2.6.8(latest)
- Operating System: 
- Deployment Method:  docker (protainer template)
- Number of Running Instances: 1
- MongoDB Version: 5.0

### Relevant logs:

Update log watchtower
```
time="2023-06-21T03:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T04:35:02Z" level=info msg="Found new docker.io/bitnami/mongodb:5.0 image (495d9bb8e48a)"
time="2023-06-21T04:35:05Z" level=info msg="Stopping /rocketchat-mongodb-1 (758888957d7b) with SIGTERM"
time="2023-06-21T04:35:10Z" level=info msg="Creating /rocketchat-mongodb-1"
time="2023-06-21T04:35:11Z" level=info msg="Removing image 962ecfbd3140"
time="2023-06-21T04:35:12Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=1 notify=no
time="2023-06-21T05:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T06:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T07:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T08:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T09:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T10:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T11:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T12:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T13:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T14:36:05Z" level=info msg="Found new registry.rocket.chat/rocketchat/rocket.chat:latest image (d76ff11d6c25)"
time="2023-06-21T14:36:06Z" level=info msg="Stopping /rocketchat-rocketchat-1 (2a3d1b3eb262) with SIGTERM"
time="2023-06-21T14:36:09Z" level=info msg="Creating /rocketchat-rocketchat-1"
time="2023-06-21T14:36:10Z" level=info msg="Removing image e6efd72ac6f8"
time="2023-06-21T14:36:26Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=1 notify=no
time="2023-06-21T15:34:42Z" level=info msg="Unable to update container \"/rocketchat-rocketchat-1\": Error response from daemon: manifest for registry.rocket.chat/rocketchat/rocket.chat:latest not found: manifest unknown: manifest unknown. Proceeding to next."
time="2023-06-21T15:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T16:34:42Z" level=info msg="Unable to update container \"/rocketchat-rocketchat-1\": Error response from daemon: manifest for registry.rocket.chat/rocketchat/rocket.chat:latest not found: manifest unknown: manifest unknown. Proceeding to next."
time="2023-06-21T16:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T17:34:42Z" level=info msg="Unable to update container \"/rocketchat-rocketchat-1\": Error response from daemon: manifest for registry.rocket.chat/rocketchat/rocket.chat:latest not found: manifest unknown: manifest unknown. Proceeding to next."
time="2023-06-21T17:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T18:36:07Z" level=info msg="Found new registry.rocket.chat/rocketchat/rocket.chat:latest image (f805549bcc1b)"
time="2023-06-21T18:36:09Z" level=info msg="Stopping /rocketchat-rocketchat-1 (bbc505cf6f06) with SIGTERM"
time="2023-06-21T18:36:11Z" level=info msg="Creating /rocketchat-rocketchat-1"
time="2023-06-21T18:36:12Z" level=info msg="Removing image d76ff11d6c25"
time="2023-06-21T18:36:28Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=1 notify=no
time="2023-06-21T19:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T20:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T21:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T22:34:44Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-21T23:34:51Z" level=info msg="Unable to update container \"/rocketchat-rocketchat-1\": Error response from daemon: Get \"https://registry.rocket.chat/v2/\": net/http: TLS handshake timeout. Proceeding to next."
time="2023-06-21T23:34:53Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
time="2023-06-22T00:34:53Z" level=info msg="Session done" Failed=0 Scanned=4 Updated=0 notify=no
```

**Comment by Noahsarker** [comment]
same issue

**Comment by Dnouv** [comment]
Thank you for opening the issue; it looks like there is a mismatch in the migration version. You could try updating the migrations collection in MongoDB as shown below:
```js
use rocketchat; // make sure to be on the correct database
db.migrations.updateOne({ _id: 'control' }, { $set: { version: 294, locked: false } });
```
(To execute this command, you need to have access to the MongoDB shell.)

**Comment by jcklerk** [comment]
> Thank you for opening the issue; it looks like there is a mismatch in the migration version. You could try updating the migrations collection in MongoDB as shown below:
> 
> ```js
> use rocketchat; // make sure to be on the correct database
> db.migrations.updateOne({ _id: 'control' }, { $set: { version: 294, locked: false } });
> ```
> 
> (To execute this command, you need to have access to the MongoDB shell.)
> 
> PS. Could you please correct the issue title? If I am not mistaken, you might be referring to the latest `6.2.8` version and not `2.6.8`

This fixed the issue 🤩
