### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by kertiskz** [RocketChat/Rocket.Chat#29740]
After updating to 6.2.8, an error appears in the log every 2 minutes
```
Error: ENOENT: no such file or directory, stat '/tmp/zipFiles/87e62a59-9fc8-452e-9f97-2ea84821861b.zip'
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at server/lib/dataExport/uploadZipFile.ts:11:16
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at server/lib/dataExport/processDataDownloads.ts:226:25
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/tmp/zipFiles/87e62a59-9fc8-452e-9f97-2ea84821861b.zip'
}
```

Server Setup Information

Version of Rocket.Chat Server: 6.2.9
Operating System: synology
Deployment Method: docker
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
NodeJS Version: 14.21.3
MongoDB Version: 6.0.7

**Comment by Deplee** [comment]
did u got a solutions for this ?
