### ISSUE TITLE
FatalProcessOutOfMemory

### ISSUE THREAD

**Issue by BoJackBR** [RocketChat/Rocket.Chat#29875]
Hello everyone,

I’m having an issue here, and I’m not sure if anyone has experienced this before. After updating to version 6.2.10, the rocketchat service has been causing problems at least twice a day. The service stops, and I have to restart it to get it back to normal.
These are the logs I managed to collect when it stopped:

**systemctl status rocketchat.service**
```
rocketchat.service - The Rocket.Chat server
     Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
     Active: failed (Result: core-dump) since Tue 2023-07-18 10:09:38 -03; 28min ago
    Process: 881 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=dumped, signal=ABRT)
   Main PID: 881 (code=dumped, signal=ABRT)

Jul 20 10:09:38 rocketchat.damapel.com.br rocketchat[881]:  4: 0xb9a327 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
Jul 20 06:09:38 rocketchat.damapel.com.br rocketchat[881]:  5: 0xd3a735  [/usr/local/bin/node]
Jul 20 10:09:38 rocketchat.damapel.com.br rocketchat[881]:  6: 0xd49a74  [/usr/local/bin/node]
Jul 20 10:09:38 rocketchat.damapel.com.br rocketchat[881]:  7: 0xd49d25 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/l>
Jul 20 10:09:38 rocketchat.damapel.com.br rocketchat[881]:  8: 0xd4c6ec v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::interna>
Jul 20 10:09:38 rocketchat.damapel.com.br rocketchat[881]:  9: 0xd1bd8b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
Jul 20 10:09:38 rocketchat.damapel.com.br rocketchat[881]: 10: 0x104c56f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
Jul 20 10:09:38 rocketchat.damapel.com.br rocketchat[881]: 11: 0x13a6259  [/usr/local/bin/node]
Jul 20 10:09:38 rocketchat.damapel.com.br systemd[1]: rocketchat.service: Main process exited, code=dumped, status=6/ABRT
Jul 20 10:09:38 rocketchat.damapel.com.br systemd[1]: rocketchat.service: Failed with result 'core-dump'.
```

tail -n 100 /var/log/syslog

```
Jul 20 10:09:23 rocketchat rocketchat[281186]: =================================
Jul 20 10:09:23 rocketchat rocketchat[281186]: === UnHandledPromiseRejection ===
Jul 20 10:09:23 rocketchat rocketchat[281186]: RangeError: Out of memory
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at Fiber.<anonymous> (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92:16)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at Fiber.run (packages/rocketchat:mongo-config/server/index.js:32:13)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at FibersContextStore.run (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/core-services/dist/lib/ContextStore.js:27:12)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at LocalBroker.call (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/core-services/dist/LocalBroker.js:14:51)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at Api.call (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/core-services/dist/lib/Api.js:30:29)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at Proxy.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/core-services/dist/lib/proxify.js:7:95)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at server/modules/listeners/listeners.module.ts:242:45
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jul 20 10:09:23 rocketchat rocketchat[281186]:  => awaited here:
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at server/modules/listeners/listeners.module.ts:242:17
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jul 20 10:09:23 rocketchat rocketchat[281186]: ---------------------------------
Jul 20 10:09:23 rocketchat rocketchat[281186]: Errors like this can cause oplog processing errors.
Jul 20 10:09:23 rocketchat rocketchat[281186]: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Jul 20 10:09:23 rocketchat rocketchat[281186]: Future node.js versions will automatically exit the process
Jul 20 10:09:23 rocketchat rocketchat[281186]: =================================
```

**Server Setup Information**
Version of Rocket.Chat Server: 6.2.10
Operating System: Ubuntu Server 20.04
Deployment Method: Manual
NodeJS Version: 14.0.0
MongoDB Version: 4.4.22
Proxy: No
Firewalls involved: No

**Any additional Information**
Virtualized on Proxmox
![image](https://github.com/RocketChat/Rocket.Chat/assets/35930902/4326f281-a3b3-472e-b9e3-e51834c1d1a9)

**Comment by debdutdeb** [comment]
could you please share some log lines above the error, to get an idea of what it was doing?

**Comment by BoJackBR** [comment]
Sure.

```
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'q29r6F6YPA588gXNQ',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-user-presence',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [ '', { added: [Array] } ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'u8Jn6rYLsXxcHWeZc',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-room-messages',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [ 'BY4pChigKq22yX2if', { useCollection: false, args: [] } ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'BnK2m3Fw6MMWMswAp',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-user',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [ 'MzXDzZ8YspzBXeRmv/userData', { useCollection: false, args: [] } ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'deo4KpDgCfH4kLcPz',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-room',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     'BY4pChigKq22yX2if/deleteMessage',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'pNTZnCgaZobPxXqWF',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-room-messages',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     '4YjJWXF64KLi9Ek8XMzXDzZ8YspzBXeRmv',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'FYsnWkZcTBWyZZMyq',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-room',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     'BY4pChigKq22yX2if/deleteMessageBulk',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'NKZrS3czeGwNeYBv3',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-room',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     '4YjJWXF64KLi9Ek8XMzXDzZ8YspzBXeRmv/deleteMessage',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'y7dk9seu7fQppF5KQ',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-room-messages',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     'MPSMQyddSjjzoyC7xQZsCMcx5ikpnftyQS',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'whwRgTovdHDENb9R9',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-room',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     '4YjJWXF64KLi9Ek8XMzXDzZ8YspzBXeRmv/deleteMessageBulk',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'mo5imGT74qBNseFBg',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-room',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     'MPSMQyddSjjzoyC7xQZsCMcx5ikpnftyQS/deleteMessage',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'uWSHWRNvgZbx5y7xg',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-room',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     'ntkaojeTZF8kvmgEi/user-activity',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'G8tr2FQJf3DfWT4Ar',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-room',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     'MPSMQyddSjjzoyC7xQZsCMcx5ikpnftyQS/deleteMessageBulk',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message { msg: 'unsub', id: 'BnK2m3Fw6MMWMswAp' }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'jEDepYuyXHzxw2JYy',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-room-messages',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     'QZsCMcx5ikpnftyQSsQuatZHdjfeErMGmK',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'yhDcxWCHr5YiQ7mAM',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-user',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [ 'MzXDzZ8YspzBXeRmv/userData', { useCollection: false, args: [] } ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'N7KDMTQneJAmXsEwf',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-room',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     'QZsCMcx5ikpnftyQSsQuatZHdjfeErMGmK/deleteMessage',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'NafqNPG59S8CHFeLz',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-room',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     'QZsCMcx5ikpnftyQSsQuatZHdjfeErMGmK/deleteMessageBulk',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'BLhk2qyoK6QC8uQo9',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-room',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [
Jul 20 10:09:16 rocketchat rocketchat[281186]:     'BRPr4Df7quPvzF3MrQZsCMcx5ikpnftyQS/user-activity',
Jul 20 10:09:16 rocketchat rocketchat[281186]:     { useCollection: false, args: [] }
Jul 20 10:09:16 rocketchat rocketchat[281186]:   ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'qvStQb5muiAJk2A3r',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-user',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [ 'QZsCMcx5ikpnftyQS/userData', { useCollection: false, args: [] } ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message { msg: 'unsub', id: 'qvStQb5muiAJk2A3r' }
Jul 20 10:09:16 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:16 rocketchat rocketchat[281186]:   msg: 'sub',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   id: 'hPGh3fybpGbmYJaRG',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   name: 'stream-notify-user',
Jul 20 10:09:16 rocketchat rocketchat[281186]:   params: [ 'QZsCMcx5ikpnftyQS/userData', { useCollection: false, args: [] } ]
Jul 20 10:09:16 rocketchat rocketchat[281186]: }
Jul 20 10:09:17 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:17 rocketchat rocketchat[281186]:   msg: 'connect',
Jul 20 10:09:17 rocketchat rocketchat[281186]:   session: 'y2Zpzgh6tCdf9oaXD',
Jul 20 10:09:17 rocketchat rocketchat[281186]:   version: '1',
Jul 20 10:09:17 rocketchat rocketchat[281186]:   support: [ '1', 'pre2', 'pre1' ]
Jul 20 10:09:17 rocketchat rocketchat[281186]: }
Jul 20 10:09:17 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:17 rocketchat rocketchat[281186]:   msg: 'connect',
Jul 20 10:09:17 rocketchat rocketchat[281186]:   session: 'ccs2aMk3MtgJC44ah',
Jul 20 10:09:17 rocketchat rocketchat[281186]:   version: '1',
Jul 20 10:09:17 rocketchat rocketchat[281186]:   support: [ '1', 'pre2', 'pre1' ]
Jul 20 10:09:17 rocketchat rocketchat[281186]: }
Jul 20 10:09:18 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:18 rocketchat rocketchat[281186]:   msg: 'connect',
Jul 20 10:09:18 rocketchat rocketchat[281186]:   session: 'a39zvL9F4tEk2xF7X',
Jul 20 10:09:18 rocketchat rocketchat[281186]:   version: '1',
Jul 20 10:09:18 rocketchat rocketchat[281186]:   support: [ '1', 'pre2', 'pre1' ]
Jul 20 10:09:18 rocketchat rocketchat[281186]: }
Jul 20 10:09:20 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:20 rocketchat rocketchat[281186]:   msg: 'connect',
Jul 20 10:09:20 rocketchat rocketchat[281186]:   session: 'gEwzjsq2fPsyaWfCD',
Jul 20 10:09:20 rocketchat rocketchat[281186]:   version: '1',
Jul 20 10:09:20 rocketchat rocketchat[281186]:   support: [ '1', 'pre2', 'pre1' ]
Jul 20 10:09:20 rocketchat rocketchat[281186]: }
Jul 20 10:09:20 rocketchat rocketchat[281186]: Internal exception while processing message { msg: 'unsub', id: 'd8aDQaYr8gHqwnNus' }
Jul 20 10:09:21 rocketchat rocketchat[281186]: Internal exception while processing message {
Jul 20 10:09:21 rocketchat rocketchat[281186]:   msg: 'connect',
Jul 20 10:09:21 rocketchat rocketchat[281186]:   session: 'MFGLG4aLLRnimgr6A',
Jul 20 10:09:21 rocketchat rocketchat[281186]:   version: '1',
Jul 20 10:09:21 rocketchat rocketchat[281186]:   support: [ '1', 'pre2', 'pre1' ]
Jul 20 10:09:21 rocketchat rocketchat[281186]: }
Jul 20 10:09:23 rocketchat rocketchat[281186]: === UnHandledPromiseRejection ===
Jul 20 10:09:23 rocketchat rocketchat[281186]: RangeError: Out of memory
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at Fiber.<anonymous> (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92:16)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at Fiber.run (packages/rocketchat:mongo-config/server/index.js:32:13)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at FibersContextStore.run (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/core-services/dist/lib/ContextStore.js:27:12)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at LocalBroker.call (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/core-services/dist/LocalBroker.js:14:51)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at Api.call (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/core-services/dist/lib/Api.js:30:29)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at Proxy.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/core-services/dist/lib/proxify.js:7:95)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at server/modules/listeners/listeners.module.ts:242:45
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jul 20 10:09:23 rocketchat rocketchat[281186]:  => awaited here:
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at server/modules/listeners/listeners.module.ts:242:17
Jul 20 10:09:23 rocketchat rocketchat[281186]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jul 20 10:09:23 rocketchat rocketchat[281186]: ---------------------------------

```

**Comment by MBraunshausen** [comment]
Hi @BoJackBR Did you manage get rid of this problem? I'm actually facing the same problem. Thank you.

**Comment by MBraunshausen** [comment]
okay. Thank you for answering.
