### ISSUE TITLE
Meteor not starting 

### ISSUE THREAD

**Issue by paragcopods** [RocketChat/Rocket.Chat#29910]
### Description:
I am running the self hosted version of RocketChat. However after all the installation when I am trying to do `yarn dev` I am getting the following error.

I had followed the official guide of installation.
[Link to reference](https://developer.rocket.chat/open-source-projects/server/server-environment-setup/mac-osx#troubleshooting)

Apple MacBook Air M1 16GB | MacOS Ventura 

### Relevant logs:
```
Started MongoDB.
Linted your app. No linting errors.
[2023-07-25T10:17:38.547Z] ERROR (System/49928 on Parag-Chirde---Copods.local): Invalid setting code SMS_Mobex_from_number: Setting SMS_Mobex_from_number is of type int but got string
[2023-07-25T10:17:38.547Z] ERROR (System/49928 on Parag-Chirde---Copods.local): Invalid setting stored SMS_Mobex_from_number: Setting SMS_Mobex_from_number is of type int but got string
[2023-07-25T10:17:38.637Z] ERROR (System/49928 on Parag-Chirde---Copods.local): Invalid setting code Cloud_Workspace_Client_Secret_Expires_At: Setting Cloud_Workspace_Client_Secret_Expires_At is of type int but got string
[2023-07-25T10:17:38.637Z] ERROR (System/49928 on Parag-Chirde---Copods.local): Invalid setting stored Cloud_Workspace_Client_Secret_Expires_At: Setting Cloud_Workspace_Client_Secret_Expires_At is of type int but got string
strict mode: missing type "object" for keyword "additionalProperties" at "#" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "#" (strictTypes)
strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes)
/Users/copods/.meteor/packages/promise/.0.12.2.z1jbmm.nui8i++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Cannot find module './build/Release/binding.node'
Require stack:
- /Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/node_modules/@kaciras/deasync/index.js
- /Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/npm-require.js
- /Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/boot.js
- /Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/.meteor/local/build/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/node_modules/@kaciras/deasync/index.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module.Mp._compile (/Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (/Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:105:23)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at npmRequire (/Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/npm-require.js:111:12)
    at Module.useNode (packages/modules-runtime.js:751:18)
    at module (/Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/packages/modules.js:203830:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/copods/.meteor/packages/modules/.0.19.0.1sxjj2p.errn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (/Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/app/app.js:1458157:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/copods/.meteor/packages/modules/.0.19.0.1sxjj2p.errn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (app/apps/server/bridges/http.ts:119:2)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/copods/.meteor/packages/modules/.0.19.0.1sxjj2p.errn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (app/apps/server/bridges/api.ts:130:2)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/copods/.meteor/packages/modules/.0.19.0.1sxjj2p.errn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (app/apps/server/bridges/http.ts:119:2)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/node_modules/@kaciras/deasync/index.js',
    '/Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/npm-require.js',
    '/Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/boot.js',
    '/Users/copods/Desktop/Pc/Programming/RocketChat/Rocket.Chat/apps/meteor/.meteor/local/build/main.js'
  ]
}
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by paragcopods** [comment]
Node version: `v14.21.3`
Meteor version: `Meteor 2.12`

**Comment by hugocostadev** [comment]
Seems that something didn't build correctly ... 
Follow these steps:
1. Make sure that the node and meteor version is what you the project needs (if you are using `nvm` check in the terminal the version of node)
2. Delete all `node_modules` from your project (in the project folder run: `find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +`)
3. run `yarn && yarn build && yarn dsv`

Let me know if works

**Comment by paragcopods** [comment]
I did follow the following steps, ensured proper versions are maintained as required. Still I am facing the similar scenario. 

However, when I ran the exact repo on an Apple MacBook with Intel chip it was running just fine. Can it be the case that these issues are because of Silicon chip? (Just a thought)

<img width="1431" alt="Screenshot 2023-07-26 at 10 09 33 AM" src="https://github.com/RocketChat/Rocket.Chat/assets/138485058/524ab474-e2df-4d3b-958d-6b00acaa0647">

**Comment by paragcopods** [comment]
@hugocostadev Can you assist?

**Comment by GleidsonDaniel** [comment]
Still a issue on m1 devices

**Comment by klp123** [comment]
@paragcopods  Did you able to resolve it? I am also facing the similar issue.

**Comment by GleidsonDaniel** [comment]
You have to run:
`yarn add deasync
`
And set in package.json:
```
"dependencies": {
    "node-gyp": "^9.4.0"
}
```

This way it worked here

But yes, it's still an issue on m1 macbooks, without this "fix" I couldn't run it at all.

**Comment by GleidsonDaniel** [comment]
Let's go, how to fix this error on m1 devices.
Clone the repo from scratch and follow these steps:
https://developer.rocket.chat/open-source-projects/server/server-environment-setup/mac-osx

Following the steps up to the yarn step, this error will occur:
```
➤ YN0009: │ @kaciras/deasync@npm:1.0.3 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/t6/7657725n60ngdypfmvk5kzw40000gn/T/xfs-c242bdac/build.log)
➤ YN0009: │ fibers@npm:5.0.3 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/t6/7657725n60ngdypfmvk5kzw40000gn/T/xfs-9abf92ec/build.log)
➤ YN0009: │ fibers@npm:5.0.3 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/t6/7657725n60ngdypfmvk5kzw40000gn/T/xfs-67e8cb77/build.log)
➤ YN0009: │ fibers@npm:5.0.3 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/t6/7657725n60ngdypfmvk5kzw40000gn/T/xfs-465834d5/build.log)
➤ YN0000: └ Completed in 47s 161ms
➤ YN0000: Failed with errors in 5m 58s
```

The doc itself has a step-by-step guide on how to resolve the fibers error (Sometimes you have to do this step more than once, but it works):
https://developer.rocket.chat/open-source-projects/server/server-environment-setup/mac-osx#troubleshooting

So when you run `yarn` again the error that will remain will be deadsync:
```
➤ YN0007: │ @kaciras/deasync@npm:1.0.3 must be built because it never has been before or the last one failed
➤ YN0009: │ @kaciras/deasync@npm:1.0.3 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/t6/7657725n60ngdypfmvk5kzw40000gn/T/xfs-1a2416d3/build.log)
➤ YN0000: └ Completed in 3s 142ms
➤ YN0000: Failed with errors in 5s 357ms
```

In this case you can try two solutions:
`yarn add deasync`
if does not work
`yarn add node-gyp` (not global)

After running `yarn add`, you can see that this error will appear in some of the logs:
`@kaciras/deasync@npm:1.0.3 must be built because it never has been before or the last one failed`
Complete log:
```
➤ YN0000: └ Completed in 3s 838ms
➤ YN0000: ┌ Link step
➤ YN0008: │ rocket.chat@workspace:. must be rebuilt because its dependency tree changed
➤ YN0007: │ @kaciras/deasync@npm:1.0.3 must be built because it never has been before or the last one failed
➤ YN0008: │ bcrypt@npm:5.0.1 must be rebuilt because its dependency tree changed
➤ YN0008: │ isolated-vm@npm:4.4.2 must be rebuilt because its dependency tree changed
➤ YN0008: │ sharp@npm:0.30.7 must be rebuilt because its dependency tree changed
➤ YN0008: │ sodium-native@npm:3.3.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ gc-stats@npm:1.4.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=18f3a7 must be rebuilt because its dependency tree changed
➤ YN0008: │ event-loop-stats@npm:1.4.1 must be rebuilt because its dependency tree changed
➤ YN0000: └ Completed in 13s 670ms
➤ YN0000: Done with warnings in 23s 668ms
```

then run `yarn` again and it will compile deasync.
Here is the yarn log without the deasync error:
```
➤ YN0002: │ @storybook/addon-postcss@npm:2.0.0 doesn't provide webpack (pb2910), requested by css-loader
➤ YN0002: │ @storybook/addon-postcss@npm:2.0.0 doesn't provide webpack (pec374), requested by postcss-loader
➤ YN0002: │ @storybook/addon-postcss@npm:2.0.0 doesn't provide webpack (pe4518), requested by style-loader
➤ YN0002: │ @storybook/docs-tools@npm:6.5.16 doesn't provide react (p9b542), requested by @storybook/store
➤ YN0002: │ @storybook/docs-tools@npm:6.5.16 doesn't provide react-dom (pc910b), requested by @storybook/store
➤ YN0002: │ @storybook/mdx1-csf@npm:0.0.1 doesn't provide @babel/core (pd5d6b), requested by @babel/preset-env
➤ YN0002: │ @storybook/telemetry@npm:6.5.16 doesn't provide react (p48f29), requested by @storybook/core-common
➤ YN0002: │ @storybook/telemetry@npm:6.5.16 doesn't provide react-dom (p479a1), requested by @storybook/core-common
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 598ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1s 163ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 1s 456ms
➤ YN0000: Done with warnings in 3s 671ms
```
And then just run `yarn dev` or `yarn dsv`

You don't need to commit the changes, this install was just to force deasync to compile for arm.
If it doesn't work, review the steps and check if you are following them correctly, following these steps works 100%, tested more than once from scratch.
