### ISSUE TITLE
Can't create initial ADMIN from Docker

### ISSUE THREAD

**Issue by icemagno** [RocketChat/Rocket.Chat#29931]
### Description:

When I try to start a Docker container passing ADMIN_* variables it gives me an error

### Steps to reproduce:

Start a container:

```
docker run --name rocket-chat --hostname=rocket-chat  \
-v /etc/localtime:/etc/localtime:ro \
-v /srv/rocket:/home/rocket \
-e ROOT_URL=http://thisisnotmyhost:36300 \
-e MONGO_URL=mongodb://rocket-db:27017/rocketchat?replicaSet=rs0 \
-e MONGO_OPLOG_URL=mongodb://rocket-db:27017/local?replicaSet=rs0 \
-e ADMIN_USERNAME="allmightygod" \
-e ADMIN_NAME="MrRobbot" \
-e ADMIN_EMAIL="admin@thefunnydomain.com" \
-e ADMIN_PASS="myverygoodpassword" \
-e OVERWRITE_SETTING_Show_Setup_Wizard=completed \
-p 36300:3000 \
-d registry.rocket.chat/rocketchat/rocket.chat
```

### Expected behavior:

The server admin was created

### Actual behavior:

No admin is created and the console throws an error related to this

### Server Setup Information:

```
+--------------------------------------------------+
|                  SERVER RUNNING                  |
+--------------------------------------------------+
|                                                  |
|  Rocket.Chat Version: 6.2.11                     |
|       NodeJS Version: 14.21.3 - x64              |
|      MongoDB Version: 5.0.19                     |
|       MongoDB Engine: wiredTiger                 |
|             Platform: linux                      |
|         Process Port: 3000                       |
|             Site URL: http://really:36300        |
|     ReplicaSet OpLog: Enabled                    |
|          Commit Hash: 5c2eb939bf                 |
|        Commit Branch: HEAD                       |
|                                                  |
+--------------------------------------------------+
```

### Client Setup Information

N/A

### Additional context

N/A

### Relevant logs:

```
Inserting admin user:
Name: MrRobbot
Email: admin@thefunnydomain.com
Username: allmightygod
=== UnHandledPromiseRejection ===
errorClass [Error]: Match error: Expected string, got object
    at check (packages/check/match.js:36:17)
    at packages/accounts-password/password_server.js:324:3
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at server/startup/initialData.js:122:4
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
  path: '',
  sanitizedError: errorClass [Error]: Match failed [400]
      at errorClass.<anonymous> (packages/check/match.js:91:27)
      at new errorClass (packages/meteor.js:692:17)
      at check (packages/check/match.js:36:17)
      at packages/accounts-password/password_server.js:324:3
      at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
    isClientSafe: true,
    error: 400,
    reason: 'Match failed',
    details: undefined,
    errorType: 'Meteor.Error'
  },
  errorType: 'Match.Error'
}
```

**Comment by icemagno** [comment]
Seems I don't need any ```ADMIN_*``` variable because they are only for REST tests. All I need is to set wich USER ID I want to be administrator.

So setting ```INITIAL_USER=1``` makes my first user to become administrator, although the documentation shows that INITIAL_USER must be ```yes``` ( https://docs.rocket.chat/setup-and-configure/accessing-your-workspace/creating-the-first-administrator )

At least that's how it happened.

**Comment by hugocostadev** [comment]
Thanks for letting us know @icemagno ... we will update our docs
