### ISSUE TITLE
[6.3.0] - LDAP login not working for (some) existing users

### ISSUE THREAD

**Issue by svenseeberg** [RocketChat/Rocket.Chat#30034]
### Description:

When users log in via LDAP, some users 

### Steps to reproduce:

1. Configure LDAP Login
2. Login as a LDAP user and log out
3. log back in

### Expected behavior:

Login should work

### Actual behavior:

Login does not work. Wrong passwords show a notification, but the correct password shows no message at all in the GUI. The log shows the following entry:
```
{"level":50,"time":"2023-08-04T14:30:35.899Z","pid":1882221,"hostname":"rocketchat","name":"LDAP Data Converter","err":{"type":"errorClass","message":"Username already exists. [403]","stack":"Error: Username already exists. [403]<br>    at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1206:15)<br>    at app/authentication/server/startup/index.js:300:28<br>    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at AccountsServer.Accounts.insertUserDoc (app/authentication/server/startup/index.js:355:17)<br>    at app/importer/server/classes/ImportDataConverter.ts:372:19<br>    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/importer/server/classes/ImportDataConverter.ts:523:18<br>    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","isClientSafe":true,"error":403,"reason":"Username already exists.","errorType":"Meteor.Error"},"msg":"Username already exists. [403]"} 
```

Interestingly, the setting to merge existing users is already set to on.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0
- Operating System: Debian 11
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.19

### Client Setup Information

- Desktop App or Browser Version: Browser/Firefox
- Operating System: Any

**Comment by pierre-lehnen-rc** [comment]
Hi! 
On 6.3 we changed the query that searches for existing users to merge with the LDAP user, but those changes should not have any effect on users that were already using LDAP to authenticate. The only explanation I can think of is that something was already failing on your setup and before this update the user merge was working as fallback.

Do you have access to the user's data on mongodb? If so I would like you to check some things (If the login is failing for multiple/all users, checking one of them is enough):
1. Does the user have something stored on `services.ldap`? There should be two attributes there: `id` and `idAttribute`;
2. How many emails do the user have? Is there any uppercase letter in their email?
3. Is there any special character in their username? 
4. Has any of their information changed on LDAP since their last succesful login?

**Comment by svenseeberg** [comment]
>     1. Does the user have something stored on `services.ldap`? There should be two attributes there: `id` and `idAttribute`;

```json
{
	"_id" : "SOMEID",
	"createdAt" : ISODate("2021-02-15T19:03:09.313Z"),
	"services" : {
		"password" : {
			"bcrypt" : "$2b$10$SECRETHASH"
		},
		"email2fa" : {
			"enabled" : true,
			"changedAt" : ISODate("2021-02-15T19:03:09.313Z")
		},
		"ldap" : {
			"id" : "INTERNALID",
			"idAttribute" : "uid"
		},
...
}
```

>     2. How many emails do the user have? Is there any uppercase letter in their email?

In 1 case there are actually 2 addresses, but in the other cases only 1.

>     3. Is there any special character in their username?

No, only `[a-zA-Z]`.
 
>     4. Has any of their information changed on LDAP since their last succesful login?

No, not that we are aware of. I will investigate this further.

**Comment by herczmanntamasandrews** [comment]
same here, 6.3.0 in docker, cant login from any browser or desktop app

**Comment by herczmanntamasandrews** [comment]
in our case the problem was the following:

- we had an old ldap server and somewhere in the past we changed this ldap backend to an Active Directory
- users that logged in before the change had uid, users that logged in after the change had objectGUID as Unique Identifier Field
- the uid attribute is empty in the AD
- no idea why the users could login without problem until now

solution:

in mongo we updated all users like this:

db.users.update({ username: "USERNAME" }, { $set: { "services.ldap.idAttribute": "objectGUID" }})
db.users.update({ username: "USERNAME" }, { $set: { "services.ldap.id": "objectGUID-IN-HEX" }})

**important!** the objectGUID need to be inserted in hexadecimal

we exported the users from the ad with the objectGUID like this (filtered for the rocketchat group membership):

 Csvde -f C:\export.txt -r "(|(objectclass=user))" -l objectguid,samaccountname 
 
 and parsed the info in a script, that makes the changes above

i hope this helps

**Comment by pierre-lehnen-rc** [comment]
Thank you, that clarifies what's happening.
It looks like if the id/idAttribute changed at any point since the user's first login on rocket.chat, they can no longer login on 6.3.

I'll be opening a PR with the fix soon.

**Comment by pierre-lehnen-rc** [comment]
In 6.3 we fixed an issue with users who have special characters in their usernames. The special character will be removed when using that username on rocket.chat. Then, to prevent users from impersonating others by simply adding a special character to their ldap username, we changed the search by username to ignore any users that already have ldap information (`ldap: true` in their data).

There should not have been any issue if the user was being found through their `id`/`idAttribute` values (nothing changed on 6.3 regarding that), but if that search fails, the subsequent search by username/email no longer works on 6.3.

The issue here is that if the LDAP settings change, it may start loading different values for `id` and `idAttribute` and stop finding the rocket.chat users on login.

If the setting `Update User Data on Login` is enabled, then only new changes to users or ldap settings will prevent them from logging in. If that setting was disabled, then any change that happened in the past will also make users unable to login starting on 6.3.

I'm working on a fix here that we'll release in a patch, but in the meantime you can also get login working again if you set user's `ldap` attribute to false (NOT `services.ldap`).

**Comment by pierre-lehnen-rc** [comment]
> Oh, just saw that newer users have idAttribute `uidNumber` in MongoDB. That one will not match with the username at all because it's numeric, but it did work for those users until 6.2. Where is `idAttribute` taken from?

It doesn't need to match the username, it just needs to be an unique value on LDAP. `idAttribute` is the first attribute from `Unique Identifier Field` that had a valid value on the user data.

Rocket.Chat doesn't use the `Unique Idenitifier Field` to search for the user on LDAP, it uses it to find the matching user on the rocket.chat users collection. In theory this value should never change, but we failed to consider situations where the settings are modified after the initial setup, or that the LDAP backend itself may be changed.

**Comment by svenseeberg** [comment]
I'm not sure, if this is related. I have a set of (old?) users that can not log in.

The old user, which cannot log in, has the following properties in the database:
```
		"ldap" : {
			"id" : "1234567890abcdef",
			"idAttribute" : "uid"
		},
```
The LDAP log looks like this:
```
Aug 21 13:05:11 user slapd[10604]: conn=185959 fd=24 ACCEPT from IP=135.181.100.167:35740 (IP=0.0.0.0:7636)
Aug 21 13:05:11 user slapd[10604]: conn=185959 fd=24 TLS established tls_ssf=256 ssf=256
Aug 21 13:05:11 user slapd[10604]: conn=185959 op=0 BIND dn="uid=chat,dc=example,dc=de" method=128
Aug 21 13:05:11 user slapd[10604]: conn=185959 op=0 BIND dn="uid=chat,dc=example,dc=de" mech=SIMPLE ssf=0
Aug 21 13:05:11 user slapd[10604]: conn=185959 op=0 RESULT tag=97 err=0 text=
Aug 21 13:05:11 user slapd[10604]: conn=185959 op=1 SRCH base="dc=example,dc=de" scope=2 deref=0 filter="(&(objectClass=*)(uid=accounte))"
Aug 21 13:05:11 user slapd[10604]: conn=185959 op=1 SRCH attr=* +
Aug 21 13:05:11 user slapd[10604]: conn=185959 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Aug 21 13:05:11 user slapd[10604]: conn=185959 op=2 BIND anonymous mech=implicit ssf=0
Aug 21 13:05:11 user slapd[10604]: conn=185959 op=2 BIND dn="uid=AccounTe,cn=users,dc=example,dc=de" method=128
Aug 21 13:05:11 user slapd[10604]: conn=185959 op=2 RESULT tag=97 err=49 text=
Aug 21 13:05:11 user slapd[10604]: conn=185959 op=3 UNBIND
Aug 21 13:05:11 user slapd[10604]: conn=185959 fd=24 closed
```

The new user has the following properties:
```
	"services" : {
		"ldap" : {
			"idAttribute" : "entryUUID",
			"id" : "123456674575678678967968934564567456745674567245635783456456745674567456"
		},
```

The (successful) log attempt looks like this in the LDAP log:
```
Aug 21 13:11:28 user slapd[10604]: conn=186074 fd=28 ACCEPT from IP=135.181.100.167:37192 (IP=0.0.0.0:7636)
Aug 21 13:11:28 user slapd[10604]: conn=186074 fd=28 TLS established tls_ssf=256 ssf=256
Aug 21 13:11:28 user slapd[10604]: conn=186074 op=0 BIND dn="uid=chat,dc=example,dc=de" method=128
Aug 21 13:11:28 user slapd[10604]: conn=186074 op=0 BIND dn="uid=chat,dc=example,dc=de" mech=SIMPLE ssf=0
Aug 21 13:11:28 user slapd[10604]: conn=186074 op=0 RESULT tag=97 err=0 text=
Aug 21 13:11:29 user slapd[10604]: conn=186074 op=1 SRCH base="dc=example,dc=de" scope=2 deref=0 filter="(&(objectClass=*)(uid=newuser))"
Aug 21 13:11:29 user slapd[10604]: conn=186074 op=1 SRCH attr=* +
Aug 21 13:11:29 user slapd[10604]: conn=186074 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Aug 21 13:11:29 user slapd[10604]: conn=186074 op=2 BIND anonymous mech=implicit ssf=0
Aug 21 13:11:29 user slapd[10604]: conn=186074 op=2 BIND dn="uid=newuser,cn=users,dc=example,dc=de" method=128
Aug 21 13:11:29 user slapd[10604]: conn=186074 op=2 BIND dn="uid=newuser,cn=users,dc=example,dc=de" mech=SIMPLE ssf=0
Aug 21 13:11:29 user slapd[10604]: conn=186074 op=2 RESULT tag=97 err=0 text=
Aug 21 13:11:29 user slapd[10604]: conn=186074 op=3 SRCH base="uid=newuser,cn=users,dc=example,dc=de" scope=2 deref=0 filter="(objectClass=*)"
Aug 21 13:11:29 user slapd[10604]: conn=186074 op=3 SEARCH RESULT tag=101 err=0 nentries=1 text=
Aug 21 13:11:29 user slapd[10604]: conn=186074 op=4 UNBIND
Aug 21 13:11:29 user slapd[10604]: conn=186074 fd=28 closed
```

**Comment by svenseeberg** [comment]
> I'm working on a fix here that we'll release in a patch, but in the meantime you can also get login working again if you set user's `ldap` attribute to false (NOT `services.ldap`).

It seems that this does not solve the issue.

**Comment by pierre-lehnen-rc** [comment]
Changing the unique identifier or the attribute that is used as unique identifier. Changing the user's data itself wouldn't cause this.

6.3 didn't change anything in the operations that are performed on LDAP. The change is something that Rocket.Chat does with the user's data after the LDAP process is completed succesfully.
If setting `ldap` to false didn't solve it for you, then you're running into a different issue.

**Comment by svenseeberg** [comment]
> Changing the unique identifier or the attribute that is used as unique identifier. Changing the user's data itself wouldn't cause this.

But when I update the ID in the MongoDB, then this should be fixed, right? Therefore yes, there must be something else going on. The IDs did definitely not change in the LDAP database.

**Comment by pierre-lehnen-rc** [comment]
> Only one (the oldest one) has this problem

How old is it?
I'm thinking the new changes may also have an effect on users that were created on much older versions of rocket.chat (before 4.0), if they were configured not to update user's data on login/sync since then.

**Comment by svenseeberg** [comment]
It was set up in Jan 2021. We started with the latest available version back then. Must have 4.3.X or something like that.

**Comment by pierre-lehnen-rc** [comment]
I just checked the code here again, I was mistaken when I said: 

> you can also get login working again if you set user's `ldap` attribute to false (NOT `services.ldap`).

You actually need to remove `services.ldap` too.

**Comment by svenseeberg** [comment]
> You actually need to remove `services.ldap` too. Once you remove that, the "Merge Existing Users" feature will work as it used to.

Yes, this works indeed. Thanks.

**Comment by pierre-lehnen-rc** [comment]
Just to confirm: your server was configured not to update user data on login, right?

**Comment by svenseeberg** [comment]
> Just to confirm: your server was configured not to update user data on login, right?

The setting is (and was) turned on, though I cannot reproduce which combinations I tested. But I think I tested all combinations of the "merge users" and "update user data" toggles before fixing the problem by dropping the `services.ldap` attribute from all users in the MongoDB.

**Comment by ipikiiskinen** [comment]
What is the status of the fix for this issue?
We most probably have the same issue in our system (Docker intallation of RC 6.4.5 CE, Mongo 5.0.22, Active Directory LDAP integration).
We have not changed any LDAP configurations. Based on user reports, this started after upgrading from 5.4.10 to 6.4.0.
Some users have this issue, but not all.
We have used samAccountName as user indentificator. Merge Existing Users and Update User Data on Login enabled.
This is a severe issue.

**Comment by svenseeberg** [comment]
> Merge Existing Users and Update User Data on Login enabled.

If you need a quick fix for all your users, the following should work (I'd recommend a backup though):
```
use rocketchat
db.users.updateMany({}, {$set: {"ldap": false}})
db.users.updateMany({}, {$unset: {"services.ldap": true}})
```

**Comment by yanosz** [comment]
Issue confirmed on 7.4.1

After an LDAP migration, some domain parts of the DN changed. This causes non-deterministic login-problems on accounts even months later.  I've just deleted all LDAP metadata as proposed in this ticket - also unsetting importids, due to having entries referecing the old tree.
```
db.users.updateMany({}, {$unset: {"importIds": true}})
```

The quick fix is very helpful for fixing user-accounts (thanks!). However, I think that the LDAP connection should be more robust against changes in tree. It'd be great to match, merge and update accounts based on a single attribute only (e.g. common name) without collisions.

**Comment by svenseeberg** [comment]
Just another note on this subject: the following commands are also very helpful when migrating from one LDAP server to another with slightly different identifiers (UCS to Samba in our case).

> If you need a quick fix for all your users, the following should work (I'd recommend a backup though):
> 
> ```
> use rocketchat
> db.users.updateMany({}, {$set: {"ldap": false}})
> db.users.updateMany({}, {$unset: {"services.ldap": true}})
> ```

The identifiers are reset and the users are merged again based on their usernames.
