### ISSUE TITLE
TranslationProvider crash in Ukrainian language 

### ISSUE THREAD

**Issue by Sergik666** [RocketChat/Rocket.Chat#30058]
### Description:

TranslationProvider crash in Ukrainian language 

### Steps to reproduce:

1. Switch browser language to Ukrainian 
2. Login to RocketChat

### Expected behavior:

To see the channels content.

### Actual behavior:

![image](https://github.com/RocketChat/Rocket.Chat/assets/913402/3aed48e5-a0d2-484c-b37f-1f46d80b2fae)

### Server Setup Information:

Version
6.3.0
Apps Engine Version
1.40.0
Node Version
v14.21.3
Database Migration
301 (August 10, 2023 8:29 AM)
MongoDB
5.0.19 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (d3c4ef1e6)
Branch: HEAD

### Client Setup Information

- Browser Version: Chrome 115
- Operating System: Windows 10 (x64)

### Relevant logs:

```
8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:130 TypeError: Cannot read properties of undefined (reading 'hours')
    at eval (eval at <anonymous> (TranslationProvider.tsx:1:1), <anonymous>:53:38)
    at A.R [as calendar] (8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:225:719703)
    at 8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:522:2860353
    at w (ThreadMetrics.tsx:1:1676)
    at Ii (8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:130:59708)
    at $c (8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:130:111738)
    at nu (8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:130:98852)
    at tu (8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:130:98780)
    at eu (8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:130:98643)
    at Hc (8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:130:95497)
```

**Comment by KayakinKoder** [comment]
As far as I can tell, this is occurring for all non-English languages. Users are not able to view channels/chat messages due to this issue.

A temporary workaround is switching browser language to English.

**Comment by Sergik666** [comment]
This problem is not with the russian language

**Comment by Dnouv** [comment]
Thank you for opening the issue. 

This issue seems similar to -> https://github.com/RocketChat/Rocket.Chat/issues/30001

**Comment by save2love** [comment]
Had the same issue. Changing language in account preferences to English helped me.
`Windows Rocket.Chat Version 3.9.6`
