### ISSUE TITLE
SMS - Images Not Sent - Error: Method not implemented

### ISSUE THREAD

**Issue by bionemesis** [RocketChat/Rocket.Chat#30124]
We are using the Twilio API to send text messages. Regular SMS works fine, but when we attempt to send an image (have attempted small and large PNG and JPEGs), nothing is sent and the logs show:

`{"level":50,"time":"2023-08-20T01:19:08.910Z","pid":1,"hostname":"c9bb1f9b-748e-4c62-94f5-033b95106ad0","name":"[Omnichannel] Callback","err":{"type":"Error","message":"Method not implemented.","stack":"Error: Method not implemented.<br>    at Twilio.fileUploadMediaTypeWhiteList (server/services/omnichannel-integrations/providers/twilio.ts:185:9)<br>    at server/services/omnichannel-integrations/providers/twilio.ts:151:56<br>    at /app/code/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/code/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/livechat/server/sendMessageBySMS.ts:71:4<br>    at /app/code/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"Method not implemented."} `

We have "File Uploads Enabled" checked under Settings > SMS and Settings > Omnichannel.

**Comment by sarthaksharma27** [comment]
I am not able to find the issue @bionemesis
