### ISSUE TITLE
Error occurs when clicking on OTR

### ISSUE THREAD

**Issue by LYD-0** [RocketChat/Rocket.Chat#30205]
logs:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'generateKey')
    at m (functions.ts:67:9)
    at G.generateKeyPair (OTRRoom.ts:157:26)
    at G.handshake (OTRRoom.ts:79:15)
    at onClickStart (OTRWithData.tsx:23:8)
    at Object.nP (_define_property.mjs:14:1)
    at nR (_define_property.mjs:14:1)
    at nL (_define_property.mjs:14:1)
    at oR (_define_property.mjs:14:1)
    at oL (_define_property.mjs:14:1)
    at _define_property.mjs:14:1

imgs:
![图片](https://github.com/RocketChat/Rocket.Chat/assets/54184065/53372a48-bf34-4b7b-8d95-f59410198c40)

**Comment by Ninad3721** [comment]
It is working fine for me , can you please tell particularly  when  you getting this error ?

**Comment by KevLehman** [comment]
OTR feature was removed on latest version.
