### ISSUE TITLE
app crashed

### ISSUE THREAD

**Issue by khodge281** [RocketChat/Rocket.Chat#30405]
Getting this....Please fix it......Application Error
The application GUI just crashed.

**Comment by p5ych2022** [comment]
same error

**Comment by Arryboom** [comment]
same

```
peError: Cannot read properties of undefined (reading 'minutes')
    at lastDay (eval at <anonymous> (TranslationProvider.tsx:1:1), <anonymous>:73:29)
    at A.R [as calendar] (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:225:719703)
    at 241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:522:2860279
    at m (DiscussionMetrics.tsx:1:780)
    at Ii (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:59708)
    at $c (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:111738)
    at nu (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:98852)
    at tu (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:98780)
    at eu (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:98643)
    at Hc (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:95497)
zs @ 241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130
```
