### ISSUE TITLE
Exception while invoking method 'loadLocale' Error: Unknown asset: moment-locales/2.js

### ISSUE THREAD

**Issue by zjasonshen** [RocketChat/Rocket.Chat#30417]
### Description:
I'm seeing these errors in my rocketchat-logs. I think it might be causing an issue with the Omnichannel business hours features not setting the time correctly. It seems to be setting it to UTC time instead of server time.

### Steps to reproduce:

1. Start rocketchat
2. Errors will appear after a minute or 2. 

Error could also be trigger if I can my localization in my profile page.

### Expected behavior:
No errors. Business hours should be set with server time and not UTC

### Actual behavior:

Only thing I'm noticing is that business hours aren't working. Current workaround is to just turn off that feature for now.

### Server Setup Information:

- Version of Rocket.Chat Server:  6.3.4
- Operating System: CentOS 7
- Deployment Method:docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.20

### Client Setup Information

- Desktop App or Browser Version: 3.9.6
- Operating System: MacOS

### Relevant logs:

meteor-rocketchat-1  | Exception while invoking method 'loadLocale' Error: Unknown asset: moment-locales/2.js
meteor-rocketchat-1  |     at getAsset (/app/bundle/programs/server/boot.js:303:21)
meteor-rocketchat-1  |     at Object.getTextAsync (/app/bundle/programs/server/boot.js:318:18)
meteor-rocketchat-1  |     at server/lib/getMomentLocale.ts:7:17
meteor-rocketchat-1  |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
meteor-rocketchat-1  |  => awaited here:
meteor-rocketchat-1  |     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
meteor-rocketchat-1  |     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:781:32)
meteor-rocketchat-1  |     at packages/meteor.js:365:18
meteor-rocketchat-1  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
meteor-rocketchat-1  |     at packages/ddp-server/livedata_server.js:791:46
meteor-rocketchat-1  |     at new Promise (<anonymous>)
meteor-rocketchat-1  |     at Session.method (packages/ddp-server/livedata_server.js:739:23)
meteor-rocketchat-1  |     at packages/ddp-server/livedata_server.js:603:43

**Comment by mcgrathd** [comment]
We were noticing something similar on our chat server that happens at exactly 1am server time every night:

(mind the formatting)

```
{
  "level": 50,
  "time": "2023-12-07T01:00:01.343Z",
  "pid": 1,
  "hostname": "b4399c07361a",
  "name": "System",
  "msg": "Exception while invoking method loadLocale",
  "err": {
    "type": "Error",
    "message": "Unknown asset: moment-locales/zh.js",
    "stack": "Error: Unknown asset: moment-locales/zh.js\n    at getAsset (/app/bundle/programs/server/boot.js:303:21)\n    at Object.getTextAsync (/app/bundle/programs/server/boot.js:318:18)\n    at server/lib/getMomentLocale.ts:7:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at packages/meteor.js:367:22\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)\n    at packages/ddp-server/livedata_server.js:1818:36\n    at new Promise (<anonymous>)\n    at Server.applyAsync (packages/ddp-server/livedata_server.js:1817:12)\n    at Server.callAsync (packages/ddp-server/livedata_server.js:1743:17)\n    at app/api/server/v1/misc.ts:620:33\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/v1/misc.ts:620:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"
  }
}
```

After this crash, the mongodb announces its intention to terminate. Ultimately we have to run a docker compose restart. Our Omni stuff is disabled. Any ideas if they may be related?

**Comment by ranqiangjun** [comment]
I encountered the same issue with v6.5.2, I am running RC with the official docker image. Checked `/app/bundle/programs/server/assets/app/moment-locales`, no `zh.js`, the temp fix is 

```bash
cd /app/bundle/programs/server/assets/app/moment-locales
cp zh-cn.js zh.js
```

---

The error message
```
Exception while invoking method 'loadLocale' Error: Unknown asset: moment-locales/zh.js
    at getAsset (/app/bundle/programs/server/boot.js:303:21)
    at Object.getTextAsync (/app/bundle/programs/server/boot.js:318:18)
    at server/lib/getMomentLocale.ts:7:17
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:781:32)
    at packages/meteor.js:365:18
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
    at packages/ddp-server/livedata_server.js:791:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/ddp-server/livedata_server.js:603:43
```

**Comment by sweet-kkk** [comment]
Has the problem been solved? I used the official docker-compose file for deployment and ran into the same issue.

Through various attempts, eventually there were still problems.

Service Information:

```
rocketchat-1  | +--------------------------------------------------+
rocketchat-1  | |                  SERVER RUNNING                  |
rocketchat-1  | +--------------------------------------------------+
rocketchat-1  | |                                                  |
rocketchat-1  | |  Rocket.Chat Version: 7.1.0                      |
rocketchat-1  | |       NodeJS Version: 20.18.0 - x64              |
rocketchat-1  | |      MongoDB Version: 6.0.13                     |
rocketchat-1  | |       MongoDB Engine: wiredTiger                 |
rocketchat-1  | |             Platform: linux                      |
rocketchat-1  | |         Process Port: 3000                       |
rocketchat-1  | |             Site URL: http://192.168.1.198:3000  |
rocketchat-1  | |     ReplicaSet OpLog: Enabled                    |
rocketchat-1  | |          Commit Hash: 73af9c5375                 |
rocketchat-1  | |        Commit Branch: HEAD                       |
rocketchat-1  | |                                                  |
rocketchat-1  | +--------------------------------------------------+
```

Error message:

```
{
	"level": 50,
	"time": "2024-12-10T07:43:26.694Z",
	"pid": 1,
	"hostname": "033e12d09242",
	"name": "System",
	"msg": "Exception while invoking method loadLocale",
	"err": {
		"type": "Error",
		"message": "Unknown asset: moment-locales/zh.js",
		"stack": "Error: Unknown asset: moment-locales/zh.js\n    at getAsset (/tools/static-assets/server/boot.js:346:19)\n    at Object.getTextAsync (/tools/static-assets/server/boot.js:358:16)\n    at getMomentLocale (server/lib/getMomentLocale.ts:7:17)\n    at MethodInvocation.loadLocale (server/methods/loadLocale.ts:19:11)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1974:12)\n    at packages/ddp-server/livedata_server.js:1884:11\n    at EnvironmentVariableAsync.<anonymous> (packages/meteor.js:1294:16)\n    at packages/meteor.js:765:17\n    at AsyncLocalStorage.run (node:async_hooks:346:14)\n    at Object.Meteor._runAsync (packages/meteor.js:762:14)\n    at EnvironmentVariableAsync.withValue (packages/meteor.js:1290:19)\n    at packages/ddp-server/livedata_server.js:1883:47\n    at new Promise (<anonymous>)\n    at Server.applyAsync (packages/ddp-server/livedata_server.js:1880:12)\n    at packages/ddp-server/livedata_server.js:1801:12\n    at new Promise (<anonymous>)\n    at Server.callAsync (packages/ddp-server/livedata_server.js:1799:21)\n    at Object.post (app/api/server/v1/misc.ts:539:33)\n    at app/api/server/api.ts:668:97\n    at EnvironmentVariableAsync.<anonymous> (packages/meteor.js:1294:16)\n    at packages/meteor.js:765:17\n    at AsyncLocalStorage.run (node:async_hooks:346:14)\n    at Object.Meteor._runAsync (packages/meteor.js:762:14)\n    at EnvironmentVariableAsync.withValue (packages/meteor.js:1290:19)\n    at app/api/server/api.ts:668:41\n    at tracerSpan (/app/bundle/programs/server/npm/node_modules/@rocket.chat/tracing/src/index.ts:43:10)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.ts:652:23)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at packages/rocketchat:restivus/lib/route.js:57:21\n    at Object.handler (packages/rocketchat:restivus/lib/json-routes.js:43:5)"
	}
}
```

**Comment by sebastianleecn** [comment]
> I encountered the same issue with v6.5.2, I am running RC with the official docker image. Checked `/app/bundle/programs/server/assets/app/moment-locales`, no `zh.js`, the temp fix is
> 
> cd /app/bundle/programs/server/assets/app/moment-locales
> cp zh-cn.js zh.js
> The error message
> 
> ```
> Exception while invoking method 'loadLocale' Error: Unknown asset: moment-locales/zh.js
>     at getAsset (/app/bundle/programs/server/boot.js:303:21)
>     at Object.getTextAsync (/app/bundle/programs/server/boot.js:318:18)
>     at server/lib/getMomentLocale.ts:7:17
>     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
>  => awaited here:
>     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
>     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:781:32)
>     at packages/meteor.js:365:18
>     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
>     at packages/ddp-server/livedata_server.js:791:46
>     at new Promise (<anonymous>)
>     at Session.method (packages/ddp-server/livedata_server.js:739:23)
>     at packages/ddp-server/livedata_server.js:603:43
> ```

love u, baby

**Comment by juzser** [comment]
Same issue in 7.5.1. 
Missing `vi-vn.js`

**Comment by ryanhex53** [comment]
same issue in 7.6.0
