### ISSUE TITLE
exception Error: Can't wait without a fiber

### ISSUE THREAD

**Issue by Kot-o-pes** [RocketChat/Rocket.Chat#30725]
this exception is occurring constantly in 6.4.2 
```
Error: Can't wait without a fiber
    at Function.wait (/app/bundle/programs/server/node_modules/fibers/future.js:159:9)
    at Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:448:10)
    at MongoConnection.findOne (packages/mongo/mongo_driver.js:829:84)
    at Collection.findOne (packages/mongo/collection.js:459:29)
    at getUserById (packages/accounts-password/password_server.js:5:51)
    at AccountsServer.Accounts.generateResetToken (packages/accounts-password/password_server.js:402:16)
    at AccountsServer.Accounts.sendEnrollmentEmail (packages/accounts-password/password_server.js:567:14)
    at Immediate.<anonymous> (app/lib/server/functions/setUsername.ts:102:14)
    at processImmediate (internal/timers.js:464:21)
    at process.topLevelDomainCallback (domain.js:152:15)
    at process.callbackTrampoline (internal/async_hooks.js:128:24)
    ```

**Comment by hcoz** [comment]
hey! is there any update about this issue?
