### ISSUE TITLE
The user cannot change the avatar after updating from 5.4.10 to 6.4.2 (the function is enabled in the settings)

### ISSUE THREAD

**Issue by gromfaus** [RocketChat/Rocket.Chat#30802]
### Steps to reproduce:

1. User tries to change avatar
2. Gets an error "Not allowed"
3. The avatar remains the same

### Expected behavior:

User avatar has been changed

### Actual behavior:

The user cannot change the avatar after updating from 5.4.10 to 6.4.2 via snap

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.2
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: on
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.9.9 and Google Chrome 118.0.5993.118
- Operating System: All

### Additional context

The error appeared after updating from 5.4.10 to 6.4.2 . The user cannot change the avatar, admin can change the user's avatar.

### Relevant logs:

Exception while invoking method saveUserProfile errorClass [Error]: Not allowed [error-not-allowed]     at app/user-status/server/methods/setUserStatus.ts:32:10     at /snap/rocketchat-server/1581/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/snap/rocketchat-server/1581/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/methods/saveUserProfile.ts:75:3     at /snap/rocketchat-server/1581/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/snap/rocketchat-server/1581/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at packages/meteor.js:367:22     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)     at packages/ddp-server/livedata_server.js:1818:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1817:12)     at Server.callAsync (packages/ddp-server/livedata_server.js:1743:17)     at app/api/server/v1/misc.ts:559:33     at /snap/rocketchat-server/1581/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/snap/rocketchat-server/1581/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/api/server/v1/misc.ts:559:17     at /snap/rocketchat-server/1581/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {   isClientSafe: true,   error: 'error-not-allowed',   reason: 'Not allowed',   details: { method: 'setUserStatus' },   errorType: 'Meteor.Error' } 

![image](https://github.com/RocketChat/Rocket.Chat/assets/32450803/b241231f-f5b9-4e96-a356-9ffa960602ac)

**Comment by MarlynxLinux** [comment]
in your settings, you are prohibited from changing the login in your profile?
https://github.com/RocketChat/Rocket.Chat/commit/69d89c47000e3e18367e6d4cf4232bbec513cc61

**Comment by charlyrock** [comment]
We have the same problem in version 6.4.2. The user can´t change anything in his profile setting. No Descritption, no Avatar and so on.

**Comment by MarlynxLinux** [comment]
> У нас такая же проблема в версии 6.4.2. Пользователь не может ничего изменить в настройках своего профиля. Ни описания, ни аватара и так далее.

this is solved on version 6.4.3

**Comment by gromfaus** [comment]
> > У нас такая же проблема в версии 6.4.2. Пользователь не может ничего изменить в настройках своего профиля. Ни описания, ни аватара и так далее.
> 
> this is solved on version 6.4.3

Updated to 6.4.4, same problem, login cannot be changed

**Comment by gromfaus** [comment]
> in your settings, you are prohibited from changing the login in your profile? [69d89c4](https://github.com/RocketChat/Rocket.Chat/commit/69d89c47000e3e18367e6d4cf4232bbec513cc61)


I allowed the login to change, nothing changed

**Comment by floriankoenig-work** [comment]
This bug is also in 6.4.5

**Comment by floriankoenig-work** [comment]
I could somehow resolve this by disabling an reenabling the following settings:
1) Check Administration -> Permissions -> Settings -> "Accounts", "Accounts > Allow User Avatar Change", "Accounts > Allow User Profile Change" ar active for Role Admin
2) Administration -> Settings -> Accounts -> "Allow User Profile Change", "Allow User Avatar Change"

**Comment by gromfaus** [comment]
I was able to solve the problem by enabling "Allow Feature Preview", in Administration -> Settings -> Accounts.

**Comment by florisvangeel** [comment]
Cool so this issue can be closed.
Didn't experience any avatar or file issues in 6.x and use GRIDFS
_if you use local or self deployments do check permissions, perhaps root updated something and user rocketchat can't write._
