### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/app/bundle/programs/

### ISSUE THREAD

**Issue by Deplee** [RocketChat/Rocket.Chat#30814]
### Description:

Hi guys, today i'm downgrading my rocket.chat from 6.4.2 to 5.4.0 and still have a problem with npm i think...

here is some logs, any ideas ?

Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/node_modules/long/dist/long.js'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/utils/isObject.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/utils/isURL.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/utils/omit.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/utils/stringUtils.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/utils/getFileExtension.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/utils/comparisons.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/rooms/coordinator.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/publishFields.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/getUserDisplayName.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/transforms.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/callbacks.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/callbacks/callbacksBase.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/createQuoteAttachment.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/lib/getMessageUrlRegex.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/definition/IRoomTypeConfig.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21

### Actual behavior:

![image](https://github.com/RocketChat/Rocket.Chat/assets/43135746/bb78018d-64e6-4d32-98e7-8ba8918ecee1)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Operating System: ubuntu
- Deployment Method: docker
- Number of Running Instances:  1-4
- DB Replicaset Oplog: true
- MongoDB Version: 4.4.15

**Comment by Deplee** [comment]
mongo db migrations is 281. all working fine, but no some files in docker containers

**Comment by MaHDiaLaGaB** [comment]
i have same problem
