### ISSUE TITLE
LDAP user can not login after db update from 4.4 to 5.0

### ISSUE THREAD

**Issue by elbrus56** [RocketChat/Rocket.Chat#30882]
### Description:

After db update from 4.4 to 5.0 LDAP user can not login neither to WebUI nor app – got WebUI crash error.

### Steps to reproduce:

1. stop rocketchat
2. stop mongodb
3. change mongodb compatibility settings
4. update mongodb from repos
5. start mongodb

Also
- checking LDAP connection from UI works
- finding LDAP user from UI works
- local user login works

Also did not help:
- mongodb export and import after update (with indexes)
- clear indexes
- clear banner settings for user

### Actual behavior:

Got UI crash error.
<img width="430" alt="Screenshot 2023-11-07 at 20 44 58" src="https://github.com/RocketChat/Rocket.Chat/assets/29130663/49657c85-4255-4b07-868e-54b9286ace4e">

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.5
- Operating System: Debian 11
- Deployment Method: Manual installation
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0.22 wiredTiger (Single node replica set)

### Client Setup Information

- Desktop App or Browser Version: Safari, Chrome
- Operating System: macOS, iOS

### Additional context
New LDAP users can login

### Relevant logs:
`{"level":50,"time":"2023-11-08T08:28:45.040Z","pid":995,"hostname":"servername","name":"LDAP Data Converter","err":{"type":"errorClass","message":"Username already exists. [403]","stack":"Error: Username already exists. [403]<br>    at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1206:15)<br>    at app/authentication/server/startup/index.js:301:28<br>    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at AccountsServer.Accounts.insertUserDoc (app/authentication/server/startup/index.js:363:17)<br>    at app/importer/server/classes/ImportDataConverter.ts:375:19<br>    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/importer/server/classes/ImportDataConverter.ts:525:18<br>    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","isClientSafe":true,"error":403,"reason":"Username already exists.","errorType":"Meteor.Error"},"msg":"Username already exists. [403]"} `

**Comment by sidling1** [comment]
@elbrus56 what do you mean by update mongodb from the repos ? can you help me with it

**Comment by elbrus56** [comment]
> @elbrus56 what do you mean by update mongodb from the repos ? can you help me with it

Hi @sidling1! 

According to https://www.mongodb.com/docs/v5.0/tutorial/install-mongodb-on-debian/

**Comment by sidling1** [comment]
So i downloaded the new mongodb version using docker , but how do i change the version that is begin used in Rocket.Chat , also when the server runs , it shows my mongo version to be 6.0.3

**Comment by elbrus56** [comment]
I have no docker installation, manual install: https://docs.rocket.chat/deploy/deploy-rocket.chat/additional-deployment-methods/deploy-on-debian

**Comment by elbrus56** [comment]
Looks like issue with LDAP login happens when I'm updating from 6.2.1 to 6.3.

Disabling LDAP resolves the issue.
