### ISSUE TITLE
upgrade from 5.4.10 to 6.4.5, I get this error

### ISSUE THREAD

**Issue by hosienhk4185** [RocketChat/Rocket.Chat#30938]
When I upgrade from 5.4.10 to 6.4.5, I get this error

https://rchat.karabaman.ir/meteor_runtime_config.js?hash=3a8319b669285a5d286cb63115b81b33919d20b1 net::ERR_ABORTED 404 (Not Found)

home:1 Refused to execute script from 'https://rchat.karabaman.ir/meteor_runtime_config.js?hash=3a8319b669285a5d286cb63115b81b33919d20b1' because its MIME type ('') is not executable, and strict MIME type checking is enabled.

client_environment.js:1 Uncaught ReferenceError: __meteor_runtimeconfig_ is not defined

at client_environment.js:1:1

at client_environment.js:78:1

**Comment by nikolaydyankov** [comment]
I was also having the same issue:

```
meteor_runtime_config.js:1 
 Failed to load resource: the server responded with a status of 404 (Not Found)
general:1 Refused to execute script from 'http://localhost:4001/meteor_runtime_config.js?hash=5f8e4ab…' because its MIME type ('') is not executable, and strict MIME type checking is enabled.
client_environment.js:1 Uncaught ReferenceError: __meteor_runtime_config__ is not defined
    at client_environment.js:1:1
    at client_environment.js:78:1
    at url_common.js:80:1
```

Fixed it by updating the Site URL in Settings -> General to the URL where the Rocketchat server lives. I'm brand new to RC and it doesn't make any sense to me why would I need to set that setting, given that I already specified a host in the .env file when launching the docker containers. Unless it's bugged?

**Comment by hosienhk4185** [comment]
i changed it But nothing changed

**Comment by piraxi** [comment]
@hosienhk4185  I tested versions 6.4.5 through to 6.4.8 and they all have this problem when using nginx.   Please use version [6.5.0-rc.3] where the problem is not present anymore.

![image](https://github.com/RocketChat/Rocket.Chat/assets/44791530/8a2cc03a-1d82-47e5-a49b-d902e0813ec2)

**Comment by hosienhk4185** [comment]
This version [6.5.0-rc.3] is not available in snap.
Current versions of Snap:
channels:
  6.x/stable:       6.5.0  2023-12-05 (1597) 362MB -
  6.x/candidate:    ↑                              
  6.x/beta:         ↑                              
  6.x/edge:         6.5.0  2023-12-01 (1597) 362MB -
  latest/stable:    6.4.1  2023-10-16 (1580) 354MB -

**Comment by hosienhk4185** [comment]
> @hosienhk4185 I tested versions 6.4.5 through to 6.4.8 and they all have this problem when using nginx. Please use version [6.5.0-rc.3] where the problem is not present anymore.
> 
> ![image](https://private-user-images.githubusercontent.com/44791530/287147544-8a2cc03a-1d82-47e5-a49b-d902e0813ec2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDg0NTYsIm5iZiI6MTcwMjkwODE1NiwicGF0aCI6Ii80NDc5MTUzMC8yODcxNDc1NDQtOGEyY2MwM2EtMWQ4Mi00N2U1LWE0OWItZDkwMmUwODEzZWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE0MDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NmY4YWY5MzNlM2RkZTVlYWQyNWQ1NTU1Njg4NzhjNGNiZDc0OTk2YTQ0NGM5MjRmOGQxMzRmNjkxMTY2ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zbs3cmu_uPDDvsl-TJoMxXTPV6LLCovopw3pjichHyw)

channels:
  6.x/stable:       6.5.0  2023-12-05 (1597) 362MB -
  6.x/candidate:    ↑                              
  6.x/beta:         ↑                              
  6.x/edge:         6.5.0  2023-12-01 (1597) 362MB -
  latest/stable:    6.4.1  2023-10-16 (1580) 354MB -

**Comment by hosienhk4185** [comment]
> @hosienhk4185 I tested versions 6.4.5 through to 6.4.8 and they all have this problem when using nginx. Please use version [6.5.0-rc.3] where the problem is not present anymore.
> 
> ![image](https://private-user-images.githubusercontent.com/44791530/287147544-8a2cc03a-1d82-47e5-a49b-d902e0813ec2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDg0NTYsIm5iZiI6MTcwMjkwODE1NiwicGF0aCI6Ii80NDc5MTUzMC8yODcxNDc1NDQtOGEyY2MwM2EtMWQ4Mi00N2U1LWE0OWItZDkwMmUwODEzZWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE0MDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NmY4YWY5MzNlM2RkZTVlYWQyNWQ1NTU1Njg4NzhjNGNiZDc0OTk2YTQ0NGM5MjRmOGQxMzRmNjkxMTY2ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zbs3cmu_uPDDvsl-TJoMxXTPV6LLCovopw3pjichHyw)

This version [6.5.0-rc.3] is not available in snap
Current versions of Snap:
channels:
  6.x/stable:       6.5.0  2023-12-05 (1597) 362MB -
  6.x/candidate:    ↑                              
  6.x/beta:         ↑                              
  6.x/edge:         6.5.0  2023-12-01 (1597) 362MB -
  latest/stable:    6.4.1  2023-10-16 (1580) 354MB -
