### ISSUE TITLE
"Cannot read properties of undefined" in filtered.js (including fix)

### ISSUE THREAD

**Issue by fbernhard** [RocketChat/Rocket.Chat#30949]
### Description:

`supportSchemesForLink` might be `undefined` at [filtered.js#L11](https://github.com/RocketChat/Rocket.Chat/blob/master/apps/meteor/app/markdown/lib/parser/filtered/filtered.js#L11). Accessing a property of undefined leads to an exception.

![Screenshot 2023-11-14 at 08 05 32](https://github.com/RocketChat/Rocket.Chat/assets/2153140/d7f2a781-1308-474a-bc45-8a580196a4b9)

Fix: change

```
const schemes = options.supportSchemesForLink.split(',').join('|');
```

to 

```
const schemes = (options.supportSchemesForLink || 'http,https').split(',').join('|');
```

### Steps to reproduce:

I have discovered this as a user, I don't know the system.

### Expected behavior:

The code does not attempt to read properties of undefined

### Actual behavior:

The code attempts to read properties of undefined

### Server Setup Information:

Irrelevant, the bug is in the current UI code of the `master` and `develop` branch.

### Client Setup Information

- Desktop App or Browser Version: Chrome 118.0.5993.117
- Operating System: MacOS

### Relevant logs:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at Object.A [as filtered] (63a83663cd6728fca9585f431c611e7fd8c64956.js?meteor_js_resource=true:1583:2177715)
    at C.filterMarkdownFromMessage (63a83663cd6728fca9585f431c611e7fd8c64956.js?meteor_js_resource=true:1583:2283982)
    at E (63a83663cd6728fca9585f431c611e7fd8c64956.js?meteor_js_resource=true:1583:2284136)
    at i (normalizeSidebarMessage.ts:1:4491)
    at S (SideBarItemTemplateWithData.tsx:1:882)
    at M (SideBarItemTemplateWithData.tsx:1:1697)
    at Pi (63a83663cd6728fca9585f431c611e7fd8c64956.js?meteor_js_resource=true:1139:59696)
    at Rs (63a83663cd6728fca9585f431c611e7fd8c64956.js?meteor_js_resource=true:1139:111726)
    at nu (63a83663cd6728fca9585f431c611e7fd8c64956.js?meteor_js_resource=true:1139:98840)
    at ru (63a83663cd6728fca9585f431c611e7fd8c64956.js?meteor_js_resource=true:1139:98768)
```

**Comment by Harshalvk** [comment]
I would like to work on the issue??

**Comment by Thanush19** [comment]
@fbernhard  ,if the issue is not resolved yet , i can work on this...
