### ISSUE TITLE
Mail not working. Nobody can login

### ISSUE THREAD

**Issue by Aeitto** [RocketChat/Rocket.Chat#30950]
### Description:

Users dont recieve emails even when i have configured SMTP in admin panel. Test mail also dosnt work. They make accounts without need for confirmation.

I freshly hosted instance based on your guide deploy-with-docker-and-docker-compose
And used sample yml + custom .env

Originally i tried to do it based on : Self-hosting Rocket.Chat With Docker [Complete Guide]

And i have set up container for nginx reverse proxy but it wasnt working so i disabled it and and used treafik as you suggested in guide.

I dont know what might be the case - logs are not showing anything regarding mails.

Maybe my custom .env rules:

LETSENCRYPT_EMAIL=admin@domain.
LETSENCRYPT_HOST=chat.domain.
VIRTUAL_HOST=chat.domain.
Accounts_UseDNSDomainCheck=false

i added them based on guide for nginx reverse proxy

Maybe i need to use nginx but yml should be in same folder as rocket chat because i terafik is.

But I really dont know. Its my 1st time using docker. Maybe its irrelevant.

### Server Setup Information:

Server Setup Information
Version of Rocket.Chat Server: 6.4.5
Operating System: Ubuntu 23.04
Deployment Method: docker
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
NodeJS Version: 14.21.3 - x64
MongoDB Version: 5.0.22
Proxy: traefik/
Firewalls involved:

### Client Setup Information

- Desktop App or Browser Version: every client
- Operating System: windows, android

### Additional context

[How to Use Nginx Reverse Proxy With Multiple Docker Apps](https://linuxhandbook.com/nginx-reverse-proxy-docker/#:~:text=The%20following%20is%20the%20whole%20content%20of%20the%20docker%2Dcompose.yml%20file).

i did it before setting rocket chat and nginx configuration has some setting while treafik.yml is empty did i miss something in rocket.chat.docs?

### Relevant logs:

`rocketchat-rocketchat-1  | {"level":50,"time":"2023-11-12T21:55:40.298Z","pid":1,"hostname":"d64d7d4e8462","name":"System","msg":"An error occured registering with token. 'Couldn't register with token.  Please make sure token is valid or hasn't already been used'"}
rocketchat-rocketchat-1  | Error: Greeting never received
rocketchat-rocketchat-1  |     at SMTPConnection._formatError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
rocketchat-rocketchat-1  |     at SMTPConnection._onError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
rocketchat-rocketchat-1  |     at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:704:22)
rocketchat-rocketchat-1  |     at listOnTimeout (internal/timers.js:557:17)
rocketchat-rocketchat-1  |     at processTimers (internal/timers.js:500:7) {
rocketchat-rocketchat-1  |   code: 'ETIMEDOUT',
rocketchat-rocketchat-1  |   command: 'CONN'
rocketchat-rocketchat-1  | }
rocketchat-rocketchat-1  | {"level":40,"time":"2023-11-13T21:16:16.113Z","pid":1,"hostname":"d64d7d4e8462","name":"DeprecationWarning","section":"API","msg":"The parameter \"query\" in the endpoint \"/api/v1/custom-user-status.list\" is deprecated and will be removed on version 7.0.0"}
rocketchat-rocketchat-1  | {"level":40,"time":"2023-11-13T21:32:03.296Z","pid":1,"hostname":"d64d7d4e8462","name":"DeprecationWarning","section":"API","msg":"The parameter \"fields\" in the endpoint \"/api/v1/users.list\" is deprecated and will be removed on version 7.0.0"}
rocketchat-rocketchat-1  | Error: Greeting never received
rocketchat-rocketchat-1  |     at SMTPConnection._formatError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
rocketchat-rocketchat-1  |     at SMTPConnection._onError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
rocketchat-rocketchat-1  |     at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:704:22)
rocketchat-rocketchat-1  |     at listOnTimeout (internal/timers.js:557:17)
rocketchat-rocketchat-1  |     at processTimers (internal/timers.js:500:7) {
rocketchat-rocketchat-1  |   code: 'ETIMEDOUT',
rocketchat-rocketchat-1  |   command: 'CONN'
rocketchat-rocketchat-1  | }
rocketchat-rocketchat-1  | {"level":40,"time":"2023-11-13T21:16:16.113Z","pid":1,"hostname":"d64d7d4e8462","name":"DeprecationWarning","section":"API","msg":"The parameter \"query\" in the endpoint \"/api/v1/custom-user-status.list\" is deprecated and will be removed on version 7.0.0"}
rocketchat-rocketchat-1  | {"level":40,"time":"2023-11-13T21:32:03.296Z","pid":1,"hostname":"d64d7d4e8462","name":"DeprecationWarning","section":"API","msg":"The parameter \"fields\" in the endpoint \"/api/v1/users.list\" is deprecated and will be removed on version 7.0.0"}
rocketchat-rocketchat-1  | Error: You have not provided a mail URL. You can provide it by using the environment variable MAIL_URL or your settings. You can read more about it here: https://docs.meteor.com/api/email.html.
rocketchat-rocketchat-1  |     at packages/email/email.js:310:11
rocketchat-rocketchat-1  |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40`

**Comment by Aeitto** [comment]
![image](https://github.com/RocketChat/Rocket.Chat/assets/125193345/06671508-6f73-405e-8904-57beccf29fc3)
to disable 2FA i need to have working mail which is absurd. How to skip this?

**Comment by Aeitto** [comment]
im still looking for anwser and added MAIL_URL to .env as stated #3602 

recent logs shows only:
`{"level":40,"time":"2023-11-14T19:16:06.302Z","pid":1,"hostname":"a2376a77556a","name":"DeprecationWarning","section":"METHOD","msg":"The method \"deleteMessage\" is deprecated and will be removed on version 7.0.0"}
rocketchat-rocketchat-1  | Error: Greeting never received
rocketchat-rocketchat-1  |     at SMTPConnection._formatError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
rocketchat-rocketchat-1  |     at SMTPConnection._onError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
rocketchat-rocketchat-1  |     at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:704:22)
rocketchat-rocketchat-1  |     at listOnTimeout (internal/timers.js:557:17)
rocketchat-rocketchat-1  |     at processTimers (internal/timers.js:500:7) {
rocketchat-rocketchat-1  |   code: 'ETIMEDOUT',
rocketchat-rocketchat-1  |   command: 'CONN'
rocketchat-rocketchat-1  | }`

**Comment by Aeitto** [comment]
![image](https://github.com/RocketChat/Rocket.Chat/assets/125193345/4f0c3ba8-bd28-4be1-a95b-1262bf488783)
my mail is on ovh, and i did provide correct smpt server in settings and .env

Is something wrong with my provider smtp or meteor itself?

**Comment by salmoooon** [comment]
Probably related to [this](https://github.com/RocketChat/Rocket.Chat/issues/30811)

It's been broken since October
