### ISSUE TITLE
Error NPM install centos 7

### ISSUE THREAD

**Issue by kevintimothyift** [RocketChat/Rocket.Chat#31042]
> @kaciras/deasync@1.0.3 install /tmp/bundle/programs/server/npm/node_modules/@kaciras/deasync
> node script/prebuild.js install

Download failed (416): https://github.com/Kaciras/deasync/releases/download/v1.0.3/deasync-v1.0.3-node-linux-x64.tar.br
make: Entering directory `/tmp/bundle/programs/server/npm/node_modules/@kaciras/deasync/build'
  CXX(target) Release/obj.target/binding/src/deasync.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory `/tmp/bundle/programs/server/npm/node_modules/@kaciras/deasync/build'

> @napi-rs/pinyin@1.7.0 postinstall /tmp/bundle/programs/server/npm/node_modules/@napi-rs/pinyin
> node postinstall.js

> fibers@5.0.3 install /tmp/bundle/programs/server/npm/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-83-glibc` exists; testing
Binary is fine; exiting

> @rocket.chat/forked-matrix-sdk-crypto-nodejs@0.1.0-beta.13 postinstall /tmp/bundle/programs/server/npm/node_modules/@rocket.chat/forked-matrix-sdk-crypto-nodejs
> node check-exists.js

IMPORTANT:  Failed to load the native module for matrix-sdk-crypto-nodejs.  Matrix functionality depending on this will not work

> bcrypt@5.0.1 install /tmp/bundle/programs/server/npm/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/tmp/bundle/programs/server/npm/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote

> gc-stats@1.4.0 install /tmp/bundle/programs/server/npm/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v83-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for gc-stats@1.4.0 and node@14.21.3 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v83-linux-x64.tar.gz
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, unlink 'build/Makefile'
gyp ERR! System Linux 3.10.0-1160.102.1.el7.x86_64
gyp ERR! command "/home/centos/.nvm/versions/node/v14.21.3/bin/node" "/home/centos/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /tmp/bundle/programs/server/npm/node_modules/gc-stats
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/centos/.nvm/versions/node/v14.21.3/bin/node /home/centos/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/bundle/programs/server/npm/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1088:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
node-pre-gyp ERR! System Linux 3.10.0-1160.102.1.el7.x86_64
node-pre-gyp ERR! command "/home/centos/.nvm/versions/node/v14.21.3/bin/node" "/tmp/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /tmp/bundle/programs/server/npm/node_modules/gc-stats
node-pre-gyp ERR! node -v v14.21.3
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok
Failed to execute '/home/centos/.nvm/versions/node/v14.21.3/bin/node /home/centos/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gc-stats@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gc-stats@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/centos/.npm/_logs/2023-11-22T03_52_05_129Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/centos/.npm/_logs/2023-11-22T03_52_05_194Z-debug.log

I want to upgrade rocketchat from 6.2.11 to 6.4.5 but i get this error when i try to run npm install

node version: 14.21.3
mongodb: 5.0
OS: centos 7

**Comment by balc3r** [comment]
same :(
node version: 14.21.3
mongodb: 5.0
OS: Debian 12

**Comment by tregad** [comment]
Same issue with a current el8.9, 6.3.x worked fine though.
