### ISSUE TITLE
Issue with upgrade to latest from 6.3

### ISSUE THREAD

**Issue by Alexdc-12** [RocketChat/Rocket.Chat#31121]
### Description:

When trying to upgrade to any release past 6.3.1 i cannot start rocketchat service successfully. I receive the following error

```
root@ROCKETSERVER /tmp/bundle/programs/server # service rocketchat status
● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2023-11-30 19:29:13 GMT; 6s ago
  Process: 21857 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 21857 (code=exited, status=1/FAILURE)

Nov 30 19:29:13 ROCKETSERVER rocketchat[21857]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/
Nov 30 19:29:13 ROCKETSERVER rocketchat[21857]:     at server/services/meteor/service.ts:1:72
Nov 30 19:29:13 ROCKETSERVER rocketchat[21857]:     at module (server/services/meteor/service.ts:285:2)
Nov 30 19:29:13 ROCKETSERVER rocketchat[21857]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Nov 30 19:29:13 ROCKETSERVER rocketchat[21857]:     at Module.require (packages/modules-runtime.js:238:14)
Nov 30 19:29:13 ROCKETSERVER rocketchat[21857]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/
Nov 30 19:29:13 ROCKETSERVER rocketchat[21857]:   code: 'ERR_DLOPEN_FAILED'
Nov 30 19:29:13 ROCKETSERVER rocketchat[21857]: }
Nov 30 19:29:13 ROCKETSERVER systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Nov 30 19:29:13 ROCKETSERVER systemd[1]: rocketchat.service: Failed with result 'exit-code'.
```

### Steps to reproduce:

Upgrade as per the manual update instructions
Start service

### Expected behavior:

Service starts and server comes back online

### Actual behavior:

Server fails to start

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.1+ was trying 6.4.8 in this example
- Operating System: Ubuntu 18.04 LTS
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0

**Comment by Alexdc-12** [comment]
Upgrading to Ubuntu 20 fixed the issue
