### ISSUE TITLE
Version 6.5.0 will not start.

### ISSUE THREAD

**Issue by ymch** [RocketChat/Rocket.Chat#31145]
### Description:

I just updated Rocket.Chat to version 6.5.0, but the Rocket.Chat process was killed by an error that `'GLIBCXX_3.4.30' was not found`.

### Server Setup Information:

- Rocket.Chat: 6.5.0
- OS: Rocky Linux 9.3
- Node: v14.21.3
- NPM: 6.14.18
- MongoDB: 5.0.23 / wiredTiger (oplog Enabled)

### Relevant logs:

```
systemd: Started The Rocket.Chat server.
rocketchat: Some indexes for collection 'rocketchat_analytics' could not be created:
rocketchat: #011An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, unique: true, key: { room._id: 1, date: 1 }, name: "room._id_1_date_1", partialFilterExpression: { type: "rooms" } }, existing index: { v: 2, unique: true, key: { room._id: 1, date: 1 }, name: "room._id_1_date_1" }
rocketchat: Some indexes for collection 'rocketchat_uploads' could not be created:
rocketchat: #011An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, key: { rid: 1 }, name: "rid_1", sparse: true }, existing index: { v: 2, key: { rid: 1 }, name: "rid_1" }
rocketchat: /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
rocketchat:      throw error;
rocketchat:      ^
rocketchat: Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/Rocket.Chat/programs/server/npm/node_modules/isolated-vm/out/isolated_vm.node)
rocketchat:    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1173:18)
rocketchat:    at Module.load (internal/modules/cjs/loader.js:979:32)
rocketchat:    at Module.Mp.load (/opt/Rocket.Chat/programs/server/runtime.js:37:33)
rocketchat:    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
rocketchat:    at Module.require (internal/modules/cjs/loader.js:1003:19)
rocketchat:    at require (internal/modules/cjs/helpers.js:107:18)
rocketchat:    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/isolated-vm/isolated-vm.js:1:-44)
rocketchat:    at Module._compile (internal/modules/cjs/loader.js:1114:14)
rocketchat:    at Module.Mp._compile (/opt/Rocket.Chat/programs/server/runtime.js:77:23)
rocketchat:    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
rocketchat:    at Module.load (internal/modules/cjs/loader.js:979:32)
rocketchat:    at Module.Mp.load (/opt/Rocket.Chat/programs/server/runtime.js:37:33)
rocketchat:    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
rocketchat:    at Module.require (internal/modules/cjs/loader.js:1003:19)
rocketchat:    at require (internal/modules/cjs/helpers.js:107:18)
rocketchat:    at npmRequire (/opt/Rocket.Chat/programs/server/npm-require.js:111:12)
rocketchat:    at Module.useNode (packages/modules-runtime.js:751:18)
rocketchat:    at module (/opt/Rocket.Chat/programs/server/packages/modules.js:202897:8)
rocketchat:    at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat:    at Module.require (packages/modules-runtime.js:238:14)
rocketchat:    at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
rocketchat:    at module (app/integrations/server/lib/isolated-vm/isolated-vm.ts:2:43)
rocketchat:    at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat:    at Module.require (packages/modules-runtime.js:238:14)
rocketchat:    at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
rocketchat:    at module (app/integrations/server/lib/triggerHandler.js:1:1149)
rocketchat:    at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat:    at Module.require (packages/modules-runtime.js:238:14)
rocketchat:    at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
rocketchat:    at server/services/meteor/service.ts:1:72
rocketchat:    at module (server/services/meteor/service.ts:285:2)
rocketchat:    at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat:    at Module.require (packages/modules-runtime.js:238:14)
rocketchat:    at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22) {
rocketchat:  code: 'ERR_DLOPEN_FAILED'
rocketchat: }
systemd: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
systemd: rocketchat.service: Failed with result 'exit-code'.
systemd: rocketchat.service: Consumed 18.774s CPU time.
```
```
# dnf list installed | grep glibc
glibc.x86_64                                2.34-83.el9.7                                     @baseos
glibc-common.x86_64                         2.34-83.el9.7                                     @baseos
glibc-devel.x86_64                          2.34-83.el9.7                                     @appstream
glibc-gconv-extra.x86_64                    2.34-83.el9.7                                     @baseos
glibc-headers.x86_64                        2.34-83.el9.7                                     @appstream
glibc-langpack-en.x86_64                    2.34-83.el9.7                                     @baseos
```

**Comment by AntoninHL** [comment]
Hello...
 On my side, I have this error:

`systemctl status rocketchat.service
● rocketchat.service - The Rocket.Chat server
     Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-12-03 08:21:58 CET; 13min ago
    Process: 1114 ExecStart=/usr/bin/node /opt/rocket/main.js (code=exited, status=1/FAILURE)
   Main PID: 1114 (code=exited, status=1/FAILURE)

Dec 03 08:21:58 ns3616488 rocketchat[1114]:     at Module.moduleLink [as link] (/opt/rocket/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/>
Dec 03 08:21:58 nsXXXX rocketchat[1114]:     at server/services/meteor/service.ts:1:72
Dec 03 08:21:58 nsXXXX rocketchat[1114]:     at module (server/services/meteor/service.ts:285:2)
Dec 03 08:21:58 nsXXXX rocketchat[1114]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Dec 03 08:21:58 nsXXXX rocketchat[1114]:     at Module.require (packages/modules-runtime.js:238:14)
Dec 03 08:21:58 nsXXXX rocketchat[1114]:     at Module.moduleLink [as link] (/opt/rocket/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/>
Dec 03 08:21:58 nsXXXX rocketchat[1114]:   code: 'ERR_DLOPEN_FAILED'
Dec 03 08:21:58 nsXXXX rocketchat[1114]: }
Dec 03 08:21:58 nsXXXX systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Dec 03 08:21:58 nsXXXX systemd[1]: rocketchat.service: Failed with result 'exit-code'.`

**Comment by Gavilaan** [comment]
Same for me. Maybe you are as me on a Debian system. libstdc only ships with up to 3.4.28. I use the older version until this is solved.

**Comment by AntoninHL** [comment]
Solved for me...
just upgraded some packages...
`
dpkg -l | grep libstdc
ii  libstdc++-11-dev:amd64                11.4.0-1ubuntu1~22.04                   amd64        GNU Standard C++ Library v3 (development files)
ii  libstdc++6:amd64                      12.3.0-1ubuntu1~22.04                   amd64        GNU Standard C++ Library v3
`

**But big issue now**... Limitations are introduced... No more than 25 users is possible!!!
All my company is blocked.

**Comment by Rhywden** [comment]
Since my org is paying for support, I just created a ticket directly.

**Comment by etaormm** [comment]
@Antonin
There should be an option to revert to Community, according to their blog post.

**Comment by etaormm** [comment]
@bastien-effetb @AntoninHL you can just cancel the subscription and get Community features (that includes more than 25 users).
![image](https://github.com/RocketChat/Rocket.Chat/assets/104149242/e88f6a64-c4a5-45b5-a1df-e29ecc50c216)

**Comment by AntoninHL** [comment]
@rodrigok @ymch 

sorry, I can't cancel my subscription....

![image](https://github.com/RocketChat/Rocket.Chat/assets/50768/61ed257a-d917-472c-9090-03d551ef69e4)
