### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by AntoninHL** [RocketChat/Rocket.Chat#31151]
Hi Rocket Support team

I have a constant error in the logs:
`rocketchat[1125]: Error: ENOENT: no such file or directory, open '/opt/rocket/programs/web.browser/dynamic/client/views/omnichannel/sidebarItems.ts'
`

Could you help?

Pro Plan subscribed.

Antonin

**Comment by caskelly** [comment]
@renatobecker adding you for visibility.  @AntoninHL we will try to recreate on 6.5.0 and will provide an update shortly

**Comment by rijuoddusual1999** [comment]
hii @AntoninHL  which run command you are using and which os are you running?

**Comment by rodrigok** [comment]
Does the same issue happen if you access in an incognito window?

**Comment by guymarc** [comment]
I checked on my running container, the file sidebarItems.ts does not exist, but ther is a sidebarItems.ts**x**
Here is the full log entry:
Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/client/views/omnichannel/sidebarItems.ts'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at readTree (packages/dynamic-import.js:188:10)
    at IncomingMessage.<anonymous> (packages/dynamic-import.js:102:37)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)

**Comment by LeeThompson** [comment]
I get this on 6.6.0, starter plan (no need for anything more)
