### ISSUE TITLE
WebDAV Application Error

### ISSUE THREAD

**Issue by kertiskz** [RocketChat/Rocket.Chat#31183]
when downloading a folder, the error message "Application Error The application GUI just crashed."

```
react-dom.production.min.js:224  Error: mime is required
    at t (getNodeIconType.ts:17:13)
    at eval (WebdavFilePickerTable.tsx:76:26)
    at Array.map (<anonymous>)
    at eval (WebdavFilePickerTable.tsx:75:21)
    at Ch (react-dom.production.min.js:165:137)
    at li (react-dom.production.min.js:188:154)
    at ck (react-dom.production.min.js:277:343)
    at bk (react-dom.production.min.js:258:347)
    at ak (react-dom.production.min.js:258:278)
    at Tj (react-dom.production.min.js:258:138)
Ni @ react-dom.production.min.js:224
Si.c.payload @ react-dom.production.min.js:225
Cg @ react-dom.production.min.js:138
pi @ react-dom.production.min.js:192
ck @ react-dom.production.min.js:277
bk @ react-dom.production.min.js:258
ak @ react-dom.production.min.js:258
Tj @ react-dom.production.min.js:258
Lj @ react-dom.production.min.js:251
eval @ react-dom.production.min.js:131
exports.unstable_runWithPriority @ scheduler.production.min.js:26
gg @ react-dom.production.min.js:130
jg @ react-dom.production.min.js:131
ig @ react-dom.production.min.js:130
Jg @ react-dom.production.min.js:245
Oh @ react-dom.production.min.js:178
eval @ WebdavFilePickerModal.tsx:89
await in eval (асинхронно)
eval @ WebdavFilePickerModal.tsx:165
fk @ react-dom.production.min.js:270
exports.unstable_runWithPriority @ scheduler.production.min.js:26
gg @ react-dom.production.min.js:130
Oj @ react-dom.production.min.js:269
Ib @ react-dom.production.min.js:300
gd @ react-dom.production.min.js:81
```
this situation occurs unless the destination folder is empty

Server Setup Information

Version of Rocket.Chat Server: 6.5.0
Operating System: synology
Deployment Method: docker
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
NodeJS Version: 14.21.3
MongoDB Version: 6.0.12

**Comment by AndreasScharfCPB** [comment]
Same here and also here: https://forums.rocket.chat/t/webdav-crashes-gui/17865 
I’ve got the same behaviour and was testing against the official nextcloud demo server.
Server could be added in a channel, but when trying to use/access it, the GUI crashes.
RocketChat Version 6.4.1

**Comment by jimisens** [comment]
Same problem with RocketChat 6.12.0 and Nexcloud. Anyone found a solution ??

**Comment by Den4ik92** [comment]
Hi, the problem is currently in several places: 
1) apps/meteor/client/lib/utils/timeAgo.ts the timeAgo function should not be async (This was fixed by  [#34901](https://github.com/RocketChat/Rocket.Chat/pull/34901) in version 7.3.0)
2)apps/meteor/client/views/room/webdav/WebdavFilePickerModal/lib/getNodeIconType.ts the "mime" argument is required, although not all files have it (for example, a folder)
