### ISSUE TITLE
LDAP-users are getting deactivated.

### ISSUE THREAD

**Issue by peko-hki** [RocketChat/Rocket.Chat#31212]
### Description:

Since we updated to rocketchat 6.5.0 ldap users can't login anymore. Running sessions are fine,
but if one user is trying to log on the account gets deactivated.

### Steps to reproduce:

1. Update from x.x to 6.5.0
2. switch to community version
3.try to login with a LDAP user

### Expected behavior:

get a session

### Actual behavior:

"Before you can login, your account must be manually activated by an administrator."

On the admin panel NO user is shown. There is a an error message:

"PlanExecutor error during aggregation :: caused by :: can't convert from BSON type array to String"

![grafik](https://github.com/RocketChat/Rocket.Chat/assets/92443717/83d1590b-61e5-4798-9b1b-26df60d1df50)

### Server Setup Information:
- Version of Rocket.Chat Server:   6.5.0
-  OS:  Ubuntu 22.04 LTS
-  Deployment Method: snap
- Version der Anwendungs-Engine  1.41.0
- Node-Version v14.21.2
- MongoDB 5.0.15 / wiredTiger (oplog Aktiviert)

### Client Setup Information

-  Browser Version: Firefox and chrome

### Additional context

ldap connection

### Relevant logs:

{"level":35,"time":"2023-12-12T11:44:33.897Z","pid":1628,"hostname":"chat","name":"API","method":"GET","url":"/api/v1/users.list?count=25&fields=%7B%22name%22%3A1%2C%22username%22%3A1%2C%22emails%22%3A1%2C%22roles%22%3A1%2C%22status%22%3A1%2C%22avatarETag%22%3A1%2C%22active%22%3A1%7D&offset=0&query=%7B%22%24or%22%3A%5B%7B%22emails.address%22%3A%7B%22%24regex%22%3A%22%22%2C%22%24options%22%3A%22i%22%7D%7D%2C%7B%22username%22%3A%7B%22%24regex%22%3A%22%22%2C%22%24options%22%3A%22i%22%7D%7D%2C%7B%22name%22%3A%7B%22%24regex%22%3A%22%22%2C%22%24options%22%3A%22i%22%7D%7D%5D%7D&sort=%7B%20%22name%22%3A%201%20%7D","userId":"vqGa7BftEP5Ao4jRY","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0","host":"mati.hki-jena.de:3000","referer":"https://chat.hki-jena.de/admin/users","remoteIP":"10.16.14.234","err":{"type":"MongoServerError","message":"PlanExecutor error during aggregation :: caused by :: can't convert from BSON type array to String","stack":"MongoServerError: PlanExecutor error during aggregation :: caused by :: can't convert from BSON type array to String<br>    at Connection.onMessage (/snap/rocketchat-server/1597/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:231:30)<br>    at MessageStream.<anonymous> (/snap/rocketchat-server/1597/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:61:60)<br>    at MessageStream.emit (events.js:400:28)<br>    at MessageStream.emit (domain.js:475:12)<br>    at processIncomingData (/snap/rocketchat-server/1597/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:125:16)<br>    at MessageStream._write (/snap/rocketchat-server/1597/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)<br>    at writeOrBuffer (internal/streams/writable.js:358:12)<br>    at MessageStream.Writable.write (internal/streams/writable.js:303:10)<br>    at Socket.ondata (internal/streams/readable.js:731:22)<br>    at Socket.emit (events.js:400:28)<br>    at Socket.emit (domain.js:475:12)<br>    at addChunk (internal/streams/readable.js:293:12)<br>    at readableAddChunk (internal/streams/readable.js:267:9)<br>    at Socket.Readable.push (internal/streams/readable.js:206:10)<br>    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)<br>    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)<br> => awaited here:<br>    at Function.Promise.await (/snap/rocketchat-server/1597/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/api/server/v1/users.ts:511:16<br>    at /snap/rocketchat-server/1597/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/snap/rocketchat-server/1597/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at packages/meteor.js:367:22<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)<br>    at app/api/server/api.ts:635:39<br>    at /snap/rocketchat-server/1597/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","ok":0,"code":16007,"codeName":"Location1600

**Comment by nayanprompt** [comment]
facing same issue after upgrading to 6.5 community
