### ISSUE TITLE
Service '$node.list' is not available -  Workspace Info page unavailable

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#31354]
### Description:

Since upgrading Mongo from v4 to v5 I am unable to access /admin/info Workspaces page as per the screenshot attached.

The following error is in the logs.

```
{
  "level": 35,
  "time": "2023-12-19T14:31:20.949Z",
  "pid": 1,
  "hostname": "myserver.myhost.com",
  "name": "API",
  "method": "GET",
  "url": "/api/v1/instances.get",
  "userId": "hYHbjXWQMSRMu2szG",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  "host": "chat.myhost.com",
  "referer": "https://chat.myhost.com/admin/info",
  "remoteIP": "my.remote.I.P",
  "err": {
    "type": "ServiceNotAvailableError",
    "message": "Service '$node.list' is not available.",
    "stack": "ServiceNotAvailableError: Service '$node.list' is not available.\n    at ServiceBroker.findNextActionEndpoint (/app/bundle/programs/server/npm/node_modules/moleculer/src/service-broker.js:1156:13)\n    at ServiceBroker.call (/app/bundle/programs/server/npm/node_modules/moleculer/src/service-broker.js:1197:26)\n    at ee/server/local-services/instance/service.ts:198:22\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/v1/instances.ts:27:21\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at packages/meteor.js:367:22\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)\n    at app/api/server/api.ts:635:39\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40",
    "code": 404,
    "data": {
      "action": "$node.list"
    },
    "retryable": true
  },
  "status": 400,
  "responseTime": 6,
  "msg": "Service '$node.list' is not available."
}

```

### Steps to reproduce:
Upgrade to local Mongo 5  - (Mongo is not dockerised on this install)
Stop/Start rocket docker VM
Access Workspace Info page with any client

### Expected behavior:

View the Workspace Info page

### Actual behavior:

Page displays 

"Error loading pages"

![Screenshot_2024-01-02_14-48-28](https://github.com/RocketChat/Rocket.Chat/assets/3800384/e56e46a6-d0fb-48ad-9127-22346a0d7db6)

### Server Setup Information:

- Version of Rocket.Chat Server:  6.5.0 - EE licence
- Operating System: Centos
- Deployment Method: Docker
- Number of Running Instances:  1
- MongoDB Version: 5.0.x
- Apache reverse proxy 

### Additional context

System upgraded with no issues with docker continuously following my own guide on the help pages ;-)

I am not sure whether this is Rocket/Node or possibly the reverse proxy not understanding a URL used to access the page?

How would you normally access  '$node.list' ?

**Comment by reetp** [comment]
As a follow up I just upgraded this docker instance to 6.5.1
Whilst I was about it I removed a deprecated smallFiles option from the mongod,.conf
Restarted Mongo and then upgraded Rocket and it now works.

I have another instance I will test tomorrow.

**Comment by broferek** [comment]
FYI, I had the same issue in 6.5.3. Upgrading to 6.6.1 resolved it without making any modification to the Mongodb config on my side.

**Comment by reetp** [comment]
Upgrading to 6.6.x seems to have fixed it for me.
Must be a related bug/PR but can't see it.
Closing.

**Comment by reetp** [comment]
And still there on one 6.9.3 but not on another two with identical setups.

**Comment by prdaneshi** [comment]
same problem here on 6.13. what's the solution?

**Comment by MakselPr** [comment]
> same problem here on 6.13. what's the solution?

Rocket.Chat Version: 6.13.0 
NodeJS Version: 14.21.3 - x64
MongoDB Version: 5.0.29 
MongoDB Engine: wiredTiger
 Commit Hash: e9700f68b7
 
 I had the same issue.
In the logs:
rocketchat Service '$node.list' is not available.

I just ran systemctl restart rocketchat, and now I see in the logs:
'$node' service is registered.
Service '$node' started.

Currently, there are no issues.
