### ISSUE TITLE
failed to upload an icon with `ico` format for chatrooms

### ISSUE THREAD

**Issue by garylavayou** [RocketChat/Rocket.Chat#31378]
### Description:

When upload an icon for a chatroom from the Desktop client, user can select an `ico` file, but the upload will fail.
If Rocket.Chat server does not support to use `ico` files as avatars, the Desktop client should exclude `*.ico` from the system's
file selection dialog, but now the `*.ico` type is contained in the picture file filter (in Windows).

![image](https://github.com/RocketChat/Rocket.Chat/assets/25133690/258540b5-76fd-4080-ae47-3f50056a9086)

### Steps to reproduce:

1. Go to the "**#General**" channel;
2. Click on "**Chatroom**" info and click edit;
3. Click the "**upload**" button under the chatroom avatar;
4. Choose an `.ico` file (`%LocalAppData%\Programs\Rocket.Chat\resources\build\icon.ico`) to upload.

### Expected behavior:

Upload succeeds and the chatroom avatar is refreshed. 

### Actual behavior:

Uploading process keeps waiting, until the background task failed.

### Server Setup Information:

- Version of Rocket.Chat Server: `6.5.1`
- Operating System: `Linux 5.15.133.1-microsoft-standard-WSL2`
- Deployment Method: `docker`
- Number of Running Instances: `1`
- NodeJS Version: `v14.21.3`
- MongoDB Version: `5.0.5 / wiredTiger`

### Client Setup Information

- Desktop App or Browser Version: `Desktop 3.9.11`
- Operating System: `Windows 10 22H2`

### Additional context

If we save the `ico` file as a `png` file, and upload again, the operation would be success.

### Relevant logs:

```log
2024-01-05 13:18:57 === UnHandledPromiseRejection ===
2024-01-05 13:18:57 errorClass [Error]: Error: Input file contains unsupported image format [ufs: cannot upload file]
2024-01-05 13:18:57     at server/ufs/ufs-methods.ts:74:10
2024-01-05 13:18:57     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
2024-01-05 13:18:57   isClientSafe: true,
2024-01-05 13:18:57   error: 'ufs: cannot upload file',
2024-01-05 13:18:57   reason: Error: Input file contains unsupported image format
2024-01-05 13:18:57    => awaited here:
2024-01-05 13:18:57       at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
2024-01-05 13:18:57       at app/file-upload/server/lib/FileUpload.ts:235:17
2024-01-05 13:18:57       at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2024-01-05 13:18:57    => awaited here:
2024-01-05 13:18:57       at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
2024-01-05 13:18:57       at server/ufs/ufs-store.ts:360:4
2024-01-05 13:18:57       at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2024-01-05 13:18:57    => awaited here:
2024-01-05 13:18:57       at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
2024-01-05 13:18:57       at server/ufs/ufs-methods.ts:42:4
2024-01-05 13:18:57       at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40,
2024-01-05 13:18:57   details: undefined,
2024-01-05 13:18:57   errorType: 'Meteor.Error'
2024-01-05 13:18:57 }
2024-01-05 13:18:57 ---------------------------------
2024-01-05 13:18:57 Errors like this can cause oplog processing errors.
2024-01-05 13:18:57 Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
2024-01-05 13:18:57 Future node.js versions will automatically exit the process
2024-01-05 13:18:57 =================================
```

**Comment by hugocostadev** [comment]
I added a fix to the UnHandledPromiseRejection, but the .ico still is not supported due to its limitations

**Comment by Sayan4444** [comment]
Hi @hugocostadev as much as I have been able to understand, the issue is with the server side code when we try to upload the picture. However I can think of 3 solutions and let me share it with you-
1. Changing the file to png. We must change the base64 image all together and not just the type of the file. Changing the type wont make any difference.
2.  Store the image as it is without converting it to base64
3. throw a special error whenever we find a .ico file 

however I would prefer 1 to be implemented as internals should the abstracted from the end user and they should be able to do whatever they like.

**Comment by garylavayou** [comment]
@Sayan4444 I think the most straightforward method is to remove `*.ico` filter from the Windows's file selector dialog, so that users will bot be able to select an `.ico` icon file.

![image](https://github.com/RocketChat/Rocket.Chat/assets/25133690/b0336870-39f5-486a-b8d0-58dac74c6b46)

**Comment by Sayan4444** [comment]
@garylavayou thats a great solution and can be very easily implemented. But there always remain an option just below it where I can select "anyfile" and selecting that will make server crash. Never the less should I got ahead and raise a PR?
