### ISSUE TITLE
rocket chat upgrades are broken

### ISSUE THREAD

**Issue by gstlouisgit** [RocketChat/Rocket.Chat#31664]
I have tried on several occasions to upgrade rocket chat using the manual [https://docs.rocket.chat/deploy/deploy-rocket.chat/updating-rocket.chat](link)

I have tried upgrading from a previous version.  I have tried the upgrade.  I have tried snapd.  Nothing has worked and I've received all sort of different errors.  There is clearly something broken with the upgrade, and from what I have read, a lot of people are suffering the same fate.  Why is that?

When I did the upgrade, the furthest I got was it booting with error:

Cannot find module '/opt/Rocket.Chat/programs/server/node_modules/fibers/bin/linux-x64-1
08-glibc/fibers'

I have node:
root@web:~# node -v
v14.21.3

However, in the systemctl restart it looks like it thinks I have node 18*
Feb 06 12:13:09 web rocketchat[9214]:     at Object.<anonymous> (/opt/Rocket.Chat/programs/server/boot.js:2:15)
**Feb 06 12:13:09 web rocketchat[9214]: Node.js v18.19.0**
Feb 06 12:13:09 web systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Feb 06 12:13:09 web systemd[1]: rocketchat.service: Failed with result 'exit-code'.

I have spent hours trying to get this going, and I copied my previous version, that when I initially did this and failed I was able to restore to my previous.  now even the previous does not work.

So there is seriously something wrong, and with all the attempts I wouldn't be surprised that I broke something else. 
I have never had such difficult installing a software like this before.

does anymore know why systemctl attempting to start RC would show  Node.js v18.19.0?  And the error it says cannot find module path to fibers, it is present!

**Comment by gstlouisgit** [comment]
Thanks for your time 
well, I haven't had good luck with this and I've tried several times.  Looking at my config: /lib/systemd/system/rocketchat.service

This is what I have (I've tried adding Environment=NODE_VERSION=14.21.3 and the same problem )

[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.service
[Service]
#Environment=NODE_VERSION=14.21.3
ExecStart=/usr/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01 MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01 ROOT_URL=http://collaborate.smbservices.ca:3000/ PORT=3000
[Install]
WantedBy=multi-user.target

**Comment by gstlouisgit** [comment]
Thanks for your comment.  It led me to check the node version with the path and from what I understand I have two node's running!?  I got frustrated doing the manual upgrade so I turned to install snapd to install rocket chat.  I'm assuming this might have done this...?

```
root@web:~# whereis node
node: /usr/bin/node /usr/local/bin/node /usr/include/node /usr/share/man/man1/node.1.gz

root@web:~# /usr/bin/node -v
v18.19.0

root@web:~# /usr/local/bin/node -v
v14.21.3
```

So I went into vim /lib/systemd/system/rocketchat.service to change the ExecStart to below.

It still did not work trying `systemctl daemon-reload` and `systemctl restart rocketchat
`

```
[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.service
[Service]
#Environment=NODE_VERSION=14.21.3
#ExecStart=/usr/bin/node /opt/Rocket.Chat/main.js
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01 MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01 ROOT_URL=http://collaborate.smbservices.ca:3000/ PORT=3000
[Install]
WantedBy=multi-user.target
```

**Comment by gstlouisgit** [comment]
sorry, still does not work, but error is different error 

when doing ```/usr/local/bin/npm install --production```

```
root@web:/opt/Rocket.Chat# /usr/local/bin/npm install --production
npm WARN saveError ENOENT: no such file or directory, open '/opt/Rocket.Chat/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/Rocket.Chat/package.json'
npm WARN Rocket.Chat No description
npm WARN Rocket.Chat No repository field.
npm WARN Rocket.Chat No README data
npm WARN Rocket.Chat No license field.

up to date in 0.295s
found 0 vulnerabilities
```

when restarting RC


```
 systemd[1]: Started The Rocket.Chat server.
 rocketchat[24467]: Some indexes for collection 'rocketchat_analytics' could not be created:
 rocketchat[24467]:         An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, unique: true, key: { room._id: 1, date: 1 }, name: "room._id_1_date_1", partialFilterExpression: { type: "rooms" } }, existing index: { v: 2, unique: true, key: { room._id: 1, date: 1 }, name: "room._id_1_date_1" }
 rocketchat[24467]: (node:24467) UnhandledPromiseRejectionWarning: MongoServerError: An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, unique: true, key: { room._id: 1, date: 1 }, name: "room._id_1_date_1", partialFilterExpression: { type: "rooms" } }, existing index: { v: 2, unique: true, key: { room._id: 1, date: 1 }, name: "room._id_1_date_1" }
 rocketchat[24467]:     at Connection.onMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:231:30)
 rocketchat[24467]:     at MessageStream.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:61:60)
 rocketchat[24467]:     at MessageStream.emit (events.js:400:28)
domain rocketchat[24467]:     at MessageStream.emit (domain.js:475:12)
 rocketchat[24467]:     at processIncomingData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
 rocketchat[24467]:     at MessageStream._write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
 rocketchat[24467]:     at writeOrBuffer (internal/streams/writable.js:358:12)
 rocketchat[24467]:     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
 rocketchat[24467]:     at Socket.ondata (internal/streams/readable.js:731:22)
 rocketchat[24467]:     at Socket.emit (events.js:400:28)
 rocketchat[24467]:     at Socket.emit (domain.js:475:12)
 rocketchat[24467]:     at addChunk (internal/streams/readable.js:293:12)
 rocketchat[24467]:     at readableAddChunk (internal/streams/readable.js:267:9)
 rocketchat[24467]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
 rocketchat[24467]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
 rocketchat[24467]: (Use `node --trace-warnings ...` to show where the warning was created)
 rocketchat[24467]: (node:24467) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
 rocketchat[24467]: (node:24467) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 rocketchat[24467]: Some indexes for collection 'rocketchat_nps_vote' could not be created:
 rocketchat[24467]:         An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, unique: true, key: { npsId: 1, identifier: 1 }, name: "npsId_1_identifier_1" }, existing index: { v: 2, key: { npsId: 1, identifier: 1 }, name: "npsId_1_identifier_1" }
 rocketchat[24467]: (node:24467) UnhandledPromiseRejectionWarning: MongoServerError: An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, unique: true, key: { npsId: 1, identifier: 1 }, name: "npsId_1_identifier_1" }, existing index: { v: 2, key: { npsId: 1, identifier: 1 }, name: "npsId_1_identifier_1" }
 rocketchat[24467]:     at Connection.onMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:231:30)
 rocketchat[24467]:     at MessageStream.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:61:60)
 rocketchat[24467]:     at MessageStream.emit (events.js:400:28)
 rocketchat[24467]:     at MessageStream.emit (domain.js:475:12)
 rocketchat[24467]:     at processIncomingData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
 rocketchat[24467]:     at MessageStream._write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
 rocketchat[24467]:     at writeOrBuffer (internal/streams/writable.js:358:12)
 rocketchat[24467]:     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
 rocketchat[24467]:     at Socket.ondata (internal/streams/readable.js:731:22)
 rocketchat[24467]:     at Socket.emit (events.js:400:28)
 rocketchat[24467]:     at Socket.emit (domain.js:475:12)
 rocketchat[24467]:     at addChunk (internal/streams/readable.js:293:12)
 rocketchat[24467]:     at readableAddChunk (internal/streams/readable.js:267:9)
 rocketchat[24467]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
 rocketchat[24467]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
 rocketchat[24467]: (node:24467) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by gstlouisgit** [comment]
I do not have this path or nvm
/root/.nvm/versions/node/v14.21.3/bin/npm install

I do not see how moving bundle folder to /opt/rocket chat will work if I do systemctl restart

**Comment by gstlouisgit** [comment]
well I did follow their upgrade procedure and downloaded their content, did install and mv in a fresh /opt/Rocket.Chat folder, and several different strategies so I'm not sure.  But I can see a lot of people suffering from this.  Mattermost upgrade took about 5 minutes, and it was back up and running.  I guess I'll just have to stick with Mattermost.  Or try the install in a separate container.
Thanks again for your time.  And I agree, it feels like rocketchat has moved too fast and if you miss doing an upgrade you are screwed.

**Comment by florisvangeel** [comment]
True no attention for admins to keep up in the marketing race, however as first post suggested use NVM so you have node behave and make your systemd accordingly.. mine looks like this, i use a systemuser called rocketchat who owns the app and runs it with nvm installed under the profile of this user.
```
[Unit]
Description=Rocket.Chat Server
After=syslog.target
After=network.target

[Service]
Type=simple
Restart=always
StandardOutput=syslog
SyslogIdentifier=RocketChat
User=rocketchat
Group=rocketchat
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs0&directConnection=true
Environment=MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs0&directConnection=true
Environment=ROOT_URL=https://drupalchat.me
Environment=PORT=3000
Environment=DEPLOY_PLATFORM=ansible
WorkingDirectory=/var/lib/rocket.chat
ExecStart=/var/lib/rocket.chat/.nvm/versions/node/v14.19.3/bin/node /var/lib/rocket.chat/bundle/main.js

[Install]
WantedBy=multi-user.target
```
Probably this issue can be closed now.
