### ISSUE TITLE
error after downgrade from 6.5.2 to 6.4.5

### ISSUE THREAD

**Issue by jankubala** [RocketChat/Rocket.Chat#31661]
Today I've tried to downgrade my snap instalation of RC (due to broken notifications) and after that cannt connect to RC Server anymore.
Between these versions, the starter license was accepted.

### Steps to reproduce:
snap revert rocketchat-server

### Server Setup Information:
- Version of Rocket.Chat Server:  6.5.2 -> 6.4.5
- Operating System:  Ubuntu 20.04
- Deployment Method: snap

### Relevant logs:

```
sudo service snap.rocketchat-server.rocketchat-server status
● snap.rocketchat-server.rocketchat-server.service - Service for snap application rocketchat-server.rocketchat-server
     Loaded: loaded (/etc/systemd/system/snap.rocketchat-server.rocketchat-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-02-06 08:37:44 CET; 31min ago
   Main PID: 490130 (start_rocketcha)
      Tasks: 12 (limit: 629145)
     Memory: 515.7M
     CGroup: /system.slice/snap.rocketchat-server.rocketchat-server.service
             ├─490130 /bin/bash /snap/rocketchat-server/1584/bin/start_rocketchat.sh
             └─490201 node /snap/rocketchat-server/1584/main.js

lut 06 08:38:04 gitlab.xxx.local rocketchat-server.rocketchat-server[490201]:     at Function.Promise.await (/snap/rocketchat-server/1584/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
lut 06 08:38:04 gitlab.xxx.local rocketchat-server.rocketchat-server[490201]:     at ee/app/license/server/settings.ts:33:3
lut 06 08:38:04 gitlab.xxx.local rocketchat-server.rocketchat-server[490201]:     at /snap/rocketchat-server/1584/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
lut 06 08:38:04 gitlab.xxx.local rocketchat-server.rocketchat-server[490201]: (node:490201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
lut 06 08:38:04 gitlab.xxx.local rocketchat-server.rocketchat-server[490201]: (node:490201) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
lut 06 08:38:04 gitlab.xxx.local rocketchat-server.rocketchat-server[490201]: LocalStore: store created at
lut 06 08:38:04 gitlab.xxx.local rocketchat-server.rocketchat-server[490201]: LocalStore: store created at
lut 06 08:38:04 gitlab.xxx.local rocketchat-server.rocketchat-server[490201]: LocalStore: store created at
lut 06 08:38:04 gitlab.xxx.local rocketchat-server.rocketchat-server[490201]: MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
lut 06 08:38:04 gitlab.xxx.local rocketchat-server.rocketchat-server[490201]: {"level":40,"time":"2024-02-06T07:38:04.570Z","pid":490201,"hostname":"gitlab.xxx.local","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"}

```

**Comment by florisvangeel** [comment]
You can't downgrade, so be sure to take proper backups before upgrading.
