### ISSUE TITLE
Exception in delivering result of invoking 'sendSMTPTestEmail': ReferenceError: error is not defined

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#3178]
Your Rocket.Chat version: 0.29.0

SERVER:
```
rocket.chat.1-1 Exception while invoking method 'sendSMTPTestEmail' URIError: URI malformed
rocket.chat.1-1     at decodeURIComponent (native)
rocket.chat.1-1     at makePool (packages/email/email.js:29:1)
rocket.chat.1-1     at packages/email/email.js:50:1
rocket.chat.1-1     at packages/underscore/underscore.js:750:1
rocket.chat.1-1     at Object.Email.send (packages/email/email.js:183:1)
rocket.chat.1-1     at [object Object].Meteor.methods.sendSMTPTestEmail (packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:12:9)
rocket.chat.1-1     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)
rocket.chat.1-1     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
rocket.chat.1-1     at livedata_server.js:708:19
rocket.chat.1-1     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```

CLIENT:
```
Exception in delivering result of invoking 'sendSMTPTestEmail': ReferenceError: error is not defined
    at https://chat.ennit.net/ba607b630e92d975c1bf1efc281ead9491f6e723.js?meteor_js_resource=true:379:26935
    at ._callback (https://chat.ennit.net/ba607b630e92d975c1bf1efc281ead9491f6e723.js?meteor_js_resource=true:3:6834)
    at i.extend._maybeInvokeCallback (https://chat.ennit.net/ba607b630e92d975c1bf1efc281ead9491f6e723.js?meteor_js_resource=true:52:8277)
    at i.extend.receiveResult (https://chat.ennit.net/ba607b630e92d975c1bf1efc281ead9491f6e723.js?meteor_js_resource=true:52:8585)
    at i.extend._livedata_result (https://chat.ennit.net/ba607b630e92d975c1bf1efc281ead9491f6e723.js?meteor_js_resource=true:52:19788)
    at o (https://chat.ennit.net/ba607b630e92d975c1bf1efc281ead9491f6e723.js?meteor_js_resource=true:52:6563)
    at https://chat.ennit.net/ba607b630e92d975c1bf1efc281ead9491f6e723.js?meteor_js_resource=true:52:567
    at Array.forEach (native)
    at Function.A.each.A.forEach (https://chat.ennit.net/ba607b630e92d975c1bf1efc281ead9491f6e723.js?meteor_js_resource=true:1:865)
    at t.socket.onmessage (https://chat.ennit.net/ba607b630e92d975c1bf1efc281ead9491f6e723.js?meteor_js_resource=true:52:525)
```

**Comment by marceloschmidt** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/commit/b8dfae54fda4a4fa4506c1bb1e5024fdbff6e091
