### ISSUE TITLE
The Docker version Keeps Restarting, cannot access at all

### ISSUE THREAD

**Issue by acsusanto** [RocketChat/Rocket.Chat#31784]
I tried updating the docker version and it crashed my server. The server basically keeps restarting and I can't get into the server. I tried on a new virtual machine by downloading the compose.yml and it has the same thing. I think it has something to do with this error. I am not that knowledgable in docker or mongodb. I hope you can give me some insight on fixing this problem.

My ubuntu version is:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

This is part of the error I see in the logs. Please help. Thanks.
error: MongoNetworkError: getaddrinfo EAI_AGAIN mongodb
rocketchat-1  |             at connectionFailureError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:387:20)
rocketchat-1  |             at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:310:22)
rocketchat-1  |             at Object.onceWrapper (events.js:520:26)
rocketchat-1  |             at Socket.emit (events.js:400:28)
rocketchat-1  |             at emitErrorNT (internal/streams/destroy.js:106:8)
rocketchat-1  |             at emitErrorCloseNT (internal/streams/destroy.js:74:3)
rocketchat-1  |             at processTicksAndRejections (internal/process/task_queues.js:82:21) {
rocketchat-1  |           cause: Error: getaddrinfo EAI_AGAIN mongodb
rocketchat-1  |               at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
rocketchat-1  |             errno: -3001,
rocketchat-1  |             code: 'EAI_AGAIN',
rocketchat-1  |             syscall: 'getaddrinfo',
rocketchat-1  |             hostname: 'mongodb'
rocketchat-1  |           },
rocketchat-1  |           [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
rocketchat-1  |         },

**Comment by akshayg147** [comment]
The [Symbol(errorLabels)]: Set(1) { 'ResetPool' } in your error log indicates that the error belongs to the 'ResetPool' category. In the context of MongoDB, this usually means there is an issue with the connection pool to the MongoDB server.

Below checks might help:
1. Ensure that you've made .env file.
2. Also the .env file should be in same directory as your docker compose file.
3. Check your mongo connection and mongo_url that you've written in .env file.



Hope this helps. :)

**Comment by litecactus** [comment]
can you give a `docker ps`
what mongodb tag are you using?
