### ISSUE TITLE
GLIBCXX_3.4.29 not found

### ISSUE THREAD

**Issue by enricocirne** [RocketChat/Rocket.Chat#31794]
### Description:

Hei there guys,

I havent used my rocket.chat on my Unraid server in a while, so I didnt notice since when the error accures. If I am trying to start my rocket.chat Docker in Unraid, it will always stop itself after a few seconds. My logs do show this error: 

`Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /app/bundle/programs/server/npm/node_modules/isolated-vm/out/isolated_vm.node)`

I do not find any information of that error, neither in Unraid forums, Reddit or rocket.chat forums. Please help.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.1 (I think)
- Operating System: Unraid Docker (library/rocket.chat)
- MongoDB Version: 7.0.5
- Mongosh: 2.1.4

### Logs

/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /app/bundle/programs/server/npm/node_modules/isolated-vm/out/isolated_vm.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1173:18)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/app/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/app/bundle/programs/server/npm/node_modules/isolated-vm/isolated-vm.js:1:-44)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module.Mp._compile (/app/bundle/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/app/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at npmRequire (/app/bundle/programs/server/npm-require.js:111:12)
    at Module.useNode (packages/modules-runtime.js:751:18)
    at module (/app/bundle/programs/server/packages/modules.js:205069:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (app/integrations/server/lib/isolated-vm/isolated-vm.ts:2:43)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (app/integrations/server/lib/triggerHandler.js:1:1149)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at server/services/meteor/service.ts:1:72
    at module (server/services/meteor/service.ts:286:2)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22) {
  code: 'ERR_DLOPEN_FAILED'
}
/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /app/bundle/programs/server/npm/node_modules/isolated-vm/out/isolated_vm.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1173:18)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/app/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/app/bundle/programs/server/npm/node_modules/isolated-vm/isolated-vm.js:1:-44)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module.Mp._compile (/app/bundle/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/app/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at npmRequire (/app/bundle/programs/server/npm-require.js:111:12)
    at Module.useNode (packages/modules-runtime.js:751:18)
    at module (/app/bundle/programs/server/packages/modules.js:205069:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (app/integrations/server/lib/isolated-vm/isolated-vm.ts:2:43)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (app/integrations/server/lib/triggerHandler.js:1:1149)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at server/services/meteor/service.ts:1:72
    at module (server/services/meteor/service.ts:286:2)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by sampaiodiego** [comment]
this has been fixed on 6.6.1

**Comment by enricocirne** [comment]
> this has been fixed on 6.6.1

What do I need to do?
