### ISSUE TITLE
Bricked upgrade. (0.29.0 to 0.30.0)

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#3189]
Your Rocket.Chat version: 0.30.0

The upgrade went wrong this time. I did what I always would do:

```
root@server55:/home/k0nsl/rc01# git fetch origin && git reset --hard origin/develop && meteor
```

Upon launching `meteor` as per above, it threw this:
```
W20160510-03:46:16.240(-4)? (STDERR) /root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160510-03:46:16.240(-4)? (STDERR)                                            throw(ex);
W20160510-03:46:16.240(-4)? (STDERR)                                                  ^
W20160510-03:46:16.250(-4)? (STDERR) ReferenceError: Tinytest is not defined
W20160510-03:46:16.251(-4)? (STDERR)     at Template.hello.greeting (packages/percolate_synced-cron/synced-cron-tests.js:15:1)
W20160510-03:46:16.251(-4)? (STDERR)     at /home/k0nsl/rc01/.meteor/local/build/programs/server/packages/percolate_synced-cron.js:606:4
W20160510-03:46:16.251(-4)? (STDERR)     at /home/k0nsl/rc01/.meteor/local/build/programs/server/packages/percolate_synced-cron.js:674:3
W20160510-03:46:16.251(-4)? (STDERR)     at /home/k0nsl/rc01/.meteor/local/build/programs/server/boot.js:242:10
W20160510-03:46:16.251(-4)? (STDERR)     at Array.forEach (native)
W20160510-03:46:16.252(-4)? (STDERR)     at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160510-03:46:16.252(-4)? (STDERR)     at /home/k0nsl/rc01/.meteor/local/build/programs/server/boot.js:137:5
```
This later 'magically' disappeared by itself. But something more confusing surfaced in it's place.

Now when I try to run Rocket.Chat it tells me:
```
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
=> Errors prevented startup:

   While building the application:
   /home/k0nsl/rc01/packages/rocketchat-mentions-flextab/package-tap.i18n: package-tap.i18n should be loaded before languages files (*.i18n.json)
   /home/k0nsl/rc01/packages/rocketchat-message-star/package-tap.i18n: package-tap.i18n should be loaded before languages files (*.i18n.json)
   /home/k0nsl/rc01/packages/rocketchat-push-notifications/package-tap.i18n: package-tap.i18n should be loaded before languages files (*.i18n.json)
```

System details:
```
         _,met$$$$$gg.           root@server55
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 8.4 jessie
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 3.16.0-4-amd64
   ,$$P'              `$$$.      Uptime: 12d 19h 38m
  ',$$P       ,ggs.     `$$b:    Packages: 609
  `d$$'     ,$P"'   .    $$$     Shell: bash 4.3.30
   $$P      d$'     ,    $$P     CPU: Common KVM @ 2.493GHz
   $$:      $$.   -    ,d$$'     RAM: 546MB / 7908MB
   $$\;      Y$b._   _,d$P'
   Y$$.    `.`"Y$$$$P"'
   `$$b      "-.__
    `Y$$
     `Y$$.
       `$$b.
         `Y$$b.
            `"Y$b._
                `""""

```

Let me know if there is anything else I can submit so as to troubleshoot the issue. Incidentally I recall having a similar error message like this many months ago, but I forgot how we solved it.

Thanks in advance for any help in the matter.

**Comment by sampaiodiego** [comment]
did you upgrade meteor release? running `meteor update` inside rocket.chat folder.
what is the content of the file `.meteor/release`?

**Comment by k0nsl** [comment]
@sampaiodiego:

Yes I upgraded the meteor release and `.meteor/release` says `METEOR@1.2.1`.

Running `meteor update` results in the following:
```
root@server55:/home/k0nsl/rc01# meteor update
Update to release METEOR@1.3.2.4 is impossible:
While selecting package versions:
error: No version of autoupdate satisfies all constraints: @=1.2.4, @=1.2.9
Constraints on package "autoupdate":
* autoupdate@=1.2.4 <- top level
* autoupdate@=1.2.9 <- top level
* autoupdate@1.2.8 <- hot-code-push 1.0.4 <- meteor-base 1.0.4

This project is at the latest release which is compatible with your current package constraints.
```

**Comment by k0nsl** [comment]
The only issue right now (that I know of, anyway) is `Unexpected mongo exit code 14. Restarting.`

Unfortunately this exit code isn't very helpful:
>Returned by MongoDB applications which encounter an unrecoverable error, an uncaught exception or uncaught signal. The system exits without performing a clean shut down.
https://docs.mongodb.com/manual/reference/exit-codes/

**Comment by twhiting** [comment]
Worth noting that upgrading via docker didn't work either.  I checked the docker repo and it hasn't been pushed to 3.0 but I've always went and performed the upgrade when the Rocket.Chat version changed here in this repo.  Thoughts?

**Comment by k0nsl** [comment]
@twhiting: were you getting similar results as mine?

**Comment by k0nsl** [comment]
So far I have tried reverting back to `0.28.0` and `0.29.0` and copying my `.meteor` folder into either of those previous versions. Same issue: `Unexpected mongo exit code 14. Restarting.`

There was one message I hadn't seen before:
```
root@server55:/home/k0nsl/rc01/Rocket.Chat-0.28.0# meteor
[[[[[ /home/k0nsl/rc01/Rocket.Chat-0.28.0 ]]]]]

=> Started proxy.
=> Meteor 1.3.2.4 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Errors prevented startup:

   While selecting package versions:
   error: unknown package in top-level dependencies: rocketchat:slashcommands-me
   unknown package in top-level dependencies: rocketchat:slashcommands-shrug
   unknown package in top-level dependencies: rocketchat:slashcommands-topic

=> Your application has errors. Waiting for file change.
^C

**Comment by twhiting** [comment]
No I wasn't, w/ my docker containers I ran out of room to store images.  I just had to delete a couple of them and it worked fine for me after that.

**Comment by k0nsl** [comment]
Well, in the end I couldn't get my data restored and imported to my instance deployed via docker. At least something good came out from this; I now run it the "recommended way" 😏
