### ISSUE TITLE
rocketchat nodeJs deployment crashes every day at the very same time  

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#31955]
### Description:

Our rocketchat nodejs deployment restarts every day at the very same time without obvious reason. The deployment consists of four rocketchat nodejs pods. All four pods issue the same error message at the exactly same time:

```
[2024-03-11T07:03:08.551Z] INFO  7f23ec01-a533-4657-88c2-86392af149f5/REGISTRY: Node 'b49be883-7988-4d79-b0dc-f1ffd2dcd3cd' disconnected.
[2024-03-11T07:03:08.968Z] INFO  7f23ec01-a533-4657-88c2-86392af149f5/REGISTRY: Node '78dababf-6596-427f-a9d1-c526877f8609' disconnected.
[2024-03-11T07:03:09.343Z] INFO  7f23ec01-a533-4657-88c2-86392af149f5/REGISTRY: Node 'ed496e7d-bf43-4c94-afff-92a14f478fc7' disconnected.
=== UnHandledPromiseRejection ===
URIError: URI malformed
    at decodeURI (<anonymous>)
    at Router.match (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_restivus/node_modules/connect-route/lib/connect-route.js:61:12)
    at /app/bundle/programs/server/npm/node_modules/meteor/rocketchat_restivus/node_modules/connect-route/lib/connect-route.js:102:24
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
---------------------------------
Errors like this can cause oplog processing errors.
Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Future node.js versions will automatically exit the process
=================================
```

What is going on here? Someone has a hint?

### Steps to reproduce:

1. Deploy rocketchat with helm to kubernetes
2. Wait
3. Pods get restarted every day at the same time

### Expected behavior:

Continiousely running rocketchat cluster

### Actual behavior:

Pods crash every day at the same time.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.3
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: yes
- NodeJS Version: 14
- MongoDB Version: 5

cheers! t.

**Comment by himpierre** [comment]
Found the Nessus Scan query which crashes the pods reproducable. I'm hesitate to posting it here. :) Closing the ticket for now.
