### ISSUE TITLE
Failed to connect to Rocket.Chat Cloud

### ISSUE THREAD

**Issue by railsmechanic** [RocketChat/Rocket.Chat#32054]
### Description:

After updating to v6.5.4, the connection to the Rocket.Chat Cloud no longer works. As a result, it is no longer possible to send push notifications. The workspace is already registered, so no registration was needed. In v.6.4.8 everything still worked.

### Expected behavior:

Sending of Push-Nofications and Cloud Sync should work.

### Actual behavior:

Sending of Push-Nofications and Cloud Sync does not work.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.4
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog:  enabled
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: Desktop v3.9.14
- Operating System: MacOS

### Additional context

Done the update from v6.4.8 -> v6.5.4

### Relevant logs:

**Cloud connection failure:**

```json
{"level":50,"time":"2024-03-22T06:24:18.460Z","pid":1,"hostname":"rocketchat-6-0","name":"System","err":{"type":"CloudWorkspaceConnectionError","message":"Failed to connect to Rocket.Chat Cloud: undefined","stack":"CloudWorkspaceConnectionError: Failed to connect to Rocket.Chat Cloud: undefined\n    at server/modules/core-apps/cloudAnnouncements.module.ts:255:10\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/modules/core-apps/cloudAnnouncements.module.ts:86:27\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","name":"CloudWorkspaceConnectionError"},"msg":"Failed to connect to Rocket.Chat Cloud: undefined"}
```

**Cloud sync failure**

```json
{"level":50,"time":"2024-03-22T07:59:40.491Z","pid":1,"hostname":"rocketchat-6-0","name":"System","msg":"Failed to sync with Rocket.Chat Cloud","function":"syncCloudData","err":{"type":"AbortError","message":"The user aborted a request.","stack":"AbortError: The user aborted a request.\n    at abort (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1401:16)\n    at AbortSignal.abortAndFinalize (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1416:4)\n    at AbortSignal.dispatchEvent (/app/bundle/programs/server/npm/node_modules/event-target-shim/dist/event-target-shim.js:818:35)\n    at abortSignal (/app/bundle/programs/server/npm/node_modules/abort-controller/dist/abort-controller.js:52:12)\n    at AbortController.abort (/app/bundle/programs/server/npm/node_modules/abort-controller/dist/abort-controller.js:91:9)\n    at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/dist/index.js:37:51)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/cloud/server/functions/syncWorkspace/syncCloudData.ts:32:16\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/cloud/server/functions/syncWorkspace/syncCloudData.ts:70:43\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","name":"AbortError"}}
```
This error is displayed even though no user has aborted the process (as stated in the error message).

**Comment by inattendu** [comment]
same issue

**Comment by paulchen** [comment]
I don't know if it's related, but I found similar entries in the logs of my Rocket.Chat instance. However, push notifications work as expected.

During startup:

```
Mar 22 09:39:23 alpha rocketchat[1515697]: {"level":30,"time":"2024-03-22T08:39:23.647Z","pid":1,"hostname":"5da1500dd509","name":"License","msg":"New Enterprise License"}
Mar 22 09:39:23 alpha rocketchat[1515697]: {"level":30,"time":"2024-03-22T08:39:23.650Z","pid":1,"hostname":"5da1500dd509","name":"License","msg":"Limit validation failed","kind":"roomsPerGuest","limit":{"max":0,"behavior":"start_fair_policy"}}
Mar 22 09:39:23 alpha rocketchat[1515697]: {"level":30,"time":"2024-03-22T08:39:23.750Z","pid":1,"hostname":"5da1500dd509","name":"License","msg":"Limit validation failed","kind":"guestUsers","limit":{"max":0,"behavior":"start_fair_policy"}}
Mar 22 09:39:23 alpha rocketchat[1515697]: {"level":30,"time":"2024-03-22T08:39:23.794Z","pid":1,"hostname":"5da1500dd509","name":"License","msg":"License validated","modules":[{"module":"canned-responses"},{"module":"ldap-enterprise"},{"module":"livechat-enterprise"},{"module":"voip-enterprise"},{"module":"omnichannel-mobile-enterprise"},{"module":"engagement-dashboard"},{"module":"push-privacy"},{"module":"teams-mention"},{"module":"saml-enterprise"},{"module":"oauth-enterprise"},{"module":"federation"},{"module":"videoconference-enterprise"},{"module":"message-read-receipt"},{"module":"outlook-calendar"}]}
Mar 22 09:39:23 alpha rocketchat[1515697]: {"level":51,"time":"2024-03-22T08:39:23.795Z","pid":1,"hostname":"5da1500dd509","name":"License","msg":"License installed","version":"3.0","hash":"wAX_82vY"}
Mar 22 09:40:06 alpha rocketchat[1515697]: {"level":50,"time":"2024-03-22T08:40:06.038Z","pid":1,"hostname":"5da1500dd509","name":"System","msg":"Failed to update license from Rocket.Chat Cloud","url":"/license","err":{"type":"AbortError","message":"The user aborted a request.","stack":"AbortError: The user aborted a request.\n    at abort (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1401:16)\n    at AbortSignal.abortAndFinalize (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1416:4)\n    at AbortSignal.dispatchEvent (/app/bundle/programs/server/npm/node_modules/event-target-shim/dist/event-target-shim.js:818:35)\n    at abortSignal (/app/bundle/programs/server/npm/node_modules/abort-controller/dist/abort-controller.js:52:12)\n    at AbortController.abort (/app/bundle/programs/server/npm/node_modules/abort-controller/dist/abort-controller.js:91:9)\n    at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/dist/index.js:37:51)\n    at listOnTimeout (inte
rnal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/cloud/server/functions/getWorkspaceLicense.ts:27:16\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/cloud/server/functions/getWorkspaceLicense.ts:65:16\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","name":"AbortError"}}
Mar 22 09:44:48 alpha rocketchat[1515697]: {"level":30,"time":"2024-03-22T08:44:48.628Z","pid":1,"hostname":"5da1500dd509","name":"License","msg":"Limit validation failed","kind":"roomsPerGuest","limit":{"max":0,"behavior":"prevent_action"}}
Mar 22 09:44:48 alpha rocketchat[1515697]: {"level":30,"time":"2024-03-22T08:44:48.632Z","pid":1,"hostname":"5da1500dd509","name":"License","msg":"Limit validation failed","kind":"guestUsers","limit":{"max":0,"behavior":"prevent_action"}}
```

Twice a day (at 12am and 12pm UTC) the error "Failed to sync with Rocket.Chat cloud" is logged:

```
Mar 20 01:00:03 alpha rocketchat[3778830]: {"level":30,"time":"2024-03-20T00:00:03.257Z","pid":1,"hostname":"0a30f2bdeb42","name":"System","msg":"Failed to sync with Rocket.Chat Cloud","function":"announcementSync","err":{"type":"CloudWorkspaceAccessTokenEmptyError","message":"Workspace access token is empty","stack":"Error: Workspace access token is empty\n    at app/cloud/server/functions/syncWorkspace/announcementSync.ts:86:10\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"}}
Mar 20 13:00:03 alpha rocketchat[3778830]: {"level":30,"time":"2024-03-20T12:00:03.228Z","pid":1,"hostname":"0a30f2bdeb42","name":"System","msg":"Failed to sync with Rocket.Chat Cloud","function":"announcementSync","err":{"type":"CloudWorkspaceAccessTokenEmptyError","message":"Workspace access token is empty","stack":"Error: Workspace access token is empty\n    at app/cloud/server/functions/syncWorkspace/announcementSync.ts:86:10\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"}}
```

I'm currently running Rocket.Chat 6.6.5 on the Starter plan.

The error message "Failed to update license from Rocket.Chat Cloud" was only logged once today during startup when upgrading from 6.6.4 to 6.6.5.

The error message "Failed to sync with Rocket.Chat cloud" can be found in the logs from 2024-02-11 when I had 6.6.0 installed. I do not have older logs available.

**Comment by railsmechanic** [comment]
Seems to be working again. 🤷‍♂️

**Comment by reetp** [comment]
> Seems to be working again. 🤷‍♂️

Cling. Please open a new issue if it re-occurs.
