### ISSUE TITLE
New user can't input E2E password

### ISSUE THREAD

**Issue by sunstrider12** [RocketChat/Rocket.Chat#32070]
Description:
After the upgrade, new users cannot enter the E2E password. When they open the input box, they will get stuck regardless of whether they click OK or Cancel. Already downgraded to 6.6.0, still not working

Expected behavior:
new users cann't input E2E password.

Actual behavior:
new users can input E2E password

Server Setup Information:
Version of Rocket.Chat Server: 6.6.0
Operating System: Linux
Deployment Method: docker
Number of Running Instances: 1
DB Replicaset Oplog: enabled
NodeJS Version: v14.21.3
MongoDB Version: 5.0.23
Client Setup Information
Desktop App or Browser Version: Desktop v3.9.11
Operating System: MacOS
Additional context
Done the update from v6.6.2-> v6.6.6

**Comment by sunstrider12** [comment]
when new user login, i get some error

        {"level":50,"time":"2024-03-26T05:52:36.855Z","pid":1,"hostname":"91cca3248cbe","name":"System","msg":"Exception while invoking method loadLocale","err":{"type":"Error","message":"Unknown asset: moment-locales/zh.js","stack":"Error: Unknown asset: moment-locales/zh.js\n    at getAsset (/app/bundle/programs/server/boot.js:303:21)\n    at Object.getTextAsync (/app/bundle/programs/server/boot.js:318:18)\n    at server/lib/getMomentLocale.ts:7:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at packages/meteor.js:367:22\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)\n    at packages/ddp-server/livedata_server.js:1854:36\n    at new Promise (<anonymous>)\n    at Server.applyAsync (packages/ddp-server/livedata_server.js:1853:12)\n    at Server.callAsync (packages/ddp-server/livedata_server.js:1779:17)\n    at app/api/server/v1/misc.ts:617:33\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/v1/misc.ts:617:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"}}

**Comment by sunstrider12** [comment]
ok. fix it.
change the language to english.
