### ISSUE TITLE
Server down after I click "SEND A TEST PUSH TO MY USER". 

### ISSUE THREAD

**Issue by jjzhangg** [RocketChat/Rocket.Chat#3212]
Your Rocket.Chat version: 0.30.0
Server down after I click "SEND A TEST PUSH TO MY USER". 
Related logs can be found below: 

```
/app/bundle/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:155
                throw e;
                      ^
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.exports.createCredentials (crypto.js:126:17)
    at Object.exports.connect (tls.js:1345:27)
    at apnSocketLegacy (/app/bundle/programs/server/npm/raix_push/node_modules/apn/lib/socket.js:40:19)
    at Connection.initialize.spread.fail.terminated (/app/bundle/programs/server/npm/raix_push/node_modules/apn/lib/connection.js:175:17)
    at /app/bundle/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:1229:26
    at _fulfilled (/app/bundle/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/app/bundle/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/app/bundle/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:796:13)
    at /app/bundle/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:556:49
    at runSingle (/app/bundle/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:137:13)
Updating process.env.MAIL_URL
```

**Comment by jjzhangg** [comment]
I set the push notification certificates and keys following https://rocket.chat/docs/administrator-guides/push-notifications/. 

The same configuration worked in 0.26.0, and now broken after I upgrade to 0.30.0

**Comment by MartinSchoeler** [comment]
Hey @jjzhangg , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
