### ISSUE TITLE
[Bug] App crashing

### ISSUE THREAD

**Issue by iAbdulaziz93** [RocketChat/Rocket.Chat#32737]
### Description:

Hi, when I try to run the app locally using `yarn dsv` as [described here](https://github.com/RocketChat/Rocket.Chat?tab=readme-ov-file#%EF%B8%8F-local-development), the app is crashing and showing the attached error message/screenshot.

### Steps to reproduce:

Follow the installation instructions in the above link and try to run the app locally.

### Expected behavior:

The app runs locally without issues.

### Actual behavior:

The app crashes and shows an error message.

### Client Setup Information

- Operating System: macOS Sonoma v14.5

### Relevant logs:

Started MongoDB.
Linted your app. No linting errors.
/Users/abdulaziz/.meteor/packages/promise/.0.12.2.17qn87e.lqqg++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-darwin-arm64v8.node'
Require stack:
- /Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/sharp.js
- /Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/constructor.js
- /Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/index.js
- /Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/npm-require.js
- /Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/boot.js
- /Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/.meteor/local/build/main.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (internal/modules/cjs/loader.js:1116:14)
    at Module.Mp._compile (/Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (/Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:105:23)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module.Mp.load (/Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:821:12)
    at Module.require (internal/modules/cjs/loader.js:1005:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1116:14)
    at Module.Mp._compile (/Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (/Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:105:23)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module.Mp.load (/Users/abdulaziz/Dev/VSCodeProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:821:12)
Exited with code: 1
Your application is crashing. Waiting for file change.

![image](https://github.com/RocketChat/Rocket.Chat/assets/61385777/bade3cae-efa5-48a5-bbfa-73840ea23b0b)

![image](https://github.com/RocketChat/Rocket.Chat/assets/61385777/f939fc91-b4dc-4f02-a291-0de3e4c5cf09)

**Comment by reetp** [comment]
Github is for bugs in Rocket.Chat not general support.

This looks like a setup problem.

Please check your setup via this:

https://developer.rocket.chat/v1/docs/mac-osx

Please ask for help in:

https://open.rocket.chat #support

If there is actually a bug in Rocket we can re-open.
