### ISSUE TITLE
Rocket Chat is crashing periodically

### ISSUE THREAD

**Issue by eXtrem0us** [RocketChat/Rocket.Chat#32785]
### Description:

Rocket Chat crashes and gets to an nonfunctional state every few minutes and restores functioning after a delay of one minute.

### Steps to reproduce:

We're using Rocket Chat for our organization. It sometimes shows unexpected behaviors.

### Expected behavior:

Steady functioning. 

### Actual behavior:

This is the error log (output of `journalctl`) on the times it gets nonfunctional.
```
Jul 14 14:55:17 chat rocketchat[35961]: [4.8K blob data]
Jul 14 14:55:17 chat rocketchat[35961]:     at new L (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/message-parser/dist/messageParser.production.js:1:1192)
Jul 14 14:55:17 chat rocketchat[35961]:     at Object.parse (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/message-parser/dist/messageParser.production.js:1:76977)
Jul 14 14:55:17 chat rocketchat[35961]:     at s (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/message-parser/dist/messageParser.production.js:1:186564)
Jul 14 14:55:17 chat rocketchat[35961]:     at server/services/messages/hooks/BeforeSaveMarkdownParser.ts:35:44
Jul 14 14:55:17 chat rocketchat[35961]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
Jul 14 14:55:17 chat rocketchat[35961]:   expected: [
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '\r\n', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '\n', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '\r', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ' ', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '\t', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     {
Jul 14 14:55:17 chat rocketchat[35961]:       type: 'class',
Jul 14 14:55:17 chat rocketchat[35961]:       parts: [Array],
Jul 14 14:55:17 chat rocketchat[35961]:       inverted: false,
Jul 14 14:55:17 chat rocketchat[35961]:       ignoreCase: false
Jul 14 14:55:17 chat rocketchat[35961]:     },
Jul 14 14:55:17 chat rocketchat[35961]:     {
Jul 14 14:55:17 chat rocketchat[35961]:       type: 'class',
Jul 14 14:55:17 chat rocketchat[35961]:       parts: [Array],
Jul 14 14:55:17 chat rocketchat[35961]:       inverted: false,
Jul 14 14:55:17 chat rocketchat[35961]:       ignoreCase: false
Jul 14 14:55:17 chat rocketchat[35961]:     },
Jul 14 14:55:17 chat rocketchat[35961]:     {
Jul 14 14:55:17 chat rocketchat[35961]:       type: 'class',
Jul 14 14:55:17 chat rocketchat[35961]:       parts: [Array],
Jul 14 14:55:17 chat rocketchat[35961]:       inverted: false,
Jul 14 14:55:17 chat rocketchat[35961]:       ignoreCase: false
Jul 14 14:55:17 chat rocketchat[35961]:     },
Jul 14 14:55:17 chat rocketchat[35961]:     {
Jul 14 14:55:17 chat rocketchat[35961]:       type: 'class',
Jul 14 14:55:17 chat rocketchat[35961]:       parts: [Array],
Jul 14 14:55:17 chat rocketchat[35961]:       inverted: false,
Jul 14 14:55:17 chat rocketchat[35961]:       ignoreCase: false
Jul 14 14:55:17 chat rocketchat[35961]:     },
Jul 14 14:55:17 chat rocketchat[35961]:     {
Jul 14 14:55:17 chat rocketchat[35961]:       type: 'class',
Jul 14 14:55:17 chat rocketchat[35961]:       parts: [Array],
Jul 14 14:55:17 chat rocketchat[35961]:       inverted: false,
Jul 14 14:55:17 chat rocketchat[35961]:       ignoreCase: false
Jul 14 14:55:17 chat rocketchat[35961]:     },
Jul 14 14:55:17 chat rocketchat[35961]:     {
Jul 14 14:55:17 chat rocketchat[35961]:       type: 'class',
Jul 14 14:55:17 chat rocketchat[35961]:       parts: [Array],
Jul 14 14:55:17 chat rocketchat[35961]:       inverted: false,
Jul 14 14:55:17 chat rocketchat[35961]:       ignoreCase: false
Jul 14 14:55:17 chat rocketchat[35961]:     },
Jul 14 14:55:17 chat rocketchat[35961]:     {
Jul 14 14:55:17 chat rocketchat[35961]:       type: 'class',
Jul 14 14:55:17 chat rocketchat[35961]:       parts: [Array],
Jul 14 14:55:17 chat rocketchat[35961]:       inverted: false,
Jul 14 14:55:17 chat rocketchat[35961]:       ignoreCase: false
Jul 14 14:55:17 chat rocketchat[35961]:     },
Jul 14 14:55:17 chat rocketchat[35961]:     {
Jul 14 14:55:17 chat rocketchat[35961]:       type: 'class',
Jul 14 14:55:17 chat rocketchat[35961]:       parts: [Array],
Jul 14 14:55:17 chat rocketchat[35961]:       inverted: false,
Jul 14 14:55:17 chat rocketchat[35961]:       ignoreCase: false
Jul 14 14:55:17 chat rocketchat[35961]:     },
Jul 14 14:55:17 chat rocketchat[35961]:     {
Jul 14 14:55:17 chat rocketchat[35961]:       type: 'class',
Jul 14 14:55:17 chat rocketchat[35961]:       parts: [Array],
Jul 14 14:55:17 chat rocketchat[35961]:       inverted: false,
Jul 14 14:55:17 chat rocketchat[35961]:       ignoreCase: false
Jul 14 14:55:17 chat rocketchat[35961]:     },
Jul 14 14:55:17 chat rocketchat[35961]:     {
Jul 14 14:55:17 chat rocketchat[35961]:       type: 'class',
Jul 14 14:55:17 chat rocketchat[35961]:       parts: [Array],
Jul 14 14:55:17 chat rocketchat[35961]:       inverted: false,
Jul 14 14:55:17 chat rocketchat[35961]:       ignoreCase: false
Jul 14 14:55:17 chat rocketchat[35961]:     },
Jul 14 14:55:17 chat rocketchat[35961]:     {
Jul 14 14:55:17 chat rocketchat[35961]:       type: 'class',
Jul 14 14:55:17 chat rocketchat[35961]:       parts: [Array],
Jul 14 14:55:17 chat rocketchat[35961]:       inverted: false,
Jul 14 14:55:17 chat rocketchat[35961]:       ignoreCase: false
Jul 14 14:55:17 chat rocketchat[35961]:     },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '<3', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '</3', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':D', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':-D', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '=D', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '>:)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '>;)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '>:-)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '>=)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: "':)", ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: "':-)", ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: "'=)", ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: "':D", ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: "':-D", ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: "'=D", ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ":')", ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ":'-)", ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: 'O:-)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '0:-3', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '0:3', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '0:-)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '0:)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '0;^)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: 'O:)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: 'O;-)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: 'O=)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '0;-)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: 'O:-3', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: 'O:3', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':-)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '=]', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '=)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':]', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ';)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ';-)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '*-)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '*)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ';-]', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ';]', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ';D', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ';^)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':*', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':-*', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '=*', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':^*', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':P', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':-P', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '=P', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':-Þ', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':Þ', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':-b', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':b', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '>:P', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: 'X-P', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: 'B-)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: 'B)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '8)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '8-)', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: 'B-D', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '8-D', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '>:[', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':-(', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':(', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':-[', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':[', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '=(', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '>:\\', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '>:/', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':-/', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':-.', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':/', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':\\', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '=/', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '=\\', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ':L', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '=L', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '>.<', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ":'(", ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ":'-(", ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ';(', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: ';-(', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     { type: 'literal', text: '>:(', ignoreCase: false },
Jul 14 14:55:17 chat rocketchat[35961]:     ... 216 more items
Jul 14 14:55:17 chat rocketchat[35961]:   ],
Jul 14 14:55:17 chat rocketchat[35961]:   found: null,
Jul 14 14:55:17 chat rocketchat[35961]:   location: {
Jul 14 14:55:17 chat rocketchat[35961]:     source: undefined,
Jul 14 14:55:17 chat rocketchat[35961]:     start: { offset: 0, line: 1, column: 1 },
Jul 14 14:55:17 chat rocketchat[35961]:     end: { offset: 0, line: 1, column: 1 }
Jul 14 14:55:17 chat rocketchat[35961]:   }
Jul 14 14:55:17 chat rocketchat[35961]: }
```

### Server Setup Information:

- Version of Rocket.Chat Server: 6.10.0
- License Type: Community
- Number of Users: 102 (24 online, 30 connected)
- Operating System: Debian 11
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
```
[
  {
    op: 'u',
    ns: 'rocketchat.instances',
    ui: UUID('4c0bd7cf-560a-4a82-a1ab-108fa48b4d38'),
    o: {
      '$v': 2,
      diff: { u: { _updatedAt: ISODate('2024-02-21T21:31:12.018Z') } }
    },
    o2: { _id: 'e564fa11-ab03-498f-a0f4-3b2d034c1e83' },
    ts: Timestamp({ t: 1708551072, i: 1 }),
    t: Long('24'),
    v: Long('2'),
    wall: ISODate('2024-02-21T21:31:12.018Z')
  },
  {
    op: 'u',
    ns: 'rocketchat.instances',
    ui: UUID('4c0bd7cf-560a-4a82-a1ab-108fa48b4d38'),
    o: {
      '$v': 2,
      diff: { u: { _updatedAt: ISODate('2024-02-21T21:31:22.019Z') } }
    },
    o2: { _id: 'e564fa11-ab03-498f-a0f4-3b2d034c1e83' },
    ts: Timestamp({ t: 1708551082, i: 1 }),
    t: Long('24'),
    v: Long('2'),
    wall: ISODate('2024-02-21T21:31:22.019Z')
  },
  {
    op: 'u',
    ns: 'rocketchat.instances',
    ui: UUID('4c0bd7cf-560a-4a82-a1ab-108fa48b4d38'),
    o: {
      '$v': 2,
      diff: { u: { _updatedAt: ISODate('2024-02-21T21:31:32.019Z') } }
    },
    o2: { _id: 'e564fa11-ab03-498f-a0f4-3b2d034c1e83' },
    ts: Timestamp({ t: 1708551092, i: 1 }),
    t: Long('24'),
    v: Long('2'),
    wall: ISODate('2024-02-21T21:31:32.019Z')
  },
  {
    op: 'u',
    ns: 'rocketchat.instances',
    ui: UUID('4c0bd7cf-560a-4a82-a1ab-108fa48b4d38'),
    o: {
      '$v': 2,
      diff: { u: { _updatedAt: ISODate('2024-02-21T21:31:42.021Z') } }
    },
    o2: { _id: 'e564fa11-ab03-498f-a0f4-3b2d034c1e83' },
    ts: Timestamp({ t: 1708551102, i: 1 }),
    t: Long('24'),
    v: Long('2'),
    wall: ISODate('2024-02-21T21:31:42.021Z')
  },
  {
    op: 'u',
    ns: 'rocketchat.instances',
    ui: UUID('4c0bd7cf-560a-4a82-a1ab-108fa48b4d38'),
    o: {
      '$v': 2,
      diff: { sextraInformation: { u: { conns: 12 } } }
    },
    o2: { _id: 'e564fa11-ab03-498f-a0f4-3b2d034c1e83' },
    ts: Timestamp({ t: 1708551106, i: 1 }),
    t: Long('24'),
    v: Long('2'),
    wall: ISODate('2024-02-21T21:31:46.388Z')
  },
  {
    op: 'u',
    ns: 'rocketchat.instances',
    ui: UUID('4c0bd7cf-560a-4a82-a1ab-108fa48b4d38'),
    o: {
      '$v': 2,
      diff: { u: { _updatedAt: ISODate('2024-02-21T21:31:52.021Z') } }
    },
    o2: { _id: 'e564fa11-ab03-498f-a0f4-3b2d034c1e83' },
    ts: Timestamp({ t: 1708551112, i: 1 }),
    t: Long('24'),
    v: Long('2'),
    wall: ISODate('2024-02-21T21:31:52.021Z')
  },
  {
    op: 'u',
    ns: 'rocketchat.rocketchat_cron',
    ui: UUID('30846afb-fa4a-4c1e-87dc-88e234417c58'),
    o: {
      '$v': 2,
      diff: {
        u: {
          lastRunAt: ISODate('2024-02-21T21:32:00.001Z'),
          nextRunAt: ISODate('2024-02-21T21:34:00.000Z')
        }
      }
    },
    o2: { _id: ObjectId('64d21a3c47158d99da48086d') },
    ts: Timestamp({ t: 1708551120, i: 1 }),
    t: Long('24'),
    v: Long('2'),
    wall: ISODate('2024-02-21T21:32:00.005Z')
  },
  {
    op: 'i',
    ns: 'rocketchat.rocketchat_cron_history',
    ui: UUID('6b9d3323-c055-4e3c-abcd-2c76e6a08947'),
    o: {
      _id: 'kGCEntMq6Em7PTgYT',
      intendedAt: ISODate('2024-02-21T21:32:00.009Z'),
      name: 'UserDataDownload',
      startedAt: ISODate('2024-02-21T21:32:00.009Z'),
      _updatedAt: ISODate('2024-02-21T21:32:00.009Z')
    },
    o2: { _id: 'kGCEntMq6Em7PTgYT' },
    ts: Timestamp({ t: 1708551120, i: 2 }),
    t: Long('24'),
    v: Long('2'),
    wall: ISODate('2024-02-21T21:32:00.010Z')
  },
  {
    op: 'u',
    ns: 'rocketchat.rocketchat_cron_history',
    ui: UUID('6b9d3323-c055-4e3c-abcd-2c76e6a08947'),
    o: {
      '$v': 2,
      diff: {
        u: { _updatedAt: ISODate('2024-02-21T21:32:00.013Z') },
        i: { finishedAt: ISODate('2024-02-21T21:32:00.013Z') }
      }
    },
    o2: { _id: 'kGCEntMq6Em7PTgYT' },
    ts: Timestamp({ t: 1708551120, i: 3 }),
    t: Long('24'),
    v: Long('2'),
    wall: ISODate('2024-02-21T21:32:00.014Z')
  },
  {
    op: 'u',
    ns: 'rocketchat.rocketchat_cron',
    ui: UUID('30846afb-fa4a-4c1e-87dc-88e234417c58'),
    o: {
      '$v': 2,
      diff: {
        u: {
          lastFinishedAt: ISODate('2024-02-21T21:32:00.016Z'),
          lockedAt: null
        }
      }
    },
    o2: { _id: ObjectId('64d21a3c47158d99da48086d') },
    ts: Timestamp({ t: 1708551120, i: 4 }),
    t: Long('24'),
    v: Long('2'),
    wall: ISODate('2024-02-21T21:32:00.017Z')
  }
]
```
- NodeJS Version: v14.21.3
- MongoDB Version: 6.0.15

### Client Setup Information

- Desktop App or Browser Version: It happens on any browser of app
- Operating System: It happens on any client OS

### Additional context

Nothing

### Relevant logs:

The logs are noted.

**Comment by reetp** [comment]
Thanks for reporting.

For ref what hardware have you got? CPU + RAM?

What storage type?

Latter part of the logs look like it is a user data download executed via cron?

> name: 'UserDataDownload

I've seen a previous bug where it loops with a part wedged download - probably trying to download some huge attachments, or some that were a failed upload.

I'd search back through bugs - it was a few months back. 

Worth trying to clear that out and seeing if it reoccurs.

**Comment by reetp** [comment]
See this

https://github.com/RocketChat/Rocket.Chat/issues/32307

**Comment by eXtrem0us** [comment]
Dear @reetp 
I realized that the issue was about our infrastructure, (packet congestion on the load balancer network interface, which was not correctly configured), and not Rocket Chat.
Thanks for your kind response anyway.

**Comment by reetp** [comment]
(No need to @ as I read everything!)

Glad you got it sorted and thanks for letting us know!
