### ISSUE TITLE
6.12.0-rc.1 can't upload e2ee files

### ISSUE THREAD

**Issue by lovekyleman** [RocketChat/Rocket.Chat#33171]
Can't upload e2ee files of photos videos and voice messages on rocketchat IOS APP

"Accepted Media Types" in the admin panel is empty. 
It should work any types of media.

Logs:
/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","isClientSafe":true,"error":"ufs: cannot upload file","reason":{"type":"Error","message":"Input file contains unsupported image format","stack":"Error: Input file contains unsupported image format\n => awaited here:\n    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/file-upload/server/lib/FileUpload.ts:359:17\n

**Comment by lovekyleman** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/33169
Just find out this 
Can't wait for the next release
