### ISSUE TITLE
DLP Bug 

### ISSUE THREAD

**Issue by RichPex** [RocketChat/Rocket.Chat#33180]
### Description:

DLP appears to not be retruning the expected messaging when content is blocked

### Steps to reproduce:

1. Enable DLP 
2. Share a form of blocked content, default settings are fine e.g. Credit Card 0000000000000000
3. Content is blocked with error message from Rocket Cat "Invalid custom fields"

### Expected behavior:

Error message should details the block and the reason for it as per previous standard UI

### Actual behavior:

![Screenshot 2024-08-28 at 15 04 53](https://github.com/user-attachments/assets/57bde377-3249-429b-942f-38206a0f1e82)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.11.0 observed also in 6.11.1
- License Type: Enterprise trial
- Number of Users: 66 / 500
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.24

### Client Setup Information

- Desktop App - Mac OS v 4.0.2
- Operating System: Sonoma 14.6.1

**Comment by reetp** [comment]
No idea why you opened a new bug. Should have just added your info to the first one.

I will close https://github.com/RocketChat/Rocket.Chat/issues/33176 in favour of this.

**Comment by reetp** [comment]
First, do you have any custom fields set at all?

Set your logs to Debug - what do they tell you?

**Comment by RichPex** [comment]
Hi John

we have enabled logging extract below which is what we are seeing when the DLP was returning the strange response. Im not overly technical so have included my colleagues for support as needed.

To provide a further update this morning on looking to test again we find the DLP app has now disabled itself ? on re-enabling the same error occurs

We will update to 6.11.1 by end of play today but I don’t believe any issues are addressed in this dot release

{"level":50,"time":"2024-08-29T15:13:21.402Z","pid":1,"hostname":"e65ec9dcc648","name":"System","msg":"Error sending message:","err":{"type":"Error","message":"Custom fields not enabled","stack":"Error: Custom fields not enabled<br> at validateCustomMessageFields (app/lib/server/lib/validateCustomMessageFields.ts:37:9)<br> at app/lib/server/functions/sendMessage.ts:178:3<br> at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br> at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br> at app/lib/server/functions/sendMessage.ts:254:4<br> at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br> at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br> at app/lib/server/methods/sendMessage.ts:96:3<br> at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"}}

Best

Richard Hearn
Tel: +44 (0) 7471227099<tel:+447471227099>


From: John Crisp ***@***.***>
Date: Thursday, 29 August 2024 at 15:59
To: RocketChat/Rocket.Chat ***@***.***>
Cc: Richard Hearn ***@***.***>, Author ***@***.***>
Subject: Re: [RocketChat/Rocket.Chat] DLP Bug (Issue #33180)

First, do you have any custom fields set at all?

Set your logs to Debug - what do they tell you?

**Comment by reetp** [comment]
> First, do you have any custom fields set at all?

^^^^^^^^^^^^^^

Need to see if the log is correct or not because this:

> message:","err":{"type":"Error","message":"Custom fields not enabled",

**Comment by RichPex** [comment]
Do you mean custom fields in “account” in workspace settings which is blank/default or do you mean the below section which again is default I believe

The only customisation for DLP is an additional regex added to detect a particular text string

Does that help
***@***.***
Best

Richard Hearn
Tel: +44 (0) 7471227099<tel:+447471227099>


From: John Crisp ***@***.***>
Date: Monday, 2 September 2024 at 09:25
To: RocketChat/Rocket.Chat ***@***.***>
Cc: Richard Hearn ***@***.***>, Author ***@***.***>
Subject: Re: [RocketChat/Rocket.Chat] DLP Bug (Issue #33180)

First, do you have any custom fields set at all?

^^^^^^^^^^^^^^

Need to see if the log is correct or not because this:

message:","err":{"type":"Error","message":"Custom fields not enabled",

**Comment by RichPex** [comment]
When I do enable the custom field flag the message changed from the DLP to “Invalid Custom Field” seems an interplay between DLP and this setting ?

Best

Richard Hearn
Tel: +44 (0) 7471227099<tel:+447471227099>


From: Richard Hearn ***@***.***>
Date: Monday, 2 September 2024 at 09:48
To: RocketChat/Rocket.Chat ***@***.***>, RocketChat/Rocket.Chat ***@***.***>
Cc: Author ***@***.***>, Stuart Geoghegan ***@***.***>
Subject: Re: [RocketChat/Rocket.Chat] DLP Bug (Issue #33180)
Do you mean custom fields in “account” in workspace settings which is blank/default or do you mean the below section which again is default I believe

The only customisation for DLP is an additional regex added to detect a particular text string

Does that help
***@***.***
Best

Richard Hearn
Tel: +44 (0) 7471227099<tel:+447471227099>


From: John Crisp ***@***.***>
Date: Monday, 2 September 2024 at 09:25
To: RocketChat/Rocket.Chat ***@***.***>
Cc: Richard Hearn ***@***.***>, Author ***@***.***>
Subject: Re: [RocketChat/Rocket.Chat] DLP Bug (Issue #33180)

First, do you have any custom fields set at all?

^^^^^^^^^^^^^^

Need to see if the log is correct or not because this:

message:","err":{"type":"Error","message":"Custom fields not enabled",

**Comment by reetp** [comment]
N. B. It would help if you used github via a web page and not email.

Apart from plastering your details everywhere with your footer it makes it hard to read especially when you also add your previous messages too. If nothing else edit the mails and drop all the dross and repeated stuff. Thanks.

Have a look at your last post with a browser...

---------------------------

I'd start by removing *all* custom fields you can find to start with - document them all - and then add back one at a time and test to see what is affecting it.

Try to eliminate things logically.

**Comment by RichPex** [comment]
I have removed the default setting from custom fields in "Message" settings and and also disabled tested and then re-enabled the custom field setting, the errors shown for any of the regex under DLP are the same either "custom fields not enabled" or "invalid custom fields" or "Unexpected end of JSON" and no alert is triggered in the DLP channel for the moderator
