### ISSUE TITLE
Failed to communicate with Rocket.Chat Cloud

### ISSUE THREAD

**Issue by thokich** [RocketChat/Rocket.Chat#33290]
Hey,
 
new Version, new Message in Docker Log.

I get this message at longer intervals. I can't reproduce it at the moment.

2024-09-16T00:00:20.160Z 50 pid=1 hostname=123456789 name=System msg=Failed to communicate with Rocket.Chat Cloud url=https://releases.rocket.chat/v2/server/supportedVersions err={"type":"AbortError","message":"The user aborted a request.","stack":"AbortError: The user aborted a request.\n    at abort (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/node_modules/node-fetch/lib/index.js:1401:16)\n    at AbortSignal.abortAndFinalize (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/node_modules/node-fetch/lib/index.js:1416:4)\n    at AbortSignal.dispatchEvent (/app/bundle/programs/server/npm/node_modules/event-target-shim/dist/event-target-shim.js:818:35)\n    at abortSignal (/app/bundle/programs/server/npm/node_modules/abort-controller/dist/abort-controller.js:52:12)\n    at AbortController.abort (/app/bundle/programs/server/npm/node_modules/abort-controller/dist/abort-controller.js:91:9)\n    at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/dist/index.js:37:51)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts:46:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","name":"AbortError"}

Rocket.Chat in Docker 
+---------------------------------------------------------+
|                      SERVER RUNNING                     |
+---------------------------------------------------------+
|                                                         |
|  Rocket.Chat Version: 6.12.1                            |
|       NodeJS Version: 14.21.3 - x64                     |
|      MongoDB Version: 7.0.7                             |
|       MongoDB Engine: wiredTiger                        |
|             Platform: linux                             |
|         Process Port: 3000                              |
|             Site URL: https://rocketchat.deutschland.de  |
|     ReplicaSet OpLog: Enabled                           |
|          Commit Hash: 123456                        |
|        Commit Branch: HEAD                              |
|                                                         |
+---------------------------------------------------------+

**Comment by reetp** [comment]
First, please always ask in open.rocket.chat or the forums before opening an issue. Most issues are actually support issues, not bugs, and they are better places to ask first.

Next.

Fill in the bug template. Always, with as much info as possible.

It helps people understand your setup.

Read this to guide you, especially here:

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#still-stuck

> | SERVER RUNNING |

Your server is up then

>  MongoDB Version: 7.0.7

https://github.com/RocketChat/Rocket.Chat/releases

> MongoDB: 4.4, 5.0, 6.0

Note in the releases yours is not actually a supported version, though I doubt it is your issue.

> I can't reproduce it at the moment.

If you can't then it is not something that can be debugged easily....

I'll leave this open for now.

If you see further errors please post more info and more comprehensive logs (use a gist - don't paste huge amounts here as it makes the issue hard to read and more likely to be ignored..... )

Thanks.

**Comment by thokich** [comment]
Thanks and Bye, bye

**Comment by reetp** [comment]
> Thanks and Bye, bye

I presume you sorted this.

If not you might want to check why this occurs:

> Failed to communicate with Rocket.Chat Cloud
