### ISSUE TITLE
`yarn.lock` is out of date, causing "CI" builds to fail.

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat#33367]
### Description:

When pulling RC for the last 3 tagged releases (`6.10.6`, `6.11.3`, `6.12.1`) and then running `yarn --immutable`, `yarn.lock` is being updated because multiple packages are newer in the `package.json` files vs the `yarn.lock` file.

This leads to an install failure, because `yarn` can't install the wanted packages, since the lock file versions don't match those in `package.json`.

![image](https://github.com/user-attachments/assets/0b555594-2a5c-4b9c-be06-840a4a01bae9)

Furthermore, removing the `--immutable` flag will install the updated versions, which then break the Docker image due to an upgraded GLIBC requirement

```
/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /app/bundle/programs/server/npm/node_modules/isolated-vm/out/isolated_vm.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1173:18)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/app/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/app/bundle/programs/server/npm/node_modules/isolated-vm/isolated-vm.js:1:-44)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module.Mp._compile (/app/bundle/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/app/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at npmRequire (/app/bundle/programs/server/npm-require.js:111:12)
    at Module.useNode (packages/modules-runtime.js:751:18)
    at module (/app/bundle/programs/server/packages/modules.js:216576:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (app/integrations/server/lib/isolated-vm/isolated-vm.ts:2:43)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (app/integrations/server/lib/triggerHandler.js:1:1311)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at server/services/meteor/service.ts:1:72
    at module (server/services/meteor/service.ts:286:2)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22) {
  code: 'ERR_DLOPEN_FAILED'
}
```

Note that `6.9.2` and `6.9.7` also exhibit the `package.json` / `yarn.lock` inequality, but the resulting Docker images start correctly and do not have the GLIBC issue.

### Steps to reproduce:

1. Pull one of the tags specified.
2. Try to build with `yarn --immutable` -- build fails.
3. Try to build with `yarn` -- build succeeds.
4. Build/run the Docker image and note that RC fails to start with a GLIBC error.

### Expected behavior:

The `yarn.lock` should never contain older versions than the `package.json` files.

### Actual behavior:

The `yarn.lock` contains older versions than the `package.json` files.

### Server Setup Information:

- Version of Rocket.Chat Server: `6.10.6`, `6.11.3`, `6.12.1`
- License Type: N/A
- Number of Users:  N/A
- Operating System:  N/A
- Deployment Method:  N/A
- Number of Running Instances:  N/A
- DB Replicaset Oplog:  N/A
- NodeJS Version:  N/A
- MongoDB Version: N/A

### Client Setup Information

- Desktop App or Browser Version: N/A
- Operating System: N/A

**Comment by reetp** [comment]
Can I ask where you pulled the images from?

**Comment by JoshMcCullough** [comment]
I'm building the image myself using `apps/meteor/.docker/Dockerfile` from this very repo, unaltered. The issue appears to be that some dep, which is being `bumped` during `yarn install` is requiring GLIBC 3+ whereas 2+ is what's available in the base image used to build the RC image.

**Comment by casalsgh** [comment]
asking internal eng team to check

**Comment by JoshMcCullough** [comment]
For now, we switched to the Alpine Dockerfile, which has GLIBC 3 and we are good for now. But we may "prefer" to use move to the non-Alpine image if/when this is resolved.

**Comment by Suvendu-UI** [comment]
can i solve this issue?

**Comment by ggazzo** [comment]
is this still a problem?
