### ISSUE TITLE
Error installing on Debian 12

### ISSUE THREAD

**Issue by paulharris** [RocketChat/Rocket.Chat#33685]
We should reopen #29600 

Two fixes required for me (with node 14.21.3)
* Changing rU to r in:  …/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py    https://github.com/RocketChat/Rocket.Chat/issues/29600#issuecomment-2205999657   ie https://github.com/RocketChat/Rocket.Chat/issues/29600#issuecomment-1977285006
* And adjusting gc-stats version: https://github.com/RocketChat/Rocket.Chat/issues/29600#issuecomment-1977151573 ie https://github.com/RocketChat/Rocket.Chat/issues/29600#issuecomment-2206719827

**Comment by paulharris** [comment]
It almost worked, not it says "Issue with node-fibers"
```
Try running this to fix the issue: /usr/bin/node /home/rocketchat/rocketchat-6.13.0/programs/server/node_modules/fibers/build    
Error: Cannot find module '/home/rocketchat/rocketchat-6.13.0/programs/server/node_modules/fibers/bin/linux-x64-108-glibc/fibers'
Require stack:       
- /home/rocketchat/rocketchat-6.13.0/programs/server/node_modules/fibers/fibers.js
- /home/rocketchat/rocketchat-6.13.0/programs/server/boot.js
- /home/rocketchat/rocketchat-6.13.0/main.js                        
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)                              
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/rocketchat/rocketchat-6.13.0/programs/server/node_modules/fibers/fibers.js:14:39)               
    at Module._compile (node:internal/modules/cjs/loader:1356:14)   
    at Mp._compile (/home/rocketchat/rocketchat-6.13.0/programs/server/runtime.js:77:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)                                 
    at Mp.load (/home/rocketchat/rocketchat-6.13.0/programs/server/runtime.js:37:33)
/home/rocketchat/rocketchat-6.13.0/programs/server/node_modules/fibers/fibers.js:23
                throw new Error('Missing binary. See message above.');                                                           
                ^                                                                             
```

**Comment by paulharris** [comment]
Understood, will wait for 7.0.x to stablise a bit first before I go from 6 to 7
