### ISSUE TITLE
[7.0.0] Cannot install third-party app

### ISSUE THREAD

**Issue by Molkobain** [RocketChat/Rocket.Chat#33871]
### Description:

When trying to install a third party app (Tenor GIF), I have the following error in the UI:
<img width="432" alt="image" src="https://github.com/user-attachments/assets/b27d543c-ca55-4b55-80ae-98e06bc7530c">

And the following logs:
```
Nov 01 20:30:03 casiopea node[72240]: +------------------------------------------------------+
Nov 01 20:30:03 casiopea node[72240]: |                    SERVER RUNNING                    |
Nov 01 20:30:03 casiopea node[72240]: +------------------------------------------------------+
Nov 01 20:30:03 casiopea node[72240]: |                                                      |
Nov 01 20:30:03 casiopea node[72240]: |  Rocket.Chat Version: 7.0.0                          |
Nov 01 20:30:03 casiopea node[72240]: |       NodeJS Version: 20.18.0 - arm64                |
Nov 01 20:30:03 casiopea node[72240]: |      MongoDB Version: 6.0.13                         |
Nov 01 20:30:03 casiopea node[72240]: |       MongoDB Engine: wiredTiger                     |
Nov 01 20:30:03 casiopea node[72240]: |             Platform: linux                          |
Nov 01 20:30:03 casiopea node[72240]: |         Process Port: 3000                           |
Nov 01 20:30:03 casiopea node[72240]: |             Site URL: https://xxxxxxxxx/  |
Nov 01 20:30:03 casiopea node[72240]: |     ReplicaSet OpLog: Enabled                        |
Nov 01 20:30:03 casiopea node[72240]: |          Commit Hash: dfc7e0e874                     |
Nov 01 20:30:03 casiopea node[72240]: |        Commit Branch: HEAD                           |
Nov 01 20:30:03 casiopea node[72240]: |                                                      |
Nov 01 20:30:03 casiopea node[72240]: +------------------------------------------------------+
Nov 01 20:30:04 casiopea node[72240]: {"level":51,"time":"2024-11-01T19:30:04.714Z","pid":72240,"hostname":"casiopea","name":"License","msg":"License installed","version":"3.0","hash":"B_p3wS8c"}
Nov 01 20:31:11 casiopea node[72240]: The server detected an unauthenticated access to an user avatar. This type of request will soon be blocked by default.
Nov 02 00:00:06 casiopea node[72240]: {"level":51,"time":"2024-11-01T23:00:06.932Z","pid":72240,"hostname":"casiopea","name":"License","msg":"License installed","version":"3.0","hash":"M6DCMjRE"}
Nov 02 00:00:12 casiopea node[72240]: {"level":50,"time":"2024-11-01T23:00:11.965Z","pid":72240,"hostname":"casiopea","name":"System","msg":"Failed to communicate with Rocket.Chat Cloud","url":"https://releases.rocket.chat/v2/server/supportedVersions","err":{"type":"AbortError","message":"The user aborted a request.","stack":"AbortError: The user aborted a request.\n    at abort (/opt/Rocket.Chat/programs/server/npm/node_modules/node-fetch/lib/index.js:1458:16)\n    at AbortSignal.abortAndFinalize (/opt/Rocket.Chat/programs/server/npm/node_modules/node-fetch/lib/index.js:1473:4)\n    at AbortSignal.dispatchEvent (/opt/Rocket.Chat/programs/server/npm/node_modules/event-target-shim/src/event-target.mjs:337:35)\n    at abortSignal (/opt/Rocket.Chat/programs/server/npm/node_modules/abort-controller/src/abort-signal.ts:68:12)\n    at AbortController.abort (/opt/Rocket.Chat/programs/server/npm/node_modules/abort-controller/src/abort-controller.ts:26:9)\n    at Timeout.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/server-fetch/src/index.ts:42:48)\n    at listOnTimeout (node:internal/timers:581:17)\n    at processTimers (node:internal/timers:519:7)","name":"AbortError"}}
Nov 02 12:00:03 casiopea node[72240]: {"level":51,"time":"2024-11-02T11:00:03.671Z","pid":72240,"hostname":"casiopea","name":"License","msg":"License installed","version":"3.0","hash":"1P63oSLY"}
Nov 02 19:37:47 casiopea node[72240]: Failed to startup Deno subprocess Error: spawn deno ENOENT
Nov 02 19:37:47 casiopea node[72240]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:286:19)
Nov 02 19:37:47 casiopea node[72240]:     at onErrorNT (node:internal/child_process:484:16)
Nov 02 19:37:47 casiopea node[72240]:     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
Nov 02 19:37:47 casiopea node[72240]:   errno: -2,
Nov 02 19:37:47 casiopea node[72240]:   code: 'ENOENT',
Nov 02 19:37:47 casiopea node[72240]:   syscall: 'spawn deno',
Nov 02 19:37:47 casiopea node[72240]:   path: 'deno',
Nov 02 19:37:47 casiopea node[72240]:   spawnargs: [
Nov 02 19:37:47 casiopea node[72240]:     'run',
Nov 02 19:37:47 casiopea node[72240]:     '--allow-net',
Nov 02 19:37:47 casiopea node[72240]:     '--allow-read=/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine,/opt/Rocket.Chat/programs/server/npm/node_modules',
Nov 02 19:37:47 casiopea node[72240]:     '--allow-env=NODE_EXTRA_CA_CERTS',
Nov 02 19:37:47 casiopea node[72240]:     '/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts',
Nov 02 19:37:47 casiopea node[72240]:     '--subprocess',
Nov 02 19:37:47 casiopea node[72240]:     'ab4728ec-613e-472f-a24c-b48a77aacfff'
Nov 02 19:37:47 casiopea node[72240]:   ]
Nov 02 19:37:47 casiopea node[72240]: }
Nov 02 19:40:11 casiopea node[72240]: Version 9 of Highlight.js has reached EOL and is no longer supported.
Nov 02 19:40:11 casiopea node[72240]: Please upgrade or ask whatever dependency you are using to upgrade.
Nov 02 19:40:11 casiopea node[72240]: https://github.com/highlightjs/highlight.js/issues/2877
```

### Steps to reproduce:

1. Administration
2. Marketplace
3. Search for "Tenor"
4. Install app
5. See error

### Expected behavior:

App should install properly

### Actual behavior:

<img width="432" alt="image" src="https://github.com/user-attachments/assets/b27d543c-ca55-4b55-80ae-98e06bc7530c">

### Server Setup Information:

- Version of Rocket.Chat Server: 7.0.0
- License Type: Community
- Number of Users: 4
- Operating System: Debian
- Deployment Method: Manual
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v20.18.0
- MongoDB Version: v6.0.13

### Client Setup Information

- Desktop App or Browser Version: Browser on latest Chrome
- Operating System: MacOS 15.1

### Additional context

N.A.

### Relevant logs:

```
Nov 01 20:30:03 casiopea node[72240]: +------------------------------------------------------+
Nov 01 20:30:03 casiopea node[72240]: |                    SERVER RUNNING                    |
Nov 01 20:30:03 casiopea node[72240]: +------------------------------------------------------+
Nov 01 20:30:03 casiopea node[72240]: |                                                      |
Nov 01 20:30:03 casiopea node[72240]: |  Rocket.Chat Version: 7.0.0                          |
Nov 01 20:30:03 casiopea node[72240]: |       NodeJS Version: 20.18.0 - arm64                |
Nov 01 20:30:03 casiopea node[72240]: |      MongoDB Version: 6.0.13                         |
Nov 01 20:30:03 casiopea node[72240]: |       MongoDB Engine: wiredTiger                     |
Nov 01 20:30:03 casiopea node[72240]: |             Platform: linux                          |
Nov 01 20:30:03 casiopea node[72240]: |         Process Port: 3000                           |
Nov 01 20:30:03 casiopea node[72240]: |             Site URL: https://rocket.molkobain.com/  |
Nov 01 20:30:03 casiopea node[72240]: |     ReplicaSet OpLog: Enabled                        |
Nov 01 20:30:03 casiopea node[72240]: |          Commit Hash: dfc7e0e874                     |
Nov 01 20:30:03 casiopea node[72240]: |        Commit Branch: HEAD                           |
Nov 01 20:30:03 casiopea node[72240]: |                                                      |
Nov 01 20:30:03 casiopea node[72240]: +------------------------------------------------------+
Nov 01 20:30:04 casiopea node[72240]: {"level":51,"time":"2024-11-01T19:30:04.714Z","pid":72240,"hostname":"casiopea","name":"License","msg":"License installed","version":"3.0","hash":"B_p3wS8c"}
Nov 01 20:31:11 casiopea node[72240]: The server detected an unauthenticated access to an user avatar. This type of request will soon be blocked by default.
Nov 02 00:00:06 casiopea node[72240]: {"level":51,"time":"2024-11-01T23:00:06.932Z","pid":72240,"hostname":"casiopea","name":"License","msg":"License installed","version":"3.0","hash":"M6DCMjRE"}
Nov 02 00:00:12 casiopea node[72240]: {"level":50,"time":"2024-11-01T23:00:11.965Z","pid":72240,"hostname":"casiopea","name":"System","msg":"Failed to communicate with Rocket.Chat Cloud","url":"https://releases.rocket.chat/v2/server/supportedVersions","err":{"type":"AbortError","message":"The user aborted a request.","stack":"AbortError: The user aborted a request.\n    at abort (/opt/Rocket.Chat/programs/server/npm/node_modules/node-fetch/lib/index.js:1458:16)\n    at AbortSignal.abortAndFinalize (/opt/Rocket.Chat/programs/server/npm/node_modules/node-fetch/lib/index.js:1473:4)\n    at AbortSignal.dispatchEvent (/opt/Rocket.Chat/programs/server/npm/node_modules/event-target-shim/src/event-target.mjs:337:35)\n    at abortSignal (/opt/Rocket.Chat/programs/server/npm/node_modules/abort-controller/src/abort-signal.ts:68:12)\n    at AbortController.abort (/opt/Rocket.Chat/programs/server/npm/node_modules/abort-controller/src/abort-controller.ts:26:9)\n    at Timeout.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/server-fetch/src/index.ts:42:48)\n    at listOnTimeout (node:internal/timers:581:17)\n    at processTimers (node:internal/timers:519:7)","name":"AbortError"}}
Nov 02 12:00:03 casiopea node[72240]: {"level":51,"time":"2024-11-02T11:00:03.671Z","pid":72240,"hostname":"casiopea","name":"License","msg":"License installed","version":"3.0","hash":"1P63oSLY"}
Nov 02 19:37:47 casiopea node[72240]: Failed to startup Deno subprocess Error: spawn deno ENOENT
Nov 02 19:37:47 casiopea node[72240]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:286:19)
Nov 02 19:37:47 casiopea node[72240]:     at onErrorNT (node:internal/child_process:484:16)
Nov 02 19:37:47 casiopea node[72240]:     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
Nov 02 19:37:47 casiopea node[72240]:   errno: -2,
Nov 02 19:37:47 casiopea node[72240]:   code: 'ENOENT',
Nov 02 19:37:47 casiopea node[72240]:   syscall: 'spawn deno',
Nov 02 19:37:47 casiopea node[72240]:   path: 'deno',
Nov 02 19:37:47 casiopea node[72240]:   spawnargs: [
Nov 02 19:37:47 casiopea node[72240]:     'run',
Nov 02 19:37:47 casiopea node[72240]:     '--allow-net',
Nov 02 19:37:47 casiopea node[72240]:     '--allow-read=/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine,/opt/Rocket.Chat/programs/server/npm/node_modules',
Nov 02 19:37:47 casiopea node[72240]:     '--allow-env=NODE_EXTRA_CA_CERTS',
Nov 02 19:37:47 casiopea node[72240]:     '/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts',
Nov 02 19:37:47 casiopea node[72240]:     '--subprocess',
Nov 02 19:37:47 casiopea node[72240]:     'ab4728ec-613e-472f-a24c-b48a77aacfff'
Nov 02 19:37:47 casiopea node[72240]:   ]
Nov 02 19:37:47 casiopea node[72240]: }
Nov 02 19:40:11 casiopea node[72240]: Version 9 of Highlight.js has reached EOL and is no longer supported.
Nov 02 19:40:11 casiopea node[72240]: Please upgrade or ask whatever dependency you are using to upgrade.
Nov 02 19:40:11 casiopea node[72240]: https://github.com/highlightjs/highlight.js/issues/2877
```

**Comment by fc757** [comment]
So this is what fixed it for me.

systemctl stop rocketchat

curl -fsSL https://deno.land/install.sh | sh -s v1.0.0

cp deno from ~/.deno/bin to /usr/bin/deno or add it to your path

then I did deno  upgrade --version 1.43.6

**Comment by Molkobain** [comment]
Thanks for the tip, it fixed the error and I was able to install the app!
