### ISSUE TITLE
I can't register a Telegram Bot

### ISSUE THREAD

**Issue by AlejandroRM-DEV** [RocketChat/Rocket.Chat#34054]
### Description:

I can't register a Telegram Bot. I have followed the tutorial https://docs.rocket.chat/docs/telegram-app however when I enable the application I get a 403 error. The error I get is as follows:

`
[
  "Failed to register Telegram webhook. Error: ",
  "{\"stack\":\"Error: Error occurred while registering webhook. Response received from api: {\\\"status\\\":403,\\\"requestId\\\":\\\"6f395e78-6996-4b2e-955f-2f70dd35e960\\\",\\\"errorCode\\\":403,\\\"i18n\\\":\\\"workspace_telegram_disabled\\\",\\\"error\\\":\\\"workspace service record does not have the telegram service account enabled\\\"} with status code: 403\\n    at so (eval at wrapAppCode (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/handlers/app/construct.ts:56:10), <anonymous>:98:21085)\\n    at eventLoopTick (ext:core/01_core.js:168:7)\\n    at async Ci.onEnable (eval at wrapAppCode (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/handlers/app/construct.ts:56:10), <anonymous>:101:11688)\\n    at async handleApp (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/handlers/app/handler.ts:70:26)\\n    at async requestRouter (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts:73:20)\",\"message\":\"Error occurred while registering webhook. Response received from api: {\\\"status\\\":403,\\\"requestId\\\":\\\"6f395e78-6996-4b2e-955f-2f70dd35e960\\\",\\\"errorCode\\\":403,\\\"i18n\\\":\\\"workspace_telegram_disabled\\\",\\\"error\\\":\\\"workspace service record does not have the telegram service account enabled\\\"} with status code: 403\"}"
]
`

### Steps to reproduce:

1. Save Telegram Bot Token
2. View logs

### Expected behavior:

Receiving and sending messages in omnichannel

### Actual behavior:

![Captura de pantalla 2024-11-25 a la(s) 11 40 52 a m](https://github.com/user-attachments/assets/33cac3ea-ebe7-4660-9384-c6274289109e)

### Server Setup Information:

- Version of Rocket.Chat Server: 7.0.0
- License Type: Starter
- Number of Users: 2
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: 20.17.0
- MongoDB Version: 6.0.13 / wiredTiger

**Comment by reetp** [comment]
Seems it needs something enabled on your workspace account.

I'll try and find out.

**Comment by AlejandroRM-DEV** [comment]
Hi.
Yes, we redeployed the Docker, restarted it, enabled and disabled the app and nothing worked.

**Comment by casalsgh** [comment]
Seems we have a bug on the apps subscription on marketplace. Don't have a good solution for it right now. Would require some manual intervention. Will see if I can get someone to help.

**Comment by Jairo-Canova** [comment]
Hello
Can you share your workspace URL, or DM me? I'll try to enable with our API

**Comment by casalsgh** [comment]
FYI - Jairo is from Rocket.Chat support team

**Comment by Jairo-Canova** [comment]
> > Hello Can you share your workspace URL, or DM me? I'll try to enable with our API
> 
> Hi, this is our workspace URL https://chat.oruss.io, if it helps I tried using the community licence and it didn't work either.

Hello,
Telegram is a Premium app, does not work with Community. Can you please test again with Starter plan and provide fresh logs if it still doesn't work? 
If possible, also change to debug mode before testing (at Workspace > settings > Logs > log level > 2 (after testing, change back to 0 or your workspace might get slower)
If you want to I can change your plan from our side. Please keep us updated.

**Comment by reetp** [comment]
The OP said he was on Starter in his first post.

> License Type: Starter

He just tested community as well.

**Comment by AlejandroRM-DEV** [comment]
I didn't see relevant logs.

I didn't know that premium apps don't work on community, I thought they were limited to five because Facebook Messenger works fine, but we can change the license if needed.

**Comment by Jairo-Canova** [comment]
> The OP said he was on Starter in his first post.
> 
> > License Type: Starter
> 
> He just tested community as well.

Thank you. There's a workaround from our end to enable apps that show disabled on logs, but for it to work he needs to be on a plan that supports that app - he's currently on CE, so it won't work... after changing to Starter I'll try.

We've seen some issues on apps appearing as disabled on logs, our team is looking into it to fix, meanwhile we're doing this workaround

**Comment by Jairo-Canova** [comment]
> chat.oruss.io

Please change back to Starter at your convenience and let me know here, as I said to reetp above there's a workaround we're using while this is not definitively fixed

**Comment by AlejandroRM-DEV** [comment]
I'm not sure where to upgrade to Starter. When I go to the Workspace / Subscription / Upgrade button, it takes me to the Pro Plan checkout page.

**Comment by Jairo-Canova** [comment]
> chat.oruss.io

I changed from our end just now. Please navigate to Workspace > Subscription > click Sync license update button to apply changes. Then follow the steps provided on my first reply to double-check issue still happens, let me know if it does and I'll do the workaround.

**Comment by AlejandroRM-DEV** [comment]
It doesn't work:

```
[
  "Failed to register Telegram webhook. Error: ",
  {
    "stack": "Error: Error occurred while registering webhook. Response received from API: {\"status\":403,\"requestId\":\"XXXXXXXXXXX\",\"errorCode\":403,\"i18n\":\"workspace_telegram_disabled\",\"error\":\"workspace service record does not have the telegram service account enabled\"} with status code: 403\n    at so (eval at wrapAppCode (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/handlers/app/construct.ts:56:10), <anonymous>:98:21085)\n    at eventLoopTick (ext:core/01_core.js:168:7)\n    at async Ci.onEnable (eval at wrapAppCode (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/handlers/app/construct.ts:56:10), <anonymous>:101:11688)\n    at async handleApp (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/handlers/app/handler.ts:70:26)\n    at async requestRouter (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts:74:20)",
    "message": "Error occurred while registering webhook. Response received from API: {\"status\":403,\"requestId\":\"XXXXXXXXXXX\",\"errorCode\":403,\"i18n\":\"workspace_telegram_disabled\",\"error\":\"workspace service record does not have the telegram service account enabled\"} with status code: 403"
  }
]
```

**Comment by Jairo-Canova** [comment]
> It doesn't work:
> 
> ```
> [
>   "Failed to register Telegram webhook. Error: ",
>   {
>     "stack": "Error: Error occurred while registering webhook. Response received from API: {\"status\":403,\"requestId\":\"XXXXXXXXXXX\",\"errorCode\":403,\"i18n\":\"workspace_telegram_disabled\",\"error\":\"workspace service record does not have the telegram service account enabled\"} with status code: 403\n    at so (eval at wrapAppCode (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/handlers/app/construct.ts:56:10), <anonymous>:98:21085)\n    at eventLoopTick (ext:core/01_core.js:168:7)\n    at async Ci.onEnable (eval at wrapAppCode (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/handlers/app/construct.ts:56:10), <anonymous>:101:11688)\n    at async handleApp (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/handlers/app/handler.ts:70:26)\n    at async requestRouter (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts:74:20)",
>     "message": "Error occurred while registering webhook. Response received from API: {\"status\":403,\"requestId\":\"XXXXXXXXXXX\",\"errorCode\":403,\"i18n\":\"workspace_telegram_disabled\",\"error\":\"workspace service record does not have the telegram service account enabled\"} with status code: 403"
>   }
> ]
> ```

Hello. We manually enabled Telegram on your WS, please test again.

**Comment by AlejandroRM-DEV** [comment]
I couldn't make it work :(

**Comment by Jairo-Canova** [comment]
> Hello, I have the same problem. Rocket.Chat Version: 7.1.0 NodeJS Version: 20.18.0 - x64 MongoDB Version: 6.0.13 MongoDB Engine: wiredTiger Deployment Method: Docker ReplicaSet OpLog: Enabled

Hello. Telegram also shows Disabled on logs? Can you tell me your workspace URL?

**Comment by Jairo-Canova** [comment]
> I couldn't make it work :(

Hello. Same thing showing on logs? Telegram disabled?

**Comment by Jairo-Canova** [comment]
Hello. This issue was solved on version 7.0.1
https://github.com/RocketChat/Rocket.Chat/releases/tag/7.0.1

**Comment by Suvendu-UI** [comment]
i think this issue is solved right as said by Jairo-Canova

**Comment by Jairo-Canova** [comment]
> Still getting error with `workspace_telegram_disabled`. Tried all of 7.0.1, 7.0.3 and 7.1.0 - in every of them Telegram App returns the same error as OPs initial message

Hello. it is solved on 7.01~3 but still can happens on 7.1 (we're working on that). Can you try restarting your server after updating? If just that doesn't solve, can you share your WS URL? I'll take a look

**Comment by almod90** [comment]
> > Still getting error with `workspace_telegram_disabled`. Tried all of 7.0.1, 7.0.3 and 7.1.0 - in every of them Telegram App returns the same error as OPs initial message
> 
> Hello. it is solved on 7.01~3 but still can happens on 7.1 (we're working on that). Can you try restarting your server after updating? If just that doesn't solve, can you share your WS URL? I'll take a look

Thanks for a quick reply! WS is `code.swelectricians.com`. I set version 7.0.3 just now - removed and installed back TG app. At first onEnable passed without any errors, but once I put my TG bot token and restart everything it is happening again. enabling/disabling app results the same

**Comment by Jairo-Canova** [comment]
> code.swelectricians.com

Apologies for the delay. I updated manually your WS as well to enable Telegram, pls try again. 

I'll let our team know that this issue happens when downgrading from 7.1 to 7.0.3.

**Comment by VNegadov** [comment]
Hello! Please help me solve this problem. 
Version 7.2.0
When using telegram, we receive an error message:
"Error occurred while registering webhook. Response received from api:
{\"status\":403,\"requestId\":\"8f709a86-55e3-4578-8dd4-ea249d537e18\",\"errorCode\":403,\"i18n\":\"workspace_telegram_disabled\\",\\"error\":\"workspace service record does not have the telegram service account enabled\"} with status code: 403"

Workspace plan Starter Seats. Our workspace: 
https://cloud.rocket.chat/workspaces/65682a992387120001b84028
https://chat.enterego.ru/

**Comment by Jairo-Canova** [comment]
> Hello! Please help me solve this problem. Version 7.2.0 When using telegram, we receive an error message: "Error occurred while registering webhook. Response received from api: {"status":403,"requestId":"8f709a86-55e3-4578-8dd4-ea249d537e18","errorCode":403,"i18n":"workspace_telegram_disabled\",\"error":"workspace service record does not have the telegram service account enabled"} with status code: 403"
> 
> Workspace plan Starter Seats. Our workspace: https://cloud.rocket.chat/workspaces/65682a992387120001b84028 https://chat.enterego.ru/

Hello. I tried using my arcane API on this WS and got a 500 error "i18n": "internal_server_error",, is your server running? I can open your login page from browser, not sure why API didn't work. Have you setup reverse proxy? And can you share a print of your Marketplace page for Telegram? AFAIK this was solved on 7.2

**Comment by VNegadov** [comment]
Thanks for the quick reply!
https://cloud.enterego.com/index.php/s/9s9WsfAaHiZMq5d - Screenshot
our server is running and looks working well
we are using it from outside all the time, including mobile app and don't notice any troubles
what is arcane api? we use rest api to deliver messages from external system, and it works as well.

**Comment by VNegadov** [comment]
how can we reproduce this issue?

**Comment by Jairo-Canova** [comment]
> `on this WS and got a 500 error "i18n": "internal_server_error"` how can we reproduce this issue?

It was obtained with a custom API script we developed for this issue, it worked for other WS on this thread but I got this 500 error on yours =( I'll have to delve deeper to see if anything changed for 7.2 or if we need to escalate to engineering

I have back to back meetings the next few days, I'll pick this up again on tuesday, sorry for the delay

**Comment by VNegadov** [comment]
> > > > `on this WS and got a 500 error "i18n": "internal_server_error"` как мы можем воспроизвести эту проблему?
> > > 
> > > 
> > > Это было получено с помощью специального скрипта API, который мы разработали для решения этой проблемы. Он работал для других WS в этой ветке, но на вашем я получил ошибку 500 =( Мне нужно будет копнуть глубже, чтобы понять, изменилось ли что-то в версии 7.2 или нам нужно обратиться в службу поддержки В ближайшие несколько дней у меня будут встречи одна за другой, я продолжу во вторник, извините за задержку
> > 
> > 
> > Thank you! We are looking forward to solution.
> 
> Hello. It is enabled, pls test again and should be working now. I'll tell our team this is still happening on 7.2

Thank you so much for your help, everything is working as it should now!
