### ISSUE TITLE
Push Notifications Not Sending - Error: "Unsupported Version"

### ISSUE THREAD

**Issue by wichmann-git** [RocketChat/Rocket.Chat#34163]
We are experiencing an issue where push notifications are no longer being sent from our Rocket.Chat instance. The logs show repeated errors stating "Error sending push to gateway" and "unsupported version". Everything on the Rocket.Chat Cloud Console looks fine.

**System Information:**
Rocket.Chat Version: 7.1.0
Application Engine Version: 1.48.0
Node Version: v20.17.0
MongoDB Version: 6.0.13 / wiredTiger (Oplog Enabled)

**Logs:**
```
{"level":50,"time":"2024-12-11T12:25:16.633Z","pid":1,"hostname":"e2531f449699","name":"Push","msg":"Error sending push to gateway (5 try) ->","err":"{\"errorMsg\":\"unsupported version\"}"}
{"level":50,"time":"2024-12-11T12:25:16.646Z","pid":1,"hostname":"e2531f449699","name":"Push","msg":"Error sending push to gateway (5 try) ->","err":"{\"errorMsg\":\"unsupported version\"}"}
{"level":50,"time":"2024-12-11T12:25:16.707Z","pid":1,"hostname":"e2531f449699","name":"Push","msg":"Error sending push to gateway (5 try) ->","err":"{\"errorMsg\":\"unsupported version\"}"}
{"level":50,"time":"2024-12-11T12:25:16.769Z","pid":1,"hostname":"e2531f449699","name":"Push","msg":"Error sending push to gateway (5 try) ->","err":"{\"errorMsg\":\"unsupported version\"}"}
{"level":50,"time":"2024-12-11T12:25:16.899Z","pid":1,"hostname":"e2531f449699","name":"Push","msg":"Error sending push to gateway (5 try) ->","err":"{\"errorMsg\":\"unsupported version\"}"}
```

**Comment by Nirvanjha2004** [comment]
@wichmann-git can i work on this issue

**Comment by darshanlahamage** [comment]
@wichmann-git  I have rocket chat locally setup . Can you explain how to replicate this and assign it to me.

**Comment by reetp** [comment]
> We are experiencing an issue where push notifications are no longer being sent from our Rocket.Chat instance. The logs show repeated errors stating "Error sending push to gateway" and "unsupported version".

As per the issue template, what licence are you running?

How is it deployed?

Did it work with v7.0?

Have you changed anything?

**Comment by reetp** [comment]
> @wichmann-git can i work on this issue

Please don't '@' - it is not necessary and can be annoying.

No one assigns issues.

To work on it you need to triage and find out what exactly is wrong.

See my comments above.

**Comment by wichmann-git** [comment]
Hello,
We are running RocketChat on a self-hosted Docker setup with the Community Edition.
The problem started **before** upgrading to 7.0.0. 
One thing we noticed is that in the Cloud Console under "Domain," our local IP address of the instance is listed. However, on Stratus, it shows as "active" and everything appears to be working correctly.
![image](https://github.com/user-attachments/assets/2c45f561-7b2b-43f2-ad55-7ef607da90b4)

**Comment by Harshbansal8705** [comment]
> No one assigns issues.

Hello, I'm new to this repository. Could you please tell how can I start working on some issue? As the [documentation](https://developer.rocket.chat/docs/participate-in-rocketchat-development#:~:text=If%20you%20come%20across%20an%20issue%20you%27d%20like%20to%20work%20on%2C%20simply%20leave%20a%20comment.%20We%27ll%20mark%20you%20as%20Assignee%20to%20the%20issue%20and%20add%20an%20In%20Progress%20label.) says:

```
If you come across an issue you'd like to work on, simply leave a comment. We'll mark you as Assignee to the issue and add an [In Progress label](https://github.com/RocketChat/Rocket.Chat/labels/stat%3A%20in%20progress).
```

**Comment by reetp** [comment]
> > No one assigns issues.
> 
> Hello, I'm new to this repository. Could you please tell how can I start working on some issue? As the

>> If you come across an issue you'd like to work on, simply leave a comment. We'll mark you as Assignee to the issue and add an [In Progress label](https://github.com/RocketChat/Rocket.Chat/labels/stat%3A%20in%20progress).

That needs updating as it is incorrect.

You should really follow this advice:

https://open.rocket.chat/channel/Code-walk-through-and-architecture?msg=Dk4yTh5opgNZa4v9G

>> Is it mandatory to discuss an issue on the community server before creating it?7

> Basically YES, for our projects especially, going blindly assuming that an issue is (still) relevant (without knowledge/understanding of the issue/system or the ecosystem) is guaranteed to make you disillusioned from writing code that never gets merged. If the issue is a bug, you will be able to confirm it -- and rule out that it might be intentional by design or perhaps misunderstanding from a new user/admin.

Also read this for some tips.

https://gist.github.com/reetp/b0ba4e3d0ea2ff48ca9da00a5a647d42#file-developers-readme-md

You cannot try and fix something if you do not understand the problem. triage/diagnosis is the first step in saving you a lot of wasted time

**Comment by reetp** [comment]
> Hello, We are running RocketChat on a self-hosted Docker setup with the Community Edition. The problem started **before** upgrading to 7.0.0. The installed Version was 6.12.1 

Not sure why you didn't report it then....!

> One thing we noticed is that in the Cloud Console under "Domain," our local IP address of the instance is listed. However, on Status, it shows as "active" and everything appears to be working correctly. !

Well, it is, but then it isn't, hence this Issue....

So I would imagine you registered your server using the local IP before you stuck it behind a reverse proxy (you are using a reverse proxy???)?

Yes that registration is 'Active' but not necessarily synced to your server which is now on a different IP.

This will probably need someone in support to fix it on the cloud.

I'll ask someone to contact you. Please be patient. This is no paid support.

**Comment by Kartikayy007** [comment]
> > @wichmann-git can i work on this issue
> 
> Please don't '@' - it is not necessary and can be annoying.
> 
> No one assigns issues.
> 
> To work on it you need to triage and find out what exactly is wrong.
> 
> See my comments above.

hey @reetp I wanted to confirm as I am a beginner here and to open source so should I immediately start working if I see no one addressing the issue and raise a PR?

**Comment by reetp** [comment]
> > > @wichmann-git can i work on this issue
> > 
> > Please don't '@' - it is not necessary and can be annoying.

> 
> hey @reetp 

Don't you read?

> should I immediately start working

Do you actually know what the issue is?

Have you read what I posted? Have you worked out if it is a bug that needs fixing or a support issue?

If you are a beginner read all the docs and ask questions in open.rocket.chat

**Comment by Kartikayy007** [comment]
Hi @reetp Thank you for the guidance. I’ll take the time to understand the issue thoroughly, replicate it locally, and engage with the community if needed.  Appreciate your help!

**Comment by reetp** [comment]
STOP '@' !!!!!!!!!!

I am having lunch and don't want my phone pinging me. I do not work here.

I will just block you.

Thank you.

**Comment by czepan** [comment]
We have the same problem for some time now:
![image](https://github.com/user-attachments/assets/a4af13d3-5720-415a-8ed2-85b2dae749cc)

Version: 6.11.0
Selfhosted
Community Edition

**Comment by ccnikam** [comment]
Bro there are some bugs !!

**Comment by reetp** [comment]
> Version: 6.11.0

You need to use a fixed version. Yours has at least one security fix. I'd hurry up and do that if I was you......

As per debug instructions you must test on latest release as well, and properly fill out your own server details as they are all different - install type, reverse proxy, firewalls etc.

**Comment by czepan** [comment]
@reetp 
OP tested it on the newest release candidate 7.1.0 so I don't expect an update to fix this issue - must be something else.
For the other infos, there's nothing special:
- License Type: Community
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: v14.21.3
- MongoDB Version:6.0.15

**Comment by reetp** [comment]
> @reetp 

Don't do that. I don't work here.

> OP tested it on the newest release candidate 7.1.0 so I don't expect an update to fix this issue - must be something else.

As I said installs vary. Making assumptions that the cause of their issue is the cause of yours is how you waste a lot of time.....

> For the other infos, there's nothing special:

Except your version has at least one security hole...

Have you checked the URL link in the logs which accesses the web page with the support info is accessible from inside the container (note the OP didn't mention deployment type)? Should be able to wget it.

I can't remember the exact path for it.

**Comment by czepan** [comment]
The issue appears to have been resolved over the course of today – push notifications are being sent correctly again. The gateway no longer returns 'unsupported version.' We haven’t made any changes since last night, when the problem still existed, so we assume there was an issue on the gateway side.

![Screenshot_20241218-111036](https://github.com/user-attachments/assets/912045ae-2fab-4025-96fb-8cda4720fc52)
Thank you and best regards.

**Comment by wandt-git** [comment]
Hi, I am OPs customer for this server. I will provide some additional information :

Today I found this in the log:
`{"level":50,"time":"2024-12-18T12:00:15.023Z","pid":1,"hostname":"e2531f449699","name":"System","msg":"Failed to communicate with Rocket.Chat Cloud","url":"https://releases.rocket.chat/v2/server/supportedVersions","err":{"type":"AbortError","message":"The user aborted a request.","stack":"AbortError: The user aborted a request.<br>    at abort (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1458:16)<br>    at AbortSignal.abortAndFinalize (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1473:4)<br>    at AbortSignal.dispatchEvent (/app/bundle/programs/server/npm/node_modules/event-target-shim/src/event-target.mjs:337:35)<br>    at abortSignal (/app/bundle/programs/server/npm/node_modules/abort-controller/src/abort-signal.ts:68:12)<br>    at AbortController.abort (/app/bundle/programs/server/npm/node_modules/abort-controller/src/abort-controller.ts:26:9)<br>    at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/src/index.ts:43:48)<br>    at listOnTimeout (node:internal/timers:581:17)<br>    at processTimers (node:internal/timers:519:7)","name":"AbortError"}} `

I then noticed that the list in https://releases.rocket.chat/v2/server/supportedVersions does include version 7.1.0 and is accessible from our network.
![grafik](https://github.com/user-attachments/assets/6dbb9b19-11e7-4fff-93ae-096b33c9f5b1)
As that is the case, the "unsupported version" error is rather confusing.
Also, I do not see anything regarding push-service in the release notes.

> Not sure why you didn't report it then....!
Since updates were available, we first wanted to see if updating fixed the problem
Also, in another issue it was suggested to click "sync license update" in the subscription menu. While that did cause a handful of push notices to be delivered, the problem soon came back.

> (note the OP didn't mention deployment type)
He did in a later post. It is docker

**Comment by hallo43** [comment]
we are using Rocket.chat community, and Rocket.chat not push with FCM.
have anyone resolved this issues!?
@wichmann-git do you have any solution?

**Comment by wichmann-git** [comment]
> we are using Rocket.chat community, and Rocket.chat not push with FCM. have anyone resolved this issues!? @wichmann-git do you have any solution?

Unfortunately, this issue still persists, and we are still encountering the "Unsupported Version" error when sending push notifications. The entries in the log file remain unchanged.

**Comment by darshanlahamage** [comment]
> > we are using Rocket.chat community, and Rocket.chat not push with FCM. have anyone resolved this issues!? @wichmann-git do you have any solution?
> 
> Unfortunately, this issue still persists, and we are still encountering the "Unsupported Version" error when sending push notifications. The entries in the log file remain unchanged.

Which node version you are using? You have mentioned node v20.17.0

**Comment by wichmann-git** [comment]
> > > we are using Rocket.chat community, and Rocket.chat not push with FCM. have anyone resolved this issues!? @wichmann-git do you have any solution?
> > 
> > 
> > Unfortunately, this issue still persists, and we are still encountering the "Unsupported Version" error when sending push notifications. The entries in the log file remain unchanged.
> 
> Which node version you are using? You have mentioned node v20.17.0
we are currently using Node v20.18.0.

**Comment by reetp** [comment]
So I there are so many confusing bits of info here so it is hard to see the wood for the trees.

I presume wichman-git and wandt-git work at the same place. 

I think they are running this (hence the need for a comprehensive report on your OWN server rather than odd bits):

Community Edition
docker - Host/Bridged ??
v 7.10
Mongo version ??
Reverse proxy ??

(we then know with docker what the node version should be)

> One thing we noticed is that in the Cloud Console under "Domain," our local IP address of the instance is listed

I think that needs to be resolved. It should show your domain eg chatserver.mydomain.com 
If that is the case we need your workspace ID and host.domain to get support to fix it. You can find me here https://open.rocket.chat/channel/support

Note also CE has a limit of 10,000 push notifications. Even with a few users you can get though several thousand in a month without much trouble. You can check usage by clicking on the name of the server in the cloud panel.

If you run docker you need to check you can access the URL from INSIDE the docker container (and it would be good to know if you are using host or bridged mode)

Just because your desktop can get to it means nothing. 

Check this works:

```
docker exec -t -i -u root <container_name> /bin/sh
wget -q -O - https://releases.rocket.chat/v2/server/supportedVersions
```

If anyone else has issues PLEASE document it properly otherwise we can't help you.

**Comment by wichmann-git** [comment]
When executing the following command inside the Rocket.Chat Docker container:

```
docker exec -t -i -u root <container_name> /bin/sh
wget -q -O - https://releases.rocket.chat/v2/server/supportedVersions
```
The following error occurred:

```
284BA21A2D7F0000:error:02000086:rsa routines:RSA_verify_PKCS1_PSS_mgf1:last octet invalid:crypto/rsa/rsa_pss.c:95:
284BA21A2D7F0000:error:1C880004:Provider routines:rsa_verify:RSA lib:providers/implementations/signature/rsa_sig.c:842:
284BA21A2D7F0000:error:0A00007B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:581:
ssl_client: SSL_connect
wget: error getting response: Connection reset by peer
```


After some investigation, I found that the issue was related to outdated SSL libraries and certificates inside the container. Running the following commands resolved the problem:


```
docker exec -it <container_name> /bin/sh
apk update
apk upgrade
apk add --no-cache openssl ca-certificates
update-ca-certificates
```

**Result:**
After updating the packages and certificates:

1. wget successfully established connections without errors.
2. The push notification system became fully functional again.
3. The hostname appeared correctly in the Rocket.Chat Cloud Console.

Remaining Issue:
While the main issue is resolved, we still observe the following error message in the logs:

`Failed to communicate with Rocket.Chat Cloud","url":"https://releases.rocket.chat/v2/server/supportedVersions","err":{"type":"AbortError","message":"The user aborted a request.","stack":"AbortError: The user aborted a request.\n    at abort (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1458:16)\n    at AbortSignal.abortAndFinalize (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1473:4)\n    at AbortSignal.dispatchEvent (/app/bundle/programs/server/npm/node_modules/event-target-shim/src/event-target.mjs:337:35)\n    at abortSignal (/app/bundle/programs/server/npm/node_modules/abort-controller/src/abort-signal.ts:68:12)\n    at AbortController.abort (/app/bundle/programs/server/npm/node_modules/abort-controller/src/abort-controller.ts:26:9)\n    at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/src/index.ts:43:48)\n    at listOnTimeout (node:internal/timers:581:17)\n    at processTimers (node:internal/timers:519:7)","name":"AbortError"}}`

This error does not appear to have any noticeable impact on functionality. However, if anyone has insights or suggestions regarding this message, they would be greatly appreciated.
