### ISSUE TITLE
start automaticlly after restart

### ISSUE THREAD

**Issue by galrotem1993** [RocketChat/Rocket.Chat#3586]
Your Rocket.Chat version: 0.32.0

I have rocket chat develop version on ubuntu 14.04 and i want to run the develop version automaticlly at startup.
i tried the following methods with no luck:
- crontab

>  @reboot meteor
- edit the /etc/rc.local file
- upstart - https://franciskim.co/2016/01/22/how-to-setup-ubuntus-upstart-to-auto-start-meteor-on-boot/

does anyone know how to start the rocket.chat at startup?

**Comment by Deepakkothandan** [comment]
@galrotem1993 Take a look at this file, I have used this Ansible role to deploy on Ubuntu 14.04 and it works fine.  

[Rocket Chat ubuntu 14.04 Upstart](https://github.com/RocketChat/Rocket.Chat.Ansible/blob/master/templates/rocketchat_upstart.j2)

**Comment by galrotem1993** [comment]
i get this error all the time even after i bundle the app and run it via node

TypeError: Arguments to path.join must be strings
at path.js:360:15
at Array.filter (native)
at Object.exports.join (path.js:358:36)
at Object.pathJoin (


	at path.js:360:15

	at Array.filter (native)

	at Dbject.exports.join (pathijs:358:36)

	at Dbject.path39in (/opt/.meteor/packages/meteor-tool/.1.1.1@.k10ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/taa
	itatic-aSSets/server/minivfilesijs:86:16)

	at defaultwarehousebir ([tools]packaging/tropohouse.js:34:16)

	at 0bject-<anonymous> (/tools/packaging/tropohouse.js:39:42)
	at Module.~compile (module.js:456:26)

	at abject.Module._extensions..js (module.js:474:1e)
	at Module.10ad (module.js:356:32)

	at Function.ModuLe._load (nodule.‘s:312:12

**Comment by TheReal1604** [comment]
Try this: https://github.com/foreverjs/forever

I used that for a node js blog software, works great.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
