### ISSUE TITLE
Latest RocketChat (demo) don't work in IE11

### ISSUE THREAD

**Issue by AdrianoCahete** [RocketChat/Rocket.Chat#361]
Trying to reproduce #290 , i can't open RocketChat in the same browser version, but newer build (IE11 11.0.9600.17905)

Console log:
````You are running a browser with no localStorage or userData support. Logging in from one tab will not cause another tab to be logged in.````

````Error initializing storage for FS.HTTP````

````TypeError: Não é possível obter a propriedade 'setItem' de referência indefinida ou nula
    {[functions]:,
      __proto__: { },
        description: "Não é possível obter a propriedade 'setItem' de referência indefinida ou nula",
        message: "Não é possível obter a propriedade 'setItem' de referência indefinida ou nula",
        name: "TypeError",
        number: -2146823281,
        stack: "TypeError: Não é possível obter a propriedade 'setItem' de referência indefinida ou nula
            at t.HTTP._storage (https://dbde4sd21oahf.cloudfront.net/43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js:262:4835)
            at Anonymous function (https://dbde4sd21oahf.cloudfront.net/43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js:262:5004)
            at Anonymous function (https://dbde4sd21oahf.cloudfront.net/43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js:262:4662)
            at Global code (https://dbde4sd21oahf.cloudfront.net/43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js:262:2992)"
    }````

````SCRIPT5007: Não é possível obter a propriedade 'getItem' de referência indefinida ou nula
Arquivo: 43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js Linha: 498 Coluna: 124````

````SCRIPT445: O objeto não oferece suporte à ação
Arquivo: 43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js Linha: 388 Coluna: 1955````

````Clock discrepancy detected. Attempting re-sync.````

````Exception in defer callback: TypeError: Não é possível obter a propriedade 'getItem' de referência indefinida ou nula
   at Anonymous function (https://dbde4sd21oahf.cloudfront.net/43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js:462:12124)
   at Anonymous function (https://dbde4sd21oahf.cloudfront.net/43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js:58:319)
   at e._withTemplateInstanceFunc (https://dbde4sd21oahf.cloudfront.net/43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js:58:3067)
   at n (https://dbde4sd21oahf.cloudfront.net/43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js:58:228)
   at Anonymous function (https://dbde4sd21oahf.cloudfront.net/43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js:58:1108)
   at n (https://dbde4sd21oahf.cloudfront.net/43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js:57:19603)
   at t.nonreactive (https://dbde4sd21oahf.cloudfront.net/43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js:9:3932)
   at Anonymous function (https://dbde4sd21oahf.cloudfront.net/43ceb24d876e0a8c4fae1fcb52f1939ac2c3f224.js:57:19524)
   at c````

````Clock discrepancy detected. Attempting re-sync.````

**Comment by sampaiodiego** [comment]
seems that you have some security config not allowing sites to use localStorage.

what happens if you type the following command on dev tools while accessing any website?

`localStorage` (hit enter)

**Comment by AdrianoCahete** [comment]
Hm, i just opened IE directly from Start Menu (Win 8.1 x64):

````localStorage````

````null````

**Comment by sampaiodiego** [comment]
it's weird.. can you open rocket.chat on another browser so we can talk directly?

**Comment by sampaiodiego** [comment]
fixed by @AdrianoCahete restornig default settings of his IE
