### ISSUE TITLE
My try at wordpress intergration

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#3715]
Your Rocket.Chat version: 0.35.0

https://github.com/RocketChat/Rocket.Chat/issues/747

https://github.com/RocketChat/Rocket.Chat.Docs/tree/master/4.%20Administrator%20Guides/Authentication/OAuth

Does this still work or do I need to edit the template's functions.php  because I got this, there just isn't documentation for this

```
W20160707-22:34:56.111(0) (oauth_server.js:398) Error in OAuth Server: Failed to complete OAuth handshake with wordpress at http://five-rings-online.com//oauth/token. failed [400] {"error":"redirect_uri_mismatch","error_description":"The redirect URI is missing or do not match","error_uri":"http:\/\/tools.ietf.org\/html\/rfc6749#section-4.1.3"}
I20160707-22:34:56.277(0) Exception while invoking method 'login' Error: Failed to complete OAuth handshake with wordpress at http://five-rings-online.com//oauth/token. failed [400] {"error":"redirect_uri_mismatch","error_description":"The redirect URI is missing or do not match","error_uri":"http:\/\/tools.ietf.org\/html\/rfc6749#section-4.1.3"}     at CustomOAuth.getAccessToken (packages/rocketchat_custom-oauth/custom_oauth_server.coffee:71:16)     at Object.handleOauthRequest (packages/rocketchat_custom-oauth/custom_oauth_server.coffee:106:23)     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)     at middleware (packages/oauth/oauth_server.js:173:1)     at packages/oauth/oauth_server.js:146:1 
```

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates. 

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)

Thanks!
