### ISSUE TITLE
Delete and recreate default room with same name

### ISSUE THREAD

**Issue by xadcoh** [RocketChat/Rocket.Chat#3802]
Your Rocket.Chat version: (0.35.0)

Hi.

I have deployed docker version of Rocket.Chat. It's fantastic, thank you!

But there is a little problem. I have deleted default room named "general", then manualy recrated it from administration and restarted the server. It seems like group doesn't work anymore? there is a log:

```
> rocketchat_1 | Exception in defer callback: MongoError: E11000 duplicate key error collection: rocketchat.rocketchat_room index: name_1 dup key: { : "general" }
> rocketchat_1 |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
> rocketchat_1 |     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
> rocketchat_1 |     at [object Object].MongoConnection.(anonymous function) [as insert] (packages/mongo/mongo_driver.js:736:1)
> rocketchat_1 |     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:48:1)
> rocketchat_1 |     at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
> rocketchat_1 |     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
> rocketchat_1 |     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)
> rocketchat_1 |     at _Class.RocketChat.models._Base._Class.insert (packages/rocketchat_lib/server/models/_Base.coffee:17:24)
> rocketchat_1 |     at _Class.RocketChat.models.Rooms._Class.createWithIdTypeAndName (packages/rocketchat_lib/server/models/Rooms.coffee:481:4)
> rocketchat_1 |     at server/startup/initialData.coffee:5:28
> rocketchat_1 |     - - - - -
> rocketchat_1 |     at Object.toError (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
> rocketchat_1 |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:116:29
> rocketchat_1 |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7
> rocketchat_1 |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
> rocketchat_1 |     at Server.Base._callHandler (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
> rocketchat_1 |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
> rocketchat_1 |     at [object Object].MongoReply.parseBody (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
> rocketchat_1 |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
> rocketchat_1 |     at [object Object].emit (events.js:95:17)
> rocketchat_1 |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
```

Maybe i should do some database cleanup. Same behavior as for private rooms.

**Comment by vetash** [comment]
`Exception in defer callback: MongoError: E11000 duplicate key error collection: rocketchat.rocketchat_room index: name_1 dup key: { : "general" }`
I'm not that good in mongo db but i think yours says you have  2 records with same keys (`general`) so you need to delete one and restart rc. 
Yoy can youse mongo cli or use GUI tools for admin mongo db:
my favourite:
https://github.com/mrvautin/adminMongo
Hope this helps.

**Comment by xadcoh** [comment]
i've followed guide http://andrewkoroluk.com/blog/post/5533066b6098ef3d1b4c23c0 and drop/recreate index. "general" room has reappeared.

**Comment by MartinSchoeler** [comment]
You can try deleting the general channel and restarting the server.
If there is no existing general room rocket chat will create one automatically.
