### ISSUE TITLE
Upgrade to 0.36, rocketchat.service fails to start

### ISSUE THREAD

**Issue by 78c59635bdd8** [RocketChat/Rocket.Chat#3907]
Your Rocket.Chat version: 0.36

Upgraded from 0.35 to 0.36 this morning.  Now my rocketchat.service fails to start:

Aug  3 07:40:14 chat rocketchat: module.js:340
Aug  3 07:40:14 chat rocketchat: throw err;
Aug  3 07:40:14 chat rocketchat: ^
Aug  3 07:40:14 chat rocketchat: Error: Cannot find module 'fibers'
Aug  3 07:40:14 chat rocketchat: at Function.Module._resolveFilename (module.js:338:15)
Aug  3 07:40:14 chat rocketchat: at Function.Module._load (module.js:280:25)
Aug  3 07:40:14 chat rocketchat: at Module.require (module.js:364:17)
Aug  3 07:40:14 chat rocketchat: at require (module.js:380:17)
Aug  3 07:40:14 chat rocketchat: at Object.<anonymous> (/root/Rocket.Chat/programs/server/boot.js:1:75)
Aug  3 07:40:14 chat rocketchat: at Module._compile (module.js:456:26)
Aug  3 07:40:14 chat rocketchat: at Object.Module._extensions..js (module.js:474:10)
Aug  3 07:40:14 chat rocketchat: at Module.load (module.js:356:32)
Aug  3 07:40:14 chat rocketchat: at Function.Module._load (module.js:312:12)
Aug  3 07:40:14 chat rocketchat: at Module.require (module.js:364:17)
Aug  3 07:40:14 chat systemd: rocketchat.service: main process exited, code=exited, status=8/n/a
Aug  3 07:40:14 chat systemd: Unit rocketchat.service entered failed state.
Aug  3 07:40:14 chat systemd: rocketchat.service failed.

**Comment by 78c59635bdd8** [comment]
This can be closed.  Problem was user error during the upgrade.
