### ISSUE TITLE
Issue while changing profile username

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#3940]
Your Rocket.Chat version: (make sure you are running the latest)
0.36
Whenever I got to change my username in RC I get the following error but the old messages change names.
```
Exception while invoking method 'saveUserProfile' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: mentions.$.username     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:1)     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:80:1)     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)     at _Class.update (server/models/_Base.js:78:29)     at _Class.RocketChat.models.Messages._Class.updateUsernameAndMessageOfMentionByIdAndOldUsername (packages/rocketchat_lib/server/models/Messages.coffee:231:11)     at packages/rocketchat_lib/server/functions/setUsername.coffee:40:31     - - - - -     at Object.toError (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:577:27     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9     at Server.Base._callHandler (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18     at [object Object].MongoReply.parseBody (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)     at [object Object].emit (events.js:95:17)     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13) 
```

**Comment by thecanadianbaker** [comment]
We are also experiencing this issue using LDAP with 0.36
```
sync.js:179 LDAPSync ➔ error { [MongoError: The positional operator did not find the match needed from the query. Unexpanded update: mentions.$.username] stack: [Getter] }
```

**Comment by onebadvoodoo** [comment]
I am having the same issue with the same build. Just want to follow this thread for any updates.

**Comment by julienfroidefond** [comment]
Same here:
Exception while invoking method 'saveUserProfile' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: mentions.$.username ...

**Comment by sushi0x01** [comment]
+1
v0.37.0

**Comment by Flayks** [comment]
+1

**Comment by brunofoca** [comment]
same here +1
0.37.1

**Comment by graywolf336** [comment]
@RocketChat/core I experienced this the other day as well. It will get through the process of changing it but then the error happens and now you've got messages with the new username yet when you send messages you've still got your old username.

**Comment by subesokun** [comment]
I'm currently in the process of migrating all self-registered users to LDAP in our Rocket.Chat instance but therefore a bunch of users needs to be renamed so this issue currently blocks the user migration :(

**Comment by LeDistordu** [comment]
0.38.0
+1

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/Rocket.Chat/pull/4122 in develop right now, will be available in version 0.39.0

**Comment by Patrick-Remy** [comment]
For me it's also present in version 0.64.2 for all users.

**Comment by indikatordesign** [comment]
Here too. Latest version.
