### ISSUE TITLE
Certain Char Combos ("req", "ri") Cause sendError Exception

### ISSUE THREAD

**Issue by curtisclark** [RocketChat/Rocket.Chat#3945]
I know this may seem crazy, but I've verified it's not just me. Every so often, a message wouldn't get sent to the room (it just remains grey and never turns to black). After a little bit, we noticed it only happened when certain character combinations were in our messages:
re (works), req (fails), ri (fails), rig (fails), ro (fails), rot (fails), row (works)

In the logs, whenever a message fails we see: 
```
Exception while invoking method 'sendMessage' MongoError: assertion src/mongo/db/storage/mmap_v1/btree/key.cpp:608     
	at Object.Future.wait (/home/pi/rocketchat/bundle/programs/server/node_modules/fibers/future.js:398:15)     
	at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)     
	at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:1)     
	at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:104:1)     
	at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)     
	at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)     
	at [object Object].Mongo.Collection.upsert (packages/mongo/collection.js:624:1)     
	at packages/matb33_collection-hooks/upsert.js:96:1     
	at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     
	at Object.directOp (packages/matb33_collection-hooks/collection-hooks.js:18:1)     - - - - -     
	at Object.toError (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)     
	at /home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:577:27     
	at /home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7     
	at /home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9     
	at Server.Base._callHandler (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)     
	at /home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18     
	at [object Object].MongoReply.parseBody (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)     
	at [object Object].<anonymous> (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)     
	at [object Object].emit (events.js:95:17)     
	at [object Object].<anonymous> (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
```

For the record, we're using 0.30.0 on a Rasberry Pi 2

**Comment by graywolf336** [comment]
@curtisclark Can you verify this is still happening with the latest version? As I just tried it locally, on windows, and it was working fine:

![image](https://cloud.githubusercontent.com/assets/850391/18066431/06794b4a-6dfe-11e6-9c68-4eab85996638.png)

**Comment by curtisclark** [comment]
We were able to fix it by stopping mongodb, running a repair and starting everything back up. So far the issue has not popped back up.

**Comment by graywolf336** [comment]
Ah okay, so seems to maybe have been a mongodb error as sending messages with those shouldn't cause any issues on our side due to it just being in a text field. If this happens again, feel free to open the issue with more details. :+1:
