### ISSUE TITLE
Error while starting Rocket.Chat

### ISSUE THREAD

**Issue by amraei** [RocketChat/Rocket.Chat#3994]
I have updated Rocket.Chat to latest version. When I run `node main.js` I get error:
```
</html>nter>nginx/1.10.1</center>/center>d>502] <html>
    at Object.Future.wait (/var/www/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)
```

Total output is:

```
node main.js
Updating process.env.MAIL_URL
ufs: store created at 
{"line":"114","file":"migrations.js","message":"Migrations: Not migrating, already at version 55","time":{"$date":1471075473254},"level":"info"}
Updating process.env.MAIL_URL
Using GridFS for Avatar storage
➔ System ➔ startup
➔ +------------------------------------------------+
➔ |                 SERVER RUNNING                 |
➔ +------------------------------------------------+
➔ |                                                |
➔ |       Version: 0.36.0                          |
➔ |  Process Port: 3000                            |
➔ |      Site URL: http://xxxxxxxxxxxx:3000/  |
➔ |                                                |
➔ +------------------------------------------------+
 </html>nter>nginx/1.10.1</center>/center>d>502] <html>
    at Object.Future.wait (/var/www/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)
    at Object.call (packages/meteor/helpers.js:119:1)
    at Object.HTTP.post (packages/http/httpcall_common.js:61:1)
    at generateStatistics (server/startup/cron.coffee:13:8)
    at server/startup/cron.coffee:19:3
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    - - - - -
    at makeErrorByStatus (packages/http/httpcall_common.js:16:1)
    at Request._callback (packages/http/httpcall_server.js:113:1)
    at Request.self.callback (/var/www/Rocket.Chat/programs/server/npm/http/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/var/www/Rocket.Chat/programs/server/npm/http/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/var/www/Rocket.Chat/programs/server/npm/http/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)

```

**Comment by ArchRoller** [comment]
Have same error on Nitrous:
`I20160814-17:47:23.165(0)? Exception in defer callback: Error: failed [502] <html>
I20160814-17:47:23.166(0)?  <head><title>502 Bad Gateway</title></head>
I20160814-17:47:23.166(0)?  <body bgcolor="white">
I20160814-17:47:23.166(0)?  <center><h1>502 Bad Gateway</h1></center>
I20160814-17:47:23.166(0)?  <hr><center>nginx/1.10.1</center>
I20160814-17:47:23.166(0)?  </body>
I20160814-17:47:23.166(0)?  </html>
I20160814-17:47:23.166(0)?
I20160814-17:47:23.166(0)?     at Object.Future.wait (/home/nitrous/.meteor/packages/meteor-tool/.1.1.10.w1ir08++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/de
v_bundle/server-lib/node_modules/fibers/future.js:398:15)`

**Comment by ArchRoller** [comment]
Workaround: change [this](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/startup/settings.coffee#L104) line to false.
