### ISSUE TITLE
Dokku deploy doesn't work

### ISSUE THREAD

**Issue by alexgleason** [RocketChat/Rocket.Chat#4104]
Dokku is an open-source Heroku clone that you can run on your own servers.

Pushing this repo to a Dokku server doesn't work. The default buildpack can't find the `meteor` binary (`npm run start` calls `meteor run` which fails since `meteor` can't be found).

[meteor-buildpack-horse](https://github.com/AdmitHub/meteor-buildpack-horse) fails on an error:

```
-----> Building Meteor app with ROOT_URL: http://chat.alexgleason.me/
remote: 
remote: /cache/1.2.1/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:259
remote:             throw new Error('Must throw non-empty error');
remote:                   ^
remote: Error: Must throw non-empty error
remote:     at Object.Future.throw (/cache/1.2.1/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:259:10)
remote:     at Extract.<anonymous> (/tools/fs/files.js:699:42)
remote:     at Extract.emit (events.js:117:20)
remote:     at DirWriter.<anonymous> (/cache/1.2.1/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/tar/lib/extract.js:61:8)
remote:     at DirWriter.emit (events.js:117:20)
remote:     at FileWriter.<anonymous> (/cache/1.2.1/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fstream/lib/dir-writer.js:158:12)
remote:     at FileWriter.emit (events.js:92:17)
remote:     at WriteStream.<anonymous> (/cache/1.2.1/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fstream/lib/file-writer.js:50:47)
remote:     at WriteStream.emit (events.js:95:17)
remote:     at WriteStream.<anonymous> (evalmachine.<anonymous>:1669:12)
remote:     at OpenReq.Req.done (/cache/1.2.1/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/graceful-fs/graceful-fs.js:141:5)
remote:     at OpenReq.done (/cache/1.2.1/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/graceful-fs/graceful-fs.js:61:22)
remote:     at Object.oncomplete (evalmachine.<anonymous>:108:15)
To dokku@alexgleason.me:chat.alexgleason.me
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@alexgleason.me:chat.alexgleason.me'
```

[heroku-buildpack-meteor](https://github.com/jordansissel/heroku-buildpack-meteor) fails in a very similar place.

```
-----> Building Meteor App Bundle

       /tmp/build/.meteor_tool/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
       throw(ex);
       ^
       Error: ENOTDIR, readdir '/app/.meteor/packages'
       at Object.Future.wait (/tmp/build/.meteor_tool/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
       at /tools/fs/files.js:1331:28
       at Object.wrapper (/tools/fs/files.js:1334:20)
       at [object Object]._.extend.wipeAllPackages (/tools/packaging/tropohouse.js:178:31)
       at [object Object]._.extend.refresh (/tools/packaging/catalog/catalog-remote.js:790:26)
       at Object.catalog.refreshOrWarn (/tools/packaging/catalog/catalog.js:48:22)
       at /tools/cli/main.js:918:19
       at [object Object]._.extend.withProgressDisplayVisible (/tools/console/console.js:611:14)
       at /tools/cli/main.js:917:17
       - - - - -

       /tmp/build/.meteor_tool/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
       throw(ex);
       ^
       Error: ENOTDIR, readlink '/app/.meteor/packages/accounts-base/1.2.2'
       at Object.Future.wait (/tmp/build/.meteor_tool/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
       at /tools/utils/buildmessage.js:576:31
       at Array.forEach (native)
       at Function._.each._.forEach (/tmp/build/.meteor_tool/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
       at /tools/utils/buildmessage.js:574:9
       at /tools/utils/buildmessage.js:356:18
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:349:34
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:347:23
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at enterJob (/tools/utils/buildmessage.js:321:26)
       at Object.forkJoin (/tools/utils/buildmessage.js:552:3)
       at [object Object]._.extend.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:584:18)
       at /tools/project-context.js:702:25
       at /tools/utils/buildmessage.js:356:18
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:349:34
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:347:23
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at Object.enterJob (/tools/utils/buildmessage.js:321:26)
       at /tools/project-context.js:701:20
       at /tools/packaging/catalog/catalog.js:100:5
       at /tools/utils/buildmessage.js:268:13
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:261:29
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:259:18
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:250:23
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at Object.capture (/tools/utils/buildmessage.js:249:19)
       at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
       at ProjectContext._.extend._downloadMissingPackages (/tools/project-context.js:700:13)
       at /tools/project-context.js:257:35
       at /tools/utils/buildmessage.js:356:18
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:349:34
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:347:23
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at Object.enterJob (/tools/utils/buildmessage.js:321:26)
       at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
       at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
       at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
       at /tools/cli/commands.js:838:20
       at /tools/utils/buildmessage.js:268:13
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:261:29
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:259:18
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:250:23
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at Object.capture (/tools/utils/buildmessage.js:249:19)
       at Object.main.captureAndExit (/tools/cli/main.js:270:29)
       at buildCommand (/tools/cli/commands.js:837:8)
       at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:791:12)
       at /tools/cli/main.js:1378:23
       - - - - -
       at Object.Future.wait (/tmp/build/.meteor_tool/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
       at /tools/fs/files.js:1331:28
       at Object.wrapper [as readlink] (/tools/fs/files.js:1334:20)
       at /tools/packaging/tropohouse.js:455:39
       at /tools/utils/buildmessage.js:356:18
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:349:34
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:347:23
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at Object.enterJob (/tools/utils/buildmessage.js:321:26)
       at Object.download (/tools/packaging/tropohouse.js:437:20)
       at /tools/packaging/tropohouse.js:588:18
       at /tools/utils/buildmessage.js:558:23
       at /tools/utils/buildmessage.js:356:18
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:349:34
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at /tools/utils/buildmessage.js:347:23
       at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
       at enterJob (/tools/utils/buildmessage.js:321:26)
       at /tools/utils/buildmessage.js:557:24
       at runWithEnvironment (/tools/utils/fiber-helpers.js:137:21)
       at /tools/utils/fiber-helpers.js:144:14
       at /tools/utils/buildmessage.js:569:11
       - - - - -

-----> Installing App's NPM Dependencies
remote: /tmp/buildpacks/custom/bin/compile_meteor: line 66: cd: ../build/bundle/programs/server: No such file or directory
To dokku@alexgleason.me:chat.alexgleason.me
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@alexgleason.me:chat.alexgleason.me'
```

My server has 1GB of RAM and 20GB of disk space. It's mostly unused aside from one small static site.

**Comment by engelgabriel** [comment]
He have update the buildpack, but now we need this PR also finished https://github.com/RocketChat/Rocket.Chat/pull/5371

**Comment by engelgabriel** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/5371
