### ISSUE TITLE
ModelsBase.update throws error when using array update operators

### ISSUE THREAD

**Issue by KirbySSmith** [RocketChat/Rocket.Chat#4121]
Rocket.Chat version: 0.37.1

ModelsBase.update throws error when using array update operators. This causes RocketChat.models.Users.setEmailVerified to fail and is preventing users from logging in with OAuth when the email is in service data.

Error:
```
Exception while invoking method 'login' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: emails.$.verified
     at Object.Future.wait (C:\Users\_\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:398:15)
     at [object Object]._.extend.wrapAsync (packages/meteor/helpers.js:119:1)
     at [object Object]._.each.MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:1)
     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:80:1)
     at Object.CollectionHooks.extendCollectionInstance._.each.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
     at [object Object]._.each.Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
     at [object Object]._.each.Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)
     at _Class.update (server/models/_Base.js:78:29)
     at _Class.RocketChat.models.Users._Class.setEmailVerified (packages/rocketchat_lib/server/models/Users.coffee:331:11)
     at AccountsServer.Accounts.updateOrCreateUserFromExternalService (server/configuration/accounts_meld.coffee:33:28)
```
Cause:
ModelsBase.update is replacing the original query with one using ids. 

packages/rocketchat-lib/server/models/_Base.js:77
```
		query = { _id: { $in: _.pluck(ids, '_id') } };
		const result = this.model.update(query, update, options);
```
As per the MongoDb docs for [array update operators: $](https://docs.mongodb.com/manual/reference/operator/update/positional/#up._S_)
> the array field must appear as part of the query document.

**Comment by dupree972** [comment]
Rocket.Chat version .38
How come it is not possible to attach a source code file .c from a Mac into rocket chat? I added text/x-c and have text/plain as a mime type.. is there a different media type it expects?
