### ISSUE TITLE
Problem connecting rocketchat to smtp (postfix) hosted on the same LAN server 

### ISSUE THREAD

**Issue by pgtgrly** [RocketChat/Rocket.Chat#4188]
Your Rocket.Chat version: [latest version as on Sept 4 2016] 
I have been testing out rocketchat with Docker (compose 1.8.0) on the LAN.I set it up along with a mailserver on the same server machine(ubuntu 14.04 server).The SMTP is send only and is working fine and I am able to send mails. Here is the yml file part hat needed to be tweaked:

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://chat.pgsrocketchat.com
    - MAIL_URL=smtp://noreply@pgsrocketchat.com:samplepass@smtp.pgsrocketchat.com:465/
    - Accounts_UseDNSDomainCheck=True

here is the error log:

Exception while invoking method 'sendSMTPTestEmail' Error: connect ECONNREFUSED
    at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at smtpSend (packages/email/email.js:86:1)
    at Object.Email.send (packages/email/email.js:185:1)
    at [object Object].Meteor.methods.sendSMTPTestEmail (packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:15:9)
    at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:17:26)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    - - - - -
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete](net.js:896:19)

Attached here is the configuration that I am using (I also tried changing the hostname with my system IP but there was no effect)
![screen shot 2016-09-03 at 11 39 38 pm](https://cloud.githubusercontent.com/assets/17721748/18226833/e7a1f934-722f-11e6-8000-98d5fb2442e4.png)

It will be great if someone can help me out with this.

**Comment by jszaszvari** [comment]
Your getting a connection refused by your mail server that's what the
ECONNREFUSED
is about.

You need to look into the logs of that mail server to see why it's refusing
the mail .

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
