### ISSUE TITLE
Provide clear log and error messages for SMTP connections failures

### ISSUE THREAD

**Issue by markshuttle** [RocketChat/Rocket.Chat#4215]
Your Rocket.Chat version: snap (stable channel, so you ensure I am are running the latest ;))

Hi, love the snap install and am wanting to integrate it further into our setup. We have an SMTP server but it requires STARTTLS on the connection. I am unable to send welcome emails, and THINK this is the issue.

**Comment by engelgabriel** [comment]
Thanks @markshuttle we will investigate that. Do you know that you have to restart the server when you change the SMTP settings? It is a limitation of Meteor that we have already submitted a PR to fix and will be merge back into our app next week.

**Comment by markshuttle** [comment]
Didn't know to restart, thanks, but I still see these:

I20160907-01:46:23.287(0) Exception while invoking method 'sendSMTPTestEmail' Error: connect ETIMEDOUT     at Object.Future.wait (/snap/rocketchat-server/5/node_modules/fibers/future.js:449:15)     at smtpSend (meteor://💻app/packages/email/email.js:86:1)     at Object.Email.send (meteor://💻app/packages/email/email.js:185:1)     at [object Object].Meteor.methods.sendSMTPTestEmail (meteor://💻app/packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:15:9)     at [object Object].methodsMap.(anonymous function) (meteor://💻app/server/lib/debug.js:17:26)     at maybeAuditArgumentChecks (meteor://💻app/livedata_server.js:1698:12)     at meteor://💻app/livedata_server.js:708:19     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)     at meteor://💻app/livedata_server.js:706:40     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)     - - - - -     at errnoException (net.js:905:11)     at Object.afterConnect [as oncomplete] (net.js:896:19) 
I20160907-01:46:24.952(0) Exception while invoking method 'sendSMTPTestEmail' Error: connect ETIMEDOUT     at Object.Future.wait (/snap/rocketchat-server/5/node_modules/fibers/future.js:449:15)     at smtpSend (meteor://💻app/packages/email/email.js:86:1)     at Object.Email.send (meteor://💻app/packages/email/email.js:185:1)     at [object Object].Meteor.methods.sendSMTPTestEmail (meteor://💻app/packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:15:9)     at [object Object].methodsMap.(anonymous function) (meteor://💻app/server/lib/debug.js:17:26)     at maybeAuditArgumentChecks (meteor://💻app/livedata_server.js:1698:12)     at meteor://💻app/livedata_server.js:708:19     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)     at meteor://💻app/livedata_server.js:706:40     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)     - - - - -     at errnoException (net.js:905:11)     at Object.afterConnect [as oncomplete] (net.js:896:19)

**Comment by engelgabriel** [comment]
```
I20160907-01:46:23.287(0) Exception while invoking method 'sendSMTPTestEmail' Error: connect ETIMEDOUT
  at Object.Future.wait (/snap/rocketchat-server/5/node_modules/fibers/future.js:449:15)
  at smtpSend (meteor://app/packages/email/email.js:86:1)
  at Object.Email.send (meteor://app/packages/email/email.js:185:1)
  at [object Object].Meteor.methods.sendSMTPTestEmail (meteor://app/packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:15:9)
  at [object Object].methodsMap.(anonymous function) (meteor://app/server/lib/debug.js:17:26)
  at maybeAuditArgumentChecks (meteor://app/livedata_server.js:1698:12)
  at meteor://app/livedata_server.js:708:19
  at [object Object]._.extend.withValue (meteor://app/packages/meteor/dynamics_nodejs.js:56:1)
  at meteor://app/livedata_server.js:706:40
  at [object Object]._.extend.withValue (meteor://app/packages/meteor/dynamics_nodejs.js:56:1)
  - - - - -
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19) 
I20160907-01:46:24.952(0) Exception while invoking method 'sendSMTPTestEmail' Error: connect ETIMEDOUT
  at Object.Future.wait (/snap/rocketchat-server/5/node_modules/fibers/future.js:449:15)
  at smtpSend (meteor://app/packages/email/email.js:86:1)
  at Object.Email.send (meteor://app/packages/email/email.js:185:1)
  at [object Object].Meteor.methods.sendSMTPTestEmail (meteor://app/packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:15:9)
  at [object Object].methodsMap.(anonymous function) (meteor://app/server/lib/debug.js:17:26)
  at maybeAuditArgumentChecks (meteor://app/livedata_server.js:1698:12)
  at meteor://app/livedata_server.js:708:19
  at [object Object]._.extend.withValue (meteor://app/packages/meteor/dynamics_nodejs.js:56:1)
  at meteor://app/livedata_server.js:706:40
  at [object Object]._.extend.withValue (meteor://app/packages/meteor/dynamics_nodejs.js:56:1)
  - - - - -
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19) 
```

**Comment by markshuttle** [comment]
The issue in my case turned out to be that the SMTP ports were blocked
for Google cloud generally. Switching to a random high port enabled
traffic to flow. Thanks for the debugging and sorry for the noise! It
might however be worth addressing this by providing a clear log message
in these circumstances, I couldn't see anything in the logs suggesting
that the connection was being blocked.

Mark

**Comment by engelgabriel** [comment]
@RocketChat/core let's provide clear log and error messages for SMTP connections failures
