### ISSUE TITLE
HipChat Import Failed

### ISSUE THREAD

**Issue by domberd** [RocketChat/Rocket.Chat#4234]
Your Rocket.Chat version: 0.37.1

While importing HipChat data the following error occurs:

Exception while invoking method 'prepareImport' ReferenceError: tempChannels is not defined     at HipChat.Importer.HipChat.Importer.HipChat.HipChat.prepare (packages/rocketchat_importer-hipchat/server.coffee:89:84)     at HipChat.<anonymous> (packages/rocketchat_importer-hipchat/server.coffee:1:1)     at HipChat.prepare (packages/rocketchat_importer/server/classes/ImporterBase.coffee:14:1)     at [object Object].Meteor.methods.prepareImport (packages/rocketchat_importer/server/methods/prepareImport.coffee:7:46)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:17:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:706:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)

**Comment by kajisaap** [comment]
We are also observing similar. The import type is also not clear. We exported data from hipchat free version.

We are at RC version 0.42 

````bash
Chat import: __MACOSX/hipchat_export/users/._list.json 
[34mI20161019-11:18:08.208(0) Exception while invoking method 'prepareImport' ReferenceError: tempChannels is not defined     at HipChat.Importer.HipChat.Importer.HipChat.HipChat.prepare (meteor://💻app/packages/rocketchat_importer-hipchat/server.coffee:89:84)     at HipChat.<anonymous> (meteor://💻app/packages/rocketchat_importer-hipchat/server.coffee:1:1)     at HipChat.prepare (meteor://💻app/packages/rocketchat_importer/lib/importTool.coffee:3:24)     at [object Object].Meteor.methods.prepareImport (meteor://💻app/packages/rocketchat_importer/server/methods/prepareImport.coffee:7:46)     at [object Object].methodsMap.(anonymous function) (meteor://💻app/packages/rocketchat:lib/server/lib/debug.js:17:26)     at maybeAuditArgumentChecks (meteor://💻app/packages/ddp-server/livedata_server.js:1711:12)     at meteor://💻app/packages/ddp-server/livedata_server.js:711:19     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)     at meteor://💻app/packages/ddp-server/livedata_server.js:709:40     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)     at meteor://💻app/packages/ddp-server/livedata_server.js:707:46     at Session.method (meteor://💻app/packages/ddp-server/livedata_server.js:681:23)     at meteor://💻app/packages/ddp-server/livedata_server.js:551:43 
[34mI20161019-11:18:57.740(0) [35mHipChat Importer ➔ warn Duplicated instance 
[34mI20161019-11:19:05.164(0) [35mHipChat Importer ➔ warn Unexpected file in the HipChat import: __MACOSX/hipchat_export/users/._list.json 
[34mI20161019-11:19:06.815(0) Exception while invoking method 'prepareImport' ReferenceError: tempChannels is not defined     at HipChat.Importer.HipChat.Importer.HipChat.HipChat.prepare (meteor://💻app/packages/rocketchat_importer-hipchat/server.coffee:89:84)     at HipChat.<anonymous> (meteor://💻app/packages/rocketchat_importer-hipchat/server.coffee:1:1)     at HipChat.prepare (meteor://💻app/packages/rocketchat_importer/lib/importTool.coffee:3:24)     at [object Object].Meteor.methods.prepareImport (meteor://💻app/packages/rocketchat_importer/server/methods/prepareImport.coffee:7:46)     at [object Object].methodsMap.(anonymous function) (meteor://💻app/packages/rocketchat:lib/server/lib/debug.js:17:26)     at maybeAuditArgumentChecks (meteor://💻app/packages/ddp-server/livedata_server.js:1711:12)     at meteor://💻app/packages/ddp-server/livedata_server.js:711:19     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)     at meteor://💻app/packages/ddp-server/livedata_server.js:709:40     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)     at meteor://💻app/packages/ddp-server/livedata_server.js:707:46     at Session.method (meteor://💻app/packages/ddp-server/livedata_server.js:681:23)     at meteor://💻app/packages/ddp-server/livedata_server.js:551:43 
[34mI20161019-11:21:00.899(0) [35mHipChat Importer ➔ warn Duplicated instance 
[34mI20161019-11:21:06.669(0) [35mHipChat Importer ➔ warn Unexpected file in the HipChat import: __MACOSX/hipchat_export/users/._list.json 
[34mI20161019-11:21:17.712(0) Exception while invoking method 'prepareImport' ReferenceError: tempChannels is not defined     at HipChat.Importer.HipChat.Importer.HipChat.HipChat.prepare (meteor://💻app/packages/rocketchat_importer-hipchat/server.coffee:89:84)     at HipChat.<anonymous> (meteor://💻app/packages/rocketchat_importer-hipchat/server.coffee:1:1)     at HipChat.prepare (meteor://💻app/packages/rocketchat_importer/lib/importTool.coffee:3:24)     at [object Object].Meteor.methods.prepareImport (meteor://💻app/packages/rocketchat_importer/server/methods/prepareImport.coffee:7:46)     at [object Object].methodsMap.(anonymous function) (meteor://💻app/packages/rocketchat:lib/server/lib/debug.js:17:26)     at maybeAuditArgumentChecks (meteor://💻app/packages/ddp-server/livedata_server.js:1711:12)     at meteor://💻app/packages/ddp-server/livedata_server.js:711:19     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)     at meteor://💻app/packages/ddp-server/livedata_server.js:709:40     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)     at meteor://💻app/packages/ddp-server/livedata_server.js:707:46     at Session.method (meteor://💻app/packages/ddp-server/livedata_server.js:681:23)     at meteor://💻app/packages/ddp-server/livedata_server.js:551:43 

````

**Comment by geekgonecrazy** [comment]
This one hasn't received any posts for a while. Going to go ahead and close this.  

Feel free to move discussion to [forum](https://forums.rocket.chat) in the community support category
