### ISSUE TITLE
update to version 0.40.0 problem

### ISSUE THREAD

**Issue by OnlineBoy** [RocketChat/Rocket.Chat#4375]
Your Rocket.Chat version: 0.40.0
when i use commend 
______________________
node main.js

it dosnt start and shows this error 
__________________________________
```
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/home/online/Rocket.Chat/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/home/online/Rocket.Chat/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/online/Rocket.Chat/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)
```

Help me Plz!

**Comment by OnlineBoy** [comment]
oh sorry 
i didnt see that new thread in wikis
From 0.x.x to 0.40.0

but wen i use 

n install 4.5

it says

     install : node-vinstall

  Error: invalid version install

**Comment by OnlineBoy** [comment]
well
correct commend is

n 4.5

not n install 4.5
