### ISSUE TITLE
Error when Importing Slack History

### ISSUE THREAD

**Issue by viper8690** [RocketChat/Rocket.Chat#4388]
Your Rocket.Chat version: 0.40.0

I am running a dockerized rocket chat on CentOS 7 and I get the following error when trying to import from Slack:

`Exception while invoking method 'prepareImport' TypeError: Cannot read property 'calculateObjectSize' of undefined
    at Function.Importer.Base.Importer.Base.Base.getBSONSize (packages/rocketchat_importer/lib/importTool.coffee:3:24)
    at packages/rocketchat_importer-slack/server.coffee:70:23
    at Slack.Importer.Slack.Importer.Slack.Slack.prepare (packages/rocketchat_importer-slack/server.coffee:62:3)
    at Slack.<anonymous> (packages/rocketchat_importer-slack/server.coffee:1:1)
    at Slack.prepare (packages/rocketchat_importer/lib/importTool.coffee:3:24)
    at [object Object].Meteor.methods.prepareImport (packages/rocketchat_importer/server/methods/prepareImport.coffee:7:46)
    at [object Object].methodsMap.(anonymous function) (packages/rocketchat:lib/server/lib/debug.js:17:26)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:707:46
    at Session.method (packages/ddp-server/livedata_server.js:681:23)
    at packages/ddp-server/livedata_server.js:551:43
`

I have the CentOS instance configured to HTTP behind a load balancer which is configured as an SSL which directs to the CentOS instance.

Is the CentOS instance which is running the app required to be SSL as well? I have successfully imported to an Ubuntu instance before and that was configured as SSL.

Thanks,

**Comment by figureone** [comment]
Same error over here, with a similar setup. Deployed via Ubuntu snap onto a 16.04.1 machine configured to HTTP, behind a HTTPS load balancer (nginx on Ubuntu 14.04). Fails when importing a hipchat export. Let me know if I can provide more data to help debug!

**Comment by TAdeJong** [comment]
Affects us too for a slack import on Ubuntu 16.04.1 in a native node deployment behind a reverse proxy.
