### ISSUE TITLE
Crash with "SSL3_GET_RECORD:wrong version number" error.

### ISSUE THREAD

**Issue by vstaf** [RocketChat/Rocket.Chat#4412]
Hi all!
After updating our rocket.chat from 0.39 to the latest 0.40.1 version and updating node js from 0.10.40 to 4.5 we got chat server process crash periodically with error:

2016-09-22 18:36:54 252: Error: 139654647129984:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:../deps/openssl/openssl/ssl/s3_pkt.c:362:

We use SSL and nginx config from documentation.

**Comment by engelgabriel** [comment]
Is this when you try to send emails?

http://www.devmedia.com.br/forum/enviar-email-retorna-o-erro-error-connecting-with-ssl-error-connecting-with-ssl-error-1408f10b-ssl-routines-ssl3getrecord-wrong-version-number/401303

**Comment by engelgabriel** [comment]
Can you share the full stack of the error?

**Comment by vstaf** [comment]
Crash appear when i send message to General chat. Sending messages to multimple private chat is ok.
Here is app-0.log fragment:

2016-09-22 19:04:47 740: Updating process.env.MAIL_URL
2016-09-22 19:04:47 777: .[32mUsing GridFS for custom emoji storage.[39m
2016-09-22 19:04:47 917: .[32mUsing FileSystem for Avatar storage.[39m
2016-09-22 19:04:48 232: .[32m➔.[39m .[32mSystem ➔ startup.[39m
2016-09-22 19:04:48 233: .[32m➔.[39m .[32m+-------------------------------------------+.[39m
2016-09-22 19:04:48 233: .[32m➔.[39m .[32m|               SERVER RUNNING              |.[39m
2016-09-22 19:04:48 233: .[32m➔.[39m .[32m+-------------------------------------------+.[39m
2016-09-22 19:04:48 233: .[32m➔.[39m .[32m|                                           |.[39m
2016-09-22 19:04:48 233: .[32m➔.[39m .[32m|       Version: 0.40.1                     |.[39m
2016-09-22 19:04:48 233: .[32m➔.[39m .[32m|  Process Port: 3000                       |.[39m
2016-09-22 19:04:48 233: .[32m➔.[39m .[32m|      Site URL: https://xxxx.xxxxxxxx.xxxx  |.[39m
2016-09-22 19:04:48 234: .[32m➔.[39m .[32m|                                           |.[39m
2016-09-22 19:04:48 234: .[32m➔.[39m .[32m+-------------------------------------------+.[39m
2016-09-22 19:05:43 334: Exception in defer callback: AuthError: Invalid login - 535 Incorrect authentication data
    at Object.Future.wait (/var/www/rocket.chat/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at smtpSend (packages/email/email.js:89:1)
    at Object.Email.send (packages/email/email.js:192:1)
    at packages/rocketchat:lib/server/lib/sendEmailOnMessage.js:120:14
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    - - - - -
    at SMTPClient._actionAUTHComplete (/var/www/rocket.chat/bundle/programs/server/npm/node_modules/meteor/email/node_modules/simplesmtp/lib/client.js:925:23)
    at SMTPClient._onData (/var/www/rocket.chat/bundle/programs/server/npm/node_modules/meteor/email/node_modules/simplesmtp/lib/client.js:354:29)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:536:20)
2016-09-22 19:05:46 157: Updating process.env.MAIL_URL
2016-09-22 19:05:47 177: ufs: store created at
2016-09-22 19:05:50 380: {"line":"114","file":"migrations.js","message":"Migrations: Not migrating, already at version 61","time":{"$date":1474560350377},"level":"info"}
2016-09-22 19:05:51 235: Updating process.env.MAIL_URL
2016-09-22 19:05:51 322: .[32mUsing GridFS for custom emoji storage.[39m
2016-09-22 19:05:51 491: .[32mUsing FileSystem for Avatar storage.[39m
2016-09-22 19:05:51 934: .[32m➔.[39m .[32mSystem ➔ startup.[39m
2016-09-22 19:05:51 935: .[32m➔.[39m .[32m+-------------------------------------------+.[39m
2016-09-22 19:05:51 935: .[32m➔.[39m .[32m|               SERVER RUNNING              |.[39m
2016-09-22 19:05:51 935: .[32m➔.[39m .[32m+-------------------------------------------+.[39m
2016-09-22 19:05:51 935: .[32m➔.[39m .[32m|                                           |.[39m
2016-09-22 19:05:51 936: .[32m➔.[39m .[32m|       Version: 0.40.1                     |.[39m
2016-09-22 19:05:51 936: .[32m➔.[39m .[32m|  Process Port: 3000                       |.[39m
2016-09-22 19:05:51 936: .[32m➔.[39m .[32m|      Site URL: https://xxx.xxxxxxx.xxx  |.[39m
2016-09-22 19:05:51 937: .[32m➔.[39m .[32m|                                           |.[39m
2016-09-22 19:05:51 937: .[32m➔.[39m .[32m+-------------------------------------------+.[39m


We don't sending any emails from rocket.chat. Email section doesn't configured.

**Comment by engelgabriel** [comment]
Someone in your GENERAL channel has email alerts turned on, and your email server setting is incorrect.

**Comment by engelgabriel** [comment]
The PR https://github.com/RocketChat/Rocket.Chat/pull/4416 will prevent the server from crashing.

**Comment by vstaf** [comment]
Thanks @engelgabriel !

**Comment by sscholl** [comment]
this issue was closed via #6940 in 0.56.0 FOR ME

Go to Administation->E-Mail->SMTP->Protocol (smtps)
