### ISSUE TITLE
Another crash after updating to 0.40.1

### ISSUE THREAD

**Issue by vstaf** [RocketChat/Rocket.Chat#4425]
Hi all!
We got another crash after updating 0.40.1 this morning. Here is the logs:
app.log
```
2016-09-23 10:15:43 200: Exception in callback of async function: Error: Future resolved more than once
    at Object.Future.return (/var/www/rocket.chat/bundle/programs/server/node_modules/fibers/future.js:261:10)
    at Object.<anonymous> (/var/www/rocket.chat/bundle/programs/server/node_modules/fibers/future.js:349:16)
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    at packages/meteor/dynamics_nodejs.js:123:1
    at packages/rocketchat_oembed/server/server.coffee:70:3
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```
error.log
```
2016-09-23 10:25:07 815: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)

```

**Comment by pokab** [comment]
We may have the same problem. It's crashing at least every few hours with the same error as in your error.log, only on standard output:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)```

**Comment by MartinSchoeler** [comment]
@vstaf could you give us more info about your setup? Thanks!

**Comment by vstaf** [comment]
Sure, what info do you need?

node v4.5.0
ubuntu (jessie/sid) x64, 3.19.0-25-generic
running rocket.chat with nginx + ssl
rocket.chat version 0.40.1

**Comment by engelgabriel** [comment]
@vstaf adn @pokab 
Do you have SMTP configured?
Can you confirm if the error occurs when you share a URL with HTTPS?
Is so, can you send us the example?

**Comment by vstaf** [comment]
Yes, i configured SMTP after my previously issue (https://github.com/RocketChat/Rocket.Chat/issues/4412).  
"SSL3_GET_RECORD:wrong version number" errors gone, but new error with crashes appear.
About urls with https: no, i can't confirm that, trying to send verious https links to chat without crashes.

**Comment by engelgabriel** [comment]
@vstaf can you try using the `develop` version?

**Comment by vstaf** [comment]
yes, migrated to develop version

```
2016-09-23 17:16:07 928: {"line":"114","file":"migrations.js","message":"Migrations: Migrating from version 61 -> 62","time":{"$date":1474640167927},"level":"info"}
2016-09-23 17:16:07 930: {"line":"114","file":"migrations.js","message":"Migrations: Running up() on version 62","time":{"$date":1474640167930},"level":"info"}
2016-09-23 17:16:07 954: {"line":"114","file":"migrations.js","message":"Migrations: Finished migrating.","time":{"$date":1474640167954},"level":"info"}
2016-09-23 17:16:17 955: .[33mNot migrating, control is locked. Attempt 1/30. Trying again in 10 seconds..[39m
2016-09-23 17:16:17 963: {"line":"114","file":"migrations.js","message":"Migrations: Not migrating, already at version 62","time":{"$date":1474640177962},"level":"info"}
2016-09-23 17:16:18 148: .[32mUsing GridFS for custom emoji storage.[39m
2016-09-23 17:16:18 531: Updating process.env.MAIL_URL
2016-09-23 17:16:18 642: .[32mUsing FileSystem for Avatar storage.[39m
2016-09-23 17:16:19 044: .[32m➔.[39m .[32mSystem ➔ startup.[39m
2016-09-23 17:16:19 044: .[32m➔.[39m .[32m+-------------------------------------------+.[39m
2016-09-23 17:16:19 044: .[32m➔.[39m .[32m|               SERVER RUNNING              |.[39m
2016-09-23 17:16:19 045: .[32m➔.[39m .[32m+-------------------------------------------+.[39m
2016-09-23 17:16:19 045: .[32m➔.[39m .[32m|                                           |.[39m
2016-09-23 17:16:19 045: .[32m➔.[39m .[32m|       Version: 0.40.1                     |.[39m
2016-09-23 17:16:19 045: .[32m➔.[39m .[32m|  Process Port: 3000                       |.[39m
2016-09-23 17:16:19 045: .[32m➔.[39m .[32m|      Site URL: https://xxxx
```  |.[39m
2016-09-23 17:16:19 046: .[32m➔.[39m .[32m|                                           |.[39m
2016-09-23 17:16:19 046: .[32m➔.[39m .[32m+-------------------------------------------+.[39m

**Comment by vstaf** [comment]
there are some error in app.log, may be it's important:

```
2016-09-23 17:18:49 974: Exception in defer callback: SyntaxError: Unexpected end of input
    at Object.parse (native)
    at packages/rocketchat_oembed/server/providers.coffee:74:19
    at packages/rocketchat_lib/lib/callbacks.coffee:73:21
    at Array.reduce (native)
    at Object.RocketChat.callbacks.run (packages/rocketchat_lib/lib/callbacks.coffee:68:103)
    at Object.OEmbed.getUrlMeta (packages/rocketchat_oembed/server/server.coffee:135:30)
    at Object.OEmbed.getUrlMetaWithCache (packages/rocketchat_oembed/server/server.coffee:148:16)
    at packages/rocketchat_oembed/server/server.coffee:195:18
    at Array.forEach (native)
    at OEmbed.RocketUrlParser (packages/rocketchat_oembed/server/server.coffee:184:16)
    at packages/rocketchat_lib/lib/callbacks.coffee:73:21
    at Array.reduce (native)
    at Object.RocketChat.callbacks.run (packages/rocketchat_lib/lib/callbacks.coffee:68:103)
    at packages/rocketchat_lib/server/functions/sendMessage.coffee:41:24
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)

```

**Comment by engelgabriel** [comment]
Can you see what URL was shared?

**Comment by vstaf** [comment]
i'm very sorry, but where i can see that? we don't save message history and have >200 private chats. don't know that message cause the crash

**Comment by rodrigok** [comment]
@vstaf Are you using LDAP with TLS enabled?

**Comment by vstaf** [comment]
nope

**Comment by engelgabriel** [comment]
@rodrigok I think the problem happens when trying to parse the JSON body of an URL to try to generate the oembed preview. Can we wrap it on a TRY/CATCH and add some debug log?

**Comment by vstaf** [comment]
I can add debug log if you tell me fragment of code and what file i need to modify :)

**Comment by pokab** [comment]
@engelgabriel Yes SMTP works as it should.
It seems you are right, the server crash is usually when someone posts a link.
I have installed 0.41.0, so far no crash.

**Comment by engelgabriel** [comment]
@vstaf please reopen this issue if the problem still happens on version 0.41.0

**Comment by vstaf** [comment]
I use latest develop version (63) and stil got crashes.
2016-09-30 08:48:13 934: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)
2016-09-30 09:36:07 678: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)
2016-09-30 09:57:25 616: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)
2016-09-30 10:58:09 639: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)
2016-09-30 11:27:12 908: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)
2016-09-30 11:38:22 001: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)
2016-09-30 11:55:22 217: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)
2016-09-30 13:15:22 623: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)
2016-09-30 14:07:05 595: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)
2016-09-30 15:05:10 039: Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)
