### ISSUE TITLE
i can't run node.js

### ISSUE THREAD

**Issue by boulakar** [RocketChat/Rocket.Chat#4448]
Hi i use Ubuntu of AWS 
I followed these steps
https://www.digitalocean.com/community/tutorials/how-to-install-configure-and-deploy-rocket-chat-on-ubuntu-14-04
but i can't run node main.js i have this error
-----------------------------
ubuntu@ip-10-0-1-68:~/Rocket.Chat$ node main.js

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/home/ubuntu/Rocket.Chat/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/home/ubuntu/Rocket.Chat/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/Rocket.Chat/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)
ubuntu@ip-10-0-1-68:~/Rocket.Chat$

**Comment by rauhmaru** [comment]
Hi, try this:

`n 4.5`

If don't work, try:
```
# cat /usr/lib/systemd/system/rocketchat.service
[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target
[Service]
ExecStart=/usr/local/bin/node /var/www/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=root
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=http://shenlong.solutis.net.br:3000/ PORT=3000
[Install]
WantedBy=multi-user.target
```

Look this line:
`ExecStart=/usr/local/bin/node /var/www/Rocket.Chat/main.js`
Check binary which the line is pointing.

**Comment by engelgabriel** [comment]
Yes, please make sure you are now using the version 4.5.0 of NodeJS. I've already asked DigitalOcean to update the tutorial.

**Comment by boulakar** [comment]
Hi i update NodeJs to 4.5.0 but not working 

ubuntu@ip-10-0-1-57:~/Rocket.Chat$ nodejs --version
v4.5.0
ubuntu@ip-10-0-1-57:~/Rocket.Chat$ node main.js

/home/ubuntu/Rocket.Chat/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Object.Future.wait (/home/ubuntu/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:216:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    - - - - -
    at [object Object].<anonymous> (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
ubuntu@ip-10-0-1-57:~/Rocket.Chat$

**Comment by B2RN** [comment]
This hasn't been solved. Just ran a clean install on a CentOS 7.2 minimal install:

```
[root@rocket-srv1 Rocket.Chat]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
```

```
[root@rocket-srv1 Rocket.Chat]# which node
/bin/node
[root@rocket-srv1 Rocket.Chat]# node -v
v4.5.0
[root@rocket-srv1 Rocket.Chat]# 
```

```
[root@rocket-srv1 Rocket.Chat]# systemctl status mongod
● mongod.service - SYSV: Mongo is a scalable, document-oriented database.
   Loaded: loaded (/etc/rc.d/init.d/mongod)
   Active: active (running) since Thu 2016-10-13 14:03:21 CEST; 4min 47s ago
     Docs: man:systemd-sysv-generator(8)
 Main PID: 8191 (mongod)
   CGroup: /system.slice/mongod.service
           └─8191 /usr/bin/mongod -f /etc/mongod.conf

Oct 13 14:03:20 rocket-srv1.mpi-cbg.de systemd[1]: Starting SYSV: Mongo is a scalable, document-oriented database....
Oct 13 14:03:20 rocket-srv1.mpi-cbg.de runuser[8187]: pam_unix(runuser:session): session opened for user mongod...d=0)
Oct 13 14:03:21 rocket-srv1.mpi-cbg.de mongod[8178]: Starting mongod: [  OK  ]
Oct 13 14:03:21 rocket-srv1.mpi-cbg.de systemd[1]: Started SYSV: Mongo is a scalable, document-oriented database..
Hint: Some lines were ellipsized, use -l to show in full.
[root@rocket-srv1 Rocket.Chat]# 
```

```
[root@rocket-srv1 Rocket.Chat]# node main.js

/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:216:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    - - - - -
    at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mo
ngodb-core/lib/topologies/server.js:313:35)                                                                          
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mo
ngodb-core/lib/connection/pool.js:260:12)                                                                            
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-cor
e/lib/connection/connection.js:162:49)                                                                               
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
[root@rocket-srv1 Rocket.Chat]# 
```

Can provide more logs and so on, but first I'd suggest opening the issue again.
