### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by mikrobyte** [RocketChat/Rocket.Chat#4476]
Your Rocket.Chat version: (make sure you are running the latest)
upgrading process from 0.39.0 to 0.41.0

`
root@h2529749:/opt# mv bundle/ Rocket.Chat
root@h2529749:/opt# rm -rf rocket.chat.tgz
root@h2529749:/opt# cd Rocket.Chat/programs/server/
root@h2529749:/opt/Rocket.Chat/programs/server# npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
/
> fibers@1.0.13 install /opt/Rocket.Chat/programs/server/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory `/opt/Rocket.Chat/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
  COPY Release/fibers.node
make: Leaving directory `/opt/Rocket.Chat/programs/server/node_modules/fibers/build'
Installed in `/opt/Rocket.Chat/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/opt/Rocket.Chat/programs/server)
amdefine@1.0.0 node_modules/amdefine

meteor-promise@0.7.2 node_modules/meteor-promise

asap@2.0.4 node_modules/asap

underscore@1.5.2 node_modules/underscore

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

semver@4.1.0 node_modules/semver

source-map-support@0.3.2 node_modules/source-map-support

source-map@0.1.32 node_modules/source-map

promise@7.1.1 node_modules/promise

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.5
├── supports-color@0.2.0
├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
└── has-ansi@0.1.0 (ansi-regex@0.2.1)

fibers@1.0.13 node_modules/fibers
root@h2529749:/opt/Rocket.Chat/programs/server# cd ../..
root@h2529749:/opt/Rocket.Chat# export ROOT_URL=http://vodteam.chat
root@h2529749:/opt/Rocket.Chat# export MONGO_URL=mongodb://localhost:27017/rocketchat
root@h2529749:/opt/Rocket.Chat# export PORT=80
root@h2529749:/opt/Rocket.Chat# node main.js

assert.js:93
  throw new assert.AssertionError({
        ^
**AssertionError: "undefined" === "function"
    at wrapPathFunction (/opt/Rocket.Chat/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)**
root@h2529749:/opt/Rocket.Chat#

`

**Comment by engelgabriel** [comment]
Please follow https://rocket.chat/docs/installation/manual-installation/ubuntu/#update and make sure you are using NodeJS 4.5.0 now. Reopen the issue if the problem persists with you node and nom version.

**Comment by mikrobyte** [comment]
Well, i am familiar with the update process, been using rocket.chat since 0.11.0 and upgrading has always been a piece of cake....

however, the link you sent me has a slight difference, i had to use n to change the node version...which i did and now node shows 4.5.0 while nodejs is another version...i am not sure if just node 4.5 is fine.

root@h2529749:/opt/Rocket.Chat# node --version
v4.5.0
root@h2529749:/opt/Rocket.Chat# nodejs --version
v0.10.25

This time, im getting another error when upgrading
**TypeError: settingKey.indexOf is not a function**
```

root@h2529749:/opt# mv bundle Rocket.Chat
root@h2529749:/opt# cd Rocket.Chat/programs/server
root@h2529749:/opt/Rocket.Chat/programs/server# npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
-
> fibers@1.0.13 install /opt/Rocket.Chat/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-v8-4.5` exists; testing
Binary is fine; exiting
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/opt/Rocket.Chat/programs/server)
amdefine@1.0.0 node_modules/amdefine

underscore@1.5.2 node_modules/underscore

meteor-promise@0.7.2 node_modules/meteor-promise

asap@2.0.4 node_modules/asap

semver@4.1.0 node_modules/semver

source-map-support@0.3.2 node_modules/source-map-support

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.5
├── supports-color@0.2.0
├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
└── has-ansi@0.1.0 (ansi-regex@0.2.1)

source-map@0.1.32 node_modules/source-map

promise@7.1.1 node_modules/promise

fibers@1.0.13 node_modules/fibers
root@h2529749:/opt/Rocket.Chat/programs/server# 


root@h2529749:/opt/Rocket.Chat# export ROOT_URL=http://under.chat
root@h2529749:/opt/Rocket.Chat# export MONGO_URL=mongodb://localhost:27017/rocketchat
root@h2529749:/opt/Rocket.Chat# export PORT=80
root@h2529749:/opt/Rocket.Chat# node main.js
Exception from task: TypeError: settingKey.indexOf is not a function
    at _Class.RocketChat.Assets._Class.processAsset (packages/rocketchat_assets/server/assets.coffee:135:17)
    at Object.RocketChat.models.Settings.find.observe.added (packages/rocketchat_assets/server/assets.coffee:178:21)
    at [object Object].observeChangesCallbacks.added (packages/minimongo/observe.js:153:1)
    at self.applyChange.added (packages/minimongo/observe.js:53:1)
    at packages/mongo/observe_multiplex.js:208:9
    at [object Object]._.extend.forEach (packages/id-map/id-map.js:48:1)
    at ObserveMultiplexer._sendAdds (packages/mongo/observe_multiplex.js:200:22)
    at packages/mongo/observe_multiplex.js:51:12
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    at Object.task (packages/meteor/dynamics_nodejs.js:123:1)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
    at packages/meteor/fiber_helpers.js:125:1
/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^

TypeError: settingKey.indexOf is not a function
    at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)
    at [object Object]._.extend.runTask (packages/meteor/fiber_helpers.js:81:1)
    at ObserveMultiplexer.addHandleAndSendInitialAdds (packages/mongo/observe_multiplex.js:47:17)
    at MongoConnection._observeChanges (packages/mongo/mongo_driver.js:1271:15)
    at Cursor.observeChanges (packages/mongo/mongo_driver.js:946:22)
    at Function.LocalCollection._observeFromObserveChanges (packages/minimongo/observe.js:177:1)
    at Cursor.observe (packages/mongo/mongo_driver.js:940:26)
    at packages/rocketchat_assets/server/assets.coffee:176:35
    at packages/rocketchat_assets/server/assets.coffee:271:1
    at packages/rocketchat_assets/server/assets.coffee:271:1
    at /opt/Rocket.Chat/programs/server/boot.js:292:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/Rocket.Chat/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/Rocket.Chat/programs/server/boot.js:128:5
    - - - - -
    at _Class.RocketChat.Assets._Class.processAsset (packages/rocketchat_assets/server/assets.coffee:135:17)
    at Object.RocketChat.models.Settings.find.observe.added (packages/rocketchat_assets/server/assets.coffee:178:21)
    at [object Object].observeChangesCallbacks.added (packages/minimongo/observe.js:153:1)
    at self.applyChange.added (packages/minimongo/observe.js:53:1)
    at packages/mongo/observe_multiplex.js:208:9
    at [object Object]._.extend.forEach (packages/id-map/id-map.js:48:1)
    at ObserveMultiplexer._sendAdds (packages/mongo/observe_multiplex.js:200:22)
    at packages/mongo/observe_multiplex.js:51:12
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    at Object.task (packages/meteor/dynamics_nodejs.js:123:1)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
    at packages/meteor/fiber_helpers.js:125:1
root@h2529749:/opt/Rocket.Chat# 



```
