### ISSUE TITLE
Slack import failed : TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by lc3t35** [RocketChat/Rocket.Chat#4614]
Your Rocket.Chat version: 0.43.0-develop (with PR#4604)
When I import a Slack zip, it fails with this error : 
````
Exception in defer callback: TypeError: Cannot read property 'toUpperCase' of undefined
I20161012-23:06:00.611(2)?     at [object Object].<anonymous> (packages/rocketchat_importer-slack/server.coffee:126:119)
I20161012-23:06:00.611(2)?     at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1
I20161012-23:06:00.611(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20161012-23:06:00.611(2)?     at Object.Meteor.runAsUser (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:185:1)
I20161012-23:06:00.612(2)?     at packages/rocketchat_importer-slack/server.coffee:113:13
I20161012-23:06:00.612(2)?     at packages/rocketchat_importer-slack/server.coffee:112:5
I20161012-23:06:00.613(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20161012-23:06:00.613(2)?     at packages/meteor/timers.js:6:1
I20161012-23:06:00.614(2)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
````
At line 126 of server.coffee, there is no control that user.profile.email is not empty 
````
userId = Accounts.createUser { email: user.profile.email, password: Date.now() + user.name + user.profile.email.toUpperCase() }
````
When I look at first user.profile from imported Slack data, it does not indeed have email set :(
I verified users.json, no email in all profile fields, example for mine
````
"profile": {
            "skype": "lc3t35",
            "first_name": "laurent",
            "last_name": "roger",
            "fields": {
                "Xf0DAKBW9J": {
                    "value": "lc3t35",
                    "alt": ""
                }
            },
            "avatar_hash": "gcc890e21b65",
            "real_name": "laurent roger",
            "real_name_normalized": "laurent roger",
            "image_24": "https:\/\/secure.gravatar.com\/avatar\/cc890e21b652d07da9edf3edeae59188.jpg?s=24&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0008-24.png",
            "image_32": "https:\/\/secure.gravatar.com\/avatar\/cc890e21b652d07da9edf3edeae59188.jpg?s=32&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0008-32.png",
            "image_48": "https:\/\/secure.gravatar.com\/avatar\/cc890e21b652d07da9edf3edeae59188.jpg?s=48&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0008-48.png",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/cc890e21b652d07da9edf3edeae59188.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0008-72.png",
            "image_192": "https:\/\/secure.gravatar.com\/avatar\/cc890e21b652d07da9edf3edeae59188.jpg?s=192&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0008-192.png",
            "image_512": "https:\/\/secure.gravatar.com\/avatar\/cc890e21b652d07da9edf3edeae59188.jpg?s=512&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0008-512.png"
        },
````
A problem when exporting is done in Slack ? did I miss something to tick ?

**Comment by lc3t35** [comment]
Solved by 
````
if user.profile.email
								userId = Accounts.createUser { email: user.profile.email, password: Date.now() + user.name + user.profile.email.toUpperCase() }
							else
								userId = Accounts.createUser { username: user.name, password: Date.now() + user.name }
````
submitting PR ...

**Comment by acrogenesis** [comment]
I'm getting this error, I'm testing on the `develop` branch
```
Exception in defer callback: Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation     at exports.check (packages/check/match.js:34:1)     at [object Object].Meteor.methods.setAvatarFromService (server/methods/setAvatarFromService.coffee:5:3)     at [object Object].methodsMap.(anonymous function) (packages/rocketchat:lib/server/lib/debug.js:17:26)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)     at packages/ddp-server/livedata_server.js:1624:18     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at Server.apply (packages/ddp-server/livedata_server.js:1623:45)     at Server.call (packages/ddp-server/livedata_server.js:1566:17)     at [object Object].<anonymous> (packages/rocketchat_importer-slack/server.coffee:135:16)     at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at Object.Meteor.runAsUser (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:185:1)     at [object Object].<anonymous> (packages/rocketchat_importer-slack/server.coffee:127:15)     at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)    
```

**Comment by lc3t35** [comment]
@acrogenesis see #4495, it's solved ;)
