### ISSUE TITLE
Slack import broken

### ISSUE THREAD

**Issue by ulope** [RocketChat/Rocket.Chat#4627]
Your Rocket.Chat version: 0.42.0

_Update: SlackBridge can mostly solve this for us, however there is also a problem with it which I've documented in #4628_

We're currently in the process of switching from Slack. Since my experience with RC so far has been very good I recommended it.

However it seems the slack import (which is an absolute must for us) is currently broken.

When starting the import with all users and channels checked I just get the pulsing RC logo with `0 / <number of messages>` and the following error message in the log:

```
Exception in defer callback: Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
    at exports.check (packages/check/match.js:34:1)
    at [object Object].Meteor.methods.setAvatarFromService (server/methods/setAvatarFromService.coffee:5:3)
    at [object Object].methodsMap.(anonymous function) (packages/rocketchat:lib/server/lib/debug.js:17:26)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
    at packages/ddp-server/livedata_server.js:1624:18
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Server.apply (packages/ddp-server/livedata_server.js:1623:45)
    at Server.call (packages/ddp-server/livedata_server.js:1566:17)
    at [object Object].<anonymous> (packages/rocketchat_importer-slack/server.coffee:135:16)
    at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:185:1)
    at [object Object].<anonymous> (packages/rocketchat_importer-slack/server.coffee:127:15)
    at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:185:1)
    at packages/rocketchat_importer-slack/server.coffee:113:13
    at packages/rocketchat_importer-slack/server.coffee:112:5
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

With all users unchecked (which we could live with) the same happens but with a different message in the log:

```
Exception in defer callback: Error: Invalid user [error-invalid-user]
    at [object Object].Meteor.methods.createChannel (packages/rocketchat_lib/server/methods/createChannel.coffee:8:14)
    at [object Object].methodsMap.(anonymous function) (packages/rocketchat:lib/server/lib/debug.js:17:26)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
    at packages/ddp-server/livedata_server.js:1624:18
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Server.apply (packages/ddp-server/livedata_server.js:1623:45)
    at Server.call (packages/ddp-server/livedata_server.js:1566:17)
    at [object Object].<anonymous> (packages/rocketchat_importer-slack/server.coffee:182:27)
    at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:185:1)
    at [object Object].<anonymous> (packages/rocketchat_importer-slack/server.coffee:181:15)
    at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:185:1)
    at packages/rocketchat_importer-slack/server.coffee:159:13
    at packages/rocketchat_importer-slack/server.coffee:158:5
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

In both cases after a while a red notification is shown in the Web UI with this message `The importer was not defined correctly, it is missing the Import class. [error-importer-not-defined]`

**Comment by jimscarver** [comment]
I get the same result with sandstorm slack import with RocketChat V0.49.3: "The importer was not defined correctly, it is missing the Import class. [error-importer-not-defined]". 

What can I do?
