### ISSUE TITLE
SlackBridge fails for some channels

### ISSUE THREAD

**Issue by ulope** [RocketChat/Rocket.Chat#4628]
Your Rocket.Chat version: 0.42.0

SlackBridge works very nice for most channels however there are some where the import fails midway through (i.e. only messages up to a certain point get imported) with the following message:

`SlackBridge got an error while importing your messages at <channel_name>: Cannot read property 'split' of undefined`

The log shows this:

```
Exception while invoking method 'slashCommand' TypeError: Cannot read property 'split' of undefined
    at SlackBridge.processSubtypedMessage (packages/rocketchat:slackbridge/slackbridge.js:445:33)
    at SlackBridge.sendMessage (packages/rocketchat:slackbridge/slackbridge.js:243:19)
    at SlackBridge.saveMessage (packages/rocketchat:slackbridge/slackbridge.js:293:10)
    at SlackBridge.importFromHistory (packages/rocketchat:slackbridge/slackbridge.js:801:10)
    at SlackBridge.importMessages (packages/rocketchat:slackbridge/slackbridge.js:889:21)
    at SlackBridgeImport (packages/rocketchat:slackbridge/slashcommand/slackbridge_import.server.js:23:26)
    at Object.RocketChat.slashCommands.run (packages/rocketchat_lib/lib/slashCommand.coffee:17:3)
    at [object Object].Meteor.methods.slashCommand (packages/rocketchat_lib/lib/slashCommand.coffee:25:28)
    at [object Object].methodsMap.(anonymous function) (packages/rocketchat:lib/server/lib/debug.js:17:26)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:707:46
    at Session.method (packages/ddp-server/livedata_server.js:681:23)
    at packages/ddp-server/livedata_server.js:551:43
```

**Comment by marceloschmidt** [comment]
Can you identify which type of message breaks it? Is it a file share, a /me message, a bot message, an edited message? I can probably fix this without this information, but it would be good to know.

Thanks.

**Comment by marceloschmidt** [comment]
I tried replicating every message type on Slack and run a /slackbridge-import to see what type of message would break it and none did. Could you try again and reopen this issue if it happens again? Also, if it happens, are you allowed to send us an export of that channel so that we may debug more thoroughly?
