### ISSUE TITLE
Failed to connect to MongoDB

### ISSUE THREAD

**Issue by B2RN** [RocketChat/Rocket.Chat#4718]
Moved from being a comment on an old ticket to a proper ticket. The old ticket (#4448) was closed before the user confirmed that it's working.

Let me know if you need any more information, copy paste of my update follows:

This hasn't been solved. Just ran a clean install on a CentOS 7.2 minimal install:

```
[root@rocket-srv1 Rocket.Chat]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
```

```
[root@rocket-srv1 Rocket.Chat]# which node
/bin/node
[root@rocket-srv1 Rocket.Chat]# node -v
v4.5.0
[root@rocket-srv1 Rocket.Chat]# 
```

```
[root@rocket-srv1 Rocket.Chat]# systemctl status mongod
● mongod.service - SYSV: Mongo is a scalable, document-oriented database.
   Loaded: loaded (/etc/rc.d/init.d/mongod)
   Active: active (running) since Thu 2016-10-13 14:03:21 CEST; 4min 47s ago
     Docs: man:systemd-sysv-generator(8)
 Main PID: 8191 (mongod)
   CGroup: /system.slice/mongod.service
           └─8191 /usr/bin/mongod -f /etc/mongod.conf

Oct 13 14:03:20 rocket-srv1.foo systemd[1]: Starting SYSV: Mongo is a scalable, document-oriented database....
Oct 13 14:03:20 rocket-srv1.foo runuser[8187]: pam_unix(runuser:session): session opened for user mongod...d=0)
Oct 13 14:03:21 rocket-srv1.foo mongod[8178]: Starting mongod: [  OK  ]
Oct 13 14:03:21 rocket-srv1.foo systemd[1]: Started SYSV: Mongo is a scalable, document-oriented database..
Hint: Some lines were ellipsized, use -l to show in full.
[root@rocket-srv1 Rocket.Chat]# 
```

```
[root@rocket-srv1 Rocket.Chat] node main.js

/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:216:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    - - - - -
    at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mo
ngodb-core/lib/topologies/server.js:313:35)                                                                          
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mo
ngodb-core/lib/connection/pool.js:260:12)                                                                            
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-cor
e/lib/connection/connection.js:162:49)                                                                               
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
[root@rocket-srv1 Rocket.Chat]# 
```

Can provide more logs and so on, or it might be something that I messed up.

Cheers,
Juraj

**Comment by geekgonecrazy** [comment]
Have you set any environment variables prior to this?  It looks like you're starting with out: MONGO_URL

**Comment by B2RN** [comment]
Don't think I did, no. I'll check it tomorrow at the machine and drop an update here.

**Comment by B2RN** [comment]
So an update. I followed the environment variables section from here:

https://rocket.chat/docs/installation/manual-installation/centos/

And this is the result:

```
[root@rocket-srv1 Rocket.Chat]# echo $PORT
3000
[root@rocket-srv1 Rocket.Chat]# echo $ROOT_URL
http://rocket-srv1.FOO.BAR:3000/
[root@rocket-srv1 Rocket.Chat]# echo $MONGO_URL
mongodb://localhost:27017/rocketchat
[root@rocket-srv1 Rocket.Chat]# node --version
v4.5.0
[root@rocket-srv1 Rocket.Chat]# node main.js

/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:216:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    - - - - -
    at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mo)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mo)
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-cor)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
```

I've also tried replacing localhost with the FQDN, but no go. As in, the same error pops up. I've tried this with and without restarting MongoDB.

Cheers,
Juraj

**Comment by geekgonecrazy** [comment]
@B2RN it seems that either localhost isn't defined (I doubt) or mongo isn't truly running.  Try running the mongo command and see if its able to successfully connect using: `mongo`

**Comment by B2RN** [comment]
@geekgonecrazy:

So, it's running:

```
[mpi@rocket-srv1 Rocket.Chat]$ pwd
/opt/Rocket.Chat
[mpi@rocket-srv1 Rocket.Chat]$ mongo
MongoDB shell version: 2.6.12
connecting to: test
Server has startup warnings:
2016-10-27T12:00:08.007+0200 [initandlisten]
2016-10-27T12:00:08.007+0200 [initandlisten] ** WARNING: Readahead for /var/lib/mongo is set to 4096KB
2016-10-27T12:00:08.007+0200 [initandlisten] **          We suggest setting it to 256KB (512 sectors) or less
2016-10-27T12:00:08.007+0200 [initandlisten] **          http://dochub.mongodb.org/core/readahead
>
bye
[mpi@rocket-srv1 Rocket.Chat]$ node main.js
/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at /opt/Rocket.Chat/programs/server/packages/accounts-base.js:1838:15
    at /opt/Rocket.Chat/programs/server/packages/accounts-base.js:1849:3
[mpi@rocket-srv1 Rocket.Chat]$ systemctl status mongod
● mongod.service - SYSV: Mongo is a scalable, document-oriented database.
   Loaded: loaded (/etc/rc.d/init.d/mongod)
   Active: active (running) since Thu 2016-10-27 12:00:08 CEST; 22h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 23443 ExecStop=/etc/rc.d/init.d/mongod stop (code=exited, status=0/SUCCESS)
  Process: 23459 ExecStart=/etc/rc.d/init.d/mongod start (code=exited, status=0/SUCCESS)
 Main PID: 23473 (mongod)
   CGroup: /system.slice/mongod.service
           └─23473 /usr/bin/mongod -f /etc/mongod.conf
```

What do you mean by localhost not being defined? It's in /etc/hosts is that's what you mean.

Cheers,
Juraj

**Comment by geekgonecrazy** [comment]
@B2RN awesome!  Yeah, usually very rare for that to happen.  But figured i'd call it out as a possibility.  Glad you got it working!

**Comment by AndyNormore** [comment]
I had set a LONG time ago mongodb://localhost:27017/your_db

I rebooted and Meteor wouldn't work. Go figure. I had forgotten I had done this. Clearing the enviro and rebooting works.

**Comment by GNUGradyn** [comment]
Havn't played with snaps until now, how did you get into the VM? I'm getting the same error and need to start mongo
