### ISSUE TITLE
Url previews are broken 

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#4779]
Your Rocket.Chat version: 239f922163a149b7d381df34584a6d422bc42680

Url previews for images appear to be broken.

```
Exception in callback of async function: Error: Encoding not recognized: 'undefined' (searched as: 'undefined')
  at Object.getCodec (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:102:23)
  at Object.getDecoder (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:118:23)
  at Object.decode (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:36:25)
  at toUtf8 (/app/bundle/programs/server/packages/rocketchat_oembed.js:85:16)
  at /app/bundle/programs/server/packages/rocketchat_oembed.js:153:13
  at runWithEnvironment (packages/meteor.js:1176:24)
```

**Comment by mcmdhr** [comment]
+1

**Comment by k0nsl** [comment]
I have the same issue on 0.45.0. It worked flawlessly on 0.44.0.
