### ISSUE TITLE
Some node modules missing in 0.44.0

### ISSUE THREAD

**Issue by bcalton** [RocketChat/Rocket.Chat#4793]
Your Rocket.Chat version: 0.44.0

I recently updated rocket.chat from 0.43.0 to 0.44.0 by following the download/move/replace method detailed at https://rocket.chat/docs/installation/manual-installation/centos/#upgrade. I have a CentOS 7 system with a systemd service setup to mange rocket.chat and this failed to restart. 

Doing a bit of digging, I tried running it myself and got this error:
```
[root@xxxx Rocket.Chat]# node main.js 
module.js:327
    throw err;
    ^

Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/boot.js:1:75)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

It seems that some of the node modules required have bee omitted from the release. I have fixed this on my own install by doing this:
```
[root@xxxx server]# cd /opt/Rocket.Chat/programs/server
[root@xxxx server]# npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
/
> fibers@1.0.15 install /opt/Rocket.Chat/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-46` exists; testing
Binary is fine; exiting
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/opt/Rocket.Chat/programs/server)
amdefine@1.0.0 node_modules/amdefine

underscore@1.5.2 node_modules/underscore

meteor-promise@0.7.2 node_modules/meteor-promise

asap@2.0.5 node_modules/asap

semver@4.1.0 node_modules/semver

source-map-support@0.3.2 node_modules/source-map-support

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

source-map@0.1.32 node_modules/source-map

chalk@0.5.1 node_modules/chalk
├── supports-color@0.2.0
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.5
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

promise@7.1.1 node_modules/promise

fibers@1.0.15 node_modules/fibers
```

**Comment by yuchaozh** [comment]
Have the same issue here on Windows 7. "Failed at the fibers@1.0.15 install script 'node build.js || nodejs build.js".

**Comment by engelgabriel** [comment]
What version of NodeJS you have installed?

**Comment by bcalton** [comment]
We are using node v4.5.0 installed using `n` as per the instructions
```
[root@xxxx ~]# node -v
v4.5.0
```

**Comment by yuchaozh** [comment]
I am using v4.5.0 too. I changed Node js to v0.10.44. It fixed the issue.

**Comment by peccu** [comment]
I upgraded from v0.10.44 to v4.5.0 by swapping all node_modules, ~/.npm, ~/.meteor, etc. like below.

```
mv /usr/lib/node_modules{,_}
mv /usr/local/bin/meteor{,_}
mv /usr/local/bin/node{,_}
mv /usr/local/bin/npm{,_}
mv /usr/local/include/node{,_}
mv /usr/local/lib/node_modules{,_}
mv /usr/local/n{,_}
mv /usr/local/share/man/man1/node.1{,_}
mv /usr/share/node{,_}
mv /usr/bin/node{,_}
mv ~/.meteor{,_}
mv ~/.npm{,_}
mv ~/.node-gyp{,_}
```

re-install Node.js,

```
sudo yum install nodejs npm
sudo -E npm i -g n
/usr/local/bin/n 4.5
sudo -E npm i -g npm@latest
curl https://install.meteor.com/ | sh
```

and build(if need), `npm install`.

```
# build
export NODE_ENV=production
meteor build --server https://example.com/ --directory /var/www/rocket.chat
# npm install
cd /var/www/rocket.chat/bundle/programs/server
npm install
```

**Comment by bcalton** [comment]
The same problem and solution is still the case in 0.45.0

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
