### ISSUE TITLE
Picture oembed doesn't work.

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#4812]
Your Rocket.Chat version: latest

Well, oembeds doesn't work any more. No matter if using protocol `HTTP` or `HTTPs`. The only thing in my log:

```
[34mI20161101-15:23:42.463(0) Exception in callback of async function: Error: Encoding not recognized: 'undefined' (searched as: 'undefined')   at Object.getCodec (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:102:23)   at Object.getDecoder (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:118:23)   at Object.decode (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:36:25)   at toUtf8 (/app/bundle/programs/server/packages/rocketchat_oembed.js:85:16)   at /app/bundle/programs/server/packages/rocketchat_oembed.js:153:13   at runWithEnvironment (packages/meteor.js:1176:24)  
[34mI20161101-15:51:15.051(0) Exception in callback of async function: Error: Encoding not recognized: 'undefined' (searched as: 'undefined')   at Object.getCodec (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:102:23)   at Object.getDecoder (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:118:23)   at Object.decode (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:36:25)   at toUtf8 (/app/bundle/programs/server/packages/rocketchat_oembed.js:85:16)   at /app/bundle/programs/server/packages/rocketchat_oembed.js:153:13   at runWithEnvironment (packages/meteor.js:1176:24)  
[34mI20161101-15:51:49.757(0) Exception in callback of async function: Error: Encoding not recognized: 'undefined' (searched as: 'undefined')   at Object.getCodec (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:102:23)   at Object.getDecoder (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:118:23)   at Object.decode (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:36:25)   at toUtf8 (/app/bundle/programs/server/packages/rocketchat_oembed.js:85:16)   at /app/bundle/programs/server/packages/rocketchat_oembed.js:153:13   at runWithEnvironment (packages/meteor.js:1176:24)  
[34mI20161101-15:52:34.786(0) Exception in callback of async function: Error: Encoding not recognized: 'undefined' (searched as: 'undefined')   at Object.getCodec (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:102:23)   at Object.getDecoder (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:118:23)   at Object.decode (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:36:25)   at toUtf8 (/app/bundle/programs/server/packages/rocketchat_oembed.js:85:16)   at /app/bundle/programs/server/packages/rocketchat_oembed.js:153:13   at runWithEnvironment (packages/meteor.js:1176:24)  
[34mI20161101-15:52:34.809(0) Exception in callback of async function: Error: Encoding not recognized: 'undefined' (searched as: 'undefined')   at Object.getCodec (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:102:23)   at Object.getDecoder (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:118:23)   at Object.decode (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:36:25)   at toUtf8 (/app/bundle/programs/server/packages/rocketchat_oembed.js:85:16)   at /app/bundle/programs/server/packages/rocketchat_oembed.js:153:13   at runWithEnvironment (packages/meteor.js:1176:24)  
[34mI20161101-16:07:59.084(0) Exception in callback of async function: Error: Encoding not recognized: 'undefined' (searched as: 'undefined')   at Object.getCodec (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:102:23)   at Object.getDecoder (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:118:23)   at Object.decode (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:36:25)   at toUtf8 (/app/bundle/programs/server/packages/rocketchat_oembed.js:85:16)   at /app/bundle/programs/server/packages/rocketchat_oembed.js:153:13   at runWithEnvironment (packages/meteor.js:1176:24)  
[34mI20161101-16:10:57.596(0) Exception in callback of async function: Error: Encoding not recognized: 'undefined' (searched as: 'undefined')   at Object.getCodec (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:102:23)   at Object.getDecoder (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:118:23)   at Object.decode (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:36:25)   at toUtf8 (/app/bundle/programs/server/packages/rocketchat_oembed.js:85:16)   at /app/bundle/programs/server/packages/rocketchat_oembed.js:153:13   at runWithEnvironment (packages/meteor.js:1176:24) 
```

**Comment by lucasvanhalst** [comment]
Same as #4779

**Comment by MartinSchoeler** [comment]
Duplicate
