### ISSUE TITLE
Can't run meteor with Rocket.chat on windows 10

### ISSUE THREAD

**Issue by redgang** [RocketChat/Rocket.Chat#4883]
Your Rocket.Chat version: 0.45.0
meteor version 1.4.2

C:\Users\Red钢\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-
promise\promise_server.js:190
      throw error;
      ^

Error: No metadata files found for isopack at: /C/Users/Red钢/AppData/Local/.meteor/packages/tap_i18n/1.8.2
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:900:13)
    at C:\tools\packaging\tropohouse.js:521:21
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Red钢\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\d
ev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:520:13
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:515:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:613:18
    at C:\tools\utils\buildmessage.js:572:21
    at C:\Users\Red钢\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\
meteor-promise\fiber_pool.js:32:39
 => awaited here:
    at Promise.await (C:\Users\Red钢\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\li
b\node_modules\meteor-promise\promise_server.js:39:12)
    at Object.forkJoin (C:\tools\utils\buildmessage.js:604:6)
    at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:609:18)
    at C:\tools\project-context.js:776:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:775:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:774:13)
    at C:\tools\project-context.js:268:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:258:18)
    at C:\tools\project-context.js:250:12
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:249:13)
    at C:\tools\runners\run-app.js:549:29
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundleApp (C:\tools\runners\run-app.js:548:31)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:617:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:876:28)
    at C:\tools\runners\run-app.js:403:12

I want to develop in the window pc, but the implementation of meteor has been reported this mistake, who can help me?

tks!

**Comment by 117028813** [comment]
I have this problem too.
my meteor version is 1.4.2
Rocket.Chat version is 0.45.0
I'm on windows 10

**Comment by NephilimLord** [comment]
Hi. I have this problem too. I removed underscore but it didn't help. Win 7 x64. Any ideas?

**Comment by 117028813** [comment]
I try to uninstall meteor then install meteor, I'm installing, but it's too slow.

**Comment by NephilimLord** [comment]
Oo, it seems i found solution! Try to do steps written by jkdowdle in https://github.com/TAPevents/tap-i18n/issues/183.

**Comment by 117028813** [comment]
I reinstall meteor, but it dosn't work too.
I clone Rocket.Chat and install meteor on linux server, it works well.
But how do I access Chat on the local browser on the server.
Server IP is 192.168.1.104

**Comment by MartinSchoeler** [comment]
This is a meteor problem. Please reopen this in their repository. Thanks!
