### ISSUE TITLE
Slack data import issue

### ISSUE THREAD

**Issue by griiettner** [RocketChat/Rocket.Chat#4899]
Your Rocket.Chat version: 1.3.1 (15)

Hello, I tried to run the slack import and the import process is stuck somewhere...

on the logs I could see that stoped here

```
[34mI20161108-00:59:48.203(0) Set edhathaway's avatar from the url: https://avatars.slack-edge.com/2016-03-11/26300818229_7edf611b53c76ac846c1_original.jpg 
[34mI20161108-01:00:03.283(0) Error while handling the setting of the avatar from a url (https://secure.gravatar.com/avatar/7a905b89988f47ec1ebb05fb21ecb3db.jpg?s=512&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0026-512.png) for griiettner: { [Error: failed [503] <!DOCTYPE html> <html>   <head>     <title>503 Backend fetch failed</title>   </head>   <body>     <h1>Error 503 Backend fetch failed</h1>     <p>Backend fetch failed</p>     <h3>Guru Meditation:</h3>     <p>XID: 56721579</p>     <hr>     <p>Varnish cache server</p>   </body> </html> ]   response:     { statusCode: 503,      content: '<!DOCTYPE html><br><html><br>  <head><br>    <title>503 Backend fetch failed</title><br>  </head><br>  <body><br>    <h1>Error 503 Backend fetch failed</h1><br>    <p>Backend fetch failed</p><br>    <h3>Guru Meditation:</h3><br>    <p>XID: 56721579</p><br>    <hr><br>    <p>Varnish cache server</p><br>  </body><br></html><br>',      headers:        { server: 'nginx',         date: 'Tue, 08 Nov 2016 01:00:03 GMT',         'content-type': 'text/html; charset=utf-8',         'content-length': '285',         connection: 'close',         'retry-after': '5',         'x-nc': 'MISS dca 2',         'source-age': '0' },      data: null } } 
[34mI20161108-01:00:03.288(0) Exception in defer callback: Error: Error while handling avatar setting from a URL (https://secure.gravatar.com/avatar/7a905b89988f47ec1ebb05fb21ecb3db.jpg?s=512&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0026-512.png) for griiettner [error-avatar-url-handling]   at Object.RocketChat.setUserAvatar (/app/bundle/programs/server/packages/rocketchat_lib.js:2877:10)   at [object Object].Meteor.methods.setAvatarFromService (/app/bundle/programs/server/app/app.js:6081:23)   at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1014:26)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:2107:12)   at /app/bundle/programs/server/packages/ddp-server.js:2026:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at Server.apply (/app/bundle/programs/server/packages/ddp-server.js:2025:47)   at Server.call (/app/bundle/programs/server/packages/ddp-server.js:1959:19)   at [object Object].<anonymous> (/app/bundle/programs/server/packages/rocketchat_importer-slack.js:296:28)   at packages/dispatch_run-as-user.js:211:14   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)   at [object Object].<anonymous> (/app/bundle/programs/server/packages/rocketchat_importer-slack.js:286:26)   at packages/dispatch_run-as-user.js:211:14   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)   at /app/bundle/programs/server/packages/rocketchat_importer-slack.js:254:29   at /app/bundle/programs/server/packages/rocketchat_importer-slack.js:323:15   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at packages/meteor.js:445:45   at runWithEnvironment (packages/meteor.js:1176:24)
```

I did not find where to stop the import process... even when I logou and login, the import process is stuck at the same place.

One thing that I can think of... is that some users that were being imported was already using Rockect.Chat... and probably the import process found some conflict with account being importaed and existing ones...

**Comment by graywolf336** [comment]
From that error it seems that setting the avatar of a user failed `(/app/bundle/programs/server/packages/rocketchat_importer-slack.js:296:28)`. I will be checking in code here shortly which adds a try/catch on that method so that in the future it doesn't stop the import.
