### ISSUE TITLE
LDAP Account Issues with getUserNameSuggestion exception

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#4912]
Your Rocket.Chat version: 0.38.0

I know we are on an older version, we don't have the time to upgrade right now and wondering if this is known. I could not find any issue relating to this.

We are noticing an error lately for new user accounts. We are using ldap and have had no issues before when new users log in. It would create the user with their cn=name and email info. What is happening now is:
1. A new user logs in for the first time via ldap. The user is found but a new register screen shows up that we have not seen before:
![clipboard](https://cloud.githubusercontent.com/assets/8405384/20151212/e9b3524e-a67e-11e6-9521-18d06007e4f6.png)

and while following the logs, the following shows up: 
`Exception while invoking method 'getUsernameSuggestion' TypeError: Cannot read property 'length' of undefined
    at generateSuggestion (server/methods/getUsernameSuggestion.coffee:27:14)
    at [object Object].Meteor.methods.getUsernameSuggestion (server/methods/getUsernameSuggestion.coffee:88:10)
    at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:17:26)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo (/var/www/rocket.chat/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)`

2. The user is now logged in and can chat but once the user logs out, they are unable to relogin. When the user attempts to log in again, RC throws an error saying username not found:
    ldap.js:346 LDAP ➔ Auth.info Authenticating uid=jtest1,cn=users,cn=accounts,dc=example,dc=us
	    ldap.js:350 LDAP ➔ Auth.info Authenticated uid=jtest1,cn=users,cn=accounts,dc=example,dc=us
	    ldap.js:363 LDAP ➔ Connection.info Disconecting
	    loginHandler.js:97 LDAPHandler ➔ debug userQuery { username: '' }
	    loginHandler.js:127 LDAPHandler ➔ info User does not exist, creating
	    sync.js:174 LDAPSync ➔ debug New user data { username: '', email: 'j.r.example.com@example.com' }
	    sync.js:179 LDAPSync ➔ error Error creating user { [Error: Email already exists. [403]]
	      error: 403,
	      reason: 'Email already exists.',
	      details: undefined,
	      message: 'Email already exists. [403]',
	      errorType: 'Meteor.Error' }
	    debug.js:15 Meteor ➔ method stream-notify-room -> userId: bX9EoXGYguijyTbaE , arguments:  { '0': 'bX9EoXGYguijyTbaEoXbH9Q4ADb2ZZbkBA/typing',

3. The user account is still found in the mongodb when searching by username.
4. We have to then delete that account and have the user relogin but it starts back at step 2.

I am not sure why the username is empty even though we defined a username during the screenshot in step 1. And in addition, the username should be pulling from ldap field #{username}.

**Comment by richardwlu** [comment]
We had to define the Username Field to something other than #{username}. Not sure why this recently caused issues, but this was the resolution.
