### ISSUE TITLE
Deployment using kadirahq/meteor-up

### ISSUE THREAD

**Issue by IcyEagle** [RocketChat/Rocket.Chat#4969]
Hi

I find a way to deploy the application using [kadirahq/meteor-up](https://github.com/kadirahq/meteor-up). As mupx, the package uses docker as well so I thought it shouldn't be a problem. Nevertheless I have an error during deployment:

```
[159.203.138.26]Error: $ROOT_URL, if specified, must be an URL
[159.203.138.26]    at Error (native)
[159.203.138.26]    at packages/meteor.js:1218:13
[159.203.138.26]    at packages/meteor.js:1233:4
```

Here is my mup.js:

```
module.exports = {
  servers: {
    one: {
      host: "xxx.xxx.xxx.xxx",
      username: "root"
    }
  },

  meteor: {
    name: 'xxx',
    path: '.',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true
    },
    env: {
      ROOT_URL: "http:/xxx.xxx.xxx.xxx",
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    docker: {
      image: 'rocket.chat'
    },
    deployCheckWaitTime: 120
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {}
    }
  }
};
```

What should I do to fix the issue?
Thanks!

**Comment by IcyEagle** [comment]
Just a silly error ("http:/" instead of "http://").
