### ISSUE TITLE
OAuth2 with error Provider ServerResponse.res.setHeader

### ISSUE THREAD

**Issue by tomaluca95** [RocketChat/Rocket.Chat#4978]
Hi, I'm tring to use RocketChat as oauth provider and i got this error
```
Exception in callback of async function: Error: Can't set headers after they are sent.
  at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
  at ServerResponse.res.setHeader (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/patch.js:134:22)
  at ServerResponse.res.setHeader (/app/bundle/programs/server/packages/rocketchat_cors.js:75:22)
  at ServerResponse.header (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/response.js:718:10)
  at ServerResponse.send (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/response.js:163:12)
  at /app/bundle/programs/server/packages/rocketchat_oauth2-server.js:292:36
  at runWithEnvironment (packages/meteor.js:1176:24)
  at packages/meteor.js:1189:14
  at Layer.handle [as handle_request] (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/layer.js:95:5)
  at next (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/route.js:131:13)
  at debugMiddleware (/app/bundle/programs/server/packages/rocketchat_oauth2-server.js:266:14)
  at Layer.handle [as handle_request] (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/layer.js:95:5)
  at next (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/route.js:131:13)
  at Route.dispatch (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/route.js:112:3)
  at Layer.handle [as handle_request] (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/layer.js:95:5)
  at /app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/index.js:277:22
  at Function.process_params (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/index.js:330:12)
  at next (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/index.js:271:10)
  at expressInit (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/middleware/init.js:33:5)
  at Layer.handle [as handle_request] (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/index.js:312:13)
  at /app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/index.js:330:12)
  at next (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/index.js:271:10)
  at query (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/middleware/query.js:49:5)
  at Layer.handle [as handle_request] (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/index.js:312:13)
  at /app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/index.js:330:12)
  at next (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/index.js:271:10)
  at Function.handle (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/router/index.js:176:3)
  at EventEmitter.handle (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_oauth2-server/node_modules/express/lib/application.js:173:10)
  at Object.fn [as handle] (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:79:14)
  at next (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
  at next (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:149:78)
  at next (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:149:78)
  at Object.handle (/app/bundle/programs/server/packages/jalik_ufs.js:1572:9)
  at next (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
  at middleware (/app/bundle/programs/server/packages/rocketchat_cas.js:186:4)
  at /app/bundle/programs/server/packages/rocketchat_cas.js:212:3

```
I'm running the last docker image
`rocket.chat            latest              882239aa781a        8 days ago          580.2 MB`

the consumer is the last version of keycloak.

**Comment by engelgabriel** [comment]
The documentation about Keycloak is going to be written. 

Please follow https://github.com/RocketChat/docs/issues/790
