### ISSUE TITLE
Can't login with Github

### ISSUE THREAD

**Issue by jpxd** [RocketChat/Rocket.Chat#504]
When I try to login with Github on demo.rocket.chat nothing happens. The Github window opens, I authorize RocketChat, and it closes. No message, no redirect, no login...

Chromes console says:
![screenshot 2015-08-19 10 23 47](https://cloud.githubusercontent.com/assets/10384363/9351793/919fa7e8-465c-11e5-9d5b-c155c61cc76e.png)

Exception in plaintext
```
Exception in delivering result of invoking 'login': TypeError: r is not a function
    at https://dbde4sd21oahf.cloudfront.net/e95b262ac4280c4244f6067ba9f788b17f79b86b.js:540:1245
    at o.callLoginMethod.userCallback (https://dbde4sd21oahf.cloudfront.net/e95b262ac4280c4244f6067ba9f788b17f79b86b.js:66:1122)
    at https://dbde4sd21oahf.cloudfront.net/e95b262ac4280c4244f6067ba9f788b17f79b86b.js:60:4032
    at https://dbde4sd21oahf.cloudfront.net/e95b262ac4280c4244f6067ba9f788b17f79b86b.js:1:8374
    at r (https://dbde4sd21oahf.cloudfront.net/e95b262ac4280c4244f6067ba9f788b17f79b86b.js:60:4547)
    at null._callback (https://dbde4sd21oahf.cloudfront.net/e95b262ac4280c4244f6067ba9f788b17f79b86b.js:3:6711)
    at a.extend._maybeInvokeCallback (https://dbde4sd21oahf.cloudfront.net/e95b262ac4280c4244f6067ba9f788b17f79b86b.js:38:11444)
    at a.extend.receiveResult (https://dbde4sd21oahf.cloudfront.net/e95b262ac4280c4244f6067ba9f788b17f79b86b.js:38:11752)
    at a.extend._livedata_result (https://dbde4sd21oahf.cloudfront.net/e95b262ac4280c4244f6067ba9f788b17f79b86b.js:38:22656)
    at o (https://dbde4sd21oahf.cloudfront.net/e95b262ac4280c4244f6067ba9f788b17f79b86b.js:38:9774)
```

**Comment by rodrigok** [comment]
Are you logging or creating a new account?

**Comment by jpxd** [comment]
Logging in
I talked to @engelgabriel on demo.rocket.chat and he said this error is because my email address is hidden in my public github profile

**Comment by engelgabriel** [comment]
Duplicates https://github.com/RocketChat/Rocket.Chat/issues/200
