### ISSUE TITLE
duplicate key error index MongoDB

### ISSUE THREAD

**Issue by Simonell** [RocketChat/Rocket.Chat#5053]
Your Rocket.Chat version: 0.46

I have rocket.chat server connected to LDAP. When one of users try logging to their account he get logged to someone other account, it's probably because indexes. My logs look like this:

> [34mI20161126-12:07:28.992(1) rocketchat_ldap rocketchat_ldap.js:341 [31mLDAP ➔ Search.error Search by id 31353036 returned 2 records [34mI20161126-12:07:28.999(1) rocketchat_ldap rocketchat_ldap.js:780
> 
> [31mLDAPSync ➔ error { [MongoError: E11000 duplicate key error index: rocketchat.users.$emails.address_1 dup key: { : "some@one.com" }]
> name: 'MongoError', message: 'E11000 duplicate key error index: rocketchat.users.$emails.address_1 dup key: { : "some@one.com" }',
> driver: true, index: 0, code: 11000, errmsg: 'E11000 duplicate key error index: rocketchat.users.$emails.address_1 dup key: { : "some@one.com" }' }

Can I rebuild that indexes or something else to resolve this problem?

**Comment by exactt** [comment]
Similar problem here. I have LDAP connection working. But users can only login once. To make it work again I manually delete the users from mongodb. This results in "internal server error" though and the logs are filed with the duplicate key messages...

**Comment by rodrigok** [comment]
Can you paste your LDAP settings here?

**Comment by exactt** [comment]
I figured I had to set "merge existing users" in LDAP settings in order for users to login more than once...

**Comment by rodrigok** [comment]
@exactt I don't think this will solve your problem, it will just create a way to pass over the problem.

Seems that your config is wrong in some way that is allowing login but it is not find the user in RC's database, then LDAP is trying to create it in every login, with `merge existing users` you are allowing RC to use email to merge user instead of create it, but RC should not try to create more than once.

If you can share your config we can try to help you to prevent this error.

The `merge existing users` was created to allow you to enable users that already had accounts to use LDAP and keep the same account merging them.

**Comment by exactt** [comment]
There is really nothing special about my install. I only added:
- LDAP Hostname
- Domain Base
- Domain user and password
- Default domain (MYCOMPANY.intern)

Shall I provide any logs? Please be quite specific. I am rather new to Rocket.Chat. Running the snap on Ubuntu 16.04 btw...

Thx!

**Comment by pyhtongates** [comment]
any solution to this?  I am having the same issue after upgrading from .16 to .52.  Some users are able to login via LDAP and others get "user not found"

Seeing a lot of these errors in the logs:
31mLDAPSync ➔ error { [MongoError: E11000 duplicate key error index: rocketchat.users.$emails.address_1 dup key:

**Comment by richardwlu** [comment]
I have started receiving this on 0.55.0 also

**Comment by Hudell** [comment]
Did anybody run into this problem on newer versions?

**Comment by richardwlu** [comment]
@Hudell I'm on 0.63.3 and do not get this error anymore for LDAP, but I do get it for messages:

    WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: rocketchat.rocketchat_message index: _id_ dup key: { : \"KMnyxrmaFN9Zk3Jxp\" }","op":{"_id":"KMnyxrmaFN9Zk3Jxp","rid":"4dHzd9EJvLmBvpeSZWiyWd5Fm8sFWvgqYu","msg":"<removed>","ts":"2018-05-31T13:57:26.213Z","alias":"<removed>","u":{"_id":"WiyWd5Fm8sFWvgqYu","username":"nashaw","name":"Naome Shaw"},"mentions":[],"channels":[],"_updatedAt":"2018-05-31T13:57:26.215Z"}})
    at Function.MongoError.create (/var/www/rocket.chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/var/www/rocket.chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)
    at /var/www/rocket.chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:668:23
    at handleCallback (/var/www/rocket.chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:120:56)
    at resultHandler (/var/www/rocket.chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/ordered.js:421:14)
    at /var/www/rocket.chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by DiJu519** [comment]
@richardwlu @Hudell 

I'm hitting this as well.  I do have oplog enabled. 

Exception while invoking method 'sendMessage'

```
WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: rocketchat.rocketchat_message index: _id_ dup key: { : \"wHQFgpM2ebbLbSLRz\" }","op":
```

Since i've hit it 3 times, each time it takes down RC. Have to restart the container.

**Comment by ggazzo** [comment]
the ldap code has changed so many times that it is not possible to say that this still happens. If you have anything about it, open another new issue with updated infos ;)
