### ISSUE TITLE
No Previews working anymore

### ISSUE THREAD

**Issue by Ingwersaft** [RocketChat/Rocket.Chat#5090]
Your Rocket.Chat version: 0.46.0

Sometimes an exception pops up... (tried `http://www.zmescience.com/wp-content/uploads/2010/09/squirrel.jpg`):
```
chat_1          | Exception in defer callback: Error: Invalid protocol: null
chat_1          |   at Request.init (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:473:31)
chat_1          |   at new Request (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:142:8)
chat_1          |   at request (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/index.js:55:10)
chat_1          |   at getUrlContent (/app/bundle/programs/server/packages/rocketchat_oembed.js:127:12)
chat_1          |   at packages/meteor.js:212:23
chat_1          |   at Object.OEmbed.getUrlMeta (/app/bundle/programs/server/packages/rocketchat_oembed.js:177:13)
chat_1          |   at Object.OEmbed.getUrlMetaWithCache (/app/bundle/programs/server/packages/rocketchat_oembed.js:237:17)
chat_1          |   at /app/bundle/programs/server/packages/rocketchat_oembed.js:299:21
chat_1          |   at Array.forEach (native)
chat_1          |   at OEmbed.RocketUrlParser (/app/bundle/programs/server/packages/rocketchat_oembed.js:282:18)
chat_1          |   at /app/bundle/programs/server/packages/rocketchat_lib.js:340:24
chat_1          |   at Array.reduce (native)
chat_1          |   at Object.RocketChat.callbacks.run (/app/bundle/programs/server/packages/rocketchat_lib.js:335:8)
chat_1          |   at /app/bundle/programs/server/packages/rocketchat_lib.js:2550:33
chat_1          |   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
chat_1          |   at packages/meteor.js:445:45
chat_1          |   at runWithEnvironment (packages/meteor.js:1176:24)
```

...but sometimes not even an exception is thrown. It worked for us with an older, non-compose setup (I think 0.42 was used).

I have to use a http proxy, but curl on commandline inside the rocket chat image works just fine:
```
rocketchat@c83e70816703:/app/bundle$ curl -L https://www.zmescience.com/wp-content/uploads/2010/09/squirrel.jpg | head -n 10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    211      0 --:--:-- --:--:-- --:--:--   211
100   154  100   154    0     0    182      0 --:--:-- --:--:-- --:--:--   182
����HPhotoshop 3.08BIMn
[...]
```

Thanks in advance :)

**Comment by YuukanOO** [comment]
Same here but no exceptions.

**Comment by Ingwersaft** [comment]
Still broken in 0.47.0
```
Exception in defer callback:


Error: Invalid protocol: null
  at Request.init (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:473:31)
  at new Request (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:142:8)
  at request (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/index.js:55:10)
  at getUrlContent (/app/bundle/programs/server/packages/rocketchat_oembed.js:127:12)
  at packages/meteor.js:212:23
  at Object.OEmbed.getUrlMeta (/app/bundle/programs/server/packages/rocketchat_oembed.js:177:13)
  at Object.OEmbed.getUrlMetaWithCache (/app/bundle/programs/server/packages/rocketchat_oembed.js:237:17)
  at /app/bundle/programs/server/packages/rocketchat_oembed.js:299:21
  at Array.forEach (native)
  at OEmbed.RocketUrlParser (/app/bundle/programs/server/packages/rocketchat_oembed.js:282:18)
  at /app/bundle/programs/server/packages/rocketchat_lib.js:339:24
  at Array.reduce (native)
  at Object.RocketChat.callbacks.run (/app/bundle/programs/server/packages/rocketchat_lib.js:334:8)
  at /app/bundle/programs/server/packages/rocketchat_lib.js:2595:33
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at packages/meteor.js:445:45
  at runWithEnvironment (packages/meteor.js:1176:24)
```

**Comment by Ingwersaft** [comment]
Still broken in 0.49.0, but now I don't se exceptions at all :/
Curl-ing the image from inside the docker image still works

**Comment by Ingwersaft** [comment]
After some further investigation, it seems quotation marks around the proxy env variable are the issue.

```
echo $HTTP_PROXY                                                                                                                                                             
"http://proxy.internal.org:1234"
```
didn't work, but
```
echo $HTTP_PROXY                                                                                                                                                             
http://proxy.internal.org:1234
```
did.

Curl, wget and other tools don't have problems with this (also every http_proxy howto uses quotation marks).

**Comment by maxdwit** [comment]
This worked for me ( 0.50.1 Ubuntu snapd):
# systemctl edit snap.rocketchat-server.rocketchat-server.service
Paste your environment:
[Service]
Environment=HTTP_PROXY=http://myproxy:1234

# systemctl stop snap.rocketchat-server.rocketchat-server.service
# systemctl start snap.rocketchat-server.rocketchat-server.service

Embedded links to pictures/youtube/servers with a specific favicon are visible in a preview.

**Comment by MartinSchoeler** [comment]
Since the issue was resolved i will close this
