### ISSUE TITLE
Error upload avatar

### ISSUE THREAD

**Issue by quanticware** [RocketChat/Rocket.Chat#5121]
Your Rocket.Chat version: 0.46

Hello, 

I move my Rocket.Chat today from CentOS7 install to LXC Ubuntu 16.04. 

I have some problem to move mongodb. Backup work fine, but restore still with errors like this:

> 2016-12-05T18:47:58.904+0000Failed: rocketchat.assets.chunks: error creating indexes for  rocketchat.assets.chunks: createIndex error: The field 'w' is not valid for an index specification. Specification: { name: "files_id_1_n_1", ns: "rocketchat.assets.chunks", w: 1, key: { files_id: 1, n: 1 } }

And I can't connect to Rocket.Chat

So I deleted all file in backup/rocketchat who have problem to be restored.

And after Rocket.Chat works again!

But I loose all upload and avatars.

And now when I tried to uploads new avatar I have this error:

> [Mon Dec 05 2016 19:50:31 GMT+0000 (UTC)] ERROR MongoError: E11000 duplicate key error collection: rocketchat.avatars.chunks index: files_id_1_n_1 dup key: { : "Fred.jpg", : 0 }   at Function.MongoError.create (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)   at toError (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:115:22)   at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1046:67   at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18   at nextTickCallbackWith0Args (node.js:420:9)   at process._tickDomainCallback (node.js:390:13)  

What I can do?

Thanks!

**Comment by quanticware** [comment]
I find solution:

Connect to mongodb
`mongo`

`show databases`

`use rocketchat`

`show tables `

`db.avatars.chunks.find()`

Find the right ObjectId corresponding to my avatar.
And finally:
`db.avatars.chunks.remove({_id: ObjectId("57238ab6040b19394a0769c6") })`

Hope it helps.
