### ISSUE TITLE
SSL3_GET_RECORD:wrong version number sending any emails since upgrading past 0.37

### ISSUE THREAD

**Issue by vrooze** [RocketChat/Rocket.Chat#5182]
Your Rocket.Chat version: 0.47

We've had this issue for a while and I've done a log of searching.
Since we upgraded past 0.37 we get the error sending any email. Registration, notification and the admin "test" button all produce the error.

We're inside of a corporate LAN with an SMTP relay that requires not authentication.
I experimented with changing the user and password which only produced an invalid login error.

Below is the log file from the most recent upgrade till now.

[Logfile.txt](https://github.com/RocketChat/Rocket.Chat/files/646333/Logfile.txt)

**Comment by graywolf336** [comment]
Does your server have a valid SSL certificate chain?

**Comment by vrooze** [comment]
It's an internal server running rocket without SSL. Also the SMTP relay is running none SSL/TLS on port 25

**Comment by vrooze** [comment]
Just to update.

I have upgraded the server to 0.48.1 to fix the integration/webhook issue. problem still persists.
```
Exception in defer callback: Error: 139962357983040:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:../deps/openssl/openssl/ssl/s3_pkt.c:362:   
at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)   
at smtpSend (packages/email.js:108:37)   at Object.Email.send (packages/email.js:211:5)   
at /opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1438:14   
at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   
at packages/meteor.js:445:45  
at runWithEnvironment (packages/meteor.js:1176:24)      - - - - -    
at Error (native)  
```

**Comment by vrooze** [comment]
Just to update with a fresh screenshot of the actual error (which doesn't appear in the log, even with debug level logging)
(had to censor domain/email for company policy as it's internal)
![image](https://cloud.githubusercontent.com/assets/16898416/22425675/2ee466c2-e6f4-11e6-8440-3c4d091b38a0.png)

The only thing shown in the log with debug level is:
```
[34mI20170130-09:47:22.887(0) rocketchat_lib rocketchat_lib.js:1062 [34mMeteor ➔ method sendSMTPTestEmail -> userId: 5aBdc5Mq2XHXS54bJ , arguments:  {} 
[34mI20170130-09:47:22.890(0) Sending test email to user@domain.tld 
```

The same error posted originally crops up every now and then. I'm unable to trigger it at will so I'm assuming it's someones channel subscription:
```
[I20170130-13:49:27.542(0) Exception in defer callback: Error: 139667687495488:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:../deps/openssl/openssl/ssl/s3_pkt.c:362:  
at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)  
at smtpSend (packages/email.js:108:37)  
at Object.Email.send (packages/email.js:211:5)  
at /opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1577:14  
at [object Object]._.extend.withValue (packages/meteor.js:1122:17)  
at packages/meteor.js:445:45  
at runWithEnvironment (packages/meteor.js:1176:24)      - - - - -   
at Error (native) 
```

Running version **0.50.1**

**Comment by Zegorax** [comment]
Hello there,

I'm experiencing the same error, 1408F10B:SSL.

Is there any news regarding this problem ?

**Comment by vrooze** [comment]
new error I just spotted registering a new user:
```
[34mI20170329-09:14:05.312(1) Exception in defer callback: Error: Error trying to send email: 140348096288576:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:../deps/openssl/openssl/ssl/s3_pkt.c:362:  [error-email-send-failed]   
at/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:2955:13   
at[object Object]._.extend.withValue (packages/meteor.js:1122:17)   
atpackages/meteor.js:445:45   
atrunWithEnvironment (packages/meteor.js:1176:24)

**Comment by sscholl** [comment]
this issue was closed via #6940 in 0.56.0 FOR ME

Go to Administation->E-Mail->SMTP->Protocol (smtps)

**Comment by vrooze** [comment]
There is not Protocol option for me in the admin.
Host
Port
Username
Password
From Email
Test
Reset

**Comment by vrooze** [comment]
Update, still not working whatever I set.

It's an internal smtp relay with no credential.

I'm at a loss of why this doesn't work

**Comment by vrooze** [comment]
Had a chat with my server admin colleague and he had the awesome idea to setup postfix to relay to the relay. Sending the rocket to localhost works fine now.

Don't know what the issue is but I have worked around it.

Feel free to close this if I am the only person with the issue remaining.
