### ISSUE TITLE
Cannot read property 'onOplogEntry' of null (Database Bricked)

### ISSUE THREAD

**Issue by CzEMC** [RocketChat/Rocket.Chat#5257]
Your Rocket.Chat version: develop/f5023304c01fbf2e7e1a737801091b72ac50cb52 (Latest Commit when issue was created)

What is outputted:
```
=> Started proxy.                             
I20161219-07:55:04.222(-5)? Will load cache for users
I20161219-07:55:04.270(-5)? 37 records load from users
I20161219-07:55:04.271(-5)? Exception in callback of async function: TypeError: Cannot read property 'onOplogEntry' of null
I20161219-07:55:04.271(-5)?     at ModelsBaseCache.startOplog (packages/rocketchat:lib/server/models/_BaseCache.js:433:3)
I20161219-07:55:04.271(-5)?     at ModelsBaseCache.target.(anonymous function) [as startOplog] (packages/rocketchat:lib/server/models/_BaseCache.js:50:24)
I20161219-07:55:04.271(-5)?     at ModelsBaseCache.load (packages/rocketchat:lib/server/models/_BaseCache.js:423:8)
I20161219-07:55:04.272(-5)?     at meteorInstall.node_modules.meteor.rocketchat:lib.server.startup.cache.CacheLoad.js (packages/rocketchat:lib/server/startup/cache/CacheLoad.js:36:31)
I20161219-07:55:04.272(-5)?     at fileEvaluate (packages/modules-runtime.js:181:9)
I20161219-07:55:04.272(-5)?     at require (packages/modules-runtime.js:106:16)
I20161219-07:55:04.273(-5)?     at packages/rocketchat_lib/startup/defaultRoomTypes.coffee:62:1
I20161219-07:55:04.273(-5)?     at packages/rocketchat_lib/startup/defaultRoomTypes.coffee:62:1
I20161219-07:55:04.273(-5)?     at /home/rocket/Rocket.Chat/.meteor/local/build/programs/server/boot.js:295:34
I20161219-07:55:04.274(-5)?     at Array.forEach (native)
I20161219-07:55:04.274(-5)?     at Function._.each._.forEach (/home/rocket/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
I20161219-07:55:04.274(-5)?     at /home/rocket/Rocket.Chat/.meteor/local/build/programs/server/boot.js:128:5
I20161219-07:55:04.275(-5)?     at /home/rocket/Rocket.Chat/.meteor/local/build/programs/server/boot.js:344:5
I20161219-07:55:04.275(-5)?     at Function.run (/home/rocket/Rocket.Chat/.meteor/local/build/programs/server/profile.js:480:12)
I20161219-07:55:04.275(-5)?     at /home/rocket/Rocket.Chat/.meteor/local/build/programs/server/boot.js:343:11
```

When I upgraded from a previous version, and used the same database, this is what happened. Running rocket chat without using a previous database, will not cause the error. Possibly a migration problem?

Thanks for the help!

**Comment by CzEMC** [comment]
This is also the same issue that thiesschneider is having on #5212

**Comment by engelgabriel** [comment]
Let's keep the other issue only.
