### ISSUE TITLE
problem with "MONGO_OPLOG_URL=mongodb://localhost:27017/local"

### ISSUE THREAD

**Issue by Abraka** [RocketChat/Rocket.Chat#5300]
Your Rocket.Chat version:  0.48.2

Im trying setup a multiple rocket chat instances with infromation from rocket.chat docs and Im unable setup enviromental variable for main.js "MONGO_OPLOG_URL=mongodb://localhost:27017/local" which do I dont know what but with this variable Im not abble to start rocket.chat server:
root@Rocket.Chat]# ROOT_URL=http://localhost:3001/  MONGO_URL=mongodb://localhost:27017/rocketchat MONGO_OPLOG_URL=mongodb://localhost:27017/local PORT=3001 /usr/bin/node /opt/Rocket.Chat/main.js
/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: $MONGO_OPLOG_URL must be set to the 'local' database of a Mongo replica set
    at Error (native)
    at OplogHandle._startTailing (packages/mongo/oplog_tailing.js:218:13)
    at new OplogHandle (packages/mongo/oplog_tailing.js:76:8)
    at new MongoConnection (packages/mongo/mongo_driver.js:222:25)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)

https://rocket.chat/docs/installation/manual-installation/multiple-instances-to-improve-performance

**Comment by csmk** [comment]
You must create the replica set: https://rocket.chat/docs/installation/manual-installation/ubuntu#setup-mongodb-replica-set

**Comment by Abraka** [comment]
Thx, it works now.
