### ISSUE TITLE
internal server error * i cant save any operation any more *

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5362]
Your Rocket.Chat version: (0.48.2)
this happend today after update from 4.4 to 4.8.2
i cant save any operation any more and server stop 
if any user try to signup ,join room,any action ,,RC showing internal server error 
![2016-12-28_183514](https://cloud.githubusercontent.com/assets/22897987/21526399/8680a2c4-cd2c-11e6-9152-18e61cc29deb.png)
this my log
Exception while invoking method 'insertOrUpdateUser' MongoError: '$set' is empty                                                                                        . You must specify a field like so: {$set: {<field>: ...}}
  at Object.wait (/opt/Rocket.Chat.48.2/programs/server/node_modules/fibers/futu                                                                                        re.js:449:15)
  at MongoConnection.<anonymous> (packages/meteor.js:213:24)
  at MongoConnection.(anonymous function) [as update] (/opt/Rocket.Chat.48.2/pro                                                                                        grams/server/packages/mongo.js:766:49)
  at Object.<anonymous> (packages/matb33_collection-hooks.js:504:27)
  at Object.collection.(anonymous function) [as update] (packages/matb33_collect                                                                                        ion-hooks.js:146:21)
  at update (/opt/Rocket.Chat.48.2/programs/server/packages/mongo.js:4007:31)
  at Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as                                                                                        -user.js:325:19)
  at Object.RocketChat.saveUser (/opt/Rocket.Chat.48.2/programs/server/packages/                                                                                        rocketchat_lib.js:2525:16)
  at insertOrUpdateUser (/opt/Rocket.Chat.48.2/programs/server/packages/rocketch                                                                                        at_lib.js:9401:23)
  at methodsMap.(anonymous function) (/opt/Rocket.Chat.48.2/programs/server/pack                                                                                        ages/rocketchat_lib.js:1013:26)
  at maybeAuditArgumentChecks (/opt/Rocket.Chat.48.2/programs/server/packages/dd                                                                                        p-server.js:2108:12)
  at /opt/Rocket.Chat.48.2/programs/server/packages/ddp-server.js:1042:22
  at withValue (packages/meteor.js:1122:17)
  at /opt/Rocket.Chat.48.2/programs/server/packages/ddp-server.js:1041:43
  at withValue (packages/meteor.js:1122:17)
  at /opt/Rocket.Chat.48.2/programs/server/packages/ddp-server.js:1040:48
  at Session.method (/opt/Rocket.Chat.48.2/programs/server/packages/ddp-server.j                                                                                        s:1018:23)
  at /opt/Rocket.Chat.48.2/programs/server/packages/ddp-server.js:880:89

    - - - - -
  at Function.MongoError.create (/opt/Rocket.Chat.48.2/programs/server/npm/node_                                                                                        modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
  at toError (/opt/Rocket.Chat.48.2/programs/server/npm/node_modules/meteor/npm-                                                                                        mongo/node_modules/mongodb/lib/utils.js:115:22)
  at /opt/Rocket.Chat.48.2/programs/server/npm/node_modules/meteor/npm-mongo/nod                                                                                        e_modules/mongodb/lib/collection.js:1046:67
  at /opt/Rocket.Chat.48.2/programs/server/npm/node_modules/meteor/npm-mongo/nod                                                                                        e_modules/mongodb-core/lib/connection/pool.js:455:18
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by engelgabriel** [comment]
How are you running Rocket.Chat? Are you running our Docker Image? Did you fork and compiled it yourself?

**Comment by Nemra1** [comment]
@engelgabriel manual installation sir..from zip file
I'm using centos 6.x

**Comment by engelgabriel** [comment]
@RocketChat/core any ideas?

**Comment by antgel** [comment]
Closing as ancient.
