### ISSUE TITLE
Authentication with MongoDB

### ISSUE THREAD

**Issue by feraudet** [RocketChat/Rocket.Chat#5437]
Your Rocket.Chat version: 0.48.1

Hi,
I tried to upgrade from 0.35 to 0.48.1 but authentication with MongoDB seem not longer working : 
```
docker run --rm -e MONGO_URL="mongodb://rocketchat:XXXXXXXXXXX@mymongodbserver:27017" myregistry/rocketchat/web:0.48.1
/app/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: double colon in host identifier
    at module.exports (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:91:13)
    at connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:290:16)
    at Function.MongoClient.connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:114:3)
    at new MongoConnection (packages/mongo/mongo_driver.js:177:11)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
```

An idea ?

Regards,

Cyril

**Comment by engelgabriel** [comment]
What version of MongoDB are you using?

Can you check the URI with:

```
mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
```
https://docs.mongodb.com/manual/reference/connection-string/

**Comment by MartinSchoeler** [comment]
@feraudet have you solved the issue?

**Comment by engelgabriel** [comment]
@feraudet please reopen if the problem persists.
