### ISSUE TITLE
"Bad Request-400" : File upload through Amazon S3 not working

### ISSUE THREAD

**Issue by makeitcount** [RocketChat/Rocket.Chat#5512]
Your Rocket.Chat version: v0.48.2

I changed file storage from gridFS to amazon S3 following the [guide](https://rocket.chat/docs/administrator-guides/file-upload/amazon-s3). Before doing that I had created a user in amazon s3, giving permission to read and write on s3. In rocket chat admin, I had saved s3 bucket name, accesskey, secret id for this user. Now file upload is not working. When I upload a file, it shows "Bad Request - 400".

P.S.
I recently had upgraded rocket chat version from v0.23.0 to v0.48.2. Since then occasionally I am getting following error. It may or may not be related to this but I couldn't figure out what exactly triggered this error
```
 Exception from sub stream-notify-all id 7rqxAAjm5R9XCG4DQ 
Error: Match error: Expected string, got null   at exports.check (packages/check.js:57:15)   
at Subscription.<anonymous> (/app/bundle/programs/server/packages/rocketchat_streamer.js:449:5)   
at Subscription.<anonymous> (/app/bundle/programs/server/packages/rocketchat_lib.js:1032:15)   
at packages/matb33_collection-hooks.js:307:21   
at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   
at Subscription._handler (packages/matb33_collection-hooks.js:306:28)   
at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:2108:12)   
at Subscription._runHandler (/app/bundle/programs/server/packages/ddp-server.js:1382:19)   
at Session._startSubscription (/app/bundle/programs/server/packages/ddp-server.js:1192:11)   
at Session.sub (/app/bundle/programs/server/packages/ddp-server.js:946:14)   
at /app/bundle/programs/server/packages/ddp-server.js:880:89  
[34mI20170111-18:67:17.730(0) Sanitized and reported to the client as: Match failed [400] 
[34mI20170111-18:67:17.731(0) undefined undefined 
```

**Comment by engelgabriel** [comment]
can you share your configuration and URL with our team privately so we can investigate?

**Comment by engelgabriel** [comment]
Please reopen the issue with more info if the problem persists

**Comment by mayaa6** [comment]
Has this problem solved?

**Comment by makeitcount** [comment]
@mayaa6 not yet. Did not have time to work on it.
