### ISSUE TITLE
Oauth Exception while invoking method 'login' 

### ISSUE THREAD

**Issue by adeviadoug** [RocketChat/Rocket.Chat#5536]
Your Rocket.Chat version: 0.49

Error message:

```
34mI20170112-21:42:02.760(0) Exception while invoking method 'login' TypeError: fun is not a function   at Resultset.find (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:2197:17)   at Resultset.findAnd (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:1965:14)   
```

**Comment by geekgonecrazy** [comment]
Also happens with Facebook.  Seems to be related to trying to hit a method not present in the caching layer.

More detailed log.  Though the above was probably enough :)
```
[34mI20170112-22:57:48.244(0) Exception while invoking method 'login' TypeError: fun is not a function   at Resultset.find (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:2197:17)   at Resultset.findAnd (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:1965:14)   at Resultset.find (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:2038:53)   at new Resultset (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:1462:21)   at LokiEventEmitter.Collection.findOne (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:4232:20)   at ModelsBaseCache.findOne (/app/bundle/programs/server/packages/rocketchat_lib.js:7965:60)   at ModelsBaseCache.target.(anonymous function) [as findOne] (/app/bundle/programs/server/packages/rocketchat_lib.js:7066:30)   at ModelsBaseCache.update (/app/bundle/programs/server/packages/rocketchat_lib.js:8241:66)   at ModelsBaseCache.target.(anonymous function) [as update] (/app/bundle/programs/server/packages/rocketchat_lib.js:7066:30)   at ModelsBaseDb.<anonymous> (/app/bundle/programs/server/packages/rocketchat_lib.js:7690:14)   at emitOne (events.js:77:13)   at ModelsBaseDb.emit (events.js:169:7)   at ModelsBaseDb.update (/app/bundle/programs/server/packages/rocketchat_lib.js:8635:11)   at ModelUsers.update (/app/bundle/programs/server/packages/rocketchat_lib.js:3569:36)   at ModelUsers.setEmailVerified (/app/bundle/programs/server/packages/rocketchat_lib.js:6755:17)   at AccountsServer.Accounts.updateOrCreateUserFromExternalService (/app/bundle/programs/server/app/app.js:4505:31)   at [object Object].<anonymous> (packages/accounts-oauth.js:133:21)   at /app/bundle/programs/server/packages/accounts-base.js:938:30   at tryLoginMethod (/app/bundle/programs/server/packages/accounts-base.js:763:14)   at AccountsServer.Ap._runLoginHandlers (/app/bundle/programs/server/packages/accounts-base.js:937:18)   at [object Object].methods.login (/app/bundle/programs/server/packages/accounts-base.js:994:27)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:2108:12)   at /app/bundle/programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:1040:48   at Session.method (/app/bundle/programs/server/packages/ddp-server.js:1018:23)   at /app/bundle/programs/server/packages/ddp-server.js:880:89  
```

**Comment by esolix** [comment]
#5516 #5519 same issues reported - was refered to #5511

**Comment by geekgonecrazy** [comment]
@esolix thanks for pointing that out.  Yeah actually 2 different errors. :smile: Might be able to be consolidated i'm not sure

**Comment by geekgonecrazy** [comment]
@rodrigok on this one i've tried removing the Google oauth, rebooting and then re-adding.  Thought maybe it was a migration gone bad.  But didn't work.  Verified on several hosts if you need one ping me, let me know and I can give you credentials to login and poke around.

**Comment by rodrigok** [comment]
@geekgonecrazy I can't reproduce this error locally. Can you help me?

**Comment by IQ2022** [comment]
i have this issue on my instance.. it has worked perfectly until i upgraded from 48.1

**Comment by engelgabriel** [comment]
@IQ2022 what is the URL for us to test?

**Comment by IQ2022** [comment]
i will private message it to you..

**Comment by IQ2022** [comment]
I should also add that Twitter still works, two that have failed google and facebook.. oddly enough facebook worked only once with a first time registration, then was unable to login again..

**Comment by IQ2022** [comment]
can we please put some work on this one asap, i think we will have many users will be locked out..  am sure this is not just impacting my instance.. a lot of users use SSO for ease of sign up..

**Comment by Perksls** [comment]
just adding that my custom oAuth also stopped working with the same error #5519

**Comment by adeviadoug** [comment]
fwiw, I submitted this ticket because our users are now locked out if they logout from their instance.

**Comment by IQ2022** [comment]
its bad i know.. :( sorry

**Comment by rackmuthu** [comment]
How to authenticate rocket chat user by using the keycloak through the rocket chat Rest API
