### ISSUE TITLE
i cant start setup developer version !

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5636]
Your Rocket.Chat version: ( latest)

start to clone 
git clone https://github.com/RocketChat/Rocket.Chat.git
cd Rocket.Chat
meteor npm start 
===================================
 meteor --allow-superuser 

`Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

/root/rc/Rocket.Chat/packages/rocketchat-livechat/plugin/build.sh: line 8: 10191 Killed                  meteor build --headless --directory $BUILD_DIR
cp: cannot stat `../build/bundle/programs/web.browser/*.css': No such file or directory
cp: cannot stat `../build/bundle/programs/web.browser/*.js': No such file or directory
cp: cannot stat `../build/bundle/programs/web.browser/head.html': No such file or directory
Unexpected mongo exit code null. Restarting.
/root/.meteor/packages/less/.2.7.8.dkh9w8++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: Builder can not write without either data or a file path or a symlink path: os/packages/rocketchat_livechat/public/head.html
    at Builder.write (/tools/isobuild/builder.js:259:13)
    at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:390:10)
    at /tools/isobuild/isopack.js:1388:21
    at Array.forEach (native)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack.js:1381:11
    at Array.forEach (native)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack.js:1271:9
    at Isopack.saveToPath (/tools/isobuild/isopack.js:1191:9)
    at /tools/isobuild/isopack-cache.js:378:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:315:18)
    at /tools/isobuild/isopack-cache.js:249:16
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:248:17
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:809:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:808:18)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/runners/run-app.js:549:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:548:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:617:35)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
root@server [~/rc/Rocket.Chat]#
`
what can i do !

**Comment by graywolf336** [comment]
Use a different user other than root to build.

**Comment by Nemra1** [comment]
idont have any another user..just root account

**Comment by graywolf336** [comment]
Then create one, meteor doesn't allow you to build and run as root.

**Comment by Nemra1** [comment]
@graywolf336 Thx u.. im trying now

**Comment by Nemra1** [comment]
another error


=> Started proxy.
=> Started MongoDB.
=> Exited from signal: SIGKILL
=> Exited from signal: SIGKILL
=> Exited from signal: SIGKILL
=> Your application is crashing. Waiting for file change.
Unexpected mongo exit code null. Restarting.
sh: line 1: 29870 Killed                  meteor

npm ERR! Linux 2.6.32-042stab105.14
npm ERR! argv "/home/livenemra1/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/livenemra1/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "start"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! Rocket.Chat@0.49.3 start: `meteor npm i && meteor`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the Rocket.Chat@0.49.3 start script 'meteor npm i && meteor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Rocket.Chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor npm i && meteor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Rocket.Chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Rocket.Chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/livenemra1/Rocket.Chat-0.49.3/npm-debug.log

**Comment by codyx** [comment]
FYI, it **is** actually possible to run meteor build using the root user. 
Make sure you've set METEOR_ALLOW_SUPER_USER to true and you may follow some instructions displayed on your prompt.
