### ISSUE TITLE
Cannot set a WebHook Integration for a user

### ISSUE THREAD

**Issue by danimaiochi** [RocketChat/Rocket.Chat#5690]
When I'm configuring a WebHook Integration, the second field (Channel) says I can specify an user, but when I do (or use the all_direct_messages suggested), it gives me the following error:
Exception in callback of async function: Error: [invalid-channel]
  at retrieveDirectMessageInfo (/opt/RocketChat/programs/server/packages/rocketchat_integrations.js:1515:9)
  at processWebhookMessage (/opt/RocketChat/programs/server/packages/rocketchat_integrations.js:1567:12)
  at sendMessage (/opt/RocketChat/programs/server/packages/rocketchat_integrations.js:1266:22)
  at /opt/RocketChat/programs/server/packages/rocketchat_integrations.js:1318:9
  at runWithEnvironment (packages/meteor.js:1176:24)

Rocket.Chat server version: 0.49.3
Number of instances: 1

**Comment by graywolf336** [comment]
This was fixed recently
