### ISSUE TITLE
After upgrade to 0.49.3 recieving many exception erros

### ISSUE THREAD

**Issue by drickerusa** [RocketChat/Rocket.Chat#5696]
Rocket.Chat Version: 0.49.3 
Running Instances: 4
DB Replicaset OpLog: Yes

After the upgrade from 0.48.1 to 0.49.3 I'm getting tons of these types of exception errors. 
Exception from sub stream-notify-room id SsTshpowBLCsvh6qF
```
TypeError: Cannot read property 't' of undefined
  at Subscription.<anonymous> (/home/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_lib.js:3345:15)
  at Streamer.isReadAllowed (/home/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_streamer.js:326:38)
  at Subscription.<anonymous> (/home/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_streamer.js:457:16)
  at Subscription.<anonymous> (/home/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1048:15)
  at packages/matb33_collection-hooks.js:307:21
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
  at maybeAuditArgumentChecks (/home/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:2108:12)
  at Subscription._runHandler (/home/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:1382:19)
  at Session._startSubscription (/home/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:1192:11)
  at Session.sub (/home/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:946:14)
  at /home/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:880:89

A few of these:
Exception in defer callback:
```
TypeError: Cannot read property 'id' of undefined
  at SlackBridge.postDeleteMessageToSlack (/home/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_slackbridge.js:1594:54)
  at SlackBridge.onRocketMessageDelete (/home/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_slackbridge.js:1461:9)
  at /home/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_lib.js:339:24
  at Array.reduce (native)
  at Object.RocketChat.callbacks.run (/home/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_lib.js:334:8)
  at /home/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_lib.js:2235:25
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at packages/meteor.js:445:45
  at runWithEnvironment (packages/meteor.js:1176:24)

and one of these:
Exception in setTimeout callback:
```
RangeError: Maximum call stack size exceeded

**Comment by drickerusa** [comment]
Never mind on the slackbridge error. I think we have that one taken care of. But the initial one is concerning.

**Comment by rodrigok** [comment]
@drickerusa Is that happening on server or your browser?

**Comment by drickerusa** [comment]
This is the exception log I configured to send to a channel. So in my browser.

**Comment by engelgabriel** [comment]
@drickerusa but it is the server log, right?

**Comment by drickerusa** [comment]
@engelgabriel I assume so. I configure in the Logs under settings. I set the log level=2 I don't show the package or the file and line and send the Log Exceptions to a channel that I have named the same.

**Comment by drickerusa** [comment]
@engelgabriel since I fixed the oplog url I have not seen anymore of these exceptions.

**Comment by engelgabriel** [comment]
Keeps us informed, thanks.
