### ISSUE TITLE
meteor npm run chimp-test errors

### ISSUE THREAD

**Issue by thinkingmik** [RocketChat/Rocket.Chat#5815]
**0.50.0-develop**
Running Instances: 1

We are developing on a fork of 0.50.0-develop
and when we launch the test cases with command
```
meteor npm run chimp-test 
```
with env variables set:
```
env:
  global:
  - MONGO_OPLOG_URL: "mongodb://localhost:27017/local"
  - MONGO_URL: "mongodb://localhost:27017/meteor"
  - TEST_MODE: "true"
```

sometimes we get test errors (with the same code), for example:
```
1) User Creation create user:
     Error: An element could not be located on the page using the given search parameters.
      at LoginPage.gotToRegister (tests/pageobjects/login.page.js:26:23)
      at Context.<anonymous> (tests/steps/03-user-creation.js:49:13)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

2) Main Elements Render "before all" hook:
     Error: An element could not be located on the page using the given search parameters ("[name=emailOrUsername]").
      at LoginPage.login (tests/pageobjects/login.page.js:52:29)
      at checkIfUserIsValid (tests/data/checks.js:26:13)
      at Context.<anonymous> (tests/steps/04-main-elements-render.js:14:3)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

 3) Channel creation "before all" hook:
     Error: An element could not be located on the page using the given search parameters ("[name=emailOrUsername]").
      at LoginPage.login (tests/pageobjects/login.page.js:52:29)
      at checkIfUserIsValid (tests/data/checks.js:26:13)
      at Context.<anonymous> (tests/steps/05-channel-creation.js:14:3)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
...
```
Why it happens?

Thanks.

**Comment by MartinSchoeler** [comment]
@thinkingmik 
* Do these errors show up every time you run the tests?
* Have you made any modifications to the ui?

**Comment by engelgabriel** [comment]
Please upgrade to the latest version 0.51.0-develop

**Comment by thinkingmik** [comment]
With the upgrade to 0.51.0-develop the unit tests seems to work! thank you very much @engelgabriel  @MartinSchoeler
