### ISSUE TITLE
Unable to start instance after OPLOG enable

### ISSUE THREAD

**Issue by quanticware** [RocketChat/Rocket.Chat#5929]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.5

Hello, 
When I try to activate OPLOG I have problem. My RocketChat is already in production since version 0.27

What I do:
mongo is already with oplog like see in doc.
```
001-rs:PRIMARY> rs.printReplicationInfo()
configured oplog size:   2583.4501953125MB
log length start to end: 1707858secs (474.41hrs)
oplog first event time:  Wed Jan 18 2017 15:07:39 GMT+0000 (UTC)
oplog last event time:   Tue Feb 07 2017 09:31:57 GMT+0000 (UTC)
now:                     Tue Feb 07 2017 09:31:58 GMT+0000 (UTC) 

```
In rocketchat systemctl file:
```
#Environment=MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=https://xxxxxxxx/ PORT=3000
Environment=MONGO_OPLOG_URL=mongodb://localhost:27017/rocketchat?replicaSet=001-rs ROOT_URL=https://xxxxxxxx/ PORT=3000
```

I restarted my rocketchat and:

```
● rocketchat.service - The Rocket.Chat  server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-02-07 09:42:02 UTC; 1s ago
  Process: 30215 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 30215 (code=exited, status=1/FAILURE)

Feb 07 09:42:02 web-rocketchat rocketchat[30215]:     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
Feb 07 09:42:02 web-rocketchat rocketchat[30215]:     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
Feb 07 09:42:02 web-rocketchat rocketchat[30215]:     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
Feb 07 09:42:02 web-rocketchat rocketchat[30215]:     at fileEvaluate (packages/modules-runtime.js:188:9)
Feb 07 09:42:02 web-rocketchat rocketchat[30215]:     at require (packages/modules-runtime.js:111:16)
Feb 07 09:42:02 web-rocketchat rocketchat[30215]:     at /opt/Rocket.Chat/programs/server/packages/accounts-base.js:1972:15
Feb 07 09:42:02 web-rocketchat rocketchat[30215]:     at /opt/Rocket.Chat/programs/server/packages/accounts-base.js:1983:3
Feb 07 09:42:02 web-rocketchat systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 09:42:02 web-rocketchat systemd[1]: rocketchat.service: Unit entered failed state.
Feb 07 09:42:02 web-rocketchat systemd[1]: rocketchat.service: Failed with result 'exit-code'.

```

I need to back to comment OPLOG variable and uncomment standard variable to retrieve my Rocketchat instance.

What I Can do?
Thanks,

**Comment by engelgabriel** [comment]
It should be 
```
Environment=MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=001-rs ROOT_URL=https://xxxxxxxx/ PORT=3000
```

**Comment by engelgabriel** [comment]
The `MONGO_OPLOG_URL` must always point the `local` database.

**Comment by quanticware** [comment]
I changed to .
`Environment=MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=001-rs ROOT_URL=https://xxxxxxxx/ PORT=3000`

And now:
```
● rocketchat.service - The Rocket.Chat  server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-02-07 15:29:11 UTC; 2s ago
  Process: 31526 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 31526 (code=exited, status=1/FAILURE)

Feb 07 15:29:11 web-rocketchat rocketchat[31526]:     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
Feb 07 15:29:11 web-rocketchat rocketchat[31526]:     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
Feb 07 15:29:11 web-rocketchat rocketchat[31526]:     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
Feb 07 15:29:11 web-rocketchat rocketchat[31526]:     at fileEvaluate (packages/modules-runtime.js:188:9)
Feb 07 15:29:11 web-rocketchat rocketchat[31526]:     at require (packages/modules-runtime.js:111:16)
Feb 07 15:29:11 web-rocketchat rocketchat[31526]:     at /opt/Rocket.Chat/programs/server/packages/accounts-base.js:1972:15
Feb 07 15:29:11 web-rocketchat rocketchat[31526]:     at /opt/Rocket.Chat/programs/server/packages/accounts-base.js:1983:3
Feb 07 15:29:11 web-rocketchat systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 15:29:11 web-rocketchat systemd[1]: rocketchat.service: Unit entered failed state.
Feb 07 15:29:11 web-rocketchat systemd[1]: rocketchat.service: Failed with result 'exit-code'.
```
Surprise! Same problem.

Sorry...
