### ISSUE TITLE
Can't create user

### ISSUE THREAD

**Issue by Exentriq** [RocketChat/Rocket.Chat#594]
After a fresh install of rocket.chat on a Ubuntu server (using these instruction: https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker), I can't create a new user (the first one).

This  is the error:
>Exception while invoking method 'registerUser' Error: getaddrinfo ENOTFOUND
    at Object.Future.wait (/var/www/rocket.chat/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at smtpSend (packages/email/email.js:76:1)
    at Object.Email.send (packages/email/email.js:153:1)
    at Object.Email.send (packages/meteorhacks:kadira/lib/hijack/email.js:10:1)
    at Object.Accounts.sendVerificationEmail (packages/accounts-password/password_server.js:627:1)
    at [object Object].Meteor.methods.registerUser (server/methods/registerUser.coffee:14:13)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:164:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    - - - - -
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

and if I try to create a new one with the same email, the web interface say:"Email already exists", but if I try to sign in, the web interface return the user not found error.

> MongoDB shell version: 2.6.11
node --version
v0.10.40

**Comment by marceloschmidt** [comment]
Is this still an issue? Have you followed the tutorial exactly? Have you configured anything related to e-mail, as this seems to be the problem?

**Comment by marceloschmidt** [comment]
Closing for lack of information.

**Comment by seeb0h** [comment]
I had the issue. Related to error in sending confirmation mail
You need to set a correct export MAIL_URL.
