### ISSUE TITLE
OEmbed duplicated record error while importing from slack

### ISSUE THREAD

**Issue by rvion** [RocketChat/Rocket.Chat#5950]
Just got this error too while importing from stack

```shell
OEmbed duplicated record https://docs.google.com/forms/d/e/xxxxxxxxx/viewform
Exception in callback of async function: RangeError: Invalid array buffer length
  at new ArrayBuffer (native)
  at new Uint8Array (native)
  at createBuffer (buffer.js:25:17)
  at allocate (buffer.js:166:12)
  at new Buffer (buffer.js:56:12)
  at read (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs/grid_store.js:788:38)
  at GridStore.read (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs/grid_store.js:775:44)
  at GridReadStream._push (/app/bundle/programs/server/npm/node_modules/meteor/jalik_ufs-gridfs/node_modules/gridfs-stream/lib/readstream.js:181:17)
  at GridReadStream._read (/app/bundle/programs/server/npm/node_modules/meteor/jalik_ufs-gridfs/node_modules/gridfs-stream/lib/readstream.js:156:8)
  at GridReadStream.Readable.read (_stream_readable.js:336:10)
  at readableAddChunk (_stream_readable.js:154:18)
  at GridReadStream.Readable.push (_stream_readable.js:111:10)
  at /app/bundle/programs/server/npm/node_modules/meteor/jalik_ufs-gridfs/node_modules/gridfs-stream/lib/readstream.js:190:28
  at read (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs/grid_store.js:801:12)
  at GridStore.read (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs/grid_store.js:775:44)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs/grid_store.js:817:12
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs/grid_store.js:1197:5
  at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:95:56)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1405:5
  at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:95:56)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor.js:674:5
  at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:171:5)
  at nextFunction (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:683:5)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:594:7
  at queryCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:253:5)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18
  at nextTickCallbackWith0Args (node.js:436:9)
  at process._tickDomainCallback (node.js:406:13)
```

I just deployed rocket.chat today with docker so it used latest images

```shell
➔ System ➔ startup
➔ +----------------------------------------------+
➔ |                SERVER RUNNING                |
➔ +----------------------------------------------+
➔ |                                              |
➔ |  Rocket.Chat Version: 0.50.1                 |
➔ |       NodeJS Version: 4.7.3 - x64            |
➔ |             Platform: linux                  |
➔ |         Process Port: 3000                   |
➔ |             Site URL: http://localhost:3000  |
➔ |     ReplicaSet OpLog: Disabled               |
➔ |          Commit Hash: 448fce0e91             |
➔ |        Commit Branch: HEAD                   |
➔ |                                              |
➔ +----------------------------------------------+
```

I don't find any way to recover from this issue. restarting the rocket.chat or mongdo db doens't solve the problem

it seems to be linked to https://github.com/RocketChat/Rocket.Chat/issues/1227, but this issue has been closed after this fix attempt: https://github.com/RocketChat/Rocket.Chat/pull/3123/commits/db7283a6b935afecbb90a6ebda7a0671671e150b

I think the error is still present since the duplicated record problem crashed rocket.chat and since it now prevents it from restarting

what could I do to recover from here ?

**Comment by engelgabriel** [comment]
@rvion can you try to upgrade to `0.51.0`?

**Comment by pierre-lehnen-rc** [comment]
Closing this as obsolete.
