### ISSUE TITLE
Updates to messages is not saved

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#6062]
Rocket.Chat Version: 0.53.0-develop
Running Instances: 3
DB Replicaset OpLog:YES
Node Version: 4.7.3

Happening on demo server now.

A 5 line message is edited, appears to be updated locally,  but on a refresh shows that message is not updated.

Chrome console log:

![screen shot 2017-02-15 at 5 58 43 pm](https://cloud.githubusercontent.com/assets/122633/22999366/f4423d34-f3a8-11e6-9b0a-309293cc3168.png)

Server side log:

```
[34mI20170215-22:58:10.357(0) Exception while invoking method 'updateMessage' TypeError: Cannot read property '_id' of undefined   at /var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:11822:48   at /var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:393:24   at Array.reduce (native)   at Object.RocketChat.callbacks.run (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:386:8)   at Object.RocketChat.updateMessage (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:3678:33)   at [object Object].Meteor.methods.updateMessage (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:13025:21)   at [object Object].methodsMap.(anonymous function) (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:1089:26)   at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira.js:2731:30)   at maybeAuditArgumentChecks (/var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:1817:12)   at /var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:876:21)   at packages/meteorhacks_kadira.js:2619:38   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at [object Object].sessionProto.protocol_handlers.method (packages/meteorhacks_kadira.js:2618:44)   at /var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:755:85  
```

**Comment by TheReal1604** [comment]
Got this also on a 0.51.0 deployment with oplog.. but only for one specific message in a new created channel. Crazy.

**Comment by localguru** [comment]
Can't reproduce that with 0.52.0

**Comment by MartinSchoeler** [comment]
@Sing-Li Have you seen this bug lately?
