### ISSUE TITLE
Exception from sub stream-notify-room id xbF987z4TEdggpCnu

### ISSUE THREAD

**Issue by lhaig** [RocketChat/Rocket.Chat#6140]
Rocket.Chat Version: 0.52.0 - Docker image
Running Instances: 1
DB Replicaset OpLog: Enabled 
Node Version: 4.7.3

Firstly thank you for a great project. and for enabling it to send errors to a channel :-)

I have been getting a few of these errors in my logs. Is this something that I should be aware of and resolve or is this normal?

```
Exception from sub stream-notify-room id xbF987z4TEdggpCnu

TypeError: Cannot read property 'indexOf' of undefined
  at Subscription.<anonymous> (/app/bundle/programs/server/packages/rocketchat_lib.js:3496:28)
  at Streamer.isReadAllowed (/app/bundle/programs/server/packages/rocketchat_streamer.js:326:38)
  at Subscription.<anonymous> (/app/bundle/programs/server/packages/rocketchat_streamer.js:457:16)
  at Subscription.<anonymous> (/app/bundle/programs/server/packages/rocketchat_lib.js:1083:15)
  at packages/matb33_collection-hooks.js:307:21
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
  at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:2108:12)
  at Subscription._runHandler (/app/bundle/programs/server/packages/ddp-server.js:1382:19)
  at Session._startSubscription (/app/bundle/programs/server/packages/ddp-server.js:1192:11)
  at Session.sub (/app/bundle/programs/server/packages/ddp-server.js:946:14)
  at /app/bundle/programs/server/packages/ddp-server.js:880:89
```

**Comment by juanrhino** [comment]
+1 I'm getting the same error over and over

**Comment by geekgonecrazy** [comment]
We get this as well:

```
TypeError: Cannot read property 't' of undefined
  at [object Object].<anonymous> (/app/bundle/programs/server/packages/rocketchat_lib.js:3934:12)
  at Streamer.isReadAllowed (/app/bundle/programs/server/packages/rocketchat_streamer.js:343:38)
  at [object Object].<anonymous> (/app/bundle/programs/server/packages/rocketchat_streamer.js:478:16)
  at [object Object].<anonymous> (/app/bundle/programs/server/packages/rocketchat_lib.js:1047:15)
  at packages/matb33_collection-hooks.js:307:21
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
  at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1823:12)
  at [object Object]._.extend._runHandler (/app/bundle/programs/server/packages/ddp-server.js:1174:17)
  at [object Object]._.extend._startSubscription (/app/bundle/programs/server/packages/ddp-server.js:1022:9)
  at [object Object]._.extend.protocol_handlers.sub (/app/bundle/programs/server/packages/ddp-server.js:817:12)
  at /app/bundle/programs/server/packages/ddp-server.js:755:85
```

Only difference being `Cannot read property 't' of undefined` instead of `Cannot read property 'indexOf' of undefined`

**Comment by MartinSchoeler** [comment]
Could this be happening because of the coffeescript conversions?

**Comment by lhaig** [comment]
I have had the same errors after my initial one
`TypeError: Cannot read property 't' of undefined
  at [object Object].<anonymous> (/app/bundle/programs/server/packages/rocketchat_lib.js:3912:15)
  at Streamer.isReadAllowed (/app/bundle/programs/server/packages/rocketchat_streamer.js:343:38)
  at [object Object].<anonymous> (/app/bundle/programs/server/packages/rocketchat_streamer.js:478:16)
  at [object Object].<anonymous> (/app/bundle/programs/server/packages/rocketchat_lib.js:1088:15)
  at packages/matb33_collection-hooks.js:307:21
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
  at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1823:12)
  at [object Object]._.extend._runHandler (/app/bundle/programs/server/packages/ddp-server.js:1174:17)
  at [object Object]._.extend._startSubscription (/app/bundle/programs/server/packages/ddp-server.js:1022:9)
  at [object Object]._.extend.protocol_handlers.sub (/app/bundle/programs/server/packages/ddp-server.js:817:12)
  at /app/bundle/programs/server/packages/ddp-server.js:755:85`

**Comment by geekgonecrazy** [comment]
@MartinSchoeler i'm not sure.  I haven't been able to spend the time to track it down to see where this is happening in the code.  But i'd say its likely

**Comment by webus** [comment]
is there any news ?

**Comment by aventrax** [comment]
Same here, it seems related to #7258 ..
I have Oplog with 2 instances. The error goes away shutting down the primary instance.

**Comment by lhaig** [comment]
I am closing this as I no longer support that server
