### ISSUE TITLE
Rocket.Chat Docker container crashs every day on the same time

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#6143]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Enabled

My Rocket.Chat Instance inside a docker container is crashing every day on 10:27 (UTC+1). Its exactly happen on the same time. The mongodb is on version 3.2 and is running also in a docker container - but is not affected by this issue. (dont crash)

Here is the stacktrace from the docker logfile:

```
2017-02-22T10:27:08.765271637Z FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
2017-02-22T10:27:08.765289393Z
2017-02-22T10:27:08.765318941Z <--- Last few GCs --->
2017-02-22T10:27:08.765327021Z
2017-02-22T10:27:08.765333434Z 86399979 ms: Mark-sweep 972.5 (1457.4) -> 974.8 (1457.4) MB, 206.5 / 0 ms [allocation failure] [scavenge might not succeed].
2017-02-22T10:27:08.765341447Z 86400179 ms: Mark-sweep 974.8 (1457.4) -> 972.5 (1457.4) MB, 200.5 / 0 ms [allocation failure] [scavenge might not succeed].
2017-02-22T10:27:08.765348951Z 86400389 ms: Mark-sweep 972.5 (1457.4) -> 974.0 (1457.4) MB, 209.6 / 0 ms [last resort gc].
2017-02-22T10:27:08.765355853Z 86400606 ms: Mark-sweep 974.0 (1457.4) -> 972.5 (1457.4) MB, 217.5 / 0 ms [last resort gc].
2017-02-22T10:27:08.765377021Z
2017-02-22T10:27:08.765395813Z
2017-02-22T10:27:08.765402510Z <--- JS stacktrace --->
2017-02-22T10:27:08.765408741Z
2017-02-22T10:27:08.765414454Z ==== JS stack trace =========================================
2017-02-22T10:27:08.765420557Z
2017-02-22T10:27:08.765425872Z Security context: 0x2e25c05b4629 <JS Object>
2017-02-22T10:27:08.765431396Z     1: slowToString [buffer.js:421] [pc=0x2ad54c4c1595] (this=0x3d708b4f3a71 <an Uint8Array with map 0x352872304941>,encoding=0x2e25c05bd761 <String[4]: utf8>,start=3375341,end=3691682)
2017-02-22T10:27:08.765439141Z     2: /* anonymous */(aka /* anonymous */) [/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/deserializer.js:~39] [pc=0x2ad54c25c6c6] (this=0x2e25c05041b9 <undefin...
2017-02-22T10:27:08.765446417Z
```

```
2017-02-23T10:27:05.909102584Z FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
2017-02-23T10:27:05.909122938Z
2017-02-23T10:27:05.909142643Z <--- Last few GCs --->
2017-02-23T10:27:05.909150810Z
2017-02-23T10:27:05.909157373Z 86395520 ms: Mark-sweep 955.7 (1457.4) -> 955.7 (1457.4) MB, 149.4 / 0 ms [allocation failure] [scavenge might not succeed].
2017-02-23T10:27:05.909163778Z 86395668 ms: Mark-sweep 955.7 (1457.4) -> 955.8 (1457.4) MB, 147.8 / 0 ms [allocation failure] [scavenge might not succeed].
2017-02-23T10:27:05.909170032Z 86395829 ms: Mark-sweep 955.8 (1457.4) -> 955.7 (1457.4) MB, 160.8 / 0 ms [last resort gc].
2017-02-23T10:27:05.909175852Z 86395990 ms: Mark-sweep 955.7 (1457.4) -> 955.8 (1457.4) MB, 160.6 / 0 ms [last resort gc].
2017-02-23T10:27:05.909182874Z
2017-02-23T10:27:05.909188984Z
2017-02-23T10:27:05.909195357Z <--- JS stacktrace --->
2017-02-23T10:27:05.909201224Z
2017-02-23T10:27:05.909207087Z ==== JS stack trace =========================================
2017-02-23T10:27:05.909234952Z
2017-02-23T10:27:05.909245665Z Security context: 0x21a433cb4629 <JS Object>
2017-02-23T10:27:05.909252724Z     1: slowToString [buffer.js:421] [pc=0x1ae5f77292d5] (this=0x2bd460b95b29 <an Uint8Array with map 0x3a19aa304941>,encoding=0x21a433cbd761 <String[4]: utf8>,start=2127477,end=2443818)
2017-02-23T10:27:05.909259130Z     2: /* anonymous */(aka /* anonymous */) [/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/deserializer.js:~39] [pc=0x1ae5f782aa06] (this=0x21a433c041b9 <undefin...
2017-02-23T10:27:05.909263931Z
```

**Comment by imtrobin** [comment]
I have similar issues since upgrading to 0.52.0, my instance dies every morning and I have to reboot to restart it.

**Comment by imtrobin** [comment]
Not sure if this is related, but this is from my log from Admin View Logs

Will load cache for rocketchat_subscription 
[34mI20170311-02:25:05.981(0) 632 records load from rocketchat_subscription 
[34mI20170311-02:25:05.982(0) Will load cache for rocketchat_settings 
[34mI20170311-02:25:06.016(0) 458 records load from rocketchat_settings 
[34mI20170311-02:25:07.565(0) Updating process.env.MAIL_URL 
[34mI20170311-02:25:08.216(0) Will load cache for rocketchat_permissions 
[34mI20170311-02:25:08.221(0) 66 records load from rocketchat_permissions 
[34mI20170311-02:25:08.242(0) Will load cache for rocketchat_roles 
[34mI20170311-02:25:08.243(0) 9 records load from rocketchat_roles 
[34mI20170311-02:25:09.958(0) ufs: store created at  
[34mI20170311-02:25:11.517(0) (rocketchat_migrations.js:160) Migrations: Not migrating, already at version 88
[34mI20170311-02:25:12.052(0) Updating process.env.MAIL_URL 
[34mI20170311-02:25:12.115(0) [32mUsing GridFS for custom sounds storage 
[34mI20170311-02:25:12.122(0) [32mUsing GridFS for custom emoji storage 
[34mI20170311-02:25:13.334(0) [32mUsing FileSystem for Avatar storage 
[34mI20170311-02:25:13.544(0) [32m➔ [32mSystem ➔ startup 
[34mI20170311-02:25:13.545(0) [32m➔ [32m+---------------------------------------------------+ 
[34mI20170311-02:25:13.545(0) [32m➔ [32m|                   SERVER RUNNING                  | 
[34mI20170311-02:25:13.546(0) [32m➔ [32m+---------------------------------------------------+ 
[34mI20170311-02:25:13.546(0) [32m➔ [32m|                                                   | 
[34mI20170311-02:25:13.546(0) [32m➔ [32m|  Rocket.Chat Version: 0.52.0                      | 
[34mI20170311-02:25:13.547(0) [32m➔ [32m|       NodeJS Version: 4.7.3 - x64                 | 
[34mI20170311-02:25:13.547(0) [32m➔ [32m|             Platform: linux                       | 
[34mI20170311-02:25:13.547(0) [32m➔ [32m|         Process Port: 3000                        | 
[34mI20170311-02:25:13.547(0) [32m➔ [32m|             Site URL: http://xxxxxxxxxxx.xxx  | 
[34mI20170311-02:25:13.547(0) [32m➔ [32m|     ReplicaSet OpLog: Disabled                    | 
[34mI20170311-02:25:13.548(0) [32m➔ [32m|          Commit Hash: 1418bb6485                  | 
[34mI20170311-02:25:13.548(0) [32m➔ [32m|        Commit Branch: HEAD                        | 
[34mI20170311-02:25:13.548(0) [32m➔ [32m|                                                   | 
[34mI20170311-02:25:13.548(0) [32m➔ [32m+---------------------------------------------------+ 
[34mI20170311-02:32:15.329(0) Exception in defer callback: Error: Greeting never received   at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)   at smtpSend (packages/email.js:108:37)   at Object.Email.send (packages/email.js:211:5)   at /app/bundle/programs/server/packages/rocketchat_lib.js:1608:14   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at packages/meteor.js:445:45   at runWithEnvironment (packages/meteor.js:1176:24)      - - - - -   at SMTPClient.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/simplesmtp/lib/client.js:289:25)   at Timer.listOnTimeout (timers.js:92:15)

**Comment by TheReal1604** [comment]
and again.. :( 

```
2017-03-15T18:19:08.756747943Z FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
2017-03-15T18:19:08.756820796Z
2017-03-15T18:19:08.756840335Z <--- Last few GCs --->
2017-03-15T18:19:08.756846640Z
2017-03-15T18:19:08.756850520Z 86399803 ms: Mark-sweep 978.7 (1457.5) -> 979.0 (1457.5) MB, 243.6 / 0 ms [allocation failure] [scavenge might not succeed].
2017-03-15T18:19:08.756865367Z 86400043 ms: Mark-sweep 979.0 (1457.5) -> 978.7 (1457.5) MB, 239.8 / 0 ms [allocation failure] [scavenge might not succeed].
2017-03-15T18:19:08.756869781Z 86400287 ms: Mark-sweep 978.7 (1457.5) -> 976.3 (1457.5) MB, 244.5 / 0 ms [last resort gc].
2017-03-15T18:19:08.756873434Z 86400538 ms: Mark-sweep 976.3 (1457.5) -> 978.7 (1457.5) MB, 250.9 / 0 ms [last resort gc].
2017-03-15T18:19:08.756883838Z
2017-03-15T18:19:08.756889983Z
2017-03-15T18:19:08.756895764Z <--- JS stacktrace --->
2017-03-15T18:19:08.756901945Z
2017-03-15T18:19:08.756908537Z ==== JS stack trace =========================================
2017-03-15T18:19:08.756913716Z
2017-03-15T18:19:08.756917204Z Security context: 0x14e5a40b4629 <JS Object>
2017-03-15T18:19:08.756920789Z     1: slowToString [buffer.js:421] [pc=0x291382f0ebb5] (this=0x13b0fd6f10a9 <an Uint8Array with map 0x1a0d16747809>,encoding=0x14e5a40bd761 <String[4]: utf8>,start=3060597,end=3376938)
2017-03-15T18:19:08.756924980Z     2: /* anonymous */(aka /* anonymous */) [/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/deserializer.js:~39] [pc=0x291382cc8a46] (this=0x14e5a40041b9 <undefin...
2017-03-15T18:19:08.756947101Z

```

**Comment by k0nsl** [comment]
How much memory is available on the server in question, @TheReal1604?

**Comment by TheReal1604** [comment]
@k0nsl the server has the following specs:

4vCPU
10GB RAM

**Comment by k0nsl** [comment]
Good, thank you. I guess we can rule out lack of memory. I run my instance on less memory than that, without any issues. Have you tried upgrading to `0.53.0` to see if the issue persists or not?

**Comment by TheReal1604** [comment]
@k0nsl it is already updated. sry, dont mention that here.

**Comment by lunacite** [comment]
We have the same problem and our server has 32gb

**Comment by BirknerAlex** [comment]
I've posted a solution what maybe also fixes your issue #6588.

**Comment by geekgonecrazy** [comment]
@TheReal1604 do you notice it going to 1.76GB and then restarting?  If so then yes looks like we can consolidate down issues.  The solution posted here: https://github.com/RocketChat/Rocket.Chat/issues/6588#issuecomment-296713211 should do the trick

**Comment by TheReal1604** [comment]
@geekgonecrazy for my shame i didnt have some monitoring in place for this instance. I try to setup a rough monitoring to look if this is the case.

**Comment by TheReal1604** [comment]
Closing because this is resolved.
