### ISSUE TITLE
Sending email with amazon SES

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#6195]
Right now, I can't manage to setup latest Rocket.Chat to send emails from Amazon Simple Email Service.

I configured MAIL_URL and SMTP Settings the right way.

I manage to send test email.
I manage to send password reset.

I can't manage to send verification emails (and no errors in the console).

I can't manage to send offline emails.
Here is the error I get:
```
Exception in defer callback: DeliveryError: Message delivery failed: 554 Message rejected: Email address is not verified. The following identities failed the check in region EU-WEST-1: the_email_of_the_user@gmail.com
  at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
  at smtpSend (packages/email.js:108:37)
  at Object.Email.send (packages/email.js:211:5)
  at /app/bundle/programs/server/packages/rocketchat_lib.js:1608:14
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at packages/meteor.js:445:45
  at runWithEnvironment (packages/meteor.js:1176:24)

    - - - - -
  at SMTPConnectionPool._onConnectionReady (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/simplesmtp/lib/pool.js:308:21)
  at emitTwo (events.js:87:13)
  at SMTPClient.emit (events.js:172:7)
  at SMTPClient._actionStream (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/simplesmtp/lib/client.js:1093:14)
  at SMTPClient._onData (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/simplesmtp/lib/client.js:354:29)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at TLSSocket.Readable.push (_stream_readable.js:111:10)
  at TLSWrap.onread (net.js:537:20)
```

I can't manage to send invitation emails.
Here is the error:
```
Exception in defer callback: Error: Error trying to send email: Message delivery failed: 554 Message rejected: Email address is not verified. The following identities failed the check in region EU-WEST-1: pierre.ozoux@gmail.com [error-email-send-failed]
  at /app/bundle/programs/server/packages/rocketchat_lib.js:2658:13
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at packages/meteor.js:445:45
  at runWithEnvironment (packages/meteor.js:1176:24)
```

It looks to me that the "from" is not setup correctly in some cases.

Do you know a way to debug the email that is sent?

**Comment by pierreozoux** [comment]
Ok, I thing I found the issue being SES.
I opened a ticket with Amazon, and let you know if it solved the issue.

**Comment by pierreozoux** [comment]
Ok, I confirm that this is solved.

For any body finding this thread:
The issue is that when you start SES, it is in sandbox mode. It is not clear what it means at the beginning, but the interesting part is that you can't send emails outside of the verified domains.
You just need to open a support request to remove the "sandbox" limit, and then everything resolves.

Sorry @rocket.chat for the confusion.
