### ISSUE TITLE
Issue with 'katex' when trying to run v0.53

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#6210]
Rocket.Chat Version:    0.53
Running Instances: 
DB Replicaset OpLog:
Node Version:   4.5.0

I just tried running the new version of RocketChat and get this error:

**Error: ENOENT: no such file or directory, scandir 'C:\Users\EliteBook\Google DriveNow\meteor\Rocket.Chat-master\packages\rocketchat-katex\node_modules\katex\dist\fonts'**
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at package.js:27:27
    at __bottom_mark__ (C:\tools\utils\parse-stack.js:64:14)
    at PackageSource.initFromPackageDir (C:\tools\isobuild\package-source.js:620:9)
    at C:\tools\packaging\catalog\catalog-local.js:354:23
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at initSourceFromDir (C:\tools\packaging\catalog\catalog-local.js:341:20)
    at C:\tools\packaging\catalog\catalog-local.js:409:9
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\EliteBook\AppData\Local\.meteor\packages\meteor-tool\1.4.2_6\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\catalog\catalog-local.js:408:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at LocalCatalog._loadLocalPackages (C:\tools\packaging\catalog\catalog-local.js:407:18)
    at LocalCatalog.initialize (C:\tools\packaging\catalog\catalog-local.js:119:10)
    at C:\tools\project-context.js:661:29
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:653:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._initializeCatalog (C:\tools\project-context.js:652:13)
    at C:\tools\project-context.js:268:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:258:18)
    at C:\tools\project-context.js:250:12
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:249:13)
    at C:\tools\runners\run-app.js:549:29
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundleApp (C:\tools\runners\run-app.js:548:31)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:617:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:876:28)
    at C:\tools\runners\run-app.js:403:12

**Comment by tomse** [comment]
got the same error.. following in case an answer appears :-)

**Comment by zombified** [comment]
I don't know if this helps, but I found I had to do an `meteor npm install` before I did the `meteor add rocketchat:internal-hubot meteorhacks:kadira` step to build it otherwise the katex dependency wasn't installed when doing the `meteor add`, which at some point triggers https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-katex/package.js#L26-L29

**Comment by stuurgurs** [comment]
`meteor npm install  `   helps

**Comment by kazimagircan** [comment]
ger same error insistently. I tried each step yours idea, and ı didnt solve problem.Someone help me please. katex problem how to get solving?
