### ISSUE TITLE
Error after upgrade to 53

### ISSUE THREAD

**Issue by givisok** [RocketChat/Rocket.Chat#6215]
I have error after update rocketchat docker image to lastes:

```
Error: $MONGO_OPLOG_URL must be set to the 'local' database of a Mongo replica set
rocketchat_1 |     at Error (native)
rocketchat_1 |     at [object Object]._.extend._startTailing (packages/mongo/oplog_tailing.js:218:13)
rocketchat_1 |     at new OplogHandle (packages/mongo/oplog_tailing.js:76:8)
rocketchat_1 |     at new MongoConnection (packages/mongo/mongo_driver.js:220:25)
rocketchat_1 |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
rocketchat_1 |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
rocketchat_1 |     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
rocketchat_1 |     at new Mongo.Collection (packages/mongo/collection.js:99:40)
rocketchat_1 |     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
rocketchat_1 |     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)

```

**Comment by TheReal1604** [comment]
@givisok you have to start first your mongo-init-replica docker container. This one enable the oplog for you.

**Comment by givisok** [comment]
@TheReal1604 it's help. Thank you.
