### ISSUE TITLE
Custom OAuth generates Internal Server Error

### ISSUE THREAD

**Issue by whuber-work** [RocketChat/Rocket.Chat#6216]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

I enabled an custom-oauth für auth0. in the logs of auth0 it is a success login. but from RocketChat I get an Internal Server Error. From the logs:
Mar 02 09:34:38 ip-172-31-4-192 snap[8517]: {"line":"428","file":"oauth.js","message":"Error in OAuth Server: Cannot read property 'error' of null","time":{"$date":1488447278745},"level":"warn"}
Mar 02 09:34:38 ip-172-31-4-192 snap[8517]: Exception while invoking method 'login' TypeError: Cannot read property 'error' of null
Mar 02 09:34:38 ip-172-31-4-192 snap[8517]:   at CustomOAuth.getAccessToken (/snap/rocketchat-server/511/programs/server/packages/rocketchat_custom-oauth.js:146:21)
Mar 02 09:34:38 ip-172-31-4-192 snap[8517]:   at Object.handleOauthRequest (/snap/rocketchat-server/511/programs/server/packages/rocketchat_custom-oauth.js:200:28)
Mar 02 09:34:38 ip-172-31-4-192 snap[8517]:   at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)
Mar 02 09:34:38 ip-172-31-4-192 snap[8517]:   at middleware (packages/oauth.js:203:5)
Mar 02 09:34:38 ip-172-31-4-192 snap[8517]:   at packages/oauth.js:176:5

**Comment by whuber-work** [comment]
figured it out: Identity Path has to point to: /userid
