### ISSUE TITLE
Install Problem: 

### ISSUE THREAD

**Issue by lescheib** [RocketChat/Rocket.Chat#6325]
when i try to run/configure the mongo DB with:

```
export MONGO_URL='mongodb://<mongoadmin>:<password>@localhost:<port>/rocketchat'
export ROOT_URL=<url>
export PORT=65381
node main.js
```

i got this message:

```
MongoError: auth failed
    at Object.Future.wait (/home/exa/rocketchat/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:219:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime.js:188:9)
    - - - - -
    at Function.MongoError.create (/home/exa/rocketchat/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    at /home/exa/rocketchat/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/home/exa/rocketchat/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:429:16)
    at [object Object].messageHandler (/home/exa/rocketchat/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/home/exa/rocketchat/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:317:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
```

But when i try to connect to the mongoadmi with this string it works:

`	mongo admin --port <port> -u <mongoadmin> -p <password>	`

what am I doing wrong?

**Comment by TheReal1604** [comment]
@lescheib Just an config example from my systems:

 ```
- MONGO_URL=mongodb://rocket:password@rocket-1:27017,rocket-2:27017,rocket-3:27017/rocketchat?replicaSet=rs0&readPreference=nearest&w=majority
- MONGO_OPLOG_URL=mongodb://username:password@rocket-1:27017,rocket-2:27017,rocket-3:27017/local?authSource=admin&replicaSet=rs0
```

Maybe you need the authSource=<authdb> parameter.
