### ISSUE TITLE
loading package emojione:emojione@2.2.6 Error

### ISSUE THREAD

**Issue by szluohua** [RocketChat/Rocket.Chat#6337]
Rocket.Chat Version: 0.53
Running Instances: 
DB Replicaset OpLog:
Node Version:4.7.3

=> Errors prevented startup:                  
   
   While loading package emojione:emojione@2.2.6:
   error: Command failed:
   /home/luo/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
   rebuild --update-binary
   Error making request.
   Error: read ECONNRESET
   at exports._errnoException (util.js:907:11)
   at TLSWrap.onread (net.js:558:26)
   
   Please report this full log at https://github.com/Medium/phantomjs
   
   npm ERR! Linux 4.4.0-66-generic
   npm ERR! argv
   "/home/luo/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/luo/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
   "rebuild" "--update-binary"
   npm ERR! node v4.7.3
   npm ERR! npm  v4.1.2
   npm ERR! code ELIFECYCLE
   npm ERR! phantomjs@1.9.20 install: `node install.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the phantomjs
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node install.js
   npm ERR! You can get information on how to open an issue for this project
   with:
   npm ERR!     npm bugs phantomjs
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls phantomjs
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!
   /home/luo/.meteor/packages/emojione_emojione/.2.2.6.10t3dgk++os+web.browser+web.cordova/npm/node_modules/.temp-fomic8/npm-debug.log
   Error making request.
   Error: read ECONNRESET
   at exports._errnoException (util.js:907:11)
   at TLSWrap.onread (net.js:558:26)
   
   Please report this full log at https://github.com/Medium/phantomjs
   
   npm ERR! Linux 4.4.0-66-generic
   npm ERR! argv
   "/home/luo/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/luo/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
   "rebuild" "--update-binary"
   npm ERR! node v4.7.3
   npm ERR! npm  v4.1.2
   npm ERR! code ELIFECYCLE
   npm ERR! phantomjs@1.9.20 install: `node install.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the phantomjs
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node install.js
   npm ERR! You can get information on how to open an issue for this project
   with:
   npm ERR!     npm bugs phantomjs
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls phantomjs
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!
   /home/luo/.meteor/packages/emojione_emojione/.2.2.6.10t3dgk++os+web.browser+web.cordova/npm/node_modules/.temp-fomic8/npm-debug.log
   
   
=> Your application has errors. Waiting for file change.

**Npm has been installed**

**Comment by szluohua** [comment]
The problem has been solved,these are the problems I encountered in starting Rocket.chat
Rocket.chat version: 0.53
Node version: v4.7.3
npm: 3.10.10

1.  .travis.yml add
```
before_install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 80 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --set gcc /usr/bin/gcc-5
```
[Install errors with node v4 and v5 #776](https://github.com/node-inspector/node-inspector/issues/776#issuecomment-162383014)

2. [bcrypt fails at the install script at node-gyp rebuild #432](https://github.com/kelektiv/node.bcrypt.js/issues/432)
`npm install --save bcrypt-nodejs && npm uninstall --save bcrypt`
3. [Latest versions seem to require NPM 3 #5210](https://github.com/RocketChat/Rocket.Chat/issues/5210)
`npm install -g npm@3`
