### ISSUE TITLE
SandStorm Rocket.Chat Errors in Log

### ISSUE THREAD

**Issue by MatheusRV** [RocketChat/Rocket.Chat#6352]
[34mI20170313-04:16:23.106(0) [32m➔ [32m+----------------------------------------------+ 
[34mI20170313-04:16:23.107(0) [32m➔ [32m|                SERVER RUNNING                | 
[34mI20170313-04:16:23.108(0) [32m➔ [32m+----------------------------------------------+ 
[34mI20170313-04:16:23.111(0) [32m➔ [32m|                                              | 
[34mI20170313-04:16:23.112(0) [32m➔ [32m|  Rocket.Chat Version: 0.52.0                 | 
[34mI20170313-04:16:23.112(0) [32m➔ [32m|       NodeJS Version: 4.4.7 - x64            | 
[34mI20170313-04:16:23.113(0) [32m➔ [32m|             Platform: linux                  | 
[34mI20170313-04:16:23.114(0) [32m➔ [32m|         Process Port: 8000                   | 
[34mI20170313-04:16:23.115(0) [32m➔ [32m|             Site URL: http://127.0.0.1:8000  | 
[34mI20170313-04:16:23.115(0) [32m➔ [32m|     ReplicaSet OpLog: Disabled               | 
[34mI20170313-04:16:23.116(0) [32m➔ [32m|          Commit Hash: 1418bb6485             | 
[34mI20170313-04:16:23.117(0) [32m➔ [32m|        Commit Branch: master                 | 
[34mI20170313-04:16:23.117(0) [32m➔ [32m|                                              | 
[34mI20170313-04:16:23.118(0) [32m➔ [32m+----------------------------------------------+ 
[34mI20170313-16:29:24.700(0) Exception while invoking method 'setAdminStatus' Error: Match error: Expected string, got null   at exports.check (packages/check.js:57:15)   at [object Object].setAdminStatus (/programs/server/packages/rocketchat_lib.js:11994:4)   at [object Object].methodsMap.(anonymous function) (/programs/server/packages/rocketchat_lib.js:1064:26)   at maybeAuditArgumentChecks (/programs/server/packages/ddp-server.js:2108:12)   at /programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /programs/server/packages/ddp-server.js:1040:48   at lib$es6$promise$$internal$$initializePromise (/node_modules/es6-promise/dist/es6-promise.js:373:9)   at new lib$es6$promise$promise$$Promise (/node_modules/es6-promise/dist/es6-promise.js:664:9)   at Session.method (/programs/server/packages/ddp-server.js:1018:23)   at /programs/server/packages/ddp-server.js:880:89  
[34mI20170313-16:29:24.707(0) Sanitized and reported to the client as: Match failed [400] 
[34mI20170313-16:29:24.711(0) undefined undefined 
[34mI20170313-16:29:27.381(0) Exception while invoking method 'setUserActiveStatus' Error: Match error: Expected string, got null   at exports.check (packages/check.js:57:15)   at [object Object].setUserActiveStatus (/programs/server/app/app.js:7961:4)   at [object Object].methodsMap.(anonymous function) (/programs/server/packages/rocketchat_lib.js:1064:26)   at maybeAuditArgumentChecks (/programs/server/packages/ddp-server.js:2108:12)   at /programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /programs/server/packages/ddp-server.js:1040:48   at lib$es6$promise$$internal$$initializePromise (/node_modules/es6-promise/dist/es6-promise.js:373:9)   at new lib$es6$promise$promise$$Promise (/node_modules/es6-promise/dist/es6-promise.js:664:9)   at Session.method (/programs/server/packages/ddp-server.js:1018:23)   at /programs/server/packages/ddp-server.js:880:89  
[34mI20170313-16:29:27.383(0) Sanitized and reported to the client as: Match failed [400] 
[34mI20170313-16:29:27.384(0) undefined undefined

**Comment by MatheusRV** [comment]
closing, i re-install and everything goes fine.
