### ISSUE TITLE
Error messages during update

### ISSUE THREAD

**Issue by rhruiz** [RocketChat/Rocket.Chat#6434]
Rocket.Chat Version: 0.52.0 -> 0.53.0 and 0.53.0 -> 0.54.0
Running Instances: 2 (one with old version and one trying to start with the new version)
DB Replicaset OpLog: Enabled
Node Version: v4.7.3 (using the `rocketchat/rocket.chat` docker image with the version tag)

During the upgrades from 0.52.0 to 0.53.0 we encountered the message bellow.
We had to open a mongo shell and remove all entries from the `usersSessions` collection for the upgrade to complete.

We believed this was a format change in the collection but the same thing happened in the 0.53 to 0.54.0 upgrade.

```Users with admin role already exist; Ignoring environment variables ADMIN_PASS
Exception in callback of async function: MongoError: Cannot apply $pull to a non-array value
  at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
  at [object Object].<anonymous> (packages/meteor.js:213:24)
  at [object Object].MongoConnection.(anonymous function) [as update] (/app/bundle/programs/server/packages/mongo.js:831:49)
  at Object.<anonymous> (packages/matb33_collection-hooks.js:504:27)
  at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
  at [object Object].update (/app/bundle/programs/server/packages/mongo.js:3882:31)
  at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user.js:325:19)
  at Object.UserPresence.removeLostConnections (packages/konecty_user-presence.js:98:18)
  at Object.UserPresence.start (packages/konecty_user-presence.js:278:16)
  at /app/bundle/programs/server/app/app.js:5285:15
  at Function.time (/app/bundle/programs/server/profile.js:309:28)
  at /app/bundle/programs/server/boot.js:312:13
  at /app/bundle/programs/server/boot.js:353:5
  at Function.run (/app/bundle/programs/server/profile.js:510:12)
  at /app/bundle/programs/server/boot.js:351:11

    - - - - -
  at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
  at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1048:67
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18
  at nextTickCallbackWith0Args (node.js:489:9)
  at process._tickDomainCallback (node.js:459:13)

[Wed Mar 22 2017 21:04:44 GMT+0000 (UTC)] ERROR MongoError: Cannot apply $pull to a non-array value
  at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
  at [object Object].<anonymous> (packages/meteor.js:213:24)
  at [object Object].MongoConnection.(anonymous function) [as update] (/app/bundle/programs/server/packages/mongo.js:831:49)
  at Object.<anonymous> (packages/matb33_collection-hooks.js:504:27)
  at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
  at [object Object].update (/app/bundle/programs/server/packages/mongo.js:3882:31)
  at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user.js:325:19)
  at Object.UserPresence.removeLostConnections (packages/konecty_user-presence.js:98:18)
  at Object.UserPresence.start (packages/konecty_user-presence.js:278:16)
  at /app/bundle/programs/server/app/app.js:5285:15
  at Function.time (/app/bundle/programs/server/profile.js:309:28)
  at /app/bundle/programs/server/boot.js:312:13
  at /app/bundle/programs/server/boot.js:353:5
  at Function.run (/app/bundle/programs/server/profile.js:510:12)
  at /app/bundle/programs/server/boot.js:351:11

    - - - - -
  at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
  at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1048:67
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18
  at nextTickCallbackWith0Args (node.js:489:9)
  at process._tickDomainCallback (node.js:459:13)```

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
