### ISSUE TITLE
version 17 migration error

### ISSUE THREAD

**Issue by dbussert** [RocketChat/Rocket.Chat#644]
I got this error when updating my rocket.chat to the latest

```
I20150831-14:02:13.041(-4)? Using GridFS for Avatar storage
I20150831-14:02:13.043(-4)? ufs: created tmpDir /tmp/ufs
I20150831-14:02:13.043(-4)? Migrating from version 15 -> 18
I20150831-14:02:13.043(-4)? Running up() on version 16
I20150831-14:02:13.043(-4)? Running up() on version 17
I20150831-14:02:13.043(-4)? Exception in defer callback: MongoError: can't find index with key:{ _hidden: 1 }
I20150831-14:02:13.043(-4)?     at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.4.xvre8c++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20150831-14:02:13.043(-4)?     at packages/meteor/helpers.js:119:1
I20150831-14:02:13.044(-4)?     at Migrations.add.up (server/startup/migrations/v17.coffee:6:4)
I20150831-14:02:13.044(-4)?     at migrate (packages/percolate:migrations/migrations_server.js:142:1)
I20150831-14:02:13.044(-4)?     at Object.Migrations._migrateTo (packages/percolate:migrations/migrations_server.js:153:1)
I20150831-14:02:13.044(-4)?     at Object.Migrations.migrateTo (packages/percolate:migrations/migrations_server.js:80:1)
I20150831-14:02:13.044(-4)?     at server/startup/migrations/xrun.coffee:4:15
I20150831-14:02:13.044(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150831-14:02:13.044(-4)?     at packages/meteor/timers.js:6:1
I20150831-14:02:13.044(-4)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150831-14:02:13.044(-4)?     - - - - -
I20150831-14:02:13.044(-4)?     at Object.toError (/root/.meteor/packages/mongo/.1.1.0.11t75li++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
I20150831-14:02:13.045(-4)?     at /root/.meteor/packages/mongo/.1.1.0.11t75li++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1194:31
I20150831-14:02:13.045(-4)?     at /root/.meteor/packages/mongo/.1.1.0.11t75li++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1903:9
I20150831-14:02:13.045(-4)?     at Server.Base._callHandler (/root/.meteor/packages/mongo/.1.1.0.11t75li++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
I20150831-14:02:13.045(-4)?     at /root/.meteor/packages/mongo/.1.1.0.11t75li++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
I20150831-14:02:13.045(-4)?     at [object Object].MongoReply.parseBody (/root/.meteor/packages/mongo/.1.1.0.11t75li++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I20150831-14:02:13.045(-4)?     at [object Object].<anonymous> (/root/.meteor/packages/mongo/.1.1.0.11t75li++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
I20150831-14:02:13.045(-4)?     at [object Object].emit (events.js:95:17)
I20150831-14:02:13.045(-4)?     at [object Object].<anonymous> (/root/.meteor/packages/mongo/.1.1.0.11t75li++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
I20150831-14:02:13.045(-4)?     at [object Object].emit (events.js:98:17)
I20150831-14:02:13.046(-4)? startStreamBroadcast
I20150831-14:02:13.046(-4)? connecting in localhost:23026
```

**Comment by sampaiodiego** [comment]
I'm sorry fot that.. now you got stuck on migration v17. you'll have to access the mongodb shell and run this:

`db.migrations.update({}, { $set: { version: 17, locked: false } })`

**Comment by marceloschmidt** [comment]
Is this still causing errors? Can this be closed, @sampaiodiego ?

**Comment by sampaiodiego** [comment]
nope!
