### ISSUE TITLE
Migrating from LDAP to crowd -> user already exists

### ISSUE THREAD

**Issue by rndmh3ro** [RocketChat/Rocket.Chat#6545]
I initially connected rocket.chat with LDAP and synced all users, this worked fine. Now I wanted to use Atlassian Crowd instead of LDAP. The connection to Crowd works fine, but when trying to login, the user cannot login and the following is logged:

```
[34mI20170331-11:45:43.264(2) rocketchat_crowd.js:239 [34mCROWD ➔ info Init CROWD login myuser 
[34mI20170331-11:45:43.272(2) rocketchat_crowd.js:111 [34mCROWD ➔ info Going to crowd: myuser 
[34mI20170331-11:45:43.938(2) rocketchat_crowd.js:210 [34mCROWD ➔ info Error creating new user for crowd user { [Error: Username already exists. [403]]   error: 403,   reason: 'Username already exists.',   details: undefined,   message: 'Username already exists. [403]',   errorType: 'Meteor.Error' } 
[34mI20170331-11:45:43.943(2) Exception while invoking method 'login' TypeError: Cannot convert undefined or null to object   at Function.keys (native)   at ModelsBaseDb.defineSyncStrategy (/snap/rocketchat-server/528/programs/server/packages/rocketchat_lib.js:9406:35)   at ModelsBaseDb.update (/snap/rocketchat-server/528/programs/server/packages/rocketchat_lib.js:9537:24)   at [object Object].model.update (/snap/rocketchat-server/528/programs/server/packages/rocketchat_lib.js:9326:24)   at ModelsBaseDb.update (/snap/rocketchat-server/528/programs/server/packages/rocketchat_lib.js:9565:32)   at [object Object].model.update (/snap/rocketchat-server/528/programs/server/packages/rocketchat_lib.js:9326:24)   at CROWD.addNewUser (/snap/rocketchat-server/528/programs/server/packages/rocketchat_crowd.js:218:18)   at [object Object].<anonymous> (/snap/rocketchat-server/528/programs/server/packages/rocketchat_crowd.js:258:15)   at /snap/rocketchat-server/528/programs/server/packages/accounts-base.js:910:30   at tryLoginMethod (/snap/rocketchat-server/528/programs/server/packages/accounts-base.js:738:14)   at AccountsServer.Ap._runLoginHandlers (/snap/rocketchat-server/528/programs/server/packages/accounts-base.js:909:18)   at [object Object].methods.login (/snap/rocketchat-server/528/programs/server/packages/accounts-base.js:967:27)   at maybeAuditArgumentChecks (/snap/rocketchat-server/528/programs/server/packages/ddp-server.js:1817:12)   at /snap/rocketchat-server/528/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/528/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/528/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/528/programs/server/packages/ddp-server.js:876:21)   at /snap/rocketchat-server/528/programs/server/packages/ddp-server.js:755:85  

```

Crowd itself gets its information from the same LDAP-server so I don't know why its trying to create a new user. Any hints?

Rocket.Chat Version: 0.53.0, also happens with 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

**Comment by rndmh3ro** [comment]
I did some more testing:

I deleted a LDAP user, then changed the auth-method to crowd. The user was then newly created and able to login. However the private conversation I had with him cannot be opened anymore, the error message says "the user could not be found." Now if I want to open the private conversation, the following error is logged:
```
[34mI20170718-13:54:43.951(2) Exception while invoking method 'createDirectMessage' MongoError: E11000 duplicate key error collection: parties.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "ya2gpEZWf9k9BPBZk", : "brst", : "d", : null }   at Object.Future.wait (/snap/rocketchat-server/829/node_modules/fibers/future.js:449:15)   at [object Object].<anonymous> (packages/meteor.js:213:24)   at [object Object].MongoConnection.(anonymous function) [as update] (/snap/rocketchat-server/829/programs/server/packages/mongo.js:836:49)   at Object.<anonymous> (packages/matb33_collection-hooks.js:504:27)   at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)   at [object Object].update (/snap/rocketchat-server/829/programs/server/packages/mongo.js:3899:31)   at ModelsBaseDb.update (/snap/rocketchat-server/829/programs/server/packages/rocketchat_lib.js:10647:32)   at ModelsBaseDb.upsert (/snap/rocketchat-server/829/programs/server/packages/rocketchat_lib.js:10722:16)   at ModelSubscriptions.upsert (/snap/rocketchat-server/829/programs/server/packages/rocketchat_lib.js:4283:36)   at [object Object].Meteor.methods.createDirectMessage (/snap/rocketchat-server/829/programs/server/app/app.js:6506:35)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/829/programs/server/packages/rocketchat_lib.js:1028:26)   at maybeAuditArgumentChecks (/snap/rocketchat-server/829/programs/server/packages/ddp-server.js:1823:12)   at /snap/rocketchat-server/829/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/829/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/829/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/829/programs/server/packages/ddp-server.js:876:21)   at /snap/rocketchat-server/829/programs/server/packages/ddp-server.js:755:85      - - - - -   at Function.MongoError.create (/snap/rocketchat-server/829/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)   at toError (/snap/rocketchat-server/829/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)   at /snap/rocketchat-server/829/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1049:67   at /snap/rocketchat-server/829/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18   at nextTickCallbackWith0Args (node.js:489:9)   at process._tickDomainCallback (node.js:459:13) 
```

I guess if I delete my user, too, the error will disappear.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Can please try to reproduce this on latest stable and check, whether it might be related to #6535? I think there are already several issues talking about `E11000 duplicate key error index` so a search for error might also bring up some other things to try for you. I'll happily reopen if you find this to be different (and if so, in what way) than all the other E11000 errors :)

Cheers
Thomas

**Comment by snoopotic** [comment]
Hi. It seems the migration-problem still occurrs in 0.72.3

[34mI20181218-09:17:03.427(0) rocketchat_logger rocketchat_logger.js:299 [34mCROWD ➔ info Init CROWD login myuser 
[34mI20181218-09:17:03.429(0) rocketchat_logger rocketchat_logger.js:299 [34mCROWD ➔ info Going to crowd: myuser 
[34mI20181218-09:17:04.017(0) rocketchat_logger rocketchat_logger.js:299 [31mCROWD ➔ error Error creating new crowd user. Username already exists. [403] 

I don't want to delete users but migrate same usernames from LDAP to CROWD.

I disabled LDAP/enabled LDAP with and without fallback but crowd seems to have precedence and does not work. 
Seems it needs a user resync with crowd-data if user exists and is allowed to log in and hase same username.

**Comment by NateDreier** [comment]
@snoopotic, have you heard anything? I will be needing to migrate from LDAP -> Crowd in the next 2 months and just started researching.

**Comment by mfominov** [comment]
maybe there is solution like for cas?
https://github.com/RocketChat/Rocket.Chat/issues/3379

**Comment by mfominov** [comment]
db.getCollection('users').update({username:"[USER]"}, { $set: { "crowd_username": "[USER]" }});
db.getCollection('users').update({username:"[USER]"}, { $set: { "crowd": true }});
