### ISSUE TITLE
what should be in MAIL_URL

### ISSUE THREAD

**Issue by oinirio** [RocketChat/Rocket.Chat#656]
I setup the mail details in the smtp menu inside admin but when I try to recover the password still said that I need to setup MAIL_URL.

**Comment by marceloschmidt** [comment]
Have you filled out SMTP_Host, SMTP_Username and SMTP_Password? 
If you open another terminal at the root of your meteor app and type meteor shell, then type process.env.MAIL_URL, is there any return, or is it empty?

**Comment by oinirio** [comment]
process.env.MAIL_URL returns ```'smtp://$user%40gmail.com:$pass@smtl.gmail.com:587'```

but when I try to reset a password the meteor log throws an exception

```
Exception while invoking method 'sendForgotPasswordEmail' Error: getaddrinfo ENOTFOUND
at Object.Future.wait (/home/phi/.meteor/packages/meteor-tool/.1.1.4.1e309qs++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
at smtpSend (packages/email/email.js:76:1)
at Object.Email.send (packages/email/email.js:153:1)
at Object.Email.send (packages/meteorhacks:kadira/lib/hijack/email.js:10:1)
at Object.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:421:1)
at [object Object].Meteor.methods.sendForgotPasswordEmail (server/methods/sendForgotPasswordEmail.coffee:6:13)
at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:164:1)
at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
at packages/ddp/livedata_server.js:648:1
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at errnoException (dns.js:37:11)
at Object.onanswer [as oncomplete] (dns.js:124:16)
```

**Comment by oinirio** [comment]
my bad, I have a typo in MAIL_URL.

working now
