### ISSUE TITLE
Restoring Rocket.Chat instance on new server

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#6633]
Rocket.Chat Version: 0.54.2
Running Instances: 4
DB Replicaset OpLog: N/A
Node Version: N/A

I had some spare time over today and decided to try moving my production instance over to a new server which has better hardware and network -- on a wholly different data center.

So I backed up my data with this command:
```
docker save -o /root/rocketchat-backup/k0nsl-rocketchat-mongodb-$( date '+%Y-%m-%d_%H-%M-%S' ).tar.gz mongo
```

Then I rsync'd the compressed backup file over to the new server and tried restoring it with the following command:
```
docker load -i k0nsl-rocketchat-mongodb-2017-04-07_12-29-03.tar.gz
```
And it shows that it successfully restored:
```
Loaded image: mongo:latest
```
Fine, right? Then I run:
```
docker-compose up -d
```
Which shows that the two containers starts.

But it fails and this is the only output I have available at the moment:
```
panzer:~/chat# cat output-newest.txt
Attaching to chat_mongo_1, chat_chat_1
chat_mongo_1 exited with code 139
chat_1   | 
chat_1   | /app/bundle/programs/server/node_modules/fibers/future.js:313
chat_1   | 						throw(ex);
chat_1   | 						^
chat_1   | MongoError: failed to connect to server [mongo:27017] on first connect
chat_1   |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
chat_1   |     at new MongoConnection (packages/mongo/mongo_driver.js:217:27)
chat_1   |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
chat_1   |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
chat_1   |     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
chat_1   |     at new Mongo.Collection (packages/mongo/collection.js:99:40)
chat_1   |     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
chat_1   |     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
chat_1   |     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
chat_1   |     at fileEvaluate (packages/modules-runtime.js:197:9)
chat_1   |     - - - - -
chat_1   |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:325:35)
chat_1   |     at emitOne (events.js:77:13)
chat_1   |     at [object Object].emit (events.js:169:7)
chat_1   |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
chat_1   |     at [object Object].g (events.js:260:16)
chat_1   |     at emitTwo (events.js:87:13)
chat_1   |     at [object Object].emit (events.js:172:7)
chat_1   |     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:173:49)
chat_1   |     at Socket.g (events.js:260:16)
chat_1   |     at emitOne (events.js:77:13)
chat_mongo_1 exited with code 139
chat_mongo_1 exited with code 139
chat_chat_1 exited with code 1
```
I did verify that before I restored this backup I could access a "clean" installation on the new server. It worked fine. But I am unable to restore my backup from the old server to the new one.

Am I doing something wrong or what? :/

Thanks in advance for any help!

**Comment by Rohlik** [comment]
`docker save` command just send **images** to a tar archive. Docker doesn´t store your new created data in images, but in containers. So, you need `docker commit` command, which created new image from your current container. After that, you can use `docker save` and move that archive to another server.
PS: Do you have your old and new server same **domainname**?

**Comment by TheReal1604** [comment]
@k0nsl Dont need to do that stuff. Just save your rocket.chat data inside the mongodb with mongodump..
https://docs.mongodb.com/manual/reference/program/mongodump/

After this, you can spin up a new environment with a new mongodb cluster and new rocket.chat docker container. Now restore your dump with mongorestore.

https://docs.mongodb.com/manual/reference/program/mongorestore/

Thats all, your new container should now come up with the old configuration and data. 👍

**Comment by k0nsl** [comment]
I tried your recommendation, @Rohlik, but no progress:

On the old server I ran the following commands:
```
docker commit -p 6f4759d066b0 k0nsl-rockethat-mongo
docker save -o /root/rocketchat-backup/k0nsl-rockethat-mongo.tar k0nsl-rockethat-mongo
rsync -avzhe ssh k0nsl-rockethat-mongo.tar root@10.0.0.5:/root/
```
Then on the new server I ran these commands:
```
docker load -i k0nsl-rockethat-mongo.tar
docker-compose up
```
And it just outputs the same as I posted earlier:
```
panzer:~/Rocket.Chat# docker-compose up
rocketchat_mongo_1 is up-to-date
Recreating rocketchat_chat_1
Attaching to rocketchat_mongo_1, rocketchat_chat_1
chat_1   | 
chat_1   | /app/bundle/programs/server/node_modules/fibers/future.js:313
chat_1   | 						throw(ex);
chat_1   | 						^
chat_1   | MongoError: failed to connect to server [mongo:27017] on first connect
chat_1   |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
chat_1   |     at new MongoConnection (packages/mongo/mongo_driver.js:217:27)
chat_1   |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
chat_1   |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
chat_1   |     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
chat_1   |     at new Mongo.Collection (packages/mongo/collection.js:99:40)
chat_1   |     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
chat_1   |     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
chat_1   |     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
chat_1   |     at fileEvaluate (packages/modules-runtime.js:197:9)
chat_1   |     - - - - -
chat_1   |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:325:35)
chat_1   |     at emitOne (events.js:77:13)
chat_1   |     at [object Object].emit (events.js:169:7)
chat_1   |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
chat_1   |     at [object Object].g (events.js:260:16)
chat_1   |     at emitTwo (events.js:87:13)
chat_1   |     at [object Object].emit (events.js:172:7)
chat_1   |     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:173:49)
chat_1   |     at Socket.g (events.js:260:16)
chat_1   |     at emitOne (events.js:77:13)
rocketchat_chat_1 exited with code 1
chat_1   | 
chat_1   | /app/bundle/programs/server/node_modules/fibers/future.js:313
chat_1   | 						throw(ex);
chat_1   | 						^
chat_1   | MongoError: failed to connect to server [mongo:27017] on first connect
chat_1   |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
chat_1   |     at new MongoConnection (packages/mongo/mongo_driver.js:217:27)
chat_1   |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
chat_1   |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
chat_1   |     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
chat_1   |     at new Mongo.Collection (packages/mongo/collection.js:99:40)
chat_1   |     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
chat_1   |     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
chat_1   |     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
chat_1   |     at fileEvaluate (packages/modules-runtime.js:197:9)
chat_1   |     - - - - -
chat_1   |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:325:35)
chat_1   |     at emitOne (events.js:77:13)
chat_1   |     at [object Object].emit (events.js:169:7)
chat_1   |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
chat_1   |     at [object Object].g (events.js:260:16)
chat_1   |     at emitTwo (events.js:87:13)
chat_1   |     at [object Object].emit (events.js:172:7)
chat_1   |     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:173:49)
chat_1   |     at Socket.g (events.js:260:16)
chat_1   |     at emitOne (events.js:77:13)
chat_1   | 
chat_1   | /app/bundle/programs/server/node_modules/fibers/future.js:313
chat_1   | 						throw(ex);
chat_1   | 						^
chat_1   | MongoError: failed to connect to server [mongo:27017] on first connect
chat_1   |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
chat_1   |     at new MongoConnection (packages/mongo/mongo_driver.js:217:27)
chat_1   |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
chat_1   |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
chat_1   |     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
chat_1   |     at new Mongo.Collection (packages/mongo/collection.js:99:40)
chat_1   |     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
chat_1   |     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
chat_1   |     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
chat_1   |     at fileEvaluate (packages/modules-runtime.js:197:9)
chat_1   |     - - - - -
chat_1   |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:325:35)
chat_1   |     at emitOne (events.js:77:13)
chat_1   |     at [object Object].emit (events.js:169:7)
chat_1   |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
chat_1   |     at [object Object].g (events.js:260:16)
chat_1   |     at emitTwo (events.js:87:13)
chat_1   |     at [object Object].emit (events.js:172:7)
chat_1   |     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:173:49)
chat_1   |     at Socket.g (events.js:260:16)
chat_1   |     at emitOne (events.js:77:13)
chat_1   | 
chat_1   | /app/bundle/programs/server/node_modules/fibers/future.js:313
chat_1   | 						throw(ex);
chat_1   | 						^
chat_1   | MongoError: failed to connect to server [mongo:27017] on first connect
chat_1   |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
chat_1   |     at new MongoConnection (packages/mongo/mongo_driver.js:217:27)
chat_1   |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
chat_1   |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
chat_1   |     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
chat_1   |     at new Mongo.Collection (packages/mongo/collection.js:99:40)
chat_1   |     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
chat_1   |     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
chat_1   |     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
chat_1   |     at fileEvaluate (packages/modules-runtime.js:197:9)
chat_1   |     - - - - -
chat_1   |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:325:35)
chat_1   |     at emitOne (events.js:77:13)
chat_1   |     at [object Object].emit (events.js:169:7)
chat_1   |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
chat_1   |     at [object Object].g (events.js:260:16)
chat_1   |     at emitTwo (events.js:87:13)
chat_1   |     at [object Object].emit (events.js:172:7)
chat_1   |     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:173:49)
chat_1   |     at Socket.g (events.js:260:16)
chat_1   |     at emitOne (events.js:77:13)
rocketchat_chat_1 exited with code 1
```

**Comment by Rohlik** [comment]
@k0nsl How yours docker-compose look like? (mask your private data)

**Comment by k0nsl** [comment]
Oh, it is incredibly rudimentary, @Rohlik. Here you go:

```
mongo:
  image: k0nsl-rockethat-mongo
  command: mongod --smallfiles --oplogSize 128
  restart: always

chat:
  image: rocketchat/rocket.chat:latest
#  image: rocketchat/rocket.chat:0.54.2
  environment:
    - PORT=3000
    - ROOT_URL=https://k0nsl.org
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 3000:3000
  restart: always
```

The same `docker-compose.yml` composition works fine on the new server if I change the `mongo` section and pull a clean image of MongoDB, but not if I load my backed up data.

**Comment by Rohlik** [comment]
@k0nsl Are you running `docker commit` on stopped container? If not, try your container stop first. Maybe mongodb needs to be properly exited....
Are you using same domainname for old and new server?

**Comment by k0nsl** [comment]
@Rohlik: The container was running but I passed the `-p` flag in order to pause it. At any rate, I will try stopping the container  later today or tomorrow and re-do the whole process.

It uses the same domain name.

**Comment by sampaiodiego** [comment]
@k0nsl have you managed it?

**Comment by k0nsl** [comment]
@sampaiodiego: No, unfortunately stopping the container yielded the same result as passing `-p` would and I am thus still stuck in the same spot as I was before.

**Comment by sampaiodiego** [comment]
ok, so the new mongo container is up and running right? do you have access to its mongo shell?

**Comment by saenzramiro** [comment]
Same here!

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this. Please feel free to open a topic on our [forum](https://forums.rocket.chat) in the community support category
