### ISSUE TITLE
Can't configure RocketChat with SAML and Azure Ad or OAUTH with Office 365

### ISSUE THREAD

**Issue by basitmohammad** [RocketChat/Rocket.Chat#6660]
I can't seem to configure my RocketChat to work with SAML or OAUTH. Is there any documentation that could help me to know exactly what to configure on both ends??

Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

**Comment by basitmohammad** [comment]
Update: This is the error I get when trying to log in with OAuth.

`Exception while invoking method 'login' Error: Failed to complete OAuth handshake with office365 at https://login.microsoftonline.com/oauth/token. failed [404]   at CustomOAuth.getAccessToken (/opt/Rocket.Chat/programs/server/packages/rocketchat_custom-oauth.js:151:17)   at Object.handleOauthRequest (/opt/Rocket.Chat/programs/server/packages/rocketchat_custom-oauth.js:212:28)   at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)   at middleware (packages/oauth.js:203:5)   at packages/oauth.js:176:5  `

**Comment by basitmohammad** [comment]
Update: The new error I'm receiving, this is getting really annoying trying to configure. Any ideas?

`Exception while invoking method 'login' Error: Failed to fetch identity from office365 at https://login.microsoftonline.com/me. failed [404]   at CustomOAuth.getIdentity (/opt/Rocket.Chat/programs/server/packages/rocketchat_custom-oauth.js:198:17)   at Object.handleOauthRequest (/opt/Rocket.Chat/programs/server/packages/rocketchat_custom-oauth.js:214:25)   at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)   at middleware (packages/oauth.js:203:5)   at packages/oauth.js:176:5  `

**Comment by basitmohammad** [comment]
Anyone want to help?...

**Comment by basitmohammad** [comment]
So.......can I at least get an acknowledgment that you can see this?
