### ISSUE TITLE
I can't download any files from rocketchat

### ISSUE THREAD

**Issue by alefq** [RocketChat/Rocket.Chat#6670]
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.3 - x64 

 I can't download any files, neither through desktop client nor web version. This is what goes out in syslog. 

```
Apr 12 09:01:32 devtools nodejs-example[1627]: Error: `value` required in setHeader(&quot;Content-Type&quot;, value).
Apr 12 09:01:32 devtools nodejs-example[1627]:   at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at ServerResponse.res.setHeader (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/patch.js:134:22)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at ServerResponse.res.setHeader (/opt/Rocket.Chat/programs/server/packages/rocketchat_cors.js:83:20)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at ServerResponse.setWriteHeadHeaders (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/webapp/node_modules/on-headers/index.js:82:19)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at ServerResponse.writeHead (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/webapp/node_modules/on-headers/index.js:41:36)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at readFromGridFS (/opt/Rocket.Chat/programs/server/packages/rocketchat_file-upload.js:789:7)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at Object.FileUpload.addHandler.get (/opt/Rocket.Chat/programs/server/packages/rocketchat_file-upload.js:831:10)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at Object.FileUpload.get (/opt/Rocket.Chat/programs/server/packages/rocketchat_file-upload.js:247:33)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at Object.handle (/opt/Rocket.Chat/programs/server/packages/rocketchat_file-upload.js:321:22)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at next (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at Object.handle (/opt/Rocket.Chat/programs/server/packages/jalik_ufs.js:1239:17)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at next (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at middleware (/opt/Rocket.Chat/programs/server/packages/rocketchat_cas.js:233:4)
Apr 12 09:01:32 devtools nodejs-example[1627]:   at /opt/Rocket.Chat/programs/server/packages/rocketchat_cas.js:260:3```

**Comment by tarabanton** [comment]
Rocket.Chat Version: 0.54.2
Running Instances: 4
DB Replicaset OpLog: Enabled

Same issue here.

**Comment by HLFH** [comment]
Same as @tarabanton with mime type undefined on last RocketChat version 0.57.0.

**Comment by underlines** [comment]
On OSX using Rambox and Chrome all files get downloaded without file extension. I guess this is related to the mime type problem?

**Comment by louisemessage** [comment]
@rodrigok do you know why this is happening?

**Comment by ifohancroft** [comment]
Me and all my co-workers can't download any files either but only when using a desktop client.

Server version: 0.66.3

**Comment by dormeiri** [comment]
Same here, there is no button to download attachments from mobile
Version 1.1.3

**Comment by geekgonecrazy** [comment]
going to close this as mobile, desktop and web client have all received a lot of changes since this was opened.
