### ISSUE TITLE
Problems with email notifications / View logs from GUI after upgrading to 0.55.0 rc2

### ISSUE THREAD

**Issue by bartroff** [RocketChat/Rocket.Chat#6678]
Rocket.Chat Version: 0.55.0-rc.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.5.0 - x64 

After changing to 0.55.0 rc2 the email feature stopped working for me. I tried several things, like setting the hostname/port in env instead of using GUI, changing between port 25/587 etc.

I get the following error:

```
Apr 12 14:22:59 rocketchat: Sending test email to user@user.com
Apr 12 14:22:59  rocketchat: Exception in callback of async function: Error: unable to get local issuer certificate
Apr 12 14:22:59 rocketchat: at Error (native)
Apr 12 14:22:59 rocketchat: at TLSSocket.<anonymous> (_tls_wrap.js:1022:38)
Apr 12 14:22:59  rocketchat: at emitNone (events.js:67:13)
Apr 12 14:22:59  rocketchat: at TLSSocket.emit (events.js:166:7)
Apr 12 14:22:59  rocketchat: at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:586:8)
Apr 12 14:22:59  rocketchat: at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:428:38)
Apr 12 14:22:59  rocketchat: [Wed Apr 12 2017 14:22:59 GMT+0200 (CEST)] ERROR Error: unable to get local issuer certificate
Apr 12 14:22:59  rocketchat: at Error (native)
Apr 12 14:22:59  rocketchat: at TLSSocket.<anonymous> (_tls_wrap.js:1022:38)
Apr 12 14:22:59  rocketchat: at emitNone (events.js:67:13)
Apr 12 14:22:59  rocketchat: at TLSSocket.emit (events.js:166:7)
Apr 12 14:22:59  rocketchat: at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:586:8)
Apr 12 14:22:59  rocketchat: at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:428:38)
Apr 12 14:22:59  rocketchat: Exception in callback of async function: Error: Connection closed unexpectedly
Apr 12 14:22:59  rocketchat: at SMTPConnection._onClose (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/smtp-connection/lib/smtp-connection.js:561:30)
Apr 12 14:22:59  rocketchat: at Socket.g (events.js:260:16)
Apr 12 14:22:59  rocketchat: at emitOne (events.js:82:20)
Apr 12 14:22:59 rocketchat: at Socket.emit (events.js:169:7)
Apr 12 14:22:59  rocketchat: at TCP._onclose (net.js:486:12)
Apr 12 14:22:59  rocketchat: [Wed Apr 12 2017 14:22:59 GMT+0200 (CEST)] ERROR Error: Connection closed unexpectedly
Apr 12 14:22:59  rocketchat: at SMTPConnection._onClose (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/smtp-connection/lib/smtp-connection.js:561:30)
Apr 12 14:22:59  rocketchat: at Socket.g (events.js:260:16)
Apr 12 14:22:59  rocketchat: at emitOne (events.js:82:20)
Apr 12 14:22:59  rocketchat: at Socket.emit (events.js:169:7)
Apr 12 14:22:59  rocketchat: at TCP._onclose (net.js:486:12)
```

What am I doing wrong? 

When trying to access 'View Logs' feature via GUI, it doesn't show anything. The log throws this error:

```
Apr 13 09:18:34  rocketchat: Exception from sub stdout id DxyEB5mgSgEo3c8jS TypeError: Cannot read property 'forEach' of undefined
Apr 13 09:18:34 rocketchat: at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/packages/rocketchat_logger.js:594:14)
Apr 13 09:18:34 rocketchat: at packages/matb33_collection-hooks.js:307:21
Apr 13 09:18:34 rocketchat: at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Apr 13 09:18:34 rocketchat: at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
Apr 13 09:18:34 rocketchat: at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1823:12)
Apr 13 09:18:34 rocketchat: at [object Object]._.extend._runHandler (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1174:17)
Apr 13 09:18:34 rocketchat: at [object Object]._.extend._startSubscription (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1022:9)
Apr 13 09:18:34 rocketchat: at [object Object]._.extend.protocol_handlers.sub (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:817:12)
Apr 13 09:18:34 rocketchat: at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:755:85
```

Any help appreciated.

Best regards - Allan

**Comment by MartinSchoeler** [comment]
@ggazzo is that second error related to the logger conversion?

**Comment by engelgabriel** [comment]
The email problem is caused by https://github.com/meteor/meteor/issues/8591

**Comment by sampaiodiego** [comment]
@bartroff can you please try the `rc.4` version?

**Comment by bartroff** [comment]
Thanks @sampaiodiego works now like charm, also logs issue is gone.
