### ISSUE TITLE
Direct message conversations can be archived, but not unarchived

### ISSUE THREAD

**Issue by JakeSteam** [RocketChat/Rocket.Chat#6728]
Rocket.Chat Version: 0.54.2

Type `/archive` in a private conversation and the room will be archived, with no option to unarchive it. 

The archive option is hidden from the room's info, but directly entering the command is not forbidden.

https://i.imgur.com/fdiOyE9.png

**Comment by MartinSchoeler** [comment]
This still happens on the latest version, and also throws this error on the server console 
<details>

```Exception while invoking method 'slashCommand' TypeError: Cannot read property 'u' of undefined
I20170419-11:12:31.624(-3)?   at RocketChatIntegrationHandler.executeTriggers (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_integrations.js:1076:40)
I20170419-11:12:31.626(-3)?   at _wrapperFunction (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_integrations.js:2961:93)
I20170419-11:12:31.627(-3)?   at /home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:368:24
I20170419-11:12:31.628(-3)?   at Array.reduce (native)
I20170419-11:12:31.629(-3)?   at Object.RocketChat.callbacks.run (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:361:8)
I20170419-11:12:31.630(-3)?   at Object.RocketChat.archiveRoom (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:2284:23)
I20170419-11:12:31.631(-3)?   at [object Object].Meteor.methods.archiveRoom (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:11861:21)
I20170419-11:12:31.632(-3)?   at [object Object].methodsMap.(anonymous function) (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:1069:26)
I20170419-11:12:31.633(-3)?   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
I20170419-11:12:31.634(-3)?   at maybeAuditArgumentChecks (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1823:12)
I20170419-11:12:31.635(-3)?   at /home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1761:16
I20170419-11:12:31.635(-3)?   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170419-11:12:31.637(-3)?   at /home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1760:45
I20170419-11:12:31.641(-3)?   at [object Object]._.extend.applyAsync (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1759:12)
I20170419-11:12:31.642(-3)?   at [object Object]._.extend.apply (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1704:24)
I20170419-11:12:31.643(-3)?   at [object Object]._.extend.call (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1684:17)
I20170419-11:12:31.644(-3)?   at Archive (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_slashcommands-archive.js:75:9)
I20170419-11:12:31.644(-3)?   at Object.RocketChat.slashCommands.run (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:760:12)
I20170419-11:12:31.645(-3)?   at [object Object].Meteor.methods.slashCommand (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:772:37)
I20170419-11:12:31.645(-3)?   at [object Object].methodsMap.(anonymous function) (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:1069:26)
I20170419-11:12:31.646(-3)?   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
I20170419-11:12:31.646(-3)?   at maybeAuditArgumentChecks (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1823:12)
I20170419-11:12:31.648(-3)?   at /home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:905:20
I20170419-11:12:31.648(-3)?   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170419-11:12:31.650(-3)?   at /home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:904:41
I20170419-11:12:31.651(-3)?   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170419-11:12:31.651(-3)?   at /home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:903:46
I20170419-11:12:31.652(-3)?   at [object Object]._.extend.protocol_handlers.method (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:876:21)
I20170419-11:12:31.653(-3)?   at /home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:755:85
I20170419-11:12:31.653(-3)? 
I20170419-11:12:31.654(-3)?  => awaited here:
I20170419-11:12:31.655(-3)?   at Promise.await (/home/martin/.meteor/packages/promise/.0.8.8.pi3gbc++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:39:12)
I20170419-11:12:31.655(-3)?   at [object Object]._.extend.apply (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1717:22)
I20170419-11:12:31.656(-3)?   at [object Object]._.extend.call (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1684:17)
I20170419-11:12:31.657(-3)?   at Archive (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_slashcommands-archive.js:75:9)
I20170419-11:12:31.660(-3)?   at Object.RocketChat.slashCommands.run (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:760:12)
I20170419-11:12:31.660(-3)?   at [object Object].Meteor.methods.slashCommand (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:772:37)
I20170419-11:12:31.662(-3)?   at [object Object].methodsMap.(anonymous function) (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:1069:26)
I20170419-11:12:31.666(-3)?   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
I20170419-11:12:31.667(-3)?   at maybeAuditArgumentChecks (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1823:12)
I20170419-11:12:31.669(-3)?   at /home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:905:20
I20170419-11:12:31.669(-3)?   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170419-11:12:31.671(-3)?   at /home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:904:41
I20170419-11:12:31.672(-3)?   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170419-11:12:31.672(-3)?   at /home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:903:46
I20170419-11:12:31.674(-3)?   at [object Object]._.extend.protocol_handlers.method (/home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:876:21)
I20170419-11:12:31.675(-3)?   at /home/martin/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:755:85
I20170419-11:12:31.676(-3)? 
```

**Comment by graywolf336** [comment]
Best way to fix your current issue, open the room in Chrome then open developer tools and run the following Javascript code in the console: `Meteor.call('unarchiveRoom', Session.get('openedRoom'))`

**Comment by JakeSteam** [comment]
@graywolf336 Thanks for the workaround, will try when back in the office.

I believe we got our sysadmin to unarchive it directly in the db, but good to know there's a less drastic solution.

**Comment by vikas0121** [comment]
Hi,

I'm facing an issue, Is there any way to open the closed room and start the chat in the same room again?

**Comment by JakeSteam** [comment]
@vikas0121 Sounds unrelated to this issue, suggest you raise a new one.
