### ISSUE TITLE
TypeError: C annot read property 'names' of undefined

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#6729]
Rocket.Chat Version: 0.55.0

THis happend in Rocket chat Developer version 0.55.0 And Stuck on this

```
=> Started MongoDB.
W20170419-13:31:05.677(2)? (STDERR) Note: you are using a pure-JavaScript implem
entation of bcrypt.
W20170419-13:31:05.885(2)? (STDERR) While this implementation will work correctl
y, it is known to be
W20170419-13:31:05.886(2)? (STDERR) approximately three times slower than the na
tive implementation.
W20170419-13:31:05.888(2)? (STDERR) In order to use the native implementation in
stead, run
W20170419-13:31:05.889(2)? (STDERR)
W20170419-13:31:05.889(2)? (STDERR)   meteor npm install --save bcrypt
W20170419-13:31:05.890(2)? (STDERR)
W20170419-13:31:05.891(2)? (STDERR) in the root directory of your application.
I20170419-13:31:05.893(2)? Will load cache for users
I20170419-13:31:05.894(2)? 0 records load from users
I20170419-13:31:05.894(2)? Will load cache for rocketchat_room
I20170419-13:31:05.895(2)? 0 records load from rocketchat_room
I20170419-13:31:05.895(2)? Will load cache for rocketchat_subscription
I20170419-13:31:05.896(2)? 0 records load from rocketchat_subscription
I20170419-13:31:05.896(2)? Will load cache for rocketchat_settings
I20170419-13:31:05.897(2)? 297 records load from rocketchat_settings
I20170419-13:31:05.897(2)? Updating process.env.MAIL_URL
I20170419-13:31:05.898(2)? Will load cache for rocketchat_permissions
I20170419-13:31:05.898(2)? 0 records load from rocketchat_permissions
I20170419-13:31:05.899(2)? Will load cache for rocketchat_roles
I20170419-13:31:05.899(2)? 0 records load from rocketchat_roles
I20170419-13:31:05.900(2)? LocalStore: store created at
I20170419-13:31:05.901(2)? Exception in callback of async function: TypeError: C
annot read property 'names' of undefined
I20170419-13:31:05.901(2)?   at Object.addSettings (C:\Users\Ahmed ElSheikh\rc55
\.meteor\local\build\programs\server\packages\rocketchat_smarsh-connector.js:71:
29)
I20170419-13:31:05.902(2)?   at Object.RocketChat.settings.addGroup (C:\Users\Ah
med ElSheikh\rc55\.meteor\local\build\programs\server\packages\rocketchat_lib.js
:3379:8)
I20170419-13:31:05.902(2)?   at meteorInstall.node_modules.meteor.rocketchat:sma
rsh-connector.server.settings.js (C:\Users\Ahmed ElSheikh\rc55\.meteor\local\bui
ld\programs\server\packages\rocketchat_smarsh-connector.js:48:21)
I20170419-13:31:05.903(2)?   at fileEvaluate (packages\modules-runtime.js:197:9)

I20170419-13:31:05.903(2)?   at require (packages\modules-runtime.js:120:16)
I20170419-13:31:05.904(2)?   at C:\Users\Ahmed ElSheikh\rc55\.meteor\local\build
\programs\server\packages\rocketchat_smarsh-connector.js:378:1
I20170419-13:31:05.905(2)?   at C:\Users\Ahmed ElSheikh\rc55\.meteor\local\build
\programs\server\packages\rocketchat_smarsh-connector.js:388:3
I20170419-13:31:05.906(2)?   at C:\Users\Ahmed ElSheikh\rc55\.meteor\local\build
\programs\server\boot.js:303:34
I20170419-13:31:05.907(2)?   at Array.forEach (native)
I20170419-13:31:05.908(2)?   at Function._.each._.forEach (C:\Users\Ahmed ElShei
kh\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_b
undle\server-lib\node_modules\underscore\underscore.js:79:11)
I20170419-13:31:05.909(2)?   at C:\Users\Ahmed ElSheikh\rc55\.meteor\local\build
\programs\server\boot.js:128:5
I20170419-13:31:05.909(2)?   at C:\Users\Ahmed ElSheikh\rc55\.meteor\local\build
\programs\server\boot.js:352:5
I20170419-13:31:05.910(2)?   at Function.run (C:\Users\Ahmed ElSheikh\rc55\.mete
or\local\build\programs\server\profile.js:510:12)
I20170419-13:31:05.910(2)?   at C:\Users\Ahmed ElSheikh\rc55\.meteor\local\build
\programs\server\boot.js:351:11
I20170419-13:31:05.910(2)?

```

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @Nemra1 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing.

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**:
https://open.rocket.chat/channel/support (for general support)
* **The Rocket.Chat Community Dev Channel**:
https://open.rocket.chat/channel/dev (for development-focussed support)
* **The Rocket.Chat Community Support Forum**:
https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
