### ISSUE TITLE
LDAP sync - TimeLimitExceededError for bigger LDAP database

### ISSUE THREAD

**Issue by danpospisil** [RocketChat/Rocket.Chat#6732]
We have LDAP database which ldiff is over 300 Mb (because of user photos). When we try to run LDAP sync we get "TimeLimitExceededError". Is there any way how to increase this timeout? Thanks!

Full error is following:
```
rocketchat_2_1        | LDAP ➔ Search.info Searching user *
rocketchat_2_1        | rocketchat_logger rocketchat_logger.js:377 LDAP ➔ Search.error { [TimeLimitExceededError: Time Limit Exceeded]
rocketchat_2_1        |   dn: [Getter],
rocketchat_2_1        |   code: [Getter],
rocketchat_2_1        |   name: [Getter],
rocketchat_2_1        |   message: [Getter] }
rocketchat_2_1        | rocketchat_logger rocketchat_logger.js:377 LDAPSync ➔ error { [TimeLimitExceededError: Time Limit Exceeded]
rocketchat_2_1        |   dn: [Getter],
rocketchat_2_1        |   code: [Getter],
rocketchat_2_1        |   name: [Getter],
rocketchat_2_1        |   message: [Getter] }
rocketchat_2_1        | Exception while invoking method 'ldap_sync_users' TimeLimitExceededError: Time Limit Exceeded
rocketchat_2_1        |   at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
rocketchat_2_1        |   at LDAP.searchAllSync (packages/meteor.js:213:24)
rocketchat_2_1        |   at LDAP.searchUsersSync (/app/bundle/programs/server/packages/rocketchat_ldap.js:281:16)
rocketchat_2_1        |   at sync (/app/bundle/programs/server/packages/rocketchat_ldap.js:730:26)
rocketchat_2_1        |   at [object Object].Meteor.methods.ldap_sync_users (/app/bundle/programs/server/packages/rocketchat_ldap.js:1219:16)
rocketchat_2_1        |   at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1069:26)
rocketchat_2_1        |   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
rocketchat_2_1        |   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1823:12)
rocketchat_2_1        |   at /app/bundle/programs/server/packages/ddp-server.js:905:20
rocketchat_2_1        |   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
rocketchat_2_1        |   at /app/bundle/programs/server/packages/ddp-server.js:904:41
rocketchat_2_1        |   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
rocketchat_2_1        |   at /app/bundle/programs/server/packages/ddp-server.js:903:46
rocketchat_2_1        |   at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:876:21)
rocketchat_2_1        |   at /app/bundle/programs/server/packages/ddp-server.js:755:85
rocketchat_2_1        |     - - - - -
rocketchat_2_1        |   at messageCallback (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1419:45)
rocketchat_2_1        |   at Parser.onMessage (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1089:14)
rocketchat_2_1        |   at emitOne (events.js:77:13)
rocketchat_2_1        |   at Parser.emit (events.js:169:7)
rocketchat_2_1        |   at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:117:8)
rocketchat_2_1        |   at TLSSocket.onData (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1076:22)
rocketchat_2_1        |   at emitOne (events.js:77:13)
rocketchat_2_1        |   at TLSSocket.emit (events.js:169:7)
rocketchat_2_1        |   at readableAddChunk (_stream_readable.js:153:18)
rocketchat_2_1        |   at TLSSocket.Readable.push (_stream_readable.js:111:10)
rocketchat_2_1        |   at TLSWrap.onread (net.js:540:20)
```

Rocket.Chat Version: 0.55.0
Running Instances: 2
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by wcgcoder** [comment]
@MartinSchoeler @rodrigok 

Hello!
Respectfully recommend that this is *not* a support ticket. 
This is a fundamental breaking problem for anyone but the smallest organizations. 
The LDAP sync feature as it is implemented currently is unusable!

I can also replicate this in versions 0.56.0 through 0.57.2
