### ISSUE TITLE
Online status not reflected in '@'

### ISSUE THREAD

**Issue by drasbeck** [RocketChat/Rocket.Chat#6848]
Rocket.Chat Version: 0.56.0-develop
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

After running a `sudo snap refresh rocketchat-server --edge` on a RPi running Raspbian 9.0 (stretch) armv7l, online status is no longer reflected in most user-@'s throughout the UI. As shown in the attached screenie:

<img width="557" alt="online_status" src="https://cloud.githubusercontent.com/assets/8578706/25567899/cb9c2adc-2df7-11e7-84bd-e93e8f3798b2.png">

CMD+SHIFT+R does not change this behaviour, neither does restarting the server.

**Comment by drasbeck** [comment]
I get the same behavior with both Android and iOS-client.

**Comment by jszaszvari** [comment]
56.0_rc0 

Same issue 

Logs are filled with 

```
Exception while invoking method 'UserPresence:online' MongoError: not master and slaveOk=false at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15) at [object Object]._.extend._nextObject (/app/bundle/programs/server/packages/mongo.js:1059:47) at [object Object]._.extend.forEach (/app/bundle/programs/server/packages/mongo.js:1091:22) at [object Object]._.extend.map (/app/bundle/programs/server/packages/mongo.js:1101:10) at [object Object]._.extend.fetch (/app/bundle/programs/server/packages/mongo.js:1121:17) at [object Object].Cursor.(anonymous function) (/app/bundle/programs/server/packages/mongo.js:953:44) at [object Object].cursorProto.(anonymous function) (packages/rocketchat_monitoring.js:3350:32) at [object Object].kadira_Cursor_fetch [as fetch] (packages/rocketchat_monitoring.js:3744:32) at Object.<anonymous> (packages/matb33_collection-hooks.js:445:81) at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21) at [object Object].update (/app/bundle/programs/server/packages/mongo.js:3886:31) at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user.js:325:19) at Object.UserPresence.setConnection (packages/konecty_user-presence.js:191:29) at [object Object].Meteor.methods.UserPresence:online (packages/konecty_user-presence.js:293:18) at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30) at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1069:26) at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1823:12) at /app/bundle/programs/server/packages/ddp-server.js:905:20 at [object Object]._.extend.withValue (packages/meteor.js:1122:17) at /app/bundle/programs/server/packages/ddp-server.js:904:41 at [object Object]._.extend.withValue (packages/meteor.js:1122:17) at /app/bundle/programs/server/packages/ddp-server.js:903:46 at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:876:21) at packages/rocketchat_monitoring.js:2619:38 at [object Object]._.extend.withValue (packages/meteor.js:1122:17) at [object Object].sessionProto.protocol_handlers.method (packages/rocketchat_monitoring.js:2618:44) at /app/bundle/programs/server/packages/ddp-server.js:755:85 - - - - - at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11) at queryCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:212:36) at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18 at nextTickCallbackWith0Args (node.js:489:9) at process._tickDomainCallback (node.js:459:13)
4 hours agoMay 4th, 17:37:04 UTC```

Time to restore me thinks

**Comment by geekgonecrazy** [comment]
I believe this is good to close as of #6896 :+1:
