### ISSUE TITLE
Avatar LDAP Sync / Chunks out of order

### ISSUE THREAD

**Issue by willihelm** [RocketChat/Rocket.Chat#6864]
Rocket.Chat Version: 0.55.0
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: 4.5.0

I use RC with an LDAP AD and sometimes I realize that some users dont have an avatar in RC although there is one in the LDAP. In the Logs I see the following error in between the normal LDAP-Sync logs:

`Exception in callback of async function: MongoError: exception: chunks out of order   at Function.MongoError.create (/usr/local/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)   at /usr/local/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:483:72   at authenticateStragglers (/usr/local/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:429:16)   at [object Object].messageHandler (/usr/local/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:463:5)   at Socket.<anonymous> (/usr/local/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:349:20)   at emitOne (events.js:77:13)   at Socket.emit (events.js:169:7)   at readableAddChunk (_stream_readable.js:153:18)   at Socket.Readable.push (_stream_readable.js:111:10)   at TCP.onread (net.js:536:20)  `

When looking at the MongoDB I can see that there are hundrets of chunks for one user but this user has no avatar file. This blocks the avatar synchronization for all other new users. After deleting all of the chunks of that user (over 200) the LDAP-Sync throws no more errors and the avatar for that user is syncing correctly.
Hope that the the others sync too after restarting the server as allways when you change something to the DB.

**Comment by KervyN** [comment]
Hey, how did you do this?
I have the same issue.
