### ISSUE TITLE
[rocketchat-ui-vrecord] Object has no method 'mainModule'

### ISSUE THREAD

**Issue by panaceya** [RocketChat/Rocket.Chat#6874]
```
$ meteor    
=> Running Meteor from a checkout -- overrides project version (Meteor 1.4.3.2)
[[[[[ /usr/home/rocketchat/Rocket.Chat ]]]]]  

=> Started proxy.                             
TypeError: Object [object Object] has no method 'mainModule'
    at package.js:23:6
    at __bottom_mark__ (/tools/utils/parse-stack.js:59:14)
    at [object Object]._.extend.initFromPackageDir (/tools/isobuild/package-source.js:1049:52)
    at /tools/packaging/catalog/catalog-local.js:286:23
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at initSourceFromDir (/tools/packaging/catalog/catalog-local.js:273:20)
    at /tools/packaging/catalog/catalog-local.js:345:9
    at /tools/utils/buildmessage.js:592:26
    at Array.forEach (native)
    at Function._.each._.forEach (/usr/home/rocketchat/meteor/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/utils/buildmessage.js:590:9
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at enterJob (/tools/utils/buildmessage.js:321:26)
    at Object.forkJoin (/tools/utils/buildmessage.js:552:3)
    at [object Object]._.extend._loadLocalPackages (/tools/packaging/catalog/catalog-local.js:341:18)
    at [object Object]._.extend.initialize (/tools/packaging/catalog/catalog-local.js:86:10)
    at /tools/project-context.js:573:29
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at /tools/project-context.js:565:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._.extend._initializeCatalog (/tools/project-context.js:564:13)
    at /tools/project-context.js:257:35
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
    at /tools/runners/run-app.js:517:29
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at bundleApp (/tools/runners/run-app.js:516:31)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    at /tools/runners/run-app.js:396:12
TypeError: Object [object Object] has no method 'mainModule'
    at package.js:20:6
    at __bottom_mark__ (/tools/utils/parse-stack.js:59:14)
    at [object Object]._.extend.initFromPackageDir (/tools/isobuild/package-source.js:1049:52)
    at /tools/packaging/catalog/catalog-local.js:286:23
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at initSourceFromDir (/tools/packaging/catalog/catalog-local.js:273:20)
    at /tools/packaging/catalog/catalog-local.js:345:9
    at /tools/utils/buildmessage.js:592:26
    at Array.forEach (native)
    at Function._.each._.forEach (/usr/home/rocketchat/meteor/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/utils/buildmessage.js:590:9
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at enterJob (/tools/utils/buildmessage.js:321:26)
    at Object.forkJoin (/tools/utils/buildmessage.js:552:3)
    at [object Object]._.extend._loadLocalPackages (/tools/packaging/catalog/catalog-local.js:341:18)
    at [object Object]._.extend.initialize (/tools/packaging/catalog/catalog-local.js:86:10)
    at /tools/project-context.js:573:29
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at /tools/project-context.js:565:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._.extend._initializeCatalog (/tools/project-context.js:564:13)
    at /tools/project-context.js:257:35
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
    at /tools/runners/run-app.js:517:29
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at bundleApp (/tools/runners/run-app.js:516:31)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    at /tools/runners/run-app.js:396:12
TypeError: Object [object Object] has no method 'mainModule'
    at package.js:26:6
    at __bottom_mark__ (/tools/utils/parse-stack.js:59:14)
    at [object Object]._.extend.initFromPackageDir (/tools/isobuild/package-source.js:1049:52)
    at /tools/packaging/catalog/catalog-local.js:286:23
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at initSourceFromDir (/tools/packaging/catalog/catalog-local.js:273:20)
    at /tools/packaging/catalog/catalog-local.js:345:9
    at /tools/utils/buildmessage.js:592:26
    at Array.forEach (native)
    at Function._.each._.forEach (/usr/home/rocketchat/meteor/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/utils/buildmessage.js:590:9
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at enterJob (/tools/utils/buildmessage.js:321:26)
    at Object.forkJoin (/tools/utils/buildmessage.js:552:3)
    at [object Object]._.extend._loadLocalPackages (/tools/packaging/catalog/catalog-local.js:341:18)
    at [object Object]._.extend.initialize (/tools/packaging/catalog/catalog-local.js:86:10)
    at /tools/project-context.js:573:29
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at /tools/project-context.js:565:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._.extend._initializeCatalog (/tools/project-context.js:564:13)
    at /tools/project-context.js:257:35
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
    at /tools/runners/run-app.js:517:29
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at bundleApp (/tools/runners/run-app.js:516:31)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    at /tools/runners/run-app.js:396:12
=> Errors prevented startup:                  
   
   While reading package from `/usr/home/rocketchat/Rocket.Chat/packages/rocketchat-custom-oauth`:
   package.js:23:6: Object [object Object] has no method 'mainModule'
   
   While reading package from `/usr/home/rocketchat/Rocket.Chat/packages/rocketchat-google-natural-language`:
   package.js:20:6: Object [object Object] has no method 'mainModule'
   
   While reading package from `/usr/home/rocketchat/Rocket.Chat/packages/rocketchat-i18n`:
   vm.js:32:12: Unexpected token ILLEGAL
   at new Script (vm.js:32:12)
   at Function.Script.createScript (vm.js:48:10)
   at Object.files.runJavaScript (/tools/fs/files.js:933:32)
   at [object Object]._.extend.initFromPackageDir (/tools/isobuild/package-source.js:975:13)
   at /tools/packaging/catalog/catalog-local.js:286:23
   at /tools/utils/buildmessage.js:356:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:349:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:347:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at Object.enterJob (/tools/utils/buildmessage.js:321:26)
   at initSourceFromDir (/tools/packaging/catalog/catalog-local.js:273:20)
   at /tools/packaging/catalog/catalog-local.js:345:9
   at /tools/utils/buildmessage.js:592:26
   at Array.forEach (native)
   at Function._.each._.forEach (/usr/home/rocketchat/meteor/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at /tools/utils/buildmessage.js:590:9
   at /tools/utils/buildmessage.js:356:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:349:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:347:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at enterJob (/tools/utils/buildmessage.js:321:26)
   at Object.forkJoin (/tools/utils/buildmessage.js:552:3)
   at [object Object]._.extend._loadLocalPackages (/tools/packaging/catalog/catalog-local.js:341:18)
   at [object Object]._.extend.initialize (/tools/packaging/catalog/catalog-local.js:86:10)
   at /tools/project-context.js:573:29
   at /tools/utils/buildmessage.js:356:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:349:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:347:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at Object.enterJob (/tools/utils/buildmessage.js:321:26)
   at /tools/project-context.js:565:20
   at /tools/packaging/catalog/catalog.js:100:5
   at /tools/utils/buildmessage.js:268:13
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:261:29
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:259:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:250:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at Object.capture (/tools/utils/buildmessage.js:249:19)
   at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
   at ProjectContext._.extend._initializeCatalog (/tools/project-context.js:564:13)
   at /tools/project-context.js:257:35
   at /tools/utils/buildmessage.js:356:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:349:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:347:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at Object.enterJob (/tools/utils/buildmessage.js:321:26)
   at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
   at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
   at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
   at /tools/runners/run-app.js:517:29
   at /tools/utils/buildmessage.js:268:13
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:261:29
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:259:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:250:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at Object.capture (/tools/utils/buildmessage.js:249:19)
   at bundleApp (/tools/runners/run-app.js:516:31)
   at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
   at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
   at /tools/runners/run-app.js:396:12
   
   
   While reading package from `/usr/home/rocketchat/Rocket.Chat/packages/rocketchat-katex`:
   vm.js:32:12: Unexpected token ILLEGAL
   at new Script (vm.js:32:12)
   at Function.Script.createScript (vm.js:48:10)
   at Object.files.runJavaScript (/tools/fs/files.js:933:32)
   at [object Object]._.extend.initFromPackageDir (/tools/isobuild/package-source.js:975:13)
   at /tools/packaging/catalog/catalog-local.js:286:23
   at /tools/utils/buildmessage.js:356:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:349:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:347:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at Object.enterJob (/tools/utils/buildmessage.js:321:26)
   at initSourceFromDir (/tools/packaging/catalog/catalog-local.js:273:20)
   at /tools/packaging/catalog/catalog-local.js:345:9
   at /tools/utils/buildmessage.js:592:26
   at Array.forEach (native)
   at Function._.each._.forEach (/usr/home/rocketchat/meteor/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at /tools/utils/buildmessage.js:590:9
   at /tools/utils/buildmessage.js:356:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:349:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:347:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at enterJob (/tools/utils/buildmessage.js:321:26)
   at Object.forkJoin (/tools/utils/buildmessage.js:552:3)
   at [object Object]._.extend._loadLocalPackages (/tools/packaging/catalog/catalog-local.js:341:18)
   at [object Object]._.extend.initialize (/tools/packaging/catalog/catalog-local.js:86:10)
   at /tools/project-context.js:573:29
   at /tools/utils/buildmessage.js:356:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:349:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:347:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at Object.enterJob (/tools/utils/buildmessage.js:321:26)
   at /tools/project-context.js:565:20
   at /tools/packaging/catalog/catalog.js:100:5
   at /tools/utils/buildmessage.js:268:13
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:261:29
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:259:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:250:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at Object.capture (/tools/utils/buildmessage.js:249:19)
   at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
   at ProjectContext._.extend._initializeCatalog (/tools/project-context.js:564:13)
   at /tools/project-context.js:257:35
   at /tools/utils/buildmessage.js:356:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:349:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:347:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at Object.enterJob (/tools/utils/buildmessage.js:321:26)
   at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
   at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
   at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
   at /tools/runners/run-app.js:517:29
   at /tools/utils/buildmessage.js:268:13
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:261:29
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:259:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at /tools/utils/buildmessage.js:250:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
   at Object.capture (/tools/utils/buildmessage.js:249:19)
   at bundleApp (/tools/runners/run-app.js:516:31)
   at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
   at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
   at /tools/runners/run-app.js:396:12


   While reading package from `/usr/home/rocketchat/Rocket.Chat/packages/rocketchat-ui-vrecord`:
   package.js:26:6: Object [object Object] has no method 'mainModule'
```

Git master branch:
```
$ git rev-parse --verify HEAD
2e4306bcc108fe0d94df9c066fa23045485d8a7e
```
Git develop branch:
```
$ git rev-parse --verify HEAD
a4d6dda15692115d180e7557d907a2a6a6005116
```
```
$ freebsd-version
11.0-RELEASE-p3
$ ~/meteor/meteor --version
Unreleased, running from a checkout at 5dbffc4 (grafted, HEAD -> release-1.2.1-universal, origin/release-1.2.1-universal)
$HOME/meteor/dev_bundle/bin/node --version
v0.10.40
```

How fix and run rocket chat?

**Comment by PieterBogema** [comment]
Using https://rocket.chat/docs/installation/manual-installation/freebsd/ i got this error:
```
                                                                                
   While reading package from                                                   
   `/usr/home/rocketchat/Rocket.Chat/packages/rocketchat-markdown`:             
   package.js:21:6: Object [object Object] has no method 'mainModule'           
                                                                                
   While reading package from                                                   
   `/usr/home/rocketchat/Rocket.Chat/packages/rocketchat-ui-vrecord`:           
   package.js:25:6: Object [object Object] has no method 'mainModule'           
                                                                                
   While reading package from                                                   
   `/usr/home/rocketchat/Rocket.Chat/packages/rocketchat-webrtc`:               
   package.js:13:6: Object [object Object] has no method 'mainModule'           
                                                                                
=> Your application has errors. Waiting for file change.
```

Running this in a FreeNAS jail.

**Comment by grzegorz-uniti** [comment]
I have the same errors:

`While reading package from `/usr/home/rocketchat/Rocket.Chat/packages/rocketchat-ldap`:
package.js:23:6: Object [object Object] has no method 'mainModule'

While reading package from `/usr/home/rocketchat/Rocket.Chat/packages/rocketchat-markdown`:
package.js:21:6: Object [object Object] has no method 'mainModule'

While reading package from `/usr/home/rocketchat/Rocket.Chat/packages/rocketchat-ui-vrecord`:
package.js:25:6: Object [object Object] has no method 'mainModule'

While reading package from `/usr/home/rocketchat/Rocket.Chat/packages/rocketchat-webrtc`:
package.js:13:6: Object [object Object] has no method 'mainModule'`

Is anybody fix it?

**Comment by geekgonecrazy** [comment]
Please see community forum for FreeBSD help.  Currently community supported
