### ISSUE TITLE
Error: Greeting never received

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#6937]
Exception in defer callback:
```
Error: Greeting never received
  at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
  at Mail._syncSendMail (packages/meteor.js:213:24)
  at smtpSend (packages/email.js:110:13)
  at Object.Email.send (packages/email.js:168:5)
  at Object.Email.send (packages/rocketchat_monitoring.js:3496:28)
  at /app/bundle/programs/server/packages/rocketchat_lib.js:1650:14
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at packages/meteor.js:445:45
  at runWithEnvironment (packages/meteor.js:1176:24)

    - - - - -
  at SMTPConnection._formatError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)
  at SMTPConnection._onError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:531:20)
  at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:472:22)
  at Timer.listOnTimeout (timers.js:92:15)


```

**Comment by engelgabriel** [comment]
closed via https://github.com/RocketChat/Rocket.Chat/pull/6940
