### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by lazydino** [RocketChat/Rocket.Chat#6990]
Rocket.Chat Version: 0.56.0
Running Instances: 
DB Replicaset OpLog:
Node Version:

Heroku one-click deployment is not working. 
https://rocket.chat/docs/installation/paas-deployments/heroku/

<details>
```
-----> Node.js app detected
-----> Listing HEROKU_ environment variables
HEROKU_APP_ID:           
HEROKU_APP_NAME:         
HEROKU_DYNO_ID:          
HEROKU_RELEASE_VERSION:  
HEROKU_SLUG_COMMIT:      
HEROKU_SLUG_DESCRIPTION: 
-----> Installing meteor
Downloading Meteor distribution
Meteor 1.4.4.2 has been installed in your home directory (~/.meteor).
Now you need to do one of the following:
  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/app/tmp/cache/meteor/.meteor/packages/meteor-tool/1.4.4_2/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
-----> Target Meteor version: Meteor 1.4.4.2
-----> Checking if this meteor version supports --server-only
-----> Using node: v4.8.2
----->    and npm: 4.5.0
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> bcrypt@1.0.2 install /tmp/build_72282ea6b400407b9d413fd85b3e3aa5/RocketChat-Rocket.Chat-3018807/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.8.2 (node-v46 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/tmp/build_72282ea6b400407b9d413fd85b3e3aa5/RocketChat-Rocket.Chat-3018807/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
  COPY /tmp/build_72282ea6b400407b9d413fd85b3e3aa5/RocketChat-Rocket.Chat-3018807/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/tmp/build_72282ea6b400407b9d413fd85b3e3aa5/RocketChat-Rocket.Chat-3018807/node_modules/bcrypt/build'
> Rocket.Chat@0.56.0 postinstall /tmp/build_72282ea6b400407b9d413fd85b3e3aa5/RocketChat-Rocket.Chat-3018807
> cd packages/rocketchat-katex && npm i
rocketchat-katex@1.0.0 /tmp/build_72282ea6b400407b9d413fd85b3e3aa5/RocketChat-Rocket.Chat-3018807/packages/rocketchat-katex
└─┬ katex@0.7.1 
  └── match-at@0.1.0 
Rocket.Chat@0.56.0 /tmp/build_72282ea6b400407b9d413fd85b3e3aa5/RocketChat-Rocket.Chat-3018807
├─┬ babel-runtime@6.23.0 
│ ├── core-js@2.4.1 
│ └── regenerator-runtime@0.10.5 
├─┬ bcrypt@1.0.2 
│ ├── bindings@1.2.1 
│ ├── nan@2.5.0 
│ └─┬ node-pre-gyp@0.6.32 
│   ├─┬ mkdirp@0.5.1 
│   │ └── minimist@0.0.8 
│   ├─┬ nopt@3.0.6 
│   │ └── abbrev@1.1.0 
│   ├─┬ npmlog@4.1.0 
│   │ ├─┬ are-we-there-yet@1.1.4 
│   │ │ ├── delegates@1.0.0 
│   │ │ └─┬ readable-stream@2.2.9 
│   │ │   ├── buffer-shims@1.0.0  deduped
│   │ │   ├── core-util-is@1.0.2  deduped
│   │ │   ├── inherits@2.0.3  deduped
│   │ │   ├── isarray@1.0.0  deduped
│   │ │   ├── process-nextick-args@1.0.7  deduped
│   │ │   ├─┬ string_decoder@1.0.0 
│   │ │   │ └── buffer-shims@1.0.0  deduped
│   │ │   └── util-deprecate@1.0.2  deduped
│   │ ├── console-control-strings@1.1.0 
│   │ ├─┬ gauge@2.7.4 
│   │ │ ├── aproba@1.1.1 
│   │ │ ├── console-control-strings@1.1.0  deduped
│   │ │ ├── has-unicode@2.0.1 
│   │ │ ├── object-assign@4.1.1 
│   │ │ ├── signal-exit@3.0.2 
│   │ │ ├─┬ string-width@1.0.2 
│   │ │ │ ├── code-point-at@1.1.0 
│   │ │ │ ├─┬ is-fullwidth-code-point@1.0.0 
│   │ │ │ │ └── number-is-nan@1.0.1 
│   │ │ │ └── strip-ansi@3.0.1  deduped
│   │ │ ├─┬ strip-ansi@3.0.1 
│   │ │ │ └── ansi-regex@2.1.1 
│   │ │ └─┬ wide-align@1.1.2 
│   │ │   └── string-width@1.0.2  deduped
│   │ └── set-blocking@2.0.0 
│   ├─┬ rc@1.1.7 
│   │ ├── deep-extend@0.4.2 
│   │ ├── ini@1.3.4 
│   │ ├── minimist@1.2.0 
│   │ └── strip-json-comments@2.0.1 
│   ├─┬ request@2.81.0 
│   │ ├── aws-sign2@0.6.0 
│   │ ├── aws4@1.6.0 
│   │ ├── caseless@0.12.0 
│   │ ├─┬ combined-stream@1.0.5 
│   │ │ └── delayed-stream@1.0.0 
│   │ ├── extend@3.0.1 
│   │ ├── forever-agent@0.6.1 
│   │ ├─┬ form-data@2.1.4 
│   │ │ ├── asynckit@0.4.0 
│   │ │ ├── combined-stream@1.0.5  deduped
│   │ │ └── mime-types@2.1.15  deduped
│   │ ├─┬ har-validator@4.2.1 
│   │ │ ├─┬ ajv@4.11.8 
│   │ │ │ ├── co@4.6.0 
│   │ │ │ └─┬ json-stable-stringify@1.0.1 
│   │ │ │   └── jsonify@0.0.0 
│   │ │ └── har-schema@1.0.5 
│   │ ├─┬ hawk@3.1.3 
│   │ │ ├─┬ boom@2.10.1 
│   │ │ │ └── hoek@2.16.3  deduped
│   │ │ ├─┬ cryptiles@2.0.5 
│   │ │ │ └── boom@2.10.1  deduped
│   │ │ ├── hoek@2.16.3 
│   │ │ └─┬ sntp@1.0.9 
│   │ │   └── hoek@2.16.3  deduped
│   │ ├─┬ http-signature@1.1.1 
│   │ │ ├── assert-plus@0.2.0 
│   │ │ ├─┬ jsprim@1.4.0 
│   │ │ │ ├── assert-plus@1.0.0 
│   │ │ │ ├── extsprintf@1.0.2 
│   │ │ │ ├── json-schema@0.2.3 
│   │ │ │ └─┬ verror@1.3.6 
│   │ │ │   └── extsprintf@1.0.2  deduped
│   │ │ └─┬ sshpk@1.13.0 
│   │ │   ├── asn1@0.2.3 
│   │ │   ├── assert-plus@1.0.0 
│   │ │   ├─┬ bcrypt-pbkdf@1.0.1 
│   │ │   │ └── tweetnacl@0.14.5  deduped
│   │ │   ├─┬ dashdash@1.14.1 
│   │ │   │ └── assert-plus@1.0.0 
│   │ │   ├─┬ ecc-jsbn@0.1.1 
│   │ │   │ └── jsbn@0.1.1  deduped
│   │ │   ├─┬ getpass@0.1.7 
│   │ │   │ └── assert-plus@1.0.0 
│   │ │   ├─┬ jodid25519@1.0.2 
│   │ │   │ └── jsbn@0.1.1  deduped
│   │ │   ├── jsbn@0.1.1 
│   │ │   └── tweetnacl@0.14.5 
│   │ ├── is-typedarray@1.0.0 
│   │ ├── isstream@0.1.2 
│   │ ├── json-stringify-safe@5.0.1 
│   │ ├─┬ mime-types@2.1.15 
│   │ │ └── mime-db@1.27.0 
│   │ ├── oauth-sign@0.8.2 
│   │ ├── performance-now@0.2.0 
│   │ ├── qs@6.4.0 
│   │ ├── safe-buffer@5.0.1 
│   │ ├── stringstream@0.0.5 
│   │ ├─┬ tough-cookie@2.3.2 
│   │ │ └── punycode@1.4.1 
│   │ ├─┬ tunnel-agent@0.6.0 
│   │ │ └── safe-buffer@5.0.1  deduped
│   │ └── uuid@3.0.1 
│   ├─┬ rimraf@2.5.4 
│   │ └─┬ glob@7.1.1 
│   │   ├── fs.realpath@1.0.0 
│   │   ├─┬ inflight@1.0.6 
│   │   │ ├── once@1.4.0  deduped
│   │   │ └── wrappy@1.0.2  deduped
│   │   ├── inherits@2.0.3  deduped
│   │   ├─┬ minimatch@3.0.4 
│   │   │ └── brace-expansion@1.1.7  deduped
│   │   ├─┬ once@1.4.0 
│   │   │ └── wrappy@1.0.2  deduped
│   │   └── path-is-absolute@1.0.1 
│   ├── semver@5.3.0  deduped
│   ├─┬ tar@2.2.1 
│   │ ├─┬ block-stream@0.0.9 
│   │ │ └── inherits@2.0.3  deduped
│   │ ├─┬ fstream@1.0.11 
│   │ │ ├── graceful-fs@4.1.11 
│   │ │ ├── inherits@2.0.3  deduped
│   │ │ ├── mkdirp@0.5.1  deduped
│   │ │ └── rimraf@2.5.4  deduped
│   │ └── inherits@2.0.3 
│   └─┬ tar-pack@3.3.0 
│     ├─┬ debug@2.2.0 
│     │ └── ms@0.7.1 
│     ├── fstream@1.0.11  deduped
│     ├─┬ fstream-ignore@1.0.5 
│     │ ├── fstream@1.0.11  deduped
│     │ ├── inherits@2.0.3  deduped
│     │ └── minimatch@3.0.4  deduped
│     ├─┬ once@1.3.3 
│     │ └── wrappy@1.0.2 
│     ├─┬ readable-stream@2.1.5 
│     │ ├── buffer-shims@1.0.0 
│     │ ├── core-util-is@1.0.2 
│     │ ├── inherits@2.0.3  deduped
│     │ ├── isarray@1.0.0 
│     │ ├── process-nextick-args@1.0.7 
│     │ ├── string_decoder@0.10.31 
│     │ └── util-deprecate@1.0.2 
│     ├── rimraf@2.5.4  deduped
│     ├── tar@2.2.1  deduped
│     └── uid-number@0.0.6 
├── codemirror@5.25.2 
├── file-type@4.3.0 
├── highlight.js@9.11.0 
├── jquery@3.2.1 
├── mime-db@1.28.0 
├─┬ mime-type@3.0.4 
│ ├── media-typer@0.3.0 
│ ├─┬ minimatch@2.0.10 
│ │ └─┬ brace-expansion@1.1.7 
│ │   ├── balanced-match@0.4.2 
│ │   └── concat-map@0.0.1 
│ ├─┬ path.js@1.0.7 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ inherits-ex@1.1.8 
│ │ │ └── xtend@4.0.1  deduped
│ │ └── util-ex@0.3.15  deduped
│ └─┬ util-ex@0.3.15 
│   ├── inherits-ex@1.1.8  deduped
│   └── xtend@4.0.1 
├── moment@2.18.1 
├─┬ moment-timezone@0.5.13 
│ └── moment@2.18.1  deduped
├── photoswipe@4.1.2 
├─┬ prom-client@8.1.1 
│ ├─┬ tdigest@0.1.1 
│ │ └── bintrees@1.0.1 
│ └── util-extend@1.0.3 
├── semver@5.3.0 
└── toastr@2.1.2 
-----> Running before bundling
-----> Installing phantomjs.
-----> Building Meteor app with ROOT_URL: https://magnetarchat.herokuapp.com
=> Errors while initializing project:
While loading emojione:emojione@2.2.6...:
error: Command failed:
/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.4_2.5g3s0q++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --update-binary
Error checking path, continuing { [Error: EACCES: permission denied, open
'/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js']
errno: -13,
code: 'EACCES',
syscall: 'open',
path:
'/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
}
Phantom installation failed { [Error: EACCES: permission denied, open
'/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js']
errno: -13,
code: 'EACCES',
syscall: 'open',
path:
'/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
} Error: EACCES: permission denied, open
'/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
at Error (native)
at Object.fs.openSync (fs.js:549:18)
at Object.fs.writeFileSync (fs.js:1156:15)
at writeLocationFile
(/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:108:6)
at Promise._successFn
(/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:80:5)
at nextTickCallback
(/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
at nextTickCallbackWith0Args (node.js:489:9)
at process._tickCallback (node.js:418:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!
/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.4_2.5g3s0q++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-05-17T00_21_42_173Z-debug.log
Error checking path, continuing { [Error: EACCES: permission denied, open
'/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js']
errno: -13,
code: 'EACCES',
syscall: 'open',
path:
'/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
}
Phantom installation failed { [Error: EACCES: permission denied, open
'/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js']
errno: -13,
code: 'EACCES',
syscall: 'open',
path:
'/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
} Error: EACCES: permission denied, open
'/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
at Error (native)
at Object.fs.openSync (fs.js:549:18)
at Object.fs.writeFileSync (fs.js:1156:15)
at writeLocationFile
(/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:108:6)
at Promise._successFn
(/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:80:5)
at nextTickCallback
(/tmp/mt-14l7iqw/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
at nextTickCallbackWith0Args (node.js:489:9)
at process._tickCallback (node.js:418:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!
/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.4_2.5g3s0q++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-05-17T00_21_42_173Z-debug.log
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```
</details>

**Comment by JacobCZ** [comment]
I'm having exactly the same problem...

**Comment by ErvalhouS** [comment]
There are several issues with this same problem that are already closed. This has not been fixed.

**Comment by localguru** [comment]
See #7173

**Comment by sampaiodiego** [comment]
Heroku deployment were fixed by the following commits:
https://github.com/RocketChat/Rocket.Chat/commit/9afe9d166b0bc992ba8bb4465ac20fbb59856d95
https://github.com/RocketChat/meteor-buildpack-horse/commit/3e87e6a12350b94c9621b849b0801e643d0bf453
https://github.com/RocketChat/meteor-buildpack-horse/commit/a383919b51a18f603a3c39034ffcbbf552baae39

**Comment by ErvalhouS** [comment]
Deployment is not fixed for defaults on Heroku button.

**Comment by sampaiodiego** [comment]
the change that make it run is not on `master` branch yet (which is used on keroku button).

until there you can set `NODE_ENV` config variable as `development` :+1:

**Comment by jourdanrodrigues** [comment]
Same issue with `NODE_ENV` set to `development`.
