### ISSUE TITLE
Error on deleting file: path must be a string

### ISSUE THREAD

**Issue by Xarkam** [RocketChat/Rocket.Chat#7076]
Rocket.Chat Version: 0.56
Running Instances: docker
DB Replicaset OpLog: enabled
Node Version: 4.8.1

I have this error on deleting file in chat.

```
Exception in callback of async function: TypeError: path must be a string   
    at TypeError (native)   
    at Object.fs.stat (fs.js:830:11)   
    at LocalStore._this.delete (/app/bundle/programs/server/packages/jalik_ufs-local.js:156:20)   
    at Object.<anonymous> (/app/bundle/programs/server/packages/jalik_ufs.js:2070:28)   
    at packages/matb33_collection-hooks.js:558:28   
    at Array.forEach (native)   
    at Function._.each._.forEach (packages/underscore.js:139:11)   
    at packages/matb33_collection-hooks.js:557:11  
    at Array.forEach (native)   
    at Function._.each._.forEach (packages/underscore.js:139:11)   
    at Object.<anonymous> (packages/matb33_collection-hooks.js:556:9)   
    at Object.collection.(anonymous function) [as remove] (packages/matb33_collection-hooks.js:146:21)   
    at [object Object].remove (/app/bundle/programs/server/packages/mongo.js:3936:31)   
    at ModelsBaseDb.remove (/app/bundle/programs/server/packages/rocketchat_lib.js:9752:32)   
    at [object Object].model.remove (/app/bundle/programs/server/packages/rocketchat_lib.js:9405:24)   
    at /app/bundle/programs/server/packages/jalik_ufs-local.js:159:50   
    at runWithEnvironment (packages/meteor.js:1176:24)  
```

**Comment by showp1984** [comment]
The issue appears (for me) under the following circumstances:

1. setting file uploads to file system.
2. uploading a file with whitespaces & see it fail at that silently, no error message is being logged (eg: "not a pretty picture.jpg")
3. deleting that "empty" file from rocket.chat
4. Exception will pop up in the log
