### ISSUE TITLE
[Help Wanted] Unable to start rocket chat through pm2 instance 

### ISSUE THREAD

**Issue by ahsan-AJ** [RocketChat/Rocket.Chat#7091]
I am trying to start the server using pm2 configuration with existing example-pm2.json file.
It is working on console on pm2 cli but it is not being accessed from the URL.
I am using Amazon EC2 instance running on Ubuntu 16.04.
How do I resolve this issue ?

**Comment by richardwlu** [comment]
What do you mean it is not being accessed from the URL?

You are unable to start RC using PM2 but you say it is working on console?

Can you please elaborate and post your example-pm2.json file?

**Comment by jszaszvari** [comment]
Logs / Console output?

**Comment by fais3000** [comment]
@JSzaszvari In my case. It used to run properly till 0.67 Now on 0.68.2 it shows following errors if running via pm2

`14|rocketc | 2018-08-01 12:31:39 521: TypeError: promise.await is not a function
14|rocketc |     at Server.apply (/var/www/rocketchat/programs/server/packages/ddp-server.js:1749:27)
14|rocketc |     at Server.call (/var/www/rocketchat/programs/server/packages/ddp-server.js:1724:17)
14|rocketc |     at Meteor.startup (/var/www/rocketchat/programs/server/packages/steffo_meteor-accounts-saml.js:1214:17)
14|rocketc |     at Function.time (/var/www/rocketchat/programs/server/profile.js:309:28)
14|rocketc |     at /var/www/rocketchat/programs/server/boot.js:427:13
14|rocketc |     at /var/www/rocketchat/programs/server/boot.js:472:5
14|rocketc |     at Function.run (/var/www/rocketchat/programs/server/profile.js:510:12)
14|rocketc |     at /var/www/rocketchat/programs/server/boot.js:470:11
14|rocketc |`

If i run it directly as node main.js it works fine
