### ISSUE TITLE
configure SMTP，but not working

### ISSUE THREAD

**Issue by xutao3653** [RocketChat/Rocket.Chat#7131]
Rocket.Chat Version: 0.56.0 
Running Instances: rhel7
DB Replicaset OpLog: Disabled
Node Version: 4.4.7 - x64

When I configure SMTP, it doesn't work！
And test send mail faild
view logs：
`Sending test email to test@test.com 
[34mI20170527-17:52:23.792(8) Exception in callback of async function: TypeError: this is not a typed array.   
at Function.from (native)   
at LastNewline._flush (/root/pkg/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/mime-node/last-newline.js:28:26)   
at LastNewline.<anonymous> (_stream_transform.js:118:12)   
at LastNewline.g (events.js:260:16)   
at emitNone (events.js:67:13)   
at LastNewline.emit (events.js:166:7)   
at prefinish (_stream_writable.js:471:12)   
at finishMaybe (_stream_writable.js:479:7)   
at endWritable (_stream_writable.js:491:3)   
at LastNewline.Writable.end (_stream_writable.js:456:5)   
at PassThrough.onend (_stream_readable.js:498:10)   
at PassThrough.g (events.js:260:16)   
at emitNone (events.js:72:20)   
at PassThrough.emit (events.js:166:7)   
at endReadableNT (_stream_readable.js:921:12)   
at nextTickCallbackWith2Args (node.js:442:9)   
at process._tickDomainCallback (node.js:397:17)  `

please help！！！

**Comment by xutao3653** [comment]
@RocketChat/core

**Comment by MartinSchoeler** [comment]
@xutao3653 Tested in the latest develop branch and it worked fine, could you give us more info on what email service are you using?

**Comment by PatrickGriffiths** [comment]
I am having the same problem. I'm using whois.com's free email accounts that come with a domain and I'm hosting on a pi2 right now. If you need more information from somewhere please let me know how to get it for you! Would love to get this working ASAP. The hard work so far is definitely appreciated.

**Comment by xutao3653** [comment]
@MartinSchoeler I tested the mail and found something wrong with it，But using forgotten passwords can work！There are other mail services that can send mail. I don't know how it happened

**Comment by xutao3653** [comment]
@PatrickGriffiths You can try to forget the password directly, See if you get the mail?

**Comment by santhosh9** [comment]
can someone help me with the issue at below link
[https://github.com/RocketChat/Rocket.Chat/issues/7810](url)
