### ISSUE TITLE
File Upload Error

### ISSUE THREAD

**Issue by ToniIltanen** [RocketChat/Rocket.Chat#7163]
Rocket.Chat Version: 0.57.0-develop
Running Instances: 1
DB Replicaset OpLog: Disabled

Auth is setted up through Custom oAuth, which works fine.
When uploading a file (GridFX in use), the following error is given:

`
[34mI20170604-21:13:02.571(0) rocketchat_logger rocketchat_logger.js:377 [34mMeteor ➔ method ufsCreate -> userId: Th8Thjq2xoYcyJ6X2 , arguments:  { '0':     { name: 'testFile.pdf',      size: 34084,      type: 'application/pdf',      rid: 'EaGqfkHgRjNHiieYBTh8Thjq2xoYcyJ6X2',      description: '',      store: 'rocketchat_uploads' } } 

[34mI20170604-21:13:03.270(0) Exception in callback of async function: Error: Can't set headers after they are sent.   at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)   at ServerResponse.res.setHeader (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/patch.js:134:22)   at ServerResponse.res.setHeader (/app/bundle/programs/server/packages/rocketchat_cors.js:83:20)   at ServerResponse.setWriteHeadHeaders (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/on-headers/index.js:82:19)   at ServerResponse.writeHead (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/on-headers/index.js:41:36)   at WriteStream.<anonymous> (/app/bundle/programs/server/packages/jalik_ufs.js:1350:21)   at emitNone (events.js:72:20)   at WriteStream.emit (events.js:166:7)   at finishMaybe (_stream_writable.js:482:14)   at endWritable (_stream_writable.js:492:3)   at WriteStream.Writable.end (_stream_writable.js:457:5)   at /app/bundle/programs/server/packages/jalik_ufs.js:1339:20   at runWithEnvironment (packages/meteor.js:1176:24)  
`

**Comment by geekgonecrazy** [comment]
Do you get this consistently?  Or is there anything else you can do to reproduce this?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
