### ISSUE TITLE
rest api set user avatar

### ISSUE THREAD

**Issue by moxun33** [RocketChat/Rocket.Chat#7191]
Rocket.Chat Version: 0.54
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: V4.5.0

### when I try to set user avatar used rest api, the problem shown as below!  I have tried it  many times, still not working!  Can anybody gives me some help? Thank you!
![](https://ws4.sinaimg.cn/large/006tNc79gy1fgdk8lx3w8j30e803bglm.jpg)

**Comment by MartinSchoeler** [comment]
@moxun33 Sorry but can you be a little more clear? What do you mean with "problem shown as below"?
Thanks!

**Comment by moxun33** [comment]
@MartinSchoeler 
When I send a set avatar request, I got  error 'Bad Request'.  You can find it in the picture!.

**Comment by geekgonecrazy** [comment]
I believe #7045 fixes this

**Comment by moxun33** [comment]
Thanks!

**Comment by moxun33** [comment]
@MartinSchoeler 
 I have upgraded to V0.57.0-rc.1, still not solve the problem and get the same error as I said before.
The server echo some errors when I send the  request.
![](https://ws2.sinaimg.cn/large/006tNbRwgy1fgetf445v3j30ft09d0ss.jpg)

**Comment by geekgonecrazy** [comment]
Ah give removing the content type header and see if that makes any difference

**Comment by moxun33** [comment]
@geekgonecrazy 
![](https://ws1.sinaimg.cn/large/006tNbRwgy1fgeuw63vtqj30ei05taa7.jpg)

**Comment by geekgonecrazy** [comment]
Can you check your server logs for an error?  It looks like the server either wasn't up or crashed when you made that request

**Comment by moxun33** [comment]
The error occured like this!

```bash
Exception in callback of async function: Error: Forbidden [forbidden]
  at Object.<anonymous> (/opt/Rocket.Chat/programs/server/packages/jalik_ufs.js:2054:27)
  at packages/matb33_collection-hooks.js:352:26
  at Array.forEach (native)
  at Function._.each._.forEach (packages/underscore.js:139:11)
  at Object.<anonymous> (packages/matb33_collection-hooks.js:351:9)
  at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
  at [object Object].insert (/opt/Rocket.Chat/programs/server/packages/mongo.js:3832:38)
  at ModelsBaseDb.insert (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:10587:54)
  at [object Object].model.insert (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:10394:24)
  at LocalStore.Store.self.create (/opt/Rocket.Chat/programs/server/packages/jalik_ufs.js:1915:45)
  at FileUploadClass.insert (/opt/Rocket.Chat/programs/server/packages/rocketchat_file-upload.js:572:28)
  at Object.RocketChat.setUserAvatar (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:3589:12)
  at /opt/Rocket.Chat/programs/server/packages/rocketchat_api.js:3069:18
  at runWithEnvironment (packages/meteor.js:1176:24)
```

**Comment by graywolf336** [comment]
@moxun33 If you feel like being adventurous, can you try with the latest develop build? As we believe this was fixed already and is in develop, but we want to make sure

**Comment by graywolf336** [comment]
Also, how are you trying to set the avatar? Via a url or by providing an image?

**Comment by graywolf336** [comment]
Sorry for the spam of comments, but I just tired locally with the `develop` branch and it appears to be fixed.

`curl -H "X-Auth-Token: B4Xp00FX-o-vqXPy8hZxiEnlwk1VAley8ppWGL5fRsM" -H "X-User-Id: yAooaWu8LCsq5q4z5" -F "image=@PDBlWGI.jpg" http://localhost:3000/api/v1/users.setAvatar`

So, I'm going to go ahead and close this. If you try it with the develop branch and it doesn't work, feel free to reopen.

**Comment by moxun33** [comment]
It works ! Thanks!

**Comment by graywolf336** [comment]
Awesome, thanks for following up!
