### ISSUE TITLE
Image upload doesn't work

### ISSUE THREAD

**Issue by datngoews** [RocketChat/Rocket.Chat#7223]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.2

Hi, I suddenly get this error in syslog when uploading an image. On the GUI, the upload progress bar runs to 100% and `Internal server error` message appears.

The problem is that it works with other file types and it was ok last weeks...

Not sure if this is related to #2718 or not as the backtrace is different. Anything else that you guys need to clarify the issue?

```
rocketchat[430]: [Error: FileNotFound: no file with id rPRzZ3teHPDTztGcC found]
rocketchat[430]: Exception while invoking method 'ufsComplete' TypeError: Cannot read property 'pipe' of undefined
rocketchat[430]:   at Object.Future.wait (/var/www/html/Rocket.Chat/programs/server/node_modules/fibers/future.js:446:16)
rocketchat[430]:   at [object Object].Meteor.methods.ufsComplete (/var/www/html/Rocket.Chat/programs/server/packages/jalik_ufs.js:818:24)
rocketchat[430]:   at [object Object].methodsMap.(anonymous function) (/var/www/html/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1021:26)
rocketchat[430]:   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
rocketchat[430]:   at maybeAuditArgumentChecks (/var/www/html/Rocket.Chat/programs/server/packages/ddp-server.js:1823:12)
rocketchat[430]:   at /var/www/html/Rocket.Chat/programs/server/packages/ddp-server.js:905:20
rocketchat[430]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
rocketchat[430]:   at /var/www/html/Rocket.Chat/programs/server/packages/ddp-server.js:904:41
rocketchat[430]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
rocketchat[430]:   at /var/www/html/Rocket.Chat/programs/server/packages/ddp-server.js:903:46
rocketchat[430]:   at [object Object]._.extend.protocol_handlers.method (/var/www/html/Rocket.Chat/programs/server/packages/ddp-server.js:876:21)
rocketchat[430]:   at /var/www/html/Rocket.Chat/programs/server/packages/ddp-server.js:755:85
rocketchat[430]:     - - - - -
rocketchat[430]:   at gm.identify (/var/www/html/Rocket.Chat/programs/server/packages/rocketchat_file-upload.js:502:19)
rocketchat[430]:   at emitMany (events.js:108:13)
rocketchat[430]:   at gm.emit (events.js:182:7)
rocketchat[430]:   at gm.<anonymous> (/var/www/html/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_file/node_modules/gm/lib/getters.js:129:14)
rocketchat[430]:   at cb (/var/www/html/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_file/node_modules/gm/lib/command.js:322:16)
rocketchat[430]:   at gm._spawn (/var/www/html/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_file/node_modules/gm/lib/command.js:226:14)
rocketchat[430]:   at gm._exec (/var/www/html/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_file/node_modules/gm/lib/command.js:190:17)
rocketchat[430]:   at gm.identify (/var/www/html/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_file/node_modules/gm/lib/getters.js:127:10)
rocketchat[430]:   at LocalStore.UploadFS.store.Local.transformWrite (/var/www/html/Rocket.Chat/programs/server/packages/rocketchat_file-upload.js:517:43)
rocketchat[430]:   at LocalStore.transformWrite (/var/www/html/Rocket.Chat/programs/server/packages/jalik_ufs.js:2364:45)
rocketchat[430]:   at LocalStore.Store.self.write (/var/www/html/Rocket.Chat/programs/server/packages/jalik_ufs.js:2027:22)
rocketchat[430]:   at [object Object].Meteor.methods.ufsComplete (/var/www/html/Rocket.Chat/programs/server/packages/jalik_ufs.js:794:23)
rocketchat[430]:   at [object Object].methodsMap.(anonymous function) (/var/www/html/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1021:26)
rocketchat[430]:   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
rocketchat[430]:   at maybeAuditArgumentChecks (/var/www/html/Rocket.Chat/programs/server/packages/ddp-server.js:1823:12)
rocketchat[430]:   at /var/www/html/Rocket.Chat/programs/server/packages/ddp-server.js:905:20
rocketchat[430]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
rocketchat[430]:   at /var/www/html/Rocket.Chat/programs/server/packages/ddp-server.js:904:41
rocketchat[430]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
rocketchat[430]:   at /var/www/html/Rocket.Chat/programs/server/packages/ddp-server.js:903:46
rocketchat[430]:   at [object Object]._.extend.protocol_handlers.method (/var/www/html/Rocket.Chat/programs/server/packages/ddp-server.js:876:21)
rocketchat[430]:   at /var/www/html/Rocket.Chat/programs/server/packages/ddp-server.js:755:85
```

**Comment by datngoews** [comment]
no more issues with the latest version. Thank you guys anyway!
