### ISSUE TITLE
Error: [Can't find migration version 98]

### ISSUE THREAD

**Issue by ToniIltanen** [RocketChat/Rocket.Chat#7237]
using latest Develop -version, following error came after restarting which is preventing start:

Exception in callback of async function: Error: [Can't find migration version 98]
  at Object.Migrations._findIndexByVersion (/app/bundle/programs/server/packages/rocketchat_migrations.js:405:8)
  at Object.Migrations._migrateTo (/app/bundle/programs/server/packages/rocketchat_migrations.js:272:22)
  at Object.Migrations.migrateTo (/app/bundle/programs/server/packages/rocketchat_migrations.js:201:20)
  at meteorInstall.server.startup.migrations.xrun.js (/app/bundle/programs/server/app/app.js:4808:24)
  at fileEvaluate (packages/modules-runtime.js:197:9)
  at require (packages/modules-runtime.js:120:16)
  at /app/bundle/programs/server/app/app.js:9754:1
  at /app/bundle/programs/server/boot.js:303:34
  at Array.forEach (native)
  at Function._.each._.forEach (/app/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
  at /app/bundle/programs/server/boot.js:128:5
  at /app/bundle/programs/server/boot.js:352:5
  at Function.run (/app/bundle/programs/server/profile.js:510:12)
  at /app/bundle/programs/server/boot.js:351:11

**Edit**
I dropped the migration version directly from the db to 97, and the latest develop version started working again. Seems that the version 98 was added in some point, and removed in some point.

**Comment by ToniIltanen** [comment]
Closing, as this was a development issue (added migration - removed migration)
