### ISSUE TITLE
About Rocket.Chat+ Identification Broke in Linux Desktop Application

### ISSUE THREAD

**Issue by ml48603** [RocketChat/Rocket.Chat#7239]
Date of this post is 2017-06-13

Rocket.Chat Server v0.56
Server: Ubuntu 16.04 LTS Server with Snappy v2.25
Desktop application: RocketChat+ v2.7.0 running on Ubuntu MATE Desktop 16.04.2 LTS

Android Apps running on S4 Smartphone and S2 Tablet with Marshmallow 6.0
RocketChat+ Rated 3.6 is version 1.0.14 released 6/7/2017
RocketChat Rated 3.3 is version 2.5.0 released 12/22/2016

The Linux Desktop Application package "About Rocket.Chat+" results in an empty dialogue being thrown, along with a second dialogue that says:

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at Event.set (/opt/Rocket.Chat+/resources/electron.asar/browser/api/web-contents.js:252:22)
    at EventEmitter.electron.ipcMain.on (/opt/Rocket.Chat+/resources/app.asar/app/background.js:496:27)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/opt/Rocket.Chat+/resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

Has this problem been identified?

**Comment by geekgonecrazy** [comment]
@ml48603 this looks to be an issue with the desktop app can you create an issue on that repo?  https://github.com/RocketChat/Rocket.Chat.Electron/issues

**Comment by ml48603** [comment]
@geekgobecrazy
Done
see https://github.com/RocketChat/Rocket.Chat.Electron/issues/468

**Comment by geekgonecrazy** [comment]
:+1: thanks!
