### ISSUE TITLE
Random No user with username "username" was found!

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7258]
I am getting sporadic instances where I click on a direct message chat with a user that I have been having, and receive the above message in place of the chat.  Sometimes it takes several refreshes of the web page before I can see the messages.  Any idea why?

Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by cbanal** [comment]
We have the same issue with 0.53.0.

**Comment by 1stposition-ad** [comment]
I had the same problem because i changed the policy for the usernames, i changed the usernames in the chat as well, and had the exact same problem.
Maybe you did something similar?

**Comment by waveyuk** [comment]
Hi @1stposition-ad 
I think it has something to do if you refresh the browser.  Not quite able to pinpoint if this is definitely the issue though.

**Comment by Gummikavalier** [comment]
Specs; RC 0.56, one instance, OpLog enabled, node version 4.5.0.

We've seen this happening too, and always with direct message rooms. Personally I've encountered this problem several times after restoring (older) browser session after switching computers, but others have mentioned that it happens with desktop clients too.

We are now testing with OpLog disabled as we don't have recollection seeing this problem before enabling OpLog.

**Comment by Nosferous** [comment]
Also having this issue

Rocket.Chat Version: 0.55.0
Running Instances: 1
OpLog: Enabled
Node Version: 4.8.0
Server: Ubuntu 16.04 LTS

We are using LDAP authentication to our Windows AD server, has been this way since the beginning. There have been no changes to our AD config or this user. And it has seemingly been working perfectly fine.

One user specifically is having issues chatting with various users. Command+R would usually resolve it temporarily. As the issue was specific to one user one of my sys admins deleted the problem user. We recreated the user but the issue is still persisting. And one of the users he was having chatting with consistently gets the user not found error, command+R no longer clears it even temporarily.

Our users are using the latest version of Rocket.Chat+ Electron (2.8.0) I had the problem user switch to browser after recreation and issue persist. (Issue also existed on 2.4.x and later, we recently upgraded everyone to 2.8.0)

I have tried deleting rooms between these users in the Administration > Rooms.
Hiding direct messages on each users client and trying to recreate direct message.
Neither improve results.

I've also tried clearing the RocketChat cache in Message > General
I've also logged the problem user accounts onto different machines / browsers and it follows their accounts to different workstations they've never used before.

I did force disable OpLog and restarted R.C+ service but issue persist. I still want to try rebooting the server in full but have to do that off-hours. I do not expect that to resolve the issue. But hoping that forces a further change with the OpLog adjustment. The server has been rebooted multiple times since the user has had this issue with no clearing by-reboot. This reboot would just be first full reboot since post-OpLog setting change.

Anyone have further suggestions?

**Comment by chrisaudet** [comment]
We've run into this issue as well.  Like Nosferous, we've been using LDAP exclusively.  The issue is with one specific user who's account was deleted.  Later he logged in with the same credentials, and the issue began occurring.  I assume logging in with LDAP credentials re-created his rocketchat account.

The issue only occurs when messaging this user on the Cordova mobile app.  When using Electron desktop client or the web browser client, the user is able to send and receive messages normally.

Rocketchat 0.57.3

**Comment by technut371** [comment]
I'm also experiencing the same problem. We're authenticating to Crowd. A user account was deleted from RC. The user then logged in to RC and we could see that the account had been re-associated to the deleted account as the avatar still existed. DM to this user fails with 'No user with username "..." was found!.

We're also on rocketchat 0.57.3

**Comment by wonkaba** [comment]
Any luck with this? Having the same issue except cause was user changing name in LDAP

**Comment by notnamed** [comment]
Rocket.Chat Version: 0.62.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 8.9.4

Attempted fix: restart mongo, restart RocketChat

This started happening to multiple users this morning. We are not using any external auth, no user has changed their username (although this server does allow it). This was reported to me by a member of my community, and I was able to replicate. It seems like DMs between myself and other community members that I have not DMed with in the past days/weeks/months show this error, or show a blank DM session, whereas members that I have DMed with in the past 24 hours work fine. The message count in Admin -> Rooms for DMs where issues are reported is incorrect, showing 0 messages.

Interestingly, this seemed to start to fix itself on its own, about 15 minutes after my attempted fix. The DM session between myself and the user who initially reported this error is one of the ones that showed an empty room, instead of the username error; I tried to send several DMs to this user, and they showed up grey (indicating they were pending sending). After a few minutes, one of the test messages sent, and I was once again able to view our full conversation history. However, the DM count in Admin -> Rooms is still inaccurate, only reflecting the messages exchanged this morning. However, I am not able to replicate this fix across all my DM sessions that are currently showing this error.

I'm seeing two different stack traces with two different exceptions; both are included below.

```
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: Exception while invoking method 'createDirectMessage' TypeError: Cannot read property 'push' of undefined
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at ModelsBaseCache.processLocalJoinInserted (/opt/rocketchat/programs/server/packages/rocketchat_lib.js:10412:28)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at ModelsBaseCache.on.localRecord (/opt/rocketchat/programs/server/packages/rocketchat_lib.js:10313:12)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at emitOne (events.js:121:20)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at ModelsBaseCache.emit (events.js:211:7)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at ModelsBaseCache.insert (/opt/rocketchat/programs/server/packages/rocketchat_lib.js:10932:12)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at ModelsBaseDb.model._db.on (/opt/rocketchat/programs/server/packages/rocketchat_lib.js:10642:16)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at emitOne (events.js:116:13)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at ModelsBaseDb.emit (events.js:211:7)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at ModelsBaseDb.update (/opt/rocketchat/programs/server/packages/rocketchat_lib.js:11453:18)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at ModelsBaseDb.upsert (/opt/rocketchat/programs/server/packages/rocketchat_lib.js:11505:17)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at ModelRooms.upsert (/opt/rocketchat/programs/server/packages/rocketchat_lib.js:6339:21)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at MethodInvocation.createDirectMessage (/opt/rocketchat/programs/server/app/app.js:7956:29)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at MethodInvocation.methodsMap.(anonymous function) (/opt/rocketchat/programs/server/packages/rocketchat_lib.js:2158:28)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at maybeAuditArgumentChecks (/opt/rocketchat/programs/server/packages/ddp-server.js:1877:12)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at DDP._CurrentMethodInvocation.withValue (/opt/rocketchat/programs/server/packages/ddp-server.js:902:126)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at DDPServer._CurrentWriteFence.withValue (/opt/rocketchat/programs/server/packages/ddp-server.js:902:98)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at Promise (/opt/rocketchat/programs/server/packages/ddp-server.js:902:46)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at new Promise (<anonymous>:null:null)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at Session.method (/opt/rocketchat/programs/server/packages/ddp-server.js:875:23)
Mar 07 10:11:04 server.hostname.com start_rocketchat.bash[14116]: at /opt/rocketchat/programs/server/packages/ddp-server.js:754:85
```

```
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: Exception from sub stream-notify-room id PBFxZAZortNfLccaj TypeError: Cannot read property 'indexOf' of undefined
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at Subscription.<anonymous> (/opt/rocketchat/programs/server/packages/rocketchat_lib.js:6096:29)
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at Streamer.isReadAllowed (/opt/rocketchat/programs/server/packages/rocketchat_streamer.js:264:39)
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at Subscription.<anonymous> (/opt/rocketchat/programs/server/packages/rocketchat_streamer.js:372:18)
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at Subscription.<anonymous> (/opt/rocketchat/programs/server/packages/rocketchat_lib.js:2177:17)
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at packages/matb33_collection-hooks.js:307:21
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at maybeAuditArgumentChecks (/opt/rocketchat/programs/server/packages/ddp-server.js:1877:12)
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at DDP._CurrentPublicationInvocation.withValue (/opt/rocketchat/programs/server/packages/ddp-server.js:1188:73)
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at Subscription._runHandler (/opt/rocketchat/programs/server/packages/ddp-server.js:1188:51)
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at Session._startSubscription (/opt/rocketchat/programs/server/packages/ddp-server.js:1024:9)
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at Session.sub (/opt/rocketchat/programs/server/packages/ddp-server.js:816:12)
Mar 07 10:23:15 server.hostname.com start_rocketchat.bash[10891]: at /opt/rocketchat/programs/server/packages/ddp-server.js:754:85
```

**Comment by notnamed** [comment]
I was informed that another admin had tried to delete a user without a username last night, hitting the bug fixed in https://github.com/RocketChat/Rocket.Chat/pull/9986

The solution was to upgrade to 0.62.1, delete the bugged user, restart RocketChat, and instruct affected users to reload their clients.

**Comment by maraaaa** [comment]
Version:  0.63.2  (upgraded from 0.5 something, 0.53 would be my guess as that's what I wrote the cookbook for)
Database Migration Date | Mon Apr 30 2018 20:27:55 GMT-0600 (MDT)
Installed at | Fri Oct 06 2017 22:10:11 GMT-0600 (MDT)
Node Version: 0.8.3
Running Instances: 1
DB Replicaset OpLog: Default? (no idea what this is, so I'm _guessing_ it's Disabled...)

We're running into something similar I think, but it's only between one account and another.

Account A in a DM to Account B gets the "No user with username "Account B" was found!".

Account B can DM Account A and notifications pop.

Everyone else on the server can DM Account B.

I just made Account B an admin.

I just created a new account and that new account can DM Account A and Account B.

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/6535

**Comment by t4nec0** [comment]
Hello, I'm getting the same error in links from emails to DM in Rocket.Chat Version 3.10.5. 
Never experienced before, we upgraded from 2.x to 3.10 one week ago and now see the new link to go.rocket.chat which eventually redirects to our installation.
