### ISSUE TITLE
Image upload fails randomly : "gm" process 

### ISSUE THREAD

**Issue by fcoppolani** [RocketChat/Rocket.Chat#7283]
Rocket.Chat Version:  0.56
Running Instances:  2
DB Replicaset OpLog: On
Node Version: v4.5.0
240 users (not simultaneous)
VM with 3 Go RAM

I checked issues #6926 and #7223 , none of them seem to fit our trouble.
From a user point of view it looks quite like #7223, 100% loading and then a "token invalid".
We see that while uploading an image a process is launched ("gm"), it can takes a lots of memory. With a fresh start of the server, MongoDB uses less memory, images uploads are ok. After a while or by uploading a bigger image (few megs) "gm" processes takes a lots of memory (to 30%), and it gets killed by our oom-killer (that kills when systems needs memory). 

What is the purpose of this "gm" graphic library (I guess it has something to do with resizing?)? Why does it take so much memory ? Can we disable it ?

What we see in the logs :  

````
rocketchat[18555]: at exports._errnoException (util.js:907:11)
rocketchat[18555]: at WriteWrap.afterWrite (net.js:785:14)
rocketchat[18555]: Meteor ➔ publish null -> userId: null , arguments:  {}
rocketchat[18553]: Exception in setInterval callback: Error: write EPIPE
rocketchat[18553]: at Object.Future.wait (/opt/rocketchat/rocket.chat.0.56.0/programs/server/node_modules/fibers/future.js:449:15)
rocketchat[18553]: at [object Object]._.extend._nextObject (/opt/rocketchat/rocket.chat.0.56.0/programs/server/packages/mongo.js:1059:47)
rocketchat[18553]: at [object Object]._.extend.forEach (/opt/rocketchat/rocket.chat.0.56.0/programs/server/packages/mongo.js:1091:22)
rocketchat[18553]: at [object Object]._.extend.map (/opt/rocketchat/rocket.chat.0.56.0/programs/server/packages/mongo.js:1101:10)
rocketchat[18553]: at [object Object]._.extend.fetch (/opt/rocketchat/rocket.chat.0.56.0/programs/server/packages/mongo.js:1121:17)
rocketchat[18553]: at [object Object].Cursor.(anonymous function) [as fetch] (/opt/rocketchat/rocket.chat.0.56.0/programs/server/packages/mongo.js:953:44)
rocketchat[18553]: at Object.<anonymous> (packages/matb33_collection-hooks.js:445:81)
rocketchat[18553]: at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
rocketchat[18553]: at [object Object].update (/opt/rocketchat/rocket.chat.0.56.0/programs/server/packages/mongo.js:3899:31)
rocketchat[18553]: at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user.js:325:19)
rocketchat[18553]: at Object.InstanceStatus.ping (packages/konecty_multiple-instances-status.js:110:24)
rocketchat[18553]: at packages/konecty_multiple-instances-status.js:98:19
rocketchat[18553]: at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
rocketchat[18553]: at packages/meteor.js:445:45
rocketchat[18553]: at runWithEnvironment (packages/meteor.js:1176:24)
rocketchat[18553]: - - - - -
rocketchat[18553]: at exports._errnoException (util.js:907:11)
rocketchat[18553]: at WriteWrap.afterWrite (net.js:785:14)
rocketchat[18555]: Meteor ➔ publish null -> userId: null , arguments:  {}
rocketchat[18555]: Meteor ➔ method UserPresence:away -> userId: q9qrWcCKNRoidxAHz , arguments:  {}
rocketchat[18553]: Meteor ➔ publish null -> userId: null , arguments:  {}
rocketchat[18555]: stream error Network error: ws://localhost:8009/websocket: read ECONNRESET
rocketchat[18555]: Meteor ➔ publish null -> userId: null , arguments:  {}
rocketchat[18555]: Meteor ➔ publish null -> userId: null , arguments:  {}
rocketchat[18553]: Meteor ➔ publish null -> userId: null , arguments:  {}
rocketchat[18553]: Meteor ➔ publish null -> userId: null , arguments:  {}
rocketchat[18555]: Meteor ➔ publish null -> userId: null , arguments:  {}
rocketchat[18555]: Exception in callback of async function: Error: Command failed: gm identify: JPEG datastream contains no image (/tmp/gm2Fvbgo).
rocketchat[18555]: gm identify: Request did not return an image.
rocketchat[18555]: at ChildProcess.proc.on.onExit (/opt/rocketchat/rocket.chat.0.56.0/programs/server/npm/node_modules/meteor/rocketchat_file/node_modules/gm/lib/command.js:301:17)
rocketchat[18555]: at emitTwo (events.js:87:13)
rocketchat[18555]: at ChildProcess.emit (events.js:172:7)
rocketchat[18555]: at maybeClose (internal/child_process.js:829:16)
rocketchat[18555]: at Socket.<anonymous> (internal/child_process.js:319:11)
```
`

Thanks in advance for your help.

**Comment by KevLehman** [comment]
File upload feature has been refactored in newer versions, if u encounter the same issue, pls open a new one, thx
