### ISSUE TITLE
Error: [Can't find migration version 98]

### ISSUE THREAD

**Issue by Gyaviste** [RocketChat/Rocket.Chat#7299]
Rocket.Chat Version:  0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.5.0

---
Error `Exception in callback of async function: Error: [Can't find migration version 98]` occurs on server start.
Reinstallation helps to solve the problem, but problem appears again after server reboot.
Here is full error log:
```Exception in callback of async function: Error: [Can't find migration version 98]
  at Object.Migrations._findIndexByVersion (/root/Rocket.Chat/programs/server/packages/rocketchat_migrations.js:405:8)
  at Object.Migrations._migrateTo (/root/Rocket.Chat/programs/server/packages/rocketchat_migrations.js:272:22)
  at Object.Migrations.migrateTo (/root/Rocket.Chat/programs/server/packages/rocketchat_migrations.js:201:20)
  at meteorInstall.server.startup.migrations.xrun.js (/root/Rocket.Chat/programs/server/app/app.js:4808:24)
  at fileEvaluate (packages/modules-runtime.js:197:9)
  at require (packages/modules-runtime.js:120:16)
  at /root/Rocket.Chat/programs/server/app/app.js:9754:1
  at /root/Rocket.Chat/programs/server/boot.js:303:34
  at Array.forEach (native)
  at Function._.each._.forEach (/root/Rocket.Chat/programs/server/node_modules/underscore/underscore.js:79:11)
  at /root/Rocket.Chat/programs/server/boot.js:128:5
  at /root/Rocket.Chat/programs/server/boot.js:352:5
  at Function.run (/root/Rocket.Chat/programs/server/profile.js:510:12)
  at /root/Rocket.Chat/programs/server/boot.js:351:11
```
Here is my start script:
```export ROOT_URL=http://chat.kelni.pw/
export MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=001-rs
export MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=001-rs
export PORT=3000

node main.js
```

**Comment by teamsoo** [comment]
This happened to me when switching from develop to master branch.

Develop branch works fine.

**Comment by cdbessig** [comment]
This has happened on my snap this morning for almost no apparent reason.  I am using a snap that was installed using the snap instructions.

**Comment by andygreenegrass** [comment]
I just had the same problem. I had a previously working snap install just stop working.
I was on version 0.56.0. I tried `snap refresh` without any change.
I finally ran `sudo snap revert rocketchat-server` which successfully _reverted_ the version to 0.57.0
And now its working.

**Comment by cdbessig** [comment]
Andy, thank you!  That got me up and running again!  Thanks so much!

**Comment by Gyaviste** [comment]
So, is it 0.56 only problem?

**Comment by cdbessig** [comment]
Mine went back to 57 when it worked...so it seems to be something higher than 57.
root@rocketchat:~# sudo snap revert rocketchat-server
rocketchat-server reverted to 0.57.0

**Comment by djreynolds922** [comment]
Same problem here. I then manually updated again and it went back to 56 and wouldn't come back up without me reverting again. Anyone knows what'll happen when the snap tried to refresh itself?

**Comment by cdbessig** [comment]
For me it happened at 12:22am EST today.  We have nagios monitoring the server and thats when the first alert came through to us.

**Comment by moisesmcardona** [comment]
Having the same issue

**Comment by moisesmcardona** [comment]
I can confirm, the revert command fixed itas well for me

**Comment by AhmadIbrahiim** [comment]
Any update related to this issue !! @Gyaviste
