### ISSUE TITLE
Creating rocketchat user fails: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by ariep** [RocketChat/Rocket.Chat#7339]
Rocket.Chat Version: 0.57.0-rc.2
Running Instances: 2
DB Replicaset OpLog: Enabled
Node Version: v4.6.1

Sometimes creating new rocketchat users via the rocketchat api gives the following error message: `Cannot read property 'username' of undefined`.

I haven't yet found a pattern describing which attempts give the error, and which don't. All api requests are very similar (being built up programmatically), with only the contents of the fields varying. The username field of the request is of course defined and nonempty.

BTW the rocketchat user account is in fact created, but not all properties are set properly: for instance the account/email address is not set as verified even though this was requested in the api call.

**Comment by iamcmnut** [comment]
I also have this issue.

**Comment by ChrisGalliano** [comment]
Looks as if you are using the wrong userId

**Comment by ariep** [comment]
> Looks as if you are using the wrong userId

What do you mean? When creating a new user I don't use any userId: the ID of the newly created user is generated by Rocketchat, right?

**Comment by ChrisGalliano** [comment]
I'm sorry, I thought you were using the "/api/v1/users.update". Got a similar error message when working with the "update".
There are no ideas why this can happen with the "/api/v1/users.create"

**Comment by osfunapps** [comment]
does someone solved this?

**Comment by MarcosSpessatto** [comment]
Hello @ariep, could you provide us with the call data? Since you yourself said there is no standard for this problem to happen, I could not simulate the problem locally.

@osfunapps if you also suffer from this problem and can also provide the data that possibly causes this problem, it would be interesting.

**Comment by D3473R** [comment]
Hello, just had the same error `Uncaught TypeError: Cannot read property '_id' of undefined`
I am on version `1.0.2`
For me the issue only appears if i'm trying to add a user with a png profile picture.
If i leave the profile picture unset it works and i can add id later.

**Comment by peterchiuglg** [comment]
same here. any luck fixing this?

**Comment by peterchiuglg** [comment]
Hope this helps

```
}
  toJSON: [Function (anonymous)]
  isAxiosError: true,
  },
    }
      error: "Cannot read property 'username' of undefined"
      success: false,
    data: {
    },
      [Symbol(kOutHeaders)]: [Object: null prototype]
      [Symbol(isCorked)]: false,
      [Symbol(kNeedDrain)]: false,
      _redirectable: [Writable],
      reusedSocket: false,
      maxHeadersCount: null,
      parser: null,
      upgradeOrConnect: false,
      timeoutCb: null,
      aborted: false,
      res: [IncomingMessage],
      _ended: true,
      path: '/api/v1/users.create',
      method: 'POST',
      socketPath: undefined,
      agent: [Agent],
      _onPendingData: [Function: noopPendingOutput],
        '\r\n',
        'Connection: close\r\n' +
        'Host: xxxxxxxxxxxxxxxx\r\n' +
        'Content-Length: 156\r\n' +
        'User-Agent: axios/0.19.0\r\n' +
        'X-Auth-Token: xxxxxxxxxxxxxxxx\r\n' +
        'X-User-Id: xxxxxxxxxxxxxxxx\r\n' +
        'Content-Type: application/json\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
      _header: 'POST /api/v1/users.create HTTP/1.1\r\n' +
      socket: [TLSSocket],
      _headerSent: true,
      finished: true,
      _trailer: '',
      _hasBody: true,
      _contentLength: null,
      _removedTE: false,
      _removedContLen: false,
      _removedConnection: false,
      sendDate: false,
      useChunkedEncodingByDefault: true,
      shouldKeepAlive: false,
      chunkedEncoding: false,
      _last: true,
      writable: true,
      outputSize: 0,
      outputData: [],
      _maxListeners: undefined,
      _eventsCount: 6,
      _events: [Object: null prototype],
    request: <ref *1> ClientRequest {
    },
      validateStatus: [Function: validateStatus]
      maxContentLength: -1,
      xsrfHeaderName: 'X-XSRF-TOKEN',
      xsrfCookieName: 'XSRF-TOKEN',
      adapter: [Function: httpAdapter],
      timeout: 60000,
      transformResponse: [Array],
      transformRequest: [Array],
      headers: [Object],
      data: '{"email":"BC57F009-EC2C-4153-BAD9-991AFA67ACFA@localhost","password":"xxxxxxxxxxxxxx","username":"BC57F009-EC2C-4153-BAD9-991AFA67ACFA","name":"xxxxxxxxxxxx"}',
      method: 'post',
      url: 'https://xxxxxxxxxxxxxxxx/api/v1/users.create',
    config: {
    },
      vary: 'Accept-Encoding'
      'access-control-allow-headers': 'Origin, X-Requested-With, Content-Type, Accept, X-User-Id, X-Auth-Token',
      pragma: 'no-cache',
      'cache-control': 'no-store',
      'x-instance-id': 'xxxxxxxxxxxxxxxxxxx',
      'access-control-allow-origin': '*',
      connection: 'close',
      'transfer-encoding': 'chunked',
      'content-type': 'application/json',
      date: 'Mon, 04 Nov 2019 03:00:10 GMT',
    headers: {
    statusText: 'Bad Request',
    status: 400,
  response: {
  },
    }
      host: [Array]
      'content-length': [Array],
      'user-agent': [Array],
      'x-auth-token': [Array],
      'x-user-id': [Array],
      'content-type': [Array],
      accept: [Array],
    [Symbol(kOutHeaders)]: [Object: null prototype] {
    [Symbol(isCorked)]: false,
    [Symbol(kNeedDrain)]: false,
    },
      _currentUrl: 'https://xxxxxxxxxxxxxxxx/api/v1/users.create'
      _currentRequest: [Circular *1],
      _onNativeResponse: [Function (anonymous)],
      _requestBodyBuffers: [],
      _requestBodyLength: 156,
      _redirects: [],
      _redirectCount: 0,
      _options: [Object],
      _maxListeners: undefined,
      _eventsCount: 2,
      _events: [Object: null prototype],
      writable: true,
      _writableState: [WritableState],
    _redirectable: Writable {
    reusedSocket: false,
    maxHeadersCount: null,
    parser: null,
    upgradeOrConnect: false,
    timeoutCb: null,
    aborted: false,
    },
      redirects: []
      responseUrl: 'https://xxxxxxxxxxxxxxxx/api/v1/users.create',
      req: [Circular *1],
      _dumped: false,
      _consuming: true,
      client: [TLSSocket],
      statusMessage: 'Bad Request',
      statusCode: 400,
      method: null,
      url: '',
      upgrade: false,
      aborted: false,
      rawTrailers: [],
      trailers: {},
      rawHeaders: [Array],
      headers: [Object],
      complete: true,
      httpVersion: '1.1',
      httpVersionMinor: 1,
      httpVersionMajor: 1,
      socket: [TLSSocket],
      _maxListeners: undefined,
      _eventsCount: 3,
      _events: [Object: null prototype],
      readable: false,
      _readableState: [ReadableState],
    res: IncomingMessage {
    _ended: true,
    path: '/api/v1/users.create',
    method: 'POST',
    socketPath: undefined,
    },
      _sessionCache: [Object]
      maxCachedSessions: 100,
      maxFreeSockets: 256,
      maxSockets: Infinity,
      keepAlive: false,
      keepAliveMsecs: 1000,
      freeSockets: {},
      sockets: [Object],
      requests: {},
      options: [Object],
      protocol: 'https:',
      defaultPort: 443,
      _maxListeners: undefined,
      _eventsCount: 1,
      _events: [Object: null prototype],
    agent: Agent {
    _onPendingData: [Function: noopPendingOutput],
      '\r\n',
      'Connection: close\r\n' +
      'Host: xxxxxxxxxxxxxxxx\r\n' +
      'Content-Length: 156\r\n' +
      'User-Agent: axios/0.19.0\r\n' +
      'X-Auth-Token: xxxxxxxxxxxxxxxx\r\n' +
      'X-User-Id: xxxxxxxxxxxxxxxx\r\n' +
      'Content-Type: application/json\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
    _header: 'POST /api/v1/users.create HTTP/1.1\r\n' +
    },
      [Symbol(connect-options)]: [Object]
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(timeout)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(asyncId)]: 2958142,
      [Symbol(res)]: [TLSWrap],
      _httpMessage: [Circular *1],
      parser: null,
      _rejectUnauthorized: false,
      _requestCert: true,
      ssl: [TLSWrap],
      _server: null,
      server: undefined,
      _pendingEncoding: '',
      _pendingData: null,
      _sockname: null,
      allowHalfOpen: false,
      writable: false,
      _writableState: [WritableState],
      _maxListeners: undefined,
      readable: true,
      _readableState: [ReadableState],
      _host: 'xxxxxxxxxxxxxxxx',
      _parent: null,
      _hadError: false,
      connecting: false,
      _eventsCount: 9,
      _events: [Object: null prototype],
      encrypted: true,
      authorizationError: null,
      authorized: true,
      alpnProtocol: false,
      servername: false,
      _SNICallback: null,
      _controlReleased: true,
      _newSessionPending: false,
      _securePending: false,
      _secureEstablished: true,
      _tlsOptions: [Object],
    socket: TLSSocket {
    _headerSent: true,
    finished: true,
    _trailer: '',
    _hasBody: true,
    _contentLength: null,
    _removedTE: false,
    _removedContLen: false,
    _removedConnection: false,
    sendDate: false,
    useChunkedEncodingByDefault: true,
    shouldKeepAlive: false,
    chunkedEncoding: false,
    _last: true,
    writable: true,
    outputSize: 0,
    outputData: [],
    _maxListeners: undefined,
    _eventsCount: 6,
    },
      prefinish: [Function: requestOnPrefinish]
      timeout: [Function (anonymous)],
      error: [Function (anonymous)],
      aborted: [Function (anonymous)],
      abort: [Function (anonymous)],
      socket: [Function (anonymous)],
    _events: [Object: null prototype] {
  request: <ref *1> ClientRequest {
  },
    validateStatus: [Function: validateStatus]
    maxContentLength: -1,
    xsrfHeaderName: 'X-XSRF-TOKEN',
    xsrfCookieName: 'XSRF-TOKEN',
    adapter: [Function: httpAdapter],
    timeout: 60000,
    transformResponse: [ [Function: transformResponse] ],
    transformRequest: [ [Function: transformRequest] ],
    },
      'Content-Length': 156
      'User-Agent': 'axios/0.19.0',
      'X-Auth-Token': 'xxxxxxxxxxxxxxxx',
      'X-User-Id': 'xxxxxxxxxxxxxxxx',
      'Content-Type': 'application/json',
      Accept: 'application/json, text/plain, */*',
    headers: {
    data: '{"email":"BC57F009-EC2C-4153-BAD9-991AFA67ACFA@localhost","password":"xxxxxxxxxxxxxxxxxxx","username":"BC57F009-EC2C-4153-BAD9-991AFA67ACFA","name":"Emma Pan (GLG)"}',
    method: 'post',
    url: 'https://xxxxxxxxxxxxxxxx/api/v1/users.create',
  config: {
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    at endReadableNT (_stream_readable.js:1198:12)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.handleStreamEnd (/home/ubuntu/app/node_modules/axios/lib/adapters/http.js:237:11)
    at settle (/home/ubuntu/app/node_modules/axios/lib/core/settle.js:17:12)
    at createError (/home/ubuntu/app/node_modules/axios/lib/core/createError.js:16:15)
Error: Request failed with status code 400
}
  toJSON: [Function (anonymous)]
  isAxiosError: true,
  },
    }
      error: "Cannot read property 'username' of undefined"
      success: false,
    data: {
    },
      [Symbol(kOutHeaders)]: [Object: null prototype]
      [Symbol(isCorked)]: false,
      [Symbol(kNeedDrain)]: false,
      _redirectable: [Writable],
      reusedSocket: false,
      maxHeadersCount: null,
      parser: null,
      upgradeOrConnect: false,
      timeoutCb: null,
      aborted: false,
      res: [IncomingMessage],
      _ended: true,
      path: '/api/v1/users.create',
      method: 'POST',
      socketPath: undefined,
      agent: [Agent],
      _onPendingData: [Function: noopPendingOutput],
        '\r\n',
        'Connection: close\r\n' +
        'Host: xxxxxxxxxxxxxxxx\r\n' +
        'Content-Length: 156\r\n' +
        'User-Agent: axios/0.19.0\r\n' +
        'X-Auth-Token: xxxxxxxxxxxxxxxx\r\n' +
        'X-User-Id: xxxxxxxxxxxxxxxx\r\n' +
        'Content-Type: application/json\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
      _header: 'POST /api/v1/users.create HTTP/1.1\r\n' +
      socket: [TLSSocket],
      _headerSent: true,
      finished: true,
      _trailer: '',
      _hasBody: true,
      _contentLength: null,
      _removedTE: false,
      _removedContLen: false,
      _removedConnection: false,
      sendDate: false,
      useChunkedEncodingByDefault: true,
      shouldKeepAlive: false,
      chunkedEncoding: false,
      _last: true,
      writable: true,
      outputSize: 0,
      outputData: [],
      _maxListeners: undefined,
      _eventsCount: 6,
      _events: [Object: null prototype],
    request: <ref *1> ClientRequest {
    },
      validateStatus: [Function: validateStatus]
      maxContentLength: -1,
      xsrfHeaderName: 'X-XSRF-TOKEN',
      xsrfCookieName: 'XSRF-TOKEN',
      adapter: [Function: httpAdapter],
      timeout: 60000,
      transformResponse: [Array],
      transformRequest: [Array],
      headers: [Object],
      data: '{"email":"BC57F009-EC2C-4153-BAD9-991AFA67ACFA@localhost","password":"xxxxxxxxxxxxxxxxxxx","username":"BC57F009-EC2C-4153-BAD9-991AFA67ACFA","name":"Emma Pan (GLG)"}',
      method: 'post',
      url: 'https://xxxxxxxxxxxxxxxx/api/v1/users.create',
    config: {
    },
      vary: 'Accept-Encoding'
      'access-control-allow-headers': 'Origin, X-Requested-With, Content-Type, Accept, X-User-Id, X-Auth-Token',
      pragma: 'no-cache',
      'cache-control': 'no-store',
      'x-instance-id': 'xxxxxxxxxxxxxxxxxxx',
      'access-control-allow-origin': '*',
      connection: 'close',
      'transfer-encoding': 'chunked',
      'content-type': 'application/json',
      date: 'Mon, 04 Nov 2019 03:00:10 GMT',
    headers: {
    statusText: 'Bad Request',
    status: 400,
  response: {
  },
    }
      host: [Array]
      'content-length': [Array],
      'user-agent': [Array],
      'x-auth-token': [Array],
      'x-user-id': [Array],
      'content-type': [Array],
      accept: [Array],
    [Symbol(kOutHeaders)]: [Object: null prototype] {
    [Symbol(isCorked)]: false,
    [Symbol(kNeedDrain)]: false,
    },
      _currentUrl: 'https://xxxxxxxxxxxxxxxx/api/v1/users.create'
      _currentRequest: [Circular *1],
      _onNativeResponse: [Function (anonymous)],
      _requestBodyBuffers: [],
      _requestBodyLength: 156,
      _redirects: [],
      _redirectCount: 0,
      _options: [Object],
      _maxListeners: undefined,
      _eventsCount: 2,
      _events: [Object: null prototype],
      writable: true,
      _writableState: [WritableState],
    _redirectable: Writable {
    reusedSocket: false,
    maxHeadersCount: null,
    parser: null,
    upgradeOrConnect: false,
    timeoutCb: null,
    aborted: false,
    },
      redirects: []
      responseUrl: 'https://xxxxxxxxxxxxxxxx/api/v1/users.create',
      req: [Circular *1],
      _dumped: false,
      _consuming: true,
      client: [TLSSocket],
      statusMessage: 'Bad Request',
      statusCode: 400,
      method: null,
      url: '',
      upgrade: false,
      aborted: false,
      rawTrailers: [],
      trailers: {},
      rawHeaders: [Array],
      headers: [Object],
      complete: true,
      httpVersion: '1.1',
      httpVersionMinor: 1,
      httpVersionMajor: 1,
      socket: [TLSSocket],
      _maxListeners: undefined,
      _eventsCount: 3,
      _events: [Object: null prototype],
      readable: false,
      _readableState: [ReadableState],
    res: IncomingMessage {
    _ended: true,
    path: '/api/v1/users.create',
    method: 'POST',
    socketPath: undefined,
    },
      _sessionCache: [Object]
      maxCachedSessions: 100,
      maxFreeSockets: 256,
      maxSockets: Infinity,
      keepAlive: false,
      keepAliveMsecs: 1000,
      freeSockets: {},
      sockets: [Object],
      requests: {},
 [Object],
      options:[TIMING] /api/v1/users.create = 1111
      protocol: 'https:',
      defaultPort: 443,
      _maxListeners: undefined,
      _eventsCount: 1,
      _events: [Object: null prototype],
    agent: Agent {
    _onPendingData: [Function: noopPendingOutput],
      '\r\n',
      'Connection: close\r\n' +
      'Host: xxxxxxxxxxxxxxxx\r\n' +
      'Content-Length: 156\r\n' +
      'User-Agent: axios/0.19.0\r\n' +
      'X-Auth-Token: xxxxxxxxxxxxxxxx\r\n' +
      'X-User-Id: xxxxxxxxxxxxxxxx\r\n' +
      'Content-Type: application/json\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
    _header: 'POST /api/v1/users.create HTTP/1.1\r\n' +
    },
      [Symbol(connect-options)]: [Object]
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(timeout)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(asyncId)]: 2958142,
      [Symbol(res)]: [TLSWrap],
      _httpMessage: [Circular *1],
      parser: null,
      _rejectUnauthorized: false,
      _requestCert: true,
      ssl: [TLSWrap],
      _server: null,
      server: undefined,
      _pendingEncoding: '',
      _pendingData: null,
      _sockname: null,
      allowHalfOpen: false,
      writable: false,
      _writableState: [WritableState],
      _maxListeners: undefined,
      readable: true,
      _readableState: [ReadableState],
      _host: 'xxxxxxxxxxxxxxxx',
      _parent: null,
      _hadError: false,
      connecting: false,
      _eventsCount: 9,
      _events: [Object: null prototype],
      encrypted: true,
      authorizationError: null,
      authorized: true,
      alpnProtocol: false,
      servername: false,
      _SNICallback: null,
      _controlReleased: true,
      _newSessionPending: false,
      _securePending: false,
      _secureEstablished: true,
      _tlsOptions: [Object],
    socket: TLSSocket {
    _headerSent: true,
    finished: true,
    _trailer: '',
    _hasBody: true,
    _contentLength: null,
    _removedTE: false,
    _removedContLen: false,
    _removedConnection: false,
    sendDate: false,
    useChunkedEncodingByDefault: true,
    shouldKeepAlive: false,
    chunkedEncoding: false,
    _last: true,
    writable: true,
    outputSize: 0,
    outputData: [],
    _maxListeners: undefined,
    _eventsCount: 6,
    },
      prefinish: [Function: requestOnPrefinish]
      timeout: [Function (anonymous)],
      error: [Function (anonymous)],
      aborted: [Function (anonymous)],
      abort: [Function (anonymous)],
      socket: [Function (anonymous)],
    _events: [Object: null prototype] {
  request: <ref *1> ClientRequest {
  },
    validateStatus: [Function: validateStatus]
    maxContentLength: -1,
    xsrfHeaderName: 'X-XSRF-TOKEN',
    xsrfCookieName: 'XSRF-TOKEN',
    adapter: [Function: httpAdapter],
    timeout: 60000,
    transformResponse: [ [Function: transformResponse] ],
    transformRequest: [ [Function: transformRequest] ],
    },
      'Content-Length': 156
      'User-Agent': 'axios/0.19.0',
      'X-Auth-Token': 'xxxxxxxxxxxxxxxx',
      'X-User-Id': 'xxxxxxxxxxxxxxxx',
      'Content-Type': 'application/json',
      Accept: 'application/json, text/plain, */*',
    headers: {
    data: '{"email":"BC57F009-EC2C-4153-BAD9-991AFA67ACFA@localhost","password":"xxxxxxxxxxxxxxxxxxx","username":"BC57F009-EC2C-4153-BAD9-991AFA67ACFA","name":"Emma Pan (GLG)"}',
    method: 'post',
    url: 'https://xxxxxxxxxxxxxxxx/api/v1/users.create',
  config: {
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    at endReadableNT (_stream_readable.js:1198:12)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.handleStreamEnd (/home/ubuntu/app/node_modules/axios/lib/adapters/http.js:237:11)
    at settle (/home/ubuntu/app/node_modules/axios/lib/core/settle.js:17:12)
    at createError (/home/ubuntu/app/node_modules/axios/lib/core/createError.js:16:15)
Error: Request failed with status code 400

    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runMicrotasks (<anonymous>)
    at rejected (/home/ubuntu/app/dist/lib/rocketchat.js:6:65)
    at Generator.throw (<anonymous>)
    at Function.<anonymous> (/home/ubuntu/app/dist/lib/rocketchat.js:214:27)

```

**Comment by tulecbi** [comment]
I still encounter this issue

**Comment by Am0rphous** [comment]
Same
