### ISSUE TITLE
Cannot run Dev version of Rocket.chat grain

### ISSUE THREAD

**Issue by dmitry-sher** [RocketChat/Rocket.Chat#7478]
Rocket.Chat Version: 0.55, 0.56, 0.57
Running Instances: 0
DB Replicaset OpLog: no
Node Version: not sure
OS: Mac OS X 

What we want: we have a version of Rocket.Chat with some added packages, developed in-house (Smooch.io integration, and such). To debug it for sandstorm, we need to run packaging script. When i try to start `vagrant-spk dev`, it's failing multiple times, each time with different message, mostly complaining about some missing files. First it fails on phantom.js, then on other ones... logs are further down here.

Steps to reproduce:

```bash
git clone git@github.com:RocketChat/Rocket.Chat.git src
cd src
vagrant-spk vm up
vagrant-spk dev
vagrant-spk dev
vagrant-spk dev
vagrant-spk dev
vagrant-spk dev
vagrant-spk dev
```

Here are some relevant fail messages:

```While loading emojione:emojione@2.2.6...:
error: Command failed:
/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.asbjad++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm rebuild
--update-binary
Phantom installation failed { [Error: EACCES: permission denied, open
'/tmp/mt-8xcr3f/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js']
errno: -13,
code: 'EACCES',
syscall: 'open',
path: '/tmp/mt-8xcr3f/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js' } Error:
EACCES: permission denied, open
'/tmp/mt-8xcr3f/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
at Error (native)
at Object.fs.openSync (fs.js:549:18)
at Object.fs.writeFileSync (fs.js:1156:15)
at writeLocationFile
(/tmp/mt-8xcr3f/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:108:6)
at Promise._successFn
(/tmp/mt-8xcr3f/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:80:5)
at nextTickCallback
(/tmp/mt-8xcr3f/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
at nextTickCallbackWith0Args (node.js:489:9)
at process._tickCallback (node.js:418:13)
```

```While building package rocketchat:theme:
error: couldn't install npm packages from npm-shrinkwrap: Command failed:
/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.asbjad++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm install
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv
"/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.asbjad++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.asbjad++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"install"
npm ERR! node v4.8.0
npm ERR! npm  v4.3.0
npm ERR! path /opt/app/packages/rocketchat-theme/.npm/package-new-rsfm87/node_modules/sshpk/bin/sshpk-sign
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod
'/opt/app/packages/rocketchat-theme/.npm/package-new-rsfm87/node_modules/sshpk/bin/sshpk-sign'
npm ERR! enoent ENOENT: no such file or directory, chmod
'/opt/app/packages/rocketchat-theme/.npm/package-new-rsfm87/node_modules/sshpk/bin/sshpk-sign'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!
/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.asbjad++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-07-12T14_43_23_990Z-debug.log
```

and so on and so on...

With version 0.57.1 it finally stucks with some postcss-imports.
With version 0.55.1 it finally stucks with google-natural-language.

```While building package rocketchat:google-natural-language:
error: couldn't install npm package @google-cloud/language@0.8.0: Command failed:
/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.asbjad++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm install
@google-cloud/language@0.8.0
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv
"/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.asbjad++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.asbjad++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"install" "@google-cloud/language@0.8.0"
npm ERR! node v4.8.0
npm ERR! npm  v4.3.0
npm ERR! path
/opt/app/packages/rocketchat-google-natural-language/.npm/package-new-x3mav/node_modules/grpc/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod
'/opt/app/packages/rocketchat-google-natural-language/.npm/package-new-x3mav/node_modules/grpc/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js'
npm ERR! enoent ENOENT: no such file or directory, chmod
'/opt/app/packages/rocketchat-google-natural-language/.npm/package-new-x3mav/node_modules/grpc/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!
/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.asbjad++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-07-12T16_02_52_892Z-debug.log
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv
"/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.asbjad++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.asbjad++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"install" "@google-cloud/language@0.8.0"
npm ERR! node v4.8.0
npm ERR! npm  v4.3.0
npm ERR! path
/opt/app/packages/rocketchat-google-natural-language/.npm/package-new-x3mav/node_modules/grpc/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod
'/opt/app/packages/rocketchat-google-natural-language/.npm/package-new-x3mav/node_modules/grpc/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js'
npm ERR! enoent ENOENT: no such file or directory, chmod
'/opt/app/packages/rocketchat-google-natural-language/.npm/package-new-x3mav/node_modules/grpc/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!
/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.asbjad++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-07-12T16_02_52_892Z-debug.log```

**Comment by geekgonecrazy** [comment]
From what I can tell looks like we need to make some adjustments.  Last one I see built is 0.53.0

I'll take a look at this.

**Comment by dmitry-sher** [comment]
The issue is actually because of meteor version. `Vagrant-spk` doesn't supports meteor 1.4. We are going to investigate the issue next week and already had some progress last week -- at least `meteor-spk` creates the dev bundle successfully for other meteor 1.4 projects. I'll gladly share my results with you.

**Comment by geekgonecrazy** [comment]
@dmitry-sher absolutely please let me know.  We'd love to get builds generated again on new releases. :+1:

**Comment by geekgonecrazy** [comment]
Sandstorm isn't supported any more. Closing.
