### ISSUE TITLE
Small files upload problem multi-instances v. 0.57.1

### ISSUE THREAD

**Issue by krprzenioslo** [RocketChat/Rocket.Chat#7485]
Rocket.Chat Version: 0.57.1
Running Instances: 2
DB Replicaset OpLog: Enabled
Node Version: 4.5.0
GlusterFS: YES

I have a problem with file upload. When I upload small file in chat i have an error _500_ on bar at top of the window.

Error in log:

`Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: { [Error: ENOENT: no such file or directory, open '/tmp/ufs/fY7FCMZZYEgmKrkNw']
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: errno: -2,
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: code: 'ENOENT',
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: syscall: 'open',
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: path: '/tmp/ufs/fY7FCMZZYEgmKrkNw' }
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: [Error: FileNotFound: no file with id  fY7FCMZZYEgmKrkNw found]
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: Exception while invoking method 'ufsComplete' Error: ENOENT: no such file or directory, open '/tmp/ufs/fY7FCMZZYEgmKrkNw'
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at Object.Future.wait (/home/rocket.chat/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at [object Object].Meteor.methods.ufsComplete (/home/rocket.chat/Rocket.Chat/programs/server/packages/jalik_ufs.js:818:24)
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at [object Object].methodsMap.(anonymous function) (/home/rocket.chat/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1028:26)
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at maybeAuditArgumentChecks (/home/rocket.chat/Rocket.Chat/programs/server/packages/ddp-server.js:1823:12)
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at /home/rocket.chat/Rocket.Chat/programs/server/packages/ddp-server.js:905:20
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at /home/rocket.chat/Rocket.Chat/programs/server/packages/ddp-server.js:904:41
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at /home/rocket.chat/Rocket.Chat/programs/server/packages/ddp-server.js:903:46
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at [object Object]._.extend.protocol_handlers.method (/home/rocket.chat/Rocket.Chat/programs/server/packages/ddp-server.js:876:21)
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at /home/rocket.chat/Rocket.Chat/programs/server/packages/ddp-server.js:755:85
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: - - - - -
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: at Error (native)
Jul 13 14:36:02 rocket-prod-app02 rocketchat-0: rocketchat_logger rocketchat_logger.js:377 #033[34mMeteor ➔ method#033[39m ufsDelete -> userId: NXKRZCXfSg8St2SLS , arguments:  { '0': 'fY7FCMZZYEgmKrkNw', '1': 'Uploads', '2': '083b79D9B9'}`

It's look like second instance try to read file that first instance didn't finish uploading yet. With larger files (more than 1MB) is everything OK. Also when I'm running one instance of Rocket.Chat file upload work properly.
I have an idea to add a Delay  (_setTimeout()_) in function that is responsible for uploading, but i don't know which one it is.

**Comment by geekgonecrazy** [comment]
Can you go into more details on your setup?  Especially how you're running Rocket.Chat and how you have glusterfs setup.  That'll help us determine if there is a bug or if this is something in configuration

**Comment by krprzenioslo** [comment]
Thank you for the replay.
Of course, here is more details about the configuration.

Rocket.Chat file upload settings:
![upload_settings](https://user-images.githubusercontent.com/11661461/28257052-24c4a028-6ac8-11e7-8da3-05e5f4fd3fc6.PNG)

Service file in systemd:
![service settings](https://user-images.githubusercontent.com/11661461/28257067-4233c242-6ac8-11e7-9525-8f5234158954.PNG)

Permissions to directory, which is using by glusterFS:
![uprawnienia](https://user-images.githubusercontent.com/11661461/28257106-7b9a4d8a-6ac8-11e7-874a-fe1251bebf93.PNG)
![uprawnienia1](https://user-images.githubusercontent.com/11661461/28257111-7e7b06fc-6ac8-11e7-8e92-17b4ab9cf523.PNG)

GlusterFS info & status:

![info gluster](https://user-images.githubusercontent.com/11661461/28257116-8a5a1e22-6ac8-11e7-9251-5bf6ae3d3fb6.PNG)

![gluster status](https://user-images.githubusercontent.com/11661461/28257119-8d1f51d6-6ac8-11e7-8517-4d9c3be93d7a.PNG)

In glusterFS i have 4 bricks becouse the target is running 4 instances of Rocket.Chat.
Any more information you need?

**Comment by geekgonecrazy** [comment]
So in your settings there it shows that you are using gridfs.

Is the goal here to store files on glusterfs or to store in gridfs?

**Comment by krprzenioslo** [comment]
Without GlusterFS, images uploaded in 50% and I have half of image or less when i click on it in chat. With GlusterFS problem disappeared in 0.56 server.
I don't know what would be better configuration? 
I have tested the files upload with stopped Glusterfs and active gridfs in Rocket.Chat just few minutes ago. 
Problem is the same "Error 500" - my first post.
