### ISSUE TITLE
HuBot cannot reply to the same room after receiving message.

### ISSUE THREAD

**Issue by mhou1981** [RocketChat/Rocket.Chat#7514]
Rocket.Chat Version:  0.57.2
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.2

HuBot cannot reply to the same room after receiving message.  Error as follows:
```
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO Message received with ID id
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO Message receive callback id RsAqfEDLkJJraKuyc ts Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO [Incoming] mhou: rocketchat help
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO Looking up Room Name for: 54cWy9hBgv2i98Zb7yK7LxPZfeFKv8XZpm
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO Message sent to hubot brain.
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO Sending Message To Room: undefined
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO Looking up Room ID for: undefined
```

Rocket Chat error message:
```
Jul 17 15:06:50 Ubuntu snap[2292]: Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: 54cWy9hBgv2i98Zb7yK7LxPZfeFKv8XZpm
Jul 17 15:06:50 Ubuntu snap[2292]: Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event.
Jul 17 15:06:50 Ubuntu snap[2292]: Meteor ➔ method getRoomIdByNameOrId -> userId: yK7LxPZfeFKv8XZpm , arguments:  { '0': null }
Jul 17 15:06:50 Ubuntu snap[2292]: Exception while invoking method 'getRoomIdByNameOrId' Error: Match error: Expected string, got null
Jul 17 15:06:50 Ubuntu snap[2292]:   at exports.check (packages/check.js:57:15)
Jul 17 15:06:50 Ubuntu snap[2292]:   at [object Object].Meteor.methods.getRoomIdByNameOrId (/snap/rocketchat-server/829/programs/server/app/app.js:6821:3)
Jul 17 15:06:50 Ubuntu snap[2292]:   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
Jul 17 15:06:50 Ubuntu snap[2292]:   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/829/programs/server/packages/rocketchat_lib.js:1028:26)
Jul 17 15:06:50 Ubuntu snap[2292]:   at maybeAuditArgumentChecks (/snap/rocketchat-server/829/programs/server/packages/ddp-server.js:1823:12)
Jul 17 15:06:50 Ubuntu snap[2292]:   at /snap/rocketchat-server/829/programs/server/packages/ddp-server.js:905:20
Jul 17 15:06:50 Ubuntu snap[2292]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jul 17 15:06:50 Ubuntu snap[2292]:   at /snap/rocketchat-server/829/programs/server/packages/ddp-server.js:904:41
Jul 17 15:06:50 Ubuntu snap[2292]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jul 17 15:06:50 Ubuntu snap[2292]:   at /snap/rocketchat-server/829/programs/server/packages/ddp-server.js:903:46
Jul 17 15:06:50 Ubuntu snap[2292]:   at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/829/programs/server/packages/ddp-server.js:876:21)
Jul 17 15:06:50 Ubuntu snap[2292]:   at /snap/rocketchat-server/829/programs/server/packages/ddp-server.js:755:85
Jul 17 15:06:50 Ubuntu snap[2292]: Sanitized and reported to the client as: Match failed [400]
Jul 17 15:06:50 Ubuntu snap[2292]: undefined undefined
```

Can any one help with this error?  I am not sure where it is wrong.

**Comment by antgel** [comment]
I see this too. Using RC 0.57.2, hubot-rocketchat `master`, currently at `a7bb24b1c22f9830ff996e7d520d577ebb62cdb6`.

**Comment by mhou1981** [comment]
The script is working in version 1.0.8 and failed in 1.0.9.

**Comment by mhou1981** [comment]
I have moved this issue to the hubot-rocketchat repository
