### ISSUE TITLE
meteor build fails with %% Failed to install 'cordova-plugin-googleplus':Error: Variable(s) missing: REVERSED_CLIENT_ID

### ISSUE THREAD

**Issue by kepkap** [RocketChat/Rocket.Chat#7609]
Hi, guys,

I am getting error while building RocketChat from master branch. (tried other branches too, same result)

Please assist, as this is already 2-days blocker for us. We are evaluating RocketChat for customization, and cannot build customized bundle.

Thank you.

```
$ meteor build --server http://localhost:3000 --directory .build
                                              
WARNING: The output directory is under your source tree.
         Your generated files may get interpreted as source code!
         Consider building into a different directory instead
         meteor build ../output
                                              
WARN: Output exceeds 32000 characters        |
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters        -
Node#before is deprecated. Use Node#raws.before
WARN: Output exceeds 32000 characters        /
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters        -
WARNING: Attempting to install plugin cordova-plugin-device@1.1.1, but it should have a minimum version of 1.1.4 to ensure compatibility with the current platform versions.
         Installing the minimum version for convenience, but you should adjust your dependencies.
%% apple-ios version check failed ("/Users/USER/crossover/fuelmedevelopers/slackclone/rocketchat/.meteor/local/cordova-build/platforms/ios/cordova/apple_ios_version"), continuing anyways.
%% apple-ios version check failed ("/Users/USER/crossover/fuelmedevelopers/slackclone/rocketchat/.meteor/local/cordova-build/platforms/ios/cordova/apple_ios_version"), continuing anyways.
%% apple-xcode version check failed ("/Users/USER/crossover/fuelmedevelopers/slackclone/rocketchat/.meteor/local/cordova-build/platforms/ios/cordova/apple_xcode_version"), continuing anyways.
%% support for subdirectories is deprecated and will be removed in Cordova@7       
%% Failed to install 'cordova-plugin-googleplus':Error: Variable(s) missing: REVERSED_CLIENT_ID
    at /Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:362:23
    at _fulfilled (/Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
    at /Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:557:44
    at flush (/Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
=> Errors executing Cordova commands:                                              
                                                                                   
   While adding plugin https://github.com/meteor/cordova-plugin-googleplus.git#3095abe327e710ab04059ae9d3521bd4037c5a37 to Cordova project:
   Error: Variable(s) missing: REVERSED_CLIENT_ID                                  
   at
   /Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:362:23
   at _fulfilled
   (/Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at /Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:557:44
   at flush
   (/Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at nextTickCallbackWith0Args (node.js:489:9)
   at process._tickCallback (node.js:418:13)
   => awaited here:
   at Function.Promise.await
   (/Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:715:22)
   at CordovaProject.addPlugin (/tools/cordova/project.js:509:12)
   at /tools/cordova/project.js:638:16
   at Function._.each._.forEach
   (/Users/USER/.meteor/packages/meteor-tool/.1.4.4_2.176acq4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
   at /tools/cordova/project.js:637:11
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at CordovaProject.ensurePluginsAreSynchronized (/tools/cordova/project.js:535:18)
   at CordovaProject.prepareFromAppBundle (/tools/cordova/project.js:199:10)
   at /tools/cli/commands.js:1000:24
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/cli/commands.js:991:20
   at /tools/utils/buildmessage.js:271:13
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:264:29
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:262:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:253:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.capture (/tools/utils/buildmessage.js:252:19)
   at Object.main.captureAndExit (/tools/cli/main.js:273:29)
   at buildCommand (/tools/cli/commands.js:990:10)
   at Command.func (/tools/cli/commands.js:824:12)
   at /tools/cli/main.js:1483:23
 ```

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by kepkap** [comment]
@MartinSchoeler, 
Martin,I disagree with your rationale to close this issue. How is that not a bug, if I cannot build the application following official instructions, i.e. (example-build.sh)

Please, take a look at stack-trace and the command invoked, the build fails on cordova stuff.
I was able to build this with option --server-only, if that's the must_have_option - I agree to close this as not a bug.

BTW, cannot see how to re-open, should I submit a new issue then?

**Comment by vivekmunde** [comment]
TRY THIS 

Create `mobile-config.js` at the root level of project with following configuration 

```
App.configurePlugin("cordova-plugin-googleplus", {
    "REVERSED_CLIENT_ID": "CLIENT_ID_FOR_cordova-plugin-googleplus"
});
App.configurePlugin('phonegap-plugin-push', {
  SENDER_ID: "SENDER_ID_FOR_phonegap-plugin-push"
});
```

Note: You might get error for installation of `phonegap-plugin-push` as well. Thats where the second config comes in picture.
