### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir 'packages/rocketchat-katex/node_modules/katex/dist/fonts/  in rocketchat:katex package

### ISSUE THREAD

**Issue by madguy02** [RocketChat/Rocket.Chat#8031]
`Error: ENOENT: no such file or directory, scandir 'packages/rocketchat-katex/node_modules/katex/dist/fonts/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at package.js:26:29
    at __bottom_mark__ (/tools/utils/parse-stack.js:64:14)
    at [object Object].initFromPackageDir (/tools/isobuild/package-source.js:620:9)
    at /tools/packaging/catalog/catalog-local.js:354:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at initSourceFromDir (/tools/packaging/catalog/catalog-local.js:341:20)
    at /tools/packaging/catalog/catalog-local.js:409:9
    at Array.forEach (native)
    at Function._.each._.forEach (/home/madguy02/.meteor/packages/meteor-tool/.1.5.1.gpk9yj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/packaging/catalog/catalog-local.js:408:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at [object Object]._.extend._loadLocalPackages (/tools/packaging/catalog/catalog-local.js:407:18)
    at [object Object]._.extend.initialize (/tools/packaging/catalog/catalog-local.js:119:10)
    at /tools/project-context.js:679:29
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/project-context.js:671:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._initializeCatalog (/tools/project-context.js:670:13)
    at /tools/project-context.js:285:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:275:18)
    at /tools/project-context.js:240:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext._.extend.initializeCatalog (/tools/project-context.js:239:13)
    at /tools/cli/commands-packages.js:1929:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:273:29)
    at Command.func (/tools/cli/commands-packages.js:1926:8)
    at /tools/cli/main.js:1483:23
=> Errors while initializing project:         
                                              
While reading package from `/home/madguy02/Desktop/Rocket.Chat/packages/rocketchat-katex`:
native: ENOENT: no such file or directory, scandir 'packages/rocketchat-katex/node_modules/katex/dist/fonts/'

**Comment by MartinSchoeler** [comment]
@madguy02 could you give us more info? like what were you trying to do and what is the server version ?

**Comment by madguy02** [comment]
@MartinSchoeler resolved!! had issues with my set up thanks a lot, i am using 0.59.0 develop version, no issues ..resolved

**Comment by jiqianzheng** [comment]
@madguy02 I have the same question ,can you tell me more about it

**Comment by madguy02** [comment]
@jiqianzheng check your directory from where are you trying to launch meteor npm start

**Comment by chellem** [comment]
try:
`npm run postinstall`

**Comment by piotrkochan** [comment]
does not work for me on windows 10

**Comment by madguy02** [comment]
@piotrkochan did you try an npm run postinstall

**Comment by piotrkochan** [comment]
Yes
W dniu wt., 4.09.2018 o 01:00 manish kakoti <notifications@github.com>
napisał(a):

**Comment by fuminori-ido** [comment]
https://rocket.chat/docs/developer-guides/quick-start/ following part looks incorrect:

> npm postinstall

It should be as follows, right?

> npm run postinstall
