### ISSUE TITLE
Can't delete user from RC

### ISSUE THREAD

**Issue by user7832** [RocketChat/Rocket.Chat#8126]
### Description:

Faced with the next issue - can't remove user from RC.
There is LDAP authorization in RC and all users are synced from LDAP. I can delete all users, but one.
When I tried to delete user I see Exception in log (see below)

Other side of this issue (connected to this user) - I can't assign any roles to it - "Add Role" drop down box doesn't contain any roles (for other users does)

### Server Setup Information:

    Version of Rocket.Chat Server: 0.58.1
    Operating System: CentOS Linux release 7.3.1611 (Core)
    Deployment Method(snap/docker/tar/etc): tar
    Number of Running Instances: 4
    DB Replicaset Oplog: yes
    Node Version: v4.5.0

### Relevant logs:
Exception while invoking method 'deleteUser' TypeError: Cannot read property 'indexOf' of undefined
  at [object Object].Meteor.methods.deleteUser (/opt/Rocket.Chat/programs/server/app/app.js:6682:31)
  at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
  at [object Object].methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1110:26)
  at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1858:12)
  at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:904:20
  at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
  at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:903:47
  at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
  at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:46
  at [object Object]._.extend.protocol_handlers.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:875:21)
  at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:754:85

**Comment by eevrenci** [comment]
Version of Rocket.Chat Server: 0.74.2
Operating System: Debian Linux release 9.8
Deployment Method(snap/docker/tar/etc): tar
Number of Running Instances: 4
DB Replicaset Oplog: yes
Node Version: v8.11.3

Same problem. Sync with ldap server returns all users, but one of them with no roles. After that I can not assign this user to any role because add roles selection box seems empty for this user. And also I want to delete and resync with ldap server but this user can not be deleted. It gives the below error message for delete action.

[34mI20190322-16:12:33.204(3) Exception while invoking method 'deleteUser' TypeError: Cannot read property 'indexOf' of undefined     at MethodInvocation.deleteUser (server/methods/deleteUser.js:29:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at MethodInvocation.methodsMap.(anonymous function) (packages/rocketchat:lib/server/lib/debug.js:71:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

**Comment by b-altmann** [comment]
Apparently it's impossible to delete users who don't have any roles. I assume it is trying to delete the roles of the user and it can't, since it doesn't have any, therefore the exception. I suggest trying to get the users roles /info via the Rest API and see if they have any roles assigned. In the case of the `users.info` endpoint, if there is no `roles` field, then the user doesn't have any roles.

You might even be able to assign roles to the user via the Rest API and delete them afterwards. At least this worked for me.
