### ISSUE TITLE
EXCEPTION Cannot read property 't' of undefined

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat#8214]
### Description:

We get more or less 5 times a day exception `Cannot read property 't' of undefined`. I attach text of Exception below.

```
Exception from sub stream-notify-room id QhwNvWvAnQ44ZomcF

TypeError: Cannot read property 't' of undefined
  at [object Object].<anonymous> (/app/bundle/programs/server/packages/rocketchat_lib.js:4137:12)
  at Streamer.isReadAllowed (/app/bundle/programs/server/packages/rocketchat_streamer.js:342:38)
  at [object Object].<anonymous> (/app/bundle/programs/server/packages/rocketchat_streamer.js:477:16)
  at [object Object].<anonymous> (/app/bundle/programs/server/packages/rocketchat_lib.js:1129:15)
  at packages/matb33_collection-hooks.js:307:21
  at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
  at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
  at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1858:12)
  at /app/bundle/programs/server/packages/ddp-server.js:1181:16
  at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
  at [object Object]._.extend._runHandler (/app/bundle/programs/server/packages/ddp-server.js:1180:51)
  at [object Object]._.extend._startSubscription (/app/bundle/programs/server/packages/ddp-server.js:1028:9)
  at [object Object]._.extend.protocol_handlers.sub (/app/bundle/programs/server/packages/ddp-server.js:816:12)
  at /app/bundle/programs/server/packages/ddp-server.js:754:85
```

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2
* Operating System: Centos 7
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 500

**Comment by engelgabriel** [comment]
I believe this have been fixed on version 0.59.0

@rodrigok can you please confirm?
