### ISSUE TITLE
MongoError: Mod on _id not allowed

### ISSUE THREAD

**Issue by Surfoo** [RocketChat/Rocket.Chat#835]
Hello,

I tried to install Rocket.Chat (from master) on my own server (Debian Wheezy with Apache, no nginx, no ssl), and on the startup, I have a 503 error.

In the err-0.log I have:

    MongoError: Mod on _id not allowed
        at Object.Future.wait (/var/www/rocket.chat/bundle/programs/server/node_modules/fibers/future.js:398:15)
        at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
        at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:678:1)
        at OptimizedApply (packages/meteorhacks:kadira/lib/utils.js:35:1)
        at Object.ret.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/db.js:20:1)
        at Object.fields (packages/matb33:collection-hooks/update.js:80:1)
        at Object.collection.(anonymous function) [as update] (packages/matb33:collection-hooks/collection-hooks.js:103:1)
        at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:575:1)
        at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch:run-as-user/lib/collection.overwrites.js:51:1)
        at [object Object].Mongo.Collection.upsert (packages/mongo/collection.js:609:1)
        - - - - - 
        at Object.toError (/var/www/rocket.chat/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
        at /var/www/rocket.chat/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/collection/core.js:636:22
        at Server.Base._callHandler (/var/www/rocket.chat/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
        at /var/www/rocket.chat/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
        at [object Object].MongoReply.parseBody (/var/www/rocket.chat/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
        at [object Object].<anonymous> (/var/www/rocket.chat/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
        at [object Object].emit (events.js:95:17)
        at [object Object].<anonymous> (/var/www/rocket.chat/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
        at [object Object].emit (events.js:98:17)
        at Socket.<anonymous> (/var/www/rocket.chat/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)

What can I do to fix the issue?

**Comment by geekgonecrazy** [comment]
What version of mongo are you running?  Meteor requires 2.6 or greater.  We've been trying to stay compatible with the 2.4 but its on ongoing battle.

**Comment by Surfoo** [comment]
With wheezy-backports, it's 2.4.8

**Comment by geekgonecrazy** [comment]
Give 2.6 or 3.0 a shot.  Check mongodb's website. I think the have Debian repos for more up to date versions

**Comment by Surfoo** [comment]
Thanks it works with the 3.0.6 version! I registered the first account, but I can't find the Administration.. Where it is?

**Comment by geekgonecrazy** [comment]
@surfoo did you create the user before upgrading?  Its possible it didn't successfully make it admin.

**Comment by Surfoo** [comment]
Hum, no after the upgrade, because with mongo 2.4 I had a 503 error. How can I fix that?

**Comment by rwakida** [comment]
Hi @Surfoo there was a bug with assigning 'admin' role to the first created user.  I submitted a fix, but until that gets merged to master, you can simply restart meteor.  At startup, RocketChat will assign the oldest user the 'admin' role IF no admin already exists.

**Comment by Surfoo** [comment]
OK, thanks. How can I restart meteor?

**Comment by rwakida** [comment]
Or you can manually update the user in mongo.  The user should have the following role:
```
"roles" : {
		"__global_roles__" : [
			"admin"
		]
	},
```

**Comment by Surfoo** [comment]
I'm totally newbie with mongodb, I think restart meteor is easier than update the db :)

**Comment by geekgonecrazy** [comment]
@Surfoo how did you start meteor?  If you just cloned and then typed meteor.  Then a ctrl+c will work.  If you used pm2 you will have to do a pm2 restart like you did during setup.

**Comment by rwakida** [comment]
@Surfoo, I've been using mongodb for a while and I still feel like a newb.  :smile: .  

If @geekgonecrazy's advice doesn't work for you, join the rocket chat demo and talk to the devs for realtime feedback.  

https://demo.rocket.chat

**Comment by Surfoo** [comment]
ok, I restarted the app with pm2, it works, and I have my admin account :-)

**Comment by Q-efx** [comment]
Upgrading to newset MongoDB Version fixed the isee

**Comment by geekgonecrazy** [comment]
👍

**Comment by mikevanwinkle** [comment]
:+1: updating mongodb worked for me

**Comment by r00t4bl3** [comment]
:+1: I use mongodb version 2.4 and after node main.js it shows this error. After upgrading to 2.6 and it runs perfectly. I think the manual should be updated so it says minimal mongodb version is 2.6.
