### ISSUE TITLE
[BUG] Exceptions show private messages content - Exception while invoking method 'sendMessage' DUPLICATE KEY

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat#8351]
### Description:

```Exception while invoking method 'sendMessage'``` - we get this exception mostly everyday with a message with a duplicate key. The biggest problem is the fact that the exception displays the `message content`. I add the logs below. 

* Version of Rocket.Chat Server: 0.58.2
* Operating System: Centos7
* Deployment Method: docker
* Number of Running Instances:  500

LOGS:
```
{
  "code": 11000,
  "index": 0,
  "errmsg": "E11000 duplicate key error collection: rocketchat.rocketchat_message index:_id_ dup key: { : \"BL5jxD79PjeL3t62f\" }",
  "op": {
    "_id": "some__id",
    "rid": "some_id",
    "msg": "HERE GOES A MESSAGE CONTENT!!!",
    "ts": "2017-09-29T08:40:17.215Z",
    "u": {
      "_id": "some__id",
      "username": "USERNAME!!!",
      "name": "REAL_NAME!!!"
    },
    "mentions": [],
    "channels": [],
    "_updatedAt": "2017-09-29T08:40:17.223Z"
  }
}
```
```
  at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
  at [object Object].<anonymous> (packages/meteor.js:213:24)
  at [object Object].MongoConnection.(anonymous function) [as insert] (/app/bundle/programs/server/packages/mongo.js:835:49)
  at Object.<anonymous> (packages/matb33_collection-hooks.js:395:18)
  at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
  at [object Object].insert (/app/bundle/programs/server/packages/mongo.js:3850:38)
  at ModelsBaseDb.insert (/app/bundle/programs/server/packages/rocketchat_lib.js:10864:54)
  at _class.insert (/app/bundle/programs/server/packages/rocketchat_lib.js:4466:36)
  at Object.RocketChat.sendMessage (/app/bundle/programs/server/packages/rocketchat_lib.js:3321:44)
  at [object Object].Meteor.methods.sendMessage (/app/bundle/programs/server/packages/rocketchat_lib.js:14473:21)
  at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1110:26)
  at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
  at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1858:12)
  at /app/bundle/programs/server/packages/ddp-server.js:904:20
  at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
  at /app/bundle/programs/server/packages/ddp-server.js:903:47
  at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
  at /app/bundle/programs/server/packages/ddp-server.js:902:46
  at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:875:21)
  at /app/bundle/programs/server/packages/ddp-server.js:754:85

    - - - - -
  at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
  at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:658:23
  at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:95:56)
  at resultHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/ordered.js:421:14)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18
  at nextTickCallbackWith0Args (node.js:489:9)
  at process._tickDomainCallback (node.js:459:13)
```

**Comment by monspid** [comment]
Bump. I made the snippets clearly formatted. Maybe it will help you to see that the problem is huge. 
Even admins should not be able to see private messages.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Can please try to reproduce this on latest stable and check, whether it might be related to #6535? I think there are already several issues talking about `E11000 duplicate key error index` so a search for error might also bring up some other things to try for you. I'll happily reopen if you find this to be different (and if so, in what way) than all the other E11000 errors :)

Cheers
Thomas
