### ISSUE TITLE
Cannot find module "fibers/future" for the 0.59.0-rc.10 version

### ISSUE THREAD

**Issue by unixfox** [RocketChat/Rocket.Chat#8365]
### Description:

The last release candidate version can't find the npm module `fibers/future`.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.10
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: I don't know
* Node Version: v4.8.3

### Steps to Reproduce:

1. Use the last release candidate version on snap.

### Expected behavior:

Working fine.

### Actual behavior:

Crashing at the start.

### Relevant logs:
```
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]: MongoDB shell version: 3.2.7
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]: connecting to: test
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]: /snap/rocketchat-server/1102/programs/server/boot.js:392
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]: }).run();
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]:    ^
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]: Error: Cannot find module "fibers/future"
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]:     at Object.require (/snap/rocketchat-server/1102/programs/server/boot.js:232:24)
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]:     at packages/meteor.js:93:20
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]:     at packages/meteor.js:263:4
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]:     at packages/meteor.js:1392:3
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]:     at /snap/rocketchat-server/1102/programs/server/boot.js:339:34
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]:     at Function._.each._.forEach (/snap/rocketchat-server/1102/node_modules/underscore/underscore.js:153:9)
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]:     at /snap/rocketchat-server/1102/programs/server/boot.js:158:5
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]:     at /snap/rocketchat-server/1102/programs/server/boot.js:388:5
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]:     at Function.run (/snap/rocketchat-server/1102/programs/server/profile.js:510:12)
Sep 30 12:44:29 vps.aresrpg.fr rocketchat-server.rocketchat-server[18096]:     at /snap/rocketchat-server/1102/programs/server/boot.js:387:11
Sep 30 12:44:29 vps.aresrpg.fr systemd[1]: snap.rocketchat-server.rocketchat-server.service: Main process exited, code=exited, status=1/FAILURE
Sep 30 12:44:29 vps.aresrpg.fr systemd[1]: snap.rocketchat-server.rocketchat-server.service: Unit entered failed state.
```

**Comment by johnyb0y** [comment]
Did you cd to /bundle/programs/server and "sudo npm isntall" ?

**Comment by unixfox** [comment]
I already tried but I can't the snap mount is in ready only.

**Comment by geekgonecrazy** [comment]
@unixfox yes snaps are read only.  I'll take a look so we can get this fixed before we release the final version of 0.59.0

**Comment by JohnnyKing94** [comment]
Maybe it's better to downgrade to a previous stable version with snap... i hope it won't take too long...

**Comment by geekgonecrazy** [comment]
As always its recommended not to try an unreleased version on a production system. 

I'm working on identifying the cause and fixing it now.

**Comment by geekgonecrazy** [comment]
@unixfox @JohnnyKing94 please do: `sudo snap refresh rocketchat-server` it should now work.

**Comment by JohnnyKing94** [comment]
@geekgonecrazy 

This is the new error log i get for rocketchat-server
```
ott 03 21:06:03 server systemd[1]: Started Service for snap application rocketchat-server.rocketchat-server.
ott 03 21:06:03 server rocketchat-server.rocketchat-server[19456]: Checking if oplog has been enabled, and enabling if not
ott 03 21:06:03 server rocketchat-server.rocketchat-server[19456]: MongoDB shell version: 3.2.7
ott 03 21:06:03 server rocketchat-server.rocketchat-server[19456]: connecting to: test
ott 03 21:06:05 server rocketchat-server.rocketchat-server[19456]: Will load cache for users
ott 03 21:06:05 server rocketchat-server.rocketchat-server[19456]: 27 records load from users
ott 03 21:06:05 server rocketchat-server.rocketchat-server[19456]: Will load cache for rocketchat_room
ott 03 21:06:05 server rocketchat-server.rocketchat-server[19456]: 9 records load from rocketchat_room
ott 03 21:06:05 server rocketchat-server.rocketchat-server[19456]: Will load cache for rocketchat_subscription
ott 03 21:06:05 server rocketchat-server.rocketchat-server[19456]: 97 records load from rocketchat_subscription
ott 03 21:06:05 server rocketchat-server.rocketchat-server[19456]: Will load cache for rocketchat_settings
ott 03 21:06:05 server rocketchat-server.rocketchat-server[19456]: 561 records load from rocketchat_settings
ott 03 21:06:08 server rocketchat-server.rocketchat-server[19456]: Updating process.env.MAIL_URL
ott 03 21:06:08 server rocketchat-server.rocketchat-server[19456]: Will load cache for rocketchat_permissions
ott 03 21:06:08 server rocketchat-server.rocketchat-server[19456]: 74 records load from rocketchat_permissions
ott 03 21:06:08 server rocketchat-server.rocketchat-server[19456]: Will load cache for rocketchat_roles
ott 03 21:06:08 server rocketchat-server.rocketchat-server[19456]: 12 records load from rocketchat_roles
ott 03 21:06:10 server rocketchat-server.rocketchat-server[19456]: Setting default file store to GridFS
ott 03 21:06:10 server rocketchat-server.rocketchat-server[19456]: LocalStore: store created at
ott 03 21:06:10 server rocketchat-server.rocketchat-server[19456]: LocalStore: store created at
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]: Exception in callback of async function: Error: [Can't find migration version 100]
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at Object.Migrations._findIndexByVersion (/snap/rocketchat-server/1122/programs/server/packages/rocketchat_migrations.js:403:8)
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at Object.Migrations._migrateTo (/snap/rocketchat-server/1122/programs/server/packages/rocketchat_migrations.js:270:22)
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at Object.Migrations.migrateTo (/snap/rocketchat-server/1122/programs/server/packages/rocketchat_migrations.js:199:20)
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at meteorInstall.server.startup.migrations.xrun.js (/snap/rocketchat-server/1122/programs/server/app/app.js:5229:24)
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at fileEvaluate (packages/modules-runtime.js:333:9)
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at require (packages/modules-runtime.js:228:16)
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at /snap/rocketchat-server/1122/programs/server/app/app.js:10258:1
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at /snap/rocketchat-server/1122/programs/server/boot.js:338:34
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at Function._.each._.forEach (/snap/rocketchat-server/1122/node_modules/underscore/underscore.js:153:9)
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at /snap/rocketchat-server/1122/programs/server/boot.js:158:5
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at /snap/rocketchat-server/1122/programs/server/boot.js:387:5
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at Function.run (/snap/rocketchat-server/1122/programs/server/profile.js:510:12)
ott 03 21:06:14 server rocketchat-server.rocketchat-server[19456]:   at /snap/rocketchat-server/1122/programs/server/boot.js:386:11
```

This is the log for rocketchat-caddy
```
ott 03 21:07:01 server systemd[1]: Started Service for snap application rocketchat-server.rocketchat-caddy.
ott 03 21:07:01 server rocketchat-server.rocketchat-caddy[22703]: 2017/10/03 21:07:01 loading Caddyfile via flag: open /var/snap/rocketchat-server/1122/Caddyfile: no such file or directory
ott 03 21:07:01 server systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Main process exited, code=exited, status=1/FAILURE
ott 03 21:07:01 server systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Unit entered failed state.
ott 03 21:07:01 server systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result 'exit-code'.
ott 03 21:07:01 server systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Service hold-off time over, scheduling restart.
ott 03 21:07:01 server systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-caddy.
ott 03 21:07:01 server systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Start request repeated too quickly.
ott 03 21:07:01 server systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-caddy.
ott 03 21:07:09 server systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Start request repeated too quickly.
ott 03 21:07:09 server systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-caddy.
```


I hope it helps

**Comment by unixfox** [comment]
@johnyb0y You aren't running the release candidate version, use `snap refresh rocketchat-server --candidate`.

**Comment by geekgonecrazy** [comment]
@JohnnyKing94 yes looks like you must have tried to roll back to stable.  That's not going to work. 

This is exactly why we recommend not trying something out in production.

You'll need to do as @unixfox suggested and refresh back to candidate.  You're database has already ran migration 100 which is present in 0.59.0 and not present in 0.58.3.  0.58.3 is at migration level 99.  So you cannot simply roll back to stable.

If you run: `sudo snap refresh rocketchat-server --candidate` you will switch back to candidate.  It should now work.

When we release 0.59.0 then you can do: `sudo snap refresh rocketchat-server --stable` to swap back over to the stable channel, where i'd recommend sticking to avoid these sort of issues in a production system :)

**Comment by JohnnyKing94** [comment]
i'm already running the candidate version

```
root@server:~# sudo snap refresh rocketchat-server --candidate
snap "rocketchat-server" has no updates available
```
```
root@server:~# snap list
Name               Version       Rev   Developer   Notes
core               16-2.27.6     2898  canonical   core
rocketchat-server  0.59.0-rc.11  1122  rocketchat  -
```

**Comment by geekgonecrazy** [comment]
ok now it should be fixed.  Took me a good while to track down the actual issue.  Doing a refresh now should get you up and going.

Thanks for your patience.

**Comment by unixfox** [comment]
Rocketchat is now running fine for me, thank you @geekgonecrazy for your help.

**Comment by JohnnyKing94** [comment]
Yes it works now... @geekgonecrazy thank you for everything
