### ISSUE TITLE
[Bug] Server errors when closing or transferring a livechat client that was not answered

### ISSUE THREAD

**Issue by icosamuel** [RocketChat/Rocket.Chat#8399]
### Description:
Server errors when closing or transferring a livechat client that was not answered

### Server Setup Information:
* Version of Rocket.Chat Server: 0.58.2
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1

### Steps to Reproduce:
1. Have a livechat guest request, but do not answer or attribute him to an agent.
2. Go in the livechat conversation log.
3. Select the appropriate conversation and attempt to close or transfer it.

### Expected behavior:
Mark the chat as closed

### Actual behavior:
Server Error

### Relevant logs:
![screen shot](https://user-images.githubusercontent.com/5400332/31197677-d9ef638a-a91f-11e7-91b5-889dca7a67ca.png)

The stack trace found in our server log
```
Exception while invoking method 'livechat:closeRoom' TypeError: Cannot read property 'indexOf' of undefined
  at [object Object].Meteor.methods.livechat:closeRoom (/snap/rocketchat-server/1099/programs/server/packages/rocketchat_livechat.js:438:21)
  at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/1099/programs/server/packages/rocketchat_lib.js:1109:26)
  at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
  at maybeAuditArgumentChecks (/snap/rocketchat-server/1099/programs/server/packages/ddp-server.js:1857:12)
  at /snap/rocketchat-server/1099/programs/server/packages/ddp-server.js:903:20
  at [object Object].EVp.withValue (packages/meteor.js:1134:15)
  at /snap/rocketchat-server/1099/programs/server/packages/ddp-server.js:902:47
  at [object Object].EVp.withValue (packages/meteor.js:1134:15)
  at /snap/rocketchat-server/1099/programs/server/packages/ddp-server.js:901:46
  at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/1099/programs/server/packages/ddp-server.js:874:21)
  at /snap/rocketchat-server/1099/programs/server/packages/ddp-server.js:753:85

**Comment by Key4ce** [comment]
We are also facing the same issue when upgrading from 0.54.2 to 0.59.0.

Is there a way we can kick or close this session within the DB?

**Comment by kevinctracy** [comment]
This is occurring to us as well.  Ubuntu, Snaps, 5.9.3
