### ISSUE TITLE
Can't find migration version 102

### ISSUE THREAD

**Issue by JohnnyKing94** [RocketChat/Rocket.Chat#8430]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.11
* Operating System: Ubuntu Linux 16.04.1 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v5.12.0

### Steps to Reproduce:

I think snap auto-refresh the release with new revisions, cause today i got my chat not working with this error  log:
```
ott 07 12:45:34 server systemd[1]: Started Service for snap application rocketchat-server.rocketchat-server.
ott 07 12:45:34 server rocketchat-server.rocketchat-server[12720]: Checking if oplog has been enabled, and enabling if not
ott 07 12:45:34 server rocketchat-server.rocketchat-server[12720]: MongoDB shell version: 3.2.7
ott 07 12:45:34 server rocketchat-server.rocketchat-server[12720]: connecting to: test
ott 07 12:45:39 server rocketchat-server.rocketchat-server[12720]: Will load cache for users
ott 07 12:45:40 server rocketchat-server.rocketchat-server[12720]: 27 records load from users
ott 07 12:45:40 server rocketchat-server.rocketchat-server[12720]: Will load cache for rocketchat_room
ott 07 12:45:40 server rocketchat-server.rocketchat-server[12720]: 9 records load from rocketchat_room
ott 07 12:45:40 server rocketchat-server.rocketchat-server[12720]: Will load cache for rocketchat_subscription
ott 07 12:45:40 server rocketchat-server.rocketchat-server[12720]: 97 records load from rocketchat_subscription
ott 07 12:45:40 server rocketchat-server.rocketchat-server[12720]: Will load cache for rocketchat_settings
ott 07 12:45:40 server rocketchat-server.rocketchat-server[12720]: 563 records load from rocketchat_settings
ott 07 12:45:43 server rocketchat-server.rocketchat-server[12720]: Updating process.env.MAIL_URL
ott 07 12:45:49 server rocketchat-server.rocketchat-server[12720]: Will load cache for rocketchat_permissions
ott 07 12:45:49 server rocketchat-server.rocketchat-server[12720]: 74 records load from rocketchat_permissions
ott 07 12:45:49 server rocketchat-server.rocketchat-server[12720]: Will load cache for rocketchat_roles
ott 07 12:45:49 server rocketchat-server.rocketchat-server[12720]: 12 records load from rocketchat_roles
ott 07 12:45:52 server rocketchat-server.rocketchat-server[12720]: LocalStore: store created at
ott 07 12:45:52 server rocketchat-server.rocketchat-server[12720]: LocalStore: store created at
ott 07 12:45:54 server rocketchat-server.rocketchat-server[12720]: Setting default file store to GridFS
ott 07 12:45:54 server rocketchat-server.rocketchat-server[12720]: LocalStore: store created at
ott 07 12:45:54 server rocketchat-server.rocketchat-server[12720]: LocalStore: store created at
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]: Exception in callback of async function: Error: [Can't find migration version 102]
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at Object.Migrations._findIndexByVersion (/snap/rocketchat-server/1122/programs/server/packages/rocketchat_migrations.js:403:8)
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at Object.Migrations._migrateTo (/snap/rocketchat-server/1122/programs/server/packages/rocketchat_migrations.js:270:22)
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at Object.Migrations.migrateTo (/snap/rocketchat-server/1122/programs/server/packages/rocketchat_migrations.js:199:20)
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at meteorInstall.server.startup.migrations.xrun.js (/snap/rocketchat-server/1122/programs/server/app/app.js:5229:24)
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at fileEvaluate (packages/modules-runtime.js:333:9)
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at require (packages/modules-runtime.js:228:16)
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at /snap/rocketchat-server/1122/programs/server/app/app.js:10258:1
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at /snap/rocketchat-server/1122/programs/server/boot.js:338:34
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at Function._.each._.forEach (/snap/rocketchat-server/1122/node_modules/underscore/underscore.js:153:9)
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at /snap/rocketchat-server/1122/programs/server/boot.js:158:5
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at /snap/rocketchat-server/1122/programs/server/boot.js:387:5
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at Function.run (/snap/rocketchat-server/1122/programs/server/profile.js:510:12)
ott 07 12:46:01 server rocketchat-server.rocketchat-server[12720]:   at /snap/rocketchat-server/1122/programs/server/boot.js:386:11
```

**Comment by luixal** [comment]
Same problem here but with version 104. Any ideas on how to make this work when rolling back to previous version?
