### ISSUE TITLE
Unable to download an extensionless file

### ISSUE THREAD

**Issue by staticjinno** [RocketChat/Rocket.Chat#8540]
### Description:

Uploaded an extension-less file, when trying to download it i'm getting an error.

### Server Setup Information:

* Version of Rocket.Chat Server: latest (0.59.0)
* Operating System: docker on ubuntu 14
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 4.8.4 - x64 

### Steps to Reproduce:

1. upload an extension-less file
2. try to download it

### Expected behavior:

file to be downloaded

### Actual behavior:

rocket is expecting a content-type

### Relevant logs:
Error: `value` required in setHeader("Content-Type", value).
  at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
  at ServerResponse.res.setHeader (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/patch.js:134:22)
  at ServerResponse.res.setHeader (/app/bundle/programs/server/packages/rocketchat_cors.js:81:20)
  at ServerResponse.setWriteHeadHeaders (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/on-headers/index.js:82:19)
  at ServerResponse.writeHead (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/on-headers/index.js:41:36)
  at readFromGridFS (/app/bundle/programs/server/packages/rocketchat_file-upload.js:1191:7)
  at FileUploadClass.get (/app/bundle/programs/server/packages/rocketchat_file-upload.js:1273:10)
  at Object.assign.get (/app/bundle/programs/server/packages/rocketchat_file-upload.js:482:17)
  at Object.handle (/app/bundle/programs/server/packages/rocketchat_file-upload.js:784:22)
  at next (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
  at Object.handle (/app/bundle/programs/server/packages/jalik_ufs.js:1231:13)
  at next (/app/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
  at middleware (/app/bundle/programs/server/packages/rocketchat_cas.js:233:4)
  at /app/bundle/programs/server/packages/rocketchat_cas.js:260:3

**Comment by wilibox** [comment]
We are suffering from this problem too. Is it going to be fixed ?

**Comment by fabien4455** [comment]
Please see #12668 I've writed a lot of things about this problem. 

With some screenshots etc
