### ISSUE TITLE
File upload problem

### ISSUE THREAD

**Issue by exagon** [RocketChat/Rocket.Chat#8548]
Hi at all,
i've problem to upload files on local file system, here the error :

[34mMeteor ➔ method ufsComplete -> userId: AsR6v9fD7KMdFBc3E , arguments:  { '0': 'ZMyiSCHpSauiDpszC', '1': 'Uploads', '2': '6a38489aB9' } 
[34mI20171019-19:14:34.133(2) Exception while invoking method 'ufsComplete' Error: EACCES: permission denied, open '/snap/rocketchat-server/docs/ZMyiSCHpSauiDpszC.png'   at Object.Future.wait (/snap/rocketchat-server/1142/programs/server/node_modules/fibers/future.js:449:15)   at [object Object].Meteor.methods.ufsComplete (/snap/rocketchat-server/1142/programs/server/packages/jalik_ufs.js:817:24)   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/1142/programs/server/packages/rocketchat_lib.js:1109:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/snap/rocketchat-server/1142/programs/server/packages/ddp-server.js:1857:12)   at /snap/rocketchat-server/1142/programs/server/packages/ddp-server.js:903:20   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /snap/rocketchat-server/1142/programs/server/packages/ddp-server.js:902:47   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /snap/rocketchat-server/1142/programs/server/packages/ddp-server.js:901:46   at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/1142/programs/server/packages/ddp-server.js:874:21)   at /snap/rocketchat-server/1142/programs/server/packages/ddp-server.js:753:85      - - - - -   at Error (native)  
[34mI20171019-19:14:34.196(2) [34mMeteor ➔ method ufsDelete -> userId: AsR6v9fD7KMdFBc3E , arguments:  { '0': 'ZMyiSCHpSauiDpszC', '1': 'Uploads', '2': '6a38489aB9' } 
[34mI20171019-19:14:45.551(2) [34mMeteor ➔ method UserPresence:online -> userId: XDhwsjNgDtQwTJBz6 , arguments:  {} 
[34mI20171019-19:14:46.152(2) [34mMeteor ➔ method spotlight -> userId: XDhwsjNgDtQwTJBz6 , arguments:  { '0': '',   '1':     [ { _id: 'XDhwsjNgDtQwTJBz6',        emails: [Object],        username: 'admin',        active: true,        name: 'admin',        roles: [Object],        services: [Object],        status: 'online',        statusConnection: 'online',        statusDefault: 'online',        statusLivechat: 'not-available',        utcOffset: 2 } ],   '2': { users: true, rooms: true } } 
[34mI20171019-19:19:43.060(2) [34mMeteor ➔ method UserPresence:away -> userId: AsR6v9fD7KMdFBc3E , arguments:  {}

But i've 777 on /snap/rocketchat-server/docs/ directory.
Rocket chat version is 0.58.4
Someone can point me ?

thanks a lot

**Comment by exagon** [comment]
The same error on 0.59.1

**Comment by jszaszvari** [comment]
the user RocketChat is running as does not have permission to read/write to the folder its attempting to use

You said you tried 777ing the directory, but are you able to check what user and group owns the directory and verify that it matches the user that RC is running as?

**Comment by exagon** [comment]
Rocketchat use root
root@chat:/snap/rocketchat-server# ps -ef | grep rocket
root     28119     1  0 11:32 ?        00:00:00 /bin/sh /snap/rocketchat-server/1172/bin/startmongo
root     28147 28119  1 11:32 ?        00:00:07 mongod --bind_ip 127.0.0.1 --pidfilepath /var/snap/rocketchat-server/common/mongod.pid --smallfiles --journal --dbpath=/var/snap/rocketchat-server/common --replSet rs0
root     28454     1  0 11:32 ?        00:00:00 /bin/bash /snap/rocketchat-server/1172/bin/startRocketChat
root     28471 28454  4 11:32 ?        00:00:28 node /snap/rocketchat-server/1172/main.js
root     28565 26427  0 11:44 pts/0    00:00:00 grep --color=auto rocket

the file system permission :
/snap/rocketchat-server/docs

ls -ltrd /snap
drwxrwxrwx 5 root root 4096 Feb 20  2017 /snap/
ls -ltrd /snap/rocketchat-server
drwxrwxrwx 6 root www-data 4096 Oct 20 02:52 /snap/rocketchat-server
ls -ltrd /snap/rocketchat-server/docs
drwxrwxrwx 2 root www-data 4096 Feb 20  2017 /snap/rocketchat-server/docs

the error :
Exception while invoking method 'ufsComplete' Error: EACCES: permission denied, open '/snap/rocketchat-server/docs/Wb8T9RxshTsgAovhd.txt'

**Comment by exagon** [comment]
I think it's a BUG of SNAP. So i've reinstalled all manually and now the file upload on local file system work well.... but i've other problem with LDAP now :(

**Comment by o-jans** [comment]
Same problem here with 0.65.1

Exception while invoking method 'ufsComplete' Error: EACCES: permission denied, open '/var/snap/rocketchat-server/upload/xprB3KYTnAb7qtHeC.png'
