### ISSUE TITLE
Room can not add user now

### ISSUE THREAD

**Issue by steedos** [RocketChat/Rocket.Chat#857]
Exception while invoking method 'addUserToRoom' TypeError: Cannot read property '_id' of undefined
at _Class.RocketChat.models.Subscriptions._Class.createWithRoomAndUser (/data/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:947:18)
at [object Object].Meteor.methods.addUserToRoom (/data/rocket.chat/bundle/programs/server/app/server/methods/addUserToRoom.coffee.js:18:37)
at [object Object].methodMap.(anonymous function) (/data/rocket.chat/bundle/programs/server/packages/meteorhacks_kadira.js:2574:30)
at maybeAuditArgumentChecks (/data/rocket.chat/bundle/programs/server/packages/ddp.js:2445:12)
at /data/rocket.chat/bundle/programs/server/packages/ddp.js:1476:20
at [object Object]._.extend.withValue (/data/rocket.chat/bundle/programs/server/packages/meteor.js:989:17)
at /data/rocket.chat/bundle/programs/server/packages/ddp.js:1475:41
at [object Object]._.extend.withValue (/data/rocket.chat/bundle/programs/server/packages/meteor.js:989:17)
at [object Object]._.extend.protocol_handlers.method (/data/rocket.chat/bundle/programs/server/packages/ddp.js:1474:51)
at /data/rocket.chat/bundle/programs/server/packages/ddp.js:1374:43

**Comment by rwakida** [comment]
To replicate:
1. Create room
2. From right flex area, add user to room.

**Comment by rwakida** [comment]
Fixed wiht PR #860
