### ISSUE TITLE
Can't upload files and no more pre-vizualisation

### ISSUE THREAD

**Issue by pedroxim** [RocketChat/Rocket.Chat#8607]
Hello, I have 2 RocketChat (0.58.4) instance with a reverse proxy (NGINX), connected to mongoDB replicaSET. Is it normal that :
1. Sometimes, one node crashes (still works but I can't upload any file again) 
2. No more pre-vizualisation link (To make it work, I restarted the service)

**Comment by pedroxim** [comment]
StackTrace when the upload no longer works in one node
```oct. 23 17:57:46  RocketChat[31498]: at emitOne (events.js:82:20)
oct. 23 17:57:46  RocketChat[31498]: at Socket.emit (events.js:169:7)
oct. 23 17:57:46  RocketChat[31498]: at TCP._onclose (net.js:486:12)
oct. 23 17:57:46  RocketChat[31498]: Exception in callback of async function: Error: socket hang up
oct. 23 17:57:46  RocketChat[31498]: at createHangUpError (_http_client.js:213:15)
oct. 23 17:57:46  RocketChat[31498]: at Socket.socketCloseListener (_http_client.js:245:23)
oct. 23 17:57:46  RocketChat[31498]: at emitOne (events.js:82:20)
oct. 23 17:57:46  RocketChat[31498]: at Socket.emit (events.js:169:7)
oct. 23 17:57:46  RocketChat[31498]: at TCP._onclose (net.js:486:12)
oct. 23 17:57:46  RocketChat[31498]: Exception in callback of async function: Error: socket hang up
oct. 23 17:57:46  RocketChat[31498]: at createHangUpError (_http_client.js:213:15)
oct. 23 17:57:46  RocketChat[31498]: at Socket.socketOnEnd (_http_client.js:305:23)
oct. 23 17:57:46  RocketChat[31498]: at emitNone (events.js:72:20)
oct. 23 17:57:46  RocketChat[31498]: at Socket.emit (events.js:166:7)
oct. 23 17:57:46  RocketChat[31498]: at endReadableNT (_stream_readable.js:921:12)
oct. 23 17:57:46  RocketChat[31498]: at nextTickCallbackWith2Args (node.js:442:9)
oct. 23 17:57:46  RocketChat[31498]: at process._tickDomainCallback (node.js:397:17)
oct. 23 17:57:46  RocketChat[31498]: Exception in callback of async function: Error: socket hang up
oct. 23 17:57:46  RocketChat[31498]: at createHangUpError (_http_client.js:213:15)
oct. 23 17:57:46  RocketChat[31498]: at Socket.socketOnEnd (_http_client.js:305:23)
```

Stacktrace from the Nginx: 
```
2017/10/23 17:57:42 [error] 12102#12102: *342505 upstream prematurely closed connection while reading response header from upstream, client: X.X.X.X, server: rocket.domain.com, request: "POST /ufs/FileSystem:Uploads/G2yeSEFNu3PxiBMLP?token=88381a8ADB&progress=0.017363344732973927 HTTP/1.1", upstream: "http://rocket-1:3000/ufs/FileSystem:Uploads/G2yeSEFNu3PxiBMLP?token=88381a8ADB&progress=0.017363344732973927", host: "rocket.domain.com", referrer: "https://rocket.domain.com/direct/user.LDAP"
```

**Comment by sameergautam** [comment]
Did you figure out why this happened ? And what were your resolution steps ?
