### ISSUE TITLE
LDAP login issues with field sync

### ISSUE THREAD

**Issue by onigoetz** [RocketChat/Rocket.Chat#8621]
### Description

I encouter two issues with LDAP on Rocket Chat since updating to 0.59
The two issues seem linked as it looks like it can't get any field from an LDAP result.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: ubuntu
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 2
* DB Replicaset Oplog: sorry, I don't know what/where to check this.
* Node Version: 4.8.4

### Steps to Reproduce

1. Login with LDAP account

### Expected behavior

Syncing of user fields from LDAP results

### Actual behavior

```
// for existing users
rocketchat_logger TemplateVarHandler ➔ debug user does not have attribute: cn
rocketchat_logger LDAPSync ➔ debug user does not have attribute: mail

// for new users
rocketchat_logger LDAPHandler ➔ info User does not exist, creating  
Exception while invoking method 'login' TypeError: Cannot read property 'value' of undefined   
    at addLdapUser (/app/bundle/programs/server/packages/rocketchat_ldap.js:1270:43)   
```

#### Full log when the user already exists

I changed our base DN to __BASE_DN__ I'm not sure if I'm supposed to give this information :)

```
rocketchat2_1  | rocketchat_logger LDAPHandler ➔ info Init LDAP login o_vtverd
rocketchat2_1  | rocketchat_logger LDAP ➔ Connection.info Init setup
rocketchat2_1  | rocketchat_logger LDAP ➔ Connection.info Connecting ldap://192.168.14.201:389
rocketchat2_1  | ...
rocketchat2_1  | rocketchat_logger LDAP ➔ Search.info Searching user o_vtverd
rocketchat2_1  | rocketchat_logger LDAP ➔ Search.debug searchOptions { filter: '(&(objectclass=user)(sAMAccountName=o_vtverd))',
rocketchat2_1  |   scope: 'sub',
rocketchat2_1  |   sizeLimit: 1000,
rocketchat2_1  |   paged: { pageSize: 250, pagePause: false } }
rocketchat2_1  | rocketchat_logger LDAP ➔ Search.debug BaseDN __BASE_DN__
rocketchat2_1  | ...
rocketchat2_1  | rocketchat_logger LDAP ➔ Search.info Search result count 1
rocketchat2_1  | rocketchat_logger LDAP ➔ Auth.info Authenticating CN=O_Vladyslav Tverdokhliebov,OU=Mail User,OU=Ukraine,OU=Offshore,__BASE_DN__
rocketchat2_1  | ...
rocketchat2_1  | rocketchat_logger LDAP ➔ Auth.info Authenticated CN=O_Vladyslav Tverdokhliebov,OU=Mail User,OU=Ukraine,OU=Offshore,__BASE_DN__
rocketchat2_1  | rocketchat_logger LDAPHandler ➔ debug userQuery { username: 'o_vtverd' }
rocketchat2_1  | rocketchat_logger LDAPHandler ➔ info Logging user
rocketchat2_1  | rocketchat_logger LDAPSync ➔ info Syncing user data
rocketchat2_1  | rocketchat_logger LDAPSync ➔ debug user { email: undefined, _id: 'ugLkJtEgc3b8qbpnM' }
rocketchat2_1  | rocketchat_logger LDAPSync ➔ debug ldapUser SearchEntry {
rocketchat2_1  |   messageID: 2,
rocketchat2_1  |   protocolOp: 100,
rocketchat2_1  |   controls: [],
rocketchat2_1  |   log: 
rocketchat2_1  |    Logger {
rocketchat2_1  |      domain: null,
rocketchat2_1  |      _events: {},
rocketchat2_1  |      _eventsCount: 0,
rocketchat2_1  |      _maxListeners: undefined,
rocketchat2_1  |      _isSimpleChild: true,
rocketchat2_1  |      _level: 10,
rocketchat2_1  |      streams: [ [Object] ],
rocketchat2_1  |      serializers: null,
rocketchat2_1  |      src: false,
rocketchat2_1  |      fields: 
rocketchat2_1  |       { name: 'ldapjs',
rocketchat2_1  |         component: 'client',
rocketchat2_1  |         hostname: '8a2e577a444a',
rocketchat2_1  |         pid: 1,
rocketchat2_1  |         clazz: 'Client' },
rocketchat2_1  |      haveNonRawStreams: true },
rocketchat2_1  |   objectName: 'CN=O_Vladyslav Tverdokhliebov,OU=Mail User,OU=Ukraine,OU=Offshore,__BASE_DN__',
rocketchat2_1  |   attributes: 
rocketchat2_1  |    [ Attribute { type: 'objectClass', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'cn', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'sn', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'givenName', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'distinguishedName', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'instanceType', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'whenCreated', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'whenChanged', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'displayName', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'uSNCreated', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'memberOf', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'uSNChanged', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'proxyAddresses', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'targetAddress', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'mailNickname', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'internetEncoding', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'name', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'objectGUID', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'userAccountControl', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'badPwdCount', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'codePage', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'countryCode', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'badPasswordTime', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'lastLogoff', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'lastLogon', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'pwdLastSet', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'primaryGroupID', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'objectSid', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'accountExpires', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'logonCount', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'sAMAccountName', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'sAMAccountType', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'showInAddressBook', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'legacyExchangeDN', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'userPrincipalName', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'lockoutTime', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'objectCategory', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'dSCorePropagationData', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'lastLogonTimestamp', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'mail', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'msExchPoliciesExcluded', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'msExchUMDtmfMap', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'msExchRecipientDisplayType', _vals: [Object] },
rocketchat2_1  |      Attribute { type: 'msExchVersion', _vals: [Object] } ],
rocketchat2_1  |   connection: 
rocketchat2_1  |    Socket {
rocketchat2_1  |      _connecting: false,
rocketchat2_1  |      _hadError: false,
rocketchat2_1  |      _handle: 
rocketchat2_1  |       TCP {
rocketchat2_1  |         bytesRead: 3322,
rocketchat2_1  |         _externalStream: {},
rocketchat2_1  |         fd: 99,
rocketchat2_1  |         reading: true,
rocketchat2_1  |         owner: [Circular],
rocketchat2_1  |         onread: [Function: onread],
rocketchat2_1  |         onconnection: null,
rocketchat2_1  |         writeQueueSize: 0 },
rocketchat2_1  |      _parent: null,
rocketchat2_1  |      _host: null,
rocketchat2_1  |      _readableState: 
rocketchat2_1  |       ReadableState {
rocketchat2_1  |         objectMode: false,
rocketchat2_1  |         highWaterMark: 16384,
rocketchat2_1  |         buffer: [],
rocketchat2_1  |         length: 0,
rocketchat2_1  |         pipes: null,
rocketchat2_1  |         pipesCount: 0,
rocketchat2_1  |         flowing: true,
rocketchat2_1  |         ended: false,
rocketchat2_1  |         endEmitted: false,
rocketchat2_1  |         reading: true,
rocketchat2_1  |         sync: false,
rocketchat2_1  |         needReadable: true,
rocketchat2_1  |         emittedReadable: false,
rocketchat2_1  |         readableListening: false,
rocketchat2_1  |         resumeScheduled: false,
rocketchat2_1  |         defaultEncoding: 'utf8',
rocketchat2_1  |         ranOut: false,
rocketchat2_1  |         awaitDrain: 0,
rocketchat2_1  |         readingMore: false,
rocketchat2_1  |         decoder: null,
rocketchat2_1  |         encoding: null },
rocketchat2_1  |      readable: true,
rocketchat2_1  |      domain: null,
rocketchat2_1  |      _events: 
rocketchat2_1  |       { finish: [Function: onSocketFinish],
rocketchat2_1  |         _socketEnd: [Function: onSocketEnd],
rocketchat2_1  |         data: [Function: onData],
rocketchat2_1  |         close: [Object],
rocketchat2_1  |         end: [Function: onEnd],
rocketchat2_1  |         error: [Function: onSocketError],
rocketchat2_1  |         timeout: [Function: onTimeout] },
rocketchat2_1  |      _eventsCount: 7,
rocketchat2_1  |      _maxListeners: undefined,
rocketchat2_1  |      _writableState: 
rocketchat2_1  |       WritableState {
rocketchat2_1  |         objectMode: false,
rocketchat2_1  |         highWaterMark: 16384,
rocketchat2_1  |         needDrain: false,
rocketchat2_1  |         ending: false,
rocketchat2_1  |         ended: false,
rocketchat2_1  |         finished: false,
rocketchat2_1  |         decodeStrings: false,
rocketchat2_1  |         defaultEncoding: 'utf8',
rocketchat2_1  |         length: 0,
rocketchat2_1  |         writing: false,
rocketchat2_1  |         corked: 0,
rocketchat2_1  |         sync: false,
rocketchat2_1  |         bufferProcessing: false,
rocketchat2_1  |         onwrite: [Function],
rocketchat2_1  |         writecb: null,
rocketchat2_1  |         writelen: 0,
rocketchat2_1  |         bufferedRequest: null,
rocketchat2_1  |         lastBufferedRequest: null,
rocketchat2_1  |         pendingcb: 0,
rocketchat2_1  |         prefinished: false,
rocketchat2_1  |         errorEmitted: false,
rocketchat2_1  |         bufferedRequestCount: 0,
rocketchat2_1  |         corkedRequestsFree: [Object] },
rocketchat2_1  |      writable: true,
rocketchat2_1  |      allowHalfOpen: false,
rocketchat2_1  |      destroyed: false,
rocketchat2_1  |      _bytesDispatched: 305,
rocketchat2_1  |      _sockname: null,
rocketchat2_1  |      _pendingData: null,
rocketchat2_1  |      _pendingEncoding: '',
rocketchat2_1  |      server: null,
rocketchat2_1  |      _server: null,
rocketchat2_1  |      read: [Function],
rocketchat2_1  |      _consuming: true } }
rocketchat2_1  | rocketchat_logger TemplateVarHandler ➔ debug user does not have attribute: cn
rocketchat2_1  | rocketchat_logger LDAPSync ➔ debug user does not have attribute: mail
```

Also, if I defined `LDAP_Username_Field`'s value to `sAMAccountName` the `userQuery` becomes `{username: ''}`

That's why I think that every field taken from the ldapUser is empty or fails in some way

#### Full log when the user doesn't exist yet

( I replaced the user's object name with `__USER_WAS_FOUND__`)

```
rocketchat_logger LDAP ➔ Search.info Searching user dvienne 
rocketchat_logger LDAP ➔ Search.info Search result count 1 
rocketchat_logger LDAP ➔ Auth.info Authenticating __USER_WAS_FOUND__
rocketchat_logger LDAP ➔ Auth.info Authenticated __USER_WAS_FOUND__
rocketchat_logger LDAPHandler ➔ info User does not exist, creating  
Exception while invoking method 'login' TypeError: Cannot read property 'value' of undefined   
    at addLdapUser (/app/bundle/programs/server/packages/rocketchat_ldap.js:1270:43)   
    at [object Object].<anonymous> (/app/bundle/programs/server/packages/rocketchat_ldap.js:773:9)   
    at /app/bundle/programs/server/packages/accounts-base.js:925:30   
    at tryLoginMethod (/app/bundle/programs/server/packages/accounts-base.js:753:14)   
    at AccountsServer.Ap._runLoginHandlers (/app/bundle/programs/server/packages/accounts-base.js:924:18)   
    at AccountsServer.Accounts._runLoginHandlers (/app/bundle/programs/server/packages/rocketchat_lib.js:1951:33)   
    at [object Object].methods.login (/app/bundle/programs/server/packages/accounts-base.js:982:27)   
    at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   
    at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1857:12)   
    at /app/bundle/programs/server/packages/ddp-server.js:903:20   
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)   
    at /app/bundle/programs/server/packages/ddp-server.js:902:47   
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)   
    at /app/bundle/programs/server/packages/ddp-server.js:901:46   
    at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:874:21)   
    at /app/bundle/programs/server/packages/ddp-server.js:753:85  
```

#### For existing users

According to the log, an `ldapUser` is an instance of `SearchEntry` (https://github.com/mcavage/node-ldapjs/blob/7059cf6b8a0b4ff4c566714d97f3cef04f887c3b/lib/messages/search_entry.js)

Which seems to store the values in an `attributes` field. It doesn't seem to have a special getter.

And the ldapUser field is always used without the "attributes" object or anything : https://github.com/RocketChat/Rocket.Chat/blob/e2b0379dc967f59148c8e4b8aeaf4b9a0f914e80/packages/rocketchat-ldap/server/sync.js#L75

(I might be missing something, but that's what seemed logical to me)

#### For new users

I traced this error to this :
https://github.com/RocketChat/Rocket.Chat/blob/e2b0379dc967f59148c8e4b8aeaf4b9a0f914e80/packages/rocketchat-ldap/server/sync.js#L199

at `uniqueId.value`

The value of `LDAP_Unique_Identifier_Field` is `objectGUID,ibm-entryUUID,GUID,dominoUNID,nsuniqueId,uidNumber`

And as you can see it the first log, our users have an `objectGUID` in their data. but it seems the module can't get any attributes from the user's data.

**Comment by onigoetz** [comment]
Pinging @rodrigok as it seems you're the person to contact for LDAP issues :)

**Comment by rodrigok** [comment]
@onigoetz Can you contact me at https://open.rocket.chat/direct/rodrigo.nascimento?

**Comment by nebulade** [comment]
Not sure if related, but we also cannot login with LDAP anymore on 0.59. From the ldap server output I can see a correct auth bind and a subsequent correct search on login attempt, however rocket.chat logs this:
```
20:30:19 [main] rocketchat_logger rocketchat_logger.js:375 LDAP ➔ Search.error { [PagedError: missing paged control] name: 'PagedError' }
20:30:19 [main] rocketchat_logger rocketchat_logger.js:375 LDAPHandler ➔ error { [PagedError: missing paged control] name: 'PagedError' }
```

On a sidenote it seems https://docs.rocket.chat/administrator-guides/authentication/ldap/#ldap and the actual code from https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-ldap/server/settings.js are a bit out of sync, or am I reading the code incorrectly?

**Comment by sscholl** [comment]
If have the same error again in 0.60.1

```[34mI20171228-16:43:16.079(0) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Search.error { PagedError: missing paged control   at SearchPager._onEnd (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/search_pager.js:91:15)   at emitOne (events.js:116:13)   at EventEmitter.emit (events.js:211:7)   at sendResult (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1389:22)   at messageCallback (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1421:16)   at Parser.onMessage (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)   at emitOne (events.js:116:13)   at Parser.emit (events.js:211:7)   at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)   at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)   at emitOne (events.js:116:13)   at Socket.emit (events.js:211:7)   at addChunk (_stream_readable.js:263:12)   at readableAddChunk (_stream_readable.js:250:11)   at Socket.Readable.push (_stream_readable.js:208:10)   at TCP.onread (net.js:594:20)  name: 'PagedError' } 
[34mI20171228-16:43:16.087(0) rocketchat_logger rocketchat_logger.js:278 [31mLDAPHandler ➔ error { PagedError: missing paged control   at SearchPager._onEnd (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/search_pager.js:91:15)   at emitOne (events.js:116:13)   at EventEmitter.emit (events.js:211:7)   at sendResult (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1389:22)   at messageCallback (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1421:16)   at Parser.onMessage (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)   at emitOne (events.js:116:13)   at Parser.emit (events.js:211:7)   at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)   at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)   at emitOne (events.js:116:13)   at Socket.emit (events.js:211:7)   at addChunk (_stream_readable.js:263:12)   at readableAddChunk (_stream_readable.js:250:11)   at Socket.Readable.push (_stream_readable.js:208:10)   at TCP.onread (net.js:594:20)  name: 'PagedError' } ```

**Comment by sscholl** [comment]
Nevermind, I found my problem. The LDAP Server can not do pagination.
=>I passed **0 to Search Page Size** to disable pagination
