### ISSUE TITLE
Image could not be loaded in v 0.59.1

### ISSUE THREAD

**Issue by Xarkam** [RocketChat/Rocket.Chat#8622]
Hello, 

### Description:

Image can be send but not loaded in rocketchat.
I'm using the file system for stocking files and have no any error in logs.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Ubuntu 16.04.1
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: activate
* Node Version: 4.8.4

### Steps to Reproduce:
In my case, juste send picture in chan and try to loaded.

### Expected behavior:

Displaying the picture in overlay.

### Actual behavior:

![image](https://user-images.githubusercontent.com/331816/31933751-52deaa78-b8aa-11e7-9438-4ccb63d61815.png)

### Relevant logs:
```
[34mI20171024-08:50:19.309(0) Will load cache for users 
[34mI20171024-08:50:19.438(0) 12 records load from users 
[34mI20171024-08:50:19.441(0) Will load cache for rocketchat_room 
[34mI20171024-08:50:19.450(0) 15 records load from rocketchat_room 
[34mI20171024-08:50:19.452(0) Will load cache for rocketchat_subscription 
[34mI20171024-08:50:19.480(0) 49 records load from rocketchat_subscription 
[34mI20171024-08:50:19.481(0) Will load cache for rocketchat_settings 
[34mI20171024-08:50:19.540(0) 570 records load from rocketchat_settings 
[34mI20171024-08:50:21.135(0) Updating process.env.MAIL_URL 
[34mI20171024-08:50:21.896(0) Starting Email Intercepter... 
[34mI20171024-08:50:22.900(0) Will load cache for rocketchat_permissions 
[34mI20171024-08:50:22.909(0) 74 records load from rocketchat_permissions 
[34mI20171024-08:50:22.919(0) Will load cache for rocketchat_roles 
[34mI20171024-08:50:22.921(0) 11 records load from rocketchat_roles 
[34mI20171024-08:50:30.426(0) Setting default file store to FileSystem 
[34mI20171024-08:50:36.135(0) (rocketchat_migrations.js:145) Migrations: Not migrating, already at version 104
[34mI20171024-08:50:36.462(0) [32mUsing GridFS for custom sounds storage 
[34mI20171024-08:50:36.468(0) [32mUsing GridFS for custom emoji storage 
[34mI20171024-08:50:36.660(0) Updating process.env.MAIL_URL 
[34mI20171024-08:50:37.109(0) [32m➔ [32mSystem ➔ startup 
[34mI20171024-08:50:37.109(0) [32m➔ [32m+------------------------------------------------+ 
[34mI20171024-08:50:37.110(0) [32m➔ [32m|                 SERVER RUNNING                 | 
[34mI20171024-08:50:37.110(0) [32m➔ [32m+------------------------------------------------+ 
[34mI20171024-08:50:37.111(0) [32m➔ [32m|                                                | 
[34mI20171024-08:50:37.111(0) [32m➔ [32m|  Rocket.Chat Version: 0.59.1                   | 
[34mI20171024-08:50:37.111(0) [32m➔ [32m|       NodeJS Version: 4.8.4 - x64              | 
[34mI20171024-08:50:37.112(0) [32m➔ [32m|             Platform: linux                    | 
[34mI20171024-08:50:37.113(0) [32m➔ [32m|         Process Port: 3000                     | 
[34mI20171024-08:50:37.113(0) [32m➔ [32m|             Site URL: https://chat.osames.org  | 
[34mI20171024-08:50:37.114(0) [32m➔ [32m|     ReplicaSet OpLog: Enabled                  | 
[34mI20171024-08:50:37.114(0) [32m➔ [32m|          Commit Hash: 0710c94d6a               | 
[34mI20171024-08:50:37.114(0) [32m➔ [32m|        Commit Branch: HEAD                     | 
[34mI20171024-08:50:37.115(0) [32m➔ [32m|                                                | 
[34mI20171024-08:50:37.115(0) [32m➔ [32m+------------------------------------------------+ 
[34mI20171024-08:50:37.637(0) [Tue Oct 24 2017 08:50:37 GMT+0000 (UTC)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd. 
[34mI20171024-08:50:37.638(0) [32mLoaded hubot-help/src/help.coffee 
```

Thanks.

**Comment by MartinSchoeler** [comment]
@Xarkam I could not reproduce this issue, can you give us more info on your filesystem settings and such? Thanks

**Comment by Xarkam** [comment]
I have upgraded log verbosity.
And it's seem a permissions problem, because I have restarted the docker container.
```
Exception while invoking method 'ufsComplete' Error: EACCES: permission denied, open '/app/uploads/jovMMcp33j6fvyaab.jpg'   at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)   at [object Object].Meteor.methods.ufsComplete (/app/bundle/programs/server/packages/jalik_ufs.js:817:24)   at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1276:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1857:12)   at /app/bundle/programs/server/packages/ddp-server.js:903:20   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /app/bundle/programs/server/packages/ddp-server.js:902:47   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /app/bundle/programs/server/packages/ddp-server.js:901:46   at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:874:21)   at /app/bundle/programs/server/packages/ddp-server.js:753:85      - - - - -   at Error (native)  
```

It's certainly a upgrade process problem.

**Comment by Xarkam** [comment]
**Fixed** I've changed the rocketchat group gid from 998 to 99999
