### ISSUE TITLE
Issues storing SMTP Settings

### ISSUE THREAD

**Issue by CaEike81** [RocketChat/Rocket.Chat#8732]
Not able to setup SMTP as expected

Rocket.Chat Server 0.57.3
Debian 8
Number of Running Instances: 2
DB Replicaset Oplog: yes
Node Version: 4.7.1

### Steps to Reproduce:

1. Login in as Admin
2. Setting up SMTP using WebGUI (filling the form)
3. Storing the Information
4. Getting popUp "Stored Sucessfully"
5. Sending Testmail to myself resulting an "internal error" 

### Expected behavior:

Able to send mails via SMTP

### Actual behavior:
Just not working

### Relevant logs:

[34mI20171031-16:40:26.789(0) Updating process.env.MAIL_URL
[34mI20171031-16:41:44.982(0) Exception while invoking method 'sendSMTPTestEmail' TypeError: Cannot read property '0' of undefined   at [object Object].Meteor.methods.sendSMTPTestEmail (/home/webmaster/Rocket.Chat/programs/server/packages/rocketchat_lib.js:14136:35)   at [object Object].methodsMap.(anonymous function) (/home/webmaster/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1028:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/home/webmaster/Rocket.Chat/programs/server/packages/ddp-server.js:1823:12)   at /home/webmaster/Rocket.Chat/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /home/webmaster/Rocket.Chat/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /home/webmaster/Rocket.Chat/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/home/webmaster/Rocket.Chat/programs/server/packages/ddp-server.js:876:21)   at /home/webmaster/Rocket.Chat/programs/server/packages/ddp-server.js:755:85

**Comment by geraldinkorea** [comment]
I am having the same issue, I have been looking for the error logs, which log did you get the above information from? 

Cheers,
Gerald

**Comment by CaEike81** [comment]
Hey @geraldinkorea 

I just copied the log from the admin interface using the webinterface.

Anyhow I just solved the issue by updating Rocket Chat to a newer version.

**Comment by geraldinkorea** [comment]
I did the install on Wed. I will update and see if that works,

I will try to update and see if it solves the issue.

Thanks
