### ISSUE TITLE
0.59.2 to 0.59.3 - Can't find migration version 104

### ISSUE THREAD

**Issue by MrDragon** [RocketChat/Rocket.Chat#8804]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Ubuntu 14.04.5 LTS, Trusty Tahr
* Deployment Method(snap/docker/tar/etc): tgz from https://download.rocket.chat/stable
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: 4.8.4

### Steps to Reproduce:

1.  Start rocket chat
2. 
3. 

### Expected behavior:

Server starts and listens

### Actual behavior:

Server starts, but fails

### Relevant logs:
# cat rocketchat.log
Will load cache for users
86 records load from users
Will load cache for rocketchat_room
1287 records load from rocketchat_room
Will load cache for rocketchat_subscription
3289 records load from rocketchat_subscription
Will load cache for rocketchat_settings
572 records load from rocketchat_settings
Updating process.env.MAIL_URL
Will load cache for rocketchat_permissions
74 records load from rocketchat_permissions
Will load cache for rocketchat_roles
11 records load from rocketchat_roles
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
Exception in callback of async function: Error: [Can't find migration version 104]
  at Object.Migrations._findIndexByVersion (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_migrations.js:404:8)
  at Object.Migrations._migrateTo (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_migrations.js:271:22)
  at Object.Migrations.migrateTo (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_migrations.js:200:20)
  at meteorInstall.server.startup.migrations.xrun.js (/usr/local/Rocket.Chat/programs/server/app/app.js:5229:24)
  at fileEvaluate (packages/modules-runtime.js:333:9)
  at require (packages/modules-runtime.js:228:16)
  at /usr/local/Rocket.Chat/programs/server/app/app.js:10258:1
  at /usr/local/Rocket.Chat/programs/server/boot.js:338:34
  at Array.forEach (native)
  at Function._.each._.forEach (/usr/local/Rocket.Chat/programs/server/node_modules/underscore/underscore.js:79:11)
  at /usr/local/Rocket.Chat/programs/server/boot.js:158:5
  at /usr/local/Rocket.Chat/programs/server/boot.js:387:5
  at Function.run (/usr/local/Rocket.Chat/programs/server/profile.js:510:12)
  at /usr/local/Rocket.Chat/programs/server/boot.js:386:11

**Comment by MrDragon** [comment]
Well, upgrading from 0.59.2 straight to 0.59.6 (which I think is a patched version of 0.59.4) seems to have fixed things.
