### ISSUE TITLE
Console error while authenticating via the Wordpress method (oAuth)

### ISSUE THREAD

**Issue by nonsintetic** [RocketChat/Rocket.Chat#882]
While authenticating through oAuth this method pops up around the time you're asked to provide a nickname for the account you've just logged in with. The process works just fine though.

```-16:59:28.283(0)? Exception while invoking method 'getUsernameSuggestion' TypeError: Cannot call method 'split' of undefined
I20150924-16:59:28.283(0)?     at generateSuggestion (server/methods/getUsernameSuggestion.coffee:20:24)
I20150924-16:59:28.283(0)?     at [object Object].Meteor.methods.getUsernameSuggestion (server/methods/getUsernameSuggestion.coffee:69:10)
I20150924-16:59:28.283(0)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:164:1)
I20150924-16:59:28.283(0)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150924-16:59:28.283(0)?     at packages/ddp/livedata_server.js:648:1
I20150924-16:59:28.283(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150924-16:59:28.283(0)?     at packages/ddp/livedata_server.js:647:1
I20150924-16:59:28.283(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150924-16:59:28.283(0)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150924-16:59:28.284(0)?     at packages/ddp/livedata_server.js:546:1```

**Comment by marceloschmidt** [comment]
Fixed that on ba37abf
