### ISSUE TITLE
RocketChat can't talk to IPv6 Mongo server

### ISSUE THREAD

**Issue by valentin2105** [RocketChat/Rocket.Chat#8823]
Hi !

Hi try to deploy RocketChat in IPv6 only environment, 

The node process fail while trying to speak to IPv6-only MongoDB server dns name. 

```
MongoError: failed to connect to server [mongodb.default.svc.k8s.domain.tld:27017] on first connect [MongoError: getaddrinfo ENOTFOUND mongodb.default.svc.k8s.domain.tld mongodb.default.svc.k8s.domain.tld:27017]
```

It seem that `getaddrinfo` is basically used in IPv4 world only.. 

Thanks !

**Comment by frdmn** [comment]
I would assume that `getaddrinfo` is using the default DNS settings by the system. Can you check if you reach the Mongo using IPv6 on the host system with `telnet`?

```
$ telnet $(dig aaaa mongodb.default.svc.k8s.domain.tld +short | tail -1) 27017
```

**Comment by valentin2105** [comment]
```
bash-4.3# dig AAAA mongodb.default.svc.k8s.domain.tld +short
1404:f200:f:12::8204:d391
```
Telnet work. 

And RocketChat logs : 
```
/app/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: failed to connect to server [mongodb.default.svc.k8s.domain.tld:27017] on first connect [MongoError: getaddrinfo ENOTFOUND mongodb.default.svc.k8s.domain.tld mongodb.default.svc.k8s.domain.tld:27017]
    at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:210:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:99:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    - - - - -
    at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:329:35)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Socket.g (events.js:260:16)
```
