### ISSUE TITLE
Rocket.chat can not reach https://api.giphy.com/v1/ behind a proxy

### ISSUE THREAD

**Issue by Paulpatou** [RocketChat/Rocket.Chat#8825]
### Description:

I'm trying to use GifRocket in Rocketchat but it doesn't work. I'm sure the problem comes from rocket. chat that can't reach https://api.giphy.com/v1/
because we use a proxy. I have configured the proxy in Ubuntu (/etc/environment). but no change.

Where do I need to configure this proxy to make it work?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v4.8.4 x64

### Steps to Reproduce:

1. Configure outgoing Webhook in Rocket.Chat => https://github.com/FinndropStudios/GifRocket
2. Try to use the trigger words 
3. See the log error

### Expected behavior:

GifRocket reacts on a slash-command. For example entering !sticker test shows a sticker relating to the word test.

### Actual behavior:

GifRocket does not react to a slash command

### Relevant logs:
[34mI20171108-11:49:22.553(1) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Outgoing WebHook.error Error running Script in the Integration GifRocket: 

[34mI20171108-11:49:22.554(1) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Outgoing WebHook.error Stack: 

[34mI20171108-11:49:22.556(1) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Outgoing WebHook.error   TypeError: Cannot read property 'data' of undefined       at Script.process_outgoing_response (script.js:1:1074)       at evalmachine.<anonymous>:1:15       at ContextifyScript.Script.runInNewContext (vm.js:18:15)       at Object.exports.runInNewContext (vm.js:49:17)       at RocketChatIntegrationHandler.executeScript (/snap/rocketchat-server/1188/programs/server/packages/rocketchat_integrations.js:858:26)       at /snap/rocketchat-server/1188/programs/server/packages/rocketchat_integrations.js:1497:32       at runWithEnvironment (packages/meteor.js:1188:24) 

[34mI20171108-11:49:22.559(1) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Outgoing WebHook.error Error for the Integration "GifRocket" to https://api.giphy.com/v1/ is: 

[34mI20171108-11:49:22.561(1) rocketchat_logger rocketchat_logger.js:375 [31mIntegrations ➔ Outgoing WebHook.error { [Error: getaddrinfo ENOTFOUND api.giphy.com api.giphy.com:443]   code: 'ENOTFOUND',   errno: 'ENOTFOUND',   syscall: 'getaddrinfo',   hostname: 'api.giphy.com',   host: 'api.giphy.com',   port: 443 }

**Comment by frdmn** [comment]
There is a way to pass proxy settings to Meteor applications using environment variables as well: https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy

Unfortunately that won't work with the snap deployments because you're not able to adjust the environment variables that are being used here.

A solution would be to migrate to manual or Docker installation so you're able to customize your setup and add the desired proxy settings.

**Comment by Paulpatou** [comment]
Thank you for this information I understand better.
Is there a procedure to migrate from snap to docker without losing the current rocket. chat configuration?

**Comment by frdmn** [comment]
Yes, there is. Check out our documentation how to backup/export data from your Snap: https://docs.rocket.chat/installation/manual-installation/ubuntu/snaps/#how-do-i-backup-my-snap-data-

Basically, all the persistent data (users, configurations, messages, channels, even file uploads if you use the default storage) is stored all in the MongoDB - so if you dump said database and import it back onto the new system  then use that imported database you will end up with the "same" system.

**Comment by maxdwit** [comment]
One hint. The mongo Database Name within snap is different then the one used with the tar-ball version.
snap uses:  parties , the tar version uses rocketchat 

Never use the following on a live system. Backup your data.
Example, how to "rename" the mongo db from parties to rocketchat:

```
show dbs;
use rocketchat;
db.dropDatabase();
use parties;
db.copyDatabase('parties','rocketchat');
use parties;
db.dropDatabase();
show dbs;

```

**Comment by Paulpatou** [comment]
Thanks guys, I've migrated my rocket.chat snap to docker and the Mongo database.
My proxy problem is still present. I tried to follow the indications of @frdmn but I can't find the Meteor tool to configure the proxy.

Do you know where I can find it?

**Comment by maxdwit** [comment]
Do something like this to your rocketchat service:

https://www.thegeekdiary.com/how-to-configure-docker-to-use-proxy/

Maybe this helps.

 

Kind Regards

Max

 

Von: Paulpatou [mailto:notifications@github.com] 
Gesendet: Dienstag, 14. November 2017 13:23
An: RocketChat/Rocket.Chat
Cc: maxdwit; Comment
Betreff: Re: [RocketChat/Rocket.Chat] Rocket.chat can not reach https://api.giphy.com/v1/ behind a proxy (#8825)

 

Thanks guys, I've migrated my rocket.chat snap to docker and the Mongo database.
My proxy problem is still present. I tried to follow the indications of @frdmn <https://github.com/frdmn>  but I can't find the Meteor tool to configure the proxy.

Do you know where I can find it?

**Comment by holgerdell** [comment]
According to the resolution in #5090, it _is_ possible to edit the environment variables inside a snap application. (Haven't tested it though. If this works, it should be mentioned in the docs)
