### ISSUE TITLE
RocketChat failed install on Centos 7 behind proxy

### ISSUE THREAD

**Issue by devoncustard** [RocketChat/Rocket.Chat#8867]
Tested install on my home server with minimal issues. Running OK. 

Attempted install on Centos 7 server at work running behind a proxy, followed same instructions and getting google-vision errors

Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
Will load cache for users
0 records load from users
Will load cache for rocketchat_room
0 records load from rocketchat_room
Will load cache for rocketchat_subscription
0 records load from rocketchat_subscription
Will load cache for rocketchat_settings
342 records load from rocketchat_settings
Updating process.env.MAIL_URL
Starting Email Intercepter...
Will load cache for rocketchat_permissions
0 records load from rocketchat_permissions
Will load cache for rocketchat_roles
0 records load from rocketchat_roles
LocalStore: store created at
LocalStore: store created at
Exception in callback of async function: Error: Cannot find module '/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/grpc/src/node/exte
nsion_binary/node-v48-linux-x64/grpc_node.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/grpc/src/node/src/grpc_extension.js:30:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/grpc/src/node/src/client.js:38:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/grpc/src/node/index.js:30:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/@google-cloud/common-grpc/src/service.js:26:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/@google-cloud/common-grpc/src/operation.js:36:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/@google-cloud/common-grpc/src/index.js:26:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/@google-cloud/vision/src/index.js:26:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.require (/opt/Rocket.Chat/programs/server/boot.js:221:20)
    at new GoogleVision (packages/rocketchat:google-vision/server/googlevision.js:4:21)
    at googlevision.js (packages/rocketchat:google-vision/server/googlevision.js:153:27)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at /opt/Rocket.Chat/programs/server/packages/rocketchat_google-vision.js:418:1
    at /opt/Rocket.Chat/programs/server/packages/rocketchat_google-vision.js:425:3
    at /opt/Rocket.Chat/programs/server/boot.js:339:34
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/Rocket.Chat/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/Rocket.Chat/programs/server/boot.js:158:5
    at /opt/Rocket.Chat/programs/server/boot.js:388:5
    at Function.run (/opt/Rocket.Chat/programs/server/profile.js:510:12)
    at /opt/Rocket.Chat/programs/server/boot.js:387:11
LocalStore: store created at
LocalStore: store created at
Setting default file store to GridFS

Given only difference is proxy im thinking is an issue communicating with google. Interestingly the module its trying to reference doesnt exist, the path is wrong. The path on the filesystem is node-v46-linux-x64/ not node-v48-linux-x64/

However my home machine has the same setup, same folders and that works ok.

**Comment by alexandrejuma** [comment]
I had exactly the same problem and it was due to node.js version, but since I had another node.js application running I couldn't mess with it. Installed in another CentOS server and it worked just fine after installing with a fresh and up to date node.js.

**Comment by geekgonecrazy** [comment]
Please see for appropriate methods of gaining support https://rocket.chat/docs/getting-support/#getting-support

But as said above check node.js version.  If using another node.js version isn't possible, consider using docker or something that ships node.js version along with it.
