### ISSUE TITLE
Send messages from a manager to an agent and client conversation displays error "Exception while invoking method 'sendMessage' TypeError: Cannot read property 'blocker' of undefined"

### ISSUE THREAD

**Issue by soumarcelino** [RocketChat/Rocket.Chat#8936]
### Description:

This error show when a livechat manager send a message into a running chat

![display](https://user-images.githubusercontent.com/7838414/33185237-0a96073e-d060-11e7-9ac7-5f57760bdfd6.png)

### Server Setup Information:

Version of Rocket.Chat Server: 0.60.0-develop
Operating System: Ubuntu 16.10
Deployment Method(snap/docker/tar/etc): all
Number of Running Instances: 1
DB Replicaset Oplog: ?
Node Version: v8.8.1

![image](https://user-images.githubusercontent.com/7838414/33185366-d675909a-d060-11e7-8248-4ca6db93091c.png)

### Steps to Reproduce:

1. A manager enters a live chat with an agent and client.

2. The manager sends a message but no one receives the message.

3. Errors are displayed on the console

### Expected behavior:

I hope the manager's message is seen by the agent and the client.

### Actual behavior:

The manager's message is not sent to anyone.

### Relevant logs:

I20171123-14:43:57.583(-3)? Exception while invoking method 'sendMessage' TypeError: Cannot read property 'blocker' of undefined
I20171123-14:43:57.679(-3)?   at DDPCommon.MethodInvocation.sendMessage (/home/marcelino/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:13912:60)
I20171123-14:43:57.679(-3)?   at DDPCommon.MethodInvocation.methodsMap.(anonymous function) (/home/marcelino/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:1265:26)
I20171123-14:43:57.679(-3)?   at DDPCommon.MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
I20171123-14:43:57.680(-3)?   at maybeAuditArgumentChecks (/home/marcelino/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1826:12)
I20171123-14:43:57.680(-3)?   at DDP._CurrentMethodInvocation.withValue (/home/marcelino/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:892:126)
I20171123-14:43:57.680(-3)?   at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1184:15)
I20171123-14:43:57.680(-3)?   at DDPServer._CurrentWriteFence.withValue (/home/marcelino/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:892:98)
I20171123-14:43:57.681(-3)?   at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1184:15)
I20171123-14:43:57.681(-3)?   at Promise (/home/marcelino/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:892:46)
I20171123-14:43:57.681(-3)?   at new Promise (<anonymous>:null:null)
I20171123-14:43:57.681(-3)?   at Session.method (/home/marcelino/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:865:23)
I20171123-14:43:57.681(-3)?   at /home/marcelino/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:744:85

![image](https://user-images.githubusercontent.com/7838414/33185497-dcfed880-d061-11e7-8891-c13408a9b1b7.png)

![image](https://user-images.githubusercontent.com/7838414/33185538-27212bc0-d062-11e7-9c86-ded2625dc877.png)

**Comment by soumarcelino** [comment]
This problem also occurs in version 0.59.3 in Live Chat
