### ISSUE TITLE
Clicking "or talk as anonymous" doesn't work

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#8982]
### Description:
Allow read and allow write as anonymous turned on.

You click sign in to start talking or talk as anonymous

![image](https://user-images.githubusercontent.com/51996/33401786-2235446c-d520-11e7-93d8-b131f84252d5.png)

Clicking the button does nothing.  

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3

### Steps to Reproduce:

1. Click Allow Anonymous Read / Allow Anonymous Write
2. Open in new browser
3. Click Or Talk as anonymous

### Expected behavior:

allow to enter a username to talk as

### Actual behavior:
Nothing

### Relevant logs:
Might be relevant... Doesn't increment when button is pressed but is in browser logs several times:
```
Exception in template helper: TypeError: Cannot read property '_id' of null
    at Object.condition (https://s.rocket.chat/0e9b9d3ea29454961e3d11673f9fa698b04622fd.js?meteor_js_resource=true:323:1327)
    at https://s.rocket.chat/0e9b9d3ea29454961e3d11673f9fa698b04622fd.js?meteor_js_resource=true:181:40891
    at Array.map (<anonymous>)
    at Function.A.map.A.collect (https://s.rocket.chat/0e9b9d3ea29454961e3d11673f9fa698b04622fd.js?meteor_js_resource=true:7:1106)
    at t.e [as getButtons] (https://s.rocket.chat/0e9b9d3ea29454961e3d11673f9fa698b04622fd.js?meteor_js_resource=true:181:40806)
    at Object.messageActions (https://s.rocket.chat/0e9b9d3ea29454961e3d11673f9fa698b04622fd.js?meteor_js_resource=true:243:42032)
    at https://s.rocket.chat/0e9b9d3ea29454961e3d11673f9fa698b04622fd.js?meteor_js_resource=true:79:31289
    at https://s.rocket.chat/0e9b9d3ea29454961e3d11673f9fa698b04622fd.js?meteor_js_resource=true:79:17146
    at https://s.rocket.chat/0e9b9d3ea29454961e3d11673f9fa698b04622fd.js?meteor_js_resource=true:79:31922
    at Function.e._withTemplateInstanceFunc (https://s.rocket.chat/0e9b9d3ea29454961e3d11673f9fa698b04622fd.js?meteor_js_resource=true:79:37631)
```

**Comment by ggazzo** [comment]
@geekgonecrazy I think it's working now, am I wrong? 
![udrwicg5k7](https://user-images.githubusercontent.com/5263975/40627477-9bb8fc2c-6295-11e8-9400-37a85c845902.gif)

**Comment by geekgonecrazy** [comment]
I don't recall which server this was.  So i'll go ahead and close, looks like its working to me now too

**Comment by ggazzo** [comment]
;)

**Comment by vverst** [comment]
I'm having an issue with the "Or talk as anonymous" button. Clicking it does nothing (docker image version 0.66.0). Tested in Safari, Chrome, Firefox.

I downgraded to version 0.65.2 and in this version clicking on "Or talk as anonymous" button does show the choose username dialog.

**Comment by fais3000** [comment]
I'm having the same issue on 0.66

**Comment by geekgonecrazy** [comment]
@ggazzo looks like may not have gone away?

**Comment by altsyst** [comment]
same issue with 0.66.2 docker version

**Comment by fais3000** [comment]
same issue with 0.66.3

**Comment by altsyst** [comment]
link with #11381

**Comment by digiwombat** [comment]
Running the 0.66.3 snap on Ubuntu 18.04 Server, same for me:

`Exception while invoking method 'registerUser' Error: Can't call setUserId in a method after calling unblock     at MethodInvocation.setUserId (/snap/rocketchat-server/1311/programs/server/packages/ddp-common.js:367:13)     at AccountsServer.Ap._loginUser (/snap/rocketchat-server/1311/programs/server/packages/accounts-base.js:744:20)     at MethodInvocation.registerUser (/snap/rocketchat-server/1311/programs/server/app/app.js:10709:20)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at MethodInvocation.methodsMap.(anonymous function) (/snap/rocketchat-server/1311/programs/server/packages/rocketchat_lib.js:2504:36)     at maybeAuditArgumentChecks (/snap/rocketchat-server/1311/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/snap/rocketchat-server/1311/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/snap/rocketchat-server/1311/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/snap/rocketchat-server/1311/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/snap/rocketchat-server/1311/programs/server/packages/ddp-server.js:875:23)     at /snap/rocketchat-server/1311/programs/server/packages/ddp-server.js:754:85  `

**Comment by float1** [comment]
Hi, 

Version 0.68.3

Users created but function does not work.

Thank you.

**Comment by Iratu** [comment]
I was wondering if this was ever going to get fixed or if I have to move away from this system, I use it as a chat for my streaming site and it worked perfectly fine but now Anonymous is broken the users are starting to complain and viewers and streamers are dropping because I expected this to be fixed rather soon due to it being broken due to an update...

**Comment by digiwombat** [comment]
@Iratu I use mine for the same purpose and the only solution that doesn't require actually digging down for the error is in running the older version (0.65.2 in my case).

If you're using the docker-compose version, you can just fore the version number to 0.65.2 in the .yml file.

If you've updated already, you will then also need to edit the MongoDB to look for the older database migration verion (#5542 was helpful on this front).

**Comment by Beznell** [comment]
It's understandable that the devs don't really see this as a major issue or just don't see it at all. This feature is pretty handy for some communities and I would like this feature back soon as well, maybe we could do a bounty for this if anyone is willing to it could get this feature pushed or we can wait a while.

**Comment by rasos** [comment]
This is still a bug in 0.68.5. Please fix. 

`[34mI20180829-11:04:09.058(0) Exception while invoking method 'registerUser' Error: Can't call setUserId in a method after calling unblock     at MethodInvocation.setUserId (/app/bundle/programs/server/packages/ddp-common.js:367:13)     at AccountsServer.Ap._loginUser (/app/bundle/programs/server/packages/accounts-base.js:744:20)     at MethodInvocation.registerUser (/app/bundle/programs/server/app/app.js:10726:20)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at MethodInvocation.methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:2506:36)     at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/app/bundle/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/app/bundle/programs/server/packages/ddp-server.js:875:23)     at /app/bundle/programs/server/packages/ddp-server.js:754:85  `

**Comment by ricardojrgpimentel** [comment]
Just did a fresh install with snap on Ubuntu 16.04 and i have the same problem

**Comment by srk** [comment]
Did a fresh install with snap on Ubuntu 18.04.1 (version 0.69.0), and I also have the same problem

**Comment by fais3000** [comment]
> @Iratu I use mine for the same purpose and the only solution that doesn't require actually digging down for the error is in running the older version (0.65.2 in my case).
> 
> If you're using the docker-compose version, you can just force the version number to 0.65.2 in the .yml file.
> 
> If you've updated already, you will then also need to edit the MongoDB to look for the older database migration verion. #5542 was helpful on this front.
> 
> Minor Edit: I used migration version number 121 to get it to properly migrate the database to the 0.65.2 version since I couldn't properly find what it is and I didn't want to change it to something too low.

Reporting that this feature still doesn't work in 69.2 so try @Iratu's solution.

**Comment by FaizanZahid** [comment]
i m also facing same issue, clicking on talk as anonymous does nothing and throws some JS console errors.

**Comment by benjamin-dk** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=52123760)](https://www.bountysource.com/52123760-clicking-or-talk-as-anonymous-doesn-t-work)

I just added a 200$ bounty for this.

**Comment by rasos** [comment]
See also #8535 - "Room not found" messages is shown to anonymous users, even if rooms exist. Login should be offered instead.

**Comment by wreiske** [comment]
I'm taking a look at this now @benjamin-dk

**Comment by wreiske** [comment]
![ticket-8982 mov](https://user-images.githubusercontent.com/6295044/48573678-f6724a80-e8da-11e8-8de1-4adeb52cb115.gif)
Pushing my changes here in a few. Got this fixed.

**Comment by FaizanZahid** [comment]
very nice work guys!

**Comment by mjjabarullah** [comment]
can anyone make a video for how to fix this anonymous registration. [FIX] Fixed Anonymous Registration #12633

**Comment by jonnytest1** [comment]
I just installed rocket chat via snap the other day and I also get this error ?

**Comment by mrmookie** [comment]
Same issue on version 2.4.11 snap Ubuntu 18.04. Unable to chat as anon.

**Comment by rasos** [comment]
@mrmookie is your behaviour also similar to #16756?

**Comment by geekgonecrazy** [comment]
@RocketChat/frontend not sure if any new issues tracking?  But looks like maybe this isn’t working?

**Comment by mrmookie** [comment]
After installing a new snap, it works fine, so it has something to do with one of the settings I messed with. I didn't change any permissions but I enabled a few things like translation, Google OAuth, etc.. I'll check my changes to see if I can reproduce. Thanks for opening it back up.
