### ISSUE TITLE
rocketchat container fails to connect to mogodb

### ISSUE THREAD

**Issue by georgeowell** [RocketChat/Rocket.Chat#9061]
### Description:

I was just wondering if anyone could help me with this? It's quite urgent and I'm not really sure how to troubleshoot further. 

It seems the recommended docker-compose file has been [changed quite a bit](https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/docker-compose.yml) since I started so I wondered if there is some changes I should be incorporating into my own one. I'm currently using Nginx to server the application via reverse proxy.

### Server Setup Information:

* Version of Rocket.Chat Server: b491487ecca9
* Operating System: Debian 8.10
* Deployment Method(snap/docker/tar/etc): docker-compose
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. Ran script to update the docker containers
```#!/bin/bash
# UpdateRocketchat

cd /var/www/rocket.chat # Change directory to rocketchat
docker-compose stop     # Stop all Rocketchat containers
docker-compose pull     # Pull latest Rocketchat images
docker-compose up -d    # Start all Rocketchat services
```
My docker-compose file that has been deployed for over a year is

```db:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles

rocketchat:
  image: rocketchat/rocket.chat:develop
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=<redacted>
    - Accounts_UseDNSDomainCheck=True
  links:
    - db:db
  ports:
    - 3000:3000

hubot:
  image: rocketchat/hubot-rocketchat:v0.1.4
  environment:
    - ROCKETCHAT_URL=
    - ROCKETCHAT_ROOM=GENERAL
    - ROCKETCHAT_USER=
    - ROCKETCHAT_PASSWORD=
    - BOT_NAME=
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080
```

2. mongodb is update to latest imaged
```Pulling db (mongo:latest)...
latest: Pulling from library/mongo
Digest: sha256:18b239b996e0d10f4ce2b0f64db6f410c17ad337e2cecb6210a3dcf2f732ed82
```
3. rocketchat container fails and dies

### Expected behavior:

Containers start up without a hitch.

### Actual behavior:

The rocketchat container can't connect to the mongodb container and stops.

### Relevant logs:

From the docker logs of the rocketchat container:
```
/app/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: failed to connect to server [db:27017] on first connect [MongoError: connect ECONNREFUSED 172.17.0.3:27017]
    at Pool.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:115:13)
    at Pool.emit (events.js:210:7)
    at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:316:30)
    at emitTwo (events.js:125:13)
    at Connection.emit (events.js:213:7)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:314:30)
    at emitOne (events.js:115:13)
```

Full output of docker-compose logs:
```docker-compose logs
Attaching to rocketchat_hubot_1, rocketchat_rocketchat_1, rocketchat_db_1
hubot_1       | npm WARN peerDependencies The peer dependency coffee-script@^1.12.6 included from hubot-help will no
hubot_1       | npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
hubot_1       | npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
hubot_1       | npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
hubot_1       | npm WARN deprecated coffee-script@1.6.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
hubot_1       | hubot-links@0.0.1 node_modules/hubot-links
hubot_1       | 
hubot_1       | hubot-greetings@1.0.0 node_modules/hubot-greetings
hubot_1       | └── coffee-script@1.6.3
hubot_1       | 
hubot_1       | coffee-script@1.12.7 node_modules/coffee-script
hubot_1       | 
hubot_1       | hubot-help@0.2.2 node_modules/hubot-help
hubot_1       | 
hubot_1       | hubot-seen@1.0.1 node_modules/hubot-seen
hubot_1       | ├── timeago@0.1.0
hubot_1       | └── coffee-script@1.12.7
hubot_1       | [Sun Dec 10 2017 20:41:07 GMT+0000 (UTC)] INFO Starting Rocketchat adapter version 0.1.4...
hubot_1       | [Sun Dec 10 2017 20:41:07 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: wobbot
hubot_1       | [Sun Dec 10 2017 20:41:07 GMT+0000 (UTC)] INFO Connecting To: 165.114.165.21:3000
hubot_1       | npm WARN deprecated coffee-script@1.6.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
hubot_1       | hubot-help@0.2.2 node_modules/hubot-help
hubot_1       | 
hubot_1       | hubot-links@0.0.1 node_modules/hubot-links
hubot_1       | 
hubot_1       | hubot-seen@1.0.1 node_modules/hubot-seen
hubot_1       | └── timeago@0.1.0
hubot_1       | 
hubot_1       | hubot-greetings@1.0.0 node_modules/hubot-greetings
hubot_1       | └── coffee-script@1.6.3
hubot_1       | [Sun Dec 10 2017 21:07:09 GMT+0000 (UTC)] INFO Starting Rocketchat adapter version 0.1.4...
hubot_1       | [Sun Dec 10 2017 21:07:09 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: wobbot
hubot_1       | [Sun Dec 10 2017 21:07:09 GMT+0000 (UTC)] INFO Connecting To: 165.114.165.21:3000
hubot_1       | npm WARN deprecated coffee-script@1.6.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
hubot_1       | hubot-help@0.2.2 node_modules/hubot-help
hubot_1       | 
hubot_1       | hubot-links@0.0.1 node_modules/hubot-links
hubot_1       | 
hubot_1       | hubot-seen@1.0.1 node_modules/hubot-seen
hubot_1       | └── timeago@0.1.0
hubot_1       | 
hubot_1       | hubot-greetings@1.0.0 node_modules/hubot-greetings
hubot_1       | └── coffee-script@1.6.3
hubot_1       | [Sun Dec 10 2017 21:07:41 GMT+0000 (UTC)] INFO Starting Rocketchat adapter version 0.1.4...
hubot_1       | [Sun Dec 10 2017 21:07:41 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: wobbot
hubot_1       | [Sun Dec 10 2017 21:07:41 GMT+0000 (UTC)] INFO Connecting To: 165.114.165.21:3000
rocketchat_1  | 
rocketchat_1  | /app/bundle/programs/server/node_modules/fibers/future.js:313
rocketchat_1  | 						throw(ex);
rocketchat_1  | 						^
rocketchat_1  | MongoError: failed to connect to server [db:27017] on first connect [MongoError: connect ECONNREFUSED 172.17.0.3:27017]
rocketchat_1  |     at Pool.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
rocketchat_1  |     at emitOne (events.js:115:13)
rocketchat_1  |     at Pool.emit (events.js:210:7)
rocketchat_1  |     at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
rocketchat_1  |     at Object.onceWrapper (events.js:316:30)
rocketchat_1  |     at emitTwo (events.js:125:13)
rocketchat_1  |     at Connection.emit (events.js:213:7)
rocketchat_1  |     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
rocketchat_1  |     at Object.onceWrapper (events.js:314:30)
rocketchat_1  |     at emitOne (events.js:115:13)
rocketchat_1  | 
rocketchat_1  | /app/bundle/programs/server/node_modules/fibers/future.js:313
rocketchat_1  | 						throw(ex);
rocketchat_1  | 						^
rocketchat_1  | MongoError: failed to connect to server [db:27017] on first connect [MongoError: connect ECONNREFUSED 172.17.0.3:27017]
rocketchat_1  |     at Pool.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
rocketchat_1  |     at emitOne (events.js:115:13)
rocketchat_1  |     at Pool.emit (events.js:210:7)
rocketchat_1  |     at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
rocketchat_1  |     at Object.onceWrapper (events.js:316:30)
rocketchat_1  |     at emitTwo (events.js:125:13)
rocketchat_1  |     at Connection.emit (events.js:213:7)
rocketchat_1  |     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
rocketchat_1  |     at Object.onceWrapper (events.js:314:30)
rocketchat_1  |     at emitOne (events.js:115:13)
rocketchat_1  | 
rocketchat_1  | /app/bundle/programs/server/node_modules/fibers/future.js:313
rocketchat_1  | 						throw(ex);
rocketchat_1  | 						^
db_1          | 2017-12-10T20:41:00.109+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=835f44db18ff
db_1          | 2017-12-10T20:41:00.109+0000 I CONTROL  [initandlisten] db version v3.6.0
db_1          | 2017-12-10T20:41:00.109+0000 I CONTROL  [initandlisten] git version: a57d8e71e6998a2d0afde7edc11bd23e5661c915
rocketchat_1  | MongoError: failed to connect to server [db:27017] on first connect [MongoError: connect ECONNREFUSED 172.17.0.3:27017]
rocketchat_1  |     at Pool.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
rocketchat_1  |     at emitOne (events.js:115:13)
rocketchat_1  |     at Pool.emit (events.js:210:7)
db_1          | 2017-12-10T20:41:00.109+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
rocketchat_1  |     at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
rocketchat_1  |     at Object.onceWrapper (events.js:316:30)
rocketchat_1  |     at emitTwo (events.js:125:13)
db_1          | 2017-12-10T20:41:00.109+0000 I CONTROL  [initandlisten] allocator: tcmalloc
rocketchat_1  |     at Connection.emit (events.js:213:7)
rocketchat_1  |     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
db_1          | 2017-12-10T20:41:00.109+0000 I CONTROL  [initandlisten] modules: none
rocketchat_1  |     at Object.onceWrapper (events.js:314:30)
rocketchat_1  |     at emitOne (events.js:115:13)
db_1          | 2017-12-10T20:41:00.109+0000 I CONTROL  [initandlisten] build environment:
rocketchat_1  | 
rocketchat_1  | /app/bundle/programs/server/node_modules/fibers/future.js:313
db_1          | 2017-12-10T20:41:00.109+0000 I CONTROL  [initandlisten]     distmod: debian81
rocketchat_1  | 						throw(ex);
rocketchat_1  | 						^
rocketchat_1  | MongoError: failed to connect to server [db:27017] on first connect [MongoError: connect ECONNREFUSED 172.17.0.3:27017]
db_1          | 2017-12-10T20:41:00.109+0000 I CONTROL  [initandlisten]     distarch: x86_64
rocketchat_1  |     at Pool.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
rocketchat_1  |     at emitOne (events.js:115:13)
rocketchat_1  |     at Pool.emit (events.js:210:7)
rocketchat_1  |     at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
db_1          | 2017-12-10T20:41:00.109+0000 I CONTROL  [initandlisten]     target_arch: x86_64
rocketchat_1  |     at Object.onceWrapper (events.js:316:30)
rocketchat_1  |     at emitTwo (events.js:125:13)
rocketchat_1  |     at Connection.emit (events.js:213:7)
rocketchat_1  |     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
rocketchat_1  |     at Object.onceWrapper (events.js:314:30)
rocketchat_1  |     at emitOne (events.js:115:13)
db_1          | 2017-12-10T20:41:00.109+0000 I CONTROL  [initandlisten] options: { storage: { mmapv1: { smallFiles: true } } }
db_1          | 2017-12-10T20:41:00.110+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
db_1          | 2017-12-10T20:41:00.110+0000 I STORAGE  [initandlisten] 
db_1          | 2017-12-10T20:41:00.110+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
db_1          | 2017-12-10T20:41:00.110+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
db_1          | 2017-12-10T20:41:00.110+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3490M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
db_1          | 2017-12-10T20:41:00.440+0000 I STORAGE  [initandlisten] WiredTiger message [1512938460:440634][1:0x7f5eea735a00], txn-recover: Main recovery loop: starting at 101/768
db_1          | 2017-12-10T20:41:00.555+0000 I STORAGE  [initandlisten] WiredTiger message [1512938460:555618][1:0x7f5eea735a00], txn-recover: Recovering log 101 through 102
db_1          | 2017-12-10T20:41:00.653+0000 I STORAGE  [initandlisten] WiredTiger message [1512938460:653668][1:0x7f5eea735a00], txn-recover: Recovering log 102 through 102
db_1          | 2017-12-10T20:41:01.041+0000 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
db_1          | 2017-12-10T20:41:01.041+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
db_1          | 2017-12-10T20:41:01.042+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T20:41:01.799+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
db_1          | 2017-12-10T20:41:01.801+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
db_1          | 2017-12-10T21:06:46.705+0000 I CONTROL  [signalProcessingThread] got signal 15 (Terminated), will terminate after current cmd ends
db_1          | 2017-12-10T21:06:46.705+0000 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
db_1          | 2017-12-10T21:06:46.705+0000 I REPL     [signalProcessingThread] shutdown: removing all drop-pending collections...
db_1          | 2017-12-10T21:06:46.705+0000 I REPL     [signalProcessingThread] shutdown: removing checkpointTimestamp collection...
db_1          | 2017-12-10T21:06:46.705+0000 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
db_1          | 2017-12-10T21:06:46.709+0000 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
db_1          | 2017-12-10T21:06:47.103+0000 I STORAGE  [signalProcessingThread] WiredTiger message [1512940007:103254][1:0x7f5ee8dbf700], txn-recover: Main recovery loop: starting at 102/13952
db_1          | 2017-12-10T21:06:47.210+0000 I STORAGE  [signalProcessingThread] WiredTiger message [1512940007:210283][1:0x7f5ee8dbf700], txn-recover: Recovering log 102 through 103
db_1          | 2017-12-10T21:06:47.283+0000 I STORAGE  [signalProcessingThread] WiredTiger message [1512940007:283200][1:0x7f5ee8dbf700], txn-recover: Recovering log 103 through 103
db_1          | 2017-12-10T21:06:47.518+0000 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
db_1          | 2017-12-10T21:06:47.518+0000 I CONTROL  [signalProcessingThread] now exiting
db_1          | 2017-12-10T21:06:47.519+0000 I CONTROL  [signalProcessingThread] shutting down with code:0
db_1          | 2017-12-10T21:07:03.194+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=835f44db18ff
db_1          | 2017-12-10T21:07:03.194+0000 I CONTROL  [initandlisten] db version v3.6.0
db_1          | 2017-12-10T21:07:03.194+0000 I CONTROL  [initandlisten] git version: a57d8e71e6998a2d0afde7edc11bd23e5661c915
db_1          | 2017-12-10T21:07:03.194+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
db_1          | 2017-12-10T21:07:03.194+0000 I CONTROL  [initandlisten] allocator: tcmalloc
db_1          | 2017-12-10T21:07:03.194+0000 I CONTROL  [initandlisten] modules: none
db_1          | 2017-12-10T21:07:03.194+0000 I CONTROL  [initandlisten] build environment:
db_1          | 2017-12-10T21:07:03.194+0000 I CONTROL  [initandlisten]     distmod: debian81
db_1          | 2017-12-10T21:07:03.195+0000 I CONTROL  [initandlisten]     distarch: x86_64
db_1          | 2017-12-10T21:07:03.195+0000 I CONTROL  [initandlisten]     target_arch: x86_64
db_1          | 2017-12-10T21:07:03.195+0000 I CONTROL  [initandlisten] options: { storage: { mmapv1: { smallFiles: true } } }
db_1          | 2017-12-10T21:07:03.195+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
db_1          | 2017-12-10T21:07:03.195+0000 I STORAGE  [initandlisten] 
db_1          | 2017-12-10T21:07:03.195+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
db_1          | 2017-12-10T21:07:03.195+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
db_1          | 2017-12-10T21:07:03.195+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3490M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
db_1          | 2017-12-10T21:07:03.437+0000 I STORAGE  [initandlisten] WiredTiger message [1512940023:437195][1:0x7f22c15ffa00], txn-recover: Main recovery loop: starting at 104/768
db_1          | 2017-12-10T21:07:03.544+0000 I STORAGE  [initandlisten] WiredTiger message [1512940023:544471][1:0x7f22c15ffa00], txn-recover: Recovering log 104 through 105
db_1          | 2017-12-10T21:07:03.693+0000 I STORAGE  [initandlisten] WiredTiger message [1512940023:693654][1:0x7f22c15ffa00], txn-recover: Recovering log 105 through 105
db_1          | 2017-12-10T21:07:03.939+0000 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
db_1          | 2017-12-10T21:07:03.939+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T21:07:03.939+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
db_1          | 2017-12-10T21:07:03.940+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
db_1          | 2017-12-10T21:07:03.940+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T21:07:03.940+0000 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
db_1          | 2017-12-10T21:07:03.940+0000 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
db_1          | 2017-12-10T21:07:03.940+0000 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
db_1          | 2017-12-10T21:07:03.940+0000 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
db_1          | 2017-12-10T21:07:03.940+0000 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
db_1          | 2017-12-10T21:07:03.940+0000 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
db_1          | 2017-12-10T21:07:03.940+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T21:07:03.941+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T21:07:03.941+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
db_1          | 2017-12-10T21:07:03.941+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
db_1          | 2017-12-10T21:07:03.941+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T21:07:04.493+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
db_1          | 2017-12-10T21:07:04.494+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
db_1          | 2017-12-10T21:07:18.456+0000 I CONTROL  [signalProcessingThread] got signal 15 (Terminated), will terminate after current cmd ends
db_1          | 2017-12-10T21:07:18.456+0000 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
db_1          | 2017-12-10T21:07:18.456+0000 I REPL     [signalProcessingThread] shutdown: removing all drop-pending collections...
db_1          | 2017-12-10T21:07:18.456+0000 I REPL     [signalProcessingThread] shutdown: removing checkpointTimestamp collection...
db_1          | 2017-12-10T21:07:18.456+0000 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
db_1          | 2017-12-10T21:07:18.458+0000 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
db_1          | 2017-12-10T21:07:18.776+0000 I STORAGE  [signalProcessingThread] WiredTiger message [1512940038:776676][1:0x7f22bfc89700], txn-recover: Main recovery loop: starting at 105/5504
db_1          | 2017-12-10T21:07:18.879+0000 I STORAGE  [signalProcessingThread] WiredTiger message [1512940038:879897][1:0x7f22bfc89700], txn-recover: Recovering log 105 through 106
db_1          | 2017-12-10T21:07:18.951+0000 I STORAGE  [signalProcessingThread] WiredTiger message [1512940038:951450][1:0x7f22bfc89700], txn-recover: Recovering log 106 through 106
db_1          | 2017-12-10T21:07:19.203+0000 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
db_1          | 2017-12-10T21:07:19.204+0000 I CONTROL  [signalProcessingThread] now exiting
db_1          | 2017-12-10T21:07:19.204+0000 I CONTROL  [signalProcessingThread] shutting down with code:0
db_1          | 2017-12-10T21:07:34.618+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=835f44db18ff
db_1          | 2017-12-10T21:07:34.619+0000 I CONTROL  [initandlisten] db version v3.6.0
db_1          | 2017-12-10T21:07:34.619+0000 I CONTROL  [initandlisten] git version: a57d8e71e6998a2d0afde7edc11bd23e5661c915
db_1          | 2017-12-10T21:07:34.619+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
db_1          | 2017-12-10T21:07:34.619+0000 I CONTROL  [initandlisten] allocator: tcmalloc
db_1          | 2017-12-10T21:07:34.619+0000 I CONTROL  [initandlisten] modules: none
db_1          | 2017-12-10T21:07:34.619+0000 I CONTROL  [initandlisten] build environment:
db_1          | 2017-12-10T21:07:34.619+0000 I CONTROL  [initandlisten]     distmod: debian81
db_1          | 2017-12-10T21:07:34.619+0000 I CONTROL  [initandlisten]     distarch: x86_64
db_1          | 2017-12-10T21:07:34.619+0000 I CONTROL  [initandlisten]     target_arch: x86_64
db_1          | 2017-12-10T21:07:34.619+0000 I CONTROL  [initandlisten] options: { storage: { mmapv1: { smallFiles: true } } }
db_1          | 2017-12-10T21:07:34.619+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
db_1          | 2017-12-10T21:07:34.619+0000 I STORAGE  [initandlisten] 
db_1          | 2017-12-10T21:07:34.619+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
db_1          | 2017-12-10T21:07:34.619+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
db_1          | 2017-12-10T21:07:34.620+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3490M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
db_1          | 2017-12-10T21:07:34.871+0000 I STORAGE  [initandlisten] WiredTiger message [1512940054:871337][1:0x7ff136e20a00], txn-recover: Main recovery loop: starting at 107/768
db_1          | 2017-12-10T21:07:34.992+0000 I STORAGE  [initandlisten] WiredTiger message [1512940054:992708][1:0x7ff136e20a00], txn-recover: Recovering log 107 through 108
db_1          | 2017-12-10T21:07:35.077+0000 I STORAGE  [initandlisten] WiredTiger message [1512940055:77813][1:0x7ff136e20a00], txn-recover: Recovering log 108 through 108
db_1          | 2017-12-10T21:07:35.340+0000 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
db_1          | 2017-12-10T21:07:35.340+0000 I CONTROL  [initandlisten] 
db_1          | 2017-12-10T21:07:35.913+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
db_1          | 2017-12-10T21:07:35.915+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
```

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by romaroma** [comment]
Same story. Rocketchat could not connect to the latest docker's mongo container. But let's keep the issue closed so the rocketchat's developers feel comfortable )
