### ISSUE TITLE
Problem with uploading multibyte filename (Japanese character filename)

### ISSUE THREAD

**Issue by rrepolona** [RocketChat/Rocket.Chat#9083]
Problem with uploading multibyte filename. Japanese character filename 

### Description:
Problem with uploading any multibyte filename or japanese character filename.
Using AWS s3 for storage type. For english character filename the upload is always successful, we are using this for almost a year. But recently we need to upload this japanese character filename due to a client project. this is were we notice this problem

### Server Setup Information:

* Version of Rocket.Chat Server:  0.59.4
* Operating System: Ubuntu 16.04.2 LTS
* Deployment Method: snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version:

### Steps to Reproduce:

1. Upload any Japanese character filename. Upload it to anyone or any group in channel
2. After upload, wait until you see the Internal Server Error [500]

### Expected behavior:
Upload should not have any problem, since upload of any files with english character filename is always uploading succesfully 

### Actual behavior:
It display an Internal Server Error [500] 

### Relevant logs:
Logs from Server:
[34mI20171212-16:08:24.489(8) Exception while invoking method 'ufsComplete' NoSuchKey: The specified key does not exist.   at Object.Future.wait (/snap/rocketchat-server/1195/programs/server/node_modules/fibers/future.js:449:15)   at [object Object].Meteor.methods.ufsComplete (/snap/rocketchat-server/1195/programs/server/packages/jalik_ufs.js:817:24)   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/1195/programs/server/packages/rocketchat_lib.js:1276:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/snap/rocketchat-server/1195/programs/server/packages/ddp-server.js:1857:12)   at /snap/rocketchat-server/1195/programs/server/packages/ddp-server.js:903:20   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /snap/rocketchat-server/1195/programs/server/packages/ddp-server.js:902:47   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /snap/rocketchat-server/1195/programs/server/packages/ddp-server.js:901:46   at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/1195/programs/server/packages/ddp-server.js:874:21)   at /snap/rocketchat-server/1195/programs/server/packages/ddp-server.js:753:85      - - - - -   at Request.extractError (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/services/s3.js:577:35)   at Request.callListeners (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:105:20)   at Request.emit (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:77:10)   at Request.emit (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)   at Request.transition (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)   at AcceptorStateMachine.runTo (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)   at /snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10   at Request.<anonymous> (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)   at Request.<anonymous> (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)   at Request.callListeners (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:115:18)   at Request.emit (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:77:10)   at Request.emit (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)   at Request.transition (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)   at AcceptorStateMachine.runTo (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)   at /snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10   at Request.<anonymous> (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)   at Request.<anonymous> (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)   at Request.callListeners (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:115:18)   at callNextListener (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:95:12)   at IncomingMessage.onEnd (/snap/rocketchat-server/1195/programs/server/npm/node_modules/aws-sdk/lib/event_listeners.js:269:13)   at emitNone (events.js:72:20)   at IncomingMessage.emit (events.js:166:7)   at endReadableNT (_stream_readable.js:923:12)   at nextTickCallbackWith2Args (node.js:511:9)   at process._tickDomainCallback (node.js:466:17)  

https://i.imgur.com/cX4ADBR.png

**Comment by rrepolona** [comment]
It seems the new update of Rocket Chat fix the issue
