### ISSUE TITLE
Error during migration to latest commit

### ISSUE THREAD

**Issue by Lemmmy** [RocketChat/Rocket.Chat#9097]
```
22|rocketc | Error
22|rocketc |   at Object.Migrations._findIndexByVersion (/home/lem/rocketchat/bundle/programs/server/packages/rocketchat_migrations.js:406:8)
22|rocketc |   at Object.Migrations._migrateTo (/home/lem/rocketchat/bundle/programs/server/packages/rocketchat_migrations.js:273:22)
22|rocketc |   at Object.Migrations.migrateTo (/home/lem/rocketchat/bundle/programs/server/packages/rocketchat_migrations.js:202:20)
22|rocketc |   at xrun.js (/home/lem/rocketchat/bundle/programs/server/app/app.js:5874:24)
22|rocketc |   at fileEvaluate (packages/modules-runtime.js:333:9)
22|rocketc |   at require (packages/modules-runtime.js:228:16)
22|rocketc |   at /home/lem/rocketchat/bundle/programs/server/app/app.js:11072:1
22|rocketc |   at infos.forEach.info (/home/lem/rocketchat/bundle/programs/server/boot.js:414:13)
22|rocketc |   at Array.forEach (native)
22|rocketc |   at /home/lem/rocketchat/bundle/programs/server/boot.js:413:9
22|rocketc |   at /home/lem/rocketchat/bundle/programs/server/boot.js:463:5
22|rocketc |   at Function.run (/home/lem/rocketchat/bundle/programs/server/profile.js:510:12)
22|rocketc |   at /home/lem/rocketchat/bundle/programs/server/boot.js:462:11
22|rocketc | Exception in callback of async function: Error
22|rocketc |   at Object.Migrations._findIndexByVersion (/home/lem/rocketchat/bundle/programs/server/packages/rocketchat_migrations.js:406:8)
22|rocketc |   at Object.Migrations._migrateTo (/home/lem/rocketchat/bundle/programs/server/packages/rocketchat_migrations.js:273:22)
22|rocketc |   at Object.Migrations.migrateTo (/home/lem/rocketchat/bundle/programs/server/packages/rocketchat_migrations.js:202:20)
22|rocketc |   at xrun.js (/home/lem/rocketchat/bundle/programs/server/app/app.js:5874:24)
22|rocketc |   at fileEvaluate (packages/modules-runtime.js:333:9)
22|rocketc |   at require (packages/modules-runtime.js:228:16)
22|rocketc |   at /home/lem/rocketchat/bundle/programs/server/app/app.js:11072:1
22|rocketc |   at infos.forEach.info (/home/lem/rocketchat/bundle/programs/server/boot.js:414:13)
22|rocketc |   at Array.forEach (native)
22|rocketc |   at /home/lem/rocketchat/bundle/programs/server/boot.js:413:9
22|rocketc |   at /home/lem/rocketchat/bundle/programs/server/boot.js:463:5
22|rocketc |   at Function.run (/home/lem/rocketchat/bundle/programs/server/profile.js:510:12)
22|rocketc |   at /home/lem/rocketchat/bundle/programs/server/boot.js:462:11
```

On develop commit b4c4b0b, server fails to start with a migration error. Server is in a replicaset, other nodes running fine. I am updating from 1bcba85.

**Comment by TwizzyDizzy** [comment]
Hey @Lemmmy,

while you obviously are capable of building your own RC from specific commits it would still be appropriate to adhere to the issue template ([the text you removed when opening this bug](https://github.com/RocketChat/Rocket.Chat/issues/new)) in order to help friendly community members to better help you.

Thanks ;)
Thomas

**Comment by Lemmmy** [comment]
I seem to have resolved this issue by reinstalling Meteor and doing a clean build. It seems Meteor was too outdated for the build to complete.
