### ISSUE TITLE
Support the use of IAM instance profile credentials

### ISSUE THREAD

**Issue by joshuaspence** [RocketChat/Rocket.Chat#9098]
### Description:

It seems that the S3 file storage functionality requires an access key and secret access key, although it's possible that I am doing something wrong given that the UI didn't seem to complain when I did not provide these values.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.0-rc0
* Operating System: Ubuntu 16.4
* Deployment Method(snap/docker/tar/etc): TAR
* Number of Running Instances: 3
* DB Replicaset Oplog: Enabled
* Node Version: 8

### Steps to Reproduce:

1. Configure S3 storage but don't set an access key or secret access key.
2. Attempt to upload a file to a room.

### Expected behavior:

File to be upload.

### Actual behavior:

`[err] invalid-store`

### Relevant logs:

```
Exception while invoking method 'ufsComplete' InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.   at Request.extractError (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/services/s3.js:577:35)   at Request.callListeners (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:105:20)   at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:77:10)   at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)   at Request.transition (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)   at AcceptorStateMachine.runTo (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)   at /opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10   at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)   at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)   at Request.callListeners (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:115:18)   at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:77:10)   at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)   at Request.transition (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)   at AcceptorStateMachine.runTo (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)   at /opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10   at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)   at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)   at Request.callListeners (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:115:18)   at callNextListener (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:95:12)   at IncomingMessage.onEnd (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/event_listeners.js:269:13)   at emitNone (events.js:111:20)   at IncomingMessage.emit (events.js:208:7)   at endReadableNT (_stream_readable.js:1056:12)   at _combinedTickCallback (internal/process/next_tick.js:138:11)   at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by saplla** [comment]
I just hit this issue as well. The access key and secret should be optional. Currently the [AWS uploader](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-file-upload/server/config/AmazonS3.js#L72) enforces an access key and secret even though the Node AWS SDK will look in other places for keys if they aren't present.
