### ISSUE TITLE
0.60.0-rc.0 fails to start

### ISSUE THREAD

**Issue by johnassel** [RocketChat/Rocket.Chat#9102]
When upgrading to 0.60.0-rc.0 via the pre-build binaries Rocket.Chat won't start anymore:
journald states the following: 
```
Dec 13 09:56:22 chat node[22587]: /opt/rocketchat/bundle/programs/server/boot.js:50
Dec 13 09:56:22 chat node[22587]:     const { pause } = require("./debug.js");
Dec 13 09:56:22 chat node[22587]:           ^
Dec 13 09:56:22 chat node[22587]: SyntaxError: Unexpected token {
Dec 13 09:56:22 chat node[22587]:     at exports.runInThisContext (vm.js:53:16)
Dec 13 09:56:22 chat node[22587]:     at Module._compile (module.js:373:25)
Dec 13 09:56:22 chat node[22587]:     at Object.Module._extensions..js (module.js:416:10)
Dec 13 09:56:22 chat node[22587]:     at Module.load (module.js:343:32)
Dec 13 09:56:22 chat node[22587]:     at Function.Module._load (module.js:300:12)
Dec 13 09:56:22 chat node[22587]:     at Module.require (module.js:353:17)
Dec 13 09:56:22 chat node[22587]:     at require (internal/module.js:12:17)
Dec 13 09:56:22 chat node[22587]:     at Object.<anonymous> (/opt/rocketchat/bundle/main.js:4:1)
Dec 13 09:56:22 chat node[22587]:     at Module._compile (module.js:409:26)
Dec 13 09:56:22 chat node[22587]:     at Object.Module._extensions..js (module.js:416:10)
```

I tried fixing the error by removing "{" and "}" in the stated line which is
const pause = require("./debug.js"); 
afterwards.

Then Rocket.Chat complains about node-fibers:
```
Dec 13 10:01:02 chat node[22655]: ## There is an issue with `node-fibers` ##
Dec 13 10:01:02 chat node[22655]: `/opt/rocketchat/bundle/programs/server/node_modules/fibers/bin/linux-x64-46/fibers.node` is missing.
Dec 13 10:01:02 chat node[22655]: Try running this to fix the issue: /usr/local/bin/node /opt/rocketchat/bundle/programs/server/node_modules/fibers/build
Dec 13 10:01:02 chat node[22655]: /opt/rocketchat/bundle/programs/server/node_modules/fibers/fibers.js:20
Dec 13 10:01:02 chat node[22655]:                 throw new Error('Missing binary. See message above.');
Dec 13 10:01:02 chat node[22655]:                 ^
Dec 13 10:01:02 chat node[22655]: Error: Missing binary. See message above.
Dec 13 10:01:02 chat node[22655]:     at Object.<anonymous> (/opt/rocketchat/bundle/programs/server/node_modules/fibers/fibers.js:20:9)
Dec 13 10:01:02 chat node[22655]:     at Module._compile (module.js:409:26)
Dec 13 10:01:02 chat node[22655]:     at Object.Module._extensions..js (module.js:416:10)
Dec 13 10:01:02 chat node[22655]:     at Module.load (module.js:343:32)
Dec 13 10:01:02 chat node[22655]:     at Function.Module._load (module.js:300:12)
Dec 13 10:01:02 chat node[22655]:     at Module.require (module.js:353:17)
Dec 13 10:01:02 chat node[22655]:     at require (internal/module.js:12:17)
Dec 13 10:01:02 chat node[22655]:     at Object.<anonymous> (/opt/rocketchat/bundle/programs/server/boot.js:1:75)
Dec 13 10:01:02 chat node[22655]:     at Module._compile (module.js:409:26)
Dec 13 10:01:02 chat node[22655]:     at Object.Module._extensions..js (module.js:416:10)
```

As stated in the release notes node is updated:
```
root@chat:/opt/rocketchat# node -v
v8.9.3
```

After downloading and extracting the archive I installed Rocket.Chat by using
```
root@chat:/opt/rocketchat# cd bundle/programs/server/
root@chat:/opt/rocketchat/bundle/programs/server# npm install

> fibers@2.0.0 install /opt/rocketchat/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Binary is fine; exiting
npm WARN lifecycle meteor-dev-bundle@0.0.0~install: cannot run in wd %s %s (wd=%s) meteor-dev-bundle@0.0.0 node npm-rebuild.js /opt/rocketchat/bundle/programs/server
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

added 136 packages in 4.895s

```

Any idea what might be wrong here?

**Comment by rodrigok** [comment]
run-rc.sh
```nash
curl -L -o rocket.chat.tar https://releases.rocket.chat/release-candidate/download
tar -xf rocket.chat.tar
node -v
cd bundle/programs/server/
npm install
cd ../..
MONGO_URL=mongodb://localhost/meteor_60_rc ROOT_URL=http://localhost:3000 node main.js

```

Output
```
14:42:40 Downloads ➜ sh run-rc.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   235  100   235    0     0    271      0 --:--:-- --:--:-- --:--:--   271
100  121M  100  121M    0     0  11.1M      0  0:00:10  0:00:10 --:--:-- 11.9M
v8.9.0

> fibers@2.0.0 install /Users/rodrigonascimento/Downloads/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`darwin-x64-57` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /Users/rodrigonascimento/Downloads/bundle/programs/server
> node npm-rebuild.js


> phantomjs@1.9.20 install /Users/rodrigonascimento/Downloads/bundle/programs/server/npm/node_modules/meteor/emojione_emojione/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
.......
{
  "meteor-dev-bundle": "0.0.0",
  "npm": "5.6.0",
  "ares": "1.10.1-DEV",
  "cldr": "31.0.1",
  "http_parser": "2.7.0",
  "icu": "59.1",
  "modules": "57",
  "nghttp2": "1.25.0",
  "node": "8.9.0",
  "openssl": "1.0.2l",
  "tz": "2017b",
  "unicode": "9.0",
  "uv": "1.15.0",
  "v8": "6.1.534.46",
  "zlib": "1.2.11"
}
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

added 136 packages in 25.285s
Will load cache for users
0 records load from users
Will load cache for rocketchat_room
0 records load from rocketchat_room
Will load cache for rocketchat_subscription
0 records load from rocketchat_subscription
Will load cache for rocketchat_settings
0 records load from rocketchat_settings
Updating process.env.MAIL_URL
Starting Email Intercepter...
Will load cache for rocketchat_permissions
0 records load from rocketchat_permissions
Will load cache for rocketchat_roles
0 records load from rocketchat_roles
LocalStore: store created at
LocalStore: store created at
Setting default file store to GridFS
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
Updating process.env.MAIL_URL
Exception in callback of async function: Error: Invalid PORT specified
  at Object.exports.main.argv (/Users/rodrigonascimento/Downloads/bundle/programs/server/packages/webapp.js:937:15)
  at /Users/rodrigonascimento/Downloads/bundle/programs/server/boot.js:451:27
  at /Users/rodrigonascimento/Downloads/bundle/programs/server/boot.js:465:5
  at Function.run (/Users/rodrigonascimento/Downloads/bundle/programs/server/profile.js:510:12)
  at /Users/rodrigonascimento/Downloads/bundle/programs/server/boot.js:462:11

➔ System ➔ startup
➔ +----------------------------------------------+
➔ |                SERVER RUNNING                |
➔ +----------------------------------------------+
➔ |                                              |
➔ |  Rocket.Chat Version: 0.60.0-rc.0            |
➔ |       NodeJS Version: 8.9.0 - x64            |
➔ |             Platform: darwin                 |
➔ |         Process Port: undefined              |
➔ |             Site URL: http://localhost:3000  |
➔ |     ReplicaSet OpLog: Disabled               |
➔ |          Commit Hash: da248213d9             |
➔ |        Commit Branch: HEAD                   |
➔ |                                              |
➔ +----------------------------------------------+
```

**Comment by geekgonecrazy** [comment]
Your error looks like you're using an old version of node.js 

With 0.60.0 node.js 8.x is required.  Please see release notes :)

**Comment by johnassel** [comment]
Yes, indeed it used an other node version than the installed v8.9.3.
Note: When updating node the systemd service file has to be updated as well... ;)
