### ISSUE TITLE
Deleting and recreating user results in exceptions

### ISSUE THREAD

**Issue by AmShaegar13** [RocketChat/Rocket.Chat#9226]
### Description:

Deleting a user and recreating it afterwards results in unexpected behaviour. Direct chats with this user cannot be created if they previously existed. Might be not a big deal as this should never happen productively. We encountered the errors while testing.

This has happened before updating to the current release candidate as well and should have nothing to do with recent changes.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.0-rc.5
* Operating System: Debian 8
* Deployment Method(snap/docker/tar/etc): tar with pm2
* Number of Running Instances: 12
* DB Replicaset Oplog: yes
* Node Version: v8.8.1

### Steps to Reproduce:

1. Create a direct chat between Alice and Bob
2. Delete Bob through the admin interface
3. Recreate Bob (we used CAS if that's worth noting)
4a. Search for bob (as alice)
5a. Try to create the direct chat between Alice and Bob again
4b. Search for alice (as bob)
5b. Try to create the direct chat between Alice and Bob again

### Expected behavior:

The chat is created and messages can be sent.

### Actual behavior:

`No user with username "bob/alice" was found! `

### Relevant logs:

There are several exceptions:

```
Exception while invoking method 'createDirectMessage' MongoError: E11000 duplicate key error collection: rocketchat.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "72HEwvsuRjLaWWuWB", : "user1", : "d", : null }   at Function.MongoError.create (/opt/ui/data/idev/rocket.chat-v0.60.0-rc.5/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)   at toError (/opt/ui/data/idev/rocket.chat-v0.60.0-rc.5/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)   at /opt/ui/data/idev/rocket.chat-v0.60.0-rc.5/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67   at /opt/ui/data/idev/rocket.chat-v0.60.0-rc.5/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18   at _combinedTickCallback (internal/process/next_tick.js:131:7)   at process._tickDomainCallback (internal/process/next_tick.js:218:9)  
```

(Not the same users as in the first exception)
```
Empty Room for Subscription { _id: '2DCdmKCW68vRjyxog',   rid: '72HEwvsuRjLaWWuWBukWrff2BLCnBrGuSD',   u: { _id: '72HEwvsuRjLaWWuWB', username: 'admin' },   name: 'user2',   t: 'd',   open: false,   alert: false,   unread: 0,   userMentions: 0,   groupMentions: 0,   _updatedAt: 2017-12-21T14:55:30.202Z,   meta: { revision: 0, created: 1513938424743, version: 0 },   '$loki': 3400,   _room: undefined,   _user:     { _id: '72HEwvsuRjLaWWuWB',      createdAt: 2017-10-26T11:12:17.354Z,      services: { password: [Object], email: [Object], resume: [Object] },      emails: [ [Object] ],      type: 'user',      status: 'offline',      active: true,      name: 'Administrator',      _updatedAt: 2017-12-22T10:27:21.714Z,      roles: [ 'admin' ],      lastLogin: 2017-12-22T10:27:21.714Z,      statusConnection: 'online',      utcOffset: 1,      username: 'admin',      settings: { profile: {}, preferences: [Object] },      requirePasswordChange: false,      statusDefault: 'offline',      language: 'en',      meta:        { revision: 5,         created: 1513938423742,         version: 0,         updated: 1513938441717 },      '$loki': 59 },   fname: 'User 2' } 
```

May be unrelated but this happened in our production 0.58.4 server as well:
```
Exception from sub stream-notify-room id ak9nzFSYJfgwEvqy3 TypeError: Cannot read property 't' of undefined   at [object Object].<anonymous> (/opt/ui/data/idev/rocket.chat-v0.58.4-ui2/programs/server/packages/rocketchat_lib.js:4136:12)   at Streamer.isReadAllowed (/opt/ui/data/idev/rocket.chat-v0.58.4-ui2/programs/server/packages/rocketchat_streamer.js:341:38)   at [object Object].<anonymous> (/opt/ui/data/idev/rocket.chat-v0.58.4-ui2/programs/server/packages/rocketchat_streamer.js:476:16)   at [object Object].<anonymous> (/opt/ui/data/idev/rocket.chat-v0.58.4-ui2/programs/server/packages/rocketchat_lib.js:1128:15)   at packages/matb33_collection-hooks.js:307:21   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)   at maybeAuditArgumentChecks (/opt/ui/data/idev/rocket.chat-v0.58.4-ui2/programs/server/packages/ddp-server.js:1857:12)   at /opt/ui/data/idev/rocket.chat-v0.58.4-ui2/programs/server/packages/ddp-server.js:1180:16   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at [object Object]._.extend._runHandler (/opt/ui/data/idev/rocket.chat-v0.58.4-ui2/programs/server/packages/ddp-server.js:1179:51)   at [object Object]._.extend._startSubscription (/opt/ui/data/idev/rocket.chat-v0.58.4-ui2/programs/server/packages/ddp-server.js:1027:9)   at [object Object]._.extend.protocol_handlers.sub (/opt/ui/data/idev/rocket.chat-v0.58.4-ui2/programs/server/packages/ddp-server.js:815:12)   at /opt/ui/data/idev/rocket.chat-v0.58.4-ui2/programs/server/packages/ddp-server.js:753:85
```

**Comment by TwizzyDizzy** [comment]
This seems to be a dupe of #6535, is it not?

Cheers
Thomas

**Comment by AmShaegar13** [comment]
Yup. Exactly the same.
