### ISSUE TITLE
LDAP connection Error

### ISSUE THREAD

**Issue by bettaa** [RocketChat/Rocket.Chat#9276]
### Description:

I keep getting a repeated error in my syslong stating that there has been a connection error with LDAP. I have notice no degradation in service. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.0
* Operating System: Ubuntu 16.04.3 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.8.1

### Steps to Reproduce:

Not entirely sure how to reproduce this. It seems to happen on a regular basis automatically.

### Expected behavior:

No error log to be displayed when rocketchat goes to sync LDAP

### Actual behavior:

An error is written to syslog.

### Relevant logs:

Server:
```
Dec 28 15:13:24 rocketchat rocketchat-server.rocketchat-server[1236]: rocketchat_logger rocketchat_logger.js:278 #033[31mLDAP ➔ Connection.error#033[39m connection { Error: read ECONNRESET
Dec 28 15:13:24 rocketchat rocketchat-server.rocketchat-server[1236]:   at _errnoException (util.js:1024:11)
Dec 28 15:13:24 rocketchat rocketchat-server.rocketchat-server[1236]:   at TCP.onread (net.js:618:25)
Dec 28 15:13:24 rocketchat rocketchat-server.rocketchat-server[1236]:  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Dec 28 15:13:24 rocketchat rocketchat-server.rocketchat-server[1236]: rocketchat_logger rocketchat_logger.js:278 #033[34mLDAP ➔ Search.info#033[39m Closed
Dec 28 15:13:24 rocketchat rocketchat-server.rocketchat-server[1236]: rocketchat_logger rocketchat_logger.js:278 #033[34mLDAP ➔ Connection.info#033[39m LDAP connected
Dec 28 15:16:24 rocketchat rocketchat-server.rocketchat-server[1236]: rocketchat_logger rocketchat_logger.js:278 #033[31mLDAP ➔ Connection.error#033[39m connection { Error: read ECONNRESET
Dec 28 15:16:24 rocketchat rocketchat-server.rocketchat-server[1236]:   at _errnoException (util.js:1024:11)
Dec 28 15:16:24 rocketchat rocketchat-server.rocketchat-server[1236]:   at TCP.onread (net.js:618:25)
Dec 28 15:16:24 rocketchat rocketchat-server.rocketchat-server[1236]:  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Dec 28 15:16:24 rocketchat rocketchat-server.rocketchat-server[1236]: rocketchat_logger rocketchat_logger.js:278 #033[34mLDAP ➔ Search.info#033[39m Closed
Dec 28 15:16:24 rocketchat rocketchat-server.rocketchat-server[1236]: rocketchat_logger rocketchat_logger.js:278 #033[34mLDAP ➔ Connection.info#033[39m LDAP connected

```
Browser logs:
```
[34mI20171228-15:16:24.442(-8) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET   at _errnoException (util.js:1024:11)   at TCP.onread (net.js:618:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
[34mI20171228-15:16:24.444(-8) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.info Closed 
[34mI20171228-15:16:24.548(-8) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Connection.info LDAP connected 
[34mI20171228-15:19:24.535(-8) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET   at _errnoException (util.js:1024:11)   at TCP.onread (net.js:618:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
[34mI20171228-15:19:24.536(-8) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.info Closed 
[34mI20171228-15:19:24.640(-8) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Connection.info LDAP connected 
```

**Comment by bhillcv** [comment]
Same Problem!

**Comment by Skymit** [comment]
And I also have this problem:

```
[34mI20180222-12:03:31.126(3) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:1024:11)     at TCP.onread (net.js:618:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 

[34mI20180222-12:06:31.216(3) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:1024:11)     at TCP.onread (net.js:618:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
```

**Comment by sefter25** [comment]
same problem!

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Folks! A "me too" doesn't really help anybody, please use the thumbs-up for that. :)

As for the problem: without further logs (or with a higher debug level) this is something that is not really reproducible for us. At first this looks to me like a firewall timeout as the connection (at least in the one logfile above) error appears exactly 3 minutes after the connect.

Maybe strace-ing, local firewall logs or perimeter firewall logs can yield further information.

I'm closing this. When there's new information available, I will reopen. Please also tell us whether there is an actual negative effect on the availability of the server or a specific function within it.

Cheers
Twizzy

**Comment by kungaorn** [comment]
same problem
