### ISSUE TITLE
Direct Reply emails not being parsed over IMAP

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat#9300]
### Description:

Email replies via Direct Reply to emails don't appear to be getting parsed. Emails are sent out via SMTP on the same G Suite account.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.2
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v8.8.1

### Steps to Reproduce:

1. Send email to user offline
2. Receive email
3. Reply to it (states direct reply is enabled in footer of the email)
4. Check receiving IMAP address and see emails
5. Wait
6. Emails still there and not added into RocketChat.

### Expected behavior:

RocketChat to add the emails into the chat thread.

### Actual behavior:

They don't get added.

**Comment by HammyHavoc** [comment]
Enabling debug for it seemed to immediately delete the messages from the IMAP inbox (parsed), though they weren't added to RC conversations.

**Comment by pkgodara** [comment]
Does it display blank message or nothing at all in RC conversation?

**Comment by HammyHavoc** [comment]
Nothing happens; though emails are correctly sent when users are offline. Can't see it being a configuration issue as have entered the settings many times with the same result, yet this works just fine with other software we're using IMAP and SMTP with.

**Comment by HammyHavoc** [comment]
@pkgodara Just a follow-up to this: I've now enabled Gmail's POP option instead of IMAP. Same issue. I've set the email to be automatically deleted when they are accessed via POP as per the documentation, though these messages are not added to the chat. Not sure why that is. Any ideas?

**Comment by HammyHavoc** [comment]
This is one of the errors I'm seeing: 
`[34mI20180405-07:49:04.803(0) Exception in callback of async function: TypeError: Cannot read property 'text' of undefined     at POP3Intercepter.initialProcess (/snap/rocketchat-server/1246/programs/server/packages/rocketchat_lib.js:2688:25)     at Meteor.bindEnvironment (/snap/rocketchat-server/1246/programs/server/packages/rocketchat_lib.js:2652:16)     at runWithEnvironment (packages/meteor.js:1238:24)  `

**Comment by q16marvin** [comment]
any news to this issue? i have exaktly the same problem
