### ISSUE TITLE
Version 0.60.3 broke on CentOS 7 - needs newer libstdc++

### ISSUE THREAD

**Issue by JulioFN** [RocketChat/Rocket.Chat#9354]
### Description:

Version 0.60 does not support CentOS as an operating system because of libstdc++ version requirement. Maybe RHEL isn't supported either.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): Manual Installation 
* Number of Running Instances: 1
* Node Version: 8.9.3
*Libstdc++ package: libstdc++-4.8.5-16.el7_4.1.x86_64

### Steps to Reproduce:

1. Create a machine with CentOS 7.
2. Update your CentOS 7 packages to the last version with yum update.
3. Follow the steps listed on https://rocket.chat/docs/installation/manual-installation/centos/
4. Try your installation with node main.js - It will give a lib error

### Expected behavior:

Rocket.Chat would be initialized like the previous versions

### Actual behavior:

When you try to install or upgrade Rocket.Chat to version 0.60.3 it will fail.
Trying to start the service with `node main.js` will return:

> module.js:664
>
>  return process.dlopen(module, path._makeLong(filename));
>                 ^
>
>Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/Rocket.Chat/programs/server/node_modules/fibers/bin/linux-x64-57/fibers.node)
>    at Object.Module._extensions..node (module.js:664:18)
>    at Module.load (module.js:554:32)
>    at tryModuleLoad (module.js:497:12)
>    at Function.Module._load (module.js:489:3)
>    at Module.require (module.js:579:17)
>    at require (internal/module.js:11:18)
>    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:24:38)
>    at Module._compile (module.js:635:30)
>    at Object.Module._extensions..js (module.js:646:10)
>    at Module.load (module.js:554:32)

Listing the versions from the built-in libstdc++.so.6 from CentOS 7 with `strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX` will return:

GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH

The problem is that on CentOS you can't update this library with packages not included in the default repository because it almost certainly break the system.

**Comment by JulioFN** [comment]
Refer to issue #9167
