### ISSUE TITLE
Rocket.Chat IM List API

### ISSUE THREAD

**Issue by olakunleoladimeji** [RocketChat/Rocket.Chat#9388]
### Description
When I run a request to http://ROCKETCHAT_SERVER/api/v1/im.list, the result ought to look similar to [this](https://rocket.chat/docs/developer-guides/rest-api/im/list/). However, the result I get is quite different, with some fields missing (see screenshot below)

![rocket chat-error](https://user-images.githubusercontent.com/28296275/34821709-8874b330-f6bc-11e7-8c8e-69c2fa8caa3b.png)

Also, logs from my Rocket.Chat instance show this error
![screenshot_1](https://user-images.githubusercontent.com/28296275/34822152-d525db7c-f6bd-11e7-9c76-a1b5d539e7e6.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3
* Operating System: CentOS
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version: 8.9.3

### Steps to Reproduce:
1. Enable CORS on Rocket.Chat Admin
2. Get AUTH Token and Auth User ID from /api/v1/login
2. Run curl "http://ROCKETCHAT_SERVER/api/v1/im.list"  -H "Content-Type: application/json" -H "X-Auth-Token: AUTH_TOKEN" -H "X-User-Id: USER_ID" 

### Expected behavior:

Retrieve IM List similar to https://rocket.chat/docs/developer-guides/rest-api/im/list/

### Actual behavior:

IM List JSON retrieved but each IM object only displays
`_id, _updatedAt, msgs, t, ts, lm, username`
The `usernames` array of members in the direct message is missing as well as the `ro` flag.

The IM in question has messages between the users as shown below
![screenshot_2](https://user-images.githubusercontent.com/28296275/34825312-de9949b2-f6c9-11e7-977a-70374c21a51d.png)

Rocket.Chat also throws an error saying `Exception while invoking method 'getFullUserData' TypeError: Cannot destructure property `filter` of 'undefined' or 'null'.`

### Relevant logs:

[34mI20180111-12:13:48.393(0) Exception while invoking method 'getFullUserData' TypeError: Cannot destructure property `filter` of 'undefined' or 'null'.   at DDPCommon.MethodInvocation.getFullUserData (/app/bundle/programs/server/packages/rocketchat_lib.js:14466:17)   at DDPCommon.MethodInvocation.methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:2130:26)   at DDPCommon.MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1826:12)   at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:892:126)   at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)   at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:892:98)   at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)   at Promise (/app/bundle/programs/server/packages/ddp-server.js:892:46)   at new Promise (<anonymous>:null:null)   at Session.method (/app/bundle/programs/server/packages/ddp-server.js:865:23)   at /app/bundle/programs/server/packages/ddp-server.js:744:85

**Comment by olakunleoladimeji** [comment]
Fixed the issue. To get the members list in the IM, I need to make another API call to `/im.members?roomId=ROOM_ID`

This was not documented and I only found out when looking at the JSON response to `/channel.list` warning me that usernames array had been removed.

I would suggest this be added to the Rocket.Chat docs.

Still no idea why the error is shown though
