### ISSUE TITLE
LDAPHandler - error Error: User not Found after update to 0.60.4

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat#9458]
### Description:
After update from 0.58.4 to 0.60.4 there is an error during connecting to chat. There is no way to connect. We use LDAP filters. Probably it is a problem.
```
rocketchat_logger rocketchat_logger.js:278 LDAPHandler ➔ error Error: User not Found
  at DDPCommon.MethodInvocation.<anonymous> (/app/bundle/programs/server/packages/rocketchat_ldap.js:632:10)
  at /app/bundle/programs/server/packages/accounts-base.js:828:30
  at tryLoginMethod (/app/bundle/programs/server/packages/accounts-base.js:656:14)
  at AccountsServer.Ap._runLoginHandlers (/app/bundle/programs/server/packages/accounts-base.js:827:18)
  at AccountsServer.Accounts._runLoginHandlers (/app/bundle/programs/server/packages/rocketchat_lib.js:2703:35)
  at DDPCommon.MethodInvocation.methods.login (/app/bundle/programs/server/packages/accounts-base.js:885:27)
  at DDPCommon.MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
  at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1826:12)
  at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:892:126)
  at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
  at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:892:98)
  at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
  at Promise (/app/bundle/programs/server/packages/ddp-server.js:892:46)
  at new Promise (<anonymous>:null:null)
  at Session.method (/app/bundle/programs/server/packages/ddp-server.js:865:23)
  at /app/bundle/programs/server/packages/ddp-server.js:744:85
```

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Operating System: Centos 7
* Deployment Method(snap/docker/tar/etc): docker

### Steps to Reproduce:

1. Try to log in

### Expected behavior:
I expect to log in.

### Actual behavior:
User has not been found

**Comment by TheReal1604** [comment]
@monspid can you take a look at: https://github.com/RocketChat/Rocket.Chat/issues/9389

Seems that something on the ldap filters has changed.

**Comment by monspid** [comment]
Probably it's the same issue. I will try to figure it out, when I'm in job.

**Comment by monspid** [comment]
The same issue as #9389
