### ISSUE TITLE
Unmute Owner in write protected Channel 

### ISSUE THREAD

**Issue by LucitheR** [RocketChat/Rocket.Chat#9563]
### Description:

opening a new Channel that is public but write protected leads to Owner is muted and nothing that is written afterwards is visible

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3 Merge pull request #9320 from RocketChat/release-0.60.3
* Operating System:m Linux
* Deployment Method(snap/docker/tar/etc):?
* Number of Running Instances: 1

### Steps to Reproduce:

1. create new Channel
2. set it to public
3. enable write protection

### Expected behavior:

Whenever the Owner writes something it will appear normally.

### Actual behavior:

when you write something, rocket cat informs you it is muted

### Usecase

Sometimes you have to send info to people without cluttering the #general channel, for instance like the whereabouts of devices checked out from the pool. so all know where to ask for it. You need no responses, strictly one way.

**Comment by mydoghasworms** [comment]
Had this issue as well now on v 1.0.3.

However, the user who has been made an owner only gets a message from rocket.cat saying "Error", nothing more.

Only by looking in the log did we see:

```
I20190530-09:30:52.523(2) server.js:199 System ➔ error Error sending message: { Error: [You_have_been_muted]     at canSendMessage (app/authorization/server/functions/canSendMessage.js:18:9)     at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:81:17)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:73:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1685:15)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at resolve (packages/ddp-server/livedata_server.js:1683:36)     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1682:12)     at Server.apply (packages/ddp-server/livedata_server.js:1621:26)     at Server.call (packages/ddp-server/livedata_server.js:1603:17)     at Promise.asyncApply (app/file-upload/server/methods/sendFileMessage.js:82:16)     at /snap/rocketchat-server/1377/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40   isClientSafe: true,   error: 'You_have_been_muted',   reason: undefined,   details: undefined,   message: '[You_have_been_muted]',   errorType: 'Meteor.Error' } 
```

The message from Rocket.Cat should at least tell the user they are muted.

I agree though that, by default, if you make someone an owner of a read-only (broadcast) channel, it should automatically unmute them.
