### ISSUE TITLE
Fibers issue when installing RC v0.60.4

### ISSUE THREAD

**Issue by mixrat** [RocketChat/Rocket.Chat#9574]
Trying to upgrade to v0.60.4 using Node.js 8.9.1 but having issues with fibers:
`Failed at the fibers@2.0.0 install script. This is probably not a problem with npm.`
I have overcome this before by installing fibers separately with `npm install fibers`, but no luck now.

Install steps:
````
zip /root/RocketChat-54.zip /root/Rocket.Chat
rm -rf /root/Rocket.Chat/*
tar -xvf rocket.chat-0.60.4.tgz
cd /root/Rocket.Chat/bundle/programs/server
curl https://install.meteor.com/ | sh
nvm install 8.9.1
npm install
````
Error messages...
````
/root/.node-gyp/8.9.1/include/node/v8.h:4108: error: function definition does not declare parameters
/root/.node-gyp/8.9.1/include/node/v8.h:4164: error: expected unqualified-id before ‘&’ token
/root/.node-gyp/8.9.1/include/node/v8.h:4164: error: expected ‘)’ before ‘&’ token
/root/.node-gyp/8.9.1/include/node/v8.h:4164: error: expected ‘;’ before ‘&’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ostream_insert.h:36,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:46,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/locale_classes.h:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ios_base.h:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from ../src/fibers.cc:8:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘;’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected unqualified-id before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected declaration before end of line
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory `/root/Rocket.Chat/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-042stab127.2
gyp ERR! command "/root/.nvm/versions/node/v8.9.1/bin/node" "/root/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /root/Rocket.Chat/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
````
````
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.0 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
````
`npm install fibers` produces a similar error message.

Am I using the right Node.js version?

**Comment by mixrat** [comment]
It looks like my old crusty CentOS 6 is not compatible:
[https://github.com/RocketChat/Rocket.Chat/issues/9368#issuecomment-356536649](https://github.com/RocketChat/Rocket.Chat/issues/9368#issuecomment-356536649)
