### ISSUE TITLE
LDAP password sync with Active Directory

### ISSUE THREAD

**Issue by madcry** [RocketChat/Rocket.Chat#9834]
### Description:

Hello.
I'm setup LDAP sync between AD user and rocket.chat, but password i need to add manually, after sync.
Password in LDAP saved in field "description". How can i sync password automatically when sycn with AD?

### Server Setup Information:

* Version of Rocket.Chat Server:  0.61.0
* Operating System:  1 Gb
* Deployment Method(snap/docker/tar/etc):  snap
* Number of Running Instances: 1
* DB Replicaset Oplog: lates
* Node Version: v8.9.3
* mongoDB Version: lates

### Steps to Reproduce:

1. trying sync with AD LDAP from host:3000/admin/ldap

### Expected behavior:

Need password auto sync from AD to Rocket.Chat. Password saved in "description" field of AD

### Actual behavior:

Password didn't sync, i'm need to add it manually in user profile

### Relevant logs:
```
[34mI20180222-16:05:04.920(3) [34mMeteor ➔ method ldap_sync_now -> userId: ACnHicbs9yNybWGSc , arguments:  {} 
[34mI20180222-16:05:04.923(3) [34mLDAP ➔ Connection.info Init setup 
[34mI20180222-16:05:04.924(3) [34mLDAP ➔ Connection.info Connecting ldap://corp.work.org:389 
[34mI20180222-16:05:04.926(3) [34mLDAP ➔ Connection.debug connectionOptions { url: 'ldap://corp.imgrand.ru:389',   timeout: 60000,   connectTimeout: 5000,   idleTimeout: 5000,   reconnect: true } 
[34mI20180222-16:05:05.030(3) [34mLDAP ➔ Connection.info LDAP connected 
[34mI20180222-16:05:05.032(3) [34mLDAP ➔ Bind.info Binding UserDN CN=admin,CN=Users,DC=corp,DC=work,DC=org 
[34mI20180222-16:05:05.037(3) [34mLDAP ➔ Search.info Searching user * 
[34mI20180222-16:05:05.039(3) [34mLDAP ➔ Search.debug searchOptions { filter: '(&(&(memberof=CN=rocket-chat-group,OU=SYSTEM,OU=Accounts,DC=corp,DC=work,DC=org)!(userAccountControl:1.2.840.113556.1.4.803:=2))(sAMAccountName=*))',   scope: 'sub',   sizeLimit: 1000,   paged: { pageSize: 250, pagePause: true } } 
[34mI20180222-16:05:05.041(3) [34mLDAP ➔ Search.debug BaseDN OU=Accounts,DC=corp,DC=work,DC=org 
[34mI20180222-16:05:05.052(3) [34mLDAP ➔ Search.info Final Page 
[34mI20180222-16:05:05.054(3) [34mLDAPSync ➔ debug userQuery { 'services.ldap.id': 'a90088bf99a53947a0f589a13c4a9b6a' } 
[34mI20180222-16:05:05.056(3) [34mLDAP ➔ Search.info Final Page 
[34mI20180222-16:05:05.058(3) [34mLDAPSync ➔ debug userQuery { 'services.ldap.id': 'a90088bf99a53947a0f589a13c4a9b6a' } 
[34mI20180222-16:05:05.062(3) [34mLDAPSync ➔ debug userQuery merge { username: 'user_name' } 
[34mI20180222-16:05:05.065(3) [34mLDAPSync ➔ debug userQuery merge { username: 'user_name' } 
[34mI20180222-16:05:05.069(3) [34mLDAPSync ➔ debug user.name changed to: Name 
[34mI20180222-16:05:05.071(3) [34mLDAPSync ➔ debug New user data { username: 'user_name', email: 'mail@imgrand.ru' } 
[34mI20180222-16:05:05.075(3) [34mLDAPSync ➔ debug user.name changed to: Захарова Анастасия 
[34mI20180222-16:05:05.077(3) [34mLDAPSync ➔ debug New user data { username: 'user_name', email: 'mail@imgrand.ru' } 
[34mI20180222-16:05:05.096(3) rocketchat_logger rocketchat_logger.js:278 [31mLDAPSync ➔ error Error creating user { Error: Username already exists. [403]     at AccountsServer.Ap.insertUserDoc (/snap/rocketchat-server/1215/programs/server/packages/accounts-base.js:1735:52)     at AccountsServer.<anonymous> (/snap/rocketchat-server/1215/programs/server/app/app.js:194:28)     at executeBound (/snap/rocketchat-server/1215/programs/server/npm/node_modules/underscore/underscore.js:701:67)     at AccountsServer.bound [as insertUserDoc] (/snap/rocketchat-server/1215/programs/server/npm/node_modules/underscore/underscore.js:733:14)     at createUser (/snap/rocketchat-server/1215/programs/server/packages/accounts-password.js:1192:25)     at AccountsServer.Accounts.createUser (/snap/rocketchat-server/1215/programs/server/packages/accounts-password.js:1252:10)     at addLdapUser (/snap/rocketchat-server/1215/programs/server/packages/rocketchat_ldap.js:1273:29)     at ldapUsers.forEach.ldapUser (/snap/rocketchat-server/1215/programs/server/packages/rocketchat_ldap.js:1335:5)     at Array.forEach (<anonymous>:null:null)     at ldap.searchUsersSync.Meteor.bindEnvironment (/snap/rocketchat-server/1215/programs/server/packages/rocketchat_ldap.js:1305:13)     at runWithEnvironment (packages/meteor.js:1240:24)    isClientSafe: true,   error: 403,   reason: 'Username already exists.',   details: undefined,   message: 'Username already exists. [403]',   errorType: 'Meteor.Error' } 
[34mI20180222-16:05:05.097(3) [34mLDAPSync ➔ info Import finished. Users imported: 2 
[34mI20180222-16:05:05.105(3) [34mMeteor ➔ method joinDefaultChannels -> userId: gqETm45kpNPdGLBiv , arguments:  { '0': undefined } 
[34mI20180222-16:05:05.128(3) [34mIntegrations ➔ Outgoing WebHook.debug Execute Trigger: userCreated 
[34mI20180222-16:05:05.134(3) [34mIntegrations ➔ Outgoing WebHook.debug Got the event arguments for the event: userCreated { event: 'userCreated',   user:     { _id: 'gqETm45kpNPdGLBiv',      createdAt: 2018-02-22T13:05:05.084Z,      services: {},      username: 'user_name',      emails: [ [Object] ],      type: 'user',      status: 'offline',      active: true,      _updatedAt: 2018-02-22T13:05:05.085Z } } 
[34mI20180222-16:05:05.135(3) [34mIntegrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: __any 
[34mI20180222-16:05:05.136(3) [34mIntegrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event. 
[34mI20180222-16:05:05.149(3) [34mLDAPSync ➔ info Syncing user data 
[34mI20180222-16:05:05.150(3) [34mLDAPSync ➔ debug user { email: 'mail@imgrand.ru', _id: 'gqETm45kpNPdGLBiv' } 
[34mI20180222-16:05:05.151(3) [34mLDAPSync ➔ debug ldapUser undefined 
[34mI20180222-16:05:05.152(3) [34mLDAPSync ➔ debug user.name changed to: User Name 
[34mI20180222-16:05:05.155(3) [34mLDAPSync ➔ debug setting {   "name": "NAME",   "emails": [     {       "address": "mail@imgrand.ru",       "verified": true     }   ],   "services.ldap.id": "a90088bf99a53947a0f589a13c4a9b6a",   "services.ldap.idAttribute": "objectGUID",   "ldap": true } 
[34mI20180222-16:05:05.171(3) [34mLDAPSync ➔ info Syncing user avatar 
[34mI20180222-16:05:05.186(3) [34mMeteor ➔ method ufsComplete -> userId: gqETm45kpNPdGLBiv , arguments:  { '0': 'snaF6zrTuAMvpwXuS',   '1': 'GridFS:Avatars',   '2': '6a3B0B1AAB' } 
[34mI20180222-16:05:05.214(3) [34mLDAPSync ➔ info Import finished. Users imported: 2 
[34mI20180222-16:05:10.098(3) [34mLDAP ➔ Search.info Idle 
[34mI20180222-16:05:10.100(3) [34mLDAP ➔ Connection.info Disconecting 
[34mI20180222-16:05:10.103(3) [34mLDAP ➔ Search.info Closed 
```

**Comment by fcoppolani** [comment]
Hi,
Why do you do that ? You don't want the same passwords for your users between ldap and rocket.chat, it would be so much easier for you and them that way ? Anyway I believe the only possibility is to write a script and use the REST api of rocket.chat .

**Comment by fcoppolani** [comment]
Password will not be stored in Rocket.Chat (as far as I know), each time a user login, rocket.Chat will send credentials to ldap to check them.

**Comment by madcry** [comment]
Hmm, but when i try to log in i have error about login or password wrong, but in account section this account appear.

**Comment by JSzaszvari** [comment]
In the LDAP settings do you have "Merge Existing Users" set to True or False? 

If it's false , try setting it to true and forcing another sync with the directory

**Comment by JSzaszvari** [comment]
Actually.sorry just saw your screenshot. 

Can you try removing the User Filter and see if that helps ?

**Comment by madcry** [comment]
http://joxi.ru/KAxLR6lH4lNZgA
already set to true

**Comment by madcry** [comment]
logs, when try to login
http://joxi.ru/82QK3G9t1ony6r

**Comment by madcry** [comment]
When i'm delete,after sync some of accounts add to Users in R.C, but not all. And nothing change error stay same, user not found or incorrect password

**Comment by fcoppolani** [comment]
The error concerns CROWD, did you activate it (ATlassion crowd) ? If so you should deactivate it.

**Comment by madcry** [comment]
Yes this option is enabled, now disable and trying again

**Comment by madcry** [comment]
Now connection is ok, and RC trying to connect over LDAP, but again with error.

http://joxi.ru/krDMenBS0YaxJm

**Comment by madcry** [comment]
Guys really big thanks) But in future i'm wanna to use attlasian for JIRA, this will be problematic?

**Comment by fcoppolani** [comment]
About the error: it cannot find the user pechen_e, as said above remove your filter to test, you might need to check and tune the parameters, they can change for each different AD (I can't help you more on this).
About having CROWD and LDAP, I believe you cannot have both at the same time, its CROWD or LDAP. Godd luck

**Comment by madcry** [comment]
I'm typing wrong password, all work now like clock... Atlassian crowd didn't get to connect with AD server

**Comment by madcry** [comment]
Thanks!

**Comment by JSzaszvari** [comment]
@rocket-cat close 

Glad you got it working. Thanks so much!

**Comment by OtavioCapila** [comment]
I'm with the same problem,Atlassian crowd is set to false,but still not syncing passwords when i create a new user in LDAP, so i have to set manually a new password to the user in Rocket.Chat.

**Comment by maxdwit** [comment]
Same her.
User changed his AD Password.
Rocket.Chat still wants the old LDAP Password.
Change was two days ago.

**Comment by oCa-flash** [comment]
Since then, nothing has been decided? Similarly disabled Atlassian crowd but still does not synchronize passwords.
