### ISSUE TITLE
[BUG] Can't leave a channel/room - getting Error 400

### ISSUE THREAD

**Issue by der-eismann** [RocketChat/Rocket.Chat#9869]
### Description:

Whenever I try to leave a room/channel a small red overlay is popping up in the upper red corner saying "400". So I need to remove myself from the channel. Here is the log output:
```
[34mI20180223-17:01:11.553(1) Exception while invoking method 'leaveRoom' Error: Match error: Expected string, got null     
at exports.check (packages/check.js:55:15)     
at DDPCommon.MethodInvocation.leaveRoom (/snap/rocketchat-server/1215/programs/server/packages/rocketchat_lib.js:15008:3)     
at DDPCommon.MethodInvocation.methodsMap.(anonymous function) (/snap/rocketchat-server/1215/programs/server/packages/rocketchat_lib.js:2134:26)    
at DDPCommon.MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     
at maybeAuditArgumentChecks (/snap/rocketchat-server/1215/programs/server/packages/ddp-server.js:1826:12)     
at DDP._CurrentMethodInvocation.withValue (/snap/rocketchat-server/1215/programs/server/packages/ddp-server.js:892:126)     
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)     
at DDPServer._CurrentWriteFence.withValue (/snap/rocketchat-server/1215/programs/server/packages/ddp-server.js:892:98)     
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)     
at Promise (/snap/rocketchat-server/1215/programs/server/packages/ddp-server.js:892:46)     
at new Promise (<anonymous>:null:null)     
at Session.method (/snap/rocketchat-server/1215/programs/server/packages/ddp-server.js:865:23)     
at /snap/rocketchat-server/1215/programs/server/packages/ddp-server.js:744:85  
```

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1

### Steps to Reproduce:

1. Open room info
2. Click leave
3. Confirm

### Expected behavior:

Leaving the room.

### Actual behavior:

Getting error 400 and still be inside the room.

**Comment by karlprieb** [comment]
@der-eismann can you try that on the 0.62 release? I can't reproduce that here.

**Comment by der-eismann** [comment]
I can try when you release 0.62 as a snap 😄 When I look back to the 0.61 release it should come in the next few days, right?
We are still testing features before planning a bigger deployment.

**Comment by rudineirk** [comment]
I had this problem on version 0.61, yesterday I updated to 0.62 and looks like the problem is fixed

fyi: I'm running the application using Docker

**Comment by karlprieb** [comment]
Thank you for your feedback @rudineirk.

@der-eismann I'll talk with our snap guy :) and see when this will be released, so you can try that too and we can close this issue or do the fix.

**Comment by der-eismann** [comment]
Perfect! So while I wait another funny detail:
I'm unable to leave a room via the room info page:
![unbenannt](https://user-images.githubusercontent.com/10406217/36855430-b33bb37e-1d73-11e8-948d-966953e3b7ca.PNG)
But it's no problem to leave it via the room list on the left:
![unbenannt](https://user-images.githubusercontent.com/10406217/36855452-c7e686c8-1d73-11e8-9608-38188134ac94.PNG)
Let's see if the new version helps.

**Comment by karlprieb** [comment]
Ok, thank you for bringing more information!

**Comment by der-eismann** [comment]
@karlprieb were you able to talk to your snap guy? Maybe we should switch to Docker since the last update was released a month ago.

**Comment by karlprieb** [comment]
@geekgonecrazy do you know when the new snap package will be available?

**Comment by der-eismann** [comment]
Okay, the snap was updated yesterday evening. The problem is fixed, I can leave every room however I want. Thanks! :)

**Comment by karlprieb** [comment]
Thank you for the feedback @der-eismann

**Comment by geekgonecrazy** [comment]
#9992 tracks permanent resolution of the issue that kept the update back.  But has been patched in place
