### ISSUE TITLE
Cannot start RocketChat client on debian: failed to map segment from shared object

### ISSUE THREAD

**Issue by er0k** [RocketChat/Rocket.Chat#9918]
### Description:

```
$ uname -a
Linux eth 4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux
```
I just downloaded and installed 2.10.5, but I get this error when trying to run rocketchat:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.gJ5bk6: failed to map segment from shared object
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/opt/Rocket.Chat+/resources/app.asar/node_modules/@paulcbetts/system-idle-time/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/Rocket.Chat+/resources/app.asar/node_modules/@paulcbetts/system-idle-time/addon.js:1:192)
```
### Steps to Reproduce:

1. run `rocketchat`

### Expected behavior:

rocketchat client should start

### Actual behavior:

rocketchat client does not start

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

It seems like you're describing an issue in Rocket.Chat.Electron. But you opened this issue in the server application repo. Please head over to https://github.com/RocketChat/Rocket.Chat.Electron and report the issue there while adhering to the [issue template](https://github.com/RocketChat/Rocket.Chat.Electron/blob/develop/.github/ISSUE_TEMPLATE.md).

Cheers & Thanks
Thomas

**Comment by er0k** [comment]
Oops, sorry about that.
