### ISSUE TITLE
0.62.0 LDAP - Exception while invoking method 'deleteUser'

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#9957]
### Description:

Trying to delete a user from Rocket it throws this error

Exception while invoking method 'deleteUser'

MongoError: '$pull' is empty. You must specify a field like so: {$mod: {<field>: ...}}
    at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62
* Operating System: CentOS
* Deployment Method(snap/docker/tar/etc): docker 
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version:  node -v v8.9.4 but Admin panel says 8.93 ?

* mongoDB Version: 2.6.9

### Steps to Reproduce:

1. LDAP sync users
2. Find one user is a group as I had the filter wrong
3. Delete user

### Expected behavior:

Sync users
Delete user
User is deleted (at least from Rocket - possibly need to disable LDAP sync first ?)

### Actual behavior:

Sync users
Delete user
Server errors and user not deleted from Rocket

**Comment by reetp** [comment]
Think this seems to have been fixed with 0.62.1 #9989
